### ISSUE TITLE
[Request] 请加上以下功能：用户自定义哪个模型可以上传文件

### ISSUE THREAD

**Issue by Payne-Wang** [lobehub/lobe-chat#1000]
### 🥰 需求描述

目前lobe只有gpt-4-vision-preview支持文件上传，而且仅支持图片。但是目前很多将plus的功能转发，比如pandora，这些项目产生的api都可以支持上传文件分析。因此希望lobe可以支持用户自定义模型上传文件。

在之前的issue中有人提到过将该行注释可以实现文件上传(不仅限图片)：https://github.com/lobehub/lobe-chat/blob/main/src/features/ChatInput/ActionBar/FileUpload.tsx#L25

实测之后确实可以

lobe中的对话：来自pandora的转发，如果传图片的话仍然可以展示图片，传非图片，比如此处的pdf文件，则显示空
![LobeChat_随便聊聊_2024-01-10](https://github.com/lobehub/lobe-chat/assets/44337721/a90e8c55-d5bc-439c-9ebc-0e4f04d3d28f)

下图是对应的GPT PLUS账号中创建的对话，可以看到这个上传过程与直接在网页端上传没有什么差别，只不过接口可能对文件大小有限制
![image](https://github.com/lobehub/lobe-chat/assets/44337721/8574e0e2-b71b-47e9-ae90-55f5320a2ad3)

感谢大佬！

### 🧐 解决方案

暂无

**Comment by kpchen** [comment]
why it was closed？ even not resolved yet...

**Comment by jsjcjsjc** [comment]
> Because i have add an hidden model named gpt-4-all to support this

could you please tell me how to use this hidden model named gpt-4-all ?
thanks
