### ISSUE TITLE
[Bug] azure api下无法使用dalle

### ISSUE THREAD

**Issue by jingyuan2017** [lobehub/lobe-chat#1001]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

 azure api下无法使用dalle，可以调用插件，转换prompt，但是不能输出图片

**Comment by arvinxx** [comment]
看看这个有没有 https://github.com/lobehub/lobe-chat/discussions/1004

**Comment by arvinxx** [comment]
目前看下来之前写的 Azure 兼容版 Dalle 3生成模式是有问题的。后续再支持吧
