### ISSUE TITLE
[Request] 能否输出对话API给别的前端界面集成？

### ISSUE THREAD

**Issue by jingyuan2017** [lobehub/lobe-chat#1002]
### 🥰 需求描述

能否把配置好的agent，通过API对外输出，类似openai的API？

这样就可以集成在自定义的前端界面里，请问有开发计划吗

### 🧐 解决方案

能否把配置好的agent，通过API对外输出，类似openai的API？

这样就可以集成在自定义的前端界面里，请问有开发计划吗

**Comment by Sen-CaPoo** [comment]
> ### 🥰 需求描述
> 能否把配置好的agent，通过API对外输出，类似openai的API？
> 
> 这样就可以集成在自定义的前端界面里，请问有开发计划吗
> 
> ### 🧐 解决方案
> 能否把配置好的agent，通过API对外输出，类似openai的API？
> 
> 这样就可以集成在自定义的前端界面里，请问有开发计划吗
> 
> ### 📝 补充信息
> _No response_

好奇問一下，既然不使用 Lobe 的前端，那為什麼不乾脆直接串接呼叫 OpenAI 的 API 就好？

**Comment by jingyuan2017** [comment]
> > ### 🥰 需求描述
> > 能否把配置好的agent，通过API对外输出，类似openai的API？
> > 这样就可以集成在自定义的前端界面里，请问有开发计划吗
> > ### 🧐 解决方案
> > 能否把配置好的agent，通过API对外输出，类似openai的API？
> > 这样就可以集成在自定义的前端界面里，请问有开发计划吗
> > ### 📝 补充信息
> > _No response_
> 
> 好奇問一下，既然不使用 Lobe 的前端，那為什麼不乾脆直接串接呼叫 OpenAI 的 API 就好？

你说的有道理啊。。。

不过我好像是需要一个可以方便管理插件和测试对话的工具，都配置好了在去前端集成。

前端可能是语音的，就没这么复杂的界面了。

**Comment by arvinxx** [comment]
有计划： https://github.com/lobehub/lobe-chat/discussions/924

**Comment by jingyuan2017** [comment]
> 有计划： #924 ，你可以在这个帖子下补充下你的诉求。我们做的时候一并考虑

请问对外输出API的功能，近期有计划吗，预计什么时候做？

**Comment by arvinxx** [comment]
> > 有计划： #924 ，你可以在这个帖子下补充下你的诉求。我们做的时候一并考虑
> 
> 
> 
> 请问对外输出API的功能，近期有计划吗，预计什么时候做？

估计要在我们做完 saas 版以后了。 估计可能要3月份左右吧

**Comment by arvinxx** [comment]
按照目前的发展，应该不会再计划考虑开放内部 chat api 给外部集成了
