### ISSUE TITLE
[Bug] “历史消息长度压缩阈值”好像没有生效？

### ISSUE THREAD

**Issue by jingyuan2017** [lobehub/lobe-chat#1006]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

我用默认助手，设置了“是否开启历史消息长度压缩阈值”，但是从chat api的请求看，没有对内容进行压缩。

阈值设置为4，但是对话已经有10条以上，没看到压缩的效果。

请问如何确定压缩已经生效？

**Comment by arvinxx** [comment]
对…这个还没做 https://github.com/lobehub/lobe-chat/issues/34

**Comment by jingyuan2017** [comment]
> 对…这个还没做 #34
请问这个在近期的计划内吗？

**Comment by arvinxx** [comment]
在

**Comment by hqzh** [comment]
太需要这个了

**Comment by CHENXCHEN** [comment]
这个功能有任何进展吗？现在实现了吗？
