### ISSUE TITLE
本地运行插件报错

### ISSUE THREAD

**Issue by lihui123456** [lobehub/lobe-chat#1008]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

请求 URL:
http://xxxxxxx:3400/api/gateway
请求方法:
OPTIONS
状态代码:
500 Internal Server Error
   如何解决

### 🚦 期望结果

docker运行lobe- chat 镜像 本地运行[lobe-chat-plugin-template](https://github.com/lobehub/chat-plugin-template)插件，然后lobe-chat 添加插件跨域报错
![Uploading 企业微信截图_17049387921085.png…]()

**Comment by lihui123456** [comment]
- error Error [TypeError]: req.headers.get is not a function
    at originHeadersFromReq (F:\openAI\lobe\chat-plugin-template\node_modules\@lobehub\chat-plugins-gateway\dist\cors.js:52:33)
    at cors (F:\openAI\lobe\chat-plugin-template\node_modules\@lobehub\chat-plugins-gateway\dist\cors.js:74:31)
    at F:\openAI\lobe\chat-plugin-template\node_modules\@lobehub\chat-plugins-gateway\dist\edge.js:62:49
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: undefined
}  报错信息

**Comment by arvinxx** [comment]
有截图吗？

**Comment by lihui123456** [comment]
@arvinxx 
![image](https://github.com/lobehub/lobe-chat/assets/14088043/738ac7d6-dc4b-489e-a31b-b0242fd14fb8)
![企业微信截图_17049391731105](https://github.com/lobehub/lobe-chat/assets/14088043/c771387e-0a3b-4494-a6ea-2c1d11d97665)

**Comment by lihui123456** [comment]
@lobehubbot 截图如上图所示

**Comment by arvinxx** [comment]
本地运行[lobe-chat-plugin-template](https://github.com/lobehub/chat-plugin-template)插件的花，请求不应该会打到这个域名去的，你是不是添加的插件 manifest 不对？本地开发应该 添加 `manifest-dev.json` ?

**Comment by lihui123456** [comment]
@arvinxx 
![image](https://github.com/lobehub/lobe-chat/assets/14088043/a7620763-e9b3-437b-9d42-10675cc55f27)
![企业微信截图_17049394763633](https://github.com/lobehub/lobe-chat/assets/14088043/201fbc1b-fbfc-405e-b7ed-4c4c668b85e1)
这是我ti添加插件和mainfest，麻烦帮忙看看吧，困扰好久了，非常感谢

**Comment by arvinxx** [comment]
<img width="965" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/e44c77e0-1f7f-41c3-b966-9b9d3742fa2b">
这一块 revert 一下吧，不需要改哈

**Comment by lihui123456** [comment]
@arvinxx 现在改成这样了
![企业微信截图_17049409512474](https://github.com/lobehub/lobe-chat/assets/14088043/c97c47f0-6328-4a6a-9716-106d78cc09de)
![image](https://github.com/lobehub/lobe-chat/assets/14088043/6eef28e0-7070-4bbf-84fc-bee20681397e)
![image](https://github.com/lobehub/lobe-chat/assets/14088043/027d4d44-f4c3-4934-92a8-4d6c0993ce16)
全改成localhost了不知道为啥还是访问的是ip
，大神有空帮忙看看哈

**Comment by lihui123456** [comment]
@arvinxx 现在都改成localhost了 还是报错
![image](https://github.com/lobehub/lobe-chat/assets/14088043/b0a97658-209d-48c8-bf33-7d8b70e327ee)
不知道什么原因

**Comment by arvinxx** [comment]
@lihui123456 排查下来是我们的模板的问题，抱歉耽搁你时间了🙇‍♂️

请在 gateway.ts 的代码替换为

```ts
import { createGatewayOnEdgeRuntime } from '@lobehub/chat-plugins-gateway';

export const config = {
  runtime: 'edge',
};

export default async (req: Request) => {
  if (process.env.NODE_ENV === 'development') {
    return createGatewayOnEdgeRuntime()(req);
  }

  return new Response('gateway');
};
```

应该是之前更新的时候忘记修改这里的代码了。我去修正一下模板的

**Comment by lihui123456** [comment]
@arvinxx 我这边可以了，谢谢您

**Comment by arvinxx** [comment]
已修复： https://github.com/lobehub/chat-plugin-template/pull/24

**Comment by arvinxx** [comment]
@lihui123456 更新一下，上述代码在 next build 时会报错。要改成动态导入的方式：

```ts
export const config = {
  runtime: 'edge',
};

export default async (req: Request) => {
  if (process.env.NODE_ENV === 'development') {
    const { createGatewayOnEdgeRuntime } = await import('@lobehub/chat-plugins-gateway');

    return createGatewayOnEdgeRuntime()(req);
  }

  return new Response('gateway');
};
```

**Comment by lihui123456** [comment]
@arvinxx 好的，非常感谢
