### ISSUE TITLE
[Bug] askyoupdf插件不能用了

### ISSUE THREAD

**Issue by zdaoxb** [lobehub/lobe-chat#1009]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

如题 askyoupdf插件不能用了：很抱歉刚才的回复是英文的。我想通知您，我们有一个新版本的AI工具，名为AskYourPDF研究助手，它提供了更多新的和更好的功能。这些功能包括更准确的回答，能够将您的PDF文档组织成知识库并一次性与它们交流，能够使用有效的引用撰写论文和文章，以及能够自动为任何AI撰写的文本查找来源。此外，它还可以提供最新论文的详细摘要，并且能够比较多个PDF文档。

您可以在这里查看AskYourPDF研究助手：[AskYourPDF研究助手](https://chat.openai.com/g/g-UfFxTDMxq-askyourpdf-research-assistant)

如果您有付费计划，您可以享受您计划中的所有好处以及新功能，而无需额外费用。请注意，旧版插件即将淘汰。

如果您希望继续使用旧插件，您可以在这里找到安装和使用它的说明：[如何安装和使用AskYourPDF插件](https://docs.askyourpdf.com/askyourpdf-docs/how-to-install-and-use-askyourpdf-plugin-for-chatgpt)

不过，如果您想继续使用我当前可用的工具从您提到的文档（640a04a2-ca1d-431c-aae3-d729ad399e7c）中提取信息，请告诉我，我可以协助您进行操作。

**Comment by TonyBlur** [comment]
我使用过程中也是提示有新版本可用，但是我的插件仍然还是能用的

**Comment by arvinxx** [comment]
@akagwushiojiz 这个是 API ，不是插件。你要看的应该是第二个
