### ISSUE TITLE
左上角图标本地化

### ISSUE THREAD

**Issue by FrankWhh** [lobehub/lobe-chat#1015]
### Discussed in https://github.com/lobehub/lobe-chat/discussions/1014

<div type='discussions-op-text'>

<sup>Originally posted by **FrankWhh** January 11, 2024</sup>
服务器没网，dev下很慢，但是build后启动无法正常显示左上角的图标，我修改对应的链接：

> https://github.com/lobehub/lobe-chat/blob/0679c9b964ce5cb1a2246940fcc6f19fda771790/src/const/meta.ts#L9

无效。请问应该如何修改？</div>

**Comment by arvinxx** [comment]
可以考虑替换为本地图片，欢迎 PR
