### ISSUE TITLE
[Feat/Plugin] 自定义插件索引源

### ISSUE THREAD

**Issue by arvinxx** [lobehub/lobe-chat#102]
允许用户可自行定义插件市场索引源

**Comment by tonyyls** [comment]
请问这是支持了吗？文档在哪个位置？

**Comment by mushan0x0** [comment]
<img width="912" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/49131923-8ed1-4cd1-b202-63515baef486"> 插件列表的这个地方
@tonyyls
