### ISSUE TITLE
[Request] 如何支持类似官方开启代码解释器的功能

### ISSUE THREAD

**Issue by zdaoxb** [lobehub/lobe-chat#1021]
### 🥰 需求描述

例如让lobechat支持 数学公式的显示 
正准备开始教授关于1.3 高级积分技巧的内容，让我们一起跳进这个数学的深渊吧！🦌

Topic: 1.3 高级积分技巧

Main Lesson
积分是数学分析中的一个核心概念，它允许我们从函数的导数（即微分）中恢复原函数。高级积分技巧，特别是在高等数学中，是解决复杂问题的关键。以下是一些常用的高级积分方法：

部分分式积分
当我们遇到有理函数（即多项式除以多项式）时，部分分式分解是一个非常有用的技巧。这个方法涉及将复杂的有理函数分解成简单的部分，这些简单的部分可以单独积分。📘

比如说，有一个有理函数 (\frac{1}{(x+2)(x+3)})，我们可以将它分解为 (\frac{A}{x+2} + \frac{B}{x+3})，其中A和B是常数。找到这些常数后，我们可以分别对每个部分进行积分。

三角积分
三角积分涉及到含有三角函数的积分，比如 (\sin(x))，(\cos(x)) 或 (\tan(x)) 等。在这些情况下，我们可能需要使用三角恒等式或者通过适当的代换来简化积分。📐

举个例子，如果我们要积分 (\sin^2(x))，我们可以使用半角公式 (\sin^2(x) = \frac{1 - \cos(2x)}{2}) 来简化积分过程。

变量替换
变量替换，也称为u-代换，是一种将积分中的变量替换为另一个变量的方法，以简化积分。这通常在原函数的内部函数部分有一个明显的导数时使用。🔄

例如，考虑积分 (\int \sin(3x) , dx)，我们可以令 (u = 3x)，那么 (du = 3 , dx)。替换后积分变为 (\frac{1}{3}\int \sin(u) , du)，这就容易多了。 ------------------目前来看是无法正确显示数学公式的

### 🧐 解决方案

支持这个功能

**Comment by arvinxx** [comment]
数学公式问题： https://github.com/lobehub/lobe-chat/discussions/502
