### ISSUE TITLE
[Bug] 本地windows环境构建时报错如下：

### ISSUE THREAD

**Issue by huicewang** [lobehub/lobe-chat#1038]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/19237481/d0557192-de9f-4517-9641-8e351864bbc7)

**Comment by mushan0x0** [comment]
重装一下依赖试试

**Comment by huicewang** [comment]
依赖全部删除后，重新执行npm install安装，上述错误依然存在
![image](https://github.com/lobehub/lobe-chat/assets/19237481/5549fa74-7081-4337-a9eb-09c79864cf7f)


Returned expression type {role: ZodEnum<Writeable<[string, string, string, string]>>["_output"], pluginState?: ZodOptional<ZodAny>["_output"], quotaId?: ZodOptional<ZodString>["_output"], sessionId: ZodString["_output"], error?: ZodOptional<ZodAny>["_output"], content: ZodString["_output"], parentId?: ZodOptional<ZodString>["_output"], createdAt: number, topicId?: ZodOptional<ZodString>["_output"], plugin?: ZodOptional<ZodObject<{identifier: ZodString, apiName: ZodString, arguments: ZodString, type: ZodDefault<ZodEnum<Writeable<[..., ..., ..., ...]>>>}, "strip", ZodTypeAny, {[k_1 in keyof objectUtil.addQuestionMarks<baseObjectOutputType<{identifier: ..., apiName: ..., arguments: ..., type: ...}>, {[k in keyof ...]: ... extends ... ? ... : ...}[keyof {identifier: ..., apiName: ..., arguments: ..., type: ...}]>]: objectUtil.addQuestionMarks<baseObjectOutputType<{identifier: ..., apiName: ..., arguments: ..., type: ...}>, {[k in keyof ...]: ... extends ... ? ... : ...}[keyof {identifier: ..., apiName: ..., arguments: ..., type: ...}]>[k_1]}, {[k_2 in keyof baseObjectInputType<{identifier: ZodString, apiName: ZodString, arguments: ZodString, type: ...<...>}>]: baseObjectInputType<{identifier: ZodString, apiName: ZodString, arguments: ZodString, type: ...<...>}>[k_2]}>>["_output"], meta: {}, ...} is not assignable to type ChatMessage

**Comment by arvinxx** [comment]
你有同步代码吗？最新版应该没这个问题
