### ISSUE TITLE
[Bug] 开启反向代理后聊天不显示回复，报错如截图所示

### ISSUE THREAD

**Issue by sun-i** [lobehub/lobe-chat#1039]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/111034439/0a5dcf19-547a-412e-a677-65a8896b7d56)

**Comment by arvinxx** [comment]
大概率是你的配置有问题
