### ISSUE TITLE
[Request] 什么时候支持gemini？

### ISSUE THREAD

**Issue by helinr7** [lobehub/lobe-chat#1046]
### 🥰 需求描述

什么时候增加GOOGLE_KEY gemini的环境变量？

### 🧐 解决方案

什么时候增加GOOGLE_KEY gemini的环境变量？

**Comment by arvinxx** [comment]
在 https://github.com/lobehub/lobe-chat/discussions/737 跟进

**Comment by burugo** [comment]
可以先用 one-api 代替
考虑一下 one-api的用户，怎样兼容
