### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by linjungz** [lobehub/lobe-chat#1050]
### 💻 系统环境

macOS

### 📦 部署环境

Official Preview

### 🌐 浏览器

Edge

### 🐛 问题描述

在mac本地 bun run dev 后遇到如下错误：

✓ Compiled /welcome in 11.1s (13938 modules)
 ⨯ 1 | export default "file";
    ^
error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (file:1:1)
      at addPrimitives (file:1:13882)
      at extend (file:1:13846)
      at new VM (file:1:13923)
      at new EdgeVM (file:1:13846)
      at file:1:92

 ○ Compiling /_error ...

 ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3010". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase

无法正常运行

**Comment by arvinxx** [comment]
依赖更新了么？分支是最新的么？

**Comment by linjungz** [comment]
> 依赖更新了么？分支是最新的么？

是的，我刚又尝试用 npm install / npm run dev 就可以了
不知道为啥这个bun有问题

**Comment by arvinxx** [comment]
> > 依赖更新了么？分支是最新的么？
> 
> 
> 
> 是的，我刚又尝试用 npm install / npm run dev 就可以了
> 
> 不知道为啥这个bun有问题

可以把这个问题提给 bun

**Comment by linjungz** [comment]
> > > 依赖更新了么？分支是最新的么？
> > 
> > 
> > 是的，我刚又尝试用 npm install / npm run dev 就可以了
> > 不知道为啥这个bun有问题
> 
> 可以把这个问题提给 bun

好的！感谢回复，那我先把这个issue close了

**Comment by arvinxx** [comment]
我们后续把开发文档更新下，倒是有不少开发者遇到用bun 的问题了。开发时的包管理器换成 pnpm 会更稳一些
