### ISSUE TITLE
SSL Routines Error

### ISSUE THREAD

**Issue by BarryTheShen** [lobehub/lobe-chat#1052]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

This is what is returned when I type in anything
{
  "endpoint": "https://106.53.***.19:****/",
  "error": {
    "cause": {
      "library": "SSL routines",
      "reason": "wrong version number",
      "code": "ERR_SSL_WRONG_VERSION_NUMBER"
    }
  }
}

### 🚦 Expected Behavior

Its suppose to return a chat message

### 📝 Additional Information

I used a custom openai end point for this

**Comment by arvinxx** [comment]
your are using `https://xxxxx` ,please check your ssl

**Comment by BarryTheShen** [comment]
oh thank you so much

**Comment by BarryTheShen** [comment]
Now I have this error:
{
  "endpoint": "http://106.53.***.19:****/",
  "error": {
    "headers": {
      "access-control-allow-credentials": "true",
      "access-control-allow-headers": "*",
      "access-control-allow-methods": "*",
      "access-control-allow-origin": "*",
      "content-length": "18",
      "content-type": "text/plain; charset=utf-8",
      "date": "Mon, 15 Jan 2024 04:00:24 GMT"
    },
    "stack": "Error: 405 Method Not Allowed\n    at W.generate (/app/.next/server/app/api/openai/chat/route.js:22:1855)\n    at tF.makeStatusError (/app/.next/server/app/api/openai/chat/route.js:22:13240)\n    at tF.makeRequest (/app/.next/server/app/api/openai/chat/route.js:22:13970)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async k (/app/.next/server/app/api/openai/chat/route.js:2:2906)\n    at async /app/.next/server/app/api/openai/chat/route.js:7:64510",
    "status": 405
  }
}

**Comment by arvinxx** [comment]
Did your endpoint an openai api？

**Comment by BarryTheShen** [comment]
It is an openai api endpoint
