### ISSUE TITLE
[Request] MiniMax 模型支持

### ISSUE THREAD

**Issue by ifsheldon** [lobehub/lobe-chat#1053]
### 🥰 Feature Description

支持 MiniMax 的模型，MiniMax 的模型应该是国内模型和 OpenAI 最接近的了，无论是性能还是 API

### 🧐 Proposed Solution

没有官方库，所以只能用 http 请求；或者 one-api 支持 MiniMax 之后可以用 one-api，见 https://github.com/songquanpeng/one-api/pull/413

**Comment by arvinxx** [comment]
Minmax是不是不支持流式？

**Comment by ifsheldon** [comment]
支持的，除了图像的没有，基本上和 OpenAI 的 API 差不多，甚至还有 Assistant 的 API。而且个人也能拿到 API Key

**Comment by arvinxx** [comment]
之前看 langchain 的文档里它倒是有 model 层。但是不支持 stream。

<img width="675" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/83ee59d4-dcfb-4ad8-82b9-974aacb38ffa">

如果你说已经有的话，看起来是 langchain 自己的实现问题

**Comment by ifsheldon** [comment]
应该是实现的问题，官方的文档是有流式输出的，和 OpenAI 一样使用 SSE

**Comment by arvinxx** [comment]
能否给下官方文档？

**Comment by ifsheldon** [comment]
在这里 https://api.minimax.chat/document/guides/chat-model/pro

<img width="1751" alt="image" src="https://github.com/lobehub/lobe-chat/assets/39153080/b68b9894-5f84-4ed1-bb72-f28064e14b7e">

**Comment by search-codes-now-2016** [comment]
真的需要支持minimax 开发文档是https://www.minimaxi.com/document/guides/chat-model/V2
