### ISSUE TITLE
[Bug]docker部署文档中，环境变量的误导，与改正建议

### ISSUE THREAD

**Issue by GuoJiaxing1997** [lobehub/lobe-chat#1054]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

https://github.com/lobehub/lobe-chat/wiki/Environment-Variable
这里关于`OPENAI_PROXY_URL`是如下描述的：

> OPENAI_PROXY_URL
> Type: Optional
> Description: If you manually configure the OpenAI interface proxy, you can use this configuration item to override the default OpenAI API request base URL
> Default: https://api.openai.com
> Example: https://api.chatanywhere.cn

然而，代理地址正确的环境变量应该是：

> Default: https://api.openai.com/v1
> Example: https://api.chatanywhere.cn/v1

即，URL应该以`/v1`结尾，否则无法代理成功

### 🚦 期望结果

更改其为如下：

> OPENAI_PROXY_URL
> Type: Optional
> Description: If you manually configure the OpenAI interface proxy, you can use this configuration item to override the default OpenAI API request base URL
> Default: https://api.openai.com/v1
> Example: https://api.chatanywhere.cn/v1

### 📝 补充信息

祝项目越来越好！

**Comment by arvinxx** [comment]
不一定必须要加 v1 的。有些代理商是直接代理了 `openai.com/v1` ，这样用户就只需要填域名。但有些没代理，就要加 `/v1`

**Comment by canisminor1990** [comment]
> 不一定必须要加 v1 的。有些代理商是直接代理了 `openai.com/v1` ，这样用户就只需要填域名。但有些没代理，就要加 `/v1`

example 里确实应该加上 v1

**Comment by arvinxx** [comment]
default 可以加一下，但 `api.chatanywhere.cn` 这个还真不需要。
