### ISSUE TITLE
[Request] 根据 Azure OpenAI 实际的Deployment情况在聊天窗口列出/支持对应的 Model

### ISSUE THREAD

**Issue by linjungz** [lobehub/lobe-chat#1056]
### 🥰 需求描述

目前使用 Azure OpenAI 的 API，要求 Azure 上 Deployment 的命名与模型名称一致，但某些情况下Deployment可能命名无法与模型名称一致（可能是正在被使用，无法删除等）

另外在聊天窗口中，切换模型时，所有的LobeChat支持的模型都会被列出来，但在Azure上管理员并不一定会创建对应的 deployment，因此在聊天时，有可能会选中Azure上并未部署的模型，而导致API调用出错

### 🧐 解决方案

希望根据在Azure OpenAI 实际的Deployment情况，在聊天窗口列出/支持对应的 Model
是否可以考虑在配置API KEY/ENDPOINT时，增加一个Model与Deployment 的映射关系，举例如下：

//Model-Name=Deployment
gpt-4-1106-preview=gpt-4-1106-preview-deployment-name
gpt-4-vision-preview=gpt-4-vision-preview-deployment-name

这个映射关系里没有列出的模型，在聊天窗口中就不进行显示，以免用户选择后调用API会报 Deployment 不存在的错误

### 📝 补充信息

LobeChat是非常优秀的项目，我这边一直在寻找比较合适的多模态的聊天框架来做为Azure OpenAI的应用程序，因此非常希望能够参与到项目中，完善对Azure OpenAI的支持。 但我对前端/Next.js不熟悉，如果可以的话可以给我一些提示，我这边会尝试来做修改，看看是否能够完善这些功能

**Comment by arvinxx** [comment]
> 目前使用 Azure OpenAI 的 API，要求 Azure 上 Deployment 的命名与模型名称一致，但某些情况下Deployment可能命名无法与模型名称一致（可能是正在被使用，无法删除等）

想必这么做的原因你应该已经看过了，我们会在 #737 里完全解决这个问题。

> 另外在聊天窗口中，切换模型时，所有的LobeChat支持的模型都会被列出来，但在Azure上管理员并不一定会创建对应的 deployment，因此在聊天时，有可能会选中Azure上并未部署的模型，而导致API调用出错

这个复杂度很高，我之前调研过

> 同时 @azure/openai 目前并不支持 [模型查询](https://platform.openai.com/docs/api-reference/models/list)，如果要接入模型 list，需要再接入 [Azure 认知服务](https://learn.microsoft.com/zh-cn/rest/api/cognitiveservices/accountmanagement/accounts/list-models?tabs=HTTP) 的另外一个SDK。


> 是否可以考虑在配置API KEY/ENDPOINT时，增加一个Model与Deployment 的映射关系

你说的这个方案，目前应该是支持的，可以看看文档是否满足你的需求：https://github.com/lobehub/lobe-chat/wiki/Environment-Variable.zh-CN#custom_models

**Comment by linling007** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/22077944/1c8019a5-941a-4326-83c8-75323687dfc5)
![image](https://github.com/lobehub/lobe-chat/assets/22077944/2713dff0-8340-4c49-9f1b-d28de8876feb)
这里缺少了deployment_name的变量. 希望能加上
