### ISSUE TITLE
[Request] 支持路径参数配置吗?settings={"key":"你的key", "model": "gpt-4"}

### ISSUE THREAD

**Issue by yuanjie-ai** [lobehub/lobe-chat#1059]
### 🥰 Feature Description

[Request] 支持路径参数配置吗， 类似这样
```
https://api.chatllm.vip/#/?settings={"key":"你的key", "model": "gpt-4"}
```

### 🧐 Proposed Solution

[Request] 支持路径参数配置吗， 类似这样
```
https://api.chatllm.vip/#/?settings={"key":"你的key", "model": "gpt-4"}
```

### 📝 Additional Information

[Request] 支持路径参数配置吗， 类似这样
```
https://api.chatllm.vip/#/?settings={"key":"你的key", "model": "gpt-4"}
```

**Comment by arvinxx** [comment]
类似需求 #917 ，会一并考虑

**Comment by cy948** [comment]
这个需求比较简单，但参数命名可能比较有争议，自行实现可能更快。[我的实现](https://github.com/cy948/lobe-chat/blob/bc44d9f5bc1867874ab4b3f0c2d414cf37eaf42b/src/app/home/Redirect.tsx#L27)

**Comment by leoncool23** [comment]
> 这个需求比较简单，但参数命名可能比较有争议，自行实现可能更快。[我的实现](https://github.com/cy948/lobe-chat/blob/bc44d9f5bc1867874ab4b3f0c2d414cf37eaf42b/src/app/home/Redirect.tsx#L27)

你这个成功了吗？

**Comment by cy948** [comment]
@leoncool23  勉强能用。

**Comment by leoncool23** [comment]
> @leoncool23 勉强能用。

发来你的站 学习下
