### ISSUE TITLE
[Bug]如果浏览器保存访问密码，会在设置中的API key中自动填入，导致访问失败

### ISSUE THREAD

**Issue by Payne-Wang** [lobehub/lobe-chat#1075]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

在设置访问密码后，并使用浏览器保存后，在打开设置->语言模型界面时，密码会被自动填入openai设置的API key一栏，导致访问错误。这种情况难以排查（很多人打开这个是为了设置自定义模型，不会注意APIkey 被修改了）复现如下：
![image](https://github.com/lobehub/lobe-chat/assets/44337721/fe205843-8c9c-482c-b61c-feac7373470a)

**Comment by arvinxx** [comment]
这种有啥解决思路吗？

**Comment by mushan0x0** [comment]
> 这种有啥解决思路吗？

https://developer.mozilla.org/zh-CN/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion 这个属性可以
