### ISSUE TITLE
window刚拉下来的项目启动运行极慢

### ISSUE THREAD

**Issue by xianjuntang** [lobehub/lobe-chat#1077]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/31877679/3b534a99-eb86-481c-806e-d35cf9a07740)
每一步基本都要了很久，并且电脑cpu跑高到75%以上，最后一直卡在哪里进不去。在github的云空间编辑代码运行起来会快一些，不过也是非常的卡要十多秒，点击跳转页面也一样要很多秒

**Comment by arvinxx** [comment]
你的电脑可能性能不太好。你看终端的输出，编译了一个welcome页面用了266s

**Comment by xianjuntang** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/31877679/81863945-4bd3-4e92-8ca1-84d620a8d690)
@arvinxx 这个配置应该不会太差吧

**Comment by arvinxx** [comment]
i7 应该可以的吧，那感觉要排查下为啥这么慢了，你是每次启动都这样么？

**Comment by xianjuntang** [comment]
@arvinxx 是的，每次启动都很慢。
![image](https://github.com/lobehub/lobe-chat/assets/31877679/952d88bb-fc64-4c90-8a01-bd13aeae2e96)

**Comment by canisminor1990** [comment]
nextjs 在 dev 环境就是挺慢的
