### ISSUE TITLE
[Bug] EDGE_FUNCTION_INVOCATION_TIMEOUT

### ISSUE THREAD

**Issue by ginblackez** [lobehub/lobe-chat#1079]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

I use DALL-E 3 to gen image, but it is not really work sometimes.
![image](https://github.com/lobehub/lobe-chat/assets/143079361/f28179b5-12bf-4112-ad56-548eb89cd82f)

I upgraded to Vercel Pro and edited vercel.json like this, but it is not helpful.

```
{
  "installCommand": "bun install",
  "functions": {
    "app/api/**/*": {
      "maxDuration": 300
    }
  }
}
```

**Comment by Feiyuyu0503** [comment]
原来如此，我也是vercel部署，F12看了下也是这样，表现为对话框中的dall-e-3显示区无限显示生成中
```
An error occurred with your deployment
EDGE_FUNCTION_INVOCATION_TIMEOUT
```

**Comment by arvinxx** [comment]
please check vercel document: https://vercel.com/docs/functions/runtimes#max-duration
