### ISSUE TITLE
[Request] 建议增加助手调用快捷键

### ISSUE THREAD

**Issue by ccdanpian** [lobehub/lobe-chat#1081]
### 🥰 Feature Description

比如/translate就调用翻译助手，/story调用故事助手。 
快捷键由用户在助手设置页进行设置。

### 🧐 Proposed Solution

比如/translate就调用翻译助手，/story调用故事助手。 
快捷键由用户在助手设置页进行设置。

**Comment by arvinxx** [comment]
参考 #452 ，今年肯定会做的。但排期还没定

**Comment by ccdanpian** [comment]
建议优先安排一下，chatgpt网页今天已经能用快捷调用gpt助手了

**Comment by arvinxx** [comment]
@ccdanpian 最近在做 #737 这个， `@` 的功能估计要等过年期间了吧

**Comment by normal-coder** [comment]
Any more updates?

**Comment by arvinxx** [comment]
duplicate of https://github.com/lobehub/lobe-chat/issues/452
