### ISSUE TITLE
[Request] 以文本形式导出聊天记录

### ISSUE THREAD

**Issue by kawainotu** [lobehub/lobe-chat#1082]
### 🥰 需求描述

导出聊天记录的时候发现只能导出图片，对于需要对超长的聊天记录进行进一步处理的场景非常不友好，希望能以markdown的形式导出聊天记录。

### 🧐 解决方案

可以参考Next chat的方案，选择markdown导出格式之后，进行一键复制。

**Comment by canisminor1990** [comment]
赞同，后续准备支持

**Comment by arvinxx** [comment]
@canisminor1990 https://github.com/lobehub/lobe-chat/discussions/1090 开了个贴脑暴下
