### ISSUE TITLE
[Bug]用preview设置azure的时候出现报错 

### ISSUE THREAD

**Issue by BQQQQB** [lobehub/lobe-chat#1084]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

{
  "endpoint": "https://userchat.openai.az****re.com/openai/deployments/gpt-35-turbo",
  "error": {
    "code": "DeploymentNotFound",
    "message": "The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."
  }
}

**Comment by arvinxx** [comment]
你没部署名为 `gpt-35-turbo` 的模型吧

**Comment by BQQQQB** [comment]
> 你没有部署叫的`gpt-35-turbo`模型吧

我也用在线的试了一下，但是不成功，还是这个报错，这个是和我申请的模型有关系吗

**Comment by arvinxx** [comment]
有啊，你得部署一个这个名称的模型
