### ISSUE TITLE
图表生成器助手报错

### ISSUE THREAD

**Issue by scortLi** [lobehub/lobe-chat#1094]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/14088043/e981369a-8f6e-40b7-97b5-2341dde24a15)
使用图表生成器报错如图所示

**Comment by arvinxx** [comment]
有复现方案不

**Comment by scortLi** [comment]
@scortLi 
![image](https://github.com/lobehub/lobe-chat/assets/14088043/a1b0515c-aadf-4a3f-a854-5e736c03cc69)
就是添加助手然后添加天气插件问问题就报错了

**Comment by arvinxx** [comment]
返回结果那边点下我看看是啥

**Comment by scortLi** [comment]
{
  "tool_calls": [
    {
      "id": "call_ojqP6EJ81TfdqHc7MO4PymKT",
      "type": "function",
      "function": {
        "name": "python",
        "arguments": "import datetime\nimport matplotlib.pyplot as plt\n\n# 生成日期列表\ndates = []\nfor i in range(3):\n    date = datetime.datetime.now() - datetime.timedelta(days=i)\n    dates.append(date.strftime(\"%Y-%m-%d\"))\n\n# 模拟温度数据\ntemperatures = [28, 30, 29]\n\n# 绘制折线图\nplt.plot(dates, temperatures)\n\n# 设置图表标题和坐标轴标签\nplt.title(\"Guangzhou Temperature in the Last 3 Days\")\nplt.xlabel(\"Date\")\nplt.ylabel(\"Temperature (℃)\")\n\n# 显示图表\nplt.show()"
      }
    }
  ]
}
![image](https://github.com/lobehub/lobe-chat/assets/14088043/1dc9f4f9-45a0-45ed-92d8-4e44d33f4967)
![image](https://github.com/lobehub/lobe-chat/assets/14088043/2e61c8c5-3c05-4c37-b8d6-688cc6869211)
![image](https://github.com/lobehub/lobe-chat/assets/14088043/7db156d7-1424-478b-9fd1-c1cc6155301e)
@arvinxx

**Comment by arvinxx** [comment]
看起来原因是我们现在本地没有 python 的执行器… 你用的模型是标准的 gpt-4 吗？

**Comment by scortLi** [comment]
@arvinxx 
![image](https://github.com/lobehub/lobe-chat/assets/14088043/006575af-ea6f-4f54-97c0-dce46c6b70c2)
用的是这个

**Comment by arvinxx** [comment]
那这个是模型的问题了… 出现了幻觉。应用层可能暂时没法解决
