### ISSUE TITLE
[Request] 会出一个plus版本吗

### ISSUE THREAD

**Issue by losie** [lobehub/lobe-chat#1111]
### 🥰 需求描述

好项目 需要好的投资

### 🧐 解决方案

好项目 需要好的投资

**Comment by arvinxx** [comment]
我们会做 SaaS 版本的

**Comment by losie** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> We will do a SaaS version

 准备发布了吗 saas版本

**Comment by arvinxx** [comment]
@losie https://lobehub.com/ 感兴趣可以添加我们的 waitlist~
