### ISSUE TITLE
[Bug] Unrecognized request argument supplied: tools

### ISSUE THREAD

**Issue by binary-yuki** [lobehub/lobe-chat#1118]
### 💻 Operating System

macOS

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

Hi there,

为了兼容azure 和 openai 的api我采用了一个[js 脚本](https://github.com/haibbo/cf-openai-azure-proxy/blob/main/cf-openai-azure-proxy.js)用于转换azure请求格式为正常的openai请求格式达到兼容的效果

但是如果通过oneapi中转会出现error:
```json
{
  "endpoint": "https://ai.si****ax.tech/v1",
  "error": {
    "message": "Unrecognized request argument supplied: tools (request id: 20240121111812191932400LDhGk8pV)",
    "type": "invalid_request_error",
    "param": "",
    "code": null
  }
}
```
如果不通过oneapi会出现一只加载中的情况 无任何输出

不知是否与#923 相关？

### 🚦 Expected Behavior

正常输出

### 📷 Recurrence Steps

ref：加一层oneapi中转：

<img width="1058" alt="截屏2024-01-21 11 30 10" src="https://github.com/lobehub/lobe-chat/assets/60097976/947eec14-d6d2-4f48-9c17-b5bb1db6bc0f">

ref:没有使用中转

<img width="1064" alt="截屏2024-01-21 11 30 23" src="https://github.com/lobehub/lobe-chat/assets/60097976/7db4ffec-4994-4950-96fd-24e4541f64b7">

**Comment by arvinxx** [comment]
你的 azure 部署版本太低了吧。不支持 tools 关键词。试试更新到最新的部署版本。参考：

- https://github.com/lobehub/lobe-chat/issues/592
- https://github.com/lobehub/lobe-chat/discussions/551
