### ISSUE TITLE
[Request] 可否修改网站logo和标题

### ISSUE THREAD

**Issue by IPCAB** [lobehub/lobe-chat#1122]
### 🥰 需求描述

可否加入一些修改网站标题和logo的变量，比如一个变量设置网站名称另一个变量设置网站logo的图片链接

### 🧐 解决方案

加入一些修改网站标题和logo的变量

**Comment by arvinxx** [comment]
欢迎 PR：https://github.com/lobehub/lobe-chat/blob/main/src/features/AvatarWithUpload/index.tsx#L57

**Comment by h7ml** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/55233292/e8bb647f-e821-4b92-b255-4af6213d4b59)


DEFAULT_AGENT_META 字段可以这么自定义吗？
