### ISSUE TITLE
[Bug] My chats were lost!

### ISSUE THREAD

**Issue by JoshAtticus** [lobehub/lobe-chat#1124]
### 💻 Operating System

macOS

### 📦 Environment

Other

### 🌐 Browser

Chrome

### 🐛 Bug Description

Recently, chat.aivvm.com started redirecting to lobe.caifree.com, so now I can't get my chats back! Please help!

**Comment by arvinxx** [comment]
you need to contact the author of `chat.aivvm.com`. Because the data is saved on `chat.aivvm.com` host's indexedDB

**Comment by JoshAtticus** [comment]
> you need to contact the author of `chat.aivvm.com`. Because the data is saved on `chat.aivvm.com` host's indexedDB.
> 
> You need to open chat page on `chat.aivvm.com` and then export the data. And then import them on `lobe.caifree.com`.

I can't open the chat page since it automatically redirects to the new site

**Comment by JoshAtticus** [comment]
Edit: I moved the indexeddb files from chat.aivvm.com to lobe.caifree.com, it worked!

**Comment by arvinxx** [comment]
> Edit: I moved the indexeddb files from chat.aivvm.com to lobe.caifree.com, it worked!

Amazing ! how do you make it? Maybe this canbe  a guide for similar users.

**Comment by JoshAtticus** [comment]
> > Edit: I moved the indexeddb files from chat.aivvm.com to lobe.caifree.com, it worked!
> 
> Amazing! How do you make it? Maybe this canbe a guide for similar users.

On Firefox,
1. Open your profile folder (C:\Users\<username>\AppData\Roaming\Mozilla\Firefox\Profiles\ on Windows and ~/Library/Application Support/Firefox/Profiles/ on macOS)
2. Go through the folders until you find the one with the storage folder 
3. Locate the folder for the old page and open it 
4. Open the idb folder inside of it and copy everything in there 
5. Find the folder for the new page and open it 
6. Go into the idb folder, make a backup of everything in there to somewhere safe
7. Paste the files from the old site and click yes when asked to replace all files and folders.
