### ISSUE TITLE
[Bug] 暂时不支持chatglm的api调用

### ISSUE THREAD

**Issue by tyrantGXY** [lobehub/lobe-chat#1125]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

我使用oneapi，里面渠道填好了chatglm的api和模型，但是在lobechat中，无法使用。自定义模型使用后，返回非法参数错误

### 🚦 期望结果

希望能增加支持

**Comment by arvinxx** [comment]
目前是还不支持 ChatGLM 的 api ，会在 #737 中支持
