### ISSUE TITLE
[Bug] 一发信息就说管理员设置了密码，输入密码才能使用，请问密码是什么哦

### ISSUE THREAD

**Issue by 129time** [lobehub/lobe-chat#1128]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

使用出现输入密码提示，请问什么密码。

**Comment by BQQQQB** [comment]
默认lobe66

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/discussions/993
