### ISSUE TITLE
[Bug] 剩余字数会没有显示

### ISSUE THREAD

**Issue by BQQQQB** [lobehub/lobe-chat#1129]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/92673213/5fe89ba6-f80f-4c92-b1d4-8afcf62fb79c)
 我是按照名字匹配添加的模型，userchat=pgt-4,可以使用但是剩余字数会没有显示

**Comment by arvinxx** [comment]
`userchat` 没有最大上 token 的信息，自然无法显示了
