### ISSUE TITLE
[Bug] 插件AskYourPDF使用报错

### ISSUE THREAD

**Issue by BQQQQB** [lobehub/lobe-chat#1130]
### 💻 Operating System

Ubuntu

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/92673213/b75fee88-e344-4484-ba50-9fec2186f63b)
![image](https://github.com/lobehub/lobe-chat/assets/92673213/48c06e79-8d7d-4b93-aa4d-aa5b3dc1bcb1)

**Comment by BQQQQB** [comment]
我使用的在线的也报错，我用的是Azure OpenAI的API

**Comment by xiaoxuan220** [comment]
me too 是AskYouPDF接口换了吗？辛苦作者看一下，非常感谢

**Comment by arvinxx** [comment]
@xiaoxuan220 @BQQQQB 是 bug，在修了。很快修复

**Comment by BQQQQB** [comment]
@arvinxx 老师，刚好问一下这个插件的官网在哪里，就是上传PDF的网址，我刚刚在找这个没找到，方便提供一下吗？谢谢

**Comment by arvinxx** [comment]
> @arvinxx 老师，刚好问一下这个插件的官网在哪里，就是上传PDF的网址，我刚刚在找这个没找到，方便提供一下吗？谢谢

https://askyourpdf.com/zh 应该就是这个

**Comment by arvinxx** [comment]
已修复，大伙再试试

**Comment by hackiey** [comment]
@arvinxx 有些插件最后解析出来的function参数不太对，我打印出了一个youtube视频字幕的
```json
{
    "description": "Transcribe a section of a video",
    "name": "VideoCaptions____transcribeVideo",
    "parameters": {
        "properties": {
            "_requestBody": {
                "type": "object",
                "properties": {
                    "videoId": {
                        "type": "string",
                        "description": "YouTube video ID to be transcribed"
                    },
                    "segment": {
                        "type": "integer",
                        "description": "Segment number to transcribe, with each segment holding a maximum of 2k words."
                    },
                    "includeTimestamp": {
                        "type": "boolean",
                        "description": "Specifies whether to include timestamps in the transcription"
                    }
                }
            }
        },
        "type": "object"
    }
}
```
这个就会导致调用失败

**Comment by arvinxx** [comment]
> @arvinxx 有些插件最后解析出来的function参数不太对，我打印出了一个youtube视频字幕的，在properties下面多了一层_requestBody/properties
> 
> ```json
> {
>     "description": "Transcribe a section of a video",
>     "name": "VideoCaptions____transcribeVideo",
>     "parameters": {
>         "properties": {
>             "_requestBody": {
>                 "type": "object",
>                 "properties": {
>                     "videoId": {
>                         "type": "string",
>                         "description": "YouTube video ID to be transcribed"
>                     },
>                     "segment": {
>                         "type": "integer",
>                         "description": "Segment number to transcribe, with each segment holding a maximum of 2k words."
>                     },
>                     "includeTimestamp": {
>                         "type": "boolean",
>                         "description": "Specifies whether to include timestamps in the transcription"
>                     }
>                 }
>             }
>         },
>         "type": "object"
>     }
> }
> ```
> 
> 这个就会导致调用失败

这些参数是会放入请求的 body 里去调用的。openai 单纯的 fc 是不知道这些参数应该如何构造进标准请求里（比如有的是query，有的是 url params ，有的是 body），所以针对要传到 body 的部分，我做了一层中间处理，将它们都放到 `_requestBody` 下面。

**Comment by arvinxx** [comment]
@hackiey 你可以单独开个 issue 来提下

**Comment by hackiey** [comment]
是我的proxy不支持这种格式，我用OpenAI的官方库试了一下是可以运行的，没问题了。
