### ISSUE TITLE
[Request] 可以在拓展里面不启用DALL吗？api太贵了

### ISSUE THREAD

**Issue by binhtml5** [lobehub/lobe-chat#1134]
### 🥰 需求描述

可以在拓展里面不启用DALL吗？api太贵了

### 🧐 解决方案

可以在拓展里面不启用DALL吗？api太贵了

**Comment by Justin3go** [comment]
![recording](https://github.com/lobehub/lobe-chat/assets/63507251/57971782-aae2-4c11-b61d-1f686c549a3f)
可以取消吧，是这个意思嘛

**Comment by binhtml5** [comment]
> ![recording](https://private-user-images.githubusercontent.com/63507251/298996492-57971782-aae2-4c11-b61d-1f686c549a3f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjQ2NzYsIm5iZiI6MTcwNjAyNDM3NiwicGF0aCI6Ii82MzUwNzI1MS8yOTg5OTY0OTItNTc5NzE3ODItYWFlMi00YzExLWI2MWQtMWY2ODZjNTQ5YTNmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE1MzkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NDlhMzkyOGNmN2M1YmNkZWVkNDBhMjZiYTRkYWZiYmU2YTE3NjFjNGE1ODZiNzNmOTA2Yjg5ZjBjNTI4MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZNvdykDsylErMvSW7HXT9ULg5Cy9caGuVyUOtB-9E1s) [ ![recording](https://private-user-images.githubusercontent.com/63507251/298996492-57971782-aae2-4c11-b61d-1f686c549a3f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjQ2NzYsIm5iZiI6MTcwNjAyNDM3NiwicGF0aCI6Ii82MzUwNzI1MS8yOTg5OTY0OTItNTc5NzE3ODItYWFlMi00YzExLWI2MWQtMWY2ODZjNTQ5YTNmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE1MzkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NDlhMzkyOGNmN2M1YmNkZWVkNDBhMjZiYTRkYWZiYmU2YTE3NjFjNGE1ODZiNzNmOTA2Yjg5ZjBjNTI4MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZNvdykDsylErMvSW7HXT9ULg5Cy9caGuVyUOtB-9E1s) ](https://private-user-images.githubusercontent.com/63507251/298996492-57971782-aae2-4c11-b61d-1f686c549a3f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjQ2NzYsIm5iZiI6MTcwNjAyNDM3NiwicGF0aCI6Ii82MzUwNzI1MS8yOTg5OTY0OTItNTc5NzE3ODItYWFlMi00YzExLWI2MWQtMWY2ODZjNTQ5YTNmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE1MzkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NDlhMzkyOGNmN2M1YmNkZWVkNDBhMjZiYTRkYWZiYmU2YTE3NjFjNGE1ODZiNzNmOTA2Yjg5ZjBjNTI4MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZNvdykDsylErMvSW7HXT9ULg5Cy9caGuVyUOtB-9E1s) [ ](https://private-user-images.githubusercontent.com/63507251/298996492-57971782-aae2-4c11-b61d-1f686c549a3f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjQ2NzYsIm5iZiI6MTcwNjAyNDM3NiwicGF0aCI6Ii82MzUwNzI1MS8yOTg5OTY0OTItNTc5NzE3ODItYWFlMi00YzExLWI2MWQtMWY2ODZjNTQ5YTNmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE1MzkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NDlhMzkyOGNmN2M1YmNkZWVkNDBhMjZiYTRkYWZiYmU2YTE3NjFjNGE1ODZiNzNmOTA2Yjg5ZjBjNTI4MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZNvdykDsylErMvSW7HXT9ULg5Cy9caGuVyUOtB-9E1s) 可以取消吧，是这个意思嘛

是的

**Comment by ShanySky** [comment]
提供一个解决方案：用one-api搭建接口分发平台，在渠道中不启用dall-e3即可。
