### ISSUE TITLE
[Bug] 设置页面缺失

### ISSUE THREAD

**Issue by ertcds** [lobehub/lobe-chat#1138]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Docker

### 🌐 浏览器

Edge

### 🐛 问题描述

昨天更新最新版，设置页面正常，今天发现缺失一部分选项，删除缓存后，重新启动docker，第一次进入有选择，刷新页面后没有了。
<img width="409" alt="截屏2024-01-24 11 11 01" src="https://github.com/lobehub/lobe-chat/assets/9860954/76a30b81-3f6e-4088-9499-76bcdea06f5b">

**Comment by mushan0x0** [comment]
<img width="268" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/4e8cb921-abd4-4064-83aa-2f6a14b2a76c">
点这里就出来了，不过建议这个侧边隐藏后，展开按钮能够一直显示可能比较好 @canisminor1990 @arvinxx

**Comment by ertcds** [comment]
> <img alt="image" width="268" src="https://private-user-images.githubusercontent.com/29084441/299167299-4e8cb921-abd4-4064-83aa-2f6a14b2a76c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjY1MzgsIm5iZiI6MTcwNjA2NjIzOCwicGF0aCI6Ii8yOTA4NDQ0MS8yOTkxNjcyOTktNGU4Y2I5MjEtYWJkNC00MDY0LTgzYWEtMmY2YTE0YjJhNzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAzMTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNjI0ZDhhZDI1Njk4NmM2ZDFiMjc4OTcyZTg5M2NkM2VkZWViZDIwNmExZDc1ODU4ZDcwMjM3YjA5MTk1MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q32EPSExL2rNNg90Orfboo-FGO8uGPpTgU1ze9QlJ70"> 点这里就出来了，不过建议这个侧边隐藏后，展开按钮能够一直显示可能比较好 @canisminor1990 @arvinxx

对不起，我不知道什么时候隐藏了，非常感谢你。

**Comment by arvinxx** [comment]
@canisminor1990 所以我之前说设置不应该复用 SessionList 的模块。感觉更好的是参考这种样式：

<img width="1381" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/3eac47f9-d82a-4d2f-bf98-b3cb299d6350">

<img width="915" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/f4b286f8-a892-4d72-8317-fa51c597506d">

后续可以调整下到这部分的设计

**Comment by canisminor1990** [comment]
ok 后面我抽空改一下吧

**Comment by zHElEARN** [comment]
我也是，不知道什么时候把左边这个侧边栏隐藏了，根本找不到怎么开，看了这个issue才知道怎么打开
