### ISSUE TITLE
[Bug] 看不到消息时间

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#1140]
### 💻 系统环境

macOS

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

看不到消息时间了
<img width="437" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/64859c7c-f391-416d-8f5f-4432b76388f1">
我看了下被这个样式影响了
<img width="1306" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/a7571ec6-b18b-4634-ace9-b7203c0c7e47">

### 🚦 期望结果

正常是这样的
<img width="666" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/85ffb97f-9cbf-4b69-bfaa-8d7ad2e69990">

**Comment by arvinxx** [comment]
奇怪，这个 overflow 是在哪里的

**Comment by mushan0x0** [comment]
https://github.com/lobehub/lobe-ui/blob/bf387977bbff9c8a68ddb80e90deb0548dcf5b5b/src/ChatItem/style.ts#L187 应该是这样影响的

**Comment by mushan0x0** [comment]
https://github.com/lobehub/lobe-ui/blob/bf387977bbff9c8a68ddb80e90deb0548dcf5b5b/src/ChatItem/style.ts#L186 另外这里 overflow-x 也许可以设置为 auto，不然屏幕窄的话插件 debug 开启后就关不掉了
<img width="471" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/7d95945f-7f77-414d-8b84-72f9605f9a97">
