### ISSUE TITLE
[Request] 在设置界面增加自定义头部选项以让Umami更方便地采集网站流量信息

### ISSUE THREAD

**Issue by Episode233** [lobehub/lobe-chat#1141]
### 🥰 需求描述

在当前的umami实现下，用户需要手动插入script标签到每一个需要追踪的页面中。这既不方便也容易出错，特别是对于大型网站和使用docker部署的环境。
![umami](https://github.com/lobehub/lobe-chat/assets/87570815/cdf22a34-0cdb-483f-b6a0-7e7766f03f2b)

### 🧐 解决方案

我建议umami在设置界面增加一个新的选项，可以让用户添加自定义的头部。这样用户可以在这个界面直接指定需要插入的script标签，umami会自动将这个标签添加到每个页面的头部。这和alist的实现方式很类似，可以参考。
另外，如果可能的话，我也希望得到一个详细的教程讲解如何在docker部署的环境中手动添加script标签。
![alist](https://github.com/lobehub/lobe-chat/assets/87570815/84f741ac-4901-457d-9dd6-c871e9e206df)

**Comment by arvinxx** [comment]
@Episode233  要做流量统计的话，可以参考这部分的实现：https://github.com/lobehub/lobe-chat/blob/main/src/components/Analytics/index.tsx 

这样就 docker 部署几个环境变量可能就好了。

**Comment by Episode233** [comment]
貌似暂时不支持umami，未来有考虑添加吗？🫡

**Comment by arvinxx** [comment]
> 貌似暂时不支持umami，未来有考虑添加吗？🫡

欢迎PR~

**Comment by sunnycherry2023** [comment]
谢谢，你让我知道了alist还可以自定义头部（之前想给alist加入umami一直没找到办法233）
