### ISSUE TITLE
[Request] 添加openrouter api 的支持

### ISSUE THREAD

**Issue by firsteyev** [lobehub/lobe-chat#1145]
### 🥰 需求描述

openrouter  上有很多免费或低价的model，我直接在lobe-chat用openrouter 的api时，
![image](https://github.com/lobehub/lobe-chat/assets/128565700/0a1e6527-b529-4ebd-94d4-0081bae990e4)

lobe-chat会同时发送两个request,一个给chatgpt 3.5 turbo,另一个发送我自定义的model.   
![image](https://github.com/lobehub/lobe-chat/assets/128565700/b9deea9e-f110-42df-be74-a67fa712b4c2)

### 🧐 解决方案

请添加 openrouter 的支持，避免使用自选模型时同时发送chatgpt 3.5 turbo的请求

**Comment by arvinxx** [comment]
> 同时发送chatgpt 3.5 turbo的请求

这个是自动做标题总结这些使用的调用。后续可以开个配置让用户来选吧

**Comment by mushan0x0** [comment]
https://github.com/lobehub/lobe-chat/wiki/Environment-Variable.zh-CN#custom_models 可以用这个重新映射一下 GPT-3.5 Turbo 模型

**Comment by firsteyev** [comment]
> https://github.com/lobehub/lobe-chat/wiki/Environment-Variable.zh-CN#custom_models 可以用这个重新映射一下 GPT-3.5 Turbo 模型
![image](https://github.com/lobehub/lobe-chat/assets/128565700/1d9c9651-097a-4af5-84a8-1fe5ef987684)

我去掉了所有其它模型，只留了两个自选模型，但是lobe-chat仍然发给gpt3.5 turbo 一个request 
![image](https://github.com/lobehub/lobe-chat/assets/128565700/c868d71f-0ea1-4b46-8b4b-dba2637c09b5)

**Comment by firsteyev** [comment]
我明白了，大概是开启对话后，虽然对话可以使用自定义模型，但是lobe-chat默认使用 Gpt3.5 turbo 去总结对话的 标题，因此会发送一个gpt3.5 turbo 的request,而这个功能没有办法改为使用自定义的模型。

**Comment by arvinxx** [comment]
> 我明白了，大概是开启对话后，虽然对话可以使用自定义模型，但是lobe-chat默认使用 Gpt3.5 turbo 去总结对话的 标题，因此会发送一个gpt3.5 turbo 的request,而这个功能的模型名称不随用户的选择更改。

对。

**Comment by ShanySky** [comment]
如果能选择总结对话标题时使用哪个模型就更好了。

**Comment by arvinxx** [comment]
@ShanySky 会支持的
