### ISSUE TITLE
[Request] 支持新模型 gpt-4-0125-preview 和 gpt-4-turbo-preview

### ISSUE THREAD

**Issue by devyujie** [lobehub/lobe-chat#1152]
### 🥰 需求描述

官方更新了4turbo的[最新模型](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo)：gpt-4-0125-preview 和 gpt-4-turbo-preview，希望可以增加一下

### 🧐 解决方案

、

**Comment by mushan0x0** [comment]
可以等 gpt-3.5-turbo-0125 更新后再更新代码，现在可以添加自定义模型使用
<img width="831" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/87ae2f12-cfcd-471f-8a09-aa2ff0dff542">
