### ISSUE TITLE
你好请问如何把插件做成内置扩展的

### ISSUE THREAD

**Issue by scortLi** [lobehub/lobe-chat#1153]
### 🥰 需求描述

![image](https://github.com/lobehub/lobe-chat/assets/14088043/1ce7e634-5494-4b98-8e10-1bfa8ec6cf1c)
请问 下如何把插件做成内置选中的，不需要手动去配置的呢

### 🧐 解决方案

请问 下如何把插件做成内置选中的，不需要手动去配置的呢

**Comment by scortLi** [comment]
@arvinxx  是的，请问下如何配置呢

**Comment by arvinxx** [comment]
目前还不支持，等待 #913 实现

**Comment by scortLi** [comment]
@arvinxx 请问这个实现了吗

**Comment by arvinxx** [comment]
@scortLi 还没，近期会实现的
