### ISSUE TITLE
[Bug] 无法使用插件

### ISSUE THREAD

**Issue by muxinxy** [lobehub/lobe-chat#1155]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

升级到最新版本之后无法使用插件，尝试了各种模型和各种插件，助手只会回复“稍等”，不会真正调用插件。如下图所示：

![image](https://github.com/lobehub/lobe-chat/assets/32673109/6a27c764-b6b8-4dea-8237-5e0136ccd34c)

### 🚦 期望结果

正常调用插件

### 📷 复现步骤

最新版本使用插件

### 📝 补充信息

升级之前是正常的

**Comment by arvinxx** [comment]
你用的是哪个 api 服务商？

**Comment by muxinxy** [comment]
> 你用的是哪个 api 服务商？

https://one.caifree.com/

**Comment by anjiacm** [comment]
我直接用openai 的接口地址，也会报一样的错误
