### ISSUE TITLE
[Request] 自定义模型建议

### ISSUE THREAD

**Issue by bincooo** [lobehub/lobe-chat#1157]
### 🥰 需求描述

希望能做成tag输出框，因为如果多敲了空格或者中文的逗号就无法识别，如果使用者不会看调试窗的话不太容易发现。
<img width="1082" alt="Screenshot 2024-01-26 at 22 43 20" src="https://github.com/lobehub/lobe-chat/assets/36452456/4dc0c2eb-ab38-4713-890f-7586a1d62959">
<img width="476" alt="Screenshot 2024-01-26 at 22 46 42" src="https://github.com/lobehub/lobe-chat/assets/36452456/35e6afae-4b69-4e58-91b4-072b12ec83c2">

### 🧐 解决方案

无

**Comment by sing-jump-rap** [comment]
你好，自定义模型这部分有相关文档或资料吗，想接入自己的自定义模型

**Comment by bincooo** [comment]
> 你好，自定义模型这部分有相关文档或资料吗，想接入自己的自定义模型

gpt的请求协议，你实现了就行
