### ISSUE TITLE
[Bug] List rendering problem in Safari

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#1161]
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Safari

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/36695271/6a66cf16-5a2e-473d-804d-da086286cdfe)

见于 Safari PWA（macOS Sonoma），流式输出。

文本完全正常同 Markdown 列表文本，只要点击编辑然后取消即可正常渲染。但是若不做此操作，则会保留这个多出来的空白换行。

未在 Chrome 中测试。

@canisminor1990 

### 🚦 期望结果

正常列表渲染。

### 📷 复现步骤

随便问 GPT 一个问题，得到一个列表，即有概率触发此问题。

**Comment by zhuozhiyongde** [comment]
我想一个简单的解决方式就是，在整体请求完成后，重新进行一次渲染。事实上，我现在对于未能成功渲染的回答，点击一下编辑再立刻取消就能正常了。

@canisminor1990

**Comment by zhuozhiyongde** [comment]
https://github.com/lobehub/lobe-chat/assets/36695271/01815f3c-d805-4ce8-b59d-b93394b30fac

**Comment by zhuozhiyongde** [comment]
我注意到这个问题至今仍未解决，但是真的很影响体验，希望大佬们再看一眼 @canisminor1990 @arvinxx

**Comment by arvinxx** [comment]
我这个月修一下

**Comment by zhuozhiyongde** [comment]
小小的催一下~

另外，我之前说

> 在整体请求完成后，重新进行一次渲染。

这个方法确实有效，我现在也是这么做的（通过先切换到别的话题再切换回来），但是我想了一下，可能能够在过程中就重新渲染（或者更彻底的，完全修复）可能更好。因为有可能在流式输出的过程中就在阅读了（

**Comment by canisminor1990** [comment]
https://github.com/lobehub/lobe-ui/commit/cf75d6a6ae1decad3e736fbaf42f3690b5cdad75
