### ISSUE TITLE
[Request] 用 @ 功能代替助手切换

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#1162]
### 🥰 需求描述

https://mp.weixin.qq.com/s/mnvuteSe8cC41lAqU4lVzA 在输入框直接助手似乎更科学，就不用在不同助手之间切换了，然后可以合并对话列表和话题，还可以在不同助手之间共享上下文

### 🧐 解决方案

<img width="663" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/42d8082a-0dc1-463c-83b5-6f569feb8862">

**Comment by canisminor1990** [comment]
@ 功能是准备添加的，但目的不是为了合并对话列表和话题，而且增加临时呼唤协作能力，和 Agent 维度的划分不冲突
