### ISSUE TITLE
[Request] 希望可以部署在Netlify

### ISSUE THREAD

**Issue by ASDZXC535** [lobehub/lobe-chat#1163]
### 🥰 需求描述

希望可以部署在Netlify

### 🧐 解决方案

无

### 📝 补充信息

无

**Comment by chenweiask** [comment]
Netlify service is unstable in China, so you still have to bond it to your own domain. No difference against Vercel.

**Comment by ckt1031** [comment]
> Netlify service is unstable in China, so you still have to bond it to your own domain. No difference against Vercel.

Sticking to Vercel is not the only option, global user matters, they would like other platform such as Netlify, Cloudflare Pages.

Development should not only concern whether this or that service is available in China or not, and they don’t care.

**Comment by arvinxx** [comment]
已经试过了，默认就支持的。

**Comment by arvinxx** [comment]
@ASDZXC535 已补充文档： https://chat-docs.lobehub.com/zh/self-hosting/platform/netlify
