### ISSUE TITLE
math formulas[Request] 

### ISSUE THREAD

**Issue by 110rever** [lobehub/lobe-chat#1164]
### 🥰 Feature Description

When will full support for math formulas be added?

### 🧐 Proposed Solution

It seems that there is currently no support for math formula output.

**Comment by mushan0x0** [comment]
duplicate #502 #1110

**Comment by arvinxx** [comment]
you can make your personal agent like: https://github.com/lobehub/lobe-chat/discussions/1113#discussioncomment-8195223
