### ISSUE TITLE
A client-side exception has occurred

### ISSUE THREAD

**Issue by worras2019** [lobehub/lobe-chat#1172]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

When I tried to do setup in Chrome, I got this: Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by muxinxy** [comment]
Objects are not valid as a React child (found: object with keys {$$typeof, render, displayName}). If you meant to render a collection of children, use an array instead.

**Comment by TalexCK** [comment]
same

**Comment by arvinxx** [comment]
which version？

**Comment by arvinxx** [comment]
fixed in #1178
