### ISSUE TITLE
[Request] Options for send message key

### ISSUE THREAD

**Issue by Arctomachine** [lobehub/lobe-chat#1183]
### 🥰 Feature Description

Default send message hotkey is Enter, and new line hotkey is Shift+Enter, and there is no option to change it. It is not comfortable when dealing with multiline texts (code blocks, for example).

### 🧐 Proposed Solution

Add new setting to change this hotkey
Solution 1: simple toggle between Enter/Shift+Enter and Ctrl+Enter/Enter modes for send/linebreak. These are 2 most common modes used in chat apps
Solution 2: select hotkey for each action separately from Enter, Shift+Enter, Ctrl+Enter, Alt+Enter. This allows more options for people who are not satisfied with 2 modes from toggle

**Comment by arvinxx** [comment]
<img width="311" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/8e647797-9aa6-4199-a73a-08da7868d0f0">

Actually we have it

**Comment by Arctomachine** [comment]
Strange, there is no menu in my interface.
![image](https://github.com/lobehub/lobe-chat/assets/29041820/eb791d3d-661b-42b2-8810-197b95055f89)

**Comment by arvinxx** [comment]
Please check your version and upgrade to latest

**Comment by sagarspatil** [comment]
> <img alt="image" width="311" src="https://private-user-images.githubusercontent.com/28616219/300674537-8e647797-9aa6-4199-a73a-08da7868d0f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTkyODEsIm5iZiI6MTcwNzM5ODk4MSwicGF0aCI6Ii8yODYxNjIxOS8zMDA2NzQ1MzctOGU2NDc3OTctOWFhNi00MTk5LWE3M2EtMDhkYTc4NjhkMGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEzMjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiOGEzOTg3Njg4NmRmYTc1MWM0MzIxMzc1Y2JhZThhNDdkMGIyMzY3MzEzMThjMmUzNmFkMTJiNjc5NjdjN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WsL0N2Zt60DCXgv-9TQkB5HGPH5_9oPAKvIToeiLv84">
> 
> Actually we have it

I'm on the latest version 0.125.0 and I only see a plane icon for sending message, it doesn't allow me to choose like you've shown in the screenshot 
![Screenshot_20240208_190140_Firefox Nightly](https://github.com/lobehub/lobe-chat/assets/14179161/8cc714a3-0986-4bc7-8daf-ece738335fc7)
