### ISSUE TITLE
有没有考虑做登录功能呀,想要登录同步功能

### ISSUE THREAD

**Issue by atao-z** [lobehub/lobe-chat#1184]
### 🥰 需求描述

每次换设备或者换域名的时候就需要重新导入配置,使用过程就会造成部分数据不同步有点不舒服

### 🧐 解决方案

希望可以增加登录同步的功能

**Comment by arvinxx** [comment]
同步会做，登录不会

同步在 #368 跟进

**Comment by arvinxx** [comment]
我们在 `v0.141.0` 上线了基于 YJS 与 WebRTC 的实验性数据同步功能，欢迎测试并反馈：
- 反馈issue: #1683
- 背后思考：https://github.com/lobehub/lobe-chat/discussions/1681

如果上述同步功能不满足你的诉求，可以 Reopen 该 issue
