### ISSUE TITLE
[Request] 如何关闭DELL3这些服务。因为给企业内部使用。针对不同人群想限制一些功能

### ISSUE THREAD

**Issue by anjiacm** [lobehub/lobe-chat#1189]
### 🥰 需求描述

[Request] 如何关闭DELL3这些服务。因为给企业内部使用。针对不同人群想限制一些功能

### 🧐 解决方案

[Request] 如何关闭DELL3这些服务。因为给企业内部使用。针对不同人群想限制一些功能

### 📝 补充信息

[Request] 如何关闭DELL3这些服务。因为给企业内部使用。针对不同人群想限制一些功能

**Comment by deepwzh** [comment]
感觉可以自己拉取插件仓库https://github.com/lobehub/lobe-chat-plugins，替换掉PLUGINS_INDEX_URL环境变量？
或者可以简单的接一下，里面把dalle3的权限去掉就好了[https://github.com/songquanpeng/one-api](https://github.com/songquanpeng/one-api)

**Comment by arvinxx** [comment]
> 感觉可以自己拉取插件仓库https://github.com/lobehub/lobe-chat-plugins，替换掉PLUGINS_INDEX_URL环境变量？
> 
> 或者可以简单的接一下，里面把dalle3的权限去掉就好了[https://github.com/songquanpeng/one-api](https://github.com/songquanpeng/one-api)

自己拉没用，因为dalle是内置插件。所以比较好的方案应该是允许自定义哪些插件时内置插件

**Comment by anhao** [comment]
自己拉取代码，把相关功能去掉不就可以了
