### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by comeback01** [lobehub/lobe-chat#1194]
### 💻 Operating System

iOS

### 📦 Environment

Docker

### 🌐 Browser

Safari

### 🐛 Bug Description

It works on Windows 11 with Chrome, Brave, but I have the same problem with Opera as with my iPhone, I get this message:
![Capture d'écran 2024-01-30 140505](https://github.com/lobehub/lobe-chat/assets/17897116/2b71fbf4-5404-417b-9de2-4e1bdd7a3968)

### 🚦 Expected Behavior

I waited for the agent to answer.

**Comment by comeback01** [comment]
I've just tried it with Chrome on my iPhone, and it works, but still not with Safari!

**Comment by comeback01** [comment]
Yes, I've also cleared the browser cache!

I've tried it on several iPhones, and it's the same.

The problem on Windows is on Opera, and for iOS, on Safari.

The problem appeared after the last

**Comment by arvinxx** [comment]
is your token  valid ?

**Comment by comeback01** [comment]
Yes, because it works on Windows 11, with Chrome and Brave.

But it doesn't work with Opera!

On iOS, it works with Chrome, but not Safari.
