### ISSUE TITLE
能否提供个文件用于修改默认设置

### ISSUE THREAD

**Issue by cokice** [lobehub/lobe-chat#1196]
### 🥰 需求描述

就像nextweb一样，可以默认设置好压缩阈值和限制历史条数，使其类似nextweb连续对话下去，不会因为过长的对话导致api费用增加，特别是现在gpt4能上传更多的文字，普通用户没意识到这种行为，因为默认不限制条数，会导致api价格攀升。
还有作者大大我目前还是没有理解那个聊天的时候剩余token的用处是啥。

### 🧐 解决方案

no

**Comment by arvinxx** [comment]
> 就像nextweb一样，可以默认设置好压缩阈值和限制历史条数，使其类似nextweb连续对话下去，不会因为过长的对话导致api费用增加，特别是现在gpt4能上传更多的文字，普通用户没意识到这种行为，因为默认不限制条数，会导致api价格攀升。

这个倒可以变成 LobeChat 的默认设定，比如默认10条上下文这样。

需要设定默认值的话，等待 #913 实现，上一个 PR #1180 已经为此做好铺垫了，实现起来相对容易得

> 还有作者大大我目前还是没有理解那个聊天的时候剩余token的用处是啥。

比如你之前用 4k 上下文的 gpt-3.5，是非常容易用完的，这个是拿来做提示的。我们新版本会改成当前使用量
