### ISSUE TITLE
[Request] 能增加自有模型的请求设置吗 

### ISSUE THREAD

**Issue by anjiacm** [lobehub/lobe-chat#1198]
### 🥰 需求描述

因为使用GPT-4太贵了。我们想用自己拉取的模型完成一些简单业务。能否设置提供呢！比如llama2

### 🧐 解决方案

无

### 📝 补充信息

无

**Comment by arvinxx** [comment]
已在 #1293 实现

**Comment by anjiacm** [comment]
> 已在 #1293 实现

我只能说   牛啊
