### ISSUE TITLE
[Request] 能不能支持OSS对象存储或者R2存储来实现文件的上传和对话

### ISSUE THREAD

**Issue by gaojunyang666** [lobehub/lobe-chat#1202]
### 🥰 需求描述

尊敬的开发者您好，我有以下建议：
1、希望可以上传文件，然后调用GPT-all模型直接处理文件，也或者是可以把一段录音直接上传，然后可以调用wishper-1转换成文字.
2、另外能不能将tts-1模型单独列出来，就是我发一句文字，AI回复一段语音，而不需要对话，只需要这样转换即可。

### 🧐 解决方案

增加对对象存储的支持
支持tts-1的单独调用
感谢开发人员！

**Comment by zhangtony239** [comment]
同求！
