### ISSUE TITLE
[Bug] 使用插件一直要求输入密码

### ISSUE THREAD

**Issue by showifconfig** [lobehub/lobe-chat#1203]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

使用插件一直要求输入密码，输入了也没用。死循环
![image](https://github.com/lobehub/lobe-chat/assets/82651065/e2d5917d-f7ab-4f73-9ceb-693b7edf3b21)

**Comment by arvinxx** [comment]
哪个版本？

**Comment by arvinxx** [comment]
@showifconfig 你是 Docker 部署的么？ docker 部署的会有默认密码

**Comment by showifconfig** [comment]
> @showifconfig 你是 Docker 部署的么？ docker 部署的会有默认密码

是docker部署的，如何去掉默认密码，我看文档未写到

**Comment by arvinxx** [comment]
> 是docker部署的，如何去掉默认密码，我看文档未写到

环境变量里设置 ACCESS_CODE 为空值即可

-e ACCESS_CODE=""

**Comment by showifconfig** [comment]
> > 是docker部署的，如何去掉默认密码，我看文档未写到
> 
> 环境变量里设置 ACCESS_CODE 为空值即可 `-e ACCESS_CODE=""`

谢谢！还想请教一个问题，我所有插件都无法显示图片，是因为我用的不支持吗？我是Azure 3.5 -0613

**Comment by arvinxx** [comment]
> 我所有插件都无法显示图片，是因为我用的不支持吗？

啥意思？

**Comment by showifconfig** [comment]
> > 我所有插件都无法显示图片，是因为我用的不支持吗？
> 
> 啥意思？截个图？

我解决了，谢谢！不用了，提前祝新年快乐！
