### ISSUE TITLE
[Request] 支持 gpt-3.5-turbo-0125

### ISSUE THREAD

**Issue by devyujie** [lobehub/lobe-chat#1208]
### 🥰 需求描述

支持 [gpt-3.5-turbo-0125](https://platform.openai.com/docs/models/gpt-3-5-turbo)

### 🧐 解决方案

支持 [gpt-3.5-turbo-0125](https://platform.openai.com/docs/models/gpt-3-5-turbo)

**Comment by arvinxx** [comment]
在 #1173 支持
