### ISSUE TITLE
【功能需求】根据不同的访问密码统计每日使用的TOKEN数

### ISSUE THREAD

**Issue by yehao1991** [lobehub/lobe-chat#1215]
### 🥰 需求描述

想把lobe-chat部署到本地服务器，但是我们想要根据不同的访问密码统计每日使用的TOKEN数

### 🧐 解决方案

最好是可以把通不通访问密码每日使用的TOKEN数保存到数据库里面，便于查看每日每月的使用情况。

**Comment by arvinxx** [comment]
统计有计划做，但分密码统计不计划支持。自己实现吧
