### ISSUE TITLE
[Bug] 部署时未设置访问密码和API_Key后设置自定义的API_key无法调用插件功能

### ISSUE THREAD

**Issue by ShanySky** [lobehub/lobe-chat#1217]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Edge

### 🐛 Bug Description

我使用docker部署时没有设置访问密码和API-key，通过Edge浏览器打开lobechat并在设置中自定义API-key后可以正常聊天，不过调用插件时会要求输入访问密码或API-key，如下图所示：
![image](https://github.com/lobehub/lobe-chat/assets/61485912/7d593f71-441f-4c7b-ba70-80d460c43ee5)

### 🚦 Expected Behavior

可以直接调用插件

**Comment by arvinxx** [comment]
Docker有默认密码 lobe66

**Comment by ShanySky** [comment]
> Docker有默认密码 lobe66

感谢提醒！刚试了下，在docker部署时如果手动将ACCESS_CODE设置为空时确实就可以了。之前我用0.121.2版本的时候没遇到这个问题。不过，未设置ACCESS_CODE时将ACCESS_CODE当成空会不会更符合部署时的设置直觉？

**Comment by ShanySky** [comment]
对了，其实这里还有另外一个问题：在需要访问密码的情况下，即使单独设置自定义的api-key也无法使用插件。这样的设定符合开发者的预期吗？

**Comment by arvinxx** [comment]
> 在需要访问密码的情况下，即使单独设置自定义的api-key也无法使用插件。这样的设定符合开发者的预期吗？

这个有点问题。因为理论上是只需要填 密码就好了，不应该显示填写 ApiKey。这个应属于界面展示的问题，我会处理下。

新版本要求填写密码的原因 是近期有白帽给我们的反馈：https://github.com/lobehub/lobe-chat/security/advisories/GHSA-pf55-fj96-xf37

简单来说，在 0.122.3 版本及以前，哪怕用户设定了密码，服务端也是能够直接请求插件调用的这个接口，绕过密码访问的。这对于设定了 `PLUIN_SETTINGS` 环境变量的用户来说不安全（例如配置了 搜索引擎的 api key，那么就可能会被盗刷）。

所以我们在 0.122.4 版本修正了这个问题。如果服务端设定了密码，调用插件接口时也需要校验一下密码。

**Comment by arvinxx** [comment]
> 不过，未设置ACCESS_CODE时将ACCESS_CODE当成空会不会更符合部署时的设置直觉？

这个可以优化下

**Comment by ShanySky** [comment]
> > 在需要访问密码的情况下，即使单独设置自定义的api-key也无法使用插件。这样的设定符合开发者的预期吗？
> 
> 这个有点问题。因为理论上是只需要填 密码就好了，不应该显示填写 ApiKey。这个应属于界面展示的问题，我会处理下。
> 
> 新版本要求填写密码的原因 是近期有白帽给我们的反馈：[GHSA-pf55-fj96-xf37](https://github.com/lobehub/lobe-chat/security/advisories/GHSA-pf55-fj96-xf37)
> 
> 简单来说，在 0.122.3 版本及以前，哪怕用户设定了密码，服务端也是能够直接请求插件调用的这个接口，绕过密码访问的。这对于设定了 `PLUIN_SETTINGS` 环境变量的用户来说不安全（例如配置了 搜索引擎的 api key，那么就可能会被盗刷）。
> 
> 所以我们在 0.122.4 版本修正了这个问题。如果服务端设定了密码，调用插件接口时也需要校验一下密码。

是否可以改成：即使服务端设定了密码，客户端如果设置了可用的API-Key也允许使用插件？

**Comment by arvinxx** [comment]
> 客户端如果设置了可用的API-Key也允许使用插件？

可以是可以，但是这里会有风险，因为没法做任何额外的校验。

举个例子，比如你为了自己使用方便，填写了 PluginSettings，把搜索引擎的api key 配置上了。然后其他用户用了你的部署站点，填了自己的 Api Key 以后，就能直接使用你的 搜索引擎的 apikey 来调用搜索插件。

然后过了几天你自己去用的时候，发现这搜索引擎的 apikey 都被刷完了，这样就会有问题。

**Comment by arvinxx** [comment]
可能的方式是如果没有配置 PluginSettings 环境变量，就放开这个校验，允许直接使用，这样就没有风险。

**Comment by ShanySky** [comment]
> 可以是可以，但是这里会有风险，因为没法做任何额外的校验。
> 
> 举个例子，比如你为了自己使用方便，填写了 PluginSettings，把搜索引擎的api key 配置上了。然后其他用户用了你的部署站点，填了自己的 Api Key 以后，就能直接使用你的 搜索引擎的 apikey 来调用搜索插件。
> 
> 然后过了几天你自己去用的时候，发现这搜索引擎的 apikey 都被刷完了，这样就会有问题。

确实会有这个问题。

> 可能的方式是如果没有配置 PluginSettings 环境变量，就放开这个校验，允许直接使用，这样就没有风险。

也只有这个方式是比较合适的了。
