### ISSUE TITLE
[Bug] 部分插件调用时会出现插件网关出错而无法正常调用的问题

### ISSUE THREAD

**Issue by ShanySky** [lobehub/lobe-chat#1218]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Edge

### 🐛 Bug Description
注：使用的版本是 v0.122.8。

部分插件调用时会出现插件网关出错的提示。比如调用当前时间助手时就会出错，其中的detail信息如下：
{
  "stack": "TypeError: fetch failed\n    at node:internal/deps/undici/undici:12344:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async globalThis.fetch (/app/.next/server/chunks/76148.js:1:36428)\n    at async m.callApi (/app/.next/server/app/api/plugin/gateway/route.js:8:101623)\n    at async m.execute (/app/.next/server/app/api/plugin/gateway/route.js:8:101014)\n    at async r (/app/.next/server/app/api/plugin/gateway/route.js:8:97284)\n    at async /app/.next/server/app/api/plugin/gateway/route.js:8:97555\n    at async /app/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484\n    at async eI.execute (/app/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)\n    at async eI.handle (/app/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)"
}

错误截图如下：
![image](https://github.com/lobehub/lobe-chat/assets/61485912/f6670480-3b7b-4b17-a7cc-af8a3004d60c)

### 🚦 Expected Behavior

插件能正常调用

**Comment by shishangx** [comment]
我昨天使用docker方式部署，此问题依旧存在。
