### ISSUE TITLE
希望支持批量导入配置

### ISSUE THREAD

**Issue by SuperDannyBoy** [lobehub/lobe-chat#1221]
### 🥰 需求描述

自定义助手多了之后，无法批量迁移到新的设备，只能逐个导入，效率低。

### 🧐 解决方案

希望支持批量导入多个配置问题

**Comment by Justin3go** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/63507251/cf359f85-9201-4dc2-be5f-a60640ac8350)

这几个功能是不是你需要的呢

**Comment by SuperDannyBoy** [comment]
> ![image](https://private-user-images.githubusercontent.com/63507251/302148274-cf359f85-9201-4dc2-be5f-a60640ac8350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTU4MjAsIm5iZiI6MTcwNzA5NTUyMCwicGF0aCI6Ii82MzUwNzI1MS8zMDIxNDgyNzQtY2YzNTlmODUtOTIwMS00ZGMyLWJlNWYtYTYwNjQwYWM4MzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAxMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NmViODgxNmJhNTg1NmIyMjdhNDEwNmE2ZjFlNTA4YmJmNjNkYzA4NTE5NDc2ZDA2NjhjMmM3ZWM4ZmIwNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ypZlpEwliS4BRYiw9QiY2MWlHYfrWsv_GfKV440mGSs)
> 
> 这几个功能是不是你需要的呢

目前没有批量导入的功能。

**Comment by arvinxx** [comment]
你点导入设置就是批量导入呀
