### ISSUE TITLE
[Request] 请求增加Gemini API KEY的预配置

### ISSUE THREAD

**Issue by LonePheasantWarrior** [lobehub/lobe-chat#1224]
### 🥰 需求描述

目前仅支持OpenAI的ApiKey配置,如果有Gemini的ApiKey和ApiUrl的配置就好了!

### 🧐 解决方案

增加Gemini的ApiKey和ApiUrl环境变量配置

**Comment by arvinxx** [comment]
看文档，有的：https://github.com/lobehub/lobe-chat/blob/main/docs/Deployment/Environment-Variable.zh-CN.md#google-ai

**Comment by ccdanpian** [comment]
@arvinxx 大神，智谱也已经支持了吗？

**Comment by arvinxx** [comment]
@ccdanpian 支持了
