### ISSUE TITLE
[Bug] windows开发环境下的问题， 大小写敏感？

### ISSUE THREAD

**Issue by BonderTam** [lobehub/lobe-chat#1228]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

win11, node 18.19
fork,  git clone,  cd  chat,  pnpm install, pnpm run dev
首次遇到这类型的错误:
![image](https://github.com/lobehub/lobe-chat/assets/249648/4a9a82d7-7636-4f8d-91fd-d3d13adebb2a)

![image](https://github.com/lobehub/lobe-chat/assets/249648/09b1179d-1543-4ed2-8e4c-f1d45b7d1eaa)

![image](https://github.com/lobehub/lobe-chat/assets/249648/288f7d57-442e-4f16-b661-b4e75a74647f)

### 🚦 期望结果

开发环境是否还有其他需求？

**Comment by arvinxx** [comment]
@BonderTam 请给出更具体的场景，这些不足以排查
