### ISSUE TITLE
[Bug] 最新版本 0.123.1 未同步至 Docker Hub

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#1234]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/36695271/49f95b50-8b9b-4c62-b06d-e7d22f17246e)

只更新到 0.123.0，是 Actions 出问题了吗？

**Comment by arvinxx** [comment]
是的 有个bug 我修复下
