### ISSUE TITLE
[Bug] 回复消息展示换行错误

### ISSUE THREAD

**Issue by satlxq** [lobehub/lobe-chat#1241]
### 💻 系统环境

iOS

### 📦 部署环境

Docker

### 🌐 浏览器

Safari

### 🐛 问题描述

https://github.com/lobehub/lobe-chat/assets/2537293/8ff4e90a-4b20-420f-8001-eb14cf4a4f48

如上视频所示，返回消息内的内容列表，第一条展示正常，第二条开始渲染时，就不正常了。

iOS 17.2.1，iPhone 15 pro max。

### 🚦 期望结果

列表展示正常

### 📷 复现步骤

问一个问题：“你会做什么？” 返回列表形式的内容，即可重现问题

### 📝 补充信息

我的设备：Safari ，iOS 17.2.1，iPhone 15 pro max。
使用的lobe-chat版本：LobeChat v0.123.2

**Comment by arvinxx** [comment]
应该已经修复
