### ISSUE TITLE
[Request] 自定义模型 传图 判定与规则

### ISSUE THREAD

**Issue by bbb3n** [lobehub/lobe-chat#1244]
### 🥰 需求描述

![Screenshot_20240206_115006](https://github.com/lobehub/lobe-chat/assets/129975925/4d7d035e-5d32-4479-a6d1-89b118b975d7)

根据测试发现现在 自定义非 OpenAI 的模型名 ，会默认支持 传图与插件

这不太合理，是否支持应该由设置者说了算（既然你们想让有的模型不支持 传图与插件 ）

### 🧐 解决方案

CUSTOM_MODEL 环境变量
通过某种格式，例如
gpt-4-test(1,1)
括号里表示是否开启 传图 和 插件， 1开 0闭

具体如何规范您们开发者考虑，但是强烈建议允许设置这个

**Comment by 1355873789** [comment]
我个人也觉得在`CUSTOM_MODEL`里定义比较方便，但是不建议在`模型名`后面添加，可以在`展示名`后面添加，这样哪怕有错误也不影响使用，顶多就是展示的名称有点问题，出错了也好排查。
如`模型名=展示名(0,0）`

当然为了避免有人喜欢在`展示名`里加括号备注，匹配最后一个括号的内容就行，有设置按设置展示，没设置就默认全开。
如`模型名=展示名（0.001元/K tokens）(0,0）`

--------------------

另外`DIY`的标是不是可以不让展示，反正非DIY的模型名称前都有logo也不难区分，或者统一使用一个表示自定义模型的logo，这样模型列表看起来也会整洁许多，加个`DIY`部署好给不懂的小白用户使用的时候看到`DIY`以为是什么野鸡模型哈哈哈

----------------

还有既然这两个都自定义的话，那模型的最大tokens是否也可以支持自定义，替换掉`DIY`的标识。
基于上面的提议：
第一种建议是用四舍五入的方法让他显示几K。
如:
`模型名=展示名(0,0,4096）`在前端展示名就是`模型名 ...4k`
`模型名=展示名(0,0,16385）`在前端展示名就是`模型名 ...16k`

第二种建议是**n\*1024**或者**n\*1000**的方式，在`CUSTOM_MODEL`里直接自定义nK，那么该模型最大tokens就是**n\*1024**或者**n\*1000**
 `模型名=展示名(0,0,4K）`在前端展示名就是`模型名 ...4k`，最大tokens就是**4\*1024=4096**或者**4\*1000=4000**
 `模型名=展示名(0,0,16K）`在前端展示名就是`模型名 ...16k`，最大tokens就是**16\*1024=16384**或者**16\*1000=16000**

**Comment by arvinxx** [comment]
括号的问题是没法扩展，因为现在其实还有 file ，相当于支持上传文件。如果未来还支持其他模型能力，括号语义就会有问题

**Comment by 1355873789** [comment]
那如果增加环境变量来设置呢，默认全关，给需要开的模型单独设置。毕竟大多数模型只有基础的聊天能力，这样的话也不用填太多
比如在openai的设置下新增类似这种
`CUSTOM_MODELS_VISION`
`CUSTOM_MODELS_FUNCTIONCALL`
`CUSTOM_MODELS_FILE`
`CUSTOM_MODELS_MAXTOKENS`
......
反正我觉得环境变量的设置越往后越臃肿是必然的哈哈哈

**Comment by arvinxx** [comment]
开太多变量不太好，一方面是自定义配置成本高，另外一方面是实现也麻烦，未来维护成本高。

我觉得可能还是用 `CUSTOM_MODELS` 这个变量。我现在想到的语法是考虑用尖括号+属性描述的方式。

```shell
id=displayName<128000:vision:fc:file>
```

尖括号第一个值约定为这个模型的 maxToken 。第二个及以后作为模型的扩展能力，能力与能力之间用冒号 `:` 作为分隔符。

举几个例子：

- `chatglm-6b=ChatGLM 6B<4096>`：ChatGLM 6B，最大上下文 4k，没有高阶能力；
- `spark-v3.5=讯飞星火 v3.5<8192:fc>`：讯飞星火 3.5 模型，最大上下文 8k，支持 Function Call；
- `gemini-pro-vision=Gemini Pro Vision<16000:vision>`：Google 视觉模型，最大上下文 16k，支持图像识别；
- `gpt-4-all=ChatGPT Plus<128000:vision:fc:file>`，hack 的 ChatGPT Plus 网页版，上下 128k ，支持图像识别、Function Call、文件上传

**Comment by 1355873789** [comment]
附议

**Comment by zHElEARN** [comment]
用配置文件呢？json或者yml

**Comment by arvinxx** [comment]
> 用配置文件呢？json或者yml

配置文件其实是比较理想的方案，但我不清楚 怎么在vercel/docker 两种部署模式下都兼容

**Comment by zHElEARN** [comment]
> > 用配置文件呢？json或者yml
> 
> 配置文件其实是比较理想的方案，但我不清楚 怎么在vercel/docker 两种部署模式下都兼容

vercel的话，fork仓库之后直接修改仓库里面的配置文件

docker映射仓库里面的配置文件到主机上的配置文件

不知道这个解决方案怎么样

（目前我自己使用的是docker，verel也不是很清楚）
