### ISSUE TITLE
[Bug] 最新版本 0.123.3 未同步至 Docker Hub

### ISSUE THREAD

**Issue by lengxuange1** [lobehub/lobe-chat#1250]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

docker并未更新最新版本，现在旧版本问答一直未反应，需要更新最新版本

### 🚦 期望结果

更新docker镜像

**Comment by arvinxx** [comment]
<img width="754" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/eb2b03d1-864d-46c3-ae50-32c3678f67b3">

@lengxuange1 发布脚本还在自动执行 https://github.com/lobehub/lobe-chat/actions/workflows/docker.yml 一般要等半小时左右
