### ISSUE TITLE
聊天历史关闭浏览器后就消失了[Bug] 

### ISSUE THREAD

**Issue by kookeg** [lobehub/lobe-chat#1256]
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

聊天历史关闭浏览器后就消失了，有没有保留聊天历史的设置呢

**Comment by arvinxx** [comment]
默认是保留历史的。你要看看是不是同一个域名，以及磁盘空间是否充足

**Comment by kookeg** [comment]
换浏览器就没有了

**Comment by kookeg** [comment]
能设置吗，保留功能

**Comment by kookeg** [comment]
保留会话历史

**Comment by arvinxx** [comment]
> 换浏览器就没有了

换浏览器没有是正常的。
