### ISSUE TITLE
[Request] 希望所有模型服务商都能配置接口代理

### ISSUE THREAD

**Issue by skywolf123** [lobehub/lobe-chat#1258]
### 🥰 需求描述

希望所有模型服务商都能配置接口代理，就像openai的OPENAI_PROXY_URL一样

### 🧐 解决方案

每个模型服务商都可以单独配置对应的PROXY_URL

**Comment by arvinxx** [comment]
给我个理由为什么每个都需要

**Comment by skywolf123** [comment]
有些代理服务商仅支持部分模型，需要使用几个不同的代理服务商的地址

**Comment by skywolf123** [comment]
有些代理服务商仅支持部分模型，需要使用几个不同的代理服务商的地址

**Comment by arvinxx** [comment]
> 有些代理服务商仅支持部分模型，需要使用几个不同的代理服务商的地址

那你这个需求不是用每个 provider 加代理地址解决的。而是需要支持添加多个自定义 provider

**Comment by chenweiask** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > Some proxy service providers only support some models, and you need to use the addresses of several different proxy service providers
> 
> Then your need cannot be solved by adding a proxy address to each provider. Instead, you need to support adding multiple custom providers

I think the request is valid. For example, I'm using both ChatGPT and Gemini. Neither of the two could directly access from China. I have to create proxy for them, but the API addresses are different. In current case, I can only use ChatGPT, and very slow and unstable for Gemini.

**Comment by cy948** [comment]
试试部署[OneApi](https://github.com/songquanpeng/one-api)，把其他服务商聚合到一个代理。OneApi会根据不同的channel支持的模型去匹配服务商。

**Comment by arvinxx** [comment]
目前已经支持 `GOOGLE_PROXY_URL` 、 `ANTHROPIC_PROXY_URL`  等常用 provider 的 proxy ，对哪个 provider 有需要再单独提 issue吧，这个关闭了。
