### ISSUE TITLE
[Bug]ERR_JWT_EXPIRED

### ISSUE THREAD

**Issue by evilchris** [lobehub/lobe-chat#1264]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

{
  "error": {
    "code": "ERR_JWT_EXPIRED",
    "name": "h",
    "claim": "exp",
    "reason": "check_failed"
  },
  "provider": "openai"
}

**Comment by arvinxx** [comment]
it doesn't trigger with web. please add more info

**Comment by evilchris** [comment]
It due to the system time of Nginx server

**Comment by uson1x** [comment]
Hi @evilchris 

Sorry for bringing this up again. We are encountering the same issue on one of the computers which is trying to access Lobe Chat.

Just curious, the way you got it fixed is just by setting the right system time on the reverse-proxy nginx server you are using?

We used Vercel to deploy  and I believe, there is no nginx involved in Vercel deployment.
But maybe that one computer has the system time set wrong – I'll check.

**Comment by uson1x** [comment]
Wow, that actually helped. There was 2 minute difference due to turned off time synchronisation. Now it works!
