### ISSUE TITLE
[Bug] 输入密码问题

### ISSUE THREAD

**Issue by lzj0627** [lobehub/lobe-chat#1266]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

使用中文输入法 输入密码的时候输出框内容感觉有点奇怪
![image](https://github.com/lobehub/lobe-chat/assets/80609312/be4c7cf8-a505-4b83-aae3-7fec0de1aeca)
做任何操作的时候都会追加内容
![image](https://github.com/lobehub/lobe-chat/assets/80609312/8edd008b-ef87-48d7-a529-58e0d5bc7f3b)

### 📝 补充信息

不知道是不是个bug ，是的话建议可以优化一下
版本 v0.124.2

**Comment by arvinxx** [comment]
不要用中文就好了。哪有输密码的时候还开启输入法的…

**Comment by lzj0627** [comment]
> 不要用中文就好了。哪有输密码的时候还开启输入法的…

嗯，正常情况下是这样的，只是偶然间切到了中文，然后切换回英文的时候发现内容越来越多了

**Comment by arvinxx** [comment]
这个有点太 edge case 了，不计划考虑
