### ISSUE TITLE
[Bug] 助手名称、描述或者话题名称等“智能生成命名”的能力似乎仅使用openai的模型

### ISSUE THREAD

**Issue by jameszhanghkmci** [lobehub/lobe-chat#1276]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

助手名称、描述或者话题名称等“智能生成命名”的能力似乎仅使用openai的模型，我配置了gemini pro模型但是无法正常生成“智能重命名”有关内容

### 🚦 期望结果

使用当前助手配置中的模型来进行生成工作

### 📷 复现步骤

配置一个错误的openai api key，同时配置一个正确的Google Gemini Pro API KEY，且配置当前助手使用gemini pro模型，可以发现智能生成助手信息或者话题信息的能力无法工作

**Comment by MEIZU16** [comment]
我配置了openai的模型（未使用Azure），对话中可以正常使用，但是智能重命名却提示：
**Proxy error (HTTP 402 No Keys Available)**The proxy encountered an error while trying to send your prompt to the upstream service. Further technical details are provided below.****No keys available for model family 'azure-turbo'.*```{  "error": {    "message": "No keys available for model family 'azure-turbo'.",    "type": "proxy_no_keys_available"  }}```

**Comment by hitzhangjie** [comment]
Hope this feature could be supported

**Comment by chuangbo** [comment]
I also encountered this issue. I hoped to only one local Ollama model to seamless use Lobechat, but unfortunately, the 'Smart Renaming' feature currently requires the use of OpenAI, which presents some inconvenience.

**Comment by delicacyyy** [comment]
There appears to be an issue with the translation function. Regardless of the model settings I choose, it seems to consistently default to the "gpt-3.5-turbo" model.
![image](https://github.com/lobehub/lobe-chat/assets/11476249/a486d141-be68-4837-90ca-b14b3281476c)

**Comment by zyfyy** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/1721417/a2030087-4b3f-4efb-863e-d5450faf8aa2)
error message display as the auto renamed title.

**Comment by arvinxx** [comment]
@zyfyy upgrade to latest version
