### ISSUE TITLE
[Request] Local LLM SUPPORT

### ISSUE THREAD

**Issue by alfi4000** [lobehub/lobe-chat#1281]
### 🥰 Feature Description

Make it possible to enter url and api url api key to use local llms!

### 🧐 Proposed Solution

Make it possible to enter url and api url api key to use local llms!

**Comment by arvinxx** [comment]
please wait the #1265 , we will merge it soon.

**Comment by alfi4000** [comment]
oh ok

**Comment by alfi4000** [comment]
just a screenshot from autogen studio like the it would be great! just a thought!
<img width="1477" alt="297306307-eb8980ae-6241-4fb4-83bf-d904688cca81" src="https://github.com/lobehub/lobe-chat/assets/149228038/d1a98026-3584-421b-915d-42f5bfec44f4">

**Comment by alfi4000** [comment]
Will Local LLM for text to image also coming soon or just normal LLM support?

**Comment by arvinxx** [comment]
@alfi4000 It depends on Local LLM provider (like Ollama). If they can support text-to-image, we can also support in LobeChat

**Comment by arvinxx** [comment]
> just a screenshot from autogen studio like the it would be great! just a thought!

Thanks for your reference~ 😄 we will consider it later

**Comment by alfi4000** [comment]
> @alfi4000 It depends on Local LLM provider (like Ollama). If they can support text-to-image, we can also support in LobeChat

You might consider not ollama for text to image! Invokeai or a different tool that provides api maybe I am not sure if ollama supports text to image, I don't think so!

**Comment by alfi4000** [comment]
Ollama got an update you might not longer need to implement Local LLM because now it supports OpenAI compatible api !

https://youtu.be/38jlvmBdBrU?si=iJOyesu9bD3NnYDt
