### ISSUE TITLE
[Request] 发行桌面版及移动版

### ISSUE THREAD

**Issue by NebulaTechs** [lobehub/lobe-chat#1282]
### 🥰 需求描述

部署版本使用较为繁琐，建议发行可执行版本

### 🧐 解决方案

发行可执行版本

**Comment by arvinxx** [comment]
桌面版有在今年的计划中。敬请期待

**Comment by arvinxx** [comment]
桌面端在 #2024 跟进，移动端今年暂不考虑。先关闭了
