### ISSUE TITLE
[Bug] 使用插件时token计算问题

### ISSUE THREAD

**Issue by cyx1322** [lobehub/lobe-chat#1285]
### 💻 Operating System

macOS

### 📦 Environment

Docker

### 🌐 Browser

Safari

### 🐛 Bug Description

<img width="378" alt="image" src="https://github.com/lobehub/lobe-chat/assets/81369393/d45fc90f-16aa-4a27-a945-cdcd78a7d8f1">

如图，在支持function call的模型中，选择了一个插件。
在切换到不支持function call的模型之后，插件按钮变灰，后台能看到对应的prompt会被清除。
**但token count仍然包括插件的部分。**
<img width="403" alt="截屏2024-02-11 12 05 23" src="https://github.com/lobehub/lobe-chat/assets/81369393/01acb64b-dd44-4876-9832-39ec9209cc2a">

**Comment by arvinxx** [comment]
哦 的确，这块的处理漏掉了，我修正下
