### ISSUE TITLE
[Bug] Model hosted in AWS Bedrock returns 474 error code when the request is made from Vercel

### ISSUE THREAD

**Issue by gijigae** [lobehub/lobe-chat#1294]
### 💻 Operating System

macOS

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

For the AWS Bedrock (Claude 2.1), when a request is sent from Vercel deployment, the server returns the 474 error (it indicates the client sent a HTTP request in plain text to HTTPs service port) whereas a request to AWS Bedrock works flawlessly from a local environment.

![image](https://github.com/lobehub/lobe-chat/assets/81459/1a5f8bd9-ac60-4cd5-be96-517e55f9c596)

### 🚦 Expected Behavior

Model hosted in AWS Bedrock should return appropriate messages.

### 📷 Recurrence Steps

Set a model hosted in AWS Bedrock and send a request

**Comment by gijigae** [comment]
It looks like the issue only occurs from Arc Browser. Tested Claude 2.1 from Chrome and Edge browsers and they all work fine.

**Comment by arvinxx** [comment]
So I close it.
