### ISSUE TITLE
[Bug] gpt-4-all上传PDF报错。识别成图片？

### ISSUE THREAD

**Issue by DAQINCHA** [lobehub/lobe-chat#1302]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Safari

### 🐛 问题描述

<img width="755" alt="Screenshot 2024-02-14 at 7 40 29 PM" src="https://github.com/lobehub/lobe-chat/assets/121076223/b3f4645b-6d39-47e1-9090-5ef3acd125c2">
用gpt-4-all模型上传PDF文件后，报错。请问是什么原因呢？看样子好像是识别成了图片？
（因为用vision的时候，只能选择上传图片，pdf是选不了的，而gpt-4-all则可以选择pdf，所以应该不是模型问题吧？）
{
  "error": {
    "message": "fail to decode image config(webp): C.WebPGetFeatures: failed (request id: 2024021411010998425291LDOJ9MZP)",
    "type": "new_api_error",
    "param": "",
    "code": "count_token_messages_failed"
  },
  "provider": "openai",
  "endpoint": "https://ngedlktfticp.cloud.se****os.io/v1"
}

### 📷 复现步骤

选用gpt-4-all模型，上传pdf时就会出现。

**Comment by arvinxx** [comment]
是你的服务商问题。https://github.com/lobehub/lobe-chat/discussions/933
