### ISSUE TITLE
[Bug] 根据教程设置子目录路径 ENV NEXT_PUBLIC_BASE_PATH，重新构建生成docker镜像运行不成功。

### ISSUE THREAD

**Issue by koulas** [lobehub/lobe-chat#1303]
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

根据教程设置子目录路径 ENV NEXT_PUBLIC_BASE_PATH，重新构建生成docker镜像运行不成功。
访问页面显示js加载报错
![7a3651705c7bda42a9a8ad5b19be072](https://github.com/lobehub/lobe-chat/assets/2045443/994ad756-5813-4ad9-8b32-4386530d2773)

**Comment by luojiyin1987** [comment]
@koulas   麻烦提供 docker 运行命令 或者完整的 docker compose 配置文件。

**Comment by koulas** [comment]
> @koulas 麻烦提供 docker 运行命令 或者完整的 docker compose 配置文件。

是使用这个Dockerfile 生成镜像：
```
FROM node:20-slim AS base

## Sharp dependencies, copy all the files for production
FROM base AS sharp
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

RUN pnpm add sharp

## Install dependencies only when needed
FROM base AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY package.json ./

# If you want to build docker in China
# RUN npm config set registry https://registry.npmmirror.com/
RUN pnpm i

COPY . .
RUN pnpm run build:docker # run build standalone for docker version

## Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=sharp --chown=nextjs:nodejs /app/node_modules/.pnpm ./node_modules/.pnpm

USER nextjs

EXPOSE 3210

# set hostname to localhost
ENV HOSTNAME "0.0.0.0"
ENV PORT=3210

# General Variables
ENV ACCESS_CODE ""
ENV CUSTOM_MODELS ""
ENV NEXT_PUBLIC_BASE_PATH=/hub

# OpenAI
ENV OPENAI_API_KEY "sk-"
ENV OPENAI_PROXY_URL ""

# Azure OpenAI
ENV USE_AZURE_OPENAI ""
ENV AZURE_API_KEY ""
ENV AZURE_API_VERSION ""

# Google
ENV GOOGLE_API_KEY ""

# Zhipu
ENV ZHIPU_API_KEY ""

# Moonshot
ENV MOONSHOT_API_KEY ""

# Ollama
ENV OLLAMA_PROXY_URL ""
CMD ["node", "server.js"]
```
执行这个命令来运行镜像
docker run -p 3210:3210 my-lobe-app:v128

**Comment by luojiyin1987** [comment]
```shell
# If you want to build docker in China
# RUN npm config set registry https://registry.npmmirror.com/
````
应该改成 
```shell
RUN pnpm config set registry https://registry.npmmirror.com/
```
我测试了 
```shell
RUN npm config set registry https://registry.npmmirror.com/
```
是不生效的， 还是用官方的源的，而不是阿里的源。 @canisminor1990   ，我晚点时间再提pr。


@koulas  我没设置 NEXT_PUBLIC_BASE_PATH 变量，不知道你的意图是什么。  我的是可以正常运行的。

**Comment by luojiyin1987** [comment]
在Next.js中，`NEXT_PUBLIC_BASE_PATH` 是一个环境变量，用于设置应用的基础路径（base path）。这个基础路径会应用于所有的页面、静态资源和API路由。这在你的Next.js应用部署在非根URL下时特别有用，比如当你的应用是在一个子路径下运行，而不是域名的根路径。

例如，如果你的Next.js应用托管在 `https://www.example.com/myapp/`，其中 `/myapp/` 是基础路径，你可以使用 `NEXT_PUBLIC_BASE_PATH` 环境变量来设置这个路径。这样，Next.js会在内部为所有的页面和资源生成正确的路径。

使用环境变量的好处是你可以在不同的环境（如开发、测试、生产）中设置不同的值，而无需更改代码。`NEXT_PUBLIC_` 前缀是Next.js用来确定哪些环境变量应该在客户端暴露的方式。只有以 `NEXT_PUBLIC_` 开头的环境变量才会被嵌入到客户端的JavaScript包中，并且在浏览器中可用。

如何使用：

1. 在你的 `.env.local` 文件或者其他环境变量配置文件中设置 `NEXT_PUBLIC_BASE_PATH`：

```env
NEXT_PUBLIC_BASE_PATH=/myapp
```

2. 在Next.js配置文件 `next.config.js` 中使用这个环境变量来设置 `basePath`：

```javascript
module.exports = {
  basePath: process.env.NEXT_PUBLIC_BASE_PATH,
};
```

3. 在你的应用中，Next.js会自动使用这个 `basePath` 来处理所有的路由和资源链接。

例如，如果你有一个图片文件位于 `/public/images/logo.png`，你通常会这样引用它：

```jsx
<img src="/images/logo.png" alt="logo" />
```

但如果你设置了基础路径 `/myapp`，Next.js会自动处理这个路径，实际上引用的是：

```jsx
<img src="/myapp/images/logo.png" alt="logo" />
```

确保在部署你的应用时正确设置了这个环境变量，以便你的应用能够正确地加载所有的资源和导航到页面。

**Comment by arvinxx** [comment]
你设定的这个变量位置不对。应该在builder那边的

**Comment by luojiyin1987** [comment]
> 你设定的这个变量位置不对。应该在builder那边的

你的意思是   NEXT_PUBLIC_BASE_PATH 这个变量值应该在  
```shell
  ## Install dependencies only when needed
 FROM base AS builder
 ENV PNPM_HOME="/pnpm"
 ENV PATH="$PNPM_HOME:$PATH"
 RUN corepack enable
```
之前？  @arvinxx

**Comment by luojiyin1987** [comment]
`NEXT_PUBLIC_BASE_PATH`  这个变量确实应该在   `RUN pnpm run build:docker`  之前。build:docker 对应 package.json 中的 `DOCKER=true next build`  脚本命令 。 @arvinxx

**Comment by koulas** [comment]
> `NEXT_PUBLIC_BASE_PATH` 这个变量确实应该在 `RUN pnpm run build:docker` 之前。build:docker 对应 package.json 中的 `DOCKER=true next build` 脚本命令 。 @arvinxx

那么是修改成这样吗？

``
FROM node:20-slim AS base

## Sharp dependencies, copy all the files for production
FROM base AS sharp
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

RUN pnpm add sharp

## Install dependencies only when needed
FROM base AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NEXT_PUBLIC_BASE_PATH=/hub
RUN corepack enable

WORKDIR /app

COPY package.json ./

# If you want to build docker in China
# RUN npm config set registry https://registry.npmmirror.com/
RUN pnpm i

COPY . .
RUN pnpm run build:docker # run build standalone for docker version

## Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=sharp --chown=nextjs:nodejs /app/node_modules/.pnpm ./node_modules/.pnpm

USER nextjs

EXPOSE 3210

# set hostname to localhost
ENV HOSTNAME "0.0.0.0"
ENV PORT=3210

# General Variables
ENV ACCESS_CODE ""
ENV CUSTOM_MODELS ""


# OpenAI
ENV OPENAI_API_KEY "sk-"
ENV OPENAI_PROXY_URL ""

# Azure OpenAI
ENV USE_AZURE_OPENAI ""
ENV AZURE_API_KEY ""
ENV AZURE_API_VERSION ""

# Google
ENV GOOGLE_API_KEY ""

# Zhipu
ENV ZHIPU_API_KEY ""

# Moonshot
ENV MOONSHOT_API_KEY ""

# Ollama
ENV OLLAMA_PROXY_URL ""
CMD ["node", "server.js"]
``
