### ISSUE TITLE
[Request] 支持 Azure OpenAI

### ISSUE THREAD

**Issue by libli** [lobehub/lobe-chat#131]
### 🥰 需求描述 | Feature Description

希望支持azure openai。它也支持function call。而且申请及支付azure的账号更容易。

### 🧐 解决方案 | Proposed Solution

`curl "ENDPOINT/openai/deployments/MODELNAME/chat/completions?api-version=2023-07-01-preview" \
  -H "Content-Type: application/json" \
  -H "api-key: YOUR_API_KEY" \
  -d "{
  \"messages\": [],
  \"max_tokens\": 800,
  \"temperature\": 0.7,
  \"frequency_penalty\": 0,
  \"presence_penalty\": 0,
  \"top_p\": 0.95,
  \"stop\": null
}"`

调用方式如上，需要提供一个ENDPOINT url、自定义的MODELNAME、api-key。

**Comment by arvinxx** [comment]
试试配置 OPENAI_PROXY_URL 这个环境变量行不行？

**Comment by libli** [comment]
azure的鉴权是在header中的api-key这个值。

**Comment by libli** [comment]
可以支持两个header看看。同时设置bearer token和api-key。

**Comment by arvinxx** [comment]
ok，我加下
