### ISSUE TITLE
[Bug] 单点登录强制下线后仍然可以使用，限制多设备同时登录无法实现。

### ISSUE THREAD

**Issue by wyl2003** [lobehub/lobe-chat#1311]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

启用单点登录，并使用国内的Authing替代Auth0进行验证，登录过程一切正常。在Authing后台强制用户下线之后，浏览器打开登录界面确认已经下线后，lobechat仍然可以正常聊天，没有被下线。

### 🚦 期望结果

希望在强制下线之后可以正常退出登录，解决此问题之后同时可以实现限制多设备同时登录的功能。

### 📷 复现步骤

启用单点登录，环境变量正确设置身份验证服务。
身份验证服务注册账号，并在lobechat登录。
在身份验证服务后台强制下线当前登录的账号，或者开启设备互斥之后登录第二台设备。
确认身份验证平台已经退出登录，回到lobechat聊天，发现任然可以使用，此时漏洞复现。

### 📝 补充信息

无

**Comment by arvinxx** [comment]
@CloudPassenger 麻烦看下这个问题？

**Comment by cy948** [comment]
请尝试：
1. 请复现以下问题并打印一下该位置`session`的值：https://github.com/lobehub/lobe-chat/blob/961a0074335f7b4882bc64e6ce70bbe02e7619c5/src/middleware.ts#L16
2. 如果您对代码作了更改以适配Authing，请提供更改处的代码片段。

**Comment by wyl2003** [comment]
@cy948 感谢你关注这个问题。
但是很抱歉，我并没有在本地部署调试环境来运行此项目，我所做的只是把项目部署到Vercel。或者可能有什么我不了解的在Vercel获取到```session```值的方法，请告知我，我可以提供。
此外我可以提供一下Authing的配置和环境变量的细节。
- OIDC配置  *OIDC协议在Authing里似乎无法关闭，但是可以选择默认协议。经过测试默认协议选择OIDC协议或OAuth2.0协议都存在该漏洞，可能存在不兼容*
<img width="1041" alt="image" src="https://github.com/lobehub/lobe-chat/assets/108109393/89f70ba1-4114-429f-9c2a-4fd2cf07b1c9">  
   
- OAuth 2.0配置
<img width="1016" alt="image" src="https://github.com/lobehub/lobe-chat/assets/108109393/0393af0d-e604-47cd-ae52-57d53ebb5821">  
   
- 环境变量配置 截图中三项分别对应```AUTH0_CLIENT_ID```,```AUTH0_CLIENT_SECRET```,```AUTH0_ISSUER```.
<img width="204" alt="image" src="https://github.com/lobehub/lobe-chat/assets/108109393/8056fd8d-9b72-47d4-997d-bcfcbaab8c4b">

**Comment by cy948** [comment]
> @cy948 感谢你关注这个问题。 但是很抱歉，我并没有在本地部署调试环境来运行此项目，我所做的只是把项目部署到Vercel。或者可能有什么我不了解的在Vercel获取到`session`值的方法，请告知我，我可以提供。 此外我可以提供一下Authing的配置和环境变量的细节。
> 
> * OIDC配置  _OIDC协议在Authing里似乎无法关闭，但是可以选择默认协议。经过测试默认协议选择OIDC协议或OAuth2.0协议都存在该漏洞，可能存在不兼容_
> 
> <img alt="image" width="1041" src="https://private-user-images.githubusercontent.com/108109393/305995028-89f70ba1-4114-429f-9c2a-4fd2cf07b1c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTcwNDksIm5iZiI6MTcwODM1Njc0OSwicGF0aCI6Ii8xMDgxMDkzOTMvMzA1OTk1MDI4LTg5ZjcwYmExLTQxMTQtNDI5Zi05YzJhLTRmZDJjZjA3YjFjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxNTMyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTE5YzYyZDZkYjQwN2ZkNmY5YTVmM2EyZTU5ZTk0YjVhMTcxMzM4Mjg2ZGI5ODQ4NGI0NTAzODQzODg3NjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P2k05b41oohakz8jsSv-EpBsttEgEMenOjMd91gdops">
> * OAuth 2.0配置
> 
> <img alt="image" width="1016" src="https://private-user-images.githubusercontent.com/108109393/305998421-0393af0d-e604-47cd-ae52-57d53ebb5821.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTcwNDksIm5iZiI6MTcwODM1Njc0OSwicGF0aCI6Ii8xMDgxMDkzOTMvMzA1OTk4NDIxLTAzOTNhZjBkLWU2MDQtNDdjZC1hZTUyLTU3ZDUzZWJiNTgyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxNTMyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmU1MWJjMTY2MmNmNGUxMzZiYjk2ZmM5Mzk4YWY1MzI1NTUxZDI0ZjA3ZWRkYWVmZDczMjExZDRhMjA2YWU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j8uNYZcSlJJIsOdm_9sz4C5tLOTWbvjcFblRwAnHH1Q">
> * 环境变量配置 截图中三项分别对应`AUTH0_CLIENT_ID`,`AUTH0_CLIENT_SECRET`,`AUTH0_ISSUER`.
> 
> <img alt="image" width="204" src="https://private-user-images.githubusercontent.com/108109393/305998733-8056fd8d-9b72-47d4-997d-bcfcbaab8c4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTcwNDksIm5iZiI6MTcwODM1Njc0OSwicGF0aCI6Ii8xMDgxMDkzOTMvMzA1OTk4NzMzLTgwNTZmZDhkLTliNzItNDdkNC05OTdkLWJjZmNiYWFiOGM0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxNTMyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGNlNmExOGFkMjc0YTg3NWQxM2FjZmViZjFhNjhmYTZhOWIwMDlmNzY1YTUxYzRjY2Y0MDNhYjkzMDIwNDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Ddd2n35buXRzsAhtuPziYtHEwM7Cd1iYfMkT3Z-1V4">

您需要先Fork一下项目，再拉取到本地进行测试，并查看控制台的输出。

**Comment by cy948** [comment]
问了一下Chatgpt：[强制下线需要用到id Token](https://shareg.pt/N5nyCO9)，然而默认的Auth0 Provider只要求返回`code`。
 ![image](https://github.com/lobehub/lobe-chat/assets/67412196/5ab1627c-afed-4e3f-952d-6c29756de1ba)。您可能要自定义一个[Provider](https://authjs.dev/guides/providers/custom-provider)，或者看看社区是否存在已经实现的“authing.cn” Provider。

**Comment by arvinxx** [comment]
如此来看，这个应该不算 Auth0 实现的 Bug ，是没有官方支持 Authing 所使用的 OIDC 导致的。而目前所有 hackable 使用的行为都不在我们维护的范围内，这个 issue 先关了。如果有需求，建议提 支持 Authing 的 issue 或者 PR。
