### ISSUE TITLE
[Request] Add a way to configure the detail API option for vision models.

### ISSUE THREAD

**Issue by ghost** [lobehub/lobe-chat#1312]
### 🥰 Feature Description

Hi! Thanks for creating Lobe, it's a really good frontend. My feature request is pretty simple - I want to be able to choose the "detail" parameter that is used for the gpt-4-vision-preview model (https://platform.openai.com/docs/guides/vision/low-or-high-fidelity-image-understanding):

Currently it's hard-coded to "auto" here - https://github.com/lobehub/lobe-chat/blob/main/src/services/chat.ts#L152

I want to be able to choose "high" for the model to always process images in high quality. Is it possible to add this as an option to the model configuration settings?

Thanks in advance!

### 🧐 Proposed Solution

Add an option to change the "detail" option for vision models in "Model settings" of an agent.

**Comment by arvinxx** [comment]
duplicate of https://github.com/lobehub/lobe-chat/issues/755
