### ISSUE TITLE
[Request] GOOGLE_PROXY_URL Support

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#1313]
### 🥰 需求描述

如题，希望能够支持 Google proxy url 这个配置项，以实现透明代理/国产代理。

### 🧐 解决方案

Same as OPENAI_PROXY_URL.

**Comment by arvinxx** [comment]
目前 Google 官方的 SDK 暂时还没支持 baseURL，所以我没法在 LobeChat 里实现。可以去催催他们官方： https://github.com/google/generative-ai-js/issues/25
