### ISSUE TITLE
[Bug] no reply

### ISSUE THREAD

**Issue by MasticoreChen** [lobehub/lobe-chat#1322]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

通过vercel和sealos部署，已设置好接口代理、API key，通过web访问登陆后，提出任何问题，回复都是空，用相同设置部署的nextchat则正常
更换电脑和浏览器均出现该问题，版本为：LobeChat v0.128.5

![Capture](https://github.com/lobehub/lobe-chat/assets/87356961/3a596902-4eb0-4bf5-b8c7-69f98162cc9f)

### 🚦 期望结果

解决问题

### 📷 复现步骤

通过vercel和sealos部署
输入代理接口地址、apikey pass code
通过web访问，并按提示输入密码登陆
用任何模型，输入任何文字，回复都为空

**Comment by zrjcoder** [comment]
same error

**Comment by arvinxx** [comment]
https://chat-docs.lobehub.com/zh/self-hosting/faq/no-v1-suffix

**Comment by MasticoreChen** [comment]
我在Vercel 设置OPENAI_PROXY_URL后，返回值是空白，但将相同url填写到设置页面中，恢复正常，是哪里设置问题？
![image](https://github.com/lobehub/lobe-chat/assets/87356961/2a828519-48bf-4449-923a-965e6ec9be15)

![image](https://github.com/lobehub/lobe-chat/assets/87356961/56e5bdd5-a6f6-453f-8543-5157fa080f4a)

**Comment by arvinxx** [comment]
这个之前没遇到过哎，你要不 Discord 上私戳我帮你看看
