### ISSUE TITLE
[Bug] Vercel一键部署失败

### ISSUE THREAD

**Issue by SpencerLaw** [lobehub/lobe-chat#1327]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/13880081/30a69598-123e-4897-9cf5-c0c5efe5a7be)

**Comment by arvinxx** [comment]
再试试
