### ISSUE TITLE
[Bug] 使用搜索引擎插件，搜索已完成，但是骨架屏没有消失

### ISSUE THREAD

**Issue by leeyiding** [lobehub/lobe-chat#133]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/49098278/ae3f9925-1d74-4890-ae0a-92fa70bd71db)
按照正常流程，搜索已经完成了，下面这块骨架屏应该需要消失了吧，这么大一块挺占位置的。

**Comment by arvinxx** [comment]
正常是这样的：
<img width="1053" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/c7cc6acc-775d-4644-8d80-91ee1b9a4be5">

感觉是你这边前端渲染没正常显示出来，可以把 console 的报错贴一下吗

**Comment by leeyiding** [comment]
可能是偶然出现的bug，之前试了三四次都是这样，刚才测试了两次又突然正常了。等之后再复现后再反馈
