### ISSUE TITLE
[Bug] 封装docker报错

### ISSUE THREAD

**Issue by BQQQQB** [lobehub/lobe-chat#1330]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

<img width="632" alt="1708398939844_195E1CBB-859C-44f1-BD5E-453FED15DF02" src="https://github.com/lobehub/lobe-chat/assets/92673213/6324d44d-f83f-40b7-9a39-02d87573dc28">

### 🚦 期望结果

为什么一直报错
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@auth/core@workspace:*" is in the dependencies but no package named "@auth/core" is present in the workspace

This error happened while installing the dependencies of next-auth@5.0.0-beta.12

Packages found in the workspace: 
The command '/bin/sh -c pnpm i' returned a non-zero code: 1

**Comment by cy948** [comment]
已在 #1323 修复
