### ISSUE TITLE
请问下本地知识库这个功能什么时候增加呢

### ISSUE THREAD

**Issue by scortLi** [lobehub/lobe-chat#1342]
### 🥰 需求描述

我这么有本地知识库的需求什么时候增加呢？

### 🧐 解决方案

我这么有本地知识库的需求什么时候增加呢？

**Comment by arvinxx** [comment]
快的话下个月，慢的话4月

**Comment by luojiyin1987** [comment]
> 快的话下个月，慢的话4月

有具体的 issue 或者pr？ 想参与。

**Comment by arvinxx** [comment]
@luojiyin1987 暂时还没写RFC，等我写完到时候 at 你~

**Comment by scortLi** [comment]
@arvinxx 好的谢谢

**Comment by scortLi** [comment]
@arvinxx 你好，本地知识库如果实现了麻烦艾特一下我可以吗

**Comment by arvinxx** [comment]
@scortLi 好

**Comment by XiaolongYang-HZAU** [comment]
期待

**Comment by arvinxx** [comment]
@scortLi 还没有哈，应该 6 月份能上吧

**Comment by liuzj288** [comment]
> @scortLi 还没有哈，应该 6 月份能上吧

知识库进度如何了呀，另外长文档解读功能有实现方案吗？感觉智谱清言这样直接分开的方案不是很好

![image](https://github.com/lobehub/lobe-chat/assets/13833404/3d39df2c-0327-4481-a893-1ffddb5c987b)

**Comment by arvinxx** [comment]
@liuzj288 

![image](https://github.com/lobehub/lobe-chat/assets/28616219/58cfe192-4cdb-4b9b-b464-bfc061176dc2)

**Comment by guling-io** [comment]
期待
