### ISSUE TITLE
[Bug] 一直报这个错

### ISSUE THREAD

**Issue by BQQQQB** [lobehub/lobe-chat#1344]
### 💻 Operating System

Ubuntu

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description
```shell
2024/02/21 16:56:48 [error] 221168#221168: *701 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 61.48.41.22, server: aiex.mosslab.hqmoss.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:3210/favicon.ico", host: "aiex.mosslab.hqmoss.com", referrer: "https://aiex.mosslab.hqmoss.com/"
2024/02/21 16:56:49 [error] 221168#221168: *701 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 61.48.41.22, server: aiex.mosslab.hqmoss.com, request: "GET /sw.js HTTP/1.1", upstream: "http://127.0.0.1:3210/sw.js", host: "aiex.mosslab.hqmoss.com", referrer: "https://aiex.mosslab.hqmoss.com/sw.js"
```

### 🚦 Expected Behavior

老师，我用的openresty代理nginx，但是一直出现这个错误，什么原因

**Comment by BQQQQB** [comment]
对的

**Comment by cy948** [comment]
> 对的
> 

方便提供一下您的反向代理的配置吗？

**Comment by BQQQQB** [comment]
我的这个openresty的代理主要是获取docker的响应信息

**Comment by BQQQQB** [comment]
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  logs/access.log  main;


    # client_body_in_file_only off;


    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    gzip  on;

    upstream sd_service{
        server 127.0.0.1:7862; # 这里是后端服务1的IP和端口
        # 可以添加多个后端服务器，Nginx会根据配置的策略进行负载均衡
    }

    upstream comfyui_srevice{
        server 127.0.0.1:8188; # 这里是后端服务2的IP和端口
    }

    upstream face_srevice{
        server 127.0.0.1:7863; # 这里是后端服务2的IP和端口
    }

    upstream jupyter_srevice{
        server 127.0.0.1:7863; # 这里是后端服务2的IP和端口
    }

    # HTTPS server
    #
    server {
        listen       443 ssl;
        server_name  aiex.mosslab.com;

	#SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
        ssl_certificate      /etc/openresty/ssl/aiex.mosslab..com.pem;
        ssl_certificate_key  /etc/openresty/ssl/aiex.mosslab..com.key;
	ssl_session_cache shared:SSL:1m;
	ssl_session_timeout 5m;
	#TLS协议版本越高，HTTPS通信的安全性越高，但是相较于低版本TLS协议，高版本TLS协议对浏览器的兼容性较差。
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
	ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;


        #ssl_prefer_server_ciphers  on;
	location /sd/ {
            proxy_pass http://127.0.0.1:7862; # 请求/service1/路径的请求会被转发到8080端口的服务
	    access_log  /var/log/openresty/aiex.mosslab..com.sd.access.log  main;
        }

	location /jupyter/ {
            proxy_pass http://jupyter_srevice; # 请求/service1/路径的请求会被转发到8080端口的服务
        }

	location /comfyui/ {
            proxy_pass http://comfyui_srevice; # 请求/service1/路径的请求会被转发到8080端口的服务
        }

	location /face/ {
            proxy_pass http://face_srevice; # 请求/service1/路径的请求会被转发到8080端口的服务
        }
    location /v1.0/ {
        proxy_pass https://api.dingtalk.com;
    }
    location /topapi/ {
        proxy_pass https://oapi.dingtalk.com;
    }
    
	location / {
		proxy_pass http://127.0.0.1:3210/;
        proxy_buffering off;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                access_log  /var/log/openresty/aiex.mosslab.com.ask.access.log  main;
                       
        }
        access_log  /var/log/openresty/aiex.mosslab.com.access.log  main;
	    error_log   /var/log/openresty/aiex.mosslab.com.error.log;
    }

}

**Comment by BQQQQB** [comment]
@cy948 老师，还有一个问题，我们封装项目为docker的时候很慢，有啥提速方法吗？RUN pnpm i主要是这一步一直失败

**Comment by cy948** [comment]
> @cy948 老师，还有一个问题，我们封装项目为docker的时候很慢，有啥提速方法吗？RUN pnpm i主要是这一步一直失败

如果你的服务器在中国大陆，需要更改镜像源，就像文件里面说的。https://github.com/lobehub/lobe-chat/blob/cd506dde852976c542ff7873ee8da5cdfb0b7247/Dockerfile#L24

关于封装镜像很慢，也就是以下这一步
```Dockerfile
RUN pnpm run build:docker # run build standalone for docker version
```
解决方法：你可以手动在`next.config.mjs`里面关闭 nextjs 在构建时的 eslint 和 type 检查。
```mjs
const nextConfig = {
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint:{
    ignoreDuringBuilds: true,
  },
}
```

**Comment by cy948** [comment]
你的 Nginx 配置文件中`location /`里，配置的是 `proxy_pass http://127.0.0.1:3210/;` 也就是说你是在服务器上使用 Docker 部署，然后使用 Nginx 进行反向代理？

**Comment by BQQQQB** [comment]
> 你的Nginx配置文件里`location /`，配置的是`proxy_pass http://127.0.0.1:3210/;`那你是在服务器上使用Docker部署，然后使用Nginx进行反向代理？

是的

**Comment by arvinxx** [comment]
我怎么感觉像是ssl 配置的不对
