### ISSUE TITLE
[Bug] OLLAMA 接口连通性检查错误

### ISSUE THREAD

**Issue by QIN2DIM** [lobehub/lobe-chat#1352]
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Firefox

## OLLAMA 连通性检查错误

从 error.message 看出测试代码尝试盲选 llama2 构建对话测试，但 ollama 服务并未下载此模型。

![test](https://github.com/lobehub/lobe-chat/assets/62018067/f1199566-5ad7-45cc-9a17-25f7c324e51e)

也许可以访问 `https://127.0.0.1:11434/api/tags` 通过 `/api/tags` 来测试连通性，这个接口效果相当于 `ollama ls` 查看已经 pull 到机器上的模型列表。

![图片](https://github.com/lobehub/lobe-chat/assets/62018067/c198aa45-7e61-4c9d-8e79-ee69fb6cf815)

**Comment by arvinxx** [comment]
这个建议不错 cc @sjy

**Comment by sjy** [comment]
@QIN2DIM 感谢建议，修复好后好通知你 ～
