### ISSUE TITLE
[Request] Server side persistency

### ISSUE THREAD

**Issue by frmz** [lobehub/lobe-chat#1354]
### 🥰 Feature Description

I think one of the main issues of the project is the fact that data is stored on the browser, there is no persistency on the server side, this is quite an issue for people using multiple devices since they cannot switch from, say, laptop to mobile and continue a conversation there.

### 🧐 Proposed Solution

A simple solution would be to use NextJS server side to store data via a server side API layer, this would require user to at least configure a key on the client to allow encryption server side.

**Comment by arvinxx** [comment]
It will implement by #368

**Comment by frmz** [comment]
> It will implement by #368

Cool, i see Mongo, which is perfect for large scale deployment but would be nice to also have sqlite on a data path for small deployments like single user o small team deployments

**Comment by arvinxx** [comment]
Database Server DB Guide：https://lobehub.com/docs/self-hosting/advanced/server-database
