### ISSUE TITLE
[Request] Add multiple interface proxy addresses and multiple api key management, easy to quickly switch between different api keys and interface proxy addresses.

### ISSUE THREAD

**Issue by ATFmxyl** [lobehub/lobe-chat#1363]
### 🥰 Feature Description

Add a parameter list to the OpenAI KEY and endpoint interface address, save multiple entries, and use only one of them.

### 🧐 Proposed Solution

Add a list of api keys and interface proxy addresses respectively
Used to manage all the api keys and interface proxy addresses of the current open ai.
Then choose which one you need to use currently, to avoid filling in the interface address and api key repeatedly when switching between them.

**Comment by arvinxx** [comment]
I don;t think adding api key manager feature is a good way for LobeChat. If you need key pool feature, maybe the oneapi is a better solution. And it can work well with LobeChat.

as for the multiple api key calling, we have a PR for it : #1345

**Comment by ATFmxyl** [comment]
Sure, I just want to quickly switch between multiple proxy API addresses without having to repeatedly fill in the corresponding API keys for these proxy API addresses.

**Comment by ATFmxyl** [comment]
> I don't think adding api key manager feature is a good way for LobeChat. If you need key pool feature, maybe the oneapi is a better solution. And it can work well with LobeChat.
> 
> as for the multiple api key calling, we have a PR for it : #1345

Sure, I just want to quickly switch between multiple proxy API addresses without having to repeatedly fill in the corresponding API keys for these proxy API addresses.

**Comment by kevinarch** [comment]
Looking for this feature to implement

**Comment by ATFmxyl** [comment]
> Looking for this feature to implement

I think I found another way to do it.
https://github.com/Calcium-Ion/new-api
