### ISSUE TITLE
[Bug] Function calling not working with Mistral/Mixtral/Llama2 via Ollama

### ISSUE THREAD

**Issue by DEAD1SIDE** [lobehub/lobe-chat#1364]
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

When using the OpenAI Api of Ollama, function calling does not work with mistral/mixtral and Llama2. When using GPT-3.5 the Plugin runs first and then GPT generates the answer. Using any of the models above, it starts generating an answer instantly

### 📝 Additional Information

on [v0.129.0], [v0.129.1] and [v0.129.2]

**Comment by sjy** [comment]
Currently, the implement of chat service is via ollama's openai compatiable api
Keep an eye on this  https://github.com/ollama/ollama/blob/main/docs/openai.md

**Comment by arvinxx** [comment]
Is function calling working with these local models?

**Comment by arvinxx** [comment]
I find that ollama don't support function calling by now: https://twitter.com/jmorgan/status/1784378944323567996.

So maybe we can support once it have this ability.


Refs: https://github.com/lobehub/lobe-chat/issues/2220
