### ISSUE TITLE
[Request] Button to cancel an ongoing generation

### ISSUE THREAD

**Issue by davidreis97** [lobehub/lobe-chat#1367]
### 🥰 Feature Description

Often times I want to cancel an ongoing generation. (If I'm not missing anything,) there is currently no way to achieve this without deleting the response entirely.

### 🧐 Proposed Solution

Add a small X button on the menu that shows up when the user hovers over the response.

**Comment by arvinxx** [comment]
We support cancel response. Don't you find it? Which device are you using?

**Comment by davidreis97** [comment]
Sorry about that, I wasn't expecting the button to be at the bottom.
