### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by Eyobs-droid** [lobehub/lobe-chat#1375]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Firefox

### 🐛 Bug Description

After i have installed the app and start chatting with it it says server is not responding

**Comment by arvinxx** [comment]
Please check whether it helpful https://chat-docs.lobehub.com/en/self-hosting/faq/no-v1-suffix

**Comment by Eyobagithub** [comment]
okay tell me how do i correctly configure the OPENAI_PROXY_URL?

**Comment by arvinxx** [comment]
The document has solution, add `v1`

**Comment by Eyobagithub** [comment]
Yeah i know the solution is to add the v1 suffix, but how?

**Comment by Eyobagithub** [comment]
![Screenshot (20)](https://github.com/lobehub/lobe-chat/assets/109045880/72bccd31-1110-41c4-88b8-233c9165402e)



![Screenshot (21)](https://github.com/lobehub/lobe-chat/assets/109045880/e673d5ba-a43c-47c3-95b0-e394dad9fa90)



Sir, i had the lobe chat in my container but it says error?

**Comment by Eyobagithub** [comment]
@arvinxx i even tried to deploy it using the vercel, but it doesn't respond
