### ISSUE TITLE
[Request] gemini敏感詞無法回應,需要設BLOCK_NONE

### ISSUE THREAD

**Issue by keung67** [lobehub/lobe-chat#1387]
### 🥰 需求描述

安全級別 gemini pro 連要他講個笑話也不行...
參考 https://github.com/zuisong/gemini-openai-proxy/blob/main/dist/main_cloudflare-workers.mjs
```
          safetySettings: [
            HarmCategory.HARM_CATEGORY_HATE_SPEECH,
            HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
            HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
            HarmCategory.HARM_CATEGORY_HARASSMENT
          ].map((category) => ({
            category,
            threshold: HarmBlockThreshold.BLOCK_NONE
          }))
```

是否可以增加参数，将gemini的安全阈值设置为BLOCK_NONE？
https://github.com/soulteary/amazing-openai-api/issues/1

### 🧐 解决方案

[index.zip](https://github.com/lobehub/lobe-chat/files/14396320/index.zip)
lobe-chat-main\src\libs\agent-runtime\google\index.ts

### 📝 补充信息

代碼還未部署測試過

**Comment by arvinxx** [comment]
能给个测试的用例句子吗？

**Comment by keung67** [comment]
> 能给个测试的用例句子吗？
讲个笑话
https://github.com/babaohuang/GeminiProChat/issues/74

但"請你講個笑話"不會卡死
![image](https://github.com/lobehub/lobe-chat/assets/127957412/c8ee90e4-0430-44f7-8f41-8d6fe237b97e)
