### ISSUE TITLE
[Bug] Markdown有序列表格式渲染错误

### ISSUE THREAD

**Issue by leeyiding** [lobehub/lobe-chat#139]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

在遇到有序列表中混有代码块的情况下，会导致有序列表序号被截断

![image](https://github.com/lobehub/lobe-chat/assets/49098278/c6ac0821-9399-4658-b4a5-c28c30bb14a1)

**Comment by canisminor1990** [comment]
fixed
