### ISSUE TITLE
[Bug] 无法很好的支持公式

### ISSUE THREAD

**Issue by gaojunyang666** [lobehub/lobe-chat#1391]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

不能很好的支持markdown的公式
![image](https://github.com/lobehub/lobe-chat/assets/63088548/50c51c61-9e5f-4e0c-b321-ecf1d7e0fca3)

### 🚦 期望结果

应该将那种格式的公式转化为我们所熟知的那种

### 📷 复现步骤

您只需要想GPT询问，得到的结果中有公式就会出现此问题

**Comment by arvinxx** [comment]
重复： https://github.com/lobehub/lobe-chat/discussions/502
