### ISSUE TITLE
[Bug] docker

### ISSUE THREAD

**Issue by BQQQQB** [lobehub/lobe-chat#1392]
### 💻 Operating System

Ubuntu

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

我自己修改了项目当中的一些内容，之后封装docker，出现了一个问题，
curl http://localhost:3210/
curl: (56) Recv failure: Connection reset by peer

响应中断了

而且他是隔一段时间出现，没有规律，为什么？一会可以用，一会就不行

老师，这是什么原因？

**Comment by luojiyin1987** [comment]
```shell
curl -v http://example.com
```
尝试获取更多信息 @BQQQQB

**Comment by luojiyin1987** [comment]
并提供完整的docker 命令或者 docker-compose 配置文件。

**Comment by BQQQQB** [comment]
ce@HM-A10-SD:/var/log/openresty$ curl -v  http://localhost:3210
*   Trying 127.0.0.1:3210...
* Connected to localhost (127.0.0.1) port 3210 (#0)
> GET / HTTP/1.1
> Host: localhost:3210
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

**Comment by BQQQQB** [comment]
> 并提供完整的 docker 命令或者 docker-compose 配置文件。

没有这个

**Comment by BQQQQB** [comment]
@luojiyin1987 老师，你看一下可以发现问题吗

**Comment by arvinxx** [comment]
@BQQQQB 大概率是你修改内容的报错吧，可能docker中的 node 起不来，这个得你自己排查了。二开导致起不起来的我们解答不了。

**Comment by BQQQQB** [comment]
ouk
