### ISSUE TITLE
[Bug] auth0 on vercel

### ISSUE THREAD

**Issue by nexusdiscord** [lobehub/lobe-chat#1400]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

I followed the steps outlined on https://chat-docs.lobehub.com/en/self-hosting/advanced/authentication.

after clicking the sign in button on the settings page, I got error
![image](https://github.com/lobehub/lobe-chat/assets/63144643/f66886be-56f7-4197-b7b0-fad4ede9f22b)

![image](https://github.com/lobehub/lobe-chat/assets/63144643/9f5c37bb-c9d0-46a8-be0f-ffb435e1cda7)

`    at (node_modules/@auth/core/lib/actions/signin/authorization-url.js:17:23)
    at (node_modules/@auth/core/lib/actions/signin/index.js:10:61)
    at (node_modules/@auth/core/lib/index.js:60:29)
    at (node_modules/@auth/core/index.js:105:28)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:189:36)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:128:25)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:251:29)
    at (node_modules/next/dist/esm/server/web/edge-route-module-wrapper.js:81:20)
    at (node_modules/next/dist/esm/server/web/adapter.js:157:15)`

**Comment by arvinxx** [comment]
@cy948 please help to check it

**Comment by cy948** [comment]
Please provide the environment variables you used for deployment on Vercel to help us reproduce the error.

**Comment by nexusdiscord** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/63144643/aa4db69d-a694-4f20-8808-ba1b447896c7)

**Comment by cy948** [comment]
> ![image](https://private-user-images.githubusercontent.com/63144643/308230181-aa4db69d-a694-4f20-8808-ba1b447896c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDc2NDUsIm5iZiI6MTcwOTA0NzM0NSwicGF0aCI6Ii82MzE0NDY0My8zMDgyMzAxODEtYWE0ZGI2OWQtYTY5NC00ZjIwLTg4MDgtYmExYjQ0Nzg5NmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE1MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMWFlYzNiMDc3MmU5MDUzOTk3Nzg5ZjYyMTI1ZjcxZGQyZWMzMDkxNmM5NDQ1N2FhMGM2MDlmMTk3MGI2NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.117FIDyM9d-cCrcV2VbPvBK7obVVHg9WuQ7Xmoseu_4)

`AUTH0_ISSUER` with `https://` prefix? For example: `https://example.auth0.com`
