### ISSUE TITLE
怎么配置Anthropic的Claude的API到助手呢?

### ISSUE THREAD

**Issue by ddwinhzy** [lobehub/lobe-chat#1401]
### 🥰 需求描述

怎么配置Anthropic的Claude的API到助手呢?

### 🧐 解决方案

设置里头只有AWS设置,有点迷糊,能出个说明吗?

**Comment by arvinxx** [comment]
Anthropic 的 Claude 不支持

**Comment by gijigae** [comment]
@arvinxx I can use Claude via Amazon Bedrock.

![image](https://github.com/lobehub/lobe-chat/assets/81459/79dae821-acd7-4331-88ec-72797843d17c)


@ddwinhzy To use Anthropic's Claude, you first need to have access to corrsponding models in Amazon Bedrock. Once you have the proper model access, you can start using Claude with AWS settings. Hope it helps.

![image](https://github.com/lobehub/lobe-chat/assets/81459/43b342be-2509-45bd-91ee-033eb6d74234)

**Comment by arvinxx** [comment]
@gijigae I think his demand is to use Anthropic as the model provider

**Comment by ddwinhzy** [comment]
&gt; @arvinxx I can use Claude through Amazon Bedrock.


&gt; 


&gt; ! [image](https://private-user-images.githubusercontent.com/81459/308380004-79dae821-acd7-4331-88ec-72797843d17c.png?jwt= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9. eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTczNTQsIm5iZiI6MTcwOTIxNzA1NCwicGF0aCI6Ii84MTQ1OS8zMDgzODAwMDQtNzlkYWU4MjEtYWNkNy00MzMxLTg4ZWMtNzI3OTc4NDNkMTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE0MzA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOGJlZWJjOTY4MmNmYzMwMTU1Mzc0NDhkN2FlZmVhNzM2NDM3MTA0MGM0ZjhkNmQ0ZjJmMTQxODhmMmQ1YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0 .MS3j-QiCU8jzpvNVBwgqPAHXuQkJGSaEsxMkl14Bfj8)


&gt; 


&gt; @ddwinhzyTo use Claude with Anthropic, you will first need access to the appropriate model in Amazon Bedrock. Once you have the correct access to the model, you can start using Claude through your AWS setup.Hope this helps.


&gt; 


&gt; ! [image](https://private-user-images.githubusercontent.com/81459/308379542-43b342be-2509-45bd-91ee-033eb6d74234.png?jwt= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9. eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTczNTQsIm5iZiI6MTcwOTIxNzA1NCwicGF0aCI6Ii84MTQ1OS8zMDgzNzk1NDItNDNiMzQyYmUtMjUwOS00NWJkLTkxZWUtMDMzZWI2ZDc0MjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE0MzA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNGQ0ZTlhZGZhYzM3YTRmYTY3MDk0NWJhZjU0ZDI4MzAwMDkxNzkwN2M1ZGM5YmE4NDM1ZDYzOGIxMmI1ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0 .tMDIDEcqeJwzSWBPwETjt5_W01-rHn7uwk1T9g_pTu8)



I've already got access, but I don't know how to set it up.  
Aws Access Key Id:
Aws Secret Access Key:

**Comment by ddwinhzy** [comment]
> @arvinxx I can use Claude via Amazon Bedrock.我可以通过亚马逊 Bedrock 使用克劳德。
> 
> ![image](https://private-user-images.githubusercontent.com/81459/308380004-79dae821-acd7-4331-88ec-72797843d17c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTc0NjQsIm5iZiI6MTcwOTIxNzE2NCwicGF0aCI6Ii84MTQ1OS8zMDgzODAwMDQtNzlkYWU4MjEtYWNkNy00MzMxLTg4ZWMtNzI3OTc4NDNkMTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE0MzI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNzIwMDVmZGU5ZmUwYzlkNDlmOTJhMmVmMDU2NDdiZDg3OTQ1YWM1ZTM3ZWY5NzQwYTYwODc0MzBkODFhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RFxRTYKfVOPNT4OzxHMJPSTz7G2tbShXI9ql1jU4GIg)
> 
> @ddwinhzy To use Anthropic's Claude, you first need to have access to corrsponding models in Amazon Bedrock. Once you have the proper model access, you can start using Claude with AWS settings. Hope it helps.要使用 Anthropic 的 Claude，首先需要访问亚马逊 Bedrock 中的相应模型。获得适当的模型访问权限后，就可以开始使用 AWS 设置中的 Claude。希望对您有所帮助。
> 
> ![image](https://private-user-images.githubusercontent.com/81459/308379542-43b342be-2509-45bd-91ee-033eb6d74234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTc0NjQsIm5iZiI6MTcwOTIxNzE2NCwicGF0aCI6Ii84MTQ1OS8zMDgzNzk1NDItNDNiMzQyYmUtMjUwOS00NWJkLTkxZWUtMDMzZWI2ZDc0MjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE0MzI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NzczNjE4MjQ5NWMzMWFkYjliN2Q2MzRmNjFhMjRmNzMwNzI1YzI5YjU3Y2UzYzUyMmRjYjFjNTIxOTNhNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i3o1jfJhIL-RWQ8RCcxrsVSqAcK2y4tNlgEd8GrGDts)



I've already got access, but I don't know how to set it up.  
Aws Access Key Id:
Aws Secret Access Key:

**Comment by ddwinhzy** [comment]
> @gijigae I think his demand is to use Anthropic as the model provider

I've already got access, but I don't know how to set it up.
Aws Access Key Id:
Aws Secret Access Key:

**Comment by ddwinhzy** [comment]
It's configured and ready to go, thanks guys!
