### ISSUE TITLE
[Bug] C++代码显示样式问题

### ISSUE THREAD

**Issue by kindmesdilabso** [lobehub/lobe-chat#1404]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

在深色模式下,C++代码的注释看不清楚
界面配置
![image](https://github.com/lobehub/lobe-chat/assets/141629838/2681ee73-2e73-46f1-bf20-24b6dd5c0bf2)
未选中代码时的代码样式
![image](https://github.com/lobehub/lobe-chat/assets/141629838/cb97214e-f1a1-4e2f-a231-75ce4fa185c9)
选中后的样式
![image](https://github.com/lobehub/lobe-chat/assets/141629838/fb9bf717-ee64-420f-898a-5d431bdb139d)

### 🚦 期望结果

希望这个代码块的风格可以切换,包含一些常见的主题风格样式

### 📷 复现步骤

1. 设置
2. 主题设置
3. 主题色选倒数第四个
4. 中性色选第三个
5. 切换到聊天对话
6. 复制下面代码并仅添加到对话中
7. 观察代码块的样式
```c++
#include <iostream>
#include <coroutine>

// 定义协程函数
auto coroutine_function() -> std::coroutine_handle<void> {
    co_yield "Hello from coroutine!";
    return nullptr;
}

int main() {
    // 获取协程句柄
    auto handle = coroutine_function();

    // 执行协程
    handle.resume();

    return 0;
}

```

### 📝 补充信息

好像上面的代码语言和复制按钮的颜色也变的看不清了
![recording](https://github.com/lobehub/lobe-chat/assets/141629838/bcd76489-2baf-4c11-be07-639697c4c723)

**Comment by kindmesdilabso** [comment]
尝试了一下,目前最新版本还是这样,希望代码块的代码样式,字体可以单独调整

**Comment by arvinxx** [comment]
和 #3087 重复，后续一并考虑允许自定义高亮主题
