### ISSUE TITLE
[Request] Ability to require auth

### ISSUE THREAD

**Issue by dbnewman** [lobehub/lobe-chat#1406]
### 🥰 Feature Description

It appears there is no way to enforce auth, instead the user is presented the application and the auth option is added to settings.

### 🧐 Proposed Solution

There should be a configuration item to enforce auth preventing access to the app unless a user is logged in.

**Comment by arvinxx** [comment]
@cy948 what's your idea about this?

**Comment by cy948** [comment]
> @cy948 what's your idea about this?

Perhaps we can restrict access to all routes by non-authenticated users and set up a login page.

**Comment by cy948** [comment]
I think the current protection of resources is sufficient. By specifying `ACCESS_CODE` or using `OAuth`, we can prevent unauthorized users from abusing our resources. 
- If you want personalized page access control, you can refer to the documentation of [NextAuth](https://next-auth.js.org/configuration/nextjs#advanced-usage) and implement it in your own project. 
- Or if you want to extend the existing access control, you can try modifying some files. For example, if you want to force everyone chat after OAuth or provide `ACCESS_CODE`, you can modify the code like this:
in `src\app\api\chat\auth.ts`:
```diff
export const checkAuthMethod = (
  accessCode?: string,
  apiKey?: string,
  oauthAuthorized?: boolean,
) => {
  const { ACCESS_CODES, ENABLE_OAUTH_SSO } = getServerConfig();

  // if OAuth 2 header is provided
  if (ENABLE_OAUTH_SSO && oauthAuthorized) return;

  // if apiKey exist
- if (apiKey) return;

  // if accessCode doesn't exist
  if (!ACCESS_CODES.length) return;

  if (!accessCode || !ACCESS_CODES.includes(accessCode)) {
    console.warn('tracked an invalid access code, 检查到输入的错误密码：', accessCode);
    throw AgentRuntimeError.createError(ChatErrorType.InvalidAccessCode);
  }
};
```

**Comment by dbnewman** [comment]
To give some context, the type of auth we are looking for is what OpenAI have implemented, where you need to authenticate BEFORE seeing the front end, we are looking to use this for internal users, but will be using public cloud infrastructure so having that auth in front of the application reduces the possible impact of any vulnerabilities. 

The current implementation will load the front end without any auth, and then request auth to use any of the functions.

**Comment by cy948** [comment]
> To give some context, the type of auth we are looking for is what OpenAI have implemented, where you need to authenticate BEFORE seeing the front end, we are looking to use this for internal users, but will be using public cloud infrastructure so having that auth in front of the application reduces the possible impact of any vulnerabilities.
> 
> The current implementation will load the front end without any auth, and then request auth to use any of the functions.

This feature may require community discussion before being implemented. In the meantime, you can use the access control features provided by the public cloud you are using, such as `deployment-protection` on Vercel.

**Comment by cfwl1111** [comment]
Using 2FA two-factor authentication might be a good option?

**Comment by shigomany** [comment]
I think we need to use something like an admin that can register users. To be able to open Lobe Chat on any device on the web under your user (with your own data about chats and settings)

**Comment by shigomany** [comment]
> > I think we need to use something like an admin that can register users. To be able to open Lobe Chat on any device on the web under your user (with your own data about chats and settings)
> 
> We are considering this seriously. And you will see the change happen 😄

I look forward to it)
