### ISSUE TITLE
[Request] mermaid support

### ISSUE THREAD

**Issue by zealotCE** [lobehub/lobe-chat#1415]
### 🥰 Feature Description

在需要 LLM 助手返回数据时，如果返回 markdown 的 mermaid 格式内容，期望能直接显示出来。
类似这样：
<img width="701" alt="image" src="https://github.com/lobehub/lobe-chat/assets/26129403/f41f22b6-959d-4a43-a41f-f3f9d24ef943">

### 🧐 Proposed Solution

不论是输入还是助手的输出，如果返回的 markdown 内容中，只要是 mermaid 格式的内容则直接渲染

**Comment by arvinxx** [comment]
@canisminor1990 是不是可以做个配置允许这样展示出来呢？

**Comment by Delay-n-days** [comment]
i need it so

**Comment by arvinxx** [comment]
now we have supported Mermaid:

![LobeChat_随便聊聊_2024-08-08](https://github.com/user-attachments/assets/2f905882-8dab-432f-9247-be32084e0203)
