### ISSUE TITLE
[Bug] 使用ollama部署的视觉模型llava:34b，图片问答时报错

### ISSUE THREAD

**Issue by ccdanpian** [lobehub/lobe-chat#1416]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

1. ollama部署在类似AutoDL的jupyter服务器上，通过ngrok内网穿透进行访问。
使用模型为llava:34b；
2. 在服务器上可以提供图片地址，或者使用示例的API，都可正常识别图片；
![image](https://github.com/lobehub/lobe-chat/assets/130242490/60385364-91ed-40cb-adac-5e51edf6e951)
3. 在lobchat中，如果只用文字提问可以正常回复，加入图片则报如下错误。
`{
  "error": {
    "message": "json: cannot unmarshal array into Go struct field Message.messages.content of type string",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  },
  "provider": "ollama",
  "endpoint": "https://xxx.ngrok-free.app/v1"
}`

**Comment by sjy** [comment]
> related issue: https://github.com/lobehub/lobe-chat/issues/1364 
当前版本使用的openai api 兼容api endpoint 访问，官方还不支持通过该方式使用 vision 和 function call
