### ISSUE TITLE
[Bug] How to set the waiting time for custom APIs

### ISSUE THREAD

**Issue by shenmadouyaowen** [lobehub/lobe-chat#1419]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

Hello, how do I set the waiting time for custom APIs? I couldn't find this configuration option in. env

### 🚦 期望结果

I hope to have a variable that can set the waiting time for the API, because my API often returns after timeout, and then the Lobe interface cannot receive messages

### 📷 复现步骤

When I use a custom API to access, due to the special nature of the API, the return data is relatively slow, and I need to set a custom waiting time

**Comment by arvinxx** [comment]
Are you using Vercel?

**Comment by shenmadouyaowen** [comment]
> Are you using Vercel?

No, it's not Vercel, it's the discord interface transferred from Coze because it has intermediate forwarding and requires too long waiting time

**Comment by arvinxx** [comment]
I mean that is your site deployed on Vercel?

**Comment by shenmadouyaowen** [comment]
> I mean that is your site deployed on Vercel?

 No,Oracle Cloud services

**Comment by cy948** [comment]
Discord interface? 就是说在 lobechat 上通过 Discord 使用 Coze ？

**Comment by shenmadouyaowen** [comment]
> Discord interface? 就是说在 lobechat 上通过 Discord 使用 Coze ？

是啊，能加一个等待响应时间的接口么

**Comment by arvinxx** [comment]
@shenmadouyaowen 超时时间和你的服务有关系吧。我们默认应该没设定超时时长

**Comment by shenmadouyaowen** [comment]
> @shenmadouyaowen 超时时间和你的服务有关系吧。我们默认应该没设定超时时长

是没有设定，但是想要一个

**Comment by cy948** [comment]
> > @shenmadouyaowen 超时时间和你的服务有关系吧。我们默认应该没设定超时时长
> 
> 是没有设定，但是想要一个

自定义 Provider 得自己维护，找找相关请求库的文档吧。
