### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jiawuwei** [lobehub/lobe-chat#1421]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

There is a error when I access lobechat. But it works fine when deployed with sealos
![image](https://github.com/lobehub/lobe-chat/assets/28945839/57eef208-e7f8-4e4b-bef9-8288727cee2a)

**Comment by jiawuwei** [comment]
It does not work properly when deployed using docker

**Comment by arvinxx** [comment]
check the docker log?

**Comment by jiawuwei** [comment]
docker log 
<img width="1447" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28945839/228dbd31-c900-4877-bd79-b81e9b3d722d">

**Comment by arvinxx** [comment]
感觉可能是网络请求问题？你这个 docker  能连 OpenAI 吗

**Comment by jiawuwei** [comment]
我用的代理地址，没有直接调用openai接口，我通过curl命令在服务器上通过代理服务器地址调用接口返回正常

**Comment by arvinxx** [comment]
那这个就是代理的问题，可以弄个透明代理。https://github.com/lobehub/lobe-chat/discussions/466
