### ISSUE TITLE
[Bug] Connectivity Check Button doesn't work correctly

### ISSUE THREAD

**Issue by jrr997** [lobehub/lobe-chat#1427]
### 💻 Operating System

macOS

### 📦 Environment

Other

### 🌐 Browser

Chrome

### 🐛 Bug Description

在配置 Language Model(Azure OpenAI) 时有一个 Check 按钮，点击后会向 Azure OpenAI Proxy 发请求。我的配置(能在 Chat Page 中使用)是对的，但是 Check 总是返回失败。这似乎是 Check 功能没对 Azure 做适配。

### 🚦 Expected Behavior

配置正确，Check 应该通过。

### 📷 Recurrence Steps

1. 配置 Azure Language Model。
2. 点击 Check 按钮。

### 📝 Additional Information

按钮返回的错误信息如下。可以看到 endPoint 和 [Azure 文档](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions)不符。
```
{
  "error": {
    "code": "DeploymentNotFound",
    "message": "The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."
  },
  "provider": "openai",
  "endpoint": "https://xxx.openai.azure.com/openai/deployments/gpt-35-turbo"
}
```

解决方案：
把 `gpt-35-turbo` 换成用户配置的 `Custom Model Name`: `https://xxx.openai.azure.com/openai/deployments/{Custom Model Name}`

**Comment by droner-D** [comment]
Even I'm facing the same issue.. Is it resolved?
