### ISSUE TITLE
[Bug] 代码块渲染无法正常换行

### ISSUE THREAD

**Issue by leeyiding** [lobehub/lobe-chat#143]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

代码块渲染异常，所有代码都挤到一行了
![image](https://github.com/lobehub/lobe-chat/assets/49098278/3a01c1c3-472d-44a9-b15d-ff2511bf96a1)

**Comment by arvinxx** [comment]
能否将这个内容复制出来？我复现下试试看

**Comment by leeyiding** [comment]
这个直接在chat.lobehub.com测试的，应该让它随便输出一段代码都能复现

**Comment by canisminor1990** [comment]
<img width="1028" alt="image" src="https://github.com/lobehub/lobe-chat/assets/17870709/040ac0f1-b457-4b86-b2e7-59fdaa3d10c7">
复制一下？ 我这边代码块渲染还是正常的

**Comment by canisminor1990** [comment]
@arvinxx https://github.com/lobehub/lobe-ui/blob/master/src/hooks/useHighlight.ts
没加 python

**Comment by arvinxx** [comment]
@canisminor1990  怎么做动态引入？识别到某个语法然后自动加载？

**Comment by arvinxx** [comment]
我建议 python 可以内置掉，其他的再看看？

**Comment by canisminor1990** [comment]
> @canisminor1990 怎么做动态引入？识别到某个语法然后自动加载？

好像有个动态 es6 方案

**Comment by canisminor1990** [comment]
> 我建议 python 可以内置掉，其他的再看看？

fixed https://github.com/lobehub/lobe-ui/commit/0d6de6e6c657cdf9e084822370914f406f474bee

**Comment by arvinxx** [comment]
> > @canisminor1990 怎么做动态引入？识别到某个语法然后自动加载？
> 
> 好像有个动态 es6 方案
```

这个动态方案就要是外部传进来不存在的 lang 时，重新初始化 shiki 这样来实现了
