### ISSUE TITLE
[Bug] 0.130.6 的 DALLE插件，无法像旧版本一样绘图

### ISSUE THREAD

**Issue by GuoJiaxing1997** [lobehub/lobe-chat#1439]
### 💻 Operating System

Other Linux

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

如图，旧版本我记得是会直接生成4张图片的（如果没记错的话）
![Snipaste_2024-03-02_20-16-41](https://github.com/lobehub/lobe-chat/assets/88412036/f512ec8b-7d7f-4615-af01-0d713d82224c)

**Comment by GuoJiaxing1997** [comment]
买的中转API，并配置的接口代理地址，大概0.130之前的版本可以正常使用，但是更新到0.130.3和0.130.6就不行了

**Comment by arvinxx** [comment]
@GuoJiaxing1997 大概率跟你接口服务商有关系，我这边是正常的。可能你的服务商用了不支持 FC 的 chatgpt 套壳 api 吧

<img width="1054" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/75d93d1d-2331-4e7d-ae0a-cd71da69c38b">

**Comment by GuoJiaxing1997** [comment]
好的谢谢，我去了解了解

**Comment by GuoJiaxing1997** [comment]
您好再请问下，上面说的“不支持 FC 的 chatgpt 套壳 api ”，这里的FC的全称是什么？之前没听说过

**Comment by arvinxx** [comment]
> 您好再请问下，上面说的“不支持 FC 的 chatgpt 套壳 api ”，这里的FC的全称是什么？之前没听说过

Function Call https://platform.openai.com/docs/guides/function-calling
