### ISSUE TITLE
[Request] gpt 3.5 turbo已指向0125，需更新上下文

### ISSUE THREAD

**Issue by devyujie** [lobehub/lobe-chat#1440]
### 🥰 需求描述

gpt 3.5 turbo已指向0125模型，需更新上下文至16k：

![image](https://github.com/lobehub/lobe-chat/assets/48620527/86fb4b3d-bf33-4067-b50c-95e8fe7eeea7)
![image](https://github.com/lobehub/lobe-chat/assets/48620527/4a82136c-607f-460c-a1b3-24883de2157c)

### 🧐 解决方案

/

**Comment by arvinxx** [comment]
可以，今天处理下
