### ISSUE TITLE
[Bug] Vercel部署因`next-auth.ts`失败

### ISSUE THREAD

**Issue by katorly** [lobehub/lobe-chat#1441]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Edge

### 🐛 Bug Description

直接fork使用的，并与Upstream同步。多次部署仍出现此错误。 
几小时前可以正常部署，但最近的部署都报这个错了。  

![image](https://github.com/lobehub/lobe-chat/assets/70022443/45cda3a0-d2be-4055-aace-807f75a8027f)  

 
```console
Failed to compile.

 |  
 | ./src/app/api/auth/next-auth.ts:30:9
 | Type error: Type '{}' is not assignable to type 'string'.

 |  
 | 28 \|       // Pick userid from token
 | 29 \|       if (session.user) {
 | > 30 \|         session.user.id = token.userId ?? session.user.id;
 | \|         ^
 | 31 \|       }
 | 32 \|       return session;
 | 33 \|     },
 | error: script "build" exited with code 1
 | Error: Command "bun run build" exited with 1

```

### 📝 Additional Information

仅使用了以下环境变量：  
![image](https://github.com/lobehub/lobe-chat/assets/70022443/381d807c-eff2-4b89-b216-313cbd23fe46)

**Comment by 6Morpheus6** [comment]
Authentication fails for me as well and for other [Pinokio](https://github.com/pinokiocomputer/pinokio) users.
Operating System: Win 10
GPU: RTX 4070 Ti
RAM: 32GB
Platform: Pinokio
Browser: Opera

![image](https://github.com/lobehub/lobe-chat/assets/127767180/e621742f-17cd-43d7-aa61-095833c2113b)
![image](https://github.com/lobehub/lobe-chat/assets/127767180/1fb158b3-5c11-4b94-91cb-e158f4ac3793)

**Comment by fuyang0811** [comment]
一样的问题，一样的报错。

**Comment by Abigorangee** [comment]
I also encountered the same problem yesterday.
![image](https://github.com/lobehub/lobe-chat/assets/102571587/8b320a3b-6ac3-4ec7-9652-5ec551b0d6a4)

**Comment by arvinxx** [comment]
fixed, please try again~
