### ISSUE TITLE
[Bug] ACCESS_CODE 密码数组只能支持前3个值，之后的值无法生效

### ISSUE THREAD

**Issue by IkeShawn** [lobehub/lobe-chat#1442]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

`ACCESS_CODE` `code1,code2,code3,code4`
code4不会生效

**Comment by cy948** [comment]
您可以提供一个能够复现问题的示例`ACCESS_CODE`吗？

**Comment by IkeShawn** [comment]
抱歉，我更换了一组密码之后问题就消失了。我丢失了会报错的那组密码。请问您是否可以告诉我vercel部署后，环境变量中的ACCESS_CODE存储在哪个源码文件中吗？我想去部署历史中找一下。

**Comment by cy948** [comment]
我也不清楚构建产物的位置，但你可以在 dev 环境中对以下位置进行debug，当进行聊天时 `ACCESS_CODE` 在此进行验证：https://github.com/lobehub/lobe-chat/blob/04a6ef75fe9983abc8aed3910f9714dff1727a76/src/app/api/chat/auth.ts#L57

**Comment by cy948** [comment]
> 抱歉，我更换了一组密码之后问题就消失了。我丢失了会报错的那组密码。请问您是否可以告诉我vercel部署后，环境变量中的ACCESS_CODE存储在哪个源码文件中吗？我想去部署历史中找一下。

印象中 vercel 的构建快照里面不含环境变量，可能找不到了。

**Comment by arvinxx** [comment]
> 抱歉，我更换了一组密码之后问题就消失了。我丢失了会报错的那组密码。请问您是否可以告诉我vercel部署后，环境变量中的ACCESS_CODE存储在哪个源码文件中吗？我想去部署历史中找一下。

那大概率是你的密码中包含了逗号
