### ISSUE TITLE
Set the Vision model as a tool

### ISSUE THREAD

**Issue by richards199999** [lobehub/lobe-chat#1457]
### 🥰 Feature Description

Only the model that have vision capability can receive images (i.e. gpt-4-vision-preview), however, they can't use Function Calling natively.

### 🧐 Proposed Solution

The possible implementation:
When the user send an image, the image can be sent with the original prompt to the Vision model, or set a pre-prompt for this tool. e.g.:
```plain text
You are an image-to-text model./nYou MUST describe the image *in great details*./nYou have to capture *every little details*./nIf the image contain text, then you should transcribe them originally.
```
Then the model can receive the detailed description.

**Comment by arvinxx** [comment]
I think it's a good idea. but I'm doubt whether is valuable if OpenAI just release a gpt-4-turbo with fullablility of fc / vision

**Comment by arvinxx** [comment]
@richards199999 gpt-4-turbo is released with function call and vision. And there will be more and more models to support vision and fc natively. So I think this issue can be closed.

**Comment by richards199999** [comment]
yeah for sure. just look how things are iterates fast.
