### ISSUE TITLE
[Bug] oauth does not work with okta server

### ISSUE THREAD

**Issue by elvis-cai** [lobehub/lobe-chat#1458]
### 💻 Operating System

macOS

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

get http://0.0.0.0:3210/api/auth/callback/auth0?error=invalid_request&error_description=The+authentication+request+has+an+invalid+%27state%27+parameter., seems okta need a state parameter during auth as mentioned here https://devforum.okta.com/t/setting-for-requiring-state-parameter-in-request/25063

### 🚦 Expected Behavior

okta oauth success

### 📷 Recurrence Steps

```
docker run -d -p 3210:3210  -e OPENAI_API_KEY=xx   -e ENABLE_OAUTH_SSO=1 \
-e AUTH0_CLIENT_ID=0oad50tv3wgNtlTDX1d7 \
-e AUTH0_CLIENT_SECRET=4u9QRdR_7E2ftdFaAgPcKUlRiIQcges7zjfurawW0JK6SF2Jd3bQxHsPkRWOeK_9 \
-e AUTH0_ISSUER=https://xxx.oktapreview.com/ \
-e NEXTAUTH_SECRET=DNNd+TbpK66Hd3490u2S8eI1rq0gR37EURudcMyUf74 \
 --name lobe-chat\
 lobehub/lobe-chat
```

**Comment by wakefun** [comment]
You need to add an environment variable named `NEXTAUTH_URL`. In your case, it should be set to `http://localhost:3210/api/auth`. For more information, refer to the documentation on [NEXTAUTH_URL](https://chat-docs.lobehub.com/en/self-hosting/environment-variables/basic#nextauth_url).

**Comment by arvinxx** [comment]
We don't support okta by default, refs: https://github.com/lobehub/lobe-chat/pull/1143#issuecomment-1929625587

**Comment by elvis-cai** [comment]
thanks @wakefun , tried with `NEXTAUTH_URL`, but unfortunately, still got the same result.

**Comment by elvis-cai** [comment]
ah ok, understood, thanks @arvinxx  although that's bit funny, oatuh0 is acquired by Okta, however it's not support okta

**Comment by cy948** [comment]
Value of `NEXTAUTH_URL` depended by the URL you visited to, for example, if you visit from local, you should set it `http://localhost:3210/api/auth`, otherwise, if visit from public, you should set it `http://<public url>/api/auth`.
