### ISSUE TITLE
[Request] Docker 部署时数据存放在本地端而不是浏览器中

### ISSUE THREAD

**Issue by sherlcok314159** [lobehub/lobe-chat#1459]
### 🥰 需求描述

当手机和电脑同时使用时，总是需要来进行同步数据，而 docker 部署时，可以通过 docker-compose 中的 volumes 来将数据存放在本地数据库中，这个也是目前很多开源的选择，有以下好处：
- 多端不需要手动导出，进行同步
- 避免浏览器出问题数据丢失
- 便于迁移数据并进行分析

### 🧐 解决方案

可以查看很多开源项目的方案，比如 huggingface-chat-ui 用的是 mangodb，miniflux 阅读器用的是 postgres

**Comment by Wxh16144** [comment]
印象中作者大大有一个 RFC 做这个的不知道是不是同一个需求？ https://github.com/lobehub/lobe-chat/discussions/368

**Comment by arvinxx** [comment]
我们在 `v0.141.0` 上线了基于 YJS 与 WebRTC 的实验性数据同步功能，欢迎测试并反馈：
- 反馈issue: #1683
- 背后思考：https://github.com/lobehub/lobe-chat/discussions/1681

如果上述同步功能不满足你的诉求，可以 Reopen 该issue

**Comment by sherlcok314159** [comment]
体验了 WebRTC 之后，还是想要 docker 本地的模式，麻烦作者开发 @arvinxx

**Comment by arvinxx** [comment]
@sherlcok314159 https://lobehub.com/zh/docs/self-hosting/advanced/server-database

**Comment by sherlcok314159** [comment]
感谢你的帮助，但是我看目前 doc 写着尚不支持 docker。麻烦有 docker 的时候在此@我一下，谢谢

![图片](https://github.com/user-attachments/assets/376cba40-3c94-48e7-b6a1-1181e4b31263)
