### ISSUE TITLE
[Docs] 开发介绍文档

### ISSUE THREAD

**Issue by canisminor1990** [lobehub/lobe-chat#146]
与 LobeChat 文档专家互动，共建书写开发文档

- [x] 1. 简介 #313
- [x] 2. 环境设置 #316 
- [x] 3. 架构设计 #327
- [x] 4. 功能实现 #328
- [x] 5. API 实现与前后端交互 #326
- [x] 6. 测试指南 #324
- [x] 7. 资源与参考 #325

**Comment by arvinxx** [comment]
当撰写面向开发者的 Lobe-Chat web 应用开发上手指南时，以下是一个可能的指南框架，可以涵盖关键部分的内容：

- [x] 1. 介绍：简要介绍使用的技术栈和框架。https://github.com/lobehub/lobe-chat/blob/main/docs/Development-Guide/index.zh-CN.md

- [x] 2. 环境设置：https://github.com/lobehub/lobe-chat/blob/main/docs/Development-Guide/Steup-Development.zh-CN.md
   - 开发环境需求：列出开发者需要安装和配置的软件和工具。
   - 项目设置：说明如何设置和配置 Lobe-Chat web 应用的开发环境。

3. 架构设计：
   - 应用架构概述：解释应用的整体架构，包括前端、后端和数据库的组成。
   - 数据流和交互：描述应用中的数据流和不同模块之间的交互方式。

4. 功能实现：
   - 聊天功能：说明如何实现实时聊天功能，包括消息发送、接收和显示。
   - 消息存储：解释如何将聊天记录保存到数据库中，以及如何进行数据的读取和更新。
   - 其他功能：列出其他可能的功能，如聊天室管理、文件传输等。

5. 前端开发：
   - 页面设计和布局：描述如何设计和创建应用的页面结构和布局。
   - 前端框架和库：介绍使用的前端框架和库，如React、Angular等。
   - 用户界面组件：列出和解释使用的用户界面组件，如表单、按钮、聊天气泡等。

6. 后端开发：
   - API 设计：说明如何设计和实现后端的 API 接口。
   - 鉴权和安全性：介绍如何实现用户的鉴权和保护应用的安全性。

7. 部署和测试：
   - 部署步骤：列出将应用部署到服务器上的步骤。
   - 测试策略：描述如何进行单元测试、集成测试和端到端测试。

8. 资源和参考：
   - 相关文档和教程：提供与开发相关的文档和教程链接。
   - 开发者社区和支持：介绍可以获取帮助和支持的开发者社区和资源。

请根据您的具体项目需求和开发流程，对以上框架进行适当的调整和扩展，以确保指南能够覆盖项目的关键方面，并提供清晰的指导。

**Comment by arvinxx** [comment]
## 架构设计

根据 LobeChat 的实际组成部分来调整应用架构的章节。以下是一个可能的章节划分：

应用架构概览：在这个部分，提供一个整体的应用架构概览，包括前端、EdgeRuntime API、Agents 市场、插件市场以及独立插件的组成。你可以使用图表或者流程图来清晰地展示各个组件之间的关系。

前端架构：详细描述前端的架构设计，包括使用的技术栈、前端框架、UI组件库等。描述每个组件的职责以及它们如何协同工作。

EdgeRuntime API：解释 EdgeRuntime API 的角色和功能，以及它是如何与前端和其他部分进行交互的。

Agents 市场：详细描述 Agents 市场的设计和工作原理，以及它如何与其他部分进行交互。

插件市场：详细描述插件市场的设计和工作原理，以及它如何与其他部分进行交互。

独立插件：详细描述独立插件的设计和工作原理，以及它如何与其他部分进行交互。

数据流和交互：描述应用中的数据流以及不同模块之间的交互方式。你可以使用数据流图来清晰地展示数据在系统中的流动路径。

安全性和性能优化：解释你如何设计和实现应用的安全性策略，例如身份验证、权限管理等。同时，也可以描述你如何优化应用的性能，包括加载速度、响应时间等。

开发和部署流程：最后，解释开发流程，包括版本控制、测试、持续集成和持续部署���。

每个部分都需要详细解释你的设计决���，以及这些决策如何影响应用的功能性、可靠性、效率和可维护性。

**Comment by arvinxx** [comment]
测试指南：https://sharegpt.com/c/CzFaHpX

**Comment by arvinxx** [comment]
资源与参考

LobeChat 设计、开发过程使用或者参考到的资源或指南：

1. OpenAI  API 指南：https://platform.openai.com/docs/api-reference/introduction
2. OpenAI SDK: https://github.com/openai/openai-node
3. AI SDK： https://sdk.vercel.ai/docs 。
4. LangChain: https://langchain.com。 早期的会话功能基于 LangChain 实现。
5. Chat-Next-Web： https://github.com/Yidadaa/ChatGPT-Next-Web 。 Chat Next Web是个很棒的项目， LobeChat 的部分功能、Workflow 等借鉴与参考了实现。
6. Next.js 文档：https://nextjs.org/docs
7. FlowGPT：https://flowgpt.com/ 目前全球最大的 Prompt 社区，LobeChat 中的一些 Agent 来自 FlowGPT 的活跃作者。

持续补充中

**Comment by arvinxx** [comment]
# 大模型 会话实现


核心会话 API 


```ts
// src/app/api/openai/chat/handler.ts

export const runtime = 'edge';

export const POST = async (req: Request) => {
  const payload = await req.json();

  const { apiKey, endpoint } = getOpenAIAuthFromRequest(req);

  const openai = createOpenai(apiKey, endpoint);

  return createChatCompletion({ openai, payload });
};


```


会话结果：

```ts
// src/app/api/openai/chat/createChatCompletion.ts

import { OpenAIStream, StreamingTextResponse } from 'ai';

export const createChatCompletion = async ({ payload, openai }: CreateChatCompletionOptions) => {
  // ============  1. preprocess messages   ============ //
  const { messages, ...params } = payload;

  const formatMessages = messages.map((m) => ({
    content: m.content,
    name: m.name,
    role: m.role,
  }));

  // ============  2. send api   ============ //

  const response = await openai.chat.completions.create(
    {
      messages: formatMessages,
      ...params,
      stream: true,
    },
    { headers: { Accept: '*/*' } },
  );
  const stream = OpenAIStream(response);
  return new StreamingTextResponse(stream);
};
```


前端集成：
```ts
// src/services/chatModel.ts

import { merge } from 'lodash-es';

import { pluginSelectors, usePluginStore } from '@/store/plugin';
import { initialLobeAgentConfig } from '@/store/session/initialState';
import type { ChatCompletionFunctions, OpenAIStreamPayload } from '@/types/openai';

import { createHeaderWithOpenAI } from './_header';
import { OPENAI_URLS } from './_url';

interface FetchChatModelOptions {
  signal?: AbortSignal | undefined;
}

/**
 * 专门用于对话的 fetch
 */
export const fetchChatModel = (
  { plugins: enabledPlugins, ...params }: Partial<OpenAIStreamPayload>,
  options?: FetchChatModelOptions,
) => {
  const payload = merge(
    {
      model: initialLobeAgentConfig.model,
      stream: true,
      ...initialLobeAgentConfig.params,
    },
    params,
  );
  // ============  1. 前置处理 functions   ============ //

  const filterFunctions: ChatCompletionFunctions[] = pluginSelectors.enabledSchema(enabledPlugins)(
    usePluginStore.getState(),
  );

  const functions = filterFunctions.length === 0 ? undefined : filterFunctions;

  return fetch(OPENAI_URLS.chat, {
    body: JSON.stringify({ ...payload, functions }),
    headers: createHeaderWithOpenAI({ 'Content-Type': 'application/json' }),
    method: 'POST',
    signal: options?.signal,
  });
};
```

使用流式获取结果的核心方法

```ts
// src/utils/fetch.ts

/**
 * 使用流式方法获取数据
 * @param fetchFn
 * @param options
 */
export const fetchSSE = async (fetchFn: () => Promise<Response>, options: FetchSSEOptions = {}) => {
  const response = await fetchFn();

  // 如果不 ok 说明有请求错误
  if (!response.ok) {
    const chatMessageError = await getMessageError(response);

    options.onErrorHandle?.(chatMessageError);
    return;
  }

  const returnRes = response.clone();

  const data = response.body;

  if (!data) return;

  const reader = data.getReader();
  const decoder = new TextDecoder();

  let done = false;

  while (!done) {
    const { value, done: doneReading } = await reader.read();
    done = doneReading;
    const chunkValue = decoder.decode(value);

    options.onMessageHandle?.(chunkValue);
  }

  return returnRes;
};
```

**Comment by arvinxx** [comment]
## 功能实现

如何实现一个大的功能模块？

1. 路由：定义路由
2.数据结构： 定义数据结构 ( types ) 
3. 业务功能实现： zustand store 
4. 页面展示：书写静态组件/ 页面
5. 功能绑定：绑定 store 与页面的触发
