### ISSUE TITLE
[Request] 请求支持GCP的Vertex AI大模型服务

### ISSUE THREAD

**Issue by jameszhanghkmci** [lobehub/lobe-chat#1461]
### 🥰 需求描述

目前lobe-chat尚不支持GCP的Vertex AI大模型服务，此类服务用服务账号身份认证。可以满足企业级数据合规要求。

### 🧐 解决方案

langchain已经提供了对此类服务的支持，https://js.langchain.com/docs/integrations/llms/google_vertex_ai 可供参考

**Comment by arvinxx** [comment]
@jameszhanghkmci 请在 https://github.com/lobehub/lobe-chat/discussions/1284 这里回复，申请模型服务的 issue 我关了
