### ISSUE TITLE
[Bug] JavaScript heap out of memory 

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#1466]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

因为我修改了一些项目代码，所以使用的是dockerfile方式部署，但dockerfile部署的时候，提示内存不够，服务器内存是4G。想问下这个项目到底需要多少内存才能够使用dockerfile部署起来。
![image](https://github.com/lobehub/lobe-chat/assets/8185843/d22a8b7c-49ae-4b7e-bcba-725a44cb2ed9)
![image](https://github.com/lobehub/lobe-chat/assets/8185843/72b71e17-0ce9-4bd5-a586-7623f229c7d7)

### 🚦 期望结果

能够部署起来。

**Comment by arvinxx** [comment]
感觉是你魔改的问题，自行想方法解决把。如果需要参考的话：

https://github.com/lobehub/lobe-chat/issues/968#issuecomment-1880993795

**Comment by yincangshiwei** [comment]
> 感觉是你魔改的问题，自行想方法解决吧。如果需要参考的话：
> 
> [#968 (comment)](https://github.com/lobehub/lobe-chat/issues/968#issuecomment-1880993795)

。。只改了标题和跟Lobe相关的文字，都没改底层。

**Comment by yincangshiwei** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> I feel like it's a problem with your magic modification. Find a way to solve it on your own. If you need reference:
> 
> [#968 (comment)](https://github.com/lobehub/lobe-chat/issues/968#issuecomment-1880993795)

Only changed the title and text related to Lobe

**Comment by arvinxx** [comment]
@yincangshiwei 那就问问 GPT 吧，有可能是node给开的内存不够
