### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Rafcin** [lobehub/lobe-chat#1469]
### 💻 Operating System

Ubuntu

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

I added a Anthropic API key to Lobechat, and when I try to make a call to Opus it says the call is being made to OpenAI GPT 3.5. I'm on the latest deployment of Lobechat.

### 🚦 Expected Behavior

Should be calling Anthropic not OpenAI

### 📷 Recurrence Steps

Deploy the current build to Vercel > Add the Anthgropic API Key, and test a query with 2k tokens.

**Comment by arvinxx** [comment]
I think it might be a hallucination from claude Opus
