### ISSUE TITLE
[Request] Claude Plugin Support

### ISSUE THREAD

**Issue by BrandonStudio** [lobehub/lobe-chat#1472]
### 🥰 需求描述

Claude has now supported function calling with new Claude 3 models, see https://docs.anthropic.com/claude/docs/functions-external-tools. It would be very nice to add plugin support for Claude.

### 🧐 解决方案

Add plugin support for Anthropic Claude API whose model is the 3rd generation.

### 📝 补充信息

There is a very different thing that Claude API does not use JSON format for functions, rather, it uses XML. Consequently it may take extra effort to do adaptation.

**Comment by arvinxx** [comment]
I think it's painful and non-maintainable to support claude plugin with this xml syntax. I prefer to wait for an easier solution 🤷‍♂️

**Comment by arvinxx** [comment]
We support function calling. OpenAPI schema also will be transform to fc schema when invoking

**Comment by walkley** [comment]
Claude function calling enters public beta today: https://docs.anthropic.com/claude/docs/tool-use
Now it use JSON function/tool schema format, I believe it's much more easier to integrate with LobeChat.

**Comment by arvinxx** [comment]
Yes, I think so. I will try to integrate with it soon
