### ISSUE TITLE
Claude aborts reply too early

### ISSUE THREAD

**Issue by mjohenneken** [lobehub/lobe-chat#1476]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Other

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/5088045/9d520f11-200b-4e2a-9481-1db40fc9cc25)
![image](https://github.com/lobehub/lobe-chat/assets/5088045/3c799452-4a66-43ad-b680-1a687eeeb35e)

### 🚦 Expected Behavior

Continue the output

### 📷 Recurrence Steps

Select claude 3 or claude 2.0

### 📝 Additional Information

Via Clauda account and free credits

**Comment by sidedwards** [comment]
I'm experiencing this as well.

**Comment by 1iang** [comment]
same problem, depleyed on vercel.
