### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by thedavidweng** [lobehub/lobe-chat#1479]
### 💻 系统环境

Other

### 📦 部署环境

Other

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/95214375/1d84195d-963c-4db5-9a23-b2924774d077)
Issue Close Require workflow run

### 🚦 期望结果

Action 不报错

### 📷 复现步骤

Fork 项目，然后收到 Action 报错消息

**Comment by cy948** [comment]
Fork之后只保留 upstream sync 就行，其他的禁用掉。

**Comment by thedavidweng** [comment]
> Fork之后只保留 upstream sync 就行，其他的禁用掉。

建议添加此提示到 Doc
