### ISSUE TITLE
[Request] 添加anthropic的接口代理地址选项

### ISSUE THREAD

**Issue by sunzhuo** [lobehub/lobe-chat#1485]
### 🥰 需求描述

为了方便使用第三方代理提供的claude api服务

### 🧐 解决方案

添加类似openai的接口代理地址选项

**Comment by arvinxx** [comment]
@danielglh anthropic 的 SDK 支持吗？

**Comment by danielglh** [comment]
> @danielglh anthropic 的 SDK 支持吗？

支持的

![image](https://github.com/lobehub/lobe-chat/assets/1489309/cd78f5eb-ae37-43e1-a3e1-08b5dab7bdb5)

**Comment by arvinxx** [comment]
@danielglh 有空的话可以来个 PR？

**Comment by danielglh** [comment]
> @danielglh 有空的话可以来个 PR？

OK
