### ISSUE TITLE
增加Groq模型支持

### ISSUE THREAD

**Issue by yonmnm** [lobehub/lobe-chat#1489]
### 🥰 需求描述

目前 Groq 的模型免费且性能非常好

### 🧐 解决方案

支持 https://groq.com/ 的模型

### 📝 补充信息

https://console.groq.com/docs/openai

**Comment by hugoyue** [comment]
建议还是先把 http_proxy 搞定，Groq 本身有做 openai 兼容，但国内环境无法使用。[OpenAI Compatibility](https://console.groq.com/docs/openai)
