### ISSUE TITLE
[Bug] Anthropic Not in Settings

### ISSUE THREAD

**Issue by ZoinktheBoink** [lobehub/lobe-chat#1490]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

Anthropic does not appear in the language model settings.

### 🚦 Expected Behavior

Anthropic should be in the language model settings.

### 📝 Additional Information

![Screenshot 2024-03-07 230156](https://github.com/lobehub/lobe-chat/assets/141833609/ff1e51e2-c76e-4ff6-a378-94d130656b5f)

**Comment by arvinxx** [comment]
You don't sync with latest version
