### ISSUE TITLE
[Bug] 默认不支持流式打字输出效果吗

### ISSUE THREAD

**Issue by jackfong66** [lobehub/lobe-chat#1491]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

使用one-api 的openai接口。  用其他（ChatGPT-Web-Next）可以实时打印流式输出。
用lobehub 需要等待所有结果收到后，再快速的流式输出。

### 🚦 期望结果

能有打字效果

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/discussions/531

**Comment by jackfong66** [comment]
> #531

有用 ，感谢。使用ngnix反代配置
