### ISSUE TITLE
[Request] 谷歌模型无法直接访问时

### ISSUE THREAD

**Issue by mingyue0094** [lobehub/lobe-chat#1493]
### 🥰 需求描述

2个问题。
一 gemini 访问需要 添加socks5代理。 
二 gemini api  v1beta 支持函数调用了。

https://ai.google.dev/docs/api_versions?hl=zh-cn

### 🧐 解决方案

期望
一。有个环境变量，可以提供socks5代理给 谷歌 gemini
二。优化 接入 谷歌模型部分，使可用函数调用功能。

**Comment by arvinxx** [comment]
1. 代理问题详见：https://github.com/lobehub/lobe-chat/issues/1313
2. 一样等官方 SDK 实现，我们才能支持：https://github.com/google/generative-ai-js/issues/14

**Comment by arvinxx** [comment]
> 嗯。调用 generative-ai-js sdk 的方式，确实无法 新增这个功能。
> 他们是有 restapi 的，https://ai.google.dev/tutorials/rest_quickstart 构建请求json后，请求api 接口也可以。

不考虑 api 调用，这个未来自己的维护成本很高的。我倾向官方做好之后我再集成的思路，不然维护不过来。

**Comment by kierankihn** [comment]
官方 SDK 现在已经支持了函数调用

参考 google/generative-ai-js/issues/66

官方示例：https://github.com/google/generative-ai-js/blob/main/samples/node/advanced-function-calling.js
