### ISSUE TITLE
[Bug] 用代理地址和APIkey输入问题后回答为空

### ISSUE THREAD

**Issue by Ivesfsy** [lobehub/lobe-chat#1494]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

vercel部署之后，如果使用代理地址和APIkey输入问题后回答为空，API中转也看不到调用日志

### 🚦 期望结果

优化

**Comment by cy948** [comment]
代理地址后面有没有加上 `/v1`

**Comment by Ivesfsy** [comment]
> 代理地址后面有没有加上 `/v1`

谢谢
