### ISSUE TITLE
很抱歉，服务器似乎遇到了一些困难，暂时无法完成您的请求，请稍后再试[Bug] 

### ISSUE THREAD

**Issue by APPX-Studio** [lobehub/lobe-chat#1497]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

很抱歉，服务器似乎遇到了一些困难，暂时无法完成您的请求，请稍后再试

### 🚦 Expected Behavior

很抱歉，服务器似乎遇到了一些困难，暂时无法完成您的请求，请稍后再试

### 📷 Recurrence Steps

很抱歉，服务器似乎遇到了一些困难，暂时无法完成您的请求，请稍后再试

### 📝 Additional Information

很抱歉，服务器似乎遇到了一些困难，暂时无法完成您的请求，请稍后再试

**Comment by APPX-Studio** [comment]
<img width="1171" alt="image" src="https://github.com/lobehub/lobe-chat/assets/49307767/a4ef247d-6caa-4d26-814c-a0001e06d7ea">

**Comment by APPX-Studio** [comment]
<img width="1343" alt="image" src="https://github.com/lobehub/lobe-chat/assets/49307767/9c9feab7-f4b2-48fe-a24c-dcb3084fd183">

**Comment by followdd** [comment]
![Uploading 20240929013158.png…]()
