### ISSUE TITLE
[Bug] 配置PROXY_URL后，3.5 turbo模型不可用

### ISSUE THREAD

**Issue by devyujie** [lobehub/lobe-chat#1498]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

3.5 turbo 模型下，回答内容为空：
![image](https://github.com/lobehub/lobe-chat/assets/48620527/632d26c6-bce6-4440-9d07-1b1401677e53)

4 turbo 和4 turbo v模型，回答正常：
![image](https://github.com/lobehub/lobe-chat/assets/48620527/da99d1e6-4e36-40f7-b79e-4a549b24be23)

vercel 配置了 PROXY_URL 如下：
![image](https://github.com/lobehub/lobe-chat/assets/48620527/96ac0d1e-b7e5-4c61-9484-5a6cd6069697)

**Comment by arvinxx** [comment]
感觉这个可能要你自己看下3.5这个模型在你的proxy服务商那边的配置哎

**Comment by devyujie** [comment]
对面嗝屁了。
