### ISSUE TITLE
[Request] Shortcut key for switching Agent

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#1499]
### 🥰 需求描述

如题，允许使用快捷键来快速切换不同的助手。

### 🧐 解决方案

支持 CMD/Ctrl + 1~9 来快速切换助手。

**Comment by arvinxx** [comment]
很不错的建议，我之前也有想过。不过有个问题是和浏览器的快捷键会有冲突，不过是会计划跟着某个较为重要的 feature 一起做的

**Comment by arvinxx** [comment]
v1.26.0 添加 `FEATURE_FLAGS=+pin_list` 即可开启
