### ISSUE TITLE
[Bug] 这是我nginx代理获取到的信息

### ISSUE THREAD

**Issue by BQQQQB** [lobehub/lobe-chat#1502]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

{
	"chat_info": "",
	"response_data": "{ body :{ error :{ code : DeploymentNotFound , message : The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again. }, provider : openai , endpoint : https://hqmoss.openai.az****re.com/openai/deployments/ }, errorType : OpenAIBizError }",
	"prompt_tokens": "2900",
	"total_tokens": "2900",
	"timestamps": "2024-03-08 15:29:02"
}
当我提问问题到一定程度之后，获取到的信息就是这个了，但是实际是有响应的，chat_info（请求）response_data（响应）

![image](https://github.com/lobehub/lobe-chat/assets/92673213/fdc3fea4-9a53-41bb-9d9d-d155a83a08c6)

**Comment by BQQQQB** [comment]
{
	"chat_info": {
		"model": "gpt-4-vision-preview",
		"stream": true,
		"frequency_penalty": 0,
		"presence_penalty": 0,
		"temperature": 0.6,
		"top_p": 1,
		"max_tokens": 2048,
		"messages": [{
			"content": "你现在是一个openresty的代理nginx助手，你可以解决逻辑方面的问题，用中文交流",
			"role": "system"
		}, {
			"content": "你好",
			"role": "user"
		}]
	},
	"response_data": "你好！有什么问题可以帮您解决吗？",
	"prompt_tokens": "36",
	"total_tokens": "36",
	"timestamps": "2024-03-08 15:46:34"
}
这是正常的回答

**Comment by arvinxx** [comment]
没懂，看图不是响应正常的吗

**Comment by BQQQQB** [comment]
是正常响应了，但是我通过openresty的nginx代理获取到的信息（请求、响应）是这个，
{
"chat_info": "",
"response_data": "{ body :{ error :{ code : DeploymentNotFound , message : The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again. }, provider : openai , endpoint : [https://hqmoss.openai.az****re.com/openai/deployments/](https://hqmoss.openai.az%2A%2A%2A%2Are.com/openai/deployments/) }, errorType : OpenAIBizError }",
"prompt_tokens": "2900",
"total_tokens": "2900",
"timestamps": "2024-03-08 15:29:02"
}

**Comment by luojiyin1987** [comment]
"model": "gpt-4-vision-preview",   这个模型是部署了吗？
