### ISSUE TITLE
[Request] Claude Haiku 

### ISSUE THREAD

**Issue by stanyslassz** [lobehub/lobe-chat#1506]
### 🥰 Feature Description

Hi can you Add Haiku to Claude model for fast and discount chat ?

### 🧐 Proposed Solution

add Haiku

### 📝 Additional Information

add Haiku

**Comment by ckt1031** [comment]
### Haiku is not yet available through API (Mar 8)

Docs: https://docs.anthropic.com/claude/docs/models-overview

![Screenshot_2024-03-08-22-25-32-735-edit_org mozilla firefox](https://github.com/lobehub/lobe-chat/assets/65409152/6587d6cd-7777-4844-886b-c43cb85cb62e)

**Comment by arvinxx** [comment]
Yes, we will add haiku as soon as it released

**Comment by stanyslassz** [comment]
Release Done :) :)

**Comment by ckt1031** [comment]
Model now points to `claude-3-haiku-20240307`

> Yes, we will add haiku as soon as it released

https://docs.anthropic.com/claude/docs/models-overview

**Comment by stanyslassz** [comment]
Many thank

**Comment by arvinxx** [comment]
@BrandonStudio yeah, it is fixed with https://github.com/lobehub/lobe-chat/pull/1551. I forget to close.
