### ISSUE TITLE
[Bug] HTTP 524 Error on Extremely Long Prompts

### ISSUE THREAD

**Issue by atlas5301** [lobehub/lobe-chat#1510]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Firefox

### 🐛 问题描述

When sending an extremely long prompt or context, consisting of 187,630 tokens, to the Claude AI assistant through the Lobe chat interface, the interface times out and returns an HTTP 524 error before receiving the response.

### 🚦 期望结果

The Lobe chat interface should be able to handle extremely long prompts and receive the response from Claude without timing out.

### 📷 复现步骤

    Open the Lobe chat interface.
    Type a prompt or context consisting of 187,630 tokens. (long enough to trigger a high model latency)
    Send the prompt to Claude. Both claude3-opus and claude3-sonnet will reproduce this bug.
    Wait for the response.

**Comment by arvinxx** [comment]
if the HTTP 524 , it's more an issue of Nginx , it's not the issue for LobeChat
