### ISSUE TITLE
[Request] 支持AWS bedrock的Claude 3 API调用 

### ISSUE THREAD

**Issue by leoleelxh** [lobehub/lobe-chat#1511]
### 🥰 需求描述

已经链接了AWS bedrock，但是claude模型的选择上，只有2.1和1.2版本，不支持claude3？
![image](https://github.com/lobehub/lobe-chat/assets/4277749/26da1a65-d71c-4b68-977d-b516c45dd552)

而在AWS上，我已开头cladude3：
![image](https://github.com/lobehub/lobe-chat/assets/4277749/87080ffe-62a0-4ce6-9d7c-172910182c34)

### 🧐 解决方案

支持AWS bedrock的claude3模型

**Comment by liangyimingcom** [comment]
The Issue can be repro in my environment, pls take a investigate.
