### ISSUE TITLE
[Request] Add choice for chat summary

### ISSUE THREAD

**Issue by atlas5301** [lobehub/lobe-chat#1512]
### 🥰 Feature Description

We currently choose gpt-3.5-turbo and gpt-4-turbo-preview to summarize the chat and generate the title. However, is it possible that we can use other model providers to do such thing? 

### 🧐 Proposed Solution

Maybe we can add a select box for these functions, just as the one in 'default agent'.

**Comment by arvinxx** [comment]
Yes we will add this feature

**Comment by arvinxx** [comment]
we have support with system agent: https://github.com/lobehub/lobe-chat/discussions/2600
