### ISSUE TITLE
[Request] Custom model for all api providers

### ISSUE THREAD

**Issue by atlas5301** [lobehub/lobe-chat#1513]
### 🥰 Feature Description

Currently, we only support custom models for openai api. However, chances are that other model providers may release new models and users are willing to use custom models. It's beneficial to support custom models for all other model providers.

### 🧐 Proposed Solution

Add a similar Custom Model Name box to all other model providers, just like what we've done to openai models.

**Comment by arvinxx** [comment]
you are right. I will consider an common design to handle this feature
