### ISSUE TITLE
[Bug] ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production

### ISSUE THREAD

**Issue by chree188** [lobehub/lobe-chat#1514]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
这个问题怎么解决呀  sharp依赖安装成功依然报错

**Comment by arvinxx** [comment]
我试了下我们的镜像似乎没有这个问题。你是自己打的吗

**Comment by chree188** [comment]
> 我试了一下我们的镜像似乎没有这个问题。你是自己打的吗

我是自己打包部署的，难道是我的Dockerfile写的有问题？

**Comment by arvinxx** [comment]
@chree188 应该是的，自己检查下 dockerfile 吧。
