### ISSUE TITLE
[Bug] 无法检索到ollama

### ISSUE THREAD

**Issue by dandandujie** [lobehub/lobe-chat#1516]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

我在vercel部署了最新版本lobechat，windows版本的ollama已经安装好并且下载了mistral模型。但是我打开网页登录lobechat，在设置里并没有ollama这个板块

### 🚦 Expected Behavior

应该能找到ollama板块然后设置url和model

### 📷 Recurrence Steps

我在vercel部署了最新版本lobechat，windows版本的ollama已经安装好并且下载了mistral模型。但是我打开网页登录lobechat，在设置里并没有ollama这个板块

**Comment by arvinxx** [comment]
看下文档：https://chat-docs.lobehub.com/zh/usage/features/local-llm  ，暂不支持 Vercel

**Comment by alexleft** [comment]
> 看下文档：https://chat-docs.lobehub.com/zh/usage/features/local-llm ，暂不支持 Vercel

I can't find the Ollama option on the settings page. 
I use the latest Docker image and deploy it on my local Linux server.
![image](https://github.com/lobehub/lobe-chat/assets/16779585/6905b10a-b604-4c64-b7f3-7eca3e764d9a)

**Comment by arvinxx** [comment]
@alexleft you should set the OLLAMA_PROXY_URL env
