### ISSUE TITLE
[Bug] 反馈一个操作逻辑上的问题

### ISSUE THREAD

**Issue by 1355873789** [lobehub/lobe-chat#1527]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

**假如我在对话界面要进左下角的设置**

[![accfd6324302aa7bd58e05b2ee15f5dc.jpeg](https://i.piantu.cn/2024/03/11/accfd6324302aa7bd58e05b2ee15f5dc.jpeg)](https://piantu.cn/image/%E6%B5%8B%E8%AF%951.GULK)

---

**当我设置完我想要的内容后没有正式的返回按钮，所以唯一返回对话界面的方法就是点击对话按钮**

[![f49b70c3b306830799cf392b55d66974.jpeg](https://i.piantu.cn/2024/03/11/f49b70c3b306830799cf392b55d66974.jpeg)](https://piantu.cn/image/cs2.GnMH)

---

**但是这样返回后就会自动创建一个新的对话，这样使用原来的对话的话又得手动点回去**
[![63a1e3f11ad0fe74b234106504eb1141.jpeg](https://i.piantu.cn/2024/03/11/63a1e3f11ad0fe74b234106504eb1141.jpeg)](https://piantu.cn/image/cs3.G2ms)

---

### 🚦 期望结果

加一个返回按键哈哈哈，当然只不过是一个不痛不痒的问题，习惯性提下issue
[![cd2cdd63b7aad1025338199d43d4111b.jpeg](https://i.piantu.cn/2024/03/11/cd2cdd63b7aad1025338199d43d4111b.jpeg)](https://piantu.cn/image/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE-20240311031901.GH6p)

### 📷 复现步骤

如描述

**Comment by arvinxx** [comment]
我优化下点回去的逻辑吧，理论上不应该切到新话题那边

**Comment by arvinxx** [comment]
@1355873789 新的设置方案应该可以解决你的问题了
