### ISSUE TITLE
[Request] Deployment template for Railway

### ISSUE THREAD

**Issue by tiangao88** [lobehub/lobe-chat#1528]
### 🥰 Feature Description

Can you please make a deployment template for Railway.app ?
Thanks!

### 🧐 Proposed Solution

https://docs.railway.app/guides/create#starting-from-scratch

**Comment by arvinxx** [comment]
Good idea !

**Comment by tiangao88** [comment]
Any chance someone can take this?
It would bring more users and therefore more testers for a better product 😀

**Comment by arvinxx** [comment]
here it is: https://railway.app/template/FB6HrV?referralCode=9bD9mT

**Comment by tiangao88** [comment]
> ✅ @tiangao88
> 
> This issue is closed, If you have any questions, you can comment and reply. 此问题已经关闭。如果您有任何问题，可以留言并回复。

Just deployed and it works perfectly. Thank you very much 🙏
