### ISSUE TITLE
bug好多，历史对话切换一下，就没了，反应也贼慢[Bug] 

### ISSUE THREAD

**Issue by 1137882300** [lobehub/lobe-chat#1531]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

同样的open key，在其他套壳里。就可以回到当前日期，在这里就不行！！！

### 🚦 期望结果

反应要快，历史对话要保留，同样的问题，同样的key，在其他地方套壳里就能正常回答。

**Comment by arvinxx** [comment]
> 历史对话切换一下，就没了

看看右侧: https://chat-docs.lobehub.com/zh/usage/agents/concepts

> 在其他套壳里。就可以回到当前日期，在这里就不行！！！

请描述清楚你的问题，我看不懂你在说什么。

**Comment by devyujie** [comment]
+1，性能贼差，建议好好优化下。

**Comment by arvinxx** [comment]
@devyujie 请给出你觉得性能差的地方？

**Comment by s7monk** [comment]
> @devyujie 请给出你觉得性能差的地方？

我认为确实如此，在使用过程中，确实有时候比较慢，从一个比如从发现切刀会话要反映一会，可能确实是哪里有渲染影响性能的地方。

**Comment by s7monk** [comment]
> @devyujie 请给出你觉得性能差的地方？

我认为确实如此，在使用过程中，确实有时候比较慢，比如从发现tab切换回会话要等一会，可能确实是哪里有渲染影响性能的地方。

**Comment by arvinxx** [comment]
> 慢得明显的是插件窗口，打开关闭时的动画非常不流畅

这个有计划优化，我自己也发现了

> 或者给一个加载动画，显示目前正在加载

我回头看看有没有方法搞

**Comment by MapleEve** [comment]
> > 慢得明显的是插件窗口，打开关闭时的动画非常不流畅
> 
> 这个有计划优化，我自己也发现了
> 
> > 或者给一个加载动画，显示目前正在加载
> 
> 我回头看看有没有方法搞

要么做一个带动效的骨架屏吧，本地部署的嗷嗷快，如果走外网切换话题确实有点慢了

**Comment by arvinxx** [comment]
我在 #1736 尝试通过重构 layout 的实现来提升页面切换的性能，大家可以测试下看看

**Comment by arvinxx** [comment]
@BrandonStudio I will try

**Comment by lee88688** [comment]
@arvinxx 
在`/chat`页面 -> 扩展插件 -> 插件商店 点击后会有明显的等待时间才会打开弹窗，关闭弹窗也会存在这个问题。在本地开发环境看了一下，打开弹窗时多个（50几个）PluginItem一次性渲染，用JavaScript performance查看发现有一半多的时间都在`antd-style`的createStyles，这里面竟然又有接近一半的时间在复制theme的属性。
https://github.com/ant-design/antd-style/blob/4187b95fa654e8d4725c69517789e675c6c28a52/src/factories/createStyles/index.ts#L60
打个断点看了一眼theme这个对象，竟然有800多个属性😂，所以只要用了css-in-js创建style每次创建组件（这些操作是在useMemo中完成）这800多属性的theme就会被复制一次，PluginItem这种同时渲染很多组件的场景性能问题就会被放大。就目前看到的情况，这个css-in-js库有可能时拖累整个页面性能问题的帮凶。
最后在production的编译后使用performance获取到的信息和development类似，具体数值有些变化，但复制theme和创建css-in-js创建style会耗费大量的时间。

**Comment by arvinxx** [comment]
@lee88688 你的分析有点问题，和 antd-style 没啥关系。单纯是列表数据过多，一次性渲染出来比较卡而已。换成虚拟滚动就好了

**Comment by lee88688** [comment]
@arvinxx 此外在关闭弹窗时也会出现延迟，从调试工具看在关闭的时候又重新渲染了这个列表，感觉有点奇怪从上到下都是memo的组件，按道理不应该在关闭的时候出现整个列表的重渲染。

**Comment by arvinxx** [comment]
@BrandonStudio 已优化，可以再试试了 

 @lee88688 同样关闭慢的问题也解决了

**Comment by arvinxx** [comment]
@BrandonStudio 你需要的是哪里有动画？顶部加载进度条吗？还是什么

**Comment by Greasen** [comment]
> <img alt="image" width="1290" src="https://private-user-images.githubusercontent.com/31413093/319005742-d5dee7e7-f619-4cb3-b8cb-677d3c9c2516.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzUyNzEsIm5iZiI6MTcxMjEzNDk3MSwicGF0aCI6Ii8zMTQxMzA5My8zMTkwMDU3NDItZDVkZWU3ZTctZjYxOS00Y2IzLWI4Y2ItNjc3ZDNjOWMyNTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5MDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNGJjNGMxYzYyMjkzM2I4ZjkyZDc1YWRmMmVlMTY1Y2Q5NDYzYTJhNzE1NTY4ZmRkZWVmMWZkNDdlZDUxMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lO5GwlqGEBH4tEyeAFYsTtErreSGoxIS0Jym-YtPsY8">
> @arvinxx Vercel在当前main分支打包失败

更新一下版本
