### ISSUE TITLE
Groq不能支持

### ISSUE THREAD

**Issue by worras2019** [lobehub/lobe-chat#1532]
### 🥰 需求描述

现在输入Groq的自定义域名、token及自定义模型名称（比如mixtral-8x7b-32768）会出错。
{
  "error": {
    "message": "The model `gpt-3.5-turbo` does not exist or you do not have access to it.",
    "type": "invalid_request_error",
    "code": "model_not_found"
  },
  "endpoint": "https://api.***.com/openai/v1",
  "provider": "openai"
}

### 🧐 解决方案

支持Groq

**Comment by hugoyue** [comment]
> ### 🥰 需求描述
> 现在输入Groq的自定义域名、token及自定义模型名称（比如mixtral-8x7b-32768）会出错。 { "error": { "message": "The model `gpt-3.5-turbo` does not exist or you do not have access to it.", "type": "invalid_request_error", "code": "model_not_found" }, "endpoint": "https://api.***.com/openai/v1", "provider": "openai" }
> 
> ### 🧐 解决方案
> 支持Groq
> 
> ### 📝 补充信息
> _No response_

支持的模型是 llama2-70b-4096、 mixtral-8x7b-32768 吧
