### ISSUE TITLE
[Request] 希望在设置菜单中的‘接口代理地址’那里增加一个开关，用来选择该代理地址是只用于自定义模型，还是所有模型都生效

### ISSUE THREAD

**Issue by ccdanpian** [lobehub/lobe-chat#1534]
### 🥰 需求描述

背景：目前我默认部署用的是三方代理A，代理A不支持claude-3。 所以我在设置里手动添加了代理B（openrouter.ai），自定义模型里也手动添加了claude-3。

问题和需求：我不希望没有手动写在自定义模型里的gpt3.5、gpt4那些模型也走代理B，希望他们自己用默认的代理A。

### 🧐 解决方案

在设置菜单中的‘接口代理地址’那里增加一个开关，用来选择该代理地址是只用于自定义模型
![image](https://github.com/lobehub/lobe-chat/assets/130242490/72cdc146-bf3d-49e4-a708-c38e2deca9b1)

**Comment by arvinxx** [comment]
这个需求感觉不太合理。你能自己搞一个oneapi 去做下游代理的整合吗？

**Comment by ccdanpian** [comment]
对于我这样的用户来说太难太复杂了，还不如运行两个应用来的简单。

或者可以这样吗？ 每家的api，可以支持第三方代理。比如说claude，也可以像chatgpt一样，在设置里或者环境变量里，配置第三方代理。

**Comment by arvinxx** [comment]
> 或者可以这样吗？ 每家的api，可以支持第三方代理。比如说claude，也可以像chatgpt一样，在设置里或者环境变量里，配置第三方代理。
> 
> 前两天在discussion里也说了这个需求。

这个问题我之前想过，主要的问题是可能不一定符合用户预期，比如假设我只是使用透明代理来使用 google ，和我使用oneapi 代理使用google ，这两种背后的调用模式是不一样的。

前者是直接走的lobechat 的转换逻辑，而后者是用的oneapi的转换逻辑。

**Comment by ccdanpian** [comment]
大概能理解您的逻辑并且直接使用官方服务肯定效率上是最好的，不过对于大部分国内用户来说，很容易就会被封掉账户，所以还是希望lobechat能给提供一个好用又简洁elegant的解决方法。

**Comment by arvinxx** [comment]
@ccdanpian OpenRouter 已经支持~
