### ISSUE TITLE
[Request] glm模型怎样使用插件

### ISSUE THREAD

**Issue by descending-order** [lobehub/lobe-chat#1535]
### 🥰 需求描述

请问用glm-4模型调用插件不成功如何解决呀

### 🧐 解决方案

是glm和openai的接口不匹配吗，应该怎样改

### 📝 补充信息

glm-4应该怎样使用自定义插件，插件的manifest.json文件应该是什么样的

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/discussions/737#discussioncomment-8315815
