### ISSUE TITLE
会话sheet无法打开聊天窗口[Bug] 

### ISSUE THREAD

**Issue by banboo3** [lobehub/lobe-chat#1539]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Edge

### 🐛 问题描述

清理浏览器缓存后，第一次打开lobe，可以正常打开聊天窗口。但关闭页面后，再次打开lobe->设置其他模型->放回会话sheet，只能到以下页面，点击相应的会话按钮无法打开聊天窗口。
![image](https://github.com/lobehub/lobe-chat/assets/13806734/999e24f4-8d39-457b-9eff-379612d4aa25)

### 🚦 期望结果

能够正常打开聊天窗

### 📷 复现步骤

设置Gemini模型，然后返回会话页面

**Comment by arvinxx** [comment]
你这是PC还是手机…

**Comment by banboo3** [comment]
> 你这是PC还是手机…

PC window10

**Comment by arvinxx** [comment]
现在再试试呢
