### ISSUE TITLE
[Bug] 手机端无法找到历史对话记录

### ISSUE THREAD

**Issue by huicewang** [lobehub/lobe-chat#1542]
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

手机端不能看的聊天历史

### 🚦 Expected Behavior

可以看到聊天历史对话记录

**Comment by cy948** [comment]
这里是历史记录入口：
![image](https://github.com/lobehub/lobe-chat/assets/67412196/7cd23000-93dc-4c58-8a99-eeb2b827b2ff)

> 如果你遇到的是历史记录丢失问题，请提供更多细节以重现问题。
