### ISSUE TITLE
[Request]可以美化一下上传文件的展示图嘛，这样子也太丑了，可以不用展示图，写上上传文件名称也可以

### ISSUE THREAD

**Issue by Yanyutin753** [lobehub/lobe-chat#1543]
### 美化一下上传文件的展示图嘛，这样子也太丑了，可以不用展示图，写上上传文件名称也可以
<img width="734" alt="image" src="https://github.com/lobehub/lobe-chat/assets/132346501/b3cee809-8e28-4c0c-83ca-88f3d4a7c9bc">

### 🧐 解决方案

可以不用展示图，在下面引用上传文件名称也可以

### 📝 补充信息

感谢作者们的付出，期待能更好使用lobe-chat

**Comment by arvinxx** [comment]
上传文件没做标准化的支持。你用的是 gpt-4-all 的 hack 方案只能先这样。

**Comment by arvinxx** [comment]
@Yanyutin753 有，专门做知识库/PDF/文件上传功能的时候会正式支持。现在就先这样吧

**Comment by Yanyutin753** [comment]
感谢作者大大，期待lobechat变得更加强大哈哈哈哈
