### ISSUE TITLE
[Bug] Ollama not available anymore

### ISSUE THREAD

**Issue by thomclae33** [lobehub/lobe-chat#1544]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Other

### 🐛 Bug Description

Ollama is not available anymore in the LLM's (settings). Could this be as of the update [v0.133.5](https://github.com/lobehub/lobe-chat/releases/tag/v0.133.5)?

**Comment by zkwolf** [comment]
use ollama > 0.1.24 && openapi setting
