### ISSUE TITLE
[Request] 将本地聊天记录存储到指定目录

### ISSUE THREAD

**Issue by zhairuoxun** [lobehub/lobe-chat#1547]
### 🥰 需求描述

希望能够优化聊天记录的本地存储与备份，实现**可以自己指定聊天记录的存储目录**。

### 🧐 解决方案

有一次浏览器出了问题，清空了所有Cookies，然后再登陆网站发现之前所有的聊天记录都不见了！这样让我觉得自己的聊天记录非常不安全。如果可以自己指定本地聊天记录文件的存储目录，而非用Cookies存储，数据可能会更加稳定不易丢失。

### 📝 补充信息

我知道可以用备份功能实现，但比起每次导出备份然后再导入，显然直接存储在指定的，不会被轻易删除的目录更加安全。

**Comment by arvinxx** [comment]
清空 cookies 不会删除历史记录的

**Comment by zhairuoxun** [comment]
> 清空 cookies 不会删除历史记录的

您好！非常感谢您百忙之中的回复！

我确认了一下，确实是我疏忽了，我不仅清空了cookies，还清空了站点数据。所以我的描述并不准确。

不过我仍然认为 ** 可以自己指定聊天记录的存储目录 ** 对于我来说非常实用，因此建议开发组加入这个功能，希望可以考虑采纳，辛苦你们了，感谢你们开发了这么棒的项目！

**Comment by arvinxx** [comment]
> 不过我仍然认为 ** 可以自己指定聊天记录的存储目录 ** 对于我来说非常实用，因此建议开发组加入这个功能

我们后续会支持同步方案 （ #1525 ） 。但是指定存储目录这个需求在浏览器端实现应该是不太现实的

**Comment by zhairuoxun** [comment]
> > 不过我仍然认为 ** 可以自己指定聊天记录的存储目录 ** 对于我来说非常实用，因此建议开发组加入这个功能
> 
> 我们后续会支持同步方案 （ #1525 ） 。但是指定存储目录这个需求在浏览器端实现应该是不太现实的

好的，我了解了，期待同步功能，感谢你们的付出！~

**Comment by ccdanpian** [comment]
请教一下，有的时候反应特别慢，感觉应该主要出现在新建对话和进入历史对话时，和这个存储有关系吗？

**Comment by Lockeysama** [comment]
> > 不过我仍然认为 ** 可以自己指定聊天记录的存储目录 ** 对于我来说非常实用，因此建议开发组加入这个功能
> 
> 我们后续会支持同步方案 （ #1525 ） 。但是指定存储目录这个需求在浏览器端实现应该是不太现实的

我使用的一个开源笔记本软件 [Logseq](https://demo.logseq.com/#/repo/add) 的 Web 端好像看到过这个实现，如果后续有计划的话，可以参考下这个👍🏻
