### ISSUE TITLE
[Request] 暴露出一个接口，可以提供任何应用调用

### ISSUE THREAD

**Issue by XiaoMo-Donald** [lobehub/lobe-chat#1557]
### 🥰 需求描述

我想在其他的应用上调用这个接口来提供同样的聊天的能力

### 🧐 解决方案

能否在这个应用基础上暴露出一个接口，方便提供给其他应用程序使用呢？（因为这个可以部署在vercel上就已经不需要魔法了，然后通过绑定的域名再把接口转发给我自己的应用进行调用）。

当然我知道这个做起来的话 可能需要考虑到接口授权问题，不然的话任何人只要知道了你的接口都可以使用。

但是还是很想要这样的一个功能，或者不知道大佬们有没有什么其他的解决方案或者其他开源的项目可以不需要魔法部署就可以实现任何应用（包括网站、app）调用openai的接口。

当然啦，还是因为这个开源项目已经集成了比较多类型的模型，一个接口，方便任意切换任何模型而不需要改动和适配其他应用端的接口

**Comment by arvinxx** [comment]
现在已经有 /api/chat/[provider] 这个接口了，但这个目前还主要是给lobe-chat 本身自己用的。还没考虑开放api问题。

但你需要的话为啥不用 oneapi 这种呢？

**Comment by ckt1031** [comment]
有更大風險給予其他人直接調用LobeChat公益站

ChatUI應該做他該做的, 而不是做OneAPI/FastGPT

**Comment by DayDreammy** [comment]
我也有类似的需求。说一下为什么。因为lobechat有海量的插件，而oneapi是没用的，相对而言fastGPT又有一点厚重，且插件不是很多。
个人觉得开放一个端口供其他应用调用是很好的。
