### ISSUE TITLE
[Request] [体验建议] 发送消息后，Chat 自动滚动到最下方

### ISSUE THREAD

**Issue by scarqin** [lobehub/lobe-chat#1558]
### 🥰 需求描述

发送消息后，用户的关注点会放到最新的消息
![image](https://github.com/lobehub/lobe-chat/assets/15225835/de9eb1e0-7663-4b30-b9d2-8deb4216d52f)

### 🧐 解决方案

建议自动滚动到最新发送的消息处，等待回复

**Comment by arvinxx** [comment]
有道理，后续优化下~
