### ISSUE TITLE
[Request] Function calling for gemini-pro

### ISSUE THREAD

**Issue by sherlcok314159** [lobehub/lobe-chat#1561]
### 🥰 Feature Description

Gemini-pro now supports function calling. But I fail to do it in lobe-chat

### 🧐 Proposed Solution

Here is the detailed description of the function calling.

https://ai.google.dev/docs/function_calling

**Comment by sherlcok314159** [comment]
更新到最新的 lobe-chat，可是这个我似乎不知道该怎么用

<img width="583" alt="图片" src="https://github.com/lobehub/lobe-chat/assets/76043326/5bb23572-c370-44cb-a142-891f43a30de3">

我选择了 gemini-pro，但插件根本不让选，是否是相关逻辑还没处理好

**Comment by laye0619** [comment]
升级到最新版本后，其它的新增支持插件调用的模型可以的，但是google的pro，1.5等还是不行

<img width="958" alt="image" src="https://github.com/lobehub/lobe-chat/assets/9484313/3d5ca0d5-ea5d-47bd-87ef-b9864b20c0b7">

**Comment by laye0619** [comment]
> 升级到最新版本后，其它的新增支持插件调用的模型可以的，但是google的pro，1.5等还是不行
> 
> <img alt="image" width="958" src="https://private-user-images.githubusercontent.com/9484313/329830276-3d5ca0d5-ea5d-47bd-87ef-b9864b20c0b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0OTU2NDgsIm5iZiI6MTcxNTQ5NTM0OCwicGF0aCI6Ii85NDg0MzEzLzMyOTgzMDI3Ni0zZDVjYTBkNS1lYTVkLTQ3YmQtODdlZi1iOTg2NGIyMGMwYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTJUMDYyOTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFiMzJmMThmYTUzNzY1OTIzMzI1MGQ1MjllODM5YTAwMzFlMjFhYjVlZTQ5YzUzNGZiNWMzNTAyMGQ4MTJmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.41nxJT4WZZkAl9W42X8f3kOSW9S6KYaBfjAYgmtJCS0">

@sherlcok314159

**Comment by arvinxx** [comment]
@laye0619 准确来说应该是 google 的 gemini-pro 的Function Calling 能力不行，虽然官方说支持，但是基本上等于不可用。

**Comment by laye0619** [comment]
明白了，十分感谢！

Regards,
Laye
