### ISSUE TITLE
[Request] Dify provider

### ISSUE THREAD

**Issue by QIN2DIM** [lobehub/lobe-chat#1563]
### 🥰 需求描述

能否有任何一种方法，可以将 Dify 暴露出来的后端接口集成到 lobe-chat 中。

 

### 🧐 解决方案

目前（以 Claude3 为例）：

```graphql
(User) --> (LobeChat) --> (RealProvider)

```

预期：
```graphql
(User) --> (LobeChat) --> (DifyAPI) --> (RealProvider)

```

- 很久之前有在 lobe-chat 提过知识库的需求，但这个议题早已 inactive 了。

- Dify 上可以做更多的除 prompt 之外的编排工作。如果可以接入 DifyAPI 的话，相当于曲线套壳，接入了更丰富的生态。

- 目前 lobe-chat 的软件架构很灵活，公共商店的插件更新和新提供商的集成速度非常快。但也因为灵活性放弃了接入 pg 和 Milvus 之类的知识库基础设施。但类似 Dify，fastgpt 对外暴露了接口可以在其他地方接入知识库的功能。

### 📝 补充信息

DifyAPI 暴露的操控聊天应用（智能体）的接口并不是兼容性的 OpenAI 接口，返回类型和请求参数都不一样。所以直接改环境变量的 `OPENAI_PROXY` 和 `OPENAI_API_KEY` 不起作用。

**Comment by arvinxx** [comment]
1. dify 是否有 OpenAI ChatCompetition 兼容接口？有的话可以当成一个 Provider 来集成，欢迎到 https://github.com/lobehub/lobe-chat/discussions/1284 这里提需求。
2. 知识库这块在今年的 Roadmap 里，如果只是希望使用知识库的话，可以等等

**Comment by fatwang2** [comment]
dify 没有 OpenAI 格式的接口
