### ISSUE TITLE
[Request] Add support for Cloudflare AI

### ISSUE THREAD

**Issue by BrandonStudio** [lobehub/lobe-chat#1566]
### 🥰 Feature Description

Add support for not only chat models, but also embedding, image-generating, tts, etc. via plugin for Cloudflare AI

### 🧐 Proposed Solution

Add Cloudflare AI chat models for backend, and other models for plugins.

### 📝 Additional Information

Cloudflare provides [various AI models](https://developers.cloudflare.com/workers-ai/models/) as well as [generous free allocation](https://developers.cloudflare.com/workers-ai/platform/pricing/). It is very exciting to take advantage of it.

**Comment by arvinxx** [comment]
please add request in https://github.com/lobehub/lobe-chat/discussions/1284

**Comment by arvinxx** [comment]
> alternative TTS and speech recognition service

Ok, it's a good idea. I can reopen it.

**Comment by arvinxx** [comment]
As currently we have lanuched the cloudflare provider, we can close the issue now
