### ISSUE TITLE
[Request] 希望支持AWS Bedrock Claude 3系列模型 | Hope to support AWS Bedrock Claude 3 series model.

### ISSUE THREAD

**Issue by AreChen** [lobehub/lobe-chat#1568]
### 🥰 需求描述

AWS上线了CLAUDE 3,希望可以使用AWS进行接入CLAUDE 3!相比于官方接口来说更加稳定且方便付费及管理

### 🧐 解决方案

可以在部署时为claude指定服务商!

### 📝 补充信息

![image](https://github.com/lobehub/lobe-chat/assets/20765464/e0e27e2e-146d-4776-aa63-31f00278178f)
https://aws.amazon.com/bedrock/

**Comment by arvinxx** [comment]
已经支持了 #1551
