### ISSUE TITLE
[Request] Support external database, for self-hosted version

### ISSUE THREAD

**Issue by jasongitmail** [lobehub/lobe-chat#1573]
### 🥰 Feature Description

Using IndexDB browser storage has a couple limitations: 
1. User's data could get deleted by clearing the browser's site data.
2. Chat history, agents, settings, etc are not available across devices–e.g. laptop and mobile.

The option to connect a hosted, serverless-compatible database would solve this, e.g.:
- [VercelSQL](https://vercel.com/storage/postgres) (1 free DB on free plan)
- [NeonDB](https://neon.tech/ ) (1 free DB)
- [Cloudflare D1](https://developers.cloudflare.com/d1/ ) (generous free tier) and [Cloudflare Vectorize](https://developers.cloudflare.com/vectorize/)

VercelSQL (based on NeonDB) & NeonDB (based on Postgres) both support vector embeddings, which would allow for RAG too. 

### 🧐 Proposed Solution

This would require user authentication. 

- For a single-user instance, this could be a Personal Access Token, i.e. a random string defined as an environment variable, that LobeChat prompts the user for once, stores locally in browser storage, and sends with requests to the LobeChat instance to store or retrieve chat history. (probably works for 95% of people)
- For a multi-user instance, user accounts would be required. (You could define a list of allowed users as an env var comma-concatenated string or similar to prevent public registrations and limit it to just family/friends, or allow anyone to register if not specified. Each account should provide it's own API keys, so you could keep LobeChat's current API key handling and just ask the user enter their API keys on each device that they use.) _Update: I see OpenAI key is prompted for during Vercel deployment, so this might need to be done differently, I haven't looked at the code._

This way if the browser's site data is cleared, no chat history or agents are lost and it can be shared across devices; only the API keys would need to be re-entered.

**Comment by andrewluetgers** [comment]
this would be nice

**Comment by julianbrennum** [comment]
Yes, this would be nice. But I don't think it need to be serverless. MongoDB, Postgres etc would be fine. It would also be nice if the "login" interface was the first thing the user was getting if they are not logged in.

**Comment by AdamsGH** [comment]
> Yes, this would be nice. But I don't think it need to be serverless. MongoDB, Postgres etc would be fine. It would also be nice if the "login" interface was the first thing the user was getting if they are not logged in.

Fully agree with you, really miss login button and spent some time to find it

**Comment by arvinxx** [comment]
Database Server DB Guide：https://lobehub.com/docs/self-hosting/advanced/server-database
