### ISSUE TITLE
[Bug] Build failure on Vercel

### ISSUE THREAD

**Issue by jasongitmail** [lobehub/lobe-chat#1574]
### 💻 Operating System

Other Linux

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

Build fails on Vercel. With lobe-chat at commit `6adb2d6`

> ./src/app/chat/(desktop)/features/ChatInput/Footer/index.tsx
> 10:45:11.420 | 59:36  Warning: 'expand' is defined but never used. Allowed unused args must match /^_/u.  unused-imports/no-unused-vars
> 10:45:11.421 |  
> 10:45:11.421 | ./src/app/chat/(desktop)/features/ChatInput/TextArea.tsx
> 10:45:11.421 | 34:39  Warning: 'expand' is defined but never used. Allowed unused args must match /^_/u.  unused-imports/no-unused-vars
> 10:45:11.421 |  
> 10:45:11.421 | ./src/store/chat/slices/plugin/action.ts
> 10:45:11.421 | 90:13  Warning: Empty block statement.  no-empty
> 10:45:11.422 |  
> 10:45:11.424 | info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
> 10:45:12.029 | Failed to compile.
> 10:45:12.030 |  
> 10:45:12.030 | ./src/app/settings/llm/Anthropic/index.tsx:58:10
> 10:45:12.030 | Type error: Type '{ color: string; size: number; }' is missing the following properties from type 'Pick<SVGProps<SVGSVGElement>, "string" \| "filter" \| "fill" \| "values" \| "type" \| "id" \| "name" \| "style" \| "from" \| "children" \| "clipPath" \| "mask" \| ... 457 more ... \| "onPointerLeaveCapture">': onPointerEnterCapture, onPointerLeaveCapture
> 10:45:12.030 |  
> 10:45:12.030 | 56 \|       provider={providerKey}
> 10:45:12.031 | 57 \|       title={
> 10:45:12.031 | > 58 \|         <Anthropic.Text
> 10:45:12.031 | \|          ^
> 10:45:12.031 | 59 \|           color={theme.isDarkMode ? theme.colorText : Claude.colorPrimary}
> 10:45:12.031 | 60 \|           size={18}
> 10:45:12.031 | 61 \|         />
> 10:45:12.326 | error: script "build" exited with code 1
> 10:45:12.332 | Error: Command "bun run build" exited with 1
> 10:45:13.966

**Comment by EricLeeaaaaa** [comment]
Same problem here 👀👀👀

**Comment by senja24** [comment]
Facing same issue here 😅

**Comment by taoya7** [comment]
Facing same issue here 😅
