### ISSUE TITLE
[Bug] 手机端似乎不能选择Enter发送还是Ctrl+Enter发送

### ISSUE THREAD

**Issue by XUANJI233** [lobehub/lobe-chat#1575]
### 💻 系统环境

Ubuntu

### 📦 部署环境

docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

手机上似乎不能选择Enter发送还是Ctrl+Enter发送，(因为没有电脑，不确定桌面端访问是否可以切换)

使用docker部署，已更新至0.135.2问题依然存在

**Comment by arvinxx** [comment]
手机端选这个配置感觉有点奇怪，所以默认做成回车换行，发送是点击了
