### ISSUE TITLE
Support Gemini 1.5 Pro

### ISSUE THREAD

**Issue by andrewluetgers** [lobehub/lobe-chat#1577]
### 🥰 Feature Description

Support Gemini 1.5 Pro. I have Gemini 1.5 Pro api access, I would like to access the full 1,048,576 token window.
<img width="392" alt="Screenshot 2024-03-14 at 11 44 53 PM" src="https://github.com/lobehub/lobe-chat/assets/232036/4c936855-b00a-4aa9-a484-58426cad1710">
<img width="510" alt="Screenshot 2024-03-14 at 11 48 54 PM" src="https://github.com/lobehub/lobe-chat/assets/232036/4a9c4202-6289-4a95-84c5-5063d35b17b9">

### 🧐 Proposed Solution

I think its just adding support for a new model / api endpoint?

**Comment by arvinxx** [comment]
are you sure you can use gemini 1.5-pro with api? Have you tried with that?

**Comment by andrewluetgers** [comment]
Ahh yes I see now, bummer, however, going forward I wonder about making this a bit more self-service so we can add new endpoints as they become available.

**Comment by arvinxx** [comment]
@andrewluetgers I think yes. relatitive issue: https://github.com/lobehub/lobe-chat/issues/1513

**Comment by ckt1031** [comment]
#1617 
https://ai.google.dev/models/gemini
