### ISSUE TITLE
[Feat/Deploy] 支持 docker 部署

### ISSUE THREAD

**Issue by arvinxx** [lobehub/lobe-chat#158]
- [ ] Docker 一键部署最小化镜像
- [ ] 配置 semantic-release Docker 插件自动发布

https://github.com/lobehub/lobe-chat/pull/283

**Comment by VectorZhao** [comment]
+1

**Comment by yangjianchuan** [comment]
```
docker run -it -p 7860:7860 --platform=linux/amd64 \
	-e OPENAI_PROXY_URL="YOUR_VALUE_HERE" \
	-e OPENAI_API_KEY="YOUR_VALUE_HERE" \
	registry.hf.space/dongsiqie-lobe-chat:latest 
```

**Comment by yangjianchuan** [comment]
我写了一个抱脸的一键部署地址：<a href="https://huggingface.co/spaces/dongsiqie/lobe-chat?duplicate=true&amp;visibility=public">lobe-chat - a Hugging Face Space by dongsiqie</a>

**Comment by arvinxx** [comment]
Docker 一键部署的镜像 正在弄，我们在研究如何将打出的镜像尺寸最小化

**Comment by yangjianchuan** [comment]
> Docker 一键部署的镜像 正在弄，我们在研究如何将打出的镜像尺寸最小化

我在抱脸上面的部署方法尺寸很大，但是写法很简单

**Comment by leeyiding** [comment]
可以参考next.js的官方示例的Dockerfile
https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

**Comment by leoleelxh** [comment]
参考大佬们的做了一个docker，文件比较大：
docker pull leoleexh/lobe-chat

默认密码：123456

**Comment by i-iooi-i** [comment]
很需要一键部署功能，持续关注，先⭐了.

**Comment by i-iooi-i** [comment]
> 参考大佬们的做了一个docker，文件比较大： docker pull leoleexh/lobe-chat
> 
> 默认密码：123456

![image](https://github.com/lobehub/lobe-chat/assets/1827701/4345f4af-f24e-4fe6-9cb7-53c7c0149882)
大佬你好，我拉取了你的Docke，想请教下环境变量中的3500端口是干啥用的哦。

**Comment by i-iooi-i** [comment]
> Docker 一键部署的镜像 正在弄，我们在研究如何将打出的镜像尺寸最小化

https://hub.docker.com/r/lobehub/lobe-chat
大佬，这个是不是你们的镜像，先拉为敬了 🫡🫡🫡

**Comment by arvinxx** [comment]
> > Docker 一键部署的镜像 正在弄，我们在研究如何将打出的镜像尺寸最小化
> 
> 
> 
> https://hub.docker.com/r/lobehub/lobe-chat
> 
> 大佬，这个是不是你们的镜像，先拉为敬了 🫡🫡🫡

是的，还有点小bug 待修复，有问题可以直接在 PR里提

**Comment by VectorZhao** [comment]
> > > Docker 一键部署的镜像 正在弄，我们在研究如何将打出的镜像尺寸最小化
> > 
> > 
> > https://hub.docker.com/r/lobehub/lobe-chat
> > 大佬，这个是不是你们的镜像，先拉为敬了 🫡🫡🫡
> 
> 是的，还有点小bug 待修复，有问题可以直接在#283 里提

木有arm镜像啊

**Comment by i-iooi-i** [comment]
> > > Docker 一键部署的镜像 正在弄，我们在研究如何将打出的镜像尺寸最小化
> > 
> > 
> > https://hub.docker.com/r/lobehub/lobe-chat
> > 大佬，这个是不是你们的镜像，先拉为敬了 🫡🫡🫡
> 
> 是的，还有点小bug 待修复，有问题可以直接在#283 里提

很棒，已经在小破群晖NAS里支楞起来了 🫡🫡🫡

- 希望可以在环境变量里面增加访问密码，以方便外网使用~
- 建议可以在变量里配置默认key和代理，这样方便给外网的家人们上手即用~

嗯嗯 我去提一下~

**Comment by VectorZhao** [comment]
> https://hub.docker.com/r/lobehub/lobe-chat

<img width="858" alt="image" src="https://github.com/lobehub/lobe-chat/assets/16644993/542e3653-1ff2-4836-a6b4-e4634f6b3d0a">

amd64是x86架构
arm64才是arm架构

**Comment by guomengran** [comment]
https://github.com/lobehub/lobe-chat/issues/158#issuecomment-1755407434
群晖怎么部署，我的能进入界面但是不能调用模型使用
