### ISSUE TITLE
[Bug] 连通性检查bug

### ISSUE THREAD

**Issue by lx1054331851** [lobehub/lobe-chat#1581]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/12423206/50160607-8c59-44c4-85d8-1ee05fc5ba3e)

通过hook检查后发现，这里在检查后URL拼接，默认的是gpt-35-turbo，而不是自己填的model name，导致连通性测试失败，但是对话是没有问题的。

**Comment by arvinxx** [comment]
这个不是bug，是当前的Azure实现局限性：https://github.com/lobehub/lobe-chat/discussions/178

**Comment by lx1054331851** [comment]
谢谢 @arvinxx
