### ISSUE TITLE
[Bug] Where is the local document path?

### ISSUE THREAD

**Issue by IMCurie** [lobehub/lobe-chat#1588]
### 💻 Operating System

Ubuntu

### 📦 Environment

Other

### 🌐 Browser

Chrome

### 🐛 Bug Description

Today I found a broken link in the documentation at https://chat-docs.lobehub.com/ and would like to submit a PR to fix it. I referred to the Wiki and tried to deploy the project locally, but I couldn't find the access path for the local documentation.

After running `bun run dev` locally, clicking the two icons at the bottom of the page takes me to https://chat-docs.lobehub.com/ instead of the local documentation path. I'm not sure if this is an issue.

Could someone please help me with this? I am a Web beginner and I would be very grateful.

![image](https://github.com/lobehub/lobe-chat/assets/122453769/b60c1113-408b-4c30-bb24-1eb13960bae4)

### 🚦 Expected Behavior

Access the local document path.

**Comment by arvinxx** [comment]
If you want to fix docs, just find docs document here: https://github.com/lobehub/lobe-chat/tree/main/docs

**Comment by arvinxx** [comment]
@IMCurie there is no this path. the document site is another repo and we don't open source it.
