### ISSUE TITLE
[Bug] moonshot模型无法使用

### ISSUE THREAD

**Issue by linkiofo** [lobehub/lobe-chat#1593]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

moonshot模型无法使用发送信息就提示如下错误：
{
  "error": {
    "cause": {}
  },
  "endpoint": "https://api.moonshot.cn/v1",
  "provider": "moonshot"
}

**Comment by arvinxx** [comment]
给个复现：

<img width="935" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/8da96eeb-2e61-417c-a3b0-319067c7014f">

**Comment by linkiofo** [comment]
![微信截图_20240319121919](https://github.com/lobehub/lobe-chat/assets/156993166/2b38fc9c-1346-447c-8c23-d9ef25d29f4f)
![微信截图_20240319123916](https://github.com/lobehub/lobe-chat/assets/156993166/f558f34d-b256-4951-852a-f4f4d67be342)
![微信截图_20240319123958](https://github.com/lobehub/lobe-chat/assets/156993166/1917b3ff-c0e9-4966-821b-39b7ac54ef8d)
检测的时候有时能通过，有时通不过不知道问题出现在那里

**Comment by linkiofo** [comment]
@arvinxx

**Comment by arvinxx** [comment]
@linkiofo 看下 docker 日志里有没有报错之类的

**Comment by linkiofo** [comment]
![微信截图_20240319151131](https://github.com/lobehub/lobe-chat/assets/156993166/6ce32d2c-a452-440a-9bbd-d2181c70da9e)
![微信截图_20240319150938](https://github.com/lobehub/lobe-chat/assets/156993166/72e2dde9-34d6-48df-9386-473f1fc456b3)
![微信截图_20240319151003](https://github.com/lobehub/lobe-chat/assets/156993166/2354192d-b39f-4b47-ab09-64b7b9be3570)
@arvinxx 会出现一推乱码

**Comment by arvinxx** [comment]
@linkiofo 你这个问题似乎是你的 docker 没法正常请求到 moonshot.cn ？检查下这个链路

**Comment by linkiofo** [comment]
@arvinxx docker不能使用shell功能没办法查链路，感觉平台应该不会屏蔽moonshot.cn，只有可能moonshot.cn屏蔽一些海外IP访问可能
