### ISSUE TITLE
手机版有3个[Bug] 

### ISSUE THREAD

**Issue by guuger** [lobehub/lobe-chat#1595]
### 💻 系统环境

iOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Safari

### 🐛 问题描述

1. 语音输入，发送以后输出框没有清除内容。
![微信图片_20240316133727](https://github.com/lobehub/lobe-chat/assets/3183544/1d078643-cb9c-400a-b992-f5d80007683b)

2、宽度适配问题
![微信图片_20240316133734](https://github.com/lobehub/lobe-chat/assets/3183544/08cc47fb-80e2-44d6-845a-16a2e54e3017)

3、翻译看不见英语选项。
![微信图片_20240316133741](https://github.com/lobehub/lobe-chat/assets/3183544/ebc7c49a-6f58-45e9-a9ea-f5b6c0044c65)

**Comment by arvinxx** [comment]
应该都已经修复了，请检查下？
