### ISSUE TITLE
[Bug] 手机端会话列表多次点击改成两次

### ISSUE THREAD

**Issue by guuger** [lobehub/lobe-chat#1599]
### 💻 系统环境

iOS

### 📦 部署环境

Official Preview

### 🌐 浏览器

Safari

### 🐛 问题描述

这个会话列表需要点击三次才能进去，严重以为坏的，普通人不会点三次。建议文字处直接单次点击，或者一次重点击就打开链接进去。或者按当前的改成2次点击也行。
![IMG_2557](https://github.com/lobehub/lobe-chat/assets/3183544/2617cd38-053e-4589-99d9-9ad14b0655be)

**Comment by jcdiv47** [comment]
这个问题我之前在discord提问过，大佬表示比较遗憾，回复说是已知的问题，所以我猜测问题已知悉，但是可能目前不太好解决？

**Comment by arvinxx** [comment]
点3次的确是bug… 最多应该点2次的
