### ISSUE TITLE
[Request] Addition of Empty New Messages Functionality

### ISSUE THREAD

**Issue by cogscides** [lobehub/lobe-chat#1604]
### 🥰 Feature Description

I am proposing the addition of a feature that allows users to insert empty new messages from both the user and the assistant within the LopeChat application. This functionality is inspired by a similar feature found in Anthropic AI's workbench, which greatly enhances the user experience by allowing for more flexible and controlled conversations with large language models. It will help to deal with long instructions rather than adding them inside a `system prompts` and add an ability to provide a few shot examples of I/O.

### 🧐 Proposed Solution

The proposed feature would enable users to add blank message slots at the end of their ongoing conversation with the language model.

![image](https://github.com/lobehub/lobe-chat/assets/50235526/155d2d68-c029-4dbc-9a6f-f0ea84257912)

**Comment by cogscides** [comment]
Later on, I thought that the similar function is possible to add just by adding "Only add AI message" under the send dropdown:
![image](https://github.com/lobehub/lobe-chat/assets/50235526/bcda57f5-3b01-484e-8708-88286932544c)

Adding several examples of communication between the user and assistant will be possible.

**Comment by arvinxx** [comment]
Yes I think so. And I will add it soon

**Comment by dalefengs** [comment]
很棒的功能
