### ISSUE TITLE
[Request] 增加Markdown数学公式渲染条件

### ISSUE THREAD

**Issue by zhairuoxun** [lobehub/lobe-chat#1609]
### 🥰 需求描述

希望`\( \)`和`\[ \]`括住的数学公式也可以渲染

### 🧐 解决方案

ai助手在涉及到公式时，经常首选利用 `\[  \]`和`\( \)`来将公式括住，而lobechat往往只把用`$$`括住的公式渲染，因此经常会导致很多公式可读性很差，希望可以考虑调整

**Comment by zhuozhiyongde** [comment]
确实是一个好建议，虽然我之前一直采用 prompt 的方式来提示它，但是还是有概率出现这种情况。

**Comment by zhuozhiyongde** [comment]
不过有一说一，这个修改似乎和渲染方式有关，如果现在的解析是基于正则的，那非常好改，但是如果是基于成熟的 md AST 解析框架，可能就会比较难弄了（没看过代码

**Comment by zhairuoxun** [comment]
> 不过有一说一，这个修改似乎和渲染方式有关，如果现在的解析是基于正则的，那非常好改，但是如果是基于成熟的 md AST 解析框架，可能就会比较难弄了（没看过代码

我不懂开发，所以技术困难什么的确实不清楚，只是使用过程中遇到了，试着提出来，希望对软件完善有所帮助。

我确实也是一直用prompt来解决这个问题的，但是在助手市场中很多助手都没有给这样的prompt，导致经常需要增加要求，并且修改以后AI助手还不一定能记住，所以这个也还是合理的，希望开发者们可以考虑吧

**Comment by zhuozhiyongde** [comment]
即使要做，我认为这也应该是一个附加的可选 docker 参数或者设置项，而非一个默认的配置项，因为我们不清楚是否存在别的输入/输出会有这样的格式，这种格式的确是 latex 的标准格式，但是不是 markdown 的标准格式。

**Comment by arvinxx** [comment]
和 https://github.com/lobehub/lobe-chat/issues/1602#issuecomment-2002297449 一起考虑吧。后面搞一个专门的配置页用于设置各种 markdown 语法的渲染效果。

**Comment by zhuozhiyongde** [comment]
> 和 [#1602 (comment)](https://github.com/lobehub/lobe-chat/issues/1602#issuecomment-2002297449) 一起考虑吧。后面搞一个专门的配置页用于设置各种 markdown 语法的渲染效果。

其实我见过有同时支持选择 纯文本/Markdown/LaTeX 之一渲染的前端（逃

**Comment by zhairuoxun** [comment]
> 即使要做，我认为这也应该是一个附加的可选 docker 参数或者设置项，而非一个默认的配置项，因为我们不清楚是否存在别的输入/输出会有这样的格式，这种格式的确是 latex 的标准格式，但是不是 markdown 的标准格式。

嗯嗯，这样比较好！

**Comment by arvinxx** [comment]
> 其实我见过有同时支持选择 纯文本/Markdown/LaTeX 之一渲染

是指三选一还是同时渲染？

**Comment by zhuozhiyongde** [comment]
> > 其实我见过有同时支持选择 纯文本/Markdown/LaTeX 之一渲染
> 
> 
> 
> 是指三选一还是同时渲染？

三选一

**Comment by MapleEve** [comment]
> > 其实我见过有同时支持选择 纯文本/Markdown/LaTeX 之一渲染
> 
> 是指三选一还是同时渲染？

应该是思源的三选一，这个没办法（也没必要）同时渲染。

**Comment by Wxh16144** [comment]
> 和 [#1602 (comment)](https://github.com/lobehub/lobe-chat/issues/1602#issuecomment-2002297449) 一起考虑吧。后面搞一个专门的配置页用于设置各种 markdown 语法的渲染效果。

https://github.com/lobehub/lobe-chat/issues/1620 这个问题也可以关联起来，属于同一类型反馈

**Comment by MoonWeSif** [comment]
> 确实是一个好建议，虽然我之前一直采用 prompt 的方式来提示它，但是还是有概率出现这种情况。

你好，我在使用的时候也遇到了类似的问题，方便问一下prompt应该如何编写吗，对于前端上数学表达式的渲染问题了解的不多

**Comment by zhuozhiyongde** [comment]
> > 确实是一个好建议，虽然我之前一直采用 prompt 的方式来提示它，但是还是有概率出现这种情况。
> 
> 你好，我在使用的时候也遇到了类似的问题，方便问一下prompt应该如何编写吗，对于前端上数学表达式的渲染问题了解的不多

```
{{text}}

注意事项:
- 如果你需要用到公式或数学表达式，请在输出中使用符合 Markdown 语法的 LaTeX 表达式, 即用美元符号 $ 包裹行内公式, 用双美元符号 $$ 包裹块级公式。
```

**Comment by zhuozhiyongde** [comment]
临时解决方案：

1. 复制出来结果
2. 执行正则替换

正则替换：

1. `(\\\(\s*|\s*\\\))` 替换为 `$`
2. `\\[\[\]]` 替换为 `$$`

**Comment by canisminor1990** [comment]
感觉可以在助手设置里加一个配置项

**Comment by canisminor1990** [comment]
ref issues: 
- https://github.com/lobehub/lobe-chat/issues/2911
- https://github.com/lobehub/lobe-chat/issues/2651
- https://github.com/lobehub/lobe-chat/issues/2070
- https://github.com/lobehub/lobe-chat/issues/2494

ref solution: 
- https://github.com/remarkjs/react-markdown/issues/785

**Comment by canisminor1990** [comment]
ref `@lobehub/ui`: https://github.com/lobehub/lobe-ui/pull/168
