### ISSUE TITLE
[Bug] 移动端UI宽度超过575px时无法打开聊天界面

### ISSUE THREAD

**Issue by TonyBlur** [lobehub/lobe-chat#1612]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

实测当移动端UI宽度超过575px（即从576px开始及以上）时无法打开聊天界面，点击后仍然在原页面不动
可能是和桌面端UI的宽度判定存在冲突

### 🚦 期望结果

当页面宽度超过575px时切换为桌面端UI或支持移动端UI的宽度超过575px

### 📷 复现步骤

如图所示，在移动端UI的前提下，使之宽度超过575px
![image](https://github.com/lobehub/lobe-chat/assets/101348912/5d2b5c9b-5eae-481b-b48c-6bafa9d69431)

**Comment by arvinxx** [comment]
没太看明白你的需求

**Comment by TonyBlur** [comment]
> 没太看明白你的需求

感谢回复
不好意思，我之前的描述可能不够清晰，这是一个bug，就是在安卓平板的尺寸下，无法打开聊天界面
我初步研究后发现，是因为平板的浏览器会默认以移动端的UI显示该网页，而移动端的页面宽度大于等于576px时会导致无法打开聊天界面，这个bug可以在电脑浏览器上通过开发工具复现

**Comment by TonyBlur** [comment]
该问题在当前版本(0.142.7)已修复，可以据情况关闭当前issue
