### ISSUE TITLE
[Request] Support for http_proxy inside

### ISSUE THREAD

**Issue by saccohuo** [lobehub/lobe-chat#1613]
### 🥰 Feature Description

I deploy lobe-chat on my NAS with docker, and cannot connect to outsea LLM service from China.
There are socks proxy service and http proxy service working on my NAS. 
I wanna know how can I run lobe-chat behind my http_proxy. 

### 🧐 Proposed Solution

Support for explicit http_proxy for each LLM service.

**Comment by MapleEve** [comment]
自己填写一个 Docker Compose 并设置  http_proxy，具体流程可以询问GPT

**Comment by hcaihao** [comment]
> 自己填写一个 Docker Compose 并设置 http_proxy，具体流程可以询问GPT

试过不行

**Comment by bit649** [comment]
我也遇到了同样的问题，希望能支持http_proxy

**Comment by coulsontl** [comment]
同样的问题，希望能支持http_proxy +1

**Comment by newptcai** [comment]
I have proxy running locally with URL like http://127.0.0.1:xxxx.

If I install docker version of lobechat, how can I make it use to this proxy? If I put http://127.0.0.1:xxxx into PROYX_URL, I got an error which says the connection is refused.

**Comment by bit649** [comment]
> 我在本地运行代理，其 URL 如http://127.0.0.1:xxxx。
> 
> 如果我安装了 docker 版本的 lobechat，我怎样才能让它使用这个代理？如果我将http://127.0.0.1:xxxx放入PROYX_URL 中，则会收到一条错误，表示连接被拒绝。

lobechat的PROYX_URL指的不是本机代理，而是反向代理服务器。建议你再部署一个oneapi：https://github.com/songquanpeng/one-api
oneapi里生成一个令牌，填到lobechat的PROYX_URL即可

**Comment by SAnBlog** [comment]
我也遇到了同样的问题，希望能支持http_proxy

**Comment by cui-daniel** [comment]
试试我写的这个工具，也许对你有帮助 https://github.com/cui-daniel/chatgpt-api-proxy
