### ISSUE TITLE
[Request]請支援 Gemini 1.5api

### ISSUE THREAD

**Issue by Liu12God** [lobehub/lobe-chat#1617]
### 🥰 需求描述

Gemini 1.5已經開放申請api一段時間了，也有不少人拿到了api，所以請支援更長上下文的Gemini 1.5api，謝謝！
![Screenshot_20240318_005033_Chrome](https://github.com/lobehub/lobe-chat/assets/163758657/d454ec06-f49c-48df-a7c8-7401408861e9)

### 🧐 解决方案

新增Gemini 1.5api選項

**Comment by pzcn** [comment]
只是web页面的控制台进行测试，似乎并没有提供api的调用。

**Comment by MapleEve** [comment]
Gemini 1.5 谷歌官方还没有提供任何API可以调用

**Comment by ckt1031** [comment]
https://ai.google.dev/models/gemini

![Screenshot_2024-03-21-15-11-13-897_org mozilla firefox](https://github.com/lobehub/lobe-chat/assets/65409152/2df02eee-df93-4cae-8995-e4df33c1ad72)
