### ISSUE TITLE
lobe-chat fails to use ollama

### ISSUE THREAD

**Issue by fazhang-master** [lobehub/lobe-chat#1618]
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

{
  "error": {
    "headers": {
      "content-length": "18",
      "content-type": "text/plain",
      "date": "Mon, 18 Mar 2024 00:50:25 GMT"
    },
    "stack": "Error: 404 404 page not found\n    at eP.generate (/app/.next/server/edge-chunks/261.js:4:1754)\n    at sp.makeStatusError (/app/.next/server/edge-chunks/261.js:4:13675)\n    at sp.makeRequest (/app/.next/server/edge-chunks/261.js:4:14598)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async J.chat (/app/.next/server/edge-chunks/353.js:1:11187)\n    at async eh (/app/.next/server/edge-chunks/353.js:1:18173)\n    at async /app/.next/server/edge-chunks/212.js:6:64195\n    at async O.execute (/app/.next/server/edge-chunks/212.js:6:61088)\n    at async O.handle (/app/.next/server/edge-chunks/212.js:6:65462)\n    at async ey.handler (/app/.next/server/edge-chunks/212.js:7:31644)",
    "status": 404
  },
  "endpoint": "http://192.168.***.6:****/",
  "provider": "ollama"
}

### 📝 Additional Information

![image](https://github.com/lobehub/lobe-chat/assets/89283399/095e8353-f0e1-4279-ba58-09b46f3c8246)

**Comment by arvinxx** [comment]
try with `/v1` ?
