### ISSUE TITLE
[Bug] 在CUSTOM_MODELS配置中无法正确指定openrouter的自定义模型名称

### ISSUE THREAD

**Issue by wangxiaodong1021** [lobehub/lobe-chat#1624]
### 💻 系统环境

Other

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

我同时配置了OPENAI_PROXY_URL与OPENROUTER_API_KEY。我在修改CUSTOM_MODELS参数中指定openrouter的付费模型，如“anthropic/claude-3-haiku:beta”，会被误识别为OPENAI的模型接口调用

> 

### 🚦 期望结果

希望CUSTOM_MODELS解析规则中，增加对OPENROUTER_API的二级解析策略。比如：
openrouter/anthropic/claude-3-haiku:beta

**Comment by arvinxx** [comment]
我倾向添加一个OPENROUTER_CUSTOM_MODELS， cc @danielglh

**Comment by danielglh** [comment]
@arvinxx 我其实觉得对于 openrouter 这种模型巨多的，用环境变量配置并不太合适。openrouter 最好要有一个 model selector。当然，加一个环境变量并不麻烦，是可以加。

**Comment by arvinxx** [comment]
> 我其实觉得对于 openrouter 这种模型巨多的，用环境变量配置并不太合适。openrouter 最好要有一个 model selector。当然，加一个环境变量并不麻烦，是可以加。

环境变量的目的是给预设，我觉得是合理的。 model selector 是提供全量选择能力，两者不冲突
