### ISSUE TITLE
有兴趣将后端接口 api 开放出来不

### ISSUE THREAD

**Issue by thinker007** [lobehub/lobe-chat#1626]
### 🥰 需求描述

可以对接其他的端 比如 app

### 🧐 解决方案

后端接口 api 化

**Comment by arvinxx** [comment]
这个对我们的 API 设计能力要求比较高，目前可能还不到这个时机

**Comment by thinker007** [comment]
> 这个对我们的 API 设计能力要求比较高，目前可能还不到这个时机

感谢您的回复，现在已经有类似的 api 了，但是没有好的 ui
https://github.com/cheshire-cat-ai/core
