### ISSUE TITLE
[Bug] 路由跳转有些问题

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#163]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

在移动端视图的时候有些页面进不去，比如随便聊聊，点了下面自定义助手后再点随便聊聊才能进去。然后点设置页，就退不出来了。

https://github.com/lobehub/lobe-chat/assets/29084441/b5398f6f-fb90-431d-94d0-c3f809348479

退出移动视图后，侧边栏就消失了，感觉响应式这块的路由设计还要再考虑一下。

https://github.com/lobehub/lobe-chat/assets/29084441/2e13a36f-7d7d-49ce-8b1d-d2173fdb9dc6

**Comment by mushan0x0** [comment]
https://github.com/lobehub/lobe-chat/assets/29084441/5a2dd176-fe26-4ef3-b5af-b358098e4388

@arvinxx 第一个问题还是存在

**Comment by arvinxx** [comment]
看了下这个问题应该是移动端下已激活的 list 点击无法正常切换。这个再修下
