### ISSUE TITLE
I don't use ollama in lobechat

### ISSUE THREAD

**Issue by fazhang-master** [lobehub/lobe-chat#1633]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

![WechatIMG174](https://github.com/lobehub/lobe-chat/assets/89283399/12359d2b-af35-4c9a-9fe7-a80deed16366)
![WechatIMG173](https://github.com/lobehub/lobe-chat/assets/89283399/c1a56d71-cf67-4833-a5b4-9ebf3c82c5b3)
![image](https://github.com/lobehub/lobe-chat/assets/89283399/03ff7629-d43a-4c56-958b-00faba291d10)

### 🚦 期望结果

first, i can run 127.17.0.1:11434,but i don't use ollama in lobechat.my ollama run use OLLAMA_HOST=0.0.0.0 ollama serve,lobechat run use docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://192.168.31.6:11434 lobehub/lobe-chat.

**Comment by fazhang-master** [comment]
sorry ,系统环境 ubantu22.04,部署环境 docker

**Comment by okwinds** [comment]
mac一样用不了，配置http://host.docker.internal:11434/v1 or http://127.0.0.1:11434/v1 or http://localhost:11434/v1都不行

**Comment by arvinxx** [comment]
@fazhang-master 试试
```
lobechat run use docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://192.168.31.6:11434/v1 lobehub/lobe-chat.
```

**Comment by fazhang-master** [comment]
> @fazhang-master 试试加个 `v1`
> 
> ```shell
> $ docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://192.168.31.6:11434/v1 lobehub/lobe-chat
> ```

![image](https://github.com/lobehub/lobe-chat/assets/89283399/a32d081e-3ddd-458f-9303-4c0be2316b99)
![image](https://github.com/lobehub/lobe-chat/assets/89283399/4459cd4e-776e-47e3-a280-79cb2dd7ae6e)
![image](https://github.com/lobehub/lobe-chat/assets/89283399/0dfcaae5-ffb3-46b5-a2d4-cbacb67da0ef)
![image](https://github.com/lobehub/lobe-chat/assets/89283399/abeb632e-f73a-4dbb-b7f9-144164a1779f)

**Comment by fazhang-master** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > @fazhang-master 试试加个 `v1`
> > ```shell
> > $ docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://192.168.31.6:11434/v1 lobehub/lobe-chat
> > ```
> 
![image](https://github.com/lobehub/lobe-chat/assets/89283399/b56fb7aa-f406-4597-93c6-67b2f40ba0ad)
![image](https://github.com/lobehub/lobe-chat/assets/89283399/ef767461-98a5-4ae4-8b7c-6a338581f5c6)
![image](https://github.com/lobehub/lobe-chat/assets/89283399/d820c99b-a029-41e1-a5ae-1032c9e114b0)
![image](https://github.com/lobehub/lobe-chat/assets/89283399/9f97f147-d5de-4006-a616-1125cbdb2905)

**Comment by lyg5597122** [comment]
@fazhang-master 我遇到和你一样的问题。MacOS，本地部署ollama,docker运行lobechat。虽然setting-language model里ollama部分check是通过的，但是在agent对话中，依然报错“Error: connect ECONNREFUSED 127.0.0.1:11434”。 我检查lobechat日志，如下：Route: [ollama] OllamaBizError:  [TypeError: fetch failed] {
  cause:  [Error: connect ECONNREFUSED 127.0.0.1:11434] {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 11434
}
}
Route: [openai] NoOpenAIAPIKey: { error: undefined, errorType: 'NoOpenAIAPIKey' }

**Comment by williamchai** [comment]
You need to use “host.docker.internal” as ollama address. See https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container

**Comment by clusterpj** [comment]
I am experiencing the same issue, but I have noticed something additional on my end.

I have been experimenting extensively with several Ollama servers and Lobe-chat. Initially, I had an Ollama server running on port 11434. However, after encountering some issues, I reinstalled Ollama, and it now runs on port 11345. I typically run Ollama using the "ollama serve" command, which allows me to see the server's running status. Regardless of the port I configure in the Lobe-chat settings for Ollama, it always indicates that the Ollama connection is active and automatically populates Ollama models that no longer exist on my system.

Even when the connection check passes, attempting to prompt the model consistently results in the same error:

Error requesting Ollama service, please troubleshoot or retry based on the following information
json
{
  "error": {
    "cause": {
      "errno": -111,
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "127.0.0.1",
      "port": 11435
    }
  },
  "endpoint": "http://127.0.***.1:****/v1",
  "provider": "ollama"
}

**Comment by rudolfolah** [comment]
What worked for me was running `ollama serve` and then turning on the "Use Client-Side Fetching Mode" setting. From the ollama server logs, it appears the URL is different. When the setting is off it's `/v1/api/chat`, which doesn't work. When the setting is on, the URL is `/api/chat` and does work.

**Comment by lizzzcai** [comment]
when i try `$ docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://host.docker.internal:11434 lobehub/lobe-chat` (without `v1`) without `Client-Side Fetching Mode`, it is working.

**Comment by fazhang-master** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/89283399/c6082d34-35f3-4e25-9d26-3b7053c40b94)
![image](https://github.com/lobehub/lobe-chat/assets/89283399/69f95e52-7e9b-4209-9767-57b4c1d5420d)
![image](https://github.com/lobehub/lobe-chat/assets/89283399/e5324675-1077-44ed-b48b-5b7cda69484e)
Ollama is running locally, not in Docker. However, after running the lobe-chat Docker container using the following command:docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://127.0.0.1:11434 lobehub/lobe-chat。the check passes, but chatting still fails. The command curl http://127.0.0.1:11434 works successfully, and running ollama run llama3:8b also works correctly.

**Comment by arvinxx** [comment]
@Frankymuc I think you are wrong, lobechat is a free gui. It's your issue that you don't know how to use it and others play with fun. . Just a pity for you
