### ISSUE TITLE
[Bug] Safari code block overflow

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#1635]
### 💻 系统环境

macOS

### 📦 部署环境

Official Preview

### 🌐 浏览器

Safari

### 🐛 问题描述

Safari（异常）：

![image](https://github.com/lobehub/lobe-chat/assets/36695271/8303d47f-ca95-4a1a-800f-8341fb9835c3)

Chrome（正常）：

![image](https://github.com/lobehub/lobe-chat/assets/36695271/8f5611aa-00ef-4aef-a6c9-1a76a074e08a)

如图。在 Chrome 测试正常，在 Safari 异常。

测试用例：

```bash
#!/usr/bin/zsh
cd /home/ubuntu/Mx-Space/shiro
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
git fetch origin

# 尝试合并，如果遇到冲突则退出
git merge origin/main --no-gpg-sign -m "merge latest" || {
    echo "Merge conflict detected, aborting script."
    exit 1
}

# 如果合并成功，继续执行后续命令
nrm use taobao
rm -rf ./node_modules/
pnpm i
pnpm build && pm2 delete Shiro && pnpm prod:pm2
```

### 🚦 期望结果

正常折行

**Comment by zhuozhiyongde** [comment]
临时解决方案：降级到 v0.138.1
Temporary solution: Downgrade to v0.138.1

**Comment by canisminor1990** [comment]
fixed https://github.com/lobehub/lobe-ui/commit/14bea77da4a0ae3beaccfa1ab68c998cc0a77dcb, wait for redeploy @arvinxx
