### ISSUE TITLE
[Bug] 聊天窗口代码片段中没有滑条也没有自动换行

### ISSUE THREAD

**Issue by zhengjianyang** [lobehub/lobe-chat#1638]
### 💻 系统环境

macOS

### 📦 部署环境

Official Preview

### 🌐 浏览器

Safari

### 🐛 问题描述

代码片段中没有滑条也没有自动换行，如果其中一行特别长的话会把聊天窗口的宽度无限拉长，就会看不全信息

### 🚦 期望结果

代码片段中出现左右滑条可以查看遮挡的信息，固定聊天窗口的宽度
或者代码片段中自动换行并带行号区分

### 📷 复现步骤

随便让机器人回复一句特别长的话在```代码片段中

**Comment by zhuozhiyongde** [comment]
Same as https://github.com/lobehub/lobe-chat/issues/1635

**Comment by zhuozhiyongde** [comment]
Temporary solution: Downgrade to v0.138.1

**Comment by canisminor1990** [comment]
修复中

**Comment by canisminor1990** [comment]
fixed https://github.com/lobehub/lobe-ui/commit/14bea77da4a0ae3beaccfa1ab68c998cc0a77dcb, wait for redeploy @arvinxx
