### ISSUE TITLE
[Bug] -all,+gpt-4-turbo-preview后，助手默认的版本竟然还是gpt-3.5-turbo？这个怎么改改？

### ISSUE THREAD

**Issue by itcodes** [lobehub/lobe-chat#1656]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

我已经用CUSTOM_MODELS去限制了，但是助手默认还是gpt-3.5-turbo

**Comment by arvinxx** [comment]
查阅文档：https://chat-docs.lobehub.com/zh/self-hosting/environment-variables/basic#default_agent_config
