### ISSUE TITLE
[Bug]  About vercel develop

### ISSUE THREAD

**Issue by Azhizzz** [lobehub/lobe-chat#1657]
### 💻 Operating System

macOS

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

20:50:59.419 | Running build in Washington, D.C., USA (East) – iad1
-- | --
20:50:59.585 | Cloning github.com/Azhizzz/lobe-chat (Branch: main, Commit: 5efb0b4)
20:51:00.016 | Previous build cache not available
20:51:00.205 | Cloning completed: 619.903ms
20:51:00.680 | Running "vercel build"
20:51:01.191 | Vercel CLI 33.6.1
20:51:01.695 | Running "install" command: `npx bun@1.0.31 install`...
20:51:06.960 | npm WARN exec The following package was not found and will be installed: bun@1.0.31
20:51:09.661 | bun install v1.0.31 (e2567512)
20:51:09.664 | Resolving dependencies
20:51:24.235 | Resolved, downloaded and extracted [8910]
20:51:24.236 | warn: incorrect peer dependency "stylelint@15.11.0"
20:51:24.236 |  
20:51:24.236 | warn: incorrect peer dependency "stylelint@15.11.0"
20:51:24.237 |  
20:51:24.237 | warn: incorrect peer dependency "stylelint@15.11.0"
20:51:24.237 |  
20:51:24.237 | warn: incorrect peer dependency "stylelint@15.11.0"
20:51:24.237 |  
20:51:24.237 | warn: incorrect peer dependency "@octokit/core@5.1.0"
20:51:24.238 |  
20:51:24.238 | warn: incorrect peer dependency "@octokit/core@5.1.0"
20:51:24.238 |  
20:51:24.238 | warn: incorrect peer dependency "stylelint@15.11.0"
20:51:24.238 |  
20:51:24.238 | warn: incorrect peer dependency "stylelint@15.11.0"
20:51:24.238 |  
20:51:24.239 | warn: incorrect peer dependency "@octokit/core@5.1.0"
20:51:24.239 |  
20:51:24.239 | warn: incorrect peer dependency "@octokit/core@5.1.0"

It's been stuck in this process for 10 or 20 minutes with no change to go forward

### 🚦 Expected Behavior

Successful deployment

**Comment by lirtual** [comment]
#1654 I have encountered the same issue as well. The new fix doesn't seem to have resolved the deployment problem. During deployment, the progress has been stuck at "warn: incorrect peer dependency "@octokit/core@5.1.0".

**Comment by arvinxx** [comment]
Ok, actually there is another problem with `bun@1.0.31`  , so i guess need to downgrade to 1.0.30 again😨

**Comment by Azhizzz** [comment]
> #1654 I have encountered the same issue as well. The new fix doesn't seem to have resolved the deployment problem. During deployment, the progress has been stuck at "warn: incorrect peer dependency "@octokit/core@5.1.0".#1654 我也遇到了同样的问题。新的修复程序似乎没有解决部署问题。在部署期间，进度一直停留在“警告：不正确的对等依赖项”@octokit/core@5.1.0”。

Yes, I deployed for 54 minutes with a hint at the end: Your deployment's build step did not complete within the maximum of 45min

**Comment by Azhizzz** [comment]
> #1654 I have encountered the same issue as well. The new fix doesn't seem to have resolved the deployment problem. During deployment, the progress has been stuck at "warn: incorrect peer dependency "@octokit/core@5.1.0".#1654 我也遇到了同样的问题。新的修复程序似乎没有解决部署问题。在部署期间，进度一直停留在“警告：不正确的对等依赖项”@octokit/core@5.1.0”。

Yes, I deployed for 54 minutes with a hint at the end: Your deployment's build step did not complete within the maximum of 45min

**Comment by sadokx** [comment]
This happened to me just now, how to fix it?
