### ISSUE TITLE
[Bug] 使用`browser`作为语音识别服务时出现白屏

### ISSUE THREAD

**Issue by cy948** [lobehub/lobe-chat#1660]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Edge

### 🐛 问题描述

使用`browser`作为语音识别服务时出现白屏
![image](https://github.com/lobehub/lobe-chat/assets/67412196/6b6e3bcc-9764-46b9-a1c1-502e8c38cff6)

### 🚦 期望结果

不白屏

### 📷 复现步骤

- 进入`/settings/tts`
- 语音识别服务选择 `Browser`
- 通过左侧导航栏图标返回 `/chat` 再刷新页面，或通过地址栏直接进入 `/chat`

### 📝 补充信息

![image](https://github.com/lobehub/lobe-chat/assets/67412196/1270b2e4-7c47-43da-8c09-ebe5c9e5ed9a)

**Comment by arvinxx** [comment]
相关问题：
- https://github.com/lobehub/lobe-chat/issues/761
- https://github.com/lobehub/lobe-chat/issues/703

主要原因是 @canisminor1990 之前实现不规范导致的：https://github.com/lobehub/lobe-chat/blob/43e544a3549aff9a691e3740ed8614ec13c32a29/src/hooks/useSTT.ts#L36-L61

上述写法违反 react hooks 规范了，但我一直没时间改，如果有兴趣的话欢迎来个 PR？

**Comment by cy948** [comment]
@arvinxx 好的，我先研究一下代码
