### ISSUE TITLE
[Bug] lobe-chat 在使用auth0时，即使在auth0上删除该用户,只要用户不删除浏览器记录仍能正常使用

### ISSUE THREAD

**Issue by Yanyutin753** [lobehub/lobe-chat#1661]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

## lobe-chat 在使用auth0时，即使在auth0上删除该用户,只要用户不删除浏览器记录仍能正常使用！！！
# 在一些极其特别的情况，这个问题应该要得到解决

### 🚦 期望结果

希望能定时自动刷新登录结果

### 📷 复现步骤

我测试，登录了auth0后能正常使用，然后我在auth0控制台删除该用户，该用户在不删除浏览器记录的情况下仍能正常使用

### 📝 补充信息

希望作者能尽快解决，感谢大佬们的付出！！！

**Comment by arvinxx** [comment]
你搜下 issue ，好像之前有类似的问题

**Comment by Yanyutin753** [comment]
看到了 是不是没什么好的解决办法🥹🥹🥹

**Comment by Yanyutin753** [comment]
大佬 这个有解决方案嘛

**Comment by arvinxx** [comment]
@Yanyutin753 我对 auth0 不是很了解，可能需要 @cy948 来帮忙看下

**Comment by cy948** [comment]
未来版本引入后端数据库后会实现远程下线功能。敬请期待。

**Comment by Yanyutin753** [comment]
好 因为开auth0，我想开github，google认证，方便我同学使用，然后自己写了一个插件能监控。但是发现就算删除用户，用户还是能用，后面想想还是先不用auth0了，感觉大佬们的付出，期待新功能！！！

**Comment by cy948** [comment]
@Yanyutin753 当前的会话管理不依赖数据库，所以不能进行用户管理。等 1.0 版本支持后端数据库后会一并支持这个功能。如果你很迫切需要用户管理功能，我推荐你在你的二开版本中为 NextAuth 接入 Database Adapter。NextAuth 配置位置：`/src/app/api/auth/next-auth.ts`，[Authjs](https://authjs.dev/reference/adapter/supabase) 相关文档。接入示例：
```diff
export default NextAuth({
  // 保留其他设置，并新增以下配置
+  adapter: SupabaseAdapter({
+    url: process.env.NEXT_PUBLIC_SUPABASE_URL,
+    secret: process.env.SUPABASE_SERVICE_ROLE_KEY,
+  }),
+  session: {
+    strategy: ENABLE_DATABASE ? 'database' : 'jwt',
+  },
  // ...
})
```

**Comment by arvinxx** [comment]
> 我想开github，google认证，方便我同学使用，然后自己写了一个插件能监控。但是发现就算删除用户，用户还是能用，后面想想还是先不用auth0了

@Yanyutin753 在 `0.154.0` 我们支持了使用 Clerk 作为 Auth 方案，应该能够满足你的诉求了。

**Comment by Yanyutin753** [comment]
github action 打包报错了 我刚刚看了一下

**Comment by Yanyutin753** [comment]
很强了，感谢大佬们的付出！

**Comment by xingpingcn** [comment]
我在使用GitHub的时候依然遇到这个问题，退出登录了但是用户图标还在，而且还能进行对话
