### ISSUE TITLE
[Request] Needed support for Google Gemini 1 and PaLM 2 Models from Vertex AI Studio

### ISSUE THREAD

**Issue by arunkumarakvr** [lobehub/lobe-chat#1662]
### 🥰 Feature Description

Needed support for Google Gemini 1 and PaLM 2 Models from Vertex AI Studio like Azure OpenAI Service not the ones that are already added from Google AI Studio like OpenAI Platform.

### 🧐 Proposed Solution

Leverage Vertex AI Studio APIs as like Azure OpenAI Service APIs

### 📝 Additional Information

Refer to the official site of Google Cloud Vertex AI Studio

**Comment by arvinxx** [comment]
@arunkumarakvr Please add your request in our discussion: https://github.com/lobehub/lobe-chat/discussions/1284

**Comment by arvinxx** [comment]
simmilar here: https://github.com/lobehub/lobe-chat/discussions/1284#discussioncomment-8686696
