### ISSUE TITLE
vercel fail to deploy, seems to stuck somewhere

### ISSUE THREAD

**Issue by hekmon8** [lobehub/lobe-chat#1663]
### 💻 Operating System

Ubuntu

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Other

### 🐛 Bug Description

I have tried 3 times but keep same logs. Default node 18.x and 20.x instead do not work.
![IMG_7618](https://github.com/lobehub/lobe-chat/assets/35729939/285311d3-cf8c-422a-a43f-910bcfc8a751)

**Comment by arvinxx** [comment]
Try to sync with latest

**Comment by hekmon8** [comment]
> Try to sync with latest

Fine. It works! Thx
