### ISSUE TITLE
Feedback for “配置 Auth0 身份验证服务”

### ISSUE THREAD

**Issue by ykangw** [lobehub/lobe-chat#1670]
Images are not showing on this page https://chat-docs.lobehub.com/zh/self-hosting/advanced/sso-providers/auth0

**Comment by arvinxx** [comment]
@CloudPassenger Hello, it seems the image are missing, do you know how to deal with it?

**Comment by CloudPassenger** [comment]
Oh I think that's because the screenshots were stored in my repo and I rebased it 😭 which make them lost... 

I have a backup in my personal computer but unfortunately I am on holiday right now and away from the keyboard.

I will try to restore them in these few days.

**Comment by arvinxx** [comment]
@CloudPassenger that's fine, take your time and enjoy your holiday. I'm ok with time.
