### ISSUE TITLE
Feedback for “Docker Deployment Guide”

### ISSUE THREAD

**Issue by jngjr417intel** [lobehub/lobe-chat#1671]
Do I need to change this  or use it exactly? 
I put my key in

-------
Using a Proxy Address
If you need to use the OpenAI service through a proxy, you can configure the proxy address using the OPENAI_PROXY_URL environment variable:

$ docker run -d -p 3210:3210 \
  -e OPENAI_API_KEY=sk-xxxx \
  -e OPENAI_PROXY_URL=https://api-proxy.com/v1 \
  -e ACCESS_CODE=lobe66 \
  --name lobe-chat \
  lobehub/lobe-chat

**Comment by jngjr417intel** [comment]
Thank you

**Comment by RonakSiddhpura** [comment]
**Docker Deployment Guide**

Using a Proxy Address
If you need to utilize the OpenAI service through a proxy, you can configure the proxy address using the OPENAI_PROXY_URL environment variable. Follow the steps below to integrate this feature into your Docker deployment:

Update Docker Run Command:

When running your Docker container, ensure to include the necessary environment variables. Here's an example of the docker run command:

bash
Copy code
$ docker run -d -p 3210:3210 \
-e OPENAI_API_KEY=sk-xxxx \
-e OPENAI_PROXY_URL=https://api-proxy.com/v1 \
-e ACCESS_CODE=lobe66 \
--name lobe-chat \
lobehub/lobe-chat
Replace sk-xxxx with your actual OpenAI API key and https://api-proxy.com/v1 with the URL of your proxy server.

Explanation of Environment Variables:

OPENAI_API_KEY: Your unique OpenAI API key.
OPENAI_PROXY_URL: The URL of the proxy server you intend to use.
ACCESS_CODE: Any additional access code required for authentication (if applicable).
Example Scenario:

Let's say you have an OpenAI API key sk-abc123 and you want to use a proxy server located at https://my-proxy-server.com/proxy. Your Docker run command would look like this:

bash
Copy code
$ docker run -d -p 3210:3210 \
-e OPENAI_API_KEY=sk-abc123 \
-e OPENAI_PROXY_URL=https://my-proxy-server.com/proxy \
-e ACCESS_CODE=lobe66 \
--name lobe-chat \
lobehub/lobe-chat
Adjust the values according to your specific setup.

**Comment by jngjr417intel** [comment]
Thank you. I do not think I need to use a proxy because I do have access through a proxy already to the internet.
