### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jason1024po** [lobehub/lobe-chat#1672]
### 💻 系统环境

macOS

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

左侧折叠后，展开不是很方便。因为展开按钮隐藏了，鼠标要在周围要晃对位置才显示展开按钮。

### 🚦 期望结果

1.可以显示一个透明度低的展开按钮
2.加大展开按钮点击区域。

**Comment by cy948** [comment]
同感，确实有些不直观。

**Comment by arvinxx** [comment]
最近优化下

**Comment by arvinxx** [comment]
已优化
