### ISSUE TITLE
[Request]有没有对应的API对外暴漏，因为有些业务需要使用LOBE优秀的特性，想直接调用对应的API实现

### ISSUE THREAD

**Issue by bestNiu** [lobehub/lobe-chat#1676]
### 🥰 需求描述

目前的API调用感觉参数太多了，有没有对应的API对外暴露的，方便特定的业务调用

### 🧐 解决方案

希望能把某些功能的接口对外报漏，并且简洁api参数

### 📝 补充信息

lobe业务化

**Comment by arvinxx** [comment]
你想要调用啥？chat接口比如 one-api 这种挺成熟的吧？

**Comment by LeoQuote** [comment]
我猜是想用上lobe 的插件和预设的agent，直接开始会话，包装一下给后端程序用

**Comment by MapleEve** [comment]
> 我猜是想用上lobe 的插件和预设的agent，直接开始会话，包装一下给后端程序用

那不是 langchain 的活吗
