### ISSUE TITLE
[Request] 移动端界面有点卡

### ISSUE THREAD

**Issue by reece00** [lobehub/lobe-chat#168]
### 🥰 需求描述 | Feature Description

路过试了下移动端，这点击肉眼可见的延迟，我也不知道跟点一下就重复一遍的index.zh-CN.json的200ms有没有关系

### 🧐 解决方案 | Proposed Solution

~

**Comment by arvinxx** [comment]
可能不是延迟，而是现在没有针对移动端做点击操作的优化...

如果仔细看的话，现在的交互是：点一下「hover」住列表项，再点一下才会真实触发「点击」。只有第二下点击，才会触发跳转。
