### ISSUE TITLE
This branch is 18 commits behind

### ISSUE THREAD

**Issue by Root-FTW** [lobehub/lobe-chat#1696]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

My forked version stopped updating, what can I do? it's the first time something like this has happened to me, it had been working perfectly for months.

![image](https://github.com/lobehub/lobe-chat/assets/108767514/c85e3042-dc74-40e1-bf25-e5250bf19023)

![screencapture-github-Root-FTW-lobe-chat-actions-runs-8394145006-2024-03-22-10_26_30](https://github.com/lobehub/lobe-chat/assets/108767514/be761c6b-3835-44ca-99cf-ccb23fe381cb)

**Comment by arvinxx** [comment]
@Root-FTW Just click the  Update Branch, and that's enough
![image](https://github.com/lobehub/lobe-chat/assets/28616219/522fa3bd-b75c-4ef8-868a-7464bc488730)

If you want to know more, check https://github.com/lobehub/lobe-chat/discussions/1692

**Comment by Root-FTW** [comment]
my version of lobechat is based on this guide:
https://chat-docs.lobehub.com/en/self-hosting/advanced/upstream-sync

It had always worked for months, until today, and the option you tell me about does not exist in my interface.
![image](https://github.com/lobehub/lobe-chat/assets/108767514/4b50ad56-f336-4ffb-bc07-995dd332256f)


There is no button that says "Sync Fork" :(

**Comment by arvinxx** [comment]
@Root-FTW invite me to you project, I can check for you

**Comment by Root-FTW** [comment]
> @Root-FTW invite me to you project, I can check for you

OMG done, THANKS!

**Comment by arvinxx** [comment]
Plz give me an admin role

**Comment by Root-FTW** [comment]
> Plz give me an admin role

I don't get the option to give you admin permissions. :(

**Comment by arvinxx** [comment]
@Root-FTW in settings -> Collaborators and teams

**Comment by Root-FTW** [comment]
> @Root-FTW in settings -> Collaborators and teams

![image](https://github.com/lobehub/lobe-chat/assets/108767514/3cd749c1-2dee-41a3-9ac2-4867dee0e466)
