### ISSUE TITLE
[Bug] 移动设备上助手列表无法删除

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#170]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

https://github.com/lobehub/lobe-chat/assets/29084441/5d819a2b-bf5f-490b-b4c1-380654697fd9

**Comment by canisminor1990** [comment]
@arvinxx 需要一个长按菜单的方式

**Comment by arvinxx** [comment]
列表长按挺奇怪的。一般是左右滑的吧

**Comment by canisminor1990** [comment]
> 列表长按挺奇怪的。一般是左右滑的吧

右滑只能实现删除，主要还有一些其他的操作，可以先实现长按菜单，再考虑要不要加右滑的特性，前者要用的地方比较多

**Comment by arvinxx** [comment]
我不建议在Session List 里实现长按菜单，两个点：

1. 现在 Session 的长按已经有系统交互绑定了（a 链接在 iOS 里自带了预览页面 + 其他操作的行为）

![93062f2eb01332b37379d49229b5f665](https://github.com/lobehub/lobe-chat/assets/28616219/13c9bfc6-a365-4fc0-ba84-f4e69c0afac5)

这种程度的能力我觉得是原生才能做好的，web 里做不到或者做不好。

2. 左右滑动是比较符合移动端通用交互的方式，微信、QQ都是这么搞的

![753c371441397f853b396da49a1db289](https://github.com/lobehub/lobe-chat/assets/28616219/2f6e7248-ae83-4f5d-b8bb-6d5e470d1ddf)

现成组件也有：https://mobile.ant.design/zh/components/swipe-action#%E7%A4%BA%E4%BE%8B

**Comment by arvinxx** [comment]
现有方案可以支持删除，优化方案待 1.x 后实施
