### ISSUE TITLE
[Bug] 配置界面的文本框输入太卡

### ISSUE THREAD

**Issue by BrandonStudio** [lobehub/lobe-chat#1701]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

配置界面的文本框（如API代理地址）的输入框太卡，键盘输入`anthropic`，实际到框里的可能只有`antrpc`

### 📝 补充信息

这个代理地址的输入还需要动画或者不停向服务器发信息吗？只是输个文本为什么这么卡？

**Comment by arvinxx** [comment]
因为整个 form 在重渲染。后续我优化下吧
