### ISSUE TITLE
[Bug] 奇怪的 UI 组件

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#1708]
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Safari

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/36695271/6f3913af-3e7d-4f14-9eec-69bedcb684a1)

**Comment by zhuozhiyongde** [comment]
重启之后居然没了，不知道什么情况。作者可以视情况关闭这个 issue

**Comment by zhuozhiyongde** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/36695271/e93f6674-9616-4e63-ba71-8235b81b2e58)

可以稳定复现。复现的操作是，选中 置顶的助手的第一个，即可看到这个问题。在 Safari/Chrome 下均可复现。

**Comment by zhuozhiyongde** [comment]
打扰下大佬 想知道有无后续跟进 @arvinxx

**Comment by arvinxx** [comment]
@zhuozhiyongde 会修复，是个滚动配置

**Comment by zhuozhiyongde** [comment]
看上去已经修复了？是否可以关闭此 Issue 了 @arvinxx
