### ISSUE TITLE
[Perf] 路由跳转响应太慢，移动端更明显

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#171]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

https://github.com/lobehub/lobe-chat/assets/29084441/e76789ae-135e-4ca1-81fd-46c6ef3604b4

**Comment by canisminor1990** [comment]
正在想办法优化，你用的录屏软件是哪个啊，效果挺棒的😚

**Comment by mushan0x0** [comment]
> 正在想办法优化，你用的录屏软件是哪个啊，效果挺棒的😚

用的 Screen Studio

**Comment by Yidadaa** [comment]
@canisminor1990 

Screen Studio 确实好用，准备黄金复刻一个跨平台版本 

![image](https://github.com/lobehub/lobe-chat/assets/16968934/1a435940-7158-49f3-a53c-0073c4410f3e)

**Comment by mushan0x0** [comment]
> @canisminor1990
> 
> Screen Studio 确实好用，准备黄金复刻一个跨平台版本
> 
> ![image](https://user-images.githubusercontent.com/16968934/267084537-1a435940-7158-49f3-a53c-0073c4410f3e.png)

支持，可以把价格打下来，先上 win 再上 mac🤣

**Comment by canisminor1990** [comment]
> @canisminor1990 
> 
> Screen Studio 确实好用，准备黄金复刻一个跨平台版本 
> 
> ![image](https://github.com/lobehub/lobe-chat/assets/16968934/1a435940-7158-49f3-a53c-0073c4410f3e)
> 

![Screenshot_2023-09-12-00-43-27-643_com.alibaba.android.rimet.aliding.png](https://github.com/lobehub/lobe-chat/assets/17870709/694ab3eb-eaa3-4789-a967-b74c05a96485)

**Comment by eightHundreds** [comment]
不要用react server component就行

**Comment by arvinxx** [comment]
@eightHundreds 这是个取舍。 不用 rsc 的话的确后面切换是丝滑的。但是首屏会很慢，而且难解移动端的尺寸问题。而 RSC 可以解决：
![image](https://github.com/lobehub/lobe-chat/assets/28616219/473a1c0f-53f7-485c-ad3f-9a93407ebc0b)

- #252

**Comment by mushan0x0** [comment]
[lobe.ai0x0.com](https://lobe.ai0x0.com) 用 dokcer 部署到国内服务器就很快了

**Comment by arvinxx** [comment]
@mushan0x0 还真挺快的。有做什么额外的优化吗？还是直接部署了

**Comment by mushan0x0** [comment]
@arvinxx 就直接用国内阿里云服务器部署就很快，整个项目本身的优化就很好了，没有做额外的优化 👍

**Comment by arvinxx** [comment]
@mushan0x0 你的文档查询这块 怎么做的？有没有兴趣来开源贡献一波？正好有社区用户愿意付费开发文档会话插件

<img width="1188" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/b7f4d8d4-d3cb-4181-a98a-f1f9c1b88161">

**Comment by mushan0x0** [comment]
@arvinxx fastgpt 似乎最主要是靠的 https://github.com/pgvector/pgvector 来实现的

**Comment by kalicyh** [comment]
> @canisminor1990 
> 
> Screen Studio 确实好用，准备黄金复刻一个跨平台版本 
> 
> ![image](https://github.com/lobehub/lobe-chat/assets/16968934/1a435940-7158-49f3-a53c-0073c4410f3e)
> 

今天看到有人复刻了支持win，特意回来留言https://www.demoget.com/
