### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by tulong66** [lobehub/lobe-chat#1713]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

正常安装完了后，open-ai/google的API-key设定后，LobeHub的反应不正常啊？该如何解决啊？具体如下图。
![image](https://github.com/lobehub/lobe-chat/assets/13995023/54e80aca-bdb9-4d6b-920f-33c03ef59ab4)
![image](https://github.com/lobehub/lobe-chat/assets/13995023/fbadce70-529e-480e-86da-776a059d7ffd)

**Comment by MapleEve** [comment]
返回都是你的用量用完了
