### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Yym04201** [lobehub/lobe-chat#1715]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

![1711269131287](https://github.com/lobehub/lobe-chat/assets/164730841/6a241213-2b35-4166-910b-fc491d257b77)
无法使用lobechat 即便更换为cloud模型，也是上述错误

**Comment by arvinxx** [comment]
这个看上去似乎是你的api token 用尽了呀…

**Comment by Yym04201** [comment]
那咋办捏，不是说lv2用户可以任意使用吗



发自我的iPhone


------------------ Original ------------------
From: Arvin Xu ***@***.***&gt;
Date: Sun,Mar 24,2024 4:58 PM
To: lobehub/lobe-chat ***@***.***&gt;
Cc: Yym04201 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [lobehub/lobe-chat] [Bug]  (Issue #1715)





 
这个看上去似乎是你的api token 用尽了呀…

**Comment by arvinxx** [comment]
那你问这个服务供应商，lobe chat 只是一个前端ui
