### ISSUE TITLE
如何在环境变量设置限制历史消息数和开启历史消息长度压缩阈值 我查看了DEFAULT_AGENT_CONFIG好像没这个值[Request] 

### ISSUE THREAD

**Issue by cokice** [lobehub/lobe-chat#1717]
### 🥰 需求描述

作者大大如何在环境变量设置限制历史消息数和开启历史消息长度压缩阈值 我查看了DEFAULT_AGENT_CONFIG好像没这个值

### 🧐 解决方案

是要如何设置  还是说暂时还没做这个功能

**Comment by XiaolongYang-HZAU** [comment]
有相同的问题

**Comment by cokice** [comment]
> 有相同的问题

这是我的设置 你参考下
DEFAULT_AGENT_CONFIG="enableHistoryCount=true;historyCount=13;enableCompressThreshold=true;compressThreshold=8"
