### ISSUE TITLE
[Bug] iOS 上的一些界面问题

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#172]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

- [ ] 1. 标题文字显示不全，被裁切了一部分
- [ ] 2. 下方提交按钮显示不全

![IMG_ABB048385DA1-1](https://github.com/lobehub/lobe-chat/assets/29084441/bfd3f705-81d8-4007-a422-409f5e3cdf28)

- [ ] 3. 没有屏蔽弹簧效果，Next-web 不会有这个问题

https://github.com/lobehub/lobe-chat/assets/29084441/f0e4d7e3-e081-4238-afe7-4daee19e2991

- [ ] 4. 没有禁用移动端缩放

https://github.com/lobehub/lobe-chat/assets/29084441/f2188f17-2d69-401b-80ab-22dca8dc4a4f

- [ ] 5. 清空会话消息确认弹窗异常

![IMG_0893](https://github.com/lobehub/lobe-chat/assets/29084441/6c1598b1-8769-471e-8201-431318d78548)

- [ ] 6. 移动端点击这个保存为话题没有反馈提示

<img width="342" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/46c5de99-5116-49dc-8095-52794463e8ad">

- [ ] 7. 移动端输入框内容无法换行
- [ ] 8. 移动端输入框换行提示是 PC 上的提示

**Comment by mushan0x0** [comment]
- [ ] 3. 没有屏蔽弹簧效果，Next-web 不会有这个问题


https://github.com/lobehub/lobe-chat/assets/29084441/f0e4d7e3-e081-4238-afe7-4daee19e2991

**Comment by canisminor1990** [comment]
感谢反馈，目前移动端还有很多地方没适配好
