### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by supeer-shz** [lobehub/lobe-chat#1720]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

你好，我在电脑端部署了。换一个电脑打开网址，为什么还得重新设置apikey？谢谢。

**Comment by arvinxx** [comment]
这是一个本地应用，配置都存在本地的。
