### ISSUE TITLE
[Bug] 使用GPT-4 Turbo Preview，经常回复中断不能完整的输出，需要输入继续才能继续输出

### ISSUE THREAD

**Issue by zsychn** [lobehub/lobe-chat#1722]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Other

### 🐛 问题描述

使用GPT-4 Turbo Preview，经常出现一段回复不能完整的输出，需要输入继续才能继续输出，多次出现。

### 🚦 期望结果

完整的回复问题，不会中断。

### 📷 复现步骤

使用GPT-4 Turbo Preview，提问，比如提问“轻断食会导致脱水的原理”

### 📝 补充信息

![WX20240325-113707@2x](https://github.com/lobehub/lobe-chat/assets/23525693/f6b60ebb-b81d-4431-ab97-8e0607d5c5b6)

**Comment by zsychn** [comment]
![WX20240325-120456@2x](https://github.com/lobehub/lobe-chat/assets/23525693/a0d629c9-3588-48eb-866f-6ecee4e4e6e0)
使用gpt-4-0125-preview  相对流畅很多。

**Comment by arvinxx** [comment]
感觉这个和模型有关系，和 LobeChat 似乎无关？

**Comment by MapleEve** [comment]
GPT 自带的 4096token 的限制，有些模型必须发继续

**Comment by zsychn** [comment]
不知道有没有关系，用其他的客户端，不需要发继续就能正常收到不中断。

**Comment by arvinxx** [comment]
重复 #1379
