### ISSUE TITLE
[Bug] 部署完毕后，报错

### ISSUE THREAD

**Issue by tolshao** [lobehub/lobe-chat#1727]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

新人，没什么部署经验，没定位到问题在哪里，api在gpt-next-chat在vercel的部署可以用的，
vercel的域名是cloudflare挂的cdn
自己部署的proxy-url在ios的opencat上也能用，感谢大佬
报错如下：
{
  "error": {
    "headers": {
      "cache-control": "private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0",
      "connection": "keep-alive",
      "content-length": "15",
      "content-type": "text/plain; charset=UTF-8",
      "date": "Mon, 25 Mar 2024 06:17:28 GMT",
      "expires": "Thu, 01 Jan 1970 00:00:01 GMT",
      "referrer-policy": "same-origin",
      "x-frame-options": "SAMEORIGIN"
    },
    "stack": "Error: 520 error code: 520\n    at (vc/edge/function:131:5262)\n    at (vc/edge/function:134:6423)\n    at (vc/edge/function:134:7367)\n    at (vc/edge/function:190:36145)\n    at (vc/edge/function:190:53998)\n    at (vc/edge/function:122:98393)\n    at (vc/edge/function:122:95159)\n    at (vc/edge/function:122:99689)\n    at (vc/edge/function:123:32581)\n    at (vc/edge/function:123:3753)",
    "status": 520
  },
  "endpoint": "https://openai-proxy.to****ao.top/openai/v1",
  "provider": "openai"
}

### 📷 Recurrence Steps

变量部署了api、proxy-url和gemini的api，结果都一样，有时候是source 400的错误

### 📝 Additional Information

chrome、safari都试过，不行

**Comment by luojiyin1987** [comment]
520 错误代码表示网关超时，服务器在作为代理或网关时收到了无效的响应。 gpt-next-chat的 BASE_URL  是？  
lobe-chat 中的   OPENAI_PROXY_URL 是什么 ？   两种是不一样的

**Comment by tolshao** [comment]
见笑了，我这里文本文件出故障了，后面多了个乱码符号，不知道这里有没有可能做校验

Thanks @ Regards！

Tolshao

**Comment by luojiyin1987** [comment]
那关闭 issue
