### ISSUE TITLE
[Request] 在会话页面添加`不进行markdown渲染`的开关

### ISSUE THREAD

**Issue by one-pyy** [lobehub/lobe-chat#1728]
### 🥰 需求描述

在会话页面中, 有时会输入或输出xml格式, 如果进行markdown渲染则无法显示其中的字符

[Claude官方 - 使用xml tag进行提示工程](https://docs.anthropic.com/claude/docs/use-xml-tags)

### 🧐 解决方案

在会话页面添加`不进行markdown渲染`的开关

### 📝 补充信息

lobe-chat太强辣! 感谢开发者让孩子能用上api!

**Comment by MapleEve** [comment]
你可以先尝试在 Agent prompt 中加入输出规范

**Comment by arvinxx** [comment]
重复 https://github.com/lobehub/lobe-chat/issues/3858#issuecomment-2373640837
