### ISSUE TITLE
[Bug] 带下拉框的按钮点击后下拉框都会抖动一下

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#173]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

https://github.com/lobehub/lobe-chat/assets/29084441/a2777dc8-8476-494e-a4ff-b86e4ef610fa

### 🚦 期望结果 | Expected Behavior

不抖动

**Comment by canisminor1990** [comment]
目前已知是 Antd 组件的问题

**Comment by arvinxx** [comment]
> 目前已知是 Antd 组件的问题

@canisminor1990 
和 豆酱确认了，不是 antd 组件的问题。是因为现在的按钮有缩放导致的，正常的 antd 按钮不会造成抖动问题。我建议默认所有操作按钮默认去掉缩放吧，要开启加 props 来开启。

**Comment by mushan0x0** [comment]
应该可以在图标外面套一个正常大小的元素，然后只缩放图标

**Comment by canisminor1990** [comment]
我修一下

**Comment by canisminor1990** [comment]
fixed in https://github.com/lobehub/lobe-ui/commit/3a165403016c21636de640313def4d1d2605044b
