### ISSUE TITLE
[Request] 内置一些助手

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#174]
### 🥰 需求描述 | Feature Description

点击新建聊天后，显示一些内置的助手以供选择

<img width="387" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/d60316b5-4826-47f5-8e67-b8b480bce3ff">

### 🧐 解决方案 | Proposed Solution

类似于 Next-web 的面具

**Comment by mushan0x0** [comment]
可能跟 #142 重复

**Comment by canisminor1990** [comment]
正在开发中，😚 如果你有什么好用的助手提示词也可以在这里提交：https://github.com/lobehub/lobe-chat-agents

**Comment by arvinxx** [comment]
助手市场已发布~ 欢迎前来体验：

<img width="1840" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/4009982a-f05b-4334-9da0-4fb222d21a79">

**Comment by arvinxx** [comment]
@mushan0x0 另外补充一下，这里的大部分角色都是我们实际在用的角色，比如 zustand 相关的。 LobeChat 中的不少 slice 代码，都是里面的角色直接生成的

**Comment by mushan0x0** [comment]
> @mushan0x0 另外补充一下，这里的大部分角色都是我们实际在用的角色，比如 zustand 相关的。 LobeChat 中的不少 slice 代码，都是里面的角色直接生成的

确实很实用，看得出来是花了很多心思的👍
