### ISSUE TITLE
[Bug] 前端界面跳转url错误

### ISSUE THREAD

**Issue by zzy347964399** [lobehub/lobe-chat#1740]
### 💻 系统环境

Windows

### 📦 部署环境

Other

### 🌐 浏览器

Edge

### 🐛 问题描述

首页https://lobehub.com/home
点击“Get Started”，跳转的是
https://chat.lobehub.ocm
最后三个字母错了
![Uploading 111.png…]()

**Comment by arvinxx** [comment]
已修复
