### ISSUE TITLE
[Bug] 思维导图插件原作者删库后提示异常

### ISSUE THREAD

**Issue by barry2323** [lobehub/lobe-chat#1743]
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Other

### 🐛 问题描述

思维导图插件原作者删库后提示异常，插件无法卸载，不停弹窗

### 🚦 期望结果

卸载思维导图插件

### 📷 复现步骤

如果曾经安装思维导图插件问题会重复出现

**Comment by arvinxx** [comment]
@barry2323 为啥无法卸载

**Comment by kpchen** [comment]
+1, that error alert is really annoying .

**Comment by TonyBlur** [comment]
> @barry2323 为啥无法卸载

![Screenshot_2024-03-28-16-37-52-961_com.microsoft.emmx-edit.jpg](https://github.com/lobehub/lobe-chat/assets/101348912/d44afd38-da1d-4633-b001-bc7a073e6470)

如上图所示，菜单按钮位置一直在转圈，没有卸载按钮

**Comment by Moonlit7** [comment]
The service has been restored, I am sorry that the job order was not maintained in time
