### ISSUE TITLE
[Bug] gemini 模型 不会正常扮演助手

### ISSUE THREAD

**Issue by sao-coding** [lobehub/lobe-chat#1745]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

有寫提示詞的情況下無法作用
![image](https://github.com/lobehub/lobe-chat/assets/58339015/61d44c8d-9c16-4bab-b4b3-1f5e09f4deda)
![image](https://github.com/lobehub/lobe-chat/assets/58339015/a28200b6-b7d6-494c-b7be-5eb27c0e98a3)

### 🚦 Expected Behavior

![image](https://github.com/lobehub/lobe-chat/assets/58339015/1e852b92-475e-4ef3-a462-4523a3fae7b4)

使用其他語言模型就可以

**Comment by MapleEve** [comment]
curl https://generativelanguage.googleapis.com/v1beta/models?key=XXXX
查询下你的账号到底有没有 1.5 的使用权，有使用权的账号会收到谷歌的邮件的。

**Comment by sao-coding** [comment]
> curl https://generativelanguage.googleapis.com/v1beta/models?key=XXXX 查询下你的账号到底有没有 1.5 的使用权，有使用权的账号会收到谷歌的邮件的。

我發現我沒有 1.5 的使用權，但 gemini pro , gemini-pro-vision 的模型 也一樣不支援助手

**Comment by MapleEve** [comment]
> > curl https://generativelanguage.googleapis.com/v1beta/models?key=XXXX 查询下你的账号到底有没有 1.5 的使用权，有使用权的账号会收到谷歌的邮件的。
> 
> 我發現我沒有 1.5 的使用權，但 gemini pro , gemini-pro-vision 的模型 也一樣不支援助手

<img width="1887" alt="image" src="https://github.com/lobehub/lobe-chat/assets/1845053/9acb2037-742e-4421-acf3-b7265c6bca86">
毫无问题……

**Comment by sao-coding** [comment]
> > > curl https://generativelanguage.googleapis.com/v1beta/models?key=XXXX 查询下你的账号到底有没有 1.5 的使用权，有使用权的账号会收到谷歌的邮件的。
> > 
> > 
> > 我發現我沒有 1.5 的使用權，但 gemini pro , gemini-pro-vision 的模型 也一樣不支援助手
> 
> <img alt="image" width="1887" src="https://private-user-images.githubusercontent.com/1845053/317187776-9acb2037-742e-4421-acf3-b7265c6bca86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDA1MTksIm5iZiI6MTcxMTU0MDIxOSwicGF0aCI6Ii8xODQ1MDUzLzMxNzE4Nzc3Ni05YWNiMjAzNy03NDJlLTQ0MjEtYWNmMy1iNzI2NWM2YmNhODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMTE1MDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRmZmVjMTg0MzRhMTRhOWJkYWIwNWQ3NmIzOGQwNDk3YWNjZjRiY2IwMDAyNmYyOTA2OGEwZWIwNmU0NmVmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HeTxrPtB1e6XnIoOvg7kPX0TAW8hJ6hcUa22qmNP8t0"> 毫无问题……

https://github.com/lobehub/lobe-chat/assets/58339015/9ff4a335-a120-4b55-90bd-a8dd17117994

你是直接給他提示詞不應該是這樣
他完全吃不到角色設定

**Comment by MapleEve** [comment]
你不需要给他说开始，因为这个流程对于主流模型是 GPTs 流程，他只需要完成你给他的任务就行了，所以直接给出问题

**Comment by sao-coding** [comment]
> 你不需要给他说开始，因为这个流程对于主流模型是 GPTs 流程，他只需要完成你给他的任务就行了，所以直接给出问题

如果直接問就好了 那有沒有用助手根本就沒有差了
角色提示詞是給模型角色設定做他相關的事情

![image](https://github.com/lobehub/lobe-chat/assets/58339015/a1608bbd-7d39-4626-a5cb-e7e3bee0e610)

我在 Google 把角色關鍵詞打進去他是正常運行的

**Comment by arvinxx** [comment]
应该是我的实现问题：

https://github.com/lobehub/lobe-chat/blob/aaedfa716ea6d0a48266f0572d811729c7a0a25a/src/libs/agent-runtime/google/index.ts#L141

把 system role 给过滤掉了，我后面修复下
