### ISSUE TITLE
[Bug] docker compose环境变量设置ZEROONEAI_API_KEY无效

### ISSUE THREAD

**Issue by xaya1001** [lobehub/lobe-chat#1752]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Edge

### 🐛 Bug Description

docker compose环境变量设置ZEROONEAI_API_KEY无效
docker logs 错误信息：`Route: [zeroone] InvalidZeroOneAPIKey: { error: undefined, errorType: 'InvalidZeroOneAPIKey' }`
无论是用env_file还是environment
弹出错误窗口后，输入key后就可以了

### 🚦 Expected Behavior

docker compose环境变量设置ZEROONEAI_API_KEY

**Comment by luojiyin1987** [comment]
麻烦提供对应的docker compose 文件， 敏感信息要注掉

**Comment by arvinxx** [comment]
文档里写错了，已修复： https://github.com/lobehub/lobe-chat/pull/1754
