### ISSUE TITLE
[Bug]Perplexity AI的API Key使用报错

### ISSUE THREAD

**Issue by jbswbs** [lobehub/lobe-chat#1759]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

![2024-03-27_163814](https://github.com/lobehub/lobe-chat/assets/84269659/6f016194-9b04-44e2-9551-5bdad5e3a1e9)
![2024-03-27_163919](https://github.com/lobehub/lobe-chat/assets/84269659/e7f58d96-d4ec-424f-a3c0-983ff8cc4a48)
检查通过，但使用回复乱码

**Comment by limboinf** [comment]
同样的问题
https://github.com/lobehub/lobe-chat/issues/1780

**Comment by jerome-massey** [comment]
I have the same environment (Docker and Chrome) and I'm having the same issue.  Lobe Chat [v0.147.0] 

![Screenshot 2024-04-10 235555](https://github.com/lobehub/lobe-chat/assets/47702468/fc71513e-182d-41cc-b773-e404eb4b85e7)

**Comment by limboinf** [comment]
通过代码调用是OK的，但是lobehub 就出现问题了。sonar-small-online、sonar-medium-online 模型都试了。

```python
from openai import OpenAI

messages = [
    {
        "role": "user",
        "content": (
            "美国降息最新消息"
        ),
    },
]

client = OpenAI(api_key=YOUR_API_KEY, base_url="https://api.perplexity.ai")

response = client.chat.completions.create(
    model="sonar-small-online",
    messages=messages,
)
print(response)
```

python demo.py

输出：

```python
ChatCompletion(id='806bb765-c593-4969-9375-07dcc5aab01e', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='美联储最新消息是在北京时间4月11日凌晨2点发布的，其中显示了美联储官员对美国经济、金融状况以及对货币政策路径的研判，释放了美联储降息、放慢量化紧缩的最新信号。大多数美联储官员认为，政策利率可能处于本轮紧缩周期的峰值，几乎所有联储官员认为，若经济总体发展符合他们的预期，将适合今年某个时候降息。美联储官员上月还讨论了结束缩减资产负债表的可能性。', role='assistant', function_call=None, tool_calls=None), delta={'role': 'assistant', 'content': ''})], created=7292468, model='sonar-small-online', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=194, prompt_tokens=37, total_tokens=231))
```

同样提示词：

<img width="837" alt="image" src="https://github.com/lobehub/lobe-chat/assets/4414032/702115e2-fce7-4845-8c2e-bd9ae446315e">
