### ISSUE TITLE
[Request] 增加文档解析功能

### ISSUE THREAD

**Issue by forever-lwy** [lobehub/lobe-chat#1760]
### 🥰 需求描述

我希望可以支持解析能提取文字的文件如doc、pdf、txt等，然后将提取到的文字直接放进上下文中进行简单的与文件对话。基于现在大模型普遍的长上下文，这应该是处理不太大的文件效果最好的方式。而且应该可以在没有服务端数据库的前提下实现。

### 🧐 解决方案

chatnio项目似乎是差不多的方案，或许可以参考一下。

### 📝 补充信息

无

**Comment by xiaoxuan220** [comment]
I need too
