### ISSUE TITLE
[Request] 自动获取 models

### ISSUE THREAD

**Issue by recall704** [lobehub/lobe-chat#1766]
### 🥰 需求描述

OPENAI 提供了 API 可以自动获取 models

https://platform.openai.com/docs/api-reference/models

### 🧐 解决方案

使用 api 自动获取

**Comment by recall704** [comment]
可以参考: https://github.com/danny-avila/LibreChat/blob/main/api/server/services/ModelService.js

**Comment by arvinxx** [comment]
有个很大的问题是拉过来的模型列表大部分都不是用于对话的，这个过滤成本有点高

**Comment by ckt1031** [comment]
> 有个很大的问题是拉过来的模型列表大部分都不是用于对话的，这个过滤成本有点高

可以預設一個regex正規表達式, 用戶有需求可以在環境變數自行更改
