### ISSUE TITLE
[Bug] 聊天到一半切换成Azure gpt-4-vision-preview模型，无法识别图片

### ISSUE THREAD

**Issue by Eobravo** [lobehub/lobe-chat#1778]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

和其他Azure gpt模型聊天到一半切换成Azure gpt-4-vision-preview模型，无法识别图片。如果清空聊天记录后，先和Azure gpt-4-vision-preview模型聊天，可以成功识别图片。
![Snipaste_2024-03-28_11-36-26](https://github.com/lobehub/lobe-chat/assets/93071927/88ceca7d-1316-4bc8-a223-2aa82919577c)
![Snipaste_2024-03-28_11-36-02](https://github.com/lobehub/lobe-chat/assets/93071927/6f328d86-ae4b-41b9-a955-2b04708ab464)

**Comment by arvinxx** [comment]
这个我也不知道啥情况哎…
