### ISSUE TITLE
[Bug] pplx-7b-online、pplx-70b-online 模型输出内容诡异

### ISSUE THREAD

**Issue by limboinf** [lobehub/lobe-chat#1780]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

pplx-7b-online 模型输出的内容过于诡异，我不清楚是什么导致的，温度（0.6）等其他配置都是默认的。

<img width="1039" alt="image" src="https://github.com/lobehub/lobe-chat/assets/4414032/cd8e760f-a153-4b63-9aa4-fd2edab512c9">

pplx-70b-online 也是一样

<img width="1064" alt="image" src="https://github.com/lobehub/lobe-chat/assets/4414032/3e4dad42-5f7c-44db-a79a-c8b0e2458bed">
 

### 📷 复现步骤

default agent( 随便聊聊）

input: 小米汽车什么时候发布会？价格大概多少？

**Comment by 1PercentSync** [comment]
pplx7b基于mistral7b，70b基于llama70b，本身中文能力很差，容易出现不断重复的问题，并且不是新的模型，失去了官方的支持，这里应该做的是同步pplx最新的模型 https://docs.perplexity.ai/docs/model-cards 不过问题也是显而易见的，medium甚至没有中文能力，输出的只有英文
![image](https://github.com/lobehub/lobe-chat/assets/127626920/e21a39fe-1418-4236-a967-c7c7ff3f297a)
![image](https://github.com/lobehub/lobe-chat/assets/127626920/eede462f-246a-400b-873d-b3ac56939f3e)

**Comment by 1PercentSync** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/127626920/f3ca7e18-44e6-4c36-a123-76e56cbc72d1)
sonar 7b倒是没问题

**Comment by YuChenSSR** [comment]
I had the same weirdness here, just a "hello".
我这里也是同样的诡异,只是说了一声 “hello”

<img width="774" alt="image" src="https://github.com/lobehub/lobe-chat/assets/55662670/7c3f6c7f-dd1f-4990-9f5b-84dca21b0d5a">

**Comment by MapleEve** [comment]
试着调整一下对话助手里面的4个设置吧，Lobe 只负责返回对应的内容，你就算是 curl 一下。这种本地的7B 模型返回的也是这样的。
