### ISSUE TITLE
[Bug] 部署到vercel失败

### ISSUE THREAD

**Issue by jyuan15** [lobehub/lobe-chat#1783]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

是fork项目后部署的，试了三四次，都是部署时间到4分6秒时报错，提示“Failed to compile”

![2024-03-28_150105](https://github.com/lobehub/lobe-chat/assets/12642186/ae9533a3-736a-4a30-9bba-8ec43fb81b62)

`......
2352 packages installed [40.76s]
warn: tree-sitter's install script took 23.6s
Detected Next.js version: 14.1.4
Running "bun run build"
$ next build
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
   ▲ Next.js 14.1.4
   Creating an optimized production build ...
 ✓ (pwa) Compiling for server...
 ✓ (pwa) Compiling for server...
 ✓ (pwa) Compiling for client (static)...
 ○ (pwa) Service worker: /vercel/path0/public/sw.js
 ○ (pwa)   URL: /sw.js
 ○ (pwa)   Scope: /
 ✓ Compiled successfully
   Linting and checking validity of types ...
./src/app/chat/(desktop)/features/ChatInput/Footer/index.tsx
59:36  Warning: 'expand' is defined but never used. Allowed unused args must match /^_/u.  unused-imports/no-unused-vars
./src/app/chat/(desktop)/features/ChatInput/TextArea.tsx
34:39  Warning: 'expand' is defined but never used. Allowed unused args must match /^_/u.  unused-imports/no-unused-vars
./src/store/chat/slices/plugin/action.ts
90:13  Warning: Empty block statement.  no-empty
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Failed to compile.
./src/app/welcome/features/Banner/Hero.tsx:36:64
Type error: Type 'string' is not assignable to type 'number'.
  34 |         }}
  35 |       >
> 36 |         {mobile ? <LogoThree size={size.logo} /> : <LogoSpline height={'100%'} width={'100%'} />}
     |                                                                ^
  37 |       </Flexbox>
  38 |       <div className={styles.title} style={{ fontSize: size.title }}>
  39 |         <strong style={mobile ? { fontSize: '1.2em' } : {}}>LobeChat</strong>
error: script "build" exited with code 1
Error: Command "bun run build" exited with 1
`

### 🚦 期望结果

正常部署

### 📷 复现步骤

删除项目重新部署，都在同一个时间点报错

**Comment by arvinxx** [comment]
it should be fixed now
