### ISSUE TITLE
[Bug] 使用Openrouter的API，回答一次问题两次API调用

### ISSUE THREAD

**Issue by fankaizhe** [lobehub/lobe-chat#1792]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

使用openrouter的API自定义模型，每次问答都顺带一个gpt 3.5turbo的API调用记录，但窗口中只调用的一个模型
![image](https://github.com/lobehub/lobe-chat/assets/33307391/5dd67ec2-252a-471f-9e8c-d6ffd9d6d2b3)

**Comment by arvinxx** [comment]
因为会有总结标题啊
