### ISSUE TITLE
[Bug] 现在的gemini1.5pro似乎是假的

### ISSUE THREAD

**Issue by gaojunyang666** [lobehub/lobe-chat#1793]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/63088548/f61a1e29-082f-47e8-baf8-5dd7151eb73d)
如图所示，调用的似乎是1.0，而不是1.5

**Comment by blueman240328** [comment]
我也发现了 #1794

**Comment by xaya1001** [comment]
https://github.com/lobehub/lobe-chat/discussions/1284#discussioncomment-8942220
来这里投票吧，希望能更新一下
