### ISSUE TITLE
模型选择 Gemini 1.5 ，但是请求地址还是 gemini-pro?

### ISSUE THREAD

**Issue by blueman240328** [lobehub/lobe-chat#1794]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

模型选择 Gemini 1.5 或 Gemini ultra, 但是错误信息是从 `gemini-pro` 返回的，这是不是可以认为并没有成功请求到 `gemini-1.5-pro-latest`. （已确认 api 有 1.5 和 ultra 的调用权限）

![image_2024-03-28_23-24-51](https://github.com/lobehub/lobe-chat/assets/165200338/59816eb2-5ce3-454b-9944-eba940274615)

```json
{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: [400 Bad Request] Please ensure that multiturn requests ends with a user role or a function response."
  },
  "provider": "google"
}
```

### 🚦 期望结果

如果选择的 `gemini-pro-vision` ，那么错误信息就是从 `/models/gemini-pro-vision` 返回的，据此推断如果正常请求 `gemini-1.5-pro-latest`，那么错误信息也会从 `/models/gemini-1.5-pro-latest` 返回。

![image](https://github.com/lobehub/lobe-chat/assets/165200338/7b8ab419-831f-4621-9273-18002eed42d6)

### 📷 复现步骤

根据错误信息, gemini 的对话必须从 user role 开始，那么如果把历史消息数限制在双数，就会返回上述错误，根据返回的错误信息，发现是从 `/models/gemini-pro` 的请求地址返回的，并不是选择的 `/models/gemini-1.5-pro-latest` 的地址返回

**Comment by xaya1001** [comment]
https://github.com/lobehub/lobe-chat/discussions/1284#discussioncomment-8942220
来这里投票吧，希望能更新一下

**Comment by blueman240328** [comment]
https://github.com/lobehub/lobe-chat/issues/1769#issuecomment-2024577454

**Comment by arvinxx** [comment]
写了下 RFC： https://github.com/lobehub/lobe-chat/discussions/1796
