### ISSUE TITLE
[Bug] 使用ngrok反向代理ollama服務，不支持https協議

### ISSUE THREAD

**Issue by kevin5251984** [lobehub/lobe-chat#1795]
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

我把ollama使用ngrok發佈後，ngrok所提供的https設置在接口代理地址。
但lobe會自動的使用 11434接回，而不是 https的443接口

![截圖 2024-03-29 凌晨1 18 57](https://github.com/lobehub/lobe-chat/assets/159868618/80523b17-bb5b-4f98-b31a-4e3d5f00997f)

### 🚦 期望结果

我設定的 `https://xxxx.ngrok-free.app` 應該可以直接使用
而不是變成 `http://xxxx.ngrok-free.app:11434`

**Comment by arvinxx** [comment]
现在再试试最新版呢？

**Comment by kevin5251984** [comment]
> 现在再试试最新版呢？
The same, it looks like ollama can only use the http protocol.
一樣的，看來ollama只能使用http協議。

**Comment by arvinxx** [comment]
这个可能和 ollama 的 sdk 有关系。因为请求我调用的是他们的 sdk ，建议去他们那边提个issue

**Comment by arvinxx** [comment]
不对，我看他们的实现上是会做url处理的，那看来是我的实现问题

**Comment by eyebrowkang** [comment]
遇到了同样的问题，不仅是443端口，80端口也是，似乎这里指定了endpoint没有端口的情况下使用11434
