### ISSUE TITLE
[Request] 希望支持更多本地部署的大模型

### ISSUE THREAD

**Issue by Yerosius** [lobehub/lobe-chat#1805]
### 🥰 需求描述

如题，希望支持更多本地部署的大模型，如本地版ChatGLM、Nvidia大模型、Vivo蓝心大模型等

### 🧐 解决方案

同上

**Comment by 1PercentSync** [comment]
支持更多模型的本质是支持更多的api格式。模型本身是没有api的，有api的是推理引擎和推理引擎的封装，比如ollama和tabbyapi，vllm等。通常是兼容openai格式的。你提到的chatglm和蓝心都是模型的名字，他们的gguf版本都是可以给ollama运行的，而英伟达出的那个安装包是一个包含模型推理引擎tensorrt的前端，他用的模型也是开源mistral和llama。

**Comment by Luffyzm3D2Y** [comment]
> 支持更多模型的本质是支持更多的api格式。模型本身是没有api的，有api的是推理引擎和推理引擎的封装，比如ollama和tabbyapi，vllm等。通常是兼容openai格式的。你提到的chatglm和蓝心都是模型的名字，他们的gguf版本都是可以给ollama运行的，而英伟达出的那个安装包是一个包含模型推理引擎tensorrt的前端，他用的模型也是开源mistral和llama。

@1PercentSync  感谢你的回复，对我很有帮助。我想问一下，是否给出任何GGUF model file，Ollama都能够支持部署推理呢？比如蓝心大模型，官方好像不支持，是不是除了需要导出蓝心的GGUF model file，还需要修改Ollama的API推理代码？
