### ISSUE TITLE
[Bug]   升级后， 页面对话，换行丢失。

### ISSUE THREAD

**Issue by mingyue0094** [lobehub/lobe-chat#1809]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

docker 
LobeChat v0.130.7 升级到
LobeChat v0.142.9  发现一个bug.

换行丢失。

发送前是有换行的，发出后，界面上就变成没换行的了。 ai 回复的内容也是没换行。 但是，回复的内容，复制出来，粘贴到记事本，就又有换行了。

**Comment by sxjeru** [comment]
该 issue 已可关闭。
