### ISSUE TITLE
Azure Dalle nor working[Bug] 

### ISSUE THREAD

**Issue by goforu** [lobehub/lobe-chat#1819]
### 💻 Operating System

Ubuntu

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

Azure Version config still call openai api
<img width="1226" alt="image" src="https://github.com/lobehub/lobe-chat/assets/5236864/9fa2bfaa-a1e8-494c-ba77-aacbbc70e6d6">

**Comment by Eobravo** [comment]
我这边也出现了一样的问题，Azure openai模型无法调用dalle3画图
![Snipaste_2024-04-18_11-48-58](https://github.com/lobehub/lobe-chat/assets/93071927/33637d35-8673-4ae6-8e0a-7fec0c858ce4)
![Snipaste_2024-04-18_11-47-52](https://github.com/lobehub/lobe-chat/assets/93071927/8a5a5a4a-0d8b-4dfa-aaf9-bad7fe6cabe2)
![Snipaste_2024-04-18_11-46-21](https://github.com/lobehub/lobe-chat/assets/93071927/dfa5386f-a6fe-43f4-8384-6e7440922a9a)

**Comment by arvinxx** [comment]
目前看下来之前写的 Azure 兼容版 Dalle 3生成模式是有问题的。后续再支持吧
