### ISSUE TITLE
[Bug] 授权失败的弹窗提供显式关闭按钮

### ISSUE THREAD

**Issue by Yidadaa** [lobehub/lobe-chat#182]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/16968934/d8adc93e-a4e1-410f-84ce-87c7f450045b)

即便在设置中已经填写 api key，授权失败弹窗依然无法关闭。

### 🚦 期望结果 | Expected Behavior

提供显式的关闭按钮，尽管点击“确认并重试”可以关闭此弹窗，但由于输入框没有自动填充已经填写的 api key，会使用户感到迷惑。

### 📷 复现步骤 | Recurrence Steps

1. 进入设置，清除掉所有 api 设置
2. 随便发一条消息，触发失败弹窗
3. 进入设置，填写 api 设置
4. 回到聊天界面，失败弹窗没有显式关闭按钮

**Comment by arvinxx** [comment]
点点点 里其实可以删除来着
