### ISSUE TITLE
[Bug] gemini 1.5 pro and gemini 1.0 ultra does not work.

### ISSUE THREAD

**Issue by jiojiojackson** [lobehub/lobe-chat#1820]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Edge

### 🐛 Bug Description

 gemini 1.5 pro and gemini 1.0 ultra does not work.
![image](https://github.com/lobehub/lobe-chat/assets/128605081/101943b0-f6b5-496d-9a19-15b0c7397c5d)

**Comment by EricLeeaaaaa** [comment]
Same Issue Here

**Comment by arvinxx** [comment]
because you don't get the api access. please apply for it
