### ISSUE TITLE
[Bug] 最新版本的ollamo不兼容【从0.1.28升级到0.1.30】

### ISSUE THREAD

**Issue by mintisan** [lobehub/lobe-chat#1821]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

其他 continue.dev 在 Ollama 更新前后都可以使用，但是lobe-chat在ollama跟新晚后现实如下：
【continue.dev和lobe-chat和Ollama在同一个局域网】

![image](https://github.com/lobehub/lobe-chat/assets/9136049/c3cd0ff5-2a46-4114-b150-9b175440429b)

**Comment by bltcn** [comment]
需要在启动ollama的服务时，增加参数OLLAMA_ORIGINS=*

**Comment by happypatwu** [comment]
The latest version can not connect to ollama. Have configured and applied Environment="OLLAMA_ORIGINS=*". Roll back to v0.136.0
