### ISSUE TITLE
[Request] 能否支持http请求的形式

### ISSUE THREAD

**Issue by Zzoay** [lobehub/lobe-chat#1822]
### 🥰 需求描述

能否支持直接发送http请求的形式，而不是只能传入api_key和代理地址。因为，我这边不是通过api_key进行验证的，我是通过在请求的时候header里的"Authorization"参数验证。

### 🧐 解决方案

或许可以支持http请求？配置http请求参数即可。或者实现用户自行配置模型服务？只要保证输入一致即可。这样就算模型服务更新了，只要用户自行配置就可以了，也不用你们追踪这么多个模型的更新。

**Comment by LeoQuote** [comment]
我觉得不太可能支持，因为都是用的官方SDK或者兼容实现，人家不可能为你这个需求自己构造请求，你自己可以用反向代理实现，或者自己看看代码提pr

**Comment by Zzoay** [comment]
> 我觉得不太可能支持，因为都是用的官方SDK或者兼容实现，人家不可能为你这个需求自己构造请求，你自己可以用反向代理实现，或者自己看看代码提pr

我的意思不是说额外套一层，而只是加一个原本官方RESTful API的调用，是不是会比SDK兼容性更好呢？而且对于我们用户感知的输入参数都是完全一致的，不存在什么兼容性问题。
