### ISSUE TITLE
[Bug] 当插件列表过多时，selector溢出屏幕

### ISSUE THREAD

**Issue by Yerosius** [lobehub/lobe-chat#1825]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/76488510/a2debb79-2a6f-4cdf-b811-775feea6b733)

**Comment by arvinxx** [comment]
怎么会装这么多…

**Comment by TonyBlur** [comment]
当屏幕上下宽度较窄的时候，装一定数量的插件，这个问题比较明显

**Comment by Wxh16144** [comment]
看起来需要平铺起来，但是移动端怎么办呢 😨

**Comment by Yerosius** [comment]
无需平铺，只需要加一个滚动条即可解决






---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年4月1日 19:38 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [lobehub/lobe-chat] [Bug] 当插件列表过多时，selector溢出屏幕 (Issue #1825) |

看起来需要平铺起来，但是移动端怎么办呢 😨

**Comment by wuyuan1992** [comment]
> 怎么会装这么多…

![image](https://github.com/lobehub/lobe-chat/assets/20351654/98c64412-e579-428b-b9eb-2056f3cf71fc)
我是试用的时候全装了一遍，就发现了。是不是用模型 dropdown menu 一样的的处理就可以了?

**Comment by Yerosius** [comment]
> > 怎么会装这么多…
> 
> ![image](https://private-user-images.githubusercontent.com/20351654/318622901-98c64412-e579-428b-b9eb-2056f3cf71fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDg2ODYsIm5iZiI6MTcxMjA0ODM4NiwicGF0aCI6Ii8yMDM1MTY1NC8zMTg2MjI5MDEtOThjNjQ0MTItZTU3OS00MjhiLWI5ZWItMjA1NmYzY2Y3MWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA4NTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMmIwNjY3ZGY0OWZlMjAwOWVjNjJhNTAzMTA1NGE2MTJkMzM0MThkMmFlNGJiNTI3NTFiYWY3OTk5MzY0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oQiCGE0QnoTzpj7v2aQsDaH_7sYqxIDymVHLonbhqZs) 我是试用的时候全装了一遍，就发现了。是不是用模型 dropdown menu 一样的的处理就可以了?

请问这是什么IDE？
