### ISSUE TITLE
[Bug] 使用代理后API连接报错

### ISSUE THREAD

**Issue by sezhai** [lobehub/lobe-chat#1826]
### 💻 Operating System

Ubuntu

### 📦 Environment

Official Preview

### 🌐 Browser

Edge

### 🐛 Bug Description

{
  "error": {
    "type": "invalid_request_error",
    "code": "unknown_url",
    "message": "Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.",
    "param": null
  },
  "endpoint": "https://yukun.dy****pn.de/",
  "provider": "openai"
}

**Comment by arvinxx** [comment]
加个 `v1` 试试

**Comment by sezhai** [comment]
可以了，谢谢！
