### ISSUE TITLE
[Bug] 滚动条与展开按钮 hover 区重叠

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#1827]
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/36695271/4b4687ef-220b-44bc-a4e2-0782a9136b2c)

如题，我记得明明之前滚动条不是这样的啊好像（

现在会导致无法使用鼠标滚动滚动条。

### 🚦 期望结果

正常工作，另外可以的话，取消这个导轨，修改滚动条样式。

**Comment by arvinxx** [comment]
改动的原因见 https://github.com/lobehub/lobe-chat/issues/444

自定义滚动条样式会导致hover上去的时候无法选中，所以先暂时移除了这个滚动条的样式，等我后续研究下如何优化这块的样式吧

**Comment by zhaobudaomingzi** [comment]
同样不能用鼠标拖动滚动条，只能用滚轮了

https://github.com/lobehub/lobe-chat/assets/54617500/dfb67a0f-e76c-4659-8d2d-4340d8b9137a

**Comment by arvinxx** [comment]
@zhuozhiyongde 目前基本完美了

**Comment by zhuozhiyongde** [comment]
> @zhuozhiyongde 目前基本完美了

Thx！
