### ISSUE TITLE
[Bug] 使用钉钉手机端访问页面，无法添加助手

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#1840]
### 💻 系统环境

Other

### 📦 部署环境

Official Preview

### 🌐 浏览器

Other

### 🐛 问题描述

我在钉钉里面添加了这个网站服务进去，但在钉钉手机端里，点击发现，然后点开助手后，内容显示不全，无法滚动，也无法添加助手。
![钉钉问题页面](https://github.com/lobehub/lobe-chat/assets/8185843/819dd294-a5f4-4adc-8783-c90eafeb6f49)

### 🚦 期望结果

在钉钉手机端那里可以正常使用添加助手和预览助手信息。

### 📷 复现步骤

打开钉钉手机端客户端-访问服务-发现-点击助手

**Comment by yincangshiwei** [comment]
有人吗

**Comment by arvinxx** [comment]
钉钉浏览器内核是多少？太低不在我们考虑的兼容范围内

**Comment by yincangshiwei** [comment]
> 钉钉浏览器内核是多少？太低不在我们考虑的兼容范围内
好像是UC3内核，版本为69.0.3497.100。我这边先跟钉钉确认和反馈下看看。

**Comment by arvinxx** [comment]
69不计划支持。 升到最少 89 吧
