### ISSUE TITLE
[Bug] GoogleGenerativeAI Error

### ISSUE THREAD

**Issue by sc2flash** [lobehub/lobe-chat#1841]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

只有Gemini 1.5 和1.0Ultra出现这个问题
{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-ultra:streamGenerateContent?alt=sse: [404 Not Found] models/gemini-ultra is not found for API version v1beta, or is not supported for StreamGenerateContent. Call ListModels to see the list of available models and their supported methods."
  },
  "provider": "google"
}

**Comment by arvinxx** [comment]
因为你的api没有这个模型。当然没法用了
