### ISSUE TITLE
[Bug] Gemini-1.5-Pro not found

### ISSUE THREAD

**Issue by edward821220** [lobehub/lobe-chat#1842]
### 💻 Operating System

macOS

### 📦 Environment

Official Preview

### 🌐 Browser

Edge

### 🐛 Bug Description

Gemini-1.5-Pro not found

```
{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:streamGenerateContent?alt=sse: [404 Not Found] models/gemini-1.5-pro-latest is not found for API version v1beta, or is not supported for StreamGenerateContent. Call ListModels to see the list of available models and their supported methods."
  },
  "provider": "google"
}
```

**Comment by rogepi** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/56425392/68db9740-6a10-466c-95b9-f416d68f9afd)

From models list API, it seems that Gemini free API does not currently support Gemini-1.5-Pro

**Comment by rogepi** [comment]
> ![image](https://private-user-images.githubusercontent.com/56425392/318379327-68db9740-6a10-466c-95b9-f416d68f9afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTk5ODYsIm5iZiI6MTcxMTk1OTY4NiwicGF0aCI6Ii81NjQyNTM5Mi8zMTgzNzkzMjctNjhkYjk3NDAtNmExMC00NjZjLTk1YjktZjQxNmQ2OGY5YWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA4MjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZWMwM2EzOWRmNDhhNTM0MWY4MzZjMmJjNmVmZDgyZDI1ZWE4ZTIwMTM3ZWZmMTA2N2Q5NzNiOTM0MzVlMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DRG0z8F-324_8yYZAxGSAeOkVc6r33dIexDzh6peW_U)
> 
> From models list API, it seems that Gemini free API does not currently support Gemini-1.5-Pro
> 
> Gemini 1.0 Pro is still working fine

Maybe we can use the models list API to get the models available for Gemini in Lobe Chat.

**Comment by ckt1031** [comment]
> > From models list API, it seems that Gemini free API does not currently support Gemini-1.5-Pro
> > Gemini 1.0 Pro is still working fine
> 
> Maybe we can use the models list API to get the models available for Gemini in Lobe Chat.

Gemini 1.5 Pro and Gemini Ultra API are currently in preview and only available to selected developers.

**Comment by yuwenhuoxuan** [comment]
@rogepi Gemini 1.0 Pro works fine,thanks
