### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yanliang020** [lobehub/lobe-chat#1844]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

591dcb3cb5e343cd6a99db4c21a703eec4502ad2 🐛 fix: fix gemini 1.5 pro model id to support gemini new models (https://github.com/lobehub/lobe-chat/pull/1776)
我认为这里提交的修复 Gemini 1.5 Pro 型号是错误的，因为现在按照新模型去请求以后会出现google的报错：[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:streamGenerateContent?alt=sse: [404 Not Found] models/gemini-1.5-pro-latest is not found for API version v1beta, or is not supported for StreamGenerateContent. Call ListModels to see the list of available models and their supported methods."

**Comment by ckt1031** [comment]
#1842
