### ISSUE TITLE
右侧滚动条无法鼠标拖动

### ISSUE THREAD

**Issue by Masque423** [lobehub/lobe-chat#1846]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/105150874/ca429840-d56e-4c0c-b7e2-81fc776b31f9)

**Comment by Masque423** [comment]
因为鼠标放上去会显示那个折叠的按钮，应该是被那个影响了

**Comment by Yerosius** [comment]
+1

**Comment by MinionsZQG** [comment]
+1，刚准备来反馈这个BUG

**Comment by arvinxx** [comment]
fix in https://github.com/lobehub/lobe-chat/pull/1775
