### ISSUE TITLE
[Bug] 最新版本使用google gemini-1.5pro模型报错，旧版本没问题

### ISSUE THREAD

**Issue by yuwenhuoxuan** [lobehub/lobe-chat#1848]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:streamGenerateContent?alt=sse: [404 Not Found] models/gemini-1.5-pro-latest is not found for API version v1beta, or is not supported for StreamGenerateContent. Call ListModels to see the list of available models and their supported methods."
  },
  "provider": "google"
}

**Comment by xaya1001** [comment]
LobeChat v0.145.5
没问题啊
![image](https://github.com/lobehub/lobe-chat/assets/20111942/b8463524-b0fe-4984-9571-b0798c4b92dc)

我估计你没收到官方的申请邮件吧？旧版本那个1.5pro是假的，新版本才是真的1.5

**Comment by yuwenhuoxuan** [comment]
@xaya1001 Gemini 1.0 Pro可以使用，谢谢提醒。之前假的Gemini 1.5pro在lobe-chat旧版本中可用，今天更新lobe-chat后就无法使用了。

**Comment by Masque423** [comment]
> @xaya1001 Gemini 1.0 Pro可以使用，谢谢提醒。之前假的Gemini 1.5pro在lobe-chat旧版本中可用，今天更新lobe-chat后就无法使用了。

因为你的api并没有1.5的权限，所以之前假的（你以为是1.5其实是1.0）可以用，新版本是真的1.5所以用不了

**Comment by MapleEve** [comment]
<img width="742" alt="image" src="https://github.com/lobehub/lobe-chat/assets/1845053/bb7ed499-6536-4c1b-8d51-e561b3a32386">
没有收到这个邮件的，都没有 Gemini-1.5 的使用权限。

**Comment by ZDancer** [comment]
我收到了，邮件，但是还是不能用1.5.
还试着重新生成了密钥，还是不行。

**Comment by ConnorCHN** [comment]
> 我收到了楼上的邮件，但是还是不能用1.5. 还试着重新生成了密钥，不行。

Gemini 1.5pro 5月2号要收费的，免费的api应该用不了，即便是能用的话，对于TPM和请求数都是有限制的。参考：官方价格表
![微信截图_20240402163736](https://github.com/lobehub/lobe-chat/assets/8830361/e661dd5d-4436-4ccb-861b-825bb8df5314)

**Comment by ZDancer** [comment]
Got it, in the next minute, 1.5 Pro is fine to use.

**Comment by AlphaCatMeow** [comment]
请教一下，应该如何获取真正的Gemini 1.5 Pro的权限？我在官网链接https://ai.google.dev/只能获取到1.0的权限。但是在aistudio.google.com中是可以使用Gemini 1.5 Pro模型的。

**Comment by MapleEve** [comment]
> 请教一下，应该如何获取真正的Gemini 1.5 Pro的权限？我在官网链接[https://ai.google.dev/只能获取到1.0的权限。但是在aistudio.google.com中是可以使用Gemini](https://ai.google.dev/%E5%8F%AA%E8%83%BD%E8%8E%B7%E5%8F%96%E5%88%B01.0%E7%9A%84%E6%9D%83%E9%99%90%E3%80%82%E4%BD%86%E6%98%AF%E5%9C%A8aistudio.google.com%E4%B8%AD%E6%98%AF%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8Gemini) 1.5 Pro模型的。

官方已经关闭测试申请通道了。等5月2号正式收费之后就可以付费使用了

**Comment by ZDancer** [comment]
User should join the waitlist for Gemini pro .15 and wait for the access to it. invitation for waitlist is issued by Google team, it should be selected, however i dont know the rules.
