### ISSUE TITLE
[Bug] 未检测到 Ollama 服务，请检查是否正常启动

### ISSUE THREAD

**Issue by mengzyou** [lobehub/lobe-chat#1857]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Edge

### 🐛 问题描述

配置运行的ollama服务地址后，提示“未检测到 Ollama 服务，请检查是否正常启动”
![image](https://github.com/lobehub/lobe-chat/assets/360603/37ebdb69-5d8c-48a2-9bc8-c62a1c2e368e)

### 🚦 期望结果

正常连接Ollama服务

### 📷 复现步骤

`设置` > `语言模型` 中启用 `Ollama`，然后配置接口代理地址后，点击测试连通性
![image](https://github.com/lobehub/lobe-chat/assets/360603/06a3ea18-014c-4285-84bf-52e6281fdce0)

**Comment by MapleEve** [comment]
先自己测试一下是否可以通过对应的 IP:端口 curl 到ollama，Ollama 服务启动后需要一些设置才可以局域网/外网访问

**Comment by luojiyin1987** [comment]
```shell
curl http://10.8.40.232:11434
```
验证一下
ollama 默认是是本地监听的。 不是局域网内监听的

**Comment by chenzhuowen** [comment]
same Issue。

![image](https://github.com/lobehub/lobe-chat/assets/20341696/164f3a01-b8d1-4033-a4b4-80142942d050)

![image](https://github.com/lobehub/lobe-chat/assets/20341696/dc22a545-7dbc-4596-8a17-ffe1a4c6e8de)

**Comment by luojiyin1987** [comment]
I  use  OpenWebUI  ,  conect  ollama 
![image](https://github.com/lobehub/lobe-chat/assets/6524977/06902a74-aacb-48db-a2b9-2908b5543e46)
no `v1`

I  use docker compose to run lobe-chat ,  I can not find   ollama config in  lobe-chat web.

**Comment by mengzyou** [comment]
> ```shell
> curl http://10.8.40.232:11434
> ```
> 
> 验证一下 ollama 默认是是本地监听的。 不是局域网内监听的

已验证过，OpenWebUI是可以使用ollama的

**Comment by MapleEve** [comment]
> 这应该是个bug,我也浮现了，我看后台链接，是lobe-chat 去访问ollama的时候默认检测都是访问http协议。当部署在vercal上的时候，默认是带https的访问。这个时候访问http的ollama节点就会出现header错误。

如果是 CORS 那就不是BUG，而是部署之后需要解决的问题，针对 Ollama 的部署需要进行 Nginx 转出，或者参考 Ollama 的官方 Issue
https://github.com/ollama/ollama/issues/669

**Comment by sunxidong9999** [comment]
我这里部署也出现了这个问题 https://github.com/lobehub/lobe-chat/issues/1944#issuecomment-2046601289

**Comment by Windfarer** [comment]
failed on firefox, but ok on chrome
