### ISSUE TITLE
[Bug] 用Nginx 进行反代，出现初始化失败问题

### ISSUE THREAD

**Issue by vank3f3** [lobehub/lobe-chat#1859]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Docker

### 🌐 浏览器

Edge

### 🐛 问题描述

使用的是“lobehub/lobe-chat:latest” 20210402最新打包的docker image
在docker部署好之后，用IP+端口能正常访问，但是用Nginx进行反代的时候，首页初始化失败。
其中，Nginx配置如下
``` Shell
server {
	listen 80;
	server_name  abc.com;

	location ^~ / {
		proxy_pass http://10.0.254.104;
		proxy_set_header Host $host; 
		proxy_set_header X-Real-IP $remote_addr; 
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
		proxy_set_header REMOTE-HOST $remote_addr; 
		proxy_set_header Upgrade $http_upgrade; 
		proxy_set_header Connection "upgrade"; 
		proxy_http_version 1.1; 
		add_header Cache-Control no-cache; 
		proxy_cache off;  
		proxy_buffering off;  
		chunked_transfer_encoding on;  
		tcp_nopush on;  
		tcp_nodelay on;  
		keepalive_timeout 300;  
	}

}
```

出现的问题主要如下图
![image](https://github.com/lobehub/lobe-chat/assets/47717461/7415fd56-ff06-4ca8-bbb1-fe9ad773a497)
![image](https://github.com/lobehub/lobe-chat/assets/47717461/de0fde67-ac42-46fb-895e-c7e713701d47)

### 🚦 期望结果

能满足用Nginx 对 lobe-chat 进行反向代理

**Comment by luojiyin1987** [comment]
看到 `A Error with Permissions-Policy header: Origin trial controlled feature not enabled:`   一类的报错， 在浏览器里是否给了对应的权限？  @vank3f3

**Comment by vank3f3** [comment]
> 看到 `A Error with Permissions-Policy header: Origin trial controlled feature not enabled:` 一类的报错， 在浏览器里是否给了对应的权限？ @vank3f3

请教一下，需要进行哪些权限呢，部署了lobechat后，直接使用IP是可以正常使用的呀，但是加上了Nginx的反向代理后就会出现上图lobe-chat的初始化失败

**Comment by luojiyin1987** [comment]
我习惯配置 
```yaml
proxy_pass http://10.0.254.104;
```
Nginx 有什么报错日志？

**Comment by vank3f3** [comment]
> 我习惯配置
> 
> ```yaml
> proxy_pass http://10.0.254.104/;
> ```
> 
> Nginx 有什么报错日志？

你好，经验证是Nginx中的`proxy_buffering off;` 这行所影响，注释后可以正常初始化了

**Comment by luojiyin1987** [comment]
@vank3f3   麻烦关闭 issue
