### ISSUE TITLE
增加云端存储功能

### ISSUE THREAD

**Issue by lzk821** [lobehub/lobe-chat#1861]
### 🥰 需求描述

希望能出一个配置云端保存的功能

### 🧐 解决方案

可以自定义云端存储网盘或者云端服务器存储，或者可以存储在部署的服务器上

**Comment by hjw21century** [comment]
This project is local-first.

**Comment by arvinxx** [comment]
@hjw21century right.

And also we are working on the backend database feature.

**Comment by arvinxx** [comment]
服务端数据库配置指南：https://lobehub.com/zh/docs/self-hosting/advanced/server-database
