### ISSUE TITLE
[Bug] Ollama 模型设置不见了

### ISSUE THREAD

**Issue by tisfeng** [lobehub/lobe-chat#1862]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Safari

### 🐛 问题描述

很奇怪，最近发现 Ollama 模型设置不见了，之前版本是存在的，我还设置过 Ollama 自定义模型。。。

我确认部署在 vercel 的 lobe-chat 已同步更新到最新版本。

<img width="1673" alt="image" src="https://github.com/lobehub/lobe-chat/assets/25194972/36f57b39-0d55-4711-8c03-6e76017652e4">

### 🚦 期望结果

能使用 Ollama 本地服务。

### 📷 复现步骤

直接设置中查看。

**Comment by arvinxx** [comment]
Vercel 部署不支持ollama哈

**Comment by tisfeng** [comment]
哦，明白了。

这个应该是目前请求强制中转导致的吧，我记得之前讨论过，允许本地请求直达，请问这个有在安排吗？

**Comment by arvinxx** [comment]
有 预计下个月做

**Comment by SODAWater1** [comment]
可是我是在docker部署的，也找不到这个模型的设置

**Comment by tisfeng** [comment]
因为它不能使用常规方式部署，目前需要使用专门搭配 Ollama 的 [docker 方式部署](https://chat-docs.lobehub.com/en/usage/features/local-llm) 😓

这点就很别扭，不仔细看文档，十个人会有八九个踩坑 🥹
 
```bash
docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://host.docker.internal:11434/v1 lobehub/lobe-chat
```

**Comment by arvinxx** [comment]
未来等 client 支持了这块就会放开了。加这个的原因是避免不用 ollama 的用户看到以后造成疑惑
