### ISSUE TITLE
[Bug] 滚动条被header遮挡一部分

### ISSUE THREAD

**Issue by Yerosius** [lobehub/lobe-chat#1868]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

现在滚动条会被header遮挡一部分，这会导致上下文过长滚动条过小的时候会被header完全遮盖住

**Comment by arvinxx** [comment]
这个应该不是问题，高度是可以这么做的，这样背后有内容的时候能有毛玻璃的效果，预告用户上面是有内容的

<img width="1322" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/1320da92-a331-441b-a801-e782bc61ea6d">

**Comment by Yerosius** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/76488510/c91f8c68-1b43-421f-92ef-e55e320cee27)
不是，我指的是这一部分，会被header遮挡住一部分

**Comment by Yerosius** [comment]
@arvinxx

**Comment by arvinxx** [comment]
我明白你的意思。就是要实现我所说的效果，滚动条就必须要有一部分被遮挡
