### ISSUE TITLE
[Bug] 插件调用异常的几种情况

### ISSUE THREAD

**Issue by wuyuan1992** [lobehub/lobe-chat#1876]
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/20351654/d78d74dd-0930-4b5d-9bb7-9ffd8a78f655)
![image](https://github.com/lobehub/lobe-chat/assets/20351654/d024b433-4fd1-489b-94ae-7e23590ef1d2)
![image](https://github.com/lobehub/lobe-chat/assets/20351654/fc86f566-1cc0-492b-a09c-cd0d5bf887f8)

使用插件会出现的问题：
- 调用接口失败
- 插件被循环调用（截图2中不只是循环调用3次，是手动停止前，持续循环调用）
- 无法识别和调用插件

### 🚦 期望结果

插件调用正常

### 📷 复现步骤

使用 gpt3.5 或 gpt4 配合单个插件（我出现问题的时实时天气和 steam）

### 📝 补充信息

插件问题应该是偶现的问题。在昨天的使用中，gpt4 是能够识别插件并只查询一次的。

**Comment by arvinxx** [comment]
1. 我排查看下；
2. 这个在 #999 中能解决
3. 这个可能和模型本身有关吧？
