### ISSUE TITLE
[Bug] versel一键部署失败

### ISSUE THREAD

**Issue by albertimff** [lobehub/lobe-chat#1877]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

昨天部署成功，今天发现有更新，想着重新部署，不知如何更新，就删除了github中的原项目和versel中的原项目，然后重新进行一键部署，和昨天相同，但今天部署出现如下问题。
![图片1](https://github.com/lobehub/lobe-chat/assets/154483517/75bfeefd-0376-438c-9c56-da69f9bea3ed)
![图片2](https://github.com/lobehub/lobe-chat/assets/154483517/a3514d39-2474-4fda-875e-69af1feb13a9)

### 🚦 Expected Behavior

不清楚是不是原始删除的时候是不是有隐藏环境被删除了，还是versel自己的问题

**Comment by arvinxx** [comment]
再重新部署下试试？

**Comment by arvinxx** [comment]
同步一下最近的提交，或者等1小时

**Comment by albertimff** [comment]
由于是我部署的第一个任务，自己是个小白，我能不能直接在vercel里面import最新的创建代码仓如图
![image](https://github.com/lobehub/lobe-chat/assets/154483517/191d4ffb-1a3d-46a4-a068-929dc442e3ac)

**Comment by albertimff** [comment]
部署成功啦，十分感谢。顺便我想问一下我在本地的阿里云服务器上也布置了一个这个东西，只不过什么代理转发地址不知道是什么东西，有什么地方可以了解到的吗？

**Comment by arvinxx** [comment]
@albertimff https://github.com/lobehub/lobe-chat/discussions/466
