### ISSUE TITLE
[Request] 请求添加对Fine-tuning模型调用支持

### ISSUE THREAD

**Issue by leeyiding** [lobehub/lobe-chat#188]
### 🥰 需求描述 | Feature Description

目前openai已开放对gpt-3.5-turbo的微调支持，可以通过接口查询用户已经训练的模型，微调后的模型调用方式只需要修改model名称即可

### 🧐 解决方案 | Proposed Solution

openai提供了接口可以查询用户已经训练的模型列表
```bash
curl https://api.openai.com/v1/fine_tuning/jobs \
  -H "Authorization: Bearer $OPENAI_API_KEY"
```
查询结果如下
```json
{
  "object": "list",
  "data": [
    {
      "object": "fine_tuning.job",
      "id": "ftjob-xxxxxxxxxxxxxxxxxxxxxxx",
      "model": "gpt-3.5-turbo-0613",
      "created_at": 1694484520,
      "finished_at": null,
      "fine_tuned_model": null,
      "organization_id": "org-xxxxxxxxxxxxxxxxxx",
      "result_files": [],
      "status": "running",
      "validation_file": null,
      "training_file": "file-xxxxxxxxxxxxxxxxxxx",
      "hyperparameters": {
        "n_epochs": 3
      },
      "trained_tokens": null,
      "error": null
    },
    {
      "object": "fine_tuning.job",
      "id": "ftjob-xxxxxxxxxxxxxxxxx",
      "model": "gpt-3.5-turbo-0613",
      "created_at": 1694437049,
      "finished_at": 1694438970,
      "fine_tuned_model": "ft:gpt-3.5-turbo-0613:personal:correction:xxxxxxx",
      "organization_id": "org-xxxxxxxxxxxxx",
      "result_files": [
        "file-xxxxxxxxxxxxxxxx"
      ],
      "status": "succeeded",
      "validation_file": null,
      "training_file": "file-xxxxxxxxxxxxxx",
      "hyperparameters": {
        "n_epochs": 3
      },
      "trained_tokens": 486432,
      "error": null
    }
  ],
  "has_more": false
}
```

其中把status为succeeded的fine_tuned_model字段提取出来即可
参考：
https://platform.openai.com/docs/guides/fine-tuning
https://platform.openai.com/docs/api-reference/fine-tuning/undefined

**Comment by arvinxx** [comment]
这个我们需要评估一下。微调能力我知道有开放，但目前有多少人在使用，以及在哪些场景下使用，还是打个问号的。

如果可以的话，能否提供更加详细的场景介绍，以方便我们评估这个功能的重要度？

**Comment by leeyiding** [comment]
没有特殊应用场景，只是为了测试微调模型的输出效果，使用命令行也能测试，但是在Web应用中对测试过程进行截图展示会比较美观。所以并不是非常重要，只是基于产品功能的丰富程度进行考虑，这是一个低优先级的需求，开发者可以评估考虑一下，是否把此项需求添加到今后的开发计划中。

**Comment by arvinxx** [comment]
> 没有特殊应用场景，只是为了测试微调模型的输出效果，使用命令行也能测试，但是在Web应用中对测试过程进行截图展示会比较美观。所以并不是非常重要，只是基于产品功能的丰富程度进行考虑，这是一个低优先级的需求，开发者可以评估考虑一下，是否把此项需求添加到今后的开发计划中。

我们未来会做 web 服务的，这块倒是可以考虑作为增值功能提供出来（包括和微调相关的管理数据集选择、管理、优化的整套东西）。如果没有其他强烈应用场景中的话，开源版本中可能应该不会加进来了。

**Comment by MuCqq** [comment]
我想使用0613的模型，现在的模型傻傻的

**Comment by arvinxx** [comment]
> 我想使用0613的模型，现在的模型傻傻的

现在默认用的就是 0613模型。你可以在你的 API key看看调用情况
