### ISSUE TITLE
云端同步支持移动端和对岸保段同步吗？[Bug] 

### ISSUE THREAD

**Issue by zsychn** [lobehub/lobe-chat#1885]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Safari

### 🐛 问题描述

我电脑端是  ARC浏览器，手机端是safari，使用相同的频道和密码，但是数据不同步。

### 🚦 期望结果

电脑和 手机 可以同步

**Comment by denispol** [comment]
Same for me, I have never been able to sync either of my devices. Each time, only of the devices (the current one) shows in the browser, even if all have lobe-chat open
