### ISSUE TITLE
对话记录的保存问题

### ISSUE THREAD

**Issue by tomkkh521dd** [lobehub/lobe-chat#1892]
### 🥰 需求描述

我不明白对话历史记录的保存机制是怎么样的，但以使用者的角度：
1.希望保存的记录稳定可靠；
2.能生成每条记录的标题，而不是默认话题。
3.记录中区别哪个模型的对话，有明显的标记。

### 🧐 解决方案

如何解决，没什么建议。

**Comment by MapleEve** [comment]
你说的1，2，3目前都有
