### ISSUE TITLE
[Bug] 手机pc不可同步

### ISSUE THREAD

**Issue by BaituLime** [lobehub/lobe-chat#1897]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Firefox

### 🐛 Bug Description

两种浏览器都试了，都是看不到对方

![IMG_20240404_184718_760](https://github.com/lobehub/lobe-chat/assets/50917215/58dd40bf-79d0-4cfe-ad7e-5442fd80f58e)
![IMG_20240404_184721_878](https://github.com/lobehub/lobe-chat/assets/50917215/22606f0b-2779-494a-827e-9a4ad6747bf7)
![IMG_20240404_184725_152](https://github.com/lobehub/lobe-chat/assets/50917215/4bbb459f-0553-4de6-a007-1acfadb6f377)
![IMG_20240404_184727_842](https://github.com/lobehub/lobe-chat/assets/50917215/22984b1b-7789-4377-a9e2-774ffd796e26)

### 🚦 Expected Behavior

希望手机pc可以同步。

**Comment by cy948** [comment]
常见问题见：https://github.com/lobehub/lobe-chat/issues/1683

**Comment by arvinxx** [comment]
WebRTC 功能已归档，此 issue 终结
