### ISSUE TITLE
[Request] 助手列表自动生成对话标题

### ISSUE THREAD

**Issue by luzhenhua1** [lobehub/lobe-chat#190]
### 🥰 需求描述 | Feature Description

Hi，此项目的 ui 设计真的超赞！能否实现列表助手自动生成对话标题？根据对话内容自动生成合适的标题，隔壁 Next Web 已经实现此功能，如果有这个功能用户体验将更加接近在 OpenAi 官方对话，非常方便，

### 🧐 解决方案 | Proposed Solution

新增设置选项：根据对话内容自动生成合适的标题（默认开启）

**Comment by canisminor1990** [comment]
已经实现的能力 当你保存话题的时候会自动生成

**Comment by arvinxx** [comment]
我们和chatgpt的产品逻辑有挺大差别。我们的视角是基于「助手」来构建的。就像你在微信里和一个个朋友聊天，我们更希望大家感知的是一个个的助手角色。

你可以和助手进行对话，然后在你需要的时候，把和助手的会话保存为一个个的「话题」。
