### ISSUE TITLE
[Bug] 同步未成功

### ISSUE THREAD

**Issue by scutken** [lobehub/lobe-chat#1900]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Edge

### 🐛 问题描述

两个机器，同时连接到同一个频道，但是未同步，只能显示自己连接。
![image](https://github.com/lobehub/lobe-chat/assets/38615478/9656b9db-b1bb-4f73-b5be-195d9954bf58)

![clipboard-image-1712234847](https://github.com/lobehub/lobe-chat/assets/38615478/27f3bb2a-06ea-4b3c-8dee-f1f85b50f707)

**Comment by xiaohuakang** [comment]
我一直没有同步成功过

**Comment by Hurray0** [comment]
我这边显示已同步，但是自定义助手、聊天记录等等都没有变化，不知道同步的是什么

**Comment by arvinxx** [comment]
WebRTC 功能已归档，此 issue 终结
