### ISSUE TITLE
[Bug]代码无法高亮，同时排版不好看 

### ISSUE THREAD

**Issue by lmuiotctf** [lobehub/lobe-chat#191]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

代码无法高亮，同时排版不好看 

### 🚦 期望结果 | Expected Behavior

代码高亮，优化下排版

### 📷 复现步骤 | Recurrence Steps

![image](https://github.com/lobehub/lobe-chat/assets/52068443/0458c8cd-2619-49c2-970c-abd31330ad0d)

**Comment by arvinxx** [comment]
@canisminor1990 加下 java 的高亮支持

**Comment by canisminor1990** [comment]
fixed in https://github.com/lobehub/lobe-ui/commit/280e8cfe922afddc2150a6bb0562516935917796
