### ISSUE TITLE
[Request] 自定义模型支持隐藏显示其他服务商模型

### ISSUE THREAD

**Issue by devyujie** [lobehub/lobe-chat#1910]
### 🥰 需求描述

发现自定义模型只对openai模型有作用，能否扩展到其他模型
![image](https://github.com/lobehub/lobe-chat/assets/48620527/041fda93-a660-444b-ab64-2b4f39058d63)

### 🧐 解决方案

、

**Comment by chu-obs** [comment]
拉开模型选项，所有的模型全部都显示了，除了openai的模型可以隐藏，其他根本不会用到的模型，比如claude 2.0 2.1,期待增加其他的自定义模型。

**Comment by arvinxx** [comment]
已经在 https://github.com/lobehub/lobe-chat/pull/1916 支持
