### ISSUE TITLE
[Request] Skip Auth.js sign-in page on SSO login if there is only one provider

### ISSUE THREAD

**Issue by YangHanlin** [lobehub/lobe-chat#1913]
### 🥰 Feature Description

Currently, LobeChat sends the user to the sign-in page provided by Auth.js (e.g. the screenshot below) to select the provider to continue.

![Screenshot](https://github.com/lobehub/lobe-chat/assets/8692892/9c1d5801-0cce-45b4-8d7e-e6caefb245d5)

However, as LobeChat does not support email or credentials provider for now, if there's only one SSO provider configured, it does not make much sense to display a button for the user only to click again. I think it can be better to skip this page and redirect the user directly to the SSO provider if there is only one to choose from.

### 🧐 Proposed Solution

According to the [docs](https://next-auth.js.org/getting-started/client#starts-oauth-sign-in-flow-when-clicked), ID of the selected provider can be provided to [calls to `signIn()`](https://github.com/search?q=repo%3Alobehub%2Flobe-chat+signIn%28&type=code) to skip the sign-in page and redirect to the OAuth2 provider directly.

I'll be happy to submit a PR if we can make this change.

**Comment by arvinxx** [comment]
I think it's better to skip choose If there's only one provider. But the implement method need to be think. 
Currently I prefer to get the enable provider with `/api/config`. And then add a new selector to pick the state. If the length of enabled provider = 1, than set it into Signin function.

**Comment by YangHanlin** [comment]
> I think it's better to skip choose If there's only one provider. But the implement method need to be think. Currently I prefer to get the enable provider with `/api/config`. And then add a new selector to pick the state. If the length of enabled provider = 1, than set it into Signin function.

@arvinxx Thanks. Will try to implement.

**Comment by cy948** [comment]
This change will require significant modifications to existing code and may introduce new rules for using login hooks. Please carefully consider the significance of this change and if necessary, please also change documentation  for sso development in the PR.
