### ISSUE TITLE
[Bug] Netlify 部署失败

### ISSUE THREAD

**Issue by altair441n** [lobehub/lobe-chat#1917]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Other

### 🌐 浏览器

Chrome

### 🐛 问题描述

3月28号及之前是正常的，Github 上打开了自动更新，某个版本之后就一直部署失败了，目前部署版本停留在 v0.142.8
![1712468745649](https://github.com/lobehub/lobe-chat/assets/15700958/72019802-973f-4186-90e5-7d4da7ed1c16)
![Snipaste_2024-04-07_13-53-52](https://github.com/lobehub/lobe-chat/assets/15700958/7097aacb-0946-44d7-8589-2e79c50273b5)

10:25:10 AM: Netlify Build                                                 
10:25:10 AM: ────────────────────────────────────────────────────────────────
10:25:10 AM: ​
10:25:10 AM: ❯ Version
10:25:10 AM:   @netlify/build 29.39.0
10:25:10 AM: ​
10:25:10 AM: ❯ Flags
10:25:10 AM:   baseRelDir: true
10:25:10 AM:   buildId: 661202df772551000835812f
10:25:10 AM:   deployId: 661202df7725510008358131
10:25:10 AM: ​
10:25:10 AM: ❯ Current directory
10:25:10 AM:   /opt/build/repo
10:25:10 AM: ​
10:25:10 AM: ❯ Config file
10:25:10 AM:   /opt/build/repo/netlify.toml
10:25:10 AM: ​
10:25:10 AM: ❯ Context
10:25:10 AM:   production
10:25:10 AM: ​
10:25:10 AM: ❯ Installing plugins
10:25:10 AM:    - @netlify/plugin-nextjs@5.0.0
10:25:11 AM: ​
10:25:11 AM: ❯ Using Next.js Runtime - v5.0.0
10:25:12 AM: ​
10:25:12 AM: @netlify/plugin-nextjs (onPreBuild event)                     
10:25:12 AM: ────────────────────────────────────────────────────────────────
10:25:12 AM: ​
10:25:13 AM: Next.js cache restored
10:25:13 AM: ​
10:25:13 AM: (@netlify/plugin-nextjs onPreBuild completed in 706ms)
10:25:13 AM: ​
10:25:13 AM: build.command from netlify.toml                               
10:25:13 AM: ────────────────────────────────────────────────────────────────
10:25:13 AM: ​
10:25:13 AM: $ npm run build
10:25:13 AM: > @lobehub/chat@0.145.13 build
10:25:13 AM: > next build
10:25:15 AM:    ▲ Next.js 14.1.4
10:25:15 AM:    Creating an optimized production build ...
10:25:15 AM:  ⚠ Found lockfile missing swc dependencies, run next locally to automatically patch
10:25:15 AM:  ✓ (pwa) Compiling for server...
10:25:15 AM:  ✓ (pwa) Compiling for server...
10:25:15 AM:  ✓ (pwa) Compiling for client (static)...
10:25:15 AM:  ○ (pwa) Service worker: /opt/build/repo/public/sw.js
10:25:15 AM:  ○ (pwa)   URL: /sw.js
10:25:15 AM:  ○ (pwa)   Scope: /
10:27:09 AM:  ⚠ Compiled with warnings
10:27:09 AM: ./src/app/settings/llm/TogetherAI/index.tsx
10:27:09 AM: Attempted import error: "Together" is not exported from "@lobehub/icons" (imported as "Together").
10:27:09 AM: Import trace for requested module:
10:27:09 AM: ./src/app/settings/llm/TogetherAI/index.tsx
10:27:09 AM: ./src/app/settings/llm/index.tsx
10:27:09 AM: ./src/app/settings/llm/TogetherAI/index.tsx
10:27:09 AM: Attempted import error: "Together" is not exported from "@lobehub/icons" (imported as "Together").
10:27:09 AM: Import trace for requested module:
10:27:09 AM: ./src/app/settings/llm/TogetherAI/index.tsx
10:27:09 AM: ./src/app/settings/llm/index.tsx
10:27:09 AM: ./src/components/ModelProviderIcon/index.tsx
10:27:09 AM: Attempted import error: "Together" is not exported from "@lobehub/icons" (imported as "Together").
10:27:09 AM: Import trace for requested module:
10:27:09 AM: ./src/components/ModelProviderIcon/index.tsx
10:27:09 AM: ./src/components/ModelSelect/index.tsx
10:27:09 AM: ./src/features/ModelSwitchPanel/index.tsx
10:27:09 AM: ./src/app/chat/(desktop)/features/ChatHeader/Tags.tsx
10:27:09 AM: ./src/app/chat/(desktop)/features/ChatHeader/Main.tsx
10:27:09 AM: ./src/app/chat/(desktop)/features/ChatHeader/index.tsx
10:27:09 AM: ./src/app/chat/(desktop)/index.tsx
10:27:09 AM: ./src/features/Conversation/Error/APIKeyForm/TogetherAI.tsx
10:27:09 AM: Attempted import error: "Together" is not exported from "@lobehub/icons" (imported as "Together").
10:27:09 AM: Import trace for requested module:
10:27:09 AM: ./src/features/Conversation/Error/APIKeyForm/TogetherAI.tsx
10:27:09 AM: ./src/features/Conversation/Error/APIKeyForm/index.tsx
10:27:09 AM: ./src/features/Conversation/Error/InvalidAPIKey.tsx
10:27:09 AM: ./src/features/Conversation/Error/index.tsx
10:27:09 AM: ./src/features/Conversation/components/ChatItem/index.tsx
10:27:09 AM: ./src/features/Conversation/components/VirtualizedList/index.tsx
10:27:09 AM: ./src/features/Conversation/index.tsx
10:27:09 AM: ./src/app/chat/(mobile)/mobile/page.tsx
10:27:09 AM: ./src/app/settings/llm/TogetherAI/index.tsx
10:27:09 AM: Attempted import error: "Together" is not exported from "@lobehub/icons" (imported as "Together").
10:27:09 AM: Import trace for requested module:
10:27:09 AM: ./src/app/settings/llm/TogetherAI/index.tsx
10:27:09 AM: ./src/app/settings/llm/index.tsx
10:27:09 AM: ./src/app/settings/llm/TogetherAI/index.tsx
10:27:09 AM: Attempted import error: "Together" is not exported from "@lobehub/icons" (imported as "Together").
10:27:09 AM: Import trace for requested module:
10:27:09 AM: ./src/app/settings/llm/TogetherAI/index.tsx
10:27:09 AM: ./src/app/settings/llm/index.tsx
10:27:09 AM: ./src/components/ModelProviderIcon/index.tsx
10:27:09 AM: Attempted import error: "Together" is not exported from "@lobehub/icons" (imported as "Together").
10:27:09 AM: Import trace for requested module:
10:27:09 AM: ./src/components/ModelProviderIcon/index.tsx
10:27:09 AM: ./src/components/ModelSelect/index.tsx
10:27:09 AM: ./src/features/AgentSetting/AgentConfig/ModelSelect.tsx
10:27:09 AM: ./src/features/AgentSetting/AgentConfig/index.tsx
10:27:09 AM: ./src/features/AgentSetting/index.tsx
10:27:09 AM: ./src/app/settings/agent/Agent.tsx
10:27:09 AM: ./src/app/settings/agent/page.tsx
10:27:09 AM: ./src/features/Conversation/Error/APIKeyForm/TogetherAI.tsx
10:27:09 AM: Attempted import error: "Together" is not exported from "@lobehub/icons" (imported as "Together").
10:27:09 AM: Import trace for requested module:
10:27:09 AM: ./src/features/Conversation/Error/APIKeyForm/TogetherAI.tsx
10:27:09 AM: ./src/features/Conversation/Error/APIKeyForm/index.tsx
10:27:09 AM: ./src/features/Conversation/Error/InvalidAPIKey.tsx
10:27:09 AM: ./src/features/Conversation/Error/index.tsx
10:27:09 AM: ./src/features/Conversation/components/ChatItem/index.tsx
10:27:09 AM: ./src/features/Conversation/components/VirtualizedList/index.tsx
10:27:09 AM: ./src/features/Conversation/index.tsx
10:27:09 AM: ./src/app/chat/(mobile)/mobile/page.tsx
10:27:09 AM:    Linting and checking validity of types ...
10:27:24 AM: ./src/app/chat/(desktop)/features/ChatInput/Footer/index.tsx
10:27:24 AM: 59:36  Warning: "expand" is defined but never used. Allowed unused args must match /^_/u.  unused-imports/no-unused-vars
10:27:24 AM: ./src/app/chat/(desktop)/features/ChatInput/TextArea.tsx
10:27:24 AM: 34:39  Warning: "expand" is defined but never used. Allowed unused args must match /^_/u.  unused-imports/no-unused-vars
10:27:24 AM: ./src/store/chat/slices/plugin/action.ts
10:27:24 AM: 90:13  Warning: Empty block statement.  no-empty
10:27:24 AM: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
10:27:28 AM: Failed to compile.
10:27:28 AM: 
10:27:28 AM: ./src/app/settings/llm/TogetherAI/index.tsx:1:10
10:27:28 AM: Type error: Module ""@lobehub/icons"" has no exported member "Together".
10:27:28 AM: > 1 | import { Together } from "@lobehub/icons";
10:27:28 AM:     |          ^
10:27:28 AM:   2 | import { useTheme } from "antd-style";
10:27:28 AM:   3 | import { memo } from "react";
10:27:28 AM:   4 |
10:27:29 AM: Failed during stage "building site": Build script returned non-zero exit code: 2
10:27:29 AM: ​
10:27:29 AM: @netlify/plugin-nextjs (onEnd event)                          
10:27:29 AM: ────────────────────────────────────────────────────────────────
10:27:29 AM: ​
10:27:29 AM: ​
10:27:29 AM: (@netlify/plugin-nextjs onEnd completed in 7ms)
10:27:29 AM: ​
10:27:29 AM: "build.command" failed                                        
10:27:29 AM: ────────────────────────────────────────────────────────────────
10:27:29 AM: ​
10:27:29 AM:   Error message
10:27:29 AM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
10:27:29 AM: ​
10:27:29 AM:   Error location
10:27:29 AM:   In build.command from netlify.toml:
10:27:29 AM:   npm run build
10:27:29 AM: ​
10:27:29 AM:   Resolved config
10:27:29 AM:   build:
10:27:29 AM:     command: npm run build
10:27:29 AM:     commandOrigin: config
10:27:29 AM:     environment:
10:27:29 AM:       - ACCESS_CODE
10:27:29 AM:       - CUSTOM_MODELS
10:27:29 AM:       - DEFAULT_AGENT_CONFIG
10:27:29 AM:       - OPENAI_API_KEY
10:27:29 AM:       - OPENAI_PROXY_URL
10:27:29 AM:     publish: /opt/build/repo/.next
10:27:29 AM:     publishOrigin: config
10:27:29 AM:   plugins:
10:27:29 AM:     - inputs: {}
10:27:29 AM:       origin: ui
10:27:29 AM:       package: "@netlify/plugin-nextjs"
10:27:29 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
10:27:29 AM: Failing build: Failed to build site
10:27:29 AM: Finished processing build request in 3m6.175s

### 🚦 期望结果

部署成功

### 📷 复现步骤

Netlify 上重新部署

**Comment by cy948** [comment]
用 pnpm 试试？

**Comment by xWTF** [comment]
Update your packages, seems like they forgot to update the `package.json`.

```bash
# if you're using pnpm
pnpm up

# or
rm -rf node_modules
npm i
```

**Comment by altair441n** [comment]
@cy948 @xWTF Pnpm works, THX.

**Comment by icex05** [comment]
> @cy948 @xWTF Pnpm works, THX.

Could you share how you did it?

I’ve also deployed using Netlify, but when I open the site, it shows “Page Not Found”. Even after you synced the project today and it automatically redeployed, it still shows “Page Not Found”. My Deploy log doesn’t have any content, and it shows 2:50:59 PM: [ERROR] Deploy logs are currently unavailable. We are working on resolving the issue.

Could you explain your steps?

**Comment by icex05** [comment]
> Update your packages, seems like they forgot to update the `package.json`.
> 
> ```shell
> # if you're using pnpm
> pnpm up
> 
> # or
> rm -rf node_modules package-lock.json
> npm i
> ```

Could you tell me how to use this code? I’ve just started with Netlify and I’m not very familiar with its features. Could you please explain the steps simply?

**Comment by altair441n** [comment]
> > @cy948 @xWTF Pnpm works, THX. Pnpm 有效，谢谢。
> 
> Could you share how you did it?你能分享一下你是如何做到的吗？
> 
> I’ve also deployed using Netlify, but when I open the site, it shows “Page Not Found”. Even after you synced the project today and it automatically redeployed, it still shows “Page Not Found”. My Deploy log doesn’t have any content, and it shows 2:50:59 PM: [ERROR] Deploy logs are currently unavailable. We are working on resolving the issue.我还使用 Netlify 进行部署，但当我打开该网站时，它显示“找不到页面”。即使您今天同步了项目并自动重新部署，它仍然显示“找不到页面”。我的部署日志没有任何内容，并且显示 2:50:59 PM：[错误] 部署日志当前不可用。我们正在努力解决这个问题。
> 
> Could you explain your steps?你能解释一下你的步骤吗？

On the Site configuration page, I changed the Build command in Build settings from "npm run build" to "pnpm run build", it works for me.

**Comment by icex05** [comment]
> > > @cy948 @xWTF Pnpm works, THX. Pnpm 有效，谢谢。
> > 
> > 
> > Could you share how you did it?你能分享一下你是如何做到的吗？ 
> > I’ve also deployed using Netlify, but when I open the site, it shows “Page Not Found”. Even after you synced the project today and it automatically redeployed, it still shows “Page Not Found”. My Deploy log doesn’t have any content, and it shows 2:50:59 PM: [ERROR] Deploy logs are currently unavailable. We are working on resolving the issue.我还使用 Netlify 进行部署，但当我打开该网站时，它显示“找不到页面”。即使您今天同步了项目并自动重新部署，它仍然显示“找不到页面”。我的部署日志没有任何内容，并且显示 2:50:59 PM：[错误] 部署日志当前不可用。我们正在努力解决这个问题。 
> > Could you explain your steps?你能解释一下你的步骤吗？
> 
> 在站点配置页面上，我将构建设置中的构建命令从“npm run build”更改为“pnpm run build”，它对我有用。

I tried out this method and it worked for me. Thanks!
