### ISSUE TITLE
[Bug] v0.145.13不知道你们有没有出现这样的BUG

### ISSUE THREAD

**Issue by linkiofo** [lobehub/lobe-chat#1918]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

v0.145.13不知道你们有没有出现这样的BUG，就是使用一段时间之后打开设置里面主题图标会显示不正常，不正常之后不管你们是重置所有设置还是清除删除会话，重新打开浏览器都还是不正常显示，只能打开无痕模型或者新建用户打开有能正常显示很怪异。
![微信截图_20240407164718](https://github.com/lobehub/lobe-chat/assets/156993166/6772a41d-a583-420c-bd1d-591140452aae)

**Comment by arvinxx** [comment]
似乎没有出现，最好给个复现说明
