### ISSUE TITLE
Docs Inaccessible - 402: PAYMENT_REQUIRED

### ISSUE THREAD

**Issue by nikhil-pandey** [lobehub/lobe-chat#1923]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/3397134/d9671476-3b10-4023-bf2c-5a1fde5d8755)

**Comment by arvinxx** [comment]
The document site is fixed. Please try again
