### ISSUE TITLE
[Bug] 对话搜索问题

### ISSUE THREAD

**Issue by fmaxyou** [lobehub/lobe-chat#1924]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

![Screenshot-wQxYRdR1](https://github.com/lobehub/lobe-chat/assets/26402739/6aa4ce0c-0676-4c02-b3f3-423e1e98c7c0)
Q1：右侧的话题栏中搜索，会跨越助手进行搜索，不是当前助手的话题点进去会显示空内容

![Screenshot-uqp4XV7F](https://github.com/lobehub/lobe-chat/assets/26402739/1dbbd0f5-e279-4d65-882a-73ca8e1964a4)
Q2：左侧顶部的搜索有问题，无法搜索对话，也无法搜索助手，都是为空结果

**Comment by fmaxyou** [comment]
![Screenshot-UEMwKgsg](https://github.com/lobehub/lobe-chat/assets/26402739/adb5ef8a-2487-4597-a674-29acbdc3d9b3)

左侧的搜索还是无法使用

**Comment by fmaxyou** [comment]
@lobehubbot

**Comment by arvinxx** [comment]
@fmaxyou 我记得有个 issue ，我最近有空修下吧

**Comment by MazzaWill** [comment]
遇到同样的问题。 复现问题场景：删除某关键词助手后，再创建新的同样关键词助手，搜索就会出现为空的情况。
