### ISSUE TITLE
[Bug] 自动创建话题功能全部是默认话题了

### ISSUE THREAD

**Issue by a616824431** [lobehub/lobe-chat#1926]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![微信图片_20240408102418](https://github.com/lobehub/lobe-chat/assets/82078775/77bac7f4-1084-4c2b-a92c-aaf10b6f0b9a)

**Comment by a616824431** [comment]
好久之前就这样了 是没人发现吗？

**Comment by arvinxx** [comment]
默认使用的是openai 的gpt-3.5 模型来的话题标题总结，如果你不添加openai 的apikey，就没法正常总结。其他用openai 的人不会遇到这个问题，可能你用的不是openai 的吧。

后续我们会做个改造，支持选择固定模型/当前会话模型进行总结，或者禁用自动总结

**Comment by a616824431** [comment]
这我就知道了什么情况了  我用的这个key没有gpt-3.5模型的渠道 。只有gpt4相关的一些渠道

**Comment by Huangwh826** [comment]
> 默认使用的是openai 的gpt-3.5 模型来的话题标题总结，如果你不添加openai 的apikey，就没法正常总结。其他用openai 的人不会遇到这个问题，可能你用的不是openai 的吧。
> 
> 后续我们会做个改造，支持选择固定模型/当前会话模型进行总结，或者禁用自动总结

建议加个可选：不支持话题总结的话，可以摘录首个聊天的前 x 个字符作为话题标题

**Comment by a616824431** [comment]
> > 默认使用的是openai 的gpt-3.5 模型来的话题标题总结，如果你不添加openai 的apikey，就没法正常总结。其他用openai 的人不会遇到这个问题，可能你用的不是openai 的吧。
> > 后续我们会做个改造，支持选择固定模型/当前会话模型进行总结，或者禁用自动总结
> 
> 建议加个可选：不支持话题总结的话，可以摘录首个聊天的前 x 个字符作为话题标题

为什么不能是用当前正在使用的模型进行标题总结呢？

**Comment by Huangwh826** [comment]
> > > 默认使用的是openai 的gpt-3.5 模型来的话题标题总结，如果你不添加openai 的apikey，就没法正常总结。其他用openai 的人不会遇到这个问题，可能你用的不是openai 的吧。
> > > 后续我们会做个改造，支持选择固定模型/当前会话模型进行总结，或者禁用自动总结
> > 
> > 
> > 建议加个可选：不支持话题总结的话，可以摘录首个聊天的前 x 个字符作为话题标题
> 
> 为什么不能是用当前正在使用的模型进行标题总结呢？

我想到的是，如果话题总结+当前咨询问题是一次请求的话，用模型总结是比较好的，但是如果“话题总结”跟“当前咨询问题”是分开请求的话，会比较消耗token，特别是比较长的聊天

**Comment by a616824431** [comment]
可以只对提问进行总结撒。
