### ISSUE TITLE
Feedback for “在 LobeChat 中使用 Ollama”

### ISSUE THREAD

**Issue by ysyx2008** [lobehub/lobe-chat#1933]
按教程容器部署后，始终无法连接本地Ollama的端口，是需要特殊的配置吗？

确认Ollama运行及服务正常。

![图片](https://github.com/lobehub/lobe-chat/assets/11251894/aac3e45a-d4b7-46d3-b736-24cf9ca2ca79)

**Comment by njuFerret** [comment]
> 按教程容器部署后，始终无法连接本地Ollama的端口，是需要特殊的配置吗？
> 
> 确认Ollama运行及服务正常。
> 
> ![图片](https://private-user-images.githubusercontent.com/11251894/320687548-aac3e45a-d4b7-46d3-b736-24cf9ca2ca79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzI2NjAsIm5iZiI6MTcxMjYzMjM2MCwicGF0aCI6Ii8xMTI1MTg5NC8zMjA2ODc1NDgtYWFjM2U0NWEtZDRiNy00NmQzLWI3MzYtMjRjZjljYTJjYTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAzMTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMzZiZTBhOGQwNzRmYWQ4N2MxNGZmNDMxYjUyYjdlNWIzMjIzYzQ5YTU5NTllODI0NWFlN2U4OTU3MjE3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HvuDSBsYTCuEth-bgbzDcb0NnCgWMTW0mHqjzXpayJw)

同样的问题，使用ollama在连通性检查中，检查失败；但在部署时修改环境变量后，可以使用ollama
`    environment:
       - 'OLLAMA_PROXY_URL=http://ip:port/v1'
`

**Comment by ysyx2008** [comment]
> > 按教程容器部署后，始终无法连接本地Ollama的端口，是需要特殊的配置吗？
> > 确认Ollama运行及服务正常。
> > ![图片](https://private-user-images.githubusercontent.com/11251894/320687548-aac3e45a-d4b7-46d3-b736-24cf9ca2ca79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzI2NjAsIm5iZiI6MTcxMjYzMjM2MCwicGF0aCI6Ii8xMTI1MTg5NC8zMjA2ODc1NDgtYWFjM2U0NWEtZDRiNy00NmQzLWI3MzYtMjRjZjljYTJjYTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAzMTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMzZiZTBhOGQwNzRmYWQ4N2MxNGZmNDMxYjUyYjdlNWIzMjIzYzQ5YTU5NTllODI0NWFlN2U4OTU3MjE3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HvuDSBsYTCuEth-bgbzDcb0NnCgWMTW0mHqjzXpayJw)
> 
> 同样的问题，使用ollama在连通性检查中，检查失败；但在部署时修改环境变量后，可以使用ollama
> 
> ```yaml
>    environment:
>        - 'OLLAMA_PROXY_URL=http://ip:port/v1'
> ```

感谢回复，这是修改lobe-Chat的环境变量吧？是在docker run命令中指定参数吗？

**Comment by njuFerret** [comment]
> > > 按教程容器部署后，始终无法连接本地Ollama的端口，是需要特殊的配置吗？
> > > 确认Ollama运行及服务正常。
> > > ![图片](https://private-user-images.githubusercontent.com/11251894/320687548-aac3e45a-d4b7-46d3-b736-24cf9ca2ca79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzI2NjAsIm5iZiI6MTcxMjYzMjM2MCwicGF0aCI6Ii8xMTI1MTg5NC8zMjA2ODc1NDgtYWFjM2U0NWEtZDRiNy00NmQzLWI3MzYtMjRjZjljYTJjYTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAzMTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMzZiZTBhOGQwNzRmYWQ4N2MxNGZmNDMxYjUyYjdlNWIzMjIzYzQ5YTU5NTllODI0NWFlN2U4OTU3MjE3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HvuDSBsYTCuEth-bgbzDcb0NnCgWMTW0mHqjzXpayJw)
> > 
> > 
> > 同样的问题，使用ollama在连通性检查中，检查失败；但在部署时修改环境变量后，可以使用ollama
> > ```yaml
> >    environment:
> >        - 'OLLAMA_PROXY_URL=http://ip:port/v1'
> > ```
> 
> 感谢回复，这是修改lobe-Chat的环境变量吧？是在docker run命令中指定参数吗？

这里是compose方式，配置yml文件，在yml配置文件中定义，

**Comment by MrOops1985** [comment]
连通性检查失败，但实际可以使用

**Comment by ysyx2008** [comment]
> 连通性检查失败，但实际可以使用

测试了，用不了：
![图片](https://github.com/lobehub/lobe-chat/assets/11251894/cb98e602-4be4-4334-9575-39bc672148c5)

ollama本身正常运行：
![图片](https://github.com/lobehub/lobe-chat/assets/11251894/ecde4227-6c20-4663-a733-47cb5b0cb840)

**Comment by ysyx2008** [comment]
使用的wsl环境，Ollama直接安装，lobechat使用docker部署的。

**Comment by GitHUB-ZYD** [comment]
你好，运行docker容器以后，默认还是可以访问到宿主机器的ip和服务的，只需要将OLLAMA_PROXY_URL设置成你的宿主机的ip，不能是127.0.0.1，默认的bridge模式，127指向容器自己。
设置好以后，检查还是会失败，但是对话是可以进行的。

**Comment by MapleEve** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/1845053/a0312e50-88a3-4bcc-95c6-861ce2b7bae2)
我是这样设置的（Windwos），然后局域网暴露给 NAS 上的 Docker Lobe Chat，这样他就可以用这台机器的局域网 IP 来访问本地的大模型了 （别忘记防火墙设置）

**Comment by xinsheng2008** [comment]
windows的本机部署docker的Lobe Chat，试试用host.docker.internal替代ip行不行。

**Comment by chuan1127** [comment]
lobehub在unraid中，使用bond0网络，docker run运行，ip为192.168.50.152:3210，同时ollama，使用bond0网络，docker run运行，使用bond0网络,ip为192.168.50.151:11434, 我已经使用了npm代理了ollama,代理地址示例为：ollama.xxxx.com. 而且告诉我Ollama is running, 当我在设置页面检查ollama，接口代理地址设置为https://ollama.xxxx.com/v1,告诉我未检测到 Ollama 服务，请检查是否正常启动
Show Details
json
{
  "host": "ollama.xxx.com",
  "message": "please check whether your ollama service is available",
  "provider": "ollama"
}
由于我在unraid中运行，使用的是bond0网络, 我需要怎么做？还是说我需要使用host网络运行。

**Comment by GitHUB-ZYD** [comment]
> lobehub在unraid中，使用bond0网络，docker run运行，ip为192.168.50.152:3210，同时ollama，使用bond0网络，docker run运行，使用bond0网络,ip为192.168.50.151:11434, 我已经使用了npm代理了ollama,代理地址示例为：ollama.xxxx.com. 而且告诉我Ollama is running, 当我在设置页面检查ollama，接口代理地址设置为[https://ollama.xxxx.com/v1,告诉我未检测到](https://ollama.xxxx.com/v1,%E5%91%8A%E8%AF%89%E6%88%91%E6%9C%AA%E6%A3%80%E6%B5%8B%E5%88%B0) Ollama 服务，请检查是否正常启动 Show Details json { "host": "ollama.xxx.com", "message": "please check whether your ollama service is available", "provider": "ollama" } 由于我在unraid中运行，使用的是bond0网络, 我需要怎么做？还是说我需要使用host网络运行。

你可以试着 docker -it 进入那个运行lobe chat的容器，然后ping一下lobe chat的服务器的ip，可以ping通就再试一下curl 192.168.50.151:11434 看看能否访问到ollama服务。记得改一下apt install的源，这样子apt update和istall 会快一些

**Comment by chuan1127** [comment]
![ollama](https://github.com/lobehub/lobe-chat/assets/106908523/f6881f78-cdd1-4034-b252-d1325d86f5ef)
![chat](https://github.com/lobehub/lobe-chat/assets/106908523/588f0336-213e-49ba-9ff9-bab78d7be8a5)
这是我在unraid中的配置，他们是可以单独运行的，同时已经按照官网的要求代理了，配置如下：
location / {
    proxy_pass $forward_scheme://$server:$port;
    proxy_set_header Host $http_host;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Method $request_method;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Forwarded-Uri $request_uri;
    # 添加 CORS 头部，如果需要
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		proxy_buffering off;
		proxy_cache off;
		send_timeout 600;
		proxy_connect_timeout 600;
		proxy_send_timeout 600;
		proxy_read_timeout 600;
}
但是检查显示：未检测到 Ollama 服务，请检查是否正常启动
Show Details
json
{
  "host": "ollama.xxx.com",
  "message": "please check whether your ollama service is available",
  "provider": "ollama"
}

**Comment by MapleEve** [comment]
> ![ollama](https://private-user-images.githubusercontent.com/106908523/321966040-f6881f78-cdd1-4034-b252-d1325d86f5ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzUwNjMsIm5iZiI6MTcxMjkzNDc2MywicGF0aCI6Ii8xMDY5MDg1MjMvMzIxOTY2MDQwLWY2ODgxZjc4LWNkZDEtNDAzNC1iMjUyLWQxMzI1ZDg2ZjVlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQxNTEyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGY2YzRjN2Y3NjJkNTQ0MjZjNGQzMGVlYjUxMzgzODQ1ZTg3YWMzZmEwOGVlOTMwNDQyMTViMWY2ODUxYjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sm1E6nv00Ey2RzSZMFPI4H-oG8_1PGJRYL-1tjpekdw) ![chat](https://private-user-images.githubusercontent.com/106908523/321966050-588f0336-213e-49ba-9ff9-bab78d7be8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzUwNjMsIm5iZiI6MTcxMjkzNDc2MywicGF0aCI6Ii8xMDY5MDg1MjMvMzIxOTY2MDUwLTU4OGYwMzM2LTIxM2UtNDliYS05ZmY5LWJhYjc4ZDdiZThhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQxNTEyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmE5ZGJjYjA5NGZiZjBjMTcyMDM4Y2EyOTI1OTAzYjM1MjgxMTdhYTRkNTdkMTZhN2M2NWI2NThmNTI0MWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5mmrVex2nfxhMSMYjr06qqN0bRWsaTEmJCQdaLSOBYk) 这是我在unraid中的配置，他们是可以单独运行的，同时已经按照官网的要求代理了，配置如下： location / { proxy_pass forwardscheme://forward_scheme://server:port;proxysetheaderHostport; proxy_set_header Host http_host; proxy_http_version 1.1; proxy_set_header Upgrade httpupgrade;proxysetheaderConnection"upgrade";proxysetheaderX−Forwarded−Forhttp_upgrade; proxy_set_header Connection "upgrade"; proxy_set_header X-Forwarded-For remote_addr; proxy_set_header X-Forwarded-For Double subscripts: use braces to clarifyproxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Host http_host; proxy_set_header X-Forwarded-Proto scheme;proxysetheaderX−Forwarded−Methodscheme; proxy_set_header X-Forwarded-Method request_method; proxy_set_header X-Forwarded-Ssl on; proxy_set_header X-Real-IP remoteaddr;proxysetheaderX−Original−URLremote_addr; proxy_set_header X-Original-URL scheme://httphosthttp_hostrequest_uri; proxy_set_header X-Forwarded-Uri $request_uri; # 添加 CORS 头部，如果需要 add_header 'Access-Control-Allow-Origin' '*'; add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS'; proxy_buffering off; proxy_cache off; send_timeout 600; proxy_connect_timeout 600; proxy_send_timeout 600; proxy_read_timeout 600; } 但是检查显示：未检测到 Ollama 服务，请检查是否正常启动 Show Details json { "host": "ollama.xxx.com", "message": "please check whether your ollama service is available", "provider": "ollama" }

我在Ubuntu的推理机和训练机以及MacOS上都部署过Ollama都没重现这个情况，因为我都是局域网内部署和请求，所以如果是外网访问的我这边也没有什么办法来重现，可能需要其他人来看看什么问题了。

**Comment by bigsuperangel** [comment]
> 连通性检查失败，但实际可以使用

是的，检测一直失败，实际可以使用

**Comment by arvinxx** [comment]
@sjy 我感觉是不是之前拿 modellist 来检查的思路并不是特别好？要不还是改回用模型调用？

**Comment by chuan1127** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > Connectivity check fails, but actually works
> 
> Yes, the detection keeps failing and it actually works

![1](https://github.com/lobehub/lobe-chat/assets/106908523/aa498001-3faf-4262-af08-fa1afe446dc8)
我这里应该使没有正常工作，但是我单独使用 Ollama，使正常的
