### ISSUE TITLE
[Request] 链接带相关密钥和代理参数，进入后直接使用

### ISSUE THREAD

**Issue by vank3f3** [lobehub/lobe-chat#1934]
### 🥰 需求描述

请问一下，在next-web 中，可以以`https://域名/#/?settings={"key":"密钥","url":"api代理地址"}`的方式，免输入密码或密钥+代理地址，即可直接进行对话，请问在`lobe`中是否有相似的使用方式呢。

### 🧐 解决方案

可通过链接传参的方式，免去输入密码或密钥+代理。

**Comment by cy948** [comment]
https://github.com/lobehub/lobe-chat/discussions/1632
