### ISSUE TITLE
[Bug] v0.146.0出现各种新bug

### ISSUE THREAD

**Issue by jsoncode** [lobehub/lobe-chat#1935]
### 💻 系统环境

Windows

### 📦 部署环境

Other

### 🌐 浏览器

Chrome

### 🐛 问题描述

1. 更新项目后，无法进行npm run build ，出现各种报错。
![image](https://github.com/lobehub/lobe-chat/assets/13176273/679ef682-ec49-401b-a845-d246ed3cd168)

2. 通过npm run dev进入项目后 http://localhost:3010/settings/llm  设置页面报错：
![image](https://github.com/lobehub/lobe-chat/assets/13176273/dd29f7b7-feed-4f7e-8e78-7e5b24f52dbe)

### 🚦 期望结果

修复bug，正常运行

### 📷 复现步骤

1. git clone https://github.com/lobehub/lobe-chat.git
2. cd lobe-chat
3. npm install
4. vim .env.example OLLAMA_PROXY_URL=http://127.0.0.1:11434/v1
5. npm run build / npm run dev

**Comment by arvinxx** [comment]
更新下本地依赖
