### ISSUE TITLE
[Request] 网络访问使用代理服务器的问题

### ISSUE THREAD

**Issue by njuFerret** [lobehub/lobe-chat#1936]
### 🥰 Feature Description

在内网部署时，服务器需要通过代理访问网络，此时openai的各项服务，包括插件商店功能均因网络原因无法使用，

### 🧐 Proposed Solution

在系统中增加设置网络访问代理服务器功能

**Comment by ShanySky** [comment]
如果能使用docker部署的话，可以考虑在运行容器的时候指定代理，这样就可以访问外网了。需要注意的是，如果使用的是官方示例的docker部署命令（Bridge模式），代理服务必须要部署在宿主机上，或者使用nginx映射到宿主机，然后用docker虚拟网桥的网关ip加端口号的形式访问，如 http://172.16.0.1:7890
