### ISSUE TITLE
[Request] 可以加一个启用渲染（比如html）的选项吗？

### ISSUE THREAD

**Issue by CoREse** [lobehub/lobe-chat#1938]
### 🥰 需求描述

如https://github.com/lobehub/lobe-chat/issues/217#issue-1906353014 所提到的，以前对于未被代码块包括的包括html标签是会被渲染的，这当然很影响程序稳定性，但后来一刀切都砍掉了，却使它少了一个功能。比如说如果我想让chatgpt输出html标签的结果（比如\<ruby\>标签添加拼音），结果是不会被渲染的。如果能在句子菜单里加上一个启动渲染的选项就好了。感谢！
实现起来应该也不难，加个选项不让这一句进行https://github.com/lobehub/lobe-chat/issues/217#issue-1906353014 添加上的转义之类的处理就ok了。

### 🧐 解决方案

在每句的...菜单以及助手设置界面添加“启用渲染”的选项。

**Comment by arvinxx** [comment]
如果你需要 Artifacts 类似的功能，目前已经实现了，这个issue先关了。如果有另外的诉求可以再 reopen
