### ISSUE TITLE
[Bug] 通过docker compose部署后没有ollama模型

### ISSUE THREAD

**Issue by sunxidong9999** [lobehub/lobe-chat#1944]
### 💻 Operating System

Other Linux

### 📦 Environment

Docker

### 🌐 Browser

Edge

### 🐛 Bug Description

操作系统：Debian GNU/Linux 11 (bullseye)
部署环境：Docker Compose version v2.6.0
浏览器：123.0.2420.81 (正式版本) (64 位)
Lobechat版本：lobehub/lobe-chat:v0.146.0
Docker compose配置：
`
version: '3.8'

services:
  lobechat:
    image: lobehub/lobe-chat:v0.146.0
    container_name: lobechat
    restart: always
    ports:
      - '3210:3210'
`
bug描述：在上述环境中部署完成后，语言模型配置中没有ollama:
![image](https://github.com/lobehub/lobe-chat/assets/32069514/d27c70d7-2eee-4d25-b835-e0efcec8620d)

### 🚦 Expected Behavior

无

### 📷 Recurrence Steps

按以上环境部署即可。

### 📝 Additional Information

无

**Comment by MrOops1985** [comment]
加个环境变量：OLLAMA_PROXY_URL

https://chat-docs.lobehub.com/zh/self-hosting/examples/ollama

**Comment by sunxidong9999** [comment]
感谢回复，加上环境变量后，lobechat的设置中已经有ollama了，不过有个新问题，设置中对ollama的连通性检查不通过。
lobechat是部署在上文中描述的docker中，ollama是部署在相同局域网下的一台Windows10上面。
用lobechat所在的系统通过curl命令可以访问ollama：
![image](https://github.com/lobehub/lobe-chat/assets/32069514/d06eb68d-4502-467c-8ae2-5889fd7a96b3)
在Lobechat中设置：
![image](https://github.com/lobehub/lobe-chat/assets/32069514/7ee39570-8fa2-40a5-87f7-ea2f7f8d8723)
其中不管是docker-compose.yaml配置中的地址，还是Lobechat中的接口代理地址，均尝试过把"/v1"去除，现象依旧

**Comment by sunxidong9999** [comment]
补充一些调试信息，在F12看到是被403了：
![image](https://github.com/lobehub/lobe-chat/assets/32069514/ef49d148-16a1-4d9a-8033-e1198ea7ff0a)
在docker宿主机上用curl可以：
![image](https://github.com/lobehub/lobe-chat/assets/32069514/b680187f-b942-4b54-83e1-b30859d9aa8f)

**Comment by MapleEve** [comment]
<img width="488" alt="image" src="https://github.com/lobehub/lobe-chat/assets/1845053/be0720d9-24a7-4418-a462-a869b6c8f5ae">

看了下请求头有可能是 CORS 的关系，你试试反代 ollama 到 HTTPS 下面是否可以成功

**Comment by zcf0508** [comment]
ollama 的服务需要设置支持跨域

```
set OLLAMA_ORIGINS=*
set OLLAMA_HOST=0.0.0.0:11434
```

**Comment by sunxidong9999** [comment]
> ollama 的服务需要设置支持跨域
> 
> ```
> set OLLAMA_ORIGINS=*
> set OLLAMA_HOST=0.0.0.0:11434
> ```

实测有效，问题已经解决，非常感谢！！
