### ISSUE TITLE
[Bug] 回复样式问题

### ISSUE THREAD

**Issue by tanjie-ola** [lobehub/lobe-chat#1945]
### 💻 Operating System

macOS

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/113013739/8a7465bc-087e-4439-850e-40041fc01b68)
突然回复都变成这样了

**Comment by KaiSiMai** [comment]
一样，不是模型问题。

**Comment by yangwen27** [comment]
一样，换了模型也是排版乱

**Comment by wuzikai18** [comment]
+1

**Comment by XiaolongYang-HZAU** [comment]
一样的问题

**Comment by xyspg** [comment]
other chat interface providers do not seem to have this issue

**Comment by m-guo** [comment]
应该自动部署了主分支最新的代码

**Comment by xiaoheimissu** [comment]
me,too, 检查了不是模型回复的问题

**Comment by Greasen** [comment]
谁提交代码之前不自测的嘛？

**Comment by amoonlighti** [comment]
出现了一样的问题，使用的是Gemini1.5的模型

**Comment by scylamb** [comment]
直接回滚到之前的版本就好了，1025b85
:bookmark: chore(release): v0.146.0

**Comment by tisfeng** [comment]
好离谱的 bug 🥲

我刚在 vercel 回滚 Rollback 临时可解决 🙂

<img width="1492" alt="image" src="https://github.com/lobehub/lobe-chat/assets/25194972/95abac23-6366-40de-910f-3946c3fa07b2">

**Comment by 98zi** [comment]
https://github.com/lobehub/lobe-chat/compare/v0.146.0...v0.146.1
对照一下，好像只修改了 claude 😂

**Comment by arvinxx** [comment]
感觉是依赖更新导致的，我检查下

**Comment by arvinxx** [comment]
应该是 `ai@3.0.20` 的锅。我先锁到 `3.0.19` 了，晚点再详细研究下是什么原因

**Comment by arvinxx** [comment]
检查了，就是 `ai@3.0.20` 的锅，已提 issue: https://github.com/vercel/ai/issues/1316
