### ISSUE TITLE
[Bug] 返回的消息内容好像是乱码了？

### ISSUE THREAD

**Issue by shylock-wu** [lobehub/lobe-chat#1947]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

结果给我返回了好多无效的`0`字符
![CleanShot 2024-04-10 at 11 40 18](https://github.com/lobehub/lobe-chat/assets/73875874/d460cedd-a407-45f4-816d-fe9fb5425673)

### 🚦 期望结果

正常输出就行

### 📷 复现步骤

随便问GPT

### 📝 补充信息

部署的git hash值 `8bf9db93ad318db7d1d968e8e788be1c7a012a62`

**Comment by arvinxx** [comment]
更新到最新版，已经修复了： #1946

**Comment by serenalee87** [comment]
用docker拉取latest版本，依然没有更新，还是有bug，是需要指定特点模型么？

**Comment by arvinxx** [comment]
@serenalee87 Docker latest 应该是 `0.146.2` 了，你确定拉取的版本对吗？

**Comment by shylock-wu** [comment]
我遇到这个问题应该是自动更新的action，恰好在一个小时之内的冷却时间。导致主分支没有及时更新导致的，主动sync一下再部署就好了
