### ISSUE TITLE
[Request] Google Analytics

### ISSUE THREAD

**Issue by buraktabn** [lobehub/lobe-chat#1949]
### 🥰 Feature Description

Give an option to use Google Analytics

### 🧐 Proposed Solution

Next.js provides the necessary libraries. [Here](https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#google-analytics) is the docs.
We could conditionally use this if the env variable found for it.

**Comment by arvinxx** [comment]
Actually we have it alreay: https://lobehub.com/docs/self-hosting/environment-variables/analytics#google-analytics
