### ISSUE TITLE
[Bug] selector overflow

### ISSUE THREAD

**Issue by ken0311** [lobehub/lobe-chat#1957]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/129929032/39b5cccc-90a3-491e-b8c0-0aee00ca90cc)
When model selection menu is too large,  the selection menu may overflow the screen
![image](https://github.com/lobehub/lobe-chat/assets/129929032/19c18c2b-75f2-4bcc-b4d1-a87069ef4589)
the same as translation menu

**Comment by arvinxx** [comment]
@ken0311 we have fix the translation menu, Do you still meet this issue?

**Comment by ken0311** [comment]
Thanks. The issue with the translation selection menu overflowing the screen has been resolved.However, on small-screen devices like 14-inch laptops, there is still an overflow issue with the model selection menu. This can be resolved by setting the browser zoom to 80%.
