### ISSUE TITLE
[Bug] 无法显示自定义的模型

### ISSUE THREAD

**Issue by Yanyutin753** [lobehub/lobe-chat#1958]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

## 在模型配置的时候已经添加了自定义模型，如下图所示
![image](https://github.com/lobehub/lobe-chat/assets/132346501/8d67e49a-f678-426c-9e47-a1d2f20ff37e)

## 并没有显示相应的自定义模型
![image](https://github.com/lobehub/lobe-chat/assets/132346501/378f8781-a216-49c1-b817-a299cf67f0a8)

### 🚦 期望结果

希望能适配自定义模型

### 📷 复现步骤

希望能适配自定义模型

### 📝 补充信息

希望能适配自定义模型

**Comment by arvinxx** [comment]
我check下，可能是个bug

**Comment by Yanyutin753** [comment]
@arvinxx 大佬好像定义了CUSTOM_MODELS之后，无法通过联网获取新模型
![image](https://github.com/lobehub/lobe-chat/assets/132346501/318b369c-3dde-4416-b520-5be3bf9467de)

**Comment by arvinxx** [comment]
@Yanyutin753 对，`CUSTOM_MODELS` 优先级高于联网获取

**Comment by goldenhawksu** [comment]
同样的问题，挺严重影响使用的，用new-api管理的接口，在lobe-chat里可以自动搜索出来自定义模型，但在“随便聊聊”界面，没有对应的这些模型可选；0.146.2用起来很顺利，没有这样的问题；
