### ISSUE TITLE
[Bug] 当模型支持自动继续的时候，继续的对话会出现在对话中

### ISSUE THREAD

**Issue by MapleEve** [lobehub/lobe-chat#1961]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

当生成长度的 token 大于模型单次输出的时候，在 agent prompt 里面加上自动继续的提示，但是继续的内容会在对话中打出（模型生成的对话框）

![image](https://github.com/lobehub/lobe-chat/assets/1845053/0a8889a7-7ab5-4dfc-882f-9e27dd3a180a)

### 🚦 期望结果

隐藏掉 User 和 Assistant 的对话

### 📷 复现步骤

使用的是 Kimi 逆向和 Gemini 1.5 测试，均有机会被打印出来

**Comment by arvinxx** [comment]
重复 #1379
