### ISSUE TITLE
[Request] 为 OpenAI gpt-4-turbo API 更新支持

### ISSUE THREAD

**Issue by PeterBilly** [lobehub/lobe-chat#1963]
### 🥰 需求描述

OpenAI 更新了`gpt-4-turbo-2024-04-09`以及指向其的`gpt-4-turbo`。
这是`gpt-4-turbo-preview`的生产模型，允许图像输入和函数调用。
建议添加对其的支持。

### 🧐 解决方案

添加对`gpt-4-turbo-2024-04-09`以及`gpt-4-turbo`的支持。

**Comment by arvinxx** [comment]
可以的。在我们还没支持前，你应该可以通过拉取模型列表的方式获取并使用最新的模型

**Comment by devyujie** [comment]
> 可以的。在我们还没支持前，你应该可以通过拉取模型列表的方式获取并使用最新的模型

拉取不到 4 turbo
![image](https://github.com/lobehub/lobe-chat/assets/48620527/bbc92bb4-8271-40a3-8e0c-05b508cfd7bf)
![image](https://github.com/lobehub/lobe-chat/assets/48620527/03b6d36f-29bb-4318-bf86-2fc4a7d81a4c)

**Comment by arvinxx** [comment]
拉不到应该是你的 model provider 还不支持吧？

**Comment by sebastianarena** [comment]
I do see them, but they do not specify that function calling and vision processing is there to use yet.
Looking forward for the update!
Thanks!

<img width="281" alt="Screenshot 2024-04-11 at 10 32 28" src="https://github.com/lobehub/lobe-chat/assets/640406/b685e042-2366-444a-aaeb-0ecfee469197">
<img width="215" alt="Screenshot 2024-04-11 at 10 32 45" src="https://github.com/lobehub/lobe-chat/assets/640406/b1612903-7098-472a-b846-3493627fbfb7">

**Comment by DEAN-Cherry** [comment]
> > 可以的。在我们还没支持前，你应该可以通过拉取模型列表的方式获取并使用最新的模型
> 
> 拉取不到 4 turbo ![image](https://private-user-images.githubusercontent.com/48620527/321502679-bbc92bb4-8271-40a3-8e0c-05b508cfd7bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTA3NjMsIm5iZiI6MTcxMjkxMDQ2MywicGF0aCI6Ii80ODYyMDUyNy8zMjE1MDI2NzktYmJjOTJiYjQtODI3MS00MGEzLThlMGMtMDViNTA4Y2ZkN2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA4Mjc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhODUzYzRiZjk0MzU1YjU1YTAwN2U4NjY3NTJiY2FhOGVjNWQxYjk2YTY4ZmI1MjI0YzdjNThiOTM3YWY4MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zR7bo9NpkEjmNTrtY4awIm5UxtaHgKV7FBau_68O8d0) ![image](https://private-user-images.githubusercontent.com/48620527/321502706-03b6d36f-29bb-4318-bf86-2fc4a7d81a4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTA3NjMsIm5iZiI6MTcxMjkxMDQ2MywicGF0aCI6Ii80ODYyMDUyNy8zMjE1MDI3MDYtMDNiNmQzNmYtMjliYi00MzE4LWJmODYtMmZjNGE3ZDgxYTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA4Mjc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MTg5Mjk2NWU2Yjg1ZWRjZGZmZjAxZTRkMGE3NDU0N2EwYzhkODJhY2M1NjQ0Mzc3MDdkZmZlY2UyNTJkYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BQuvjBYrSaGSOcE7cqb8OFxSMBlYeaedp07Rd42bdFw)

请问这个拉取模型是在哪里设置的?
