### ISSUE TITLE
Add function calling support for Claude-3 models

### ISSUE THREAD

**Issue by richards199999** [lobehub/lobe-chat#1967]
### 🥰 Feature Description

> Claude is capable of interacting with external client-side tools and functions, allowing you to equip Claude with your own custom tools to perform a wider variety of tasks.

now claude-3 has support function calling natively, i hope lobechat would support it soon.

### 🧐 Proposed Solution

Here is there official doc: https://docs.anthropic.com/claude/docs/tool-use

**Comment by arvinxx** [comment]
refs to: https://github.com/lobehub/lobe-chat/discussions/1310
