### ISSUE TITLE
[Bug]  Azure OpenAI 无法使用

### ISSUE THREAD

**Issue by securitgithub** [lobehub/lobe-chat#1968]
### 💻 系统环境

Rocky Linux release 9.1 (Blue Onyx)

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

更新版本后， Azure OpenAI 无法使用，请问具体如何设置。https://chat-docs.lobehub.com/zh/self-hosting/examples/azure-openai 按照链接设置之前版本可以，现在不行了，截图里面的设置也没有了。

### 部署方式
安装此文档进行部署：https://chat-docs.lobehub.com/zh/self-hosting/platform/docker-compose

**Comment by arvinxx** [comment]
你是配置的环境变量，还是在界面上填 api key 的？

**Comment by securitgithub** [comment]
![1712807089086](https://github.com/lobehub/lobe-chat/assets/24914793/764521d3-51d0-4bf3-849e-c1322f3a3396)
![1712807188466](https://github.com/lobehub/lobe-chat/assets/24914793/f6ef19e1-1325-4ef7-b271-c1a3fbfbe1de)
![1712806962415](https://github.com/lobehub/lobe-chat/assets/24914793/8d59b4de-e650-42a7-8cfb-80962723cf5e)

**Comment by securitgithub** [comment]
> 你是配置的环境变量，还是在界面上填 api key 的？

dokcer 配置文件

**Comment by securitgithub** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > Did you configure environment variables or fill in the api key on the interface?
> 
> dokcer configuration file

之前都是正常的，跟配置文件应该没多大关系，curl测试也正常。

**Comment by securitgithub** [comment]
![1712808712444](https://github.com/lobehub/lobe-chat/assets/24914793/8ed7350e-7da2-40d0-9a6a-c37045a2b0de)

**Comment by arvinxx** [comment]
`0.147.0` 版本由于拆开来了 Azure 和 OpenAI 的配置，因此有些环境变量已经变了。针对 Azure OpenAI 的配置，需要从 `OPENAI_PROXY_URL` 改为 `AZURE_ENDPOINT`。

**Comment by securitgithub** [comment]
> AZURE_ENDPOINT

这里怎么选择?
![1712810073749](https://github.com/lobehub/lobe-chat/assets/24914793/30265dec-86df-4cf4-9bc1-14827bb544a9)
![1712810106338](https://github.com/lobehub/lobe-chat/assets/24914793/de65f093-6f60-4ae9-b8a1-fb5dc70fabf3)

**Comment by arvinxx** [comment]
@securitgithub 更新下最新的镜像，我理解应该和 #1958 这个是同一个问题

**Comment by fooooxxxx** [comment]
> @securitgithub 更新下最新的镜像，我理解应该和 #1958 这个是同一个问题

开发者您好，我更新了最新的镜像，Azure模型依然默认为空。

是不是因为 src/app/api/config/route.ts 的 config 的 `languageModel` 没有设置azure模型的原因？

**Comment by arvinxx** [comment]
@fooooxxxx 需要你自己在设置里添加 azure 模型了，因为之前实现的局限性，要求 id 和 deployment 同名，但是会有很多用户提  id 和部署名不一样的问题：
- #1952 
- #1056

所以现在在这一版里支持了 id 和 deploymentName 分开设置。

**Comment by missuo** [comment]
在最新的版本中 https://github.com/lobehub/lobe-chat/releases/tag/v0.147.6 Azure 仍然无法使用，在 Docker 环境变量中已经设置，但是仍然显示未开启 Azure 服务。

<img width="604" alt="image" src="https://github.com/lobehub/lobe-chat/assets/55200481/876a8688-0f83-44b9-9a9f-2cff125e6750">

**Comment by arvinxx** [comment]
@missuo 哦，我傻了，这块忘记改了，一会修下
