### ISSUE TITLE
[Request] 当前初始化默认只启用第一个模型，希望能自行调整或初始全部启用

### ISSUE THREAD

**Issue by ITOTI-Y** [lobehub/lobe-chat#1974]
### 🥰 需求描述

添加Model_list功能后初始默认只启用第一个模型，用户需要到设置界面自行更新并启用模型（我理解这项设置的目的是让用户在测试后关闭自己不需要的模型，而不是让用户一开始就开启自己需要的模型），希望能在部署时设置默认启用的模型，或初始化时默认启用全部模型并由用户自行关闭。

### 🧐 解决方案

提供默认启用模型的参数设置或默认显示所有可用模型

**Comment by arvinxx** [comment]
> 添加Model_list功能后初始默认只启用第一个模型

没懂，应该没有默认只启用第一个吧？你的case是啥样的

**Comment by arvinxx** [comment]
> 希望能在部署时设置默认启用的模型

这个改造 ModelList 的时候考虑过，后续可以加一个 `ENABLED_MODELS` 环境变量做默认开启模型的控制。但看下大家的需求度有多少了。

**Comment by buwanyuanshen** [comment]
最新版本，环境变量设置了默认模型，进去之后只有三个模型可供选择，其余的模型还需要去设置勾选。。。是不是多此一举了。

**Comment by zhuozhiyongde** [comment]
确实很多此一举，默认只有一个模型（隐私模式下）：

![image](https://github.com/lobehub/lobe-chat/assets/36695271/5f2b9824-4d01-4a15-bbc9-bcf0c2f516c7)

必须去模型列表里手动重置一下才行：

![image](https://github.com/lobehub/lobe-chat/assets/36695271/21e7a084-eeec-473e-bebd-1a62e480e9c1)

而且很奇怪的是，重置/获取模型列表之前长这样：

![image](https://github.com/lobehub/lobe-chat/assets/36695271/e8dad9a9-d61b-405c-966b-e88898158fe3)

重置后才是正确的名称：

![image](https://github.com/lobehub/lobe-chat/assets/36695271/8a1fbacd-3a13-4533-aff4-553fadc2036e)


我的环境变量：

```sh
OPENAI_MODEL_LIST=-all,+gpt-3.5-turbo-0125=GPT-3.5 Turbo,+gpt-4-0125-preview=GPT-4 Turbo,+gpt-4-vision-preview=GPT-4 Vision
```

**Comment by zhuozhiyongde** [comment]
我认为这里应该允许所有模型都默认开启，而不是默认需要去手动勾选。
