### ISSUE TITLE
[Docs] Feedback for `self-hosting/platform/docker-compose`

### ISSUE THREAD

**Issue by null119** [lobehub/lobe-chat#1976]
### 📝 Reference

https://lobehub.com/docs/self-hosting/platform/docker-compose

### 🐛 Feedback

docker-compose 页面无法打开，报错：
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 2838552747

**Comment by arvinxx** [comment]
https://chat-docs.lobehub.com/zh/self-hosting/platform/docker-compose 先看这个吧

**Comment by canisminor1990** [comment]
fixed
