### ISSUE TITLE
[BUG]手机端无法提交修改后的自定义模型数据

### ISSUE THREAD

**Issue by Yanyutin753** [lobehub/lobe-chat#1977]
### 💻 系统环境

iOS

### 📦 部署环境

Docker

### 🌐 浏览器

Safari

### 🐛 问题描述

![IMG_6133](https://github.com/lobehub/lobe-chat/assets/132346501/7c3888cc-1cd0-46be-92dc-138897c9462b)
![IMG_6134](https://github.com/lobehub/lobe-chat/assets/132346501/445cf950-9272-400b-930e-cb809547f8e7)
## 感谢作者，感谢lobe

**Comment by ShanySky** [comment]
我也遇到了这个问题，针对手动添加的模型，在编辑完它的配置后（比如开启支持函数调用），好像只会临时保存在页面中，当我切换到其他页面，比如通用配置页面，再切回模型配置页面后打开原来那个模型的配置弹窗后会发现支持函数调用的复选框又变成了未选中状态。这种情况只有在手机上有，而在电脑上是正常的。

**Comment by sxjeru** [comment]
相关 #2319 #2294
