### ISSUE TITLE
[Bug] 自定义模型勾选“支持函数调用”“支持视觉识别”后助手处无法识别能力，且不显示tokens数量

### ISSUE THREAD

**Issue by deyinliwork** [lobehub/lobe-chat#1981]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

如题

![image](https://github.com/lobehub/lobe-chat/assets/156164981/c829b9ad-09f7-45cb-95ee-3508f1917b8f)

### 🚦 期望结果

![image](https://github.com/lobehub/lobe-chat/assets/156164981/06287741-b193-4f16-8a3e-12ef0bd30366)

### 📷 复现步骤

![image](https://github.com/lobehub/lobe-chat/assets/156164981/1b337e0b-390a-440e-97e2-f59a009ebea8)

![image](https://github.com/lobehub/lobe-chat/assets/156164981/7344541d-c4ef-409a-90b2-f9bd390257f4)

**Comment by MapleEve** [comment]
https://github.com/lobehub/lobe-chat/pull/1984

我尝试在PR里面加这个模型的正式支持
但是你提的这个应该属于另一个BUG

**Comment by arvinxx** [comment]
> 但是你提的这个应该属于另一个BUG


是的，我晚点修下

**Comment by deyinliwork** [comment]
感谢，静候佳音~
