### ISSUE TITLE
[Bug] 为什么fork并upstream sync项目一段时间后就无法再同步了？

### ISSUE THREAD

**Issue by mwnu** [lobehub/lobe-chat#1983]
### 💻 系统环境

Other

### 📦 部署环境

Other

### 🌐 浏览器

Other

### 🐛 问题描述

Sync latest commits from upstream repo
The process '/usr/bin/sh' failed with exit code 1
Sync latest commits from upstream repo
[🚨 AC] Issues are disabled for this repo
Sync latest commits from upstream repo
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: aormsby/Fork-Sync-With-Upstream-action@v3.4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Sync latest commits from upstream repo
[🎃 AC] 'issue-number' is missing or this action not needed yet!
Sync latest commits from upstream repo
[🎃 AC] 'issue-number' is missing or this action not needed yet!

![image](https://github.com/lobehub/lobe-chat/assets/45463732/f4afaae9-3400-4f75-847c-e1311dd1df8a)

### 🚦 期望结果

正常同步

### 📷 复现步骤

fork项目，然后在actions中启用upstream sync workflows，默认每小时同步一次。
一段时间后就无法再upstream sync 了。
我两次重新fork项目，两次都能正常同步一周左右，然后就出现一样的错误。

### 📝 补充信息

![image](https://github.com/lobehub/lobe-chat/assets/45463732/b0776551-35a7-4e33-85d7-4933c08968f0)

**Comment by MapleEve** [comment]
最近几次更新好像修改了acrion规则，手动点一下sync就好了

**Comment by mwnu** [comment]
> 最近几次更新好像修改了acrion规则，手动点一下sync就好了

我看https://github.com/lobehub/lobe-chat/blob/main/.github/workflows/sync.yml 是6个月前的，手动同步一样的错误。

**Comment by arvinxx** [comment]
参阅： https://github.com/lobehub/lobe-chat/discussions/1692

**Comment by kcity** [comment]
服了 到现在还是经常出现这个问题，不知道怎么解决

**Comment by arvinxx** [comment]
@kcity 好好看文档
