### ISSUE TITLE
[Request]  Is it possible to add a function that does not require api to use chatgpt3.5? 

### ISSUE THREAD

**Issue by chuan1127** [lobehub/lobe-chat#1988]
### 🥰 需求描述

Currently openai chatgpt3.5, no login required. Is it possible to add a feature that doesn't require an API to use chatgpt3.5? I think the quality and speed of chatgpt3.5 translation is very fast. Compared with chatgpt4.0, the immersive translation speed of chatgpt4.0 is a bit slow.

### 🧐 解决方案

Currently openai uses chatgpt3.5, no login is required. Is it possible to add a feature that doesn't require an API to use chatgpt3.5? I think the quality and speed of chatgpt3.5 translation is very fast. Compared with chatgpt4.0, the immersive translation speed of chatgpt4.0 is a bit slow.

**Comment by arvinxx** [comment]
we don't plan to support free chatgpt 3.5 reverse API. It's not a legal way. make be you can add it by yourself.
