### ISSUE TITLE
[Bug] PWA 在点击部分模型回复的链接时，没有使用打开新窗口，导致整个程序卡死

### ISSUE THREAD

**Issue by MapleEve** [lobehub/lobe-chat#1989]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

Gemini，Kimi等模型在回答的时候给的链接有可能不带 _blank
点击后PWA会跳转出聊天界面

### 🚦 期望结果

点击外链永远打开新窗口

### 📷 复现步骤

![image](https://github.com/lobehub/lobe-chat/assets/1845053/efc6c317-c51d-4ffa-b1bb-fce17fb262d3)

**Comment by sxjeru** [comment]
请问最新版本还能否复现？这边之前也有遇到，现在测不出来了。（Gemini）
