### ISSUE TITLE
[Bug] 使用docker部署后无法访问助手市场和插件商店

### ISSUE THREAD

**Issue by mqhe2007** [lobehub/lobe-chat#1990]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

在阿里云ECS云服务器使用1Panel面板使用docker部署后无法访问助手市场和插件商店，请求接口报500错误
<img width="655" alt="image" src="https://github.com/lobehub/lobe-chat/assets/13450661/e2f6479f-40e4-47a5-b018-5a89f5672489">
<img width="659" alt="image" src="https://github.com/lobehub/lobe-chat/assets/13450661/b93d9de1-abec-4793-a37c-c3f55ac22aac">
日志报错：
<img width="1680" alt="image" src="https://github.com/lobehub/lobe-chat/assets/13450661/3af7e1f4-6009-44fc-ba3c-7d2adc3bbf07">

### 🚦 期望结果

正常拉取助手市场索引和插件索引，正常访问。

### 📷 复现步骤

阿里云ECS云服务器，使用1Panel面板，使用docker部署

**Comment by arvinxx** [comment]
可能被墙了…

**Comment by coulsontl** [comment]
> 可能被墙了…

Docker部署能否支持一下http_proxy

**Comment by MarkHappyShao** [comment]
这个最后要如何解决？ @mqhe2007
