### ISSUE TITLE
[Bug] 当前版本GPT4无法开启商店中的部分插件功能

### ISSUE THREAD

**Issue by TyangWu** [lobehub/lobe-chat#1992]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

如题，开启后报错
<img width="574" alt="2024-04-12_061726" src="https://github.com/lobehub/lobe-chat/assets/156160589/bba265af-d5f5-45cf-abc0-deb3f69a5e3c">

**Comment by yincangshiwei** [comment]
可以先选回GPT-4 Trubo Preview模型，新模型有问题，我也是。
