### ISSUE TITLE
[Bug] Vercel 部署时预渲染页面错误

### ISSUE THREAD

**Issue by PeterBilly** [lobehub/lobe-chat#1993]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

我拉取了LobeChat v0.147.6版本到我的Fork中(从v0.146.2到v0.147.6)，并触发了Vercel的自动部署。
Vercel无法完成自动部署的Build阶段，日志显示在预渲染`/settings/agent`和`/chat/mobile`时出现`ERR_REQUIRE_ESM`错误。
具体地:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /vercel/path0/node_modules/shiki/dist/index.mjs not supported.
```
我做了以下操作：
- 对v0.147.6版本执行重新部署(Redeploy)，失败，错误日志大致相同。
- 回到v0.146.2(最后一个可用的版本)执行重新部署(Redeploy)，失败，错误日志大致相同。

### 🚦 期望结果

考虑Vercel更新了他们的部署环境：
`Vercel CLI: 33.7.0 -> 33.7.1`

### 📷 复现步骤

1. 准备一个运行着 lobe-chat v0.146.2版本的Vercel部署。
2. 拉取 lobehub/lobe-chat [🔖 chore(release): v0.147.6 [skip ci]](https://github.com/lobehub/lobe-chat/commit/b7768f9c67976a6cf4d001f9c393ad852bfd39e1)
3. 等待Vercel触发自动部署/手动Deploy

### 📝 补充信息

使用v0.147.6和v0.146.2版本的LobeChat在Vercel上的完整错误日志，以及最后一次成功的部署(v0.146.2)日志
[last_successful_v0.146.2.log](https://github.com/lobehub/lobe-chat/files/14952211/last_successful_v0.146.2.log)
[v0.146.2.log](https://github.com/lobehub/lobe-chat/files/14952212/v0.146.2.log)
[v0.147.6.log](https://github.com/lobehub/lobe-chat/files/14952213/v0.147.6.log)
：

**Comment by felixiho** [comment]
i'm also experiencing the same issue.
