### ISSUE TITLE
[Request] 是否能考虑在环境变量中配置 Azure OpenAI 模型

### ISSUE THREAD

**Issue by fooooxxxx** [lobehub/lobe-chat#1996]
## 原因
已知 v0.147.0 之后的版本不再像以前一样使用 `CUSTOM_MODELS` 去自定义模型 #1968 #1056 , 而是需要使用者在设置中手动配置 Azure 相关模型.

这导致了使用 Azure OpenAI 的用户无法做到输入密码后开箱即用

## 需求
想要在应用部署时配置好 Azure OpenAI 模型, 使得普通用户可以开箱即用

### 🧐 解决方案

在环境变量中新增变量 `AZURE_OPENAI_MODEL_LIST` 以预先配置 Azure OpenAI 的模型, 使得用户不再需要自己配置模型

语法类似于这样 
```
id=azureDeployName[?key=value][&key=value]
```
## 举例
我想要预先配置一个`gpt-4-vision`模型, 其在 Azure OpenAI 的部署名为 `gpt-4-vision-preview`
那我应当配置变量 
```env
AZURE_OPENAI_MODEL_LIST=gpt-4-vision=gpt-4-vision-preview?vision=true&functionCall=true
```

如果有多个模型配置则使用 逗号 分割
```env
AZURE_OPENAI_MODEL_LIST=gpt-4-vision=gpt-4-vision-preview?vision=true&functionCall=true,gpt-3.5=gpt-35-turbo
```

### 📝 补充信息

模型配置语法也可以直接使用JSON或者别的，只要能实现目的就可以了

非常感谢LobeChat和它的开发者们 🥰

**Comment by arvinxx** [comment]
嗯，我认为 Azure 需要一个 MODEL_LIST ， 就是之前语法还没想好。整体的逻辑应该会参考之前写的。
https://github.com/lobehub/lobe-chat/issues/1244#issuecomment-1937000393

主要的问题是 deploymentName 应该放在哪

**Comment by arvinxx** [comment]
已经支持，语法规则如下：

```shell
id->deploymentName=displayName
```

如果填 deploymentName，那么默认使用 id 。晚点我把文档加上去

**Comment by fooooxxxx** [comment]
试了一下一切正常👍
```env
AZURE_MODEL_LIST=gpt-3.5-trubo->gpt-35-turbo=GPT-3.5 Turbo<16384:fc>,gpt-4-trubo->gpt-4-turbo-preview=GPT-4 Turbo<128000:fc>,gpt-4-trubo-vision->gpt-4-vision-preview=GPT-4 Turbo Vision<128000:fc:vision>
```

**Comment by any35** [comment]
this is NOT work in current version!
