### ISSUE TITLE
[Bug] Ollama配置中自定义qwen:32b模型支持函数调用却不起作用

### ISSUE THREAD

**Issue by riverscn** [lobehub/lobe-chat#2000]
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Edge

### 🐛 问题描述

<img width="723" alt="image" src="https://github.com/lobehub/lobe-chat/assets/555062/2ebac262-be76-4d62-9845-bf942cbf4403">
<img width="723" alt="image" src="https://github.com/lobehub/lobe-chat/assets/555062/f63a839e-8077-4a23-b1bc-59d60cebd5eb">

### 🚦 期望结果

能够使用function calling

**Comment by zidanereal5** [comment]
Ollama配置中自定义qwen:32b模型支持函数调用吗？能调用成功吗
