### ISSUE TITLE
[Bug] 无法删除/修改之前客户端环境变量时期所设置的模型

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#2003]
### 💻 Operating System

macOS

### 📦 Environment

Docker

### 🌐 Browser

Safari

### 🐛 Bug Description

如题，近期更新了可视化的 Model list，但是在使用问题中出现了如下问题。

## 以往

我原先通过部署一个私有的 LobeChat 网站，供朋友们使用，然而我还有一些不愿意允许公开访问的模型，但是我想自己用，于是我通过创建一个新的 OpenAI API Key，并在客户端设置页面搭配类似如下的环境变量，实现只有本地可用 Claude 模型。

```text
-all,+gpt-3.5-turbo-0125=GPT-3.5 Turbo,+gpt-4-0125-preview=GPT-4 Turbo,+gpt-4-vision-preview=GPT-4 Vision,+claude-3-opus-20240229=Claude-3 Opus,+claude-3-sonnet-20240229=Claude-3 Sonnet,+claude-3-haiku-20240307=Claude-3 Haiku
```

这样的环境变量使用。

## 现在

然而，更新后，我发现我似乎无法设置这个变量了，也即无法在客户端完全的自定义模型变量，取而代之的是一个获取列表的功能，这造成了不便，我无法移除、重命名原先通过本地环境变量添加的模型，也无法覆盖命名（修改提供的模型的显示名）。

举个例子，我现在的服务器 docker 配置如下：

```text
OPENAI_MODEL_LIST=-all,+gpt-3.5-turbo-0125=GPT-3.5 Turbo,+gpt-4-turbo-2024-04-09=GPT-4 Turbo
```

在本地，我看到的是这样的：

![image](https://github.com/lobehub/lobe-chat/assets/36695271/df3126ef-0f78-4584-af5c-978a18f8e456)

可以看到，我无法移除/重命名原先客户端环境变量时期添加的 Claude 系列的模型，亦无法将这个原先客户端环境变量时期所设置的 GPT-4-New 重命名为 GPT-4 Turbo。

**Comment by zhuozhiyongde** [comment]
我还注意到，即使我重置了设置，面对本地变量和客户端变量的冲突的时候，还会出现奇怪的重复：

![image](https://github.com/lobehub/lobe-chat/assets/36695271/47dea3b8-4dc9-4493-8c62-fbbb2697e867)

**Comment by MegaSuite** [comment]
我通过vercel部署，也出现了类似的问题
![IMG_3216](https://github.com/lobehub/lobe-chat/assets/108850837/93107450-ec63-42b7-be1d-7c19478e4bd7)
![IMG_3217](https://github.com/lobehub/lobe-chat/assets/108850837/04d1e5ca-406d-401a-8ad3-e1b34545a50a)

**Comment by zhuozhiyongde** [comment]
换句话说，就是不支持修改名列默认模型列表的默认模型的显示名、删除已添加的默认模型。

**Comment by MegaSuite** [comment]
> 我通过vercel部署，也出现了类似的问题 ![IMG_3216](https://private-user-images.githubusercontent.com/108850837/321876115-93107450-ec63-42b7-be1d-7c19478e4bd7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDM3NzUsIm5iZiI6MTcxMjkwMzQ3NSwicGF0aCI6Ii8xMDg4NTA4MzcvMzIxODc2MTE1LTkzMTA3NDUwLWVjNjMtNDJiNy1iZTFkLTdjMTk0NzhlNGJkNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMDYzMTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2MyZmNhYmY4NzU0NjE3YTk5ZmUxZWU5YmIzZThiMGVlZTc1MTA2ZmU0Yjk5MjBjMjA2YzIyZjhmYjBlZDc1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EMDWPmIzY6M8KlnTdCvyUoEJbInYGbb7ZBFNjSdD22Q) ![IMG_3217](https://private-user-images.githubusercontent.com/108850837/321876130-04d1e5ca-406d-401a-8ad3-e1b34545a50a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDM3NzUsIm5iZiI6MTcxMjkwMzQ3NSwicGF0aCI6Ii8xMDg4NTA4MzcvMzIxODc2MTMwLTA0ZDFlNWNhLTQwNmQtNDAxYS04YWQzLWUxYjM0NTQ1YTUwYS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMDYzMTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQyOTIwNmQ0ZTgyZjdhZTFjNzI3OWE1MTJiN2UyYzAyMjU0YTAxNWI2N2QzMjkwZWZiZDkyN2RhMjk1NGQ3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Wqbabow4b_SyMLB3JSOmiN-xhpaZQBNZP6iruRG5OUs)

通过点击下图标注的刷新按钮解决了这个问题

**Comment by XiaolongYang-HZAU** [comment]
vercel部署遇到了一样的问题，必须手动点击模型列表中的刷新按钮，环境变量的模型才会生效

**Comment by arvinxx** [comment]
> 我发现我似乎无法设置这个变量了，也即无法在客户端完全的自定义模型变量，取而代之的是一个获取列表的功能，这造成了不便，我无法移除、重命名原先通过本地环境变量添加的模型，也无法覆盖命名（修改提供的模型的显示名）。

这个应该是我之前的一个实现逻辑问题，会优先找预设列表中存在的同名 id，如果存在则认为是LobeChat 内置的模型，不允许修改。这个我后续修正下。

**Comment by arvinxx** [comment]
不过我觉得可能更好的方式应该是通过 one-api 这样的平台，你部署用的 apikey 可以只限制基础模型的 model-list，然后自己再建一个包含 opus的 apiKey 。这样更方便吧

**Comment by BlazarWinGX** [comment]
![463e4186-c578-481c-b9d1-1cd93f87da02](https://github.com/lobehub/lobe-chat/assets/133990625/3294352d-05ea-464b-866e-76b304d5ac21)
![6c1aded0-0f14-4c09-8f7e-fa96386bad01](https://github.com/lobehub/lobe-chat/assets/133990625/505e541a-ea34-4a50-970f-46334689dc96)
我也遇到了同样的问题，使用docker-compose部署，无法自定义模型。

**Comment by zhuozhiyongde** [comment]
> 不过我觉得可能更好的方式应该是通过 one-api 这样的平台，你部署用的 apikey 可以只限制基础模型的 model-list，然后自己再建一个包含 opus的 apiKey 。这样就你自己的电脑上填写 api key，拉个模型列表就好了

我觉得没必要吧，，，原先 lobe chat 就能做的事情，为啥要再让用户自己搞一个

这本身就是修改一个 Models 请求字段的事情，又搞一个 docker 感觉 duck 不必

**Comment by zhuozhiyongde** [comment]
one-api 更多的还是做更多渠道/API供应商的负载均衡吧

**Comment by zhuozhiyongde** [comment]
> > 我发现我似乎无法设置这个变量了，也即无法在客户端完全的自定义模型变量，取而代之的是一个获取列表的功能，这造成了不便，我无法移除、重命名原先通过本地环境变量添加的模型，也无法覆盖命名（修改提供的模型的显示名）。
> 
> 这个应该是我之前的一个实现逻辑问题，会优先找预设列表中存在的同名 id，如果存在则认为是LobeChat 内置的模型，不允许修改。这个我后续修正下。

我觉得就不应该不允许修改内置模型，比如我想本地给内置模型重命名一下显示名，为啥就不行（

这本来就应该是一个完全客户端可控的配置项，对于服务端如果想限制，那么配置 API-Key 的权限才应该是更好的吧。

不过这也引发了一个问题，是否可以增加一个在 docker 部署的时候的选项，类似于“不允许客户端使用超出授权范围的模型”（在客户端不额外提供自己的 API 配置的情况下）。这似乎有点越权嫌疑，不应该是 Lobe Chat 干的事情，但我细想了一下觉得还是有必要的，原生的 OpenAI API Key 可能没有提供向现在这些代理提供的这么多的细粒度的管理吧？万一服务端设置的是只开 3.5，但是客户端自行修改开了 4，是不是就不太好。

@arvinxx

**Comment by arvinxx** [comment]
> 又搞一个 docker 感觉 duck 不必

你没懂我的意思。 One-api是支持key 颗粒度的模型管理的。比如给 a key 配置了 3.5 的模型，那么用户输入a key然后点下获取，模型列表里就只会有3.5。 

像你说的这个情况，我感觉就是你默认的部署镜像就用a key。 然后你给自己创建一个 b key ，里面添加 opus / 4 等自己要用的模型，然后把这个key填到你自己的本地电脑上，再拉取一下列表就是这个 key 的模型了。

**Comment by zhuozhiyongde** [comment]
> > 又搞一个 docker 感觉 duck 不必
> 
> 你没懂我的意思。 One-api是支持key 颗粒度的模型管理的。比如给 a key 配置了 3.5 的模型，那么用户输入a key然后点下获取，模型列表里就只会有3.5。
> 
> 像你说的这个情况，我感觉就是你默认的部署镜像就用a key。 然后你给自己创建一个 b key ，里面添加 opus / 4 等自己要用的模型，然后把这个key填到你自己的本地电脑上，再拉取一下列表就是这个 key 的模型了。

我就是这么做的呀

**Comment by zhuozhiyongde** [comment]
我用的API提供商本来就用到了one-api，我就是开了两个Key来管理权限，但是现在的问题是：
1. 我无法修改默认模型的显示名、是否启用函数、识图等配置项
2. 我觉得其实 lobe-chat 可以做一个这个选项，来允许没有使用 one-api 这样的“中间件”的用户在服务端实现额外模型的权限禁用

**Comment by arvinxx** [comment]
> 我觉得就不应该不允许修改内置模型，比如我想本地给内置模型重命名一下显示名，为啥就不行（

如果诉求上是服务端希望自己完全控制模型列表的话，那就干脆这个配置做成全自定义，不和我们预定义的list 合并。但这样一来就是所有的能力这些都要你自己定义，比如function call 这些。

**Comment by zhuozhiyongde** [comment]
这里的默认模型，指的是“在默认模型列表上的模型”，也即在 [modelProviders](https://github.com/lobehub/lobe-chat/blob/main/src/config/modelProviders/openai.ts) 里的。

**Comment by zhuozhiyongde** [comment]
> > 我觉得就不应该不允许修改内置模型，比如我想本地给内置模型重命名一下显示名，为啥就不行（
> 
> 如果诉求上是服务端希望自己完全控制模型列表的话，那就干脆这个配置做成全自定义，不和我们预定义的list 合并。但这样一来就是所有的能力这些都要你自己定义，比如function call 这些。
> 
> 如果你是希望在浏览器里修改服务端预定义的模型名，那这个需求是不合理的。

我的首要诉求是，在客户端（启用私有 api key url）的情况下可以完整的配置模型，在服务端可以配置是否限制客户端（在不提供额外的 Key 的情况下）修改启用模型、模型的配置。

**Comment by zhuozhiyongde** [comment]
或者说，我希望客户端在不提供额外的 key 的时候不允许 patch 服务端给的信息，但是如果客户端已经提供了额外的 key，那你客户端就成了服务端，允许你 patch，服务端就当一个 proxy 帮你完成请求罢了。

**Comment by arvinxx** [comment]
> 我觉得其实 lobe-chat 可以做一个这个选项，来允许没有使用 one-api 这样的“中间件”的用户在服务端实现额外模型的权限禁用

这个不计划做，不属于 lobe-chat 的范畴。应该交由 one-api这样的去管。

**Comment by zhuozhiyongde** [comment]
> 通过 api key 拉到

比如说我现在拉到的是 GPT-4 New 的显示名称，我希望他显示为 GPT-4 Turbo（

或者考虑一些奇葩的二开，他没有提供根据 api key 获取 models list 的情况呢

**Comment by arvinxx** [comment]
> 在客户端（启用私有 api key url）的情况下可以完整的配置模型

这个需求现在我理解应该满足了啊？ 你应该可以通过输入自定义模型id 来完成配置的吧

**Comment by zhuozhiyongde** [comment]
> > 我觉得其实 lobe-chat 可以做一个这个选项，来允许没有使用 one-api 这样的“中间件”的用户在服务端实现额外模型的权限禁用
> 
> 这个不计划做，不属于 lobe-chat 的范畴。应该交由 one-api这样的去管。

确实，我也感觉有点越权，但我是觉得做了也无伤大雅，还是那句话，不是所有人都有 one-api 中间件让你细粒度鉴权的，万一直接接到 openai 的官方源，（对于没有配置经验的人）就可能会出现预期外的情况。我在服务端开的只有 3.5，但是为啥你客户端可以加 4 的模型这样子的

**Comment by zhuozhiyongde** [comment]
> > 在客户端（启用私有 api key url）的情况下可以完整的配置模型
> 
> 这个需求现在我理解应该满足了啊？ 你应该可以通过输入自定义模型id 来完成配置的吧

可以加模型（而且只能加不能删），但是不能修改显示名与功能配置，也即不能 patch 拉到的 model 信息

**Comment by arvinxx** [comment]
> > 通过 api key 拉到
> 
> 
> 
> 比如说我现在拉到的是 GPT-4 New 的显示名称，我希望他显示为 GPT-4 Turbo（

我理解你应该可以通过添加 gpt-4-turbo 这个模型来覆盖原有的显示，我有专门做成用户定义的模型会覆盖预设模型的逻辑。
 
> 
> 或者考虑一些奇葩的二开，他没有提供根据 api key 获取 models list 的情况呢

这个不考虑了，为啥我要管这种奇葩？

**Comment by zhuozhiyongde** [comment]
> > > 我觉得其实 lobe-chat 可以做一个这个选项，来允许没有使用 one-api 这样的“中间件”的用户在服务端实现额外模型的权限禁用
> > 
> > 
> > 这个不计划做，不属于 lobe-chat 的范畴。应该交由 one-api这样的去管。
> 
> 确实，我也感觉有点越权，但我是觉得做了也无伤大雅，还是那句话，不是所有人都有 one-api 中间件让你细粒度鉴权的，万一直接接到 openai 的官方源，（对于没有配置经验的人）就可能会出现预期外的情况。我在服务端开的只有 3.5，但是为啥你客户端可以加 4 的模型这样子的

而且如果做了，应该设置为默认开启。

**Comment by zhuozhiyongde** [comment]
> > > 通过 api key 拉到
> > 
> > 
> > 比如说我现在拉到的是 GPT-4 New 的显示名称，我希望他显示为 GPT-4 Turbo（
> 
> 我理解你应该可以通过添加 gpt-4-turbo 这个模型来覆盖原有的显示，我有专门做成用户定义的模型会覆盖预设模型的逻辑。
> 
> > 或者考虑一些奇葩的二开，他没有提供根据 api key 获取 models list 的情况呢
> 
> 这个不考虑了，为啥我要管这种奇葩？

同 model ID 只能存在一个显示项。

第二点赞同，所以我说了可做可不做（

**Comment by arvinxx** [comment]
> 万一直接接到 openai 的官方源 

我记得现在官方源也有权限管理了吧。好像是可以设置 key 的

**Comment by zhuozhiyongde** [comment]
> > 万一直接接到 openai 的官方源
> 
> 我记得现在官方源也有权限管理了吧。好像是可以设置 key 的权限范围的

诶是吗，我今年二月后就没用过官方的 API了

**Comment by zhuozhiyongde** [comment]
草 感觉在 issue 版聊起来了，我们或许应该去 discord 讨论，在 issue 这里老给大家发邮件，不太好（

**Comment by arvinxx** [comment]
> 同 model ID 只能存在一个显示项。

哦 我知道了，这个算是一个小细节漏考虑了。 你可以试试先随便写一个 abx，然后把 id 改成gpt-4-turbo 呢？

**Comment by zhuozhiyongde** [comment]
> > 同 model ID 只能存在一个显示项。
> 
> 哦 我知道了，这个算是一个小细节漏考虑了。 你可以试试先随便写一个 abx，然后把 id 改成gpt-4-turbo 呢？

我们在 discord 聊吧
