### ISSUE TITLE
[Request] 能否在请求OpenAI时添加HttpsProxyAgent

### ISSUE THREAD

**Issue by fakeroot-lu** [lobehub/lobe-chat#2004]
### 🥰 需求描述

现有程序访问OpenAI时，无法获取操作系统环境变量：HTTPS_PROXY或者https_proxy设置代理地址。

### 🧐 解决方案

添加 https-proxy-agent，并从操作系统中获取变量 PROXY_URL

import http from 'http';
import { HttpsProxyAgent } from 'https-proxy-agent';

// Configure the default for all requests:
const openai = new OpenAI({
  httpAgent: new HttpsProxyAgent(process.env.PROXY_URL),
});

// Override per-request:
await openai.models.list({
  httpAgent: new http.Agent({ keepAlive: false }),
});

参考链接：https://www.npmjs.com/package/openai

**Comment by arvinxx** [comment]
'http'  'https-proxy-agent' 这俩库不兼容 Edge Runtime

**Comment by fakeroot-lu** [comment]
使用OpenAI的时候，不是lobe-chat调用openai接口吗？难道是通过浏览器直接访问吗？

**Comment by fakeroot-lu** [comment]
不好意思，我理解错了 Edge Runtime

**Comment by Hurray0** [comment]
我也有这个代理的问题，环境变量设置了HTTP_PROXY，但是不管用。
当前还是用腾讯云函数搭了一个openai的代理服务作为url才暂时解决的。希望能有更好用的方案

**Comment by cui-daniel** [comment]
迫于无奈自己写了个代理工具，现在可以使用代理访问ChatGPT了，https://github.com/cui-daniel/chatgpt-api-proxy
