### ISSUE TITLE
[Bug] OPENAI_API_KEY is required when deploy to Vercel

### ISSUE THREAD

**Issue by cnkang** [lobehub/lobe-chat#2007]
### 💻 Operating System

Ubuntu

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

It is required to have OPENAI_API_KEY set when deploying to Vercel, but I would prefer to make it optional so I can use Azure OpenAI API instead.

### 🚦 Expected Behavior

make OPENAI_API_KEY as optional value

### 📷 Recurrence Steps

deploy to Vercel

**Comment by arvinxx** [comment]
you can set it random like `abc` and then deploy once. then go to settings -> env to update it.

**Comment by cnkang** [comment]
Thanks, that solve the problem.
