### ISSUE TITLE
[Bug] 本地安装报错   error: MissingPackageJSON

### ISSUE THREAD

**Issue by anjiacm** [lobehub/lobe-chat#2011]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

/data/code/lobe-chat# bun i

error: MissingPackageJSON
Bun could not find a package.json file.

### 🚦 期望结果

/data/code/lobe-chat# bun i

error: MissingPackageJSON
Bun could not find a package.json file.

### 📷 复现步骤

/data/code/lobe-chat# bun i

error: MissingPackageJSON
Bun could not find a package.json file.

**Comment by arvinxx** [comment]
没懂

**Comment by MapleEve** [comment]
本地 yarn install 就起来了，你这是不是没有clone完整
