### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by securitgithub** [lobehub/lobe-chat#2017]
### 💻 系统环境

Other Linux

### 📦 部署环境

Other

### 🌐 浏览器

Chrome

### 🐛 问题描述

Microsoft Azure openAi 是不是必须要填客户端接口信息才能使用，能在服务端配置文件解决吗？
![image](https://github.com/lobehub/lobe-chat/assets/24914793/b33af413-31de-4702-8950-a0c58d19038e)
截图这样填了，就可以使用了（服务端配置不能正常使用），希望能在服务端配置文件解决这个问题，换台电脑又要设置。

**Comment by arvinxx** [comment]
看文档 https://lobehub.com/zh/docs/self-hosting/environment-variables/model-provider#azure-model-list
