### ISSUE TITLE
[Bug] 选择有字符限制的模型后在聊天输入框输入时卡顿明显

### ISSUE THREAD

**Issue by ShanySky** [lobehub/lobe-chat#2019]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Edge

### 🐛 问题描述

在配置稍弱的电脑上或者是在配置一般的手机上（骁龙870），只要选择有字符限制的模型，在聊天输入框输入时明显会觉得很卡，而换用没有字符限制的模型（如自定义模型）后就会恢复正常。这个问题在配置高的新电脑上不明显，今天是在旧电脑上发现的，旧电脑CPU是i7-8550U，16G内存，出现该问题时CPU的使用率看不出什么问题，内存的使用率也没有超过60%。我翻看了issue，有一个类似的问题 #1701 ，有没有可能是有字符限制的模型在输入时需要实时统计已使用字符，然后又要渲染页面导致CPU不够用或是前端线程分配不过来？
![image](https://github.com/lobehub/lobe-chat/assets/61485912/45eaa233-b152-47b6-8627-3992f79a414a)

### 🚦 期望结果

在配置稍弱的电脑上或是在手机上，使用带字符限制（即带已使用字符统计功能）的模型，在聊天框输入时也能很流畅。

### 📷 复现步骤

在配置稍弱的电脑上或者是在配置一般的手机上，选择带字符限制的模型，在聊天输入框输入文本。我能复现出来的电脑的配置是：i7-8550U，16G内存，手机的配置是：骁龙870，8G内存。

**Comment by XiaolongYang-HZAU** [comment]
在最近版本遇到了相同的问题，在清楚历史记录后有所缓解，但是仍然不如旧版本流畅

**Comment by CXwudi** [comment]
大家知道上一个不卡的版本是哪个吗？这卡顿根本用不了啊

**Comment by arvinxx** [comment]
@CXwudi 最新版应该修正了，你试了最新版了么？

**Comment by CXwudi** [comment]
哦哦，最新版没问题了，感谢修复

**Comment by ShanySky** [comment]
刚试了下当前的最新版本 0.147.10，确实已经解决了，感谢修复。
