### ISSUE TITLE
[Question] 如何将助手市场的内容改为自己的私有部署助手市场内容

### ISSUE THREAD

**Issue by Dreamkaka** [lobehub/lobe-chat#202]
### 🧐 问题描述 | Proposed Solution

看到助手市场能自己部署，就自己部署了一个，但是没有找到相关的配置更改教程，想问一下该如何把默认的市场改为自己部署的市场🤔

**Comment by canisminor1990** [comment]
配置功能还在开发中，会在近期上线，倒是会关联此 issue

**Comment by arvinxx** [comment]
已补充文档： https://github.com/lobehub/lobe-chat/blob/main/docs/Environment-Variable.zh-CN.md#agents_index_url
