### ISSUE TITLE
[Request] Support turning off animation effects

### ISSUE THREAD

**Issue by luckyyyyy** [lobehub/lobe-chat#2025]
### 🥰 Feature Description

Although the animation of antd is overall excellent, I hope to be able to turn it off as it is not entirely suitable for productivity tools.

### 🧐 Proposed Solution

```tsx
  <ConfigProvider motion={config.motion}>
   
  </ConfigProvider>
```

**Comment by KenMacD** [comment]
At the very least please provide an option to not animate the waving hand on the inbox/welcome page. The other animations typically activate on hover but that waving hand waves all the time, and is particularly distracting when it just happens to be on screen while doing other tasks.
