### ISSUE TITLE
[Request] Can Azure OpenAI support custom Display Name?

### ISSUE THREAD

**Issue by missuo** [lobehub/lobe-chat#2030]
### 🥰 Feature Description

<img width="491" alt="image" src="https://github.com/lobehub/lobe-chat/assets/55200481/446ad52a-8ab1-4504-9c91-75d1c566cd8c">

Currently, after Azure OpenAI added GPT-4, it seems that custom display names cannot be set, which looks somewhat inconsistent. Hopefully, this can be supported.

<img width="631" alt="image" src="https://github.com/lobehub/lobe-chat/assets/55200481/74798ffb-5568-4340-b01c-68b41385cc9e">

GPT-3.5-Turbo can be set.

### 🧐 Proposed Solution

Consistency for all display names

**Comment by arvinxx** [comment]
It's might a bug. Let me check it.
