### ISSUE TITLE
[Bug] 使用gpt-4-vision-preview，回應的message都很短

### ISSUE THREAD

**Issue by VolunteerFun123** [lobehub/lobe-chat#2045]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

我使用的lobechat version為: v0.147.15
當我使用gpt-4-vision-preview時，任何訊息回應很短
![image](https://github.com/lobehub/lobe-chat/assets/156403194/6763d618-9685-45d9-ad10-4c4b695cd7e6)
但我轉為openai  時，回應都正常
![image](https://github.com/lobehub/lobe-chat/assets/156403194/d9097286-2605-4bf2-91c8-396c1cc07304)

**Comment by arvinxx** [comment]
原因看下： https://github.com/lobehub/lobe-chat/discussions/427#discussioncomment-7540361 理论上这个问题我应该修复了才对啊

**Comment by VolunteerFun123** [comment]
您好，感謝您的回覆
但我從docker compose中設定env
DEFAULT_AGENT_CONFIG: model=gpt-4-trubo-vision;params.max_tokens=800
仍然無法work
Docs中找不到azure openai的max_tokens設置
請問您應該如何正確設置呢?
感謝!!

查看丟出的json內容，確實沒有帶到max_tokens
{"model":"gpt-4-vision-preview","stream":true,"frequency_penalty":0,"presence_penalty":0,"temperature":0.6,"top_p":1,"messages":[{"content":"請解釋kubernetes","role":"user"}]}

**Comment by arvinxx** [comment]
为什么会有 turbo-vision 这个model name…

**Comment by VolunteerFun123** [comment]
延續上述的問題
我發現送出request時，azure問完還會繼續問openai，不知道是否有影響?
但openai 這邊我已經設置OPENAI_MODEL_LIST: -all
![image](https://github.com/lobehub/lobe-chat/assets/156403194/9d208b2f-9c8a-49cd-a5a5-d0692a10e944)


azure openai的回應還是短訊息(但有max_tokens=2048)
AZURE_MODEL_LIST設置如下: 
AZURE_MODEL_LIST: gpt-4-vision-preview=gpt-4-vision-preview<128000>
![image](https://github.com/lobehub/lobe-chat/assets/156403194/0bce41e6-0c57-4622-99bf-bd7aceb1cfe0)

**Comment by VolunteerFun123** [comment]
後來我把Model從
gpt-4-vision-preview  改為  gpt-4 
就正常了

AZURE_ENDPOINT: https://ai-gpt-application.openai.azure.com
AZURE_API_VERSION: 2024-02-15-preview
AZURE_MODEL_LIST: gpt-4=gpt-4<128000>

**Comment by wilber-F** [comment]
我也遇到同样的问题，使用azure的gpt-4-vision-preview模型，回复就会中途中断，在旧版本使用OPENAI_PROXY_URL参数部署时，只要把部署名设置成和OPENAI一致，是可以正常使用的，但更新到最新版本，改用AZURE_ENDPOINT参数部署后，就会中断。
