### ISSUE TITLE
如何添加商用的接口

### ISSUE THREAD

**Issue by myzf** [lobehub/lobe-chat#2049]
### 🥰 需求描述

使用了阿里云的阿里灵积的千问，有apikey，其他信息等，能否直接加入lobe chat中作为一种模型使用呢？
还是说目前不支持这样呢

### 🧐 解决方案

如果支持的话，可否告知下怎么用的

**Comment by arvinxx** [comment]
请前往 https://github.com/lobehub/lobe-chat/discussions/1284 提需求
