### ISSUE TITLE
[Bug] Performance issue with very large messages

### ISSUE THREAD

**Issue by johnnymo87** [lobehub/lobe-chat#2055]
### 💻 Operating System

macOS

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Firefox

### 🐛 Bug Description

Hi, thank you very much for this project!

I'd like to report a performance bug: the UI takes long time to display a message when it is very large.

I noticed this performance problem when I started using Gemini 1.5 Pro, with its 1056K context window. I was interested to see how much better the model's responses were when I gave it a massive amount of context, e.g. part of a book or a code base. But once I did this, the UI took a long time to display the very large message that I sent.

### 🚦 Expected Behavior

Just a guess, I wonder if the very large message would display quickly if by default we didn't display all of its contents, only the beginning? And if the user really wanted to see all of the very large message, perhaps there would be some UI element for the user to click.

### 📷 Recurrence Steps

1. Get about half a million tokens by downloading the complete works of Shakespeare and then copying the first 40K lines to your clipboard (assumes macOS).
   ```
   wget https://ocw.mit.edu/ans7870/6/6.006/s08/lecturenotes/files/t8.shakespeare.txt
   head -n 40000 t8.shakespeare.txt | pbcopy
   ```
2. Paste into a new chat with `Gemini 1.5 Pro`, send the message.

**Comment by arvinxx** [comment]
It's a known issue with tokenizer. https://github.com/lobehub/lobe-chat/discussions/1029

**Comment by johnnymo87** [comment]
Thank you very much for the response, @arvinxx. Should I close this issue since you're already tracking the issue over there?

**Comment by arvinxx** [comment]
@johnnymo87 just left it open. That's a discussion, not a really issue. I'll close the issue when I fix it in the future.

**Comment by arvinxx** [comment]
@johnnymo87 Hi, I think it's fixed. Please try it again?

**Comment by johnnymo87** [comment]
@arvinxx Works beautifully, thank you! 🙏 

<img width="757" alt="image" src="https://github.com/user-attachments/assets/a916be69-f27b-4140-9614-45c09f50a43a">

I tested:
* Uploading the Shakespeare message, getting a response.
* Clicking `View Details`.
* Clicking in and out of this particular `Topic`.

Performance was great for everything 👏 👏 👏
