### ISSUE TITLE
[Bug] AWS模型列表不能禁用不支持的模型

### ISSUE THREAD

**Issue by cnkang** [lobehub/lobe-chat#2056]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Safari

### 🐛 问题描述

我在AWS上没有开通Claude 3模型，但是这个模型被显示在列表中了，默认没办法禁用掉
![WX20240415-191141](https://github.com/lobehub/lobe-chat/assets/555836/de19f3c4-0ad4-4ba6-8e3b-3e94383508d8)

### 🚦 期望结果

希望可以有个类似AWS_MODEL_LIST的参数，可以选择去掉某些模型

**Comment by arvinxx** [comment]
现在有 `AWS_BEDROCK_MODEL_LIST` 可以自行配置
