### ISSUE TITLE
[Bug] % pnpm i  ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @sentry/integrations@7.110.1  This error happened while installing the dependencies of @sentry/nextjs@7.110.1  The latest release of @sentry/integrations is "7.110.0".  Other releases are:   * next: 7.80.2-alpha.1  If you need the full list of all 373 published versions run "$ pnpm view @sentry/integrations versions". Progress: resolved 527, reused 525, downloaded 0, added 0

### ISSUE THREAD

**Issue by shanghailiwei** [lobehub/lobe-chat#2059]
### 💻 Operating System

macOS

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

% pnpm i
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @sentry/integrations@7.110.1

This error happened while installing the dependencies of @sentry/nextjs@7.110.1

The latest release of @sentry/integrations is "7.110.0".

Other releases are:
  * next: 7.80.2-alpha.1

If you need the full list of all 373 published versions run "$ pnpm view @sentry/integrations versions".
Progress: resolved 527, reused 525, downloaded 0, added 0

**Comment by arvinxx** [comment]
it seems `@sentry/nextjs` latest version is 7.110.1: https://www.npmjs.com/package/@sentry/integrations. I think you might using cnpm and it's sync is down current. But it's not a bug with lobe-chat.
