### ISSUE TITLE
[Bug] webapp 经常报错

### ISSUE THREAD

**Issue by jasoncym** [lobehub/lobe-chat#2061]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

1. 助手不知道在哪里重命名
2. 在更新角色设定时，就经常报错。
3. 模型长期的配置好的信息都丢失，又要重新添加一次
4. openai的key莫名其妙说为空，明明是填好的。

### 🚦 期望结果

一切保存正常就好

**Comment by dalefengs** [comment]
1. 不知道就多点点
2. 报错请说明出来
3. 大概率是你清空了浏览器数据
4. 同上

不说明白问题，错误信息，大佬们怎么给你解决？
issues 建议 Close
