### ISSUE TITLE
自定义模型gpt-4-turbo-2024-04-09，不支持上传图片

### ISSUE THREAD

**Issue by znygithub** [lobehub/lobe-chat#2064]
### 🥰 需求描述

<img width="1038" alt="ba4bfb943ecec94546abe5d1ae965e4" src="https://github.com/lobehub/lobe-chat/assets/98650439/d479b7ec-4388-493a-8485-cd0412a74404">
求求噜，需要支持自定义模型也能上传图片，或者是适配一下这个模型

### 🧐 解决方案

需要支持自定义模型也能上传图片，或者是适配一下这个模型

**Comment by fooooxxxx** [comment]
1. 确定你的模型是否支持图片识别
2. 左下角点击设置，在模型列表中找到你的自定义模型，以我的Azure OpenAI 的 `MyCustomModel`为例，点击`配置模型`
![image](https://github.com/lobehub/lobe-chat/assets/33800760/5a903da9-b076-48b6-8107-18ca3ff12ebe)
3. 配置模型勾选`支持视觉识别`
![image](https://github.com/lobehub/lobe-chat/assets/33800760/5919cc24-ea06-4440-8571-13a5239f1a2b)

然后在返回对话界面，就能开启图片识别了

**Comment by Hurray0** [comment]
gpt-4-turbo-2024-04-09不需要自定义，就是gpt-4-turbo。当然刷新一下模型列表，也会有各个版本的，包括最新的0409
可以理解为openai官方会映射gpt-4-turbo到最新的模型版本。
