### ISSUE TITLE
[Bug] latex格式的东西显示无转换

### ISSUE THREAD

**Issue by cnliucheng** [lobehub/lobe-chat#2070]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

latex格式的内容在chatgpt显示无转换，但是在其它模型可以正常转换

### 🚦 Expected Behavior

希望可以正常显示LaTeX在chatgpt

**Comment by Anivie** [comment]
[see](https://github.com/lobehub/lobe-chat/discussions/502#discussioncomment-7653600).

**Comment by cnliucheng** [comment]
> [see](https://github.com/lobehub/lobe-chat/discussions/502#discussioncomment-7653600).

同一个公式，使用gemini模型可以正常显示LaTex，用chatgpt模型就不行

**Comment by Anivie** [comment]
> > [see](https://github.com/lobehub/lobe-chat/discussions/502#discussioncomment-7653600).
> 
> 同一个公式，使用gemini模型可以正常显示LaTex，用chatgpt模型就不行

这个是因为gemini和gpt使用的md方言不一致，lobe默认只适配gemini用的方言

**Comment by cnliucheng** [comment]
> > > [see](https://github.com/lobehub/lobe-chat/discussions/502#discussioncomment-7653600).
> > 
> > 
> > 同一个公式，使用gemini模型可以正常显示LaTex，用chatgpt模型就不行
> 
> 这个是因为gemini和gpt使用的md方言不一致，lobe默认只适配gemini用的方言

好的，目前使用chatg4模型的时候只能这样解决了，用其它的模型例如gemini、qwen都是正常的，谢谢。

**Comment by Haerbin23456** [comment]
差不多的问题。我这是 `\(` `\)` 和 `\[` `\]` 括起来的公式显示不了，如果手动改成 `$` `$` 或 `$$`  `$$` 就正常了，改完之后后续 `gpt-4-turbo-2024-04-09` 的回答也会自动采用  `$` `$` 和 `$$`  `$$`。
然而 `gpt-4-turbo-2024-04-09` 的默认回答似乎总是  `\(` `\)` 和 `\[` `\]` 的，如果没有前文语境并且没要求他用美元符号的话
![问题截图](https://github.com/lobehub/lobe-chat/assets/60066765/bf8568f0-66fc-4e0a-a5b7-86e4231ef85c)
```markdown
在数学和向量几何中，一个向量在另一个向量上的投影可以通过一定的公式计算得出。具体来说，如果我们想要计算向量 **b** 在向量 **a** 上的投影向量，我们可以使用以下公式：

设向量 **a** 和向量 **b** 分别为 \( \vec{a} \) 和 \( \vec{b} \)，则 **b** 在 **a** 上的投影向量 **proj_a(b)** 可以表示为：

\[ \text{proj}_{\vec{a}} (\vec{b}) = \frac{\vec{a} \cdot \vec{b}}{\vec{a} \cdot \vec{a}} \vec{a} \]

其中 "·" 表示向量的点积（内积），计算如下：

\[ \vec{a} \cdot \vec{b} = |\vec{a}| |\vec{b}| \cos \theta \]

这里 \( |\vec{a}| \) 和 \( |\vec{b}| \) 分别是向量 **a** 和 **b** 的模（长度），而 \( \theta \) 是两向量之间的夹角。

这个公式的几何意义是：将 **b** 向 **a** 的方向投影，得到的向量在 **a** 上的分量。这个投影向量与 **a** 同向或反向，并且其长度是 **b** 在 **a** 方向上的分量的长度。

例如，如果我们有向量 \( \vec{a} = (3, 4) \) 和 \( \vec{b} = (2, 1) \)，那么我们首先计算点积：

\[ \vec{a} \cdot \vec{b} = 3 \times 2 + 4 \times 1 = 6 + 4 = 10 \]

然后计算 \( \vec{a} \cdot \vec{a} \)：

\[ \vec{a} \cdot \vec{a} = 3 \times 3 + 4 \times 4 = 9 + 16 = 25 \]

因此，投影向量为：

\[ \text{proj}_{\vec{a}} (\vec{b}) = \frac{10}{25} \vec{a} = \frac{2}{5} (3, 4) = \left( \frac{6}{5}, \frac{8}{5} \right) \]

这就是 **b** 在 **a** 上的投影向量的表示方法。
```

**Comment by Anivie** [comment]
> 差不多的问题。我这是 `\(` `\)` 和 `\[` `\]` 括起来的公式显示不了，如果手动改成 `$` `$` 或 `$$` `$$` 就正常了，改完之后后续 `gpt-4-turbo-2024-04-09` 的回答也会自动采用 `$` `$` 和 `$$` `$$`。 然而 `gpt-4-turbo-2024-04-09` 的默认回答似乎总是 `\(` `\)` 和 `\[` `\]` 的，如果没有前文语境并且没要求他用美元符号的话 ![问题截图](https://private-user-images.githubusercontent.com/60066765/323482079-bf8568f0-66fc-4e0a-a5b7-86e4231ef85c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjA1MDgsIm5iZiI6MTcxMzQyMDIwOCwicGF0aCI6Ii82MDA2Njc2NS8zMjM0ODIwNzktYmY4NTY4ZjAtNjZmYy00ZTBhLWE1YjctODZlNDIzMWVmODVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA2MDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNGQ2NjgwY2RlMmU4MjI2Nzg1OTgzMDU0ZDZiOGUzYTAxNGJjZjczNGNjZGYxMDVjNDQwODM4MjYzMGVjNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LLlH44NDiS83pG1t1PiEaxEyU-KBSXgJ1iyAU_Xd1og)
> 
> ```
> 在数学和向量几何中，一个向量在另一个向量上的投影可以通过一定的公式计算得出。具体来说，如果我们想要计算向量 **b** 在向量 **a** 上的投影向量，我们可以使用以下公式：
> 
> 设向量 **a** 和向量 **b** 分别为 \( \vec{a} \) 和 \( \vec{b} \)，则 **b** 在 **a** 上的投影向量 **proj_a(b)** 可以表示为：
> 
> \[ \text{proj}_{\vec{a}} (\vec{b}) = \frac{\vec{a} \cdot \vec{b}}{\vec{a} \cdot \vec{a}} \vec{a} \]
> 
> 其中 "·" 表示向量的点积（内积），计算如下：
> 
> \[ \vec{a} \cdot \vec{b} = |\vec{a}| |\vec{b}| \cos \theta \]
> 
> 这里 \( |\vec{a}| \) 和 \( |\vec{b}| \) 分别是向量 **a** 和 **b** 的模（长度），而 \( \theta \) 是两向量之间的夹角。
> 
> 这个公式的几何意义是：将 **b** 向 **a** 的方向投影，得到的向量在 **a** 上的分量。这个投影向量与 **a** 同向或反向，并且其长度是 **b** 在 **a** 方向上的分量的长度。
> 
> 例如，如果我们有向量 \( \vec{a} = (3, 4) \) 和 \( \vec{b} = (2, 1) \)，那么我们首先计算点积：
> 
> \[ \vec{a} \cdot \vec{b} = 3 \times 2 + 4 \times 1 = 6 + 4 = 10 \]
> 
> 然后计算 \( \vec{a} \cdot \vec{a} \)：
> 
> \[ \vec{a} \cdot \vec{a} = 3 \times 3 + 4 \times 4 = 9 + 16 = 25 \]
> 
> 因此，投影向量为：
> 
> \[ \text{proj}_{\vec{a}} (\vec{b}) = \frac{10}{25} \vec{a} = \frac{2}{5} (3, 4) = \left( \frac{6}{5}, \frac{8}{5} \right) \]
> 
> 这就是 **b** 在 **a** 上的投影向量的表示方法。
> ```

具体讨论在这个[issue](https://github.com/lobehub/lobe-chat/issues/1609)中有，目前只能通过加prompt的方式解决，我也希望能支持gpt使用的方言
