### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by iqilu2012** [lobehub/lobe-chat#2077]
### 💻 Operating System

macOS

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

升级到最新版本后，生成的内容都是片断式的。生成不完整。不如升级前可以完整输出内容

### 🚦 Expected Behavior

升级到最新版本后，生成的内容都是片断式的。生成不完整。不如升级前可以完整输出内容

**Comment by arvinxx** [comment]
需要给出详细信息
