### ISSUE TITLE
[Request] 建议增加对使用Xinference本地部署的支持，不单单是Ollama

### ISSUE THREAD

**Issue by MarkHappyShao** [lobehub/lobe-chat#2084]
### 🥰 需求描述

建议增加对使用Xinference本地部署的支持，不单单是Ollma

### 🧐 解决方案

增加接口对接支持即可

**Comment by arvinxx** [comment]
@MarkHappyShao 给个理由？

**Comment by arvinxx** [comment]
在这里添加： https://github.com/lobehub/lobe-chat/discussions/1284
