### ISSUE TITLE
[Request] 鉴于ChatGPT已经可以免注册直接使用，是否能直接使用ChatGPT的接口？

### ISSUE THREAD

**Issue by aiddroid** [lobehub/lobe-chat#2085]
### 🥰 Feature Description

鉴于ChatGPT已经可以免注册直接使用，是否能直接使用ChatGPT的接口，达到无需填写Token开箱即可使用？

### 🧐 Proposed Solution

如上

**Comment by arvinxx** [comment]
这种逆向工程的事情不计划做。
