### ISSUE TITLE
[Bug] Authentik Middleware

### ISSUE THREAD

**Issue by shigomany** [lobehub/lobe-chat#2088]
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Other

### 🐛 Bug Description

When I provided all the information on authentic, when trying to communicate with AI, I do not see a window that requires authorization through Authentick. And the following errors appear in the console:

```log
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at /app/.next/server/src/middleware.js:13:74574
    at r5 (/app/.next/server/src/middleware.js:13:74892)
    at o8 (/app/.next/server/src/middleware.js:369:46269)
    at af (/app/.next/server/src/middleware.js:369:55910)
    at ay (/app/.next/server/src/middleware.js:369:57261)
    at Object.r [as handler] (/app/.next/server/src/middleware.js:369:56930)
    at /app/.next/server/src/middleware.js:13:23516
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/app/.next/server/src/middleware.js:13:15290)
    at /app/.next/server/src/middleware.js:13:23329

```

### 🚦 Expected Behavior

A window appears that you need to log in

### 📷 Recurrence Steps

Deploy via docker with provided variables:

File: `.env`:

```
# openssl rand -base64 32
NEXTAUTH_SECRET="****"

# SSO
ENABLE_OAUTH_SSO=1
SSO_PROVIDERS="authentik"
AUTHENTIK_CLIENT_ID="****"
AUTHENTIK_CLIENT_SECRET="****"
AUTHENTIK_ISSUER="https://authentik.mysite.com/application/o/ai/"
NEXTAUTH_URL="https://ai.mysite.com"

# MODELS
ANTHROPIC_API_KEY="sk-****"
OPENAI_API_KEY="sk-****"
```

File `docker-compose.yaml`:

```yaml
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    env_file:
      - .env
```

### 📝 Additional Information

Docker version: `Docker version 26.0.0, build 2ae903e`
Lobe chat: `v0.147.18`

**Comment by arvinxx** [comment]
@RealTong hi, please help to check it

**Comment by RealTong** [comment]
@shigomany 

You need to add the `ACCESS_CODE` environment variable. You can generate this value using `uuidgen` or by visiting the online website https://www.uuidgenerator.net/.

**Comment by shigomany** [comment]
@RealTong Yes, a window with an access code now appears. But if I enter it, then authorization via SSO does not require anyway) Authorization via SSO is just so necessary, it does **not protect** anything) And recently, access code has become **optional**

And error in console log exists:

```
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at /app/.next/server/src/middleware.js:13:74574
    at r5 (/app/.next/server/src/middleware.js:13:74892)
    at o8 (/app/.next/server/src/middleware.js:369:46269)
    at af (/app/.next/server/src/middleware.js:369:55910)
    at ay (/app/.next/server/src/middleware.js:369:57261)
    at Object.r [as handler] (/app/.next/server/src/middleware.js:369:56930)
    at /app/.next/server/src/middleware.js:13:23516
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/app/.next/server/src/middleware.js:13:15290)
    at /app/.next/server/src/middleware.js:13:23329
```

**Comment by arnabk** [comment]
I am getting the exact same error. I followed this documentation https://lobehub.com/docs/self-hosting/advanced/sso-providers/auth0

What was the resolution?

**Comment by shigomany** [comment]
This bug is not fixed because this bug was not well publicized.
