### ISSUE TITLE
[Request] 是不是可以给一个快速升级的方式，页面提示“有新版本可用：0.147.18”，但是无法一键升级

### ISSUE THREAD

**Issue by zytbft** [lobehub/lobe-chat#2090]
### 🥰 需求描述

[Request] 是不是可以给一个快速升级的方式，页面提示“有新版本可用：0.147.18”，但是无法一键升级

### 🧐 解决方案

希望你们能给出解决方案

**Comment by arvinxx** [comment]
你用啥部署的

**Comment by Hurray0** [comment]
我是用docker部署的，现在需要手动docker pull image，然后用之前的环境变量重新docker run一个新容器

**Comment by arvinxx** [comment]
https://lobehub.com/zh/docs/self-hosting/platform/docker#crontab-%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0%E8%84%9A%E6%9C%AC%EF%BC%88%E5%8F%AF%E9%80%89%EF%BC%89
