### ISSUE TITLE
[Bug] lob-chat docker 按步骤操作无法访问 ollama

### ISSUE THREAD

**Issue by tanjcf** [lobehub/lobe-chat#2091]
### 💻 Operating System

Other Linux

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

ollama 是运行正常，能在另一个节点上正常访问
![image](https://github.com/lobehub/lobe-chat/assets/70000350/ebe48012-ed69-42a7-962b-5b8b30c87850)
lobehub docker 运行正常
![image](https://github.com/lobehub/lobe-chat/assets/70000350/2225411d-0d34-4600-b645-e2ad83f7c3e1)

![image](https://github.com/lobehub/lobe-chat/assets/70000350/93a2e742-4073-4ca6-84e2-592748c741b6)
![image](https://github.com/lobehub/lobe-chat/assets/70000350/8f0e90d2-3c87-4169-b717-163de52a05e9)

**Comment by arvinxx** [comment]
没加 v1 ?

**Comment by tanjcf** [comment]
> 没加v1？

![image](https://github.com/lobehub/lobe-chat/assets/70000350/23dbfa0d-7e9f-49ae-8a9c-eef2d982906d)
![image](https://github.com/lobehub/lobe-chat/assets/70000350/28436396-65c6-4e52-8f87-fef1d627a257)

**Comment by tanjcf** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/70000350/01cd7c49-515d-480b-b358-446ca711fa94)
![image](https://github.com/lobehub/lobe-chat/assets/70000350/2735eb9e-9d9f-46f7-ba3d-8d92619c3ce8)

**Comment by skyfox2000** [comment]
<img width="749" alt="image" src="https://github.com/lobehub/lobe-chat/assets/44539673/7664d1c1-e176-40d5-9ac0-e57bd9eccb13">
调用Ollama时使用了Options方法，导致无法返回结果

**Comment by saccohuo** [comment]
+1

**Comment by skyfox2000** [comment]
> <img alt="image" width="749" src="https://private-user-images.githubusercontent.com/44539673/324192106-7664d1c1-e176-40d5-9ac0-e57bd9eccb13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODgwNDIsIm5iZiI6MTcxMzY4Nzc0MiwicGF0aCI6Ii80NDUzOTY3My8zMjQxOTIxMDYtNzY2NGQxYzEtZTE3Ni00MGQ1LTlhYzAtZTU3YmQ5ZWNjYjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA4MjIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZWVjMDllNzY0OWNjYWE0N2JmNWM1ZWY0ZGM4MGZlMjUwNzEyMTNlMGRkZDM4ODcxMDc0M2M4ZjkzMGNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V-xUPYX70d8ddIab1ICjDHh0ov-qV54h5pTU-W91be8">
> 调用Ollama时使用了Options方法，导致无法返回结果 如何解决？

启动ollama docker时，增加参数 -e OLLAMA_ORIGINS=* 或者设置环境参数

**Comment by saccohuo** [comment]
> > <img alt="image" width="749" src="https://private-user-images.githubusercontent.com/44539673/324192106-7664d1c1-e176-40d5-9ac0-e57bd9eccb13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODgwNDIsIm5iZiI6MTcxMzY4Nzc0MiwicGF0aCI6Ii80NDUzOTY3My8zMjQxOTIxMDYtNzY2NGQxYzEtZTE3Ni00MGQ1LTlhYzAtZTU3YmQ5ZWNjYjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA4MjIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZWVjMDllNzY0OWNjYWE0N2JmNWM1ZWY0ZGM4MGZlMjUwNzEyMTNlMGRkZDM4ODcxMDc0M2M4ZjkzMGNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V-xUPYX70d8ddIab1ICjDHh0ov-qV54h5pTU-W91be8">
> > 调用Ollama时使用了Options方法，导致无法返回结果 如何解决？
> 
> 启动ollama docker时，增加参数 -e OLLAMA_ORIGINS=* 或者设置环境参数

我的配置如下，还是提示“未检测到 Ollama 服务，请检查是否正常启动”：
![image](https://github.com/lobehub/lobe-chat/assets/13887263/f60db5fd-78c0-4e61-bfff-265001d6fe49)

```
version: '3.8'
 
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    network_mode: host
    restart: always
    environment:
        - OLLAMA_ORIGINS=*
    volumes:
      - ./ollama:/root/.ollama
```

**Comment by InnerLive** [comment]
I have the same problem.
`OLLAMA_ORIGINS=*` is set in the Ollama Docker container.
I have also installed open-webui as a Docker and the access works there without any problems.

**Comment by LeonXu260** [comment]
I have the same issue as well, when I am trying to call Ollama with docker desktop. It gives me an error said something about the JSON format.

**Comment by LeonXu260** [comment]
Here's another issue that I have when running Ollama with docker desktop, not sure if we should be running Ollama on Docker desktop or I should download Ollama locally

<img width="486" alt="iShot_2024-04-22_08 34 52" src="https://github.com/lobehub/lobe-chat/assets/19643979/6833e838-9345-45a1-95ec-9d0698ccd1da">

**Comment by InnerLive** [comment]
> I have the same issue as well, when I am trying to call Ollama with docker desktop. It gives me an error said something about the JSON format. See images below when I am trying to call Ollama with docker desktop <img alt="iShot_2024-04-22_08 30 21" width="395" src="https://private-user-images.githubusercontent.com/19643979/324521402-4a501e91-2f45-46b5-9aa0-81b7873cd7e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDA2OTksIm5iZiI6MTcxMzgwMDM5OSwicGF0aCI6Ii8xOTY0Mzk3OS8zMjQ1MjE0MDItNGE1MDFlOTEtMmY0NS00NmI1LTlhYTAtODFiNzg3M2NkN2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE1Mzk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NjhlYzgyZWZhMmNiN2VkZGM1MzIxODNjZDc3MWJhZTdkNTg1MmRjMDBlMjNiMjVkY2RhY2M5YjZmNmZlZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uEQKbpSzPuPpoKvYzCtRVY8prhqh16p1Di8Qi5L1Wrw">

I get this error in the log:

`Route: [ollama] 500: [TypeError: Value is not JSON serializable]`
