### ISSUE TITLE
生成图片类与表格文档类的插件不能使用

### ISSUE THREAD

**Issue by your98k** [lobehub/lobe-chat#2099]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Safari

### 🐛 Bug Description

![IMG_7806](https://github.com/lobehub/lobe-chat/assets/167296005/e433e11c-7def-441c-9de6-497d803df316)
显示即将生成图片或者文档就没有后续了 所以插件都是如此

### 📷 Recurrence Steps

重复出现此bug

**Comment by arvinxx** [comment]
你确定你的模型支持fc吗
