### ISSUE TITLE
[Bug] 使用AWS - Claude3 opus 版本的时候  请求第一次成功 第二次就报错了

### ISSUE THREAD

**Issue by anjiacm** [lobehub/lobe-chat#2105]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

0|lobe-chat  |  ⨯ Error: failed to pipe response
0|lobe-chat  |     at pipeToNodeResponse (/data/code/lobe-chat/node_modules/next/dist/server/pipe-readable.js:111:15)
0|lobe-chat  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|lobe-chat  |     at async NextNodeServer.runEdgeFunction (/data/code/lobe-chat/node_modules/next/dist/server/next-server.js:1214:13)
0|lobe-chat  |     at async NextNodeServer.handleCatchallRenderRequest (/data/code/lobe-chat/node_modules/next/dist/server/next-server.js:245:37)
0|lobe-chat  |     at async NextNodeServer.handleRequestImpl (/data/code/lobe-chat/node_modules/next/dist/server/base-server.js:791:17)
0|lobe-chat  |     at async invokeRender (/data/code/lobe-chat/node_modules/next/dist/server/lib/router-server.js:174:21)
0|lobe-chat  |     at async handleRequest (/data/code/lobe-chat/node_modules/next/dist/server/lib/router-server.js:353:24)
0|lobe-chat  |     at async requestHandlerImpl (/data/code/lobe-chat/node_modules/next/dist/server/lib/router-server.js:377:13)
0|lobe-chat  |     at async Server.requestListener (/data/code/lobe-chat/node_modules/next/dist/server/lib/start-server.js:140:13) {
0|lobe-chat  |   [cause]: ValidationException: messages: roles must alternate between "user" and "assistant", but found multiple "assistant" roles in a row
0|lobe-chat  |       at D (/data/code/lobe-chat/.next/server/edge-chunks/837.js:78:26142)
0|lobe-chat  |       at G (/data/code/lobe-chat/.next/server/edge-chunks/837.js:78:27043)
0|lobe-chat  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|lobe-chat  |       at async /data/code/lobe-chat/.next/server/edge-chunks/837.js:78:26539
0|lobe-chat  |       at async tb.deserializer (/data/code/lobe-chat/.next/server/edge-chunks/837.js:78:10383)
0|lobe-chat  |       at async tb.asyncIterator (/data/code/lobe-chat/.next/server/edge-chunks/837.js:78:8909)
0|lobe-chat  |       at async T (/data/code/lobe-chat/.next/server/edge-chunks/837.js:247:3169)
0|lobe-chat  |       at async Object.pull (/data/code/lobe-chat/.next/server/edge-chunks/837.js:247:2136) {
0|lobe-chat  |     '$fault': 'client',
0|lobe-chat  |     '$metadata': {
0|lobe-chat  |       httpStatusCode: undefined,
0|lobe-chat  |       requestId: undefined,
0|lobe-chat  |       extendedRequestId: undefined,
0|lobe-chat  |       cfId: undefined
0|lobe-chat  |     }
0|lobe-chat  |   }
0|lobe-chat  | }
0|lobe-chat  | Error: aborted
0|lobe-chat  |     at abortIncoming (node:_http_server:794:17)
0|lobe-chat  |     at socketOnClose (node:_http_server:788:3)
0|lobe-chat  |     at Socket.emit (node:events:531:35)
0|lobe-chat  |     at Socket.emit (node:domain:488:12)
0|lobe-chat  |     at TCP.<anonymous> (node:net:337:12)
0|lobe-chat  |     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
0|lobe-chat  |   code: 'ECONNRESET'
0|lobe-chat  | }

### 🚦 Expected Behavior

使用AWS - Claude3 opus 版本的时候  请求第一次成功 第二次就报错了

**Comment by anjiacm** [comment]
/root/.pm2/logs/lobe-chat-error.log last 15 lines:
0|lobe-cha |     at Socket.emit (node:events:531:35)
0|lobe-cha |     at Socket.emit (node:domain:488:12)
0|lobe-cha |     at TCP.<anonymous> (node:net:337:12)
0|lobe-cha |     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
0|lobe-cha |   code: 'ECONNRESET'
0|lobe-cha | }
0|lobe-cha | Error: aborted
0|lobe-cha |     at abortIncoming (node:_http_server:794:17)
0|lobe-cha |     at socketOnClose (node:_http_server:788:3)
0|lobe-cha |     at Socket.emit (node:events:531:35)
0|lobe-cha |     at Socket.emit (node:domain:488:12)
0|lobe-cha |     at TCP.<anonymous> (node:net:337:12)
0|lobe-cha |     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
0|lobe-cha |   code: 'ECONNRESET'
0|lobe-cha | }

**Comment by arvinxx** [comment]
fix in https://github.com/lobehub/lobe-chat/pull/2439
