### ISSUE TITLE
Questions regarding Llama 3 on openrouter

### ISSUE THREAD

**Issue by dillfrescott** [lobehub/lobe-chat#2108]
It seems as though Llama 3 on openrouter does not support plugins/functions? But llama 3 was made for instructions, I think it should be allowed to use the plugins :)

**Comment by MapleEve** [comment]
https://github.com/meta-llama/llama3/issues/78

Llama3 并不源生支持这些功能，你需要找微调过的以它为基底的其他模型。

**Comment by dillfrescott** [comment]
But it seems as though no models on openrouter support plugins. Is this the case?

**Comment by arvinxx** [comment]
> But it seems as though no models on openrouter support plugins. Is this the case?

Currently yes. And I will improve it in the future https://github.com/lobehub/lobe-chat/discussions/1310
