### ISSUE TITLE
GigaChat

### ISSUE THREAD

**Issue by den47999** [lobehub/lobe-chat#2109]
### 🥰 Feature Description

Good afternoon: ) can you add the GigaChat model? 
https://developers.sber.ru/docs/ru/gigachat/api/overview

### 🧐 Proposed Solution

The only one of GigaChat's unique features is the creation of images based on text descriptions. This allows visualization of ideas, concepts and scenes described by the user.

**Comment by arvinxx** [comment]
Can you add this request to here? https://github.com/lobehub/lobe-chat/discussions/1284
