### ISSUE TITLE
[Bug] docker部署完后打不开

### ISSUE THREAD

**Issue by gaye746560359** [lobehub/lobe-chat#2112]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

版本0.148部署完后访问http://ip:3210打不开
![image](https://github.com/lobehub/lobe-chat/assets/3060035/a39e38b4-bdcb-4a8d-8b9c-a27c2cf4d180)

**Comment by arvinxx** [comment]
请给出更多信息

**Comment by gaye746560359** [comment]
不好意思，是服务器防火墙没有打开端口。
