### ISSUE TITLE
[Request] Groq支持手动填写API Endpoint

### ISSUE THREAD

**Issue by saccohuo** [lobehub/lobe-chat#2115]
### 🥰 需求描述

需求：Groq支持手动填写API Endpoint
使用场景：科学上网，使用代理做了API中转，需要手动填写Endpoint

### 🧐 解决方案

Groq支持手动填写API Endpoint

**Comment by arvinxx** [comment]
Groq 现在需要科学上网了么？

**Comment by saccohuo** [comment]
> Groq 现在需要科学上网了么？

不科学上网的话，Groq网站可以进去，但是会提示fail to fetch。
