### ISSUE TITLE
[Bug] Ollama API 的这个 Bug 好奇怪，实在不知道是啥情况。

### ISSUE THREAD

**Issue by BoosterCore** [lobehub/lobe-chat#2116]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

Ollama API 服务看起来是正常启动了，Lobe的模型设置页面看起来也是连通的，但聊天时就报错了。。。
![屏幕截图 2024-04-21 012449](https://github.com/lobehub/lobe-chat/assets/73834045/b0b1c09a-e266-4e32-9246-fea03171f561)
![屏幕截图 2024-04-21 012044](https://github.com/lobehub/lobe-chat/assets/73834045/ec69f2cc-ffc4-4159-9b73-c8f30e09774b)
![屏幕截图 2024-04-21 012131](https://github.com/lobehub/lobe-chat/assets/73834045/c75e9908-4a6f-4ee2-aa43-6e665e7e9b92)
![屏幕截图 2024-04-21 012230](https://github.com/lobehub/lobe-chat/assets/73834045/93e5d856-025d-4b7c-bd09-3c97766037f8)
![屏幕截图 2024-04-21 013324](https://github.com/lobehub/lobe-chat/assets/73834045/992abbaf-2758-4fc1-b6e8-2fa1630ca1fc)

**Comment by BoosterCore** [comment]
By the way, the same API service setting can use this project, https://github.com/Bin-Huang/chatbox, to normally call the llama3 model.

**Comment by arvinxx** [comment]
because the Call is from browser, there is CORS problem

**Comment by BoosterCore** [comment]
It's so strange, I woke up and the bug was gone! It finally works!

**Comment by gavid0124** [comment]
> because the Call is from browser, there is CORS problem

Who knows how to solve this problem? I encountered the same issue. Why is it that when using OpenAI's API no CORS problem?

**Comment by arvinxx** [comment]
@gavid0124 https://lobehub.com/docs/self-hosting/examples/ollama#setting-environment-variables-on-mac
