### ISSUE TITLE
[Request] 助手支持设置各自的语言模型，如果没有设置，则继承全局的语言模型

### ISSUE THREAD

**Issue by suka233** [lobehub/lobe-chat#2123]
### 🥰 需求描述

助手支持设置各自的语言模型，如果没有设置，则继承全局的语言模型。适用于对于单个平台，手上有多个不同的key或者不同的转发代理地址的情况。

### 🧐 解决方案

![image](https://github.com/lobehub/lobe-chat/assets/43712875/b4ada3af-8207-4e60-aff5-49410a19a071)

**Comment by arvinxx** [comment]
不计划支持。没必要
