### ISSUE TITLE
[Request] 在一次更新之后，输入框手动输入内容变得卡顿

### ISSUE THREAD

**Issue by M31ancholy** [lobehub/lobe-chat#2125]
### 🥰 需求描述

希望能够优化一下这个问题，保证正常的输入体验

### 🧐 解决方案

希望能够优化一下这个问题，保证正常的输入体验

**Comment by arvinxx** [comment]
哪个版本？

**Comment by M31ancholy** [comment]
v0.147.9 这个问题在手动慢速键盘输入的时候不明显，但是在快速输入的时候能感受到，可能是我版本太低了？

**Comment by arvinxx** [comment]
@M31ancholy 升级到最新版本，你说的这个版本是有这个问题，但在 https://github.com/lobehub/lobe-chat/pull/2012 已经修复了
