### ISSUE TITLE
antd Vercel build error

### ISSUE THREAD

**Issue by dillfrescott** [lobehub/lobe-chat#2126]
![Screenshot_20240421_044019](https://github.com/lobehub/lobe-chat/assets/56714680/48e864bd-226c-46bc-bf47-32e7e624c604)

**Comment by your98k** [comment]
我也是

**Comment by dillfrescott** [comment]
@your98k remove the `^`

https://github.com/lobehub/lobe-chat/blob/77e84a9c85999f8e2922fc5d54704cef50fa93ac/package.json#L102

**Comment by your98k** [comment]
> 删除`^`
> 
> https://github.com/lobehub/lobe-chat/blob/77e84a9c85999f8e2922fc5d54704cef50fa93ac/package.json#L102

好的 我试试

**Comment by arvinxx** [comment]
antd 已经修复
