### ISSUE TITLE
[Bug] 无法重新部署也无法更新

### ISSUE THREAD

**Issue by your98k** [lobehub/lobe-chat#2127]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Edge

### 🐛 Bug Description

![9b069a1605d9a0eecb74b61d0db01f1](https://github.com/lobehub/lobe-chat/assets/167296005/dbdc933c-2688-48d0-bd66-b50d71a9e81b)

**Comment by arvinxx** [comment]
antd 已经修复
