### ISSUE TITLE
[Request] Fetch model list with api key

### ISSUE THREAD

**Issue by moroeoer2** [lobehub/lobe-chat#2131]
### 🥰 Feature Description

Some openai endpoints require an api key to fetch the models list from /v1/models, currently it does not fetch the list with the api

### 🧐 Proposed Solution

Retry the model list fetch using the api key if no models are returned at the first attempt

**Comment by arvinxx** [comment]
actually we have supported the model list fetch. What's the detail of your problem ?

**Comment by moroeoer2** [comment]
Some endpoints require api key for the fetch

**Comment by arvinxx** [comment]
@moroeoer2 you can just add api key and then fetch the model list. What's the issue ?

**Comment by moroeoer2** [comment]
There's an endpoint which needs authorization for /v1/models, the fetch doesn't use api key for that

**Comment by arvinxx** [comment]
Actually the fetch use the apikey.
