### ISSUE TITLE
[Bug] undefined Logged in

### ISSUE THREAD

**Issue by ornell** [lobehub/lobe-chat#2134]
### 💻 Operating System

macOS

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

<img width="645" alt="Screenshot 2024-04-21 at 23 26 19" src="https://github.com/lobehub/lobe-chat/assets/2592716/1af97fa7-21b2-4bfd-a732-39002fb7d1ea">
When using Zitadel for auth and you have signed in, on the setting page (/settings/common) instead of showing the name, username or email for the signed in user it shows "undefined Logged in". 

### 🚦 Expected Behavior

Show given name, given + last name, nickname or email provided by zitadel.

**Comment by arvinxx** [comment]
@YangHanlin please help to check

**Comment by YangHanlin** [comment]
@ornell Do you have `Application Settings > Token Settings > User Info inside ID token` enabled? If not, could you please enable this option and try again?

![image](https://github.com/lobehub/lobe-chat/assets/8692892/17ea56b7-a96d-4966-ae29-8fce221b99d9)

**Comment by ornell** [comment]
You are entirely correct. It worked. Checked the docs and couldn't see it here though: https://lobehub.com/docs/self-hosting/advanced/sso-providers/zitadel 

MIght be worth adding :)
