### ISSUE TITLE
[Request] Embedded Ollama within lobechat

### ISSUE THREAD

**Issue by LeonXu260** [lobehub/lobe-chat#2137]
### 🥰 Feature Description

Currently, the Ollama model works by installing ollama separately. https://lobehub.com/docs/usage/providers/ollama

### 🧐 Proposed Solution

Embed Ollama model within the lobechat docker image or provide instructions on how to install Ollama with a separate docker images.

**Comment by MapleEve** [comment]
Ollama 的运行依赖于较大的显存，而 LobeChat 是一个纯前端的 Chatbot，如果有必要，他们应该分开部署。如果仅仅是本地部署， Ollama不应该运行在 Docker 内而是使用其官方的启动器。

**Comment by arvinxx** [comment]
我感觉可能的方式是提供一个docker compose的编排文件
