### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by methduck420** [lobehub/lobe-chat#2143]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Other

### 🐛 Bug Description

Error occurred while requesting Groq service. Please troubleshoot based on the following information or retry.
Show Details
json
{
  "error": {
    "headers": {
      "cache-control": "max-age=15",
      "connection": "keep-alive",
      "content-length": "4517",
      "content-type": "text/html; charset=UTF-8",
      "date": "Mon, 22 Apr 2024 07:06:20 GMT",
      "expires": "Mon, 22 Apr 2024 07:06:35 GMT",
      "referrer-policy": "same-origin",
      "set-cookie": "__cf_bm=ogWMUCOm5Z7wfwQsLOzxZsinAEhb1HbuVSpKTAbLrUU-1713769580-1.0.1.1-eHO_AlCqxQBfkMchVwbenwgOxooZM0Xk_9gSBzDv7S9hkkzBCQ8jJSLMWQm6i418aJ_8hDndDg6mY8L2qNNlyw; path=/; expires=Mon, 22-Apr-24 07:36:20 GMT; domain=.groq.com; HttpOnly; Secure; SameSite=None",
      "x-frame-options": "SAMEORIGIN"
    },
    "stack": "Error: 403 <!DOCTYPE html>\n\n\n\n <html class=\"no-js\" lang=\"en-US\"> \n<head>\n<title>Attention Required! | Cloudflare</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" />\n\n<style>body{margin:0;padding:0}</style>\n\n\n\n<script>\n  if (!navigator.cookieEnabled) {\n    window.addEventListener('DOMContentLoaded', function () {\n      var cookieEl = document.getElementById('cookie-alert');\n      cookieEl.style.display = 'block';\n    })\n  }\n</script>\n\n\n\n</head>\n<body>\n  <div id=\"cf-wrapper\">\n    <div class=\"cf-alert cf-alert-error cf-cookie-error\" id=\"cookie-alert\" data-translate=\"enable_cookies\">Please enable cookies.</div>\n    <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n      <div class=\"cf-wrapper cf-header cf-error-overview\">\n        <h1 data-translate=\"block_headline\">Sorry, you have been blocked</h1>\n        <h2 class=\"cf-subheadline\"><span data-translate=\"unable_to_access\">You are unable to access</span> groq.com</h2>\n      </div>\n\n      <div class=\"cf-section cf-highlight\">\n        <div class=\"cf-wrapper\">\n          <div class=\"cf-screenshot-container cf-screenshot-full\">\n            \n              <span class=\"cf-no-screenshot error\"></span>\n            \n          </div>\n        </div>\n      </div>\n\n      <div class=\"cf-section cf-wrapper\">\n        <div class=\"cf-columns two\">\n          <div class=\"cf-column\">\n            <h2 data-translate=\"blocked_why_headline\">Why have I been blocked?</h2>\n\n            <p data-translate=\"blocked_why_detail\">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>\n          </div>\n\n          <div class=\"cf-column\">\n            <h2 data-translate=\"blocked_resolve_headline\">What can I do to resolve this?</h2>\n\n            <p data-translate=\"blocked_resolve_detail\">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>\n          </div>\n        </div>\n      </div>\n\n      <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n  <p class=\"text-13\">\n    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">8783c543820a1122</strong></span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span id=\"cf-footer-item-ip\" class=\"cf-footer-item hidden sm:block sm:mb-1\">\n      Your IP:\n      <button type=\"button\" id=\"cf-footer-ip-reveal\" class=\"cf-footer-ip-reveal-btn\">Click to reveal</button>\n      <span class=\"hidden\" id=\"cf-footer-ip\">2a06:98c0:3600::103</span>\n      <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    </span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n  <script>(function(){function d(){var b=a.getElementById(\"cf-footer-item-ip\"),c=a.getElementById(\"cf-footer-ip-reveal\");b&&\"classList\"in b&&(b.classList.remove(\"hidden\"),c.addEventListener(\"click\",function(){c.classList.add(\"hidden\");a.getElementById(\"cf-footer-ip\").classList.remove(\"hidden\")}))}var a=document;document.addEventListener&&a.addEventListener(\"DOMContentLoaded\",d)})();</script>\n</div>\n\n\n    </div>\n  </div>\n\n  <script>\n  window._cf_translation = {};\n  \n  \n</script>\n\n</body>\n</html>\n\n    at (vc/edge/function:131:5173)\n    at (vc/edge/function:134:6395)\n    at (vc/edge/function:134:7339)\n    at (vc/edge/function:190:68040)\n    at (vc/edge/function:190:88387)\n    at (vc/edge/function:122:98536)\n    at (vc/edge/function:122:95315)\n    at (vc/edge/function:122:99829)\n    at (vc/edge/function:123:32585)\n    at (vc/edge/function:123:3805)",
    "status": 403
  },
  "endpoint": "https://api.groq.com/openai/v1",
  "provider": "groq"
}

### 🚦 Expected Behavior

i got this error when I checked my API key from Groq

**Comment by dholakashyap** [comment]
i too

**Comment by hrithikt** [comment]
@methduck420 , @dholakashyap can you guys try again once. i was facing the same issue some time back. but when i checked now its working fine. maybe its some issue on groq's side and they may have fixed it.

**Comment by methduck420** [comment]
all good. appreciate it

- Tim Chappell

**Comment by nagaame** [comment]
I have the same issue, but it's already been fixed now.

**Comment by dholakashyap** [comment]
Yeah, Mine too, it's working all good.

**Comment by arvinxx** [comment]
We do nothing. It mostly like the groq fixed the network issue.
