### ISSUE TITLE
[Bug] lobechat本地启动连接ollama无法访问

### ISSUE THREAD

**Issue by ganzi01234** [lobehub/lobe-chat#2144]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

如图，在浏览器中正常启动了ollama的服务
![image](https://github.com/lobehub/lobe-chat/assets/9687149/a33b18c3-2d10-48ac-969e-f169f254b6c7)
在lobechat中已经配置了ollama的服务，并且检查通过
![image](https://github.com/lobehub/lobe-chat/assets/9687149/0a0e5c55-a0cb-45f9-8704-e52f0356610c)
但是在对话的时候报错
![image](https://github.com/lobehub/lobe-chat/assets/9687149/442a237a-ae8d-4504-86cc-4d8f66407066)

### 🚦 期望结果

期望正常对话结果

### 📷 复现步骤

ollama和lobechat都是本地开发环境启动，没有使用dock启动lobechat

**Comment by yangkang5303** [comment]
ollama不支持 /v1/chat/completion 方法导致

**Comment by liusuchao** [comment]
Hello, I have the same problem?         

![Snipaste_2024-04-23_09-11-09](https://github.com/lobehub/lobe-chat/assets/15273205/133d03a3-4361-4d58-8f66-3de3eb92fc18)

**Comment by hallfay0** [comment]
> ollama不支持 /v1/chat/completion 方法导致

你知道如何解决这个错误？

**Comment by tisfeng** [comment]
> ollama不支持 /v1/chat/completion 方法导致

[Ollama OpenAI compatibility ](https://github.com/ollama/ollama/blob/main/docs/openai.md)

> Ollama provides experimental compatibility with parts of the [OpenAI API](https://platform.openai.com/docs/api-reference) to help connect existing applications to Ollama.
