### ISSUE TITLE
[Bug] 官网使用groq api请求被拒绝，疑似ip无法通过cloudflare验证

### ISSUE THREAD

**Issue by NextDoorLaoHuang-HF** [lobehub/lobe-chat#2147]
### 💻 系统环境

macOS

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

发送消息后返回：
{
  "error": {
    "headers": {
      "cache-control": "max-age=15",
      "connection": "keep-alive",
      "content-length": "4517",
      "content-type": "text/html; charset=UTF-8",
      "date": "Mon, 22 Apr 2024 06:35:04 GMT",
      "expires": "Mon, 22 Apr 2024 06:35:19 GMT",
      "referrer-policy": "same-origin",
      "set-cookie": "__cf_bm=_5_Yzf94aiWgBeeP9XEaFJNb3Pj_VLztIA1e46Ah2PE-1713767704-1.0.1.1-wNBJb1J38eIsBL61zf5CGXKsyVznbp6asqQdLXagWy15sdLgM768yoNUAXOxWUEAWRpyn7kQQg2lcBifCblfEg; path=/; expires=Mon, 22-Apr-24 07:05:04 GMT; domain=.groq.com; HttpOnly; Secure; SameSite=None",
      "x-frame-options": "SAMEORIGIN"
    },
    "stack": "Error: 403 <!DOCTYPE html>\n\n\n\n <html class=\"no-js\" lang=\"en-US\"> \n<head>\n<title>Attention Required! | Cloudflare</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" />\n\n<style>body{margin:0;padding:0}</style>\n\n\n\n<script>\n  if (!navigator.cookieEnabled) {\n    window.addEventListener('DOMContentLoaded', function () {\n      var cookieEl = document.getElementById('cookie-alert');\n      cookieEl.style.display = 'block';\n    })\n  }\n</script>\n\n\n\n</head>\n<body>\n  <div id=\"cf-wrapper\">\n    <div class=\"cf-alert cf-alert-error cf-cookie-error\" id=\"cookie-alert\" data-translate=\"enable_cookies\">Please enable cookies.</div>\n    <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n      <div class=\"cf-wrapper cf-header cf-error-overview\">\n        <h1 data-translate=\"block_headline\">Sorry, you have been blocked</h1>\n        <h2 class=\"cf-subheadline\"><span data-translate=\"unable_to_access\">You are unable to access</span> groq.com</h2>\n      </div>\n\n      <div class=\"cf-section cf-highlight\">\n        <div class=\"cf-wrapper\">\n          <div class=\"cf-screenshot-container cf-screenshot-full\">\n            \n              <span class=\"cf-no-screenshot error\"></span>\n            \n          </div>\n        </div>\n      </div>\n\n      <div class=\"cf-section cf-wrapper\">\n        <div class=\"cf-columns two\">\n          <div class=\"cf-column\">\n            <h2 data-translate=\"blocked_why_headline\">Why have I been blocked?</h2>\n\n            <p data-translate=\"blocked_why_detail\">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>\n          </div>\n\n          <div class=\"cf-column\">\n            <h2 data-translate=\"blocked_resolve_headline\">What can I do to resolve this?</h2>\n\n            <p data-translate=\"blocked_resolve_detail\">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>\n          </div>\n        </div>\n      </div>\n\n      <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n  <p class=\"text-13\">\n    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">87839777342a67b8</strong></span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span id=\"cf-footer-item-ip\" class=\"cf-footer-item hidden sm:block sm:mb-1\">\n      Your IP:\n      <button type=\"button\" id=\"cf-footer-ip-reveal\" class=\"cf-footer-ip-reveal-btn\">Click to reveal</button>\n      <span class=\"hidden\" id=\"cf-footer-ip\">2a06:98c0:3600::103</span>\n      <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    </span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n  <script>(function(){function d(){var b=a.getElementById(\"cf-footer-item-ip\"),c=a.getElementById(\"cf-footer-ip-reveal\");b&&\"classList\"in b&&(b.classList.remove(\"hidden\"),c.addEventListener(\"click\",function(){c.classList.add(\"hidden\");a.getElementById(\"cf-footer-ip\").classList.remove(\"hidden\")}))}var a=document;document.addEventListener&&a.addEventListener(\"DOMContentLoaded\",d)})();</script>\n</div>\n\n\n    </div>\n  </div>\n\n  <script>\n  window._cf_translation = {};\n  \n  \n</script>\n\n</body>\n</html>\n\n    at (vc/edge/function:131:5173)\n    at (vc/edge/function:134:6395)\n    at (vc/edge/function:134:7339)\n    at (vc/edge/function:190:68040)\n    at (vc/edge/function:190:88387)\n    at (vc/edge/function:122:98536)\n    at (vc/edge/function:122:95315)\n    at (vc/edge/function:122:99829)\n    at (vc/edge/function:123:32585)\n    at (vc/edge/function:123:3805)",
    "status": 403
  },
  "endpoint": "https://api.groq.com/openai/v1",
  "provider": "groq"
}

### 🚦 期望结果

修复该问题，或者为groq添加客户端请求模式，经测试，在本地通过代理可以正常使用该api

**Comment by dholakashyap** [comment]
i also got the same issue in vercel

**Comment by arvinxx** [comment]
@cy948 感觉 client 端请求可以给 groq 开启来试试看？

**Comment by saccohuo** [comment]
+1

**Comment by arvinxx** [comment]
这个问题现在还存在吗？

**Comment by NextDoorLaoHuang-HF** [comment]
> 这个问题现在还存在吗？

不存在了
