### ISSUE TITLE
[Bug] macOS Ollama 模型检查通过，但对话失败 CORS 报错

### ISSUE THREAD

**Issue by tisfeng** [lobehub/lobe-chat#2164]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

Ollama 模型检查通过，但对话失败 CORS 报错。

之前这里报过这个问题  https://github.com/lobehub/lobe-chat/discussions/728#discussioncomment-9196340 ，模型检查都会失败，后面参考这里 [在 Mac 上设置环境变量](https://lobehub.com/zh/docs/self-hosting/examples/ollama#%E5%9C%A8-mac-%E4%B8%8A%E8%AE%BE%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)，模型检查成功了，但对话还是失败 CORS，请问该如何解决？

我搜了一下，很多其他系统用户都提到了这个问题 https://github.com/lobehub/lobe-chat/issues/2144 。

<img width="1205" alt="image" src="https://github.com/lobehub/lobe-chat/assets/25194972/a78acf98-d4ab-40dc-833f-637b4817920b">

<img width="1300" alt="image" src="https://github.com/lobehub/lobe-chat/assets/25194972/7d91e3ac-9567-4a90-b1b6-c10f76af493d">

### 🚦 期望结果

我的服务部署在 Vercel，希望能在 Mac 本地使用 Ollama 模型。

**Comment by minosss** [comment]
Some here. If turn off client-side mode and use LAN IP it works.
lobe runs on a server in the LAN

**Comment by arvinxx** [comment]
It seems that we don't handle it correctly with client mode. I think it's a bug and I will fix it soon.

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/discussions/2169
