### ISSUE TITLE
[Bug] Attempted import error: 'Ai21' is not exported from '@lobehub/icons' (imported as 'Ai21').

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#2165]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

更新到v0.148.8，有些莫名错误提示，但好像不影响使用。
![image](https://github.com/lobehub/lobe-chat/assets/8185843/3479e09e-35dd-4643-ad31-fa48e8386e98)
![image](https://github.com/lobehub/lobe-chat/assets/8185843/a1b2bdd7-a72c-446a-9c51-cd01a2166d07)
![image](https://github.com/lobehub/lobe-chat/assets/8185843/15f3162f-ad3c-4a6e-b191-89212f26471f)

**Comment by arvinxx** [comment]
升级下本地依赖

**Comment by yincangshiwei** [comment]
> 升级下本地依赖

我升级了，每次更新版本，我都重新pnpm install。
