### ISSUE TITLE
[Bug] 写代码时，渲染了react代码，影响观看

### ISSUE THREAD

**Issue by DaZiYuan** [lobehub/lobe-chat#217]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/80653/e298b187-1865-4021-932d-d411f248696a)

### 🚦 期望结果 | Expected Behavior

返回代码就行，不要渲染UI

**Comment by canisminor1990** [comment]
是因为没有使用 markdown codeblock 么

**Comment by DaZiYuan** [comment]
我用的全栈 Web 开发人员这个模板。提问：用react写一个修改密码界面
![image](https://github.com/lobehub/lobe-chat/assets/80653/b022c334-609d-4333-921b-89b5e4bf5448)

**Comment by canisminor1990** [comment]
\`\`\`tsx
...react code
\`\`\`

**Comment by canisminor1990** [comment]
你那段渲染出错的文本能否提供一下，方便复现，我这边复现不出来

<img width="459" alt="image" src="https://github.com/lobehub/lobe-chat/assets/17870709/07800f01-6001-40fe-9a4e-f370fe8462c9">

**Comment by DaZiYuan** [comment]
我刚才刷新了下网页，重现不了。我再试试

**Comment by DaZiYuan** [comment]
重现了。提问：用react写一个修改密码界面 ``` test ```   。只要加了```就会出问题

**Comment by DaZiYuan** [comment]
写代码的时候经常会问，参考这个代码```....```

**Comment by leeyiding** [comment]
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>test</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      text-align: center;
      background-color: #f2f2f2;
    }
    button {
      padding: 10px 20px;
      font-size: 16px;
      background-color: #4CAF50;
      color: white;
      border: none;
      cursor: pointer;
      transition: background-color 0.3s;
    }
    button:hover {
      background-color: #45a049;
    }
  </style>
</head>
<body>
  <button onclick="redirect()">跳转</button>
  <script>
    function redirect() {
      window.location.href = "https://baidu.com";
    }
  </script>
</body>
</html>
```
我也复现了一下，把这串html代码不加代码块，直接发送，会直接渲染

**Comment by canisminor1990** [comment]
直接发不用代码块是会被解析的 因为加了remark对应的html解析能力 但代码块里面的不应该 实在不行只能把解析关了

**Comment by arvinxx** [comment]
> 直接发不用代码块是会被解析的 因为加了remark对应的html解析能力 但代码块里面的不应该 实在不行只能把解析关了

我存在稳定复现的情况：

异常被解析：

<img width="745" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/ee957256-2930-40aa-9b27-3c61a8ec2227">

步骤：
1. 找一个存在 shiki 高亮的代码块，等待其从未加载变成已加载；
2. 切换到相应的 html 代码块

![er](https://github.com/lobehub/lobe-chat/assets/28616219/d9c597be-7ed5-4d9a-981e-60fa3a99c6e6)

**Comment by canisminor1990** [comment]
fixed
