### ISSUE TITLE
配置oLLama代理地址报错[Bug] 

### ISSUE THREAD

**Issue by gavid0124** [lobehub/lobe-chat#2177]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Other

### 🌐 浏览器

Chrome

### 🐛 问题描述

Ollama服务是正常启动，见截图：
![20240424150247](https://github.com/lobehub/lobe-chat/assets/8635721/6db81fbb-9496-4a20-bcd3-b901498e2a39)
但是配置Ollama接口代理地址报错了
![20240424150107](https://github.com/lobehub/lobe-chat/assets/8635721/6bcda89f-4881-4b17-9260-7d66e8dff408)

### 🚦 期望结果

Ollama接口代理地址可以正常配置

### 📷 复现步骤

见问题描述及截图

**Comment by arvinxx** [comment]
升级到最新版再试试

**Comment by gavid0124** [comment]
> 升级到最新版再试试

我更新了代码，重启后还是同样的问题

**Comment by arvinxx** [comment]
清除 Ollama 的 proxy URL 和本地的proxy 设置，然后再试试呢

**Comment by gavid0124** [comment]
> 清除 Ollama 的 proxy URL 和本地的proxy 设置，然后再试试呢

还是不行，这是报错的截图：
![20240424160354](https://github.com/lobehub/lobe-chat/assets/8635721/870eea71-5f26-424c-8f32-215ba5043f7c)
清除proxy URL就是127.0.0.1方式调用了，浏览器控制台报这个错误：
![20240424160848](https://github.com/lobehub/lobe-chat/assets/8635721/4ddf7ced-9873-4776-91b4-26694a66e62f)
我发现用外网IP会出现CORS的问题，既然openai的接口也是远程方式可以调用，那ollama按说也应该可以的。所以，我有个建议：ollama是不是用后端方式调用就不会涉及CORS的问题了呢？

**Comment by arvinxx** [comment]
你这没更新最新版
