### ISSUE TITLE
[Bug] ollama连接问题

### ISSUE THREAD

**Issue by liuzj288** [lobehub/lobe-chat#2178]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

只能使用本机连接http://127.0.0.1:11434，使用局域网或者外网ip则显示报错
![image](https://github.com/lobehub/lobe-chat/assets/13833404/b1598770-6c72-4f63-9d22-5d1d05d64242)
![image](https://github.com/lobehub/lobe-chat/assets/13833404/1eda25e0-9bf1-491a-b80c-b631eab740ed)

而win10系统已设置系统环境变量OLLAMA_ORIGINS 和 OLLAMA_HOST，使用浏览器访问服务也没问题
![image](https://github.com/lobehub/lobe-chat/assets/13833404/24f0d372-dc3c-4bed-87a5-981c28c171b8)
![image](https://github.com/lobehub/lobe-chat/assets/13833404/87ba9348-2814-403d-b96c-36c9be3ba859)

这是什么原因导致的呢，是否有解决办法？

**Comment by miracletiger** [comment]
▲ Next.js 14.1.4
   - Local:        http://localhost:3210
   - Network:      http://0.0.0.0:3210

 ✓ Ready in 57ms
Route: [ollama] 500: [TypeError: Value is not JSON serializable] 
I encountered the same problem and had updated to the v0.148.10

**Comment by cnkang** [comment]
same here, it works in before

**Comment by arvinxx** [comment]
可能要设置 ollama ，配置host环境变量到 0.0.0.0 https://lobehub.com/zh/docs/self-hosting/examples/ollama#%E5%9C%A8-mac-%E4%B8%8A%E8%AE%BE%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

**Comment by arvinxx** [comment]
>    ▲ Next.js 14.1.4
> 
>    - Local:        http://localhost:3210
> 
>    - Network:      http://0.0.0.0:3210
> 
> 
> 
>  ✓ Ready in 57ms
> 
> Route: [ollama] 500: [TypeError: Value is not JSON serializable] 
> 
> I encountered the same problem and had updated to the v0.148.10                          

Plz update to 149

**Comment by liuzj288** [comment]
> 可能要设置 ollama ，配置host环境变量到 0.0.0.0 https://lobehub.com/zh/docs/self-hosting/examples/ollama#%E5%9C%A8-mac-%E4%B8%8A%E8%AE%BE%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

win102系统已添加环境变量OLLAMA_HOST

**Comment by liuzj288** [comment]
> @liuzj288 看下控制台请求是啥样的？

![image](https://github.com/lobehub/lobe-chat/assets/13833404/3318de51-2a93-4513-af29-20a214f1e52a)

**Comment by arvinxx** [comment]
@liuzj288 这个应该是浏览器限制，https 无法访问 http 协议的。如果你是使用的 Docker 部署，可以试试将 Ollama 的请求变成服务端发起（将客户端发起请求那个选项关掉）。如果你是使用 vercel 的话，那么应该无解（vercel 不支持在服务端调用ip）

**Comment by arvinxx** [comment]
> 那这样的话外网访问https域名的怎样添加ollama地址

不太明白你想做什么？是想把 ollama 以服务化的方式提供出来吗？

**Comment by BBM-Freehub** [comment]
有同样的问题，只能使用本机连接。跨域连接，在ollama.service中加入Environment="OLLAMA_ORIGINS=*"后可以检测成功，但会话时依旧报错。

**Comment by arvinxx** [comment]
@BBM-Freehub 更新到最新 0.149.0 了吗

**Comment by BBM-Freehub** [comment]
> @BBM-Freehub 更新到最新 0.149.0 了吗

使用了0.149.0最新版本，测试连接通过，但访问会话时，仍旧报错。但ollama在本机运行时正常。

**Comment by arvinxx** [comment]
> 访问会话时，仍旧报错。

具体报啥错呢？

**Comment by BBM-Freehub** [comment]
> > 访问会话时，仍旧报错。
> 
> 具体报啥错呢？

找到了原因，是配置里面的模型列表，之前版本模型名是我们自己创建的，现在的版本已经可以选择到llama3:70B和llama3:8B，所以再使用以前的名称，会话时就会报错。现在重新刷新了模型列表，选择列表中的名字，
![1](https://github.com/lobehub/lobe-chat/assets/86555393/37210304-8a20-458e-ac9e-199bc5186c9b)
该问题已经解决。
