### ISSUE TITLE
[Bug] pc端的edge浏览器升级后数据丢失&平时语言模型配置数据PC端、手机端不能同步

### ISSUE THREAD

**Issue by Nicecsh** [lobehub/lobe-chat#2179]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

1. pc端环境：Windows 11 家庭中文版23H2 22631.3447+Edge 124.0.2478.51  (64 位)，手机端环境：鸿蒙4.0+chrome 123.0.6312.99。

2. pc端的edge浏览器升级后，聊天列表中的所有助手丢失，chat聊天数据全部丢失，设置数据中只有语言模型--openai--模型列表数据和云端同步--同步频道密码保留， 语言模型、云端同步中的其它数据全部丢失。
但是之前登录成功的网站不会自动登录，重新登录时浏览器中保存的账号、密码都在，手动选择后登录成功，根据这种情况来看可能是edge浏览器自身的原因引起lobechat数据丢失。

 3. 平时pc端浏览器与手机端浏览器同时连接lobechat网站并显示“已同步”情况下，两边的语言模型设置数据不会实时同步。

**Comment by arvinxx** [comment]
看看这个 https://github.com/lobehub/lobe-chat/discussions/1685 是否是类似你的情况

**Comment by Nicecsh** [comment]
> 看看这个 #1685 是否是类似你的情况

大佬辛苦了☕️，这么晚还回信息

**Comment by arvinxx** [comment]
WebRTC 功能已归档，此 issue 终结
