### ISSUE TITLE
[Request] 默认ollama模型列表优化

### ISSUE THREAD

**Issue by jsoncode** [lobehub/lobe-chat#2181]
### 🥰 需求描述

在ollama模型列表里，对于默认列表，可以直接调用 http://127.0.0.1:11434/api/tags 接口进行显示，这样不用每次新增一个模型，还要在lobe里手动添加，非常麻烦。

### 🧐 解决方案

通过 http://127.0.0.1:11434/api/tags 接口来获取ollama模型列表

**Comment by arvinxx** [comment]
这里有个问题。因为其他provider的获取list，是拉到所有可用模型的 list ，而 ollama 这个的全量 list ，应该是他们官网的这个地方：https://ollama.com/library 。但目前没看到这个接口。所以暂时先隐藏了这个按钮。我觉得这个交互的逻辑是不一样的，一个是全量的list，一个是可用的 list
