### ISSUE TITLE
[Bug] vercel  中部署最新代码导致 Gemini 请求403 被限制区域

### ISSUE THREAD

**Issue by NuerSir** [lobehub/lobe-chat#2184]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

一直在 vercel 上使用没问题，最近 2 天内更新导致被区域限制，本地翻墙可以解决，不知什么原因，确认 vercel 在美区。
2 天前一直在用，且正常。
<img width="1024" alt="image" src="https://github.com/lobehub/lobe-chat/assets/6175358/3ecea1f5-c279-4e3a-9feb-e5a81bb27ed5">

**Comment by arvinxx** [comment]
refs: https://github.com/lobehub/lobe-chat/pull/2149 ， @RubuJam  看来得回滚了

**Comment by RubuJam** [comment]
> refs: https://github.com/lobehub/lobe-chat/pull/2149 ， @RubuJam  看来得回滚了？

我用了两天，都还正常，要不先回滚看看？

**Comment by Cassianvale** [comment]
你需要在新加坡才可以
