### ISSUE TITLE
[Bug] ollama 可以添加,检查通过,但是chat 中报错

### ISSUE THREAD

**Issue by miracletiger** [lobehub/lobe-chat#2187]
### 💻 Operating System

Ubuntu

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

可以添加ollama 模型,检查通过 选择ollama模型 chat 后报错, 使用的最新版本LobeChat v0.149.2 , ollama version is 0.1.32
{
  "error": {
    "message": "fetch failed",
    "name": "TypeError"
  },
  "provider": "ollama"
}

**Comment by miracletiger** [comment]
我使用了lobe 相同ip的ollama 可以访问了,其他服务器的ollama 访问会报错让检查扩域什么的, 
sudo bash -c 'cat <<'EOF' > /etc/systemd/system/ollama.service
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="OLLAMA_HOST=0.0.0.0"
Environment="OLLAMA_MODELS=/data/model/ollama_cache"
Environment="OLLAMA_ORIGINS=*"
[Install]
WantedBy=default.target
EOF'
我的ollama 其他服务器上配置是这样的, telnet 可以联通 其他ip 11434 但是 lobe无法访问,只能访问lobe 所在ip的11434

**Comment by arvinxx** [comment]
@miracletiger 没太看明白，能讲清楚一些吗？

**Comment by heavenwing** [comment]
我的也报错。一开始检查报错，配置了OLLAMA_ORIGINS后正常。但是聊天出错。报奇怪的 https://<my host server>/api/chat/ollama 401错误。
我是lobechat以容器的方式跑在Azure App Service里面（启用了用户验证），ollama跑到本地的localhost。
版本为：v0.148.9

**Comment by heavenwing** [comment]
刚刚升级到了：v0.149.2，其支持了浏览器请求模式后，我的问题解决了。

**Comment by zivenyang** [comment]
是ollama跨域的问题，参考https://lobehub.com/zh/docs/self-hosting/examples/ollama#%E9%9D%9E%E6%9C%AC%E5%9C%B0%E8%AE%BF%E9%97%AE-ollama 
添加
OLLAMA_HOST=0.0.0.0
OLLAMA_ORIGINS=*
然后lobechat中ollama的url改成ipv4地址即可

**Comment by liweizju** [comment]
I have exactly the same problem, did anyone solve that?
I tried the following solution, but it doesn't work. Thanks!!

I'm in macbook with M3 chip, locally delpoyed ollama with llama3.1. And LobeChat is installed in docker.

> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> It is a cross-domain problem with ollama. Please refer to https://lobehub.com/zh/docs/self-hosting/examples/ollama#%E9%9D%9E%E6%9C%AC%E5%9C%B0%E8%AE %BF%E9%97%AE-ollama Add to OLLAMA_HOST=0.0.0.0 OLLAMA_ORIGINS=* Then change the url of ollama in lobechat to the ipv4 address

**Comment by aibeishu** [comment]
更新后，出现这个问题了：{
  "error": {
    "name": "TypeError",
    "message": "fetch failed"
  },
  "provider": "ollama"
}
