### ISSUE TITLE
翻译的功能，在某些屏幕条件下，无法点击(因为没有产生滚动条)

### ISSUE THREAD

**Issue by shylock-wu** [lobehub/lobe-chat#2191]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

无法滚动的翻译列表，在浏览器窗口高度不够的情况下，无法选择最上面的一些翻译语言，因为我要选择**简体中文**，但其实选不中，因为列表没法滚动
![CleanShot 2024-04-25 at 11 48 08](https://github.com/lobehub/lobe-chat/assets/73875874/486cf7dd-7c46-43f6-a2fe-75ea3466ef04)

### 🚦 期望结果

固定一个高度，可滚动就行了

**Comment by arvinxx** [comment]
可以 我优化下

**Comment by RubuJam** [comment]
请问这个翻译功能，你是怎么调出来的？

**Comment by RubuJam** [comment]
> @RubuJam 
> 
> <img width="588" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/d1508d55-b645-4436-8b47-111d162637ff">
> 
> 

明白了，之前看错了，还以为是自动翻译的标题，是说为什么没有，谢谢你

**Comment by shylock-wu** [comment]
> 可以 我优化下

大佬什么时候优化，过去两周了，我看新发布的版本好像都没有优化这个地方
