### ISSUE TITLE
How can I find my loccal models in ollama?

### ISSUE THREAD

**Issue by tyouter** [lobehub/lobe-chat#2194]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/examples/ollama.zh-CN.mdx

### 🐛 Feedback

When I install the local lobehub successfully at Windows11, it shows this model choice page which ollama models are not my local models
![image](https://github.com/lobehub/lobe-chat/assets/8369452/8c2f9e28-0edd-4d3f-a463-a5290be298fc)
My local models are:
![image](https://github.com/lobehub/lobe-chat/assets/8369452/3ac63d41-a2a7-4516-8bda-b10ca8a22b43)

**Comment by BBM-Freehub** [comment]
> ### 📝 Reference
> https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/examples/ollama.zh-CN.mdx
> 
> ### 🐛 Feedback
> When I install the local lobehub successfully at Windows11, it shows this model choice page which ollama models are not my local models ![image](https://private-user-images.githubusercontent.com/8369452/325557402-8c2f9e28-0edd-4d3f-a463-a5290be298fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTE4MTksIm5iZiI6MTcxNDA1MTUxOSwicGF0aCI6Ii84MzY5NDUyLzMyNTU1NzQwMi04YzJmOWUyOC0wZWRkLTRkM2YtYTQ2My1hNTI5MGJlMjk4ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjVUMTMyNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGI1NGI4YjgwYzMwOGFlMTNiMGVmNDMwZGZjMTA4MjRmMWM4N2I0MTJjNDVmYjBiNTM1ZDU4YWY5OTlmNDdlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OjXWNut1LK0ZGZMHk2UzCJU3aIYe-4e-NuQ_PC7ceSk) My local models are: ![image](https://private-user-images.githubusercontent.com/8369452/325558028-3ac63d41-a2a7-4516-8bda-b10ca8a22b43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTE4MTksIm5iZiI6MTcxNDA1MTUxOSwicGF0aCI6Ii84MzY5NDUyLzMyNTU1ODAyOC0zYWM2M2Q0MS1hMmE3LTQ1MTYtOGJkYS1iMTBjYThhMjJiNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjVUMTMyNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTExMjJhNTdjZTJiMjBmNDQ5ZGNjMTYxNjVmYmQ1MTcxYTJiODlhMzg4NDI4ZGQ5NTU2YjQzMzI4NTEwYWVlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.POMAv60tCByEVCtQ59BgoX61G8vryK6KnAHg35Ppxfw)

列表中的有些是不能用的，区分大小写的地方有错误，你可以自己创建列表。
<img width="221" alt="2" src="https://github.com/lobehub/lobe-chat/assets/86555393/512f615d-8913-41fc-ba4b-9c063dfb033f">
此问题可能与[2196]基本一样。
