### ISSUE TITLE
[Bug] ollama连接报错：显示ollama并未运行

### ISSUE THREAD

**Issue by dandandujie** [lobehub/lobe-chat#2196]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

我在本地下载了ollama程序并且安装了一个模型，ollama运行后默认在本地11434端口，我的lobechat是用vercel部署的，所以直接填写localhost11431是无法连接上ollama的。所以我使用cloudflare创建了一个隧道tunnel，以此实现内网穿透效果，把localhost:11434用自定义域名访问代理。在cloudflare界面，显示的是我的隧道运行正常，我已经在浏览器访问过这个url，显示的是ollama is running，但是lobechat这边我填入https://域名/v1还是显示无法连接上ollama服务器，
Ollama service is unavailable. Please check if Ollama is running properly or if the cross-origin configuration of Ollama is set correctly.
Ollama 服务不可用。请检查 Ollama 是否正常运行，或 Ollama 的跨源配置是否设置正确。
Show Details
{
  "host": "我的域名",
  "message": "please check whether your ollama service is available or set the CORS rules",
  "provider": "ollama"
}
在聊天界面提问后也只是回复{
  "error": {
    "message": "404 page not found",
    "name": "ResponseError",
    "status_code": 404
  },
  "provider": "ollama"
}

### 🚦 Expected Behavior

使用cloudflare创建了一个隧道tunnel，以此实现内网穿透效果，把localhost:11434用自定义域名访问代理

**Comment by arvinxx** [comment]
所以直接填写localhost11431是无法连接上ollama的

不你错了，直接填是可以连的😅

**Comment by dandandujie** [comment]
> > 所以直接填写localhost11431是无法连接上ollama的
> 
> 不你错了，直接填是可以连的😅

我之前不知道为啥无法连接，刚刚尝试了一下现在可以直接用localhost连接了。但是如果我要跨域访问的话，用公网访问这个本机项目还是要用到内网穿透，所以我想问下我上面提到的内网穿透方案失败如何解决。

**Comment by dandandujie** [comment]
> > 所以直接填写localhost11431是无法连接上ollama的
> 
> 不你错了，直接填是可以连的😅

![image](https://github.com/lobehub/lobe-chat/assets/142396650/125408dd-8b75-4628-99d9-aa68c417840d)
![Uploading image.png…]()
我用域名访问和ip访问都显示ollama is running。按道理，填这个域名应该是可以连接上的

**Comment by dandandujie** [comment]
我在系统变量设置了这些，但没有效果。模型名字是我从ollama官方那里找的一个模型，原原本本的复制粘贴它的名字。我现在发现，我即使是用localhost11434，还是会报错{
  "error": {
    "message": "error code: 1003",
    "name": "ResponseError",
    "status_code": 403
  },
  "provider": "ollama"
}，必须开“客户端请求模式”才会有回复，但是回复速度非常慢；不用localhost又会出现之前的报错

**Comment by arvinxx** [comment]
> 必须开“客户端请求模式”才会有回复，但是回复速度非常慢

有回复就是能用了啊，回复慢这不是你自己电脑的问题吗

**Comment by dandandujie** [comment]
因为我一开始使用这个模型时回复是很快的，现在调整后用模型回复慢了很多，我以为是有什么新问题
