### ISSUE TITLE
[Bug] Unable to switch to openrouter model after last few commits

### ISSUE THREAD

**Issue by dillfrescott** [lobehub/lobe-chat#2203]
### 💻 Operating System

Other Linux

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

Cannot select my openrouter model. gets stuck on openai models after building last commit.

### 🚦 Expected Behavior

Id expect to be able to select my llama 70b instruct openrouter model...

### 📷 Recurrence Steps

Build from latest commit.

**Comment by dillfrescott** [comment]
I just rolled back to commit [33e2236](https://github.com/dillfrescott/lobe-chat/commit/33e22362077e77ca694e051a5bc71685c257ccc7) and it works fine again. So one of the latest commits broke the program.

**Comment by arvinxx** [comment]
@dillfrescott what's the behavior that you can't use open router? I have tried , it seems work correctly?

**Comment by dillfrescott** [comment]
The openrouter model shows up under the list, but every time I click it, it snaps back to gpt3.5. It also defaults to gpt3.5 even when I specifically have an env variable telling it to default to the openrouter model.

I rolled back a few commits and it behaved normally again, indicating something happened today that broke it.

**Comment by arvinxx** [comment]
@dillfrescott could you please show me a screenshot of your case？ I have tried but it still seems work correctly

**Comment by dillfrescott** [comment]
https://github.com/lobehub/lobe-chat/assets/56714680/3193b2e1-d41e-44fc-b1ea-a26e26437d6e

**Comment by arvinxx** [comment]
@dillfrescott have you try with https://chat-preview.lobehub.com/chat ? does it work correctly?

**Comment by dillfrescott** [comment]
It seems to

**Comment by dillfrescott** [comment]
Its still completely broken for me on my vercel. And i never modified the code at all

**Comment by arvinxx** [comment]
@dillfrescott do you try to clean your config or reset it?

**Comment by dillfrescott** [comment]
I just use the same ENV variables I've always used and vercel does a clean build each commit. So I don't think it's anything on my end. Very odd

**Comment by arvinxx** [comment]
@dillfrescott could you share your env? might be an issue with specific env

**Comment by dillfrescott** [comment]
Sure I will when I get home later!

**Comment by dillfrescott** [comment]
![Screenshot_20240426_193701](https://github.com/lobehub/lobe-chat/assets/56714680/db6d3080-542f-415e-a308-129f91259902)
![Screenshot_20240426_193729](https://github.com/lobehub/lobe-chat/assets/56714680/fc18197c-2879-4167-8655-5f0da40b0759)
![Screenshot_20240426_193759](https://github.com/lobehub/lobe-chat/assets/56714680/74bd2a38-ecf8-40a9-9db6-c6b45d404607)

**Comment by dillfrescott** [comment]
Thank you!
