### ISSUE TITLE
[Request] 增加关闭 Topic 自动重命名开关

### ISSUE THREAD

**Issue by deyinliwork** [lobehub/lobe-chat#2206]
### 🥰 需求描述

用于节省tokens，因为过长的token会使用gpt-4重命名topic，费用超级高。

![image](https://github.com/lobehub/lobe-chat/assets/156164981/cd7ac319-4a3a-4467-b790-b3f8c3acebcc)

### 🧐 解决方案

增加功能开关

**Comment by 0712wu** [comment]
原来的我费用是这么没的，看来要禁掉gpt-4-turbo-preview

**Comment by arvinxx** [comment]
在 #2683 支持自行指定话题重命名的模型，可以自行切换成一个低费率的模型
