### ISSUE TITLE
无法正常使用azure的vision模型[Bug] 

### ISSUE THREAD

**Issue by Xscut** [lobehub/lobe-chat#2207]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Edge

### 🐛 问题描述

自从可以直接在环境变量中根据azure的部署名进行配置后就无法使用azure的vision模型

### 🚦 期望结果

正常使用azure的vision模型

### 📷 复现步骤

![image](https://github.com/lobehub/lobe-chat/assets/54270525/9a779689-a675-4ecd-913f-7c86ef0d377b)
配置如图，上传图片后会报错
![image](https://github.com/lobehub/lobe-chat/assets/54270525/6e0a31ff-2b1c-495b-9c4a-02a0c42172d2)

**Comment by arvinxx** [comment]
@Xscut 感觉应该是 vision 相关的 bug，但是由于我没有 azure 账号，是否方便借我下你的 key 做下测试？

**Comment by dholakashyap** [comment]
i am too having this problem

**Comment by dholakashyap** [comment]
please fix this ASAP
