### ISSUE TITLE
[Request] 增加私有知识库功能

### ISSUE THREAD

**Issue by franklili3** [lobehub/lobe-chat#222]
### 🥰 需求描述 | Feature Description

用于企业客服，回答企业的已有问答。

### 🧐 解决方案 | Proposed Solution

可以使用langchain技术建立知识库，用户上传文档，机器人有限按照知识库回答。

**Comment by arvinxx** [comment]
私有知识库技术实现方案还在构思中。

因为现有的LobeChat是一个纯本地化的方案。因此如何存储管理私有知识库、处理向量化的流程，和本地文件的集成 这些都要通盘考虑。

**Comment by onlinedear** [comment]
太棒了，希望能够增加一个或多个文档的问答、总结，支持pdf、doc、exl等文档格式。

**Comment by sunsky89757** [comment]
+1

**Comment by QIN2DIM** [comment]
有两个比较优秀的做 LangChain Services 的项目可以借鉴，FastGPT 和 Dify。

我看 lobe-chat 集成了 langchain-ts: latest，关于知识库的增删改查都可以基于这个版本的 langchain 实现。而编排复杂 ChatFLow 也有对应的 low-code project，如 Flowise（版本相对落后）。

### Retrival = Loader+Transform+Embedding+VectorStore+Retrieve.

![图片](https://github.com/lobehub/lobe-chat/assets/62018067/1b446552-891f-4153-b316-c7d15ddfc41d)


1.**Documents loader**:  从信源获取数据，可以是结构化文档，非结构化文本或从任意产品集成来的数据接口。如常见的 CSV, PDF, Confluence。

2.**Transform**：分段与清洗，将文本 chunk 分段，对应着多个 splitter，按照不同规则分割数据集，这是通常是构建知识库的第一步。常见的有：
✓Code Test Splitter：按照语言语法进行分段
✓Recursive Character Text Splitter：换行符循环分割
✓Markdown Text Splitter：按照 Markdown 语法分段
✓Token Text Splitter：按照固定 tokens 长度切断文本

3.**Embed**：嵌入编码 Embedding，通常借助大模型对已分段的语料进行编码，被编码后数据包含了大模型对分片内容的高纬度理解信息。选择编码模型通常是构建知识库的第二步。常被用于编码的大模型有：OpenAI Embedding-2，JINA Cohere，HuggingFace 开源模型。

4.**Store**：向量数据库。被编码后的富文本信息通常以向量形式存储。而在 AI Agents 的架构中，VectorStore 是存储长期记忆的重要介质。这是构建知识库的必备步骤。对于 services 类型项目来说，向量数据库的选型并不重要，比如 FastGPT 仅通过 postgresql 插件就解决了这件事。而在 LangChain 的实现中，可以对接的向量数据库非常多，常见的有：Qdrant，Milvus，Weaviate，In-Memory Vector Store，Pinecone。

5.**Retrieve**：向量检索器。
6.**Indexing**：數據同步，避免重複寫入，避免重新編寫未更改的内容。


### PREVIEW

非常期待的 feat！！知识库是对国内大环境比较有用的研发方向。如果要做的话，可以尝试在样式中加一下类似 perplexity 的“引用和归属”功能。

![知识库问答+对话引导](https://github.com/lobehub/lobe-chat/assets/62018067/5f3438a0-b8de-443e-93a7-a0b5fd9b3b5e)

**Comment by arvinxx** [comment]
感谢建议！
这两个产品我都有研究过，不过我们可能会尝试一些新的方案。原因是这两个产品都需要用户提供一个 db 和服务端，而lobe-chat目前是一个完全本地化的产品，没有db 服务。

所以如何结合还需要做这部分功能时再评估一下产品方案。

**Comment by ddosakura** [comment]
本地化产品也可以有db

最近看到的项目 https://github.com/rubickCenter/rubick 使用了 https://github.com/pouchdb/pouchdb 作为本地数据库+webdav同步数据，感觉对知识库的存储来说是个挺好的思路

知识库需要的是向量数据库，这个可以看看 https://github.com/shravansunder/hnswlib-wasm 这类可以直接在浏览器中运行的库

其它相关资料：https://localfirstweb.dev/

**Comment by callzhang** [comment]
Any updates?

**Comment by fanyinghao** [comment]
可以尝试开放接口的方式，第三方通过插件来实现文件处理的流程。这个项目之需要在前端提供上传文件功能即可，后续交由插件处理。

**Comment by ihcbbs** [comment]
> 可以尝试开放接口的方式，第三方通过插件来实现文件处理的流程。这个项目之需要在前端提供上传文件功能即可，后续交由插件处理。

是的，我不知道这个功能为什么到现在都还不做，像moonshot，像千问，上传了它自己就会解析，可以问答了，什么向量模型，什么数据库，都是另外的事情。

**Comment by arvinxx** [comment]
> 是的，我不知道这个功能为什么到现在都还不做，像moonshot，像千问，上传了它自己就会解析，可以问答了

那要不你来 PR 个上传文件的插件？非常欢迎~


你说的这些我也知道，而且像智谱 openai 也有自己的assistant api可以传文件。但这并不是我期望的使用方案。我并不希望 LobeChat 绑定某个特定 provider ，这会导致未来扩展性存在缺陷。比较典型的就是 openai 的 assistant api一开始并不支持流式返回，这意味着如果使用他们的方案，用openai实现文件上传的会话体验就会远比普通方案差一大截。而且用文件上传的接口还和普通流式是两套，一旦这么搞维护成本就是几何倍数上增，迟早会变成💩山。

此外，这种 provider 的api 传完你就传完了，之前传的文件也没地方管理，二次复用，以及真正变成可被积累的知识库。你传给 moonshot 的文件没法直接在被千问的模型消费，用户就会非常疑惑为什么自己的文件切个 provider 就不支持了。

API 能力是能力， 但这不是简单包下就能变成足够好用的产品的。 文件上传的功能我们很快就会开始做，再耐心等待一会吧

**Comment by wdzhwsh4067** [comment]
> > 是的，我不知道这个功能为什么到现在都还不做，像moonshot，像千问，上传了它自己就会解析，可以问答了
> 
> 那要不你来 PR 个上传文件的插件？非常欢迎~
> 
> 你说的这些我也知道，而且像智谱 openai 也有自己的assistant api可以传文件。但这并不是我期望的使用方案。我并不希望 LobeChat 绑定某个特定 provider ，这会导致未来扩展性存在缺陷。比较典型的就是 openai 的 assistant api一开始并不支持流式返回，这意味着如果使用他们的方案，用openai实现文件上传的会话体验就会远比普通方案差一大截。而且用文件上传的接口还和普通流式是两套，一旦这么搞维护成本就是几何倍数上增，迟早会变成💩山。
> 
> 此外，这种 provider 的api 传完你就传完了，之前传的文件也没地方管理，二次复用，以及真正变成可被积累的知识库。你传给 moonshot 的文件没法直接在被千问的模型消费，用户就会非常疑惑为什么自己的文件切个 provider 就不支持了。
> 
> API 能力是能力， 但这不是简单包下就能变成足够好用的产品的。 文件上传的功能我们很快就会开始做，再耐心等待一会吧

支持作者！
