### ISSUE TITLE
[Bug] llama3-Insturct cant install any plugin

### ISSUE THREAD

**Issue by iChristGit** [lobehub/lobe-chat#2220]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/20077386/a67a140f-521b-4711-ae86-00242b0bb75a)

I tried using llama3-8B-Insturct and the normal llama-3-8B through ollama, I can chat, but I cannot access the plugin store..
I am very interested in all the options like websearch, but do it locally without api.

### 🚦 Expected Behavior

Maybe its expected that ollama models wont be able to use plugins.. please clarify on this

**Comment by arvinxx** [comment]
Because ollama don't support function calling by now: https://twitter.com/jmorgan/status/1784378944323567996

**Comment by iChristGit** [comment]
> Because ollama don't support function calling by now: https://twitter.com/jmorgan/status/1784378944323567996

Oh, thanks for clarifying, il wait for official implementation.
