### ISSUE TITLE
[Bug] Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by chuan1127** [lobehub/lobe-chat#2222]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

点击设置页面，偶尔会出现 Application error: a client-side exception has occurred (see the browser console for more information).再次刷新页面会正常显示

### 📷 复现步骤

点击设置页面，偶尔会出现 Application error: a client-side exception has occurred (see the browser console for more information).再次刷新页面会正常显示

**Comment by arvinxx** [comment]
需要一个复现

**Comment by RubuJam** [comment]
> 需要一个复现

使用vercel部署最新代码，即`0.150.2`，并清理vercel和浏览器cache后，点击`随便聊聊`或设置中的`默认模型`时，基本是百分百触发
这是我部署的网站：https://lobe-production.vercel.app

**Comment by arvinxx** [comment]
@RubuJam 

<img width="1421" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/15fc0bbd-0a06-4346-9443-f48611c553a6">

得看下 Console 报啥错了

**Comment by RubuJam** [comment]
> @RubuJam 
> 
> 
> 
> <img width="1421" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/15fc0bbd-0a06-4346-9443-f48611c553a6">
> 
> 
> 
> 得看下 Console 报啥错了

@arvinxx 刚刚不小心把那个部署删了，现在已经重新部署了，但有个奇特的问题，使用相同的代码和环境变量，部署了两个，但其中一个不会报错，一个会疯狂报错，我在外面，没办法直接提供console信息
会报错：lobe-production.vercel.app
不会报错：lobe-edu.vercel.app

**Comment by arvinxx** [comment]
@RubuJam 应该是 `DEFAULT_AGENT_CONFIG` 配置的识别问题：

<img width="1463" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/ef92e42a-8f4d-4a50-83eb-971743f5218d">

plugins 应该是个数组的，被识别成了字符串。导致出问题。

**Comment by RubuJam** [comment]
> @RubuJam 应该是 `DEFAULT_AGENT_CONFIG` 配置的识别问题：
> 
> 
> 
> <img width="1463" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/ef92e42a-8f4d-4a50-83eb-971743f5218d">
> 
> 
> 
> plugins 应该是个数组的，被识别成了字符串。导致出问题，你要检查下环境变量是否配置有问题。

那有可能是我的写法问题，原本是`plugins=lobe-image-designer;enableAutoCreateTopic=true;model=gemini-pro;provider=google`
我把它改成了，目前正在部署
`enableAutoCreateTopic=true;model=gemini-pro;provider=google;plugins=lobe-image-designer`

**Comment by arvinxx** [comment]
@RubuJam 试了下的确本地能复现 `enableAutoCreateTopic=true;model=gemini-pro;provider=google;plugins=lobe-image-designer` 这个的报错，看来是针对插件字段的解析逻辑有缺陷，我修一下吧

**Comment by RubuJam** [comment]
> enableAutoCreateTopic=true;model=gemini-pro;provider=google;plugins=lobe-image-designer

`enableAutoCreateTopic=true;model=gemini-pro;provider=google;plugins=lobe-image-designer`这个也会报错吗，我的vercel部署一直在排队，还没不清楚情况

**Comment by arvinxx** [comment]
@RubuJam 目前看是的，原因是之前解析时，当只存在一个 plugin 时，会解析成字符串而不是数组。我在 #2239 修复了
