### ISSUE TITLE
[Bug]  网站启用https，无法设置访问 ollama

### ISSUE THREAD

**Issue by icanfly777** [lobehub/lobe-chat#2229]
### 💻 Operating System

Ubuntu

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

如果以 https的方式访问 ，那么 ollama 就不能正常设置 ，以http的形式访问测试可以通过 ，请能尽快修复，非常感谢！

<img width="1369" alt="Snipaste_2024-04-27_02-30-08" src="https://github.com/lobehub/lobe-chat/assets/13691055/2c66e2d8-1613-465c-954c-2bf9ac8bfa92">

**Comment by arvinxx** [comment]
你用127.0.0.1:11434 这种连接就好了。本身https的网站请求http是不被浏览器允许的

**Comment by icanfly777** [comment]
> 你用127.0.0.1:11434 这种连接就好了。本身https的网站请求http是不被浏览器允许的

明白了，非常感谢
