### ISSUE TITLE
[Request] 希望支持更多的第三方的代理

### ISSUE THREAD

**Issue by onlinedear** [lobehub/lobe-chat#223]
### 🥰 需求描述 | Feature Description

目前只有对Azure的OpenAI接口做了支持，但国内很多小伙伴无法使用外币信用卡支付。

### 🧐 解决方案 | Proposed Solution

希望能使用到api2d.com这样的第三方代理平台。

**Comment by arvinxx** [comment]
已经支持的。自定义配置代理地址即可

**Comment by arvinxx** [comment]
后面我们补一下这部分的文档

**Comment by onlinedear** [comment]
没找到配置的说明文档

**Comment by 52eraja** [comment]
支持oneapi么？

**Comment by s544838371** [comment]
> 没找到配置的说明文档

环境变量里加OPENAI_PROXY_URL

**Comment by s544838371** [comment]
> 支持oneapi么？

https://github.com/lobehub/lobe-chat/issues/263

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/discussions/735
