### ISSUE TITLE
设置环境变量后，依然弹出需要设置OpenAI API Key

### ISSUE THREAD

**Issue by RubuJam** [lobehub/lobe-chat#2230]
### 💻 系统环境

iOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

我的环境变量设置如下
`DEFAULT_AGENT_CONFIG`= `plugins=search-engine,lobe-image-designer;enableAutoCreateTopic=true;model=gemini-pro;provider=google;`
`OPENAI_MODEL_LIST`= `-all`
部署后，虽在设置中显示正确，但首次使用需要自行设置模型，不然会一直弹出如下内容，且此时token统计也没工作，需要点击任意一个模型才会启用，似乎`provider`没能正确处理
![IMG_5435](https://github.com/lobehub/lobe-chat/assets/36145660/86579973-13eb-4416-9545-030224aa8259)

### 🚦 期望结果

直接调用对应模型（此问题似乎在这几个版本中出现）

**Comment by arvinxx** [comment]
你试过浏览器的无痕模式也是这样吗？

**Comment by RubuJam** [comment]
> 你试过浏览器的无痕模式也是这样吗？

对，而且我定位到0.149.5版本起，开始出现此问题，高度怀疑是0.149.5的某些变动，导致出现该问题

**Comment by arvinxx** [comment]
结合这两个因素来看，应该是bug，有另外一个用户也遇到了类似的问题， https://github.com/lobehub/lobe-chat/issues/2203

我等下看下修一下

**Comment by RubuJam** [comment]
> 结合这两个因素来看，应该是bug，有另外一个用户也遇到了类似的问题， https://github.com/lobehub/lobe-chat/issues/2203
> 
> 
> 
> 我等下看下修一下

我这两天有点其它事情，只能麻烦你了

**Comment by Firetheft** [comment]
问题依然存在
