### ISSUE TITLE
[Bug] 部署报错

### ISSUE THREAD

**Issue by zsychn** [lobehub/lobe-chat#2232]
### 💻 Operating System

macOS

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

部署报错 
#15 190.3 ./src/hooks/useOAuthSession.ts:1:22

#15 190.3 Type error: Cannot find module '@auth/core/types' or its corresponding type declarations.

#15 190.3 

#15 190.3 > 1 | import { User } from '@auth/core/types';

#15 190.3     |                      ^

#15 190.3   2 | import { SessionContextValue, useSession } from 'next-auth/react';

#15 190.3   3 | import { useMemo } from 'react';

#15 190.3   4 |

#15 190.7  ELIFECYCLE  Command failed with exit code 1.

#15 ERROR: process "/bin/sh -c pnpm run build:docker # run build standalone for docker version" did not complete successfully: exit code: 1

------

 > [builder 6/6] RUN pnpm run build:docker # run build standalone for docker version:

190.2 

190.3 ./src/hooks/useOAuthSession.ts:1:22

190.3 Type error: Cannot find module '@auth/core/types' or its corresponding type declarations.

190.3 

190.3 > 1 | import { User } from '@auth/core/types';

190.3     |                      ^

190.3   2 | import { SessionContextValue, useSession } from 'next-auth/react';

190.3   3 | import { useMemo } from 'react';

190.3   4 |

190.7  ELIFECYCLE  Command failed with exit code 1.

------

Dockerfile:103

--------------------

 101 |     

 102 |     COPY . .

 103 | >>> RUN pnpm run build:docker # run build standalone for docker version

 104 |     

 105 |     ## Production image, copy all the files and run next

--------------------

error: failed to solve: process "/bin/sh -c pnpm run build:docker # run build standalone for docker version" did not complete successfully: exit code: 1

Failed to build with zeaburpack: run buildctl build: exit status 1

**Comment by arvinxx** [comment]
哪个版本

**Comment by zsychn** [comment]
> 哪个版本

Revert "🐛 fix: fix display error when using DEFAULT_AGENT_CONFIG env" This reverts commit e46215c17a8761d27c1194416a4c476b9e13d2bd.

和 

📝 docs(bot): Auto sync agents & plugin to readme
都部署失败

**Comment by arvinxx** [comment]
我本地试了下似乎没问题，如何复现？

**Comment by zsychn** [comment]
> 我本地试了下似乎没问题，如何复现？

![image](https://github.com/lobehub/lobe-chat/assets/23525693/c0a221af-c80c-4bd1-b28b-3f9253b346f5)
似乎从某个版本齁，一直都是这个什么import { User } from '@auth/core/types'; 出错

**Comment by zsychn** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/23525693/d5d8272a-0ed9-465b-8406-e0750dcc161d)
这是最后一个成功的版本
