### ISSUE TITLE
[Request] 支持DeepInfra

### ISSUE THREAD

**Issue by saccohuo** [lobehub/lobe-chat#2234]
### 🥰 需求描述

https://deepinfra.com/

DeepInfra的llama3 70b价格很有竞争力。

![image](https://github.com/lobehub/lobe-chat/assets/13887263/cf3cd3b2-2b8d-48d1-9230-b8b3bf1209b4)

### 🧐 解决方案

支持DeepInfra

**Comment by arvinxx** [comment]
相似问题： #2242 ，请前往 https://github.com/lobehub/lobe-chat/discussions/1284 提需求
