### ISSUE TITLE
[Request] 多LLM同时发送请求，类似ChatHub

### ISSUE THREAD

**Issue by saccohuo** [lobehub/lobe-chat#2235]
### 🥰 需求描述

![image](https://github.com/lobehub/lobe-chat/assets/13887263/8bd0399c-8aaa-471f-a284-d5fe15caf9ef)

### 🧐 解决方案

多LLM同时发送请求，类似ChatHub

**Comment by arvinxx** [comment]
后续有计划做

**Comment by arvinxx** [comment]
重复 https://github.com/lobehub/lobe-chat/issues/3122
