### ISSUE TITLE
更新镜像之后，助手下面的模型名称不会自动隐藏了[Bug] 

### ISSUE THREAD

**Issue by coulsontl** [lobehub/lobe-chat#2237]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

之前如果随便聊聊使用的模型和助手的模型是一样的，在助手下面就不会展示展示模型名称了，比较简洁清爽，现在不管咋样永远会展示那个模型名称，导致左边会话栏一排相同的模型名称，显得乱糟糟的而且让左边能显示的会话变少（会话的高度增加了）。
<img width="776" alt="image" src="https://github.com/lobehub/lobe-chat/assets/149155411/43d2e1fd-5df7-4325-887d-1003b057ad2e">

**Comment by arvinxx** [comment]
emm... 众口难调啊， 我先改回来，后面做成配置吧

**Comment by coulsontl** [comment]
@arvinxx 佬，改完还是有bug，会话只有选第一个GPT-3.5才会隐藏，但是我随便聊聊选的是GPT-4 turbo preview
<img width="784" alt="image" src="https://github.com/lobehub/lobe-chat/assets/149155411/591d85ec-289b-4600-b406-2d7f103a4587">

<img width="712" alt="image" src="https://github.com/lobehub/lobe-chat/assets/149155411/03c795ef-1a4e-49d4-b123-62205858a344">
