### ISSUE TITLE
[Request] Embed Lobechat as a customer support chatbot in the website

### ISSUE THREAD

**Issue by manhdg98** [lobehub/lobe-chat#224]
### 🥰 需求描述 | Feature Description

Embed Lobechat as a customer support chatbot in the website,
I need to embed it as a chat feature for our website
Example: 
![image](https://github.com/lobehub/lobe-chat/assets/49272142/0fee7cd5-ed6a-47a3-998c-7471022d5584)

### 🧐 解决方案 | Proposed Solution

N/A

### 📝 补充信息 | Additional Information

N/A

**Comment by arvinxx** [comment]
We are consider about it , please stay tuning~

**Comment by manhdg98** [comment]
Thanks for contributing

**Comment by manhdg98** [comment]
> We are considering about it , please stay tuning~

Hey @arvinxx Is this feature implemented yet?

**Comment by xihajun** [comment]
+1

**Comment by xihajun** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/25631641/a2a64951-50b5-4312-b386-3779f917c3ca)

**Comment by arvinxx** [comment]
I think as LobeChat's evolution, it's not suitable to embed it into other website. So I decide to close it.

**Comment by xihajun** [comment]
> I think as LobeChat's evolution, it's not suitable to embed it into other website. So I decide to close it.

Agree, it is a bit slow, do you think it is possible for someone based on lobechat to write a lighter version of it?

**Comment by arvinxx** [comment]
@xihajun Maybe you need Next Chat? https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web
