### ISSUE TITLE
[Bug] 部署在局域网上的服务无法被访问到

### ISSUE THREAD

**Issue by AppleRiven** [lobehub/lobe-chat#2243]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

我在本地和局域网内的服务器上部署了相同的服务，本地可以通过localhost:local_port正常访问，但是无法在本地通过remoteIP:remotePort访问服务器上的服务，已经在NextChat上试过可行。

**Comment by arvinxx** [comment]
没懂，你部署了啥？和 LobeChat 有啥关系

**Comment by progmboy** [comment]
局域网本地nas docker运行lobechat 且开启了https, 然后访问非https的ollama检测失败 .
![image](https://github.com/lobehub/lobe-chat/assets/9927043/bbf9f61d-8ae1-4c11-8fe2-2a3ee126923b)

另外关闭“使用客户端请求模式”，虽然测试失败，但是是可以正常使用的。

**Comment by arvinxx** [comment]
> 另外关闭“使用客户端请求模式”，虽然检测失败，但是是可以正常使用的。

那应该是检测这块的逻辑问题，我们后续优化下
