### ISSUE TITLE
[Request] Google Gemini Safety Settings

### ISSUE THREAD

**Issue by Rubecks** [lobehub/lobe-chat#2245]
### 🥰 Feature Description

The Google Gemini API has options to adjust four different safety settings, with four levels each.
https://ai.google.dev/gemini-api/docs/safety-settings

### 🧐 Proposed Solution

Would it be possible to implement four more sliders for these safety settings in the model settings UI?

**Comment by arvinxx** [comment]
What's the purpose of this?

**Comment by svnkxmza** [comment]
@arvinxx 
I have met some people with the same problem and have this case to refer to! : https://github.com/microsoft/autogen/pull/2410

**Comment by svnkxmza** [comment]
I have met some people with the same problem and have this case to refer to! #github.com/microsoft/autogen/pull/2410
