### ISSUE TITLE
[Request] 支持多个 oneapi 同时存在

### ISSUE THREAD

**Issue by sxjeru** [lobehub/lobe-chat#2253]
### 🥰 需求描述

已知存在兼容 OpenAI API 的 [oneapi](https://github.com/songquanpeng/one-api)，希望能实现多 oneapi 共存。

为了避免与 OpenAI 产生不必要的混淆，另可单独出一个 oneapi 区域。

每个 API 均能单独设置 Key、接口地址、模型。
若存在模型重复，可以考虑简单报错，或者负载均衡。

### 🧐 解决方案

见上。

**Comment by sxjeru** [comment]
相关 #1985

**Comment by arvinxx** [comment]
在 https://github.com/lobehub/lobe-chat/discussions/2040 中支持

**Comment by ckt1031** [comment]
我覺得大可不必, 你自己部署一個OneAPI中繼所有OneAPI/OpenAI API就行了

**Comment by sxjeru** [comment]
> 我覺得大可不必, 你自己部署一個OneAPI中繼所有OneAPI/OpenAI API就行了

感谢提供另外的解决方案，各有优缺点可言。

**Comment by arvinxx** [comment]
@ckt1031 不考虑 oneapi，仅考虑提供允许添加自定义的 OpenAI 兼容 API 对于很多场景来说会有比较好的灵活度。例如某些小的Provider 只要兼容 openai 的接口规范，用户就可以将这个 provider 添加到自己的配置中
