### ISSUE TITLE
[Bug] 设置页面会重复嵌套显示

### ISSUE THREAD

**Issue by athlan20** [lobehub/lobe-chat#2270]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

目前版本是LobeChat v0.145.13，不知道是之前哪次更新版本后，点设置进去会嵌套显示，如下图
![image](https://github.com/lobehub/lobe-chat/assets/2987056/59ca2fc1-18c5-4142-a81a-40afe6b97cf4)

### 🚦 期望结果

不嵌套显示设置

**Comment by arvinxx** [comment]
最新版我看是正常的

**Comment by athlan20** [comment]
好的，应该是我自动部署在某个版本卡住了，我重新更新下
