### ISSUE TITLE
部署在docker中时，本地用户无法实现同步、调用Gemini等功能

### ISSUE THREAD

**Issue by Daisy-DGY** [lobehub/lobe-chat#2274]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

服务器系统：Ubuntu；本地用户系统：Windows
问题：当lobe部署在Vercel中时，本地用户可以在设置中填写key来访问Gemini模型，修改同步频道等；但是，当lobe部署在服务器的docker中作为服务时，本地用户无法通过修改key访问Gemini，其他模型暂未尝试；并且，数据同步选项也一直是无法开启的状态。

### 🚦 期望结果

能否让docker中部署的lobe像Vercel一样服务不同用户

### 📝 补充信息

![image](https://github.com/lobehub/lobe-chat/assets/166905969/d8c72406-f76e-4335-abbc-8617e12f392f)
![image](https://github.com/lobehub/lobe-chat/assets/166905969/890e83e8-1c5e-4abe-bfa2-34a6b4a6c741)

**Comment by arvinxx** [comment]
gemini 的问题是你的docker 网络问题，需要你自行解决。 同步的问题详见：https://github.com/lobehub/lobe-chat/discussions/2276
