### ISSUE TITLE
[Bug] 移动端“添加助手并会话”跳转问题

### ISSUE THREAD

**Issue by ozshen** [lobehub/lobe-chat#2277]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

最新调整session逻辑的版本，移动端点击“添加助手并会话”，没有正确跳转到选定的助手会话界面。

### 📷 复现步骤

移动端进入助手市场，选择任意一个gpts，点击“添加助手并会话”

session值是新的，但是停留在空白的自定义助手界面
![image](https://github.com/lobehub/lobe-chat/assets/14324029/f3844b5a-6b65-4390-9c80-def9ca177158)
![image](https://github.com/lobehub/lobe-chat/assets/14324029/0a6d9ec7-f681-4db4-815d-f75929c5a1e5)

此时浏览器链接，复制到新的浏览器tab访问也是显示不正确的，没有正确的关联到新的助手会话。
https://chat-preview.lobehub.com/chat/mobile?session=c4ca0a68-dcb1-4210-9161-edaec5ff9d89

**Comment by arvinxx** [comment]
应该是个bug，我修下
