### ISSUE TITLE
[Bug]0.150.10 bun i打包时出错

### ISSUE THREAD

**Issue by chaoskwok** [lobehub/lobe-chat#2279]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Official Preview

### 🌐 浏览器

Edge

### 🐛 问题描述

bun i的时候，提示如下：

gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@21.6.0 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/home/chaos/web/lobe-chat-0.150.10/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/home/chaos/web/lobe-chat-0.150.10/node_modules/tree-sitter-json/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/chaos/web/lobe-chat-0.150.10/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/chaos/snap/bun-js/26/.cache/node-gyp/21.6.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/chaos/snap/bun-js/26/.cache/node-gyp/21.6.0',
gyp info spawn args '-Dnode_gyp_dir=/home/chaos/web/lobe-chat-0.150.10/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/chaos/snap/bun-js/26/.cache/node-gyp/21.6.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/home/chaos/web/lobe-chat-0.150.10/node_modules/tree-sitter-json',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: name 'llvm_version' is not defined while evaluating condition 'llvm_version=="0.0"' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at <anonymous> (/home/chaos/web/lobe-chat-0.150.10/node_modules/node-gyp/lib/configure.js:183:29)
gyp ERR! stack at emit (node:events:161:48)
gyp ERR! stack at #handleOnExit (node:child_process:583:16)
gyp ERR! stack at processTicksAndRejections (:12:39)
gyp ERR! System Linux 5.15.0-105-generic
gyp ERR! command "/snap/bun-js/26/_bun/bin/bun" "/home/chaos/web/lobe-chat-0.150.10/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/chaos/web/lobe-chat-0.150.10/node_modules/tree-sitter-json
gyp ERR! node -v v21.6.0
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok

**Comment by arvinxx** [comment]
如果你是本地打包的话，换成 pnpm 试试
