### ISSUE TITLE
[Request] 建议欢迎页可以让用户设置是否启用；并可以隐藏左下角提示升级的红点

### ISSUE THREAD

**Issue by coulsontl** [lobehub/lobe-chat#2281]
### 🥰 需求描述

如题，现在欢迎页无法关闭，应该只展示一次吧。现在更新的频次还是比较高的，左下角设置按钮上经常弹出那个提示的红点，对于强迫症患者不太友好，希望可以设置不提示升级

### 🧐 解决方案

欢迎页只展示一次，用户可以设置不提示升级

**Comment by arvinxx** [comment]
@coulsontl 为啥你觉得应该只展示一次？

**Comment by coulsontl** [comment]
> @coulsontl 为啥你觉得应该只展示一次？

常用的IDE，比如VSCode, IntelliJ 都是在第一次安装的时候弹welcome，左下角可以勾选取消welcome
<img width="770" alt="image" src="https://github.com/lobehub/lobe-chat/assets/149155411/732809e1-a81c-49b8-9cfd-fb824385f738">

**Comment by arvinxx** [comment]
> 当我习惯了使用LobeChat之后，其实欢迎页里的哪些东西可能一年都不会使用一次；新手可能需要，老用户是不需要的放在那是一种干扰

助手推荐对你来说都不需要么？以及或者如果我们常问问题后续会推荐你比较感兴趣的问题的话？

**Comment by arvinxx** [comment]
了解了，我们会加一下是否显示隐藏 welcome 的配置。

至于你说的小红点的问题，目前我们已经有了 Feature Flag 的能力，可以通过环境变量的方式来开启或者隐藏某些功能。只是目前还没有小红点的配置，我们有计划添加。或者有兴趣的话也欢迎 PR。

Refs: https://github.com/lobehub/lobe-chat/discussions

**Comment by yincangshiwei** [comment]
别啊，推荐助手挺不错的。

**Comment by coulsontl** [comment]
> 了解了，我们会加一下是否显示隐藏 welcome 的配置。
> 
> 至于你说的小红点的问题，目前我们已经有了 Feature Flag 的能力，可以通过环境变量的方式来开启或者隐藏某些功能。只是目前还没有小红点的配置，我们有计划添加。或者有兴趣的话也欢迎 PR。
> 
> Refs: #1894

大佬说了，会做成配置，喜欢自己配置打开就可以了

**Comment by coulsontl** [comment]
> 别啊，推荐助手挺不错的。

大佬说了，会做成配置，喜欢自己配置打开就可以了

**Comment by xiaohuakang** [comment]
确实繁琐了，还是一开始的简洁比较适合当作日常使用工具，增加个开关比较合理

**Comment by xiaohuakang** [comment]
确实繁琐了，还是一开始的简洁比较适合当作日常使用工具，增加个开关比较合理
