### ISSUE TITLE
希望`enableAutoCreateTopic`调用其他模型

### ISSUE THREAD

**Issue by RubuJam** [lobehub/lobe-chat#2282]
### 🥰 需求描述

目前自动编写标题还是依赖于OpenAi，希望能引入其他模型辅助编写

### 🧐 解决方案

希望设置环境变量`enableAutoCreateTopic`时，可以指定某个厂商提供的模型，或者直接调用对话中的模型，但由于可能在过程中切换模型，后者实现更为麻烦

**Comment by arvinxx** [comment]
目前有个 PR 在做类似的事情：https://github.com/lobehub/lobe-chat/pull/1902 ，后面可以做成配置项，比如 固定模型/ 使用当前模型 / 禁用
