### ISSUE TITLE
[Request] 

### ISSUE THREAD

**Issue by skribascode** [lobehub/lobe-chat#2283]
### 🥰 Feature Description

Remove requirement of OpenAI KEY

### 🧐 Proposed Solution

If user don't use OpenAI, why required the openAI key for use all others model

**Comment by skribascode** [comment]
The context, i want use lobe less openAI, for just use mistral or others, but not openAI and is required ;-)

**Comment by arvinxx** [comment]
It seems not a platform we know. Maybe you need to contact them
