### ISSUE TITLE
[Bug] [Tablet] [Chrome] There are gaps at the bottom of the page

### ISSUE THREAD

**Issue by BaituLime** [lobehub/lobe-chat#2288]
### 💻 Operating System

Android

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

Samsung S9 Ultra

https://github.com/lobehub/lobe-chat/assets/50917215/ebecf19c-89f1-4422-bc5d-469d3f7ed874

**Comment by arvinxx** [comment]
Do it occur with largest version？
