### ISSUE TITLE
Docker 部署的lobe-hcat，接入auth0认证，环境变量都ok，但点击Sign on with Auth0后报500 Internal Server Error [Bug] 

### ISSUE THREAD

**Issue by Jerryye17** [lobehub/lobe-chat#2292]
### 💻 Operating System

Other Linux

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

0.151.1最新版本Lobe-Chat，接入Auth0，配置完全按照官方的操作：https://lobehub.com/zh/docs/self-hosting/advanced/sso-providers/auth0，同时也配置了NEXTAUTH_URL=https://自己的域名/api/auth，但点击Sign on with Auth0后报500 Internal Server Error

Request URL:          https://xxx.com/api/auth/signin/auth0
Request Method:   POST
Status Code:          500 Internal Server Error
Remote Address:   127.0.0.1:7890
Referrer Policy:       strict-origin-when-cross-origin

**Comment by Jerryye17** [comment]
我的部署方式：
docker run -d -p 3210:3210 \
    -e OPENAI_API_KEY=sk-Q8eIJ7bxxxxxxxxxxxxxxxxxxxxxPj5NNR5RPyv \
    -e OPENAI_PROXY_URL=http://x.x.x.x:9000/v1 \
    -e OLLAMA_PROXY_URL=http://10.160.139.44:11434 \
    -e ENABLE_OAUTH_SSO=1 \
    -e NEXTAUTH_SECRET=zwck+67A0J7/Ro/cC79sdfsdfsdggsgMEnFw3wM8uA= \
    -e SSO_PROVIDERS=auth0 \
    -e AUTH0_CLIENT_ID=od39McW88udsdfsfsdfgW55G49GgoA2 \
    -e AUTH0_CLIENT_SECRET=Xjq7GfwSWkXisdfsdfsdfsdfsdf2XzybyvUGZeOMWfOf5oubEOkVy0e \
    -e AUTH0_ISSUER=dev-xgqsdfsfsdfqu54f3.us.auth0.com \
    -e ACCESS_CODE=123456ABCDEF \
    -e NEXTAUTH_URL=https://自己的域名/api/auth \
    --name lobe-chat lobehub/lobe-chat

**Comment by arvinxx** [comment]
@cy948 又得你来帮忙看看了~

**Comment by cy948** [comment]
AUTH0_ISSUER 前面添加  `https://` 再试试

**Comment by Jerryye17** [comment]
感谢，确实在AUTH0_ISSUER 前面添加 https:// 就解决问题了

**Comment by Jerryye17** [comment]
部署参数需要在auth0的domian前加https
-e AUTH0_ISSUER=https://dev-xxxxx.auth0.com

**Comment by gemnioo** [comment]
> AUTH0_ISSUER 前面添加 `https://` 再试试

Hi @cy948  could you pls help check why this 500 Internal Server Error ? 

PS  followed Docker deploy tutorial with 'Microsoft Entra ID' + 'Cloudflare R2'+'tailscale funnel'

lobe-chat.env
```
root@japan:~# cat lobe-chat.env
APP_URL=https://tailscale funnel link
DATABASE_URL=postgres://postgres:password@pgvector:5432/postgres
KEY_VAULTS_SECRET='openssl rand -base64 32'
NEXT_AUTH_SECRET='openssl rand -base64 32'
NEXT_AUTH_SSO_PROVIDERS=microsoft-entra-id
AUTH_MICROSOFT_ENTRA_ID_ID=
AUTH_MICROSOFT_ENTRA_ID_SECRET=
AUTH_MICROSOFT_ENTRA_ID_TENANT_ID=
NEXTAUTH_URL=https://tailscale funnel link/api/auth/callback/microsoft-entra-id
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_BUCKET=lobechat
S3_ENDPOINT=https://numbers.r2.cloudflarestorage.com
OPENAI_API_KEY=sk-
OPENAI_PROXY_URL=https://api.openai.com/v1
ACCESS_CODE=password
```

the  only difference was not set the "# 用于外网访问 S3 的公共域名，需配置 CORS
S3_PUBLIC_DOMAIN=https://s3-for-lobechat.your-domain.com " as "S3_ENDPOINT=" have 

```
root@japan:~# docker logs -f lobe-chat-database
🌐 DNS Server: [ '127.0.0.11' ]
-------------------------------------
[Database] Start to migration...
✅ database migration pass.
-------------------------------------
  ▲ Next.js 14.2.8
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210

 ✓ Starting...
 ✓ Ready in 162ms
 ```

**Comment by gemnioo** [comment]
Update fixed. by adding "R2.dev subdomain" aka "Public R2.dev Bucket URL" in Cloudflare R2 Bucket Setting page.

added to  lobe-chat.env  "S3_PUBLIC_DOMAIN=https:/{string-numbers}.r2.dev
