### ISSUE TITLE
[Bug] Bottom of README

### ISSUE THREAD

**Issue by KPCOFGS** [lobehub/lobe-chat#2293]
### 💻 Operating System

Ubuntu

### 📦 Environment

Official Preview

### 🌐 Browser

Other

### 🐛 Bug Description

At the bottom of the README file, there is `Copyright © 2023` I believe it should be 2024

### 🚦 Expected Behavior

N/A

### 📷 Recurrence Steps

N/A

**Comment by arvinxx** [comment]
@KPCOFGS How about update it 😋? PR welcome~

**Comment by KPCOFGS** [comment]
PR #2298
