### ISSUE TITLE
[Bug]自定义模型会和现存模型自动关联 

### ISSUE THREAD

**Issue by crybest** [lobehub/lobe-chat#2294]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/102134756/01461eda-954d-4da7-b792-0ec6a0e84abc)
如图suos所示，自定义了一个claude-3-opus，其实和claude-3-opus-20240229 关联起来了，改其中一个，会自动更改另外一个

**Comment by sxjeru** [comment]
并非更复杂的问题，而是模型设置页的表单初始值没有更新，导致你看上去在改另一个模型，实际在改这一个。
