### ISSUE TITLE
[Bug] 设置页面 参数未正确加载

### ISSUE THREAD

**Issue by MartialBE** [lobehub/lobe-chat#230]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

在系统设置或者会话设置中的 聊天设置 模型设置，当你设置好参数后，再次重新进来还是默认参数，没有加载用户设置的参数。
（只是页面没有加载用户参数，聊天时还是生效了）

### 🚦 期望结果 | Expected Behavior

正确加载用户参数

### 📷 复现步骤 | Recurrence Steps

去系统设置 或者会话设置。修改 聊天设置或者模型设置后，退出设置页面，再次重新进去。

**Comment by arvinxx** [comment]
收到，应该是组件加载的 bug 近期修一下
