### ISSUE TITLE
[Bug] 語音合成服務選項無法儲存

### ISSUE THREAD

**Issue by bentwnghk** [lobehub/lobe-chat#2300]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

語音合成服務有三個選項：OpenAI, Edge Speech, Microsoft Speech，默認為OpenAI。嘗試切換到Edge Speech失敗，系統無法儲存用戶選項，會自動切回到OpenAI。

### 🚦 Expected Behavior

切換到Edge Speech或Microsoft Speech後，儲存用戶選項。

### 📷 Recurrence Steps

1. 設定
2. 默認助手
3. 語音合成服務: 選擇 Edge Speech
4. 關於
5. 語音合成服務: 系統自動切回到 OpenAI

**Comment by arvinxx** [comment]
默认助手的设置有个bug ，详见 https://github.com/lobehub/lobe-chat/issues/2241
