### ISSUE TITLE
[Bug] Fatal Application Error when asking question to ai

### ISSUE THREAD

**Issue by dillfrescott** [lobehub/lobe-chat#2302]
### 💻 Operating System

Other Linux

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

I asked `how would i use ack and sed to replace all occurrences of https://consumet-jade.vercel.app with https://consumet-beta.vercel.app` and it throws an application error every time when generating the response.

![Screenshot_20240429_205812](https://github.com/lobehub/lobe-chat/assets/56714680/c19525cf-fafe-4658-ab35-38d8645a43ea)

### 🚦 Expected Behavior

Not an error

### 📷 Recurrence Steps

1. Ask it: `how would i use ack and sed to replace all occurrences of https://consumet-jade.vercel.app with https://consumet-beta.vercel.app`

2. See error.

### 📝 Additional Information

n/a

**Comment by dillfrescott** [comment]
When I refresh the page, the response has successfully completed though.

**Comment by arvinxx** [comment]
What's your version and do you set any env？

**Comment by dillfrescott** [comment]
newest commit and: https://github.com/lobehub/lobe-chat/issues/2203#issuecomment-2080236476

**Comment by arvinxx** [comment]
@dillfrescott It's really strange. could you dm me in discord and share your website? I need to check it for you.

**Comment by dillfrescott** [comment]
its `chat.dill.moe`

**Comment by dillfrescott** [comment]
Funny enough, that exact question still causes a crash lol
![Screenshot_20240509_225235](https://github.com/lobehub/lobe-chat/assets/56714680/415a631a-3959-496b-8c61-db08317284a4)

**Comment by arvinxx** [comment]
@dillfrescott I think it's solved by now?
