### ISSUE TITLE
[Bug] 弹窗每次都弹，不能永久关掉

### ISSUE THREAD

**Issue by crybest** [lobehub/lobe-chat#2309]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/102134756/ae79f5b3-06d5-45d8-bb04-a201e240f1c3)
这个每次刷新都出来呢

**Comment by arvinxx** [comment]
点一下应该就消失了呀？

**Comment by crybest** [comment]
点拒绝，刷新又出来

**Comment by arvinxx** [comment]
@crybest 如果是这样的话可能是个bug，我检查下
