### ISSUE TITLE
[Request] Ollama Functions 的计划

### ISSUE THREAD

**Issue by gavinliu** [lobehub/lobe-chat#2311]
### 🥰 需求描述

目前只支持了 OpenAI 的 Function Calling，期望本地模型能够支持 Function Calling

### 🧐 解决方案

https://js.langchain.com/docs/integrations/chat/ollama_functions

是否可以用 Langchain 中的 Ollama Functions 完成功能开发？

**Comment by arvinxx** [comment]
没有计划，我们不准备用 LangChain。计划等 Ollama 自行实行Function后我们再接入

**Comment by hl1221hl** [comment]
ollama 已经支持 function calling 了

**Comment by arvinxx** [comment]
@hl1221hl 有文档吗

**Comment by gavinliu** [comment]
https://ollama.com/blog/tool-support 这里

@arvinxx

**Comment by gavinliu** [comment]
有计划不？

魔搭社区也有个 Ollama + Qwen2 的 Function calling 的文章，https://mp.weixin.qq.com/s/d82jUnXldJw_UPVPngZjDQ

**Comment by arvinxx** [comment]
@BrandonStudio 没有吧，当时 anothropic 就支持了流式 tools 的。  

非 stream 模式转成 stream 模式不复杂的，但主要的问题是必须要先在流式模式下存在对应的返回数据结构才能将非流式转成流式。 Groq 做了这一层转换，是因为 groq 的api 对应了 openai 的结构，所以将groq 的非流式tools 转成openai 的流式tools 就好了。

而ollama这边不能这么做。原因是 Ollama 本身的返回的流式数据结构是和 openai 不一致的。目前 ollama 只有文本的流式返回结构，没有定义 tools 的。这就导致如果现在要将ollama非流式的tools转成流式，就要我自定义一个 ollama 的 tools 的流式结构，而这个结构大概率和官方的流式 tools 是对不上，那就又有迁移成本。
