### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zzf8264** [lobehub/lobe-chat#2316]
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Safari

### 🐛 问题描述

使用safari 去连通性检查 发现 一只不通 抓包之后发现 请求头有问题 并且 也有警告
url：http://localhost:11434/api/tags
Accept: application/json
Content-Type: application/json
Origin: http://localhost:8080
Referer: http://localhost:8080/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: ollama-js/0.5.0 (macintel Browser/Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15;)
报错是：Failed to load resource: FetchEvent.respondWith received an error: no-response: no-response :: [{"url":"http://localhost:11434/api/tags"}]

然后我换了edge 浏览器 再操作就正常 没得报错 我看了 edge浏览器的请求头是正常的 也测试连通性检查没问题，发现就是safari浏览器 访问有问题

**Comment by arvinxx** [comment]
能不能写规范点？再这样以后不规范的问题我都直接关掉了

**Comment by arvinxx** [comment]
应该是 Ollama 检测问题， Safari 不支持 https 访问 http ，换个浏览器就好
