### ISSUE TITLE
[Request] 

### ISSUE THREAD

**Issue by Upcreat** [lobehub/lobe-chat#2317]
### 🥰 需求描述

您好，能否在页面中增加其他视觉的大模型例如InternVL。有些可以提供统一的Openai的接口，但是在设置完成Llm的api以后，不能选择输入图片。
![image](https://github.com/lobehub/lobe-chat/assets/83943594/04752733-6664-4ff9-a15a-54773f9118db)

### 🧐 解决方案

希望可以在“语言模型”设置Openapi处（或其他位置）增加一个可选选项：是视觉模型还是纯文本模型。

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/pull/1916 已经支持了的
