### ISSUE TITLE
[Bug] 移动端自定义模型配置缺少底部按钮

### ISSUE THREAD

**Issue by sxjeru** [lobehub/lobe-chat#2319]
### 💻 系统环境

Android

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

如图所示，PC端存在 footer 部分，移动端缺失，导致无法保存配置。
怀疑此处问题：https://github.com/lobehub/lobe-ui/blob/master/src/Modal/index.tsx

![image](https://github.com/lobehub/lobe-chat/assets/20513115/18d5ce0d-1f9c-45d3-95ea-02b75b800578)

![image](https://github.com/lobehub/lobe-chat/assets/20513115/ae442f23-b2be-4ef1-bba0-81fd2c214056)

### 📝 补充信息

src/app/(main)/settings/llm/components/ProviderModelList/ModelConfigModal.tsx
用 footer 自定义两个按钮是可行的，最好是搞清楚为何默认的两个按钮不显示。

**Comment by arvinxx** [comment]
@sxjeru 需要补一下 footer ，因为移动端用了 antd 的 Drawer 组件，但Drawer组件默认是没按钮的。
