### ISSUE TITLE
[Request] Ollama模型能否设置不默认显示

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#2323]
### 🥰 需求描述

能否把Ollama模型默认开启交给环境去控制，跟其它模型语言一样。因为大多数都人应该都不会在服务本机装Ollama模型，所以没必要默认开启，或者改成通过环境变量去控制。
![image](https://github.com/lobehub/lobe-chat/assets/8185843/11300f87-28b4-4a24-90bf-1f82fb79ca2b)

### 🧐 解决方案

通过环境变量去控制是否默认开启。

**Comment by sxjeru** [comment]
不知为何，ModelProviderCard 的 enabled 在 initialSettingsState 时事实上没有生效。

**Comment by RubuJam** [comment]
在环境变量中将`OLLAMA_MODEL_LIST`设置为`-all`即可
ref：https://lobehub.com/docs/self-hosting/environment-variables/model-provider
