### ISSUE TITLE
[Bug] The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#2325]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

启动有个警告，不知有啥影响。
![image](https://github.com/lobehub/lobe-chat/assets/8185843/10dfeea9-0f66-44e4-ac82-bfabfe7008a7)

**Comment by arvinxx** [comment]
哪个版本？我们的代码里应该没这个配置了才对

**Comment by yincangshiwei** [comment]
最新版没有出现。
