### ISSUE TITLE
ollama导入的自定义模型无法使用

### ISSUE THREAD

**Issue by gaye746560359** [lobehub/lobe-chat#2326]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

我使用ollama导入了自定义模型，并命名为llama3cn。在lobechat中选择该模型对话时弹出提示要求下载模型

**Comment by arvinxx** [comment]
这个就是没找到模型吧？自行检查下模型id
