### ISSUE TITLE
以前Ollama变量没有配置默认是不开的，现在没有配置Ollama变量模型也是自动开启了

### ISSUE THREAD

**Issue by linkiofo** [lobehub/lobe-chat#2328]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

以前Ollama变量没有配置默认是不开的，现在没有配置Ollama变量模型也是自动开启了。
![微信截图_20240501122249](https://github.com/lobehub/lobe-chat/assets/156993166/23eb7606-be38-460d-bdc6-8019b39faa6c)

**Comment by sxjeru** [comment]
重复 #2323

**Comment by arvinxx** [comment]
最新版使用 `ENABLE_OLLAMA=0` 可关闭

**Comment by potato1949** [comment]
> 最新版使用 `ENABLE_OLLAMA=0` 可关闭
@arvinxx 
在最新版本里配置以上环境变量，用chrome的隐身模式打开还是会有ollama的选项，似乎不生效。能帮忙看下么？辛苦了

**Comment by arvinxx** [comment]
@potato1949 `ENABLED_OLLAMA=0`，对齐了下变量名，按这个来
