### ISSUE TITLE
[Request] ability to disable custom api entry.

### ISSUE THREAD

**Issue by GOvEy1nw** [lobehub/lobe-chat#2334]
### 🥰 Feature Description

Add option to disable the ability for users to add a custom API, so they can only access and use it if they have an access code.

### 🧐 Proposed Solution

Likely via an environment variable such as DISABLE_CUSTOM_API

**Comment by HRA42** [comment]
That is a needed one! Don't want to provide the bandwith for everyone :D

**Comment by arvinxx** [comment]
We have supported it, please check document: https://lobehub.com/docs/self-hosting/advanced/feature-flags

**Comment by HRA42** [comment]
@arvinxx its still possible to set the openAI key after first setup when you need to enter the app password

My featureflags:
`FEATURE_FLAGS=-webrtc_sync,-language_model_settings,-openai_api_key,-openai_proxy_url,-create_session,-edit_agent,-dalle,-check_updates,-welcome_suggest`

Screenshot:
![image](https://github.com/lobehub/lobe-chat/assets/44985923/72290304-a6a8-493e-96df-fb10edafdbfa)
![image](https://github.com/lobehub/lobe-chat/assets/44985923/a7663fa8-4d79-40bc-aacb-ed95f2fc6290)

**Comment by arvinxx** [comment]
@HRA42 Thanks the catch, this is the missing one
