### ISSUE TITLE
[Bug] Ollama service is unavailable

### ISSUE THREAD

**Issue by yanliang84** [lobehub/lobe-chat#2337]
### 💻 Operating System

macOS

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

问题1, 文档里一致没写,docker run后,打开什么url访问chat,请问是这个么https://chat-preview.lobehub.com/chat?session=inbox&agent=
问题2, 如果是,想请问,为什么是访问一个远程的网页,而不是localhost的呢?
问题3, 3210端口是用来做啥的?
问题4 在本地启动了ollama后, 也启动了 ollama run mistral, terminal可以正常使用,curl localhost:11434也可以. 也执行了launchctl setenv OLLAMA_ORIGINS "*". 但在“语言模型“配置里,仍然链接不上ollama,报错是:
response.OllamaServiceUnavailable
Show Details
json
{
  "host": "http://127.0.0.1:11434",
  "message": "please check whether your ollama service is available or set the CORS rules",
  "provider": "ollama"
}
请问可能是什么问题呢?

### 🚦 Expected Behavior

期望使用lobe-chat访问本地ollama里的mistral模型

### 📷 Recurrence Steps

在本地启动了ollama后, 也启动了 ollama run mistral, terminal可以正常使用,curl localhost:11434也可以. 也执行了launchctl setenv OLLAMA_ORIGINS "*". 启动:docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://host.docker.internal:11434/v1 lobehub/lobe-chat

在“语言模型“配置里,仍然链接不上ollama,报错是:
response.OllamaServiceUnavailable
Show Details
json
{
  "host": "http://127.0.0.1:11434",
  "message": "please check whether your ollama service is available or set the CORS rules",
  "provider": "ollama"
}

**Comment by kampchen** [comment]
我也是，局域网有一台机器开的ollama，其他的应用比如openwebui和dify都可以调用ollama，就是lobechat不行，错误提示和楼主一样，配置了“ollama origins”也不行

**Comment by Mrered** [comment]
我也有同样的问题，局域网 Ollama 用 Open WebUI 都可以访问，用 LobeChat 不行

**Comment by ninjadogz** [comment]
我在Windows环境里,局域网内通过lobechat连Ollama遇到了同样的问题。（openweb ui可以正常连接。)

检查了ollama的连接记录，局域网连接的时候显示了以下日志。
`[GIN] 2024/05/04 - 18:35:30 | 403 |            0s |     10.168.10.1 | OPTIONS  "/api/tags"`
可能是从origin “http://10.168.10.1:3210” 获取 “http://（ollama）:11434/api/tags” 的访问被 ollama的CORS 策略阻止了。

我在系统环境变量追加了OLLAMA_ORIGINS=*，重启ollama之后就可以正常连接了。 
`set OLLAMA_HOST=0.0.0.0; set OLLAMA_ORIGINS=*; ollama serve`
linux用export或者修改.bashrc应该可以达到一样的效果。

**Comment by Mrered** [comment]
> 我在Windows环境里,局域网内通过lobechat连Ollama遇到了同样的问题。（openweb ui可以正常连接。)
> 
> 检查了ollama的连接记录，局域网连接的时候显示了以下日志。 `[GIN] 2024/05/04 - 18:35:30 | 403 | 0s | 10.168.10.1 | OPTIONS "/api/tags"` 可能是从origin “[http://10.168.10.1:3210”](http://10.168.10.1:3210%E2%80%9D) 获取 “http://（ollama）:11434/api/tags” 的访问被 ollama的CORS 策略阻止了。
> 
> 我在系统环境变量追加了OLLAMA_ORIGINS=*，重启ollama之后就可以正常连接了。 `set OLLAMA_HOST=0.0.0.0; set OLLAMA_ORIGINS=*; ollama serve` linux用export或者修改.bashrc应该可以达到一样的效果。

我已经将 OLLAMA_ORIGINS=* 设置到环境变量了，【沉浸式翻译】都可以正常调用，就是 LobeChat 不行

**Comment by yanliang84** [comment]
暂时没有回复,如果大家只是想有一个UI能够比较方便的调试LLM的话,可以使用一下这个项目,简单易部署:Ollama-ui

**Comment by holycrypto** [comment]
Same issue
```json
{
  "host": "http://127.0.0.1:11434",
  "message": "please check whether your ollama service is available or set the CORS rules",
  "provider": "ollama"
}
```

**Comment by btjawa** [comment]
是浏览器
(blocked:mixed-content)
策略的锅
