### ISSUE TITLE
[Bug]设置页面，模型选择，平板显示异常

### ISSUE THREAD

**Issue by GentlemanHu** [lobehub/lobe-chat#2341]
### 💻 Operating System

iOS

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Edge

### 🐛 Bug Description

设置页面，模型选择，平板显示异常，显示不完整

![IMG_0032](https://github.com/lobehub/lobe-chat/assets/34559079/2938fbfc-e735-4e46-a4a4-61298dd538ee)

### 🚦 Expected Behavior

正常显示

**Comment by arvinxx** [comment]
@GentlemanHu 我们先 revert 了
