### ISSUE TITLE
[Request] 提供悬浮侧栏, 以解决使用半个屏幕时的聊天框较窄问题

### ISSUE THREAD

**Issue by one-pyy** [lobehub/lobe-chat#2351]
### 🥰 需求描述

当前情况下, 左栏与右栏要么展开要么收起。在都收起的情况下聊天框的宽度充足, 然而只要展开一个, 聊天框就会略显狭窄, 都展开的话浏览器就能左右拖动。

### 🧐 解决方案

方案一是提供悬浮侧栏, 能够平时收缩左右栏, 当鼠标悬浮在上面时展开提供选择, 移出后收回

方案二是提供聊天框自定义的最小宽度, 能够通过浏览器的左右拖动来近似解决这个问题

### 📝 补充信息

lobe-chat是用过的最好的聊天前端, 非常感谢大佬们的付出!

**Comment by sxjeru** [comment]
方案二 如果是希望突破目前的最小宽度，可以临时考虑更改下面路径文件。

[src/const/layoutTokens.ts](https://github.com/sxjeru/lobe-chat/blob/main/src/const/layoutTokens.ts)

**Comment by one-pyy** [comment]
> 方案二 如果是希望突破目前的最小宽度，可以临时考虑更改下面路径文件。
> 
> [src/const/layoutTokens.ts](https://github.com/sxjeru/lobe-chat/blob/main/src/const/layoutTokens.ts)

好嘞, 感谢大佬!

**Comment by arvinxx** [comment]
方案一我们很快也会做的

**Comment by one-pyy** [comment]
> 方案一我们很快也会做的

感恩大佬们的付出!! 辛苦大佬们了!!
