### ISSUE TITLE
[Bug] Vercel builds timing out

### ISSUE THREAD

**Issue by dillfrescott** [lobehub/lobe-chat#2354]
![Screenshot_20240503_014721](https://github.com/lobehub/lobe-chat/assets/56714680/983a42d6-26b0-4c58-9d69-98f8e661ce53)

**Comment by yincangshiwei** [comment]
昨天开始的版本打包非常慢，慢了个几十倍。

**Comment by dillfrescott** [comment]
Oh, vercel only gives you 45 minutes for a build, so its failing.

**Comment by dillfrescott** [comment]
Okay! Thank you!

**Comment by allenheyulong** [comment]
请问这里只是更新了antd的包就好了么？为啥我更新了还是一样呢
