### ISSUE TITLE
[Bug] 通过readme上的按钮直接部署vercel，自动克隆，但新的仓库无法自动同步。我手动分支之后，又无法部署成功

### ISSUE THREAD

**Issue by lukefan** [lobehub/lobe-chat#2355]
### 💻 Operating System

macOS

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

今天发现升级了，但是在Actions里面没有找到upstream选项。
提了Issue，被感知是fork的姿势不对。
于是删除了github仓库，重新fork，这次可以自动up stream了。但是点击readme里面的自动部署到vercel的按钮，那个url要求我再克隆一个仓库。
于是问了GPT4，把那个URL做了修改：https://vercel.com/new/import?repository-url=https%3A%2F%2Fgithub.com%2Flukefan%2Flobe-chat&env=OPENAI_API_KEY,ACCESS_CODE&envDescription=Find%20your%20OpenAI%20API%20Key%20by%20clicking%20the%20right%20Learn%20More%20button.%20%7C%20Access%20Code%20can%20protect%20your%20website&envLink=https%3A%2F%2Fplatform.openai.com%2Faccount%2Fapi-keys&project-name=lobe-chat&repository-name=lobe-chat

然后部署了很长时间，还是没有结束。

**Comment by arvinxx** [comment]
部署时间长这个应该是今天的 vercel 构建坏了，等官方修复吧

<img width="958" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/c803b0ba-e791-4557-9836-bba47b8fafda">
