### ISSUE TITLE
Opening and Closing Sidebar via Icon Buttons

### ISSUE THREAD

**Issue by icnahom** [lobehub/lobe-chat#2365]
For better user experience, I believe pressing the buttons on the sidebar should toggle it's open and close state.
![image](https://github.com/lobehub/lobe-chat/assets/60504285/c4c96508-b87e-476b-bc9a-43328a38b602)

**Comment by arvinxx** [comment]
please track it here : https://github.com/lobehub/lobe-chat/pull/2357
