### ISSUE TITLE
[Bug] Fail to send prompt with image with Azure GPT-4 2024-04-09

### ISSUE THREAD

**Issue by Lerty** [lobehub/lobe-chat#2375]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

I can send image to this model on Azure playground, but fail on LobeChat

**Comment by Lerty** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/17094974/a8793add-7a10-4121-9063-0e5777913e2a)

**Comment by Lerty** [comment]
I found Azure using this message json :


{\"role\":\"user\",\"content\":[{\"type\":\"text\",\"text\":\"hi\"},{\"type\":\"image_url\",\"image_url\":{\"url\":\"<base64 image>\"}}]},


it use **image_url** instead of **url** of JSON properties of messages

**Comment by Lerty** [comment]
Hmmm.... 
this is interesting....

LobeChat is **already** using image_url, why the web error shows error loading 'url'


![image](https://github.com/lobehub/lobe-chat/assets/17094974/fac021b8-0d67-43f2-8ff9-db2cf9cd5db7)

**Comment by arvinxx** [comment]
@Lerty please check the post message payload. I think we use the `image_url`
