### ISSUE TITLE
[Bug] Cannot view settings button for customized model with relatively long name in openai model list

### ISSUE THREAD

**Issue by Starlento** [lobehub/lobe-chat#2376]
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Edge

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/33574105/df78a64d-6395-494b-8fdc-13b5fefcec98)

**Comment by arvinxx** [comment]
why your model select list are so small

**Comment by Starlento** [comment]
> why your model select list is so small

In previous version, the settings is in full page, I do not have issue with that. You can see that other models are set in previous version. But in recent update, it is a pop-up window. And I cannot find a scroll bar to get the settings button.
Here is the full screenshot:
![image](https://github.com/lobehub/lobe-chat/assets/33574105/50277f07-e7b8-4161-a07a-0617a18e2503)

**Comment by arvinxx** [comment]
Can your check with latest version？
