### ISSUE TITLE
[Bug] vercel部署失败

### ISSUE THREAD

**Issue by cnxsu** [lobehub/lobe-chat#2388]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

`<html>
<body>

Error: Invalid environment variables
11:15:39.912 | at p (/vercel/path0/.next/server/edge-chunks/412.js:1:891)
11:15:39.912 | at /vercel/path0/.next/server/edge-chunks/412.js:1:1071
11:15:39.912 | at i (/vercel/path0/.next/server/edge-chunks/412.js:1:1379)
11:15:39.912 | at 4093 (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:362:2425)
11:15:39.913 | at t (/vercel/path0/.next/server/edge-runtime-webpack.js:1:143)
11:15:39.913 | at 3261 (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:357:56389)
11:15:39.913 | at t (/vercel/path0/.next/server/edge-runtime-webpack.js:1:143)
11:15:39.913 | at t (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:362:4513)
11:15:39.913 | at /vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:362:4546
11:15:39.913 | at t.O (/vercel/path0/.next/server/edge-runtime-webpack.js:1:548)
11:15:39.929 |  
11:15:39.929 | > Build error occurred
11:15:39.936 | Error: Failed to collect page data for /api/auth/[...nextauth]
11:15:39.936 | at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15
11:15:39.937 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
11:15:39.937 | type: 'Error'
11:15:39.940 | }
11:15:40.141 | error: script "build" exited with code 1
11:15:40.162 | Error: Command "bun run build" exited with 1
11:15:43.471

<br class="Apple-interchange-newline">
</body>
</html>`

**Comment by arvinxx** [comment]
你填了啥环境变量

**Comment by arvinxx** [comment]
我大概知道原因了，是个bug，我修复下

**Comment by cy948** [comment]
`NEXTAUTH_SECRET` 已经废弃 #2374 ，请使用 `NEXT_AUTH_SECRET` 代替。稍后文档会更新这部分变量说明。
