### ISSUE TITLE
[Request] Function calling support for minimax models

### ISSUE THREAD

**Issue by ifsheldon** [lobehub/lobe-chat#2394]
### 🥰 Feature Description

Please add function calling/plugin calling for minimax models. Now plugins are disabled when a minimax model is selected. But MiniMax models and APIs support function calling. If the code calls MiniMax ChatCompletionV2 APIs, then adding function calling should be easy since the APIs are compatible with OpenAI's APIs.

### 🧐 Proposed Solution

Add function calling support for MiniMax models by copying and modifying the function calling support for OpenAI's models.

**Comment by ifsheldon** [comment]
I tried to investigate into this and found a minor discrepancy that is not compatible with OpenAI's API. The parameters of a function should be a string, not a json object. Otherwise, MiniMax will throw an error. That means, we need to serialize the object describing the parameters of a function into a string first and then serialize the `ChatStreamPayload` object.

**Comment by arvinxx** [comment]
@ifsheldon I have tried it. there is a really challange due to we pasre the response by ourself due to Minimax's strange error code. https://github.com/lobehub/lobe-chat/pull/2087#issuecomment-2064183112 

I'll consider it in the #1310

**Comment by ifsheldon** [comment]
@arvinxx Wow, the progress you've made are just unbelievable. Thanks a lot!
