### ISSUE TITLE
[Bug] 应用密码输入框卡顿

### ISSUE THREAD

**Issue by imwito** [lobehub/lobe-chat#2397]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

当设置 ACCESS_CODE 环境变量后登录lobechat后在密码框输入密码时会出现卡顿。

### 🚦 期望结果

优化密码框输入性能。

### 📷 复现步骤

1.设置 ACCESS_CODE 环境变量。
2.密码框输入密码。

### 📝 补充信息

设置里语言模型选项下输入api等也会出现一定卡顿，两者可能是相似问题。

**Comment by Mgrsc** [comment]
> 👀 @imwito
> 
> 感谢您提出问题。我们将对此事进行调查，并尽快回复您。请确保您已向我们提供了尽可能多的背景信息。 非常感谢您提交 issue。我们会尽快调查此事，并尽快回复您。请确保您已经提供了尽可能多的背景信息。

Please resolve this issue promptly as it greatly affects the input of passwords and custom URLs.
