### ISSUE TITLE
[Bug] Cannot upload images using the LLaVA 34B model.

### ISSUE THREAD

**Issue by wwjCMP** [lobehub/lobe-chat#2400]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

Cannot upload images using the LLaVA 34B model.

**Comment by arvinxx** [comment]
Please give more info, I can upload on my side

**Comment by arvinxx** [comment]
@wwjCMP you need to config the model with env Or model panel

**Comment by wwjCMP** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/32979859/60716549-90b3-41bb-9905-56531357fb27)

**Comment by arvinxx** [comment]
@wwjCMP check the doc https://lobehub.com/zh/docs/self-hosting/advanced/model-list

**Comment by wwjCMP** [comment]
> @wwjCMP check the doc https://lobehub.com/zh/docs/self-hosting/advanced/model-list

I understand that specific settings need to be made for the model, but I don't know where to set them.

![image](https://github.com/lobehub/lobe-chat/assets/32979859/87c58b8f-a4a5-4b0c-b477-217a18dbbe29)

**Comment by arvinxx** [comment]
@wwjCMP please give me the `OLLAMA_MODEL_LIST` string , I will try
