### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ccarpo** [lobehub/lobe-chat#2402]
### 💻 Operating System

Other

### 📦 Environment

Docker

### 🌐 Browser

Other

### Summary
When I try to ping a dns name in the docker image the domain is always resolved to host.paolsverdes.com

### Details
in the /etc/resolv.conf file the pve.org is registered as search provider:

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "resolvectl status" to see details about the actual nameservers.

nameserver 1.1.1.1
nameserver 8.8.8.8
search pve.org
```

### Impact
all dns requests the container resolves is routed to a 3rd party.

### 🚦 Expected Behavior

If I provide the name of local container or any other domain it should be handled first locally and the resolved by a public DNS provider.

### 📷 Recurrence Steps

❯ docker inspect -f '{{.State.Pid}}' lobe-chat
[result pid]
❯ sudo nsenter -t [result pid]-n ping ollama-server
PING host.palosverdes.com (47.180.81.17) 56(84) bytes of data.
64 bytes from barracuda.palosverdes.com (47.180.81.17): icmp_seq=1 ttl=51 time=175 ms
64 bytes from barracuda.palosverdes.com (47.180.81.17): icmp_seq=2 ttl=51 time=175 ms

**Comment by arvinxx** [comment]
I think it's not an issue of lobe chat?
