### ISSUE TITLE
[Bug] Models from OpenRouter that support image input not being identified as having image capability in LobeChat.

### ISSUE THREAD

**Issue by trilin6** [lobehub/lobe-chat#2405]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

As mentioned in my discussion post, i think this may be a bug so submitting this issue in hope someone could confirm if this is intended functionality or how to fix it.

### Discussed in https://github.com/lobehub/lobe-chat/discussions/2404

<div type='discussions-op-text'>

<sup>Originally posted by **trilin6** May  6, 2024</sup>
# Vision models not identifying as supporting images, disabling image input functionality ->

Recently started using LobeChat, and have ran into an issue. 

Connecting to openrouter, I see some models like GPT-4 Vision correctly identify as accepting images in the model list, however Claude 3 Opus which clearly supports image input in openrouter has this disabled in LobeChat. I am unable to find any way to override this manually and am not sure if this is intentional for some reason or a bug. 

Could anyone inform me whether this is something I'm able to fix?

Thank you.

![2024-05-06 20 59 56 - firefox](https://github.com/lobehub/lobe-chat/assets/27000192/5bc0a5c9-ce88-46e2-b989-e2918a22d4a5)
![2024-05-06 21 02 43 - firefox](https://github.com/lobehub/lobe-chat/assets/27000192/189c7966-b3ce-4cf3-a02e-fd683f319da5)

</div>

### 🚦 Expected Behavior

If a model supports image input, green eye logo should appear by model name in dropdown and image functionality should be enabled. 

This is the case for GPT-4 Vision model from OpenRouter, but Claude 3 which also supports images does not display as such.

**Comment by arvinxx** [comment]
currently we use text match to check whether the modal have vision. I can fix it

**Comment by sazonovanton** [comment]
Issue is there (v1.12.14)

![image](https://github.com/user-attachments/assets/e4a90757-c342-4769-976d-ab333e7eef3a)
