### ISSUE TITLE
[Bug] yi-34B-chat-200k返回不全

### ISSUE THREAD

**Issue by liuzj288** [lobehub/lobe-chat#2408]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

使用yi-34B-chat-200k时出现返回不全的问题，回复继续也没有输出剩余内容

![image](https://github.com/lobehub/lobe-chat/assets/13833404/6708ea7a-1e71-41ef-8df0-fc05034dcac8)

**Comment by arvinxx** [comment]
@MapleEve 来帮忙看看？

**Comment by MapleEve** [comment]
> @MapleEve 来帮忙看看？
@liuzj288 
Yi的200K最大返回应该也是4096，如果可以的话给个Chrome F12的报错信息才好定位到是什么原因，有可能是流式断了。

另外这个问题出现的是一次还是经常？

**Comment by liuzj288** [comment]
> > @MapleEve 来帮忙看看？
> 
> @liuzj288 Yi的200K最大返回应该也是4096，如果可以的话给个Chrome F12的报错信息才好定位到是什么原因，有可能是流式断了。
> 
> 另外这个问题出现的是一次还是经常？

使用这个模型的话是经常这样，需要哪个位置的报错信息？你也可以尝试下，应该很容易复现

![image](https://github.com/lobehub/lobe-chat/assets/13833404/c32a5d28-81c0-45ba-919c-8c4c7211d5c5)

![image](https://github.com/lobehub/lobe-chat/assets/13833404/2a811a9f-b662-49ef-bb4c-e595ac19471d)

![image](https://github.com/lobehub/lobe-chat/assets/13833404/8d1ebe8a-7385-492c-a21f-c372c2120b02)

**Comment by MapleEve** [comment]
> yi-34B

我稍微看了下，目前官方已经更新了模型名称，如果你是直连的话（非 Ollama 自部署的），等下面这个 PR 通过之后你再试试新的模型名称。

https://github.com/lobehub/lobe-chat/pull/2471

另外200K 的模型丢失注意力的情况如果不是回复异常中断（在 Chrome 的开发者工具界面会显示链接主动断开），就是模型自身 RAG 的问题。所以我需要一个重现出来的时候，谷歌开发者工具的控制台/网络连接内容。
