### ISSUE TITLE
[Request] 跨平台同步

### ISSUE THREAD

**Issue by techkoala** [lobehub/lobe-chat#241]
### 🥰 需求描述 | Feature Description

请问后续是否考虑提供跨平台同步功能？

### 🧐 解决方案 | Proposed Solution

可以通过webdav，各类网盘，或者upstash这种免费数据库实现

**Comment by arvinxx** [comment]
在1.x版本中有计划，当前还在0.x阶段。

**Comment by techkoala** [comment]
> 前还在0.x阶段。

好的，感谢。
