### ISSUE TITLE
[Request] DeepSeek-V2 API接入，目前为全球最强开源MoE模型

### ISSUE THREAD

**Issue by wk-mike** [lobehub/lobe-chat#2412]
### 🥰 需求描述

DeepSeek-V2 API接入lobe-chat

### 🧐 解决方案

DeepSeek-V2 与openai API 完全兼容，可以很方便的接入

### 📝 补充信息

在目前大模型主流榜单中，DeepSeek-V2均表现出色:
中文综合能力（AlignBench）开源模型中最强，与GPT-4-Turbo，文心4.0等闭源模型在评测中处于同一梯队
英文综合能力（MT-Bench）与最强的开源模型LLaMA3-70B同处第一梯队，超过最强MoE开源模型Mixtral 8x22B
知识、数学、推理、编程等榜单结果也位居前列
支持128K上下文窗口

DeepSeek-V2 API的定价为：每百万tokens输入1元、输出2元（32K上下文），价格仅为GPT-4-Turbo的近百分之一

深度求索始终秉持着最开放的开源精神，以开源推动人类AGI事业的前行。这次的DeepSeek-V2模型和论文也将完全开源，免费商用，无需申请：

模型权重：

https://huggingface.co/deepseek-ai
技术报告：

https://github.com/deepseek-ai/DeepSeek-V2/blob/main/deepseek-v2-tech-report.pdf

**Comment by wk-mike** [comment]
查看DeepSeek-V2接口文档  https://platform.deepseek.com/docs

**Comment by arvinxx** [comment]
已经在这里跟进了 https://github.com/lobehub/lobe-chat/discussions/1284#discussioncomment-9338675 这个issue我关了
