### ISSUE TITLE
Add the ability to change models for Auto Rename 

### ISSUE THREAD

**Issue by icnahom** [lobehub/lobe-chat#2420]
### 🥰 Feature Description

Limiting the model used for Auto Rename just to OpenAI, restricts users that can access their API.

### 🧐 Proposed Solution

Add a way to change the model used for Auto Rename.

### 📝 Additional Information

![image](https://github.com/lobehub/lobe-chat/assets/60504285/92a779e2-0e38-40d3-a4c5-6af86b2259d4)

**Comment by arvinxx** [comment]
Supported in https://github.com/lobehub/lobe-chat/pull/2683
