### ISSUE TITLE
[Bug] v0.155.0配置信息填入之后 默认保存了 但是返回后再查看，内容框为空 但是好像配置起作用了

### ISSUE THREAD

**Issue by jarlin8** [lobehub/lobe-chat#2423]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

设置>>默认助手>>用户输入预处理::用户最新的一条消息会填充到此模板
![image](https://github.com/lobehub/lobe-chat/assets/81870669/f826f6b9-9818-47e5-b421-fa1588f4027b)

**Comment by arvinxx** [comment]
应该是渲染出问题了，我们排查下

**Comment by canisminor1990** [comment]
fix in https://github.com/lobehub/lobe-chat/commit/12c62a03ec7ee7e8266b3edc08e78411035e8e6c
