### ISSUE TITLE
[Bug] [Critical] 在客户端配置语言模型的API key和代理地址之后无法使用服务端提供的服务

### ISSUE THREAD

**Issue by BrandonStudio** [lobehub/lobe-chat#2436]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

无法输入服务端访问密码

在填写API key和代理地址之后，删除配置，无法使用服务端提供的代理和内置API key

**Comment by arvinxx** [comment]
能具体说明下问题么？你这么说没看懂

**Comment by arvinxx** [comment]
你看下客户端请求有没有开启？会不会是删除客户端请求地址的时候没有关从客户端请求？
