### ISSUE TITLE
[Bug] Anthropic 无法从客户端请求

### ISSUE THREAD

**Issue by BrandonStudio** [lobehub/lobe-chat#2441]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

同样的配置，从客户端请求就失败，从服务器请求就成功。
![image](https://github.com/lobehub/lobe-chat/assets/55647556/dd28b0a7-bb4c-492d-a9f7-8d71031b3534)
![image](https://github.com/lobehub/lobe-chat/assets/55647556/0b8ec2e7-77a4-429d-a2d4-c4c7387276e3)
![image](https://github.com/lobehub/lobe-chat/assets/55647556/405948d8-7725-4613-a151-a97d1517831e)

### 📝 补充信息

本地调试发现从客户端输出的请求是OPTIONS而不是POST

**Comment by arvinxx** [comment]
可能被跨域限制了吧？你看下请求？
