### ISSUE TITLE
[Request] 

### ISSUE THREAD

**Issue by MartinGaoC** [lobehub/lobe-chat#2452]
### 🥰 需求描述

发现了一个很好用的平台，上边的model费用很有优势
![image](https://github.com/lobehub/lobe-chat/assets/29423673/b7715281-cf1d-4c49-a4a0-b7fff2a50cdb)

### 🧐 解决方案

可以添加对 zgi.ai 的支持，使用费用更低的model

**Comment by arvinxx** [comment]
可以前往 discussion 提议。 https://github.com/lobehub/lobe-chat/discussions/1284
