### ISSUE TITLE
[Request] 参考glm-free-api以实现支持AI绘图、支持联网搜索、支持长文档解读等功能

### ISSUE THREAD

**Issue by liuzj288** [lobehub/lobe-chat#2453]
### 🥰 需求描述

可否参考这个项目实现glm的支持AI绘图、支持联网搜索、支持长文档解读、支持代码调用、支持图像解析呢
[https://github.com/LLM-Red-Team/glm-free-api](https://github.com/LLM-Red-Team/glm-free-api)

### 🧐 解决方案

支持高速流式输出、支持智能体对话、支持多轮对话、支持AI绘图、支持联网搜索、支持长文档解读、支持代码调用、支持图像解析，零配置部署，多路token支持，自动清理会话痕迹。

**Comment by arvinxx** [comment]
不考虑任何逆向功能
