### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by youtonghy** [lobehub/lobe-chat#2461]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

当自定义模型名字过长的时候，不显示设置和删除按钮
![image](https://github.com/lobehub/lobe-chat/assets/48373340/c60de20d-2d8e-4c80-bf29-ec7067ea2d3d)

**Comment by arvinxx** [comment]
宽度应该调整过了，现在还有这个问题吗
