### ISSUE TITLE
[Bug] 无法正常使用 Azure 的模型

### ISSUE THREAD

**Issue by alva-lin** [lobehub/lobe-chat#2463]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Edge

### 🐛 Bug Description

使用 Azure 的模型，模型配置如下

模型ID: gpt-35-turbo-16k
模型部署名称: GPT-01-35-turbo-16k（对应 Azure 中的部署名称）
模型展示名称: Azure GPT-3.5 Turbo 16k

1. 新增了 Azure 的模型后，点击检查，发送了正确的网络请求并收到正确响应，但是控制台报错。
2. 回到聊天界面选择新增的模型，发送聊天后，发送了正确的网络请求并收到正确响应，但是控制台报错。

点击连通性检查后，发送的请求内容如下

```
https://yuheng-azure-openai-ea-us-05.openai.azure.com/openai/deployments/GPT-01-35-turbo-16k/chat/completions?api-version=2024-03-01-preview

{"stream":true,"max_tokens":2048,"temperature":0.6,"top_p":1,"presence_penalty":0,"frequency_penalty":0,"messages":[{"role":"user","content":"你好"}]}
```

响应如下

[连通性检查-响应.txt](https://github.com/lobehub/lobe-chat/files/15286276/-.txt)

控制台报错如下

<img width="807" alt="控制台报错" src="https://github.com/lobehub/lobe-chat/assets/30727022/685dd2b2-f216-4e0d-83d8-6cb5df0cc582">

---

如果需要测试用的 APIKEY & URL，可以后续发邮件

**Comment by arvinxx** [comment]
应该是个 bug 我修一下

**Comment by arvinxx** [comment]
根据你提供的响应修复了，https://github.com/lobehub/lobe-chat/pull/2465 等这个合并以后可以再试试看~

**Comment by alva-lin** [comment]
现在可以了，非常感谢
