### ISSUE TITLE
[Bug] 验证API有效性时，统一都是一闪而过，无论是否有效，最后都定位在 “检查通过”

### ISSUE THREAD

**Issue by lopins** [lobehub/lobe-chat#2466]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

[Bug] 验证API有效性时，统一都是一闪而过，无论是否有效，最后都定位在 “检查通过”

### 🚦 Expected Behavior

[0eb3fc0c-6688-4cea-a72a-3e55743a9763.webm](https://github.com/lobehub/lobe-chat/assets/44494732/d7de42fc-5610-4cd5-9060-1b8dd694ad06)

**Comment by RubuJam** [comment]
你可以看看console是否有对应请求发出

**Comment by Lopins** [comment]
> 你可以看看console是否有对应请求发出

有请求，也有结果，但是最终显示的前端状态都是检查通过，这个意思
