### ISSUE TITLE
[Bug] Plugins don't work

### ISSUE THREAD

**Issue by OmiiiDev** [lobehub/lobe-chat#247]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

custom "Agent" plugins don't work, i tried using web crawl and it doesn't work
Here is an example:
![image](https://github.com/lobehub/lobe-chat/assets/103533638/43d5a581-b341-45e4-bbc0-7eeccc9ed1f2)
i gave it an api key for the web search, but weather and web crawling don't work either

**Comment by arvinxx** [comment]
I will try to replay it

**Comment by OmiiiDev** [comment]
any fix yet?

**Comment by arvinxx** [comment]
@OmiiiDev I try but don't replay . It seems work will on my side.

<img width="1470" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/c42aee29-eef7-46f6-bb07-a7bb08c1e5b9">

**Comment by OmiiiDev** [comment]
Ok I will try to reproduce it and show again

**Comment by OmiiiDev** [comment]
Ok, so what i did was host the site on vercel, and then i added custom openai api proxy url and when i started talking to a custom agent and tried using its plugins it gives me this:
![image](https://github.com/lobehub/lobe-chat/assets/103533638/2bf38444-82bd-4d1b-bd48-5fbb5098689e)

**Comment by arvinxx** [comment]
@OmiiiDev did your try to create a new agent and try again?

**Comment by OmiiiDev** [comment]
Yes multiple times
