### ISSUE TITLE
[Request] 聊天内容批量操作和导出

### ISSUE THREAD

**Issue by sheldon123z** [lobehub/lobe-chat#2474]
### 🥰 需求描述

单个聊天过程的对话内容无法导出，只能一个一个地复制，希望可以加入批量操作聊天内容，并导出成指定格式的功能。

### 🧐 解决方案

请求加入对聊天内容的导出，同时能够批量化对聊天内容进行删除，清理。导出格式最好可以支持markdown，docx，pdf 这三种，如果可以，请加入导出成为训练数据集的功能。

**Comment by zhaoying9105** [comment]
附议

**Comment by arvinxx** [comment]
这个月做!
