### ISSUE TITLE
[Request] Support for Reka AI

### ISSUE THREAD

**Issue by InnerLive** [lobehub/lobe-chat#2477]
### 🥰 Feature Description

It would be great if you would support the multimodal models of Reka.ai.

The models understand text, images, video and audio.

The documentation is here:
https://docs.reka.ai/

### 🧐 Proposed Solution

Please add the reka.ai models via their API.

**Comment by arvinxx** [comment]
@InnerLive Please add it here: https://github.com/lobehub/lobe-chat/discussions/1284
