### ISSUE TITLE
[Bug] Can't view/edit second TogetherAI custom model

### ISSUE THREAD

**Issue by sirius422** [lobehub/lobe-chat#2478]
### 💻 Operating System

Other Linux

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

The custom models function does not work properly when adding cusmtom models >1. All the configurations of custom models are displayed the same as the first one.

### 🚦 Expected Behavior

When clicking the gear button, It should display the corresponding configuration.

### 📷 Recurrence Steps

1. Add the first custom model under Settings - Language Model - together.ai. Let's take `LLaMA-3 Chat (70B)` as an example. Paste string `meta-llama/Llama-3-70b-chat-hf` to "Model List" and choose `Create and add meta-llama/Llama-3-70b-chat-hf model`.
2. (Optional) Change the `Model Display Name` in `Custom model Configuration` under the dropdown menu.
3. Add a second custom model, i.e. `Qwen/Qwen1.5-110B-Chat`, like we did in step 1.
4. Now Click the gear button under the dropdown menu of the `Qwen/Qwen1.5-110B-Chat`. The menu is still displays the configuration of `LLaMA-3 Chat (70B)`, instead of `Qwen 1.5 Chat (110B)`.
![image](https://github.com/lobehub/lobe-chat/assets/38351200/7c19d13f-58eb-40c6-a62d-0441744bc527)
5. If you modify the model ID, display name and Context length to `Qwen/Qwen1.5-110B-Chat`, `Qwen 1.5 Chat (110B)` and 32K, the configuration will be saved properly and work as intented
![image](https://github.com/lobehub/lobe-chat/assets/38351200/7862b7d6-1799-47bc-800e-2c89c72b3ba4)
![image](https://github.com/lobehub/lobe-chat/assets/38351200/bf1a0b67-ef8d-4295-8e0b-c46ef0125fa0)
![image](https://github.com/lobehub/lobe-chat/assets/38351200/c4ed16dd-c595-4ddc-8e54-6fcba04e42e9)
6. After closing the `Custom model Configuration`, If I click the gear button of `Qwen 1.5 Chat (110B)` again, it will be still displayed as`LLaMA-3 Chat (70B)`. This is the same to the third custom model added.

**Comment by sxjeru** [comment]
It should have been fixed. #2488
