### ISSUE TITLE
[Request] OpenAI GPT-4o support

### ISSUE THREAD

**Issue by arunkumar611** [lobehub/lobe-chat#2479]
### 🥰 Feature Description

GPT4-mo support

### 🧐 Proposed Solution

GPT4-mo support

**Comment by linchen1987** [comment]
GPT4-mo  -> GPT-4o ?

**Comment by liuzj288** [comment]
> GPT4-mo -> GPT-4o ?

应该是GPT-4o吧，感觉是打快了给打错了

**Comment by AreChen** [comment]
希望支持,目前模型列表中的4o不支持图像输入

**Comment by ProblemFactory** [comment]
在正式添加支持之前，可以暂时通过手动添加模型使用4o。
