### ISSUE TITLE
OPENAI_API_KEY目前都哪里有买？[Request] 

### ISSUE THREAD

**Issue by star2k** [lobehub/lobe-chat#2480]
### 🥰 需求描述

大家是月抛型购买的OPENAI_API_KEY，还是国际信用卡付费方案？
单独购买有推荐店铺么？

### 🧐 解决方案

大家是月抛型购买的OPENAI_API_KEY，还是国际信用卡付费方案？
单独购买有推荐店铺么？

**Comment by cokice** [comment]
网上到处都有的卖 google 一下就好，就是不知道中转的是不是给你 gpt4
还有这个没必要提 issues 了

**Comment by yincangshiwei** [comment]
> ### 🥰 需求描述
> 大家是月抛型购买的OPENAI_API_KEY，还是国际信用卡付费方案？ 单独购买有推荐店铺么？
> 
> ### 🧐 解决方案
> 大家是月抛型购买的OPENAI_API_KEY，还是国际信用卡付费方案？ 单独购买有推荐店铺么？
> 
> ### 📝 补充信息
> _No response_

怎么联系。

**Comment by yincangshiwei** [comment]
> ### 🥰 需求描述
> 大家是月抛型购买的OPENAI_API_KEY，还是国际信用卡付费方案？ 单独购买有推荐店铺么？
> 
> ### 🧐 解决方案
> 大家是月抛型购买的OPENAI_API_KEY，还是国际信用卡付费方案？ 单独购买有推荐店铺么？
> 
> ### 📝 补充信息
> _No response_

已发gmail，可以看一下。
