### ISSUE TITLE
[Request] 支持文件上传，音视频

### ISSUE THREAD

**Issue by allenheyulong** [lobehub/lobe-chat#2482]
### 🥰 Feature Description

文件上传能够读取文件内容并输出指定要求内容
现在GPT-4o支持语音，视频聊天，能否支持？

### 🧐 Proposed Solution

增加文件上传
增加语音、视频功能

**Comment by arvinxx** [comment]
> 现在GPT-4o支持语音，视频聊天，能否支持？

GPT-4o 的接口还不支持上传语音视频文件。估计还要等一段时间吧

**Comment by arvinxx** [comment]
已支持：https://github.com/lobehub/lobe-chat/pull/3487
