### ISSUE TITLE
[Bug] 聊天历史对话错误地出现在“默认话题(临时)”

### ISSUE THREAD

**Issue by zhaobudaomingzi** [lobehub/lobe-chat#2485]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

聊天历史对话在结束响应后不是新建一个话题进行保存，而是错误地出现在“默认话题(临时)”，见下图：
![屏幕截图 2024-05-13 175604](https://github.com/lobehub/lobe-chat/assets/54617500/6a06a690-0dd4-4d1d-9414-da106b764363)

### 🚦 Expected Behavior

结束对话后，应该新建一个话题保存历史对话

### 📷 Recurrence Steps

1. 进入“随便聊聊”-“默认话题(临时)”
2. 发送自己的问题
3. （可能必须的步骤）在该网页正在输出回答的时候，新建另一个lobechat网页

### 📝 Additional Information

我推测此bug的产生可能有以下两个原因：
1. 在该网页正在输出回答时，我新建的另一个lobechat网页是另一个域名下的，并且与之前的网页一起都打开了webrtc同步
2. 该网页最终输出的回答是“无法完成请求”，因此不会完成一个新话题的创建，导致最终历史对话残留在“默认话题(临时)”

**Comment by arvinxx** [comment]
相关问题： #2501  ，应该已经已修复
