### ISSUE TITLE
[Bug] Azure OpenAI does not provide server-side option

### ISSUE THREAD

**Issue by BrandonStudio** [lobehub/lobe-chat#2487]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Edge

### 🐛 Bug Description

While OpenAI and Anthropic can send requests on server side, Azure OpenAI does not provide such option.

### 🚦 Expected Behavior

Provide "Send from server" option for Azure OpenAI

**Comment by arvinxx** [comment]
send from client？

**Comment by arvinxx** [comment]
I think the request is sent in server by default. It maybe some issue with it. @cy948 Could you please help to check it?

**Comment by cy948** [comment]
> > send from client？
> 
> I can now see the request direct to the API endpoint in the broswer console, where CORS error is reported.

Could you show me the request url?

**Comment by cy948** [comment]
Could u please help us test whether the bug would produce on the [fix preview](https://lobe-chat-git-fix-fetch-on-client-cy948s-projects.vercel.app/)? For security reason, please use a temporarily key to test. Fix detail in #2519

**Comment by cy948** [comment]
> In the fix preview, the request is sent to the backend, which avoid CORS error. However, this does not provide the option to switch between client request and server request.

Cause the request sent from client will produce CORS error, we consider disable "client request" feature for azure provider. So it would not show the options to swich between client request and server request.

**Comment by cy948** [comment]
> I believe sending directly to original Azure endpoint (*.openai.azure.com) does not meed CORS error. I met CORS error because I was sending to Cloudflare AI Gateway. Are you sure about that?

idk. So we decide to show the option for the "client request" feature in the preview and keep it disable at default.
