### ISSUE TITLE
[Bug] 自定义模型的表单问题

### ISSUE THREAD

**Issue by BrandonStudio** [lobehub/lobe-chat#2488]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

在添加多个自定义模型时，输入第一个自定义模型的信息是正常的。
当添加第二个自定义模型的时候，设置页面显示的仍然是第一个自定义模型的信息。

如：已添加一个 `model_a`，其显示名称设置为 `Model A`，最大token数设为32K
此时添加一个 `model_b`，点进设置页面，显示的仍然是 `model_a`、`Model A` 和 32K 的配置，而不是 `model_b`。
将表单改为 `model_b`、`Model B` 和 128 K，再点击 `model_a` 的设置，显示的是 `model_b`、`Model B` 和 128 K，而不是 `model_a`、`Model A` 和 32K。

### 🚦 期望结果

设置自定义模型的表单不应保留上一个模型的信息，而应该是本模型的信息

### 📝 补充信息

在 Azure OpenAI 上测的，不知道其它模型有没有这个问题

**Comment by sxjeru** [comment]
理论上已经在 #2318 被修复。
拉取到本地调试运行是正常的，暂不清楚 release 为何没有实装。
