### ISSUE TITLE
【BUG】编辑助手导致置顶取消

### ISSUE THREAD

**Issue by maxyou2090** [lobehub/lobe-chat#2489]
编辑助手导致置顶取消，保存后会取消置顶

**Comment by maxyou2090** [comment]
![Screenshot-tmtSCSbj](https://github.com/lobehub/lobe-chat/assets/26402739/91070e25-6b55-4057-8d7e-3e50f593a3b3)
补充说明下，是点击头像这里编辑后

**Comment by arvinxx** [comment]
最新版还有这个问题吗？
