### ISSUE TITLE
[Request] 希望在PluginSettingRender.tsx 加入Select 和 slider 组件 在开发插件是会需要 希望新增

### ISSUE THREAD

**Issue by laikedou** [lobehub/lobe-chat#249]
### 🥰 需求描述 | Feature Description

PluginSettingRender.tsx 中增加select组件

### 🧐 解决方案 | Proposed Solution

PluginSettingRender.tsx 里面新增

**Comment by arvinxx** [comment]
OK 合理的，我加一下
