### ISSUE TITLE
[Request] 能否添加webdav同步支持

### ISSUE THREAD

**Issue by wheesys** [lobehub/lobe-chat#2490]
### 🥰 需求描述

现有的同步方案需要多个设备在线互相同步，而且能同步的信息有点少，能不能添加webdav同步，然后加上诸如模型配置，助手配置的同步

### 🧐 解决方案

使用webdav，利用用户自己的存储能力自行同步，比如nas，网盘之类的

**Comment by arvinxx** [comment]
应该暂时没有这个计划了
