### ISSUE TITLE
[Bug] 提示gpt-4模型不存在

### ISSUE THREAD

**Issue by cksdxz1007** [lobehub/lobe-chat#2492]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Edge

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/21142070/c7d4e790-44f4-4c4b-88e5-36a63f046f6d)
![image](https://github.com/lobehub/lobe-chat/assets/21142070/03bbc7f5-5706-4e01-9f1b-4b3c4a31f3c9)
连接检测通过，但在聊天窗口却提示模型不存在。
我使用docker compose 并使用lobechat 的配置文件部署。

**Comment by arvinxx** [comment]
你试下3.5在不在。4可能就是你没有权限

**Comment by cksdxz1007** [comment]
> > 机器人检测到问题正文的语言不是英语，会自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> 你能试试 3.5 版吗？4 也许您没有权限

谢谢 ，果然是4没有权限
