### ISSUE TITLE
[Request] ollama本地大模型自定义选择是否支持视觉

### ISSUE THREAD

**Issue by MarsSovereign** [lobehub/lobe-chat#2493]
### 🥰 需求描述

ollama运行的本地大模型，例如llava，是支持视觉的，但是目前lobechat中加载ollama运行的模型都是默认不支持视觉，而且没有选项可以自行打开

### 🧐 解决方案

当使用ollama本地模型时，允许用户自行选择是否打开视觉能力（其实其他能力也一样，比如插件）

**Comment by Luffyzm3D2Y** [comment]
我也发现了，lobe-chat似乎不支持Ollama中的支持视觉的大模型，在Ollama上下载了Llava，但是无法在lobe-chat上使用。。。。。

**Comment by Luffyzm3D2Y** [comment]
而且希望Ollama中的自定义支持/不支持视觉的模型都能够使用Lobe-chat.

**Comment by Luffyzm3D2Y** [comment]
> 我也发现了，lobe-chat似乎不支持Ollama中的支持视觉的大模型，在Ollama上下载了Llava，但是无法在lobe-chat上使用。。。。。

可以看一下这个issue #1351，在前端更新设置之后就没有这个问题了。

**Comment by arvinxx** [comment]
这是支持的
