### ISSUE TITLE
latex公式出问题

### ISSUE THREAD

**Issue by YangSJ1** [lobehub/lobe-chat#2494]
我在模型里加上了提示词，提醒要正确加$，但是还是有概率出现渲染错误。
<img width="505" alt="Snipaste_2024-05-14_18-10-53" src="https://github.com/lobehub/lobe-chat/assets/156590961/fad4561a-d064-4388-b30f-35251bd002b1">
<img width="593" alt="Snipaste_2024-05-14_18-10-32" src="https://github.com/lobehub/lobe-chat/assets/156590961/621c2a50-2dec-4ad3-92e8-e30d2f111f23">

**Comment by YangSJ1** [comment]
模型为gpt-4-vision-preview。

**Comment by elonlo** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/5669148/e5c399b1-589a-4d92-8b92-18f90eda38ea)
me too

**Comment by YiyangLu** [comment]
The problem occurs because gpt would output the math latex equation in a strange style: **\( latex_code \)**

For example: when we ask the following question to chatgpt(website) or gpt4o api:
```
For the probability density function of gaussian distribution:
$$
p(x|\mu,\Sigma)=\frac{1}{(2\pi)^{p/2}|\Sigma|^{1/2}}e^{-\frac{1}{2}(x-\mu)^{T}\Sigma^{-1}(x-\mu)}
$$

what is the meaning for each variable?
```

The answer would be similar. They will include the following content:
```
- **\( x \)**: This is the \( p \)-dimensional random vector representing the variable whose distribution is being described. In other words, \( x \in \mathbb{R}^p \) is the vector of observations.

- **\( \mu \)**: This is the \( p \)-dimensional mean vector of the distribution. It represents the expected value (or the center) of the distribution. In other words, \( \mu \in \mathbb{R}^p \) is the vector of means for each dimension.

- **\( \Sigma \)**: This is the \( p \times p \) covariance matrix of the distribution. It describes the variance and the covariance between each pair of dimensions in the random vector \( x \). \( \Sigma \) must be a symmetric and positive-definite matrix. The diagonal elements represent the variances of each dimension, and the off-diagonal elements represent the covariances between dimensions.

- **\( |\Sigma| \)**: This is the determinant of the covariance matrix \( \Sigma \). The determinant of \( \Sigma \) is used in the normalization constant of the Gaussian distribution. It is crucial because it adjusts the height of the distribution so that the total probability integrates to 1.

- **\( \Sigma^{-1} \)**: This is the inverse of the covariance matrix \( \Sigma \). The inverse covariance matrix is also known as the precision matrix. It is used in the exponent to measure the "distance" of the vector \( x \) from the mean \( \mu \), scaled by the covariance structure of the distribution.

- **\( (x - \mu) \)**: This is the \( p \)-dimensional vector of deviations of \( x \) from the mean \( \mu \).

- **\( (x - \mu)^{T} \Sigma^{-1} (x - \mu) \)**: This is the Mahalanobis distance squared. It measures how many standard deviations away the vector \( x \) is from the mean \( \mu \), considering the shape of the distribution given by \( \Sigma \). It generalizes the concept of the z-score to multiple dimensions.

- **\( (2\pi)^{p/2} \)**: This term in the normalization constant comes from the multivariate generalization of the Gaussian distribution. It ensures that the integral of the pdf over the entire space is 1, maintaining the property of a probability distribution.
```

**Comment by YangSJ1** [comment]
> The problem occurs because gpt would output the math latex equation in a strange style: **( latex_code )**
> 
> For example: when we ask the following question to chatgpt(website) or gpt4o api:
> 
> ```
> For the probability density function of gaussian distribution:
> $$
> p(x|\mu,\Sigma)=\frac{1}{(2\pi)^{p/2}|\Sigma|^{1/2}}e^{-\frac{1}{2}(x-\mu)^{T}\Sigma^{-1}(x-\mu)}
> $$
> 
> what is the meaning for each variable?
> ```
> 
> The answer would be similar. They will include the following content:
> 
> ```
> - **\( x \)**: This is the \( p \)-dimensional random vector representing the variable whose distribution is being described. In other words, \( x \in \mathbb{R}^p \) is the vector of observations.
> 
> - **\( \mu \)**: This is the \( p \)-dimensional mean vector of the distribution. It represents the expected value (or the center) of the distribution. In other words, \( \mu \in \mathbb{R}^p \) is the vector of means for each dimension.
> 
> - **\( \Sigma \)**: This is the \( p \times p \) covariance matrix of the distribution. It describes the variance and the covariance between each pair of dimensions in the random vector \( x \). \( \Sigma \) must be a symmetric and positive-definite matrix. The diagonal elements represent the variances of each dimension, and the off-diagonal elements represent the covariances between dimensions.
> 
> - **\( |\Sigma| \)**: This is the determinant of the covariance matrix \( \Sigma \). The determinant of \( \Sigma \) is used in the normalization constant of the Gaussian distribution. It is crucial because it adjusts the height of the distribution so that the total probability integrates to 1.
> 
> - **\( \Sigma^{-1} \)**: This is the inverse of the covariance matrix \( \Sigma \). The inverse covariance matrix is also known as the precision matrix. It is used in the exponent to measure the "distance" of the vector \( x \) from the mean \( \mu \), scaled by the covariance structure of the distribution.
> 
> - **\( (x - \mu) \)**: This is the \( p \)-dimensional vector of deviations of \( x \) from the mean \( \mu \).
> 
> - **\( (x - \mu)^{T} \Sigma^{-1} (x - \mu) \)**: This is the Mahalanobis distance squared. It measures how many standard deviations away the vector \( x \) is from the mean \( \mu \), considering the shape of the distribution given by \( \Sigma \). It generalizes the concept of the z-score to multiple dimensions.
> 
> - **\( (2\pi)^{p/2} \)**: This term in the normalization constant comes from the multivariate generalization of the Gaussian distribution. It ensures that the integral of the pdf over the entire space is 1, maintaining the property of a probability distribution.
> ```

But I think the website should try to display the latex formula correctly in markdown form
