### ISSUE TITLE
[Bug] Claude Models don't seem to work

### ISSUE THREAD

**Issue by a7t0fwa7** [lobehub/lobe-chat#2495]
### 💻 Operating System

Other Linux

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

I keep getting error messages for the Claude3 and Claude2 models. I have entered my API key and verified the calls are made correctly as shown below:
![image](https://github.com/lobehub/lobe-chat/assets/43460290/71074205-ab38-45ef-b174-b761a3372006)
However I get this error message anytime I try to converse with Claude as shown below. Is this an existing bug?
![image](https://github.com/lobehub/lobe-chat/assets/43460290/6488a3cf-0f35-44d3-925d-3b105c8d9e59)

### 🚦 Expected Behavior

I expect that I am able to chat with Claude like I can with the other models

**Comment by a7t0fwa7** [comment]
Thank you very much for your help

**Comment by arvinxx** [comment]
@a7t0fwa7 remove your api proxy field
