### ISSUE TITLE
[Bug] gpt-4o cannot input image

### ISSUE THREAD

**Issue by evilchris** [lobehub/lobe-chat#2497]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

[Bug] gpt-4o cannot input image

**Comment by heshunme** [comment]
Could you provide more details? This feature seems to be working fine on my end.
<img width="503" alt="screenshot" src="https://github.com/lobehub/lobe-chat/assets/40694895/531bdd5f-74fa-46d2-b4b9-71605da65b8f">

**Comment by Henry-Suen** [comment]
> Could you provide more details? This feature seems to be working fine on my end. <img alt="screenshot" width="503" src="https://private-user-images.githubusercontent.com/40694895/330517147-531bdd5f-74fa-46d2-b4b9-71605da65b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDYxMzIsIm5iZiI6MTcxNTg0NTgzMiwicGF0aCI6Ii80MDY5NDg5NS8zMzA1MTcxNDctNTMxYmRkNWYtNzRmYS00NmQyLWI0YjktNzE2MDVkYTY1YjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA3NTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYWFjZjI2MjkwNDRhODllMDgxY2IyODRkZTY2MGQ1MWIwYzRmYTY4ZGFmOGQ5YTVmZTgyOTA5YzQzMTM0ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.33yzptGi7v_4AeOwo3r9emvs11GVH-0zP2vfkNqqv2g">

I am having the same issue. Because when you change the model to 4o, the upload image button will go gray and not clickable.
How do you manage to upload an image?
![image](https://github.com/lobehub/lobe-chat/assets/45254361/a802ae65-3c83-420d-a009-406a97afa6bd)

And here Arvinxx said "The current logic to determine whether multimodality is supported is whether the model name contains vision"

https://github.com/lobehub/lobe-chat/discussions/1025#discussioncomment-8104434

**Comment by ChrisXHLeung** [comment]
after I upgraded to the latest version, and cleaned my browser's data and history, It worked again.
It indicated that there could be some bug in the search and adding an online model which not originally supported.

**Comment by Henry-Suen** [comment]
Ah, I think they have solved it cuz after refreshing the model list. ( The "Get Models List" button in the Settings>Language Model)
The 4o got some icons and context length.
Now I can upload images, too.
![image](https://github.com/lobehub/lobe-chat/assets/45254361/ea6c65e1-40b9-4d01-af78-4323dc501858)

**Comment by softdream1981** [comment]
but we still can't upload .doc .pdf ?
