### ISSUE TITLE
[Bug] Ipad OS17.5（及17.4.x）系统下浏览器访问点击任一非输入功能按钮都会弹出系统键盘

### ISSUE THREAD

**Issue by GSYCCN** [lobehub/lobe-chat#2498]
### 💻 Operating System

iOS

### 📦 Environment

Official Preview

### 🌐 Browser

Safari

### 🐛 Bug Description

bug大致情况如标题，chrome/safari，全屏/台前调度窗口均可复现。Ipad OS17.5及前一17.4.x（具体版本号忘了）均可复现。最近一个月的lobechat均可复现。IOS下正常。

### 📷 Recurrence Steps

https://github.com/lobehub/lobe-chat/assets/11055122/6758b34f-f8f8-435d-89c6-065b305dfec8

**Comment by arvinxx** [comment]
你期望的是？

**Comment by GSYCCN** [comment]
> 你期望的是？

就是和其他移动端（比如ios上的Safari）访问体验一样，除了点击（触摸）输入框等确实有键盘输入需求的区域之外，点击（触摸）其他按钮/区域（比如设置键、功能切换键）不唤出键盘。现在这种情况很影响使用体验，因为键盘会占据很大一部分显示空间，必须把手动把键盘隐藏才能看到网页内容继续操作，继续操作又会自动唤出键盘。

**Comment by arvinxx** [comment]
我大概知道原因了，我们近期尽快优化掉~

**Comment by gaarry** [comment]
我也遇到了
