### ISSUE TITLE
[Bug] ❗频繁重试，使得API消耗很严重

### ISSUE THREAD

**Issue by Yanyutin753** [lobehub/lobe-chat#2501]
### 💻 Operating System

Windows

### 📦 Environment

Docker

![image](https://github.com/lobehub/lobe-chat/assets/132346501/7df9808b-e8b0-4521-b7a0-e7a5c11926e0)

### 🌐 Browser

Safari

### 🐛 Bug Description

只要没有专注页面，页面回答没有结束，而浏览其他页面，lobe就会不断重试，导致api消耗严重

![image](https://github.com/lobehub/lobe-chat/assets/132346501/c1509057-7500-4bff-ad15-698d2162c15d)

### 🚦 Expected Behavior

只要没有专注页面，页面回答没有结束，而浏览其他页面，lobe就会不断重试，导致api消耗严重

### 📷 Recurrence Steps

只要没有专注页面，页面回答没有结束，而浏览其他页面，lobe就会不断重试，导致api消耗严重

### 📝 Additional Information

希望能恢复正常！

**Comment by wangjia991** [comment]
的确，我在使用中也出现了类似的问题。大概是昨天晚上开始。

**Comment by haanling94** [comment]
我这比你更严重，没离开画面也都频繁重试，最开始是回复几个词，重试后就中断，导致最后连结果都不出来，直接报错
![image](https://github.com/lobehub/lobe-chat/assets/166829276/1af1049f-0cb7-4829-b9bc-6ea915d61bbe)
![image](https://github.com/lobehub/lobe-chat/assets/166829276/2d49e378-24a8-4f13-b7e5-64615d366cb9)

**Comment by lfglfg11** [comment]
@haanling94 我跟你的一摸一样,这问题非常严重,已经无法正常使用,我不管是vercel部署还是其他部署方式都相同问题,而且vercel部署的,前两天更新后的版本还不支持流式了!

**Comment by arvinxx** [comment]
@Yanyutin753 @lfglfg11 @wangjia991 怎么复现？有没有具体的复现方法？

**Comment by arvinxx** [comment]
试试 0.159.8 能否解决上述问题

**Comment by arvinxx** [comment]
> 前两天更新后的版本还不支持流式了

不支持流式可以另外开一个 issue 帮你看看

**Comment by haanling94** [comment]
> 试试 `0.159.8` 能否解决上述问题

新版已解决
