### ISSUE TITLE
默认环境变量配置在chat中体现

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#2508]
### 🥰 需求描述

你好我在启动容器是分别配置openai 和 OLLAMA 还有智浦的环境变量但是启动容器时无法提现，还是需要输入，我想让她成为默认的值，请问应该怎么解决

### 🧐 解决方案

我想要环境变量配置完容器里面就会存在无需用户再次输入

### 📝 补充信息

麻烦帮忙看一下谢谢

**Comment by arvinxx** [comment]
使用 Default Agent config 环境变量 https://lobehub.com/zh/docs/self-hosting/environment-variables/basic#default-agent-config
