### ISSUE TITLE
各种大模型的url和key在docker部署lobechat中直接配置进去

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#2509]
### 🥰 需求描述

各种大模型的url和key在docker部署lobechat中直接配置进去，用户启动网页直接使用即可

### 🧐 解决方案

麻烦帮忙看看这个问题，我现在的命令是
docker container  run -d -p 3210:3210 -e OPENAI_API_KEY=hk  -e OPEN_PROXY_URL=https     -e  OLLAMA_PROXY_URL=http -e    Zhipu_API_KEY=e9jnAw2U5   -e ACCESS_CODE=lobe66 --name lobe-chat  lobehub/lobe-chat:latest
 但是启动时这些大模型数据还是要手工填入

### 📝 补充信息

![1715743051776](https://github.com/lobehub/lobe-chat/assets/169867372/fb374ec2-fd81-4c7e-8f94-b770b844b3fa)

**Comment by snape4669** [comment]
@zhangleijun111 如果在部署时没报错，那部署后的模型页面是不显示后台部署的信息的，你试一下直接在你填写正确api key那个模型那里，点连通性检查，如果显示检查通过，那就没问题了，如果报错，要看看具体报错信息是什么

**Comment by zhangleijun111** [comment]
如果我不想修改功能只想修改一下Ui界面知道怎么修改哪个文件发

**Comment by arvinxx** [comment]
好好看看文档。你的环境变量写错了

**Comment by snape4669** [comment]
那你应该看官方的[Development Guide](https://github.com/lobehub/lobe-chat/wiki/index)
