### ISSUE TITLE
手机端页面导入配置文件的按钮消失了[Bug] 

### ISSUE THREAD

**Issue by Leefurmore** [lobehub/lobe-chat#2510]
### 💻 系统环境

iOS

### 📦 部署环境

Docker

### 🌐 浏览器

Safari

### 🐛 问题描述

自从settings页移到头像那里后，手机端上现在无法正常导入全局配置文件，只能先请求桌面端网页后，再点头像进行导入，希望能改进这个问题。

**Comment by sxjeru** [comment]
点击头像 -> 数据存储 -> 导入配置。

入口在这，功能实现应该没问题。

**Comment by Leefurmore** [comment]
Got it, thanks for your support.
