### ISSUE TITLE
打开设置页面卡顿[Bug] 

### ISSUE THREAD

**Issue by BruceLee569** [lobehub/lobe-chat#2516]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

每次打开设置都会向服务器发送请求，导致设置页面显示卡顿，没请求必要时能否先显示？

**Comment by arvinxx** [comment]
@Cp0204 你确定最新版本还有这个问题吗

**Comment by BruceLee569** [comment]
> @Cp0204 你确定最新版本还有这个问题吗

用的是最新版本，每次打开设置页和子设置项时，都会往 api/market 发送GET请求，导致进入页面卡顿。
![image](https://github.com/lobehub/lobe-chat/assets/49506152/7ced3985-6bb8-4743-9e01-654f5a1c8c5c)

**Comment by Cp0204** [comment]
> @Cp0204 你确定最新版本还有这个问题吗

是的，最新版。lobe请求资源太频繁，首次打开，就有200+个请求，切换对话，也会请求，部署在远程的体验很不好。

![image](https://github.com/lobehub/lobe-chat/assets/5239753/3fd6eabc-73b0-4366-a36d-97f1f9ee566d)

**Comment by Cp0204** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/5239753/9263318e-033b-4c9c-88e7-50974ddc591a)

每切换对话都会请求这些资源，其实不必要的。 

---

不知道作者是不是部署在本地，并且用的配置非常高的电脑（或者mac和windows之间的差异？），因为我在issue下尝试搜解决方法，发现其实很多人反映过卡顿的问题，作者似乎感受不强。其实卡顿感很明显的。

我也怀疑过网络的问题，试过部署在国内的服务器，有一点改善，但也没有质的区别。

**Comment by ShinChven** [comment]
确实很卡

**Comment by devyujie** [comment]
+1

**Comment by eightHundreds** [comment]
求求你把ssr，server component去掉💔

**Comment by arvinxx** [comment]
> 都会往 api/market 发送GET请求，导致进入页面卡顿。

是因为这个请求卡顿吗？

**Comment by arvinxx** [comment]
> 每切换对话都会请求这些资源，其实不必要的。

这些资源应该都在 service worker 缓存了的。你说的卡应该和这个没关系


我日常用的是MBP 20年 M1 的 13寸，并没有很卡。另外之前已经做了非常多轮的性能优化，应该比以前好很多了。目前剩余已知的是会话页面的切换和助手的切换是还存在一定延迟的问题，下个月应该能根治掉了。

**Comment by ShinChven** [comment]
反正没有NextChat丝滑

**Comment by BruceLee569** [comment]
有缓存的情况下体验还过得去，首次访问的加载速度是真的慢，PC端要1分多钟才渲染完毕。我对比过ChatGPT-Next-Web和chatgpt-web-midjourney-proxy，PC端浏览器他们只需要三四秒，移动端lobe也至少比他们慢一倍，包括PWA应用。
测试链接：https://ai.jdz-ceramic.com/、https://ai1.jdz-ceramic.com/
测试服务器：搬瓦工2H2G

https://github.com/lobehub/lobe-chat/assets/49506152/e6e9018a-4807-4ff1-9f41-60b1288d27b9

**Comment by Cp0204** [comment]
> service worker

service worker 也撐不住資源多啊，一個幾十毫秒，時間都量變引起質變了。再加上服務器的請求…… 😂

**Comment by arvinxx** [comment]
> 首次访问的加载速度是真的慢，PC端要1分多钟才渲染完毕。

@BruceLee569 preview 站点的访问也有这么慢么？另外我拿我的电脑打开你的站点很快啊，没缓存的情况也基本上秒开。你确定不是你的网络问题么？

https://github.com/lobehub/lobe-chat/assets/28616219/863eb9ea-a1d6-4fec-a679-f933446b1976

**Comment by BruceLee569** [comment]
@arvinxx 网络没问题的，进这个聊天页面：https://ai.jdz-ceramic.com/chat

**Comment by Cp0204** [comment]
> 有缓存的情况下体验还过得去，首次访问的加载速度是真的慢，PC端要1分多钟才渲染完毕。我对比过ChatGPT-Next-Web和chatgpt-web-midjourney-proxy，PC端浏览器他们只需要三四秒，移动端lobe也至少比他们慢一倍，包括PWA应用。推荐给朋友都不好意思，用户体验堪忧呀，希望能多多测试优化一下。
> 
> 测试用户端：Windows11 Chrome浏览器 测试链接：https://ai.jdz-ceramic.com/chat https://ai1.jdz-ceramic.com/ https://ai2.jdz-ceramic.com/ 测试服务器：搬瓦工2H2G 服务器部署方式：docker镜像
> 
>  1716173717854-1716173266494-20240520_104413.mp4

首次访问的请求数😂

![image](https://github.com/lobehub/lobe-chat/assets/5239753/3a321895-8981-4a32-a9a5-f51f0f447aeb)

**Comment by ShinChven** [comment]
https://github.com/lobehub/lobe-chat/assets/3351486/fdc14906-577b-429e-81e9-63134ea3e4f9

MacBook Pro 15 mid 2014 16GB

**Comment by BruceLee569** [comment]
> 2024-05-20.2.35.28.mov 
> MacBook Pro 15 mid 2014 16GB

😂 跟我一样，没有对比就没有伤害。。

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/assets/28616219/4cbccbb3-9905-4482-a9c0-58f0c4463b10

我试了访客模式，直接访问，SSR 首屏 2s 左右，10s 后渲染完成 list 。总体大概 20s 左右全部渲染完成。这个速度在我看来也还行啊？ 毕竟你这个又没 CDN 加速，下载速度完全取决于你的服务端出口带宽…

如果是在 Vercel 部署的 preview，静态资源走的 CDN ，全部渲染出来只要 5s：

https://github.com/lobehub/lobe-chat/assets/28616219/ae0294a8-ab26-4a1f-b176-23d0c99eedf5

**Comment by arvinxx** [comment]
> 另外提个建议：感觉主页没必要单独显示一个欢迎界面，没啥作用，直接显示对话框用户体验会更好吧，主流的工具默认都是一个对话框，功能够用能用就好，拖慢性能的实现可以考虑放一放。

你的这个建议让我有点怀疑你是不是真的在用了… 这个 welcome 只有新用户进来才会显示，如果你的本地会话记录超过 4 条，默认就会跳转到 /chat 路由的。

**Comment by ShinChven** [comment]
> Area.mp4 
> 我试了访客模式，直接访问，SSR 首屏 2s 左右，10s 后渲染完成 list 。总体大概 20s 左右全部渲染完成。这个速度在我看来也还行啊？ 毕竟你这个又没 CDN 加速，下载速度完全取决于你的服务端出口带宽…
> 
> 如果是在 Vercel 部署的 preview，静态资源走的 CDN ，全部渲染出来只要 5s：
> 
>  Preview.mp4

我不管，我就是喜欢秒开。

**Comment by arvinxx** [comment]
> MacBook Pro 15 mid 2014 16GB

@ShinChven 如果是这个配置，使用 LobeChat 会卡的话，我个人还是建议你使用 NextChat 吧。 我并不打算为这么老的设备做什么优化，抱歉 🤷‍♂️

**Comment by ShinChven** [comment]
> > MacBook Pro 15 mid 2014 16GB
> 
> @ShinChven 如果是这个配置，使用 LobeChat 会卡的话，我个人还是建议你使用 NextChat 吧。 我并不打算为这么老的设备做什么优化，抱歉 🤷‍♂️

我主力机 M1 Max 64GB 进 Settings 也卡……

**Comment by arvinxx** [comment]
@ShinChven 那能否录个屏看下具体怎么卡呢？

**Comment by BruceLee569** [comment]
> > 另外提个建议：感觉主页没必要单独显示一个欢迎界面，没啥作用，直接显示对话框用户体验会更好吧，主流的工具默认都是一个对话框，功能够用能用就好，拖慢性能的实现可以考虑放一放。
> 
> 你的这个建议让我有点怀疑你是不是真的在用了… 这个 welcome 只有新用户进来才会显示，如果你的本地会话记录超过 4 条，默认就会跳转到 /chat 路由的。

我用了这么久，都安利给几个朋友了。谁也不会去留意首页的跳转路由啊，所以我说缓存之后再用速度还可以，但进设置页还是会卡，我对前端不太熟悉，但我觉得点击后路由跳转到 `settings/modal` 应该就是卡顿的原因，其他框架进入设置并不会有路由跳转的动作。包括进入每一个子设置项，都会单独发送请求，等个一两秒，请问这设计是否合理呢？

即使将它优化到秒进，让请求在后台成功后再更新数据，但我只是进一个首页，后台在那里默默发送超过1000个请求（绝大部分都是不知道有什么用处的 js 文件），然后点一下设置，又在那里发送超过500个请求，说实话用这耗电量都大好多。

大部分用户都是普通人，第一次打开的时候也确实很卡（人们分享的时候也不会留意链接是首页还是聊天页），我试了你的 vercel 链接也是一样卡，跟 cdn 没关系，请在Windows端测试一下。


https://github.com/lobehub/lobe-chat/assets/49506152/b03ee873-65e6-4009-8c76-364cbbcf2aa6


找到bug点了，3秒请求之后，在页面处随便点击一下，UI就渲染出来了。（虽然后台还是会默默依次发送近1000个js请求。。）

https://github.com/lobehub/lobe-chat/assets/49506152/320911c9-b651-4a5f-a2b3-5fed7d0bda34

**Comment by arvinxx** [comment]
> 找到bug点了，3秒请求之后，在页面处随便点击一下，UI就渲染出来了

这个似乎是 SSR 水合问题… 就是客户端和服务端的语种没有匹配上，导致首次水合失败，然后会一直 fallback 到静态 html 的样子。只有用户做了点击操作后，才会重新在 client 端进行渲染。但第二次及以后，客户端的主题/语种都会在 cookie 中记录下来，这样水合就能顺利完成。

我理解这个应该也就是第一次会出现，而且用户不做任何操作的概率也比较低，所以一直没当回事 😅

我看看后续怎么修复下吧。

> 即使将它优化到秒进，让请求在后台成功后再更新数据，但我只是进一个首页，后台在那里默默发送超过1000个请求（绝大部分都是不知道有什么用处的 js 文件），然后点一下设置，又在那里发送超过500个请求，说实话用这耗电量都大好多。

这个我理解应该是 pwa 的特性吧？浏览器会在空闲的时候预先将整个网站都缓存下来，这样在未来打开网站的速度会加快。这不算一个 feature 么…

**Comment by arvinxx** [comment]
> 其他框架进入设置并不会有路由跳转的动作。包括进入每一个子设置项，都会单独发送请求，等个一两秒，请问这设计是否合理呢

你说的发给 `/api/market` 这个我已经修了，你再试试看？ 另外我好像没看到你录制关于进入设置页卡的视频？

**Comment by BruceLee569** [comment]
嗯嗯 感谢回复 现在好很多了

设置项每次点完还是需要等待渲染，不能秒开，操作速度一快UI也容易反应不过来，感觉卡卡的。首次缓存后再次点击，大部分UI都不用等待渲染了。但是关闭窗口之后再进入又会慢一点，PWA应用杀后台再进又会更慢一点。

后续能够注意优化就更好啦 👏

**Comment by kele527** [comment]
问题是本质不是加载慢，而是操作的时候UI卡顿，比如点任意一个按钮，都要等2秒才响应，正常的网页应该是点击后在0.1秒内响应，超过0.3秒就会明显感受到卡顿

**Comment by arvinxx** [comment]
@kele527 你说的没错，操作延迟的问题是存在的，还需要做更多的优化

**Comment by ShinChven** [comment]
你是不是整了什么 SSR ？纯SPA应该不会这么卡

**Comment by arvinxx** [comment]
> 你是不是整了什么 SSR ？纯SPA应该不会这么卡

跟SSR没啥关系。 Next 默认的路由体系是 MPA (多页应用)，理论上是会比SPA的慢

**Comment by dongjb** [comment]
我部署在新加坡的服务器上，有缓存的情况下访问应该还行，2S左右，但是切换操作的不是很流畅，有卡顿，另外我将代码拉到本地，启动巨慢，是超级慢，点一个页面都得好2、3分钟......

配置：i9Mac 64G内存

**Comment by ShinChven** [comment]
> 我部署在新加坡的服务器上，有缓存的情况下访问应该还行，2S左右，但是切换操作的不是很流畅，有卡顿，另外我将代码拉到本地，启动巨慢，是超级慢，点一个页面都得好2、3分钟......
> 
> 配置：i9Mac 64G内存

新加坡+1，我NextChat和Lobe都在一起。

最近给朋友安利lobe，昨天就告诉我加载不出来。

<img width="341" alt="image" src="https://github.com/lobehub/lobe-chat/assets/3351486/9cd5a426-0e50-4e84-8d48-4daddfb70a3a">

**Comment by ShinChven** [comment]
> > 你是不是整了什么 SSR ？纯SPA应该不会这么卡
> 
> 跟SSR没啥关系。 Next 默认的路由体系是 MPA (多页应用)，理论上是会比SPA的慢

要不要用 Vite + React Router 重构一下， 非常丝滑的。挂在 Express 的 middleware 上一样可以搞 MPA 。

https://github.com/ShinChven/druid/blob/main/app/src/views/index.ts

**Comment by arvinxx** [comment]
@ShinChven 不计划

**Comment by ShinChven** [comment]
> > 有缓存的情况下体验还过得去，首次访问的加载速度是真的慢，PC端要1分多钟才渲染完毕。我对比过ChatGPT-Next-Web和chatgpt-web-midjourney-proxy，PC端浏览器他们只需要三四秒，移动端lobe也至少比他们慢一倍，包括PWA应用。推荐给朋友都不好意思，用户体验堪忧呀，希望能多多测试优化一下。
> > 测试用户端：Windows11 Chrome浏览器 测试链接：https://ai.jdz-ceramic.com/chat https://ai1.jdz-ceramic.com/ https://ai2.jdz-ceramic.com/ 测试服务器：搬瓦工2H2G 服务器部署方式：docker镜像
> > 1716173717854-1716173266494-20240520_104413.mp4
> 
> 卡顿非常影响用户体验。 虽然卡顿的issue被关闭了好几个，但是今天2024-07-28为止，首次访问卡顿的问题并没有改善，首页几分钟才能进去。我部署在vercel，一段时间不请求，服务端自动把next.js实例卸载了，那么再次访问又是首次访问首页，又要等几分钟才能开始使用。 有时候就是几秒钟有那么一个想法要问一下AI，打开网页等个几分钟正是会打断思路，有这个等的时间，干点别的事情之后，又会忘记刚才自己想要打开lobechat要干嘛了？

我最近肉翻了以后，感觉速度已经很好了。归根结底还是要感谢祖国。

**Comment by SuperNG6** [comment]
> @arvinxx 网络没问题的，直接进这个聊天页面会很卡：https://ai.jdz-ceramic.com/chat 为什么要发送两百多个JS请求 chat UI 才渲染出来 😂
> 
> 像你这样先进主页，再点立即开始速度就还好。
> 
> 另外提个建议：感觉主页没必要单独显示一个欢迎界面，没啥作用，直接显示对话框用户体验会更好吧，主流的工具默认都是一个对话框，功能够用能用就好，拖慢性能的实现可以考虑放一放。

我也认我欢迎页面没什么用，自己用的服务，直接进入对话框比较好，可以使用 nginx 重写路径，指向 /chat

**Comment by bestZwei** [comment]
还是觉得慢，加载的组件多、页面操作响应慢、对话输出的缓冲... 虽然功能强大，但总感觉比一般都网页慢

**Comment by liangzhaoliang95** [comment]
服务端版本的更卡，动不动就是加载失败，真的很无语。
无奈只能换回本地版本用用

**Comment by arvinxx** [comment]
@liangzhaoliang95 试试最新的服务端版本呢？
