### ISSUE TITLE
[Bug] 电脑端浏览器获取不到gpt4o模型

### ISSUE THREAD

**Issue by TyangWu** [lobehub/lobe-chat#2518]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

使用的是Chrome，Docker更新后，gpt4o需要手动更新模型列表才能显示，Gemini Flash需要点一下重置才能显示出来。

**Comment by TyangWu** [comment]
edge浏览器没有Gemini这个问题。我不记得了，这两个模型都是使用的默认配置

**Comment by arvinxx** [comment]
@TyangWu 那我确定应该就是你之前改过模型配置的关系
