### ISSUE TITLE
[Bug] Ollama连通性检查失败

### ISSUE THREAD

**Issue by anrgct** [lobehub/lobe-chat#2520]
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

![1715781855586](https://github.com/lobehub/lobe-chat/assets/16172523/7781693b-0a03-426d-8193-0cdae16327f3)
Ollama连通性检查失败，我通过配置docker中lobe访问主机的ollama服务，关闭了“使用客户端请求模式”，但是“连通性检查”仍然是通过浏览器直接发出的，虽然在聊天界面可以正常使用了，但是这个提示是错误的。

**Comment by rennai** [comment]
启动 ollama 需要设置环境变量：
OLLAMA_ORIGINS=* ollama serve
或
OLLAMA_ORIGINS=* ollama run llama3

**Comment by anrgct** [comment]
https访问http有mixed-content错误，“使用客户端请求模式”并不控制“连通性检查”。我在Windows控制面板-系统属性-环境变量-用户环境变量新建变量名"OLLAMA_HOST"变量值"0.0.0.0",变量名"OLLAMA_ORIGINS"变量值"*"，设置成功后，沉浸式翻译都接入ollama成功了，但是lobe-chat中“连通性检查”始终失败，因为我是https的本地域名启动的lobe-chat，这个状态下“使用客户端请求模式”关闭后可以正常聊天使用。

**Comment by arvinxx** [comment]
duplicate of #2266
