### ISSUE TITLE
[Bug] NEXT_PUBLIC_BASE_PATH not work

### ISSUE THREAD

**Issue by YealKio** [lobehub/lobe-chat#2526]
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

Chat-lobe + ollama +nginx not work.
Chat-lobe can not init in the first time, like nginx SUBPATH thing, not sure, see my step please.

BTW, ollama server and Chat-lobe server are not the same device, but in LAN.
I can run OPEN-WEBUI + OLLAMA + NGINX without problem.

### 🚦 Expected Behavior

Even can not init.

### 📷 Recurrence Steps

Chat lobe run with docker: 
`sudo docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://192.168.2.202:11434 -e NEXT_PUBLIC_BASE_PATH=/chat-lobe  lobehub/lobe-chat`
this my nginx conf file:

```

upstream chat-lobe {
   server 127.0.0.1:3210;
}

    location  /chat-lobe/ {
         proxy_pass http://chat-lobe/;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         access_log /var/log/nginx/chat-lobe.access.log;
         error_log /var/log/nginx/chat-lobe.error.log;
    }
```

when I open my.nas.com:port/chat-lobe, the Chrome just show:
![image](https://github.com/lobehub/lobe-chat/assets/48641500/52bbef73-127f-4cbf-a030-1e411096c8fc)

The website console like:

![image](https://github.com/lobehub/lobe-chat/assets/48641500/e367ff62-8807-478c-a587-28aa965e7ce0)

Can not find any thing, and  one of Request URL  like: `Request URL:
http://my.nas.com:port/_next/static/chunks/webpack-72cd2e677540060b.js` 

It look like NEXT_PUBLIC_BASE_PATH  not work as expected, please help!

### 📝 Additional Information

Ollama server and Chat-lobe server are not the same device, but in LAN.

**Comment by arvinxx** [comment]
NEXT_PUBLIC_BASE_PATH is not working with docker. You need to build it with `NEXT_PUBLIC_` env by yourself
