### ISSUE TITLE
[Request] 多代理添加和切换

### ISSUE THREAD

**Issue by zxitedu** [lobehub/lobe-chat#2527]
### 🥰 需求描述

会有一种情况 有多个代理的地址 但是会有不稳定的情况 希望可以添加一个多代理和多代理支持的功能
There will be a situation where there are multiple proxy addresses, but there will be unstable situations. I hope to add a function of multi-proxy and multi-proxy support.

### 🧐 解决方案

可以在配置的时候添加多个代理，可以在对话框进行切换 就可以解决了 谢谢
You can add multiple proxies during configuration, and you can switch in the dialog box to solve it, thank you.

**Comment by arvinxx** [comment]
多代理不计划支持，你可以考虑使用 one-api 来做负载均衡
