### ISSUE TITLE
[Request] Make text streaming stop scrolling after certain amount of words to prevent interrupting reading on mobile views.

### ISSUE THREAD

**Issue by Henry-Suen** [lobehub/lobe-chat#2534]
### 🥰 Feature Description

Since some models generate texts pretty fast and when the texts are long (especially for stories and code), the dialogues are scrolling fast down to the bottom which interrupts reading and makes us have to scroll back to the start every time.
Here's an example.

https://github.com/lobehub/lobe-chat/assets/45254361/d8b3a3e2-d4a0-47f1-be7d-c967a37475a4

### 🧐 Proposed Solution

Make the scrolling stop after a customizable amount of words been output. So short conversations won't be affected.

**Comment by sonnyding1** [comment]
Or by default scroll to the bottom while text is still generating, but when the user performs a manual scroll, automatic scrolling should stop, the user can actually look at the text.

**Comment by Henry-Suen** [comment]
> Or by default scroll to the bottom while text is still generating, but when the user performs a manual scroll, automatic scrolling should stop, the user can actually look at the text.

They already did that. And it's not working efficiently. The scrolling keeps fighting with user's holding. 
Developers of LobeChat can check how ChatGPT app on iOS handle this. 
When the top of the text reaches the top of the screen, it'll just stop scrolling.

**Comment by youralmight** [comment]
I hope it never scrolls.

This issue appears not only on mobile but also on desktop views. I don't understand why most users tolerate this problem.

Moreover, this problem not only affects the reading experience, but it also makes copying difficult because scrolling changes the cursor's position in the text
