### ISSUE TITLE
[Bug] 使用远程模型（比如说配置如 docker 的参数中）时，校验通过的提示不再展示

### ISSUE THREAD

**Issue by ha7rock** [lobehub/lobe-chat#2538]
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Other

### 🐛 问题描述

在客户端设置模型的界面中，当模型的 api-key 是在后端配置过时，当下的版本点击“检查”后不再像之前一样显示“检查通过”的提示。

### 🚦 期望结果

希望修复

### 📷 复现步骤

如前所述，必现 bug

**Comment by miladhatami1393** [comment]
Good job
