### ISSUE TITLE
[Request] 关于支持nextchat聊天记录的导入

### ISSUE THREAD

**Issue by yuluod** [lobehub/lobe-chat#2542]
### 🥰 需求描述

现在主要用的是nextchat，所以有一堆聊天记录。基于不想丢失聊天记录的想法，能否支持nextchat的导出的json格式的数据备份？

### 🧐 解决方案

能够提供按钮或者什么形式导出

**Comment by arvinxx** [comment]
不计划支持，nextchat 是基于会话维度，而LobeChat是基于助手维度，两者并不等价。

另外考虑到nextchat 版本后续版本迭代可能会造成数据结构的破坏性变更，这个功能的可持续性是存疑的。
