### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by guling-io** [lobehub/lobe-chat#2560]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

可以不可以给密码设置一个开关，可以自由控制是否需要填写密码

### 🚦 期望结果

密码开关，控制是否需要填写密码

**Comment by arvinxx** [comment]
本来就支持。去掉access code环境变量就好
