### ISSUE TITLE
[Bug] gemini 生成报错

### ISSUE THREAD

**Issue by devyujie** [lobehub/lobe-chat#2564]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/48620527/5add186b-29ec-4dae-8cc1-14acc7f58f3c)

**Comment by Met-Du** [comment]
I encountered this error too. It's been happening for two days.

**Comment by Nicecsh** [comment]
same question

**Comment by arvinxx** [comment]
<img width="950" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/90ecb8a2-b3a7-4a41-aa74-96e5e6e8a126">

I can't reproduce this error. please show more info.

**Comment by Nicecsh** [comment]
问题的产生受内置插件DALL E3影响，停用DALL E3可以临时性解决问题。
