### ISSUE TITLE
[Bug] 数学的符号没有翻译过来

### ISSUE THREAD

**Issue by shareLanb** [lobehub/lobe-chat#2568]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Firefox

### 🐛 问题描述

数学的符号没有翻译过来
<img width="778" alt="c657217c28a3b6907c08bdf7cbb526d4" src="https://github.com/lobehub/lobe-chat/assets/150011750/dcc136a2-8555-4e65-994a-f3c91d8cb34b">

### 🚦 期望结果

能修复吗，还是说我这里的问题

**Comment by shareLanb** [comment]
希望弄成markdown形式的，至少弄个能看的

**Comment by arvinxx** [comment]
应该已经修复了
