### ISSUE TITLE
[Bug] The openai agent parameters in the Docker startup method cannot be switched to the official API direct connection mode.

### ISSUE THREAD

**Issue by osbi-code** [lobehub/lobe-chat#2569]
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

After I started Docker with the following command (specifying the openai apikey and proxy in the parameters)：
```
sudo docker run -d -p 22004:3210 \
  -e ACCESS_CODE=XXXXXX\
  -e OPENAI_API_KEY=sk-62yXKMz9LiXXXXXXXX \
  -e OPENAI_PROXY_URL=https://XXXXXX/v1 \
  --restart always \
  --name lobe-chat_demo \
  lobehub/lobe-chat
```
 I later obtained the official direct connection key. I then set the key in the web interface, leaving the proxy field empty. However, the system kept prompting that the key does not exist.

**Comment by arvinxx** [comment]
need more information about your case
