### ISSUE TITLE
启动慢，响应慢[Bug] 

### ISSUE THREAD

**Issue by Greasen** [lobehub/lobe-chat#2572]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

启动的好慢啊，点击应用中的功能响应也很慢，是什么原因导致的不知道

### 🚦 期望结果

同时打开 chatgpt 和 lobechat，chatgpt启动要快很多很多

**Comment by dongjb** [comment]
i9的Mac，64G内存，启动巨慢，响应也是，搞的我以为没操作上

![CleanShot 2024-05-24 at 10 09 04@2x](https://github.com/lobehub/lobe-chat/assets/33796081/0aed19b2-a782-4680-83cd-a1ba378b936a)

**Comment by arvinxx** [comment]
@dongjb 你这个是dev 当然慢了…

**Comment by Greasen** [comment]
这段时间的测试看来快了很多很多。但是移动端还是偏慢的。是资源加载的问题嘛？

**Comment by Greasen** [comment]
> > 但是移动端还是偏慢的。是资源加载的问题嘛？
> 
> @Greasen 能否具体说下是哪里慢？可以再开个 issue 专门说明下，我们好定向优化

1. 移动端初始化打开页面白屏时间过久
2. 底部菜单和链接点击进入页面的时候比较慢

相比之下，已经比之前快很多了，pc 端和移动端都有了很大的提升，非常感谢作者

**Comment by lwdnxu** [comment]
大佬，那应该用那个版本？

**Comment by arvinxx** [comment]
@anuxs 我们并没有遇到你说的问题，如果你需要协助排查，可以开一个 issue 我们帮你看看。

**Comment by leeyoshinari** [comment]
不知道为什么作者说不慢，但是我这里一直都很慢。之前我就提过，他们给了一个浏览器网站性能测试结果，如果我觉得慢让我排查一下问题，但是我要是能自己排查的话，我就会自己修复了。

**Comment by arvinxx** [comment]
@leeyoshinari 你觉得怎么样算慢？目前 lobechat.com 我自己用的情况下，首屏看网络情况在 2-5s 之间，在我看来是可以接受的范围。

https://github.com/user-attachments/assets/7ca34bd0-253a-4bd2-a771-2151964f928d

如果你要求极致的首屏秒开，目前我们的情况下暂时是做不到的，可以考虑换 NextChat

**Comment by arvinxx** [comment]
如果觉得慢可以另外开个 issue 来帮你看下，老的 issue 就不挖坟了
