### ISSUE TITLE
[Bug] 偶发的返回错误Invalid schema for function 'clock-time____getCurrentTime____standalone': None is not of type 'array'.

### ISSUE THREAD

**Issue by songtanjichuan** [lobehub/lobe-chat#2575]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/7565822/6d597504-abfb-4e96-a422-32eda0a27a90)

![image](https://github.com/lobehub/lobe-chat/assets/7565822/b7d3bcb7-a46a-48c7-a7ac-9815dca0ce60)
复现不可控。我怀疑是时间插件导致的问题

### 🚦 Expected Behavior

期望 不会偶发性的返回错误

### 📷 Recurrence Steps

1.在随便聊聊中选择时钟插件，试了几次就复现了。

**Comment by arvinxx** [comment]
试过官方 API 吗？也有可能是你的服务商的问题哦…

**Comment by songtanjichuan** [comment]
确实是我服务商的问题，打扰了
