### ISSUE TITLE
[Request] 

### ISSUE THREAD

**Issue by Microcarft** [lobehub/lobe-chat#2578]
### 🥰 需求描述

目前LobeChat的SSO功能已经很不错，但我希望能增加一项较为小众的需求就是基于Synology NAS的SSO应用登录。或者说，可以给出一套公有化SSO模板，用户可以自定义配置为Synology SSO或者其他SSO功能。

### 🧐 解决方案

我更喜欢有一套面向大部分SSO的模板，这样用户可以自定义配置想要的SSO服务

**Comment by arvinxx** [comment]
现在是基于 Next-auth 做的 SSO ，理论上只要 next-auth 支持的 provider ，我们都能比较容易地接入：

<img width="315" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/74cec5df-527a-4e6b-8c62-c947ac8c875b">

另外得益于 @cy948 的优秀工作，我们也有了完善的接入指南：https://github.com/lobehub/lobe-chat/wiki/Add-New-Authentication-Providers.zh-CN 。你可以看下是否能满足你的接入诉求？

**Comment by KnightNFS** [comment]
I think its very useful for Self-Hosting . It will be great to add as additional SSO provider in feature releases.

**Comment by cy948** [comment]
可以创建自定义 Authjs SSO Provider  https://authjs.dev/guides/configuring-oauth-providers#use-your-own-provider 再进行接入。

**Comment by Microcarft** [comment]
感谢！我想我已经知道如何去尝试了。不过我自己对 Authjs SSO 并没有了解，或许我应该去学习了。再次感谢您的解答！

**Comment by KnightNFS** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> You can create a custom Authjs SSO Provider https://authjs.dev/guides/configuring-oauth-providers#use-your-own-provider and then access it.

Could you please make a short explain guide . 
1. to which folder need to place {provider_name.ts} file ? ( As i understand under "sso-providers" subfolder)
2. Do i need add a some specific code lines into  {provider_name.ts} to match the logic of your Code and the system has determined the provider? 
3. What Envelopment Variable we can use for specific "issuer" URL 

Thank you.
