### ISSUE TITLE
[Bug] 除聊天以外的所有窗口均无法正常打开

### ISSUE THREAD

**Issue by yutu233** [lobehub/lobe-chat#2582]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Edge

### 🐛 问题描述

点击设置或其他跳转页面的选项时弹出此窗口
![屏幕截图 2024-05-21 123525](https://github.com/lobehub/lobe-chat/assets/143586420/ca3fa682-dbbc-4c7c-b801-a1a5164c670f)

**Comment by arvinxx** [comment]
你本地连接有打开么？
