### ISSUE TITLE
[Request] 能否增加一个类似子账号的功能

### ISSUE THREAD

**Issue by chuan1127** [lobehub/lobe-chat#2601]
### 🥰 需求描述

由于目前只有一个管理员密码，如果这个密码给其它人员使用，会有一些担心，

### 🧐 解决方案

使用管理员密码，分发二级密码，对不同的人员进行不同的设置，或者说增加注册系统，管理员能管理注册的这些账号.

**Comment by arvinxx** [comment]
现在已经支持 Auth 了，请查阅文档
