### ISSUE TITLE
[Request] 能不能把随便聊聊的话题移动到列表当中

### ISSUE THREAD

**Issue by iamsad3508** [lobehub/lobe-chat#2603]
### 🥰 需求描述

有时在随便聊聊里面聊得比较多的时候，就可想新建一个分组来专门存放它，但又没有找到这个功能

### 🧐 解决方案

在随便聊聊的话题增加一个移动到分组的功能，谢谢各位作者

**Comment by arvinxx** [comment]
duplicate of https://github.com/lobehub/lobe-chat/issues/2583
