### ISSUE TITLE
[Bug] GPT-4o联网功能没了

### ISSUE THREAD

**Issue by xzqiaochu** [lobehub/lobe-chat#2606]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

5月15号的时候，我意外的发现GPT-4o具备了联网功能（当时lobe-chat还未添加gpt-4o模型，是我手动添加的）
我当时的提问是”搜一下胖猫事件并概括“，gpt-4o首先产生了这样的输出
> search("胖猫事件 2024")
mclick(["0", "1", "4", "6", "8"])
end-searching

然后准确的回答了这个问题，并附上了诸多链接

![image](https://github.com/lobehub/lobe-chat/assets/41484968/16067c38-16ee-4ad2-8b4d-6304ddd0134f)

我并没有开启任何插件，这一点截图左上角可以证明。如果开启了插件是会显示的

今天（5月22）我更新了lobe-chat项目后，发现官方已经支持了gpt-4o模型。我进行了尝试，但发现联网功能已经不可用了

![image](https://github.com/lobehub/lobe-chat/assets/41484968/62f8125d-ef53-4dbb-9dcf-c563be7e410e)

我不清楚这个联网功能是OpenAI提供的，还是lobe-chat提供的。我在搜索引擎查询了“gpt-4o取消联网功能”，并未发现相关新闻。

**Comment by xzqiaochu** [comment]
补充：GPT-4o返回的搜索结果包括维基百科的内容，我当时的电脑网络环境可以访问维基百科，服务器环境不能访问维基百科

附上5月15日GPT-4o的完整回复：

> search("胖猫事件 2024")
> mclick(["0", "1", "4", "6", "8"])
> **end-searching**

**胖猫事件**是2024年发生在重庆的一个引发广泛关注的悲剧。事件的主要人物是网名为“胖猫”的21岁男孩，他因与网恋女友谭竹的复杂关系最终选择跳江自杀。

**事件背景**：
胖猫与谭竹通过网络游戏《王者荣耀》相识并发展为情侣关系。在两年的交往过程中，胖猫为谭竹花费了约51万元人民币。然而，在2024年4月初，谭竹提出分手，胖猫在极力挽回无果后，将身上仅剩的6.66万元转给谭竹，并于4月11日跳江自杀【[胖猫跳江事件 - 维基百科，自由的百科全书](https://zh.wikipedia.org/zh-hans/%E8%83%96%E7%8C%AB%E8%B7%B3%E6%B1%9F%E4%BA%8B%E4%BB%B6#:~:text=4%E6%9C%88%E5%88%9D%EF%BC%8C%E8%B0%AD%E7%AB%B9%E5%8F%88%E6%8F%90%E5%87%BA%E4%BA%86%E5%92%8C%E8%83%96%E7%8C%AB%E5%88%86%E6%89%8B%EF%BC%8C%E8%80%8C%E8%83%96%E7%8C%AB%E5%88%99%E6%98%AF%E6%9E%81%E5%8A%9B%E6%8C%BD%E5%9B%9E%E3%80%82%E8%83%96%E7%8C%AB%E8%BA%AB%E4%B8%8A%E4%BB%85%E5%89%A9%E7%9A%846.66%E4%B8%87%E5%85%83%E4%BA%BA%E6%B0%91%E5%B8%81%E5%A4%87%E6%B3%A8%E2%80%9C%E8%87%AA%E6%84%BF%E8%B5%A0%E4%BA%88%E2%80%9D%E8%BD%AC%E7%BB%99%E8%B0%AD%E7%AB%B9%E5%90%8E%E5%9C%A8%E3%80%9062%E2%80%A0%E9%87%8D%E5%BA%86%E9%95%BF%E6%B1%9F%E5%A4%A7%E6%A1%A5%E3%80%91%E8%B7%B3%E4%B8%8B%5B3%5D%E3%80%82%E4%BA%8B%E5%90%8E%E8%B0%AD%E7%AB%B9%E4%B8%8E%E8%83%96%E7%8C%AB%E7%88%B6%E4%BA%B2%E4%BB%A5%E8%B5%94%E5%81%BF13%E4%B8%87%E5%85%83%E8%BE%BE%E6%88%90%E5%92%8C%E8%A7%A3%EF%BC%8C%E8%80%8C%E8%83%96%E7%8C%AB%E7%9A%84%E5%A7%90%E5%A7%90%E5%9C%A8%E8%AE%A1%E7%AE%97%E5%90%8E%E5%8F%91%E7%8E%B0%E4%B8%A4%E4%BA%BA%E7%9A%84%E8%BD%AC%E8%B4%A6%E4%B8%80%E5%85%B1%E6%9C%8951%E4%B8%87%E5%85%83%EF%BC%8C%E5%9B%A0%E6%AD%A4%E5%8F%91%E5%B8%83%E8%A7%86%E9%A2%91%E5%88%B0%E7%BD%91%E7%BB%9C%E8%80%8C%E8%A2%AB%E4%B8%96%E4%BA%BA%E7%86%9F%E7%9F%A5%E3%80%82%E8%83%96%E7%8C%AB%E5%B0%B8%E4%BD%93%E5%B7%B2%E4%BA%8E5%E6%9C%883%E6%97%A5%E7%81%AB%E5%8C%96%E3%80%82%20%0A%0A5%E6%9C%889%E6%97%A5%EF%BC%8C%E6%B3%B8%E5%B7%9E%E7%BD%91%E8%AD%A6%E6%8C%87%E6%8E%A7%E6%B3%B8%E5%B7%9E%E7%BD%91%E6%B0%91%E8%AE%B8%E6%9F%90%E4%B8%BA%E5%8D%9A%E5%8F%96%E7%9C%BC%E7%90%83%E5%90%B8%E5%BC%95%E6%B5%81%E9%87%8F%EF%BC%8C%E9%80%9A%E8%BF%87%E5%BE%AE%E5%8D%9A%E8%B4%A6%E5%8F%B7%E2%80%9C%40%E8%B0%AD%E7%AB%B9%E5%A4%8F%E6%97%A5%E7%82%8E%E7%82%8E%E2%80%9D%E5%86%92%E5%85%85%E2%80%9C%E8%83%96%E7%8C%AB%E2%80%9D%E4%BA%8B%E4%BB%B6%E5%BD%93%E4%BA%8B%E4%BA%BA%EF%BC%8C%E5%8F%91%E5%B8%832021%E5%B9%B411%E6%9C%88%E8%87%B32024%E5%B9%B44%E6%9C%88%E4%B8%8E%E2%80%9C%E8%83%96%E7%8C%AB%E2%80%9D%E4%B9%8B%E9%97%B4%E7%9A%84%E8%B5%84%E9%87%91%E5%BE%80%E6%9D%A5%E3%80%81%E8%81%8A%E5%A4%A9%E8%AE%B0%E5%BD%95%E7%AD%89%E8%B4%B4%E6%96%87%E3%80%82%E6%B3%B8%E5%B7%9E%E7%BD%91%E8%AD%A6%E8%A1%A8%E7%A4%BA%E8%BF%99%E4%BA%9B%E8%B4%B4%E6%96%87%E5%9D%87%E4%B8%BA%E8%99%9A%E6%9E%84%EF%BC%8C%E5%B9%B6%E4%B8%94%E5%B7%B2%E8%A1%8C%E6%94%BF%E5%A4%84%E7%BD%9A%E8%AE%B8%E6%9F%90%EF%BC%8C%E7%9B%B8%E5%85%B3%E8%B4%A6%E5%8F%B7%E5%B7%B2%E6%B3%A8%E9%94%80%5B4%5D%E3%80%82%20%0A%0A,%E8%AE%B8%E7%A5%BA%E5%AE%89.%20%E3%80%9088%E2%80%A0%E8%83%96%E8%B2%93%E4%BA%8B%E4%BB%B6%E2%94%8221%E6%AD%B2%E6%B7%B1%E6%83%85%E7%94%B72%E5%B9%B4%E7%B5%A6%E5%A5%B3%E5%8F%8B51%E8%90%AC%20%E5%88%86%E6%89%8B%E5%BE%8C%E8%B7%B3%E6%B1%9F%E8%87%AA%E6%AE%BA%E2%80%A0web.archive.org%E3%80%91)】【[重庆21岁男主播胖猫跳江事件：聊天记录52页PDF曝光（附原视频完整版）两年花51w换不来真心|同居|清晨|分手|pdf|重庆市_网易订阅](https://www.163.com/dy/article/J197977005459BTA.html)】。

**社会反应**：
事件曝光后，引发了大量网友的同情和愤怒。许多网友通过外卖平台为胖猫点餐纪念，导致重庆长江大桥上堆满了鲜花和食品。然而，一些餐饮商家被曝出送出了空包外卖或注水奶茶，激起了更多的公众愤怒【[祭奠“胖猫”的外卖出现空包或注水，五家餐饮连锁品牌致歉_新闻频道_央视网(cctv.com)](https://news.cctv.com/2024/05/04/ARTInEQmFzGQwEDbIzJrYwGL240504.shtml#:~:text=%E2%80%9C%E5%AF%B9%E6%AD%A4%E8%A1%8C%E4%B8%BA%EF%BC%8C%E6%88%91%E4%BB%AC%E6%84%9F%E5%88%B0%E6%97%A0%E6%AF%94%E9%9C%87%E6%83%8A%E5%92%8C%E6%B0%94%E6%84%A4%E3%80%82%E2%80%9D%E8%8C%B6%E7%99%BE%E9%81%93%E8%A1%A8%E7%A4%BA%EF%BC%8C%E5%B7%B2%E8%A6%81%E6%B1%82%E9%97%A8%E5%BA%97%E5%BC%80%E9%99%A4%E6%B6%89%E4%BA%8B%E5%91%98%E5%B7%A5%EF%BC%8C%E6%89%A3%E9%99%A4%E9%97%A8%E5%BA%97%E4%BF%9D%E8%AF%81%E9%87%91%E5%B9%B6%E4%B8%8E%E5%85%B6%E8%A7%A3%E7%BA%A6%EF%BC%9B%E6%89%80%E6%B6%89%E8%AE%A2%E5%8D%95%E5%85%A8%E9%83%A8%E9%80%80%E6%AC%BE%E3%80%81%E9%80%90%E4%B8%80%E8%87%B4%E6%AD%89%EF%BC%8C%E5%B9%B6%E7%BB%99%E4%BA%88%E6%AF%8F%E7%AC%94%E8%AE%A2%E5%8D%95%E9%87%91%E9%A2%9D10%E5%80%8D%E7%9A%84%E7%8E%B0%E9%87%91%E8%A1%A5%E5%81%BF%E3%80%82%0A%0A%E8%8C%B6%E7%99%BE%E9%81%93%E8%BF%98%E8%A1%A8%E7%A4%BA%EF%BC%8C%E4%BB%A5%E2%80%9C%E8%83%96%E7%8C%AB%E2%80%9D%E4%B9%8B%E5%90%8D%E5%90%91%E5%9B%9B%E5%B7%9D%E7%9C%81%E9%9D%92%E5%B0%91%E5%B9%B4%E5%8F%91%E5%B1%95%E5%9F%BA%E9%87%91%E4%BC%9A%E2%80%9C%E8%8C%B6%E7%99%BE%E9%81%93%E7%88%B1%E5%BF%83%E5%9F%BA%E9%87%91%E2%80%9D%E8%BF%BD%E5%8A%A0%E6%8D%90%E6%AC%BE100%E4%B8%87%E5%85%83%EF%BC%8C%E7%94%A8%E4%BA%8E%E5%85%B3%E7%88%B1%E9%9D%92%E5%B0%91%E5%B9%B4%E7%B1%BB%E5%85%AC%E7%9B%8A%E9%A1%B9%E7%9B%AE%E3%80%82%E5%8F%91%E5%B8%83%E8%AF%A5%E5%A3%B0%E6%98%8E%E6%95%B0%E5%B0%8F%E6%97%B6%E5%90%8E%EF%BC%8C%E8%8C%B6%E7%99%BE%E9%81%93%E5%85%AC%E5%B8%83%E4%BA%86%E6%8D%90%E6%AC%BE100%E4%B8%87%E5%85%83%E7%9A%84%E9%93%B6%E8%A1%8C%E5%9B%9E%E6%89%A7%E3%80%82%0A%0A%E2%80%9C%E6%84%BF%E9%80%9D%E8%80%85%E5%AE%89%E6%81%AF%E3%80%82%E2%80%9D5%E6%9C%883%E6%97%A5%EF%BC%8C%E8%9C%9C%E9%9B%AA%E5%86%B0%E5%9F%8E%E5%9C%A8%E5%BE%AE%E5%8D%9A%E5%8F%91%E6%96%87%E7%A7%B0%EF%BC%8C%E4%BA%86%E8%A7%A3%E5%88%B0%E7%9B%B8%E5%85%B3%E6%83%85%E5%86%B5%E5%90%8E%EF%BC%8C%E5%B8%82%E5%9C%BA%E7%BB%8F%E7%90%86%E5%AF%B9%E6%B6%89%E4%BA%8B%E8%AE%A2%E5%8D%95%E8%BF%9B%E8%A1%8C%E9%80%90%E4%B8%80%E6%A0%B8%E5%AE%9E%EF%BC%8C%E7%BB%8F%E8%BF%87%E7%8E%B0%E5%9C%BA%E8%AF%A2%E9%97%AE%E5%8F%8A%E7%9B%91%E6%8E%A7%E8%B0%83%E5%8F%96%EF%BC%8C%E2%80%9C%E5%8F%91%E7%8E%B0%E6%9C%89%E4%B8%AA%E5%88%AB%E9%97%A8%E5%BA%97%E5%AD%98%E5%9C%A8%E4%B8%8D%E6%8C%89%E6%A0%87%E5%87%86%E5%87%BA%E9%A4%90%E7%9A%84%E6%83%85%E5%86%B5%E2%80%9D%E3%80%82%0A%0A%E2%80%9C%E6%88%91%E4%BB%AC%E5%B7%B2%E8%A6%81%E6%B1%82%E5%BD%93%E4%BA%8B%E9%97%A8%E5%BA%97%E9%97%AD%E5%BA%97%E6%95%B4%E6%94%B9%EF%BC%8C%E8%81%94%E7%B3%BB%E7%82%B9%E9%A4%90%E4%BA%BA%E9%81%93%E6%AD%89%EF%BC%8C%E5%B9%B6%E4%BA%88%E4%BB%A510%E5%80%8D%E8%AE%A2%E5%8D%95%E9%87%91%E9%A2%9D%E7%9A%84%E8%B5%94%E5%81%BF%E3%80%82%E2%80%9D%E8%9C%9C%E9%9B%AA%E5%86%B0%E5%9F%8E%E8%A1%A8%E7%A4%BA%EF%BC%8C%E4%BC%9A%E4%BB%A5%E6%AD%A4%E4%B8%BA%E6%88%92%EF%BC%8C%E5%9D%9A%E5%86%B3%E6%9D%9C%E7%BB%9D%E6%AD%A4%E7%B1%BB%E4%BA%8B%E4%BB%B6%E5%86%8D%E6%AC%A1%E5%8F%91%E7%94%9F%E3%80%82%0A%0A%E5%93%81%E7%89%8C%E5%95%86%E8%87%B4%E6%AD%89%EF%BC%8C%E8%AF%84%E8%AE%BA%E6%96%87%E7%AB%A0%E7%A7%B0%E2%80%9C%E6%9C%8D%E5%8A%A1%E4%B8%8D%E7%9C%9F%E8%AF%9A%E5%8F%8D%E5%99%AC%E8%87%AA%E5%B7%B1%E2%80%9D%0A%0A%E4%BA%8B%E5%8F%91%E5%90%8E%EF%BC%8C%E6%B6%89%E4%BA%8B%E7%9A%84%E9%A4%90%E9%A5%AE%E5%93%81%E7%89%8C%E5%95%86%E6%9C%89%E7%9A%84%E5%8F%91%E5%B8%83%E2%80%9C%E5%A3%B0%E6%98%8E%E2%80%9D%EF%BC%8C%E6%9C%89%E7%9A%84%E7%9B%B4%E6%8E%A5%E2%80%9C%E8%87%B4%E6%AD%89%E2%80%9D%E3%80%82%0A%0A5%E6%9C%883%E6%97%A5%EF%BC%8C%E9%A4%90%E9%A5%AE%E5%93%81%E7%89%8C%E5%8D%8E%E8%8E%B1%E5%A3%AB%E5%9C%A8%E5%BE%AE%E5%8D%9A%E5%8F%91%E5%B8%83%E3%80%8A%E8%87%B4%E6%AD%89%E4%BF%A1%E3%80%8B%EF%BC%9A%E7%BB%8F%E4%BA%86%E8%A7%A3%EF%BC%8C2024%E5%B9%B45%E6%9C%883%E6%97%A5%E5%87%8C%E6%99%A80)】【[官方调查胖猫事件空包外卖，律师：商家或涉嫌诈骗，茶百道、蜜雪冰城等致歉 - 青岛新闻网](https://news.qingdaonews.com/zhongguo/2024-05/04/content_23566710.htm)】。

**商家反应和处理**：
涉事的多个餐饮品牌如茶百道、蜜雪冰城、华莱士等，随后发表声明道歉，承诺对所有空包订单全额退款并给予10倍赔偿。此外，茶百道还宣布以胖猫的名义向四川省青少年发展基金会捐款100万元，以示悼念和补救【7†source】【[胖猫事件后续：茶百道致歉赔偿，爱心捐款100万_新闻频道_中华网](https://news.china.com/socialgd/10000169/20240503/46461389_all.html)】。

**法律和舆论**：
该事件不仅在公众中引起强烈反响，也引发了法律界的关注。有律师指出，商家故意发送空包外卖的行为涉嫌诈骗，违反了《中华人民共和国消费者权益保护法》等法律规定，消费者有权要求赔偿【9†source】。

**总结**：
胖猫事件反映了网络恋情中的风险以及社会对弱势群体的关注。公众的同情心和愤怒推动了事件的持续发酵，同时也引发了对商家诚信和社会责任的深刻反思。希望这样的悲剧不再重演，也呼吁社会对类似事件中的受害者给予更多的关注和支持。Content is blocked

**Comment by xzqiaochu** [comment]
补充：根据one-api的日志，5月15日联网搜索成功的那次只发生了一次请求，也就是说联网搜索和补全是一次完成的

<img width="814" alt="image" src="https://github.com/lobehub/lobe-chat/assets/41484968/9de4e337-d1e2-453f-bc15-1420f29a6c5d">

**Comment by arvinxx** [comment]
大概率是你的服务商用了 ChatGPT 上的逆向 gpt-4o ，官方 API 应该是不支持搜索的。
