### ISSUE TITLE
[Bug] 最新版ollama又默认开出来了

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#2618]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/8185843/ed5f89dc-122b-4063-919b-6e1b2ad1150f)
能否直接隐藏掉，默认没有，或者哪里可以配置。

**Comment by arvinxx** [comment]
`ENABLED_OLLAMA=0`

**Comment by Jkkoi** [comment]
@arvinxx 请问这个环境变量的说明是否在文档中更新了，我没有在文档中找到相应的环境变量

**Comment by arvinxx** [comment]
@Jkkoi 还没加，近期会补上去

**Comment by RubuJam** [comment]
@Jkkoi 文档已经更新

Documentation has been updated
