### ISSUE TITLE
[Bug] 使用gpt-4o模型,结果滚屏时会报错response.undifined

### ISSUE THREAD

**Issue by zhaojie199512** [lobehub/lobe-chat#2622]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

docker部署，镜像是最新的版本，使用gpt-4o模型，结果滚屏时候会报错response.undifined，换成其他模型回复结果是正常显示的；使用另一个前端项目chat-next调用gpt-4o模型，回复结果也是正常的，

![image](https://github.com/lobehub/lobe-chat/assets/12878073/b6307b01-1afa-4da5-bed4-02037f39c8ef)
![image](https://github.com/lobehub/lobe-chat/assets/12878073/ad64894f-45b9-4edb-92ee-dd1dab93fdfc)

### 🚦 期望结果

回复结果完整显示

### 📷 复现步骤

问题：highcharts 鼠标选中一块区域放大，后点击重置按钮。这个过程中触发了highcharts的哪些事件，事件的入参定义是怎样
回答问题时会报错

**Comment by llanc** [comment]
I encountered the same problem. 
After answering, it automatically changes to 'response.undefined'
![image](https://github.com/lobehub/lobe-chat/assets/31590534/c8d40332-d618-401f-ad6b-f777f35c6b6e)

**Comment by swizardlv** [comment]
遇到同样问题 ， 在mac的safari下是正常的，但是 chrome 和 arc 都是 Response.undefined 
<img width="611" alt="image" src="https://github.com/lobehub/lobe-chat/assets/10117682/e740d76a-212b-463a-a95f-26a6bebc1804">

**Comment by deyinliwork** [comment]
尝试关闭语言模型处的“使用客户端请求模式”

**Comment by swizardlv** [comment]
> 尝试关闭语言模型处的“使用客户端请求模式”

请问lobe 在哪里设置这个？ 找了几遍都没发现

**Comment by radar1i** [comment]
> > 尝试关闭语言模型处的“使用客户端请求模式”
> 
> 请问lobe 在哪里设置这个？ 找了几遍都没发现

![image](https://github.com/lobehub/lobe-chat/assets/162831953/315c4d78-3e32-4e5c-b57a-c805c8d8b95e)

**Comment by junxian-li-hpc** [comment]
> > 尝试关闭语言模型处的“使用客户端请求模式”
> 
> 请问lobe 在哪里设置这个？ 找了几遍都没发现

![image](https://github.com/lobehub/lobe-chat/assets/45509716/690228f2-8485-4808-b1df-99af9d17d07b)

**Comment by junxian-li-hpc** [comment]
但是关闭这个选项之后，没有回复完，输出就停止了
![image](https://github.com/lobehub/lobe-chat/assets/45509716/26172319-2a7d-4877-81a2-9dae0255400d)

**Comment by Loongphy** [comment]
不会使用的是 burn.hair 吧，已经修了
https://github.com/lobehub/lobe-chat/pull/2782
