### ISSUE TITLE
[Request] 希望支持one-api 部署后的代理 目前无法使用

### ISSUE THREAD

**Issue by laike** [lobehub/lobe-chat#263]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

用https://github.com/songquanpeng/one-api 这个One-Api搭建的代理没法再Lobe-Chat使用，我自己拉了源码来看不知道什么原因造成的 我试了下不通过 /api/openai/chat进行请求是可以的 不知道是不是使用的npm库openai 这个库不兼容 麻烦大佬空了看下

### 🚦 期望结果 | Expected Behavior

希望支持One-Api 部署的代理

**Comment by arvinxx** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/28616219/a4a6b96a-374e-43ad-a5f6-0c9cf0ce7a5e)

部署的时候设置一下proxy url的环境变量？

**Comment by laike** [comment]
> ![image](https://user-images.githubusercontent.com/28616219/271812120-a4a6b96a-374e-43ad-a5f6-0c9cf0ce7a5e.png)
> 
> 部署的时候设置一下proxy url的环境变量？
> 
> https://github.com/lobehub/lobe-chat/blob/main/docs/Environment-Variable.zh-CN.md

回去试下看行不行

**Comment by leoleelxh** [comment]
配置可以，但是不能通过oneapi 选择模型。

**Comment by canisminor1990** [comment]
https://github.com/lobehub/lobe-chat/discussions/284

**Comment by 52eraja** [comment]
我现在用oneapi是正常可以使用  只是lobe没有更多可以选或自定义模型
