### ISSUE TITLE
[Request] 如何隐藏PWA

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#2632]
### 🥰 需求描述

我这不需要用到这个浏览器桌面扩展，在哪可以隐藏掉它
![image](https://github.com/lobehub/lobe-chat/assets/8185843/155a048c-9ad1-4522-92ee-3165e533eea6)

### 🧐 解决方案

隐藏安装PWA浏览器桌面扩展。

**Comment by arvinxx** [comment]
没有办法
