### ISSUE TITLE
[Bug] 调用插件会显示调用两个，是就这样设计的，还是bug？

### ISSUE THREAD

**Issue by songtanjichuan** [lobehub/lobe-chat#2635]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/7565822/19481d76-bb7c-4b7c-9bcf-6e75b8ec1797)
![image](https://github.com/lobehub/lobe-chat/assets/7565822/b5ae3c0e-ab8b-46cc-8d95-77dd5306058f)

### 🚦 期望结果

只调用一次，要是就这样设计的，那就没事了。

### 📷 复现步骤

1，显示一个插件：时钟时间，或者 实时天气
2.  输入北京时间或者北京天气

**Comment by arvinxx** [comment]
是这样设计的，因为现在 Tool Calling 的实现规范里需要这样：

```
role=assistant
tools:
   - name: realtimeWeather
      arguments: "{...}"

role=tool
content: "...."
```

必须要拆成两条才能正常运作。 弊端就是看上去会比较繁琐。但也有两个好处。

一是支持平行 tool Calling，你可以试试看同时问杭州和北京天气如何这样的问题。

二是，支持后置调用插件的消息（比如你说帮我，给我介绍下 BTC 是什么，并查询一下它的价格）

未来会准备做 Group Message ，来解决 UI 上两条消息看上去重复的问题。

**Comment by songtanjichuan** [comment]
> 是这样设计的，因为现在 Tool Calling 的实现规范里需要这样：
> 
> ```
> role=assistant
> tools:
>    - name: realtimeWeather
>       arguments: "{...}"
> 
> role=tool
> content: "...."
> ```
> 
> 必须要拆成两条才能正常运作。 弊端就是看上去会比较繁琐。但也有两个好处。
> 
> 一是支持平行 tool Calling，你可以试试看同时问杭州和北京天气如何这样的问题。
> 
> 二是，支持后置调用插件的消息（比如你说 给我介绍下 BTC 是什么，并查询一下它的价格）
> 
> 未来会准备做 Group Message ，来解决 UI 上两条消息看上去重复的问题。

好的，感谢回复
