### ISSUE TITLE
[Request] 建议提供自定义选项自定义显示每个会话摘要的模型

### ISSUE THREAD

**Issue by redapple0204** [lobehub/lobe-chat#2636]
### 🥰 需求描述

目前显示每个会话摘要（如图）请求使用的模型默认为gpt-3.5-turbo，建议提供选项给用户选择自定义模型来获取摘要
![image](https://github.com/lobehub/lobe-chat/assets/16254644/7bd4a47e-8107-4292-9216-728e141f5add)

### 🧐 解决方案

提供选项给用户选择自定义模型来获取摘要

**Comment by arvinxx** [comment]
在这里支持： https://github.com/lobehub/lobe-chat/discussions/2600

**Comment by arvinxx** [comment]
已支持 https://github.com/lobehub/lobe-chat/pull/2683
