### ISSUE TITLE
[Bug] 使用 GPT-4o 时无法渲染生成获取的照片

### ISSUE THREAD

**Issue by yangsa666** [lobehub/lobe-chat#2638]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

使用 GPT-4o 时无法渲染生成获取的照片
![image](https://github.com/lobehub/lobe-chat/assets/31430559/1955228f-3500-4369-9c5d-42c9aabda4e6)
![image](https://github.com/lobehub/lobe-chat/assets/31430559/e3e639ae-4b06-4507-9ad1-3064355e414d)

### 🚦 Expected Behavior

获取到生成的图片，并正确渲染。

### 📷 Recurrence Steps

 让 GPT 4o 生成图片。

**Comment by arvinxx** [comment]
这不是正常的么… 目前 gpt-4o 的 API 不支持直接生成图片，给你随机返回的图片链接就不一定是准确的。
