### ISSUE TITLE
望添加功能

### ISSUE THREAD

**Issue by wzsxyjs** [lobehub/lobe-chat#2649]
非常感谢作者给大家带来这么好的项目，为了能够在国人中应用更加广泛，希望添加直接接入到微信、微信公众号（或服务号）、企业微信、抖音、飞书等，这样就大大方便应用。

**Comment by RubuJam** [comment]
在上述平台上线难度很大，处于合规等多个问题，短期之内暂不考虑

It is challenging to utilise the above platforms online due to compliance issues. Therefore, we will not consider this option in the near future.

**Comment by arvinxx** [comment]
+1 合规因素是最大的挑战
