### ISSUE TITLE
[Bug] 安卓Chrome浏览器在设置页面无法完全滑动到最底部

### ISSUE THREAD

**Issue by leeyiding** [lobehub/lobe-chat#265]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Android13 
Chrome浏览器 115.0.5790.166 (正式版本) （64 位） 
lobe-chat 0.82.9
在设置页面滑动到最底部有一部分内容被遮挡
![S31006-00111497_com android chrome](https://github.com/lobehub/lobe-chat/assets/49098278/e5537a41-d75d-43b6-8587-4fecafc52843)

**Comment by leeyiding** [comment]
又测试了一下 Android的Edge浏览器也是这样的问题

**Comment by canisminor1990** [comment]
https://github.com/lobehub/lobe-chat/commit/68775b83763fed8e2e65053936e18a2f792775e0
