### ISSUE TITLE
latex公式显示

### ISSUE THREAD

**Issue by fomalhaut1998** [lobehub/lobe-chat#2651]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [X] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 软件版本

v0.161.16

### 💻 系统环境

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/53938635/295ee616-67e2-47c6-a716-c803438244f6)
如图公式没有正确显示。

### 📷 复现步骤

如图让其输出一个公式即可

### 🚦 期望结果

应该按照正确的方式渲染出latex公式

### 📝 补充信息

暂无

**Comment by sanbei011** [comment]
**I have a similar problem.**

**Comment by GSYCCN** [comment]
我想这应该是一个偶发问题，可能和大模型输出的公式格式不一定每一次都很标准有关。过去两周时间，以我的经验，大概有10%的概率触发无法正常显示，但大多数时候通过重新生成回答可以解决。我刚刚让gpt-4o生成了一个latex格式的公式给我，可以正常显示（桌面端/0.161.19）

**Comment by fomalhaut1998** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/53938635/95b29957-5d3f-4bea-a26a-e5eebd8264ec)
![image](https://github.com/lobehub/lobe-chat/assets/53938635/16ca70c1-47e2-40ff-bc92-949916d3ed73)
这是GPT-4o-2024-05-13和claude-3-opus-20240229生成的公式，通过重新生成也无法正确渲染，似乎从来都不能正确显示！
![image](https://github.com/lobehub/lobe-chat/assets/53938635/bf0126c8-a411-4833-871b-0de02413f392)
而Gemini-1.5-pro的公式则可以正确渲染，如果可以的话希望能够修复，感谢！

**Comment by GSYCCN** [comment]
看上去lobechat只会渲染$/$$包围的latex数学公式，虽然gpt-4o输出的那种写法也是正确的。渲染条件确实考虑得不是很全面。不是很清楚他们的渲染是怎么实现的。在更新之前，你可以用prompt的方式要求GPT，所有latex格式的数学式子都要用$/$$包围。

**Comment by fomalhaut1998** [comment]
感谢解答！

**Comment by tisfeng** [comment]
来个小伙伴支持一下数学公式吧，不然看着真太别扭了 🥺

## ChatGPT

<img width="1237" alt="image" src="https://github.com/lobehub/lobe-chat/assets/25194972/fc54ef63-5e15-44ca-87a8-bcc0f466e610">

## LobeChat
<img width="994" alt="image" src="https://github.com/lobehub/lobe-chat/assets/25194972/f348b13e-f65b-4b86-855e-2491d7f96caf">

**Comment by q351941406** [comment]
+1

**Comment by koolcandy** [comment]
+1

**Comment by tisfeng** [comment]
赞 👍

<img width="1002" alt="image" src="https://github.com/lobehub/lobe-chat/assets/25194972/7a8e5d76-a5e1-4810-b887-3db961261f90">
