### ISSUE TITLE
[Bug] Could not find "stylelint-config-recommended"

### ISSUE THREAD

**Issue by vual** [lobehub/lobe-chat#2652]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [ ] Docker
- [X] Other

### 📌 软件版本

0.161

### 💻 系统环境

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [ ] Chrome
- [X] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

改了代码，提交的时候报错
![image](https://github.com/lobehub/lobe-chat/assets/25891219/0f06b712-fb1e-4098-adcc-4177f68fea54)

**Comment by arvinxx** [comment]
你改了代码遇到这个报错只能自己解决了毕竟我们并不知道你到底还改了啥。建议试试根据报错的提示自行排查。看上去像是依赖没装对的问题

**Comment by RubuJam** [comment]
运行`npm run stylelint-config-recommended@13.0.0`应该可以解决你的问题

**Comment by vual** [comment]
> 你改了代码遇到这个报错只能自己解决了，毕竟我们并不知道你到底还改了啥，建议根据报错的提示自行排查。看上去像是依赖没装对的问题

主要是没改啥内容，就改了下语言文件的个别文字描述。

**Comment by arvinxx** [comment]
@vual 安装方式换成 pnpm 再试试。

**Comment by vual** [comment]
> @vual 安装方式换成 pnpm 再试试。

果然，用pnpm i就没问题了，一开始idea提示 npm install，就直接执行了

**Comment by arvinxx** [comment]
> idea提示 npm install，就直接执行了

idea 系列可以配置默认安装的包管理器的，可以配置成 pnpm
