### ISSUE TITLE
[Bug]  当我使用docker run安装之后，在portainer里面安装，并且使用watchtower自动更新，会导致无法重启，项目丢失 

### ISSUE THREAD

**Issue by chuan1127** [lobehub/lobe-chat#2653]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

portainer

### 💻 Operating System

- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [X] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [ ] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [X] Other

### 🐛 Bug Description

当我使用docker run安装之后，在portainer里面安装，并且使用watchtower自动更新，会导致无法重启，项目丢失

**Comment by arvinxx** [comment]
这个不属于项目的问题了。你得自己解决运维的问题
