### ISSUE TITLE
[Bug] 在设置页面刷新会导致所有设置项恢复默认值

### ISSUE THREAD

**Issue by leeyiding** [lobehub/lobe-chat#266]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

如题，设置页面进行刷新，导致设置恢复默认值

**Comment by arvinxx** [comment]
bug 来源：https://github.com/lobehub/lobe-chat/commit/89c56485448c3773b520ab1ccf488c5bd794cc0c#diff-844f38caccb54296268a3631ad387339b69d50fb9ab3da9741d98c47f212df63

修正PR：https://github.com/lobehub/lobe-chat/pull/268/files#diff-844f38caccb54296268a3631ad387339b69d50fb9ab3da9741d98c47f212df63
