### ISSUE TITLE
[Bug] Can't deploy on Vercel

### ISSUE THREAD

**Issue by cennne** [lobehub/lobe-chat#2662]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [X] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 Version

v0.161.19

### 💻 Operating System

- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [ ] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

<img width="776" alt="image" src="https://github.com/lobehub/lobe-chat/assets/34563979/7f192a4d-d172-4b88-993d-2cdc64113d1a">
When deploy, I got this error

**Comment by bug2327747158** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/122770406/16b3ebe5-aab7-48d6-b2ec-ad4a874d4807)
我也一样
