### ISSUE TITLE
[Request] 支持语音输入输出

### ISSUE THREAD

**Issue by dcityteg** [lobehub/lobe-chat#267]
### 🥰 需求描述 | Feature Description
您好，请问能否语音输入与输出呢？

### 🧐 解决方案 | Proposed Solution
语音识别+语音生成
开启功能后喊一声HEY LOBE（我没想好）就能自动唤醒
单独页面：按下语音输入按钮就自动回复（类似语音助手）
Page: Automatically reply when the voice input button is pressed (similar to a voice assistant).

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/discussions/367
