### ISSUE TITLE
[Request] 能否添加GPT-4o上传图片的功能

### ISSUE THREAD

**Issue by songyp0505** [lobehub/lobe-chat#2674]
### 🥰 需求描述

如题，4o已经出了好长时间了，好多软件都支持了上传图片给4o，希望能把这个功能添加上，或者是我方法不对？我的版本是[0.161.22](https://github.com/lobehub/lobe-chat/releases/tag/v0.161.22)

### 🧐 解决方案

添加gpt4o上传图片的功能

**Comment by arvinxx** [comment]
老早支持的

**Comment by songyp0505** [comment]
> 老早支持的

请问是需要怎么使用呢，我把模型换成4o，图片的按钮就灰了，而且4o也不显示token数，有点迷糊，每次升级完版本我都去看，每次都不行

**Comment by arvinxx** [comment]
> > 老早支持的
> 
> 
> 
> 请问是需要怎么使用呢，我把模型换成4o，图片的按钮就灰了，而且4o也不显示token数，有点迷糊，每次升级完版本我都去看，每次都不行

你是不是之前添加过自定义的gpt4o？试着删除下

**Comment by songyp0505** [comment]
> > > 老早支持的
> > 
> > 
> > 请问是需要怎么使用呢，我把模型换成4o，图片的按钮就灰了，而且4o也不显示token数，有点迷糊，每次升级完版本我都去看，每次都不行
> 
> 你是不是之前添加过自定义的gpt4o？试着删除下

感谢！！！！！！可以了！
