### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 349601929** [lobehub/lobe-chat#2684]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 软件版本

docker pull lobehub/lobe-chat

### 💻 系统环境

- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

 docker run -d -p 3210:3210 --restart=always \
  -e OPENAI_API_KEY=sk-XXX \
  -e OPENAI_PROXY_URL=XXX \
  -e ACCESS_CODE=123456 \
  --name lobe-chat \
  lobehub/lobe-chat

### 📷 复现步骤

登录 IP:3210  不需要密码就能登录  换了密码规则也一样

### 🚦 期望结果

为什么加了密码不生效？

### 📝 补充信息

登录 IP:3210  不需要密码就能登录使用  换了密码规则也一样

**Comment by arvinxx** [comment]
密码保护的是ai请求
