### ISSUE TITLE
[Bug] Mistral models not working in latest releases

### ISSUE THREAD

**Issue by bentwnghk** [lobehub/lobe-chat#2685]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [X] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

v0.162.0

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [X] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

Mistral models have stopped working since the last couple of LobeChat releases.

Performing a connectivity test in Settings results in error: 請求 Mistral AI 服務出錯，請根據以下信息排查或重試

> {
  "error": {
    "headers": {
      "access-control-allow-origin": "*",
      "connection": "keep-alive",
      "content-length": "232",
      "content-type": "application/json",
      "date": "Mon, 27 May 2024 11:23:47 GMT",
      "x-kong-proxy-latency": "28",
      "x-kong-request-id": "c4160231633ca201bfd34c6c6584aa32",
      "x-kong-upstream-latency": "24"
    },
    "stack": "Error: 422 status code (no body)\n    at (vc/edge/function:139:64761)\n    at (vc/edge/function:142:6415)\n    at (vc/edge/function:142:7364)\n    at (vc/edge/function:222:5925)\n    at (vc/edge/function:225:28090)\n    at (vc/edge/function:130:85865)\n    at (vc/edge/function:130:84080)\n    at (vc/edge/function:130:87161)\n    at (vc/edge/function:131:33514)\n    at (vc/edge/function:131:3796)",
    "status": 422
  },
  "endpoint": "https://api.mistral.ai/v1",
  "provider": "mistral"
}

### 📝 Additional Information

![螢幕擷取畫面 2024-05-27 192522](https://github.com/lobehub/lobe-chat/assets/101241940/9052a793-082c-4758-a54e-9c5c72fa9205)

**Comment by aanwark** [comment]
I am facing the same issue.

**Comment by mnismt** [comment]
Me too. Hope it can be fixed soon. Thank you guys for your hard work!

![CleanShot 2024-06-29 at 17 13 52@2x](https://github.com/lobehub/lobe-chat/assets/27861064/bb5421a1-8875-46c6-a709-7bff5ca6af68)

**Comment by liebig** [comment]
Unfortunately, the problem still exists. Is there any news here?
