### ISSUE TITLE
[Bug] 密码输入框中一次输入会键入两个字母

### ISSUE THREAD

**Issue by leeyiding** [lobehub/lobe-chat#270]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

聊天界面的密码输入框中，在Windows默认的微软拼音输入法中文模式下，输入一个字母会一次性键入两个相同的字母，另外测试搜狗拼音输入法的中文模式下无该问题

**Comment by arvinxx** [comment]
这怎么感觉是微软拼音输入法的问题呢？

**Comment by leeyiding** [comment]
看样子像是触发了两次input的onChange事件

[https://github.com/react-component/input-number/issues/276](https://github.com/react-component/input-number/issues/276)
[https://juejin.cn/post/7160633186144223240](https://juejin.cn/post/7160633186144223240)
