### ISSUE TITLE
[Bug] 从URL导入配置不生效

### ISSUE THREAD

**Issue by ZeroDeng01** [lobehub/lobe-chat#2702]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [X] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 Version

v0.162.8

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [X] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [x] Chrome
- [x] Edge
- [x] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

当我请求如下url的时候无法导入openai的配置信息，模型设置里面对应的url和key依然空值的
https://chat.******xx.com/?settings={%22languageModel%22:{%22openai%22:{%22apiKey%22:%22sk-j6M3aMDFBA*********8d2890E5D6E70f%22,%22endpoint%22:%22https://ai.*******ng.com/v1%22}}}

### 📷 Recurrence Steps

![image](https://github.com/lobehub/lobe-chat/assets/19732560/d8212223-bde3-46e6-93a2-09b19ddab129)

**Comment by arvinxx** [comment]
`languageModel` 改为 `keyVaults` ，`endpoint` 改为 `baseURL` 。前段时间重构过了，文档还没更新

**Comment by ZeroDeng01** [comment]
openai里面的`fetchOnClient`和`autoFetchModelLists`参数是失效了或者改名了吗？我在构造的json参数里面增加这两个配置参数后实际并没有生效！这两个参数如果取消了，希望能增加回来！THX~

**Comment by arvinxx** [comment]
@ZeroDeng01 这两个参数仍然在 languageModels 里。api key 和 baseURL 拆到 keyVaults 里去了

**Comment by ZeroDeng01** [comment]
> @ZeroDeng01 这两个参数仍然在 languageModels 里。api key 和 baseURL 拆到 keyVaults 里去了

THX~
