### ISSUE TITLE
[Bug] 信令服务器连接失败，将无法建立点对点通信频道，请检查网络后重试

### ISSUE THREAD

**Issue by Ray1735** [lobehub/lobe-chat#2704]
### 📦 Environment

- [ ] Official
- [X] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 Version

社区版用户

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [X] Firefox
- [ ] Other

### 🐛 Bug Description

火狐、谷歌和安卓手机的谷歌都登陆了相同的频道和密码，但都提示“信令服务器连接失败，将无法建立点对点通信频道，请检查网络后重试”。消息也没有同步

**Comment by arvinxx** [comment]
重试下

**Comment by StromKuo** [comment]
信令服务器连接失败，我这里又出了这个问题
