### ISSUE TITLE
[Bug] 安卓手机用谷歌登录频道后显示已同步，但是OPENAI密钥和聊天记录都没有从PC端同步进来

### ISSUE THREAD

**Issue by Ray1735** [lobehub/lobe-chat#2706]
### 📦 Environment

- [ ] Official
- [X] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 Version

社区

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [X] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [X] Firefox
- [ ] Other

### 🐛 Bug Description

安卓手机用谷歌登录频道后显示已同步，但是OPENAI密钥和聊天记录都没有从PC端同步进来

**Comment by arvinxx** [comment]
设置目前没有配置在同步中 #1725

**Comment by Ray1735** [comment]
可是和助手的聊天记录也没有同步到手机上，都等2天了。请问是什么原因呢

**Comment by Henry-Suen** [comment]
它这个同步是需要你电脑和手机同时在线才会同步。而且只同步助手和对话。 而且不支持苹果safari。目前来说局限性比较大。
我基本放弃使用了。还是用导入导出吧、

**Comment by arvinxx** [comment]
> 目前来说局限性比较大。

+1 , 倒是可以期待下 #2611 这个方案，感觉应该会比 WebRTC 的好一些。或者等我们正在做的服务端数据库。

**Comment by Ray1735** [comment]
> 它这个同步是需要你电脑和手机同时在线才会同步。而且只同步助手和对话。 而且不支持苹果safari。目前来说局限性比较大。 我基本放弃使用了。还是用导入导出吧、

感谢回复。但是我手机和电脑同时开着，也不同步。有点搞不懂。
