### ISSUE TITLE
[Bug] azure的模型之下，插件无法使用，不能回复消息

### ISSUE THREAD

**Issue by pptomtiger** [lobehub/lobe-chat#2707]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 软件版本

162.8

### 💻 系统环境

- [ ] Windows
- [ ] macOS
- [X] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

azure的模型之下，勾选任意一个插件，比如搜索，插件无法使用，聊天框无消息回复

### 📷 复现步骤

打开azure模型，对接好api，聊天，添加搜索插件，发消息，没有内容回复

### 🚦 期望结果

修复好

**Comment by TyroneXie** [comment]
同样遇到这个问题，换成OpenAI就可以，Azure的不行

**Comment by shog86** [comment]
<img width="699" alt="image" src="https://github.com/lobehub/lobe-chat/assets/19712631/c47787af-b034-4cd2-9bf8-d445020a493b">
同遇到这个问题，回复框一直这样

**Comment by shog86** [comment]
<img width="706" alt="image" src="https://github.com/lobehub/lobe-chat/assets/19712631/d18f652c-96c9-47b4-9eb0-d92f63ea46ef">
事实上不只是搜索插件没反应，创建表格插件也没反应

**Comment by shog86** [comment]
求看一下这个问题 @arvinxx

**Comment by arvinxx** [comment]
@shog86 我没 azure 账号，搞不了… 得谁借我一个才能看了

**Comment by shog86** [comment]
> @shog86 我没 azure 账号，搞不了… 得谁借我一个才能看了

怎么私信你，我给你部署个新的你测试一下

**Comment by arvinxx** [comment]
> > @shog86 我没 azure 账号，搞不了… 得谁借我一个才能看了
> 
> 怎么私信你，我给你部署个新的你测试一下

Discord 上加我？ arvinxu

**Comment by htdohk** [comment]
我也有相同的问题，如需Azure的4o部署来测试，我也可以提供
