### ISSUE TITLE
关于访问码和apikey进行一对一的映射

### ISSUE THREAD

**Issue by Chenm4** [lobehub/lobe-chat#2711]
### 🥰 需求描述

我可能有多个访问码，分发给多个朋友使用，我希望他们是有限额的使用，所以每个访问码都是单独的对应一个设置了余额的key。能否实现这个功能？

### 🧐 解决方案

例如在vercel中我访问密码有5个，用逗号隔开，key也有5个，跟访问密码一一对应。这是我想到的最简单的实现方法，亦或者单独的字典映射，例如在vercel的环境变量中：
OPENAI_API_KEY_first 对应 sk-xxxxxx
ACCESS_CODE_first  对应 OPENAI_API_KEY_first 
然后第二个：
OPENAI_API_KEY_second 对应 sk-xxxxxxxxxx
ACCESS_CODE_second  对应 OPENAI_API_KEY_second 
算是非常基础的一个后台管理了。哪怕哪一个访问密码不小心泄露也不至于损失很大。

**Comment by arvinxx** [comment]
这个不计划做。
