### ISSUE TITLE
[Bug] HTTP ERROR 502

### ISSUE THREAD

**Issue by cfwl1111** [lobehub/lobe-chat#2714]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 软件版本

v0.162.9

### 💻 系统环境

- [X] Windows
- [ ] macOS
- [X] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [X] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [X] Edge
- [ ] Safari
- [X] Firefox
- [ ] Other

### 🐛 问题描述

我有两台服务器一台香港的一台深圳的都通过 docker 部署了 lobe-chat，香港的打开后经常 502 异常，深圳的没有问题，请问有遇到类似问题的老哥吗，该如何解决呢（香港的这台服务器还跑有其他 web 服务是没有问题的，唯独lobe-chat出现这个情况）

<img width="1920" alt="企业微信截图_20240529172139" src="https://github.com/lobehub/lobe-chat/assets/45492444/91231dbe-8c99-4aac-8529-b8d27f7828bb">
<img width="1920" alt="企业微信截图_20240529172054" src="https://github.com/lobehub/lobe-chat/assets/45492444/6c9e7c0e-46c5-43e1-aab5-0d7376cee362">

**Comment by arvinxx** [comment]
502 是服务端错误，你得看下是不是哪些环境配错了之类的吧。

**Comment by cfwl1111** [comment]
> 502 是服务端错误，你得看下是不是哪些环境配错了之类的吧。

两个服务端的环境变量和版本是一致的，我配置两台一样的就是为了排除差异问题。按照目前的情况来看香港这个像是网络问题，但其它的服务又是正常，需要我提供什么来排查吗

**Comment by cfwl1111** [comment]
> @cfwl1111 看下 docker 日志？

麻烦你看下，日志和环境变量应该都没问题的。如果可以，我提供域名和访问密码发你测试下

![Screenshot_2024-05-30-01-01-08-61_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/lobehub/lobe-chat/assets/45492444/bc0caed5-da30-4623-89c4-a9bb3c13478b)

![Screenshot_2024-05-30-01-03-32-77_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/lobehub/lobe-chat/assets/45492444/d0c81083-46c4-4acc-a1a0-59f20800a283)

**Comment by arvinxx** [comment]
@cfwl1111 试下直接使用 IP访问，看看能否正常打开？ 正常需要排查一下是 nginx 的问题还是docker的问题

**Comment by cfwl1111** [comment]
> @cfwl1111试下直接使用IP访问，看看是否正常？ 正常需要排查一下是nginx的问题还是docker的问题

一星期前出现这问题的时候我发现请求太多首页很难加载完成，然后后面开始出现 502 错误我也以为是 WEB 反代服务器的问题，通过 IP 访问测试过，问题依旧，这个问题的症状在于客户端浏览器请求出现 502 错误或者 lobe-chat 自带的响应错误页面时反复刷新下时而正常时而不正常。（网页缓存清理过）

**Comment by AppleRiven** [comment]
我最近也是这个问题，美国的服务器，系统ubuntu22.04，部署在docker里。
裸连：浏览器能正常访问Lobe的端口；
开代理：浏览器访问Lobe端口提示502，但可以正常访问其他端口上的服务；此外，在cmd中可以正常curl remote ip:3210.

**Comment by AppleRiven** [comment]
我最近也是这个问题，美国的服务器，系统ubuntu22.04，部署在docker里。
裸连：浏览器能正常访问Lobe的端口；
开代理：浏览器访问Lobe端口提示502，但可以正常访问其他端口上的服务；此外，在cmd中可以正常curl remote ip:3210.

**Comment by cfwl1111** [comment]
按照楼上说的，要么是 lobe-chat 的网络请求过多导致客户端浏览器异常中断返回错误响应，要么是 lobe-chat 的部分资源无法通过服务端的网络请求。这要说是服务端网络问题吧但其它服务又正常，搞不懂搞不懂🥴

**Comment by cfwl1111** [comment]
@arvinxx 不知道是不是 lobe-chat 这边修改了啥，截止目前已恢复正常响应，缀更新今天推送的最新版后也是正常响应，后续再看看会不会复现吧

**Comment by arvinxx** [comment]
@cfwl1111 没有改啥哎

**Comment by cfwl1111** [comment]
> @cfwl1111 没有改啥哎

那先不关闭这个问题吧，看下后续还有没有其他人会有这个情况
