### ISSUE TITLE
[Bug] IOS端浏览器访问-“将当前会话保存为话题”不可用

### ISSUE THREAD

**Issue by Sun-drenched** [lobehub/lobe-chat#2717]
### 📦 Environment

- [ ] Official
- [X] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 Version

0.162.9

### 💻 Operating System

- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [X] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [X] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

如题，具体表现是，IOS下使用浏览器访问（请求移动端网页），聊天（临时会话）输入框右上方有“将当前会话保存为话题”按钮，但点击后提示的触发方法是MAC的快捷键。

https://github.com/lobehub/lobe-chat/assets/11055122/401d22a5-1b24-407b-8c70-1e22aa7b5263

**Comment by arvinxx** [comment]
你首先话题里要有东西吧… 以及如果有东西的情况下，再点一次呢？

**Comment by Sun-drenched** [comment]
> 你首先话题里要有东西吧… 以及如果有东西的情况下，再点一次呢？

嗯，点击按钮，话题内有对话就可以正常运作。描述有误，并不算一个bug，只是在ios端看见mac的快捷键提示比较奇怪。

**Comment by arvinxx** [comment]
我后续优化下，在 移动端把快捷键隐藏掉吧
