### ISSUE TITLE
[Bug] Vercel 部署一直报错

### ISSUE THREAD

**Issue by maoling1411** [lobehub/lobe-chat#2719]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [X] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 Version

。。。

### 💻 Operating System

- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [X] Other

### 🌐 Browser

- [ ] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [X] Other

### 🐛 Bug Description

Vercel 部署一直报错

**Comment by arvinxx** [comment]
给出下截图或者报错日志

**Comment by russellyi** [comment]
我也遇到了。
<img width="424" alt="image" src="https://github.com/lobehub/lobe-chat/assets/3949708/a4691c6d-7f58-4fac-a7cd-b91f65a87e79">

<img width="1236" alt="image" src="https://github.com/lobehub/lobe-chat/assets/3949708/2e72c311-3986-4d70-b46a-cac917551b49">

**Comment by arvinxx** [comment]
@russellyi 点一个redeploy试一下？

**Comment by SuogeeAI** [comment]
> @russellyi 点一个redeploy试一下？

redeploy 是可以成功构建的，我这个是筛选了构建失败的结果，最近两周的构建一般都是失败一次，成功一次。正常构建 6 分钟左右，失败的全部都是超过了 45 分钟。
