### ISSUE TITLE
[Bug] 市场索引请求失败

### ISSUE THREAD

**Issue by Dreamkaka** [lobehub/lobe-chat#272]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

请求市场的`index.json`时失败，打开控制台发现是请求的站点而不是索引的
<img width="724" alt="image" src="https://github.com/lobehub/lobe-chat/assets/97349507/a4576611-69ac-4169-aad0-1206fdfba1fd">

**Comment by arvinxx** [comment]
上一个重构 pr 的引入的 bug， 在 #273 修复
