### ISSUE TITLE
[Bug] 接入 Next Auth 之后，不登陆还是能发起对话

### ISSUE THREAD

**Issue by DrayChou** [lobehub/lobe-chat#2734]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [X] Other

### 📌 Version

latest

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [X] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

接入 Next-Auth 之后，登陆界面已经提示 登入注册
![image](https://github.com/lobehub/lobe-chat/assets/760245/83911887-4770-4606-95af-2eac5b787cdf)

按照我的理解和文档内容，应该是不登陆就不能使用了，但是测试发现点击 开始对话|马上开始 ，或者 直接访问到 /chat 之后就可以直接进行对话了。

这与设定不符。

**Comment by xingpingcn** [comment]
这个是因为你浏览器有缓存，loba现在还没有后端，拿的还是在你浏览器里面的cookie。
还是因为没有后端，即使你登录了之后，是不能限制用户的。也就是说，假如我只希望我的GitHub账户可以使用，而其他GitHub用户不可以，但现实是所有人都可以用。需要在auth函数哪里写死GitHub 邮箱，缺点就是每次更改都要rebuild

**Comment by DrayChou** [comment]
> 这个是因为你浏览器有缓存，loba现在还没有后端，拿的还是在你浏览器里面的cookie。 还是因为没有后端，即使你登录了之后，是不能限制用户的。也就是说，假如我只希望我的GitHub账户可以使用，而其他GitHub用户不可以，但现实是所有人都可以用。需要在auth函数哪里写死GitHub 邮箱才可以限制用户，缺点就是每次更改都要rebuild

你大概是没有自己尝试过。
我开启了 Next Auth 设定之后，直接对话就是可以对话的。这时候应该要求登陆之后再对话的。
而且我本身是开发人员，每次测试之前清理本地状态时必做的。

**Comment by newcworld** [comment]
一样，nextAuth配置后，没有登录拦截

**Comment by xingpingcn** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/117259690/6b0a741d-f2b5-43c1-8069-9a8e994bb649)
我不清楚你什么情况，这是我用最新版的情况。

**Comment by DrayChou** [comment]
> ![image](https://private-user-images.githubusercontent.com/117259690/338041731-6b0a741d-f2b5-43c1-8069-9a8e994bb649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjQ1MTgsIm5iZiI6MTcxODE2NDIxOCwicGF0aCI6Ii8xMTcyNTk2OTAvMzM4MDQxNzMxLTZiMGE3NDFkLWYyYjUtNDNjMS04MDY5LTlhOGU5OTRiYjY0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMzUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzg3NzI3NDg1YTY3YmIwMjMwN2QyNmZjNjM0NTNkYWEzMGEwOTdlMzU3NDNkOTJmMzFjOTdkNjA3ZjFmN2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NijQEMZ9PfumnwEn3vKwwXOzdQjW8Kp2khCeGz-g_IY) 我不清楚你什么情况，这是我用最新版的情况。 估计是docker版本的问题，我用的是vercel部署的

同时配置 auth 认证和 openai token 的 env 环境变量的情况下，再次确认了下确实是没有拦截。

**Comment by xingpingcn** [comment]
> 同时配置 auth 认证和 openai token 的 env 环境变量的情况下，再次确认了下确实是没有拦截。

密码有没有配置

**Comment by DrayChou** [comment]
> > 同时配置 auth 认证和 openai token 的 env 环境变量的情况下，再次确认了下确实是没有拦截。
> 
> 密码有没有配置

你说的密码是那个？ access code ？我都已经开启了 auth 认证，还要再开启 这个？

**Comment by xingpingcn** [comment]
> > > 同时配置 auth 认证和 openai token 的 env 环境变量的情况下，再次确认了下确实是没有拦截。
> > 
> > 
> > 密码有没有配置
> 
> 你说的密码是那个？ access code ？我都已经开启了 auth 认证，还要再开启 这个？

对啊

**Comment by DrayChou** [comment]
> > > > 同时配置 auth 认证和 openai token 的 env 环境变量的情况下，再次确认了下确实是没有拦截。
> > > 
> > > 
> > > 密码有没有配置
> > 
> > 
> > 你说的密码是那个？ access code ？我都已经开启了 auth 认证，还要再开启 这个？
> 
> 对啊

这个逻辑我不是很能理解。
所以我决定自己改源代码。

**Comment by xingpingcn** [comment]
> > > > > 同时配置 auth 认证和 openai token 的 env 环境变量的情况下，再次确认了下确实是没有拦截。
> > > > 
> > > > 
> > > > 密码有没有配置
> > > 
> > > 
> > > 你说的密码是那个？ access code ？我都已经开启了 auth 认证，还要再开启 这个？
> > 
> > 
> > 对啊
> 
> 这个逻辑我不是很能理解。 所以我决定自己改源代码。

你设一个很长的密码就不怕被爆破了。而且用auth就可以。

我觉得后端完善了之后，就好解决了

**Comment by arvinxx** [comment]
@cy948 帮忙看看这个case

**Comment by cy948** [comment]
@xingpingcn 是正解。https://lobehub.com/zh/docs/self-hosting/advanced/authentication#next-auth

**Comment by DrayChou** [comment]
那么，关闭这个 issue 吧。
