### ISSUE TITLE
[Bug] 云端同步功能一直连接失败，之前一直是好的。

### ISSUE THREAD

**Issue by f43310** [lobehub/lobe-chat#2738]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [X] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 软件版本

Version 0.162.11

### 💻 系统环境

- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [X] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

云端同步功能一直连接失败，之前一直是好的。

**Comment by wexender** [comment]
我也经常出现这个问题，请问可以配置连接自己的中继服务器吗？或者直接配置部署中央存储服务器。

**Comment by jackman815** [comment]
I have encountering same problem after update

**Comment by yufeiyohi** [comment]
I also have this sync issue, always show connection failed.
Can we create own signaling server?

**Comment by ShinChven** [comment]
After updating a few versions, this feature started working.

**Comment by arvinxx** [comment]
@ShinChven but I don't make any update of this feature 😅 maybe it's your network that start to support WebRTC ?

**Comment by arvinxx** [comment]
> I also have this sync issue, always show connection failed.
> Can we create own signaling server?

I will support it next week

**Comment by WyInnovate** [comment]
最近连接不上了
WebSocket connection to 'wss://y-webrtc-signaling.lobehub.com/' failed
