### ISSUE TITLE
[Request]  是否可以新增配合midjourney-proxy接入Midjourney或者是否有接入用户系统功能

### ISSUE THREAD

**Issue by laike** [lobehub/lobe-chat#274]
### 🥰 需求描述 | Feature Description

配合 https://github.com/novicezk/midjourney-proxy 加入md绘图功能
https://github.com/yangjian102621/chatgpt-plus
https://github.com/yangjian102621/chatgpt-plus-exts

### 🧐 解决方案 | Proposed Solution

https://github.com/novicezk/midjourney-proxy

**Comment by canisminor1990** [comment]
有点 hack 我们先看下稳定性

**Comment by arvinxx** [comment]
感觉接入mj，不如等一等接入 dalle 3

**Comment by i-iooi-i** [comment]
Midjourney 是有接口的，我们公司的企业微信就有接入Midjourney，直接在企业微信界面选择Midjourney机器人，输入 提示词，然后返回图像结果。

**Comment by arvinxx** [comment]
> Midjourney 是有接口的，我们公司的企业微信就有接入Midjourney，直接在企业微信界面选择Midjourney机器人，输入 提示词，然后返回图像结果。

这块有没有文档看下？

**Comment by i-iooi-i** [comment]
> > Midjourney 是有接口的，我们公司的企业微信就有接入Midjourney，直接在企业微信界面选择Midjourney机器人，输入 提示词，然后返回图像结果。
> 
> 这块有没有文档看下？

这个倒是没有了，毕竟我是个美术，不是开发。🥹🥹

**Comment by canisminor1990** [comment]
@arvinxx 可以试试插件实现，用上面 hack 点的方案，放插件里稳定性差点也无所谓

**Comment by arvinxx** [comment]
在 #408 中跟进

**Comment by arvinxx** [comment]
Midjourney 插件 1.0 已正式发布~  🥳 🥳

欢迎大家体验反馈~

https://github.com/lobehub/lobe-chat/discussions/408#discussioncomment-8170635
