### ISSUE TITLE
[Bug] plugins not working when using proxy.

### ISSUE THREAD

**Issue by getteq** [lobehub/lobe-chat#2751]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

latest

### 💻 Operating System

- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [X] Firefox
- [ ] Other

### 🐛 Bug Description

When using openai proxy, plugins does not work

### 📷 Recurrence Steps

using openai proxy services
plugins are not working
if tou dont use proxy, it works

### 🚦 Expected Behavior

when using openai proxy, plugins should work

### 📝 Additional Information

Actually last week, it works even i use openai proxy service

**Comment by arvinxx** [comment]
I think it's your proxy issue. Some proxy reverse the free chatGPT to API， which its 3.5 model can't use tool calling
