### ISSUE TITLE
DEFAULT_AGENT_CONFIG设置默认模型出错[Bug] 

### ISSUE THREAD

**Issue by lixizhenggmail** [lobehub/lobe-chat#2754]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

v0.162.13

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [X] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [X] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

DEFAULT_AGENT_CONFIG设置默认模型命令如下：
DEFAULT_AGENT_CONFIG=model=gemini-1.5-pro-latest
部署后，可以看到聊天页面默认显示gemini-1.5-pro-latest模型了，但是对话时却还是使用的openai的接口，导致返回错误。

**Comment by arvinxx** [comment]
还需要加 provider=google
