### ISSUE TITLE
how do I change the icon that says LobeHub at the top

### ISSUE THREAD

**Issue by Finsi19** [lobehub/lobe-chat#2755]
### 📦 Environment

- [X] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 Version

0.162.11

### 💻 Operating System

- [X] Windows
- [X] macOS
- [X] Ubuntu
- [X] Other Linux
- [X] iOS
- [X] Android
- [X] Other

### 🌐 Browser

- [X] Chrome
- [X] Edge
- [X] Safari
- [X] Firefox
- [X] Other

### 🐛 Bug Description

how do I change the icon that says LobeHub at the top

### 📷 Recurrence Steps

how do I change the icon that says LobeHub at the top

### 🚦 Expected Behavior

i want to change the icon LobeHu 

### 📝 Additional Information

icon at the top of web

**Comment by Finsi19** [comment]
> 👀 @Finsi19
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible. Please make sure you have given us as much context as possible. 非常感谢您提交 issue。我们会尽快调查此事，并尽快回复您。

**Comment by Finsi19** [comment]
when will you reply and let me know?

**Comment by Finsi19** [comment]
HOWWW TO CHANGE THE ICON

**Comment by arvinxx** [comment]
Please read source code and do it by yourself. We won't give an easy we to change it
