### ISSUE TITLE
[Request] 希望接入 Coze BOT 的API

### ISSUE THREAD

**Issue by binjoo** [lobehub/lobe-chat#2764]
### 🥰 需求描述

我看到最新的 COZE 是支持Bot API的，能否截图 Coze Bot API，从而实现在 LobeChat 中白嫖 gpt4o。

Coze API: https://www.coze.com/open

![image](https://github.com/lobehub/lobe-chat/assets/219092/5739364b-e2ab-4246-a94b-3ff3001caf62)

### 🧐 解决方案

接入Coze API

**Comment by arvinxx** [comment]
去这里提吧 https://github.com/lobehub/lobe-chat/discussions/1284
