### ISSUE TITLE
[Request] 可以支持上传word excel 或这txt嘛

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#2765]
### 🥰 需求描述

可以支持上传word excel 或这txt嘛

### 🧐 解决方案

可以支持上传word excel 或这txt嘛

### 📝 补充信息

可以支持上传word excel 或这txt嘛

**Comment by xenstar** [comment]
As far I know, they are working on this currently.

**Comment by oasis168** [comment]
希望上传图片功能这边，增加一个截图功能，这样就不需要专门用其他软件截图后再上传到客户端中

**Comment by sxjeru** [comment]
> 希望上传图片功能这边，增加一个截图功能，这样就不需要专门用其他软件截图后再上传到客户端中

win mac ubuntu 等常见系统应该都有自带的截图工具可用。
