### ISSUE TITLE
[Bug] Vercel Edge Function 偶尔未在指定区域执行

### ISSUE THREAD

**Issue by sxjeru** [lobehub/lobe-chat#2770]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [X] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 软件版本

latest

### 💻 系统环境

- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [ ] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

如图所示，偶尔会将 google 的请求通过地理位置最近的 hk 节点发送，而不是遵守 preferredRegion 。

https://github.com/lobehub/lobe-chat/blob/1d2bc0ddcea0b7816fd5c506f8f747c56ed7c8c4/src/app/api/chat/google/route.ts#L18

![image](https://github.com/lobehub/lobe-chat/assets/20513115/8ae307ae-0a9f-4104-b603-4c7b56c47f13)

### 📝 补充信息

目前考虑的可能解决方案是增加 preferredRegion 数量。

**Comment by arvinxx** [comment]
感觉你这个问题要提个工单给 vercel ？

**Comment by sxjeru** [comment]
Vercel 官方讨论追踪：https://github.com/orgs/vercel/discussions/7075

或许可以考虑再次尝试 #2149 ，这边添加 `hnd1` 后没出过问题了。
