### ISSUE TITLE
除了lobechat还有什么平台比较好的支持接入智普AI

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#2771]
### 🥰 需求描述

除了lobechat还有什么平台比较好的支持接入智普AI

### 🧐 解决方案

除了lobechat还有什么平台比较好的支持接入智普AI

### 📝 补充信息

除了lobechat还有什么平台比较好的支持接入智普AI

**Comment by arvinxx** [comment]
请不要再重复问同样的问题了，不然我要禁你了
