### ISSUE TITLE
[Request] Support Deployment to Zeabur as serverless via zbpack.json Configuration

### ISSUE THREAD

**Issue by AHA1GE** [lobehub/lobe-chat#2772]
### 🥰 Feature Description

Currently, Deploying to Zeabur requires a paid plan for official Docker support. To enhance flexibility and accessibility, it would be beneficial to add support for deploying to Zeabur using serverless functions. This can be achieved by adding a configuration file, `zbpack.json`, to the project.

### 🧐 Proposed Solution

Introduce a `zbpack.json` configuration file with the following content:
```json
{
  "serverless": true,
  "ignore_dockerfile": true
}
```
### 📝 Additional Information

- Allowing users to decide their deployment method can help them balance performance and cost based on their needs.
- Proper documentation should be included to guide users/devs about the zbpack.json and deployment to Zeabur.

**Comment by arvinxx** [comment]
PR Welcome~

**Comment by AHA1GE** [comment]
https://github.com/lobehub/lobe-chat/pull/2775

**Comment by AHA1GE** [comment]
https://github.com/lobehub/lobe-chat/pull/2787
