### ISSUE TITLE
[Request] Hope there is longer historical message

### ISSUE THREAD

**Issue by trytoworkmorehappy** [lobehub/lobe-chat#2777]
### 🥰 需求描述

30 is tooooooo for me

### 🧐 解决方案

I hope it can develop into 100

**Comment by arvinxx** [comment]
There is no limit by default

**Comment by trytoworkmorehappy** [comment]
> There is no limit by default

Sorry, there may have been a mistake in my expression. I hope that the historical context limit can be adjusted according to one's own needs, rather than the maximum being 30😥😥😥

**Comment by sxjeru** [comment]
Consider maintaining the slider range and increasing the maximum value of the input box.


https://github.com/lobehub/lobe-chat/blob/a5c3d6fc08b393eb966f0dd958bc27e0cb4cdc4d/src/features/ChatInput/ActionBar/History.tsx#L34
https://github.com/lobehub/lobe-ui/blob/master/src/SliderWithInput/index.tsx

**Comment by trytoworkmorehappy** [comment]
> Consider maintaining the slider range and increasing the maximum value of the input box.
> 
> https://github.com/lobehub/lobe-chat/blob/a5c3d6fc08b393eb966f0dd958bc27e0cb4cdc4d/src/features/ChatInput/ActionBar/History.tsx#L34
> 
> 
> https://github.com/lobehub/lobe-ui/blob/master/src/SliderWithInput/index.tsx

thanks！
