### ISSUE TITLE
[Bug] LLM说完一句话后，此句子会消失，进而显示response.undefined

### ISSUE THREAD

**Issue by GuoJiaxing1997** [lobehub/lobe-chat#2779]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

0.162.15

### 💻 Operating System

- [x] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

![6d04f32291115460c747dacbffbda51](https://github.com/lobehub/lobe-chat/assets/88412036/6f6fa222-56d7-4d79-a449-728aacf19050)
如图，Show Details内容为空
使用的是中转API提供商，但是在其他开源项目中未发现问题（如Chatbox），故推测不是APT的原因造成的

### 📷 Recurrence Steps

稳定复现

**Comment by arvinxx** [comment]
哪个中转商？

**Comment by GuoJiaxing1997** [comment]
https://burn.hair/ @arvinxx

**Comment by GuoJiaxing1997** [comment]
额……也有可能是中转商的原因，图中前两轮对话的中转商文字生成速度很慢，就没有出现这个情况
第三轮对话文字一下子就生成了，但是瞬间变成response.undefined
![image](https://github.com/lobehub/lobe-chat/assets/88412036/f12be27a-3752-41fd-b115-7aaad2e1d24f)
不过第三轮对话的那个中转商在chatbox中未出问题，有点奇怪

**Comment by arvinxx** [comment]
和 #2752 看起来是一个问题，根本原因是这个服务商没有完全按照标准的 openai 输出结构进行流式输出，导致在 LobeChat 中的流式解析出错。我先兼容下吧，但我建议最好是服务商本身要去做好标准化流式输出的规范，不然可能其他地方还会挂。

**Comment by GuoJiaxing1997** [comment]
好的谢谢大佬
