### ISSUE TITLE
[Request] 感觉目前项目 的性能有很大问题，几乎所有交互都存在卡顿，特别是手机上，都会都有0.几秒 的延迟 。

### ISSUE THREAD

**Issue by Jayden666z** [lobehub/lobe-chat#2781]
### 🥰 需求描述

感觉目前项目 的性能有很大问题，几乎所有交互都存在卡顿，特别是手机上，都会都有0.几秒 的延迟 。

### 🧐 解决方案

希望可以流畅交互

**Comment by arvinxx** [comment]
请给出下具体卡顿的地方？ 录个屏，我具体看下

**Comment by Jayden666z** [comment]
因为每次点击 都要与服务器交互 这个是 切换聊天列表的时候延迟，特别依赖网络情况，网络卡的时候要 好久，我觉得这个不合理呀。
![image](https://github.com/lobehub/lobe-chat/assets/37990999/5a4d00e9-be8b-4b98-ac3d-63aa7d4069de)

**Comment by finexss** [comment]
而且浏览器打开一次首页，需要加载10M以上的数据，耗费时间太长，有多个人一起用的话，服务器就太难了。
希望能精简一下。

**Comment by xingpingcn** [comment]
还有就是每次点击右上角设置都要卡一下

**Comment by Sun-drenched** [comment]
> 请给出下具体卡顿的地方？ 录个屏，我具体看下

我之前遇到过一个情况，就是在开启客户端请求模式、流式响应时，如果GPT返回的回答比较长（可能需要15-20s才能显示完毕），在回答输出期间，打开设置和设置中的操作过程是相当卡顿甚至于无响应的。一旦答案输出完毕就恢复正常。

**Comment by arvinxx** [comment]
> 而且浏览器打开一次首页，需要加载10M以上的数据，耗费时间太长，有多个人一起用的话，服务器就太难了。

这个不影响你使用的吧，现在首屏打开应该没什么瓶颈了才对。你想要所有页面响应快，肯定就要做预加载，浏览器会在空闲时候拉取静态资源。至于服务器负担不了，不应该是去加钱升配置么？我自己的机器跑着没啥问题。

> 还有就是每次点击右上角设置都要卡一下

能不能录个屏看下具体怎么卡，我自己点还挺很丝滑的啊？

**Comment by arvinxx** [comment]
> 我之前遇到过一个情况，就是在开启客户端请求模式、流式响应时，如果GPT返回的回答比较长（可能需要15-20s才能显示完毕），在回答输出期间，打开设置和设置中的操作过程是相当卡顿甚至于无响应的。一旦答案输出完毕就恢复正常。

最新版还有这个问题吗？我理解可能和这个是同一个问题： https://github.com/lobehub/lobe-chat/issues/2724#issuecomment-2138607651

**Comment by arvinxx** [comment]
@Jayden666z 可以试下，应该修好了

**Comment by Sun-drenched** [comment]
> > 我之前遇到过一个情况，就是在开启客户端请求模式、流式响应时，如果GPT返回的回答比较长（可能需要15-20s才能显示完毕），在回答输出期间，打开设置和设置中的操作过程是相当卡顿甚至于无响应的。一旦答案输出完毕就恢复正常。
> 
> 最新版还有这个问题吗？我理解可能和这个是同一个问题： [#2724 (comment)](https://github.com/lobehub/lobe-chat/issues/2724#issuecomment-2138607651)

有，并不是一个问题。
而且修正一下表述，没有开启客户端请求模式也会出现这个问题。在视频中，我复现了这个问题。在GPT输出回答之前，打开设置动作比较流畅（此Lobechat部署在国内服务器，不存在网络问题），一旦GPT开始输出回答，打开设置等界面上的操作异常卡顿，可以看到我连续点击设置很多次，直到回答输出完才弹出设置界面。
https://github.com/lobehub/lobe-chat/assets/11055122/4e145ff2-285a-443b-bf30-183f89622ffa

**Comment by arvinxx** [comment]
> 在GPT输出回答之前，打开设置动作比较流畅（此Lobechat部署在国内服务器，不存在网络问题），一旦GPT开始输出回答，打开设置等界面上的操作异常卡顿，可以看到我连续点击设置很多次，直到回答输出完才弹出设置界面。
https://github.com/lobehub/lobe-chat/assets/11055122/4e145ff2-285a-443b-bf30-183f89622ffa

@canisminor1990 看下这个问题，会不会是拦截路由的影响？

**Comment by arvinxx** [comment]
@Sun-drenched 可以单独开个 issue 跟进哈，不在这个 issue 下讨论了。

**Comment by Sun-drenched** [comment]
> 没有开启客户端请求模式也会出现这个问题。在视频中，我复现了这个问题。在GPT输出回答之前，打开设置动作比较流畅（此Lobechat部署在国内服务器，不存在网络问题），一旦GPT开始输出回答，打开设置等界面上的操作异常卡顿，可以看到我连续点击设置很多次，直到回答输出完才弹出设置界面。

#2823

**Comment by Sun-drenched** [comment]
> @Sun-drenched 可以单独开个 issue 跟进哈，不在这个 issue 下讨论了。

#2823
