### ISSUE TITLE
[Bug] api-key切换失效

### ISSUE THREAD

**Issue by Sun-drenched** [lobehub/lobe-chat#2784]
### 📦 Environment

- [X] Official
- [X] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 Version

0.162.17

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

（自部署），在服务端设置accesscode和默认apikey后，在客户端填入accesscode的情况下，如果在模型设置界面自行填入了另外的apikey，当清空自行填入的key后，无法切换到服务端默认key（显示apikey为空）。需要重置设置才能恢复使用服务端默认key。

**Comment by JARVISMindEngineer** [comment]
<img width="879" alt="image" src="https://github.com/lobehub/lobe-chat/assets/165481157/5ff787b5-3dff-459a-b993-8b98908e3707">

另外还有一个小问题；本地设置了OPENAI_PROXY_URL，
未登录的情况下，弹出输入自己的OpenApiKey界面，下边的代理地址默认写的是这个 `placeholder={'https://api.openai.com/v1'} `
但不管是重新设置还是保持默认，都无法覆盖掉 OPENAI_PROXY_URL；不知道是不是截图中的问题呢？读取和写入的KEY不同。

**Comment by JARVISMindEngineer** [comment]
<img width="572" alt="image" src="https://github.com/lobehub/lobe-chat/assets/165481157/68f5407d-ab49-4d7d-8293-d154b5d05066">

**Comment by arvinxx** [comment]
> <img width="879" alt="image" src="https://github.com/lobehub/lobe-chat/assets/165481157/5ff787b5-3dff-459a-b993-8b98908e3707">
> 
> 
> 
> 另外还有一个小问题；本地设置了OPENAI_PROXY_URL，
> 
> 未登录的情况下，弹出输入自己的OpenApiKey界面，下边的代理地址默认写的是这个 `placeholder={'https://api.openai.com/v1'} `
> 
> 但不管是重新设置还是保持默认，都无法覆盖掉 OPENAI_PROXY_URL；不知道是不是截图中的问题呢？读取和写入的KEY不同。

的确，应该是的，欢迎提个PR 来修复🥹
