### ISSUE TITLE
auzre 模型之下，插件用不了，不返回信息

### ISSUE THREAD

**Issue by pptomtiger** [lobehub/lobe-chat#2786]
auzre 模型之下，插件用不了，不返回信息，所有插件都不可用，都这样状态
<img width="1115" alt="bug" src="https://github.com/lobehub/lobe-chat/assets/128691534/f36e0d13-0385-41a0-80e0-22e7beffa7c5">
<img width="1099" alt="bug2" src="https://github.com/lobehub/lobe-chat/assets/128691534/b305eb34-9b3f-4f37-948e-73fcc5a6b3ac">

**Comment by kbautista3** [comment]
我试了搜索插件，确实不起作用

**Comment by shog86** [comment]
https://github.com/lobehub/lobe-chat/issues/2707
一样
