### ISSUE TITLE
[Bug] 之前走服务端发起请求为何现在更改为前端直接发起

### ISSUE THREAD

**Issue by cookieY** [lobehub/lobe-chat#2789]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 软件版本

v0.162.17

### 💻 系统环境

- [X] Windows
- [X] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [X] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [X] Edge
- [X] Safari
- [X] Firefox
- [ ] Other

### 🐛 问题描述

不知为何更改了 llm 请求模式从后端发起变更为前端发起，导致 self-host 部署无法使用 proxychains-ng 进行访问。

### 🚦 期望结果

希望请求经由后端进行访问

**Comment by arvinxx** [comment]
没有改默认的，你可以自行选择服务端还是前端。

原因的话可以看下以前的一些讨论：

- https://github.com/lobehub/lobe-chat/discussions/728
- https://github.com/lobehub/lobe-chat/issues/772
- https://github.com/lobehub/lobe-chat/discussions/1257

**Comment by cookieY** [comment]
感谢作者回复，我查看了环境变量以及FeatureFlags 没有找到相关客户端还是服务端模式切换的参数。文档中似乎也没有涉及。请问是在哪里更改切换？谢谢

**Comment by arvinxx** [comment]
默认就是服务端请求，如果你填写了自定义的apikey或者proxy url，就会显示切换请求的switch
