### ISSUE TITLE
[Request] 通过 URL search 参数配置模型服务服务商接口

### ISSUE THREAD

**Issue by ShinChven** [lobehub/lobe-chat#2790]
### 🥰 需求描述

希望通过 URL 跳转来集成 LobeChat，使用 search 参数来一键配置服务服务商接口。

请问 LobeChat 是否有这样的功能？
如果没有，是否能增加该功能？

### 🧐 解决方案

提供一个专门的配置路由，读取参数中的信息，自动配置模型服务商的接口。

**Comment by arvinxx** [comment]
查看文档：https://lobehub.com/zh/docs/self-hosting/advanced/settings-url-share
