### ISSUE TITLE
[Request] 如何可以通过url参数设置key

### ISSUE THREAD

**Issue by jinjianming** [lobehub/lobe-chat#2792]
### 🥰 需求描述

如何可以通过url参数设置key和api地址

### 🧐 解决方案

https://like.chatapi.asia/#/?settings={"key":"sk-xxx","url":"https://chat.chatapi.asia"}

**Comment by arvinxx** [comment]
提问前不先看文档的吗？ https://lobehub.com/zh/docs/self-hosting/advanced/settings-url-share
