### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by liugod** [lobehub/lobe-chat#2795]
### 📦 Environment

- [X] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 Version

0.162.17

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

内置插件dalle3报错429错误，说是api速率受限，信息如下
Error requesting OpenAI service. Please troubleshoot or retry based on the following information.
Show Details
json
{
  "error": {
    "headers": {
      "cache-control": "private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0",
      "connection": "keep-alive",
      "content-length": "16",
      "content-type": "text/plain; charset=UTF-8",
      "date": "Wed, 05 Jun 2024 10:12:45 GMT",
      "expires": "Thu, 01 Jan 1970 00:00:01 GMT",
      "referrer-policy": "same-origin",
      "retry-after": "54749",
      "set-cookie": "_cfuvid=L51NXj57IPgnXHADpjjUfRso1_Snc91_Zr09KBJ9HYc-1717582365250-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None",
      "x-frame-options": "SAMEORIGIN"
    },
    "stack": "Error: 429 error code: 1015\n    at (vc/edge/function:139:64790)\n    at (vc/edge/function:142:6412)\n    at (vc/edge/function:142:7358)\n    at (vc/edge/function:225:795)\n    at (vc/edge/function:225:27626)\n    at (vc/edge/function:130:85872)\n    at (vc/edge/function:130:84076)\n    at (vc/edge/function:130:87175)\n    at (vc/edge/function:131:33520)\n    at (vc/edge/function:131:3794)",
    "status": 429
  },
  "endpoint": "https://api.openai.com/v1",
  "provider": "openai"
}

### 📝 Additional Information

我搜了一下，这个dalle3是内置的，我的服务器在vercel上面，会不会是因为vercel的服务器的访问被算成一个了？

**Comment by arvinxx** [comment]
速率限制是你的apikey不支持，换一个支持更多并发的key试试

**Comment by liugod** [comment]
后来把接口改为自己的网关好像是解决了，会不会是因为lobechat部署在vercel上面，同样的机房访问量太多？

**Comment by liugod** [comment]
> 速率限制是你的apikey不支持，换一个支持更多并发的key试试

不是的，我这个并发很少，就一个人用，我的key是50张每分钟，还差很远。
