### ISSUE TITLE
[Bug] Gemini模型还是有问题，有些助手报错

### ISSUE THREAD

**Issue by finexss** [lobehub/lobe-chat#2796]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

0.162.13

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [X] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [X] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

使用电脑和手机，访问的同一个项目，使用docker部署，用Gemini的模型，官方的api，同一个时间，有的助手里可以正常使用，有的助手里报404错误，而且报错的助手对话一直报错，能正常使用的助手也一直正常，莫名其妙的。
![IMG_6490](https://github.com/lobehub/lobe-chat/assets/154498355/08287786-45de-474d-ac2c-cd11af62c8c4)
![IMG_6491](https://github.com/lobehub/lobe-chat/assets/154498355/4f7be252-80e2-43cd-82ed-d2942bf24bc6)
![IMG_6491](https://github.com/lobehub/lobe-chat/assets/154498355/53d4c070-fd72-481d-bff8-accb8171160d)

**Comment by arvinxx** [comment]
相关问题：#2537 ，应该是重复的
