### ISSUE TITLE
编译之后太大了

### ISSUE THREAD

**Issue by sunli1223** [lobehub/lobe-chat#2798]
### 🥰 需求描述

本来部署在阿里云的函数计算，现在已经无法直接部署了，因为压缩后超过500M的上限了。感觉里面有很多没有必要的资源。

### 🧐 解决方案

精简编译后的大小

**Comment by arvinxx** [comment]
你的打包姿势有问题吧？ 我用 docker 打出来才 100+M ，可以参考下

**Comment by arvinxx** [comment]
> 考不考虑把各个功能分开呢？
> 或者开个类似于条件编译的东西，不需要的东西就可以不部署？

没法分开，nextjs 并不支持。
