### ISSUE TITLE
How do I set up WebRTC-based syncronization?

### ISSUE THREAD

**Issue by betterthanever2** [lobehub/lobe-chat#2805]
### 📝 Question

I have recently set up self-hosted version of Lobe chat, and I can see the CloudSync section in the settings. But I can't find any documentation on this.

I'm new to WebRTC. From what I quickly googled, I understand that I need to set up a signalling server so that my peers could exchange their _handshaking data_?

**Comment by Sun-drenched** [comment]
The signaling server is currently maintained by the developer, you just need to set up a channel name and password

**Comment by betterthanever2** [comment]
Thanks! I got confused, because it didn't work right away. It magically started working the next morning. Might be related to the Internet issues we've been having here.

BTW, are there plans for persistent storage, db- or file-based?

**Comment by Sun-drenched** [comment]
WebRTC is really not very stable and is just a transitional solution. As for your comment about persistent storage, as far as I know, they are working on it.

**Comment by delfer** [comment]
Any updates?

**Comment by arvinxx** [comment]
We will add the env these days
