### ISSUE TITLE
[Question] 我怎么不是流式返回

### ISSUE THREAD

**Issue by ThisCook** [lobehub/lobe-chat#281]
### 🧐 问题描述 | Proposed Solution

得等整句话返回完了才显示出来，是我那儿没配置对吗？

**Comment by canisminor1990** [comment]
需要更多信息，比如提供下你当前的环境和复现方法

**Comment by s544838371** [comment]
目前我也是这样，部署在vercel上，只设置了两个环境变量，OPENAI_API_KEY和ACCESS_CODE，目前就是随便问你都会什么？这个问题，都不是流式返回，而且还很慢

**Comment by arvinxx** [comment]
> 目前我也是这样，最新版本部署在vercel上，只设置了两个环境变量，OPENAI_API_KEY和ACCESS_CODE，目前就是随便问：你都会什么？这个问题，都不是流式返回，而且还很慢

有没有试试其他的问题？

**Comment by s544838371** [comment]
> > 目前我也是这样，最新版本部署在vercel上，只设置了两个环境变量，OPENAI_API_KEY和ACCESS_CODE，目前就是随便问：你都会什么？这个问题，都不是流式返回，而且还很慢
> 
> 有没有试试其他的问题？
# 提问1
Q：你好
A：你好！有什么我可以帮助你的吗？
这个时候用时5秒，时间显示正常
# 提问2
Q：你能干什么？
A：作为 AI 助理，我可以帮助你完成以下任务：
1. 回答问题：我可以回答各种问题，包括常识问题、历史问题、科学问题等等。
2. 提供信息：我可以提供各种信息，包括新闻、天气、股票行情、体育比赛结果等等。
3. 日程管理：我可以帮助你管理日程安排，提醒你重要的会议、活动等。
4. 翻译：我可以提供多种语言之间的翻译服务。
5. 音乐播放：我可以根据你的喜好播放音乐。
6. 闹钟设置：我可以帮助你设置闹钟，确保你按时起床或完成其他任务。
7. 提醒事项：我可以帮助你设置提醒事项，提醒你完成重要任务。
8. 聊天互动：我可以与你进行简单的聊天互动，提供一些娱乐和休闲。
请注意，我是一名 AI 助理，虽然我可以提供很多帮助，但在某些情况下可能无法完全满足你的需求。如果你有任何问题或需要帮助，请随时告诉我。
用时16:39:48-16:40:50

**Comment by s544838371** [comment]
默认助手第一次提问的时候你的提问时间会变成AI的回复时间，按理说比如你提问是16:38:10秒，返回是16:38:40，目前是返回是16:38:40，提问也变成了16:38:40，第二次第三次就时间显示正常了

**Comment by canisminor1990** [comment]
你使用非自部署版本正常么？

**Comment by s544838371** [comment]
> 你使用非自部署版本正常么？

chat-preview.lobehub.com 是正常的，可以流式

**Comment by canisminor1990** [comment]
检查下自部署版本 fork 仓库是否自动同步失败了

**Comment by s544838371** [comment]
> 检查下自部署版本 fork 仓库是否自动同步失败了

11.09 AM的自动同步是成功的
