### ISSUE TITLE
[Request] 是否可用用OpenAI的file-search接口快速实现一个文档解析的功能出来？

### ISSUE THREAD

**Issue by zhaoying9105** [lobehub/lobe-chat#2811]
### 🥰 需求描述

如题

### 🧐 解决方案

如题

### 📝 补充信息

openai 接口文档：https://platform.openai.com/docs/assistants/tools/file-search/quickstart

**Comment by arvinxx** [comment]
不计划，这样和单个 provider 的耦合太重了，不是符合我们的长期发展思路
