### ISSUE TITLE
通义千问2.0

### ISSUE THREAD

**Issue by qzkingjz** [lobehub/lobe-chat#2812]
### 🥰 需求描述

能否增加阿里通义千问2.0模型

### 🧐 解决方案

模型中能否增加对通义千问2.0的支持

**Comment by xenstar** [comment]
I already added it with Openrouter. 

![image](https://github.com/lobehub/lobe-chat/assets/55502651/a1311fbb-a61a-4a0d-b6ce-56dcd2f66020)
