### ISSUE TITLE
[Request] 支持 siliconflow

### ISSUE THREAD

**Issue by devyujie** [lobehub/lobe-chat#2817]
### 🥰 需求描述

支持 [siliconflow](https://cloud.siliconflow.cn/)

### 🧐 解决方案

支持 siliconflow

**Comment by sxjeru** [comment]
相关申请：https://github.com/lobehub/lobe-chat/discussions/1284#discussioncomment-9701451

**Comment by arvinxx** [comment]
应该不计划
