### ISSUE TITLE
glm-4-9b-chat无法使用fc

### ISSUE THREAD

**Issue by gaye746560359** [lobehub/lobe-chat#2818]
![image](https://github.com/lobehub/lobe-chat/assets/3060035/0bc53364-68cd-4f1d-81b9-043941399670)

**Comment by arvinxx** [comment]
你这个不是 OpenAI 的么? 这么就是glm4 了

**Comment by xingpingcn** [comment]
> 你这个不是 OpenAI 的么? 这么就是glm4 了

估计用的oneapi

**Comment by gaye746560359** [comment]
> 你这个不是 OpenAI 的么? 这么就是glm4 了

是vllm的标准openai接口。不能直接调用模型吗？

**Comment by arvinxx** [comment]
> 是vllm的标准openai接口。

那你可能要看下vllm是否支持function calling 的能力
