### ISSUE TITLE
[Bug] 对markdown语法的处理办法存在bug，包括输入，展示，复制等

### ISSUE THREAD

**Issue by hlc1209** [lobehub/lobe-chat#2819]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 软件版本

0.162.20

### 💻 系统环境

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

当前的做法，默认开启markdown语法，其在显示和复制时的处理有非常大的bug
如果用户在输入框键入3*4（任何基本的数学式），那么聊天气泡中就会变成3 _4_。用户从聊天气泡中复制后的文字就会变成34

在对AI返回的文字的显示上也有bug，见https://github.com/lobehub/lobe-chat/issues/2819#issuecomment-2156223674

另外
默认对用户输入开启markdown语法并非最佳做法
对于广大群众，markdown闻所未闻。应默认多数用户不知道markdown语法（这是合理的假设，也是openai chatgpt网页端的默认行为）
不过鉴于修改的难度。可以先默认开启markdown语法，但是要把我上面说的显示和复制bug改掉。

### 🚦 期望结果

在这件事情上，作者可参考openai chatgpt网页端的默认行为。openai在这方面行为细节的处理是极为优秀的。照抄即可。
两个例子
https://github.com/lobehub/lobe-chat/issues/2819#issuecomment-2156222993
https://github.com/lobehub/lobe-chat/issues/2819#issuecomment-2156223674

**Comment by hlc1209** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/45445824/aa1b12d1-d395-4b96-8a75-8e1bbe19edc0)
给一个openai chatgpt网页端的处理方式，供参考。

**Comment by hlc1209** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/45445824/51a60246-50d1-456e-92d1-1bb26f8df63b)

![image](https://github.com/lobehub/lobe-chat/assets/45445824/d3c4a049-2d4e-402d-a23d-5df3c10757a6)

对比chatgpt网页端和lobechat

**Comment by hlc1209** [comment]
> 你图片里的显示应该是模型输出的问题，而不是渲染问题，你可以点击消息旁边的编辑看一下，他写的是 `*3*4*5*` 还是 `*3\*4\*5*`，前者说明是模型输出错误

确实是模型输出错误。

> 我的建议是，响应还是按markdown显示，提示可以给一个选项是否启用markdown渲染

这个建议我感觉很好

**Comment by arvinxx** [comment]
和 #2819 重复
