### ISSUE TITLE
[Bug] GPT输出回答时界面操作异常卡顿

### ISSUE THREAD

**Issue by Sun-drenched** [lobehub/lobe-chat#2823]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

0.162.20

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

开启流式响应时，如果GPT返回的回答比较长（可能需要15-20s才能显示完毕），在回答输出期间，打开设置和设置中的操作过程是相当卡顿甚至于无响应的。一旦答案输出完毕就恢复正常。
没有开启客户端请求模式也会出现这个问题。在视频中，我复现了这个问题。在GPT输出回答之前，打开设置动作比较流畅（此Lobechat部署在国内服务器，不存在网络问题），一旦GPT开始输出回答，打开设置等界面上的操作异常卡顿，可以看到我连续点击设置很多次，直到回答输出完才弹出设置界面。

https://github.com/lobehub/lobe-chat/assets/11055122/f5def4ae-0aa7-4f96-9a63-d8e0862c3516

**Comment by arvinxx** [comment]
@Sun-drenched 帮忙确认下，点击其他操作按钮卡不卡？ 例如导入配置、分享或者角色设定的编辑按钮。

<img width="346" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/a1c189f9-54c4-4b07-86ca-f333695dccdf">

**Comment by Sun-drenched** [comment]
> @Sun-drenched 帮忙确认下，点击其他操作按钮卡不卡？ 例如导入配置、分享或者角色设定的编辑按钮。
> 
> <img alt="image" width="346" src="https://private-user-images.githubusercontent.com/28616219/337960165-a1c189f9-54c4-4b07-86ca-f333695dccdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MjQwMjcsIm5iZiI6MTcxNzkyMzcyNywicGF0aCI6Ii8yODYxNjIxOS8zMzc5NjAxNjUtYTFjMTg5ZjktNTRjNC00YjA3LTg2Y2EtZjMzMzY5NWRjY2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDA5MDIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZGE4ZWExN2VmOGQ5YmM4OGZiZmM5YzNjOTA0NTA5YWIxZWZhZWVmZTRjZGRlMTFmNDI1Nzc5ODZkNDY0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GTn-O2tRnRPV8Lb95kCfdrW1IQ4H_GChCykW_Ln76jo">

你说的这三个不卡

**Comment by arvinxx** [comment]
@Sun-drenched 那右上角的会话设置是不是会卡？

<img width="203" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/df1a410d-63a7-45f7-b8e0-a7738762d7d0">

**Comment by Sun-drenched** [comment]
> @Sun-drenched 那右上角的会话设置是不是会卡？
> 
> <img alt="image" width="203" src="https://private-user-images.githubusercontent.com/28616219/337960703-df1a410d-63a7-45f7-b8e0-a7738762d7d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MjQ0NjQsIm5iZiI6MTcxNzkyNDE2NCwicGF0aCI6Ii8yODYxNjIxOS8zMzc5NjA3MDMtZGYxYTQxMGQtNjNhNy00NWY3LWI4ZTAtYTc3Mzg3NjJkN2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDA5MDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMTMxZjdiOTM0OWYwZjBiNjhiZWNlZTdmZDBmNzViODVkMDQyZWNmMjFjOWJkMDM3YjEyODcyNzMwMzAzMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKNvMLIICpWroXiUldqq4YI3L9iOuJHsH0I_FAP_VOs">

是的。主观感受，卡顿程度和应用设置相同。

**Comment by arvinxx** [comment]
那看来像是拦截路由的问题，得研究下有没有解法。 cc @canisminor1990 

- refs: https://github.com/lobehub/lobe-chat/discussions/2295#discussioncomment-9290942

**Comment by hjkcai** [comment]
主要是看起来目前项目大量使用了 RSC，很多 UI 操作都要等待 RSC 响应。在本地开发，或者本机使用的时候没什么感觉，如果套一个 cloudflare tunnel 或者用延迟高一点的服务器，UI 操作等待时间会很长。理论上大部分 UI 操作都不应该等待服务器的响应才对？

**Comment by arvinxx** [comment]
> 理论上大部分 UI 操作都不应该等待服务器的响应才对？

@hjkcai  只能说是部分正确吧， 现在 LobeChat 的很多界面是可以通过服务端配置来控制的，我们有好多 Feature Flags 来控制是否显示某些元素（比如 WebRTC 同步、模型设置等等），在传统 带有 SSR 的 SPA 中是比较难做到很完美的前端开关控制的。 很显然 RSC 是非常适合这种诉求的技术方案。

这个 issue 的根因我粗估和 RSC 没啥关系，而可能是跟 nextjs 的拦截路由有关系。（和 RSC 没关系的原因就是在输出前和输出后点击都不卡，只有输出中才卡）

**Comment by hjkcai** [comment]
@arvinxx 或许可以在启动的时候一次性借助 RSC 拉取配置？每个 UI 交互都需要独立去拉取配置每次都有延迟。

交互延迟的问题跟这个 issue 应该没有直接关系，不过也挺影响用户体验的

**Comment by arvinxx** [comment]
> 或许可以在启动的时候一次性借助 RSC 拉取配置

嗯，这个是优化方案。要解决这个 issue 的问题，要做的事情就是得把之前 rsc 取 model 配置的逻辑换成你说的一次性拉取然后存到内存里，然后再把现在的拦截路由都改成普通 modal。 我们会在 1.0 发布后做这个优化。

**Comment by arvinxx** [comment]
> 交互延迟的问题跟这个 issue 应该没有直接关系，不过也挺影响用户体验的

这个可以麻烦你再开个 issue ，列下哪些地方会有你说的交互延迟的问题吗？之前已经修了很多地方了，我不确定还有哪里存在这个问题的

**Comment by Happ1ness-dev** [comment]
I have the same exact delay on mobile (android) too, but I also have extreme lag for response streaming. The text appears very slowly, and it takes far too long for it to finish, more than several minutes even on fastest models. (Meaning that the streaming has ended, but it's not yet finished displaying the response for some reason).

It's a bit better for smaller chats with shorter history.

**Comment by Happ1ness-dev** [comment]
> The text appears very slowly, and it takes far too long for it to finish, more than several minutes even on fastest models.

I found a workaround for it, you just have to open the settings and wait a about 20-30 second for it to finish responding. Yes, that's a weird workaround, but it saves me 5-10 minutes for each answer (I'm serious, that's how long it takes usually).
