### ISSUE TITLE
[Bug] 在手机上使用lobehub时，不可用

### ISSUE THREAD

**Issue by TonyKingWJX** [lobehub/lobe-chat#2829]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

v0.162.21

### 💻 Operating System

- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [X] Android
- [ ] Other

### 🌐 Browser

- [ ] Chrome
- [X] Edge
- [ ] Safari
- [ ] Firefox
- [X] Other

### 🐛 Bug Description

当我在手机浏览器上使用lobehub时（浏览器：edge、华为浏览器），会显示response.undefined或者发生客户端异常。我是在自己服务器上部署的，手机电脑用的都是同一个lobehub，并且电脑上的lobehub连接WiFi、连接手机热点都能使用，手机端在使用流量时出现response.undefined，换成WiFi（同一个），又能正常使用了，就很起怪
![91e21742436707472f4aacf62433f461](https://github.com/lobehub/lobe-chat/assets/115714101/6590292a-1c4b-45a3-abca-49b4242dbca5)
![e6905ad98a666bdb70e874b2d1266f6](https://github.com/lobehub/lobe-chat/assets/115714101/f225403e-c5e4-4ccd-8b34-074f2ff669c6)

**Comment by xingpingcn** [comment]
电脑连接手机热点测试的时候，清除浏览器缓存了吗？我试过一种情况，就是某些js在没有加载完之前，会有一些莫名其妙的问题，等他加载完就没有问题了，推测是你的vps到你的手机运营商的网络不太好导致的

**Comment by TonyKingWJX** [comment]
> 电脑连接手机热点测试的时候，清除浏览器缓存了吗？我试过一种情况，就是某些js在没有加载完之前，会有一些莫名其妙的问题，等他加载完就没有问题了，推测是你的vps到你的手机运营商的网络不太好导致的

没有清除浏览器缓存，可能就是vps和手机运营商网络的问题吧😭
