### ISSUE TITLE
如何通过配置环境变量让lobchat容器第一次启动打开的时候只能看到智谱AI的模型，看不到其他模型

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#2831]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 软件版本

7.9

### 💻 系统环境

- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [X] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

如何通过配置环境变量让lobchat容器第一次启动打开的时候只能看到智谱AI的模型，看不到其他模型,像图片上这个样子
![1717991239032](https://github.com/lobehub/lobe-chat/assets/169867372/8659aec5-4a65-41ce-bcbd-9e84c8b1a2e2)

### 📷 复现步骤

如何通过配置环境变量让lobchat容器第一次启动打开的时候只能看到智谱AI的模型，看不到其他模型
![1717991239032](https://github.com/lobehub/lobe-chat/assets/169867372/cde8fb70-c2da-4051-82f6-c77e9475daaa)

### 🚦 期望结果

如何通过配置环境变量让lobchat容器第一次启动打开的时候只能看到智谱AI的模型，看不到其他模型
![1717991239032](https://github.com/lobehub/lobe-chat/assets/169867372/cbb5e8fb-d91a-4657-bf6f-c319593f3331)

**Comment by sxjeru** [comment]
参考：https://lobehub.com/zh/docs/self-hosting/environment-variables/model-provider
可尝试添加下述 env。

ENABLED_OPENAI=0
ENABLED_OLLAMA=0

**Comment by zhangleijun111** [comment]
> > Bot检测到问题主体的语言不是英语，自动翻译它。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> 参考:[https://lobe hub . com/zh/docs/self-hosting/environment-variables/model-provider](https://lobehub.com/zh/docs/self-hosting/environment-variables/model-provider)您可以尝试添加以下env。
> 
> ENABLED_OPENAI=0ENABLED_OLLAMA=0

是否有环境变量吧智谱AI打开并且把KEY默认填入

**Comment by sxjeru** [comment]
> 是否有环境变量吧智谱AI打开并且把KEY默认填入

ZHIPU_API_KEY=''

https://lobehub.com/zh/docs/self-hosting/environment-variables/model-provider#zhipu-api-key

**Comment by zhangleijun111** [comment]
> > 机器人程序检测到问题主体的语言不是英语,自动翻译它。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > 有什么环境变量吗？打开智普AI，默认填钥匙。
> 
> ZHIPU_API_KEY= ' '
> 
> [https://lobe hub . com/zh/docs/self-hosting/environment-variables/model-provider # zhipu-API-key](https://lobehub.com/zh/docs/self-hosting/environment-variables/model-provider#zhipu-api-key)

没有办法默认打开只能通过配置环境变量输入密钥操作是嘛，开关还是需要手动的？？？

**Comment by sxjeru** [comment]
可以先试试看，如果没有自动展示智谱AI模型再回复，我去看看能否提个pr。

**Comment by zhangleijun111** [comment]
> > Bot检测到问题正文的语言不是英语，请自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> 可以先试一试。如果AI模型在回复前没有自动显示，我会看看是否可以提交PR。

![0137bb859c203f1c7809689c6aeeece](https://github.com/lobehub/lobe-chat/assets/169867372/2baedaf6-a4ec-4017-ba58-bcb125cf3e55)
![3604f48a7b0fac2c2e9b0e93527ae36](https://github.com/lobehub/lobe-chat/assets/169867372/ec3f2c2d-ecde-405e-884b-6c24eca10435)
我的环境变量配置zhipukey，容器第一次启动页打开了，但是检查通过不了，但是我讲key手动填入是可以的，这是为什么呢？？？

**Comment by sxjeru** [comment]
环境变量名是全大写的，ZHIPU_API_KEY。

**Comment by zhangleijun111** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> The environment variable name is in all uppercase letters, ZHIPU_API_KEY.

![8bf3985a22d7206ae408a23a1dc165e](https://github.com/lobehub/lobe-chat/assets/169867372/c8731fac-9d78-47cc-915e-3599c1959953)我改成了大写还是不行为什么呢

**Comment by zhangleijun111** [comment]
> > Bot检测到问题正文的语言不是英语，请自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> 你能提供更多信息吗？在这里测试没有问题。
> 
> 此外，您可以关闭重复的问题:#2825

可以了而且智普的开关也自动打开了谢谢！，麻烦问下上传文档的功能大概多久才会有啊

**Comment by sxjeru** [comment]
或许这个月底？我也很期待文件上传能早日实装。

**Comment by arvinxx** [comment]
> 麻烦问下上传文档的功能大概多久才会有啊

这个月中开始做，快的话月底上。
