### ISSUE TITLE
 API Error

### ISSUE THREAD

**Issue by thelapyae** [lobehub/lobe-chat#2834]
### 📦 Environment

- [ ] Official
- [X] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 Version

Web

### 💻 Operating System

- [ ] Windows
- [X] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

Can’t even check the connection to the server when I put Claude API key and test . Same goes for Perplexity API 

### 📷 Recurrence Steps

Both Claude and Perplexity API can see the model list . But when I press check it got error. 

### 🚦 Expected Behavior

Just want to run smooth like other API services

### 📝 Additional Information

Nothing yet

**Comment by arvinxx** [comment]
Need more information for this issue
