### ISSUE TITLE
[Bug] gemini1.5pro无法使用插件

### ISSUE THREAD

**Issue by xingpingcn** [lobehub/lobe-chat#2838]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [X] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 Version

最新

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/117259690/bb2895a9-d3af-4387-b07d-7b84a5a86369)

使用官方api

```json
{
  "identifier": "weather",
  "message": "[gateway] plugin 'weather' is not found，please check the plugin list in https://chat-plugins.lobehub.com, or create an issue to [lobe-chat-plugins](https://github.com/lobehub/lobe-chat-plugins/issues)"
}
```

**Comment by arvinxx** [comment]
根据这个报错来看，应该是 Google Gemini Pro 在 Function calling 上对于 tool 的识别能力有限导致的。

我之前自己测试也是有这个问题，这个不算是 LobeChat 的 bug ，而是 Google Gemini 的Function calling水平有限导致的。

**Comment by xingpingcn** [comment]
这些模型我只有glm-4，还不是官方api，是oneapi转的，就没办法测试了
![image](https://github.com/lobehub/lobe-chat/assets/117259690/fe7dc09d-0177-4e01-9328-5783abf72aa4)

**Comment by arvinxx** [comment]
> 这些模型我只有glm-4，还不是官方api，是oneapi转的

你去对应平台官网注册一下不就有了？国内的供应商注册以后还送几千万token的
