### ISSUE TITLE
the check passes, but chatting still fails.

### ISSUE THREAD

**Issue by fazhang-master** [lobehub/lobe-chat#2839]
![image](https://github.com/lobehub/lobe-chat/assets/89283399/c6082d34-35f3-4e25-9d26-3b7053c40b94)
![image](https://github.com/lobehub/lobe-chat/assets/89283399/69f95e52-7e9b-4209-9767-57b4c1d5420d)
![image](https://github.com/lobehub/lobe-chat/assets/89283399/e5324675-1077-44ed-b48b-5b7cda69484e)
Ollama is running locally, not in Docker. However, after running the lobe-chat Docker container using the following command:docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://127.0.0.1:11434 lobehub/lobe-chat。the check passes, but chatting still fails. The command curl http://127.0.0.1:11434 works successfully, and running ollama run llama3:8b also works correctly.

_Originally posted by @fazhang-master in https://github.com/lobehub/lobe-chat/issues/1633#issuecomment-2158219327_

**Comment by arvinxx** [comment]
do it still occur ?
