### ISSUE TITLE
Cloud Sync [Bug] 

### ISSUE THREAD

**Issue by Chammar37** [lobehub/lobe-chat#2842]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [X] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

v0.162.21

### 💻 Operating System

- [X] Windows
- [X] macOS
- [X] Ubuntu
- [X] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [X] Edge
- [X] Safari
- [X] Firefox
- [ ] Other

### 🐛 Bug Description

The cloud sync was working for a while, syncing with multiple computers and then all of sudden it stopped working and i lost my lists/topics/chats on other computers, saying 'Cloud Sync Failed'.

I've tried to re-create another channel with a different name, the sync says 'Connected' although I don't see topics/chats from my other computer.

Is there a better way of making the 'shared chats' use case more reliable with WebRTC Sync? Is there coming releases to fix these issues?

Thank you! 

### 📷 Recurrence Steps

Adding 'Sync Channel Name' and 'Sync Channel Password', clicking Enable Sync.

Connecting other computers with same name/password

### 🚦 Expected Behavior

To see all the same Lists, Topics and Chats from my other computer on the lobechat UI

**Comment by cogscides** [comment]
Same for me. Sync functionality disappeared and then I enabled it via flags. Now it's not syncing. It displays "Connection Failed" and here is the console log outputs: 
```
WebSocket connection to 'wss://y-webrtc-signaling.lobehub.com/' failed: 
o @ 70065.4eb3154cdab79e5d.js:1
---
70065.4eb3154cdab79e5d.js:1 WebSocket connection to 'wss://y-webrtc-signaling.lobehub.com/' failed: WebSocket is closed before the connection is established. 
disconnect @ 70065.4eb3154cdab79e5d.js:1
```

**Comment by 9Somboon** [comment]
I think the feature might be discontinued in the community version. To be an important feature for subscription users on the lobehub website.

**Comment by cogscides** [comment]
> To be an important feature for subscription users on the lobehub website.

Very sad to hear that as at the moment community self-hosted version lack any options to sync except Vercel stack.

**Comment by arvinxx** [comment]
@cogscides @9Somboon we don't remove it. You still can enable it with Feature Flag https://lobehub.com/docs/self-hosting/advanced/feature-flags

**Comment by cogscides** [comment]
> @cogscides @9Somboon we don't remove it. You still can enable it with Feature Flag https://lobehub.com/docs/self-hosting/advanced/feature-flags


I enabled it, and I see it in UI. But I got errors in the console:

https://github.com/lobehub/lobe-chat/issues/2842#issuecomment-2185145168

**Comment by cogscides** [comment]
Can we have a `WEB_RTC_SIGNALING_URL` specified in the environment so we can host the signaling container?

**Comment by cogscides** [comment]
Are there any updates on this? It makes the self-hosted version useless as we haven't any other convenient sync options. As far as I know, server db isn't yet implemented for self-hosted option.

**Comment by cogscides** [comment]
Discussion on how to setup WebRTC sync for lobe-chat:
https://github.com/lobehub/lobe-chat/discussions/3192
