### ISSUE TITLE
[Bug] Ctrl+Enter 发送后不会开始回答过程

### ISSUE THREAD

**Issue by hlc1209** [lobehub/lobe-chat#2849]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 软件版本

0.162.21

### 💻 系统环境

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

在Ctrl+Enter 模式下，按Ctrl+Enter后不会开始回答过程

按发送按钮可以自动开始回答
在Enter模式下，按Enter可以自动开始回答

### 📷 复现步骤

1. 设置发送模式
![image](https://github.com/lobehub/lobe-chat/assets/45445824/3b6d5693-609e-4863-8aa2-deb8716ff81d)
2. 输入任意内容
3. 按ctrl+enter发送
![image](https://github.com/lobehub/lobe-chat/assets/45445824/75856fa4-a1a1-4902-a86d-4ce7f8dc6284)

**Comment by sxjeru** [comment]
这边无法复现问题，Ctrl+回车可以正常触发对话。

**Comment by hlc1209** [comment]
> 这边无法复现问题，Ctrl+回车可以正常触发对话。

我昨天尝试清空浏览器缓存。确实正常触发对话。
但是今天再次使用时，又出现了同样的问题。

**Comment by ozshen** [comment]
什么时候能解决浏览器最小化后无法继续应答的问题？还有多个会话同时应答的功能支持... chatgpt-next-web是可以支持的

**Comment by arvinxx** [comment]
> 什么时候能解决浏览器最小化后无法继续应答的问题？还有多个会话同时应答的功能支持... 

分别提下issue?

**Comment by hlc1209** [comment]
问题持续出现中。
最近折腾公网建站。
所以试了各种浏览器。都是稳定复现bug。
版本已经升级到最新v1.0.11

**Comment by hlc1209** [comment]
升级到v1.1.3后bug消失。再测试几天，没问题我close了
