### ISSUE TITLE
自动补全未生成头像

### ISSUE THREAD

**Issue by maxyou2090** [lobehub/lobe-chat#2850]
![CleanShot 2024-06-12 at 07 00 14](https://github.com/lobehub/lobe-chat/assets/26402739/8e6fed68-98c4-4b26-bb21-19c0d3d03c4e)

之前头像也会自动生成，现在都是这个BOT的头像，其他内容会自动生成

**Comment by arvinxx** [comment]
我看下，可能是个 bug
