### ISSUE TITLE
【feat】能否在选择模型处加一个刷新模型的按钮

### ISSUE THREAD

**Issue by Yanyutin753** [lobehub/lobe-chat#2853]
### 🥰 需求描述

【feat】能否在选择模型处加一个刷新模型的按钮，增强用户体验

### 🧐 解决方案

【feat】能否在选择模型处加一个刷新模型的按钮，增强用户体验

### 📝 补充信息

【feat】能否在选择模型处加一个刷新模型的按钮，增强用户体验

**Comment by arvinxx** [comment]
没懂，刷新模型干嘛的？

**Comment by Yanyutin753** [comment]
> 没懂，刷新模型干嘛的？

就不用跑到模型设置里刷新了，有时候模型数据会消失，得重新刷新

**Comment by ITOTI-Y** [comment]
> 没懂，刷新模型干嘛的？

他指的是获取模型信息的按钮，目前当上游更新模型时，需要进入应用设置->语言模型->获取模型列表进行更新，有点繁琐

**Comment by arvinxx** [comment]
> 他指的是获取模型信息的按钮，目前当上游更新模型时，需要进入应用设置->语言模型->获取模型列表进行更新，有点繁琐

哪家的模型 Provider 天天刷新？这不是个普通用户的高频行为吧，不考虑做。
