### ISSUE TITLE
[Bug] 助手列表不刷新

### ISSUE THREAD

**Issue by mxdlzg** [lobehub/lobe-chat#2857]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

v0.162.23

### 💻 Operating System

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [ ] Chrome
- [X] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

不论是新建助手还是删除助手，只显示toast的信息。列表纹丝不动。

**Comment by arvinxx** [comment]
有录屏吗？

**Comment by mxdlzg** [comment]
@arvinxx 


https://github.com/lobehub/lobe-chat/assets/18144577/64a9521a-79b5-4707-a241-fa06502084cb

**Comment by mxdlzg** [comment]
对了，环境是Edge安装的应用

**Comment by mxdlzg** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/18144577/363b17e6-3bd2-41fa-a5e7-7bdeed7e6605)

<img width="636" alt="image" src="https://github.com/lobehub/lobe-chat/assets/18144577/470de24f-29c2-42da-afa5-b17109376a2d">

session错误应该是正常的，我server没设任何登录方法。
但是看起来_vercel/insights/script.js是404

**Comment by mxdlzg** [comment]
emm
