### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SammyDeM** [lobehub/lobe-chat#2871]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

latest

### 💻 Operating System

- [ ] Windows
- [ ] macOS
- [X] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

API response.ProviderBizError

{
  "error": {
    "message": "Invalid model 'pplx-7b-chat'. Permitted models can be found in the documentation at https://docs.perplexity.ai/docs/model-cards.",
    "type": "invalid_model",
    "code": 400
  },
  "endpoint": "https://api.perplexity.ai",
  "provider": "perplexity"
}

**Comment by sxjeru** [comment]
`pplx-7b-chat` has been deprecated and removed from the documentation.
Please check the link for available models.

https://docs.perplexity.ai/docs/model-cards
