### ISSUE TITLE
[Bug] 环境变量 FEATURE_FLAGS 中的 -openai_api_key,-openai_proxy_url 没有生效

### ISSUE THREAD

**Issue by suemor233** [lobehub/lobe-chat#2883]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 软件版本

v0.162.24

### 💻 系统环境

- [ ] Windows
- [ ] macOS
- [X] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

环境变量里配置了 `FEATURE_FLAGS=-openai_api_key,-openai_proxy_url` 但前端并没有生效，用户依旧可以自定义 OpenAI API Key 和 OpenAI Proxy URL。

简单看了下源码，这个功能似乎并没有实现。

![CleanShot 2024-06-16 at 01 30 38@2x](https://github.com/lobehub/lobe-chat/assets/89030875/6d92ef9f-2855-46cb-a9e8-254046d4bede)

**Comment by arvinxx** [comment]
这个界面忘记加了，欢迎 PR 一下？ 可以参考 https://github.com/lobehub/lobe-chat/blob/main/src/app/(main)/settings/llm/ProviderList/OpenAI/index.tsx#L11 这里

**Comment by suemor233** [comment]
> 这个界面忘记加了，欢迎 PR 一下？ 可以参考 https://github.com/lobehub/lobe-chat/blob/main/src/app/(main)/settings/llm/ProviderList/OpenAI/index.tsx#L11 这里

行，我来改改看

**Comment by Sun-drenched** [comment]
这项功能原来设计的是不输入Access_Code就不能用整个服务吗？我还一直以为这是故意为之，输密码就能用预设Key（比如自己用），不输密码只要自己有key还是能用（比如把自己部署的网站分享给朋友用）

**Comment by arvinxx** [comment]
> 这项功能原来设计的是不输入Access_Code就不能用整个服务吗？我还一直以为这是故意为之，输密码就能用预设Key（比如自己用），不输密码只要自己有key还是能用（比如把自己部署的网站分享给朋友用）

这是另外一个服务能力，针对服务端配置了api key 或者 proxy url 的用户，他们不想被访客白嫖网站流量，或者不允许填写自定义apikey，只能用access code访问。所以我们会在界面上隐藏配置 api key 或者 proxy url 的功能
