### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by czh020110** [lobehub/lobe-chat#2890]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [ ] Vercel / Zeabur / Sealos
- [ ] Docker
- [X] Other

### 📌 软件版本

浏览器

### 💻 系统环境

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [X] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

搜索引擎插件无法正常使用，回答的结果不是插件的返回结果。而是ai自己写的，也没有显示搜索的相关网址。
![mmexport1718540468699](https://github.com/lobehub/lobe-chat/assets/106853837/8e3fa4e0-d6c3-451f-b197-086abf1afe3c)

### 📷 复现步骤

1.使用插件并发送：“搜索一下c语言和c++的关系”
2.搜索引擎返回结果：“[
  {
    "content": "从理论上来说，学C++前并不一定非得学C语言，但是有C语言底子再去学C++往往更具优势，最起码「面向过程编程」这一部分内容能够轻车熟路。 但是遗憾的是， ...",
    "date": "2020年8月24日",
    "displayed_link": "https://cloud.tencent.com › developer › news",
    "favicon": "https://serpapi.com/searches/666ed6b966d81fc76a7233ea/images/56c30b8488ee531abd1414a08844f6923fc3fe68d80666f3aab14c92f2c03045.avif",
    "link": "https://cloud.tencent.com/developer/news/681542",
    "source": "腾讯云",
    "title": "很多人都搞不清楚C语言和C＋的关系！今天我们来一探 ..."
  },
  {
    "content": "C++ 读作”C加加“，是”C Plus Plus“的简称。顾名思义，C++是在C的基础上增加新特性，玩出了新花样，所以叫”C Plus Plus“，就像iPhone 6S 和iPhone 6、Win10 ...",
    "date": "2016年8月30日",
    "displayed_link": "https://blog.csdn.net › czg13548930186 › article › details",
    "favicon": "https://serpapi.com/searches/666ed6b966d81fc76a7233ea/images/56c30b8488ee531abd1414a08844f6920e15d11b056e4f2e8df575176ddd2ec6.avif",
    "link": "https://blog.csdn.net/czg13548930186/article/details/52374278",
    "source": "CSDN博客",
    "title": "C和C++到底有什么关系_c语言和c 有什么"
  },
  {
    "content": "我们都知道C语言是面向过程语言，而C++是面向对象语言，说C和C++的区别，也就是在比较面向过程和面向对象的区别。 （1）面向过程和面向对象的区别. 面向 ...",
    "date": "2022年7月1日",
    "displayed_link": "https://www.51cto.com › article",
    "favicon": "https://serpapi.com/searches/666ed6b966d81fc76a7233ea/images/56c30b8488ee531abd1414a08844f692f1e0cca7f05795040b6c5e92128201e7.avif",
    "link": "https://www.51cto.com/article/712924.html",
    "source": "51CTO",
    "title": "C语言和C++的区别和联系"
  },
  {
    "content": "C语言和C++的关系相当密切，但是也存在许多显著的差异。C++标准起源于早期C标准， 并被设计为与当时的C语言在源代码编写和链接方面很大程度上兼容。 因此，两种语言的 ...",
    "displayed_link": "https://zh.wikipedia.org › zh-cn › C与C++的兼容性",
    "favicon": "https://serpapi.com/searches/666ed6b966d81fc76a7233ea/images/56c30b8488ee531abd1414a08844f69223dbc8e29434959c17f584c8a97cdb52.avif",
    "link": "https://zh.wikipedia.org/zh-cn/C%E4%B8%8EC%2B%2B%E7%9A%84%E5%85%BC%E5%AE%B9%E6%80%A7",
    "source": "维基百科",
    "title": "C与C++的兼容性"
  },
  {
    "content": "C是一个结构化语言，它的重点在于算法和数据结构。C程序的设计首要考虑的是如何通过一个过程，对输入（或环境条件）进行运算处理得到输出（或实现过程（ ...",
    "date": "2019年10月7日",
    "displayed_link": "https://cloud.tencent.com › developer › news",
    "favicon": "https://serpapi.com/searches/666ed6b966d81fc76a7233ea/images/56c30b8488ee531abd1414a08844f692c597a01216376a368527186d53f3d51e.avif",
    "link": "https://cloud.tencent.com/developer/news/451227",
    "source": "腾讯云",
    "title": "C语言和CPP是什么关系？它们之间又有什么差异？"
  },
  {
    "content": "C语言和C++是两种非常流行的编程语言，他们的名称相似，来源也有很大相关性——它们都是从B语言发展而来的。这两种语言还是有点区别的，本文将详细介绍 ...",
    "date": "2023年5月18日",
    "displayed_link": "https://www.w3cschool.cn › article",
    "favicon": "https://serpapi.com/searches/666ed6b966d81fc76a7233ea/images/56c30b8488ee531abd1414a08844f69203278281acf30069b0e6717cb7ac9a73.avif",
    "link": "https://www.w3cschool.cn/article/42693058.html",
    "source": "编程狮",
    "title": "c++和c语言的区别有哪些？一张表带你了解 ..."
  },
  {
    "content": "简单来说，C++就像是C语言的亲弟弟，而C#就是他们二者的远房亲戚（其实它更像是Java的表兄弟）。这三门语言都是十分优秀的编程语言，也都有很高的运行 ...",
    "date": "2022年5月25日",
    "displayed_link": "https://blog.csdn.net › article › details",
    "favicon": "https://serpapi.com/searches/666ed6b966d81fc76a7233ea/images/56c30b8488ee531abd1414a08844f692554160f797e70f8eec444e07cf76e977.avif",
    "link": "https://blog.csdn.net/qq_42366672/article/details/124966217",
    "source": "CSDN博客",
    "title": "编程语言：C语言/C++/C#三种语言，它们之间分别是什么关系 ..."
  },
  {
    "content": "C++ 主要在C 语言的基础上增加了物件导向和泛型的机制，提高了开发效率，以适用於大中型软件的编写。 C++与C 的血缘关系早期并没有”C++“这个名字，而是 ...",
    "date": "2022年2月19日",
    "displayed_link": "https://www.cnblogs.com › netlog",
    "favicon": "https://serpapi.com/searches/666ed6b966d81fc76a7233ea/images/56c30b8488ee531abd1414a08844f6920b193c60ae3dee07c2ab236688f18cc1.avif",
    "link": "https://www.cnblogs.com/netlog/p/15913722.html",
    "source": "博客园",
    "title": "浅谈C语言和C++之间的区别与联系- 张赐荣"
  },
  {
    "content": "c++和c语言的区别有：1、面向过程和面向对象的区别；2、具体语言上的区别；3、主体不同；4、优势不同；5、特点不同。其中，具体语言上的区别有关键 ...",
    "date": "2022年8月29日",
    "displayed_link": "https://worktile.com › ask",
    "favicon": "https://serpapi.com/searches/666ed6b966d81fc76a7233ea/images/56c30b8488ee531abd1414a08844f692c388acb19108a65ca974d5a208eb2333.avif",
    "link": "https://worktile.com/kb/ask/21161.html",
    "source": "Worktile",
    "title": "c++和c语言的区别"
  }
]”

3.AI回复结果：“C语言和C++的关系相当密切，但是也存在许多显著的差异。C++ 是在 C 的基础上增加新特性的一种编程语言，被设计为与当时的C语言在源代码编写和链接方面很大程度上兼容。C语言是面向过程的编程语言，重点在于算法和数据结构。而C++既包含了C语言的面向过程编程，也增加了面向对象的编程特性，提高了开发效率，适用于大中型软件的编写。

从理论上来说，学C++前并不一定非得学C语言，但是有C语言底子再去学C++往往更具优势，最起码「面向过程编程」这一部分内容能够轻车熟路。学习C++可以更好地理解面向对象编程的思想，而面向对象编程是现代软件开发的主流方法。

同时，虽然C++在很大程度上兼容C语言，但也有许多C语言的语法在C++中被改变或废弃....”

4.可以看到AI回复的不是搜索到的结果

### 🚦 期望结果

希望使用搜索引擎插件时，AI回复的的是搜索引擎的返回结果。

### 📝 补充信息

thanks

**Comment by arvinxx** [comment]
你用了什么模型？

**Comment by czh020110** [comment]
> 你用了什么模型？

gpt-4o

**Comment by arvinxx** [comment]
这个问题还存在吗？
