### ISSUE TITLE
[Bug] Netlify部署报错

### ISSUE THREAD

**Issue by S45618** [lobehub/lobe-chat#2891]
### 📦 部署环境

- [ ] Official
- [ ] Official Preview
- [X] Vercel / Zeabur / Sealos
- [ ] Docker
- [ ] Other

### 📌 软件版本

162.25

### 💻 系统环境

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 问题描述

netlify AI给出的解析⬇️
![图片](https://github.com/lobehub/lobe-chat/assets/170120833/6bd6d494-be8f-491e-9a4b-9bb2815ae54c)

### 📷 复现步骤

7:20:02 PM: build-image version: 006dca901dab83234b4881f914ac1a189ff41daa (focal)
7:20:02 PM: buildbot version: 9bbdac2b13a98595e6082353a9003cde1cbabfa5
7:20:02 PM: Fetching cached dependencies
7:20:02 PM: Starting to download cache of 462.8MB
7:20:04 PM: Finished downloading cache in 2.277s
7:20:04 PM: Starting to extract cache
7:20:11 PM: Finished extracting cache in 7.289s
7:20:11 PM: Finished fetching cache in 9.649s
7:20:11 PM: Starting to prepare the repo for build
7:20:12 PM: Preparing Git Reference refs/heads/main
7:20:13 PM: Custom build command detected. Proceeding with the specified command: 'NODE_OPTIONS=--max_old_space_size=4096 npm run build'
7:20:14 PM: Starting to install dependencies
7:20:14 PM: Python version set to 3.8
7:20:14 PM: Attempting Ruby version 2.7.2, read from environment
7:20:15 PM: Using Ruby version 2.7.2
7:20:15 PM: Started restoring cached go cache
7:20:15 PM: Finished restoring cached go cache
7:20:15 PM: go version go1.19.13 linux/amd64
7:20:16 PM: Using PHP version 8.0
7:20:17 PM: Started restoring cached Node.js version
7:20:18 PM: Finished restoring cached Node.js version
7:20:18 PM: Attempting Node.js version 'lts/hydrogen' from .nvmrc
7:20:18 PM: v18.20.3 is already installed.
7:20:18 PM: Now using node v18.20.3 (npm v10.7.0)
7:20:18 PM: Enabling Node.js Corepack
7:20:18 PM: Started restoring cached build plugins
7:20:18 PM: Finished restoring cached build plugins
7:20:18 PM: Started restoring cached corepack dependencies
7:20:18 PM: Finished restoring cached corepack dependencies
7:20:18 PM: No npm workspaces detected
7:20:18 PM: Started restoring cached node modules
7:20:18 PM: Finished restoring cached node modules
7:20:19 PM: Installing npm packages using npm version 10.7.0
7:20:27 PM: > @lobehub/chat@0.162.25 prepare
7:20:27 PM: > husky
7:20:27 PM: added 6 packages, changed 1 package, and audited 3414 packages in 8s
7:20:27 PM: 686 packages are looking for funding
7:20:27 PM:   run `npm fund` for details
7:20:27 PM: 8 vulnerabilities (4 moderate, 4 high)
7:20:27 PM: To address all issues possible (including breaking changes), run:
7:20:27 PM:   npm audit fix --force
7:20:27 PM: Some issues need review, and may require choosing
7:20:27 PM: a different dependency.
7:20:27 PM: Run `npm audit` for details.
7:20:27 PM: npm packages installed
7:20:27 PM: Successfully installed dependencies
7:20:27 PM: Starting build script
7:20:28 PM: Detected 2 framework(s)
7:20:28 PM: "next" at version "14.2.3"
7:20:28 PM: "vite" at version "5.2.12"
7:20:28 PM: Section completed: initializing
7:20:30 PM: ​
7:20:30 PM: Netlify Build                                                 
7:20:30 PM: ────────────────────────────────────────────────────────────────
7:20:30 PM: ​
7:20:30 PM: ❯ Version
7:20:30 PM:   @netlify/build 29.47.5
7:20:30 PM: ​
7:20:30 PM: ❯ Flags
7:20:30 PM:   baseRelDir: true
7:20:30 PM:   buildId: 666eca4b7d7acd0008f0b9ea
7:20:30 PM:   deployId: 666eca4b7d7acd0008f0b9ec
7:20:30 PM: ​
7:20:30 PM: ❯ Current directory
7:20:30 PM:   /opt/build/repo
7:20:30 PM: ​
7:20:30 PM: ❯ Config file
7:20:30 PM:   /opt/build/repo/netlify.toml
7:20:30 PM: ​
7:20:30 PM: ❯ Context
7:20:30 PM:   production
7:20:30 PM: ​
7:20:30 PM: ❯ Using Next.js Runtime - v5.3.2
7:20:32 PM: Next.js cache restored
7:20:32 PM: ​
7:20:32 PM: build.command from netlify.toml                               
7:20:32 PM: ────────────────────────────────────────────────────────────────
7:20:32 PM: ​
7:20:32 PM: $ NODE_OPTIONS=--max_old_space_size=4096 npm run build
7:20:32 PM: > @lobehub/chat@0.162.25 build
7:20:32 PM: > next build
7:20:33 PM:   ▲ Next.js 14.2.3
7:20:33 PM:    Creating an optimized production build ...
7:20:34 PM:  ⚠ Found lockfile missing swc dependencies, run next locally to automatically patch
7:20:34 PM:  ✓ (pwa) Compiling for server...
7:20:34 PM:  ✓ (pwa) Compiling for server...
7:20:34 PM:  ✓ (pwa) Compiling for client (static)...
7:20:34 PM:  ○ (pwa) Service worker: /opt/build/repo/public/sw.js
7:20:34 PM:  ○ (pwa)   URL: /sw.js
7:20:34 PM:  ○ (pwa)   Scope: /
7:22:33 PM:  ✓ Compiled successfully
7:22:33 PM:    Linting and checking validity of types ...
7:22:49 PM: ./src/app/(main)/profile/[[...slugs]]/Client.tsx
7:22:49 PM: 58:8  Warning: 'k' is defined but never used. Allowed unused vars must match /^_/u.  unused-imports/no-unused-vars
7:22:49 PM: ./src/layout/AuthProvider/Clerk/useAppearance.ts
7:22:49 PM: 92:8  Warning: 'k' is defined but never used. Allowed unused vars must match /^_/u.  unused-imports/no-unused-vars
7:22:49 PM: ./src/store/chat/slices/plugin/action.ts
7:22:49 PM: 204:13  Warning: Empty block statement.  no-empty
7:22:49 PM: ./src/utils/fetch.ts
7:22:49 PM: 367:11  Warning: Empty block statement.  no-empty
7:22:49 PM: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
7:22:52 PM: Failed to compile.
7:22:52 PM: 
7:22:52 PM: ./src/features/ChatInput/ActionBar/Clear.tsx:42:9
7:22:52 PM: Type error: Type '{ icon: ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>; overlayStyle: { ...; }; placement: "bottom"; title: any; }' is not assignable to type 'IntrinsicAttributes & ActionIconProps & RefAttributes<HTMLDivElement>'.
7:22:52 PM:   Property 'overlayStyle' does not exist on type 'IntrinsicAttributes & ActionIconProps & RefAttributes<HTMLDivElement>'.
7:22:52 PM:   40 |       <ActionIcon 
7:22:52 PM:   41 |         icon={Eraser} 
7:22:52 PM: > 42 |         overlayStyle={{ maxWidth: 'none' }}
7:22:52 PM:      |         ^
7:22:52 PM:   43 |         placement={'bottom'} 
7:22:52 PM:   44 |         title={actionTitle} />
7:22:52 PM:   45 |     </Popconfirm>
7:22:53 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
7:22:53 PM: ​
7:22:53 PM: "build.command" failed                                        
7:22:53 PM: ────────────────────────────────────────────────────────────────
7:22:53 PM: ​
7:22:53 PM:   Error message
7:22:53 PM:   Command failed with exit code 1: NODE_OPTIONS=--max_old_space_size=4096 npm run build (https://ntl.fyi/exit-code-1)
7:22:53 PM: ​
7:22:53 PM:   Error location
7:22:53 PM:   In build.command from netlify.toml:
7:22:53 PM:   NODE_OPTIONS=--max_old_space_size=4096 npm run build
7:22:53 PM: ​
7:22:53 PM:   Resolved config
7:22:53 PM:   build:
7:22:53 PM:     command: NODE_OPTIONS=--max_old_space_size=4096 npm run build
7:22:53 PM:     commandOrigin: config
7:22:53 PM:     environment:
7:22:53 PM:       - ACCESS_CODE
7:22:53 PM:       - OPENAI_API_KEY
7:22:53 PM:       - NODE_OPTIONS
7:22:53 PM:     publish: /opt/build/repo/.next
7:22:53 PM:     publishOrigin: config
7:22:53 PM:   plugins:
7:22:53 PM:     - inputs: {}
7:22:53 PM:       origin: ui
7:22:53 PM:       package: '@netlify/plugin-nextjs'
7:22:53 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
7:22:53 PM: Failing build: Failed to build site
7:22:53 PM: Finished processing build request in 2m51.724s

### 🚦 期望结果

顺利部署

**Comment by arvinxx** [comment]
重新安装下依赖应该就行了的
