### ISSUE TITLE
Customizable BaseURL or relative resource paths

### ISSUE THREAD

**Issue by netikras** [lobehub/lobe-chat#2904]
### 🥰 Feature Description

I've started up a self-hosted instance of lobe-chat inside a docker container. I also exposed it through my custom domain, through nginx. I was hoping to hide lobechat behind a custom URL, but it seems that this way it only loads the initial HTML and fails to load all the other resources. It seems like all the resources are fetched from src="/*", i.e. using absolute paths.

My nginx snippet I've tried.

```
  location ~ ^/my/gpt/?(.*) {
    proxy_pass http://127.0.0.1:3210/$1$is_args$args;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    sub_filter       'src="/' 'src="';
    sub_filter       'href="/' 'href="';
    sub_filter_once  off;
  }
```

![image](https://github.com/lobehub/lobe-chat/assets/2045031/cecd55e0-aef7-40f0-b72f-d7ae075df128)

### 🧐 Proposed Solution

Make the BaseURL configurable. Possibly via Env variables. And explain in the docs how it can be configured.

Even better -- make the resource paths relative in the HTML. This should make it more flexible.

**Comment by arvinxx** [comment]
actually we have a baseUrl env. But you need to build docker by yourself
