### ISSUE TITLE
[Request] OpenAI API Multi-Source Aggregation

### ISSUE THREAD

**Issue by chou18194766xx** [lobehub/lobe-chat#2906]
### 🥰 需求描述

I have multiple third-party relay sources for OpenAI, but Lobechat only seems to support filling in one source. Can you consider supporting multiple sources?

### 🧐 解决方案

It is possible to consider customizing multiple Openai API URLs and API keys, and then use them by indicating the source alias in the model selection bar

**Comment by xingpingcn** [comment]
https://github.com/songquanpeng/one-api

try this

**Comment by GuoJiaxing1997** [comment]
同样希望增加这个功能，对中国大陆地区依赖API中转供应商的用户来说确实很方便，因为很多时候有些供应商的连接不稳定，需要频繁切换。

**Comment by chou18194766xx** [comment]
> 会在这里做： #2040

Great! Looking forward to your updates
