### ISSUE TITLE
[Request] Docker 版本希望可以增加更多变量设置

### ISSUE THREAD

**Issue by i-iooi-i** [lobehub/lobe-chat#291]
### 🥰 需求描述 | Feature Description

![image](https://github.com/lobehub/lobe-chat/assets/1827701/6edb4f93-c4e6-47c2-8ccd-ffc2f12ace6a)

希望可以在Docker里面增加更多变量设置：

- 配置代理，初始 openai 和 key。
  应用场景：可以直接把LobeChat地址链接发给朋友或者远方家里的家人使用，省去了教他们前期配置的麻烦，上手即用。

- 配置访问密码。
   应用场景：地址放到外网，防止被陌生人白吃白嫖。🤤
   
   

### 🧐 解决方案 | Proposed Solution

没有解决方案，坐等大佬解决~~ 

### 📝 补充信息 | Additional Information

![image](https://github.com/lobehub/lobe-chat/assets/1827701/75837de3-469b-4a70-9e09-9b02d9f66c65)

这个剩余额度是否可以考虑做个开关隐藏呢，每次发出去消息，都忍不住看着这个数字在跑，会让一部分人产生情绪焦虑。。。😂

**Comment by i-iooi-i** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/1827701/08ad0eec-7c14-4b39-aa73-e349ee277708)

另外，大佬是否可以考虑把 GitHub 和 Discord 整合到下面的 “设置” 界面里，没有别的意思哈。

- 只是这两个功能可能不是用户日常必须的核心功能。
- 而在视觉感受上，导致页面也不是很简洁，且图标堆集在页面的下方，会分散上方的视线，整体界面协调度上稍显头重脚轻了一点。

**Comment by arvinxx** [comment]
你是用的是哪个 docker 管理工具？

**Comment by i-iooi-i** [comment]
> 你是用的是哪个 docker 管理工具？

![image](https://github.com/lobehub/lobe-chat/assets/1827701/5d00ee03-d4a8-4ac2-9da3-6669023f1791)


使用的是群晖NAS的Docker哈，在群晖套件里面改名为 Container Manager（容器管家） 了。
https://demo.synology.cn/zh-cn/dsm

**Comment by arvinxx** [comment]
Access code 已支持，可以试下

**Comment by i-iooi-i** [comment]
> Access code 已支持，可以试下

大佬效率👍

刚在环境变量里配置了6位数密码。

本地内网环境下清除cookie，访问LobeChat ，在聊天框输入文本的时候，会弹出输入密码的选项，输入6位数密码验证通过了，没有问题。

外网环境，通过反向代理用域名访问，在聊天界面也被要求输入密码，但是输入密码之后，提示“密码不正确或为空”，这是个问题哈。

**Comment by VectorZhao** [comment]
> > Access code 已支持，可以试下
> 
> 大佬效率👍
> 
> 刚在环境变量里配置了6位数密码。
> 
> 本地内网环境下清除cookie，访问LobeChat ，在聊天框输入文本的时候，会弹出输入密码的选项，输入6位数密码验证通过了，没有问题。
> 
> 外网环境，通过反向代理用域名访问，在聊天界面也被要求输入密码，但是输入密码之后，提示“密码不正确或为空”，这是个问题哈。

我是npm反代vps，域名访问也是输入密码提示不对。。。已经配置了ACCESS_CODE

**Comment by VectorZhao** [comment]
ip:port访问，密码是提示正确的。但是明明docker-compose里面配置了key和url，聊天时没反应。
![image](https://github.com/lobehub/lobe-chat/assets/16644993/9d9a81d1-dbe2-4b8c-9a7d-61b19e7981ff)

**Comment by arvinxx** [comment]
反代的 headers 有没有透传呀？

**Comment by arvinxx** [comment]
可能跟我们之前实现传递 ApiKey 和 ACCESS_TOKEN 的逻辑有关系。现在是直接将这些字段放进headers 里传过去的。可能反代传过去的时候丢了。我晚上自己起个 docker 试试看

**Comment by VectorZhao** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/16644993/6d6fcc67-d8ea-4c00-8d7e-7fe6c709b313)
![image](https://github.com/lobehub/lobe-chat/assets/16644993/b34ebd52-c00f-4f53-aef8-ce885023b74a)
![image](https://github.com/lobehub/lobe-chat/assets/16644993/0fe60a8a-9b90-4493-9cf7-ff2d0379e858)

**Comment by arvinxx** [comment]
> 外网环境，通过反向代理用域名访问，在聊天界面也被要求输入密码，但是输入密码之后，提示“密码不正确或为空”，这是个问题哈。

@i-iooi-i 已修复。试试拉取最新版 Docker 镜像

**Comment by i-iooi-i** [comment]
> > 外网环境，通过反向代理用域名访问，在聊天界面也被要求输入密码，但是输入密码之后，提示“密码不正确或为空”，这是个问题哈。
> 
> @i-iooi-i 已修复。试试拉取最新版 Docker 镜像

感谢大佬，已经拉取最新镜像了。
密码验证的问题已经解决了，但是代理key似乎验证出错
还要麻烦看下呢：https://github.com/lobehub/lobe-chat/issues/292
