### ISSUE TITLE
[Bug] 不支持数学公式

### ISSUE THREAD

**Issue by jaychoubaby** [lobehub/lobe-chat#2911]
### 📦 部署环境

Docker

### 📌 软件版本

1.0.6

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

![1](https://github.com/lobehub/lobe-chat/assets/26641387/3f625ec9-338a-447c-ad30-b66a14e82c32)
![2](https://github.com/lobehub/lobe-chat/assets/26641387/5ecbf20a-6cfa-42f8-b54c-e71d219f82f9)
图一是本项目的数学公式展示，图2是某next项目的数学公式显示，希望优化

### 📷 复现步骤

问一个数学题相关的问题，返回的数学公式支持不友好

### 🚦 期望结果

能够正确显示数学公式

**Comment by jaychoubaby** [comment]
> 请点击编辑，检查模型响应中，公式两侧是否有“$”符号

`设长方形的宽为 \( x \) cm，长为 \( \frac{5}{3}x \) cm。

当宽增加变成正方形后，正方形的边长为 \( \frac{5}{3}x \) cm。

原长方形的面积为：
\[ \text{原面积} = x \times \frac{5}{3}x = \frac{5}{3}x^2 \]

正方形的面积为：
\[ \text{正方形面积} = \left( \frac{5}{3}x \right)^2 = \frac{25}{9}x^2 \]

根据题意，正方形的面积比原长方形的面积多30平方厘米：
\[ \frac{25}{9}x^2 - \frac{5}{3}x^2 = 30 \]

将 \(\frac{5}{3}x^2\) 转换成分母为9的形式：
\[ \frac{25}{9}x^2 - \frac{15}{9}x^2 = 30 \]
\[ \frac{10}{9}x^2 = 30 \]

两边同时乘以9：
\[ 10x^2 = 270 \]

两边同时除以10：
\[ x^2 = 27 \]

取正的平方根：
\[ x = \sqrt{27} = 3\sqrt{3} \]

所以，长方形的宽为 \( x = 3\sqrt{3} \) cm，长为 \( \frac{5}{3}x = 5\sqrt{3} \) cm。

总结：
长方形的宽为 \( 3\sqrt{3} \) cm，长为 \( 5\sqrt{3} \) cm。`


点编辑数据如下

**Comment by jaychoubaby** [comment]
> 请点击编辑，检查模型响应中，公式两侧是否有“$”符号

某next点编辑数据如下，看起来是一样的，只是展示效果不一致

`这是一个代数问题，我们可以通过设置方程来求解。

设原来的长方形的宽为 \(3x\)，长为 \(5x\)，那么它的面积就是 \(15x^2\)。

当宽增加变成正方形后，长和宽都变为 \(5x\)，新的面积就是 \(25x^2\)。

题目告诉我们面积增加了30平方厘米，所以我们可以建立一个方程：

\[25x^2 - 15x^2 = 30\]

简化这个方程，我们得到：

\[10x^2 = 30\]

解这个方程，我们得到：

\[x^2 = 3\]

所以 \(x = \sqrt{3}\)。

那么，长方形的宽就是 \(3x = 3\sqrt{3}\) 厘米，长就是 \(5x = 5\sqrt{3}\) 厘米。`

**Comment by hlc1209** [comment]
同遇到该问题。
gpt-4o输出公式不使用$$

**Comment by jaychoubaby** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/26641387/9ff5ef88-bb5c-4ac9-b820-18e14ae4ea28)
No language model supports mathematical formulas.
