### ISSUE TITLE
[Bug] 我看很多参数都没有在 .env.example里，能否添加进去，并加上使用说明？

### ISSUE THREAD

**Issue by vual** [lobehub/lobe-chat#2912]
### 📦 部署环境

Docker

### 📌 软件版本

1.0.7

### 💻 系统环境

Other Linux

### 🌐 浏览器

Edge

### 🐛 问题描述

我看很多参数都没有在 .env.example里，能否添加进去，并加上使用说明？

**Comment by arvinxx** [comment]
具体哪些参数？有些参数是 internal 的，有些可能只是单纯忘记加了

**Comment by vual** [comment]
> 具体哪些参数？有些参数是 internal 的，有些可能只是单纯忘记加了

比如，数据库，s3那些，就没有。

**Comment by arvinxx** [comment]
@vual 哦 这个可以加下，忘记了。你可以先看文档 https://lobehub.com/docs/self-hosting/advanced/server-database
