### ISSUE TITLE
[Request] disable/hidden Clerk auth signup button

### ISSUE THREAD

**Issue by nexusdiscord** [lobehub/lobe-chat#2915]
### 🥰 Feature Description

Hello, I really like the Clerk look, can you provide an option to disable/hide the signup button on Clerk login?

### 🧐 Proposed Solution

like providing an option in the environment

**Comment by arvinxx** [comment]
it seems a good idea to have a feature flag to disable/ hide the clerk signup

**Comment by hassnain9166** [comment]
please add this feature too thank you

**Comment by hassni12** [comment]
---

🎉 **Success!** 🎉

I used the following code snippet to hide the footer action in the sign-in component, and it worked like a charm for me! 🚀

```
<ClerkLoaded>
  <SignIn
    path="/sign-in"
    appearance={{
      elements: {
        footerAction: { display: "none" },
      },
    }}
  />
</ClerkLoaded>
```

Give it a try and watch the magic happen! ✨💻

---

**Comment by nexusdiscord** [comment]
> 🎉 **Success!** 🎉
> 
> I used the following code snippet to hide the footer action in the sign-in component, and it worked like a charm for me! 🚀
> 
> ```
> <ClerkLoaded>
>   <SignIn
>     path="/sign-in"
>     appearance={{
>       elements: {
>         footerAction: { display: "none" },
>       },
>     }}
>   />
> </ClerkLoaded>
> ```
> 
> Give it a try and watch the magic happen! ✨💻

I am not familiar with this. Where should I put this code?

**Comment by arvinxx** [comment]
@hassni12 PR welcome with a feature flag
