### ISSUE TITLE
[Bug] 启用 S3 后无法向 Gemini 发送图片

### ISSUE THREAD

**Issue by sxjeru** [lobehub/lobe-chat#2918]
### 📦 部署环境

Vercel

### 📌 软件版本

1.0.7

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

目前启用 S3 会改变所有图片上传方式，实际上对于 Gemini 来说，原本的 Base64 上传方式更合适。

![image](https://github.com/lobehub/lobe-chat/assets/20513115/8ade2511-b4ac-4fb2-866e-0e5b6915f868)

**Comment by arvinxx** [comment]
重复 #3051
