### ISSUE TITLE
[Bug] Docker 似乎不支持反向代理

### ISSUE THREAD

**Issue by i-iooi-i** [lobehub/lobe-chat#292]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/1827701/888b05c1-d895-42ab-a340-d9ff8be50a14)

在内网环境中，检查代理与KEY是检测通过的。

![image](https://github.com/lobehub/lobe-chat/assets/1827701/ed64051d-c624-4979-9558-8709ccb4dfbf)
但是做了反向代理，通过域名访问，
相同的代理与KEY，检测会出现报错。 😗

**Comment by arvinxx** [comment]
似乎endpoint没生效… 得看看是为啥。你的反向代理是本地填写的吗？

**Comment by i-iooi-i** [comment]
> 似乎endpoint没生效… 得看看是为啥。你的反向代理是界面上填写的吗？

不是在界面上填写的哦。

群晖系统自带了反向代理工具，我是在群晖反代工具里填写的反代端口。

我在群晖Docker建了很多容器，都是用群晖自带的反向代理工具成功反代出去的，按理说不应该有问题才对。

**Comment by i-iooi-i** [comment]
> 似乎endpoint没生效… 得看看是为啥。你的反向代理是界面上填写的吗？

<img width="630" alt="iShot_2023-10-11_02 43 14" src="https://github.com/lobehub/lobe-chat/assets/1827701/a6630a3a-5a72-402a-9f96-56463d3ab099">
<img width="1457" alt="iShot_2023-10-11_02 41 48" src="https://github.com/lobehub/lobe-chat/assets/1827701/e24aa471-80a9-4ab5-98a1-4a2295d1057c">

这是LobeChat容器的日志，大佬看下有无帮助。

**Comment by arvinxx** [comment]
有可能是反代请求转发丢了header的问题，你能试下把请求头也一并转发吗？

**Comment by arvinxx** [comment]
之前用于放在请求头中的 AccessCode 使用了下划线，而 NGINX 会忽略下划线。已修复。等待发版后重新拉取最新版即可。

**Comment by i-iooi-i** [comment]
> 之前用于放在请求头中的 AccessCode 使用了下划线，而 NGINX 会忽略下划线。已修复。等待发版后重新拉取最新版即可。

大佬，我刚才拉取了13分钟前发布的镜像，外网访问，输入密码，验证通过了哈。 👍

**Comment by i-iooi-i** [comment]
> 之前用于放在请求头中的 AccessCode 使用了下划线，而 NGINX 会忽略下划线。已修复。等待发版后重新拉取最新版即可。
![image](https://github.com/lobehub/lobe-chat/assets/1827701/b4018893-5135-4c46-bb90-6ad84ace911a)
![image](https://github.com/lobehub/lobe-chat/assets/1827701/99d5609f-5956-4d1f-a6de-5667621d51a8)
![image](https://github.com/lobehub/lobe-chat/assets/1827701/ea003b41-1e6c-4f51-aa5e-7cd24742d443)
![image](https://github.com/lobehub/lobe-chat/assets/1827701/47b7b17c-0d7b-4895-a0e8-10fd3a171a6d)
![image](https://github.com/lobehub/lobe-chat/assets/1827701/854cf6e0-b616-4cfb-bea2-a6737bcbbfc5)
![image](https://github.com/lobehub/lobe-chat/assets/1827701/dac24d5a-2f73-470e-8618-956173626150)

但是还面临另外一个问题，就是现在外网使用反向代理的情况下，代理key请求还是出错的状态。
内网没有这个问题的。

**Comment by arvinxx** [comment]
@i-iooi-i 

<img width="669" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/2cec7641-0fc2-47a7-a9e6-c69bda95b944">

你这两是配反了吗？

**Comment by VectorZhao** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/16644993/70225cc6-74ab-4240-9c57-41bd5e811c25)
两个填反了。

我这里在环境变量里面提供了key和url，打开web输入密码直接聊天是没有反应的。只有自己在页面配置key和url才行

**Comment by VectorZhao** [comment]
可以了，OPENAI_PROXY_URL忘了加/v1

readme里面给出的示例没有/v1.

**Comment by arvinxx** [comment]
> readme里面给出的示例没有/v1

来个 PR 改下？

**Comment by i-iooi-i** [comment]
> @i-iooi-i
> 
> <img alt="image" width="669" src="https://user-images.githubusercontent.com/28616219/274141494-2cec7641-0fc2-47a7-a9e6-c69bda95b944.png">
> 你这两是配反了吗？

睡眠不足，人中午容易傻掉，hhhh

**Comment by VectorZhao** [comment]
> > readme里面给出的示例没有/v1
> 
> 来个 PR 改下？

修改了一下，没PR过不知道操作有没有问题

**Comment by i-iooi-i** [comment]
> @i-iooi-i
> 
> <img alt="image" width="669" src="https://user-images.githubusercontent.com/28616219/274141494-2cec7641-0fc2-47a7-a9e6-c69bda95b944.png">
> 你这两是配反了吗？

![image](https://github.com/lobehub/lobe-chat/assets/1827701/313d5907-399c-4636-8461-93933775c4f2)

完美，在环境变量里面填写好KEY，即便不在wed端设置key，也阔以访问了。 😍😍
