### ISSUE TITLE
[Request] Add MODEL_LIST variable to all models

### ISSUE THREAD

**Issue by ykangw** [lobehub/lobe-chat#2923]
### 🥰 Feature Description

Currently we have MODEL_LIST environment variable for some model providers, like OpenAI and OpenRouter AI. 
Can we add MODEL_LIST environment variable to all model providers?

### 🧐 Proposed Solution

Add XXX_MODEL_LIST environment variables, where XXX is the name of each model provider.

**Comment by arvinxx** [comment]
Please just say what provider you need. It's not a good idea to add all model list env.
