### ISSUE TITLE
[Bug] 智谱官网的apikey无法识别吗？

### ISSUE THREAD

**Issue by vual** [lobehub/lobe-chat#2928]
### 📦 部署环境

Docker

### 📌 软件版本

1.0.8

### 💻 系统环境

Other Linux

### 🌐 浏览器

Edge

### 🐛 问题描述

智谱官网的apikey无法识别吗？
![image](https://github.com/lobehub/lobe-chat/assets/25891219/8ad7933d-f5c8-4633-b3ce-378c2268f0e4)
![image](https://github.com/lobehub/lobe-chat/assets/25891219/7ca298a0-4fb9-4489-9c72-ef364300815c)

**Comment by arvinxx** [comment]
<img width="909" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/e1d9b290-9655-43d7-8b04-1704eaa108b2">

我试了下我这边可以用的？你是怎么配置的

**Comment by vual** [comment]
> <img alt="image" width="909" src="https://private-user-images.githubusercontent.com/28616219/340941738-e1d9b290-9655-43d7-8b04-1704eaa108b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NzcxOTYsIm5iZiI6MTcxODc3Njg5NiwicGF0aCI6Ii8yODYxNjIxOS8zNDA5NDE3MzgtZTFkOWIyOTAtOTY1NS00M2Q3LThiMDQtMTcwNGVhYTEwOGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA2MDEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMDZlZGE4MjA2MGY2N2YwYTYyODk0M2NhYWE4MmQ0MDU3ZDQzMmMyMjE1MjA5ZjAzZWU1YmY3Y2MyOTk2MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wzd7nAOpwlUROGG_lUG79IlrFIYIlxvSOYvPZJVzyJc">
> 我试了下我这边可以用的？你是怎么配置的

就是把智谱官网的apikey复制下来，填的设置里，没有多余的操作，我这边是智谱新版apikey

**Comment by vual** [comment]
> <img alt="image" width="909" src="https://private-user-images.githubusercontent.com/28616219/340941738-e1d9b290-9655-43d7-8b04-1704eaa108b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NzkwMzQsIm5iZiI6MTcxODc3ODczNCwicGF0aCI6Ii8yODYxNjIxOS8zNDA5NDE3MzgtZTFkOWIyOTAtOTY1NS00M2Q3LThiMDQtMTcwNGVhYTEwOGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA2MzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MzQyMDdiODhiN2IxMmI4NDZjMDk5YWRlZjEzNGMxY2QwYmUxOTdjNDVlZDQwZjA3NjRjNDk0N2Y4YzlkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pBArYib_hRrDNCSsuP6hrjOIJv2IWt63WCZp8y5CXX4">
> 我试了下我这边可以用的？你是怎么配置的

我知道了，开启客户端模式，就不行了，是不是客户端模式还未实现？

**Comment by arvinxx** [comment]
> 是不是客户端模式还未实现？

@cy948 帮忙看看？

**Comment by qyg20** [comment]
复制的看看前后有没有空格去掉，智商支持客户端模式。
