### ISSUE TITLE
[Request]  deploying lobeChat on my Raspberry Pi 4B

### ISSUE THREAD

**Issue by KingDoum** [lobehub/lobe-chat#2929]
### 🥰 需求描述

Hello, developer, I've observed that in the future, we plan to use Postgres as our server-side database. When installing it with Docker, will there be any issues with installing Postgres itself?

I'm deploying lobeChat on my Raspberry Pi 4B, and I'm concerned that using Postgres might prevent the deployment onto the Raspberry Pi. Could you kindly address my concerns?

### 🧐 解决方案

all

**Comment by arvinxx** [comment]
https://lobehub.com/docs/self-hosting/advanced/server-database
