### ISSUE TITLE
[Bug] ollama 无法取消客户端模式

### ISSUE THREAD

**Issue by qyg20** [lobehub/lobe-chat#2934]
### 📦 Environment

Docker

### 📌 Version

v1.0.6

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/82088525/95416bec-be73-4690-aea3-899e03cd0e1e)

**Comment by CooperZhuang** [comment]
我这边遇到的问题是无法打开客户端模式，v1.0.13

The problem I'm having on my side is that I can't open the client mode, v1.0.13

**Comment by CooperZhuang** [comment]
> 我这边遇到的问题是无法打开客户端模式，v1.0.13
> 
> The problem I'm having on my side is that I can't open the client mode, v1.0.13我这边遇到的问题是无法打开客户端模式，v1.0.13

忘记我，输入ollama 的 api key 后正常了。
Forget me, it works fine after entering the api key for ollama.

**Comment by qyg20** [comment]
> > 我这边遇到的问题是无法打开客户端模式，v1.0.13
> > The problem I'm having on my side is that I can't open the client mode, v1.0.13
> 
> 忘记我，输入ollama 的 api key 后正常了。 Forget me, it works fine after entering the api key for ollama.

ollama 没有输入apikey 的地方啊，升级到v1.0.13还是有相同问题，看了一下代码，好像是写死了。
