### ISSUE TITLE
[Bug] response.undefined

### ISSUE THREAD

**Issue by fomalhaut1998** [lobehub/lobe-chat#2936]
### 📦 部署环境

Vercel

### 📌 软件版本

v1.0.11

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/lobehub/lobe-chat/assets/53938635/569fea27-9124-402c-8b48-384375862785)
部分模型（Gemini 1.5 Pro、Qwen2-72b-instruct、Qwen-Max-longContext等）对话生成过程中会突然出现“response.undefined”，经过测试，这个出现的频率最近变得很高，几乎每次都会出现这个问题。

### 📷 复现步骤

直接输入对应模型的API，然后进行对话即可

**Comment by arvinxx** [comment]
是用的官方模型吗？

**Comment by fomalhaut1998** [comment]
> 是用的官方模型吗？

是的，Gemini用的是Google官方的API，然后Qwen用的是阿里云官方的API

**Comment by bt-nia** [comment]
I have the same issue. 
I see this with an Azure deployment. The response comes in, but at a certain point, the whole response disappears and the error is shown.
