### ISSUE TITLE
[Bug] Clerk does not work in a docker container

### ISSUE THREAD

**Issue by MihailGalay** [lobehub/lobe-chat#2937]
### 📦 Environment

Docker

### 📌 Version

v1.0.11

### 💻 Operating System

Other

### 🌐 Browser

Chrome, Firefox

### 🐛 Bug Description

I add environment variables for Clerk to the docker composition: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY + CLERK_SECRET_KEY
And I get an error in the browser:
**Application error: a client-side exception has occurred (see the browser console for more information).**

And in the console errors:
74384-4aad2cedfcfb56ef.js:1 Error: @clerk/nextjs: Missing publishableKey. You can get your key at https://dashboard.clerk.com/last-active?path=api-keys.
    at Object.throwMissingPublishableKeyError (31535-f5b8ff63be366f76.js:1:38653)
    at 31535-f5b8ff63be366f76.js:1:35495
    at rE (8cfc3720-8920feddc37dd012.js:1:40346)
    at iZ (8cfc3720-8920feddc37dd012.js:1:117031)
    at ia (8cfc3720-8920feddc37dd012.js:1:95167)
    at 8cfc3720-8920feddc37dd012.js:1:94989
    at il (8cfc3720-8920feddc37dd012.js:1:94996)
    at oJ (8cfc3720-8920feddc37dd012.js:1:92352)
    at oZ (8cfc3720-8920feddc37dd012.js:1:91771)
    at MessagePort.M (74384-4aad2cedfcfb56ef.js:1:92012)
(anonymous) @ 74384-4aad2cedfcfb56ef.js:1
8cfc3720-8920feddc37dd012.js:1 Uncaught Error: Minified React error #423; visit https://react.dev/errors/423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at iZ (8cfc3720-8920feddc37dd012.js:1:118354)
    at ia (8cfc3720-8920feddc37dd012.js:1:95167)
    at 8cfc3720-8920feddc37dd012.js:1:94989
    at il (8cfc3720-8920feddc37dd012.js:1:94996)
    at oJ (8cfc3720-8920feddc37dd012.js:1:92352)
    at oZ (8cfc3720-8920feddc37dd012.js:1:91771)
    at MessagePort.M (74384-4aad2cedfcfb56ef.js:1:92012)

I debugged a little, it looks like the client environment variables are not set from the environment variables (Docker).

### 📷 Recurrence Steps

Add keys for clerics to the docker-compose yaml file: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY + CLERK_SECRET_KEY

### 🚦 Expected Behavior

The clerk should start working.

**Comment by arvinxx** [comment]
it's a known issue, Docker don't support `NEXT_PUBLIC_` env.

**Comment by bikerduweb** [comment]
Docker don't support NEXT_PUBLIC_XXX env variables, but the ClerkProvider component do accept parameters and allow us to provide the publishableKey as a parameter. So it could allow to provide the publishable key from another ENV variable (for example CLERK_PUBLISHABLE_KEY)
Cf. https://clerk.com/docs/components/clerk-provider

```
return (
    <ClerkProvider
      appearance={updatedAppearance}
      localization={localization}
      publishableKey={process.env.CLERK_PUBLISHABLE_KEY}
      signUpUrl={!enableClerkSignUp ? '/login' : '/signup'} // Redirect sign-up to sign-in if disabled
    >
      {children}
      <UserUpdater />
    </ClerkProvider>
  );
```

Could be a solution to this problem and allow to use docker? I'm not able to do PR as I don't have enough knowledge of Lobechat internals, but maybe someone could test this?
