### ISSUE TITLE
[Bug] user auth 和 access code 冲突

### ISSUE THREAD

**Issue by z-mio** [lobehub/lobe-chat#2938]
### 📦 部署环境

Vercel

### 📌 软件版本

v1.0.11

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

配置 `user auth` 后 `access code` 不会默认失效, 导致上传文件时错误
![image](https://github.com/lobehub/lobe-chat/assets/52116367/8a692c33-9095-4f46-a8c3-e1e940c928b8)

### 📷 复现步骤

同时配置 `user auth` 和 `access code`

### 🚦 期望结果

配置 `user auth` 后 `access code` 默认失效

**Comment by cy948** [comment]
`user auth` 指 clerk 还是 nextauth？

**Comment by z-mio** [comment]
clerk, 没测试过nextauth, 不过应该是环境变量问题
同时添加 `user auth` 和 `access code` 的环境变量, 会冲突

**Comment by gaarry** [comment]
确实，删除 access code 的环境变量，照片就能正常上传了。
