### ISSUE TITLE
[Bug] 智普清言的glm-4v模型发送图片显示图片输入格式/解析错误

### ISSUE THREAD

**Issue by XHB-111** [lobehub/lobe-chat#2945]
### 📦 Environment

Docker

### 📌 Version

v1.0.13

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

使用智普清言的glm-4v进行图像识别，发送图片显示图片输入格式/解析错误。我换了gpt4o就可以正常发送图片
![屏幕截图 2024-06-20 113414](https://github.com/lobehub/lobe-chat/assets/128414699/9fe83f90-43a0-451f-8a31-b0d91edde818)

![屏幕截图 2024-06-20 113600](https://github.com/lobehub/lobe-chat/assets/128414699/f1cbe031-2b3b-4e36-8d63-fe56ec967cdb)

**Comment by sxjeru** [comment]
这是在用 oneapi 吗，可以换用官方的 api 配合 lobechat 的原生智谱清言试试。

![image](https://github.com/lobehub/lobe-chat/assets/20513115/2914a681-4cac-42a2-b986-f25a3275dda9)

**Comment by arvinxx** [comment]
这种不算是 LobeChat 的问题
