### ISSUE TITLE
[Bug] 配置服务端数据库后无法使用

### ISSUE THREAD

**Issue by cfwl1111** [lobehub/lobe-chat#2948]
### 📦 部署环境

Docker

### 📌 软件版本

v1.0.13

### 💻 系统环境

Other

### 🌐 浏览器

Other

### 🐛 问题描述

按控制台的错误来看像是 Clerk 相关配置出了问题，该如何处理呢

<img width="1416" alt="企业微信截图_20240620153454" src="https://github.com/lobehub/lobe-chat/assets/45492444/4707aa45-4813-4020-b779-2cc56cb67e27">
<img width="1918" alt="企业微信截图_20240620153632" src="https://github.com/lobehub/lobe-chat/assets/45492444/3000b35a-6b37-47ac-a897-e9be08d4b79b">

### 📝 补充信息
Postgres 数据库也是部署在 docker 上

**Comment by cfwl1111** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/45492444/a07f285b-d9eb-4181-977a-2a60a1ef3596)

sorry，才看到文档提示

**Comment by arvinxx** [comment]
你要自己打docker镜像
