### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zhogu** [lobehub/lobe-chat#2950]
### 📦 部署环境

Docker

### 📌 软件版本

v1.0.13

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

donot support `http` endpoint for azure openai models :

Route: [azure] AgentRuntimeError: {
  cause: undefined,
  message: 'Cannot connect to http://[my azure openai proxy]/openai/deployments/gpt-4/chat/completions?api-version=2023-07-01-preview while allowInsecureConnection is false.',
  name: 'Error'
}

The endpoint is a my personal reverse proxy, which will redirect the request to multiple azure openai endpoints. The proxy only support http request. But I cannot find a way to set  `allowInsecureConnection` as true.

**Comment by arvinxx** [comment]
I think it's not an issue for LobeChat. You need to think about why not use https

**Comment by zhogu** [comment]
> I think it's not an issue for LobeChat. You need to think about why not use https

Alright. The http proxy works well when I used openai python lib to access it. I can understand the error msg is not produced by the code in this repo but some depended libs.  Could you provide some information on it?

**Comment by zhogu** [comment]
According to the error msg, it might be possible to set `allowInsecureConnection` as true. So I wonder how to make it.

**Comment by arvinxx** [comment]
I don't think is a good idea to add this params in the LobeChat main repo, maybe you can change it by yourself https://github.com/lobehub/lobe-chat/blob/main/src/libs/agent-runtime/azureOpenai/index.ts

**Comment by zhogu** [comment]
> I don't think is a good idea to add this param in the LobeChat main repo, maybe you can change it by yourself https://github.com/lobehub/lobe-chat/blob/main/src/libs/agent-runtime/azureOpenai/index.ts

Thanks, I agree with you.
