### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by czh020110** [lobehub/lobe-chat#2956]
### 📦 部署环境

Other

### 📌 软件版本

社区版

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

搜索引擎插件无法正常使用

### 📷 复现步骤

如图报错：{
  "error": {
    "message": "Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'. (request id: 20240621004857147654774PGwFx8wC)",
    "type": "invalid_request_error",
    "param": "messages.[1].role",
    "code": null
  },
![image](https://github.com/lobehub/lobe-chat/assets/106853837/b3706fc2-78a0-4994-9b36-c1bdea6db7cf)

### 🚦 期望结果

希望能正常返回

**Comment by arvinxx** [comment]
是不是开了历史记录限制的关系

**Comment by arvinxx** [comment]
现在还有吗？
