### ISSUE TITLE
[Bug] CF R2--S3图片上传失败

### ISSUE THREAD

**Issue by AiharaMahiru** [lobehub/lobe-chat#2965]
### 📦 Environment

Vercel

### 📌 Version

1.1.3

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

这是我的配置信息（已处理），当我上传文件时，遇到“文件上传失败，请检查网络连接或稍后再试
详情: TRPCClientError: UNAUTHORIZED”的错误，日志为
'''
[POST] [middleware: "src/middleware"] /trpc/edge/upload.createS3PreSignedUrl status=200
[POST] /trpc/edge/upload.createS3PreSignedUrl?batch=1&nxtPtrpc=upload.createS3PreSignedUrl status=401
Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
TRPCError: UNAUTHORIZED
at (src/libs/trpc/middleware/password.ts:21:12)
at (node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:152:0)
at (node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:182:0)
at (node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:137:0)
at (node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:195:0)
at (node_modules/@trpc/server/dist/adapters/fetch/fetchRequestHandler.mjs:32:0)
at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:195:0)
at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:124:0)
at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:257:0) {
code: 'UNAUTHORIZED',
name: 'TRPCError'
}
'''

### 📷 Recurrence Steps

![screen](https://github.com/lobehub/lobe-chat/assets/124856966/c9470cc6-cf07-4090-8500-4f5b6f946109)

**Comment by arvinxx** [comment]
是不是还有access code

**Comment by AiharaMahiru** [comment]
> 是不是还有access code

还真是的，非常感谢。

**Comment by AHA1GE** [comment]
> > 是不是还有access code
> 
> 还真是的，非常感谢。

我遇到了相同问题。请问是如何解决的？

**Comment by LarkinZero** [comment]
我这里的情况是，即使配置ACCESS_CODE了也一样会报错
```
Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
[TRPCError: UNAUTHORIZED] { code: 'UNAUTHORIZED', name: 'TRPCError' }
```

**Comment by wcu1117** [comment]
> 我这里的情况是，即使配置ACCESS_CODE了也一样会报错
> 
> ```
> Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
> [TRPCError: UNAUTHORIZED] { code: 'UNAUTHORIZED', name: 'TRPCError' }
> ```

解决了吗

**Comment by LarkinZero** [comment]
> > 我这里的情况是，即使配置ACCESS_CODE了也一样会报错
> > ```
> > Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
> > [TRPCError: UNAUTHORIZED] { code: 'UNAUTHORIZED', name: 'TRPCError' }
> > ```
> 
> 解决了吗
解决了，应该是我操作问题。环境变量里有ACCESS_CODE了。
但是在lobechat的Web界面里，你需要在左上角头像，点击应用设置-通用设置底部的系统设置里，把访问密码填上，这个字段就是ACCESS_CODE的值。
<img width="800" alt="image" src="https://github.com/user-attachments/assets/a1d7d321-cdd6-4531-8fc5-fb60925c1a41">

**Comment by wcu1117** [comment]
> > > 我这里的情况是，即使配置ACCESS_CODE了也一样会报错
> > > ```
> > > Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
> > > [TRPCError: UNAUTHORIZED] { code: 'UNAUTHORIZED', name: 'TRPCError' }
> > > ```
> > 
> > 
> > 解决了吗
> 
> 解决了，应该是我操作问题。环境变量里有ACCESS_CODE了。 但是在lobechat的Web界面里，你需要在左上角头像，点击应用设置-通用设置底部的系统设置里，把访问密码填上，这个字段就是ACCESS_CODE的值。 <img alt="image" width="800" src="https://private-user-images.githubusercontent.com/6387162/362089680-a1d7d321-cdd6-4531-8fc5-fb60925c1a41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTEzNDcsIm5iZiI6MTcyNDgxMTA0NywicGF0aCI6Ii82Mzg3MTYyLzM2MjA4OTY4MC1hMWQ3ZDMyMS1jZGQ2LTQ1MzEtOGZjNS1mYjYwOTI1YzFhNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDIxMDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE1YmFiZWEzNTIzZGM0ZWYxMTA2ZDY0MzJkYWVhODFiOGQzYjNmNzIzMDhlYjlmNGNlYjVlNDI0ZDk0MDQ3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.URoZ0lX29rQC6_TTQlK0fb1x1SMxcJhCXSZjdfKsr88">

有点离谱，还要这样配置，我更新到最新版看看，好像这个bug修复了
