### ISSUE TITLE
[Request] Clarify model list documentation

### ISSUE THREAD

**Issue by CGamesPlay** [lobehub/lobe-chat#2972]
### 🥰 Feature Description

On `docs/self-hosting/advanced/model-list.mdx`, it doesn't actually say *where* to put the model list configuration. By searching through github issues I found that it's going to be in a model-specific environment variable. It would be helpful if this page linked to the specific documentation for these providers.

### 🧐 Proposed Solution

Something like this:

```
# Model List

LobeChat supports customizing the model list during deployment. This configuration is done for each [model provider](model-providers). You can use...

[model-providers]: /docs/self-hosting/environment-variables/model-provider
```

**Comment by arvinxx** [comment]
In environment
