### ISSUE TITLE
[Request] Claude Artifacts

### ISSUE THREAD

**Issue by Aunali321** [lobehub/lobe-chat#2981]
### 🥰 Feature Description

Claude.ai added Artifacts feature today, it forms 2 windows, this is a cool feature, could you consider adding it to lobechat?

![image](https://github.com/lobehub/lobe-chat/assets/48486084/0e0198ed-1b6f-433f-86f4-d6204c399e11)

### 🧐 Proposed Solution

Implement it in lobe chat

**Comment by arvinxx** [comment]
We will consider to add this in LobeChat Cloud as an advanced feature

**Comment by Aunali321** [comment]
What if i contribute this part myself? Would be open to merge it and benefit thousands of users?

**Comment by arvinxx** [comment]
@Aunali321 You can write a RFC firstly and I will review it. If the design is good enough, the answer is yes.
