### ISSUE TITLE
[Bug] OAuth SSO Disabled When Using Only NEXT_AUTH_SECRET

### ISSUE THREAD

**Issue by nikkoxgonzales** [lobehub/lobe-chat#2986]
### 📦 Environment

Docker

### 📌 Version

1.1.4

### 💻 Operating System

Ubuntu

### 🌐 Browser

Edge

### 🐛 Bug Description

The application incorrectly disables Single Sign-On (SSO) functionality when only the NEXT_AUTH_SECRET environment variable is set. This occurs despite the deprecation message suggesting that setting NEXT_AUTH_SECRET should be sufficient for SSO to work.

### 📷 Recurrence Steps

1. Set up the application with only the NEXT_AUTH_SECRET environment variable.
2. Attempt to use OAuth SSO functionality.
3. Observe that SSO is disabled.

### 🚦 Expected Behavior

OAuth SSO should remain functional when NEXT_AUTH_SECRET is set, without requiring the deprecated ENABLE_OAUTH_SSO variable.

### 📝 Additional Information

- The application log shows the following deprecation message:
- "'ENABLE_OAUTH_SSO' is deprecated and will be removed in LobeChat 1.0. just set 'NEXT_AUTH_SECRET' enough',"
- This message implies that setting NEXT_AUTH_SECRET should be sufficient for SSO to work.
- The current behavior contradicts the deprecation message, as SSO is disabled when only NEXT_AUTH_SECRET is set.
- This issue may impact users who have removed the ENABLE_OAUTH_SSO variable based on the deprecation notice.

**Comment by cy948** [comment]
We already notice this problem and it will be fixed at #2935
