### ISSUE TITLE
[Bug] 手机端界面似乎存在一些适配问题

### ISSUE THREAD

**Issue by i-iooi-i** [lobehub/lobe-chat#299]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/1827701/0c8643a2-3652-4aed-a6d9-7db6bded5b48)

手机：iPhone 15 Pro
操作：将 LobeChat 添加到主屏幕
问题：页面下方的区域出现了大片的空白，不确定是否是适配问题。

### 🚦 期望结果 | Expected Behavior

无

### 📷 复现步骤 | Recurrence Steps

无

### 📝 补充信息 | Additional Information

无

**Comment by canisminor1990** [comment]
看一下版本号

**Comment by i-iooi-i** [comment]
> 提供一下版本号，是最新的么

刚才测试了一下，在 LobeChat v0.86.1   LobeChat v0.86.2  上面都存在这个问题。
ios版本是最新的 17.0.3

**Comment by canisminor1990** [comment]
好的 我排查下
