### ISSUE TITLE
[Bug] 1.1.6部署错误

### ISSUE THREAD

**Issue by ZeroDeng01** [lobehub/lobe-chat#2997]
### 📦 部署环境

Vercel

### 📌 软件版本

1.1.6

### 💻 系统环境

Windows, macOS, iOS, Android

### 🌐 浏览器

Chrome

### 🐛 问题描述

Vercel（免费方案）部署报错，错误信息如下：
```
$ bun run db:migrate
$ MIGRATION_DB=1 tsx scripts/migrateServerDB/index.ts
✅ database migration pass.
Traced Next.js server files in: 34.76ms
Created all serverless functions in: 12.870s
Collected static files (public/, static/, .next/static): 76.671ms
Build Completed in /vercel/output [6m]
Deploying outputs...
Injected preview comments middleware, you can disable this in your project settings.
Error: Builder returned invalid maxDuration value for Serverless Function "trpc/tools/[trpc]". Serverless Functions must have a maxDuration between 1 and 60 for plan hobby. : https://vercel.com/docs/concepts/limits/overview#serverless-function-execution-timeout
```
![image](https://github.com/lobehub/lobe-chat/assets/19732560/f8cdd89f-f2e1-47dc-81cd-40bc67646334)

### 📷 复现步骤

正常GitHub通过sync fork同步部署

### 🚦 期望结果

正常部署

**Comment by breakstring** [comment]
> ### 📦 部署环境
> Vercel
> 
> ### 📌 软件版本
> 1.1.16
> 
> ### 💻 系统环境
> Windows, macOS, iOS, Android
> 
> ### 🌐 浏览器
> Chrome
> 
> ### 🐛 问题描述
> Vercel（免费方案）部署报错，错误信息如下：
> 
> ```
> $ bun run db:migrate
> $ MIGRATION_DB=1 tsx scripts/migrateServerDB/index.ts
> ✅ database migration pass.
> Traced Next.js server files in: 34.76ms
> Created all serverless functions in: 12.870s
> Collected static files (public/, static/, .next/static): 76.671ms
> Build Completed in /vercel/output [6m]
> Deploying outputs...
> Injected preview comments middleware, you can disable this in your project settings.
> Error: Builder returned invalid maxDuration value for Serverless Function "trpc/tools/[trpc]". Serverless Functions must have a maxDuration between 1 and 60 for plan hobby. : https://vercel.com/docs/concepts/limits/overview#serverless-function-execution-timeout
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/19732560/342056912-f8cdd89f-f2e1-47dc-81cd-40bc67646334.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzg1NDAsIm5iZiI6MTcxOTEzODI0MCwicGF0aCI6Ii8xOTczMjU2MC8zNDIwNTY5MTItZjhjZGQ4OWYtZjJlMS00N2RjLTgxY2QtNDBiYzY3NjQ2MzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEwMjQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YWNhZjkzODllMDlkMzk5YmE2ODliOTU4NGExYzdmNWQ3N2I1MGJiMWRhMDliYjQyYjE1NzM0OWExZGUzMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hc55QC4yBXGh-LlzAdx4I29hf7ioBLC2B3IM3L7xGgU)
> 
> ### 📷 复现步骤
> 正常GitHub通过sync fork同步部署
> 
> ### 🚦 期望结果
> 正常部署
> 
> ### 📝 补充信息
> _No response_

Same issue here.
:(
