### ISSUE TITLE
[Bug] Claude 3.5 在图片的内容分析上有问题

### ISSUE THREAD

**Issue by breakstring** [lobehub/lobe-chat#3001]
### 📦 Environment

Vercel

### 📌 Version

1.1.6

### 💻 Operating System

macOS

### 🌐 Browser

Other

### 🐛 Bug Description

无法使用 Claude 3.5 解析图片内容，OpenAI 则没问题。

### 📷 Recurrence Steps

1. 选择模型为 Claude 3.5，插入图片到聊天窗口中，输入 prompt 请求解析。
2. 报错提示如下：
、、、
{
  "error": {
    "error": {
      "type": "error",
      "error": {
        "type": "invalid_request_error",
        "message": "messages.0.content.1.image.source.base64.media_type: Input should be 'image/jpeg', 'image/png', 'image/gif' or 'image/webp'"
      }
    },
    "status": 400,
    "headers": {
      "via": "1.1 google",
      "date": "Sun, 23 Jun 2024 23:28:03 GMT",
      "connection": "keep-alive",
      "request-id": "req_01BhNKq3EqhyioScf16uDPm5",
      "content-type": "application/json",
      "content-length": "193",
      "x-should-retry": "false",
      "x-cloud-trace-context": "b8d7344e29c2adb51dfd7c01eb5a9e9f"
    }
  },
  "endpoint": "https://api.anthropic.com",
  "provider": "anthropic"
}
、、、
![image](https://github.com/lobehub/lobe-chat/assets/14105911/56f08892-2963-424b-bf11-6d6419d88893)

### 🚦 Expected Behavior

2. 返回解析的内容

**Comment by arvinxx** [comment]
看报错应该是 Anthropic 的api不支持base64 的图片，必须要可访问的 url 才能识别。你配置下s3应该就好了

**Comment by breakstring** [comment]
> 看报错应该是 Anthropic 的api不支持base64 的图片，必须要可访问的 url 才能识别。你配置下s3应该就好了

我是采用的服务端数据库存储方案，目前是华为云兼容 S3 的 OBS。
BTW: 请求 OpenAI 正常。

**Comment by arvinxx** [comment]
那估计是个 bug，我晚点看看

**Comment by breakstring** [comment]
> 那估计是个 bug，我晚点看看

Any update?

**Comment by arvinxx** [comment]
https://docs.anthropic.com/en/docs/build-with-claude/vision#can-claude-read-image-urls 查阅了下官方文档， Claude API 目前不支持传入 url 来识别，如果要使用必须要传输 base64。这么看和 Google 的 Gemini 问题一样，可能还是得用 base64 传输

**Comment by hominsu** [comment]
any update?

**Comment by huangyafei** [comment]
确实是个影响挺大的问题，请问有什么进展了么？

**Comment by arvinxx** [comment]
Here is the PR to fix similar issue: https://github.com/lobehub/lobe-chat/pull/3370

**Comment by wxy-skye** [comment]
The problem still persists. The server-side mode cannot use Claude for image recognition. It can only use GPT.

**Comment by hlc1209** [comment]
+1，严重影响日常使用

**Comment by adminewacc** [comment]
me too, pls fix that

**Comment by RetrainIt** [comment]
+1，严重影响日常使用

**Comment by RetrainIt** [comment]
你的来信我已收到，谢谢。

**Comment by 2019YKL** [comment]
S3有办法本地的那个S3么，我识图目前还没成功过（
![CleanShot 2024-09-04 at 17 54 26@2x](https://github.com/user-attachments/assets/8323fe0c-e60a-49dc-855e-461761c394f8)

**Comment by Stardust-SJF** [comment]
I wonder if it is possible to use base64 to directly upload images to the model provider instead of uploading images into the knowledge database, or convert the image to base64 after retrieving it from S3 storage and then encode (to base 64) and send them to model providers?

**Comment by adminewacc** [comment]
> I wonder if it is possible to use base64 to directly upload images to the model provider instead of uploading images into the knowledge database, or convert the image to base64 after retrieving it from S3 storage and then encode (to base 64) and send them to model providers?

i solved it

**Comment by adminewacc** [comment]
> S3有办法本地的那个S3么，我识图目前还没成功过（ ![CleanShot 2024-09-04 at 17 54 26@2x](https://private-user-images.githubusercontent.com/51532948/364326260-8323fe0c-e60a-49dc-855e-461761c394f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NjE4MjksIm5iZiI6MTcyNTY2MTUyOSwicGF0aCI6Ii81MTUzMjk0OC8zNjQzMjYyNjAtODMyM2ZlMGMtZTYwYS00OWRjLTg1NWUtNDYxNzYxYzM5NGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDIyMjUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNThhNzljMTJkYzQwOWFmZmExMzdlMWM1M2IyMzIzZThjYmVkZTEzZDNlMTUwNzFkYTczODdkYzgzNjlmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nquZTBW6gLk_PuEYNMyc9i8q6ObPdk8_0LAiCxDY5w0)

in this case i think that it is showing this error because of your api key quota
