### ISSUE TITLE
[BUG]服务端数据库模式下用户的话题似乎无法同步

### ISSUE THREAD

**Issue by breakstring** [lobehub/lobe-chat#3005]
抱歉，刚手机上发现的，用Github APP没法打开issue模板。

服务端部署方式:Vercel
版本:1.1.6
客户端1: Mac PWA
客户端2: Android PWA

复现步骤:
1，客户端1上登录并聊天
2，客户端2上同一账号登录
3，客户端2上能看到消息数量，但是消息列表中没有聊天记录

![IMG_20240624_122245.jpg](https://github.com/lobehub/lobe-chat/assets/14105911/8f6c5e40-d1ab-4c84-b62c-859848cb843d)

![Screenshot_2024-06-24-12-22-15-709_com.microsoft.emmx.jpg](https://github.com/lobehub/lobe-chat/assets/14105911/b3d44218-39e1-4669-880a-a96249441a27)

**Comment by arvinxx** [comment]
这个应该是pwa 下的一个auth问题，你试试切到发现，然后再切回会话？

**Comment by breakstring** [comment]
> 这个应该是pwa 下的一个auth问题，你试试切到发现，然后再切回会话？

不行。
1，我现在在客户端2上直接随便聊聊，列表中也不出现我聊的内容
2，从发现里随便找个助手添加到对话并聊天，可以出现在列表中。但是关掉PWA并重新打开后刚才那个聊天也就不见了。

**Comment by arvinxx** [comment]
你看下日志那边有没有什么报错

**Comment by breakstring** [comment]
> 你看下日志那边有没有什么报错

刚更新到 1.1.7，Android PWA 上测试了一下看到后台的确有错误：
<img width="1170" alt="image" src="https://github.com/lobehub/lobe-chat/assets/14105911/2e547b31-553a-43cb-986b-dbbec8f73b83">

BTW： 注意到刚才在 Android PWA 上那条消息出现在了 Mac PWA 上，但是 Android 上没有。

**Comment by gaspire** [comment]
@breakstring  如何配置服务端数据库模式，我修改了以下环境变量，启动报401错误：

**Comment by breakstring** [comment]
> @breakstring  如何配置服务端数据库模式，我修改了以下环境变量，启动报401错误：
> NEXT_PUBLIC_SERVICE_MODE=server
> DATABASE_URL=postgres://:@127.0.0.1:5432/lobe
> KEY_VAULTS_SECRET=BT1PaMM8LWsP2FfuMaMlo59niX4/woVZTgEYimgu3Jo=

呃 我是Vercel用的Vercel的serverless数据库倒是没有问题……你要不还是查查看日志的错误信息排查下吧
