### ISSUE TITLE
[Bug] 关于docker build的问题

### ISSUE THREAD

**Issue by jaychoubaby** [lobehub/lobe-chat#3008]
### 📦 部署环境

Docker

### 📌 软件版本

1.0.6

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

我在使用docker bulid -t编译的时候，一直报错，首先是lint的检查报错，接着又是@clerk/types的报错，我用的是1.0.6版本的代码进行本地编译，可以正常运行，可是当我打镜像的时候就出现了这个问题，我想请问你们开发在docker bulid的时候是否遇到过这个问题，有没有好的解决办法，感谢回复。

### 📷 复现步骤

docker bulid -t

### 🚦 期望结果

正确编译

**Comment by Sun-drenched** [comment]
详细的报错信息？

**Comment by jaychoubaby** [comment]
这是当我设置跳过lint检查之后的报错信息：

` => ERROR [builder 6/6] RUN npm run build:docker                                                                                                                                                   296.5s 
------
 > [builder 6/6] RUN npm run build:docker:
4.008
4.008 > @lobehub/chat@1.0.7 build:docker
4.008 > DOCKER=true next build && npm run build-sitemap
4.008
8.291 Attention: Next.js now collects completely anonymous telemetry regarding usage.
8.291 This information is used to shape Next.js' roadmap and prioritize features.
8.291 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
8.291 https://nextjs.org/telemetry
8.291
8.539   ▲ Next.js 14.2.4
8.539
8.725    Creating an optimized production build ...
9.398  ✓ (pwa) Compiling for server...
9.410  ✓ (pwa) Compiling for server...
9.421  ✓ (pwa) Compiling for client (static)...
9.425  ○ (pwa) Service worker: /app/public/sw.js
9.425  ○ (pwa)   URL: /sw.js
9.425  ○ (pwa)   Scope: /
256.1  ✓ Compiled successfully
256.1    Skipping linting
256.1    Checking validity of types ...
295.3 Failed to compile.
295.3
295.3 ./src/app/(main)/profile/[[...slugs]]/Client.tsx:4:32
295.3 Type error: Cannot find module '@clerk/types' or its corresponding type declarations.
295.3
295.3   2 |
295.3   3 | import { UserProfile } from '@clerk/nextjs';
295.3 > 4 | import { ElementsConfig } from '@clerk/types';
295.3     |                                ^
295.3   5 | import { createStyles } from 'antd-style';
295.3   6 | import { memo } from 'react';
295.3   7 |
295.7 npm notice
295.7 npm notice New minor version of npm available! 10.7.0 -> 10.8.1
295.7 npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
295.7 npm notice To update run: npm install -g npm@10.8.1
295.7 npm notice
------
Dockerfile:51
--------------------
  49 |
  50 |     # run build standalone for docker version
  51 | >>> RUN npm run build:docker
  52 |
  53 |     ## Production image, copy all the files and run next
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build:docker" did not complete successfully: exit code: 1`

**Comment by jaychoubaby** [comment]
我直接fork代码之后通过 github action进行docker build，报错如下：

` - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 79)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 83)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 85)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 88)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 89)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 90)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 93)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 94)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 95)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 98)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 101)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 104)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 107)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 108)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 111)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 114)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 117)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 120)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 121)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 124)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 127)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 130)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 133)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 136)
Dockerfile:51
--------------------
  49 |     
  50 |     # run build standalone for docker version
  51 | >>> RUN npm run build:docker
  52 |     
  53 |     ## Production image, copy all the files and run next
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build:docker" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c npm run build:docker" did not complete successfully: exit code: 1`

**Comment by jaychoubaby** [comment]
是我的问题，我重新编译可以过了
