### ISSUE TITLE
[Request] 我按文档部署了docker版本但是发现文档和项目不太一致，让我对使用路径产生很大的疑惑

### ISSUE THREAD

**Issue by bakamake** [lobehub/lobe-chat#3011]
### 🥰 需求描述

![Weixin Screenshot_20240624181719](https://github.com/lobehub/lobe-chat/assets/159852463/fc5044c2-cc94-456f-905b-e7d75aa8cc81)
https://github.com/lobehub/lobe-chat/assets/34400653/bae262d6-0d49-47f3-bc9c-356cf6f3f34e
这两张图片的不一致让我没办法知道从哪里输入deepseek的api

### 🧐 解决方案

请作者大大们告诉我应该在哪里用我的api

**Comment by arvinxx** [comment]
右上角是助手设置。你要进入应用设置，在左上角
