### ISSUE TITLE
[Bug] Issue after login to server side version

### ISSUE THREAD

**Issue by xenstar** [lobehub/lobe-chat#3012]
### 📦 Environment

Vercel

### 📌 Version

 v1.1.7

### 💻 Operating System

Windows

### 🌐 Browser

Chrome, Other

### 🐛 Bug Description

So after login to the account, this page is popup and then keep opening. Even click on close button, will show again

![image](https://github.com/lobehub/lobe-chat/assets/55502651/4d5d4974-df49-4c94-82b9-f0f9f5c5a6f9)

domain.xyz/settings/modal?agent=&session=inbox&tab=agent&topic=tpc_VCtxiOr1NZot

### 📷 Recurrence Steps

To solve the issue, I have to again open the my main domain, and then the link switch to domain.com/chat?agent= then the issue is solved.

### 🚦 Expected Behavior

After new user sign up, and sign it, it should take them to the domain.com/chat?agent= and then if no api or other settings need to be done, then it will guide step by step.

**Comment by arvinxx** [comment]
I think this issue has been solved in the latest version?

**Comment by xenstar** [comment]
yes solved.
