### ISSUE TITLE
[Bug] 配置运行数据库postgres, 启动失败报401错误

### ISSUE THREAD

**Issue by gaspire** [lobehub/lobe-chat#3025]
### 📦 Environment

Other

### 📌 Version

latest

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

配置运行数据库postgres, 启动失败报401错误:
{"level":30,"time":1719293790532,"pid":35951,"hostname":"ShizengdeMacBook-Pro.local","msg":"Error in tRPC handler (lambda) on path: session.getSessionConfig, type: query"}
 GET /trpc/lambda/session.getSessionConfig?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22id%22%3A%22inbox%22%7D%7D%7D 401 in 62ms

#.env 文件配置如下:
NEXT_PUBLIC_SERVICE_MODE=server
DATABASE_URL=postgres://:@127.0.0.1:5432/lobe
KEY_VAULTS_SECRET=BT1PaMM8LWsP2FfuMaMlo59niX4/woVZTgEYimgu3Jo=

**Comment by arvinxx** [comment]
啥环境

**Comment by gaspire** [comment]
本地开发环境

---- 回复的原邮件 ----
| 发件人 | Arvin ***@***.***> |
| 发送日期 | 2024年06月25日 18:21 |
| 收件人 | lobehub/lobe-chat ***@***.***> |
| 抄送人 | ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [lobehub/lobe-chat] [Bug] 配置运行数据库postgres, 启动失败报401错误 (Issue #3025) |

啥环境

**Comment by arvinxx** [comment]
要配 clerk

**Comment by gaspire** [comment]
配置了clerk, 还是报401:
<img width="1227" alt="image" src="https://github.com/lobehub/lobe-chat/assets/49259119/e926b1c5-c3af-48ce-aec6-686ec11a1d95">

**Comment by ZeroDeng01** [comment]
> 本地开发环境
> 
> ---- 回复的原邮件 ----
> | 发件人 | Arvin ***@***.***> |
> | 发送日期 | 2024年06月25日 18:21 |
> | 收件人 | lobehub/lobe-chat ***@***.***> |
> | 抄送人 | ***@***.***>,
> Mention ***@***.***> |
> | 主题 | Re: [lobehub/lobe-chat] [Bug] 配置运行数据库postgres, 启动失败报401错误 (Issue #3025) |
> 
> 啥环境
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

本地环境能接到clerk的webhook消息吗?
