### ISSUE TITLE
[Bug] v1.1.11 Azure Error

### ISSUE THREAD

**Issue by htdohk** [lobehub/lobe-chat#3037]
### 📦 部署环境

Vercel

### 📌 软件版本

v1.1.11

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

这个提交之后，Azure崩了。Vercel回滚到上个部署是OK的。
<img width="1555" alt="截屏2024-06-25 20 56 31" src="https://github.com/lobehub/lobe-chat/assets/107847138/f97f0c9a-c65a-4722-bbfb-fec882213952">

**Comment by bt-nia** [comment]
Same here, do you have a working version before that @htdohk ?

**Comment by htdohk** [comment]
1.1.10 works fine~

**Comment by JillVernus** [comment]
same here, have to rollback to v1.1.10, 
(Docker)

**Comment by htdohk** [comment]
v1.1.12 fixed the Azure Plugin response issue but kept Azure response issue T_T

**Comment by arvinxx** [comment]
@htdohk 我本地测试是正常的，怎么复现？

**Comment by htdohk** [comment]
其实不用任何特殊复现步骤，相同的Vercel环境配置，v1.1.10是好的，11和刚刚的12都是如上的报错。需要我如何提供更多信息可以再告知我～

**Comment by WeihanLi** [comment]
v1.1.12 版本也有这个问题

**Comment by breakstring** [comment]
> v1.1.12 版本也有这个问题

+1

**Comment by htdohk** [comment]
@arvinxx v1.1.11、12、13问题依旧。无需复现路径，就是任何发送都是回复这个报错。烦请优先解决不然完全无法使用了。

**Comment by arvinxx** [comment]
搜了下 userAgentData 在代码里并不存在，感觉像是依赖问题

**Comment by arvinxx** [comment]
@BrandonStudio 感觉应该锁一下 `@azure/core-rest-pipeline` 版本就好了，可以来提个 PR ？

**Comment by arvinxx** [comment]
@BrandonStudio 服务端 runtime 是 edge runtime ，这个能确保发出来的请求是贴近客户这一侧的，以及 stream 时长不超时。切到 node runtime 可以也可以，但是就是默认有 10s 时长限制。

我感觉这个根本上还是这个依赖的问题，应该推 azure 修才是。

**Comment by arvinxx** [comment]
fix in https://github.com/lobehub/lobe-chat/pull/3066
