### ISSUE TITLE
ios下添加到主屏幕不显示logo[Bug] 

### ISSUE THREAD

**Issue by Spades-X** [lobehub/lobe-chat#3042]
### 📦 部署环境

Docker

### 📌 软件版本

1.1.10

### 💻 系统环境

iOS

### 🌐 浏览器

Chrome, Safari

### 🐛 问题描述

通过Docker Compose部署私人lobechat，手机端通过浏览器分享到主屏幕不显示logo，safari和chrome浏览器都是一样

### 📷 复现步骤

浏览器分享到主屏幕即可

### 🚦 期望结果

修复一下这个缺陷

**Comment by arvinxx** [comment]
你的域名是 .top 吗？

**Comment by Spades-X** [comment]
你好，域名是.com


________________________________
发件人: Arvin Xu ***@***.***>
发送时间: Wednesday, June 26, 2024 10:55:25 AM
收件人: lobehub/lobe-chat ***@***.***>
抄送: Spades-X ***@***.***>; Mention ***@***.***>
主题: Re: [lobehub/lobe-chat] ios下添加到主屏幕不显示logo[Bug] (Issue #3042)


你的域名是 .top 吗？

―

**Comment by arvinxx** [comment]
@Spades-X 有没有开启 https?

**Comment by Spades-X** [comment]
开启https，通过nginx proxy manager反代，npm部署在另一台主机
________________________________
发件人: Arvin Xu ***@***.***>
发送时间: Wednesday, June 26, 2024 11:16:20 AM
收件人: lobehub/lobe-chat ***@***.***>
抄送: Spades-X ***@***.***>; Mention ***@***.***>
主题: Re: [lobehub/lobe-chat] ios下添加到主屏幕不显示logo[Bug] (Issue #3042)


@Spades-X<https://github.com/Spades-X> 有没有开启 https?

―

**Comment by arvinxx** [comment]
你可能要试下图片是否能正常访问，我试了下我们部署的版本是正常的。可能要检查下你自己的部署方式吧
