### ISSUE TITLE
[Bug] 使用历史消息数与设置不符

### ISSUE THREAD

**Issue by sxjeru** [lobehub/lobe-chat#3044]
### 📦 部署环境

Vercel

### 📌 软件版本

latest

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

已启用服务端数据库。

配置页打开“限制历史消息数”，将“附带消息数”设为 10。
返回聊天页刷新，依旧是“不限制”。

在输入框上方的“使用历史消息数”处关闭“不限制”，并将消息数设为 6。
刷新后，依旧变为“不限制”。

**Comment by athlan20** [comment]
关注一下这个bug的进展

**Comment by Ssttar** [comment]
关注一波，一样的问题

**Comment by czh020110** [comment]
确实有这个问题，而且我设置历史消息数1的时候它还是会显示上一条ai发的消息的tiken，按理说token应该为0的，不过我在消费日志里传入的确实没包含上个消息的token数

**Comment by KingDoum** [comment]
默默问一下，现在你用起来习惯了么，服务器版本好用么~

**Comment by arvinxx** [comment]
@sxjeru 这个问题还在吗？

**Comment by sxjeru** [comment]
> 这个问题还在吗？

还在，这边梳理了一下问题的重现方式。

选择一个话题，其中只有4条对话，然后设置历史消息数为更大的数，例如10，这时由于话题中没有更多对话，右边的 token 计数器也不会改变。然后刷新，保持在这个话题，会发现历史消息数的“不限制”开关被自动开启。关闭“不限制”，刷新，会发现历史消息数被重置为1。

**Comment by sxjeru** [comment]
抱歉，是我这边没更新，此问题已得到解决。
