### ISSUE TITLE
[Bug] LobeChat 切换对话卡顿

### ISSUE THREAD

**Issue by yh4922** [lobehub/lobe-chat#3045]
### 📦 部署环境

Docker

### 📌 软件版本

1.1.11

### 💻 系统环境

Windows, Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

在切换对话时，如果目标对话聊天记录多了 就会卡顿，清空当前对话就能解决这个问题

**Comment by arvinxx** [comment]
录个屏看下？

**Comment by yh4922** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> Record the screen and take a look?


https://github.com/lobehub/lobe-chat/assets/18353610/1f18a5c4-a9c3-47e8-9329-ac9020223ffe

**Comment by arvinxx** [comment]
markdown 内容渲染需要时间，这个卡一下感觉避免不了

**Comment by yh4922** [comment]
但是卡顿有点太久了 我测试弄了 10几条数据 就这样了 正常对话一天可能几百条  卡的更久了

**Comment by arvinxx** [comment]
你的设备性能如何？我的m1 本地切换还挺快的。基本上秒切

**Comment by yh4922** [comment]
设备名称	DESKTOP-21V58T3
处理器	Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz   2.90 GHz
机带 RAM	32.0 GB
设备 ID	8480AEED-AF71-46F9-BC46-06B8F6D060CF
产品 ID	00330-80000-00000-AA229
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

也不算很差
