### ISSUE TITLE
[Bug] 创建表格插件用不了了

### ISSUE THREAD

**Issue by shog86** [lobehub/lobe-chat#3049]
### 📦 Environment

Vercel

### 📌 Version

1.1.12

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

创建表格插件生成时错误

{
  "error": {
    "status": 400,
    "statusCode": 400,
    "response": {
      "ok": false,
      "url": "https://sheet-generator.brandzzy.com/generate-csv",
      "status": 400,
      "statusText": "Bad Request",
      "headers": {
        "access-control-allow-origin": "*",
        "alt-svc": "h3=\":443\"; ma=86400",
        "cf-cache-status": "DYNAMIC",
        "cf-ray": "899b792bdaf40aa1-IAD",
        "connection": "keep-alive",
        "content-length": "54",
        "content-type": "application/json; charset=utf-8",
        "date": [
          "Wed",
          "26 Jun 2024 07:27:11 GMT"
        ],
        "etag": "W/\"36-i0GHixakdSF4t0Qq7n2Lr2Wgem8\"",
        "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
        "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=dMMrlkRtGHKQ9Q7GvlYRv1fgX0OMccWP8W2EvCCyexhAAAf2PqSzDxONNobPZhjZAdwA8DdvIkd84jz2RvifTGcUY6o5ZM%2FuOHXgozTn28f%2FaimZAYTVLQ233I%2Fqphb6K5uA9EnKYW4n5ith%2FSXd\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
        "server": "cloudflare",
        "x-powered-by": "Express"
      },
      "text": "{\"error\":\"Invalid data. Expected an array of arrays.\"}",
      "data": "{\"error\":\"Invalid data. Expected an array of arrays.\"}",
      "body": {
        "error": "Invalid data. Expected an array of arrays."
      },
      "obj": {
        "error": "Invalid data. Expected an array of arrays."
      }
    }
  }
}

### 📷 Recurrence Steps

<img width="528" alt="image" src="https://github.com/lobehub/lobe-chat/assets/19712631/6554909c-1550-4eff-9bb2-506feb18dc6b">

### 🚦 Expected Behavior

生成CSV文件并下载

**Comment by arvinxx** [comment]
这个感觉是插件本身的问题。
