### ISSUE TITLE
[Bug] 服务端 db 模式中，gemini 不支持直接传图片 url

### ISSUE THREAD

**Issue by gaarry** [lobehub/lobe-chat#3051]
### 📦 Environment

Vercel

### 📌 Version

V1.1.11

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

服务端 db 模式中，gemini 不支持直接传图片 url
<img width="668" alt="image" src="https://github.com/lobehub/lobe-chat/assets/38985003/5f827e6c-d5a8-4bbf-8e2c-84ebd109eeca">

**Comment by shog86** [comment]
确实是的，而且我对比了4o返回的报错信息以及CF R2上存储的文件的url之后，发现：

4o只是说找不到图片url，Gemini也说找不到，但提供了一个地址：

https://s3-for-lobechat.我的域名.com/files/477823/4784e645-1481-4fd3-93fb-41156878fa6d.jpg——这个地址无法访问

但我在R2桶里看到的图片地址是我的域名.com/files/477823/4784e645-1481-4fd3-93fb-41156878fa6d.jpg——这个地址是可以访问的

所以是不是服务端部署后哪里把图片url拼错了？

**Comment by JJTools** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> It is indeed true, and after comparing the error message returned by 4o and the URL of the file stored on CF R2, I found:
> 
> 4o just said that the image url could not be found, and Gemini also said that it could not be found, but provided an address:
> 
> https://s3-for-lobechat.mydomain.com/files/477823/4784e645-1481-4fd3-93fb-41156878fa6d.jpg - This address cannot be accessed
> 
> But the image address I saw in the R2 bucket is my domain name.com/files/477823/4784e645-1481-4fd3-93fb-41156878fa6d.jpg - this address is accessible
> 
> So did the image URL get spelled wrong somewhere after the server was deployed?

4o can find the image and provide the answer normally, but Gemini 1.5 does not work and will prompt this error. Directly accessing the link in the browser can also open the image.
