### ISSUE TITLE
[Bug] pnpm build 报错：Cannot read properties of undefined (reading 'migrate')

### ISSUE THREAD

**Issue by gaspire** [lobehub/lobe-chat#3052]
### 📦 Environment

Other

### 📌 Version

latest

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

执行pnpm build, 报错 Cannot read properties of undefined (reading 'migrate')
<img width="1568" alt="image" src="https://github.com/lobehub/lobe-chat/assets/49259119/c6dbfbcb-9a61-4fa7-97e1-b0b7193974fd">

**Comment by arvinxx** [comment]
你的 DB URL 配的是啥

**Comment by gaspire** [comment]
用的是 neon postgresql

**Comment by gaspire** [comment]
用本地的postgresql@15 也不行

**Comment by gaspire** [comment]
<img width="613" alt="image" src="https://github.com/lobehub/lobe-chat/assets/49259119/a89cd51a-8cff-4721-98d0-fc3deb308624">
https://neon.tech/docs/guides/drizzle-migrations  按照上面的文档做了修改，可以了

**Comment by gray0128** [comment]
使用 azure的gpt4o，界面中也报这个运行时错误。其他模型正常

**Comment by arvinxx** [comment]
@gaspire 可能是你的链接不是pooler 模式导致的
