### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'userAgentData')

### ISSUE THREAD

**Issue by mrtungdev** [lobehub/lobe-chat#3053]
### 📦 Environment

Vercel

### 📌 Version

v1.1.13

### 💻 Operating System

macOS

### 🌐 Browser

Chrome, Edge

### 🐛 Bug Description

Just upgraded latest version (old version worked) and got error:
```
Lobe language model runtime execution error. Please troubleshoot or retry based on the following information.
{
  "error": {
    "message": "Cannot read properties of undefined (reading 'userAgentData')",
    "name": "TypeError"
  },
  "endpoint": "https://***.openai.azure.com/",
  "provider": "azure"
}
```
This error when ussing Azure but with Claude 3.5 work fine.

**Comment by luckfu** [comment]
还没修复好吗？今天都摸鱼一天没发工作了

**Comment by arvinxx** [comment]
fix in https://github.com/lobehub/lobe-chat/pull/3066
