### ISSUE TITLE
[Bug] Claude API 调用报错（use error）

### ISSUE THREAD

**Issue by EEE1even** [lobehub/lobe-chat#3054]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

我在尝试使用Claude API时报错，并且不显示报错代码
我已经开启了使用客户端请求模式，并且可以正常访问Openai API服务，所以可以排除网络连接问题
排查发现在pycharm上可以正常调用API进行输出，但是lobe-chat上不行
下面是报错代码：
```
{
  "error": {
    "cause": {}
  },
  "endpoint": "https://api.anthropic.com",
  "provider": "anthropic"
}
```
可以看到并没有错误代码反馈，我目前无法解决这个问题

---------------------

I got an error trying to use the Claude API, and it doesn't show the error code, 
I've enabled the use of client request mode and I can access the Openai API service normally,so you can rule out internet connection problems
I checked and found that I can call the API on pycharm and output it normally, but not on lobe-chat.
Here is the error code:
```
{
  "error": {
    "cause": {}
  },
  "endpoint": "https://api.anthropic.com",
  "provider": "anthropic"
}
```
As you can see there is no error code feedback, I can't fix this bug at the moment

**Comment by arvinxx** [comment]
服务端请求可以吗

**Comment by EEE1even** [comment]
> 服务端请求可以吗

你是指通过url请求服务吗？

**Comment by EEE1even** [comment]
> 服务端请求可以吗

我能通过下述形式进行请求
```
import anthropic
import os

os.environ["http_proxy"] = "http://localhost:7890"
os.environ["https_proxy"] = "http://localhost:7890"

client = anthropic.Anthropic(
    api_key="my key"
)

message = client.messages.create(
    model="claude-3-5-sonnet-20240620",
    max_tokens=1000,
    temperature=0,
    system="",
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "你是谁"
                }
            ]
        }
    ]
)
print(message.content)
```python

**Comment by dalefengs** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/58434904/087e6be1-dd72-4142-bb27-318837dbb052)
![image](https://github.com/lobehub/lobe-chat/assets/58434904/88a1f073-df3d-423f-a111-284c19547d09)

我也遇到了，使用客户端请求和服务端请求都会出现该错误，只要回复内容长，就必定发生错误
