### ISSUE TITLE
[Bug] 文档模式编辑按钮丢失

### ISSUE THREAD

**Issue by dalefengs** [lobehub/lobe-chat#3056]
### 📦 部署环境

Docker

### 📌 软件版本

v1.1.13

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

![recording](https://github.com/lobehub/lobe-chat/assets/58434904/8482f80c-942e-4242-b185-18fca546155a)
使用文档模式，对话模式正常

### 📷 复现步骤

使用文档模式，对话模式正常

**Comment by one-pyy** [comment]
+1

**Comment by dalefengs** [comment]
这个问题有办法解决嘛

**Comment by dalefengs** [comment]
这个bug 2月了，有大佬优化下么

**Comment by arvinxx** [comment]
@dalefengs 做完知识库了，这些小 bug 准备开始修了

**Comment by arvinxx** [comment]
已修复
