### ISSUE TITLE
Lobe AI runtime error with 1.1.14

### ISSUE THREAD

**Issue by shog86** [lobehub/lobe-chat#3069]
### 📦 Environment

Vercel

### 📌 Version

1.1.14

### 💻 Operating System

iOS

### 🌐 Browser

Safari

### 🐛 Bug Description

Lobe AI Runtime 执行出错，请根据以下信息排查或重试

Show Details

json
{   "error": {     "message": "Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'."   },   "endpoint": "https://xxx.openai.azure.com",   "provider": "azure"

### 📷 Recurrence Steps

gpt-4o, 网络搜索 plugin on

query: 请用表格列出比特币最近一周价格

**Comment by arvinxx** [comment]
消息不完整吧，删掉重试
