### ISSUE TITLE
[Request] Support function calling in Claude 3/3.5

### ISSUE THREAD

**Issue by hoveychen** [lobehub/lobe-chat#3070]
### 🥰 Feature Description

As stated in https://docs.anthropic.com/en/docs/build-with-claude/tool-use, since Claude 3, it supports tool call, which is similar to function calling. It would be great to support it.

### 🧐 Proposed Solution

Support tool-use in claude 3/3.5 as function call

**Comment by arvinxx** [comment]
have supported

**Comment by hoveychen** [comment]
> have supported: https://lobehub.com/zh/docs/usage/tools-calling/anthropic

I've tried the official anthoripic version of Claude, it has indeed supported function call.
However, it's not supported in AWS Bedrock Claude, which IMO is essentially the same models for business.
