### ISSUE TITLE
[Bug] 卡顿非常严重

### ISSUE THREAD

**Issue by QQOQ** [lobehub/lobe-chat#3071]
### 📦 部署环境

Other

### 📌 软件版本

最新版

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

ui界面操作非常卡顿，不得不放弃这个项目，估计逻辑有严重或者依赖过多

**Comment by arvinxx** [comment]
具体哪里卡，请给出详细说明。最好有录屏。之前反馈的很多卡顿都已经优化掉了。

**Comment by bwnjnOEI** [comment]
我是linux系统，配置（64g内存，i9CPU， 48g显存，线路是GN2）应该没问题，但是每次打开`设置和发现`等操作风扇就转且轻微卡顿，隔壁openwebui基本没动静，我是看网上作者说将要更好支持RAG才来的，因为openwebui现在这方面支持比较差。

**Comment by arvinxx** [comment]
@bwnjnOEI 如果有卡顿问题建议新开一个帖子，并附上卡顿的视频问题，然后针对性排查下可能是什么问题。
