### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Chris930101** [lobehub/lobe-chat#3073]
### 📦 部署环境

Vercel

### 📌 软件版本

v1.1.14

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

每天自动更新的，昨天更新完之后就变这样了，不知道为啥？

Lobe AI Runtime 执行出错，请根据以下信息排查或重试
Show Details
{
  "error": {
    "message": "Cannot read properties of undefined (reading 'userAgentData')",
    "name": "TypeError"
  },
  "endpoint": "https://***.openai.azure.com/",
  "provider": "azure"
}

### 📝 补充信息

我一直用的azure，但是在前台网页的模型设置里，我把参数填进azure的模型里，我使用客户端模式是不会出错的

**Comment by arvinxx** [comment]
fix in https://github.com/lobehub/lobe-chat/pull/3066
