### ISSUE TITLE
[Bug] DB模式下 Claude无法正确上传图片

### ISSUE THREAD

**Issue by pzcn** [lobehub/lobe-chat#3076]
### 📦 Environment

Vercel

### 📌 Version

1.1.14

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

查看DB模式下向claude3发出带图的消息中的post请求仍然是base64，而不是url，但是base64的data为空。在非DB模式下进行测试并没有问题。
![image](https://github.com/lobehub/lobe-chat/assets/29601158/53b3267d-0880-4196-9011-0221ef155485)

### 📷 Recurrence Steps

在DB模式下上传一个图片给Claude模型

**Comment by RubuJam** [comment]
请提供一下你的环境变量设置

Please provide your environment variable settings

**Comment by arvinxx** [comment]
duplicate with https://github.com/lobehub/lobe-chat/issues/3001
