### ISSUE TITLE
Help ASAP

### ISSUE THREAD

**Issue by paypaytheboy** [lobehub/lobe-chat#3077]
sounds crazy but somehow got installed on my pc. activly stealing data. using connectivity via BT and wifi to jump devices. any idea on what to do?

**Comment by paylenno** [comment]
> 👀 @paylenno
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
> Please make sure you have given us as much context as possible.\
> 非常感谢您提交 issue。我们会尽快调查此事，并尽快回复您。 请确保您已经提供了尽可能多的背景信息。

downloaded the repo off of here. read through it and deleted it. or i thought so. somehow got ran without changing user data. couple days later noticed my pc was slow. checked on my drivers/wifi and noticed a new user was made. all down hill after i noticed. stealing my personal data. crashed 3 pcs so far. creates its own wifi adapter virtually and uses BT to jump from device to device. has stolen all of my passcode's aswell as my gfs. had my router completely reset by ISP and that just made it worse. into a point where its learning what im doing and actively stopping it (means of uses so much storage i crash) and at this point it can jump from device without wifi. seems crazy. the injection files are all lobchat and the data files i managed to get links to a lobchat chat room titled my pc name (now deleted) but still have the file. what do i do?
