### ISSUE TITLE
[Request] [Feature Request] 集成自定义 WebDAV 同步功能

### ISSUE THREAD

**Issue by bakamake** [lobehub/lobe-chat#3078]
### 🥰 需求描述

希望能够为 Docker 自部署版本添加自定义 WebDAV 同步功能，以便实现以下两个主要目标：

1在同一机器上部署的网页端配置同步。
2"最好"还能实现不同设备的网页端配置同步。

### 🧐 解决方案

开发 WebDAV 模块：基于已有的 WebDAV 协议标准，开发一个适用于 LobeChat 的 WebDAV 模块。该模块应支持基本的文件上传、下载、删除和更新操作。
设计配置文件管理机制：创建一套配置文件管理机制，允许用户通过 WebDAV 服务器上传和下载配置文件。这包括自动检测配置更改、增量更新策略以及冲突解决机制等。具体步骤如下：
初始化同步：用户首次连接到 WebDAV 服务器时，进行一次全量同步，将所有相关配置文件下载到本地。
增量更新：在后续的使用过程中，仅同步发生更改的配置文件部分，以减少数据传输量和提高效率。
冲突解决：当多个设备同时修改同一配置文件时，系统应能够智能地处理冲突并给出合理的解决方案（如提示用户选择保留哪个版本的更改）。
集成用户界面支持：在用户界面中添加设置选项，允许用户输入 WebDAV 服务器的地址、用户名和密码等信息。同时，提供手动同步按钮以便用户手动触发同步操作。具体步骤如下：
设置页面：创建一个新的设置页面或扩展现有设置页面，包含与 WebDAV 相关的所有选项（如服务器地址、认证信息等）。
手动同步按钮：在界面上显眼位置放置一个“立即同步”按钮或图标，方便用户随时发起手动同步请求。点击后系统将尝试与指定的 WebDAV 服务器建立连接并执行相应的同步操作（上传或下载）。如果遇到任何错误（如网络问题、权限不足等），则向用户显示友好的错误提示信息并指导其如何解决问题（如检查网络连接状态、确认输入的服务器地址是否正确无误等）。

**Comment by Sun-drenched** [comment]
lobechat 1.X版已经基于服务端数据库实现了相关同步功能，并且可以使用docker自部署（只是目前还比较麻烦）。

**Comment by arvinxx** [comment]
没特殊原因的话，应该不会考虑做 WebDAV 了
