### ISSUE TITLE
[Bug] 每次重启浏览器语言重新变成英文

### ISSUE THREAD

**Issue by leeyiding** [lobehub/lobe-chat#308]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

我默认设置的语言是中文简体，但是每次重启浏览器进入后，界面全显示的英文，而且在语言设置这块还是显示的简体中文。

![S31012-00280629_com android chrome](https://github.com/lobehub/lobe-chat/assets/49098278/bd7110e3-0030-4c59-8906-763ee2207696)

**Comment by arvinxx** [comment]
版本是最新的吗？这个问题应该之前修了呀

**Comment by leeyiding** [comment]
是最新版 0.88.0

**Comment by arvinxx** [comment]
你试试切成跟随系统语言试试

**Comment by leeyiding** [comment]
这个问题我只在Chrome浏览器复现了，无论是Windows还是Android。在Edge测试是没有这个问题的。
另外切换成跟随系统语言Chrome浏览器还是英文，Edge变更成了简体中文

![image](https://github.com/lobehub/lobe-chat/assets/49098278/0c23443f-d21b-4d20-98de-83cc62e72ba8)
![image](https://github.com/lobehub/lobe-chat/assets/49098278/a950a1f8-62d4-47f2-bfbe-370dc6672cad)

**Comment by arvinxx** [comment]
你看下Chrome浏览器里的语言，是不是把英文放第一位了？

**Comment by leeyiding** [comment]
默认就是中文的
![image](https://github.com/lobehub/lobe-chat/assets/49098278/470c7b1c-f4fb-4a22-9e99-f17eea41acce)
![c64821749e16fd50db98d2074001f89](https://github.com/lobehub/lobe-chat/assets/49098278/78686570-d540-46b3-b9c1-28a3da9d19e4)

**Comment by arvinxx** [comment]
那就很奇怪了…你试试执行 navigator.language 看看出来的是什么？

**Comment by leeyiding** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/49098278/5ec85375-fc5c-4d6a-9012-9c5789101e74)

**Comment by arvinxx** [comment]
我知道了… zh-CN 没匹配上 zh ... 我想想咋整

**Comment by arvinxx** [comment]
你试试把简体 挪到最上面

**Comment by leeyiding** [comment]
> 有个绕过的方法： 把简体 挪到第一位

可以，解决了

**Comment by canisminor1990** [comment]
> 我知道了… zh-CN 没匹配上 zh ... 我想想咋整

找找有没有简写语言转换的库 感觉应该是有现成的
