### ISSUE TITLE
[Docs]clerk配置后Missing publishableKey

### ISSUE THREAD

**Issue by weiben1989** [lobehub/lobe-chat#3080]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/advanced/authentication.zh-CN.mdx

### 🐛 Feedback

_Your response_

在lobechat里面设置 clerk的问题，
首先我拿到了clerk得apikey，然后在nano.env 里面添加的了 两个key 还有 openai的key
再然后 运行 
docker stop lobe-chat
docker rm lobe-chat
docker run -d -p 3210:3210 \
  --env-file .env \
  --name lobe-chat \
  lobehub/lobe-chat:latest

可以最后访问显示的是 Application error: a client-side exception has occurred (see the browser console for more information).
说的问题是 Missing publishableKey 的错误
头大了 求助

**Comment by htdohk** [comment]
我也遇到这个问题，但是查一下历史Issue得知Docker好像不支持NEXT_PUBLIC_XXX这个变量，只能Vercel部署。

**Comment by weiben1989** [comment]
> 我也遇到这个问题，但是查一下历史Issue得知Docker好像不支持NEXT_PUBLIC_XXX这个变量，只能Vercel部署。

我折腾了一天半，这仿佛是一个噩耗～～

**Comment by weiben1989** [comment]
> 我也遇到这个问题，但是查一下历史Issue得知Docker好像不支持NEXT_PUBLIC_XXX这个变量，只能Vercel部署。

你现在解决了这个验证问题没～哈哈

**Comment by Sun-drenched** [comment]
> 我也遇到这个问题，但是查一下历史Issue得知Docker好像不支持NEXT_PUBLIC_XXX这个变量，只能Vercel部署。

不是不支持，是NEXT_PUBLIC_XXX变量必须在构建时就注入docker镜像，直接拉取官方镜像，在启动容器时设置NEXT_PUBLIC_XXX变量值是不可行的。
目前，如果你想要使用docker方式运行lobechat cloud版，你需要自己构建镜像（在构建时就在dockerfile中声明并赋值所有cloud版lobechat所需的环境变量）。或者拉取官方镜像后，以官方镜像为基础设置新的环境变量（构建参数）再构建一个新的镜像应该也是可行的。

**Comment by weiben1989** [comment]
> > 我也遇到这个问题，但是查一下历史Issue得知Docker好像不支持NEXT_PUBLIC_XXX这个变量，只能Vercel部署。
> 
> 不是不支持，是NEXT_PUBLIC_XXX变量必须在构建时就注入docker镜像，直接拉取官方镜像，在启动容器时设置NEXT_PUBLIC_XXX变量值是不可行的。 目前，如果你想要使用docker方式运行lobechat cloud版，你需要自己构建镜像（在构建时就在dockerfile中声明并赋值所有cloud版lobechat所需的环境变量）。或者拉取官方镜像后，以官方镜像为基础设置新的环境变量（构建参数）再构建一个新的镜像应该也是可行的。

你好啊，我让ai帮我理解了一下是这么个意思吗？

**已知情况**

> 需要在 Docker 构建时注入 NEXT_PUBLIC_ 环境变量。
> 直接使用官方镜像，并在运行时设置 NEXT_PUBLIC_ 变量是不可行的。
> 需要构建自定义的 Docker 镜像，并在构建时声明并赋值所有环境变量。

**当前问题**

> 如何在 Docker 构建时注入 NEXT_PUBLIC_ 环境变量。
> 确保自定义镜像可以在运行时正确工作。

**解决方案**

> 在 Dockerfile 中声明和设置环境变量：
> 使用 ARG 和 ENV 指令在 Dockerfile 中设置环境变量。
> 构建自定义 Docker 镜像：
> 使用 docker build 命令，在构建时传入环境变量值。
> 运行 Docker 容器：
> 确保其他非 NEXT_PUBLIC_ 变量在运行时通过 -e 选项传递。
>

**Comment by Sun-drenched** [comment]
> > > 我也遇到这个问题，但是查一下历史Issue得知Docker好像不支持NEXT_PUBLIC_XXX这个变量，只能Vercel部署。
> > 
> > 
> > 不是不支持，是NEXT_PUBLIC_XXX变量必须在构建时就注入docker镜像，直接拉取官方镜像，在启动容器时设置NEXT_PUBLIC_XXX变量值是不可行的。 目前，如果你想要使用docker方式运行lobechat cloud版，你需要自己构建镜像（在构建时就在dockerfile中声明并赋值所有cloud版lobechat所需的环境变量）。或者拉取官方镜像后，以官方镜像为基础设置新的环境变量（构建参数）再构建一个新的镜像应该也是可行的。
> 
> 你好啊，我让ai帮我理解了一下是这么个意思吗？
> 
> **已知情况**
> 
> > 需要在 Docker 构建时注入 NEXT_PUBLIC_ 环境变量。
> > 直接使用官方镜像，并在运行时设置 NEXT_PUBLIC_ 变量是不可行的。
> > 需要构建自定义的 Docker 镜像，并在构建时声明并赋值所有环境变量。
> 
> **当前问题**
> 
> > 如何在 Docker 构建时注入 NEXT_PUBLIC_ 环境变量。
> > 确保自定义镜像可以在运行时正确工作。
> 
> **解决方案**
> 
> > 在 Dockerfile 中声明和设置环境变量：
> > 使用 ARG 和 ENV 指令在 Dockerfile 中设置环境变量。
> > 构建自定义 Docker 镜像：
> > 使用 docker build 命令，在构建时传入环境变量值。
> > 运行 Docker 容器：
> > 确保其他非 NEXT_PUBLIC_ 变量在运行时通过 -e 选项传递。

差不多可以这么理解把

**Comment by weiben1989** [comment]
> 把

还是失败了，没有一点耐心了。哈哈

**Comment by Sun-drenched** [comment]
> > 把
> 
> 还是失败了，没有一点耐心了。哈哈

是可行的，我是通过拉取仓库再在本地构建的方式自部署了cloud版lobechat。只不过这个过程也有一些需要注意的tips。如果没有这方面经验的话，可以等待后续开发者（可能会出）的cloud版镜像，会方便很多。

**Comment by arvinxx** [comment]
> 可以等待后续开发者（可能会出）的cloud版镜像，会方便很多

会出的，等 @cy948 的接入 next-auth 的 pr  #2935 合并以后，会给一个 server db 版本的镜像

**Comment by weiben1989** [comment]
> > 可以等待后续开发者（可能会出）的cloud版镜像，会方便很多
> 
> 会出的，等 @cy948 的接入 next-auth 的 pr  #2935 合并以后，会给一个 server db 版本的镜像

好的好的，期待住了！感谢(^🙏^)
