### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by silencer404** [lobehub/lobe-chat#3083]
### 📦 部署环境

Docker

### 📌 软件版本

v1.1.15

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome, Firefox

### 🐛 问题描述

docker compose 私有化部署zitadel和lobe-chat，相同的配置从0.x版本升级到1.0新版本。0.x版本可以进行sso验证用户信息登陆，1.0版本之后只有密码登陆，配置zitadel失效，docker logs没有报错
![图片](https://github.com/lobehub/lobe-chat/assets/25236846/8b08f2b5-f4be-453c-8afa-1aacade52118)
![图片](https://github.com/lobehub/lobe-chat/assets/25236846/918d7346-7a50-491e-ac27-145ad9ae8e16)

ZITADEL_ISSUER在新版本zitadel中已经没有这个条目了，请更新文档
![图片](https://github.com/lobehub/lobe-chat/assets/25236846/62af9942-58ed-41fe-ab96-d1550563f2ff)
当前文档链接：
https://lobehub.com/zh/docs/self-hosting/advanced/sso-providers/zitadel

### 📷 复现步骤

浏览器无痕模式加载配置启动，登陆界面只有密码登陆

### 🚦 期望结果

支持zitadel登陆

**Comment by ykangw** [comment]
Same Issue on Vercel using Microsoft Entra ID

**Comment by arvinxx** [comment]
自行检查下环境变量： https://lobehub.com/zh/docs/self-hosting/environment-variables/auth#next-auth 1.0 之前应该明确告知过环境变量有名称有变更。
