### ISSUE TITLE
[Bug] 部署服务端之后上传图片出现错误

### ISSUE THREAD

**Issue by shog86** [lobehub/lobe-chat#3085]
### 📦 部署环境

Vercel

### 📌 软件版本

1.2.5

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

部署了服务端在R2，上传图片有问题
很抱歉，服务器似乎遇到了一些困难，暂时无法完成您的请求，请稍后再试
错误详情
text
insert or update on table "messages" violates foreign key constraint "messages_topic_id_topics_id_fk"

**Comment by shog86** [comment]
上传图片也有问题
很抱歉，服务器似乎遇到了一些困难，暂时无法完成您的请求，请稍后再试
错误详情
text
insert or update on table "messages" violates foreign key constraint "messages_topic_id_topics_id_fk"

**Comment by shog86** [comment]
<img width="772" alt="image" src="https://github.com/lobehub/lobe-chat/assets/19712631/09f1b18a-ead7-41e4-a41b-1ecec5c4d8e4">
 猜测是因为这里文字描述和截图不一致，我是按截图来的，设置的对象读与写，现在改成管理员读与写试试

**Comment by shog86** [comment]
还是不行，上传的图片显示这样
<img width="578" alt="image" src="https://github.com/lobehub/lobe-chat/assets/19712631/ec2be4c5-6bd7-4759-93b2-0026e677ef84">


然后报错信息是
{
  "error": {
    "code": "BadRequest",
    "type": null,
    "param": null,
    "message": "The provided image url is not accessible."
  },
  "endpoint": "https://xxx.openai.azure.com",
  "provider": "azure"
}

**Comment by shog86** [comment]
Lobechat Cloud当时没遇到这个问题么。。。

**Comment by shog86** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/19712631/6bb7db19-f34f-44fd-87ea-5acbe6813df2)
但在R2里又看到了所有上传的图片，而且链接都可以直接公网访问

**Comment by RubuJam** [comment]
需要的是`管理员读与写`权限，而非`对象读和写`

In order to achieve the desired outcome, it is necessary to obtain the `Administrator Read and Write` permission, rather than the `Object Read and Write`.

**Comment by shog86** [comment]
> 需要的是`管理员读与写`权限，而非`对象读和写`
> 
> In order to achieve the desired outcome, it is necessary to obtain the `Administrator Read and Write` permission, rather than the `Object Read and Write`.

我给了管理员读写权限，现在服务端指南里文本和截图对不上

但其他都没问题，就是文件上传了大模型取不到

**Comment by shog86** [comment]
https://github.com/lobehub/lobe-chat/issues/3051#issuecomment-2210334332  在另一个issue下面加了个评论，似乎找到了服务端部署后无法读图的原因

**Comment by RubuJam** [comment]
文档里的警告是我后期加的，原有文档有不少问题，但图片我当时不方便修改，欢迎PR

The annotations in the document were added subsequently added by myself. The original document is rife with issues but it was not feasible to modify the images at the time. However, PR are welcome.

**Comment by RubuJam** [comment]
或许你可以把这部分的环境变量发一下，我可以帮你看看，当然，记得隐藏关键信息

Please send me the environment variables for this part so that I can assist you in reviewing them. Please ensure that you conceal any sensitive information.

**Comment by RubuJam** [comment]
或许你可以把这部分的环境变量发一下，我可以帮你看看，当然，记得隐藏关键信息

Send me the environment variables for this part so that I can assist you in reviewing them. Ensure that you conceal any sensitive information.

**Comment by shog86** [comment]
> 文档里的警告是我后期加的，原有文档有不少问题，但图片我当时不方便修改，欢迎PR
> 
> The annotations in the document were added subsequently added by myself. The original document is rife with issues but it was not feasible to modify the images at the time. However, PR are welcome.

截了个图
<img width="960" alt="image" src="https://github.com/lobehub/lobe-chat/assets/19712631/01e042c0-cbcc-437b-8dd3-d417c8cc2621">

**Comment by shog86** [comment]
> 或许你可以把这部分的环境变量发一下，我可以帮你看看，当然，记得隐藏关键信息
> 
> Send me the environment variables for this part so that I can assist you in reviewing them. Ensure that you conceal any sensitive information.

如下（Clerk部分没问题，所以没显示详情了，S3 Endpoint最后的路径也去掉了）：
<img width="799" alt="image" src="https://github.com/lobehub/lobe-chat/assets/19712631/f58e6971-ce8c-492e-95dd-4ddb6f47137a">
<img width="433" alt="image" src="https://github.com/lobehub/lobe-chat/assets/19712631/cad4312c-32dc-48e2-b850-74956ea5bf44">
<img width="752" alt="image" src="https://github.com/lobehub/lobe-chat/assets/19712631/027dbc97-89dc-4c2b-88d9-4571f39f841b">


NEXT_PUBLIC_S3_DOMAIN=https://**s3-for-lobechat**.your-domain.com/

在配置数据库这里，这个参数前后写得不一样，有一处写的是NEXT_PUBLIC_S3_DOMAIN=https://**s3-dev**.your-domain.com/

到底该 咋写呢？我两种都试过，也都重新部署过，但都无法读图，结合我在https://github.com/lobehub/lobe-chat/issues/3051#issuecomment-2210334332 这里的分析，感觉我的环境配置应该没问题，是lobechat拼地址的时候没拼对。。。（我是Azure OpenAI，不知道会不会也有些影响

**Comment by shog86** [comment]
文档里说：在 Vercel 的部署环境变量中，添加 DATABASE_URL 等环境变量，将上一步准备好的 Postgres 数据库连接 URL 填入其中。

这儿是说在vercel整体设置那儿加变量，还是在部署的lobechat里设置的地方加变量？

我是在整个Vercel的设置里加的，然后链接到lobechat这个项目，按理说和在lobechat项目设置里配置变量是一样的
![image](https://github.com/lobehub/lobe-chat/assets/19712631/89123fae-ad7d-4f36-bb39-7c7fb258504e)

**Comment by arvinxx** [comment]
@RubuJam 为什么需要管理员读写？只要桶读写就好了

**Comment by RubuJam** [comment]
> @RubuJam 为什么需要管理员读写？只要桶读写就好了

我也不知道为什么要用管理员读写，但如果不给管理员读写，就会出问题

**Comment by RubuJam** [comment]
所有环境变量，都在你部署的那个项目中填写就好，无需在vercel整体中设置
> 文档里说：在 Vercel 的部署环境变量中，添加 DATABASE_URL 等环境变量，将上一步准备好的 Postgres 数据库连接 URL 填入其中。
> 
> 
> 
> 这儿是说在vercel整体设置那儿加变量，还是在部署的lobechat里设置的地方加变量？
> 
> 
> 
> 我是在整个Vercel的设置里加的，然后链接到lobechat这个项目，按理说和在lobechat项目设置里配置变量是一样的
> 
> ![image](https://github.com/lobehub/lobe-chat/assets/19712631/89123fae-ad7d-4f36-bb39-7c7fb258504e)

**Comment by RubuJam** [comment]
> NEXT_PUBLIC_S3_DOMAIN

NEXT_PUBLIC_S3_DOMAIN是你自己在CF里绑定的域名，这里应该是写错了，你可以在PR里修改一下

**Comment by shog86** [comment]
> > NEXT_PUBLIC_S3_DOMAIN
> 
> NEXT_PUBLIC_S3_DOMAIN是你自己在CF里绑定的域名，这里应该是写错了，你可以在PR里修改一下

？
只写https://我的域名.com 就可以了，不要任何前缀？

环境变量我这样引用不行？也有可能是出问题的原因？

**Comment by shog86** [comment]
我明天改改试试先

**Comment by RubuJam** [comment]
写什么取决于你的R2里连接的是什么，在设置-公开访问-自定义域中连接
> ？
> 只写https://我的域名.com 就可以了，不要任何前缀？不过好像有道理，因为读图引用的地址确实多了前缀
> 
> 环境变量我这样引用不行？也有可能是出问题的原因？

**Comment by shog86** [comment]
> > > NEXT_PUBLIC_S3_DOMAIN
> > 
> > NEXT_PUBLIC_S3_DOMAIN是你自己在CF里绑定的域名，这里应该是写错了，你可以在PR里修改一下
> 
> ？
> 只写https://我的域名.com 就可以了，不要任何前缀？不过好像有道理，因为读图引用的地址确实多了前缀
> 
> 环境变量我这样引用不行？也有可能是出问题的原因？

环境变量我在vercel设置里链接到lobechat项目也是可以的

域名那里是我一开始看错了，确实要和R2绑定的域名一致就行
