### ISSUE TITLE
[Bug] "An unexpected error occurred." when trying to deploy on Vercel

### ISSUE THREAD

**Issue by aodrasa** [lobehub/lobe-chat#309]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

Hey, I'm repeatedly getting the error "An unexpected error occurred. Our team has already been notified and are working to resolve the issue, please try again shortly." when trying to deploy on Vercel using the one click deploy in the repo. Any idea how I can resolve this?

Thanks

**Comment by arvinxx** [comment]
I will try to figure it out

**Comment by aodrasa** [comment]
> I will try to figure it out

That would be great thank you!

**Comment by arvinxx** [comment]
@aodrasa we have fixed this bug. You can try it again.
