### ISSUE TITLE
[Bug] 在AI自身有toolCall函数调用，不用在system中填充多余的提示

### ISSUE THREAD

**Issue by bincooo** [lobehub/lobe-chat#3096]
### 📦 部署环境

Docker

### 📌 软件版本

latest

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

RT，我调试时发现在支持tool功能会在头部的system里填充 Tools\n\nYou can use these tools below: ....

感觉此处可省略节省token，另一方面指令理解较差的AI也会受干扰

**Comment by arvinxx** [comment]
你想简单了 https://github.com/lobehub/lobe-chat/discussions/1310#discussioncomment-9137726
