### ISSUE TITLE
 [Request] Qwen/通义千问希望支持国际版Endpoint

### ISSUE THREAD

**Issue by RyanLookchard** [lobehub/lobe-chat#3099]
### 🥰 需求描述

现在支持的国内版的api接口 "https://dashscope.aliyuncs.com/compatible-mode/v1",
国际版的api接口是 'https://dashscope-intl.aliyuncs.com/api/v1'

详情可参考国际版文档：https://www.alibabacloud.com/help/en/model-studio/developer-reference/qwen-model-api-details?spm=a2c63.p38356.0.0.33b95aeeSzbNee

### 🧐 解决方案

希望可以让用户自由选择哪个版本
或者可以自定义api url

**Comment by sxjeru** [comment]
作为临时方案，可在此处变更 api endpoint.

https://github.com/lobehub/lobe-chat/blob/9ea871105ee0a9eed0173807453f9c000f77b026/src/libs/agent-runtime/qwen/index.ts#L7
