### ISSUE TITLE
[Request] docker本地化部署方法

### ISSUE THREAD

**Issue by yinggoga** [lobehub/lobe-chat#310]
### 🥰 需求描述 | Feature Description

docker本地化部署方法

### 🧐 解决方案 | Proposed Solution

docker本地化部署方法

**Comment by canisminor1990** [comment]
https://github.com/lobehub/lobe-chat/issues/300

**Comment by arvinxx** [comment]
@yinggoga 详见：https://github.com/lobehub/lobe-chat/blob/main/docs/Docker-Deployment.zh-CN.md
