### ISSUE TITLE
[Request] Support a side window displaying HTML/generated codes, just like Artifacts function in latest Claude.

### ISSUE THREAD

**Issue by hoveychen** [lobehub/lobe-chat#3103]
### 🥰 Feature Description

https://support.anthropic.com/en/articles/9487310-what-are-artifacts-and-how-do-i-use-them
https://www.youtube.com/watch?v=vT3WeSibhBo
It's really productive to display rendered HTML in the side window.
IMO, it's purely a frontend feature that can be implemented in the client UI.

### 🧐 Proposed Solution

Maybe directly extract the content in markdown quote block, and display them in a side window which can directly interact?

**Comment by arvinxx** [comment]
duplicate of #2981
