### ISSUE TITLE
[Request] 添加glm-4-alltools模型，并使用这个模型自带的fc功能，比如联网功能，而不需要另外设置或安装fc插件

### ISSUE THREAD

**Issue by Myra009** [lobehub/lobe-chat#3104]
### 🥰 需求描述

添加glm-4-alltools模型，并使用这个模型自带的fc功能，比如联网功能，而不需要另外设置或安装fc插件

### 🧐 解决方案

glm-4-alltools直接添加使用是可以的，但是无法使用自带的联网等其他功能，希望添加这个模型

**Comment by arvinxx** [comment]
glm-4-alltools 这个模型哪来的？

**Comment by sxjeru** [comment]
GLM-4 All Tools 应该没下放到 api，只能在 https://chatglm.cn/ 享受。

https://arxiv.org/html/2406.12793v1#S1

**Comment by Myra009** [comment]
> GLM-4 All Tools 应该没下放到 api，只能在 https://chatglm.cn/ 享受。
> 
> https://arxiv.org/html/2406.12793v1#S1

已经有了https://open.bigmodel.cn/dev/api#glm-4-alltools

**Comment by Myra009** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿机器人检测到问题正文的语言不是英语，自动翻译它。 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> Where did the glm-4-alltools model come from?glm-4-alltools 模型是从哪里来的？

https://open.bigmodel.cn/dev/api#glm-4-alltools
