### ISSUE TITLE
[Bug] qwen的api key在这里用不了

### ISSUE THREAD

**Issue by bakamake** [lobehub/lobe-chat#3108]
### 📦 部署环境

Docker

### 📌 软件版本

lastest

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

![🤯 随便聊聊 · LobeChat 和另外 14 个页面 - 个人 - Microsoft​ Edge 2024_7_1 23_58_52](https://github.com/lobehub/lobe-chat/assets/159852463/89296f62-3833-42ab-ad61-03e25e4df090)
报的错qwen的文档里没有，另外同一个key在chatbox上可以用
![Chatbox 2024_7_1 23_48_21](https://github.com/lobehub/lobe-chat/assets/159852463/ede6657b-efe2-412b-a994-fcbe0a0fcdf4)

### 📷 复现步骤

![🤯 随便聊聊 · LobeChat 和另外 14 个页面 - 个人 - Microsoft​ Edge 2024_7_2 0_03_57](https://github.com/lobehub/lobe-chat/assets/159852463/df3e4ba5-94cd-4320-925d-efec58494107)

### 🚦 期望结果

搞不懂这是不是bug

**Comment by arvinxx** [comment]
关掉客户端请求模式

**Comment by bakamake** [comment]
关掉后设置检查连通性成功
![🤯 随便聊聊 · LobeChat 和另外 12 个页面 - 个人 - Microsoft​ Edge 2024_7_2 0_22_21](https://github.com/lobehub/lobe-chat/assets/159852463/3da4561a-ea42-4c5e-9541-56f02b4e8964)

**但是**请求还是有报错，而且是**两种不一样的报错**
如下两图
![image](https://github.com/lobehub/lobe-chat/assets/159852463/6f2a934f-87b4-4cb0-9a46-d0a41ca2a635)
![🤯 随便聊聊 · LobeChat 和另外 12 个页面 - 个人 - Microsoft​ Edge 2024_7_2 0_22_25](https://github.com/lobehub/lobe-chat/assets/159852463/bc9a6bfe-2513-4b42-bea3-cf1233b7eb2d)

**Comment by arvinxx** [comment]
你自己配了一个 qwen 的模型？换一个别的试试

**Comment by bakamake** [comment]
deepseek正常使用，api-key是在阿里灵积调的

**Comment by arvinxx** [comment]
你切一个另外的 qwen模型试试

**Comment by bakamake** [comment]
换来换去，已知massage:“ 'frequency_penalty' is not supported now",

**Comment by Mingholy** [comment]
> 换来换去，已知massage:“ 'frequency_penalty' is not supported now",

如果是自定义LLM，模型名称需要是以下枚举值之一
`qwen-turbo``qwen-plus``qwen-max``qwen-max-0428``qwen-max-0403``qwen-max-0107``qwen-max-1201``qwen-max-longcontext`
入参需要满足文档要求：https://help.aliyun.com/zh/dashscope/developer-reference/api-details

**Comment by bakamake** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/159852463/2180f841-deab-42ed-9189-c08d66b674c4)
