### ISSUE TITLE
[Request] How to disable sign up when using clerk. (如何禁止注册)

### ISSUE THREAD

**Issue by vegetablesB** [lobehub/lobe-chat#3113]
### 🥰 需求描述

How to disable sign up when using clerk? (如何禁止注册)

### 🧐 解决方案

The only secure way to do that is using the allow list option in your Clerk dashboard.

The bad new is that you can't use it in production mode with the free plan

**Comment by NiallLDY** [comment]
估计都得在代码层面把登陆UI改掉，或者买clerk会员

**Comment by vegetablesB** [comment]
dup https://github.com/lobehub/lobe-chat/issues/2915

**Comment by Sun-drenched** [comment]
> 估计都得在代码层面把登陆UI改掉，或者买clerk会员

个人用的话用clerk DEV模式开白名单也行
