### ISSUE TITLE
在vps上docker总是异常推出

### ISSUE THREAD

**Issue by wming126** [lobehub/lobe-chat#3115]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Ubuntu

### 🌐 Browser

Firefox

### 🐛 Bug Description

docker 服务运行一段时间后服务异常推出。docker ps查看无docker进程。

### 📷 Recurrence Steps

长期运行docker 进程自动退出。

### 🚦 Expected Behavior

可长期稳定运行。

### 📝 Additional Information

none

**Comment by arvinxx** [comment]
这个你自行解决吧，我没有遇到过哎
