### ISSUE TITLE
[Bug] 通过AWS的Bedrock的claude3或者claude 3.5，无法分析图片

### ISSUE THREAD

**Issue by kun-ma** [lobehub/lobe-chat#3116]
### 📦 Environment

Docker

### 📌 Version

v1.2.3

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

上传图片到聊天窗口后，就会报错，图片本身很小
{
  "message": "很抱歉，服务器似乎迷失了方向，暂时无法提供服务，请稍后再试",
  "type": 502
}

**Comment by breakstring** [comment]
Hi team, please also check #3001  
Anthropic 3.5 failed with base64 issue.

**Comment by arvinxx** [comment]
duplicate with #3001
