### ISSUE TITLE
[Bug] 服务端数据库模式下, 如果未登录报401错误，期望跳到登录页

### ISSUE THREAD

**Issue by gaspire** [lobehub/lobe-chat#3120]
### 📦 Environment

Other

### 📌 Version

latest

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

服务端数据库模式下, 如果未登录报401错误，期望跳到登录页

**Comment by arvinxx** [comment]
duplicate of #2909
