### ISSUE TITLE
[Bug] -language_model_settings 的 FEATURE_FLAGS 不起作用

### ISSUE THREAD

**Issue by breakstring** [lobehub/lobe-chat#3123]
### 📦 部署环境

Vercel

### 📌 软件版本

1.2.3

### 💻 系统环境

macOS

### 🌐 浏览器

Other

### 🐛 问题描述

备注：客户端为 PWA 应用

 在FEATURE_FLAGS里面设置了-language_model_settings 后，在客户端依然可以设置语言模型。

### 📷 复现步骤

1. Vercel 部署时在环境变量里面设置 FEATURE_FLAGS 其中包含-language_model_settings
2. 重新部署
3. 重新打开客户端
4. 进入应用设置，点击语言模型并修改
<img width="996" alt="image" src="https://github.com/lobehub/lobe-chat/assets/14105911/b86843e8-0b29-4e6d-9eb7-2e0a85458658">
<img width="1011" alt="image" src="https://github.com/lobehub/lobe-chat/assets/14105911/bd46b510-2d46-4996-9901-d53d797638f4">

### 🚦 期望结果

应该无法看到语言模型或者无法修改吧？抱歉不太熟悉咱们的代码，不太清楚这个 flag 具体的设定行为到底应该是怎样。

**Comment by arvinxx** [comment]
去掉引号

**Comment by breakstring** [comment]
> 去掉引号

多谢，我试试看。。。。。我看文档里有个地方写着要加上引号防止解析错误
:(

**Comment by breakstring** [comment]
> 去掉引号

去掉引号后可以了。多谢。
