### ISSUE TITLE
[Bug] 部署服务端数据库模式不能全文检索了

### ISSUE THREAD

**Issue by m-guo** [lobehub/lobe-chat#3124]
### 📦 Environment

Vercel

### 📌 Version

v1.2.3

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

服务端数据库模式下不能本地数据库那行全文检索了，连话题也无法搜索了

**Comment by arvinxx** [comment]
哪里的搜索挂了？我可以搜的呀

**Comment by m-guo** [comment]
command + K 搜索
![Screenshot 2024-07-02 at 21 48 43](https://github.com/lobehub/lobe-chat/assets/8684229/19f7254b-ed9a-426b-9233-7c5f8daec1ad)

我部署的环境可以在多端设备上同步数据，文字和图片都同步过去了；但是搜索框单个字符都搜索不到。

**Comment by shog86** [comment]
我Vercel服务端部署的，确实搜不出来，对话内容和助手名字都搜不出来

<img width="887" alt="image" src="https://github.com/lobehub/lobe-chat/assets/19712631/80c79e30-785e-49db-97b4-2a7f5f81c1d1">

<img width="859" alt="image" src="https://github.com/lobehub/lobe-chat/assets/19712631/4c8ff7a5-9dcc-4b23-964f-9e25db207fba">

**Comment by xwydq** [comment]
> 服务端数据库模式下不能本地数据库那行全文检索了，连话题也无法搜索了

请问服务端数据库模式部署时 一直报错：
```
$ bun run db:migrate
$ MIGRATION_DB=1 tsx scripts/migrateServerDB/index.ts
❌ Database migrate failed: ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] {
      error: [Function],
      message: [Function],
      close: [Function],
      open: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'arraybuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _errorEmitted: true,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'wss://35.232.228.178/v2',
    _req: null,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
      at TLSSocket.emit (node:events:518:28)
      at TLSSocket._finishInit (node:_tls_wrap:1085:8)
      at ssl.onhandshakedone (node:_tls_wrap:871:12) {
    code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
  },
  [Symbol(kMessage)]: 'unable to verify the first certificate'
}
error: script "db:migrate" exited with code 1
error: script "build-migrate-db" exited with code 1
error: script "postbuild" exited with code 1
Error: Command "bun run build" exited with 1
```
------------------
是什么原因

**Comment by m-guo** [comment]
![Screenshot 2024-07-11 at 21 54 52](https://github.com/lobehub/lobe-chat/assets/8684229/ac2b208f-f489-417e-b48d-273ee35f09d2)
在话题搜索框里可以进行全文检索。版本 v1.3.5

**Comment by shog86** [comment]
> ![Screenshot 2024-07-11 at 21 54 52](https://github.com/lobehub/lobe-chat/assets/8684229/ac2b208f-f489-417e-b48d-273ee35f09d2)
> 
> 在话题搜索框里可以进行全文检索。版本 v1.3.5
> 
> 
> 
> 我的部署环境完全使用官方文档的步骤和用到的服务（数据库）。
> 
> 

你的搜索有结果吗，我就搜看到的助手名字（里的一个词）都没任何结果显示

**Comment by m-guo** [comment]
> > ![Screenshot 2024-07-11 at 21 54 52](https://private-user-images.githubusercontent.com/8684229/347844962-ac2b208f-f489-417e-b48d-273ee35f09d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDY4NTksIm5iZiI6MTcyMDc0NjU1OSwicGF0aCI6Ii84Njg0MjI5LzM0Nzg0NDk2Mi1hYzJiMjA4Zi1mNDg5LTQxN2UtYjQ4ZC0yNzNlZTM1ZjA5ZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMDEwOTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWIxMTAzOTYwZTEyNWY2YWMwMmU2NGZmZGI4YjQ0NzU5MjEyNWRjMTc2ZjgyMzQ2Y2ExYTAxODA4MzlhMDhjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zWre4775wmpJ30u5DnBr1d6wYPxhptiAeAca27izGcw)
> > 在话题搜索框里可以进行全文检索。版本 v1.3.5
> > 我的部署环境完全使用官方文档的步骤和用到的服务（数据库）。
> 
> 这儿搜索是有结果的，但你在助手列表那里（也就是首页）搜索有结果吗，我就搜看到的助手名字（里的一个词）都没任何结果显示

没有啊，这个单子原本就是反馈这个问题的，我这个只是补充下信息。

**Comment by Aliang-code** [comment]
应该是要指定这个
```
# 指定 Postgres database driver 为 node
DATABASE_DRIVER=node
```

**Comment by m-guo** [comment]
> 应该是要指定这个
> 
> ```
> # 指定 Postgres database driver 为 node
> DATABASE_DRIVER=node
> ```

我的情况确实是没有配置这个，翻了下文档，是应该添加这个环境变量。

但是我添加完，然后重新部署之后还是无法搜索，一样的现象。

**Comment by m-guo** [comment]
> > 应该是要指定这个
> > ```
> > # 指定 Postgres database driver 为 node
> > DATABASE_DRIVER=node
> > ```
> 
> 我的情况确实是没有配置这个，翻了下文档，是应该添加这个环境变量。
> 
> 但是我添加完，然后重新部署之后还是无法搜索，一样的现象。

我使用的 Vercel 提供的那个 Vercel Postgres，这个应该不需要配置DATABASE_DRIVER，所以还是不知道哪里的问题。

**Comment by arvinxx** [comment]
是 bug ，我近期修下

**Comment by 80imike** [comment]
> 是 bug ，我近期修下

<img width="332" alt="image" src="https://github.com/user-attachments/assets/515a4d8d-13b4-4ca4-a709-bd5f3a1f8c17">



<img width="323" alt="image" src="https://github.com/user-attachments/assets/bd167ffa-90bd-4bde-a41a-b175c4810fef">


这个 bug 依旧存在

**Comment by CloudPassenger** [comment]
The same problem occurs in my senerio, using Vercel + Neon Postgres deployment

**Comment by arvinxx** [comment]
@80imike @CloudPassenger 还没修，近期修复

**Comment by 80imike** [comment]
> @80imike @CloudPassenger 还没修，近期修复

这个问题 1.9.22 还没有修复呀，期待尽快修复，没有搜索的确不方便

**Comment by zcsunt** [comment]
same problem

**Comment by 80imike** [comment]
再来看看，期待早日修复

**Comment by m-guo** [comment]
期待早日修复，还是很重要的功能的。

**Comment by arvinxx** [comment]
@80imike 这个月后半月弄下，其实也困扰我😅

**Comment by m-guo** [comment]
1.32.1 版本还是无法全文检索，只解决了搜索助手的名字：
![image](https://github.com/user-attachments/assets/8e63885d-fa7d-4bf1-8122-91b61999e61f)

**Comment by arvinxx** [comment]
@cy948 是不是可以考虑把 message 的 content 检索也加上？

**Comment by cy948** [comment]
@arvinxx 按照目前的实现，如果直接搜消息内容全文可能会有性能问题。可能得先建全文索引才能做。

**Comment by m-guo** [comment]
![image](https://github.com/user-attachments/assets/d9eb5780-c251-4c3d-ac5f-34e9a935c573)

除了不能全文检索，现在除了可以在第一个内部搜索，其余的助手内部检索功能也失效了：
![image](https://github.com/user-attachments/assets/91e137ef-1847-4243-83a0-6b9282c98f6b)
