### ISSUE TITLE
[Bug] 正如#2728提到的问题,对于top域名需要访问npmmirror的资源无法加载

### ISSUE THREAD

**Issue by Mgrsc** [lobehub/lobe-chat#3125]
### 📦 部署环境

Docker

### 📌 软件版本

v1.2.3

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome, Edge, Firefox

### 🐛 问题描述

正如问题 [#2728 ](https://github.com/lobehub/lobe-chat/issues/2728)所提到的top域名无法访问npmmirror资源，导致很多功能无法使用，可否考虑迁移到别的存储库，或者提供离线版本
![image](https://github.com/lobehub/lobe-chat/assets/118801216/b161f903-50e1-461c-8477-b28e4dde3003)

**Comment by arvinxx** [comment]
不计划解决。建议换 .com 等域名。

**Comment by eronez** [comment]
@Mgrsc 
For PC, "CORS Unblock" is all your need.
For Mobile and Tablet, try browser which can use "CORS Unblock".
It's better to avoid using .top domain.
