### ISSUE TITLE
[Bug] 低版本的iOS无法使用

### ISSUE THREAD

**Issue by AndyLin2020** [lobehub/lobe-chat#3128]
### 📦 Environment

Docker

### 📌 Version

v1.2.5

### 💻 Operating System

iOS

### 🌐 Browser

Safari

### 🐛 Bug Description

iPhone 12 ，系统iOS 14.3，Docker部署了Lobe-Chat，打开首页点击开如后提示 “页面遇到一点问题”
14.4.2试过也一样提示

**Comment by arvinxx** [comment]
升级系统，低版本有问题我们不计划兼容
