### ISSUE TITLE
[Bug] Microsoft Entra ID 正确配置后不显示SSO登录入口

### ISSUE THREAD

**Issue by ykangw** [lobehub/lobe-chat#3136]
### 📦 部署环境

Vercel

### 📌 软件版本

1.2.6

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

在Vercel按照文档（https://lobehub.com/zh/docs/self-hosting/advanced/sso-providers/microsoft-entra-id）正确配置了Microsoft Entra ID作为SSO登录服务。在过去几个月，SSO登录一直使用正常。但是从大约2周前（约1.0.0版本）开始，登录选项里不再显示SSO登录（见下图）。

<img width="891" alt="image" src="https://github.com/lobehub/lobe-chat/assets/72436879/b271ba01-2410-40df-8d33-9748ae67bf3f">

在Azure检查确认Microsoft Entra ID没有问题。

把Lobe回退到历史版本可以暂时解决。希望尽快修复，谢谢。

**Comment by arvinxx** [comment]
看下配置，以及后台有没有报错

**Comment by ykangw** [comment]
> 看下配置，以及后台有没有报错

配置的环境变量和中文文档完全一致，后台没有报错

**Comment by ykangw** [comment]
我注意到文档的两个页面对于环境变量的说明有些不同。

- 文档页面1:https://lobehub.com/zh/docs/self-hosting/environment-variables/auth#microsoft-entra-id
- 文档页面2:https://lobehub.com/zh/docs/self-hosting/advanced/sso-providers/microsoft-entra-id

我按照文档页面1设置了如下环境变量，没有SSO入口：
NEXT_AUTH_SSO_PROVIDERS azure-ad
NEXTAUTH_SECRET
AZURE_AD_CLIENT_ID
AZURE_AD_CLIENT_SECRET
AZURE_AD_TENANT_ID
ACCESS_CODE

也尝试过按照文档页面2增加这两个环境变量，但还是没有SSO入口：
ENABLE_OAUTH_SSO 1
SSO_PROVIDERS azure-ad

两种配置在vercel后台都没有报错。

**Comment by arvinxx** [comment]
@cy948 帮忙看看？

**Comment by cy948** [comment]
将在 #2935 中修复。
