### ISSUE TITLE
[Bug] Claude API接口代理地址不能完全自定义

### ISSUE THREAD

**Issue by tomleung1996** [lobehub/lobe-chat#3139]
### 📦 部署环境

Docker

### 📌 软件版本

1.2.5

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

使用第三方的Claude API接口时，lobechat会向/v1/messages请求，但服务商的API地址为/v1/chat/completions（与OpenAI类似），导致没有办法正常使用。请问有相应的处理方法么？

**Comment by arvinxx** [comment]
那你套 openai 的url，cluade 接入的是官网的 SDK，接口参数都不一样，你如果用 oneapi 这种是没法正常 work 的。

**Comment by NeonBubbles** [comment]
只需要在lobechat的openai模型那设置，然后点击模型列表右下方的“获取模型列表”，添加claude模型后就能直接使用了。
根本不用在anthropic模型那设置。
