### ISSUE TITLE
问下上传word excel txt 这个功能这个月可以上线了嘛，我看DB已经有了[Request] 

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#3140]
### 🥰 需求描述

问下上传word excel txt 这个功能这个月可以上线了嘛，我看DB已经有了

### 🧐 解决方案

问下上传word excel txt 这个功能这个月可以上线了嘛，我看DB已经有了

### 📝 补充信息

问下上传word excel txt 这个功能这个月可以上线了嘛，我看DB已经有了

**Comment by XiaolongYang-HZAU** [comment]
同求，拜托啦
