### ISSUE TITLE
[Request] 希望有可以自己设置搜索引擎的网络搜索插件

### ISSUE THREAD

**Issue by Myra009** [lobehub/lobe-chat#3142]
### 🥰 需求描述

希望有可以自己设置搜索引擎的网络搜索插件，现在的网络插件都是使用谷歌的

### 🧐 解决方案

希望有可以自己设置搜索引擎的网络搜索插件

**Comment by arvinxx** [comment]
已经在 Cloud 版本支持

<img width="1522" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/98e1178f-13bf-46db-bb59-c5938f0a2944">
