### ISSUE TITLE
[Bug] 通过模型的扩展能力配置无法使gpt-4-turbo这个模型不显示vision和fc功能

### ISSUE THREAD

**Issue by zidou-kiyn** [lobehub/lobe-chat#3144]
### 📦 Environment

Docker

### 📌 Version

1.2.9

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

我按照文档的[https://lobehub.com/zh/docs/self-hosting/advanced/model-list](模型扩展能力设置)无法使gpt-4-turbo等模型不显示vision和fc功能如图
![image](https://github.com/lobehub/lobe-chat/assets/63180724/b868d1ca-5a0a-4ec1-87a4-285dffed325a)
![image](https://github.com/lobehub/lobe-chat/assets/63180724/5e0833e7-ebb1-4b7b-9fbd-0324057c9aee)
并且gpt-3.5-turbo的支持tokens显示错误，16000应该显示为16k，网页显示为15k

**Comment by zidou-kiyn** [comment]
并且我希望给kimi模型添加一个moonshot的icon

**Comment by arvinxx** [comment]
你咋配的

**Comment by zidou-kiyn** [comment]
> 你咋配的

配置就在第二张截图中

**Comment by arvinxx** [comment]
16000 当然不是16k, 16000 / 1024 = ?

看了下的确不支持去掉 vision 和 fc ，但这个需求太小众了，不准备做了

**Comment by arvinxx** [comment]
@BrandonStudio 模型厂商这么搞的，比如 128k OpenAI 的定义就是 128000 。这个得问 OpenAI 为啥这么搞…

**Comment by skymkmk** [comment]
@arvinxx 部分 API 中转服务强行兼容的 OpenAI 格式可能会导致 FC 功能不可用，这种时候能关掉 FC 是最好的。是否考虑一下加上用自定义扩展能力完全覆盖模型能力？而且我个人感觉现有的扩展功能语法如果不是覆盖的话也不符合直觉。
