### ISSUE TITLE
[Request] 希望增加一个“继续生成”按钮

### ISSUE THREAD

**Issue by bestZwei** [lobehub/lobe-chat#3145]
### 🥰 需求描述

希望增加一个“继续生成”按钮，在AI没一次性输出完完整结果时，点击该按钮，继续生成上一条消息。

### 🧐 解决方案

希望增加一个“继续生成”按钮，在AI没一次性输出完完整结果时，点击该按钮，继续生成上一条消息。

**Comment by arvinxx** [comment]
duplicate https://github.com/lobehub/lobe-chat/issues/1379
