### ISSUE TITLE
[Request] docker上部署 和本地部署，速度上差了很多，我想问题是否有与docker类似的版本提供

### ISSUE THREAD

**Issue by lwdnxu** [lobehub/lobe-chat#3148]
### 🥰 需求描述

[Request] docker上部署 和本地部署，速度上差了很多，我想问题是否有与docker类似的版本提供

### 🧐 解决方案

是否可以提供更简洁的lobe-chat的版本，比如只有和docker中内容类似的，因为我看docker中的/app文件夹下的内容是非常简洁的，谢谢

**Comment by arvinxx** [comment]
没懂你的本地部署指的是啥

**Comment by lwdnxu** [comment]
> 没懂你的本地部署指的是啥

就是我想进行二次开发，下载源码以后本地部署了，但是跑起来非常慢，在几百G内存和4090上都试了，初次加载得几分钟，因此我想请问一下，是否有和docker安装一样较为简洁的版本

**Comment by arvinxx** [comment]
未来可能会考虑做一个桌面端版本，但你说的这种版本应该是不会有的。

以及慢的问题也可能是你的代码实现问题。水合不正确就可能会有首屏加载慢的问题。
