### ISSUE TITLE
Your LobeChat gives too few chat points!

### ISSUE THREAD

**Issue by ceeheemee** [lobehub/lobe-chat#3149]
### 🥰 需求描述

The usage points you provide for free users are too few and not enough. If you really want to benefit people, the benefits you provide in the name of open source are too low. Can you improve or add more benefits for free users?

### 🧐 解决方案

Allow free users to use more points to chat and allow free users to continue chatting with LobeChat's artificial intelligence that integrates multiple artificial intelligences on more topics? 🧐🧐🧐

**Comment by arvinxx** [comment]
No, Open Source is our benefit way. the LobeChat Cloud is our commercial version. If you think the free is not engouth, you can pay for it. Or you can deploy your own LobeChat with your own api key
