### ISSUE TITLE
[Bug] 同步时经常失败，稳定性需要改进

### ISSUE THREAD

**Issue by Nicecsh** [lobehub/lobe-chat#3157]
### 📦 部署环境

Vercel

### 📌 软件版本

v0.162.25

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

同步功能不够稳定
![屏幕截图(101)](https://github.com/lobehub/lobe-chat/assets/22073409/c38d3913-4996-4311-9f47-9c866b4e804e)

**Comment by Sun-drenched** [comment]
1.X版已经支持基于服务端数据库的同步，并默认关闭了WebRTC 同步功能

**Comment by Nicecsh** [comment]
> 1.X版已经支持基于服务端数据库的同步，并默认关闭了WebRTC 同步功能

您好！X版是现在的最新版v1.2.13还是其它意思呢？我是fork了lobechat部署在vercel上，设置了Upstream Sync Action自动更新。
这段时间自动更新会失败，不知道如何解决。

![image](https://github.com/lobehub/lobe-chat/assets/22073409/47913435-33f5-40b6-bb45-334bad7f1389)

**Comment by sxjeru** [comment]
可以试试手动拉取，或者删掉存储库重新 fork 一份。

![image](https://github.com/lobehub/lobe-chat/assets/20513115/3b65ffe8-5217-4b24-a052-a3e7d1fae79a)

**Comment by shog86** [comment]
我也vercel，目前自动sync没啥问题，也部署了服务端，香

**Comment by xenstar** [comment]
> > Version 1.X already supports synchronization based on the server database, and the WebRTC synchronization function is turned off by default.
> 
> Hello! Is version X the latest version v1.2.13 or does it mean something else? I forked lobechat and deployed it on vercel, and set Upstream Sync Action to automatically update. Automatic updates will fail during this period. I don’t know how to solve it. Manually running the workflow also fails. The picture below is a screenshot of the error message.
> 
> ![image](https://private-user-images.githubusercontent.com/22073409/346335688-47913435-33f5-40b6-bb45-334bad7f1389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzODkwMzUsIm5iZiI6MTcyMDM4ODczNSwicGF0aCI6Ii8yMjA3MzQwOS8zNDYzMzU2ODgtNDc5MTM0MzUtMzNmNS00MGI2LWJiNDUtMzM0YmFkN2YxMzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDIxNDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMWM0YmZlNzAzMWRhNjNkZmFlZTI4Y2ViNzY4ZjhkNTg1MzAwNmE0ZTRjMjI3YzQwMzhkNzdmNDk5MTdmMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gfpfLV1LHr6b6Q2r6i2GrWP6FSL2IJYDDbXqJBfQ9l4)

I also have the same problem. They messed up something in the code..

**Comment by Nicecsh** [comment]
> 可以试试手动拉取，或者删掉存储库重新 fork 一份。
> 
> ![image](https://private-user-images.githubusercontent.com/20513115/346337149-3b65ffe8-5217-4b24-a052-a3e7d1fae79a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjUxOTIsIm5iZiI6MTcyMDQyNDg5MiwicGF0aCI6Ii8yMDUxMzExNS8zNDYzMzcxNDktM2I2NWZmZTgtNTIxNy00YjI0LWEwNTItYTNlN2QxZmFlNzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA3NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZmU5NmUwZWE0ODk0ZmU1ZTJjOTU4Mzg4NTA3MmQxYjBjNTdiODUxYmUxZDgxMWU1YTcyNzViOWE2MzdkM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z97ncieFZygA3egFiWBSg78oX91wYMJ-mNyBzYGgFAs)

谢谢提醒！点了“sync fork"后，提示有52条讨论无法同步，可以选择忽略掉52条讨论，然后自动同步到了最新版！

**Comment by Nicecsh** [comment]
> > > Version 1.X already supports synchronization based on the server database, and the WebRTC synchronization function is turned off by default.
> > 
> > 
> > Hello! Is version X the latest version v1.2.13 or does it mean something else? I forked lobechat and deployed it on vercel, and set Upstream Sync Action to automatically update. Automatic updates will fail during this period. I don’t know how to solve it. Manually running the workflow also fails. The picture below is a screenshot of the error message.
> > ![image](https://private-user-images.githubusercontent.com/22073409/346335688-47913435-33f5-40b6-bb45-334bad7f1389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzODkwMzUsIm5iZiI6MTcyMDM4ODczNSwicGF0aCI6Ii8yMjA3MzQwOS8zNDYzMzU2ODgtNDc5MTM0MzUtMzNmNS00MGI2LWJiNDUtMzM0YmFkN2YxMzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDIxNDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMWM0YmZlNzAzMWRhNjNkZmFlZTI4Y2ViNzY4ZjhkNTg1MzAwNmE0ZTRjMjI3YzQwMzhkNzdmNDk5MTdmMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gfpfLV1LHr6b6Q2r6i2GrWP6FSL2IJYDDbXqJBfQ9l4)
> 
> I also have the same problem. They messed up something in the code..

🤝

**Comment by Nicecsh** [comment]
> 我也vercel，目前自动sync没啥问题，也部署了服务端，香

同样的部署方法，你幸运啊！我这是第二次自动同步出问题了
