### ISSUE TITLE
通过Vercel部署时支持多用户管理和上传文档进行数据分析[Request] 

### ISSUE THREAD

**Issue by michael7908** [lobehub/lobe-chat#3163]
### 🥰 需求描述

目前通过Vercel部署时，不支持多用户通过用户名和密码登录，不方便；
而且不支持上传Word等文档进行数据分析。

### 🧐 解决方案

通过Vercel部署时支持多用户管理和上传文档进行数据分析

**Comment by arvinxx** [comment]
已经支持用户登陆了 https://lobehub.com/zh/docs/self-hosting/advanced/server-database

文件上传已经很多人提过了，正在做
