### ISSUE TITLE
[Bug] 无法调用插件，没有错误提示。

### ISSUE THREAD

**Issue by ftalk** [lobehub/lobe-chat#3165]
### 📦 Environment

Vercel

### 📌 Version

Next.js  (14.2.4)

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

已经安装插件，但是无法使用。无论是画图、搜索还是其他功能，对话都无法调用插件，也没有错误提示。
这里使用 OpenAI 的 API 是 DeepBricks 的 API 服务，对答正常。

### 📷 Recurrence Steps

1. 检查 DeepBricks OpenAI API 正常使用。
2. 安装插件
3. 勾选插件
4. 对话中明确表示“搜素”“画图”“draw”等文字。
5. 没有报错，只是想普通对答那样回复。没有调用插件的痕迹。

<img width="1004" alt="Screenshot 2024-07-08 at 01 31 00" src="https://github.com/lobehub/lobe-chat/assets/49120188/95968e71-25ea-46ee-bf57-9c5d5d2a3f86">

### 🚦 Expected Behavior

应该有报错信息。
或者正常使用插件。

**Comment by SAnBlog** [comment]
使用这个项目几个月了,一次插件都没成功使用过,每次安装后要么没调用,要么就是调用返回空白错误

**Comment by arvinxx** [comment]
那说明 DeepBricks API 不是官方原版，不支持 Tools Calling

**Comment by arvinxx** [comment]
@SAnBlog 请检查你的 api provider 是否是支持 Tools Calling

**Comment by ftalk** [comment]
> 那说明 DeepBricks API 不是官方原版，不支持 Tools Calling

谢谢！
更换成 OpenRouter 的 API 之后可以正常使用插件。谢谢！

<img width="1004" alt="Screenshot 2024-07-08 at 01 31 00" src="https://github.com/lobehub/lobe-chat/assets/49120188/b6a4b072-d4bd-42f8-b294-1c9db87caf07">
