### ISSUE TITLE
QNAP plug-in not working issue

### ISSUE THREAD

**Issue by bjdr69** [lobehub/lobe-chat#3166]
At the same time, lobe-chat is deployed on Amazon's EC2 linux VPS and QNAP 464C with docker, and the plug-in function can be implemented on EC2, but no matter which large model is selected on QNAP, the plug-in icon cannot be lit up in the session interface (even if several models are installed in the plug-in store), what special settings are required for plug-in applications on QNAP NAS?

**Comment by arvinxx** [comment]
what's the QNAP?

**Comment by Matinal111** [comment]
> QNAP 是什么？
威联通 NAS，可以使用 docker 容器服务

**Comment by Lockeysama** [comment]
> what's the QNAP? 
NAS 😂

**Comment by arvinxx** [comment]
The plugin is not relative with deployment platform. you need to check your model list config

**Comment by Lockeysama** [comment]
> The plugin is not relative with deployment platform. you need to check your model list config

@bjdr69

**Comment by bjdr69** [comment]
> > The plugin is not relative with deployment platform. you need to check your model list configThe plugin is not relative with deployment platform. You need to check your model list configuration
>
> @bjdr69

Thanks, it's solved now
