### ISSUE TITLE
[Bug] 配置OLLAMA_HOST不生效

### ISSUE THREAD

**Issue by qian-lou** [lobehub/lobe-chat#3168]
### 📦 Environment

Other

### 📌 Version

v1.2.13

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

<img width="454" alt="image" src="https://github.com/lobehub/lobe-chat/assets/43488993/b127bedd-776e-46d9-88b6-203ae1b2a45c">
已经配置了，但是还是无法访问

### 📷 Recurrence Steps

1

### 🚦 Expected Behavior

1

### 📝 Additional Information

1

**Comment by qian-lou** [comment]
> 👀 @qian-lou
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible. Please make sure you have given us as much context as possible. 非常感谢您提交 issue。我们会尽快调查此事，并尽快回复您。 请确保您已经提供了尽可能多的背景信息。

谢谢

**Comment by arvinxx** [comment]
配好之后应该要重启下服务的吧？

**Comment by arvinxx** [comment]
@qian-lou 此问题解决了吗
