### ISSUE TITLE
[Bug] 重置以及清除信息，似乎SerpAPI API Key依然被保存在浏览器中

### ISSUE THREAD

**Issue by i-iooi-i** [lobehub/lobe-chat#317]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/1827701/16062517-160b-4c01-aa6e-9bec149c38dd)
![image](https://github.com/lobehub/lobe-chat/assets/1827701/ef0d0e8e-bf63-4faf-9f88-9989561c4e4f)

如题，刚测试了一下。
重置以及清除信息之后，开启 “搜索引擎” ，SerpAPI API Key 依然在里面。

**Comment by arvinxx** [comment]
重置的范围的确没包含插件的设置，明天修下
