### ISSUE TITLE
[Bug] 配置OLLAMA_MODEL_LIST后必须手动刷新一次才生效

### ISSUE THREAD

**Issue by htdohk** [lobehub/lobe-chat#3173]
### 📦 部署环境

Vercel, Docker

### 📌 软件版本

v1.2.14

### 💻 系统环境

Windows, macOS, Android

### 🌐 浏览器

Chrome

### 🐛 问题描述

无论是Docker还是Vercel，配置OLLAMA_MODEL_LIST字段为“-all,+qwen2:7b-instruct-q4_0“，清空浏览器缓存后重新进入看到Ollama模型选项为空，必须重新在模型列表中点一次重置，才能刷出正确的模型。
![企业微信截图_16dd49ed-631c-4c99-9f9e-60047304e6a2](https://github.com/lobehub/lobe-chat/assets/107847138/c0923da6-bf36-4aab-bb1f-cc0dba4791a3)
![企业微信截图_a117fcd6-4006-48ea-b466-67fec29b01b3](https://github.com/lobehub/lobe-chat/assets/107847138/aeac1e56-be61-4e6e-abe6-b3a76c9cc0a7)
![企业微信截图_e81eb810-1117-4bee-aca5-a8cf3f8a6363](https://github.com/lobehub/lobe-chat/assets/107847138/a36bcf22-a2ec-44f4-940b-fce3dd945b0c)

**Comment by arvinxx** [comment]
fixed like https://github.com/lobehub/lobe-chat/issues/2101
