### ISSUE TITLE
[Bug] 无法正确识别127.0.0.1为本机ip地址

### ISSUE THREAD

**Issue by AppleRiven** [lobehub/lobe-chat#3180]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

我将CoGPT和Lobe部署在VPS上，CoGPT的端口为9000。

问题：
在Lobe的模型配置中，当我将OpenAI的api代理地址修改为http://127.0.0.1:9000/v1时，请求出错；但当我将api代理地址修改为http://myvps_public_ip:9000/v1时可以正常响应。

![image](https://github.com/lobehub/lobe-chat/assets/96679272/3bc1eaaf-42ec-48e0-bd11-c0c7349e0d16)

**Comment by arvinxx** [comment]
你如果用docker部署， 127.0.0.1 指向的不是本机地址，你得配成 host 模式才行。
