### ISSUE TITLE
[Bug] 对话框中选择Claude无法链接

### ISSUE THREAD

**Issue by Pai-Po** [lobehub/lobe-chat#3183]
### 📦 Environment

Zeabur

### 📌 Version

latest

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/12437819/3ffa2a02-9b34-48dd-904a-24a7dd5d99a9)
测试网络连接时，是可以连接通的；我的代理服务器也成功转发了请求；
然而当我在对话框中尝试用claude时，会发生如下错误，模型选择的是Haiku
{
  "error": {
    "status": 500,
    "headers": {
      "content-length": "142",
      "content-type": "application/json"
    },
    "error": {
      "timestamp": "2024-07-09T13:01:49.417+00:00",
      "path": "/v1/messages",
      "status": 500,
      "error": "Internal Server Error",
      "requestId": "35a60294-299671"
    }
  },
  "endpoint": "https://api.gp****pi.net/",
  "provider": "anthropic"
}
切换选择模型为3.5-sonnet时，会报如下错误
{
  "error": {
    "status": 404,
    "headers": {
      "content-type": "application/json"
    },
    "error": {
      "error": {
        "message": "Invalid URL (POST /v1/messages) (request id: )",
        "type": "invalid_request_error",
        "param": "",
        "code": ""
      }
    }
  },
  "endpoint": "https://api.gp****pi.net/",
  "provider": "anthropic"
}
，感觉有点问题

**Comment by arvinxx** [comment]
你用的是透明代理还是 one-api 这种类型的？这个 Proxy 只支持透明代理，不支持 one-api 这种

**Comment by shog86** [comment]
你试试把信息录到OpenAI那个地方去然后获取模型

**Comment by Pai-Po** [comment]
第一次向claude发送包，可以收到正常的回复，如下图：
![image](https://github.com/lobehub/lobe-chat/assets/12437819/026263e0-25ce-47f5-9252-f12df20fca1c)
但是从调试上看，onOpen函数成功执行了，但是返回的body值是空
![image](https://github.com/lobehub/lobe-chat/assets/12437819/e43ff017-fa52-4c5a-864d-fc4cadb4dae4)
进一步调试发现，是transformAnthropicStream这个transormer没有执行导致
![image](https://github.com/lobehub/lobe-chat/assets/12437819/6fbfb9bc-bcd1-40e5-83d8-a200057212e2)
![image](https://github.com/lobehub/lobe-chat/assets/12437819/d98905f2-1942-40b9-916c-4f97e92e2fb6)
劳烦帮忙看看，究竟是为啥？

**Comment by arvinxx** [comment]
@Pai-Po 你的代理接口的 chunk 的原始和 Anthropic 的一致吗？

**Comment by Pai-Po** [comment]
下面是从chrome中复制出来的返回内容，我不知道原始的Anthropic是什么样的，不过应该是一致的，你可以瞅瞅

data:{"type":"message_start","message":{"id":"msg_bdrk_01SgtEMUC7rHNa8JMKPSNnif","model":"claude-3-haiku-20240307","type":"message","role":"assistant","content":[],"usage":{"input_tokens":12,"output_tokens":1}}}

data:{"type":"content_block_start","index":0,"content_block":{"type":"text","text":""}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"很"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"高"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"兴"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"认"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"识"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"你"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"!"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"我"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"是"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"一"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"个"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"人"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"工"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"智"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"能"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"助"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"手"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":","}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"可"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"以"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"帮"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"助"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"你"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"完"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"成"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"各"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"种"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"任"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"务"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":","}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"比"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"如"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"回"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"答"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"问"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"题"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"、"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"提"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"供"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"建"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"议"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"和"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"分"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"析"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"数"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"据"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"等"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"。"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"你"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"有"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"什"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"么"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"需"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"要"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"帮"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"助"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"的"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"吗"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"?"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"我"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"会"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"尽"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"我"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"所"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"能"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"为"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"你"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"服"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"务"}}

data:{"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"。"}}

data:{"type":"content_block_stop","index":0}

data:{"type":"message_delta","delta":{"stop_reason":"end_turn"},"usage":{"output_tokens":79}}

data:{"type":"message_stop"}

**Comment by arvinxx** [comment]
我看了下这个请求应该是 Anthropic 的官方流的结构，所以响应应该没问题。你现在是怎么填写的？为什么我感觉你这个像是走了客户端请求

**Comment by Pai-Po** [comment]
是的，我勾选的走客户端请求，我觉得没必要绕一下后端再发。但是我关了走客户端请求，在zeabur上部署的也不通，就是检查链接那都不通，不知道是不是zeabur服务器也做了限制；反正是本地存储key，客户端还是好点。

**Comment by arvinxx** [comment]
@Pai-Po 如果可以的话私戳我下 proxy地址和 api key ？我可能需要测下你这个 case
