### ISSUE TITLE
[Bug] Netlify 部署陷入死循环

### ISSUE THREAD

**Issue by shylock-wu** [lobehub/lobe-chat#3189]
### 📦 Environment

Netlify

### 📌 Version

v1.3.5

### 💻 Operating System

macOS

### 🌐 Browser

Edge

### 🐛 Bug Description

看样子应该是EsLint依赖的版本出了问题，导致部署的时候Netlify一致重复输出
![CleanShot 2024-07-10 at 15 41 54@2x](https://github.com/lobehub/lobe-chat/assets/73875874/a8f44473-7528-43e6-a939-daaf80b4d8f1)

### 📷 Recurrence Steps

导入新的项目部署就会遇到这个问题

### 🚦 Expected Behavior

不报错，正常打包部署

**Comment by arvinxx** [comment]
你用的是 pnpm 吗

**Comment by shylock-wu** [comment]
﻿
﻿
不是，就是用的配置文件，我看是npm run build

在 2024年7月10日，17:25，Arvin Xu ***@***.***> 写道：

﻿

你用的是 pnpm 吗

**Comment by shylock-wu** [comment]
不是，就是用的配置文件，我看是npm run build
![CleanShot 2024-07-10 at 20 01 48@2x](https://github.com/lobehub/lobe-chat/assets/73875874/e12ae282-9133-4ef1-b190-89f65c35548b)

**Comment by arvinxx** [comment]
换成pnpm install试试

**Comment by shylock-wu** [comment]
只能修改打包命令吧，例如修改成`pnpm build`，下载依赖的命令，netlify好像是自动的，没法修改
从构建信息看，自动使用的`npm`
![CleanShot 2024-07-12 at 10 22 29](https://github.com/user-attachments/assets/10cd18d2-6dfc-4fbe-82d7-0d4c36429c88)

**Comment by shylock-wu** [comment]
Netlify 部署失败，AI 给的答复，EsLint相关依赖的问题，但我估计正常安装也会有这个问题
![CleanShot 2024-07-12 at 11 51 41](https://github.com/user-attachments/assets/c1260c3d-464e-45f8-8866-56a60253baf3)

**Comment by RubuJam** [comment]
同步一下最新的代码，应该修复了这个问题

Synchronize the latest code, this problem should be fixed

**Comment by shylock-wu** [comment]
> 同步一下最新的代码，应该修复了这个问题
> 
> Synchronize the latest code, this problem should be fixed

你们测试过了吗，去Netlify导入一个项目测试一下很简单的，实际上并没有修复。我部署最新的代码还是同样的问题，使用`pnpm`跟部署失败没有关系

**Comment by shylock-wu** [comment]
是这个包`@typescript-eslint/eslint-plugin`对等依赖的问题
![CleanShot 2024-07-15 at 12 12 51](https://github.com/user-attachments/assets/a05c82a9-8a51-4747-b373-388caabb9a3e)

**Comment by RubuJam** [comment]
@shylock-wu 我尝试修改了配置文件，但无论如何都会存在问题，我建议你改用`Vercel`

I tried modifying the configuration file, but the problem persists regardless. I suggest you use `Vercel` instead.

**Comment by shylock-wu** [comment]
多谢🤗！
使用`Vercel`部署没问题，之所以要在`Netlify`部署，是因为我发现`Vervel`的提供的免费域名被污染了，我的Wifi打不开，但是用Netlify部署的可以打开，都是在不开🪜的情况下

**Comment by RubuJam** [comment]
@shylock-wu  或许你可以试一试Zeabur或Sealos，这两个平台应该还未被污染

Maybe you can try Zeabur or Sealos, these two platforms should not be polluted yet.

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/pull/3232 可以再试试 @shylock-wu
