### ISSUE TITLE
[Docs] Feedback for `self-hosting/examples/azure-openai`

### ISSUE THREAD

**Issue by mask0918** [lobehub/lobe-chat#3191]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/examples/azure-openai.zh-CN.mdx

### 🐛 Feedback

The markdown source file is normal, but it is displayed incorrectly on the lobehub website
Loading page reports error.
![image](https://github.com/lobehub/lobe-chat/assets/32533802/a9d6ef8c-cb92-4c63-a2d5-19b17599e821)

**Comment by arvinxx** [comment]
please try again
