### ISSUE TITLE
[Bug] TOKEN计算不包含图片

### ISSUE THREAD

**Issue by maxyou2090** [lobehub/lobe-chat#3195]
### 📦 部署环境

Docker

### 📌 软件版本

v1.3.5

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

![CleanShot 2024-07-11 at 14 56 28@2x](https://github.com/lobehub/lobe-chat/assets/26402739/b82cb379-ff15-4346-ada0-0885c43d74b8)

**Comment by arvinxx** [comment]
重复：https://github.com/lobehub/lobe-chat/issues/2713
