### ISSUE TITLE
[Bug] 新会话总是提示“OpenAI API Key 不正确或为空，请检查 OpenAI API Key 后重试”，即便默认的模型不是chatgpt

### ISSUE THREAD

**Issue by earor-R** [lobehub/lobe-chat#3196]
### 📦 Environment

Docker

### 📌 Version

v1.3.5

### 💻 Operating System

Ubuntu

### 🌐 Browser

Edge

### 🐛 Bug Description

我使用环境变量配置默认的模型为`llama2-chinese`，但是使用新的浏览器开启默认会话，还是会提示填写OpenAI API Key，必须要手动切换一下模型才能正常使用。
```
docker run -d -p 3210:3210 -e DEFAULT_AGENT_CONFIG='model=llama2-chinese' -e ENABLED_OPENAI=0 -e OPENAI_MODEL_LIST='-all,+gpt-3.5-turbo' -e OLLAMA_PROXY_URL=http://xxx.net:7634 -e OLLAMA_MODEL_LIST='-all,+llama3,+phi3,+qwen2,+llama2-chinese,+codellama,+llava' -e ACCESS_CODE=xxx --name lobe-chat lobehub/lobe-chat 
```

### 📷 Recurrence Steps

1. 使用docker命名部署lobe-chat
2. 使用清除缓存之后的浏览器打开LobeChat的页面
3. 和默认助手对话或者新建助手进行对话
4. 填入ACCESS_CODE之后会出现这个提示

### 🚦 Expected Behavior

当我使用ollama的模型时**不要提示**`OpenAI API Key 不正确或为空，请检查 OpenAI API Key 后重试`

### 📝 Additional Information

我尝试了只添加环境变量`ENABLED_OPENAI=0`，不添加OPENAI相关的任何环境变量，都没用，希望开发者解决，谢谢。

**Comment by earor-R** [comment]
忘记添加图片了

![image](https://github.com/lobehub/lobe-chat/assets/14047624/f3096bca-5e1c-427e-9914-1e50697935f0)

**Comment by arvinxx** [comment]
要加 `provider=ollama`

**Comment by luluming** [comment]
> 忘记添加图片了
> 
> ![image](https://github.com/lobehub/lobe-chat/assets/14047624/f3096bca-5e1c-427e-9914-1e50697935f0)

我也遇到了和你一样的问题，这个怎么解决的 啊？
