### ISSUE TITLE
[Request] 是否可以记录默认上次访问的话题页签

### ISSUE THREAD

**Issue by i-iooi-i** [lobehub/lobe-chat#320]
### 🥰 需求描述 | Feature Description

<img width="1125" alt="iShot_2023-10-15_01 00 15" src="https://github.com/lobehub/lobe-chat/assets/1827701/5e9ff033-300b-4dde-846e-cd84979b55b0">

是否可以记录上次访问的话题页签呢？

发现一个问题，就是在不同的机器人之间来回切换，切换回来，最后都会回到 默认话题 页签。在PC上还好，无非就鼠标点击一下的事情，但是在手机上就不是很方便了，要频繁操作切换页签，还是蛮麻烦的。

### 🧐 解决方案 | Proposed Solution

wu

### 📝 补充信息 | Additional Information

wu

**Comment by arvinxx** [comment]
默认记住页签不一定合理的。之前有的用户反馈说希望每次打开助手，都是一个新会话。就和你的诉求完全相反了

**Comment by i-iooi-i** [comment]
> 默认记住页签不一定合理的。之前有的用户反馈说希望每次打开助手，都是一个新会话。就和你的诉求完全相反了

那能否考虑设置里面做个开关选项啥的？

**Comment by arvinxx** [comment]
> 那能否考虑设置里面做个开关选项啥的？

这个感觉可以有，后面加一下

**Comment by arvinxx** [comment]
release on v0.103.0
