### ISSUE TITLE
[Bug] Vercel deployment banned by OpenAI API

### ISSUE THREAD

**Issue by stephonye** [lobehub/lobe-chat#3203]
### 📦 Environment

Vercel

### 📌 Version

1.3.6

### 💻 Operating System

macOS

### 🌐 Browser

Safari

### 🐛 Bug Description

Deployed on Vercel in countries and regions that OpenAI defines as prohibited from access.
![截屏2024-07-12 10 13 24](https://github.com/user-attachments/assets/480ae0ee-9ea8-4c02-b8b0-55b72f7c6559)

### 📷 Recurrence Steps

Can always be reproduced

### 🚦 Expected Behavior

OpenAI returns information normally, Other systems have no problem accessing OpenAI using Vercel.

### 📝 Additional Information

Changing the API Key and redeploying did not solve the problem.

**Comment by RubuJam** [comment]
你是否启用了使用客户端请求？

Do you have Use Client Requests enabled?

**Comment by stephonye** [comment]
> 你是否启用了使用客户端请求？
> 
> Do you have Use Client Requests enabled?

我应该在哪里关闭/停用客户端请求？

**Comment by RubuJam** [comment]
如果你在`设置`-`语言模型`中自行设置了OpenAi Key，就会弹出这个选择

If you set the OpenAi Key yourself in `Settings`-`Language Model`, this option will pop up

> 我应该在哪里关闭/停用客户端请求？

**Comment by stephonye** [comment]
> 如果你在`设置`-`语言模型`中自行设置了OpenAi Key，就会弹出这个选择
> 
> If you set the OpenAi Key yourself in `Settings`-`Language Model`, this option will pop up
> 
> > 我应该在哪里关闭/停用客户端请求？

请教我该如何解决这个问题呢，我清空了浏览器缓存也没有解决问题。

**Comment by RubuJam** [comment]
你的Key是在环境变量中设置的，还是自己在软件中手动输入的

Is your key set in the environment variable or entered manually in the software?

> 请教我该如何解决这个问题呢，我清空了浏览器缓存也没有解决问题。

**Comment by stephonye** [comment]
> 你的Key是在环境变量中设置的，还是自己在软件中手动输入的
> 
> Is your key set in the environment variable or entered manually in the software?
> 
> > 请教我该如何解决这个问题呢，我清空了浏览器缓存也没有解决问题。

我的Key是在环境变量中配置的，没有在Web Client中输入过。

![截屏2024-07-12 11 42 36](https://github.com/user-attachments/assets/f4f25d5c-fe95-4881-bd98-66f68a80d625)

**Comment by RubuJam** [comment]
你对代码有没有修改过？

Have you modified the code?

 
> 我的Key是在环境变量中配置的，没有在Web Client中输入过。
> 
> 
> 
> ![截屏2024-07-12 11 42 36](https://github.com/user-attachments/assets/f4f25d5c-fe95-4881-bd98-66f68a80d625)
> 
>

**Comment by stephonye** [comment]
> 你对代码有没有修改过？
> 
> Have you modified the code?
> 
> > 我的Key是在环境变量中配置的，没有在Web Client中输入过。
> > ![截屏2024-07-12 11 42 36](https://private-user-images.githubusercontent.com/6421173/348118588-f4f25d5c-fe95-4881-bd98-66f68a80d625.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTYzNjUsIm5iZiI6MTcyMDc1NjA2NSwicGF0aCI6Ii82NDIxMTczLzM0ODExODU4OC1mNGYyNWQ1Yy1mZTk1LTQ4ODEtYmQ5OC02NmY2OGE4MGQ2MjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMDM0NzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTg5ZGNiNmQ2OTE2OThiNzJlYWEzNTY2Zjg1N2RmZjIxMTg2YzU3N2FhYmNiY2EzZTA4MTZmYmE1M2YwYTM5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HGipTFiC5qJG6nWwp6JwPN8TyDprHpeskwJ1kWpKDRA)

也没有修改过代码，都是直接同步repo之后自动部署在Vercel

**Comment by arvinxx** [comment]
解决方案是参考 googe 的 route，排除大陆附近的调用区域

**Comment by stephonye** [comment]
> 解决方案是参考 googe 的 route，排除大陆附近的调用区域

请教有没有文档可以参考Google的router，如何排除被OpenAI禁止的调用区域？

**Comment by RubuJam** [comment]
https://vercel.com/docs/functions/configuring-functions/region

> 请教有没有文档可以参考Google的router，如何排除被OpenAI禁止的调用区域？

**Comment by stephonye** [comment]
其实我没好意思说，我觉得是Vercel自动部署了1.3.6之后才出问题，可能跟你们improve agent runtime code有关。我已经重新部署了几次，我没法rollback回去验证。

**Comment by stephonye** [comment]
非常非常感谢。
> https://vercel.com/docs/functions/configuring-functions/region
> 
> > 请教有没有文档可以参考Google的router，如何排除被OpenAI禁止的调用区域？

**Comment by RubuJam** [comment]
你可以参考一下#3167 ，如果有其它问题，欢迎及时反馈

You can refer to #3167. If you have any other questions, please give us your feedback.

**Comment by arvinxx** [comment]
@stephonye 这个跟1.3.6 没关系吧，OpenAI 7.9 正式开始封大陆相关 IP，你换个之前部署的地址大概率也是没法用的…

**Comment by cmj2002** [comment]
It seems that there is an environment variable `OPENAI_FUNCTION_REGIONS` controlling the execution region of the edge function that has not been documented.

https://github.com/lobehub/lobe-chat/blob/3463b303090c1e6df72e6f16b6413ae76a154446/src/app/api/chat/%5Bprovider%5D/route.ts#L13

https://github.com/lobehub/lobe-chat/blob/3463b303090c1e6df72e6f16b6413ae76a154446/src/app/api/config.ts#L3-L14

https://github.com/lobehub/lobe-chat/blob/3463b303090c1e6df72e6f16b6413ae76a154446/src/config/llm.ts#L5-L10

**Comment by breakstring** [comment]
才发现了这个问题。。。唉。。。。
我现在不得已把 OpenAI 的接口套上了代理，指定他们走我新加坡的服务器跑一圈儿，汗

**Comment by stephonye** [comment]
> @stephonye 这个跟1.3.6 没关系吧，OpenAI 7.9 正式开始封大陆相关 IP，你换个之前部署的地址大概率也是没法用的…

非常感谢您的支持，多谢多谢🙏。

**Comment by RubuJam** [comment]
@stephonye 我们正在修改代码，解决这个问题，应该很快就可以更新：）

We are currently revising the code to fix this issue and it should be available soon :)

**Comment by stephonye** [comment]
真的是太棒了，永远支持你们！
> @stephonye 我们正在修改代码，解决这个问题，应该很快就可以更新：）
> 
> We are currently revising the code to fix this issue and it should be available soon :)
