### ISSUE TITLE
选项里的语言模型页面，Anthrop通道无法对自己创建的模型进行设置(即勾选函数调用/视觉识别/文件上传)，也无法删除。OpenAI通道是可以的。

### ISSUE THREAD

**Issue by leslietoo** [lobehub/lobe-chat#3207]
![lobechat2](https://github.com/user-attachments/assets/68e1f502-18bc-46b2-9da6-86ecc8939068)
![lobechat](https://github.com/user-attachments/assets/55995eb6-8a5d-423f-b8fc-e1d57c89d663)

**Comment by RubuJam** [comment]
没启用这个功能，可能是因为后端没做相关支持

This feature is not enabled, probably because the backend does not provide relevant support

**Comment by leslietoo** [comment]
sorry，我不太明白你说的”后端不支持“是什么意思？比如有个api中转服务商提供的模型名叫claude-3.5-sonnet（用的小数点且不带版本号），lobechat默认的anthrope模型列表里没有这个名字，我只能自己创建一个，但又无法勾选函数回调和图片上传，所以用不了这两个功能。但是这个模型名肯定是支持图片和插件的（放到其他类似聊天工具里可以用）。

**Comment by leslietoo** [comment]
另外，你说的”如果你想删除你自定义的模型，在输入框中在对应模型中点击×即可“，这只是把过滤条件里的模型去掉了，下拉列表里的自创建模型名依然还在列表里，无法被删除。

**Comment by arvinxx** [comment]
<img width="677" alt="image" src="https://github.com/user-attachments/assets/2369f5de-217c-4d4d-9143-63c638b29fad">

目前看应该已经解决了
