### ISSUE TITLE
[Request] 谷歌和grog支持了Gemma 2 模型

### ISSUE THREAD

**Issue by leter** [lobehub/lobe-chat#3218]
### 🥰 Feature Description

google和grog支持了Gemma 2 模型, 最新版本是否能支持调用

### 🧐 Proposed Solution

新增api调用的模型类别 Gemma 2

**Comment by RubuJam** [comment]
#2308

**Comment by RubuJam** [comment]
#3208

**Comment by RubuJam** [comment]
#3208
