### ISSUE TITLE
[Bug] LobeChat 加入CF R2之后 Gemini 1.5 模型无法正常解析图片

### ISSUE THREAD

**Issue by JJTools** [lobehub/lobe-chat#3224]
### 📦 部署环境

Vercel

### 📌 软件版本

V1.4.0

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

LobeChat 加入CF R2之后 ChatGPT 支持正常图片解析，但是Gemini 1.5 模型均出现该问题
{
"error": {
"message": "currently we don't support image url: https://xxxxx.com/files/478058/xxxxxxx.png"
},
"provider": "google"
}

### 📷 复现步骤

PC端截图，直接粘贴到LobeChat。
发送问题提示异常。
不接入R2 不存在此问题

### 🚦 期望结果

正常请求

**Comment by arvinxx** [comment]
duplicate #3051
