### ISSUE TITLE
[Request] 希望阿里千问系列大模型支持function call

### ISSUE THREAD

**Issue by armfeel** [lobehub/lobe-chat#3226]
### 🥰 需求描述

希望阿里千问系列大模型支持function call

### 🧐 解决方案

希望阿里千问系列大模型支持function call

**Comment by RubuJam** [comment]
这个不是我们能解决的，要供应商支持，我们才会开放

This is not something we can solve. We will open it up only if Alibaba supports it.

**Comment by arvinxx** [comment]
@RubuJam 千问是支持的 ，已经有PR了 #3114
