### ISSUE TITLE
按最后对话时间倒序排列助手，最常用的助手在最上面

### ISSUE THREAD

**Issue by shog86** [lobehub/lobe-chat#3228]
### 🥰 Feature Description

按最后对话时间倒序排列助手，最常用的助手在最上面

### 🧐 Proposed Solution

或者提供手动排列助手的可能性

**Comment by shog86** [comment]
1.6.1好像又不行了

**Comment by arvinxx** [comment]
@shog86 咋不行？

**Comment by shog86** [comment]
哦，要新建话题才可以，继续聊旧话题不会更新助手排序

**Comment by arvinxx** [comment]
> 哦，要新建话题才可以，继续聊旧话题不会更新助手排序

你希望在聊旧话题时也更新助手排序吗

**Comment by shog86** [comment]
> > 哦，要新建话题才可以，继续聊旧话题不会更新助手排序
> 
> 你希望在聊旧话题时也更新助手排序吗

yes。不知道这是不是个大众的需求，因为我有时候会回去找旧话题继续聊
