### ISSUE TITLE
突然jwt过期

### ISSUE THREAD

**Issue by XHB-111** [lobehub/lobe-chat#3229]
### 📦 Environment

Docker

### 📌 Version

v1.4.3

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

只有我这台设备出现jwt过期，换了
其他设备使用一切正常
<img width="419" alt="屏幕截图 2024-07-16 065219" src="https://github.com/user-attachments/assets/55be3212-6c61-4468-b0f8-1f1c3cb67395">

**Comment by arvinxx** [comment]
检查下电脑日期，设备其实
