### ISSUE TITLE
[Bug] documentation webrtc zeabur button is wrong

### ISSUE THREAD

**Issue by insign** [lobehub/lobe-chat#3234]
### 📦 Environment

Zeabur

### 📌 Version

n/d

### 💻 Operating System

Other

### 🌐 Browser

Other

### 🐛 Bug Description

The button at https://lobehub.com/docs/self-hosting/advanced/webrtc leads the user to deploy the full app itself instead the signaling server making users like me lose hours or give up. The probably correct way is fix the button to the right template or do like me and fork the [one file project of signaling](https://github.com/lobehub/y-webrtc-signaling) and configure at zeabur, works fine.

**Comment by arvinxx** [comment]
Now there is a docker image, so one click deploy will be fine

**Comment by insign** [comment]
But where is it documented ?

**Comment by arvinxx** [comment]
@insign you can just click the zeabur button again?

**Comment by insign** [comment]
> @insign you can just click the zeabur button again?

As I said I did it alone. But I'm happy it's fixed now.

**Comment by insign** [comment]
Just to let you know, zeabur is blocking the service after some days, hopefully it is easy to deploy, better if you publish the image at docker hub.

**Comment by arvinxx** [comment]
@insign OK，A good idea to have docker-image. I will push it soon
