### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by calonye** [lobehub/lobe-chat#3235]
### 📦 部署环境

Other

### 📌 软件版本

v1.4.3

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome, Edge

### 🐛 问题描述

我在ollama 的 qwen2 7b q4 模型中设置了`/set parameter top_k -1 `和`/set parameter num_ctx 32768`, 再运行时候测试有效，但再 lobechat 里面会话时，发现会话内容长度仍旧不会超乎出 2048,请问如何解决？

### 🚦 期望结果

提供一下 lobechat 如何配合 ollama 修改上下文长度

**Comment by arvinxx** [comment]
这个似乎不是 LobeChat 的问题？输出受限感觉不是 LobeChat 限制的
