### ISSUE TITLE
[Bug] 通义千问Qwen API使用报错

### ISSUE THREAD

**Issue by morningtzh** [lobehub/lobe-chat#3240]
### 📦 部署环境

Other

### 📌 软件版本

v1.5.1

### 💻 系统环境

Windows, iOS

### 🌐 浏览器

Edge, Safari

### 🐛 问题描述

目前部署在Azure北美容器应用上，一直存在类似 #3108 的问题，但早期无论是否打开客户端请求模式都存在问题。目前最新版本v1.5.1已默认关闭客户端请求模式，依然存在问题。是否需要和 #3099 一样使用国际版API？

配置截图，聊天框也是同样返回：
![image](https://github.com/user-attachments/assets/c1fd0928-c5dc-463e-864a-3f73018f1798)

查看日志可以看到是fetch失败
2024-07-17T08:54:34.358024997Z Route: [qwen] ProviderBizError: [TypeError: fetch failed] { cause: [Error: AggregateError] }

### 📷 复现步骤

同问题描述

### 🚦 期望结果

期望能正常访问dashscope qwen模型

**Comment by arvinxx** [comment]
fetch failed 应该就是连不通吧，感觉要有国际版

**Comment by Mingholy** [comment]
你的API-KEY是从哪里获取的呢？

**Comment by morningtzh** [comment]
>  fetch failed 应该就是连不通吧，感觉要有国际版

可能是，后面等另一个issue支持国际版了再试试

**Comment by morningtzh** [comment]
> 你的API-KEY是从哪里获取的呢？

key没有问题，我从环境变量中拷贝出来，qwen-max能curl通，正常得出结果

**Comment by Mingholy** [comment]
#3108 看下来应该是配置了一个自定义模型，首先使用了客户端请求；关闭客户端请求之后传入了一个不正确的模型名，传入了不支持的参数造成的报错。但从截图上看，至少网关是确定可以访问得到的。


参考#3254 其实并没有『国际专供』这一说，所以得排除下是否是网络环境的问题，得在部署的环境里测试下这两个endpoint能否curl得到：
`https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions`
`https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions`
随便填API-KEY至少应该能拿到`invalid_api_key`

```
curl --location 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions' \
--header 'Authorization: Bearer sk-xxx' \
--header 'Content-Type: application/json' \
--data '{
    "model": "qwen-plus",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "你是谁"
        }
    ],
    "stream": false
}'
```

**Comment by morningtzh** [comment]
@Mingholy 今天配置GPT4o mini时发现新版本 qwen已经可以访问了。不知道是否和你昨天提交的 #3252 有关
