### ISSUE TITLE
[Bug] 今天Qwen更新视觉模型后，回复文本总在最后一点断开

### ISSUE THREAD

**Issue by LovelyGuYiMeng** [lobehub/lobe-chat#3243]
### 📦 部署环境

Vercel, Zeabur

### 📌 软件版本

最新

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

今天更新视觉模型后，回复文本总在最后一点被stop中止，前几天是完全没问题的，而且我vercel和zeabur两个平台都试过有问题
![QQ_1721228811959](https://github.com/user-attachments/assets/d020bf40-7c4c-42dc-ada4-1edc8bda6346)
![QQ_1721228831322](https://github.com/user-attachments/assets/e74e06c3-1020-41b3-a67e-8c68c870b061)

**Comment by arvinxx** [comment]
@Mingholy 能否帮忙看下

**Comment by Mingholy** [comment]
@arvinxx @LovelyGuYiMeng 正在调查中，目前看是因为qwen-vl和qwen-turbo返回的最后一条message行为不同，qwen-vl会在当`finish_reason`为`stop`时仍然在`content`中返回有效信息。会尽快修复
