### ISSUE TITLE
[Bug] 在部署平台自定义域名后，通过自定义域名访问无法加载动态图标 

### ISSUE THREAD

**Issue by LovelyGuYiMeng** [lobehub/lobe-chat#3246]
### 📦 部署环境

Vercel, Zeabur

### 📌 软件版本

最新

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

用平台官方给的域名可以加载动态图标，自定义域名访问403无法加载
![QQ_1721243235007](https://github.com/user-attachments/assets/3023bc5a-51b8-4cc6-86a8-98eabf61e3a5)
![QQ_1721243246748](https://github.com/user-attachments/assets/c64e16e2-8354-41ef-bc40-9c3a98c879d9)

![48e8ea8f23fcd6e22e81ac72e2a3d335](https://github.com/user-attachments/assets/1378cf9a-23e5-4787-a3f2-b1ec8e558d5a)
![24d26dc4ecc3a2bc1ee725d5ea350ccf](https://github.com/user-attachments/assets/c3e46156-6e79-40d9-a7b4-e5f1880265b4)
![QQ_1721243044294](https://github.com/user-attachments/assets/84406e8b-2bfa-4921-ae0c-f94ccc95b038)

**Comment by Matinal111** [comment]
不要使用top域名

**Comment by LovelyGuYiMeng** [comment]
> 不要使用top域名

啊，跟top域名有关吗，为什么top域名不行呢

**Comment by arvinxx** [comment]
因为top域名黑产太多了，被禁了。
