### ISSUE TITLE
[Bug] 在文档模式下对话时，点击编辑自己之前说的话，此时确定/取消两个按钮都会丢失，且无法退出编辑

### ISSUE THREAD

**Issue by one-pyy** [lobehub/lobe-chat#3247]
### 📦 Environment

Docker

### 📌 Version

1.5.4

### 💻 Operating System

Ubuntu

### 🌐 Browser

Edge

### 🐛 Bug Description

在文档模式下对话时，点击编辑自己之前说的话，此时确定/取消两个按钮都会丢失，且无法退出编辑。

### 📷 Recurrence Steps

1. 聊天设置中选择文档模式
    ![image](https://github.com/user-attachments/assets/07c5c3c8-e0b3-4b65-ac6c-18c07e75072c)
2. 随便发一条消息
    ![image](https://github.com/user-attachments/assets/ed78ab17-af87-4ccf-94fe-acdfc63d2dd3)
3. 点击编辑自己发送的消息。此时发现确定/取消按钮缺失，且按esc/ctrl+enter/enter等都无法退出编辑
    ![image](https://github.com/user-attachments/assets/c85710f4-82ec-4a6e-9d91-f21f3518110c)

### 🚦 Expected Behavior

类似于编辑ai消息。应该有按钮

![image](https://github.com/user-attachments/assets/dcfe0ff1-9dd6-471d-95d4-73b37090cafd)

### 📝 Additional Information

麻烦大佬们修一下这个bug！感觉好像平时编辑自己发的东西的场景还挺常见的！

辛苦大佬们了！感谢大佬们做出的非常厉害的lobe-chat！

**Comment by lowspace** [comment]
遇到了相同的问题。

**Comment by heltonteixeira** [comment]
Same problem here in both views.

**Comment by dalefengs** [comment]
这个bug 2月了，有大佬优化下么
