### ISSUE TITLE
Qwen Plus/Turbo 函数调用不可用[Bug] 

### ISSUE THREAD

**Issue by Spades-X** [lobehub/lobe-chat#3248]
### 📦 Environment

Docker

### 📌 Version

1.5.4

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

切换模型选项中，Qwen Plus/Turbo显示模型支持调用函数，但窗口中函数缺不可调用。
![image](https://github.com/user-attachments/assets/13e181d8-ec69-4839-b875-57c1d2bcb7e9)
![image](https://github.com/user-attachments/assets/6e92d76d-24cc-4fb3-a553-5e275a204323)

**Comment by arvinxx** [comment]
你有没有自己添加过 qwen模型？试试重置下

**Comment by Spades-X** [comment]
> 您没有自己添加过qwen模型吗？尝试重置下

重置后问题还是存在，
添加模型这里不显示可调用函数：
![image](https://github.com/user-attachments/assets/d6a862dc-bc1d-4fd3-a59e-3749f6abf069)
但是这里还是提示可调用：
![image](https://github.com/user-attachments/assets/33e62519-1954-4928-97e6-21bb19615962)

**Comment by arvinxx** [comment]
那看起来是个 bug… 我回头看下原因

**Comment by hezhijie0327** [comment]
要么清下缓存？最新 commit 测下来功能和图标显示都正常的
![image](https://github.com/user-attachments/assets/70be48e1-e51a-42dd-a1b1-3462d26055b9)
![image](https://github.com/user-attachments/assets/c65dc6ae-a8fb-4181-a5cb-5993a347730f)
![image](https://github.com/user-attachments/assets/ee34e8dc-fb7f-4dc7-b050-834b4dc4e50d)
![image](https://github.com/user-attachments/assets/98a11fab-5e12-4dc1-aac4-6095fdb18760)

**Comment by Spades-X** [comment]
清除浏览器缓存后，问题解决
