### ISSUE TITLE
[Bug] reach 45 mins deployment limit in vercel for some commit

### ISSUE THREAD

**Issue by vegetablesB** [lobehub/lobe-chat#3250]
### 📦 Environment

Vercel

### 📌 Version

latest

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

I have the error from vercel says _Your deployment's build step did not complete within the maximum of 45min_.

The usage limit in vercel is low for my project.

<img width="1691" alt="image" src="https://github.com/user-attachments/assets/abe85fca-339a-401a-8931-35dd7195f01d">
<img width="1301" alt="image" src="https://github.com/user-attachments/assets/fa71d7e9-fe38-46c7-a73f-f99e9e41125b">

**Comment by arvinxx** [comment]
I thinks it's the reason of lint: https://github.com/lobehub/lobe-chat/issues/3535#issuecomment-2305102307 , wait for antd to release 5.21.0 these days
