### ISSUE TITLE
[Bug] Google Gemini not working

### ISSUE THREAD

**Issue by Igroshka** [lobehub/lobe-chat#3251]
### 📦 Environment

Vercel

### 📌 Version

1.5.4

### 💻 Operating System

Windows, Ubuntu, Android, Other

### 🌐 Browser

Chrome, Edge

### 🐛 Bug Description

When trying to generate text from any Google model, errors occur. (If used in an agent. It works in “Just Let’s Chat”)

`{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:streamGenerateContent?alt=sse: [400 Bad Request] * GenerateContentRequest.tools[0].function_declarations[0].parameters.properties: should be non-empty for OBJECT type\n"
  },
  "provider": "google"
}`

**Comment by wangxinqijian** [comment]
> 👀 👀@Igroshka
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.感谢您提出问题。我们将对此事进行调查，并尽快回复您。 Please make sure you have given us as much context as possible.请确保您已向我们提供了尽可能多的背景信息。 非常感谢您提交 issue。我们会尽快调查此事，并尽快回复您。 请确保您已经提供了尽可能多的背景信息。非常感谢您提交 issue。 我们会尽快调查此事，并尽快回复您。 请确保您已经提供了尽可能多的背景信息。

flash是可以的，报错的是pro

**Comment by wangxinqijian** [comment]
> 👀 @Igroshka
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible. Please make sure you have given us as much context as possible. 非常感谢您提交 issue。我们会尽快调查此事，并尽快回复您。 请确保您已经提供了尽可能多的背景信息。

试了好几个项目，应该是谷歌的问题，flash是正常的，pro有时正常有时报错

**Comment by arvinxx** [comment]
I think it's a google's issue, like https://github.com/lobehub/lobe-chat/issues/2537 . you can disable your plugins
