### ISSUE TITLE
是否可以支持接入智谱AI更多的大模型？

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#3257]
### 🥰 需求描述

是否可以支持接入智谱AI更多的大模型？

### 🧐 解决方案

是否可以支持接入智谱AI更多的大模型？

### 📝 补充信息

是否可以支持接入智谱AI更多的大模型？

**Comment by breakstring** [comment]
智谱？所以。。。您到底自己部署过么（或者哪怕看一下文档么）？

**Comment by zhangleijun111** [comment]
> 智谱？所以。。。您到底自己部署过么（或者哪怕看一下文档么）？

我意思是现在的模型不全兄弟

**Comment by breakstring** [comment]
> > 智谱？所以。。。您到底自己部署过么（或者哪怕看一下文档么）？
> 
> 我意思是现在的模型不全兄弟
抱歉，我的错。。。

**Comment by arvinxx** [comment]
@breakstring 欢迎提交PR：https://github.com/lobehub/lobe-chat/blob/main/src/config/modelProviders/zhipu.ts

**Comment by zhangleijun111** [comment]
> @breakstring 欢迎提交PR：https://github.com/lobehub/lobe-chat/blob/main/src/config/modelProviders/zhipu.ts

谢谢大神，文档解析功能靠你了
