### ISSUE TITLE
[Bug] gpt-4o突然不能识别图片了

### ISSUE THREAD

**Issue by alexbiaolol** [lobehub/lobe-chat#3260]
### 📦 Environment

Docker

### 📌 Version

lobehub/lobe-chat          latest    21d59951b6dd   40 hours ago    372MB

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

<img width="461" alt="gpt" src="https://github.com/user-attachments/assets/4451d05a-e7f8-400e-9812-bbb2978ce088">

突然今天发现gpt-4o不能识别图片了。问他，他说他用的是GTP-4.

### 📷 Recurrence Steps

Paste an image

### 🚦 Expected Behavior

Traslate the content in the image

**Comment by alexbiaolol** [comment]
之前是可以的。

**Comment by arvinxx** [comment]
你用的不是官方api key吧？找下你的key服务商问问

**Comment by alexbiaolol** [comment]
> 你用的不是官方api key吧？找下你的key服务商问问

<img width="440" alt="1" src="https://github.com/user-attachments/assets/8f1b2c8a-aea7-4a81-9208-4d52388676c3">
从Key的统计页面看到，今天和昨天的不一样，但是UI上面我什么都没做。

**Comment by arvinxx** [comment]
@alexbiaolol 那你问下你的服务商

**Comment by bentwnghk** [comment]
@alexbiaolol Try another API key service provider, e.g. [https://api.mr5ai.com](https://api.mr5ai.com)
