### ISSUE TITLE
[Bug] 无法同步删除模型

### ISSUE THREAD

**Issue by fqscfqj** [lobehub/lobe-chat#3265]
### 📦 部署环境

Docker

### 📌 软件版本

v1.6.1

### 💻 系统环境

Other Linux

### 🌐 浏览器

Edge

### 🐛 问题描述

我使用docker版，当我在变量中删除一个模型后，网页上尽管模型选项已经消失了但还是可以正常对话
![image](https://github.com/user-attachments/assets/7cf8ade2-ac48-4896-ab06-ada1d97c14a8)

### 📷 复现步骤

1.在变量中设置一个模型
2.在lobechat中选中这个模型
3.在变量中删除这个模型
4.在lobechat中继续对话

### 🚦 期望结果

同步删除模型，使被删除的模型对话无法启动

**Comment by arvinxx** [comment]
这个你得从api key层面限制。ui没法限制的。
