### ISSUE TITLE
[Request] 增加对GPT-4o-mini模型的支持

### ISSUE THREAD

**Issue by Michael-Fei** [lobehub/lobe-chat#3267]
### 🥰 需求描述

昨天OpenAI发布了gpt-4o-mini，API价格低廉，希望尽快支持

### 🧐 解决方案

添加gpt-4o-mini模型

**Comment by hezhijie0327** [comment]
最新 Commit 已经支持了 a84d8073e30c65e57f5dda7cfead568b06ebf793
![image](https://github.com/user-attachments/assets/9ca98ec7-009b-44ac-90d2-76db5fd55f87)
