### ISSUE TITLE
[Bug] Openrouter模型不支持函数

### ISSUE THREAD

**Issue by shog86** [lobehub/lobe-chat#3269]
### 📦 Environment

Vercel

### 📌 Version

1.6.1

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

<img width="392" alt="LobeChat 2024-07-20 22 54 33" src="https://github.com/user-attachments/assets/c8c3dd5b-5b28-4f61-b29a-233ddd8e4255">
这是Lobe的问题还是Openrouter的问题？
而且Openrouter的Gemma 2 9b free用不了，但Qwen 2 7b可以用

**Comment by shog86** [comment]
用不了的意思是会是这样
![image](https://github.com/user-attachments/assets/f27971db-c52e-440c-b105-a11cd33238af)

**Comment by shog86** [comment]
Good news: Tool use / function calling works fine via OpenRouter and GPT-4o mini, Claude wrote a nice Python script that works nearly out-of-the-box, just change the model name from `openai/gpt-4` to `openai/gpt-4o-mini` -> https://claude.site/artifacts/34895885-69b0-4ab5-a3c4-2babf85dc5c5 (tested)

**Comment by JJTools** [comment]
You can open it yourself
+mode<fc> 
+gpt-3.5<fc>

**Comment by shog86** [comment]
> You can open it yourself
> 
> +mode\<fc\> 
> 
> +gpt-3.5\<fc\>
> 
> 

How do I do it in lobechat?

**Comment by JJTools** [comment]
Reference documents, list of custom models
-all,+gpt-35=git-35\<200000:fc:vision\>
You can configure it to turn on some support

**Comment by wangdake5111** [comment]
同样的问题，请问解决了吗

**Comment by shog86** [comment]
@arvinxx 求看这个问题。。。类似的还有https://github.com/lobehub/lobe-chat/issues/3346

**Comment by arvinxx** [comment]
现在是否支持插件的判断是根据desc中是否有function calling字段

**Comment by shog86** [comment]
> 现在是否支持插件的判断是根据desc中是否有function calling字段

但OpenRouter本身的API，这些模型都是支持FC的，是要在lobechat哪里设置一下才能用吗？

**Comment by hllshiro** [comment]
![image](https://github.com/user-attachments/assets/a7c90e93-3077-4a96-b0cb-c6a92bf94be5)
![image](https://github.com/user-attachments/assets/6b4b9bf0-c762-4558-84a7-e98891ab1e59)
![image](https://github.com/user-attachments/assets/8a15bb6d-2e60-4f9d-a332-6e501704af29)
可以通过自定义模型功能，你能够自己创建一个支持任何特性的模型。注意在创建时需要输入一个其他的名称，否则会选中已有的模型，然后在修改配置时修改为你期望的模型名称。

**Comment by shog86** [comment]
我这么配置了一下，但Claude还是不行
<img width="570" alt="image" src="https://github.com/user-attachments/assets/61ba63ee-03f4-43cb-b84d-a06debb8e7f3">

**Comment by arvinxx** [comment]
我试了下， OpenRouter 的 Claude Tools Calling 兼容度很有问题。暂时估计支持不了了

**Comment by shog86** [comment]
OpenRouter修复了这个问题，试了一下，可以了
![image](https://github.com/user-attachments/assets/a77e7da0-e5f8-4408-ac0d-26702996554e)
![image](https://github.com/user-attachments/assets/60297b53-77a0-4ac4-9237-3d6499ec5ad3)
