### ISSUE TITLE
When the context length exceeds 40,000, asking questions will cause significant lag in the response.

### ISSUE THREAD

**Issue by Mgrsc** [lobehub/lobe-chat#3279]
### 📦 Environment

Docker

### 📌 Version

v1.6.1

### 💻 Operating System

Windows, Ubuntu, Other Linux, Android

### 🌐 Browser

Chrome, Edge, Firefox

### 🐛 Bug Description

When the context length exceeds 40,000, asking questions will cause significant lag in the response.
![image](https://github.com/user-attachments/assets/a7278466-da81-44bf-836a-d8d2cc6a6c40)

### 🚦 Expected Behavior

No lag will occur.

**Comment by Happ1ness-dev** [comment]
Having the same issue, but it's just 20k+ for me on Android
