### ISSUE TITLE
[Bug] 我使用gpt-4o-mini对话提示openai密钥错误

### ISSUE THREAD

**Issue by yh4922** [lobehub/lobe-chat#3290]
### 📦 Environment

Docker

### 📌 Version

1.6.6

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

docker 配置了环境变量
![image](https://github.com/user-attachments/assets/7f366f90-8605-49fe-911c-7c5c4e218faf)
使用其他模型 `gpt-3.5-turbo` `gpt-4o` 都可以正常对话   使用 `gpt-4o-mini` 模型  提示Openaikey 错误
![image](https://github.com/user-attachments/assets/d7a90d5a-6712-4718-947f-e8889856aefe)

**Comment by arvinxx** [comment]
看下服务端抛错是啥？

**Comment by yh4922** [comment]
> 看下服务端抛错是啥？

![image](https://github.com/user-attachments/assets/49d19ecf-23e3-4f9e-9417-687753357cad)

**Comment by arvinxx** [comment]
你这是找的三方 provider 么？问下你的服务商？

**Comment by Trimness0441** [comment]
大概率是key没权限，第三方供应商新模型需要给key赋权才能用

**Comment by yh4922** [comment]
乌龙了  确实是接口代理还没有支持 新的模型
