### ISSUE TITLE
[Request] 有没有办法，可以调用gpts?

### ISSUE THREAD

**Issue by xutaojian0721** [lobehub/lobe-chat#3293]
### 🥰 需求描述

自己写的prompt质量不太行，gpts里面有很多优质的提示词助手，希望可以调用

### 🧐 解决方案

添加一个gpts相关插件可以吗？

**Comment by arvinxx** [comment]
不计划做hack方案，chatgpt似乎也没有对应接口。所以可能这个不能支持
