### ISSUE TITLE
[Bug] Vercel 版 1.6.10无法通过 Clerk 登录

### ISSUE THREAD

**Issue by breakstring** [lobehub/lobe-chat#3298]
### 📦 部署环境

Vercel

### 📌 软件版本

1.6.10

### 💻 系统环境

macOS

### 🌐 浏览器

Other

### 🐛 问题描述

Mac 上 PWA 版，昨晚 Vercel 上的部署更新到 1.6.10 后无法登录。

### 📷 复现步骤

1. 打开PWA 应用
2. 左上角点击图标，进行登录流程
3. 输入邮件地址，获取 Clerk 验证码并输入
4. 右上角始终提示无法验证
<img width="419" alt="image" src="https://github.com/user-attachments/assets/e4800784-69ca-4715-a021-f9467e8f94e3">
Vercel 的 Log 里也看到错误日志：
![image](https://github.com/user-attachments/assets/7c34387d-77bc-4807-a445-8688c6c8cded)

BTW：试了下浏览器也一样报错

**Comment by breakstring** [comment]
重新部署了一遍现在正常了。。。算了，先关了这个 issue 吧。

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/pull/3299
