### ISSUE TITLE
[Request] 增加云同步的功能

### ISSUE THREAD

**Issue by xiaobaiyg09** [lobehub/lobe-chat#330]
### 🥰 需求描述 | Feature Description

期望可以增加云同步的功能。以实现PC端和APP端的数据同步。
场景：在地铁上想对之前PC端问的问题继续沟通，就需要这个功能
价值：
提升体验，对于用户来讲可以将所有的聊天汇总的到一起，而不是换个浏览器就没有之前的记录

### 🧐 解决方案 | Proposed Solution

可以参考https://nb.nextweb.fun/#/settings中的云同步的功能
<img width="1169" alt="image" src="https://github.com/lobehub/lobe-chat/assets/131843403/77291716-1bdf-42d2-9833-49cdd9f60c28">

**Comment by arvinxx** [comment]
ok ，我们调研下实现方案

**Comment by i-iooi-i** [comment]
刚想上来提这个issues，居然有人先提了 🫡🫡🫡
若是能支持一下webdav的同步存储就很棒。

**Comment by guuger** [comment]
云同步功能非常有必要，电脑手机，公司家里设备太多了。

**Comment by arvinxx** [comment]
我们在 v0.141.0 上线了基于 YJS 与 WebRTC 的实验性数据同步功能，欢迎测试并反馈 https://github.com/lobehub/lobe-chat/discussions/1681
