### ISSUE TITLE
[Bug] markdown数学公式显示错误

### ISSUE THREAD

**Issue by hlc1209** [lobehub/lobe-chat#3305]
### 📦 部署环境

Docker

### 📌 软件版本

v1.6.10

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

markdown数学公式解析显示错误

### 📷 复现步骤

以下是复现用的markdown语句，截取自gpt-4o的回答
`The encoder transforms the input image ($24 \times 24 \times 1$) through a series of convolutional layers。。。 size $4 \times 4$. This encoded 。。are shown, denoted as $z_{3,1}, z_{3,2}, \ldots, z_{3,i}, \ldots, z_{3,n}$, with the corresponding images $I_1, I_2, \ldots, I_i, \ldots, I_n$ where $n \rightarrow \infty$. The distance $z_1$ represents layer. $z_2$ denotes layers. $z_{3,1}$ and $z_{3,n}$ indicate`

以下是lobechat显示的效果
![image](https://github.com/user-attachments/assets/56dbd801-6539-4277-8006-ea30728a7d21)

### 🚦 期望结果

以下是Typora的显示效果，显示正常
![image](https://github.com/user-attachments/assets/58a94e4a-ac8b-4645-bf15-fd4f94c8a0fa)

以下是github自带markdown显示效果，显示正常
The encoder transforms the input image ($24 \times 24 \times 1$) through a series of convolutional layers。。。 size $4 \times 4$. This encoded 。。are shown, denoted as $z_{3,1}, z_{3,2}, \ldots, z_{3,i}, \ldots, z_{3,n}$, with the corresponding images $I_1, I_2, \ldots, I_i, \ldots, I_n$ where $n \rightarrow \infty$. The distance $z_1$ represents layer. $z_2$ denotes layers. $z_{3,1}$ and $z_{3,n}$ indicate

**Comment by arvinxx** [comment]
这个应该已经修复了

**Comment by arvinxx** [comment]
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/504a0c10-8a74-436e-9a9e-946a534cb861">
