### ISSUE TITLE
[Request] 助手配置和消息使用mysql数据库存储

### ISSUE THREAD

**Issue by kdszh** [lobehub/lobe-chat#331]
### 🥰 需求描述 | Feature Description

目前助手配置存在浏览器，有几个问题：
1.用户更换终端（电脑或者手机）后需要重新配置
2.系统管理员无法对用户的配置进行强制管理

### 🧐 解决方案 | Proposed Solution

希望能支持存到mysql一键读取

**Comment by arvinxx** [comment]
> 2.系统管理员无法对用户的配置进行强制管理

这个能举出一些具体例子么？哪里需要配置

**Comment by arvinxx** [comment]
1.用户更换终端（电脑或者手机）后需要重新配置

refs: #330

**Comment by kdszh** [comment]
> > 2.系统管理员无法对用户的配置进行强制管理
> 
> 这个能举出一些具体例子么？哪里需要配置

需要保存到mysql的配置的内容：
1.主题和系统设置（全局配置）
2.助手列表
3.助手设置
4.助手的话题列表
5.会话消息

我在lobechat包装了用户管理模块，用户登录时会把id传到后台，我希望不同的用户能看到或者使用的插件会有差别，比如以下几个例子：

1.用户A是老板，他第一次登录就可以看到和使用属于他的插件，而其他员工是无法看到和使用老板插件的
2.用户B和用户C是不同组的员工，他们能使用的插件各不相同，只有系统管理员能授权配置用户能用哪些插件
3.假设用户A使用插件有问题，管理员用可以模拟他的用户态登录，从而拥有他的插件和配置信息去调试问题
4.用户安装插件，调用插件的日志记录，做一些运营数据分析

**Comment by arvinxx** [comment]
lobe-chat 项目本身不会考虑提供 mysql 的存储接入方案，这个先关了~
