### ISSUE TITLE
插件"通过Serper搜索Google"弹窗

### ISSUE THREAD

**Issue by havelhuang** [lobehub/lobe-chat#3322]
### 📦 Environment

Vercel

### 📌 Version

1.6.5

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

已安装成功插件，每次打开LobeChat，会弹窗安装失败
![屏幕截图 2024-07-26 144956](https://github.com/user-attachments/assets/7ef98d91-1f72-4540-93b9-0585331a7e1a)

### 📷 Recurrence Steps

每次打开LobeChat应用

### 🚦 Expected Behavior

不要弹窗

### 📝 Additional Information

无

**Comment by arvinxx** [comment]
你把这个插件卸载掉就好了？
