### ISSUE TITLE
[Request] 新更新的版本是针对文件上传的功能嘛

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#3323]
### 🥰 Feature Description

新更新的版本是针对文件上传的功能嘛

### 🧐 Proposed Solution

新更新的版本是针对文件上传的功能嘛

### 📝 Additional Information

新更新的版本是针对文件上传的功能嘛

**Comment by arvinxx** [comment]
单纯优化了上传的一些样式。整个文件上传功能还需要1-2周
