### ISSUE TITLE
关于实现月之暗面的kimi接口的附件上传功能

### ISSUE THREAD

**Issue by wenocy** [lobehub/lobe-chat#3324]
### 🥰 需求描述

在月之暗面的官方接口文档中，是能够通过在调用api的时候上传附件（xls、pdf、doc、png等）的，但lobe-chat仍未支持。

### 🧐 解决方案

根据官方文档接入即可：https://platform.moonshot.cn/docs/api/files#%E5%A4%9A%E6%96%87%E4%BB%B6%E5%AF%B9%E8%AF%9D%E7%A4%BA%E4%BE%8B

**Comment by arvinxx** [comment]
知识库功能暂不会计划使用上述接口

**Comment by wenocy** [comment]
好的，感谢回复💖
