### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sinxyz** [lobehub/lobe-chat#3329]
### 📦 部署环境

Docker

### 📌 软件版本

v1.7.2

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

tools can't  work with ollama，but it can work with groq in same model

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/pull/3327

**Comment by arvinxx** [comment]
duplicate of #3436
