### ISSUE TITLE
[Request] Support for 8192 Output Tokens for Anthropic API

### ISSUE THREAD

**Issue by pixelbreeze38** [lobehub/lobe-chat#3333]
### 🥰 Feature Description

Hello,

I noticed that the current implementation of the Anthropic API client doesn’t support the 8192 output tokens feature. According to the [Anthropic documentation](https://docs.anthropic.com/en/docs/about-claude/models#model-comparison), this feature is in beta and requires the header `anthropic-beta: max-tokens-3-5-sonnet-2024-07-15`. If this header isn’t specified, the limit defaults to 4096 tokens.

### 🧐 Proposed Solution

To address this, I’ve made a local change that allows the use of 8192 tokens. The update involves modifying the Anthropic client initialization to include the required header.

### Changes Made:
In the file `src/libs/agent-runtime/anthropic/index.ts`, I modified the client initialization as follows:

```typescript
this.client = new Anthropic({
  apiKey,
  baseURL,
  defaultHeaders: { "anthropic-beta": "max-tokens-3-5-sonnet-2024-07-15" },
});
```
This change sets the defaultHeaders property to include the necessary beta header, which enables the extended output token limit.

### 📝 Additional Information

To ensure that users are aware of the beta status of the extended output token limit, it would be helpful to include a disclaimer such as:

Claude 3.5 Sonnet supports max tokens up to 8192 with a beta header. [More Info](https://docs.anthropic.com/en/docs/about-claude/models#model-comparison)

**Comment by RubuJam** [comment]
Maybe you should just submit a PR :)

**Comment by arvinxx** [comment]
@pixelbreeze38 PR welcome~
