### ISSUE TITLE
[Bug] openai api 语音合成试听报错：很抱歉，服务器拒绝了您的请求，可能是因为您的权限不足或未提供有效的身份验证

### ISSUE THREAD

**Issue by ZhongYoulin** [lobehub/lobe-chat#3335]
### 📌 软件版本

web

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

连通性检查没有问题，语音聊天也能回复，语音输入可以识别，但是回复文本播放报错，语音合成试听也报这个错

**Comment by arvinxx** [comment]
请给出更详细的说明
