### ISSUE TITLE
IOS safari Unable to open[Bug] 

### ISSUE THREAD

**Issue by srcrs** [lobehub/lobe-chat#3338]
### 📦 部署环境

Docker

### 📌 软件版本

1.7.2

### 💻 系统环境

iOS

### 🌐 浏览器

Safari

### 🐛 问题描述

in iphone 12, system version is 14.5.1, unable to open, alog

Application error: a client-side exception has occurred (see the browser console for more information).

![WechatIMG359](https://github.com/user-attachments/assets/54f8cbe3-7635-4ee0-9b0d-72c9d88b364c)

**Comment by arvinxx** [comment]
maybe your iOS version is too low, try with latest version?

**Comment by srcrs** [comment]
> maybe your iOS version is too low, try with latest version?

yes，upgraded is ok
