### ISSUE TITLE
[Bug] 对话消息搜索好像搜索不出东西

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#334]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

<img width="355" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/af1f51f9-89f3-4b2c-83e1-b14e18a31784">
这个地方

**Comment by arvinxx** [comment]
搜索不出来可能是bug。后续也会做搜索能力的整体升级，加cmdk那种交互

**Comment by arvinxx** [comment]
<img width="413" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/63a2e22b-6292-4f0f-871e-018e7d25fe51">

我试了下应该是能搜出来的，只是交互上没有显示搜索到的信息。交互优化在后续迭代实施
