### ISSUE TITLE
[Bug] anthropic claude访问报错

### ISSUE THREAD

**Issue by gaye746560359** [lobehub/lobe-chat#3340]
### 📦 部署环境

Docker

### 📌 软件版本

1.7.2

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

仅配置了claude的key，聊天时报错
![1722091432928](https://github.com/user-attachments/assets/dcab4711-2d97-40c0-a3f5-dc2d705c0ad1)

**Comment by arvinxx** [comment]
你是不是开启了前端请求？

**Comment by gaye746560359** [comment]
> 你是不是开启了前端请求？

开启了客户端请求

**Comment by arvinxx** [comment]
详见： https://github.com/lobehub/lobe-chat/discussions/2442
