### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by weituo2002** [lobehub/lobe-chat#3342]
### 📦 部署环境

Official Preview

### 📌 软件版本

最新版1.72

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

使用deepbriks.ai的api key在lobe官网上配置，openai的模型可以正常使用，但是所有claude的模型都无法联通，无法使用

### 🚦 期望结果

希望能够正常使用claude3.5

**Comment by arvinxx** [comment]
请给出下具体的报错截图

**Comment by weituo2002** [comment]
![error](https://github.com/user-attachments/assets/d2fbd3da-2241-47b8-aa23-d0c7e64a8062)

**Comment by weituo2002** [comment]
在nextchat中，由于Deepbricks的API基本兼容OpenAI的格式
可以把Deepbricks当作一个新的供应商使用即可，例如这里CUSTOM_MODELS=-all,+claude-3.5-sonnet@OpenAI 可以让这个claude3.5的模型以OpenAI的格式发送到Deepbricks的服务器。
在nextchat中就可以正常使用了，但是lobe就不行，而且换成openouter的api key也不行

**Comment by weituo2002** [comment]
在nextchat中如下设置就可以用了：
![Uploading nextchat.jpg…]()

**Comment by weituo2002** [comment]
![nextchat](https://github.com/user-attachments/assets/068207ea-c9dc-4251-a7df-b42c271b9f28)

**Comment by arvinxx** [comment]
@weituo2002 你把api地址放到 OpenAI 那边去就好了。
