### ISSUE TITLE
[Request] 增加选项，替换UI中的tempture为Top_p

### ISSUE THREAD

**Issue by hlc1209** [lobehub/lobe-chat#3343]
### 🥰 需求描述

我觉得Top_p比tempture效果好得多
增加选项，替换UI中的tempture为Top_p。
![image](https://github.com/user-attachments/assets/433444b6-8739-4424-8111-b583102ba73c)

### 🧐 解决方案

增加选项，替换UI中的tempture为Top_p。
![image](https://github.com/user-attachments/assets/433444b6-8739-4424-8111-b583102ba73c)

**Comment by sxjeru** [comment]
![image](https://github.com/user-attachments/assets/8b3b94c4-6cb2-4609-abb1-041137df660d)

目前可以在此处更改。

**Comment by arvinxx** [comment]
@hlc1209 能否给出下你觉得 Top p 效果更好的示例？

**Comment by hlc1209** [comment]
> @hlc1209 能否给出下你觉得 Top p 效果更好的示例？

在很多需要创造力，但是又需要逻辑性的场合，temp调节到1，会偶尔有很奇怪的回答，调节top_p就会有创造力的同时降低说胡话的概率

**Comment by arvinxx** [comment]
@hlc1209 能否给出几个具体的案例？在需要有创造力的场景下，presense penalty 和frequency penalty 拉大也会有效果的，怎么确保 top_p 的调节效果是比较好的，而不是presense penalty 和frequency penalty ？
