### ISSUE TITLE
[Bug] openrouter api的模型无法支持fc

### ISSUE THREAD

**Issue by wangdake5111** [lobehub/lobe-chat#3346]
### 📦 Environment

Docker

### 📌 Version

v1.7.1

### 💻 Operating System

Ubuntu

### 🌐 Browser

Edge

### 🐛 Bug Description

openrouter api的模型无法支持fc（显然claude-3.5支持vision和fc，但是不会有图标显示，在对话界面也是直接不可以使用，是否是因为lobe-chat关于模型部分是硬编码？而openrouter的模型路径前面会带provider导致的），
<img width="406" alt="CleanShot 2024-07-28 at 09 34 33@2x" src="https://github.com/user-attachments/assets/1e10ee4f-6ddd-4045-881d-e5db1bfd102b">
如果我在OPENROUTER_CUSTOM_MODELS中手动打开，虽然可以访问插件，但是claude-3.5-sonnet模型依然会返回response.undefined
![image](https://github.com/user-attachments/assets/c026ad58-a58d-4e4f-b81a-5ab25f112d14)

### 🚦 Expected Behavior

fix it

**Comment by wangdake5111** [comment]
add

经过调整，虽然可以调用了，但是无法返回数据

![Image](https://github.com/user-attachments/assets/1bf93fc7-3360-4aa4-8a1c-e8eab554806a)

这是gpt会返回的


![Image](https://github.com/user-attachments/assets/b933cab1-65fc-4029-b8f4-f913c6bbd386)

**Comment by shog86** [comment]
请问调整啥了？我vercel部署也有这问题

**Comment by wangdake5111** [comment]
> 请问调整啥了？我vercel部署也有这问题

手动打开models 的特性，你可以看看文档里关于 MODEL_LIST 的部分，比如=OPENROUTER_MODEL_LIST="+claude-3.5-sonnet<200000:fc:vision>"

但是手动打开依然无法正常使用插件，会调用但不会返回

**Comment by arvinxx** [comment]
我试了下， OpenRouter 的 Claude Tools Calling 兼容度很有问题。暂时估计支持不了了

**Comment by arvinxx** [comment]
和 #3269 重复

**Comment by shog86** [comment]
OpenRouter愿意帮忙排查一下，能辛苦你给个你测试的日志不？ @arvinxx 
![image](https://github.com/user-attachments/assets/171f6694-faff-42b9-92b2-e72d30f30c20)

**Comment by arvinxx** [comment]
@shog86 我这周有给他们提过



it's about tools calling stream. OpenAI 's Tools Calling index start with 0, it likes: 

```json
{
  choices: [
    {
      delta: {
        tool_calls: [
          {
            function: { name: 'tool1', arguments: '{}' },
            id: 'call_1',
            index: 0,
            type: 'function',
          },
          {
            function: { name: 'tool2', arguments: '{}' },
            id: 'call_2',
            index: 1,
          },
        ],
      },
      index: 0,
    },
  ],
  id: '2',
}
```

but currently the Claude tools calling in OpenRouter is 
```json
{
  id: 'gen-Bx4R8TCbr4GElWZJtE30XGDQyoYW',
  model: 'anthropic/claude-3.5-sonnet',
  object: 'chat.completion.chunk',
  created: 1725817213,
  choices: [
    {
      delta: {
        role: 'assistant',
        content: null,
        tool_calls: [{ index: 1, type: 'function', function: { arguments: '{"city"' } }],
      },
      index: 0,
    },
  ],
},
```

if the index start with 1, it will hard to support

**Comment by arvinxx** [comment]
我周二跟他们反馈的，感觉没上心吧。![image](https://github.com/user-attachments/assets/5a73a130-9dba-463c-adc4-7bc0249d3697)

**Comment by shog86** [comment]
> 我周二跟他们反馈的，感觉没上心吧。

他们说今天修复了！你有空了看看~

**Comment by shog86** [comment]
试了一下，可以了
![image](https://github.com/user-attachments/assets/a77e7da0-e5f8-4408-ac0d-26702996554e)
![image](https://github.com/user-attachments/assets/60297b53-77a0-4ac4-9237-3d6499ec5ad3)
