### ISSUE TITLE
[Bug] 自定义模型显示不全

### ISSUE THREAD

**Issue by demonlzxgg** [lobehub/lobe-chat#335]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

当加入大量自定义模型后，选择模型这里显示不出全部的模型。 
![image](https://github.com/lobehub/lobe-chat/assets/33321963/75eda73e-9565-419d-8f63-ad041c2c52de)

### 🚦 期望结果 | Expected Behavior

希望能给选择模型添加一个滚动选取功能。
另外希望将Environment-Variable添加上自定义模型的选项。

**Comment by arvinxx** [comment]
> 当加入大量自定义模型后，选择模型这里显示不出全部的模型。

从未设想过会有人添加这么多模型…

**Comment by arvinxx** [comment]
> 另外希望将Environment-Variable添加上自定义模型的选项

这个可以

**Comment by arvinxx** [comment]
@demonlzxgg 已在 v0.99.0 版本支持 ，使用 `NEXT_PUBLIC_CUSTOM_MODELS` 变量, [文档传送门](https://github.com/lobehub/lobe-chat/blob/main/docs/Environment-Variable.zh-CN.md#next_public_custom_models)
