### ISSUE TITLE
[Bug] Groq提供商的llama3.1-405B调用失败

### ISSUE THREAD

**Issue by xzy103** [lobehub/lobe-chat#3367]
### 📦 Environment

Docker

### 📌 Version

1.7.8

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

Groq提供商的Llama3.1模型，8B和70B都没问题，405B模型提示“模型不存在”，可能是模型名称不对？
![image](https://github.com/user-attachments/assets/74024587-b5d8-454d-a59c-5c1eccee50ec)
![image](https://github.com/user-attachments/assets/d3d42c9f-5136-4b57-9251-7846173d11a6)
```json
{
  "error": {
    "message": "The model `llama-3.1-405b-reasoning` does not exist or you do not have access to it.",
    "type": "invalid_request_error",
    "code": "model_not_found"
  },
  "endpoint": "https://groq.****.com/openai/v1",
  "provider": "groq"
}
```

**Comment by RubuJam** [comment]
该模型暂时未对免费用户开放使用

This model is not available to free users yet.

**Comment by xzy103** [comment]
> 该模型暂时未对免费用户开放使用
> 
> This model is not available to free users yet.

原来如此
