### ISSUE TITLE
[Request] 请求失败没有重试按钮

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#337]
### 🥰 需求描述 | Feature Description

<img width="668" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/7350e709-2bbf-4d78-b6fe-4e4b78820ec1">

### 🧐 解决方案 | Proposed Solution

<img width="911" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/f6f8d0cd-9107-407d-8164-a31bb5bd4812">

**Comment by canisminor1990** [comment]
@arvinxx 你看下 我之前actionbar 的改动里把 system 的重新生成移除了，感觉需要和普通的重新生成做一些逻辑区分

**Comment by arvinxx** [comment]
> @arvinxx 你看下 我之前 actionbar 的改动里把 system 的重新生成移除了，感觉需要和普通的重新生成做一些逻辑区分，重新生成并删除上一条报错消息

这个为啥是 system

**Comment by canisminor1990** [comment]
@arvinxx 你看下 我之前actionbar 的改动里把 system 的重新生成移除了，感觉需要和普通的重新生成做一些逻辑区分

目前写的是报错会fallback到system的actionbar改完逻辑后可以移除

**Comment by arvinxx** [comment]
@canisminor1990 得先把重试和删除加回来

**Comment by canisminor1990** [comment]
> @canisminor1990 得先把重试和删除加回来

删除有的，重试按上面说明的逻辑修改后可以加回来

**Comment by arvinxx** [comment]
> @arvinxx 
> 
> 目前写的是报错会fallback到system的actionbar改完逻辑后可以移除

这个不合理。system 是llm 的role，不应该和应用的耦合，应该复用 assistant才对

**Comment by arvinxx** [comment]
举个例子，如果是包含 systemRole 的会话分享场景。你这个直接就冲突了。systemRole 的消息还没法复制

**Comment by canisminor1990** [comment]
你没理解我说的意思，我说的是现在 error 用了 system 兜底，需要重写一个 error 专用的，其中重新生成的 action 要区分下逻辑，重新生成时需要自动删除上一条错误消息

**Comment by arvinxx** [comment]
> 你没理解我说的意思，我说的是现在 error 用了 system 兜底，需要重写一个 error 专用的，其中重新生成的 action 要区分下逻辑，重新生成时需要自动删除上一条错误消息

我的意思是任何消息类型 拿 system 作为兜底不合理。因为system有自己的业务语义，不是一个应用层面定义的额外类型。

**Comment by canisminor1990** [comment]
> > 你没理解我说的意思，我说的是现在 error 用了 system 兜底，需要重写一个 error 专用的，其中重新生成的 action 要区分下逻辑，重新生成时需要自动删除上一条错误消息
> 
> 我的意思是任何消息类型 拿 system 作为兜底不合理。因为system有自己的业务语义，不是一个应用层面定义的额外类型。

😹😹😹 所以只是目前临时的啊
