### ISSUE TITLE
[Bug] Does the function "History Message Length Compression Threshold" work?

### ISSUE THREAD

**Issue by 2p990i9hpral** [lobehub/lobe-chat#3371]
### 📦 Environment

Official Preview

### 📌 Version

v1.7.8

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

I set "History Message Length Compression Threshold" to 3, but after 3 chats, nothing seems to change. I couldn't find any explanation on how this feature works in the official documentation. How does this feature work?
Is it the intended behavior that nothing changes?

**Comment by 2p990i9hpral** [comment]
https://github.com/lobehub/lobe-chat/discussions/1034
https://github.com/lobehub/lobe-chat/issues/34

I found the two issues and discussion. Isn't it implemented yet?

**Comment by arvinxx** [comment]
Yes. We will implement it in the Q3

**Comment by arvinxx** [comment]
now it's implemented
