### ISSUE TITLE
[Request] 回答结果内容过长的时候，答到一半停了。能不能像GTP逛网一样，点击继续按钮，跟在后面继续答保持连贯性。

### ISSUE THREAD

**Issue by kusila** [lobehub/lobe-chat#3372]
### 🥰 需求描述

回答结果内容过长的时候，答到一半停了。能不能像GTP逛网一样，点击继续按钮，跟在后面继续答保持连贯性。

### 🧐 解决方案

监听到未答完，按钮变成继续回答，内容连贯未答完的位置继续补充

**Comment by arvinxx** [comment]
可以，我们后续加上去

**Comment by arvinxx** [comment]
duplicate #1379
