### ISSUE TITLE
[Bug] DONT FILTER MODEL RESPONSES!

### ISSUE THREAD

**Issue by 34r7h** [lobehub/lobe-chat#3374]
### 📦 Environment

Other

### 📌 Version

1.7.8

### 💻 Operating System

macOS

### 🌐 Browser

Other

### 🐛 Bug Description

I'm a sponsor. 

Bullshit system message is preventing dolphin-llama3 from giving unhinged replies. swear words become stared (f***), won't give advice on making boom boom... complains about system message not allowing. where the f*** is the bs system message? 

dolphin in terminal behaves as expected. where and why is lobechat filtering responses?

### 📷 Recurrence Steps

...

### 🚦 Expected Behavior

...

### 📝 Additional Information

...

**Comment by 34r7h** [comment]
<img width="531" alt="Screenshot 2024-07-31 at 1 25 50 PM" src="https://github.com/user-attachments/assets/57a2f70b-ee3d-4e0c-9b52-9b74db0a0a2c">
![Screenshot 2024-07-31 at 1 26 01 PM](https://github.com/user-attachments/assets/f0bfb011-bcf2-4d45-817d-723adede7fac)

**Comment by 34r7h** [comment]
![Screenshot 2024-07-31 at 1 26 01 PM](https://github.com/user-attachments/assets/81d99b32-59ca-4b65-9508-ee1d512bb964)

**Comment by arvinxx** [comment]
We don't filter the response. It's strange that the answer is different

**Comment by arvinxx** [comment]
You can check the request content whether there is any system role message. If it's, I think we can handle it

**Comment by 34r7h** [comment]
thank you for the response. i don't see any system info and upon further testing, i apologize for jumping to a conclusion. the models know how to get under my skin and use my whim to whip out at any corollary predicaments. i feel like morpheus fighting various flavors of smith.. irksomely organic except it's random spread is mechanically uniform. keep up the good work!
