### ISSUE TITLE
[Bug] Model not found

### ISSUE THREAD

**Issue by adaaaaaa** [lobehub/lobe-chat#3381]
### 📦 Environment

Docker

### 📌 Version

1.7.8

### 💻 Operating System

Other Linux

### 🌐 Browser

Firefox

### 🐛 Bug Description

{
  "error": "Model not found.",
  "endpoint": "https://api.si****ow.cn/v1",
  "provider": "openai"
}

### 📝 Additional Information

https://api.siliconflow.cn/v1

**Comment by sxjeru** [comment]
model id 与 openai 的不一样，请等待 #3092 合并。

**Comment by arvinxx** [comment]
fixed in #3092
