### ISSUE TITLE
[Bug] 更新文档

### ISSUE THREAD

**Issue by ykangw** [lobehub/lobe-chat#3386]
### 📦 Environment

Vercel

### 📌 Version

1.8.0

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

Lobe在1.8.0版本已支持基于NextAuth的服务器端数据库，但是文档还没有更新。使用当前的文档，很难正确配置NextAuth和服务器端数据库。

此外，如果只想使用NextAuth作为身份验证，而不使用服务器端数据库，对照当前文档的“身份验证”部分配置环境变量后，不显示SSO登陆界面的问题仍然没有解决  #3136 

希望确认，这是一个bug，还是文档中的环境变量没有更新。

### 🚦 Expected Behavior

希望更新文档“私有化部署”中关于“服务器端数据库”和“身份验证”部分的内容。

**Comment by arvinxx** [comment]
服务端 Database 的镜像会单独打出来，所以再耐心等待一会

**Comment by arvinxx** [comment]
先在这里列一个极简示例吧，文档需要做一次结构调整，还要点时间。

1. 创建 pg 实例（注意：以下命名仅用于演示，因为不包含这个pg实例并没有包含持久化部分）

```
docker run --name my-postgres --network pg -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -d postgres
```

2. 创建一个 `lobe-chat.env` 文件用于存放环境变量：

```.env
# DB 必须
KEY_VAULTS_SECRET=jgwsK28dspyVQoIf8/M3IIHl1h6LYYceSYNXeLpy6uk=
DATABASE_URL=postgres://postgres:mysecretpassword@my-postgres:5432/postgres

# NEXT_AUTH 相关
NEXT_AUTH_SECRET=3904039cd41ea1bdf6c93db0db96e250
NEXT_AUTH_SSO_PROVIDERS=auth0
NEXTAUTH_URL=https://your-prod-domain.com/api/auth
AUTH0_CLIENT_ID=xxxxxx
AUTH0_CLIENT_SECRET=cSX_xxxxx
AUTH0_ISSUER=https://lobe-chat-demo.us.auth0.com

# S3 相关
S3_ACCESS_KEY_ID=xxxxxxxxxx
S3_SECRET_ACCESS_KEY=xxxxxxxxxx
S3_ENDPOINT=https://xxxxxxxxxx.r2.cloudflarestorage.com
S3_BUCKET=lobechat
NEXT_PUBLIC_S3_DOMAIN=https://s3-for-lobechat.your-domain.com
```

3. 启动 lobe-chat-database docker 镜像

```sh
docker run -it -d -p 3210:3210 --network pg --env-file lobe-chat.env lobehub/lobe-chat-database
```

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/issues/3391

**Comment by cy948** [comment]
> 此外，如果只想使用NextAuth作为身份验证，而不使用服务器端数据库，对照当前文档的“身份验证”部分配置环境变量后，不显示SSO登陆界面的问题仍然没有解决 https://github.com/lobehub/lobe-chat/issues/3136

你好，这个 BUG 仍然复现吗？ 您使用了哪些环境变量呢？ 我使用以下环境变量时没有出现问题。
```env
NEXT_AUTH_SECRET=
AUTH0_CLIENT_ID=
AUTH0_CLIENT_SECRET=
AUTH0_ISSUER=https://*.auth0.com
```
> Auth0 不需要指定启用，所以省略了 `NEXT_AUTH_SSO_PROVIDERS`

**Comment by ykangw** [comment]
> > 此外，如果只想使用NextAuth作为身份验证，而不使用服务器端数据库，对照当前文档的“身份验证”部分配置环境变量后，不显示SSO登陆界面的问题仍然没有解决 #3136
> 
> 你好，这个 BUG 仍然复现吗？ 您使用了哪些环境变量呢？ 我使用以下环境变量时没有出现问题。
> 
> ```dotenv
> NEXT_AUTH_SECRET=
> AUTH0_CLIENT_ID=
> AUTH0_CLIENT_SECRET=
> AUTH0_ISSUER=https://*.auth0.com
> ```
> 
> > Auth0 不需要指定启用，所以省略了 `NEXT_AUTH_SSO_PROVIDERS`

你好，经过检查，是我的next auth设置不对，经过修正，已经可以使用azure ad正常进行sso登陆。非常感谢！

**Comment by Amandizz** [comment]
KEY_VAULTS_SECRET=jgwsK28dspyVQoIf8/M3IIHl1h6LYYceSYNXeLpy6uk=
请问这个KEY_VAULTS_SECRET是什么意思？这个值可以自定义吗？
