### ISSUE TITLE
[Bug] Microsoft Entra ID 身份验证服务报错

### ISSUE THREAD

**Issue by Matinal111** [lobehub/lobe-chat#3388]
### 📦 Environment

Docker

### 📌 Version

v1.8.0

### 💻 Operating System

Windows

### 🌐 Browser

Chrome, Firefox

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/dcf343a5-b920-4b87-bb47-cde719b05212)
按文档配置好了，一登录就出现这个错误

**Comment by 534002646** [comment]
github登录也是一样的情况，等待官方回复

**Comment by Matinal111** [comment]
> github登录也是一样的情况，等待官方回复

问题解决，docker 镜像问题，详情阅 #3387
