### ISSUE TITLE
搜索插件都用不了呢[Bug] 

### ISSUE THREAD

**Issue by crybest** [lobehub/lobe-chat#3389]
### 📦 Environment

Official Preview

### 📌 Version

最新

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/c9cde459-2dba-4c8d-a6b8-3d70c5f2de1e)
已经填了key，调用没返回

**Comment by RubuJam** [comment]
你是用的什么模型？

What model did you use?

**Comment by arvinxx** [comment]
大概率是用了tool calling 能力很差的模型，比如 Google Gemini
