### ISSUE TITLE
[Request] 建议话题列表操作项不使用下拉选择

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#339]
### 🥰 需求描述 | Feature Description

目前这样想要删除一个话题需要鼠标放到菜单上，等菜单显示后再点删除按钮。建议右边图标直接换成删除操作，重命名的话点选中的话题标题进行重命名

### 🧐 解决方案 | Proposed Solution

<img width="285" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/368de6dd-b1bb-4cd6-bcab-156b4bf0437d">

**Comment by arvinxx** [comment]
后面还会有分享话题 和 转移话题的功能。

**Comment by mushan0x0** [comment]
> 后面还会有分享话题 和 转移话题的功能。

<img width="151" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/e802dd06-9d24-4b66-8bc6-ff2804247a2d">

或许可以做成这样的hover选中的话题：蒙层+图标

**Comment by mushan0x0** [comment]
这样横向显示，再加几个功能图标也放得下了

**Comment by canisminor1990** [comment]
感觉可以考虑下加个多选批量删除

**Comment by arvinxx** [comment]
如果是删除麻烦，后面新增一个批量删除吧。
