### ISSUE TITLE
[Bug] dockerfile部署后，agent无法加载。

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#3395]
### 📦 Environment

Docker

### 📌 Version

1.8.2

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome, Edge, Safari, Firefox

### 🐛 Bug Description

使用最新的dockerfile打包部署后，agent无法加载出来。估计是PROXYCHAINS不适配我这个环境，这玩意能否去掉。
![image](https://github.com/user-attachments/assets/b7fcab31-4085-43e7-816f-e6087029f2b4)

**Comment by yincangshiwei** [comment]
果然是PROXYCHAINS问题，我去掉就没事。

**Comment by arvinxx** [comment]
@hezhijie0327 来帮忙看看这个 case?

**Comment by hezhijie0327** [comment]
@yincangshiwei docker 部署命令能提供下嘛，如 `docker run -it --rm --name lobe-chat -e PROXY_URL="http://127.0.0.1:7890" lobehub/lobe-chat:latest`

![image](https://github.com/user-attachments/assets/6bc6a5de-9486-44d0-acf6-0f526ffc6bd8)
![image](https://github.com/user-attachments/assets/0a59d543-84cc-4d89-9782-a7c18f0f2b0e)

我本地跑了下没啥问题，建议检查下：
1. 代理配置：`docker exec -it lobe-chat cat /etc/proxychains/proxychains.conf` 
![image](https://github.com/user-attachments/assets/62745239-6884-4e77-b6e3-f2a582a4e885)
2. DNS 记录：`docker exec -it lobe-chat nslookup chat-agents.lobehub.com` 
![image](https://github.com/user-attachments/assets/d81b8832-03b7-4044-96e7-62ab9847e5ce)

**Comment by hugoyue** [comment]
docker 官方镜像，运行测试一切正常 。

**Comment by yincangshiwei** [comment]
> @yincangshiwei docker 部署命令能提供下嘛，如 `docker run -it --rm --name lobe-chat -e PROXY_URL="http://127.0.0.1:7890" lobehub/lobe-chat:latest`
> 
> ![image](https://private-user-images.githubusercontent.com/58100052/354930646-6bc6a5de-9486-44d0-acf6-0f526ffc6bd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjQ4NDIsIm5iZiI6MTcyMjgyNDU0MiwicGF0aCI6Ii81ODEwMDA1Mi8zNTQ5MzA2NDYtNmJjNmE1ZGUtOTQ4Ni00NGQwLWFjZjYtMGY1MjZmZmM2YmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAyMjIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMmM0NzZlNGQ1NjA0ZmQyNmQwNDVjMDY3YzYyNmZlOTZlMDdkZTIwNzY3NGNlMzA3ZGU4YjY0MjBlYTg0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1iZm7y39p1n1-qoFGH32HCw09NXcrZ97wIK1v6q8KOM) ![image](https://private-user-images.githubusercontent.com/58100052/354930674-0a59d543-84cc-4d89-9782-a7c18f0f2b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjQ4NDIsIm5iZiI6MTcyMjgyNDU0MiwicGF0aCI6Ii81ODEwMDA1Mi8zNTQ5MzA2NzQtMGE1OWQ1NDMtODRjYy00ZDg5LTk3ODItYTdjMThmMGYyYjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAyMjIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMGExYzM2MjA5ZGZlNjFiYmIzNmFlZWE1OGFmNDE3NjgyMTAyZDM0OGRkZjNjODhlNDY1YzdlNDQxYzcyMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wh7R9N10eNIJSgWItw5SEuxvoXqsc9mM_lJ1dxqlPbU)
> 
> 我本地跑了下没啥问题，建议检查下：
> 
> 1. 代理配置：`docker exec -it lobe-chat cat /etc/proxychains/proxychains.conf`
>    ![image](https://private-user-images.githubusercontent.com/58100052/354930993-62745239-6884-4e77-b6e3-f2a582a4e885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjQ4NDIsIm5iZiI6MTcyMjgyNDU0MiwicGF0aCI6Ii81ODEwMDA1Mi8zNTQ5MzA5OTMtNjI3NDUyMzktNjg4NC00ZTc3LWI2ZTMtZjJhNTgyYTRlODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAyMjIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZGIwMTYyOGRiMTAzNTE2MDA5ZGFjOWI3NDZiNzI0N2UyZGE5YzI5MGQ0NGY4OTgyYmI2Yzk5N2FhNGEyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c8SQ3lDJyUBFzfGpyiWYGet5huuKG-6CIC5dMHEdhHI)
> 2. DNS 记录：`docker exec -it lobe-chat nslookup chat-agents.lobehub.com`
>    ![image](https://private-user-images.githubusercontent.com/58100052/354930978-d81b8832-03b7-4044-96e7-62ab9847e5ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjQ4NDIsIm5iZiI6MTcyMjgyNDU0MiwicGF0aCI6Ii81ODEwMDA1Mi8zNTQ5MzA5NzgtZDgxYjg4MzItMDNiNy00MDQ0LTk2ZTctNjJhYjk4NDdlNWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAyMjIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0Yjg0OTJiYTMyMzZiMjE0MDBkMzIzMzNiYjliYTRlZmRiODhkMzI0OTQ2YjQ5OWJiZjFjZTY2OTVkMzc0NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1_OFye7jsN3kXtsa77QNodmFSG7AENsaMBzQxaxaoAM)

我环境所在是云函数

**Comment by hezhijie0327** [comment]
是腾讯还是阿里云的？

我简单的看了下两个平台的配置，你是通过 VPC 走内网隧道进你的 VPS 中的代理？要么看下 VPS 上 HTTP 或者 Socks 的防火墙开了不，我过会儿如果有空我实际试试

![image](https://github.com/user-attachments/assets/def3b562-05ff-4236-9131-fb06d6fc1705)
![image](https://github.com/user-attachments/assets/6568bc8c-ab9c-4058-8310-d1b04907e2ee)

**Comment by yincangshiwei** [comment]
腾讯，是要开启WebSocket?

**Comment by hezhijie0327** [comment]
假设你的代理客户端安装的位置在腾讯云的 VPS 下且在与云函数位于同一个 VPC 下的话，你可以试试在环境变量中填入 PROXY_URL 然后把 “私有网络” 勾上，然后在部署代理客户端的服务器上放行相关端口，如（`ufw allow 7890/tcp`）
![image](https://github.com/user-attachments/assets/277ff5f1-c7f4-4234-9823-74c6efc985fb)
![image](https://github.com/user-attachments/assets/ac3b30b8-1c69-4db7-a9ff-7c89a6a43b61)

BTW, 你可以提供下`PROXY_URL`不，我感觉你可能是在自己电脑上安装了代理客户端，然后在云函数中的环境变量`PROXY_URL`中填入了电脑本机的IP

anyway 这个目前看来应该不是镜像的问题

**Comment by hezhijie0327** [comment]
你是在云函数上改的还是更改了 Dockerfile？我去腾讯云上搞个实例试试
![image](https://github.com/user-attachments/assets/e4e6d585-a647-4e20-b5d6-ce3b7ff0bc90)
![image](https://github.com/user-attachments/assets/a5aeac18-363a-4a37-bf87-68e07664bd03)
![image](https://github.com/user-attachments/assets/99d79550-ed46-4516-8939-cf926cf4f392)

**Comment by hezhijie0327** [comment]
这个强制下载没搞明白，但是从 CURL fetch 的结果，在不配置任何环境变量时，官方镜像也能直接使用
![image](https://github.com/user-attachments/assets/4f5722fa-fe16-4942-8120-ffd6261fee24)

CURL 结果
![image](https://github.com/user-attachments/assets/0fdd2d34-bd79-4f72-8ed6-6383e9e27411)
![image](https://github.com/user-attachments/assets/d2348b3e-5a15-4f68-ac03-ccf4e93af905)

![image](https://github.com/user-attachments/assets/4e57e3ff-5476-4ccb-8faa-81640fda3ddf)
![image](https://github.com/user-attachments/assets/ca69fd62-5766-4f3f-afe0-a52c6a552272)

**Comment by hezhijie0327** [comment]
补一个原始 issue `/api/market?locale=zh-CN` 的结果
![image](https://github.com/user-attachments/assets/0a0f9786-cccd-4cc6-9ab0-45ccfb7f2afb)

**Comment by hezhijie0327** [comment]
如果是自定义域名的话，我这暂时做不了测试了，但是从fetch 下来的文件看，界面功能都是正常的且未复现 Agent 的 500 错误
![image](https://github.com/user-attachments/assets/df9fdbad-192c-4e70-9b62-415845945bc5)

按照腾讯云文档中的操作是可用的：
```
dokcer pull lobehub/lobe-chat:latest

docker tag lobehub/lobe-chat:latest ${实例名称}.tencentcloudcr.com/${命名空间}/${名称}:[tag]

docker push ${实例名称}.tencentcloudcr.com/${命名空间}/${名称}:[tag]
```

**Comment by yincangshiwei** [comment]
> ${PROXYCHAINS} node "/app/server.js";

它主要问题是，使用${PROXYCHAINS} node "/app/server.js"; 是有问题的，我改成CMD ["node", "/app/server.js"]是没问题。

**Comment by hezhijie0327** [comment]
主要是现在判定就是不引入啊...

当 `PROXY_URL` 为空，则 `${PROXYCHAINS}` 为空，即 `${PROXYCHAINS} node "/app/server.js"` 等同于 `  node "/app/server.js"`

而且官方镜像，我在云函数平台（上海区域）中运行都正常的... 你要么先试试下面这个方法
```
dokcer pull lobehub/lobe-chat:latest

docker tag lobehub/lobe-chat:latest ${实例名称}.tencentcloudcr.com/${命名空间}/${名称}:[tag]

docker push ${实例名称}.tencentcloudcr.com/${命名空间}/${名称}:[tag]
```

你如果有顾虑你改成这个看看，逻辑等同:
```
CMD \
    if [ -n "$PROXY_URL" ]; then \
        # Set regex for IPv4
        IP_REGEX="^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$"; \
        # Parse the proxy URL
        host_with_port="${PROXY_URL#*//}"; \
        host="${host_with_port%%:*}"; \
        port="${PROXY_URL##*:}"; \
        protocol="${PROXY_URL%%://*}"; \
        # Resolve to IP address if the host is a domain
        if ! [[ "$host" =~ "$IP_REGEX" ]]; then \
            nslookup=$(nslookup -q="A" "$host" | tail -n +3 | grep 'Address:'); \
            if [ -n "$nslookup" ]; then \
                host=$(echo "$nslookup" | tail -n 1 | awk '{print $2}'); \
            fi; \
        fi; \
        # Generate proxychains configuration file
        printf "%s\n" \
            'localnet 127.0.0.0/255.0.0.0' \
            'localnet ::1/128' \
            'proxy_dns' \
            'remote_dns_subnet 224' \
            'strict_chain' \
            'tcp_connect_time_out 8000' \
            'tcp_read_time_out 15000' \
            '[ProxyList]' \
            "$protocol $host $port" \
        > "/etc/proxychains/proxychains.conf"; \
        proxychains -q node "/app/server.js"; \
    else \
        node "/app/server.js"; \
    fi;
```

**Comment by hezhijie0327** [comment]
我拿 Cloudflare Workers 写了个让云函数的页面加载的脚本，页面加载和 agent 也正常
![image](https://github.com/user-attachments/assets/45fa4db9-b82f-4798-8c22-41974ae34fbe)
![image](https://github.com/user-attachments/assets/82c667a7-7535-4f8b-8c20-c01b87c46f58)

```
addEventListener( "fetch", ( event ) =>
{
    event.respondWith( handleRequest( event.request ) )
} )

async function handleRequest ( request )
{
    let url = request.url.substr( 8 )
    let path = url.split( "/" )
    url = url.substr( url.indexOf( "/" ) + 1 )

    var response = await fetch( "https://1301052320-9mcj2911qu-sh.scf.tencentcs.com/" + url )

    // get headers, then delete Content-Disposition: attachment
    let headers = new Headers( response.headers )
    headers.delete( "Content-Disposition" )

    return new Response( response.body, {
        status: response.status,
        headers: headers
    } )
}
```
