### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Deer404** [lobehub/lobe-chat#3404]
### 📦 部署环境

Docker

### 📌 软件版本

1.8.2

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

配置Azure OpenAI时，连通性检查默认使用模型是:gpt-4o-mini，这是一个不好的行为，因为azure openai的模型命名规则和open ai的模型并不一致。所以点击连通性检查，会失败。

### 📷 复现步骤

1. 模型设置Azure OpenAI
2.填入endpoint和Azure Api Version:2024-06-01
3.填入自定义模型：gpt-35-turbo (azure ai model命名就是这样)
4.点击连通性检查，会报错，原因默认使用gpt-4o-mini

### 🚦 期望结果

连通性检查，不应该都用gpt-4o-mini。
方案如下：
1. 使用已经填入的模型
2. 连通性检查应该标注使用的模型

### 📝 补充信息

Azure Open Ai 因为地区不同，提供的模型也不同，日本地区连4o mini都没有，调试半天发现原来是这样，希望除了报错位置，还可以在旁边看到连通性测试使用的模型参数。

**Comment by Deer404** [comment]
> 默认使用的模型就是`gpt-35-turbo`
> ```
> {
>   "model": "gpt-35-turbo",
>   "stream": true,
>   "frequency_penalty": 0,
>   "presence_penalty": 0,
>   "temperature": 0.6,
>   "top_p": 1,
>   "messages": [
>     {
>       "content": "你好",
>       "role": "user"
>     }
>   ]
> }
> ```

奇怪 我这边怎么测试都是4omini

**Comment by RubuJam** [comment]
或许是你添加并启用了其它模型，这时系统会选择第一个模型进行连通性检测

Maybe you have added and enabled other models, in which case the system will select the first model for connectivity detection.

**Comment by Deer404** [comment]
> @Deer404 或许是你添加并启用了其它模型，这时系统会选择第一个模型进行连通性检测
> 
> ```
> const checkModel = useUserStore((s) => {
>     const chatModelCards = modelProviderSelectors.getModelCardsById(providerKey)(s);
> 
>     if (chatModelCards.length > 0) {
>       return chatModelCards[0].deploymentName;
>     }
> 
>     return 'gpt-35-turbo';
>   });
> 
> ```
> Maybe you have added and enabled other models, in which case the system will select the first model for connectivity detection.

懂了，不过模型来源不同，也会引用到嘛，这是默认设置是吧，感觉可以加一个提示诶，感谢解答！

**Comment by RubuJam** [comment]
@Deer404 你之前是怎么设置，可以说明一下吗，我没太明白你的意思

Can you explain how you set it up before? I don't quite understand what you mean.

> 懂了，不过模型来源不同，也会引用到嘛，这是默认设置是吧，感觉可以加一个提示诶，感谢解答！

**Comment by Deer404** [comment]
> @Deer404 你之前是怎么设置，可以说明一下吗，"模型来源不同，也会引用到"，这个我没太明白，上面代码只会查询`Azure`的配置文件，而不会涉及其它模型供应商
> 
> How did you set it up before? Can you explain it? "Models from different sources will also be referenced", I don't quite understand this. The above code will only query the configuration file of `Azure` and will not involve other model providers.你之前是如何设置的？你能解释一下吗？"来自不同来源的模型也将被引用"，我不太理解这个。上述代码只会查询`Azure`的配置文件，不会涉及其他模型提供者。
> 
> > 懂了，不过模型来源不同，也会引用到嘛，这是默认设置是吧，感觉可以加一个提示诶，感谢解答！

@RubuJam 就像这样
![image](https://github.com/user-attachments/assets/0320e05e-da4b-4760-97bf-b0fdf7404b02)

**Comment by RubuJam** [comment]
@Deer404 系统确实会优先使用你启用的自定义模型

The system will indeed give priority to the custom models you enable
