### ISSUE TITLE
[Bug] 当使用openrouter时，部分模型的functionCall功能无法正常启用

### ISSUE THREAD

**Issue by hllshiro** [lobehub/lobe-chat#3412]
### 📦 部署环境

Docker

### 📌 软件版本

v1.9.3

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

从openrouter加载模型列表后，部分支持functionCall功能的模型无法启用该功能，例如gpt-4o-mini-2024-07-18。模型是否支持functionCall似乎是在modelProviders中定义，更新后合并，但openrouter.ts只有14个定义，远小于平台提供的185个模型。

### 📷 复现步骤

- 通过openrouter加载模型列表，选择gpt-4o-mini-2024-07-18模型
- 切换助手的模型为gpt-4o-mini-2024-07-18
- 设置插件，提示`当前模型不支持函数调用`

### 🚦 期望结果

能正确的开启插件功能

### 📝 补充信息

能否提供一个选项来强制开启此功能，以免于维护庞大的模型列表？

**Comment by RubuJam** [comment]
使用自定义模型即可

Use a custom model

**Comment by hllshiro** [comment]
抱歉，之前没有发现可以手动创建。

**Comment by lsalazarm99** [comment]
@RubuJam Thanks for the workaround! I'm not sure if the issue should be closed because it doesn't seem to be the way it should work. Unless it is a "won't fix".
