### ISSUE TITLE
[Bug] 使用cloudflare的r2储存上传图片提示错误

### ISSUE THREAD

**Issue by maxage** [lobehub/lobe-chat#3413]
### 📦 Environment

Docker

### 📌 Version

v1.9.3

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 错误描述
按照要求，设置到了cloudflare的R2储存，绑定了域名。在上传图片时候提示。文件上传失败，请检查网络连接或稍后再试
详情: Error: fileEnv.NEXT_PUBLIC_S3_DOMAIN is not set while enable server upload
![微信图片_20240806224148](https://github.com/user-attachments/assets/548400ea-c33c-4ecc-b8d2-c91fc67c2237)

### 储存设置
      S3_BUCKET: lobechat（储存桶名）
      S3_ENDPOINT: https://d712b5fb5xxxxxxxxxxxxe128ddf199d8e.r2.cloudflarestorage.com（S3 API）
      NEXT_PUBLIC_S3_DOMAIN: https://lobechat.xxxxx.cc (自定义域，域名是在cloudflare托管的)
      S3_ACCESS_KEY_ID: 589650ec967xxxxxxxx497f0af613b614 （管理员权限）
      S3_SECRET_ACCESS_KEY: af646c7b0f58xxxxxxx4141be09c478f9b7d1d2xxxxxx6f1b409a087f3（管理员权限）

### 在cloudflare的R2里面也能看到通过前端上传进去的图片，但是右上角提示错误，也无法识别。

![微信图片_20240806224605](https://github.com/user-attachments/assets/077d6dbe-7f27-46a0-8c79-09f0932a3396)

并且CORS也正确设置
`[
  {
    "AllowedOrigins": [
      "https://lobechat前端访问域名",
    ],
    "AllowedMethods": [
      "GET",
      "PUT",
      "HEAD",
      "POST",
      "DELETE"
    ],
    "AllowedHeaders": [
      "*"
    ],
    "ExposeHeaders": [],
    "MaxAgeSeconds": 3000
  }
]`

![error](https://github.com/user-attachments/assets/3a54c1d9-3fdc-4e1d-9926-21f79d7be0db)

**Comment by Lovest20018** [comment]
一样的问题，还有ACCESS_CODE参数客户端需要手动输入下，不然直接提示无权限。

**Comment by maxage** [comment]
> 一样的问题，还有ACCESS_CODE参数客户端需要手动输入下，不然直接提示无权限。

我没有设置ACCESS_CODE 用的Auth0登录进去的

**Comment by Lovest20018** [comment]
> > 一样的问题，还有ACCESS_CODE参数客户端需要手动输入下，不然直接提示无权限。
> 
> 我没有设置ACCESS_CODE 用的Auth0登录进去的

看到大佬说过，ACCESS_CODE应该是不需要了，不过Auth0配置文档上面还写着必须。
我删了ACCESS_CODE就没提示无权限了，跟你现在一样的问题。

**Comment by bentwnghk** [comment]
`NEXT_PUBLIC_S3_DOMAIN` 這個環境變量不能像一般環境變量在容器啟動時讀入。

**Comment by arvinxx** [comment]
这个是遗留 bug，会在知识库/文件上传功能发布时一并修复

**Comment by 534002646** [comment]
> 这个是遗留 bug，会在知识库/文件上传功能发布时一并修复

请问什么时候会发布

**Comment by sqkkyzx** [comment]
使用腾讯云COS，遇到同样问题，前端报错：

```
Error: fileEnv.NEXT_PUBLIC_S3_DOMAIN is not set while enable server upload
```

图片实际已经上传到对象存储。

**Comment by wxy-skye** [comment]
同问，什么时候发布。毕竟这个影响日常使用了。

I have the same question - when will it be released? After all, this is affecting everyday use.

**Comment by arvinxx** [comment]
@534002646 预计这两周吧。

> 同问，什么时候发布。毕竟这个影响日常使用了。

@wxy-skye 如果你的使用强依赖图片上传，可以先使用客户端 db 模式

**Comment by dalefengs** [comment]
minio 同样的问题

**Comment by briankwon** [comment]
> 这个是遗留 bug，会在知识库/文件上传功能发布时一并修复

请问能否考虑在上传文件时支持path style？目前使用了virtual host形式，对动态IP的服务器来说配置会比较繁琐

具体区别如下：
With path-style lookups, applications can access the bucket using its full path as **minio.example.net/mybucket**.

With virtual-host lookups, application can access the bucket as a virtual host as **mybucket.minio.example.net/**.

**Comment by urzz** [comment]
同楼上，cloudflare tunnel 的证书只支持到二级域名，如果使用 virtual host，依赖tunnel的minio服务就无法直接使用了。如果是 Path Style 可以使用二级域名访问

**Comment by arvinxx** [comment]
@briankwon path style 是啥？是 s3 标准的实现吗？

**Comment by briankwon** [comment]
> @briankwon path style 是啥？是 s3 标准的实现吗？

@arvinxx  path style和virtual host在s3是访问bucket和object的不同方式，URL 的结构和域名解析不太一样

假设minio的域名是minio.example.net，bucket为mybucket，object为config.env，具体区别如下：
path-style——minio.example.net/**mybucket**/config.env
virtual-host——**mybucket**.minio.example.net/config.env

可以发现bucket的位置是不同的，一个体现在path一个体现在域名，path-style在使用更简单，而virtual-host会涉及到部署反向代理解析等问题，对于个人使用有一定成本。

可以通过amazon s3 client初始化时控制是否激活path style，关于JavaScript SDK我找到了相关文档，[https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md](url)
![image](https://github.com/user-attachments/assets/c6953cfe-cbb3-4873-b3f1-bc66d6cc84fc)

**Comment by 80imike** [comment]
minio 同样的问题

**Comment by arvinxx** [comment]
@briankwon 了解了。那看来可以加个环境变量来支持这种写法。

**Comment by RidiculousBuffal** [comment]
关于NEXT_PUBLIC_变量在DOCKER中不能自动注入NEXTJS的问题下面是一个临时的解决方法:
在dockerfile中使用ARG参数取代ENV参数即:
```docker
ARG NEXT_PUBLIC_S3_DOMAIN="https://hpcow-******com"
ENV NEXT_PUBLIC_S3_DOMAIN = ${NEXT_PUBLIC_S3_DOMAIN}
```docker
经过测试可以解决这个问题,我这边是腾讯云做OSS所以
@sqkkyzx 应该可以通过我这个方式解决这个问题 @maxage @wxy-skye @bentwnghk 希望对各位有用呀！😀😀
![Snipaste_2024-08-13_17-52-24](https://github.com/user-attachments/assets/e6e108df-e2dc-4992-b232-9e5a7136fd1c)
参考链接:
 [https://stackoverflow.com/questions/76124346/how-can-i-pass-an-env-variable-to-next-js-app-running-inside-a-docker-container](url)
[https://github.com/vercel/next.js/discussions/14030](url)

**Comment by mujiannan** [comment]
部署后能够上文文件到`s3`或兼容存储桶（如`minio` ），但遇到了前端报错：`NEXT_PUBLIC_S3_DOMAIN is not set while enable server upload`，原因是官方镜像build时就已经嵌入了前端代码，在容器运行时注入的环境变量只在后端生效。`next.js`的文档[Configuring: Environment Variables | Next.js (nextjs.org)](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables)：
> **By default, environment variables are only available on the server**. To expose an environment variable to the browser, it must be prefixed with `NEXT_PUBLIC_`. However, these public environment variables will be inlined into the JavaScript bundle during `next build`.

临时解决办法（workaround）：自行build镜像，build时就把自己的`NEXT_PUBLIC` 开头的环境变量打进去。

**Comment by 80imike** [comment]
> 关于NEXT_PUBLIC_变量在DOCKER中不能自动注入NEXTJS的问题下面是一个临时的解决方法: 在dockerfile中使用ARG参数取代ENV参数即:
> 
> ARG NEXT_PUBLIC_S3_DOMAIN="https://hpcow-******com" ENV NEXT_PUBLIC_S3_DOMAIN = ${NEXT_PUBLIC_S3_DOMAIN}
> 
> 经过测试可以解决这个问题,我这边是腾讯云做OSS所以 @sqkkyzx 应该可以通过我这个方式解决这个问题 @maxage @wxy-skye @bentwnghk 希望对各位有用呀！😀😀 ![Snipaste_2024-08-13_17-52-24](https://private-user-images.githubusercontent.com/124059108/357364686-e6e108df-e2dc-4992-b232-9e5a7136fd1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTk1NjcsIm5iZiI6MTcyMzU5OTI2NywicGF0aCI6Ii8xMjQwNTkxMDgvMzU3MzY0Njg2LWU2ZTEwOGRmLWUyZGMtNDk5Mi1iMjMyLTllNWE3MTM2ZmQxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwMTM0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODhkYjdiNTkwM2ZlMTM0MGMzNzExNzQ0ODQwNzQ0MTUyNzcyMTEwZjQ5MmI5NzkwNzNmMjM4MTIxY2Y3NzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7NUo9z7QqapLliK6Lr8iSdWw40557kEe4hO7GhWGu-k) 参考链接: [https://stackoverflow.com/questions/76124346/how-can-i-pass-an-env-variable-to-next-js-app-running-inside-a-docker-container](url) [https://github.com/vercel/next.js/discussions/14030](url)

不错，期待官方镜像尽快把这个修复加进去

**Comment by arvinxx** [comment]
> 关于NEXT_PUBLIC_变量在DOCKER中不能自动注入NEXTJS的问题下面是一个临时的解决方法: 在dockerfile中使用ARG参数取代ENV参数即:
> 
> ARG NEXT_PUBLIC_S3_DOMAIN="https://hpcow-******com" ENV NEXT_PUBLIC_S3_DOMAIN = ${NEXT_PUBLIC_S3_DOMAIN}
> 
> 经过测试可以解决这个问题,我这边是腾讯云做OSS所以 @sqkkyzx 应该可以通过我这个方式解决这个问题 @maxage @wxy-skye @bentwnghk 希望对各位有用呀！😀😀 ![Snipaste_2024-08-13_17-52-24](https://private-user-images.githubusercontent.com/124059108/357364686-e6e108df-e2dc-4992-b232-9e5a7136fd1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDU0MTMsIm5iZiI6MTcyMzYwNTExMywicGF0aCI6Ii8xMjQwNTkxMDgvMzU3MzY0Njg2LWU2ZTEwOGRmLWUyZGMtNDk5Mi1iMjMyLTllNWE3MTM2ZmQxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwMzExNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjBhNzBjOGViYzBkYjViZDM2MjJiYjk1MzEyODFmNWE3OGE0ODcwNWI5ZGQyMDFiMDM1Y2ZiYmMxNTA1NjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8rMfNsH1f3480gSK2iSroErn4_IB6oe392s0VBNSj9g) 参考链接: [https://stackoverflow.com/questions/76124346/how-can-i-pass-an-env-variable-to-next-js-app-running-inside-a-docker-container](url) [https://github.com/vercel/next.js/discussions/14030](url)


你这个是运行时方案还是构建时方案？

**Comment by mujiannan** [comment]
> > 关于NEXT_PUBLIC_变量在DOCKER中不能自动注入NEXTJS的问题下面是一个临时的解决方法: 在dockerfile中使用ARG参数取代ENV参数即:
> > ARG NEXT_PUBLIC_S3_DOMAIN="https://hpcow-******com" ENV NEXT_PUBLIC_S3_DOMAIN = ${NEXT_PUBLIC_S3_DOMAIN}
> > 经过测试可以解决这个问题,我这边是腾讯云做OSS所以 @sqkkyzx 应该可以通过我这个方式解决这个问题 @maxage @wxy-skye @bentwnghk 希望对各位有用呀！😀😀 ![Snipaste_2024-08-13_17-52-24](https://private-user-images.githubusercontent.com/124059108/357364686-e6e108df-e2dc-4992-b232-9e5a7136fd1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDU0MTMsIm5iZiI6MTcyMzYwNTExMywicGF0aCI6Ii8xMjQwNTkxMDgvMzU3MzY0Njg2LWU2ZTEwOGRmLWUyZGMtNDk5Mi1iMjMyLTllNWE3MTM2ZmQxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwMzExNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjBhNzBjOGViYzBkYjViZDM2MjJiYjk1MzEyODFmNWE3OGE0ODcwNWI5ZGQyMDFiMDM1Y2ZiYmMxNTA1NjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8rMfNsH1f3480gSK2iSroErn4_IB6oe392s0VBNSj9g) 参考链接: [https://stackoverflow.com/questions/76124346/how-can-i-pass-an-env-variable-to-next-js-app-running-inside-a-docker-container](url) [https://github.com/vercel/next.js/discussions/14030](url)
> 
> 你这个是运行时方案还是构建时方案？

这个明显是构建时方案，需要用户自行build镜像的。

**Comment by RidiculousBuffal** [comment]
> > 关于NEXT_PUBLIC_变量在DOCKER中不能自动注入NEXTJS的问题下面是一个临时的解决方法: 在dockerfile中使用ARG参数取代ENV参数即:
> > ARG NEXT_PUBLIC_S3_DOMAIN="https://hpcow-******com" ENV NEXT_PUBLIC_S3_DOMAIN = ${NEXT_PUBLIC_S3_DOMAIN}
> > 经过测试可以解决这个问题,我这边是腾讯云做OSS所以 @sqkkyzx 应该可以通过我这个方式解决这个问题 @maxage @wxy-skye @bentwnghk 希望对各位有用呀！😀😀 ![Snipaste_2024-08-13_17-52-24](https://private-user-images.githubusercontent.com/124059108/357364686-e6e108df-e2dc-4992-b232-9e5a7136fd1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDU0MTMsIm5iZiI6MTcyMzYwNTExMywicGF0aCI6Ii8xMjQwNTkxMDgvMzU3MzY0Njg2LWU2ZTEwOGRmLWUyZGMtNDk5Mi1iMjMyLTllNWE3MTM2ZmQxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwMzExNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjBhNzBjOGViYzBkYjViZDM2MjJiYjk1MzEyODFmNWE3OGE0ODcwNWI5ZGQyMDFiMDM1Y2ZiYmMxNTA1NjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8rMfNsH1f3480gSK2iSroErn4_IB6oe392s0VBNSj9g) 参考链接: [https://stackoverflow.com/questions/76124346/how-can-i-pass-an-env-variable-to-next-js-app-running-inside-a-docker-container](url) [https://github.com/vercel/next.js/discussions/14030](url)
> 
> 你这个是运行时方案还是构建时方案？

应该算构建时方案

**Comment by arvinxx** [comment]
@RidiculousBuffal  构建时方案没法做进官方镜像里的吧

**Comment by sqkkyzx** [comment]
> @RidiculousBuffal 构建时方案没法做进官方镜像里的吧

能不能不从环境变量中读取这个配置，换其他方案呢，比如传入一个配置文件之类，或者直接从数据库读取

**Comment by arvinxx** [comment]
> 传入一个配置文件之类，或者直接从数据库读取

构建时变量和运行时变量的区别就是构建时变量是在构建阶段注入然后写死在构建产物里的，所以它没法在运行时灵活修改。

就先不用出其他主意了，这个问题我们会在知识库/文件上传的 feature 中修复掉的，耐心等待就好

**Comment by arvinxx** [comment]
已修复： https://github.com/lobehub/lobe-chat/pull/3487
