### ISSUE TITLE
[Bug] 添加服务端数据库报错了

### ISSUE THREAD

**Issue by 1012039590** [lobehub/lobe-chat#3415]
### 📦 部署环境

Vercel

### 📌 软件版本

1，8，2

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

按照教程添加  服务端 数据库 就报错了。
![image](https://github.com/user-attachments/assets/1ad11276-fd53-4bba-a6c2-f400987a1aed)
如果只是简单添加 key 之类， 不添加服务端数据库的变量就没问题。  请帮忙看看。  我全程使用的都是 推荐的 vercel。

**Comment by arvinxx** [comment]
你的数据库是什么？

**Comment by sxjeru** [comment]
类似 #2914 ，可以检查下有没有环境变量遗漏了。

doc：https://lobehub.com/zh/docs/self-hosting/server-database
