### ISSUE TITLE
[Bug] Deployment failure by Vercel

### ISSUE THREAD

**Issue by cuiko** [lobehub/lobe-chat#3417]
### 📦 Environment

Vercel

### 📌 Version

v1.9.3

### 💻 Operating System

Other

### 🌐 Browser

Other

### 🐛 Bug Description

![Snipaste_2024-08-06_23-48-47](https://github.com/user-attachments/assets/9a83776a-4e0d-48fc-ab9b-f3b576583971)

### 📷 Recurrence Steps

1. Fork project
2. import project in Vercel
3. Deploy

**Comment by heslanx** [comment]
The same problem is happening on Railway.

**Comment by breakstring** [comment]
估计是 #3416  要解决的问题吧
