### ISSUE TITLE
[Request] 通义千问大模型图片识别功能

### ISSUE THREAD

**Issue by Liyu910228** [lobehub/lobe-chat#3419]
### 🥰 需求描述

<img width="851" alt="4cfe6b2fe02aae825ab1f43797593cf" src="https://github.com/user-attachments/assets/13032d75-a320-42f1-8fbe-55a3674def9a">
没有办法使用通义千问模型qwen-vl-max

### 🧐 解决方案

支持通义千问模型qwen-vl-max

**Comment by Mingholy** [comment]
`qwen-vl-max`现在是支持的呀，语言模型配置中连通性检查是否成功？报错的details里有什么？

**Comment by Liyu910228** [comment]
<img width="420" alt="c7a1b3fbb839113f8613c9deec128c5" src="https://github.com/user-attachments/assets/91ee043f-5f4c-4818-8d71-ad637595b314">
对于有文字的图片识别qwen-vl-max没有报错过，但是对于纯图画的图片就看概率报错，不知道是模型问题还是什么问题

**Comment by Mingholy** [comment]
> <img alt="c7a1b3fbb839113f8613c9deec128c5" width="420" src="https://private-user-images.githubusercontent.com/55588842/356942551-91ee043f-5f4c-4818-8d71-ad637595b314.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDI0OTMsIm5iZiI6MTcyMzQ0MjE5MywicGF0aCI6Ii81NTU4ODg0Mi8zNTY5NDI1NTEtOTFlZTA0M2YtNWY0Yy00ODE4LThkNzEtYWQ2Mzc1OTViMzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA1NTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZmE2Mzg2ZGZiNzdhZDEwNTU5OTBhM2JlODQyZDYzMTU5NmExNTE3MTlhNzc3MzBiMzljODE5MDc2ZGUzOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ljP1oiOduwBcB0supZxW_27s5ovdd_NdPKbWtMLJb4A"> 对于有文字的图片识别qwen-vl-max没有报错过，但是对于纯图画的图片就看概率报错，不知道是模型问题还是什么问题

在其他的chat client上也会报错？那应该不是lobe-chat的问题了

**Comment by Liyu910228** [comment]
<img width="384" alt="2b697b532fe9866add2f777e506d58d" src="https://github.com/user-attachments/assets/548de088-3c58-4f5c-892f-087e0deecc89">
在nenext-chat上没有发现问题；在lobe-chat和Open WebUI 上是同样的问题，需要看概率；3个客户端我部署在3台云服务器上

**Comment by arvinxx** [comment]
给下详细的报错说明。不然解决不了你的问题

**Comment by Liyu910228** [comment]
<img width="736" alt="09a8f0fff2de0939a4ba6069b372850" src="https://github.com/user-attachments/assets/ac19f416-d14c-490d-9a97-1970f6ed614b">
这个one-api调用是正常的
<img width="863" alt="e73259f06fad2e53aa8243aa5688eae" src="https://github.com/user-attachments/assets/ee0b4c5f-e632-4394-aadc-819dcf02c048">
日志也有返回  这是咱们的日志
<img width="752" alt="fad9a5393d661742e366d1f33f6bcc5" src="https://github.com/user-attachments/assets/84ee07c5-af74-450a-903b-d061aa03867f">
也没有发现什么报错，感觉很奇怪

**Comment by arvinxx** [comment]
展开看下ui 层面的抛错，还有请求

**Comment by Liyu910228** [comment]
<img width="956" alt="12295c193de43c4023f91f454a49b0f" src="https://github.com/user-attachments/assets/7e1da6f4-400b-4644-b17e-64ddbdb50415">
<img width="959" alt="51c4353e856d1d1a8ec809cbda07adb" src="https://github.com/user-attachments/assets/787821b4-822c-4bee-bd80-81d5f6385075">
<img width="960" alt="ae9e27e936682153ee46a18d725d6d7" src="https://github.com/user-attachments/assets/84ec2464-e264-4f1e-af48-479eb1f0d67d">
上面响应是200ok，但是返回报错是网关问题，我不太懂这个错误
