### ISSUE TITLE
[Bug] 是否支持MiniCPM-V 2.6？

### ISSUE THREAD

**Issue by calonye** [lobehub/lobe-chat#3422]
### 📦 部署环境

Other

### 📌 软件版本

v1.9.4

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

<img width="639" alt="image" src="https://github.com/user-attachments/assets/216d6330-4a8b-4506-a735-ac96e14c803f">

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/1d81e827-d2e0-49ef-b8b0-45f31d94cbb7">

```
{
  "error": {
    "message": "llama runner process has terminated: signal: aborted (core dumped)",
    "name": "ResponseError",
    "status_code": 500
  },
  "provider": "ollama"
}
```

### 🚦 期望结果

希望支持MiniCPM-V 2.6

**Comment by sxjeru** [comment]
请问直接用 ollama 能否与此模型对话。

ref：https://github.com/ollama/ollama/issues/4912

**Comment by gotoolkits** [comment]
same issue:

➜ ollama run aiden_lu/minicpm-v2.6:Q4_K_M
Error: llama runner process has terminated: signal: abort trap

➜ ollama -v
ollama version is 0.3.4

**Comment by tyzero** [comment]
Ollama now supports MiniCamp-v 2.6. Please update it; it should allow users to send images.

 [https://github.com/ollama/ollama/releases/tag/v0.3.10](https://github.com/ollama/ollama/releases/tag/v0.3.10)

**Comment by tyzero** [comment]
@sxjeru  CLI 执行 **ollama run  minicpm-v2.6** 目前最新版本已经正常，希望尽快修复。应该只是把vision 配置默认给minicpm打开就好了。

https://github.com/ollama/ollama/releases/tag/v0.3.10

**Comment by cr-zhichen** [comment]
现在使用ollama已经可以正常使用minicpm-v2.6 ，但无法使用视觉识别
![66e4f371677f0.png](https://img-cdn.ccrui.cn/2024/09/14/66e4f371677f0.png)
