### ISSUE TITLE
[Bug] Vercel部署非数据库版报错

### ISSUE THREAD

**Issue by SpeedupMaster** [lobehub/lobe-chat#3434]
### 📦 部署环境

Vercel

### 📌 软件版本

v1.96

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

Failed to compile.
./src/app/api/middleware/auth/index.ts:1:10
Type error: Module '"@clerk/backend/internal"' has no exported member 'AuthObject'.
> 1 | import { AuthObject } from '@clerk/backend/internal';
    |          ^
  2 | import { getAuth } from '@clerk/nextjs/server';
  3 | import { NextRequest } from 'next/server';
  4 |
error: script "build" exited with code 1
Error: Command "bun run build" exited with 1

**Comment by arvinxx** [comment]
没更新吧，看着是旧代码
