### ISSUE TITLE
[Request] Ollama Tool (Funtion) Calling

### ISSUE THREAD

**Issue by DEAD1SIDE** [lobehub/lobe-chat#3436]
### 🥰 Feature Description

Ollama released Tool support [https://ollama.com/blog/tool-support](https://ollama.com/blog/tool-support).
It would be nice to use it.

### 🧐 Proposed Solution

Let the user select what models can function call

**Comment by arvinxx** [comment]
Ollama don't support stream tool using. So it's a little difficult to implement it. I plan to wait for the stream tools use implement of Ollama

**Comment by p00pcvm** [comment]
[You're not getting good publicity with that attitude.](https://youtu.be/m4sfPCI0FWQ?si=YhWH4Fw6dcpsfw5F)

**Comment by arvinxx** [comment]
@p00pcvm I' sorry for that, but I work on this only by myself and I have limited time. There are more important features to do like knowledge base/ file upload. I will maintain this project in long-term. So I make decision for what's the better in the long run.

In the mean-while you can still use Open WebUI which match better with Ollama.

As for the detail why I need to wait for , you can check it here: https://github.com/lobehub/lobe-chat/issues/2311#issuecomment-2290657866

**Comment by p00pcvm** [comment]
@arvinxx I'm sorry, I didn't realize you were doing this by yourself. I was under the impression there was a team of engineers working on the project.

**Comment by arvinxx** [comment]
@arvinxx I do the main product plan / main UX design / frontend and backend develop / marketing. @canisminor1990 will also help for some features. But LobeChat is our side project by now. That's why we open-source it, community help a lot on small bug fix and document update.
