### ISSUE TITLE
[Bug] LOBEHUB无法在new-api中带令牌直接进入，需要复制令牌

### ISSUE THREAD

**Issue by sheongkamyu** [lobehub/lobe-chat#3437]
### 📦 部署环境

Docker

### 📌 软件版本

无

### 💻 系统环境

Ubuntu, Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

LOBEHUB无法在new-api中带令牌直接进入，需要复制令牌，其他chatgpt-next等可以。

![Uploading image.png…]()

### 📷 复现步骤

RT

### 🚦 期望结果

RT

### 📝 补充信息

RT

**Comment by arvinxx** [comment]
我记得可以的吧，咋就不行了

**Comment by sheongkamyu** [comment]
在new api中无法带sk-xxxx令牌进入，还需要手动再复制一次
new api地址：https://github.com/Calcium-Ion/new-api

**Comment by arvinxx** [comment]
自己的配置的问题？我看别人的站点是可以的啊？


https://github.com/user-attachments/assets/3ea0054e-deb0-4e55-8af9-3939a7d98d02
