### ISSUE TITLE
[Bug] claude模型的“使用客户端请求模式”选项消失不见

### ISSUE THREAD

**Issue by redapple0204** [lobehub/lobe-chat#3444]
### 📦 部署环境

Official Preview

### 📌 软件版本

v1.9.6

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

claude模型的“使用客户端请求模式”选项消失不见，其他模型的正常
<img width="756" alt="image" src="https://github.com/user-attachments/assets/008ab165-2b00-4739-8624-c391dd86477e">
<img width="777" alt="image" src="https://github.com/user-attachments/assets/7d01d046-6914-4a39-ab76-1a04a591b8b9">

**Comment by arvinxx** [comment]
claude 不支持客户端请求。 https://github.com/lobehub/lobe-chat/discussions/2442
