### ISSUE TITLE
[Bug] 历史数据切换助手后不显示

### ISSUE THREAD

**Issue by alphandbelt1** [lobehub/lobe-chat#3451]
### 📦 Environment

Other

### 📌 Version

1.9.6

### 💻 Operating System

Windows, Ubuntu

### 🌐 Browser

Edge

### 🐛 Bug Description

使用最新的1.9.6在本地编译的，配置了pgsql的数据库和clerk验证。
发现切换助手后之前的历史消息就不显示了，但是看后台数据库里面是有历史的消息的。

https://github.com/user-attachments/assets/e531b090-882e-464b-8eb9-5744896e0b59

**Comment by arvinxx** [comment]
右侧边栏打开。看下topic
