### ISSUE TITLE
[Bug] Deployment failed on vercel

### ISSUE THREAD

**Issue by davaded** [lobehub/lobe-chat#3453]
### 📦 部署环境

Vercel

### 📌 软件版本

latest

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

Deployment failed on vercel, retried many times, including deleting the repository and reforking.I did not modify or add any other environment variables except the open API key
![image](https://github.com/user-attachments/assets/1e729970-6f65-4164-ac77-36f514d3299c)

**Comment by Nolovenodie** [comment]
同样遇到此问题

**Comment by arvinxx** [comment]
Ollama 发包导致，先锁 0.5.6，已提 issue: https://github.com/ollama/ollama-js/issues/132

**Comment by jmorganca** [comment]
Hi all, sorry about this. Working on a fix

**Comment by jmorganca** [comment]
Fixed in https://github.com/ollama/ollama-js/releases/tag/v0.5.8
