### ISSUE TITLE
[Request] 支持通用 OAuth2.0 / OIDC 协议的 SSO 登录

### ISSUE THREAD

**Issue by Oniokey** [lobehub/lobe-chat#3454]
### 🥰 需求描述

对于许多 SSO 系统，都实现了 OIDC 协议，例如 `Casdoor` 等等，可以适配标准 OIDC 协议来广泛增加适配的身份提供商（IdP）

### 🧐 解决方案

对于支持 well-known 能力的系统，可以通过 `https://{server}/.well-known/openid-configuration` 可以快速发现 `authorization_endpoint` `token_endpoint` `userinfo_endpoint` 和 `scopes_supported` 等 OIDC 登录流程中重要的接口，从而动态配置第三方 IdP 登录

**Comment by arvinxx** [comment]
@cy948 NextAuth 支持对接通用 OAuth 2.0/OIDC 吗？

**Comment by cy948** [comment]
> @cy948 NextAuth 支持对接通用 OAuth 2.0/OIDC 吗？

支持

**Comment by arvinxx** [comment]
@Oniokey 能否介绍下如果支持了通用 OAuth 2.0/OIDC ，有什么收益不？

**Comment by cy948** [comment]
若社区没有支持你当前的provider，你也可以自行fork并维护。NextAuth中使用通用provdier可以参考文档：https://authjs.dev/guides/configuring-oauth-providers

**Comment by mujiannan** [comment]
`wellknown-url` 是可以直接在浏览器中打开查看内容的，里面包含一些重要信息，如issuer、scopes等。  
从你的`SSO-Server` 的`wellknown-url` 拿到这些信息后，将它们当作`Auth0` 配置即可。
