### ISSUE TITLE
[Bug] Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).

### ISSUE THREAD

**Issue by liuyaaixxa** [lobehub/lobe-chat#3456]
### 📦 Environment

Other

### 📌 Version

1.9.6

### 💻 Operating System

macOS

### 🌐 Browser

Firefox

### 🐛 Bug Description

yarn run v1.22.19
$ next dev -p 3010
  ▲ Next.js 14.2.5
  - Local:        http://localhost:3010
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 2.5s
 ○ Compiling /src/middleware ...
 ✓ Compiled /src/middleware in 917ms (374 modules)
 ○ Compiling / ...
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/store/user/slices/modelList/action.ts
./src/store/user/store.ts
./src/store/user/index.ts
./src/app/(loading)/Redirect.tsx
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/store/user/slices/modelList/action.ts
./src/store/user/store.ts
./src/store/user/index.ts
./src/app/(loading)/Redirect.tsx
 GET / 500 in 45030ms
^C
(base) liuya@ZBMAC-a623b1996 zg-playgroud-chat % 

(base) liuya@ZBMAC-a623b1996 zg-playgroud-chat % yarn dev 
yarn run v1.22.19
$ next dev -p 3010
  ▲ Next.js 14.2.5
  - Local:        http://localhost:3010
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 2.7s
 ○ Compiling /_not-found ...
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/store/user/slices/modelList/action.ts
./src/store/user/store.ts
./src/store/user/index.ts
./src/features/PWAInstall/index.tsx
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/store/user/slices/modelList/action.ts
./src/store/user/store.ts
./src/store/user/index.ts
./src/features/PWAInstall/index.tsx
 GET / 500 in 2300ms
 GET / 500 in 2301ms
 GET / 500 in 14356ms
 ⚠ Found a change in next.config.mjs. Restarting the server to apply the changes...
  ▲ Next.js 14.2.5
  - Local:        http://localhost:3010
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 4.8s
 ○ Compiling /_not-found ...
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/const/settings/agent.ts
./src/const/settings/index.ts
./src/locales/create.ts
./src/layout/GlobalProvider/Locale.tsx
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/store/user/slices/modelList/action.ts
./src/store/user/store.ts
./src/store/user/index.ts
./src/features/PWAInstall/index.tsx
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/store/user/slices/modelList/action.ts
./src/store/user/store.ts
./src/store/user/index.ts
./src/features/PWAInstall/index.tsx
 GET / 500 in 2666ms
 GET / 500 in 2668ms
 GET / 500 in 2669ms
 ⚠ Found a change in next.config.mjs. Restarting the server to apply the changes...
  ▲ Next.js 14.2.5
  - Local:        http://localhost:3010
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 4.1s
 ○ Compiling /_not-found ...
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/const/settings/agent.ts
./src/const/settings/index.ts
./src/locales/create.ts
./src/layout/GlobalProvider/Locale.tsx
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: ENOENT: no such file or directory, rename '/Users/liuya/PycharmProjects/pythonProject/9n_rag_ruigewk/rag_ruige_web/zg-playgroud-chat/.next/cache/webpack/client-development-fallback/0.pack.gz_' -> '/Users/liuya/PycharmProjects/pythonProject/9n_rag_ruigewk/rag_ruige_web/zg-playgroud-chat/.next/cache/webpack/client-development-fallback/0.pack.gz'
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: ENOENT: no such file or directory, rename '/Users/liuya/PycharmProjects/pythonProject/9n_rag_ruigewk/rag_ruige_web/zg-playgroud-chat/.next/cache/webpack/client-development-fallback/0.pack.gz_' -> '/Users/liuya/PycharmProjects/pythonProject/9n_rag_ruigewk/rag_ruige_web/zg-playgroud-chat/.next/cache/webpack/client-development-fallback/0.pack.gz'
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/store/user/slices/modelList/action.ts
./src/store/user/store.ts
./src/store/user/index.ts
./src/features/PWAInstall/index.tsx
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/store/user/slices/modelList/action.ts
./src/store/user/store.ts
./src/store/user/index.ts
./src/features/PWAInstall/index.tsx
 GET / 500 in 2403ms
 GET / 500 in 2404ms
 GET / 500 in 2405ms
^C
(base) liuya@ZBMAC-a623b1996 zg-playgroud-chat % 

(base) liuya@ZBMAC-a623b1996 zg-playgroud-chat % 
(base) liuya@ZBMAC-a623b1996 zg-playgroud-chat % yarn dev 
yarn run v1.22.19
$ next dev -p 3010
  ▲ Next.js 14.2.5
  - Local:        http://localhost:3010
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 2.2s
 ○ Compiling /_not-found ...
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/store/user/slices/modelList/action.ts
./src/store/user/store.ts
./src/store/user/index.ts
./src/features/PWAInstall/index.tsx
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: ENOENT: no such file or directory, rename '/Users/liuya/PycharmProjects/pythonProject/9n_rag_ruigewk/rag_ruige_web/zg-playgroud-chat/.next/cache/webpack/client-development-fallback/0.pack.gz_' -> '/Users/liuya/PycharmProjects/pythonProject/9n_rag_ruigewk/rag_ruige_web/zg-playgroud-chat/.next/cache/webpack/client-development-fallback/0.pack.gz'
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: ENOENT: no such file or directory, rename '/Users/liuya/PycharmProjects/pythonProject/9n_rag_ruigewk/rag_ruige_web/zg-playgroud-chat/.next/cache/webpack/client-development-fallback/0.pack.gz_' -> '/Users/liuya/PycharmProjects/pythonProject/9n_rag_ruigewk/rag_ruige_web/zg-playgroud-chat/.next/cache/webpack/client-development-fallback/0.pack.gz'
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/store/user/slices/modelList/action.ts
./src/store/user/store.ts
./src/store/user/index.ts
./src/features/PWAInstall/index.tsx
 ⨯ node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:buffer
./node_modules/node-fetch/src/index.js
./node_modules/ollama/dist/shared/ollama.7d273fc8.mjs
./node_modules/ollama/dist/browser.mjs
./src/libs/agent-runtime/ollama/index.ts
./src/libs/agent-runtime/index.ts
./src/store/user/slices/modelList/action.ts
./src/store/user/store.ts
./src/store/user/index.ts
./src/features/PWAInstall/index.tsx
 GET / 500 in 1685ms
 GET / 500 in 1686ms
 GET / 500 in 1686ms

### 📷 Recurrence Steps

yarn dev 

### 🚦 Expected Behavior

yarn dev OK

**Comment by liuyaaixxa** [comment]
local dev

**Comment by liuyaaixxa** [comment]
看起来的是ollmajs包导致的这个问题

**Comment by arvinxx** [comment]
已修复 #3453
