### ISSUE TITLE
[Bug] 出现个别字乱码

### ISSUE THREAD

**Issue by Mabisi** [lobehub/lobe-chat#346]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/19968269/4d5b047e-1b0e-420a-a9c8-7310f99b3dfd)

### 📝 补充信息 | Additional Information

用的是azure open ai

**Comment by zandko** [comment]
可否分享下这个问题是如何修复的，我在使用百度文心的时候也遇到了这种问题

**Comment by arvinxx** [comment]
@zandko 参考相应pr
