### ISSUE TITLE
[Bug] 配置腾讯云的COS上传图片出错

### ISSUE THREAD

**Issue by alphandbelt1** [lobehub/lobe-chat#3461]
### 📦 Environment

Other

### 📌 Version

1.9.7

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

本地编译部署。已经使用API验证AK,SK，桶等配置是OK的，不知道问题在哪里。![image](https://github.com/user-attachments/assets/b907fe96-a5a1-42ed-904a-de486d55b165)
![image](https://github.com/user-attachments/assets/91b27bd3-76c7-4771-af2d-5d869cee1086)

**Comment by alphandbelt1** [comment]
ACCESS_CODE这个我直接在.env.local写死了，应该一样的吧？

**Comment by alphandbelt1** [comment]
在界面上更新ACCESS_CODE的时候，又有这个问题了。。。
![image](https://github.com/user-attachments/assets/58701494-41ae-4b23-8787-6d4a87304524)

**Comment by alphandbelt1** [comment]
> NEXT_PUBLIC_S3_DOMAIN

NEXT_PUBLIC_S3_DOMAIN想问下你这个是填的什么呢

**Comment by RidiculousBuffal** [comment]
> > NEXT_PUBLIC_S3_DOMAIN
> 
> NEXT_PUBLIC_S3_DOMAIN想问下你这个是填的什么呢

我填的是腾讯云的对外访问链接,就是 https://*****.cos.ap-shanghai.myqcloud.com

**Comment by RidiculousBuffal** [comment]
> ACCESS_CODE这个我直接在.env.local写死了，应该一样的吧？

可以看一下 #3413 这个issue 我一开始也没有在客户端手动写 然后就提示你这个错误 😭😭😭

**Comment by alphandbelt1** [comment]
> > > NEXT_PUBLIC_S3_DOMAIN
> > 
> > 
> > NEXT_PUBLIC_S3_DOMAIN想问下你这个是填的什么呢
> 
> 我填的是腾讯云的对外访问链接,就是 https://*****.cos.ap-shanghai.myqcloud.com

![image](https://github.com/user-attachments/assets/e1b77ecd-e864-4f1a-8e73-228a7a08918a)
你看下我填的这个，应该就是这样的吧。

**Comment by RidiculousBuffal** [comment]
> > > > NEXT_PUBLIC_S3_DOMAIN
> > > 
> > > 
> > > NEXT_PUBLIC_S3_DOMAIN想问下你这个是填的什么呢
> > 
> > 
> > 我填的是腾讯云的对外访问链接,就是 https://*****.cos.ap-shanghai.myqcloud.com
> 
> ![image](https://private-user-images.githubusercontent.com/81293467/357368973-e1b77ecd-e864-4f1a-8e73-228a7a08918a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQwNTQsIm5iZiI6MTcyMzU0Mzc1NCwicGF0aCI6Ii84MTI5MzQ2Ny8zNTczNjg5NzMtZTFiNzdlY2QtZTg2NC00ZjFhLThlNzMtMjI4YTdhMDg5MThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMDQwZWZhOTUzMzIxZDg3NmQzZGFiZjg4NzgxNWVmODE0NjllMDIyMmUyZTA0NzQ1MGIwNTQ4ODU1ZWVkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U2T0YJluAdpfpU1mkrjJbthMMmIr__52e-CyS6uOAis) 你看下我填的这个，应该就是这样的吧。

完全一致的
![image](https://github.com/user-attachments/assets/afbf7b2a-6bb0-4450-9d9b-341734c3806c)

你的储存桶是最近建的嘛,官网上面说2024.1之后建立的桶要用自定义域名:就是那个NEXT_PUBLIC_S3_DOMAIN
![image](https://github.com/user-attachments/assets/8e0492cf-c9fd-4acb-b37d-58711bf5c1ac)

**Comment by alphandbelt1** [comment]
> > > > > NEXT_PUBLIC_S3_DOMAIN
> > > > 
> > > > 
> > > > NEXT_PUBLIC_S3_DOMAIN想问下你这个是填的什么呢
> > > 
> > > 
> > > 我填的是腾讯云的对外访问链接,就是 https://*****.cos.ap-shanghai.myqcloud.com
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/81293467/357368973-e1b77ecd-e864-4f1a-8e73-228a7a08918a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQwNTQsIm5iZiI6MTcyMzU0Mzc1NCwicGF0aCI6Ii84MTI5MzQ2Ny8zNTczNjg5NzMtZTFiNzdlY2QtZTg2NC00ZjFhLThlNzMtMjI4YTdhMDg5MThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMDQwZWZhOTUzMzIxZDg3NmQzZGFiZjg4NzgxNWVmODE0NjllMDIyMmUyZTA0NzQ1MGIwNTQ4ODU1ZWVkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U2T0YJluAdpfpU1mkrjJbthMMmIr__52e-CyS6uOAis) 你看下我填的这个，应该就是这样的吧。
> 
> 完全一致的 ![image](https://private-user-images.githubusercontent.com/124059108/357369966-afbf7b2a-6bb0-4450-9d9b-341734c3806c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQzNzUsIm5iZiI6MTcyMzU0NDA3NSwicGF0aCI6Ii8xMjQwNTkxMDgvMzU3MzY5OTY2LWFmYmY3YjJhLTZiYjAtNDQ1MC05ZDliLTM0MTczNGMzODA2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMDE0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjI3ZTIxYThhNDMyYWFmNjQwNjhlNGViOGEzNjIwOWEyOTYwNDA5ZTc2YTQyMjQyNmNlOGZkNjUwZTZhOTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.och-cTA_0te-kHY1izLZMcP2CVbJ3C7wbXcKS8GbeJ4)
> 
> 你的储存桶是最近建的嘛,官网上面说2024.1之后建立的桶要用自定义域名:就是那个NEXT_PUBLIC_S3_DOMAIN ![image](https://private-user-images.githubusercontent.com/124059108/357370701-8e0492cf-c9fd-4acb-b37d-58711bf5c1ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQzNzUsIm5iZiI6MTcyMzU0NDA3NSwicGF0aCI6Ii8xMjQwNTkxMDgvMzU3MzcwNzAxLThlMDQ5MmNmLWM5ZmQtNGFjYi1iMzdkLTU4NzExYmY1YzFhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMDE0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTNhZjVkYWQ2MjYwZDVmN2E3ZDYxMzAwNjA0N2UzZjM0Yzk5ZDU3ZGM0YjQzMDY0MWRmZjgwYWRkZDIxNTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SNFd9F68NmwrVmfeB8XxXz6TLB58cbeGpIo3afropf0)

是新建的，那我看看这个

**Comment by alphandbelt1** [comment]
> > > > > > > NEXT_PUBLIC_S3_DOMAIN
> > > > > > 
> > > > > > 
> > > > > > NEXT_PUBLIC_S3_DOMAIN想问下你这个是填的什么呢
> > > > > 
> > > > > 
> > > > > 我填的是腾讯云的对外访问链接,就是 https://*****.cos.ap-shanghai.myqcloud.com
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/81293467/357368973-e1b77ecd-e864-4f1a-8e73-228a7a08918a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQwNTQsIm5iZiI6MTcyMzU0Mzc1NCwicGF0aCI6Ii84MTI5MzQ2Ny8zNTczNjg5NzMtZTFiNzdlY2QtZTg2NC00ZjFhLThlNzMtMjI4YTdhMDg5MThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMDQwZWZhOTUzMzIxZDg3NmQzZGFiZjg4NzgxNWVmODE0NjllMDIyMmUyZTA0NzQ1MGIwNTQ4ODU1ZWVkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U2T0YJluAdpfpU1mkrjJbthMMmIr__52e-CyS6uOAis) 你看下我填的这个，应该就是这样的吧。
> > > 
> > > 
> > > 完全一致的 ![image](https://private-user-images.githubusercontent.com/124059108/357369966-afbf7b2a-6bb0-4450-9d9b-341734c3806c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQzNzUsIm5iZiI6MTcyMzU0NDA3NSwicGF0aCI6Ii8xMjQwNTkxMDgvMzU3MzY5OTY2LWFmYmY3YjJhLTZiYjAtNDQ1MC05ZDliLTM0MTczNGMzODA2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMDE0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjI3ZTIxYThhNDMyYWFmNjQwNjhlNGViOGEzNjIwOWEyOTYwNDA5ZTc2YTQyMjQyNmNlOGZkNjUwZTZhOTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.och-cTA_0te-kHY1izLZMcP2CVbJ3C7wbXcKS8GbeJ4)
> > > 你的储存桶是最近建的嘛,官网上面说2024.1之后建立的桶要用自定义域名:就是那个NEXT_PUBLIC_S3_DOMAIN ![image](https://private-user-images.githubusercontent.com/124059108/357370701-8e0492cf-c9fd-4acb-b37d-58711bf5c1ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQzNzUsIm5iZiI6MTcyMzU0NDA3NSwicGF0aCI6Ii8xMjQwNTkxMDgvMzU3MzcwNzAxLThlMDQ5MmNmLWM5ZmQtNGFjYi1iMzdkLTU4NzExYmY1YzFhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMDE0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTNhZjVkYWQ2MjYwZDVmN2E3ZDYxMzAwNjA0N2UzZjM0Yzk5ZDU3ZGM0YjQzMDY0MWRmZjgwYWRkZDIxNTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SNFd9F68NmwrVmfeB8XxXz6TLB58cbeGpIo3afropf0)
> > 
> > 
> > 是新建的，那我看看这个
> 
> 但是我看你那个问题报的错是invalid key length 是不是key(access code)的长度不够之类的问题

这个是我在界面上填ACCESS-CODE的时候报的错误。

**Comment by alphandbelt1** [comment]
> > > > > > > NEXT_PUBLIC_S3_DOMAIN
> > > > > > 
> > > > > > 
> > > > > > NEXT_PUBLIC_S3_DOMAIN想问下你这个是填的什么呢
> > > > > 
> > > > > 
> > > > > 我填的是腾讯云的对外访问链接,就是 https://*****.cos.ap-shanghai.myqcloud.com
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/81293467/357368973-e1b77ecd-e864-4f1a-8e73-228a7a08918a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQwNTQsIm5iZiI6MTcyMzU0Mzc1NCwicGF0aCI6Ii84MTI5MzQ2Ny8zNTczNjg5NzMtZTFiNzdlY2QtZTg2NC00ZjFhLThlNzMtMjI4YTdhMDg5MThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMDQwZWZhOTUzMzIxZDg3NmQzZGFiZjg4NzgxNWVmODE0NjllMDIyMmUyZTA0NzQ1MGIwNTQ4ODU1ZWVkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U2T0YJluAdpfpU1mkrjJbthMMmIr__52e-CyS6uOAis) 你看下我填的这个，应该就是这样的吧。
> > > 
> > > 
> > > 完全一致的 ![image](https://private-user-images.githubusercontent.com/124059108/357369966-afbf7b2a-6bb0-4450-9d9b-341734c3806c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQzNzUsIm5iZiI6MTcyMzU0NDA3NSwicGF0aCI6Ii8xMjQwNTkxMDgvMzU3MzY5OTY2LWFmYmY3YjJhLTZiYjAtNDQ1MC05ZDliLTM0MTczNGMzODA2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMDE0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjI3ZTIxYThhNDMyYWFmNjQwNjhlNGViOGEzNjIwOWEyOTYwNDA5ZTc2YTQyMjQyNmNlOGZkNjUwZTZhOTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.och-cTA_0te-kHY1izLZMcP2CVbJ3C7wbXcKS8GbeJ4)
> > > 你的储存桶是最近建的嘛,官网上面说2024.1之后建立的桶要用自定义域名:就是那个NEXT_PUBLIC_S3_DOMAIN ![image](https://private-user-images.githubusercontent.com/124059108/357370701-8e0492cf-c9fd-4acb-b37d-58711bf5c1ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDQzNzUsIm5iZiI6MTcyMzU0NDA3NSwicGF0aCI6Ii8xMjQwNTkxMDgvMzU3MzcwNzAxLThlMDQ5MmNmLWM5ZmQtNGFjYi1iMzdkLTU4NzExYmY1YzFhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMDE0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTNhZjVkYWQ2MjYwZDVmN2E3ZDYxMzAwNjA0N2UzZjM0Yzk5ZDU3ZGM0YjQzMDY0MWRmZjgwYWRkZDIxNTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SNFd9F68NmwrVmfeB8XxXz6TLB58cbeGpIo3afropf0)
> > 
> > 
> > 是新建的，那我看看这个
> 
> 但是我看你那个问题报的错是invalid key length 是不是key(access code)的长度不够之类的问题

我又重新试了一下，在cloudfare上也开了对象存储，还是一样的问题。后面把环境变量里面的ACCESS_CODE注释了，又是另外的报错了。估计还是哪里逻辑判断有问题，等他们下周发布新版本看再吧。

**Comment by SAnBlog** [comment]
看来数据库版本问题还是不少,等一个稳定版本
