### ISSUE TITLE
[Bug] Browser slowdown when generating texts

### ISSUE THREAD

**Issue by Zaurio20** [lobehub/lobe-chat#3469]
### 📦 Environment

Official Preview

### 📌 Version

1.9.8

### 💻 Operating System

Windows

### 🌐 Browser

Other

### 🐛 Bug Description

The browser slows down when generating the response and consumes resources. Additionally, if the browser is not always visible on the screen, it will not generate the texts until clicked, and it will do so slowly.

### 📷 Recurrence Steps

Open a tab with Lobe-chat and ask a question.

### 🚦 Expected Behavior

It shouldn't consume computer resources or slow down when generating text.

**Comment by arvinxx** [comment]
I think it's fixed in the recent version. Could you try again?
