### ISSUE TITLE
[Bug] Issues with Media Uploads for Gemini and Claude

### ISSUE THREAD

**Issue by samkurd** [lobehub/lobe-chat#3473]
### 📦 Environment

Vercel

### 📌 Version

v1.10.1

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

Hello,

I have been experiencing issues with media uploads in the lobe-chat repository. I have deployed the application using Vercel and have set up the database using Neon. Additionally, I am using Cloudflare for DNS handling.

Details:

Deployment Environment:

Platform: Vercel
Database: Neon
DNS Handling: Cloudflare
Issue Description:

Previous Behavior: Before the v1.10.1 update, there were errors with media uploads across all language models.
Current Behavior: After updating to v1.10.1, media uploads work fine with OpenAI. However, I am encountering errors when using the Gemini and Claude language models.
Error Messages:

Gemini:

"**Error requesting Google service, please troubleshoot or retry based on the following information**"

`{
  "error": {
    "message": "currently we don't support image url: https://mydomain.com/files/478784/8e3cec19-9eae-442d-91b4-4791cc58f4bb.jpg"
  },
  "provider": "google"
}`

Claude:

"**Error requesting Anthropic service, please troubleshoot or retry based on the following information**"

`{
  "error": {
    "error": {
      "type": "error",
      "error": {
        "type": "invalid_request_error",
        "message": "messages.0.content.1.image.source.base64.media_type: Input should be 'image/jpeg', 'image/png', 'image/gif' or 'image/webp'"
      }
    },
    "status": 400,
    "headers": {
      "via": "1.1 google",
      "date": "Wed, 14 Aug 2024 07:34:00 GMT",
      "connection": "keep-alive",
      "request-id": "req_01LzcGdawx4398ndPL78KsKg",
      "content-type": "application/json",
      "x-robots-tag": "none",
      "content-length": "193",
      "x-should-retry": "false",
      "x-cloud-trace-context": "6a3fcc084a2ee937518088998956b28c"
    }
  },
  "endpoint": "https://api.anthropic.com",
  "provider": "anthropic"
}`

This is the error I get on my Browser console:
`https://mydomain.com/api/chat/google 471`

### 📷 Recurrence Steps

1. Deploy the lobe-chat application using **Vercel**.
2. Set up the database using **Neon**.
3. Configure DNS handling with **Cloudflare** and **R2** Storage.
4. Attempt to upload media using the Gemini and Claude language models.

### 🚦 Expected Behavior

Media uploads should work seamlessly across all language models, including Gemini and Claude.

**Comment by samkurd** [comment]
#3370 seems to address only Gemini, but I'm facing issues with Claude too. Does that fix also solves the issue with Claude?

**Comment by adminewacc** [comment]
trying to solve this problem too, if a can, i will say here how

**Comment by samkurd** [comment]
I'm looking forward to your solution, thanks @adminewacc

**Comment by adminewacc** [comment]
almost solved

**Comment by samkurd** [comment]
That's a great news

**Comment by adminewacc** [comment]
solved, i later will try to resquest it

**Comment by adminewacc** [comment]
tommorrow i solved it but i forgot to post here lol

**Comment by samkurd** [comment]
Oh that's amazing, thanks @adminewacc

**Comment by samkurd** [comment]
unfortunately the error is still available and unresolved.

**Comment by arvinxx** [comment]
@samkurd please share more info about the error you meet.

**Comment by samkurd** [comment]
This is the error I'm facing:

> Error requesting Anthropic service, please troubleshoot or retry based on the following information

> {
  "error": {
    "error": {
      "type": "error",
      "error": {
        "type": "invalid_request_error",
        "message": "messages.0.content.1.image.source.base64.data: The image was specified using the image/png media type, but does not appear to be a valid png image"
      }
    },
    "status": 400,
    "headers": {
      "via": "1.1 google",
      "date": "Tue, 10 Sep 2024 14:53:31 GMT",
      "connection": "keep-alive",
      "request-id": "req_019vWkbWd7H9i6wDvLcRbfLG",
      "content-type": "application/json",
      "x-robots-tag": "none",
      "content-length": "216",
      "x-should-retry": "false",
      "x-cloud-trace-context": "7b9beefcef835dcdec7c555695c927e1"
    },
    "request_id": "req_019vWkbWd7H9i6wDvLcRbfLG"
  },
  "endpoint": "https://api.anthropic.com",
  "provider": "anthropic"
}

![Screenshot 2024-09-10 170217](https://github.com/user-attachments/assets/934bb16c-c59d-4bc7-9aba-f9cb19ababfe)

**Comment by samkurd** [comment]
so I did a little digging, it only accepts png files and in my tests no other image format is supported.

**Comment by samkurd** [comment]
all fixed and working with OpenAI, Gemini and Claude.

**Comment by ous50** [comment]
Is it possible to adapt this method to all of the model providers? I have built an One-API server, from which I may use Claude, Gemini, ChatGPT, etc. by simply configuring the OpenAI's API. When I was using Gemini with OpenAI config, it just returns:

<img width="856" alt="Screenshot 2024-09-15 at 12 37 37 AM" src="https://github.com/user-attachments/assets/62337809-1513-47a4-9f64-13be442acc2a">


> {
  "error": {
    "code": "image_url_invalid",
    "type": "one_hub_error",
    "message": "请求上游地址失败 (request id: 202409150736377660162153tPnPuIK)"
  },
  "endpoint": "https://www/v1",
  "provider": "openai"
} 

and with `google` provider it works perfectly:

<img width="863" alt="Screenshot 2024-09-15 at 12 38 48 AM" src="https://github.com/user-attachments/assets/cb5de7e3-c123-403d-b41c-b5fd815ac55e">
