### ISSUE TITLE
[Request] 优化S3对已删除文件的存储管理

### ISSUE THREAD

**Issue by ykangw** [lobehub/lobe-chat#3476]
### 🥰 需求描述

在用户对话框中上传图片时，该图片会被上传至S3存储。然而，如果用户在发送前删除了这张图片，S3中的对应文件并不会被自动删除。由于该图片在LobeChat用户端并不显示，用户无法手动从S3中删除它，导致这些文件会永久保留在S3中，从而造成存储资源的浪费。

### 🧐 解决方案

建议在用户删除上传的图片（以及未来可能支持的文件类型）时，能够同步删除S3中的相应存储文件。

**Comment by arvinxx** [comment]
已支持：https://github.com/lobehub/lobe-chat/pull/3487
