### ISSUE TITLE
[Request]  SiliconCloud 添加 API 代理地址

### ISSUE THREAD

**Issue by Borber** [lobehub/lobe-chat#3483]
### 🥰 需求描述

像 openai / gemini 一样, 让  SiliconCloud 也支持 api 代理地址设置

### 🧐 解决方案

已有方案拓展

**Comment by arvinxx** [comment]
为啥？

**Comment by Borber** [comment]
> 为啥？

网络环境问题, 需要自己代理一下过去 😥

**Comment by Borber** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > Why?
> 
> There is a problem with the network environment. You need to deal with it yourself. 😥

The translation has a problem, I mean I nead proxy the official api to use

**Comment by arvinxx** [comment]
@Borber 如果是docker 代理的问题，是不是可以用 PROXY_URL ？ 还是说你的网络代理问题是另外的问题？能详细展开说下吗

**Comment by Borber** [comment]
> @Borber 如果是docker 代理的问题，是不是可以用 PROXY_URL ？ 还是说你的网络代理问题是另外的问题？能详细展开说下吗

就是我自己网络的问题, 目前只能通过部署一个公网代理服务来转发到对应地址,

**Comment by arvinxx** [comment]
@sxjeru 来帮忙看看？

**Comment by sxjeru** [comment]
应该可以仿照 groq 来便捷添加类似功能，已加入日程。
