### ISSUE TITLE
实时效果预览功能

### ISSUE THREAD

**Issue by Geek-Bob** [lobehub/lobe-chat#3486]
### 🥰 需求描述

实时效果预览功能。这个特性将允许用户实时预览他们的代码，而无需离开编辑器。
作为参考，我想从Claude 3.5创新的“Artifacts”功能中汲取灵感，该功能提供了超强大的实时交互能力

### 🧐 解决方案

代码预览功能。这个特性将允许用户实时预览他们的代码，而无需离开编辑器。
作为参考，我想从Claude 3.5创新的“Artifacts”功能中汲取灵感，该功能提供了超强大的实时交互能力

### 📝 补充信息

此功能的主要优点包括:
提高生产力:用户可以快速测试和迭代他们的代码，减少手动调试的需要，节省时间。
增强的准确性:实时预览使用户能够及早发现错误和不一致，从而生成更高质量的代码。
提高用户满意度:通过提供无缝的交互式编码体验，我们可以提高用户粘性和留存率。
谢谢你考虑我的建议。

**Comment by arvinxx** [comment]
duplicate of #2981

**Comment by Geek-Bob** [comment]
Will it be released in the next version?
