### ISSUE TITLE
[Bug] 保存为话题快捷键在 Mac 上不生效

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#349]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

保存为话题快捷键在 Mac 上不生效

<img width="303" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/317ca964-3877-441e-8f72-131059e22da5">

**Comment by Asuka109** [comment]
It appears that pressing `Opt+N` triggers a dead key, causing the `key` field to not match with `N`. Using the `code` field instead may solve this issue.
![image](https://github.com/lobehub/lobe-chat/assets/18379948/12a8b518-416f-4f69-acca-1d8c2c8de626)

**Comment by canisminor1990** [comment]
@arvinxx 诶 还存在这个问题么？我这边测试是好的🤔

**Comment by arvinxx** [comment]
> 还存在这个问题么？我这边测试是好的🤔

你在激活输入框的时候试试看，是不生效的
