### ISSUE TITLE
[Bug] LOBEHUB无法在new-api中带令牌直接进入，需要手动复制令牌

### ISSUE THREAD

**Issue by AthanaL** [lobehub/lobe-chat#3490]
### 📦 部署环境

Docker

### 📌 软件版本

最新

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

LOBEHUB无法在new-api中带令牌直接进入，需要复制令牌，其他chatgpt-next等可以。
在“运营设置”中填入了你自己的lobechat，然后在令牌页面直接点聊天，lobechat没有自动填入对应令牌
![image](https://github.com/user-attachments/assets/b873dacb-46ae-4b0d-b31e-92be08903924)
![image](https://github.com/user-attachments/assets/ab5fc09a-b577-45b3-9c34-9d227389d3f9)

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/issues/3437#issuecomment-2282831314
