### ISSUE TITLE
[Bug] 助手头像设置出错

### ISSUE THREAD

**Issue by Borber** [lobehub/lobe-chat#3494]
### 📦 Environment

Docker

### 📌 Version

v1.11.1

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

设置助手头像时点击无效

### 📷 Recurrence Steps

直接点击:
![new](https://github.com/user-attachments/assets/87cbd4a7-f666-488a-bc3c-2690c7e06c43)

通过 cvim 插件模拟点击:
![new_a](https://github.com/user-attachments/assets/01a65a2e-cd9f-4266-ba35-b59c57a517d0)

### 🚦 Expected Behavior

正常设置

### 📝 Additional Information

我看了一下导出配置, 头像直接时字符串, 然后有时候 AI 生成的头像是文字, 就直接设置成文字而非图标了, 感觉也有点问题 我就不具体截图了, 你直接尝试修改头像字段字符串值就能复现了

**Comment by syhien** [comment]
我也遇到了同样的问题，我的解决方案是临时在prompt里加一句“你的形象是xx（描述emoji）”然后点击魔术棒生成头像

**Comment by Borber** [comment]
> 我也遇到了同样的问题，我的解决方案是临时在prompt里加一句“你的形象是xx（描述emoji）”然后点击魔术棒生成头像

🤣与到这种问题直接提 issue啦

**Comment by arvinxx** [comment]
已修复
