### ISSUE TITLE
[Bug] 使用官方镜像database版本时，存储使用minio时的设置问题

### ISSUE THREAD

**Issue by Luxf01** [lobehub/lobe-chat#3503]
### 📦 Environment

Docker

### 📌 Version

1.11.3

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

nginx配置信息：
f.abc.com   映射到  minio的9000端口，并配置了正规的ssl证书
lobe.abc.com 映射到 lobe-char-database的3210端口，并将/test-chat/ 代理到minio的9000端口

在使用minio做为图片存储服务时，配置如下：
lobe-chat.env
ACCESS_CODE=xxxxxxxxxxxxxxxxxxx
S3_ACCESS_KEY_ID=arUeIxxx8iSdjc5d
S3_SECRET_ACCESS_KEY=l7KhAFBEvuxxxxxxkL3nX2SIpza7JpSY
S3_ENDPOINT=https://f.abc.com
S3_BUCKET=test-chat
NEXT_PUBLIC_S3_DOMAIN=https://lobe.abc.com/test-chat/

在上传图片时，浏览器端报错：
![image](https://github.com/user-attachments/assets/79bad184-0034-4bbf-a20a-8ba82896ac79)
浏览器console信息：
PUT https://test-chat.f.abc.com/files/478877/9864418f-cbb6-49f5-8220-25e2091263b5.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=arUeIaO18iSdjc5d%2F20240818%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240818T043150Z&X-Amz-Expires=3600&X-Amz-Signature=202aee93277ce5d8baa09eeba4f6945f17b6cb9cc9f2facc55d399bfb9714120&X-Amz-SignedHeaders=host&x-amz-acl=public-read&x-id=PutObject net::ERR_CERT_COMMON_NAME_INVALID
浏览器network信息：
Request URL: https://lobe.abc.com/trpc/edge/upload.createS3PreSignedUrl?batch=1
Request Method: POST
Status Code: 200 OK
Remote Address: 127.0.0.1:23457
Referrer Policy: strict-origin-when-cross-origin

Request URL: https://test-chat.f.abc.com/files/478877/9864418f-cbb6-49f5-8220-25e2091263b5.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=arUeIaO18iSdjc5d%2F20240818%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240818T043150Z&X-Amz-Expires=3600&X-Amz-Signature=202aee93277ce5d8baa09eeba4f6945f17b6cb9cc9f2facc55d399bfb9714120&X-Amz-SignedHeaders=host&x-amz-acl=public-read&x-id=PutObject
Referrer Policy: strict-origin-when-cross-origin

补充：在以上信息中，S3_ENDPOINT设置为域名时，S3_BUCKET值会跑到请求域名的前边，导致无对应域名解析及ssl证书错误；当换成内网IP或外网IP直接时，url拼接正常（如：https://192.168.0.100/test-chat/files/478877/9864418f-cbb6-49f5-8220-25e2091263b5.png....）,但是S3_ENDPOINT不能使用http，容器日志会报错。

**Comment by arvinxx** [comment]
重复 https://github.com/lobehub/lobe-chat/issues/3413#issuecomment-2282670048
