### ISSUE TITLE
[Request] 上传文档解析的功能上线了吗

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#3506]
### 🥰 需求描述

上传文档解析的功能上线了吗

### 🧐 解决方案

上传文档解析的功能上线了吗

### 📝 补充信息

上传文档解析的功能上线了吗

**Comment by sxjeru** [comment]
#3487

**Comment by zhangleijun111** [comment]
> #3487

如何部署有吗，我还是试用最新的docker镜像的  docker container  run -d -p 3210:3210  -e ENABLED_OPENAI=0  -e  ENABLED_OLLAMA=0 --restart=always  -e ZHIPU_API_KEY=ddf469a2bcf803222e61670df5691119.PGEcQ   --name lobe-chat  registry.us-west-1.aliyuncs.com/jg-images/lobe-chat:latest我看没有上传文档的按键

**Comment by sxjeru** [comment]
目前还没上线，等上面提到的 pr 合并后再看。

**Comment by zhangleijun111** [comment]
> 目前还没上线，等上面提到的 pr 合并后再看。

我想呢，我更新到最新版本了，那以后是要两个镜像结合才行是吧

**Comment by arvinxx** [comment]
已在 https://github.com/lobehub/lobe-chat/releases/tag/v1.12.0 上线
