### ISSUE TITLE
[Request] 添加快捷按钮，切换是否渲染为markdown格式，避免代码中的 # 注释被渲染为标题

### ISSUE THREAD

**Issue by GuoJiaxing1997** [lobehub/lobe-chat#3507]
### 🥰 Feature Description

如图，尤其是在输入很多带有#注释的代码的时候，观感比较差，不利于阅读
![示例](https://github.com/user-attachments/assets/0202fa58-18a9-4d19-97bc-aec4fb94d679)

### 🧐 Proposed Solution

添加快捷按钮，切换是否渲染为markdown格式，避免代码中的 # 注释被渲染为标题

**Comment by sxjeru** [comment]
目前可以按“编辑”按钮查看未渲染的原文。

一般大模型输出的结果不会出现此类问题，可以考虑添加一个选项，允许用户选择不渲染 `用户发送/大模型回复/全部` 的消息。

**Comment by arvinxx** [comment]
duplicate of #3858
