### ISSUE TITLE
[Request] 是否可以支持GLM4_long模型

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#3510]
### 🥰 需求描述

是否可以支持GLM4_long模型

### 🧐 解决方案

是否可以支持GLM4_long模型

### 📝 补充信息

是否可以支持GLM4_long模型

**Comment by sxjeru** [comment]
老哥提问前可以先看看 Pull requests 版块。

#3509

**Comment by zhangleijun111** [comment]
> > 机器人检测到问题正文的语言不是英语，并自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> 在提出问题之前，请查看 Pull requests 部分。
> 
> #3509
我看看最新版本的lobechat还是无法调用long这个模型

**Comment by sxjeru** [comment]
等提到的 pr 合并，这个 issue 会自动关闭，然后 bot 会发送 release 消息，到那时再更新 lobechat 就可以了。

**Comment by zhangleijun111** [comment]
> > 机器人检测到问题正文的语言不是英语，并自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> 当提到的 PR 合并时，该问题将自动关闭，然后机器人将发送发布消息。届时，只需更新 lobechat 即可。

谢谢大神，那问下PR合并文档大概这周可以完成

> 等提到的 PR 合并，这个 Issue 会自动关闭，然后 bot 会发送 release 消息，到那时再更新 lobechat 就可以了。

谢谢大神，那问下PR合并文档大概这周可以完成????
