### ISSUE TITLE
[Bug] Drag PDF file to chatbox, it's not uploaded

### ISSUE THREAD

**Issue by iYueCode** [lobehub/lobe-chat#3511]
### 📦 Environment

Vercel

### 📌 Version

v1.11.7

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

Drag a pdf file to chatbox, it's not uploaded, or triggered any errors.

### 🚦 Expected Behavior

PDF and DOCX files should be uploaded and parsed, just like images

**Comment by sxjeru** [comment]
Please wait for the #3487 to complete and merge.

**Comment by arvinxx** [comment]
supported in https://github.com/lobehub/lobe-chat/releases/tag/v1.12.0
