### ISSUE TITLE
[Bug] 自动话题重命名在非 OpenAI 部署中默认工作不正常，需要手动选成别的 Azure 模型再选回才能正常工作

### ISSUE THREAD

**Issue by YearsAhead** [lobehub/lobe-chat#3513]
### 📦 部署环境

Vercel

### 📌 软件版本

v1.11.7

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

我的部署中没有配置 OpenAI 本身的 Key，只使用 Azure OpenAI Service，新用户登录后默认线上的“系统助手”的模型都是正确的，但实际自动话题重命名的请求还是走 OpenAI 的，且后台会看到报错。直到去手动选成别的 Azure 模型再选回，这个自动话题重命名才会正常工作。

**Comment by potato1949** [comment]
@YearsAhead 让你参考下我的。
DEFAULT_AGENT_CONFIG=model=deepseek-chat;provider=deepseek;chatConfig.enableHistoryCount=true;chatConfig.historyCount=5
SYSTEM_AGENT=topic=deepseek/deepseek-chat,translation=deepseek/deepseek-chat,agentMeta=deepseek/deepseek-chat
