### ISSUE TITLE
[Request] 预设 agents 希望支持多条消息构建 prompt，当前过于单一

### ISSUE THREAD

**Issue by taoshantun** [lobehub/lobe-chat#3515]
### 🥰 需求描述

构建预设 prompt 的 agent 的时候，只支持 system prompt，而且据 openai 文档所描述，system prompt 控制力不强且不稳定 ——
![image](https://github.com/user-attachments/assets/5a23c77e-4a46-4120-be68-f320ffdb8970)

### 🧐 解决方案

希望能像 next chat 那样支持多条消息——

![image](https://github.com/user-attachments/assets/74fde371-50c1-436e-924d-6f5d24225497)

**Comment by lowspace** [comment]
有 workaround，复制已保存的聊天记录就能直接用了。

**Comment by arvinxx** [comment]
重复 #336
