### ISSUE TITLE
[Bug] Claude客户端请求错误

### ISSUE THREAD

**Issue by lamlados** [lobehub/lobe-chat#3522]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Other Linux

### 🌐 Browser

Edge

### 🐛 Bug Description

我使用了这个 [repo](https://github.com/cg-dot/vertexai-cf-workers) 去代理GCP vertex ai的claude， 提供了自定义的 `ANTHROPIC_API_KEY` 和 `ANTHROPIC_PROXY_URL`，服务端测试可以访问，客户端会报错：
```
{
  "error": {
    "cause": {
      "cause": {}
    }
  },
  "endpoint": "https://xxx.workers.dev/",
  "provider": "anthropic"
}
```

**Comment by arvinxx** [comment]
重复 https://github.com/lobehub/lobe-chat/discussions/2442
