### ISSUE TITLE
最新版 移动端UI错误 所有链接都有下划线

### ISSUE THREAD

**Issue by liuchao0807** [lobehub/lobe-chat#3544]
### 📦 Environment

Docker

### 📌 Version

1.12.2

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

UI错误，所有链接都有下划线，如图
![IMG_6206](https://github.com/user-attachments/assets/82396f7e-7eb3-4568-b0b7-da74b985e8b0)

### 📷 Recurrence Steps

必现

**Comment by arvinxx** [comment]
刷新下页面呢？我这边没法复现

**Comment by liuchao0807** [comment]
> 刷新下页面呢？我这边没法复现

刷新了，还是存在。 你是安卓还是iOS，和这个有关系吗

**Comment by arvinxx** [comment]
@liuchao0807 可以 Discord 上私戳我发下你的部署地址，我点开看看

**Comment by SpeedupMaster** [comment]
我也遇到了
![Snipaste_2024-08-22_13-17-35](https://github.com/user-attachments/assets/70450867-3945-4ba3-875c-f4e4004dae89)

**Comment by liuchao0807** [comment]
> @liuchao0807 可以 Discord 上私戳我发下你的部署地址，我点开看看

加你了，另外我部署的是database版本

**Comment by 80imike** [comment]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/a9541872-4121-43b2-8f88-035d413f4766">

database  1.12.2 版本的确有这个问题，我在 pc 上也有这个问题

**Comment by arvinxx** [comment]
咦 这么多人遇到了吗。我看看是啥原因

**Comment by dalefengs** [comment]
客户端和服务端都遇到这个问题了

**Comment by ZeroDeng01** [comment]
同样的问题

**Comment by 80imike** [comment]
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/c5fca6b4-2963-4eed-8c9b-c974bd81e146">


应该是代码哪里改错了 设置中的链接也有这种情况

**Comment by alphandbelt1** [comment]
> > 刷新下页面呢？我这边没法复现
> 
> 刷新了，还是存在。 你是安卓还是iOS，和这个有关系吗。 我是iOS

我在edge上也是这样，换谷歌又可以了。

**Comment by arvinxx** [comment]
感觉可能是 next 发布了 14.2.6 的关系，我先试试锁到 14.2.5 : https://github.com/lobehub/lobe-chat/pull/3540/commits/2a5e14520a753c0c28cbd0eb48785fb5f5fcef30

**Comment by dalefengs** [comment]
> 感觉可能是 next 发布了 14.2.6 的关系，我先试试锁到 14.2.5 : [2a5e145](https://github.com/lobehub/lobe-chat/commit/2a5e14520a753c0c28cbd0eb48785fb5f5fcef30)

docker 镜像更新v1.12.3  还存在此问题。 尝试更换浏览器、清缓存

![image](https://github.com/user-attachments/assets/337e7f3c-6a50-4cff-b5cd-67b09a310174)

**Comment by bentwnghk** [comment]
> > 感觉可能是 next 发布了 14.2.6 的关系，我先试试锁到 14.2.5 : [2a5e145](https://github.com/lobehub/lobe-chat/commit/2a5e14520a753c0c28cbd0eb48785fb5f5fcef30)
> 
> docker 镜像更新v1.12.3 还存在此问题。 尝试更换浏览器、清缓存
> 
> ![image](https://private-user-images.githubusercontent.com/58434904/360347618-337e7f3c-6a50-4cff-b5cd-67b09a310174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTY0NjksIm5iZiI6MTcyNDMxNjE2OSwicGF0aCI6Ii81ODQzNDkwNC8zNjAzNDc2MTgtMzM3ZTdmM2MtNmE1MC00Y2ZmLWI1Y2QtNjdiMDlhMzEwMTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4NDI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MzVjOWI1OTQ3MDg1NTY5N2I3NjUyZWJlNDZmNGJmNDc1NWNkZTgwZjFiYzNhMGFlODZlYjI2MzViMzUzN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4cnYRpxLdEbO4LjgwD8aCb8Zl_RkKvXURS0QpUFE-DA)

True, the issue is still there!

**Comment by 534002646** [comment]
> 感觉可能是 next 发布了 14.2.6 的关系，我先试试锁到 14.2.5 : [2a5e145](https://github.com/lobehub/lobe-chat/commit/2a5e14520a753c0c28cbd0eb48785fb5f5fcef30)

![image](https://github.com/user-attachments/assets/db0e4054-4ca8-4a30-b2ac-f02a58988e6d)
嘻嘻

**Comment by liuchao0807** [comment]
问题还存在😳

**Comment by arvinxx** [comment]
破案了： antd 的底层依赖 stylis 变更。 https://github.com/thysultan/stylis/issues/333
