### ISSUE TITLE
[Bug] 上传文件分块失败

### ISSUE THREAD

**Issue by jedy** [lobehub/lobe-chat#3545]
### 📦 部署环境

Docker

### 📌 软件版本

1.12.2

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

上传文件之后，服务器日志显示如下，页面一直显示分块中
![image](https://github.com/user-attachments/assets/4a0688da-b2a2-4846-aa33-510eb9891b47)
![image](https://github.com/user-attachments/assets/def9be86-1e0a-4d9a-a97f-7984a8c2f0b1)
如果这时点文件右上角的图标删除文件，会一直弹框
![image](https://github.com/user-attachments/assets/5ea3f482-268f-4880-92df-ce2676c160e5)

**Comment by jedy** [comment]
没问题了。部署的时候加了一层内部认证，导致server的rpc调用失败。

**Comment by 370738206** [comment]
@jedy 请问可以详细说明一下解决方法吗？我也遇到了这个问题

**Comment by ji-jinlong** [comment]
@jedy 您好, 能分享一下解决办法吗? 我遇到了分块失败的问题, 不知道是不是同一个原因https://github.com/lobehub/lobe-chat/discussions/3560

**Comment by ji-jinlong** [comment]
![image](https://github.com/user-attachments/assets/6ff8aae8-897c-4cfc-a837-5b46ff957981)
似乎是一样的原因, 请教大佬如何解决

**Comment by jedy** [comment]
@ji-jinlong server的程序上需要访问APP_URL，如果这个url配置了其他认证，要直接通过server的请求

**Comment by ji-jinlong** [comment]
> @ji-jinlong server的程序上需要访问APP_URL，如果这个url配置了其他认证，要直接通过server的请求

请恕我愚蠢, 我本身只能算半个程序猿, 且对这些都不太了解, 只是按照教程部署了vercel数据库,vercel服务端,clerk的认证和github的授权登录,以及CF的R2桶. 实在不了解您说的这个认证

**Comment by jedy** [comment]
你的网站是对外公开的吗，直接访问的时候需不需要先登录才能看到lobe的页面？如果是无法直接访问的，就需要配置让server的ip能够不登录直接访问。

**Comment by ji-jinlong** [comment]
> 你的网站是对外公开的吗，直接访问的时候需不需要先登录才能看到lobe的页面？如果是无法直接访问的，就需要配置让server的ip能够不登录直接访问。

我的网站会对外公开给我朋友访问. 配置了clerk登录. 不登录能够看到lobe页面, 但是无法使用, 需要登录才能使用. 点击文件或者头像回跳转到clerk登录界面.
不登录直接问会显示这样:
![image](https://github.com/user-attachments/assets/ac53b21f-32c9-4ae6-9888-0bc0978cc4e0)
这是我的网址, 或许有助于您帮我答疑: t.ccoc.cc

**Comment by jedy** [comment]
你配置的APP_URL是什么？

**Comment by ji-jinlong** [comment]
> 你配置的APP_URL是什么？

我不太确定您说的APP_URL指的是哪一步的变量. 在我配置过程中除了lobe主域名https://t.ccoc.cc和https://s3-for-lobechat.ccoc.cc就只有clerk过程中配置的DNS了

**Comment by jedy** [comment]
https://github.com/lobehub/lobe-chat/issues/3527

这里写了需要配置APP_URL

**Comment by ji-jinlong** [comment]
> #3527
> 
> 这里写了需要配置APP_URL

感谢领细心且耐心的指导, 因为教程中没有这个参数所以我没有添加. 刚加上了, 现在成功分块了. 只是,,,,现在向量化失败

猜测可能是我用的转发不支持, 不过这个我在MaxKB中是成功了的, 不知道二者有啥区别. 

```
Uncaught (in promise) TRPCClientError
    at s.from (73920-2cd3d6dba97afb1d.js:1:878)
    at 73920-2cd3d6dba97afb1d.js:1:7395
```

```json
i [TRPCError]
    at a (/var/task/.next/server/chunks/90525.js:1:1011)
    ... 6 lines matching cause stack trace ...
    at async r (/var/task/.next/server/chunks/90525.js:1:6057)
    at async /var/task/.next/server/chunks/52408.js:1:7252
    at async Promise.all (index 0) {
  code: 'INTERNAL_SERVER_ERROR',
  [cause]: o [Error]
      at /var/task/.next/server/chunks/90525.js:1:1322
      at new i (/var/task/.next/server/chunks/90525.js:1:1364)
      at a (/var/task/.next/server/chunks/90525.js:1:1011)
      at t (/var/task/.next/server/chunks/90525.js:1:6033)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async t (/var/task/.next/server/chunks/90525.js:1:5715)
      at async t (/var/task/.next/server/chunks/90525.js:1:5715)
      at async t (/var/task/.next/server/chunks/90525.js:1:5715)
      at async t (/var/task/.next/server/chunks/90525.js:1:5715)
      at async r (/var/task/.next/server/chunks/90525.js:1:6057) {
    endpoint: 'https://api.chatanywhere.***.cn/',
    error: {
      headers: [Object],
      stack: 'Error: 404 <html>\n' +
        '<head><title>404 Not Found</title></head>\n' +
        '<body>\n' +
        '<center><h1>404 Not Found</h1></center>\n' +
        '<hr><center>nginx</center>\n' +
        '</body>\n' +
        '</html>\n' +
        '    at rt.generate (/var/task/.next/server/chunks/96903.js:219:67341)\n' +
        '    at nf.makeStatusError (/var/task/.next/server/chunks/96903.js:219:59038)\n' +
        '    at nf.makeRequest (/var/task/.next/server/chunks/96903.js:219:59961)\n' +
        '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
        '    at async Object.embeddings (/var/task/.next/server/chunks/43054.js:9:3533)\n' +
        '    at async /var/task/.next/server/chunks/1701.js:5:25922\n' +
        '    at async u.middlewares (/var/task/.next/server/chunks/90525.js:1:5409)\n' +
        '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)\n' +
        '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)\n' +
        '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)',
      status: 404
    },
    errorType: 'ProviderBizError',
    provider: 'openai'
  }
}
```

**Comment by RidiculousBuffal** [comment]
> > #3527
> > 这里写了需要配置APP_URL
> 
> 感谢领细心且耐心的指导, 因为教程中没有这个参数所以我没有添加. 刚加上了, 现在成功分块了. 只是,,,,现在向量化失败
> 
> 猜测可能是我用的转发不支持, 不过这个我在MaxKB中是成功了的, 不知道二者有啥区别.
> 
> ```
> Uncaught (in promise) TRPCClientError
>     at s.from (73920-2cd3d6dba97afb1d.js:1:878)
>     at 73920-2cd3d6dba97afb1d.js:1:7395
> ```
> 
> ```json
> i [TRPCError]
>     at a (/var/task/.next/server/chunks/90525.js:1:1011)
>     ... 6 lines matching cause stack trace ...
>     at async r (/var/task/.next/server/chunks/90525.js:1:6057)
>     at async /var/task/.next/server/chunks/52408.js:1:7252
>     at async Promise.all (index 0) {
>   code: 'INTERNAL_SERVER_ERROR',
>   [cause]: o [Error]
>       at /var/task/.next/server/chunks/90525.js:1:1322
>       at new i (/var/task/.next/server/chunks/90525.js:1:1364)
>       at a (/var/task/.next/server/chunks/90525.js:1:1011)
>       at t (/var/task/.next/server/chunks/90525.js:1:6033)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async r (/var/task/.next/server/chunks/90525.js:1:6057) {
>     endpoint: 'https://api.chatanywhere.***.cn/',
>     error: {
>       headers: [Object],
>       stack: 'Error: 404 <html>\n' +
>         '<head><title>404 Not Found</title></head>\n' +
>         '<body>\n' +
>         '<center><h1>404 Not Found</h1></center>\n' +
>         '<hr><center>nginx</center>\n' +
>         '</body>\n' +
>         '</html>\n' +
>         '    at rt.generate (/var/task/.next/server/chunks/96903.js:219:67341)\n' +
>         '    at nf.makeStatusError (/var/task/.next/server/chunks/96903.js:219:59038)\n' +
>         '    at nf.makeRequest (/var/task/.next/server/chunks/96903.js:219:59961)\n' +
>         '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
>         '    at async Object.embeddings (/var/task/.next/server/chunks/43054.js:9:3533)\n' +
>         '    at async /var/task/.next/server/chunks/1701.js:5:25922\n' +
>         '    at async u.middlewares (/var/task/.next/server/chunks/90525.js:1:5409)\n' +
>         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)\n' +
>         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)\n' +
>         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)',
>       status: 404
>     },
>     errorType: 'ProviderBizError',
>     provider: 'openai'
>   }
> }
> ```

maxKB如果不单独配置的话使用的应该是本地的向量化模型shibing624_text2vec-base-chinese
![image](https://github.com/user-attachments/assets/077de685-9f2b-4c7a-818a-2077a27a6056)

**Comment by arvinxx** [comment]
> > #3527
> > 这里写了需要配置APP_URL
> 
> 感谢领细心且耐心的指导, 因为教程中没有这个参数所以我没有添加. 刚加上了, 现在成功分块了. 只是,,,,现在向量化失败
> 
> 猜测可能是我用的转发不支持, 不过这个我在MaxKB中是成功了的, 不知道二者有啥区别.
> 
> ```
> Uncaught (in promise) TRPCClientError
>     at s.from (73920-2cd3d6dba97afb1d.js:1:878)
>     at 73920-2cd3d6dba97afb1d.js:1:7395
> ```
> 
> ```json
> i [TRPCError]
>     at a (/var/task/.next/server/chunks/90525.js:1:1011)
>     ... 6 lines matching cause stack trace ...
>     at async r (/var/task/.next/server/chunks/90525.js:1:6057)
>     at async /var/task/.next/server/chunks/52408.js:1:7252
>     at async Promise.all (index 0) {
>   code: 'INTERNAL_SERVER_ERROR',
>   [cause]: o [Error]
>       at /var/task/.next/server/chunks/90525.js:1:1322
>       at new i (/var/task/.next/server/chunks/90525.js:1:1364)
>       at a (/var/task/.next/server/chunks/90525.js:1:1011)
>       at t (/var/task/.next/server/chunks/90525.js:1:6033)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async r (/var/task/.next/server/chunks/90525.js:1:6057) {
>     endpoint: 'https://api.chatanywhere.***.cn/',
>     error: {
>       headers: [Object],
>       stack: 'Error: 404 <html>\n' +
>         '<head><title>404 Not Found</title></head>\n' +
>         '<body>\n' +
>         '<center><h1>404 Not Found</h1></center>\n' +
>         '<hr><center>nginx</center>\n' +
>         '</body>\n' +
>         '</html>\n' +
>         '    at rt.generate (/var/task/.next/server/chunks/96903.js:219:67341)\n' +
>         '    at nf.makeStatusError (/var/task/.next/server/chunks/96903.js:219:59038)\n' +
>         '    at nf.makeRequest (/var/task/.next/server/chunks/96903.js:219:59961)\n' +
>         '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
>         '    at async Object.embeddings (/var/task/.next/server/chunks/43054.js:9:3533)\n' +
>         '    at async /var/task/.next/server/chunks/1701.js:5:25922\n' +
>         '    at async u.middlewares (/var/task/.next/server/chunks/90525.js:1:5409)\n' +
>         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)\n' +
>         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)\n' +
>         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)',
>       status: 404
>     },
>     errorType: 'ProviderBizError',
>     provider: 'openai'
>   }
> }
> ```

<img width="856" alt="image" src="https://github.com/user-attachments/assets/d8e0fcb2-ba4c-43f0-8ac4-6d2183beeb12">

**Comment by ji-jinlong** [comment]
> > > #3527
> > > 这里写了需要配置APP_URL
> > 
> > 
> > 感谢领细心且耐心的指导, 因为教程中没有这个参数所以我没有添加. 刚加上了, 现在成功分块了. 只是,,,,现在向量化失败
> > 猜测可能是我用的转发不支持, 不过这个我在MaxKB中是成功了的, 不知道二者有啥区别.
> > ```
> > Uncaught (in promise) TRPCClientError
> >     at s.from (73920-2cd3d6dba97afb1d.js:1:878)
> >     at 73920-2cd3d6dba97afb1d.js:1:7395
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```json
> > i [TRPCError]
> >     at a (/var/task/.next/server/chunks/90525.js:1:1011)
> >     ... 6 lines matching cause stack trace ...
> >     at async r (/var/task/.next/server/chunks/90525.js:1:6057)
> >     at async /var/task/.next/server/chunks/52408.js:1:7252
> >     at async Promise.all (index 0) {
> >   code: 'INTERNAL_SERVER_ERROR',
> >   [cause]: o [Error]
> >       at /var/task/.next/server/chunks/90525.js:1:1322
> >       at new i (/var/task/.next/server/chunks/90525.js:1:1364)
> >       at a (/var/task/.next/server/chunks/90525.js:1:1011)
> >       at t (/var/task/.next/server/chunks/90525.js:1:6033)
> >       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> >       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
> >       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
> >       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
> >       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
> >       at async r (/var/task/.next/server/chunks/90525.js:1:6057) {
> >     endpoint: 'https://api.chatanywhere.***.cn/',
> >     error: {
> >       headers: [Object],
> >       stack: 'Error: 404 <html>\n' +
> >         '<head><title>404 Not Found</title></head>\n' +
> >         '<body>\n' +
> >         '<center><h1>404 Not Found</h1></center>\n' +
> >         '<hr><center>nginx</center>\n' +
> >         '</body>\n' +
> >         '</html>\n' +
> >         '    at rt.generate (/var/task/.next/server/chunks/96903.js:219:67341)\n' +
> >         '    at nf.makeStatusError (/var/task/.next/server/chunks/96903.js:219:59038)\n' +
> >         '    at nf.makeRequest (/var/task/.next/server/chunks/96903.js:219:59961)\n' +
> >         '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
> >         '    at async Object.embeddings (/var/task/.next/server/chunks/43054.js:9:3533)\n' +
> >         '    at async /var/task/.next/server/chunks/1701.js:5:25922\n' +
> >         '    at async u.middlewares (/var/task/.next/server/chunks/90525.js:1:5409)\n' +
> >         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)\n' +
> >         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)\n' +
> >         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)',
> >       status: 404
> >     },
> >     errorType: 'ProviderBizError',
> >     provider: 'openai'
> >   }
> > }
> > ```
> 
> maxKB如果不单独配置的话使用的应该是本地的向量化模型shibing624_text2vec-base-chinese ![image](https://private-user-images.githubusercontent.com/124059108/360739332-077de685-9f2b-4c7a-818a-2077a27a6056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODIyNDcsIm5iZiI6MTcyNDM4MTk0NywicGF0aCI6Ii8xMjQwNTkxMDgvMzYwNzM5MzMyLTA3N2RlNjg1LTlmMmItNGM3YS04MThhLTIwNzdhMjdhNjA1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwMjU5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDQwMDRhM2EzZGQwZjU5Zjc0MmYzYzM5MzJkODBiMzAzOTEyN2UyYTg3ZGM2OGY2NWQ4ZmYxNzFmMTRmMTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OXKQpC0576khQh5kSb85gOa6SrxZgqRr7EdkOszIhdU)

我看了下我的MaxKB使用的是我自己添加的 text-embedding-ada-002

**Comment by ji-jinlong** [comment]
> <img alt="image" width="856" src="https://private-user-images.githubusercontent.com/28616219/360741558-d8e0fcb2-ba4c-43f0-8ac4-6d2183beeb12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODI5MTEsIm5iZiI6MTcyNDM4MjYxMSwicGF0aCI6Ii8yODYxNjIxOS8zNjA3NDE1NTgtZDhlMGZjYjItYmE0Yy00M2YwLThhYzQtNmQyMTgzYmVlYjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAzMTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NjJlYTU4NzU4NDczNTU1NWNiMzAzMTBmMGRiYzgyZGEwYjBiMmQ0YjUzZTg3NzNlMmJjYjE3YWVjNzZjZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5MtpWST8nm3QbXgOxyaGf6S06t5SbdGWdwiSsyQMVAE">


我的转发商告诉我他们支持这个模型, 有可能是其他原因, 我再折腾折腾. 

https://chatanywhere.apifox.cn/doc-2694962

**Comment by GwIhViEte** [comment]
> > #3527
> > 
> > 这里写了需要配置APP_URL
> 
> 感谢领细心且耐心的指导, 因为教程中没有这个参数所以我没有添加. 刚加上了, 现在成功分块了. 只是,,,,现在向量化失败
> 
> 猜测可能是我用的转发不支持, 不过这个我在MaxKB中是成功了的, 不知道二者有啥区别. 
> 
> ```
> Uncaught (in promise) TRPCClientError
>     at s.from (73920-2cd3d6dba97afb1d.js:1:878)
>     at 73920-2cd3d6dba97afb1d.js:1:7395
> ```
> 
> ```json
> i [TRPCError]
>     at a (/var/task/.next/server/chunks/90525.js:1:1011)
>     ... 6 lines matching cause stack trace ...
>     at async r (/var/task/.next/server/chunks/90525.js:1:6057)
>     at async /var/task/.next/server/chunks/52408.js:1:7252
>     at async Promise.all (index 0) {
>   code: 'INTERNAL_SERVER_ERROR',
>   [cause]: o [Error]
>       at /var/task/.next/server/chunks/90525.js:1:1322
>       at new i (/var/task/.next/server/chunks/90525.js:1:1364)
>       at a (/var/task/.next/server/chunks/90525.js:1:1011)
>       at t (/var/task/.next/server/chunks/90525.js:1:6033)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async t (/var/task/.next/server/chunks/90525.js:1:5715)
>       at async r (/var/task/.next/server/chunks/90525.js:1:6057) {
>     endpoint: 'https://api.chatanywhere.***.cn/',
>     error: {
>       headers: [Object],
>       stack: 'Error: 404 <html>\n' +
>         '<head><title>404 Not Found</title></head>\n' +
>         '<body>\n' +
>         '<center><h1>404 Not Found</h1></center>\n' +
>         '<hr><center>nginx</center>\n' +
>         '</body>\n' +
>         '</html>\n' +
>         '    at rt.generate (/var/task/.next/server/chunks/96903.js:219:67341)\n' +
>         '    at nf.makeStatusError (/var/task/.next/server/chunks/96903.js:219:59038)\n' +
>         '    at nf.makeRequest (/var/task/.next/server/chunks/96903.js:219:59961)\n' +
>         '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
>         '    at async Object.embeddings (/var/task/.next/server/chunks/43054.js:9:3533)\n' +
>         '    at async /var/task/.next/server/chunks/1701.js:5:25922\n' +
>         '    at async u.middlewares (/var/task/.next/server/chunks/90525.js:1:5409)\n' +
>         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)\n' +
>         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)\n' +
>         '    at async t (/var/task/.next/server/chunks/90525.js:1:5715)',
>       status: 404
>     },
>     errorType: 'ProviderBizError',
>     provider: 'openai'
>   }
> }
> ```
> 
> 
能看看你是怎么填写URL的吗？我也遇到这个问题了，但是我有点看不懂官方的教程😭
