### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by havelhuang** [lobehub/lobe-chat#3546]
### 📦 部署环境

Vercel

### 📌 软件版本

1.12.1

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

按教程配置好，文件和图片无法正常上传，卡在准备上传页面
![屏幕截图 2024-08-22 132457](https://github.com/user-attachments/assets/85ea5e09-cd75-4620-a0a1-bedf14eb6d62)
![屏幕截图 2024-08-22 132619](https://github.com/user-attachments/assets/af897eae-0988-4e77-9e2e-09e48cbcc23d)

**Comment by alphandbelt1** [comment]
![image](https://github.com/user-attachments/assets/f36dc679-0d3c-48ab-9609-f42e803e8f2a)
同样的问题，也是一直在准备上传中，前端和后端都没有报错。

**Comment by arvinxx** [comment]
看下浏览器是不是被跨域拦截了

**Comment by alphandbelt1** [comment]
> 看下浏览器是不是被跨域拦截了

果然是的。怎么弄呢这个。

**Comment by havelhuang** [comment]
已解决，将网站域名加入CloudFlare的CORS 策略中
