### ISSUE TITLE
[Request] Simple local DB integration via Mysql for persistent chats

### ISSUE THREAD

**Issue by gorfreed** [lobehub/lobe-chat#3558]
### 🥰 Feature Description

I really like Lobechat and the active development and community, but being unable to save my chats persistently so I can open them on any device makes it impossible for me to use for work.
I am aware of the documentation regarding "[Deploying Server-Side Database](https://lobehub.com/docs/self-hosting/server-database)", but it is impossible for me to accomplish the incredibly difficult setup. I also don't want to purchase an S3 server. What is the difficulty of simply saving any chats into a simple Mysql or SQlite database? It seems expectations regarding "security" are way out of proportions when trying to use Lobechat as an individual user. Unfortunately, the docker-compose documentation that could automate this procedure doesn't exist yet.

### 🧐 Proposed Solution

Have chats saved into a Mysql database. Connection settings (ip/url, password, port, databasename) can be configured with ENV variables.

**Comment by arvinxx** [comment]
> Have chats saved into a Mysql database. Connection settings (ip/url, password, port, databasename) can be configured with ENV variables.

Officially we won't support mysql /SQLite. MySQL or SQLite don't have pgvector plugin as Postgres does. It means these two db can't work with embedding semantic search which is the core part of RAG (technique behind file chat or knowledge base chat).

> I also don't want to purchase an S3 server. 

you can also deploy pg on your own local computer, and use self-hosting S3 solution like [minio](https://min.io). Here is a demo example that you can run LobeChat DB on your local PC or Mac: https://lobehub.com/docs/self-hosting/server-database/docker#using-locally-mac-windows

> Unfortunately, the docker-compose documentation that could automate this procedure doesn't exist yet.

We are working on this. You may need to wait for several days to let us finish this.

**Comment by gorfreed** [comment]
I dont want to run Lobechat on a computer. I want it to run on the linux server of my company. But even your "local" DB deployment is riddled with "S3" env varialbes that seem to be a nightmare to configure.
I will go with a competitor for this one. It doesn't have all the features Lobechat has, but I will be able to manage it myself without an IT department.

**Comment by arvinxx** [comment]
@gorfreed Sorry to hear that, but it all depends on yourself. We use the best practice of each technique for long-run. It maybe complex but it's all we need to afford. You will find S3 is neccessary in final if you have large amount size of files. In this architecture we can support unlimit size file and easy to scale up.

**Comment by arvinxx** [comment]
we have supported a much easy `docker-compose.yml` now :  https://lobehub.com/docs/self-hosting/server-database/docker-compose . Maybe you can have a try.
