### ISSUE TITLE
[Bug] minimax 有时流式输出后解析失败

### ISSUE THREAD

**Issue by Zolyn** [lobehub/lobe-chat#3563]
### 📦 部署环境

Vercel

### 📌 软件版本

1.12.4

### 💻 系统环境

Windows

### 🌐 浏览器

Firefox

### 🐛 问题描述

![图片](https://github.com/user-attachments/assets/1f95d809-2c55-4ddc-bd7e-9352af5d11e9)

**Comment by arvinxx** [comment]
数据复制出来我看下

**Comment by arvinxx** [comment]
和 #4054 重复，那个 issue 提到了根因，后续修复
