### ISSUE TITLE
[Request] 部署database版本是否一定需要一个公网的域名和服务器IP

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#3568]
### 🥰 Feature Description

部署database版本是否一定需要一个公网的域名和服务器IP

### 🧐 Proposed Solution

部署database版本是否一定需要一个公网的域名和服务器IP

### 📝 Additional Information

部署database版本是否一定需要一个公网的域名和服务器IP

**Comment by arvinxx** [comment]
不一定
