### ISSUE TITLE
向量化模型名字问题

### ISSUE THREAD

**Issue by ji-jinlong** [lobehub/lobe-chat#3571]
> 向量化需要使用 OpenAI 的 text-embedding-small-3 模型，请提前确认你的 API 是否支持该模型；

大佬, 官方文档标准模型名为 "text-embedding-3-small"

https://platform.openai.com/docs/models/embeddings

> ps: 我是说怎么我用的转发说支持但一直向量化失败

_Originally posted by @ji-jinlong in https://github.com/lobehub/lobe-chat/issues/3527#issuecomment-2306369091_

**Comment by ji-jinlong** [comment]
不对, 好像只是写议题的时候手误,,,,,代码还是对的
![efc5bc88914421059a5fd513227a3cd7](https://github.com/user-attachments/assets/0e5ce631-e83d-4510-a1b1-5a2935e6c7f8)

**Comment by arvinxx** [comment]
已更正，感谢提醒

**Comment by JonFanne** [comment]
> > 向量化需要使用 OpenAI 的 text-embedding-small-3 模型，请提前确认你的 API 是否支持该模型；
> 
> 大佬, 官方文档标准模型名为 "text-embedding-3-small"
> 
> https://platform.openai.com/docs/models/embeddings
> 
> > ps: 我是说怎么我用的转发说支持但一直向量化失败
> 
> _Originally posted by @ji-jinlong in [#3527 (comment)](https://github.com/lobehub/lobe-chat/issues/3527#issuecomment-2306369091)_

只能默认使用openai的向量数据库吗，可以更改默认向量数据库的参数为其他供应商吗
