### ISSUE TITLE
[Bug] 批量上传文件出现重复

### ISSUE THREAD

**Issue by Zolyn** [lobehub/lobe-chat#3577]
### 📦 部署环境

Vercel

### 📌 软件版本

1.12.9

### 💻 系统环境

Windows

### 🌐 浏览器

Firefox

### 🐛 问题描述

如图，批量选择3个文件上传，实际显示正在上传9个，请求也是9次
![Snipaste_2024-08-23_23-17-24](https://github.com/user-attachments/assets/b46e08f4-b29c-4384-9652-eb52beadcb4f)

**Comment by arvinxx** [comment]
你是怎么批量上传的？拖拽文件夹吗？

**Comment by arvinxx** [comment]
我研究下
