### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by tayimilkyway** [lobehub/lobe-chat#3579]
### 📦 部署环境

Docker

### 📌 软件版本

v1.12.9

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

我使用的api支持text-embedding-3-small模型，但还是一直分块失败
![1dptcckw 5h4](https://github.com/user-attachments/assets/ef67f97c-083e-40f4-8e47-7fddabf3414d)
![c1b4nhch uvt](https://github.com/user-attachments/assets/632bb789-7c01-4814-9fc9-43c0005388a8)
![kkr02x50 vax](https://github.com/user-attachments/assets/c57651eb-eb78-4a85-b8d5-881c7e357f60)

**Comment by arvinxx** [comment]
分块失败和向量化模型没关系。建议检查下你的应用部署
