### ISSUE TITLE
[Bug] Docker build error for Database Docker Image

### ISSUE THREAD

**Issue by bentwnghk** [lobehub/lobe-chat#3583]
### 📦 Environment

Docker

### 📌 Version

v1.12.11

### 💻 Operating System

Ubuntu

### 🌐 Browser

Other

### 🐛 Bug Description

Building the regular Docker image works fine, but there appears to be errors building the Database Docker image:
![Screenshot_20240824_073053_Chrome](https://github.com/user-attachments/assets/213d7098-3dff-4ee5-ba1b-b1b6397ca544)

**Comment by asanpardazzagrosheyrani** [comment]
👉♥️ for you

**Comment by arvinxx** [comment]
已在 #3584 修复，等待构建看看
