### ISSUE TITLE
[Bug] 最新数据库版本上传文件时会泄露 `S3_ENDPOINT` 地址

### ISSUE THREAD

**Issue by hezhijie0327** [lobehub/lobe-chat#3587]
### 📦 部署环境

Docker

### 📌 软件版本

v1.12.14

### 💻 系统环境

Windows, iOS

### 🌐 浏览器

Edge

### 🐛 问题描述

试了几个版本，试出来在 `v1.12.10` 版本后，在upload文件时，会泄露 `S3_ENDPOINT` 地址，像是走客户端传输？
![image](https://github.com/user-attachments/assets/a43fddad-ee1e-43db-a992-0a7fe9ac8570)

### 📷 复现步骤

在 `文件与知识库` 中上传文件，观察浏览器 Console 日志，可发现存在 `S3_ENDPOINT` 地址

**Comment by arvinxx** [comment]
走的就是浏览器传输，这个没啥问题，是标准实现方式。 https://www.shuxiaoyuan.com/blog/info/97
