### ISSUE TITLE
[Request] 外链用新窗口打开

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#359]
### 🥰 需求描述 | Feature Description

链接是在当前页打开的，在新窗口打开的话体验应该更好些吧

<img width="631" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/08318d80-a2f2-4bc0-a005-dcaddb6f7d2b">

### 🧐 解决方案 | Proposed Solution

在新窗口打开

**Comment by arvinxx** [comment]
@canisminor1990 +1

**Comment by canisminor1990** [comment]
fix in https://github.com/lobehub/lobe-ui/commit/983fd5c118c72c9c46a79447df2704c504b9ccb0
