### ISSUE TITLE
[Request] add additional headers for Anthropic Claude-API

### ISSUE THREAD

**Issue by ladisa-33** [lobehub/lobe-chat#3596]
### 🥰 Feature Description

Please make it possible to add the header "anthropic-beta": "max-tokens-3-5-sonnet-2024-07-15" to API calls. So that we can use the new 8K output from Sonnet 3.5

### 🧐 Proposed Solution

Additional header option in API-requrest

### 📝 Additional Information

<img width="593" alt="Bildschirmfoto 2024-08-24 um 21 22 56" src="https://github.com/user-attachments/assets/d190a5d5-f22c-4563-b61a-b85557667b73">

**Comment by arvinxx** [comment]
duplicate of https://github.com/lobehub/lobe-chat/issues/3596
