### ISSUE TITLE
[Request] 建议增加keycloak认证，实现完全本地化

### ISSUE THREAD

**Issue by chung1912** [lobehub/lobe-chat#3601]
### 🥰 需求描述

目前pv数据库可以本地化，minio也可以本地化，但是认证系统依然要依赖auth0或clerk这样的外网认证，希望可以增加keycloak兼容，实现完全本地化

### 🧐 解决方案

增加对keyloak身份认证的支持

**Comment by ProblemFactory** [comment]
根据文档 https://lobehub.com/docs/self-hosting/advanced/auth/next-auth/authentik lobechat支持authentik，这个应该是可以自己部署在本地的吧？

**Comment by chung1912** [comment]
> 根据文档 https://lobehub.com/docs/self-hosting/advanced/auth/next-auth/authentik lobechat支持authentik，这个应该是可以自己部署在本地的吧？

已经用了keycloak，不想搞那么多认证系统，能支持下keycloak就好了

**Comment by arvinxx** [comment]
@chung1912 keycloak 可以在非 https 下使用吗

**Comment by chung1912** [comment]
> @chung1912 keycloak 可以在非 https 下使用吗

我就是本地局域网使用的，可以http也可以https

**Comment by arvinxx** [comment]
@chung1912 试试我们最新的 docker-compose ，logto 体验应该比 keycloak 好多了：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose

**Comment by zhangleijun111** [comment]
> > Bot 检测到 issue body 的语言不是英文，自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> 试试我们最新的 docker-compose，logto 体验应该比 keycloak 好得多：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose

下载不了要魔法嘛

**Comment by zhuozhiyongde** [comment]
这个也可以关了？依照现在的文档，使用 casdoor 已经支持 Localhost / 局域网 / 公网部署
@arvinxx

**Comment by chenzikun** [comment]
我这边已经实现了对keycloak的支持，如果可以，我这边可以贡献到开源社区

**Comment by chung1912** [comment]
> 我这边已经实现了对keycloak的支持，如果可以，我这边可以贡献到开源社区

非常需要啊

**Comment by arvinxx** [comment]
@chenzikun 欢迎👏🏻~
