### ISSUE TITLE
[Bug] 环境变量解析问题

### ISSUE THREAD

**Issue by LarkinZero** [lobehub/lobe-chat#3608]
### 📦 部署环境

Docker

### 📌 软件版本

v1.12.19

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

从v1.12.9升级到v1.12.19时，没有填写APP_URL。用Portainer修改容器版本后启动，重建容器日志报错需要填写APP_URL。于是加入APP_URL环境变量，填写是https://abc.com。启动后报错：
```
$2});             fi;         fi;         printf "%s\n"             localnet: line 0: syntax error: unexpected end of file (expecting ")")
```

### 📷 复现步骤

![image](https://github.com/user-attachments/assets/9d465574-ae6c-4823-b300-68cdc0c7d742)

### 🚦 期望结果

正常启动

**Comment by arvinxx** [comment]
感觉是你的配置问题？我这边测下来没问题呀

**Comment by LarkinZero** [comment]
不知道什么情况，我把版本改回v1.12.9回退后，再升级到v1.12.19又正常了。环境变量也没动过
<img width="984" alt="image" src="https://github.com/user-attachments/assets/707986ae-7a8c-41f4-a724-4d0e22d108b5">

**Comment by arvinxx** [comment]
@LarkinZero 可能
