### ISSUE TITLE
[Request] minio如何部署可否给一个教学呀

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#3612]
### 🥰 Feature Description

minio如何部署可否给一个教学呀

### 🧐 Proposed Solution

minio如何部署可否给一个教学呀

### 📝 Additional Information

minio如何部署可否给一个教学呀

**Comment by hezhijie0327** [comment]
最近稍微研究了下 MinIO，至少功能正常，可以参考下

1. Docker 部署
```
DOCKER_PATH="/docker/minio" # 改为你的数据存储路径
SSL_PATH="/docker/ssl" # 改为你的 SSL 证书路径

docker run --name minio --restart=always \
    -e MINIO_ROOT_USER="minioadmin" \
    -e MINIO_ROOT_PASSWORD="minioadmin" \
    -e MINIO_DOMAIN="oss.example.com" \
    -e MINIO_REGION="us-east-1" \ # 非必要
    -e MINIO_SERVER_URL="https://oss.example.com:9000" \ # 非必要
    -e MINIO_BROWSER_REDIRECT_URL="https://console.example.com:9001" \ # 非必要
    -p 9000:9000/tcp \
    -p 9001:9001/tcp \
    -v ${SSL_PATH}/fullchain.cer:/etc/minio/cert/public.crt:ro \ # 非必要
    -v ${SSL_PATH}/example.com.key:/etc/minio/cert/private.key:ro \ # 非必要
    -v ${DOCKER_PATH}/data:/etc/minio/data \
    -d minio/minio:latest \
    server "/etc/minio/data" \
    --address ":9000" \
    --console-address ":9001" \
    --certs-dir "/etc/minio/cert" # 非必要
```
2. 访问 console 地址，如：https://IP:9001 或 https://console.example.com:9001 并登录
3. 创建 Buckets
![image](https://github.com/user-attachments/assets/76ae49fe-48eb-42a7-b4fe-5df51d4336a8)
![image](https://github.com/user-attachments/assets/849e2546-315f-4ef4-96e0-cac23f81cfa8)
4. 创建 AccessKey
![image](https://github.com/user-attachments/assets/d92b9a6a-b7f8-4ccd-9592-2ed94bb99a94)
![image](https://github.com/user-attachments/assets/0aee93bf-5fe8-4269-b029-da3a9c91ca6c)
5. 更改 Policy
![image](https://github.com/user-attachments/assets/0f96f43c-00fa-423f-86b3-462c24c75a16)
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::lobechat"
            ]
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::lobechat"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:prefix": [
                        "files/*"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::lobechat/files/**"
            ]
        }
    ]
}
```
6. 更改 LobeChat ENV
```
S3_ACCESS_KEY_ID="_your_access_key_id_" # 第四步中
S3_SECRET_ACCESS_KEY="_your_secret_access_key"
S3_ENABLE_PATH_STYLE="1"
S3_BUCKET="lobechat"
S3_ENDPOINT="https://oss.example.com:9000"
S3_PUBLIC_DOMAIN="https://oss.example.com:9000"
```

**Comment by fashioncj** [comment]
补几个要点
1. MINIO_DOMAIN 很重要，特别是反代的，否则签名会失败
2. 不需要配置复杂的策略，只需要在这里开通匿名读的配置就可以（希望很快就可以加上签名读取）
<img width="2186" alt="image" src="https://github.com/user-attachments/assets/d0a1dcbf-7d2a-4be8-9a34-90989e395b79">

**Comment by zhangleijun111** [comment]
> 最近稍微研究了下 MinIO，至少功能正常，可以参考下
> 
> 1. Docker 部署
> 
> ```
> DOCKER_PATH="/docker/minio" # 改为你的数据存储路径
> SSL_PATH="/docker/ssl" # 改为你的 SSL 证书路径
> 
> docker run --name minio --restart=always \
>     -e MINIO_ROOT_USER="minioadmin" \
>     -e MINIO_ROOT_PASSWORD="minioadmin" \
>     -e MINIO_DOMAIN="oss.example.com" \
>     -e MINIO_REGION="us-east-1" \ # 非必要
>     -e MINIO_SERVER_URL="https://oss.example.com:9000" \ # 非必要
>     -e MINIO_BROWSER_REDIRECT_URL="https://console.example.com:9001" \ # 非必要
>     -p 9000:9000/tcp \
>     -p 9001:9001/tcp \
>     -v ${SSL_PATH}/fullchain.cer:/etc/minio/cert/public.crt:ro \ # 非必要
>     -v ${SSL_PATH}/example.com.key:/etc/minio/cert/private.key:ro \ # 非必要
>     -v ${DOCKER_PATH}/data:/etc/minio/data \
>     -d minio/minio:latest \
>     server "/etc/minio/data" \
>     --address ":9000" \
>     --console-address ":9001" \
>     --certs-dir "/etc/minio/cert" # 非必要
> ```
> 
> 2. 访问 console 地址，如：https://IP:9001 或 https://console.example.com:9001 并登录
> 3. 创建 Buckets
>    ![image](https://private-user-images.githubusercontent.com/58100052/361395206-76ae49fe-48eb-42a7-b4fe-5df51d4336a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc0MzQsIm5iZiI6MTcyNDcyNzEzNCwicGF0aCI6Ii81ODEwMDA1Mi8zNjEzOTUyMDYtNzZhZTQ5ZmUtNDhlYi00MmE3LWI0ZmUtNWRmNTFkNDMzNmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMjFhYjg1MTgwNzBmODFkMWVmZDAwZTZjZWZjZDNkOGIyOGU2ZTYwM2U2OWY3OTg1Y2JmM2Q4ZmI0Mjc2NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wYUBo0cxNNQwfK55fOj2tWxd5uu0Bz2VznJZZx6phrI)
>    ![image](https://private-user-images.githubusercontent.com/58100052/361395243-849e2546-315f-4ef4-96e0-cac23f81cfa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc0MzQsIm5iZiI6MTcyNDcyNzEzNCwicGF0aCI6Ii81ODEwMDA1Mi8zNjEzOTUyNDMtODQ5ZTI1NDYtMzE1Zi00ZWY0LTk2ZTAtY2FjMjNmODFjZmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NDRjMGFjNjAzMjNjMmMwZjIwNmNhNDY2NGY4MmEwMGIwMDNhNDNmZTMyNTFmN2E0ODlkNzU5ZGQxNjRlOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oJ4vFBUmY6_-sdYyqIhaEDLoCMp-TNkE-wf-UpzoT-4)
> 4. 创建 AccessKey
>    ![image](https://private-user-images.githubusercontent.com/58100052/361395343-d92b9a6a-b7f8-4ccd-9592-2ed94bb99a94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc0MzQsIm5iZiI6MTcyNDcyNzEzNCwicGF0aCI6Ii81ODEwMDA1Mi8zNjEzOTUzNDMtZDkyYjlhNmEtYjdmOC00Y2NkLTk1OTItMmVkOTRiYjk5YTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MmJhZGQ4M2Y5YjYxMzVhNDVlMmNmM2FiYWVjZDZlNDIwYTUwZmNkM2JlODk2YzQ0ZDEwZmE5OGEwM2Q3YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v7JhAeCyzP5LKLIu5A33p7ZxDuEBim1ebe1hqgLO6c8)
>    ![image](https://private-user-images.githubusercontent.com/58100052/361395380-0aee93bf-5fe8-4269-b029-da3a9c91ca6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc0MzQsIm5iZiI6MTcyNDcyNzEzNCwicGF0aCI6Ii81ODEwMDA1Mi8zNjEzOTUzODAtMGFlZTkzYmYtNWZlOC00MjY5LWIwMjktZGEzYTljOTFjYTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMzhlOGFlZWNlOTA1NmI5OTMwMmNlN2ZkOGY5MDBlY2ViYTJmM2IxODAxZTdkMzcyYzU3YTMxNTYyZmE4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HP7fB2lNQE8WjrqjzDDXkQ4iV4_CBe74NxrFC6iYLqY)
> 5. 更改 Policy
>    ![image](https://private-user-images.githubusercontent.com/58100052/361396803-0f96f43c-00fa-423f-86b3-462c24c75a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc0MzQsIm5iZiI6MTcyNDcyNzEzNCwicGF0aCI6Ii81ODEwMDA1Mi8zNjEzOTY4MDMtMGY5NmY0M2MtMDBmYS00MjNmLTg2YjMtNDYyYzI0Yzc1YTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMjc1OWE2NGZhNDJjY2Q4NjA3NzY5ZDk4Y2YxNGFkMzJhNTAwZTZkOGNhYjdhM2MwN2JiYzFlOGMxZWY5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tbocm8A8XylbXLejobA6E3C1oNFWEQtdYRz8xFsMj-M)
> 
> ```
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": [
>                     "*"
>                 ]
>             },
>             "Action": [
>                 "s3:GetBucketLocation"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::lobechat"
>             ]
>         },
>         {
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": [
>                     "*"
>                 ]
>             },
>             "Action": [
>                 "s3:ListBucket"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::lobechat"
>             ],
>             "Condition": {
>                 "StringEquals": {
>                     "s3:prefix": [
>                         "files/*"
>                     ]
>                 }
>             }
>         },
>         {
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": [
>                     "*"
>                 ]
>             },
>             "Action": [
>                 "s3:PutObject",
>                 "s3:DeleteObject",
>                 "s3:GetObject"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::lobechat/files/**"
>             ]
>         }
>     ]
> }
> ```
> 
> 6. 更改 LobeChat ENV
> 
> ```
> S3_ACCESS_KEY_ID="_your_access_key_id_" # 第四步中
> S3_SECRET_ACCESS_KEY="_your_secret_access_key"
> S3_ENABLE_PATH_STYLE="1"
> S3_BUCKET="lobechat"
> S3_ENDPOINT="https://oss.example.com:9000"
> S3_PUBLIC_DOMAIN="https://oss.example.com:9000"
> ```
ocker run --name minio --restart=always \
  -e MINIO_ROOT_USER="minioadmin" \
  -e MINIO_ROOT_PASSWORD="minioadmin" \
  -e MINIO_DOMAIN="oss.example.com" \
  -p 9000:9000/tcp \
  -p 9001:9001/tcp \
  -v ${DOCKER_PATH}/data:/etc/minio/data \
  -d registry.us-west-1.aliyuncs.com/jg-images/minio:latest  我这样部署貌似不能访问9001嘛

**Comment by zhangleijun111** [comment]
> 最近稍微研究了下 MinIO，至少功能正常，可以参考下
> 
> 1. Docker 部署
> 
> ```
> DOCKER_PATH="/docker/minio" # 改为你的数据存储路径
> SSL_PATH="/docker/ssl" # 改为你的 SSL 证书路径
> 
> docker run --name minio --restart=always \
>     -e MINIO_ROOT_USER="minioadmin" \
>     -e MINIO_ROOT_PASSWORD="minioadmin" \
>     -e MINIO_DOMAIN="oss.example.com" \
>     -e MINIO_REGION="us-east-1" \ # 非必要
>     -e MINIO_SERVER_URL="https://oss.example.com:9000" \ # 非必要
>     -e MINIO_BROWSER_REDIRECT_URL="https://console.example.com:9001" \ # 非必要
>     -p 9000:9000/tcp \
>     -p 9001:9001/tcp \
>     -v ${SSL_PATH}/fullchain.cer:/etc/minio/cert/public.crt:ro \ # 非必要
>     -v ${SSL_PATH}/example.com.key:/etc/minio/cert/private.key:ro \ # 非必要
>     -v ${DOCKER_PATH}/data:/etc/minio/data \
>     -d minio/minio:latest \
>     server "/etc/minio/data" \
>     --address ":9000" \
>     --console-address ":9001" \
>     --certs-dir "/etc/minio/cert" # 非必要
> ```
> 
> 2. 访问 console 地址，如：https://IP:9001 或 https://console.example.com:9001 并登录
> 3. 创建 Buckets
>    ![图像](https://private-user-images.githubusercontent.com/58100052/361395206-76ae49fe-48eb-42a7-b4fe-5df51d4336a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjg5NzYsIm5iZiI6MTcyNDcyODY3NiwicGF0aCI6Ii81ODEwMDA1Mi8zNjEzOTUyMDYtNzZhZTQ5ZmUtNDhlYi00MmE3LWI0ZmUtNWRmNTFkNDMzNmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAzMTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNTU1MWE0MWRkYTg4NDA5MTQ4MDgyMDY2MDA4ZDM0ZjdjNzcyNGU5NjlmMGVlNTJjNThjMjZjZGRkMWUwYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d6gRCIl4B-U13okI94DSbpgUOh9b4MoopZzxz785QS4)
>    ![图像](https://private-user-images.githubusercontent.com/58100052/361395243-849e2546-315f-4ef4-96e0-cac23f81cfa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjg5NzYsIm5iZiI6MTcyNDcyODY3NiwicGF0aCI6Ii81ODEwMDA1Mi8zNjEzOTUyNDMtODQ5ZTI1NDYtMzE1Zi00ZWY0LTk2ZTAtY2FjMjNmODFjZmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAzMTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzYzMjkwMDlhODliNTVkZTgyMTA0MDQzMzc2YzE4MmYyZmZiYzZiNDNiNGUwMzgzNzMwNmNjYzA0MzlkZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jOSg7cU4fl17EUX8fau8vr1CslSG9S2pSQMzWjVomew)
> 4. 创建 AccessKey
>    ![图像](https://private-user-images.githubusercontent.com/58100052/361395343-d92b9a6a-b7f8-4ccd-9592-2ed94bb99a94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjg5NzYsIm5iZiI6MTcyNDcyODY3NiwicGF0aCI6Ii81ODEwMDA1Mi8zNjEzOTUzNDMtZDkyYjlhNmEtYjdmOC00Y2NkLTk1OTItMmVkOTRiYjk5YTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAzMTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NWQ1ZDU2YjRlODExODhlZmI1OWI3NDMzMDBjNzRjZmE5OTMwMDYxMzI1N2U0M2UxYjlhOWIzZDljOWJhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uFf5O9zvdMXWFu49l43qQBUxBfn-yrifVI_mMvWOosU)
>    ![图像](https://private-user-images.githubusercontent.com/58100052/361395380-0aee93bf-5fe8-4269-b029-da3a9c91ca6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjg5NzYsIm5iZiI6MTcyNDcyODY3NiwicGF0aCI6Ii81ODEwMDA1Mi8zNjEzOTUzODAtMGFlZTkzYmYtNWZlOC00MjY5LWIwMjktZGEzYTljOTFjYTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAzMTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwODFlOTE2NDJhOWVhOTQxNzUxZmI0Y2NkNGIyNWJhZWNhNmQ1ZjAzOWUxMWIxMDBlM2Y2YTFkNDA4ZWE0OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Svz885QzweEKLl1A7jMbdHPiVxs3d33x0ZF7qeIsvqg)
> 5. 更改 Policy
>    ![图像](https://private-user-images.githubusercontent.com/58100052/361396803-0f96f43c-00fa-423f-86b3-462c24c75a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjg5NzYsIm5iZiI6MTcyNDcyODY3NiwicGF0aCI6Ii81ODEwMDA1Mi8zNjEzOTY4MDMtMGY5NmY0M2MtMDBmYS00MjNmLTg2YjMtNDYyYzI0Yzc1YTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAzMTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYTk4ODMxMDZmZjhhNTM3MzRjMGIzOGQ3ZTA4YmNmMzM3MGE0NWJiNjljN2ZlYzMyZmEyN2I1YjdmNGVkZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wldj3f6HhC1tRlZ1LZ28wVSSCE2_c9bgQ7ijsIjAi2s)
> 
> ```
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": [
>                     "*"
>                 ]
>             },
>             "Action": [
>                 "s3:GetBucketLocation"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::lobechat"
>             ]
>         },
>         {
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": [
>                     "*"
>                 ]
>             },
>             "Action": [
>                 "s3:ListBucket"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::lobechat"
>             ],
>             "Condition": {
>                 "StringEquals": {
>                     "s3:prefix": [
>                         "files/*"
>                     ]
>                 }
>             }
>         },
>         {
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": [
>                     "*"
>                 ]
>             },
>             "Action": [
>                 "s3:PutObject",
>                 "s3:DeleteObject",
>                 "s3:GetObject"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::lobechat/files/**"
>             ]
>         }
>     ]
> }
> ```
> 
> 6. 更改 LobeChat ENV
> 
> ```
> S3_ACCESS_KEY_ID="_your_access_key_id_" # 第四步中
> S3_SECRET_ACCESS_KEY="_your_secret_access_key"
> S3_ENABLE_PATH_STYLE="1"
> S3_BUCKET="lobechat"
> S3_ENDPOINT="https://oss.example.com:9000"
> S3_PUBLIC_DOMAIN="https://oss.example.com:9000"
> ```

麻烦问一下第五步那段代码需要我做一些什么嘛，还是只要把访问策略变成公共即可

**Comment by hezhijie0327** [comment]
最简单的话就直接 Public
