### ISSUE TITLE
[Bug] database版知识库不能正常分块

### ISSUE THREAD

**Issue by chung1912** [lobehub/lobe-chat#3623]
### 📦 部署环境

Docker

### 📌 软件版本

v1.12.20(Database版)

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

database版知识库不能正常分块，上传的是pdf文件，提示超时
![image](https://github.com/user-attachments/assets/106ba6b5-afce-4879-949d-2e78c0fc8a38)

**Comment by arvinxx** [comment]
@chung1912 能否看下你的服务端日志，超时的问题可能有两种：

1. 你的 chunk 端口被保护了导致无法正常请求；
2. 你的 s3 文件没有被正常 fetch 到

**Comment by chung1912** [comment]
> @chung1912 能否看下你的服务端日志，超时的问题可能有两种：
> 
> 1. 你的 chunk 端口被保护了导致无法正常请求；
> 2. 你的 s3 文件没有被正常 fetch 到

![image](https://github.com/user-attachments/assets/258a2ed4-5407-49db-9c6e-96f87949d038)
