### ISSUE TITLE
[Bug] 文件上传失败，请检查网络连接或稍后再试

### ISSUE THREAD

**Issue by wcu1117** [lobehub/lobe-chat#3629]
### 📦 Environment

Other

### 📌 Version

1.11.1

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

配置了S3，在对话内容中选择图片上传就报错，正常文本聊天没问题。
`Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
[TRPCError: UNAUTHORIZED] { code: 'UNAUTHORIZED', name: 'TRPCError' }
 POST /trpc/edge/upload.createS3PreSignedUrl?batch=1 401 in 1428ms
`

接口报错返回
`[
    {
        "error": {
            "json": {
                "message": "UNAUTHORIZED",
                "code": -32001,
                "data": {
                    "code": "UNAUTHORIZED",
                    "httpStatus": 401,
                    "stack": "TRPCError: UNAUTHORIZED\n    at eval (webpack-internal:///(rsc)/./src/libs/trpc/middleware/password.ts:24:19)\n    at async callRecursive (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:160:32)\n    at async procedure (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:190:24)\n    at async eval (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:207:30)\n    at async Promise.all (index 0)\n    at async resolveResponse (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:419:26)\n    at async fetchRequestHandler (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/adapters/fetch/fetchRequestHandler.mjs:39:12)\n    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:228:37)\n    at async AppRouteRouteModule.execute (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:157:26)\n    at async AppRouteRouteModule.handle (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:290:30)",
                    "path": "upload.createS3PreSignedUrl"
                }
            }
        }
    }
]`

### 📷 Recurrence Steps

1

### 🚦 Expected Behavior

1

**Comment by arvinxx** [comment]
大概率是跨域问题配置

**Comment by arvinxx** [comment]
哦不对，你试试升级到最新版本，可能是 access code 的问题。应修复了

**Comment by wcu1117** [comment]
> 哦不对，你试试升级到最新版本，可能是 access code 的问题。应修复了

这个上传是没有兼容阿里云的OSS吗，我新建了一个bucket，开了公共读写功能，接口上传成功返回了路径了，但是访问出错了，我去阿里云发现里面根本没有文件

**Comment by arvinxx** [comment]
@wcu1117 兼容了，应该是你的配置不对。可以看看别人写的文档教程： https://ai.whitebook.group/bp/llmchat/web-chat-zu-jian-lobechat/fei-jie-gou-hua-shu-ju-chi-jiu-hua

**Comment by wcu1117** [comment]
> @wcu1117 兼容了，应该是你的配置不对。可以看看别人写的文档教程： https://ai.whitebook.group/bp/llmchat/web-chat-zu-jian-lobechat/fei-jie-gou-hua-shu-ju-chi-jiu-hua

看了下oss的日志，是因为跨域了。然后还发现了一个问题。我S3_PUBLIC_DOMAIN使用的是bucket+S3_ENDPOINT的形式，然后就成了这样。
![微信截图_20240830113043](https://github.com/user-attachments/assets/bb89a3b6-5b12-475a-ae6d-bd448253de91)

**Comment by wcu1117** [comment]
> @wcu1117 兼容了，应该是你的配置不对。可以看看别人写的文档教程： https://ai.whitebook.group/bp/llmchat/web-chat-zu-jian-lobechat/fei-jie-gou-hua-shu-ju-chi-jiu-hua

看了下oss的日志，是因为跨域了。然后还发现了一个问题。我S3_PUBLIC_DOMAIN使用的是bucket+S3_ENDPOINT的形式，然后就成了这样。
![微信截图_20240830113043](https://github.com/user-attachments/assets/bf27b558-d263-4d14-a641-2a7cfbbcd59e)

**Comment by wcu1117** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > @wcu1117 It’s compatible. Your configuration may be wrong. You can check out the documentation tutorials written by others: https://ai.whitebook.group/bp/llmchat/web-chat-zu-jian-lobechat/fei-jie-gou-hua-shu-ju-chi-jiu-hua
> 
> I looked at the oss log and found that it was cross-domain. Then a problem was discovered. My S3_PUBLIC_DOMAIN uses the form of bucket+S3_ENDPOINT, and then it becomes like this. ![WeChat screenshot_20240830113043](https://private-user-images.githubusercontent.com/11731733/363032365-bb89a3b6-5b12-475a-ae6d-bd448253de91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODkwNjEsIm5iZiI6MTcyNDk4ODc2MSwicGF0aCI6Ii8xMTczMTczMy8zNjMwMzIzNjUtYmI4OWEzYjYtNWIxMi00NzVhLWFlNmQtYmQ0NDgyNTNkZTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAzMzI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YThiYTc0ZWIyMDllNjFlMjdhNGI0Yzc3ZDcxYmY4NjUwM2QyYjBmZTk4OTM5ZTkyNWVhOGRhM2UyZDJmMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Ex41chXqO3BYP0HGAp9TN4d7fnDmOT2WkIwAv10ebQ)

麻烦帮我把这个记录删了，忘记打码了

**Comment by wcu1117** [comment]
可以了，权限问题，解决了，麻烦帮我把这个记录删了把，机器人自动复制了我的回复内容，感谢！！！
