### ISSUE TITLE
[Request] 将authelia和cloudflare-zero-trust登录验证合并成通用的oidc

### ISSUE THREAD

**Issue by jedy** [lobehub/lobe-chat#3642]
### 🥰 需求描述

next-auth/sso-providers/cloudflare-zero-trust.ts和next-auth/sso-providers/authelia.ts中除了名字其他都是一样的，而且两者都是标准的oidc登录流程。将clientId，clientSecret和issuer换成任意一家支持oidc的provider的信息都可以用。因此希望能直接合并成一个通用的。

### 🧐 解决方案

合并之后使用通用的环境变量。

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/pull/3624#issuecomment-2312458149

@hezhijie0327 来解释下为啥试下来不太好？

**Comment by hezhijie0327** [comment]
@arvinxx 昨天晚上本地试的时候遇到未知 BUG 了，NextAuth 报错，但是现在想想大致有点思路了

按照目前的情况来看，甚至可以把logto也并进来，我过会儿整下

**Comment by arvinxx** [comment]
@hezhijie0327 建议加一个新的 genericOIDC 吧，已经集成了的就先不动了
