### ISSUE TITLE
[Bug] Safari 添加到 Dock 之后，无法上传图片、文件

### ISSUE THREAD

**Issue by samurai00** [lobehub/lobe-chat#3643]
### 📦 部署环境

Docker

### 📌 软件版本

v1.14.3

### 💻 系统环境

macOS

### 🌐 浏览器

Safari

### 🐛 问题描述

Safari 添加到 Dock 之后，无法上传图片、文件，点击上传文件、图片，无法弹出文件选择窗口。

> 直接在 Safari 打开是没问题的，
> 在 Chrome 也没问题，
> 在 Chrome 添加 『Chrome 应用』也没问题。

### 📷 复现步骤

1. 通过 Safari 打开 docker 部署的地址
2. 按照指引，点击“分享” -> “添加到程序坞”
3. 通过程序坞打开 LobeChat
4. 点击附件📎，点击上传图片或者上传文件
5. 没反应，不弹出文件选择窗口

### 🚦 期望结果

可以弹出文件选择窗口，正常上传文件

### 📝 补充信息

https://github.com/user-attachments/assets/482fa29c-5005-496c-929d-512099638763

_No response_

**Comment by arvinxx** [comment]
@samurai00 macOS 系统版本是多少？

**Comment by zhuozhiyongde** [comment]
https://www.reddit.com/r/Safari/comments/1ery530/file_uploads_not_working_in_safari_dock_web_apps/

macOS 系统问题。
