### ISSUE TITLE
[Bug你好我用最新的docker-compose部署教程，在logto里面撞见next.js应用就一直在转圈是为什么呀，第一步就被卡死了咯？？？？

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#3644]
### 📦 部署环境

Docker

### 📌 软件版本

7.9

### 💻 系统环境

Other

### 🌐 浏览器

Firefox

### 🐛 问题描述

![17fa365d4ca8a007d011dc241bdb026](https://github.com/user-attachments/assets/6d32398e-4cd2-4869-8cea-3b1d80b1dbc8)

**Comment by zhuozhiyongde** [comment]
https://github.com/lobehub/lobe-chat/pull/3651

你可以参考这个 PR，使用全本地配置。

**Comment by zhangleijun111** [comment]
> #3651
> 
> 你可以参考这个 PR，使用全本地配置。

他不是docker吧

**Comment by zhuozhiyongde** [comment]
又想了一下，这个可能是 Logto 域名的问题，我建议你多刷新几次，还不行就清空存储，用新的这个纯本地的方案重试一遍。

**Comment by zhangleijun111** [comment]
第一遍dockecompose起来是不是会有慢呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Arthals ***@***.***&gt;
发送时间: 2024年8月28日 19:04
收件人: lobehub/lobe-chat ***@***.***&gt;
抄送: zhangleijun111 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [lobehub/lobe-chat] [Bug你好我用最新的docker-compose部署教程，在logto里面撞见next.js应用就一直在转圈是为什么呀，第一步就被卡死了咯？？？？ (Issue #3644)





 
又想了一下，这个可能是 Logto 域名的问题，我建议你多刷新几次，还不行就清空存储，用新的这个纯本地的方案重试一遍。

**Comment by zhangleijun111** [comment]
我用了但是第一遍dockercompos会卡住是为什么有什么办法吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Arthals ***@***.***&gt;
发送时间: 2024年8月28日 17:27
收件人: lobehub/lobe-chat ***@***.***&gt;
抄送: zhangleijun111 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [lobehub/lobe-chat] [Bug你好我用最新的docker-compose部署教程，在logto里面撞见next.js应用就一直在转圈是为什么呀，第一步就被卡死了咯？？？？ (Issue #3644)





 
#3651
 
你可以参考这个 PR，使用全本地配置。

**Comment by zhuozhiyongde** [comment]
@zhangleijun111 这套配置我在 Ubuntu 和 Mac 上都测试正常... 我建议你不行搞个 WSL？

**Comment by zhuozhiyongde** [comment]
@zhangleijun111 是不是改了端口，或者做了端口映射，请保持 endpoint 和对应的  PORT 环境变量是一致的，并且 logto 的端口映射都是恒等映射，参见：

https://docs.logto.io/docs/references/core/configuration/

**Comment by zhuozhiyongde** [comment]
转圈圈是 CORS 的表现
