### ISSUE TITLE
[Request] 建议增加casdoor单点登录系统

### ISSUE THREAD

**Issue by chung1912** [lobehub/lobe-chat#3645]
### 🥰 需求描述

目前虽然有多种单点登录系统，但是要么就是需要公网，要么就是本地化配置比较麻烦，casdoor部署简单，且可视化界面操作管理方便。
虽然发现auth0的参数适配casdoor参数似乎可以正常登录，但不知道有没有什么问题。
建议还是新建一套专属于casdoor的参数加以适配

### 🧐 解决方案

增加casdoor单点登录系统

**Comment by arvinxx** [comment]
你试试看logto？

**Comment by chung1912** [comment]
> 你试试看logto？

用起来不太顺畅，那个casdoor上手更轻松

**Comment by cy948** [comment]
将来可以使用 #3647 的通用实现。如通用实现无法适配，可以期待社区使用 casdoor 的贡献者进行实现。

**Comment by chung1912** [comment]
> 将来可以使用 #3647 的通用实现。如通用实现无法适配，可以期待社区使用 casdoor 的贡献者进行实现。

目前除了clerk，内网环境都无法实现联动吧？就是单点登录系统删除用户，pv数据库里面的用户信息同步删除

**Comment by cy948** [comment]
@chung1912 有适配logto webhooks 的方案，可以实现你说的功能。但不能保证100%可靠。

**Comment by arvinxx** [comment]
确定计划新增 casdoor provider，并会替换 logto 作为 首次体验/NAS/ip  类的 SSO 首选方案。且会和 logto 一样新增 webhooks 实现

**Comment by chung1912** [comment]
> 确定计划新增 casdoor provider，并会替换 logto 作为 首次体验/NAS/ip 类的 SSO 首选方案。且会和 logto 一样新增 webhooks 实现

等这个很久了，非常期待

**Comment by yincangshiwei** [comment]
期待，期待，早点出。logto太麻烦了，而且有BUG。

**Comment by chung1912** [comment]
> 期待，期待，早点出。logto太麻烦了，而且有BUG。

看来不是只有我一个人不喜欢logto，哈哈
