### ISSUE TITLE
[Bug] 今天使用openai时，收到的回复的都是空白

### ISSUE THREAD

**Issue by DEUSJIN** [lobehub/lobe-chat#3648]
### 📦 Environment

Docker

### 📌 Version

1.14.4

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

使用的时候，连通性通过检查，但是每次回复的消息都是空白

![image](https://github.com/user-attachments/assets/bc40afc6-6236-401b-987a-27eda00de362)
![image](https://github.com/user-attachments/assets/6b53486b-ff59-44ad-beb8-9171515f39f9)

**Comment by arvinxx** [comment]
之前是正常的吗？试过降级不？ `v1` 有没有加？

**Comment by DEUSJIN** [comment]
@arvinxx 多谢，没看到你的消息，多折腾了好久，看官方手册整明白，加了v1就好了，这是什么原理？

**Comment by chung1912** [comment]
这个情况我也遇到过，不过换了家api就没出现了

**Comment by arvinxx** [comment]
> @arvinxx 多谢，没看到你的消息，多折腾了好久，看官方手册整明白，加了v1就好了，这是什么原理？

Openai 的标准请求接口地址是 


api.openai.com/v1/chat/completion

你不加的话就是

api.openai.com/chat/completion

请求不到自然就空了

**Comment by DEUSJIN** [comment]
> > @arvinxx 多谢，没看到你的消息，多折腾了好久，看官方手册整明白，加了v1就好了，这是什么原理？
> 
> Openai 的标准请求接口地址是
> 
> api.openai.com/v1/chat/completion
> 
> 你不加的话就是
> 
> api.openai.com/chat/completion
> 
> 请求不到自然就空了

噢噢，学到了，感谢
