### ISSUE TITLE
[Question] 如何配置多key

### ISSUE THREAD

**Issue by huanfeng123** [lobehub/lobe-chat#365]
### 🧐 问题描述 | Proposed Solution

如何配置多key进行调用
目前只是一个代理一个key
介绍上 没有说明告知如何进行多key调用
请问有这个功能 或者方法吗

**Comment by arvinxx** [comment]
目前暂不支持。请介绍下这个需求的场景？

**Comment by eightHundreds** [comment]
比如我有azure gpt4 api(免费额度).

但是我又想用openai gpt3.5(因为训练数据是最新的)

**Comment by yichen11818** [comment]
> 目前暂不支持。请介绍下这个需求的场景？

拥有多个3.5的key 轮询访问key可以防止限速

**Comment by mushan0x0** [comment]
可以用这个 https://github.com/songquanpeng/one-api

**Comment by zsio** [comment]
> 可以用这个 https://github.com/songquanpeng/one-api

我尝试了一下，好像不能用呀，您能正常使用吗？
