### ISSUE TITLE
[Bug] database版本需要postgresql安装vector插件

### ISSUE THREAD

**Issue by JonFanne** [lobehub/lobe-chat#3652]
### 📦 部署环境

Docker

### 📌 软件版本

最新版

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

<img width="939" alt="image" src="https://github.com/user-attachments/assets/0531b36c-e0b2-42c0-b947-5e8cf88e29d3">

### 🚦 期望结果

安装拓展方法以及支持的psql版本

**Comment by sxjeru** [comment]
https://github.com/pgvector/pgvector?tab=readme-ov-file#installation

**Comment by arvinxx** [comment]
文档都写这么清楚了，一点都不看的么…
