### ISSUE TITLE
[Bug] 无法使用 chatgpt-4o-latest 模型画图

### ISSUE THREAD

**Issue by breakstring** [lobehub/lobe-chat#3656]
### 📦 部署环境

Vercel

### 📌 软件版本

1.14.5

### 💻 系统环境

macOS

### 🌐 浏览器

Other

### 🐛 问题描述

 PWA 客户端。

无法使用 chatgpt-4o-latest 模型画图。

### 📷 复现步骤

1. Vercel 后台配置启用 chatgpt-4o-latest 模型： OPENAI_MODEL_LIST=-all,+gpt-4o-mini=GPT 4o mini,+chatgpt-4o-latest=GPT 4o (Latest)。并重新部署。
2. 启动新的会话，选中该模型，启用 DALL E3 插件。
3. 下达指令绘图，报错如下：
<img width="843" alt="image" src="https://github.com/user-attachments/assets/65d6cdea-3488-41f5-9f5a-f99ee793694d">
4. Vercel 后台可见对应错误
<img width="770" alt="image" src="https://github.com/user-attachments/assets/f016fc51-510d-4da9-8e5c-392bace0e557">

**Comment by arvinxx** [comment]
这个模型看起来不支持 tools …
