### ISSUE TITLE
[Bug] 求助，pdf文件上传后向量化失败，不知道哪里出问题了，请指教

### ISSUE THREAD

**Issue by lipc20052006** [lobehub/lobe-chat#3657]
### 📦 部署环境

Docker

### 📌 软件版本

1.14.4

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

[Bug] 求助，pdf文件上传后向量化失败，不知道哪里出问题了，请指教，所用的api是支持 OpenAI 的 text-embedding-3-small 模型的
![Uploading 微信图片_20240828230959.png…]()

![微信图片_20240828230959](https://github.com/user-attachments/assets/7c09ddf9-2375-465f-a1f9-656abca0f54d)

**Comment by lipc20052006** [comment]
使用了github的授权登录,以及CF的R2桶，word的向量化也失败了

**Comment by arvinxx** [comment]
试试换个 api供应商

**Comment by arvinxx** [comment]
感觉是没有 embedding 的模型

**Comment by lipc20052006** [comment]
> 感觉是没有 embedding 的模型

换了一个 api供应商，成功了，非常感谢。

**Comment by haibara1997** [comment]
> > 感觉是没有 embedding 的模型
> 
> 换了一个 api供应商，成功了，非常感谢。

可以推荐一个供应商吗

**Comment by haibara1997** [comment]
您好，已收到邮件，会尽快处理。黄雨润18917978061
