### ISSUE TITLE
[Bug] v0.95.0 ，小助手使用gpt-4-32k调用插件，出现无限循环

### ISSUE THREAD

**Issue by kdszh** [lobehub/lobe-chat#366]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

gpt-4-32k下，出现无限循环调用function call，直到ai token打满报错，有90%的几率出现此问题
![image](https://github.com/lobehub/lobe-chat/assets/2100801/84ee5977-6415-4399-8a3a-726b0b60b807)

同样的提问，gpt-3.5-turbo 下正常返回
![image](https://github.com/lobehub/lobe-chat/assets/2100801/c621f125-d653-4422-b03d-9c420ae411a3)

### 📝 补充信息 | Additional Information

我的环境：
1.lobechat版本： v0.95.0

2.OpenAI接口，使用了azure
```
export OPENAI_PROXY_URL=***
export USE_AZURE_OPENAI=1
export AZURE_API_VERSION=2023-07-01-preview
export AZURE_API_KEY=***
```
3.插件的gateway和manifest，main入口按照lobe plugin规范，使用python 的 flask 实现

**Comment by kdszh** [comment]
补充下：使用官方的插件（比如实时天气预报），在gpt-4-32k下，没试出这个无限循环

求指点下，如何在lobechat代码里增加一些调试信息，看看哪里出了问题？

**Comment by arvinxx** [comment]
这个大概率不是 LobeChat 的问题，而是 gpt-4 自己的判断问题。你可以试试把 message 脱离 LobeChat 直接发一次请求接口，应该也是这个情况。建议你优化下 function 中 api 的描述，可能能解决。

**Comment by kdszh** [comment]
嗯，我在 gpt-4 的网关加一些输出log来debug一下。另外有没可能在lobechat里加一个强制限制调用function的配置，比如我设置为1的话，那么lobechat只调1次funcition call，无论gpt4后续返回的数据是否还包含function信息，都不要管他（目前来看很大概率是gpt4每次都返回了functioncall信息导致的循环）

**Comment by arvinxx** [comment]
> 另外有没可能在lobechat里加一个强制限制调用function的配置，比如我设置为1的话，那么lobechat只调1次funcition call

这个可以，我构思下

**Comment by arvinxx** [comment]
@kdszh 顺带问下，有没有兴趣来贡献一个Python 语法的Lobe插件模板~

**Comment by arvinxx** [comment]
> 另外有没可能在lobechat里加一个强制限制调用function的配置，比如我设置为1的话，那么lobechat只调1次funcition call

https://github.com/lobehub/lobe-chat/discussions/345#discussioncomment-7324526

**Comment by kdszh** [comment]
> @kdszh 顺带问下，有没有兴趣来贡献一个Python 语言的Lobe插件模板~

可以的，我们先把这个python插件跑通
