### ISSUE TITLE
[Bug] 生成的照片次日看就打不开

### ISSUE THREAD

**Issue by ZeroDeng01** [lobehub/lobe-chat#3666]
### 📦 部署环境

Docker

### 📌 软件版本

latest

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 如下图，头天生成的照片今天打开话题照片打不开了，控制台查看返回的url似乎也不对，docker服务log无异常信息
![1](https://github.com/user-attachments/assets/17a9d651-cc39-4341-a291-cae01b190626)
![2](https://github.com/user-attachments/assets/882c909d-3beb-4148-8fd0-7bf34f0ae0c9)
### 以下是刚刚生成的照片可以查看，返回的url也没问题
![3](https://github.com/user-attachments/assets/c9a7edfc-811b-4add-b225-0c9a6623e9e8)
### 存储使用的R2，跨域也都正确设置
![image](https://github.com/user-attachments/assets/5fe02437-c2eb-473d-9230-295c5eadb22a)

似乎以上问题不是跨域问题，也不是防火墙等问题
似乎返回的照片地址是azure的地址不是我r2的地址https://dalleprodaue.blob.core.windows.net/

**Comment by arvinxx** [comment]
应该是生成的图片没有正常上传到 S3 导致的，你可以关注下这个位置，如果没有上传到 S3 的时候，这边会有 loading ，这个时候不能关页面，得让 loading 跑完才会正确存入 S3。

<img width="43" alt="image" src="https://github.com/user-attachments/assets/2365ae14-4280-4e11-ac31-e28133432c48">

如果没存入 S3 的话， DAllE 生成的图只能预览大概 1~2 小时，之后就会过期。

**Comment by ZeroDeng01** [comment]
> 应该是生成的图片没有正常上传到 S3 导致的，你可以关注下这个位置，如果没有上传到 S3 的时候，这边会有 loading ，这个时候不能关页面，得让 loading 跑完才会正确存入 S3。
> 
> <img alt="image" width="43" src="https://private-user-images.githubusercontent.com/28616219/362553901-2365ae14-4280-4e11-ac31-e28133432c48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTM1NTQsIm5iZiI6MTcyNDkxMzI1NCwicGF0aCI6Ii8yODYxNjIxOS8zNjI1NTM5MDEtMjM2NWFlMTQtNDI4MC00ZTExLWFjMzEtZTI4MTMzNDMyYzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA2MzQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkODU1ZDlhN2NmMzBiMGIzNjAwZjhjMDAwODM0Y2I2NTk2ODc1NTY4ZGVmMzkzM2VlYjQ4MTVhNGQ4ZmYyMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y4WlvN5mkBG4ctdRAOcqtS7ElSKelwspQmPjWauia-c">
> 如果没存入 S3 的话， DAllE 生成的图只能预览大概 1~2 小时，之后就会过期。

Thx~的确是我这边没上传成功就关闭了界面导致的~
