### ISSUE TITLE
[Request] 能否把自动获取到的非标准模型也增加自定义模型配置按钮

### ISSUE THREAD

**Issue by Mgrsc** [lobehub/lobe-chat#3671]
### 🥰 需求描述

能否把自动获取到的非标准模型也增加自定义模型配置，以便某些模型不会自动加上某些功能可以手动添加。
例如claude-3-5-sonnet不会自动加上视觉功能，只有标准的claude-3-5-sonnet-20240620才会。
例如新增加的glm-4v-plus可以自己手动加上视觉功能进行使用，不必等待更新。
![image](https://github.com/user-attachments/assets/c12689aa-6271-4b06-9644-a05b25656fa6)
![image](https://github.com/user-attachments/assets/e5496f50-7fa6-41c6-8b8c-a6b1a19a439e)
![image](https://github.com/user-attachments/assets/60a29eba-29ef-479a-86bd-548b2f4f2889)

### 🧐 解决方案

给非标准命名的模型也加上自定义模型配置按钮，让用户自己自定义模型配置

**Comment by arvinxx** [comment]
> 例如claude-3-5-sonnet不会自动加上视觉功能，只有标准的claude-3-5-sonnet-20240620才会。
> 例如新增加的glm-4v-plus可以自己手动加上视觉功能进行使用，不必等待更新。

这个你可以通过自定义 Model List 变量来实现，UI 上不计划加。https://lobehub.com/zh/docs/self-hosting/advanced/model-list
