### ISSUE TITLE
[Bug] 空引用源包含不属于我的文件

### ISSUE THREAD

**Issue by Fzkuji** [lobehub/lobe-chat#3674]
### 📦 部署环境

Official Preview

### 📌 软件版本

v1.14.6

### 💻 系统环境

macOS

### 🌐 浏览器

Safari

### 🐛 问题描述

我的引用源是空的，但是当我对话的时候（保持引用源开启），模型还是会尝试搜索引用源，但此时出现了一些其他的文件，我想这不是我的文件。虽然似乎这些引用源没有大小，并且提示找不到文件，但是这还是让我担心用户的文件夹内容会因此泄露？

<img width="840" alt="Screenshot 2024-08-30 at 11 37 29 AM" src="https://github.com/user-attachments/assets/d25e2c1d-31fd-4bd3-98ec-6897f2f20bac">

<img width="1109" alt="Screenshot 2024-08-30 at 11 38 23 AM" src="https://github.com/user-attachments/assets/fed3f668-3fb5-43e7-ac8c-9ece8e7a853e">

### 📷 复现步骤

创建一个空的知识库，然后和任意的模型对话，然后查看引用源

### 🚦 期望结果

引用源中有未知源头的文件，包括但不限于：

Handbuch für Kabelanlagen Band 1-097.pdf
4.EP04｜如何从零开始创建一家“伟大的企业”？.txt
6.#6 拉美版Stripe，不止于Stripe——对话FinTech公司Liquido CEO MK.txt
6.#6 拉美版Stripe，不止于Stripe——对话FinTech公司Liquido CEO MK.txt
16.#14 把新中式旗袍店开到米兰伦敦，品牌出海的核心是文化输出——对话BrandByMei创始人Mei.txt

这些内容令我迷惑

**Comment by arvinxx** [comment]
我排查下，应该是 bug

**Comment by arvinxx** [comment]
> 但是这还是让我担心用户的文件夹内容会因此泄露

这个不会的，我们做了用户维度的数据隔离，别人是看不到你的数据的。上述 bug 已经定位到问题，很快就能修复了

**Comment by arvinxx** [comment]
@Fzkuji 你好，已经修复，可以重试下看看~

**Comment by Fzkuji** [comment]
感谢你们及时的回复和修正，我这里显示bug已经消失

**Comment by arvinxx** [comment]
@Fzkuji 好的，有任何问题和体验建议也欢迎随时在 Discord 上私信我(arvinxu)~
