### ISSUE TITLE
[Bug] 更新数据库版本后部分模型无法识别到图片或者是文本文件内容

### ISSUE THREAD

**Issue by Nightrain0** [lobehub/lobe-chat#3675]
### 📦 Environment

Vercel

### 📌 Version

1.14.8

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome, Safari

### 🐛 Bug Description

![1](https://github.com/user-attachments/assets/db5541aa-e7ec-431f-8b02-ad711231c2ef)
只在更新数据库版本后出现这些情况，暂时不清楚是什么原因导致。另外自定义设置里面的Gemini测试也无法读取到上传的文本内容和图片。只有我遇到这样的问题吗？😢

**Comment by Nightrain0** [comment]
其实如果不使用数据库版本原来的Gemini是可以读取到txt文本内容的，不过现在加了限制，只能部署数据库版本了，但是也无法正常读取到内容

**Comment by breakstring** [comment]
估计也是 #3370 相关吧？

**Comment by sxjeru** [comment]
这边偶尔在卡顿时遇到类似问题，似乎图片消息没有附加进聊天请求，可以试试重新生成。
