### ISSUE TITLE
[Bug] 无法编辑用户侧对话内容

### ISSUE THREAD

**Issue by ganxiaozhe** [lobehub/lobe-chat#3679]
### 📦 Environment

Docker

### 📌 Version

v1.14.10

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

这是一个存在许久的问题，即当编辑用户消息时，只会显示 textarea 框，但没有右下角的操作键（取消和确认）。

**Comment by arvinxx** [comment]
重复 https://github.com/lobehub/lobe-chat/issues/3247
