### ISSUE TITLE
[Request] 对话界面启用停用插件

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#370]
### 🥰 需求描述 | Feature Description

目前插件启用停用有点麻烦，需要进入会话设置里

<img width="1064" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/843e5ef9-3f16-4ab2-a00a-9db4bbf5470d">

### 🧐 解决方案 | Proposed Solution

在输入框上面加个按钮，显示分页弹窗可能方便些，如果插件多了也方便查找

<img width="624" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/df844942-ddb0-43c5-8612-eb8635dbf7ed">

**Comment by arvinxx** [comment]
可以
