### ISSUE TITLE
[Bug] 打开浏览器应用时总是进入欢迎界面

### ISSUE THREAD

**Issue by huangwb8** [lobehub/lobe-chat#3718]
### 📦 部署环境

Docker

### 📌 软件版本

v1.15.2

### 💻 系统环境

Windows, Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

每次打开后都是welcome页面：

![image](https://github.com/user-attachments/assets/1a6923ac-1778-485e-88e0-25ef17b7d834)

但通常来说，welcome页面应该仅限于第1次登陆时。日常使用时建议跳转到chat页面。

### 📷 复现步骤

1. 使用edge浏览器访问自建lobechat 
2. 下载app
3. 打开app。每次关闭后再打开的首个页面是welcome页面

### 🚦 期望结果

打开应用时应该直接跳转到chat页面

### 📝 补充信息

暂无

**Comment by arvinxx** [comment]
你没有聊过消息把，只要消息数>0 就会进到 chat 页面的

**Comment by huangwb8** [comment]
@arvinxx  我已经聊过天了 ~ 我是按这里的教程配置的 ： https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose 

我以前用本地版的时候不会这样。 但服务器版会这样。

**Comment by arvinxx** [comment]
@huangwb8 那是不是你没登录呢？

**Comment by SpeedupMaster** [comment]
数据库版本确实会出现这个问题

**Comment by huangwb8** [comment]
在MacOS中，safari浏览器添加到程序坞的时候可以在链接后面加一个\chat后缀来间接处理这个总是。 但iPhone safari、windows edge则没有办法修改链接。就算见面访问的是带\chat后缀的，创建app时黑夜链接仍然是主域名。

**Comment by arvinxx** [comment]
@huangwb8 @SpeedupMaster 我测下来只要是登录态，消息数超过1，就不会跳转 welcome，你们的操作路径是什么样的？

**Comment by SpeedupMaster** [comment]
> @huangwb8 @SpeedupMaster 我测下来只要是登录态，消息数超过1，就不会跳转 welcome，你们的操作路径是什么样的？

直接输入网址 `lobe.example.com`就会跳到`lobe.example.com/welcome`

**Comment by huangwb8** [comment]
我用的是Microsoft Edge浏览器。 我将lobechat设置成一个浏览器的APP。登陆用户后，我关闭APP窗口再打开，它就会直接去到welcome页。 如GIF所示：

![NVIDIA_Share_zY4gTTbJZ7](https://github.com/user-attachments/assets/65df87cc-2de4-4055-8d7f-20db058aeafb)

**Comment by arvinxx** [comment]
@huangwb8 你此时登录了吗？

**Comment by huangwb8** [comment]
> @huangwb8 你此时登录了吗？

登陆状态

**Comment by arvinxx** [comment]
@huangwb8 哦 我好像复现了，我看下是啥原因

**Comment by htdohk** [comment]
> @huangwb8 哦 我好像复现了，我看下是啥原因

期待解决这个问题，非常影像服务器端+移动设备的使用体验
