### ISSUE TITLE
[Request] Logto 是否可以配置 Webhook

### ISSUE THREAD

**Issue by Matinal111** [lobehub/lobe-chat#3722]
### 🥰 需求描述

RT

### 🧐 解决方案

我知道 Clerk 是已经实现了配置 Webhook 接管用户鉴权与管理，在 Logto 中也看到有配置 Webhook 的选项，请问是否也可以实现

**Comment by cy948** [comment]
终于部署成功了，可以实现一下logto 的 webhook。 你希望实现哪些 webhooooks? 场景是什么？
![image](https://github.com/user-attachments/assets/8372452f-071b-4479-9c5d-4f5f513957fa)

**Comment by Matinal111** [comment]
> 终于部署成功了，可以实现一下logto 的 webhook。 你希望实现哪些 webhooooks? 场景是什么？ ![image](https://private-user-images.githubusercontent.com/67412196/364295939-8372452f-071b-4479-9c5d-4f5f513957fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0OTk1MTUsIm5iZiI6MTcyNTQ5OTIxNSwicGF0aCI6Ii82NzQxMjE5Ni8zNjQyOTU5MzktODM3MjQ1MmYtMDcxYi00NDc5LTljNWQtNGY1ZjUxMzk1N2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDAxMjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZWM3NDUwMmM5OThhNjg1NGUwNDdjZTViZGY2Nzk3MjE5ODI5MjY0MGExOGQ1OTM2NjU4YWVlMDc3N2Q4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VdWsb3n4eC266KgvG8R7jhr_-NcB-ZcjecMEpJ8OkK8)

https://github.com/lobehub/lobe-chat/issues/3722#issuecomment-2328261800
目前基础使用场景和 Clerk 一样，实现在用户属性发生变化时通知应用并同步数据库
