### ISSUE TITLE
[Request] Please add ANTHROPIC_MODEL_LIST for Anthropic AI

### ISSUE THREAD

**Issue by blueblizza** [lobehub/lobe-chat#3726]
### 🥰 Feature Description

Add ANTHROPIC_MODEL_LIST for Anthropic AI, so that we could use third-party provider's Anthropic AI model like "claude-3-5-sonnet" (no date and version).

### 🧐 Proposed Solution

Add ANTHROPIC_MODEL_LIST as OPENAI_MODEL_LIST did.

**Comment by arvinxx** [comment]
PR Welcome
