### ISSUE TITLE
[Request] 提供一种轻量的，无特效的前端模式，改善性能问题

### ISSUE THREAD

**Issue by JustusPan** [lobehub/lobe-chat#3728]
### 🥰 Feature Description

提供一种部署模式，允许我们使用一个
简约的轻量的前端界面。

当Edge浏览器未开启图形加速功能时，lobechat默认界面的大头小人动画可以占cpu70%。
![image](https://github.com/user-attachments/assets/016b150c-d97d-41d0-b16f-e792b9ad9860)

这对于一些性能不太好的设备来说是个不小的负担。我不知道是否还有其他情况会显著影响性能以及这是否是移动设备访问lobechat性能不佳的原因之一。
个人认为lobechat的核心功能完全可以运行在一个没有花哨特效的前端上。是否可以提供一种部署模式，允许我们使用一个
简约的轻量的前端界面。

### 🧐 Proposed Solution

是否可以取消一些动效和装饰性的效果？

**Comment by VectorZhao** [comment]
希望支持，目前的UI确实比较卡顿

**Comment by arvinxx** [comment]
目前通过 #4085 已经移除部分动态模糊特效，应该能提升一部分速度。可以试试看。

后续会进一步提供配置开关，支持不使用 3D 头像，以提升性能

**Comment by Smart-SangGe** [comment]
同意，我在分享给别人使用时的时候，第一次加载总是非常缓慢，甚至出现了超时加载错误的问题，反馈给我的问题是前端的js较多，本身网站带宽也小。

**Comment by arvinxx** [comment]
目前已经移除 welcome 页面，同时加入了首屏的 loading 状态，我理解应该能改善一些性能问题了。
