### ISSUE TITLE
[Request] Auto comment feature

### ISSUE THREAD

**Issue by shraddha761** [lobehub/lobe-chat#374]
### 🥰 需求描述 | Feature Description

While user create issue , assigned bot while send a message accordingly

### 🧐 解决方案 | Proposed Solution

I create a workflow which will send message 

### 📝 补充信息 | Additional Information

Assign this issue to me

**Comment by shraddha761** [comment]
@canisminor1990 please review my issue

**Comment by canisminor1990** [comment]
merge
