### ISSUE TITLE
[Request] logto 切换为mail注册后因为无username传入数据库,可以加入一个mail 作为标识嘛?

### ISSUE THREAD

**Issue by yelc66** [lobehub/lobe-chat#3749]
### 🥰 需求描述

![image](https://github.com/user-attachments/assets/7b5583d3-e975-4f9a-a2c5-13ab001d52a6)

### 🧐 解决方案

或是可以设置哪里解决这个问题嘛

**Comment by cy948** [comment]
如果用户有`name`信息，也会进行显示。 你可以对用户的`name`信息进行更改。至于能否生效还要看 #3774  实现。 此处显示的判断逻辑： https://github.com/lobehub/lobe-chat/blob/0c4efe4b33f6f26f5b2c4d3b48e8e9c9ccac8fdf/src/store/user/slices/auth/selectors.ts#L9-L15

**Comment by arvinxx** [comment]
@cy948 我感觉应该参考下 `generic-oidc` 的实现，name 那边用 `name: profile.name ?? profile.username ?? profile.email`
