### ISSUE TITLE
[Bug] 第一条消息附带图片失败

### ISSUE THREAD

**Issue by Borber** [lobehub/lobe-chat#3760]
### 📦 部署环境

Docker

### 📌 软件版本

v1.15.10

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

第一条消息未携带图片

### 📷 复现步骤

![CleanShot 2024-09-04 at 10 16 49@2x](https://github.com/user-attachments/assets/6168125c-91b8-4590-9cb1-a3792b4a809b)

![CleanShot 2024-09-04 at 10 19 51@2x](https://github.com/user-attachments/assets/cf3d1789-4ec8-43cd-b67f-79f4d662e394)

### 🚦 期望结果

正常携带图片

**Comment by sqkkyzx** [comment]
我也有这种情况，另外补充，我这边不只是第一张图片失败，后面所有的图片，按下发送的时候都是没有携带图片的，会生成前一条消息中的图片的信息。我手动停止，然后点`删除并重新生成` 按钮，才能正常。

**Comment by sxjeru** [comment]
相同问题，在服务端数据库环境下亦存在。

**Comment by redapple0204** [comment]
相同问题
