### ISSUE TITLE
[Bug]logto穿件next.js报错问题

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#3761]
### 📦 Environment

Docker

### 📌 Version

centos

### 💻 Operating System

Other

### 🌐 Browser

Chrome

### 🐛 Bug Description

headers: {
'Access-Control-Allow-Origin': 'https://lobe-auth-ui.example.com',
'Access-Control-Expose-Headers': '*',
vary: 'Origin'
},
[cause]: Error: getaddrinfo ENOTFOUND lobe-auth-ui.example.com
at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'lobe-auth-ui.example.com'
}
}
YACmfmxk1AOZwzMy --> POST /api/applications 500 1,015ms 36b
这是另外一段报错的日志信息可以帮我看一下原因嘛  我的dns指向本机而且可以ping通

### 📷 Recurrence Steps

报错截图
![Uploading b1c819c221227a68e209381d316f7e1.png…]()

**Comment by bughoho** [comment]
这个问题为什么关闭了？我有相同的问题，ps：我的域名绑定的是IPV6的地址，用群晖内置代理从13001反向代理到3001出错的，不知道是不是因为不支持IPV6
下面是错误日志：
KqjYs19QqwIHuPzb error TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async function_ (file:///etc/logto/node_modules/.pnpm/ky@1.2.3/node_modules/ky/distribution/core/Ky.js:18:28)
    at async Ky._retry (file:///etc/logto/node_modules/.pnpm/ky@1.2.3/node_modules/ky/distribution/core/Ky.js:215:20)
    at async result.<computed> [as json] (file:///etc/logto/node_modules/.pnpm/ky@1.2.3/node_modules/ky/distribution/core/Ky.js:54:39)
    at async getAdminTenantTokenValidationSet (file:///etc/logto/packages/core/build/main-F72FFTZD.js:4148:25)
    at async getKeysAndIssuer (file:///etc/logto/packages/core/build/main-F72FFTZD.js:4197:22)
    at async verifyBearerTokenFromRequest (file:///etc/logto/packages/core/build/main-F72FFTZD.js:4204:28)
    at async authMiddleware (file:///etc/logto/packages/core/build/main-F72FFTZD.js:4230:48)
    at async file:///etc/logto/packages/core/build/main-F72FFTZD.js:2106:5
    at async cors (/etc/logto/node_modules/.pnpm/@koa+cors@5.0.0/node_modules/@koa/cors/index.js:109:16)
    at async /etc/logto/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:58:5
    at async /etc/logto/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:52:26
    at async compressMiddleware (/etc/logto/node_modules/.pnpm/koa-compress@5.1.1/node_modules/koa-compress/lib/index.js:56:5)
    at async file:///etc/logto/packages/core/build/main-F72FFTZD.js:743:7
    at async file:///etc/logto/packages/core/build/main-F72FFTZD.js:1229:7 {
  headers: {
    'Access-Control-Allow-Origin': 'https://example.icu:13002',
    'Access-Control-Expose-Headers': '*',
    vary: 'Origin'
  },
  [cause]: Error: getaddrinfo ENOTFOUND example.icu
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'example.icu'
  }
}

**Comment by zhangleijun111** [comment]
没有关我只是觉得logto太难了，试试看新出来的casdoor而已，我logto试了一个月生产部署都不行





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bughoho ***@***.***&gt;
发送时间: 2024年9月25日 15:13
收件人: lobehub/lobe-chat ***@***.***&gt;
抄送: zhangleijun111 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [lobehub/lobe-chat] [Bug]logto穿件next.js报错问题 (Issue #3761)





 
这个问题为什么关闭了？我有相同的问题，ps：我的域名绑定的是IPV6的地址，用群晖内置代理从13001反向代理到3001出错的，不知道是不是因为不支持IPV6
 下面是错误日志：
 KqjYs19QqwIHuPzb error TypeError: fetch failed at node:internal/deps/undici/undici:13178:13 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async function_ ***@***.***/node_modules/ky/distribution/core/Ky.js:18:28) at async Ky._retry ***@***.***/node_modules/ky/distribution/core/Ky.js:215:20) at async result.<computed&gt; [as json] ***@***.***/node_modules/ky/distribution/core/Ky.js:54:39) at async getAdminTenantTokenValidationSet (file://localhost/etc/logto/packages/core/build/main-F72FFTZD.js:4148:25) at async getKeysAndIssuer (file://localhost/etc/logto/packages/core/build/main-F72FFTZD.js:4197:22) at async verifyBearerTokenFromRequest (file://localhost/etc/logto/packages/core/build/main-F72FFTZD.js:4204:28) at async authMiddleware (file://localhost/etc/logto/packages/core/build/main-F72FFTZD.js:4230:48) at async file://localhost/etc/logto/packages/core/build/main-F72FFTZD.js:2106:5 at async cors ***@***.******@***.******@***.***/cors/index.js:109:16) at async ***@***.***/node_modules/koa-mount/index.js:58:5 at async ***@***.***/node_modules/koa-mount/index.js:52:26 at async compressMiddleware ***@***.***/node_modules/koa-compress/lib/index.js:56:5) at async file://localhost/etc/logto/packages/core/build/main-F72FFTZD.js:743:7 at async file://localhost/etc/logto/packages/core/build/main-F72FFTZD.js:1229:7 { headers: { 'Access-Control-Allow-Origin': 'https://example.icu:13002', 'Access-Control-Expose-Headers': '*', vary: 'Origin' }, [cause]: Error: getaddrinfo ENOTFOUND example.icu at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) { errno: -3007, code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'example.icu' } }
