### ISSUE TITLE
[Bug] 使用Docker部署并frp、CF Tunnels进行https转发后无法正常使用

### ISSUE THREAD

**Issue by aiqinxuancai** [lobehub/lobe-chat#3763]
### 📦 部署环境

Docker

### 📌 软件版本

最新

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

我在unraid中使用docker部署了lobe-chat，从本地ip访问 http://172.16.1.13:3210/ 一切正常，输入访问密码后可以正常对话。

然后我将此地址通过frp以及cf Tunnels使用https域名访问，这两个均在对话时出现如下错误

```
{
  "error": {
    "code": "ERR_JWT_EXPIRED",
    "name": "s",
    "claim": "exp",
    "reason": "check_failed",
    "payload": {
      "accessCode": "xxxxxx",
      "userId": "166e28dd-8fdd-4004-b6bb-ae8478b0700c",
      "iat": 1725438857,
      "exp": 1725438957
    }
  },
  "code": "ERR_JWT_EXPIRED",
  "name": "s",
  "claim": "exp",
  "reason": "check_failed",
  "payload": {
    "accessCode": "xxxxxx",
    "userId": "166e28dd-8fdd-4004-b6bb-ae8478b0700c",
    "iat": 1725438857,
    "exp": 1725438957
  },
  "provider": "openai"
}
```

![image](https://github.com/user-attachments/assets/cd052576-bb9f-470f-8f79-e81e42ef1bfc)

### 📷 复现步骤

通过docker部署，并在公网通过转发，https域名访问

### 🚦 期望结果

能和内网一样使用

### 📝 补充信息

我查找之前的issues，看到有说时间问题，我核对了服务器时间和本地时间均没有任何问题，并且2个域名无法访问的同时，内网地址保持正常使用。

**Comment by aiqinxuancai** [comment]
我测试将内网端口通过frp转发为HTTP协议时，一切正常，我认为是仅转发为HTTPS时存在问题，结合输出的iat和exp相差100秒，我找到了此文件，我觉得这个函数对HTTPS的转发处理可能存在问题。
https://github.com/lobehub/lobe-chat/blob/77243e12a4c9b538d54524e793cac0dda3d3839c/src/utils/jwt.ts#L7

**Comment by arvinxx** [comment]
是不是存在时区差异导致转发时间计算不对呢？

**Comment by aiqinxuancai** [comment]
> 是不是存在时区差异导致转发时间计算不对呢？

时区如果是差的话，不会只100秒，而且主要是，内网通过HTTP访问完全没问题。。。

**Comment by arvinxx** [comment]
能详细介绍下你的请求链路吗？

**Comment by aiqinxuancai** [comment]
> 能详细介绍下你的请求链路吗？

在Unraid中直接部署非数据库版本，对外的端口是3210，内网IP访问和使用均正常。
然后我有一台有公网IP的设备，上面装了frps，在本地使用frp映射https协议，配置如下
```
[[proxies]]
name = "lbhttps"
type = "https"
customDomains = ["lb.xxxxxx.me"]
[proxies.plugin]
type = "https2http"
localAddr = "172.16.1.13:3210"
crtPath = "/etc/frp/cert/lb.xxxxxx.me.pem"
keyPath = "/etc/frp/cert/lb.xxxxxx.me.key"
requestHeaders.set.x-from-where = "frp"
```
xxxxxx为隐去的部分。

映射后，访问域名httsp://lb.xxxxxx.me:xxxx可以正常访问到页面，但发送任何对话内容，均是返回我主体上所说的错误信息。

同一时刻，访问http://172.16.1.13:3210，一切正常。

---

然后我认为可能是frp有什么问题，然后使用了cf tunnels内网穿透映射，穿透出来也是https+域名访问，同样是能访问，但无法会话。

**Comment by arvinxx** [comment]
这个 JWT 抛错的含义是， payload 鉴权 token 过期。你看到的 100s 是指过期时间是 100s。

<img width="664" alt="image" src="https://github.com/user-attachments/assets/8cc1661a-c0ea-4f12-8c6b-4415d08fc09e">

建议你检查下你的本地 docker 镜像的时区是否是和你电脑一致的。如果时区不一致是有可能导致这个问题的。

-----

纯 HTTP 访问正常的原因是在构造 JWT 时 http 模式下会不做加密直接 base64 一下传递，服务端解析的时候针对 http 的场景是用的另外一套验证逻辑

**Comment by aiqinxuancai** [comment]
> 这个 JWT 抛错的含义是， payload 鉴权 token 过期。你看到的 100s 是指过期时间是 100s。
> 
> <img alt="image" width="664" src="https://private-user-images.githubusercontent.com/28616219/365538088-8cc1661a-c0ea-4f12-8c6b-4415d08fc09e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjQ1NzMsIm5iZiI6MTcyNTg2NDI3MywicGF0aCI6Ii8yODYxNjIxOS8zNjU1MzgwODgtOGNjMTY2MWEtYzBlYS00ZjEyLThjNmItNDQxNWQwOGZjMDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA2NDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNDdmZWRhNDdkMmVhMjZmMmNmNmZhM2QzZWFhYzdjOWIzMDg5NGFmOGZlODU4Mzk0NTMwYzAwYmZhNTlhNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p2ZH7O24KvNzQomVDVoSE7lBOHT79Zw9EqyJpExlabw">
> 建议你检查下你的本地 docker 镜像的时区是否是和你电脑一致的。如果时区不一致是有可能导致这个问题的。
> 
> 纯 HTTP 访问正常的原因是在构造 JWT 时 http 模式下会不做加密直接 base64 一下传递，服务端解析的时候针对 http 的场景是用的另外一套验证逻辑

我要检查一下是不是unraid的时间有什么问题

**Comment by aiqinxuancai** [comment]
> 这个 JWT 抛错的含义是， payload 鉴权 token 过期。你看到的 100s 是指过期时间是 100s。
> 
> <img alt="image" width="664" src="https://private-user-images.githubusercontent.com/28616219/365538088-8cc1661a-c0ea-4f12-8c6b-4415d08fc09e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjQzOTksIm5iZiI6MTcyNTg2NDA5OSwicGF0aCI6Ii8yODYxNjIxOS8zNjU1MzgwODgtOGNjMTY2MWEtYzBlYS00ZjEyLThjNmItNDQxNWQwOGZjMDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA2NDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYmY3OTBmYjg1YWE5ZWUyNWQwOTU5NTJiODNmMjA4NWE0MGMxMzViYjA3YTNiNzEyMGZjZWZiOTk5MWJiNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MuOeWJBO9W5WG7QJNpvV7ZBAPa3XTcZwpJ1G1PT1ZB8">
> 建议你检查下你的本地 docker 镜像的时区是否是和你电脑一致的。如果时区不一致是有可能导致这个问题的。
> 
> 纯 HTTP 访问正常的原因是在构造 JWT 时 http 模式下会不做加密直接 base64 一下传递，服务端解析的时候针对 http 的场景是用的另外一套验证逻辑

给unraid自己写了个docker进去输出了一下UTC时间，确实时间不正确，检查发现系统的ntp没生效，似乎没正确更新。问题已解决，感谢！
