### ISSUE TITLE
[Bug] 聊天窗口样式设为文档模式时，编辑后无法保存聊天信息

### ISSUE THREAD

**Issue by mcthesw** [lobehub/lobe-chat#3765]
### 📦 部署环境

Official Preview

### 📌 软件版本

v1.15.11

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

1. 设置窗口聊天样式为文档模式
![image](https://github.com/user-attachments/assets/b9b5689d-7848-4145-983b-e84a63f5c782)
2. 进行聊天
3. 发现修改之前的聊天信息后，无法保存（按钮消失了）
![image](https://github.com/user-attachments/assets/5e69110f-9756-4123-b790-5577d6b83018)

### 🚦 期望结果

让“对话模式”中存在的取消、确定按钮在“文档模式”中也能显示
![image](https://github.com/user-attachments/assets/cad50325-ed97-42c8-ab71-97aa65459356)

**Comment by adminewacc** [comment]
i think that should be tagged as feature request

**Comment by mcthesw** [comment]
> i think that should be tagged as feature request

Why do you think so? I think it should be a bug that allows you to enter editing mode but cannot exit or save the editing results

**Comment by adminewacc** [comment]
> > i think that should be tagged as feature request
> 
> Why do you think so? I think it should be a bug that allows you to enter editing mode but cannot exit or save the editing results

yea, you are right. my bad

**Comment by adminewacc** [comment]
i will try to solve this too, If I can, I will say it here

**Comment by adminewacc** [comment]
i solved
