### ISSUE TITLE
[Request] 能否实现自定义添加同一个接口类型的多个api服务提供商，现在每种接口类型只能添加一个

### ISSUE THREAD

**Issue by vjeson** [lobehub/lobe-chat#3773]
### 🥰 需求描述

能否实现自定义添加同一个接口类型的多个api服务提供商， 现在可以配置每个模型接口ai代理服务地址，但是每种类型的接口只能配置一个，比如openai接口类型的模型，只能设置一个代理地址，实际使用中，可以购买了从不同的服务器提供的openai模型，希望能够自定义添加每种模型，多个服务提供商

### 🧐 解决方案

现在可以配置每个模型接口ai代理服务地址，但是每种类型的接口只能配置一个，比如openai接口类型的模型，只能设置一个代理地址，实际使用中，可以购买了从不同的服务器提供的openai模型，希望能够自定义添加每种模型，多个服务提供商

**Comment by Lynricsy** [comment]
感觉这个可以通过自搭建api中转的形式管理更好？🤔

**Comment by arvinxx** [comment]
建议采用 oneapi/newapi 的方案，我不太想在 LobeChat 里加渠道管理的能力
