### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by havelhuang** [lobehub/lobe-chat#3777]
### 📦 Environment

Vercel

### 📌 Version

1.15.12

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

无法打开lobechat,要么被开在开启加载界面，要没显示报错。
![Uploading 截屏2024-09-05 16.51.41.png…]()

**Comment by sxjeru** [comment]
烦请附上报错内容，并检查截图是否正确上传。
