### ISSUE TITLE
在vps上用dockercompose生产部署，环境变量不生效[Bug] 

### ISSUE THREAD

**Issue by whistle003** [lobehub/lobe-chat#3790]
### 📦 Environment

Docker

### 📌 Version

1.15.12

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/64237a3d-05bf-4276-9896-a3ee8eed354e)
在vps上用dockercompose生产部署，其他功能正常，OpenAI API Key 这个环境变量不生效，环境变量配置如下：
![image](https://github.com/user-attachments/assets/8067c0d2-c137-4562-8b98-70faa9641195)

**Comment by SpeedupMaster** [comment]
PROXY_URL去掉v1试试

**Comment by whistle003** [comment]
已解决，请关闭

**Comment by Zoumachuan** [comment]
> 已解决，请关闭

请问如何解决的？

**Comment by whistle003** [comment]
> > 已解决，请关闭
> 
> 请问如何解决的？

官方文档的openaikey参数拼写错误
