### ISSUE TITLE
Dockercompose进阶部署，上传文件失败

### ISSUE THREAD

**Issue by whistle003** [lobehub/lobe-chat#3793]
### 📦 部署环境

Docker

### 📌 软件版本

1.15.13

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/user-attachments/assets/734cb362-52c0-4d0b-a400-c1877eb4364a)
上传除了图片以外的文件都提示失败，报错如图。模型是gpt-4o-mini+DALL `E3
我直接在文件管理界面是可以上传文件的，对话框上传就提示如上图

**Comment by arvinxx** [comment]
因为你的 KeyVault 不对吧，建议检查下

**Comment by whistle003** [comment]
> 因为你的 KeyVault 不对吧，建议检查下

大佬，这个在哪儿检查？

**Comment by whistle003** [comment]
> 因为你的 KeyVault 不对吧，建议检查下

我是用base32随机生成的32位数

**Comment by whistle003** [comment]
> 因为你的 KeyVault 不对吧，建议检查下

已经解决了，确实是KeyVault的问题，感谢大佬

**Comment by KingDoum** [comment]
请教一下

遇到过上传卡住的情况么？
我f12 查看 报错的是这个 ，但是我的minio 是按照 配置操作的。
唯一怀疑的就是 我的代理地址 不知道有没有填对。
docker配置文件
'MINIO_DOMAIN=lobe-s3-api.example.xyz'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=https://lobe.example.xyz:4443

[
    {
        "error": {
            "json": {
                "message": "S3 environment variables are not set completely, please check your env",
                "code": -32603,
                "data": {
                    "code": "INTERNAL_SERVER_ERROR",
                    "httpStatus": 500,
                    "path": "upload.createS3PreSignedUrl"
                }
            }
        }
    }
]
