### ISSUE TITLE
对话框里如果代码行数过多，格式会错乱[Bug] 

### ISSUE THREAD

**Issue by whistle003** [lobehub/lobe-chat#3799]
### 📦 Environment

Official Preview, Docker

### 📌 Version

1.15.18

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/2ee419b7-2b0c-4fd5-bb80-610949ed5401)
![image](https://github.com/user-attachments/assets/409b9f8e-cb04-4638-b8d1-3947b2824350)

如图所示，我把一段130多行的代码复制给lobechat，它的显示是错乱的，有的是文本格式有的是代码段格式，这样看着很不美观，请教各位有什么办法避免这种情况吗？

**Comment by sxjeru** [comment]
相关解决方案：#3507

**Comment by arvinxx** [comment]
手动加一下 ```
