### ISSUE TITLE
[Bug] 流式传输有时候会变成大段大段的输出

### ISSUE THREAD

**Issue by Lynricsy** [lobehub/lobe-chat#3800]
### 📦 部署环境

Docker

### 📌 软件版本

1.15.18

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

api返回的内容是流式传输的，但是最终在lobechat展现的却是大段大段的输出，一次输出好几行，每次输出中间卡一小段时间，显得非常卡顿
![image](https://github.com/user-attachments/assets/e7de0aef-9f6e-4ad1-9cdc-cf13b66c7ac9)

### 📷 复现步骤

正常对话，输入一段文字并发送

### 🚦 期望结果

正常一个字一个字的流式输出

**Comment by Lynricsy** [comment]
Chrome也测试过了，有同样的问题

**Comment by Lynricsy** [comment]
已经打开了在浏览器端发起请求的选项。

**Comment by Lynricsy** [comment]
> 已经打开了在浏览器端发起请求的选项。

如果关闭这个选项，反而不会出现这个问题

**Comment by Lynricsy** [comment]
我发现如果输入后等待时间较长，关闭浏览器端请求后也会出现这个问题，甚至有时候会整个答复一起出现

**Comment by imwito** [comment]
> > 已经打开了在浏览器端发起请求的选项。
> 
> 如果关闭这个选项，反而不会出现这个问题

我在使用 Azure OpenAI 时也遇到类似的问题：关闭浏览器端的请求时，可以正常流式输出；但开启后，不仅输出变得断断续续，而且在内容较多时非常容易卡死。
