### ISSUE TITLE
[Bug] Cannot change/No avatar in the database version

### ISSUE THREAD

**Issue by zylinzzz** [lobehub/lobe-chat#3802]
### 📦 Environment

Docker

### 📌 Version

v1.15.18

### 💻 Operating System

macOS, Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

The database version is deployed on Debian 12, with the Chrome client on macOS. The avatar is not displaying properly, and the error message reads: "Error while trying to use the following icon from the Manifest: https://mywebsite.xxx/icons/icon-192x192.png?v=1 (Download error or resource isn't a valid image)."
<img width="252" alt="image" src="https://github.com/user-attachments/assets/c3d9a9e8-a279-4812-aaab-9b4e08015c29">

In Common settings, the "Avatar" option is unavailable in the database version but is available in the no-database version, as shown below:
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/a5b9323a-67ed-4345-b79b-a1a9721c8747">

Both of them are v1.15.18.

**Comment by arvinxx** [comment]
Yes. currently we don't support change avtar in server database mode. Because we use SSO as auth provider. we will support webhooks (logto/casdoor) to support update avatar

**Comment by jorben** [comment]
用户名好像也没拉取过来
<img width="320" alt="image" src="https://github.com/user-attachments/assets/4e1dc824-7beb-4190-88c0-bf2f134f5fa7">

**Comment by arvinxx** [comment]
supported with casdoor: https://lobehub.com/docs/self-hosting/server-database/docker-compose
