### ISSUE TITLE
[Bug] 报错

### ISSUE THREAD

**Issue by Mabisi** [lobehub/lobe-chat#3807]
### 📦 Environment

Vercel

### 📌 Version

v1.15.18

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

报错！
![image](https://github.com/user-attachments/assets/e4378198-6ba5-4f8a-a12a-dd3a6b3e498f)

**Comment by arvinxx** [comment]
请给出更详细的抛错说明
