### ISSUE TITLE
[Bug]Docker Compose 部署 LobeChat 服务端数据库版本 logto访问重定向问题

### ISSUE THREAD

**Issue by gmksbk** [lobehub/lobe-chat#3811]
### 📦 Environment

Docker

### 📌 Version

1.22

### 💻 Operating System

Other

### 🌐 Browser

Chrome

### 🐛 Bug Description

Docker Compose 部署 LobeChat 服务端数据库版本，logto安装配置完成后，访问[http://localhost:3002的时候出现重定向错误：http://localhost:3001/unknown-session
容器内命令行wget http://localhost:3002访问logto管理界面是正常的。后台日志也正常。请问这是什么原因？配置如下：
  logto:
    image: svhd/logto
    container_name: lobe-logto
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'TRUST_PROXY_HEADER=1'
      - 'PORT=3001'
      - 'DB_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/logto'
      - 'ENDPOINT=http://localhost:3001'
      - 'ADMIN_PORT=3002'
      - 'ADMIN_DISABLE_LOCALHOST=false'
      - 'ADMIN_ENDPOINT=http://localhost:3002'
      - 'CORS_ALLOWED_ORIGINS=http://localhost:3002'     #（跨域问题追加的变量）
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']

**Comment by arvinxx** [comment]
重复 #3809
