### ISSUE TITLE
[Docs] Feedback for `self-hosting/server-database/docker-compose`

### ISSUE THREAD

**Issue by BiFangKNT** [lobehub/lobe-chat#3826]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/server-database/docker-compose.zh-CN.mdx

### 🐛 Feedback

附录中的“发布到生产”中的docker-compose.yml及[此配置文件链接](https://raw.githubusercontent.com/lobehub/lobe-chat/HEAD/docker-compose/production/docker-compose.yml)中的配置信息有误，前面`lobe-postgres`中设置的数据库名为`lobe`，在后面`lobe-logto`中的`DB_URL`的值却是`logto`，按照这个配置文件启动的话，会因为`logto`数据库不存在而报错

**Comment by BiFangKNT** [comment]
另外`postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/logto`这种写法也是错误的，host地址应该写`container_name`，也就是`lobe-postgres`，而不是服务名称（`postgresql`）

**Comment by zhuozhiyongde** [comment]
你说错了 hhh，不是 logto 的数据库有误，是 lobechat 的写错啦（

**Comment by BiFangKNT** [comment]
> 你说错了 hhh，不是 logto 的数据库有误，是 lobechat 的写错啦（

你要不看看我上面贴的链接？我说的就是lobechat的官方教程文档有错啊

**Comment by zhuozhiyongde** [comment]
lobe 数据库是 lobechat 自身用的，logto 数据库才是 logto 用的，虽然 postgres 里没有指明要创建 logto 数据库，但是 logto 会自己创建的

**Comment by zhuozhiyongde** [comment]
所以实际上错误的原因就是，之前的配置里，postgres 默认创建了 lobe 数据库，但是 lobechat 的环境变量指定的是 postgres 数据库，由于 lobechat 不会在没找到的情况下自己创建，所以这里导致了错误。

**Comment by BiFangKNT** [comment]
> lobe 数据库是 lobechat 自身用的，logto 数据库才是 logto 用的，虽然 postgres 里没有指明要创建 logto 数据库，但是 logto 会自己创建的

并不是，配置文件.env里设置了lobe的数据库是默认数据库`postgres`，所以根本用不到这个`lobe`数据库

**Comment by BiFangKNT** [comment]
> 所以实际上错误的原因就是，之前的配置里，postgres 默认创建了 lobe 数据库，但是 lobechat 的环境变量指定的是 postgres 数据库，由于 lobechat 不会在没找到的情况下自己创建，所以这里导致了错误。

`postgres`是默认创建的，并不会找不到

**Comment by zhuozhiyongde** [comment]
docker-compose 里指定了 POSTGRES_DB=lobe 啊

**Comment by BiFangKNT** [comment]
> docker-compose 里指定了 POSTGRES_DB=lobe 啊

这是lobe-postgres创建数据库的命令，和lobe调用哪个数据库是相互独立的，在.env里就是设置了lobe调用`postgres`数据库

**Comment by BiFangKNT** [comment]
> docker-compose 里指定了 POSTGRES_DB=lobe 啊

我好像理解你的想法了，你以为这是指定默认数据库名的环境变量吗？其实并不是，这是创建新数据库的环境变量，并不会影响默认数据库`postgres`的创建

**Comment by zhuozhiyongde** [comment]
你的意思是，无论是否指定了  POSTGRES_DB，都会创建一个 postgres 的库？

但如果是这样的话，原有的写法应该不会报错啊，只是多创建了一个用不上的 lobe 库。

我确定了 logto 是会在没有创建数据库的情况下自动创建 URL 的库的，我这边已经跑起来了呀

**Comment by zhuozhiyongde** [comment]
嗯，看了一眼，确实是不吃这个变量，默认创建 postgres 库，但是 logto 也确实自己创建了不存在的 logto 数据库。

**Comment by zhuozhiyongde** [comment]
这是到我 PR 之后的 production 目录下直接

```bash
cp .env.example .env
docker compose up -d
```

的结果：

![image](https://github.com/user-attachments/assets/b4586814-3e61-49b9-981b-4800ed627760)

**Comment by BiFangKNT** [comment]
> 你的意思是，无论是否指定了 POSTGRES_DB，都会创建一个 postgres 的库？
> 
> 但如果是这样的话，原有的写法应该不会报错啊，只是多创建了一个用不上的 lobe 库。
> 
> 我确定了 logto 是会在没有创建数据库的情况下自动创建 URL 的库的，我这边已经跑起来了呀

你是pgvector/pgvector:pg16这个镜像吗？我不太清楚，反正我把数据库名改了之后就不会报这个错了。但是有一个错一直没办法解决，就是我的logto一直报我的logto api域名的dns错误，不管是云logto还是自部署都是，但是我这个域名我很确定是正常解析的，总不会是只有公网v6没有v4导致的吧？这个问题我在别的议题里也提过了

**Comment by BiFangKNT** [comment]
> 这是到我 PR 之后的 production 目录下直接
> 
> ```shell
> cp .env.example .env
> docker compose up -d
> ```
> 
> 的结果：
> 
> ![image](https://private-user-images.githubusercontent.com/36695271/365449002-b4586814-3e61-49b9-981b-4800ed627760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDk3NTgsIm5iZiI6MTcyNTgwOTQ1OCwicGF0aCI6Ii8zNjY5NTI3MS8zNjU0NDkwMDItYjQ1ODY4MTQtM2U2MS00OWI5LTk4MWItNDgwMGVkNjI3NzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE1MzA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYmVlMzBjNTM0YTdhYWVmNGFmZDY5NWUzNTYxMjk3YTNhMTc5ZmFiZTMwYmE2NGZiMDZhOTJkMGVlZjJkOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lzvhne-UZRDWee2tVSP5P1mjOey6aiesfVi2-7N9rkI)

具体报错是：`TypeError: fetch failed`和`getaddrinfo ENOTFOUND lobe-auth-ui.example.com`（这里域名我替换成占位符了，实际上我日志里是相应的logto控制台的域名），另外原来是控制台域名，但这俩哪个报错应该都差不多

**Comment by zhuozhiyongde** [comment]
草，咋直接给关了

我的所有配置就是仓库里的默认配置啊，至于解析就是文档里说的那种反代配置

**Comment by zhuozhiyongde** [comment]
> 总不会是只有公网v6没有v4导致的吧？

这我真不知道了，可能得看看 logto 的文档

不过得等下周五了，我这周两门考试（）

**Comment by arvinxx** [comment]
我建议是 LobeChat 的镜像也创建一个 database 的库，和默认的 postgres 区分开

**Comment by zhuozhiyongde** [comment]
那就现在这样是 OK 的

**Comment by BiFangKNT** [comment]
> 我建议是 LobeChat 的镜像也创建一个 database ，和默认的 postgres 区分开

也行，但是这都是小事，现在的大问题是我域名的报错，云和自部署都不行，这样我完全用不了logto了。我用github是正常的，但github要不是私人的要不就完全公开，等于没有用户管理啊🤣
