### ISSUE TITLE
可以为ollama适配函数调用功能吗？谢谢

### ISSUE THREAD

**Issue by szh1118** [lobehub/lobe-chat#3827]
### 🥰 需求描述

可以给ollama的一些大模型适配函数调用这个功能吗？我在打开插件后尝试使用时发现无法使用，进一步搜索发现是当前大模型不支持函数调用导致的问题
<img width="1421" alt="屏幕截图 2024-09-08 222857" src="https://github.com/user-attachments/assets/05ae31e6-4840-475e-820f-3f5b5ba51d89">

### 🧐 解决方案

如果可能的话，可以在后续的版中加入对ollama的大模型中加入函数调用功能吗？谢谢

**Comment by arvinxx** [comment]
重复 #3436
