### ISSUE TITLE
[Bug] PR#3832 疑似导致标题显示出现问题

### ISSUE THREAD

**Issue by Lynricsy** [lobehub/lobe-chat#3840]
### 📦 Environment

Docker

### 📌 Version

1.15.23

### 💻 Operating System

Ubuntu

### 🌐 Browser

Edge

### 🐛 Bug Description

设置里面的LobeChat前面莫名多了一个`$`号
![image](https://github.com/user-attachments/assets/2b3f770b-bc71-42bd-9772-ebb81ab61368)

### 📷 Recurrence Steps

点击左上角头像，点击关于页面

### 🚦 Expected Behavior

显示`LobeChat`，就像以前版本一样
![image](https://github.com/user-attachments/assets/79837dcc-6a44-4e9b-bffd-064d31cd2384)

**Comment by arvinxx** [comment]
感谢反馈，在 #3841 修复
