### ISSUE TITLE
[Bug] Netlify 构建异常

### ISSUE THREAD

**Issue by a20185** [lobehub/lobe-chat#3849]
### 📦 Environment

Netlify

### 📌 Version

latest

### 💻 Operating System

Other

### 🌐 Browser

Chrome

### 🐛 Bug Description

2:36:03 PM: Netlify Build                                                 
2:36:03 PM: ────────────────────────────────────────────────────────────────
2:36:03 PM: ​
2:36:03 PM: ❯ Version
2:36:03 PM:   @netlify/build 29.54.0
2:36:03 PM: ​
2:36:03 PM: ❯ Flags
2:36:03 PM:   accountId: ***
2:36:03 PM:   baseRelDir: true
2:36:03 PM:   buildId: ***
2:36:03 PM:   deployId: ***
2:36:03 PM: ​
2:36:03 PM: ❯ Current directory
2:36:03 PM:   /opt/build/repo
2:36:03 PM: ​
2:36:03 PM: ❯ Config file
2:36:03 PM:   /opt/build/repo/netlify.toml
2:36:03 PM: ​
2:36:03 PM: ❯ Context
2:36:03 PM:   production
2:36:04 PM: ​
2:36:04 PM: ❯ Using Next.js Runtime - v5.7.1
2:36:11 PM: Next.js cache restored
2:36:11 PM: ​
2:36:11 PM: build.command from netlify.toml                               
2:36:11 PM: ────────────────────────────────────────────────────────────────
2:36:11 PM: ​
2:36:11 PM: $ pnpm run build
2:36:12 PM: > @lobehub/chat@1.15.24 build /opt/build/repo
2:36:12 PM: > next build
2:36:15 PM:   ▲ Next.js 14.2.8
2:36:15 PM:    Creating an optimized production build ...
2:36:16 PM:  ✓ (pwa) Compiling for server...
2:36:16 PM:  ✓ (pwa) Compiling for server...
2:36:16 PM:  ✓ (pwa) Compiling for client (static)...
2:36:16 PM:  ○ (pwa) Service worker: /opt/build/repo/public/sw.js
2:36:16 PM:  ○ (pwa)   URL: /sw.js
2:36:16 PM:  ○ (pwa)   Scope: /
2:40:06 PM:  ⚠ Compiled with warnings
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
2:40:06 PM: Attempted import error: 'Upstage' is not exported from '@lobehub/icons' (imported as 'Upstage').
2:40:06 PM: Import trace for requested module:
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/index.tsx
2:40:06 PM: ./src/features/Conversation/Error/InvalidAPIKey.tsx
2:40:06 PM: ./src/features/Conversation/Error/index.tsx
2:40:06 PM: ./src/features/Conversation/components/ChatItem/index.tsx
2:40:06 PM: ./src/features/Conversation/components/VirtualizedList/index.tsx
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
2:40:06 PM: Attempted import error: 'Upstage' is not exported from '@lobehub/icons' (imported as 'Upstage').
2:40:06 PM: Import trace for requested module:
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/index.tsx
2:40:06 PM: ./src/features/Conversation/Error/InvalidAPIKey.tsx
2:40:06 PM: ./src/features/Conversation/Error/index.tsx
2:40:06 PM: ./src/features/Conversation/components/ChatItem/index.tsx
2:40:06 PM: ./src/features/Conversation/components/VirtualizedList/index.tsx
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
2:40:06 PM: Attempted import error: 'Upstage' is not exported from '@lobehub/icons' (imported as 'Upstage').
2:40:06 PM: Import trace for requested module:
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/index.tsx
2:40:06 PM: ./src/features/Conversation/Error/InvalidAPIKey.tsx
2:40:06 PM: ./src/features/Conversation/Error/index.tsx
2:40:06 PM: ./src/features/Conversation/components/ChatItem/index.tsx
2:40:06 PM: ./src/features/Conversation/components/VirtualizedList/index.tsx
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
2:40:06 PM: Attempted import error: 'Upstage' is not exported from '@lobehub/icons' (imported as 'Upstage').
2:40:06 PM: Import trace for requested module:
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
2:40:06 PM: ./src/features/Conversation/Error/APIKeyForm/index.tsx
2:40:06 PM: ./src/features/Conversation/Error/InvalidAPIKey.tsx
2:40:06 PM: ./src/features/Conversation/Error/index.tsx
2:40:06 PM: ./src/features/Conversation/components/ChatItem/index.tsx
2:40:06 PM: ./src/features/Conversation/components/VirtualizedList/index.tsx
2:40:06 PM:    Linting and checking validity of types ...
2:41:06 PM: Killed
2:41:06 PM:  ELIFECYCLE  Command failed with exit code 137. (https://ntl.fyi/exit-code-137)
2:41:06 PM: ​
2:41:06 PM: "build.command" failed                                        
2:41:06 PM: ────────────────────────────────────────────────────────────────
2:41:06 PM: ​
2:41:06 PM:   Error message
2:41:06 PM:   Command failed with exit code 137: pnpm run build (https://ntl.fyi/exit-code-137)
2:41:06 PM: ​
2:41:06 PM:   Error location
2:41:06 PM:   In build.command from netlify.toml:
2:41:06 PM:   pnpm run build
2:41:06 PM: ​
2:41:06 PM:   Resolved config
2:41:06 PM:   build:
2:41:06 PM:     command: pnpm run build
2:41:06 PM:     commandOrigin: config
2:41:06 PM:     environment:
2:41:06 PM:       - ACCESS_CODE
2:41:06 PM:       - DEEPSEEK_API_KEY
2:41:06 PM:       - OPENAI_API_KEY
2:41:06 PM:       - OPENAI_PROXY_URL
2:41:06 PM:       - NODE_OPTIONS
2:41:06 PM:     publish: /opt/build/repo/.next
2:41:06 PM:     publishOrigin: config
2:41:06 PM:   plugins:
2:41:06 PM:     - inputs: {}
2:41:06 PM:       origin: ui
2:41:06 PM:       package: '@netlify/plugin-nextjs'
2:41:07 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
2:41:07 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
2:41:07 PM: Failing build: Failed to build site
2:41:07 PM: Finished processing build request in 6m27.102s

### 📷 Recurrence Steps

Trigger Deploy

### 🚦 Expected Behavior

Built success without error

### 📝 Additional Information

<img width="1256" alt="image" src="https://github.com/user-attachments/assets/3372809e-6282-47f3-a423-5dcbfc287b0b">

**Comment by arvinxx** [comment]
更新下依赖就好了

**Comment by a20185** [comment]
@arvinxx 似乎不起效。
不管是 `Clear cache and deploy` 还是删除 fork repo 再重新 fork，在 netlify 上都无法正常构建。

**Comment by NriotHrreion** [comment]
@arvinxx 我也遇到这个问题，一直卡在这里过不去

**Comment by NriotHrreion** [comment]
@a20185 已解决
原因是内存溢出，在netlify.toml里面调整一下内存大小就可以了

```toml
[build.environment]
NODE_OPTIONS = "--max_old_space_size=12288"
```

**Comment by NriotHrreion** [comment]
@a20185 我从netlify换称vercel部署就好了
