### ISSUE TITLE
[Bug] PWA安装浮窗出现{{appName}}

### ISSUE THREAD

**Issue by qq940500529** [lobehub/lobe-chat#3851]
### 📦 部署环境

Docker

### 📌 软件版本

v1.15.25

### 💻 系统环境

Windows 11

### 🌐 浏览器

Edge

### 🐛 问题描述

PWA安装浮窗出现{{appName}}
疑似 #3832 导致
![image](https://github.com/user-attachments/assets/ccd87e46-8a15-405a-a92d-9b2366fd5397)

### 📷 复现步骤

浏览器打开lobechat就会出现

### 🚦 期望结果

正确显示

**Comment by arvinxx** [comment]
已在 #3868 修复
