### ISSUE TITLE
[Bug] Claude图片上传后提问报错

### ISSUE THREAD

**Issue by yuwuxing** [lobehub/lobe-chat#3853]
### 📦 部署环境

Docker

### 📌 软件版本

v1.15.26

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

使用Claude sonnet 3.5模型和google Gemini 模型提问，上传一张图片，显示上传成功，但是返回报错信息：
### Claude 报错
```
{
  "error": {
    "error": {
      "type": "error",
      "error": {
        "type": "invalid_request_error",
        "message": "messages.0.content.1.image.source.base64.media_type: Input should be 'image/jpeg', 'image/png', 'image/gif' or 'image/webp'"
      }
    },
    "status": 400,
    "headers": {
      "via": "1.1 google",
      "date": "Mon, 09 Sep 2024 09:37:20 GMT",
      "cf-ray": "8c0632f70cee0906-LAX",
      "server": "cloudflare",
      "connection": "keep-alive",
      "request-id": "req_01BPu9sdKmLUNny7x43R1joy",
      "content-type": "application/json",
      "x-robots-tag": "none",
      "content-length": "193",
      "x-should-retry": "false",
      "cf-cache-status": "DYNAMIC",
      "x-cloud-trace-context": "4f50bc854b960317dd3fffd90bf36fb6"
    },
    "request_id": "req_01BPu9sdKmLUNny7x43R1joy"
  },
  "endpoint": "https://api.anthropic.com",
  "provider": "anthropic"
}
```
### Gemini Flash 1.5 报错
{
  "error": {
    "message": "currently we don't support image url: https://s3-lobechat.xxxxx.com/lobechat/files/479410/99270fd2-1643-41eb-93ca-684d1d6934ed.jpg"
  },
  "provider": "google"
}

控制台查询图片路径正常上传，图片可以访问
换了本地部署的minio和R2都是同样报错

### 📷 复现步骤

1. 上传一张图片
2. 选择Claude Sonnet 3.5或者Google Gemini模型
3. 提问
4. 返回报错信息
![a](https://github.com/user-attachments/assets/17dca220-208a-49a6-a5e0-0f34311f7be4)
![b](https://github.com/user-attachments/assets/853f1603-0088-4c0a-b978-44c713749dc7)

### 🚦 期望结果

能够正常对话

### 📝 补充信息

GPT相关模型可以回答成功
![image](https://github.com/user-attachments/assets/5c3da198-7629-4e1c-b1a9-4a6715a8f4a8)

**Comment by arvinxx** [comment]
Google Gemini 在 #3370 修复

**Comment by arvinxx** [comment]
已在 #3870 修复
