### ISSUE TITLE
[Bug] 移动端 iOS 底部安全区域过高

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#387]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

比如与微信的相对比

![IMG_4055](https://github.com/lobehub/lobe-chat/assets/29084441/259ed428-34c6-43aa-a7ef-2c1f263eddca)
![IMG_4056](https://github.com/lobehub/lobe-chat/assets/29084441/77a3b9e4-0e99-4e7b-a0d2-0ce8f7cda8f2)

**Comment by arvinxx** [comment]
@canisminor1990 看下这个

**Comment by canisminor1990** [comment]
> @canisminor1990 看下这个

我换阵营之后都没测试设备了😂

**Comment by mushan0x0** [comment]
没事，我空了来提个pr吧
