### ISSUE TITLE
[Bug] 上传图片后提问,回答错乱

### ISSUE THREAD

**Issue by eagleye1115** [lobehub/lobe-chat#3878]
### 📦 Environment

Docker

### 📌 Version

v1.15.30

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

docker部署的客户端版本v1.15.30
上传图片后提问,第一条消息没有问题, 后面的每次上传图片回答，都是上一个图片的内容
![QQ截图20240910153423](https://github.com/user-attachments/assets/3f3c1536-5198-4439-9c31-5c7668e616fa)

**Comment by eagleye1115** [comment]
@lobehubbot 我使用的就是安装的最新已经修复了#3870错误的版本

**Comment by H-TTTTT** [comment]
我跟你一样的问题，我是数据库版本，版本号v1.15.32，刚刚2024年9月10日16:33:59测试的，一样问题
![image](https://github.com/user-attachments/assets/057b3c4d-ecc0-449d-8594-e1d76b958165)

**Comment by arvinxx** [comment]
和 #3760 重复
