### ISSUE TITLE
[Request] docker-compose部署后不能流式输出

### ISSUE THREAD

**Issue by aictt** [lobehub/lobe-chat#3879]
### 🥰 需求描述

当我使用docker-compose部署时 回答并不能流式输出  是nginx配置有误还是需要什么?

### 🧐 解决方案

是nginx配置有误还是需要什么?

**Comment by arvinxx** [comment]
先试下 IP，IP如果能行大概率是 nginx 的问题。 https://github.com/lobehub/lobe-chat/discussions/531

**Comment by aictt** [comment]
> 先试下IP，IP如果能行很大概率是nginx的问题。#531

@arvinxx  是的 IP可以 谢谢 已检查
