### ISSUE TITLE
[Request] Switch Between URL and Base64 Modes for Image Input in Server Mode

### ISSUE THREAD

**Issue by fashioncj** [lobehub/lobe-chat#3881]
### 🥰 Feature Description

In server mode, I need the ability to switch between URL and Base64 modes for image input via configuration options. This feature is crucial for addressing the issue where S3 (minio) cannot be accessed via the external network in a private deployment.

#### Use Case
In private deployments, particularly when using S3-compatible storage solutions like minio, images stored in the bucket are often not accessible from the external network. This limitation hinders the ability to use URL-based image inputs in language models such as OpenAI's API. By providing a configuration option to use Base64 encoded images instead of URLs, we can ensure seamless operation in both public and private deployment environments.

#### Benefits
- Provides flexibility in deployment environments.
- Ensures compatibility with private storage solutions like minio.
- Enhances the robustness of the server mode by accommodating different image input methods.

### 🧐 Proposed Solution

1. Introduce a configuration option in the server settings to toggle between URL and Base64 modes for image input.
2. When the Base64 mode is enabled, the server should accept Base64 encoded images and decode them appropriately before processing.
3. Ensure that the switch between modes is seamless and does not affect the existing functionality for URL-based inputs.

### 📝 Additional Information

This feature would greatly enhance the usability of the server mode in restricted network environments and facilitate easier integration with private storage solutions.

For reference, please see the related PR: [PR #3370](https://github.com/lobehub/lobe-chat/pull/3370).

Thank you for considering this feature request. I look forward to your feedback and am available for any further clarification or discussion.

**Comment by fashioncj** [comment]
> I thinks it can be an env, not the ui configuration? Because if you use the local deployment, the whole image is in unreachable for external network.

Yes, an environment variable for deployment will suffice. This state is indeed tied to the deployment environment.

**Comment by arvinxx** [comment]
@fashioncj   try with `LLM_VISION_IMAGE_USE_BASE64 =1`

**Comment by jaslioin** [comment]
@fashioncj does this work for you? i pulled the latest db version image and added this env var, the image is still not converted to base64

**Comment by iproud** [comment]
This is still not working. I set the variable in my environment file and LM Studio is still complaining about the url and not Base64 being included.
LLM_VISION_IMAGE_USE_BASE64 =1
