### ISSUE TITLE
[Bug] dockerfile步数有问题，格式不正确。

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#3891]
### 📦 部署环境

Docker

### 📌 软件版本

all

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

dockerfile打包的时候会提示下面错误：
Dockerfile:52
--------------------
  51 |
  52 | >>> RUN \
  53 | >>>     # If you want to build docker in China, build with --build-arg USE_CN_MIRROR=true
  54 | >>>     if [ "${USE_CN_MIRROR:-false}" = "true" ]; then \
  55 | >>>         export SENTRYCLI_CDNURL="https://npmmirror.com/mirrors/sentry-cli"; \
  56 | >>>         npm config set registry "https://registry.npmmirror.com/"; \
  57 | >>>     fi \
  58 | >>>     # Set the registry for corepack
  59 | >>>     && export COREPACK_NPM_REGISTRY=$(npm config get registry | sed 's/\/$//') \
  60 | >>>     # Enable corepack
  61 | >>>     && corepack enable \
  62 | >>>     # Use pnpm for corepack
  63 | >>>     && corepack use pnpm \
  64 | >>>     # Install the dependencies
  65 | >>>     && pnpm i \
  66 | >>>     # Add sharp dependencies
  67 | >>>     && mkdir -p /deps \
  68 | >>>     && pnpm add sharp --prefix /deps
  69 |
--------------------
ERROR: failed to solve: process "/bin/sh -c if [ \"${USE_CN_MIRROR:-false}\" = \"true\" ]; then         export SENTRYCLI_CDNURL=\"https://npmmirror.com/mirrors/sentry-cli\";         npm config set registry \"https://registry.npmmirror.com/\";     fi     && export COREPACK_NPM_REGISTRY=$(npm config get registry | sed 's/\\/$//')     && corepack enable     && corepack use pnpm     && pnpm i     && mkdir -p /deps     && pnpm add sharp --prefix /deps" did not complete successfully: exit code: 1
![image](https://github.com/user-attachments/assets/b7d26ccc-aeb4-4581-94ef-a35f4447fc37)

**Comment by hezhijie0327** [comment]
构建时引入 `--build-arg USE_CN_MIRROR=true` 参数试试，多半网络问题

```
docker build -t lobe-chat:local --build-arg USE_CN_MIRROR=true --no-cache .
```

**Comment by yincangshiwei** [comment]
是网络问题，谢谢！
