### ISSUE TITLE
 Can Lobe chat self-hosting be deployed using Cloudflare Advanced Deployment options?

### ISSUE THREAD

**Issue by LiveWithCodeAnkit** [lobehub/lobe-chat#3893]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/server-database.mdx

I am trying to deploy on Cloudflare. I followed all the steps, including integrating my Git repository and adding all the necessary environment variables according to the Cloudflare documentation. I also updated the wrangler.toml file in the root directory. However, I am facing some errors.
![image_2024_09_11T05_22_21_571Z](https://github.com/user-attachments/assets/4121c69a-94db-42c9-a70e-9333d39759f8)

Can you help me resolve these issues?

**Comment by arvinxx** [comment]
Cloudflare don't support nodejs runtime. So it's impossible to deploy lobe-chat on CF now.
