### ISSUE TITLE
[Bug] NEXT_AUTH_SECRET可否换一种方式，对云函数不太友好。

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#3899]
### 📦 部署环境

Other

### 📌 软件版本

all

### 💻 系统环境

Other

### 🌐 浏览器

Chrome

### 🐛 问题描述

我想在云函数上面启动服务模式，数据库和身份验证那些都可通过环境变量处理，唯度这个NEXT_AUTH_SECRET比较麻烦，必须要在所在服务上面执行openssl rand -base64 32才行。可否添加一种适合云函数上面使用的。

**Comment by yincangshiwei** [comment]
> `NEXT_AUTH_SECRET` 可以通过访问 `https://generate-secret.vercel.app/32` 来生成密钥，而不需要在服务上执行 `openssl rand -base64 32` 命令，这样更适合云函数环境 [[1]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/advanced/auth.mdx).
> 
> 此外，还有其他一些环境变量也可能需要云函数友好的替代方案，例如 `NEXT_AUTH_SSO_PROVIDERS`、`NEXTAUTH_URL` 等 [[2]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/environment-variables/auth.mdx).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

https://generate-secret.vercel.app/32这个要海外网才可以访问吧。

**Comment by ReddotCleaner** [comment]
不是可以先生成一个直接填进去吗

**Comment by arvinxx** [comment]
你自己生成一个填进去就好了啊
