### ISSUE TITLE
[Bug] 图片上传对话报错

### ISSUE THREAD

**Issue by Matinal111** [lobehub/lobe-chat#3901]
### 📦 部署环境

Docker

### 📌 软件版本

1.16.4

### 💻 系统环境

Windows, Android

### 🌐 浏览器

Chrome, Firefox

### 🐛 问题描述

![image](https://github.com/user-attachments/assets/8a83ad35-f7b2-4a22-8d27-1453b2a6177d)

![image](https://github.com/user-attachments/assets/9482d4ba-3f4d-4986-81e4-9b64d938102d)

这个问题忘记哪个版本开始的一直存在，我看有相关 issues 提到过这个问题就没反馈，直到今天 V1.16.4 版本发布说是解决了这个问题，目前问题复现依旧如截图所示

**Comment by Matinal111** [comment]
S3 对象存储使用的阿里云OSS，图片上传前端界面不显示但存储桶实际已上传成功

**Comment by H-TTTTT** [comment]
我跟你遇到的问题是一样，我反馈了多次，都是给我关闭，然后说是解决
实际上只有zeabur上面部署的是完全正常的，只要是自己本地部署啥的，一直都是有问题

**Comment by Matinal111** [comment]
此问题完结，原因是我对象存储开启了私有读写，文档要求的是公有读私有写，怪我自己没看清...
