### ISSUE TITLE
[Bug] 爬虫插件不可用

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#3910]
### 📦 Environment

Official Preview

### 📌 Version

latest

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

给了链接没有返回结果，接口是返回的504

<img width="1415" alt="image" src="https://github.com/user-attachments/assets/1e7f896b-a40a-40b8-98a9-65bdf8478e9a">

**Comment by arvinxx** [comment]
应该单纯只是超时吧
