### ISSUE TITLE
[Docs] Feedback for `self-hosting/server-database/docker-compose`

### ISSUE THREAD

**Issue by H-TTTTT** [lobehub/lobe-chat#3917]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/server-database/docker-compose.zh-CN.mdx

### 🐛 Feedback
右侧文章目录，少一个发布到生产的标题
![{EECC463D-D1CD-47D8-BC44-BAB6F547F400}](https://github.com/user-attachments/assets/b389ddd7-9fe4-4ee6-9d7f-b2fb611c63bc)
logto这个值应该是更新了
![{67F9C83D-FC52-475E-9884-79C9FF2D856F}](https://github.com/user-attachments/assets/c765bd27-a4d2-49a4-8897-cdb8f2354087)
![{9FEEB388-F06E-44B6-9C88-0141D7D02D39}](https://github.com/user-attachments/assets/0ef31303-96ca-4536-9278-3dab18b12be5)
      - 'TRUST_PROXY_HEADER=1' 
      这个环境变量应该修改为
      - 'TRUST_PROXY_HEADER=true'

**Comment by BiFangKNT** [comment]
变量值的`true`和`1`是完全等价的，，

**Comment by BiFangKNT** [comment]
他们的文档有很多错漏的地方，我前几天提的问题到现在都还没改，应该是别的任务太多了，顾不及文档这边吧。想想lobe的这个更新速度，感觉人手也确实应该捉襟见肘

**Comment by BiFangKNT** [comment]
> 他们的文档有很多错漏的地方，我前几天提的问题到现在都还没改，应该是别的任务太多了，顾不及文档这边吧。想想lobe的这个更新速度，感觉人手也确实应该捉襟见肘

哦现在改了，之前看过没改的

**Comment by BiFangKNT** [comment]
你这里的问题就是标题少了一个，我当初看的时候也是觉得有点麻烦，不过问题不大，算是小纰漏
后面环境变量是没问题的，变量值的`true`和`1`是完全等价的
