### ISSUE TITLE
[Style] Alert style in setting page 

### ISSUE THREAD

**Issue by canisminor1990** [lobehub/lobe-chat#392]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

备忘

<img width="413" alt="image" src="https://github.com/lobehub/lobe-chat/assets/17870709/08f0184b-eccf-4084-9c8e-2ca8f0ab7fdd">

**Comment by arvinxx** [comment]
我其实比较喜欢设置的侧边栏能和设置放在一起，类似 Github 这样。

<img width="1329" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/aa008e9f-0e92-4d56-83cc-a2cdd93b111f">

考不考虑PC端下改回之前一版？这样更新可以做成一个长条放在顶部下面

**Comment by canisminor1990** [comment]
前一版不行 tab 还是得垂直 不然后面放不下

**Comment by arvinxx** [comment]
> 前一版不行 tab 还是得垂直 不然后面放不下

我是指头改回来。 tab 用垂直的
