### ISSUE TITLE
[Request] support other embedding?

### ISSUE THREAD

**Issue by ukhack** [lobehub/lobe-chat#3928]
### 🥰 需求描述

目前除了openai的text embedding，有很多优秀的向量模型。例如silliconcloud支持的bge-m3等
给像我这样的非openai ai(google gemini user)用户有可选择的余地

### 🧐 解决方案

建议追加一个或两个其他模型，后期可以开放sdk给用户自己对接，例如你规定api的格式，用户自己提供api url。

**Comment by arvinxx** [comment]
重复 https://github.com/lobehub/lobe-chat/issues/3928
