### ISSUE TITLE
[Bug] Unable to Upload PDF in Chat Using "Upload File" Feature

### ISSUE THREAD

**Issue by samkurd** [lobehub/lobe-chat#3929]
### 📦 Environment

Vercel

### 📌 Version

v1.16.11

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

When attempting to use the "Upload File" feature to upload a PDF file in the chat with assistants, an error occurs consistently. This issue is specific to the chat interface, as uploading PDFs in the "Files" section works normally and can be accessed in the "Knowledge Base" feature within the chat.

Screenshot of the error:
> Request Failed
Sorry, the server seems to be experiencing some difficulties and is temporarily unable to complete your request. Please try again later.
Error detail: Invalid key length

Below is what I see in the console log:
> https://mydomain.com/trpc/lambda/chunk.createParseFileTask?batch=1

### 📷 Recurrence Steps

1. Install Lobe-chat using server database and Cloudflare R2 Storage
2. Open a chat with an assistant
3. Attempt to use the "Upload File" feature to upload a PDF file

### 🚦 Expected Behavior

The PDF file should upload normally and be available for use in the chat.

### 📝 Additional Information

I have attached two screenshot of the error.
![image](https://github.com/user-attachments/assets/369fdcbd-4868-48fe-bf52-b912bffe61dc)
![image](https://github.com/user-attachments/assets/35628919-b143-4808-ab34-1e0c9f1a0021)

**Comment by arvinxx** [comment]
check your server log please.

**Comment by samkurd** [comment]
this is the server log for the error, please let me know if this is enough.

> 97013-02472d5cb275a608.js:1 
        
        
        POST https://lobe.mydomain.com/trpc/lambda/chunk.createParseFileTask?batch=1 500 (Internal Server Error)
fetch @ 97013-02472d5cb275a608.js:1
S @ 73920-aba4224cf1d54a1e.js:1
await in S
j @ 73920-aba4224cf1d54a1e.js:1
v @ 73920-aba4224cf1d54a1e.js:1
fetch @ 73920-aba4224cf1d54a1e.js:1
o @ 73920-aba4224cf1d54a1e.js:1
setTimeout
load @ 73920-aba4224cf1d54a1e.js:1
(anonymous) @ 73920-aba4224cf1d54a1e.js:1
subscribe @ 73920-aba4224cf1d54a1e.js:1
(anonymous) @ 73920-aba4224cf1d54a1e.js:1
subscribe @ 73920-aba4224cf1d54a1e.js:1
(anonymous) @ 73920-aba4224cf1d54a1e.js:1
subscribe @ 73920-aba4224cf1d54a1e.js:1
(anonymous) @ 73920-aba4224cf1d54a1e.js:1
(anonymous) @ 73920-aba4224cf1d54a1e.js:1
requestAsPromise @ 73920-aba4224cf1d54a1e.js:1
mutation @ 73920-aba4224cf1d54a1e.js:1
(anonymous) @ 73920-aba4224cf1d54a1e.js:1
apply @ 73920-aba4224cf1d54a1e.js:1
createParseFileTask @ 18264-326e6854cdf5a209.js:1
(anonymous) @ 18264-326e6854cdf5a209.js:1
startAsyncTask @ 18264-326e6854cdf5a209.js:1
(anonymous) @ 18264-326e6854cdf5a209.js:1
await in (anonymous)
uploadChatFiles @ 18264-326e6854cdf5a209.js:1
await in uploadChatFiles
beforeUpload @ default-efa24d9095913747.js:1
i @ 9106-0ac884af3a487b36.js:1
(anonymous) @ 9106-0ac884af3a487b36.js:1
beforeUpload @ 9106-0ac884af3a487b36.js:1
(anonymous) @ 9106-0ac884af3a487b36.js:1
p @ 97322-ee173d23dcff0905.js:1
a.value @ 97322-ee173d23dcff0905.js:1
(anonymous) @ 97322-ee173d23dcff0905.js:1
r @ 97322-ee173d23dcff0905.js:1
c @ 97322-ee173d23dcff0905.js:1
(anonymous) @ 97322-ee173d23dcff0905.js:1
(anonymous) @ 97322-ee173d23dcff0905.js:1
(anonymous) @ 9106-0ac884af3a487b36.js:1
(anonymous) @ 9106-0ac884af3a487b36.js:1
(anonymous) @ 9106-0ac884af3a487b36.js:1
(anonymous) @ 9106-0ac884af3a487b36.js:1
a_ @ fd9d1056-aea7120c0817ed17.js:1
aR @ fd9d1056-aea7120c0817ed17.js:1
(anonymous) @ fd9d1056-aea7120c0817ed17.js:1
sF @ fd9d1056-aea7120c0817ed17.js:1
sM @ fd9d1056-aea7120c0817ed17.js:1
(anonymous) @ fd9d1056-aea7120c0817ed17.js:1
o4 @ fd9d1056-aea7120c0817ed17.js:1
iV @ fd9d1056-aea7120c0817ed17.js:1
sU @ fd9d1056-aea7120c0817ed17.js:1
uR @ fd9d1056-aea7120c0817ed17.js:1
uM @ fd9d1056-aea7120c0817ed17.js:1
[NEW] Explain Console errors by using Copilot in Edge: click
         
         to explain an error. 
        Learn more
        Don't show again

**Comment by arvinxx** [comment]
It seems your issue is the file can be fetched. Check your s3 config

**Comment by samkurd** [comment]
Thanks @arvinxx , what do you think has been misconfigured? I'm using Cloudflare.

**Comment by jzworkmagic** [comment]
Hi @samkurd Have you solved this issue? If you have solved it, could you tell me how to solve it? Thanks

**Comment by amanbolat** [comment]
Hello,
I have encountered the same issue as @samkurd. If I try to upload a PDF file in the chat then it fails with error. Though it can be uploaded from files menu.

**Comment by arvinxx** [comment]
if the error is  `Invalid key length`, you must set a wrong `KEY_VAULTS_SECRET `, please check the document: https://lobehub.com/docs/self-hosting/server-database#key-vaults-secret
