### ISSUE TITLE
[Question] 大佬插件怎么使用呀，我部署了lobe-chat启动了插件但是不生效

### ISSUE THREAD

**Issue by dao-zero** [lobehub/lobe-chat#393]
### 🧐 问题描述 | Proposed Solution

![image](https://github.com/lobehub/lobe-chat/assets/83216969/46971883-fb1e-45d7-a061-236344a92cb7)

### 📝 补充信息 | Additional Information

就是要怎么设置才能出现插件呀

**Comment by canisminor1990** [comment]
设置中插件的 ApiKey 填写了么

**Comment by dao-zero** [comment]
那个key写的是啥呀

**Comment by arvinxx** [comment]
刷新下界面再试试？

**Comment by dao-zero** [comment]
试过了，我用的是docker部署的，和这个有关系吗

**Comment by arvinxx** [comment]
应该没有关系，你要不试试市场里的网页阅读助手是否有效

**Comment by arvinxx** [comment]
你能打开下请求部分让我看下吗？

**Comment by dao-zero** [comment]
是这个吗
![Uploading image.png…]()

**Comment by dao-zero** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/83216969/40a64942-ecaf-400c-a4cf-70ffeee21041)
是这个吗

**Comment by arvinxx** [comment]
对，看下负载

**Comment by dao-zero** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/83216969/f14584a7-7aee-4630-8fa7-23e1865d034f)

**Comment by arvinxx** [comment]
看上去是因为插件没有生效，你试试重新开关一下插件有没有用？

**Comment by dao-zero** [comment]
重开好多次了

**Comment by arvinxx** [comment]
那能不能 看下 application  localStorage 那边，点开这个地方我看下

<img width="1083" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/c3258e2e-dfc7-4d25-b22b-45dd62432ed8">

**Comment by dao-zero** [comment]
我看到了，似乎是插件没加载进这里面
![image](https://github.com/lobehub/lobe-chat/assets/83216969/648fffed-db79-45bf-a3a9-8434e4101491)

**Comment by dao-zero** [comment]
不对另一个有内容也不行：
![image](https://github.com/lobehub/lobe-chat/assets/83216969/8721767b-1504-4e10-ab71-496a9fdb04d6)

**Comment by dao-zero** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/83216969/7402b3a3-3cd6-424f-9ca5-d8f0e4fded4f)

**Comment by arvinxx** [comment]
网页的那个 web-crawer 没有吗？

**Comment by dao-zero** [comment]
有的刚刚清了下缓存没加这个
![image](https://github.com/lobehub/lobe-chat/assets/83216969/470761d2-34d4-4616-afac-b51f46ad22df)

**Comment by arvinxx** [comment]
这样你再试试看有效果么

**Comment by dao-zero** [comment]
还是没有：
![image](https://github.com/lobehub/lobe-chat/assets/83216969/116c124c-fd0b-4029-ab5c-77fe9b9b0f50)
![image](https://github.com/lobehub/lobe-chat/assets/83216969/09cf4ab7-ede6-4432-84f5-01e644b9000a)

**Comment by arvinxx** [comment]
你部署的版本是哪个版本？我试试本地能不能复现

**Comment by dao-zero** [comment]
我这边写着的是22小时之前的那个

**Comment by arvinxx** [comment]
@dao-zero 在这里开启关闭下后再试试？新开一个 topic

<img width="1144" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/b3901e8b-c4b7-4a30-b088-39cc47fc78fb">

从 agent 市场里加载的角色好像是没有正常加载插件。这个是个 bug。我修一下

**Comment by dao-zero** [comment]
还是不行，我开关好多次都不生效呀

**Comment by arvinxx** [comment]
> 还是不行，我开关好多次都不生效呀

加下discord吧 晚上再帮你看看

**Comment by dao-zero** [comment]
docker里面报这个错
![image](https://github.com/lobehub/lobe-chat/assets/83216969/88e46364-9645-472e-9070-b6a652b3d463)
![image](https://github.com/lobehub/lobe-chat/assets/83216969/1af16f3f-8f4e-42d0-9c53-cec67e02acd7)
会和这个有关系吗

**Comment by arvinxx** [comment]
应该没关系。看上去只是单纯插件没安装上 你点下插件的 tag ，然后看看这里的内容有没有：

<img width="678" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/6ab3b84a-2136-4518-8c68-c8d5cc489f51">

**Comment by dao-zero** [comment]
没有不弹出任何东西

**Comment by arvinxx** [comment]
> 没有不弹出任何东西

点开看看 https://web-crawler.chat-plugin.lobehub.com/manifest.json 这个能不能打开？

**Comment by dao-zero** [comment]
这个链接可以打开：
![image](https://github.com/lobehub/lobe-chat/assets/83216969/d2ce8786-a5f8-4b91-a683-e7dc10005e91)

**Comment by dao-zero** [comment]
@arvinxx 这个链接可以打开：
![image](https://github.com/lobehub/lobe-chat/assets/83216969/45660cf7-754d-4221-8619-65dbbaf8e63f)

**Comment by lanyuer** [comment]
我的也启用不了这个插件，天气插件可以/网页爬虫的不行

**Comment by arvinxx** [comment]
这个问题我再研究下

**Comment by arvinxx** [comment]
@dao-zero @lanyuer 请两位再试试看，应该已经修复掉了~
