### ISSUE TITLE
[Bug] InvalidProviderAPIKey

### ISSUE THREAD

**Issue by cantalupo555** [lobehub/lobe-chat#3930]
### 📦 Environment

Docker

### 📌 Version

v1.16.10

### 💻 Operating System

Ubuntu

### 🌐 Browser

Firefox

### 🐛 Bug Description

I can send the file through the "Files" tab...
![image](https://github.com/user-attachments/assets/e7509f74-0f07-449c-8229-229da0cd315e)

But when I try to use this file in the chat, this error appears:
![image](https://github.com/user-attachments/assets/48850c26-f4aa-4df9-9449-5b4a82f1b4b6)

Logs:
```
{"level":30,"time":1726158249548,"pid":1,"hostname":"3537b03d27b6","msg":"Error in tRPC handler (lambda) on path: chunk.semanticSearchForChat, type: mutation"}
a [TRPCError]
    at i (/app/.next/server/chunks/5663.js:1:946)
    ... 6 lines matching cause stack trace ...
    at async r (/app/.next/server/chunks/5663.js:1:6069)
    at async /app/.next/server/chunks/8946.js:1:7077
    at async Promise.all (index 0) {
  code: 'INTERNAL_SERVER_ERROR',
  [cause]: o [Error]
      at /app/.next/server/chunks/5663.js:1:1257
      at new a (/app/.next/server/chunks/5663.js:1:1299)
      at i (/app/.next/server/chunks/5663.js:1:946)
      at t (/app/.next/server/chunks/5663.js:1:6045)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async t (/app/.next/server/chunks/5663.js:1:5727)
      at async t (/app/.next/server/chunks/5663.js:1:5727)
      at async t (/app/.next/server/chunks/5663.js:1:5727)
      at async t (/app/.next/server/chunks/5663.js:1:5727)
      at async r (/app/.next/server/chunks/5663.js:1:6069) {
    error: undefined,
    errorType: 'InvalidProviderAPIKey'
  }
}
```

If I attach the file directly in the chat, this error appears:
![image](https://github.com/user-attachments/assets/9480f95e-aa9c-4050-8654-d2720892b530)

Log:
```
embeddingChunks error {
  message: '{"errorType":"InvalidProviderAPIKey"}',
  name: 'EmbeddingError'
}
```

**Comment by cantalupo555** [comment]
> do you set the API key?

Yes, the API keys were defined inside the .env
![image](https://github.com/user-attachments/assets/08438379-8417-42fc-af9b-2646339c11b4)

**Comment by cantalupo555** [comment]
> do you set the API key?

Yes, the API keys were defined inside the .env
![image](https://github.com/user-attachments/assets/08438379-8417-42fc-af9b-2646339c11b4)

```
[...]
#API Key
ENABLED_OPENAI=0
ENABLED_OLLAMA=0
ANTHROPIC_API_KEY=sk-ant-api03-**********AA
OPENROUTER_API_KEY=sk-or-v1-**********ab
OPENROUTER_MODEL_LIST=-all,+anthropic/claude-3-haiku,+meta-llama/llama-3.1-70b-instruct,+meta-llama/llama-3.1-405b-instruct,+qwen/qwen-2-72b-instruct,+openai/gpt-4o-mini,+google/gemini-flash-1.5
```

**Comment by arvinxx** [comment]
If you want embedding, you need to set OpenAI api key

**Comment by moeinrahimi1** [comment]
@arvinxx does it work with claude?

**Comment by nonlinear** [comment]
@arvinxx do I need OpenAI API key even if I use ollama local with `paraphrase-multilingual:latest` ? I mean, is it just a formality, or I can ONLY use OpenAI for embedding on lobechat?

**Comment by disarticulate** [comment]
there's plenty of ollama embedding models, is this hard coded?

**Comment by pyinto** [comment]
is there way to use local models for embedding? I use different provider, not OpenAI API, what my options are?

**Comment by MareDevi** [comment]
I think the software should give a way to let user setting the embedding service provider not only use openai
