### ISSUE TITLE
[Bug] 使用 logto 的 webhook ，LobeChat 容器日志会有抛错

### ISSUE THREAD

**Issue by Matinal111** [lobehub/lobe-chat#3939]
### 📦 部署环境

Docker

### 📌 软件版本

1.16.12

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome, Edge

### 🐛 问题描述

![image](https://github.com/user-attachments/assets/7f62d3ab-ecf6-48c4-aa95-1d1fdb873c0d)

**Comment by Matinal111** [comment]
@cy948 麻烦看下是什么问题导致

**Comment by cy948** [comment]
这个问题和 logto 的 webhook 无关吧。TRPC的unauthorized可以忽略，不影响使用。

**Comment by Matinal111** [comment]
> 这个问题和 logto 的 webhook 无关吧。TRPC的unauthorized可以忽略，不影响使用。

目前看来没啥使用影响，这个问题严格意义上来说和 logto webhook 确实无关，是在 LobeChat 使用了环境变量 LOGTO_WEBHOOK_SIGNING_KEY 出现的

**Comment by arvinxx** [comment]
这个问题不应该是你没登录吗…

**Comment by Matinal111** [comment]
> 这个问题不应该是你没登录吗…

不，是登录状态

**Comment by cy948** [comment]
个人不认为这个是bug，没有期望行为和不符合期望行为的表现。

**Comment by MoreChanger** [comment]
但是会一直打印[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant，日志会增加

**Comment by Matinal111** [comment]
![image](https://github.com/user-attachments/assets/0bbe02eb-2fab-4030-bc81-1560bdc09641)

移除 nextauth_url 后，不再打印auth警告日志

**Comment by MoreChanger** [comment]
但是移除nextauth_url后，退出登录并不能正确跳转回lobe网页，会指向0.0.0.0:3210

**Comment by SpeedupMaster** [comment]
> 但是移除nextauth_url后，退出登录并不能正确跳转回lobe网页，会指向0.0.0.0:3210

登录后也不能正确跳转回lobe网页，会指向0.0.0.0:3210

**Comment by SAnBlog** [comment]
> nextauth_url

+1

**Comment by cy948** [comment]
目前先用 AUTH_URL 吧，这个 duplication warning 会在稍后的 pr 中修复。

**Comment by SAnBlog** [comment]
该问题解决了吗?我也是配置了webhooks报以上错误,并且logto中发送测试负载超时

**Comment by cy948** [comment]
@SAnBlog 提个新issue看看，这里有点杂，不知道你说的是哪个问题。

**Comment by SAnBlog** [comment]
> @SAnBlog 提个新issue看看，这里有点杂，不知道你说的是哪个问题。

见https://github.com/lobehub/lobe-chat/issues/4048

**Comment by SAnBlog** [comment]
问题已解决,云厂商拦截了US IP,解禁即可
