### ISSUE TITLE
[Bug] 使用过程中总是出现乱码

### ISSUE THREAD

**Issue by twn29004** [lobehub/lobe-chat#3940]
### 📦 Environment

Official Preview

### 📌 Version

latest

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/90faf596-5b59-4969-b30f-35f5a0941520)

### 📷 Recurrence Steps

正常聊天过程，不能稳定复现

**Comment by arvinxx** [comment]
你把对话的高级参数给复位呗

**Comment by twn29004** [comment]
> 你把对话的高级参数给复位呗

高级参数是指哪些呢

**Comment by sxjeru** [comment]
模型的问题吗？有些开源模型容易出现此种问题。

**Comment by twn29004** [comment]
> 模型的问题吗？有些开源模型容易出现此种问题。

GPT-4o-mini和GPT-3.5-turbo都会出现这种情况

**Comment by arvinxx** [comment]
<img width="697" alt="image" src="https://github.com/user-attachments/assets/06093399-ecac-4523-83fc-064441b912b8">

这两个不要拉到最大
