### ISSUE TITLE
[Request] markdown输出的svg图片实时渲染功能的支持

### ISSUE THREAD

**Issue by Helium-327** [lobehub/lobe-chat#3941]
### 🥰 需求描述

可以通过提示词引导AI输出SVG代码，并通过markdown进行渲染，这样，AI将具备更多可视化的玩法。想法来源于@李继刚的”汉语新解“prompt

### 🧐 解决方案

不太懂这方面的技术，只知道typora支持实时渲染。可以参考typora的实现方式

**Comment by Helium-327** [comment]
我希望lobe-chat输出能支持SVG

**Comment by Helium-327** [comment]
good job

**Comment by fliaping** [comment]
有些模型不支持Function Call, lobe不支持使用Artifacts，但也能生成正确的svg，可是却没法渲染，看看大佬怎么解决下
