### ISSUE TITLE
[Request] 希望适配o1-mini以及o1-preview模型

### ISSUE THREAD

**Issue by Xiaokai6880** [lobehub/lobe-chat#3944]
### 🥰 需求描述

由于o1-mini以及o1-preview模型的API接口不支持流式传输及temperature必须为1，无法调用此API模型，希望能够适配完成

### 🧐 解决方案

希望适配o1-mini以及o1-preview模型

### 📝 补充信息

![image](https://github.com/user-attachments/assets/96c55831-1173-4f3c-8d22-d65d81a49d01)
![image](https://github.com/user-attachments/assets/b6869333-7034-4d05-aefd-39aa5772f4f2)

**Comment by burugo** [comment]
还是有bug，出现stream参数错误
{
  "error": {
    "message": "Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.",
    "type": "invalid_request_error",
    "param": "stream",
    "code": "unsupported_value"
  },
  "endpoint": "https://ai.gu****12.com/v1",
  "provider": "openai"
}

**Comment by burugo** [comment]
请问可以发布到最新的docker镜像吗
