### ISSUE TITLE
[Bug] 助手设置 会使用新窗口打开

### ISSUE THREAD

**Issue by MartialBE** [lobehub/lobe-chat#395]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

点击助手设置，会从新窗口打开。
应该是受 #359 影响

<img width="812" alt="iShot_2023-11-02_17 55 53" src="https://github.com/lobehub/lobe-chat/assets/42402987/19cec651-1cd5-48a9-b332-b107ab2c5bc8">

**Comment by arvinxx** [comment]
@canisminor1990 我感觉终极解法是自定义 message type 为 guide，然后自定义渲染 guide 的内容。

**Comment by arvinxx** [comment]
已修复
