### ISSUE TITLE
[Request] 建议将上传文件分块作为一个可选配置

### ISSUE THREAD

**Issue by fushes** [lobehub/lobe-chat#3950]
### 🥰 Feature Description

新版不知道为啥聊天界面上传文件自动分块，这样增加了上传文件的时间，而且对于没有配置分块向量化的用户来说简直就是灾难性。

### 🧐 Proposed Solution

提供一个环境变量配置或设置选项

**Comment by LovelyGuYiMeng** [comment]
这个是先上传才分块，根本不影响上传时间
另外如果想让AI识别文件，分块是必须的，未分块的文件无法识别
如果你想上传文件不分块，可以直接从文件管理上传，不需要在聊天页面上传

**Comment by fushes** [comment]
> 这个是先上传才分块，根本不影响上传时间 另外如果想让AI识别文件，分块是必须的，未分块的文件无法识别 如果你想上传文件不分块，可以直接从文件管理上传，不需要在聊天页面上传

我目前使用的api可以识别文件内容回答，不需要分块，另外如果从文件管理器中上传，然后引用文件提问时会报错，不知道为什么。

**Comment by jorben** [comment]
现在应该用的是RAG模式，
先对文件进行分块再向量化
提问的时候先做增强检索，再把检索到的内容提供给LLM

要是能支持Graph-RAG就更好了，现在的分块检索不太强，尤其是要求对整个文档的提炼、总结等，分块检索只能提取了部分块
另外还有就是有的pdf文件包含图片，经常会分片失败

**Comment by arvinxx** [comment]
@jorben Graph RAG 会支持的

**Comment by fushes** [comment]
已经自行修改适配，终结。
