### ISSUE TITLE
[Request] 能否把【用户管理】和【用量统计】加进去

### ISSUE THREAD

**Issue by wcu1117** [lobehub/lobe-chat#3952]
### 🥰 需求描述

我看见源码里面有这几个选项，但是对应的页面功能没有找到，希望能加一下。
想要修改一下用户信息手机之类的，还有统计每个人用了多少

### 🧐 解决方案

我看见源码里面有这几个选项，但是对应的页面功能没有找到，希望能加一下

**Comment by arvinxx** [comment]
开源版里不会加
