### ISSUE TITLE
[Request] 怎么在使用客户端部署的方式时在聊天时上传除图片外的其他类型文件

### ISSUE THREAD

**Issue by gloritygithub26** [lobehub/lobe-chat#3956]
### 🥰 需求描述

我想在客户端部署的方式下，也可以在使用聊天功能的时候上传除了图片外的其他格式的文件，从而让GPT返回文件分析的结果

### 🧐 解决方案

有简单的配置可以实现？
或者通过调整部分源码实现？

**Comment by arvinxx** [comment]
暂时没有计划支持
