### ISSUE TITLE
[Request] 当上传图像大小超过模型限定时，自动压缩图像

### ISSUE THREAD

**Issue by hlc1209** [lobehub/lobe-chat#3959]
### 🥰 需求描述

模型是官方sonnet 3.5
  "error": {
    "error": {
      "type": "error",
      "error": {
        "type": "invalid_request_error",
        "message": "messages.0.content.1.image.source.base64: image exceeds 5 MB maximum: 8845948 bytes > 5242880 bytes"
      }

### 🧐 解决方案

当上传图像大小超过模型限定时，自动压缩图像

**Comment by sxjeru** [comment]
自动压缩很难保证所有图片能压缩到 5MB 吧，还是建议用户自行处理。

**Comment by enor2017** [comment]
还是非常希望能实现这个功能，比如大概算一个压缩长宽的比例，或者用二分查找搜一下。现在手机拍的图都很大，在手机端完全没法用图片的功能
