### ISSUE TITLE
[Bug] 从助手市场添加助手，与默认插件合并出错

### ISSUE THREAD

**Issue by MartialBE** [lobehub/lobe-chat#396]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

当你的默认插件开启顺序如下图时：
<img width="649" alt="iShot_2023-11-02_18 00 49" src="https://github.com/lobehub/lobe-chat/assets/42402987/74d3f8b3-bef4-49e7-b8cd-e55e00a3aaf3">

这时候去助手市场，添加`网页内容总结专家`， 会将 `时钟`插件覆盖，并且重复显示 `网站爬虫`插件

<img width="658" alt="iShot_2023-11-02_18 01 03" src="https://github.com/lobehub/lobe-chat/assets/42402987/dbfc695c-5051-485d-8ab2-2ee5d67b0829">

**Comment by arvinxx** [comment]
奇怪，为啥你的这两个角色会互相覆盖呢？

**Comment by MartialBE** [comment]
> 奇怪，为啥你的这两个角色会互相覆盖呢？

在全局设置开启插件 按照我上面图片的顺序开启后。再去助手市场添加插件。100%复现。 注意顺序。如果不是这个顺序就正常....

**Comment by arvinxx** [comment]
好的 晚上我试试。看是什么问题

**Comment by MartialBE** [comment]
这是操作视频。


https://github.com/lobehub/lobe-chat/assets/42402987/701283de-7102-49c7-8e9a-72f535d79c40
