### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Clangman** [lobehub/lobe-chat#3961]
### 📦 Environment

Docker

### 📌 Version

1.17.2

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

I cannot find "DeepSeek-coder" in the "Model List - DeepSeek". There is only one option available.
![image](https://github.com/user-attachments/assets/b13d4bbb-d7bf-4150-ba57-e474b943312c)

### 🚦 Expected Behavior

I need "DeepSeek-coder" to appear, just like in the user guide.
![image](https://github.com/user-attachments/assets/dee5654d-20b3-4fcb-8fe8-9150318dbacb)

**Comment by SpeedupMaster** [comment]
The DeepSeek V2 Chat and DeepSeek Coder V2 models have been merged and upgraded, with the upgraded new model being DeepSeek V2.5.

**Comment by sxjeru** [comment]
ref: https://platform.deepseek.com/api-docs/quick_start/pricing/
