### ISSUE TITLE
[Bug] docker-compose部署LobeChat 服务端数据库版本provider logto is not supported

### ISSUE THREAD

**Issue by chenchengzi** [lobehub/lobe-chat#3963]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

采用docker-compose部署LobeChat 服务端数据库版本，打开主页面xxxx:3210时页面显示500
![image](https://github.com/user-attachments/assets/4e8f8a5d-bcf9-4e11-b22a-02d836ff5627)

查看日志报错如下
lobe-database  | 
lobe-database  | Error: [NextAuth] provider logto is not supported
lobe-database  |     at /app/.next/server/src/middleware.js:400:60330
lobe-database  |     at Array.map (<anonymous>)
lobe-database  |     at 9353 (/app/.next/server/src/middleware.js:400:60266)
lobe-database  |     at t (/app/.next/server/edge-runtime-webpack.js:1:143)
lobe-database  |     at /app/.next/server/src/middleware.js:423:8108
lobe-database  |     at r (/app/.next/server/edge-runtime-webpack.js:1:1539)
lobe-database  |     at /app/.next/server/src/middleware.js:1:51
lobe-database  |     at Script.runInContext (node:vm:148:12)
lobe-database  |     at runInContext (node:vm:300:6)
lobe-database  |     at evaluateInContext (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/sandbox/context.js:403:38)

相关配置如下
.env
```xml
# NextAuth 鉴权服务提供商部分，以 Logto 为例
# 其他鉴权服务提供商所需的环境变量，请参考：https://lobehub.com/zh/docs/self-hosting/environment-variables/auth
LOGTO_CLIENT_ID=pstvtqe4x0yeduik0ndxx
LOGTO_CLIENT_SECRET=gex9RqyLLtzwb7cGdukYmiWI7VnO3cH5
LOGTO_ISSUER=http://82.157.65.83:3001/oidc
```
docker-compose.yml
```xml
logto:
    image: svhd/logto
    container_name: lobe-logto
    ports:
      - '3001:3001'
      - '3002:3002'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'TRUST_PROXY_HEADER=1'
      - 'DB_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/logto'
      - 'ENDPOINT=http://82.157.65.83:3001/'
      - 'ADMIN_ENDPOINT=http://82.157.65.83:3002'
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']

```
请问这种情况如何解决

**Comment by chenchengzi** [comment]
.env中已配置
```xml
# 必填，LobeChat 域名，用于 tRPC 调用
# 请保证此域名在你的 NextAuth 鉴权服务提供商、S3 服务商的 CORS 白名单中
APP_URL=http://82.157.65.83:3210

# NEXT_AUTH 相关，也即鉴权服务必需的环境变量
NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg
# 必填，指定鉴权服务提供商，这里以 Logto 为例
NEXT_AUTH_SSO_PROVIDERS=logto
NEXTAUTH_URL=http://82.157.65.83:9000/api/auth
LOGTO_CLIENT_ID=pstvtqe4x0yeduik
LOGTO_CLIENT_SECRET=gex9RqyLLtzwb7cGdukYmiW
LOGTO_ISSUER=http://82.157.65.83:3001/oidc

```

**Comment by SpeedupMaster** [comment]
> .env中已配置
> 
> ```
> # 必填，LobeChat 域名，用于 tRPC 调用
> # 请保证此域名在你的 NextAuth 鉴权服务提供商、S3 服务商的 CORS 白名单中
> APP_URL=http://82.157.65.83:3210
> 
> # NEXT_AUTH 相关，也即鉴权服务必需的环境变量
> NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg
> # 必填，指定鉴权服务提供商，这里以 Logto 为例
> NEXT_AUTH_SSO_PROVIDERS=logto
> NEXTAUTH_URL=http://82.157.65.83:9000/api/auth
> LOGTO_CLIENT_ID=pstvtqe4x0yeduik
> LOGTO_CLIENT_SECRET=gex9RqyLLtzwb7cGdukYmiW
> LOGTO_ISSUER=http://82.157.65.83:3001/oidc
> ```

`NEXTAUTH_URL=http://82.157.65.83:9000/api/auth`
改成
`NEXTAUTH_URL=http://82.157.65.83:3210/api/auth`

**Comment by chenchengzi** [comment]
> > .env中已配置
> > ```
> > # 必填，LobeChat 域名，用于 tRPC 调用
> > # 请保证此域名在你的 NextAuth 鉴权服务提供商、S3 服务商的 CORS 白名单中
> > APP_URL=http://82.157.65.83:3210
> > 
> > # NEXT_AUTH 相关，也即鉴权服务必需的环境变量
> > NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg
> > # 必填，指定鉴权服务提供商，这里以 Logto 为例
> > NEXT_AUTH_SSO_PROVIDERS=logto
> > NEXTAUTH_URL=http://82.157.65.83:9000/api/auth
> > LOGTO_CLIENT_ID=pstvtqe4x0yeduik
> > LOGTO_CLIENT_SECRET=gex9RqyLLtzwb7cGdukYmiW
> > LOGTO_ISSUER=http://82.157.65.83:3001/oidc
> > ```
> 
> `NEXTAUTH_URL=http://82.157.65.83:9000/api/auth` 改成 `NEXTAUTH_URL=http://82.157.65.83:3210/api/auth`

感谢指正，不过修改后出现了新的错误日志如下
![image](https://github.com/user-attachments/assets/9d91193d-625e-455a-8c7a-41e0eb86410e)

**Comment by SpeedupMaster** [comment]
看下docker compose和.enn文件里的其他配置有没有问题

**Comment by chenchengzi** [comment]
> 看下docker compose和.enn文件里的其他配置有没有问题

详细配置如下
docker-compose.yml
```xml
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=lobe'
      - 'POSTGRES_PASSWORD=uWNZugjBqixf8dxC'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=cz'
      - 'MINIO_ROOT_PASSWORD=cz111111'
      - 'MINIO_DOMAIN=http://82.157.65.83:9000'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=http://82.157.65.83:3210' # Your LobeChat's domain name.
    restart: always
    command: >
      server /etc/minio/data --address ":9000" --console-address ":9001"

  logto:
    image: svhd/logto
    container_name: lobe-logto
    ports:
      - '3001:3001'
      - '3002:3002'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'TRUST_PROXY_HEADER=1'
      - 'DB_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/logto'
      - 'ENDPOINT=http://82.157.65.83:3001/'
      - 'ADMIN_ENDPOINT=http://82.157.65.83:3002'
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-database
    ports:
      - '3210:3210'
    depends_on:
      - postgresql
      - minio
      - logto
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local

```

.env
```xml 
# 必填，LobeChat 域名，用于 tRPC 调用
# 请保证此域名在你的 NextAuth 鉴权服务提供商、S3 服务商的 CORS 白名单中
APP_URL=http://82.157.65.83:3210

# Postgres 相关，也即 DB 必需的环境变量
KEY_VAULTS_SECRET=Kix2wcUONd4CX51E/ZPAd36BqM4wzJgKjPtz2sGztqQ=
DATABASE_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/lobe

# NEXT_AUTH 相关，也即鉴权服务必需的环境变量
NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg
NEXT_AUTH_SSO_PROVIDERS=logto
NEXTAUTH_URL=http://82.157.65.83:3210/api/auth

# NextAuth 鉴权服务提供商部分，以 Logto 为例
LOGTO_CLIENT_ID=pstvtqe4x0yeduik0ndxx
LOGTO_CLIENT_SECRET=gex9RqyLLtzwb7cGdukYmiWI7VnO3cH5
LOGTO_ISSUER=http://82.157.65.83:3001/oidc

# 代理相关，如果你需要的话（比如你使用 GitHub 作为鉴权服务提供商）
# HTTP_PROXY=http://localhost:7890
# HTTPS_PROXY=http://localhost:7890

# S3 相关，也即非结构化数据（文件、图片等）存储必需的环境变量
# 这里以 MinIO 为例
S3_ACCESS_KEY_ID=9VXsvLu592YIc3ORCRdA
S3_SECRET_ACCESS_KEY=AzZD7gMCmDqNYGlO3B6L0Dbzbwwg9T65j8FBeYL8
# 必填，S3 的 Endpoint，用于服务端/客户端连接到 S3 API
S3_ENDPOINT=http://82.157.65.83:9000
S3_BUCKET=lobe
S3_PUBLIC_DOMAIN=http://82.157.65.83:9000
S3_ENABLE_PATH_STYLE=1
NEXT_PUBLIC_S3_DOMAIN=http://82.157.65.83:9000
# 其他基础环境变量，视需求而定。注意不要有 ACCESS_CODE
# 请参考：https://lobehub.com/zh/docs/self-hosting/environment-variables/basic
# 请注意，对于服务端版本，其 API 必须支持嵌入（OpenAI text-embedding-3-small）模型，否则无法对上传文件进行处理，但你无需在 OPENAI_MODEL_LIST 中指定此模型
# OPENAI_API_KEY=sk-xxxx
# OPENAI_PROXY_URL=https://api.openai.com/v1
# OPENAI_MODEL_LIST=..

```

**Comment by SpeedupMaster** [comment]
MINIO_ROOT_USER length should be at least 3, and MINIO_ROOT_PASSWORD length at least 8 characters
minio用户名和密码长度太短
`NEXT_PUBLIC_S3_DOMAIN=http://82.157.65.83:9000` 这个不需要了
其他的没啥问题，不过这两个也不影响lobechat站点的呀
![image](https://github.com/user-attachments/assets/c2b23012-cfd2-4822-940b-deb9d1473e5f)
这4个都正常运行吗？

**Comment by zhangleijun111** [comment]
> > 看下docker compose和.enn文件里的其他配置有没有问题
> 
> 详细配置如下 docker-compose.yml
> 
> ```
> services:
>   postgresql:
>     image: pgvector/pgvector:pg16
>     container_name: lobe-postgres
>     ports:
>       - '5432:5432'
>     volumes:
>       - './data:/var/lib/postgresql/data'
>     environment:
>       - 'POSTGRES_DB=lobe'
>       - 'POSTGRES_PASSWORD=uWNZugjBqixf8dxC'
>     healthcheck:
>       test: ['CMD-SHELL', 'pg_isready -U postgres']
>       interval: 5s
>       timeout: 5s
>       retries: 5
>     restart: always
> 
>   minio:
>     image: minio/minio
>     container_name: lobe-minio
>     ports:
>       - '9000:9000'
>       - '9001:9001'
>     volumes:
>       - './s3_data:/etc/minio/data'
>     environment:
>       - 'MINIO_ROOT_USER=cz'
>       - 'MINIO_ROOT_PASSWORD=cz111111'
>       - 'MINIO_DOMAIN=http://82.157.65.83:9000'
>       - 'MINIO_API_CORS_ALLOW_ORIGIN=http://82.157.65.83:3210' # Your LobeChat's domain name.
>     restart: always
>     command: >
>       server /etc/minio/data --address ":9000" --console-address ":9001"
> 
>   logto:
>     image: svhd/logto
>     container_name: lobe-logto
>     ports:
>       - '3001:3001'
>       - '3002:3002'
>     depends_on:
>       postgresql:
>         condition: service_healthy
>     environment:
>       - 'TRUST_PROXY_HEADER=1'
>       - 'DB_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/logto'
>       - 'ENDPOINT=http://82.157.65.83:3001/'
>       - 'ADMIN_ENDPOINT=http://82.157.65.83:3002'
>     entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']
> 
>   lobe:
>     image: lobehub/lobe-chat-database
>     container_name: lobe-database
>     ports:
>       - '3210:3210'
>     depends_on:
>       - postgresql
>       - minio
>       - logto
>     env_file:
>       - .env
>     restart: always
> 
> volumes:
>   data:
>     driver: local
>   s3_data:
>     driver: local
> ```
> 
> .env
> 
> ```
> # 必填，LobeChat 域名，用于 tRPC 调用
> # 请保证此域名在你的 NextAuth 鉴权服务提供商、S3 服务商的 CORS 白名单中
> APP_URL=http://82.157.65.83:3210
> 
> # Postgres 相关，也即 DB 必需的环境变量
> KEY_VAULTS_SECRET=Kix2wcUONd4CX51E/ZPAd36BqM4wzJgKjPtz2sGztqQ=
> DATABASE_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/lobe
> 
> # NEXT_AUTH 相关，也即鉴权服务必需的环境变量
> NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg
> NEXT_AUTH_SSO_PROVIDERS=logto
> NEXTAUTH_URL=http://82.157.65.83:3210/api/auth
> 
> # NextAuth 鉴权服务提供商部分，以 Logto 为例
> LOGTO_CLIENT_ID=pstvtqe4x0yeduik0ndxx
> LOGTO_CLIENT_SECRET=gex9RqyLLtzwb7cGdukYmiWI7VnO3cH5
> LOGTO_ISSUER=http://82.157.65.83:3001/oidc
> 
> # 代理相关，如果你需要的话（比如你使用 GitHub 作为鉴权服务提供商）
> # HTTP_PROXY=http://localhost:7890
> # HTTPS_PROXY=http://localhost:7890
> 
> # S3 相关，也即非结构化数据（文件、图片等）存储必需的环境变量
> # 这里以 MinIO 为例
> S3_ACCESS_KEY_ID=9VXsvLu592YIc3ORCRdA
> S3_SECRET_ACCESS_KEY=AzZD7gMCmDqNYGlO3B6L0Dbzbwwg9T65j8FBeYL8
> # 必填，S3 的 Endpoint，用于服务端/客户端连接到 S3 API
> S3_ENDPOINT=http://82.157.65.83:9000
> S3_BUCKET=lobe
> S3_PUBLIC_DOMAIN=http://82.157.65.83:9000
> S3_ENABLE_PATH_STYLE=1
> NEXT_PUBLIC_S3_DOMAIN=http://82.157.65.83:9000
> # 其他基础环境变量，视需求而定。注意不要有 ACCESS_CODE
> # 请参考：https://lobehub.com/zh/docs/self-hosting/environment-variables/basic
> # 请注意，对于服务端版本，其 API 必须支持嵌入（OpenAI text-embedding-3-small）模型，否则无法对上传文件进行处理，但你无需在 OPENAI_MODEL_LIST 中指定此模型
> # OPENAI_API_KEY=sk-xxxx
> # OPENAI_PROXY_URL=https://api.openai.com/v1
> # OPENAI_MODEL_LIST=..
> ```

你成功了吗，你这样配法是不是nginx都不需要了

**Comment by cy948** [comment]
强制更新下 lobe-chat-database 这个镜像

**Comment by zhangleijun111** [comment]
我是最新的兄弟



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yao Cai ***@***.***&gt;
发送时间: 2024年9月17日 11:34
收件人: lobehub/lobe-chat ***@***.***&gt;
抄送: zhangleijun111 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [lobehub/lobe-chat] [Bug] docker-compose部署LobeChat 服务端数据库版本provider logto is not supported (Issue #3963)





 
强制更新下 lobe-chat-database 这个镜像

**Comment by chenchengzi** [comment]
> MINIO_ROOT_USER length should be at least 3, and MINIO_ROOT_PASSWORD length at least 8 characters minio用户名和密码长度太短 `NEXT_PUBLIC_S3_DOMAIN=http://82.157.65.83:9000` 这个不需要了 其他的没啥问题，不过这两个也不影响lobechat站点的呀 ![image](https://private-user-images.githubusercontent.com/130642629/367533849-c2b23012-cfd2-4822-940b-deb9d1473e5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjIyMjcsIm5iZiI6MTcyNjYyMTkyNywicGF0aCI6Ii8xMzA2NDI2MjkvMzY3NTMzODQ5LWMyYjIzMDEyLWNmZDItNDgyMi05NDBiLWRlYjlkMTQ3M2U1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwMTEyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MmU4ZWUxNzY3YWU5ZjE3MmE0NTk1NWUxNTM1ZGRiMDE2NGMxNTc5YjEyYmZkMWQ4MjVlYTdiZDZiN2JmOWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z233kly8xFN0hPjCD3QPPiakkyRMWKK6BDQTLjfu-rU) 这4个都正常运行吗？

其他未发现报错，不配置NEXT_PUBLIC_S3_DOMAIN=http://82.157.65.83:9000的话会报下面这个错误，不清楚什么原因，docker-compose拉取的都是最新版镜像
![image](https://github.com/user-attachments/assets/5f1b243b-1479-4e46-84c3-d4e4a6b8369b)

**Comment by cy948** [comment]
@zhangleijun111  看一下你的 docker 镜像的 hash ，tag 在 https://hub.docker.com/r/lobehub/lobe-chat-database/tags

**Comment by yaleh** [comment]
Mine: sha256:e495a07763f8120081ee010f30be290aeec7c8c15eb0ecad7344b9941abe7493 . Which is different from the one at Docker Hub. 

I pulled it no more than 24 hours ago. I'll pull it again.

**Comment by SpeedupMaster** [comment]
> NEXT_PUBLIC_S3_DOMAIN=http://82.157.65.83:9000

NEXT_PUBLIC_S3_DOMAIN这个现在改成S3_PUBLIC_DOMAIN了，应该是不再需要了。
你把lobechat的镜像改成lobehub/lobe-chat:v1.17.7重新拉取试试。

**Comment by zhangleijun111** [comment]
> > NEXT_PUBLIC_S3_DOMAIN=http://82.157.65.83:9000
> 
> NEXT_PUBLIC_S3_DOMAIN这个现在改成S3_PUBLIC_DOMAIN了，应该是不再需要了。 你把lobechat的镜像改成lobehub/lobe-chat-database：v1.17.7重新拉取试试。

我用了谷歌绕过

> > NEXT_PUBLIC_S3_DOMAIN=http://82.157.65.83:9000
> 
> NEXT_PUBLIC_S3_DOMAIN这个现在改成S3_PUBLIC_DOMAIN了，应该是不再需要了。 你把lobechat的镜像改成lobehub/lobe-chat-database：v1.17.7重新拉取试试。

我用了谷歌烧过https的那个设置，这是我报错的日志
LOGTO_CLIENT_ID will be removed in the future. Please set AUTH_LOGTO_ID instead.
LOGTO_CLIENT_SECRET will be removed in the future. Please set AUTH_LOGTO_SECRET instead.
LOGTO_ISSUER will be removed in the future. Please set AUTH_LOGTO_ISSUER instead.
LOGTO_CLIENT_ID will be removed in the future. Please set AUTH_LOGTO_ID instead.
LOGTO_CLIENT_SECRET will be removed in the future. Please set AUTH_LOGTO_SECRET instead.
LOGTO_ISSUER will be removed in the future. Please set AUTH_LOGTO_ISSUER instead.
\u26a0\ufe0f `NEXT_PUBLIC_S3_DOMAIN` will be de deprecated in the next major version, please replace it with `S3_PUBLIC_DOMAIN` in your env
LOGTO_CLIENT_ID will be removed in the future. Please set AUTH_LOGTO_ID instead.
LOGTO_CLIENT_SECRET will be removed in the future. Please set AUTH_LOGTO_SECRET instead.
LOGTO_ISSUER will be removed in the future. Please set AUTH_LOGTO_ISSUER instead.
\u26a0\ufe0f `NEXT_PUBLIC_S3_DOMAIN` will be de deprecated in the next major version, please replace it with `S3_PUBLIC_DOMAIN` in your env
[auth][error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ib (/app/.next/server/chunks/56239.js:368:43941)
    at async iv (/app/.next/server/chunks/56239.js:368:46576)
    at async ix (/app/.next/server/chunks/56239.js:368:49215)
    at async iU (/app/.next/server/chunks/56239.js:368:53430)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
    at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/server/base-server.js:1359:42)
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}

**Comment by cy948** [comment]
fetch failed 是网络问题，服务器可能与auth endpoint不互通

**Comment by zhangleijun111** [comment]
> fetch failed 是网络问题，服务器可能与auth endpoint不互通

您回答的是我这个问题嘛，另外和logto有关的配置全部使用http而不是https是吧

**Comment by zhangleijun111** [comment]
> fetch failed 是网络问题，服务器可能与auth endpoint不互通

我现在点击登录报这个错误
{"code":"oidc.invalid_redirect_uri","message":"无效返回链接, 该 redirect_uri 未被此应用注册。","error":"invalid_redirect_uri","error_description":"redirect_uri did not match any of the client's registered redirect_uris","state":"eyJyYW5kb20iOiJxOFhndnRmc3ZCSEM0QlpvTGtqZGd6ODJCbnl6UldOVE9uTjNPRnczaUd3In0","iss":"http://172.20.8.120:3001/oidc"}

**Comment by cy948** [comment]
先用 AUTH_URL ，另外 logto 只支持https。

**Comment by zhangleijun111** [comment]
> NEXT_PUBLIC_S3_DOMAIN

我知道不是说--ignore加谷歌浏览器绕过他嘛，我现在logto倒是登陆配置好了，但是进lobechat点登陆不行了，这是啥问题呀？？？

**Comment by zhangleijun111** [comment]
> 先用 AUTH_URL ，另外 logto 只支持https。

[
![14b876f3ef415939c90bcb919fd96eb](https://github.com/user-attachments/assets/3403b709-7db9-4a5f-885a-5ad17ae46d1f)
](url)这里要改伐

**Comment by arvinxx** [comment]
新版文档已上线，推荐使用 Casdoor。 https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose

**Comment by huangzsdy** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> A new version of the documentation is now online, and it is recommended to use Casdoor. https://lobehub.com/en/docs/self-hosting/server-database/docker-compose

请问有没有不联网的方案，即第一次安装时联网，后续整个docker都搬迁到私人部署的内网环境
