### ISSUE TITLE
[Request] 是否考虑接入用户系统功能

### ISSUE THREAD

**Issue by guling-io** [lobehub/lobe-chat#397]
### 🥰 需求描述 | Feature Description

是否考虑接入用户系统功能

### 🧐 解决方案 | Proposed Solution

是否考虑接入用户系统功能

**Comment by arvinxx** [comment]
LobeChat 中不会，LobeChat 的定位始终是一个本地优先的 Chatbot 客户端。用户系统请自行实现~
