### ISSUE TITLE
[Bug] 图片识别需要点重新生成才能成功

### ISSUE THREAD

**Issue by alexbiaolol** [lobehub/lobe-chat#3979]
### 📦 Environment

Docker

### 📌 Version

8896d5dde4cf v1.17.4

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/74dfaff5-783c-4bb2-84e1-cae1887070b7)

每一次直接识别都是不成功的，需要点“重新生成”，就可以识别图片了。很奇怪。

### 📷 Recurrence Steps

图片里面的1 -> 2 -> 3

### 🚦 Expected Behavior

需要第一次就能识别

**Comment by arvinxx** [comment]
duplicate #3760
