### ISSUE TITLE
[Request] Support chatting without rewrite user messages

### ISSUE THREAD

**Issue by Stardust-SJF** [lobehub/lobe-chat#3980]
### 🥰 Feature Description

I found that in some scenarios the rewritten message cannot clearly reflect the user's original message's meaning, leading to a misunderstanding of AI models. There should be an option to control whether user messages can be rewritten before sending to LLM models.

### 🧐 Proposed Solution

Add a button in settings to allow users to send messages without rewriting.

**Comment by arvinxx** [comment]
You are right, I'm working on it
