### ISSUE TITLE
[Bug] 无法调用new-api中的Meta-Llama-3.1-405B-Instruct模型

### ISSUE THREAD

**Issue by a15355447898a** [lobehub/lobe-chat#3983]
### 📦 部署环境

Docker

### 📌 软件版本

1.17.4

### 💻 系统环境

Other Linux

### 🌐 浏览器

Edge

### 🐛 问题描述

我在[https://aigc.x-see.cn](https://aigc.x-see.cn)上面买了个转发的api,其中有Meta-Llama-3.1-405B-Instruct模型和其他的模型
![image](https://github.com/user-attachments/assets/7e51c5f6-b52d-47ec-99ce-acdf49d1f42f)

我可以正确调用gpt-4o.gpt-4o-mini等等各种模型,除了Meta-Llama-3.1-405B-Instruct

调用它会得到一个空的返回值

### 🚦 期望结果

应该正确返回ai的返回值

### 📝 补充信息

我确信api站点没有错误,因为我可以在chatbox上面正确调用Meta-Llama-3.1-405B-Instruct模型

![image](https://github.com/user-attachments/assets/b478b779-8315-44d1-b2bf-0749d9ac1924)

直接请求api也证明站点没有问题

![image](https://github.com/user-attachments/assets/82ae5aac-3202-416b-bef7-431b6bbaf378)

**Comment by arvinxx** [comment]
这个是 new-api 的问题吧，很明显你这个接口的输出结果不符合 OpenAI Stream 输出的标准规范。

我们兼容的场景是这样的：

```ts
  it('should handle content with finish_reason', async () => {
    const mockOpenAIStream = new ReadableStream({
      start(controller) {
        controller.enqueue({
          id: '123',
          model: 'deepl',
          choices: [
            {
              index: 0,
              delta: { role: 'assistant', content: 'Introduce yourself.' },
              finish_reason: 'stop',
            },
          ],
        });

        controller.close();
      },
    });

    const protocolStream = OpenAIStream(mockOpenAIStream);

    const decoder = new TextDecoder();
    const chunks = [];

    // @ts-ignore
    for await (const chunk of protocolStream) {
      chunks.push(decoder.decode(chunk, { stream: true }));
    }

    expect(chunks).toEqual(
      ['id: 123', 'event: text', `data: "Introduce yourself."\n`].map((i) => `${i}\n`),
    );
  });
```
标准的是 `delta` ，而不应该是 `message` 字段。

请给 new-api 提 issue，这个不属于 LobeChat 应该管的问题。既然要兼容 OpenAI API 规范，请兼容准确
