### ISSUE TITLE
[Bug] Auth module  and configurations should not be part of lobe-chat-database. 

### ISSUE THREAD

**Issue by jwu-sym** [lobehub/lobe-chat#3987]
### 📦 部署环境

Docker

### 📌 软件版本

*

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

Forcing auth for database version of lobe-chat seemed an architectural flaw.  Open-WebUI project never imposed auth requirement. Opensource project usualy is a tool, not a massive social application. 
When database and RAG needed for lobe-chat for the version, please do not enforce auth, it's an overkill.

**Comment by arvinxx** [comment]
database version need auth to know who you are, or the data can't be saved in the db. Open WebUI have implemented a basic login/auth feature but we don't. They also have auth and enforce it, it's not a good example.

I think each open source project should find it's way in the whole ecosystem. LobeChat is a chat framework for modern chat experience, mutli-modal, plugin system and knowledge base. I don't think the auth should be the core part of LobeChat so 
 we won't take time into do the basic function like encrpt user password or send email verifaciation, and just throw this work to the SSO providers (like Auth0 , Clerk , Casdoor), who can be more professional.

>  Opensource project usualy is a tool, not a massive social application.

We don't position LobeChat just a tool, we prefer to make it an open-source AI application. So we will keep to involve it with more and more features and more flexible intergation.
