### ISSUE TITLE
[Request] 增加请求头作为身份验证方式

### ISSUE THREAD

**Issue by GZYZhy** [lobehub/lobe-chat#3995]
### 🥰 需求描述

在内部部署（如团队或个人工具）的场景下，LobeChat经常被部署在反向代理的后端。以上场景中，很多反向代理过程中已经集成了单点登录功能，可以通过向后端传输"X-REMOTE-USER"等请求头来传递已通过验证的用户信息。LobeChat的自部署数据库版可否添加一种模式，直接通过读取用户定义的请求头来获取用户名、电子邮件、头像、UUID？个人认为这一功能将极大便利LobeChat作为团队工作台的集成工具之一出现。

## 方式一
- 服务部署时，指定`AUTH_BY_HEADER=TRUE`,`AUTH_USERNAME_HEADER=X-REMOTE-USER-NAME`,`AUTH_USERID_HEADER=X-REMOTE-USER-ID`,`AUTH_USEREMAIL_HEADER=X-REMOTE-USER-EMAIL`,`AUTH_USERFAVICON_HEADER=X-REMOTE-USER-FAVICON`等变量；
- 服务运行中，直接读取访问者的对应请求头，完成无感身份认证。
- 个人认为此方法非常普适，但可能安全性略差，需要反向代理服务器注意请求头的过滤，不过这是部署团队自己要注意的事情了。

## 方式二
- 很多团队的反向代理中认证方式也是OIDC或OAuth2.0，
- 通过读取其传递的`X-REMOTE-USER-TOKEN`等类似的OAuth2.0 Token，再通过Token从SSO拉取用户信息来完成无感身份认证。
- 个人认为此方法泛用性较差，可能不兼容团队的一些情况，但安全性略高，可以预防伪造请求头攻击。

## 目的
主要就是为了免除登录团队工具之后，跳转或通过内嵌页面来到LobeChat后还得再登陆一次的繁琐。

### 📝 补充信息

对于我提到的”集成了身份认证的反向代理服务器“，可以以[oauth2-proxy/oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy)做个参考，当然，很多团队相关的功能是自己实现的，集成在自己的工作台里。
不太了解项目的构成，也暂时没时间细细阅读代码，所以无法自己动手修改。不过个人认为此功能还是有很大应用前景的。如蒙关注，感激不尽。

**Comment by GZYZhy** [comment]
这一功能本质上只是将身份验证前移到反向代理服务器层面了，没有改变任何LobeChat本身功能，也不涉及权限分配、价格统计等商业行为，应该可以在开源版采用吧

**Comment by arvinxx** [comment]
@GZYZhy 能否详细解释下 LobeChat 和网关之间的请求交互逻辑。是需要 LobeChat 在向网关发送请求时带上什么特定的标记吗？这个请求的范围是怎么样的？是所有页面，还是部分 url ，还是仅鉴权的请求？

**Comment by GZYZhy** [comment]
- 访问的流程如下：
用户打开网站=》反向代理服务器（Nginx）对用户进行身份验证=》身份验证通过，反向代理服务器（Nginx）在用户的请求中额外插入身份验证头（例如x-remote-user）=》请求被反向代理服务器（Nginx）发送到lobechat =》lobechat直接信任请求头传递的信息，以其内容作为可信的用户信息=》正常提供服务响应=》反向代理服务器（Nginx）将响应发给用户=》用户在浏览器上成功浏览。
- lobechat在此流程中需要做到的只有**读取**发到lobechat请求中某些指定的请求头，并直接将其作为用户信息来使用。

**Comment by arvinxx** [comment]
> 因此，我认为可以对于用户的每个请求，均进行一次检测，检测请求头中的用户和浏览器本地保存的用户是否为同一个。如果二者不符，以请求头中的用户信息为准提供服务，并用请求头的用户信息覆盖浏览器本地的保存。如果浏览器中没有保存任何用户信息（用户没登录过），则将请求头的用户信息写到浏览器中。如果没有请求头，代表请求并非按标准流程来自反向代理服务器，直接拒绝服务（401 unauthorized）。这样可以防止用户切换了账号而浏览器cookie中保存的仍是旧信息的问题。

这个和我们在服务端db 的版本中实现是不兼容的，用户信息并没有存储在浏览器本地而是在数据库中，next-auth 的鉴权是会去过一道数据库的，所以用纯请求头鉴权的方案应该不太可行。建议走标准 OIDC 的模式
