### ISSUE TITLE
[Bug] 在服务器版本中，是否有导出配置与对话的功能？

### ISSUE THREAD

**Issue by one-pyy** [lobehub/lobe-chat#3998]
### 📦 部署环境

Other

### 📌 软件版本

v1.17.7-docker-lobe_chat_database

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

在服务器版本中，是否已经删去了导出配置与对话的功能？因为原本浏览器版本是有这个功能的，部署了服务器才发现这个功能消失了（无法备份一些配置）

### 📷 复现步骤

![image](https://github.com/user-attachments/assets/b4db0e6e-d97c-418d-88ac-386da23a474e)

点开头像，原本有导出但现在消失了；手机版本上导入按钮也没有

### 🚦 期望结果

期望能像浏览器版本一样能导出对话、助手配置等（可能数据库不能导出，会比较麻烦）

**Comment by ZhenyuXiaoLab** [comment]
同求此功能！

**Comment by arvinxx** [comment]
暂时不支持
