### ISSUE TITLE
[Request] Hotkey/Shortcut Key to open new agent conversation?

### ISSUE THREAD

**Issue by sanebg** [lobehub/lobe-chat#4000]
### 🥰 Feature Description

I'm kinda shocked this is missing since this is available on all the major competitors (e.g. Chatbox for example). Especially when it comes to AI  and such it's a real shame there is no Keyboard Shortcuts section

### 🧐 Proposed Solution

Implement keyboard shortcuts to manage new chats, close existing etc.

**Comment by arvinxx** [comment]
try `ALT` + `N`

<img width="338" alt="image" src="https://github.com/user-attachments/assets/7252f92b-fdf6-462d-baa5-e544e4c96ae9">
