### ISSUE TITLE
[Bug] lobe-chat-db使用compose线上部署，logto启动后自动退出（其他服务正常）

### ISSUE THREAD

**Issue by Amandizz** [lobehub/lobe-chat#4007]
### 📦 Environment

Docker

### 📌 Version

27.1.2

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

lobe-chat-db使用compose线上部署，logto启动后自动退出（其他服务正常）
注：几天之前同样的操作，没有任何问题。就最近两天出现的这种问题。
报错信息：
> cli
> logto db seed --swe

info Seeding skipped
npm notice
npm notice New patch version of npm available! 10.8.2 -> 10.8.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
npm notice To update run: npm install -g npm@10.8.3
npm notice

> start
> cd packages/core && NODE_ENV=production node .

(node:44) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
cache    warn No Redis client initialized, skipping
pre      error Found undeployed database alterations, you must deploy them first by npm run alteration deploy command.

 See https://docs.logto.io/docs/references/using-cli/database-alteration for reference.

index    error Error while initializing app:
index    error Error: Undeployed database alterations found.
    at checkAlterationState (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26444:9)
    at async Promise.all (index 0)
    at async checkPreconditions (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26408:3)
    at async Promise.all (index 3)
    at async file:///etc/logto/packages/core/build/main-F72FFTZD.js:26480:3

**Comment by SpeedupMaster** [comment]
logto版本更新导致的，可以继续使用 svhd/logto:1.19.0 版本，不会报错

**Comment by Amandizz** [comment]
想骂人， @dosubot 差点让我数据丢失~

**Comment by Amandizz** [comment]
> logto版本更新导致的，可以继续使用 svhd/logto:1.19.0 版本，不会报错

@SpeedupMaster 感谢~ 你说的对！
