### ISSUE TITLE
[Bug] docekr compose 快速启动，配置logto时会出现"http://localhost:3001/unknown-session" 

### ISSUE THREAD

**Issue by xlarryzhu** [lobehub/lobe-chat#4019]
### 📦 部署环境

Docker

### 📌 软件版本

1.19.2

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome, Edge

### 🐛 问题描述

使用 Docker Compose 部署 LobeChat 服务端数据库版本，使用默认配置文件进行快速部署，其余组件可以通过IP:端口进行访问（如IP:3210），但访问logto管理界面（IP:3002)时会自动跳转至"http://localhost:3001/unknown-session" ，无法添加logto的管理员账号。

**Comment by gzxyls** [comment]
我跟你问题一模一样

**Comment by cy948** [comment]
要访问3002的管理员端口，3001不允许直接访问

**Comment by gzxyls** [comment]
就是访问的3002，然后他会自动跳转到标题所示的网址

**Comment by cy948** [comment]
见 https://github.com/logto-io/logto/issues/6531

**Comment by gzxyls** [comment]
> 见 [logto-io/logto#6531](https://github.com/logto-io/logto/issues/6531)

没用，就是按照文档访问的 localhost:3002，才会自动跳转到 http://localhost:3001/unknown-session

**Comment by onion9156** [comment]
same issue using production deployment on docker compose
accessing mydomain.com would access lobechat web interface
once I click login button it redirects to `http://localhost:3001/oidc/auth?response_type=code&client_id=a2su5yoxykq6oroycsy3q&redirect_uri=http%3A%2F%2Flocalhost%3A3210%2Fapi%2Fauth%2Fcallback%2Flogto&scope=openid+offline_access+profile+email&state=eyJyYW5kb20iOiJfQ0tpVmhzUmVWdkRiWG9QcDZJTFNXNElTYzhVS3RRVGlDNjZqNFhwNFpzIn0&code_challenge=TQiAPCy_eiMTtREkHGDNzq1H8BazsFyFN2zEOuXppBM&code_challenge_method=S256`
my reverse proxy is working, as accessing s3 panel through lobe-s3-ui.mydomain.com works
just that logto keeps redirecting me to localhost despite REDIRECT_URL being correctly set according to the documentation

**Comment by LeGibet** [comment]
从外网访问出问题的话，我自己是把配置里的localhost全部换成了服务器的公网地址，解决了这个问题

**Comment by pinsily** [comment]
docker 配置文件：
- 'ENDPOINT=http://localhost:${LOGTO_PORT}'
- 'ADMIN_ENDPOINT=http://localhost:3002'
      
改成对应的ip：port

**Comment by arvinxx** [comment]
新版文档已上线，已推荐使用 Casdoor。 https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose

**Comment by xlarryzhu** [comment]
good job
