### ISSUE TITLE
[Bug] Seems the knowledge base chunk does not work when public access is disabled(?)

### ISSUE THREAD

**Issue by xqliu** [lobehub/lobe-chat#4031]
### 📦 Environment

Vercel

### 📌 Version

v1.19.2

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

* UI Screenshot 

https://github.com/user-attachments/assets/a6fc17d1-3834-42d5-a052-50b10367e175

* API error 

Request URL: https://chat.muyan.cloud/trpc/lambda/file.getFiles?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22category%22%3Anull%2C%22knowledgeBaseId%22%3A%22kb_0qBJL2If6EQu%22%2C%22q%22%3Anull%2C%22sortType%22%3A%22desc%22%2C%22sorter%22%3A%22createdAt%22%2C%22showFilesInKnowledgeBase%22%3Afalse%7D%2C%22meta%22%3A%7B%22values%22%3A%7B%22category%22%3A%5B%22undefined%22%5D%7D%7D%7D%7D

Error when call the API directly: 

```
[{"error":{"json":{"message":"UNAUTHORIZED","code":-32001,"data":{"code":"UNAUTHORIZED","httpStatus":401,"path":"file.getFiles"}}}}]
```

```
[
    {
        "result": {
            "data": {
                "json": [
                    {
                        "createdAt": "2024-09-13T07:01:22.124Z",
                        "fileType": "text/plain",
                        "id": "file_YQZo5zRCV1bM",
                        "name": "customization.groovy",
                        "size": 13119,
                        "updatedAt": "2024-09-13T08:28:34.965Z",
                        "url": "https://xxxxx",
                        "chunkCount": null,
                        "chunkingError": {
                            "body": {
                                "detail": "trigger file parse async task error. Please check your app is public available or check your proxy settings is set correctly."
                            },
                            "name": "TaskTriggerError"
                        },
                        "chunkingStatus": "error",
                        "embeddingError": null,
                        "embeddingStatus": null,
                        "finishEmbedding": false
                    },
```

### 📷 Recurrence Steps

1. Enable the setting that user have to login to use the lobe-chat
2. Upload knowledge base
3. Try to chunk the file

### 🚦 Expected Behavior

Should be able to chunk the file successfully. 

### 📝 Additional Information

I guess that's related to the setting that user have to login to use lobe-chat.

**Comment by xqliu** [comment]
很奇怪，pdf 文件可以分块成功，groovy 文件，md 文件，png 文件这些都没法分块成功

**Comment by arvinxx** [comment]
Vercel 上检查下 APP_URL 配置是否正确。

分块目前有些不支持，可以在这里提： https://github.com/lobehub/lobe-chat/discussions/3550

**Comment by xqliu** [comment]
Looks like related to the knowledge base name contains Chinese? no idea... 

I have changed the name of the knowledge base to LCDP (all English) and uploaded the md file again, and somehow it works now....

Interesting...

Thanks :)
