### ISSUE TITLE
[Bug] 添加apikey之后检查通过，但是模型没有任何输出，也不报错

### ISSUE THREAD

**Issue by neverl805** [lobehub/lobe-chat#4032]
### 📦 部署环境

Docker

### 📌 软件版本

1.19.4

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/user-attachments/assets/8884674a-b042-421b-a11f-11db99ee9d5f)
我在别的网站上可以使用，但是这里配置后，模型没有任何输出，docker镜像也没报错日志

**Comment by arvinxx** [comment]
加 /v1
