### ISSUE TITLE
[Bug] 在流输出过程中，页面会变得异常卡顿，特别是在多模型得情况下 出现明显掉帖 且输出界面卡顿

### ISSUE THREAD

**Issue by Caoxiongk** [lobehub/lobe-chat#4037]
### 📦 部署环境

Docker

### 📌 软件版本

0.1.0

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

流输出过程中，页面会变得异常卡顿，特别是在多模型得情况下 出现明显掉帖 且输出界面卡顿 因为项目是基于以前老版本二开 请问如何解决这个问题呢

### 📷 复现步骤

流输出过程中，页面会变得异常卡顿，特别是在多模型得情况下 出现明显掉帖 且输出界面卡顿 因为项目是基于以前老版本二开 请问如何解决这个问题呢

### 🚦 期望结果

不卡顿

**Comment by Caoxiongk** [comment]
Uploading 飞书20240920-103828.mp4…

**Comment by Caoxiongk** [comment]
https://github.com/user-attachments/assets/6a87c381-b1bc-4853-a4e8-5b1c0f651c9f

https://zanbang.obs.cn-south-1.myhuaweicloud.com/brainyai/2024-09-20/852bac4570874e65a819af326b0ee1cc/飞书20240920103828.mp4

**Comment by arvinxx** [comment]
二开问题不在答疑范围内，自行想办法解决吧。
