### ISSUE TITLE
[Bug] 本地部署数据库版本时无法正常使用S3存储

### ISSUE THREAD

**Issue by jdassd** [lobehub/lobe-chat#4040]
### 📦 Environment

Docker

### 📌 Version

v1.19

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

 有一个BUG 3781 反馈 存储桶本地设置和阿里云都不能连接到OSS报错的问题
![image](https://github.com/user-attachments/assets/1cf30370-c9a5-4af2-a92d-557870a4f205)
这个错误是说S3_ENDPOINT为不合标准的url地址
但实际填入的内容是标准的

后来凑巧经过1Panel面板查看容器参数时发现
参数后面多了`#`号，以及原本应该注释掉的中文
怀疑文档模板的文案是有问题的

在环境配置.env文件中去掉后即可正常导入参数

**Comment by Zoumachuan** [comment]
是这样的，这个env文件除了#后面的注释会变成url的一部分，openaikey的拼写也有问题，希望能修改一下

**Comment by BiFangKNT** [comment]
> 是这样的，这个env文件除了#后面的注释会变成url的一部分，openaikey的拼写也有问题，希望能修改一下

是这样的。我很早之前就提出过教程有问题，一直没改。 #3826  #3909

**Comment by cy948** [comment]
> 是这样的。我很早之前就提出过教程有问题，一直没改。 #3826 #3909

你提个 pr 修改一下？
