### ISSUE TITLE
[Bug] 移动端存在的几个问题

### ISSUE THREAD

**Issue by SAnBlog** [lobehub/lobe-chat#4045]
### 📦 Environment

Docker

### 📌 Version

v1.19.9

### 💻 Operating System

macOS, Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

1.无法查看历史话题
2.话题无法自动重命名
logto注册后无法显示名称,即使在logto后台编辑用户信息后也无法同步到LobeChat,这个问题有点难受

**Comment by SpeedupMaster** [comment]
移动端历史话题正常同步，可以正常查看。话题自动重命名也正常。
![IMG_3378](https://github.com/user-attachments/assets/af2621df-53a6-402c-ac59-2ca2d0c09c4d)

logto需要设置webhook #3774 ，设置后可同步用户名及头像

**Comment by SAnBlog** [comment]
> 移动端历史话题正常同步，可以正常查看。话题自动重命名也正常。 ![IMG_3378](https://private-user-images.githubusercontent.com/130642629/369448855-af2621df-53a6-402c-ac59-2ca2d0c09c4d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDU4ODYsIm5iZiI6MTcyNjg0NTU4NiwicGF0aCI6Ii8xMzA2NDI2MjkvMzY5NDQ4ODU1LWFmMjYyMWRmLTUzYTYtNDAyYy1hYzU5LTJjYTJkMGMwOWM0ZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNTE5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTU1YzM0ZDFiYzM3ZjY5NTY1MTNjNWNjZWM0N2Q4OTgxZTBkNzJlM2ZmOGU5NGJmMjNjNDIzNDE5OTFjYWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N5UY6gaP_df_SuhvnXyEF9jYOFThqQtXudzT_n22ID4)
> 
> logto需要设置webhook #3774 ，设置后可同步用户名及头像

第一个是没发现顶部点击话题可以查看历史话题,不好意思
第二个问题更新到最新版本已经修复了
第三 也解决了感谢回复
