### ISSUE TITLE
[Bug] logto修改用户信息回调超时,webhooks请求/api/webhooks/logto超时

### ISSUE THREAD

**Issue by SAnBlog** [lobehub/lobe-chat#4048]
### 📦 Environment

Docker

### 📌 Version

v1.19.11

### 💻 Operating System

macOS, Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

![Snipaste_2024-09-20_23-59-32](https://github.com/user-attachments/assets/d35b3f55-df8f-46cb-8566-89cba54be737)
![Snipaste_2024-09-21_00-00-57](https://github.com/user-attachments/assets/45bb5e07-c58c-4717-b90b-edd264eabb51)

NEXTAUTH_URL=https://xxx.com/api/auth
APP_URL=https://xxx.com
上述两个参数有没有影响?

**Comment by SAnBlog** [comment]
LOGTO_WEBHOOK_SIGNING_KEY已经配置了

**Comment by cy948** [comment]
你确定你的 logto 能访问到 lobe 吗？

**Comment by SAnBlog** [comment]
> 你确定你的 logto 能访问到 lobe 吗？

可以正常登录的

**Comment by cy948** [comment]
你的lobe部署在本地 但logto是在云端?

**Comment by SAnBlog** [comment]
> 你的lobe部署在本地 但logto是在云端?

是的,logto用的Logto Cloud,lobe是私有部署

**Comment by cy948** [comment]
webhook是由logto server对lobe发起的，你的lobe不能在公网访问到，所以也就无法使用，并不是bug。

**Comment by SAnBlog** [comment]
> webhook是由logto server对lobe发起的，你的lobe不能在公网访问到，所以也就无法使用，并不是bug。

我的服务是公网服务,都是通过域名访问的,https://xxx.com/api/webhooks/logto能直接打开,请求405

**Comment by SAnBlog** [comment]
> logto控制台显示 timeout 基本上就是网络不可达，logto访问不到。

好吧,我猜测可能是云服务厂商那边对境外IP进行了限制
