### ISSUE TITLE
[Request] elevenlabs.io Text To Speech API 

### ISSUE THREAD

**Issue by KnightNFS** [lobehub/lobe-chat#4059]
### 🥰 Feature Description

To give users a wider choice of voices , can be use alternative Text-to-Speech service - elevenlabs.io API

### 🧐 Proposed Solution

Add new Speech Recognition Service selection "elevenlabs.io"
Add API key field ( and ENV VARIABLE )

**Comment by arvinxx** [comment]
duplicate of #651
