### ISSUE TITLE
[Request] Optimize this code file: drizzle.config.ts

### ISSUE THREAD

**Issue by vignesh1507** [lobehub/lobe-chat#4077]
### 🥰 Feature Description

drizzle.config.ts
The above code file needs error handling and some other functionalities. 

### 🧐 Proposed Solution

Error Handling: If dotenv.config() fails to load the .env file, it doesn't handle the error. Consider checking if the environment variables are properly loaded.

1. Schema and Path Strings: Ensure that the paths for schema and out (./src/database/server/schemas/lobechat and ./src/database/server/migrations) exist, or this could lead to runtime issues.

2. Connection String Logic: It only checks NODE_ENV for test. Ensure other environments are correctly handled.

These are just a suggestion to optimize the code much better.

**Comment by arvinxx** [comment]
> Schema and Path Strings: Ensure that the paths for schema and out (./src/database/server/schemas/lobechat and ./src/database/server/migrations) exist, or this could lead to runtime issues.

drizzle.config.ts don't need to run at runtime.


> Connection String Logic: It only checks NODE_ENV for test. Ensure other environments are correctly handled.

don't need to check for the prod. If not set correctly it will just throw Error.


> Error Handling: If dotenv.config() fails to load the .env file, it doesn't handle the error. Consider checking if the environment variables are properly loaded.

Can you provide more detail info about this?
