### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LR0NMAN-git** [lobehub/lobe-chat#4078]
### 📦 部署环境

Docker

### 📌 软件版本

1.19.2

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

txt 文件向量化报错，报错信息：
```
embeddingChunks error {
  message: `{"length":167,"name":"error","severity":"ERROR","code":"58P01","where":"unnamed portal parameter $2 = '...'","file":"dfmgr.c","line":"207","routine":"internal_load_library"}`,
  name: 'EmbeddingError'
}
```
![image](https://github.com/user-attachments/assets/4a474062-39fe-47e1-8fdf-d9a76ae9bae7)

### 📷 复现步骤

1. logto 登录 lobechat
2. 新建 GPT-4o 聊天窗口
3. 从聊天窗口上传 txt 文件

**Comment by arvinxx** [comment]
看样子是你没装 pgvector 插件

**Comment by LR0NMAN-git** [comment]
> 看样子是你没装 pgvector 插件

是的，我发现了，不过我开始部署时是安装了的，现在莫名其妙消失了，感谢回答
