### ISSUE TITLE
[Request] 【模型】和【模型服务商】这俩名字起的比较模糊，不能见名知意

### ISSUE THREAD

**Issue by JustinLeei** [lobehub/lobe-chat#4082]
### 🥰 需求描述

第一次看有点云里雾里的。

### 🧐 解决方案

变成一个菜单，只保留【模型服务商】，在这个菜单下介绍模型即可

**Comment by arvinxx** [comment]
模型和模型服务商是两个概念。OpenAI 是服务商，它提供的模型是比如 GPT3.5 等。Google是服务商，Gemini 是他的模型

**Comment by JustinLeei** [comment]
下面这样的设计是不是更好一些呢 ![image](https://github.com/user-attachments/assets/23c64f15-15bc-4b3b-a3c3-5fa914f8a227)

**Comment by arvinxx** [comment]
@JustinLeei  这在哪里配置供应商的 api key 之类的？
