### ISSUE TITLE
Infinite Loading Issue

### ISSUE THREAD

**Issue by lAnviuml** [lobehub/lobe-chat#4086]
### 📦 Environment

Vercel

### 📌 Version

v1.19.22

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

After following the deployment instructions with Vercel and Clerk, when accessing the application via [https://app.adrien-murillo.com](https://app.adrien-murillo.com), the page gets stuck on an infinite loading screen. The user interface does not load, and no errors are displayed on the screen. The application fails to fully load, preventing any interaction or use of LobeChat's features.

### 📷 Recurrence Steps

1. **Access the Application**:
   - Open Google Chrome.
   - Navigate to [https://app.adrien-murillo.com](https://app.adrien-murillo.com).

2. **Observe the Behavior**:
   - The page displays a loading screen with an animation (e.g., spinning wheel).
   - The loading screen persists indefinitely.
   - No part of the user interface appears.

3. **Check the Browser Console**:
   - Open Developer Tools (F12).
   - Go to the "Console" tab.
   - Note any error or warning messages (see Additional Information section).

### 🚦 Expected Behavior

I expected the application to load normally, displaying the complete user interface, with the ability to sign in via Clerk and use all features provided by LobeChat, including sending messages, creating chats, etc.

### 📝 Additional Information

- **Browser Console**:
  - **Error 1**: `Failed to load resource: the server responded with a status of 500 (Internal Server Error)`.
  - **Error 2**: `Uncaught TypeError: Cannot read property 'user' of undefined at App.js:45`.
  - **Warning**: `Some cookies are misusing the recommended “SameSite“ attribute`.

- **Vercel Logs**:
  - No significant errors appear in the deployment logs.
  - Server functions seem to be deployed correctly.

- **Environment Variables Configuration**:
  - All required environment variables have been configured as per documentation, including:
    - `CLERK_WEBHOOK_SECRET`
    - `CLERK_SECRET_KEY`
    - `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY`
    - `DATABASE_URL`
    - `S3_ACCESS_KEY_ID`
    - `S3_SECRET_ACCESS_KEY`
    - `S3_BUCKET`
    - `S3_ENDPOINT`
    - `S3_PUBLIC_DOMAIN`
    - `APP_URL`
    - `NEXT_PUBLIC_SERVICE_MODE`

- **Troubleshooting Attempts**:
  - **Clerk Configuration Check**:
    - Public and secret keys match those provided by Clerk.
    - The webhook is correctly configured with the URL `https://app.adrien-murillo.com/api/webhooks/clerk`.
  - **Testing on Different Browsers**:
    - The same issue occurs on Firefox and Edge.
  - **Clearing Cache and Using Incognito Mode**:
    - No improvement observed.
  - **Checking CORS Permissions for S3**:
    - CORS rules are configured to allow requests from `https://app.adrien-murillo.com`.

- **Additional Observations**:
  - It seems that the application fails to fetch certain resources or data needed for the initial load.
  - Network requests in the "Network" tab of the Developer Tools show failures on certain APIs.

- **Hypotheses**:
  - The issue might be related to a misconfiguration in Clerk or an incompatibility with the deployed version.
  - A communication issue with the database or S3 storage could also be a contributing factor.

**Comment by arvinxx** [comment]
please give an screenshot of the browser console error

**Comment by lAnviuml** [comment]
Hi @arvinxx ,

Thanks for the suggestion. Here's the screenshot of the browser console error when accessing the application:

![Lobechat](https://github.com/user-attachments/assets/4879f39b-59a3-48c7-b45e-8cad3d81af6b)

The project is live at the following address: [app.adrien-murillo.com](https://app.adrien-murillo.com)

Let me know if you need any more information or if there's anything else I should check.

**Comment by arvinxx** [comment]
<img width="689" alt="image" src="https://github.com/user-attachments/assets/9a76751c-e3ab-4402-98b7-2e5714d8b648">

as this error message. You need to check your clerk config or your network. If you config clerk in the prod. You need to bind the domain config at first.
