### ISSUE TITLE
[Bug] Logto enables email login，but after logging in, there is no default user name and the name is displayed as empty

### ISSUE THREAD

**Issue by 2439241440** [lobehub/lobe-chat#4089]
### 📦 部署环境

Docker

### 📌 软件版本

1.19.22

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

Logto enables email login，but after logging in, there is no default user name and the name is displayed as empty

### 📷 复现步骤

<img width="841" alt="image" src="https://github.com/user-attachments/assets/85ef364f-fe04-48bd-8529-ec8347527d85">
<img width="559" alt="image" src="https://github.com/user-attachments/assets/355ade8c-57f9-41ef-baa4-d59d4a520149">
<img width="330" alt="image" src="https://github.com/user-attachments/assets/24d398fb-d5e1-4885-b9a5-44ce2ede221c">

### 🚦 期望结果

Email login generates a default username or uses an email address as the username

**Comment by SpeedupMaster** [comment]
You need to set up a webhook for logto.  #3774

**Comment by 2439241440** [comment]
> You need to set up a webhook for logto. #3774

I have looked at the relevant content and found that setting a username in the Logto system can indeed update the webhook. However, what I want is to set a default username for the user when logging in for the first time

**Comment by SpeedupMaster** [comment]
logto cannot set a username during registration, you can try using zitadel. 
![image](https://github.com/user-attachments/assets/c92ee648-797c-4550-a897-9c32f8ecc3c4)

**Comment by SpeedupMaster** [comment]
Casdoor is also an option

**Comment by 2439241440** [comment]
> Casdoor is also an option

Okay, I'll give it a try. Thank you
