### ISSUE TITLE
[Request] 插件及Prompt助手服务端永久性存储

### ISSUE THREAD

**Issue by Ruler27** [lobehub/lobe-chat#409]
### 🥰 需求描述 | Feature Description

对话信息和api key什么的都可以不保存，留给SaaS版，但是建议插件和Prompt助手可以保存在服务端，方便多客户端同步。
这样自己用，换个设备输密码就行了，不需要导出导入的步骤。

### 🧐 解决方案 | Proposed Solution

插件及Prompt助手服务端永久性存储。
另外建议给一个通道，让用户可以在自己部署的lobechat里直接分享插件和Prompt助手给你们，这样你们的生态系统也能快点建立起来。
甚至可以直接弄个平台共享给所有用户，用户自己打分，你们也能省去一个个筛选的麻烦。

**Comment by arvinxx** [comment]
> 对话信息和api key什么的都可以不保存，留给SaaS版，但是建议插件和Prompt助手可以保存在服务端，方便多客户端同步。
这样自己用，换个设备输密码就行了，不需要导出导入的步骤。

相关 issue: 
- https://github.com/lobehub/lobe-chat/issues/330

目前构思中的技术方案： 

- #368 

我个人其实是比较强烈的 Local First 主义者，所以这个功能大概率会先于 SaaS 版做出来。大家可以用 WebDAV 或者 Upstash 做同步，保证数据始在个人手中。哪怕我们后面做 SaaS 版，也一定包含这部分的功能。


> 另外建议给一个通道，让用户可以在自己部署的lobechat里直接分享插件和Prompt助手给你们，这样你们的生态系统也能快点建立起来。
> 甚至可以直接弄个平台共享给所有用户，用户自己打分，你们也能省去一个个筛选的麻烦。



目前有地方可以直接分享 Prompt 助手的，点这个按钮就可以发布助手到市场上了。别人也能看到，而且这些助手现在是开源的，大家都能看到：https://github.com/lobehub/lobe-chat-agents

<img width="1534" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/c05419b0-af57-4944-836d-3e672b827235">

至于插件部分，我感觉相对难一点。因为需要投入开发，成本相对高一些。但我们也有地方供大家提交插件：
https://github.com/lobehub/lobe-chat-plugins

**Comment by lknife** [comment]
> > 对话信息和api key什么的都可以不保存，留给SaaS版，但是建议插件和Prompt助手可以保存在服务端，方便多客户端同步。
> > 这样自己用，换个设备输密码就行了，不需要导出导入的步骤。
> 
> 我个人其实是比较强烈的 Local First 主义者，所以这个功能大概率会先于 SaaS 版做出来。大家可以用 WebDAV 或者 Upstash 做同步，保证数据始在个人手中。哪怕我们后面做 SaaS 版，也一定包含这部分的功能。目前构思中的技术方案：
> 
> * [[RFC] 跨端同步WebDAV & YJS #368](https://github.com/lobehub/lobe-chat/discussions/368)
> 
> 相关 issue:
> 
> * [[Request] 增加云同步的功能 #330](https://github.com/lobehub/lobe-chat/issues/330)
> 
> > 另外建议给一个通道，让用户可以在自己部署的lobechat里直接分享插件和Prompt助手给你们，这样你们的生态系统也能快点建立起来。
> > 甚至可以直接弄个平台共享给所有用户，用户自己打分，你们也能省去一个个筛选的麻烦。
> 
> 目前有地方可以直接分享 Prompt 助手的，点这个按钮就可以发布助手到市场上了。别人也能看到，而且这些助手现在是开源的，大家都能看到：https://github.com/lobehub/lobe-chat-agents
> 
> <img alt="image" width="1534" src="https://user-images.githubusercontent.com/28616219/280518774-c05419b0-af57-4944-836d-3e672b827235.png">
> 至于插件部分，我感觉相对难一点。因为需要投入开发，成本相对高一些。但我们也有地方供大家提交插件： https://github.com/lobehub/lobe-chat-plugins

看来你们已经考虑的很全面了。
不存储在服务端的话，多端同步的我有在用思源笔记，我是同步到S3上，他们多设备同步的时候，更晚的那个会提醒云端被锁定了，之前的同步完成才会允许别的设备同步，这个思路不知道对你们有没有用。

**Comment by arvinxx** [comment]
我们在 `v0.141.0` 上线了基于 YJS 与 WebRTC 的实验性数据同步功能，欢迎测试并反馈：
- 反馈issue: #1683
- 背后思考：https://github.com/lobehub/lobe-chat/discussions/1681

如果上述同步功能不满足你的诉求，可以 Reopen 该issue
