### ISSUE TITLE
[Request] 需要 ANTHROPIC_MODEL_LIST 环境变量支持

### ISSUE THREAD

**Issue by Noah-Wu66** [lobehub/lobe-chat#4093]
### 🥰 需求描述

需要 ANTHROPIC_MODEL_LIST 环境变量支持

### 🧐 解决方案

需要 ANTHROPIC_MODEL_LIST 环境变量支持，能够自由的修改想要的Claude模型

**Comment by arvinxx** [comment]
duplicate of #3726 and PR Welcome
