### ISSUE TITLE
[Bug] 输入了API出现错误

### ISSUE THREAD

**Issue by piboxoh827** [lobehub/lobe-chat#410]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![Screenshot_20231105_200203](https://github.com/lobehub/lobe-chat/assets/147383696/ef29cb7e-2cee-4075-b0bd-5774abe90127)
错误信息：Error requesting OpenAl service . Please troubleshoot or retry based on the following information .

**Comment by arvinxx** [comment]
<img width="876" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/41f2486f-a168-4a42-a30b-bfd93a5e08f0">
这个应该是你的 API 账单的问题吧，详情参考：https://platform.openai.com/docs/guides/error-codes/api-errors
