### ISSUE TITLE
[Bug] can't access aws bedrock models 

### ISSUE THREAD

**Issue by gemnioo** [lobehub/lobe-chat#4100]
### 📦 Environment

Docker

### 📌 Version

v1.19.21

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome, Firefox

### 🐛 Bug Description

I followed this lobe-chat tutorial  https://lobehub.com/docs/usage/providers/bedrock

I can confirm the root account have already grant access to models like Claude 3.5 and Claude 3 series（I could chat in the chat playground

and the new add user have "AmazonBedrockFullAccess" and  "AWSMarketplaceFullAccess" as this manual indicate https://docs.aws.amazon.com/bedrock/latest/userguide/model-access-permissions.html 

and confirm the twice us-east-1 and access key  but still have this error, but the user page have "Access key last used time is now" 

```
{
  "error": {
    "body": {
      "httpStatusCode": 403,
      "requestId": "91768718-b0b7-4d76-b230-af00dffd7b56",
      "attempts": 1,
      "totalRetryDelay": 0
    },
    "message": "You don't have access to the model with the specified model ID.",
    "type": "AccessDeniedException"
  },
  "provider": "bedrock",
  "region": "us-east-1"
}
```

### 🚦 Expected Behavior

pls advise

**Comment by hezhijie0327** [comment]
You need get the access from here first. https://us-east-1.console.aws.amazon.com/bedrock/home?region=us-east-1#/modelaccess
![image](https://github.com/user-attachments/assets/49cef348-b0e1-4005-8e1c-d304fe0bcb9e)
![image](https://github.com/user-attachments/assets/ec6d0dbb-f75a-48de-a94f-d72eb79c6d84)

**Comment by gemnioo** [comment]
as I state. "root account have already grant access to models like Claude 3.5 and Claude 3 series（I could chat in the chat playground"  

and the user "lobechat" which i created.  have the main three full access: 
"AmazonBedrockFullAccess" 
"AWSDataExchangeSubscriberFullAccess"
"AWSMarketplaceFullAccess" 
as followed the documentation 
https://docs.aws.amazon.com/bedrock/latest/userguide/model-access-permissions.html

**Comment by hezhijie0327** [comment]
So weird... Actually, `AmazonBedrockFullAccess` is enough.
![image](https://github.com/user-attachments/assets/d9a17ed0-be28-4ce0-873b-08b812c2c6a0)

BTW, you gain the access in `us-east-1` or other region? Each region's access is isolated.

**Comment by gemnioo** [comment]
Update: 

after open support case. the "can't access aws bedrock models" issue fixed.  As the tutorial https://lobehub.com/docs/usage/providers/bedrock  didn't mention the Connectivity Check request the Anthropic "Claude Instant" model access.

**Comment by 0x2E** [comment]
>  the Connectivity Check request the Anthropic "Claude Instant" model access.

https://github.com/lobehub/lobe-chat/blob/7d1e5c46aecc582308483d329b6007a8f8c76b70/src/config/modelProviders/bedrock.ts#L278

It works for me. Thanks bro!

**Comment by gemnioo** [comment]
update with this still open PR issue: 

https://github.com/lobehub/lobe-chat/issues/2221

and with the aws bedrock claude models support [cross-region inference ](https://docs.aws.amazon.com/bedrock/latest/userguide/inference-profiles-support.html)

seems need lobechat update the bedrock models request endpoint to support muti region request:

'us.anthropic.claude-3-5-sonnet-20241022-v2:0'  or designated the region with 'anthropic.claude-3-5-sonnet-20240620-v1:0'

refer this issues in liteLLM proxy  https://github.com/BerriAI/litellm/issues/6589#issuecomment-2466572532

**Comment by josperrod9** [comment]
@gemnioo which version did you use it to validate?
