### ISSUE TITLE
[Bug] 使用github app认证，登陆时提示invalid redirect uri

### ISSUE THREAD

**Issue by SaltedFish23** [lobehub/lobe-chat#4109]
### 📦 部署环境

Docker

### 📌 软件版本

v1.19.21

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

使用github app进行本地的身份验证，在localhost:3210登陆时会跳转到github的界面，提示invalid redirect uri，然后无反应。
这是具体的界面：
![image](https://github.com/user-attachments/assets/17cc3a19-1465-45b0-8e85-29c553344ee8)
这是.env文件中的设置：
![image](https://github.com/user-attachments/assets/1aaf77ac-ca97-44cb-9063-02ffc14bdb9f)

**Comment by SpeedupMaster** [comment]
Github Callbak URL没设置？
环境变量中NEXTAUTH_URL也要设置

**Comment by SaltedFish23** [comment]
> Github Callbak URL没设置？ 环境变量中NEXTAUTH_URL也要设置

成功了，感谢
一开始看文档写这个是可选所以就没填

**Comment by SaltedFish23** [comment]
> Github Callbak URL没设置？ 环境变量中NEXTAUTH_URL也要设置

如果设置成https://127.0.0.1:3210/api/auth，就会跳转到https://localhost:3210/api/auth/signin?error=MissingCSRF并且报错`localhost发送了无效的响应`，有错误信息`ERR_SSL_PROTOCOL_ERROR`

如果改成https://127.0.0.1:3210/api/auth，就还是会提示invalid redirect uri

这有什么办法吗

**Comment by SpeedupMaster** [comment]
直接使用localhost不行吗？

**Comment by SaltedFish23** [comment]
> 直接使用localhost不行吗？

非常感谢，只要把127.0.0.1全部改成localhost，再用http替代https就行了
