### ISSUE TITLE
[Question] Minio upload file  

### ISSUE THREAD

**Issue by squirrelfeng** [lobehub/lobe-chat#4110]
### 📦 Environment

Docker

### 📌 Version

1.9.24

### 💻 Operating System

Ubuntu

### 🌐 Browser

Firefox

### 🐛 Bug Description

Hello, i deployed with minio, and set config.json in bucket policy, but still cannot upload file, shows it is blocked.
I use my existing minio docker, and should set cors already,

![image](https://github.com/user-attachments/assets/e525d401-8de4-4e92-8746-36a27bf0e747)

![image](https://github.com/user-attachments/assets/8b290f69-9597-4c81-9da1-5cb1789744d8)

**Comment by squirrelfeng** [comment]
it doesn't help, is there any other thing i can do?

**Comment by arvinxx** [comment]
try to set the exactly url?
