### ISSUE TITLE
[Bug] 向量化失败

### ISSUE THREAD

**Issue by hujh818** [lobehub/lobe-chat#4111]
### 📦 Environment

Zeabur

### 📌 Version

latest

### 💻 Operating System

Ubuntu

### 🌐 Browser

Edge

### 🐛 Bug Description

文件上传成功后，向量化失败
![image](https://github.com/user-attachments/assets/d39cd3eb-139c-47d8-a855-06037784c258)

zeabur的log显示是
执行第 1 个任务

任务[1]: embeddings: 1.757s

embeddingChunks error { message: '{}', name: 'EmbeddingError' }

**Comment by arvinxx** [comment]
看下服务端抛错

**Comment by hujh818** [comment]
[
[runtime-log-20240924-111413.log.gz](https://github.com/user-attachments/files/17113650/runtime-log-20240924-111413.log.gz)
](url)
这是lobechat完整的日志

**Comment by BiFangKNT** [comment]
> [ [runtime-log-20240924-111413.log.gz](https://github.com/user-attachments/files/17113650/runtime-log-20240924-111413.log.gz) ](url) 这是lobechat完整的日志

你的key里是否没有`text-embedding-3-small`模型？你的`text-embedding-3-small`是否正常可用？

**Comment by hujh818** [comment]
> > [ [runtime-log-20240924-111413.log.gz](https://github.com/user-attachments/files/17113650/runtime-log-20240924-111413.log.gz) ](url) 这是lobechat完整的日志
> 
> 你的key里是否没有`text-embedding-3-small`模型？你的`text-embedding-3-small`是否正常可用？

是有的，OpenAI().embeddings.create(input = ["测试文本"],model="text-embedding-3-small").data[0].embedding
按这行代码是能跑出结果的

**Comment by hujh818** [comment]
![image](https://github.com/user-attachments/assets/1376394e-1344-41cb-ab55-0e69481ca4bd)
但是在这里面的模型列表里面没有显示

**Comment by BiFangKNT** [comment]
> ![image](https://github.com/user-attachments/assets/1376394e-1344-41cb-ab55-0e69481ca4bd)
> 但是在这里面的模型列表里面没有显示

这里本来就不会显示向量模型的。不是这里有问题

**Comment by hujh818** [comment]
不知道是哪里的问题呢 或者要怎么测试是否是text-embedding-3-small没法调用造成的呢？

**Comment by BiFangKNT** [comment]
> 不知道是哪里的问题呢 或者要怎么测试是否是text-embedding-3-small没法调用造成的呢？

以下是gpt4o的回答，仅供参考：

这个错误消息显示了多个问题，主要与授权、JWT（JSON Web Token）会话和嵌入（embeddings）操作相关。我们可以分解各个部分，逐一分析：

### 1. **JWTSessionError: no matching decryption secret**
   - **问题**：这表示在解密 JWT 时，没有找到匹配的解密密钥。JWT 通常用于用户身份验证或授权，JWT 的加密与解密依赖于一个密钥。这个错误提示无法找到正确的密钥来解密 JWT。
   - **可能原因**：
     1. **配置错误**：服务器端的 JWT 密钥配置可能不正确，或者 JWT 的密钥已被更改但尚未正确更新。
     2. **密钥同步问题**：在使用多个服务器或实例时，可能存在密钥未同步到所有实例的情况。

### 2. **EmbeddingError: '{}'**
   - **问题**：`embeddingChunks error` 表明在执行嵌入操作时发生了错误，但错误信息 `{}` 没有提供详细信息。
   - **可能原因**：
     1. **输入数据问题**：输入的数据可能不符合预期的格式，或者嵌入模型不支持处理该数据。
     2. **模型或服务问题**：嵌入操作可能涉及调用外部模型服务，如果服务不可用或有内部问题，就会导致错误。

### 3. **LangChainChunkingError: Unsupported file type**
   - **问题**：这个错误指出文件类型不被支持。LangChain 在处理文件的嵌入时，可能遇到了不支持的文件格式。
   - **可能原因**：
     1. **文件格式不被支持**：传入的文件格式不在 LangChain 支持的类型列表中。解决方案可能是转换文件格式或检查是否有更适合的文件处理方法。
     2. **模型限制**：用于嵌入的模型不支持处理该文件类型，导致分块处理失败。

### 4. **其他警告**
   - **Label '任务[1]: insert db' already exists for console.time()**：这个警告表示在代码中重复创建了一个 `console.time()` 标签，通常是调试代码时用于计时的工具。多次使用相同标签可能引发警告。
   - **Node 警告**：`(node:19) Warning: Label '任务[1]: insert db' already exists for console.time()` 提示在 Node.js 中发生了重复标签问题。

### 解决方案建议：
1. **JWT 解密问题**：
   - 检查 JWT 的加密和解密密钥配置，确保服务器端使用正确的密钥。
   - 如果使用多个服务器或实例，确保密钥在所有实例之间同步。

2. **嵌入错误**：
   - 查看输入数据，确保其格式正确并与嵌入模型的要求匹配。
   - 检查嵌入服务的状态，确保它们没有挂起或宕机。

3. **文件类型错误**：
   - 检查 LangChain 的文档，确认支持的文件类型。
   - 如果文件类型不被支持，尝试将文件转换为被支持的格式（例如从 `.pdf` 转为 `.txt`）。

4. **Node 警告**：
   - 检查代码中 `console.time()` 的使用，避免重复定义相同的标签。

**Comment by BiFangKNT** [comment]
> 不知道是哪里的问题呢 或者要怎么测试是否是text-embedding-3-small没法调用造成的呢？

我再确认一下，你要分块的文件是什么类型的？

**Comment by arvinxx** [comment]
你先试试换一个官方 key 呢？

**Comment by hujh818** [comment]
> > 不知道是哪里的问题呢 或者要怎么测试是否是text-embedding-3-small没法调用造成的呢？
> 
> 我再确认一下，你要分块的文件是什么类型的？

这种类型都试过，都不行

**Comment by hujh818** [comment]
> 你先试试换一个官方 key 呢？

我没有官方key只有，只有特定openai_base_url的key

**Comment by arvinxx** [comment]
@hujh818  试下 [这家](https://aihubmix.com/home?aff=8DBz)  的 key

**Comment by BiFangKNT** [comment]
> > 你先试试换一个官方 key 呢？
> 
> 我没有官方key只有，只有特定openai_base_url的key

兄啊，现在环境变量不是已经改成`OPENAI_PROXY_URL`了吗？

**Comment by hujh818** [comment]
> > > 你先试试换一个官方 key 呢？
> > 
> > 
> > 我没有官方key只有，只有特定openai_base_url的key
> 
> 兄啊，现在环境变量不是已经改成`OPENAI_PROXY_URL`了吗？

我打错了 我实际用的是OPENAI_PROXY_URL

**Comment by pipuwong** [comment]
> @hujh818 试下 [这家](https://aihubmix.com?aff=8DBz) 的 key

感谢推荐，已成功购买并且解决了向量化失败的问题。
