### ISSUE TITLE
[Bug] 从第二条消息开始，发送图片模型不可见

### ISSUE THREAD

**Issue by redapple0204** [lobehub/lobe-chat#4121]
### 📦 部署环境

Official Preview

### 📌 软件版本

v1.19.31

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

给模型发送第二条消息开始，模型无法正常接收图片
![image](https://github.com/user-attachments/assets/c731daae-56b8-4be7-a3c2-7efa83e2fb1e)

### 📷 复现步骤

先给模型发送第一条消息，然后第二条消息附带一张图片

### 🚦 期望结果

图片能够被正常识别到

### 📝 补充信息

该问题在一个月前的版本出现过，不过在9月初的一次更新修复了该问题。之后该问题又重新出现

**Comment by arvinxx** [comment]
这个问题还没有被修复。 重复 #3760
