### ISSUE TITLE
[Request] 文件向量化支持 GitHub 的 OpenAI Text Embedding 3

### ISSUE THREAD

**Issue by ymefg** [lobehub/lobe-chat#4128]
### 🥰 需求描述

GitHub 里面现已有这两个模型：

- https://github.com/marketplace/models/azure-openai/text-embedding-3-large
- https://github.com/marketplace/models/azure-openai/text-embedding-3-small

向量化能否支持使用 GitHub 的模型？毕竟可以[免费使用](https://docs.github.com/en/github-models/prototyping-with-ai-models#rate-limits)而无需 OpenAI 的 Key。

### 🧐 解决方案

增加 选项/Flag/环境变量 以支持切换到 GitHub 的模型来向量化文件。

**Comment by arvinxx** [comment]
重复 #4128

**Comment by ymefg** [comment]
> 重复 #4128

#4128 刚好就是这个 issue 呀，和哪个重复了？

**Comment by spuniun** [comment]
Why was this issue closed? It would be great to use Azure text-embedding models for this instead of only defaulting to OpenAI

**Comment by arvinxx** [comment]
My fault ,duplicate with #3785
