### ISSUE TITLE
[Bug] pnpm self-hosting:docker-cn@database 报错

### ISSUE THREAD

**Issue by gaspire** [lobehub/lobe-chat#4130]
### 📦 Environment

Other

### 📌 Version

latest

### 💻 Operating System

macOS, Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

 执行pnpm self-hosting:docker-cn@database，报错：
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/85fef8bc-bcba-4cf2-a0ac-437ddb483985">

**Comment by gaspire** [comment]
`310.7 > Build error occurred
310.7 Error: Failed to collect page data for /discover/provider/[slug]
310.7     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/build/utils.js:1268:15
310.7     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
310.7   type: 'Error'
310.7 }
------
Dockerfile.database:84
--------------------`

**Comment by arvinxx** [comment]
你同步最新代码了吗？

**Comment by arvinxx** [comment]
<img width="1845" alt="image" src="https://github.com/user-attachments/assets/93b36347-e5c7-46ab-bff1-0d5e7637dcc2">

无法复现，请自行排查吧。
