### ISSUE TITLE
[Request] 协议商业询问

### ISSUE THREAD

**Issue by 239573049** [lobehub/lobe-chat#4131]
### 🥰 Feature Description

如果我对于1.0的lobechat的版本的源码进行修改，然后进行开源，这个行为是否允许？
如果需要，那么我的开源协议是需要和lobechat一致吗？
还有，如果开源别人在使用我提供的开源项目，那么在不改我的开源基础上商业是否允许？或者在修改我提供的开源项目上商业是否允许？

### 🧐 Proposed Solution

询问行为是否允许

**Comment by arvinxx** [comment]
@239573049

> 如果我对于1.0的lobechat的版本的源码进行修改，然后进行开源，这个行为是否允许？
> 如果需要，那么我的开源协议是需要和lobechat一致吗？

二开非商业化均允许，不需要和 LobeChat 一致。

> 还有，如果开源别人在使用我提供的开源项目，那么在不改我的开源基础上商业是否允许？或者在修改我提供的开源项目上商业是否允许？

如果二开基础上要商业化，需要找我们要授权。具体可以联系 hello@lobehub.com

**Comment by 239573049** [comment]
抱歉，我是指我的开源项目被别人用于商用项目，但是并没有修改源码的情况下别人是否可以商用使用，不会进行修改代码
