### ISSUE TITLE
[Bug] Docker database pgvector connectivity issue on Lobchat files section

### ISSUE THREAD

**Issue by BILAL324** [lobehub/lobe-chat#4134]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

![WhatsApp Image 2024-09-25 at 3 38 53 PM](https://github.com/user-attachments/assets/e66c1278-7997-4221-a5d2-1b634a82abcf)

the Postgresql database pgvector should list the database or if empty should show that 
but it just keep sending get request and get the response of permission denied 
I checked in the docker container of the application the database is accessible properly
as you can see in img but showing error on frontend

![WhatsApp Image 2024-09-25 at 4 10 50 PM](https://github.com/user-attachments/assets/8a6f9591-702e-42e9-bc73-53975ab96a19)

![WhatsApp Image 2024-09-25 at 4 12 11 PM](https://github.com/user-attachments/assets/f32840fe-b1b9-4c38-9d6b-9a499fb80898)

### 📷 Recurrence Steps

i thing there is an issue in the image file so build that igain with the connectivity and all other testings and then push it

### 🚦 Expected Behavior

the Postgresql database should list the database or if empty should show that 
but it just keep sending get request and get the response of permission denied 
even in the docke container of the application the database is accessible properly

**Comment by arvinxx** [comment]
I think it's not the lobe-chat-database image's issue. It's impossible to list image in the LobeChat frontend. You should check the connection at the container level.

Please check your docker image log, I think it's an issue with your db like missing the pgvector plugin
