### ISSUE TITLE
[Bug] word和ppt可以但是excel就是分块失败是为什么呀

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#4142]
### 📦 部署环境

Docker

### 📌 软件版本

7.9

### 💻 系统环境

Other

### 🌐 浏览器

Chrome

### 🐛 问题描述

[
![75bf680617aaac3f6f1a428eaaa648f](https://github.com/user-attachments/assets/fba73a66-fe40-4577-ba9c-0125ee9f9339)
](url)

**Comment by SpeedupMaster** [comment]
还不支持

**Comment by zhangleijun111** [comment]
> 还不支持

哦哦是不行对法我想呢，后续会可以嘛
