### ISSUE TITLE
[Request] 单独记住每个对话使用的模型

### ISSUE THREAD

**Issue by lknife** [lobehub/lobe-chat#415]
### 🥰 需求描述 | Feature Description

当前版本：Docker 0.96.8
有些对话可能需要不同的模型，目前对话框那里设置的好像是全局模型，忘记切换就需要再问一遍，比较麻烦。
助手有默认的模型，会自动切换，但是也不能单独更改某一个保存的对话。
比如根据需求，普通问题就问GPT3.5，要求高的（论文润色之类的）得问GPT4，也有可能同一个助手会希望切换模型有个对比。

### 🧐 解决方案 | Proposed Solution

单独记住每个对话使用的模型。

**Comment by arvinxx** [comment]
这个需求并不合理，不同对话建议通过不同 agent 来完成。我们不会去做 topic 粒度的模型切换。
