### ISSUE TITLE
[Bug] ❌ Database migrate failed: TypeError: Cannot read properties of undefined (reading 'migrate')

### ISSUE THREAD

**Issue by e1100x** [lobehub/lobe-chat#4152]
### 📦 Environment

Vercel

### 📌 Version

lobechat 1.19.34，Github Codespaces

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

使用codespace直接运行。
bun install ---- ok
bun build ---- ok

但在codespace中修改为server版，使用vercel的Postgres（全新初始化）。仅做如下配置（尝试了serverless和node），始终报错，一直无法build成功，提示❌ Database migrate failed

```
# Specify the service mode as server if you want to use the server database
NEXT_PUBLIC_SERVICE_MODE=server

# Postgres database URL
DATABASE_URL=postgres://default:BChG1Yzu9oTx@ep-restless-cell-a49pem4x.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require
# DATABASE_DRIVER=node

# use `openssl rand -base64 32` to generate a key for the encryption of the database
# we use this key to encrypt the user api key
KEY_VAULTS_SECRET=jgwsK28dspyVQoIf8/M3IIHl1h6LYYceSYNXeLpy6uk=

APP_URL=https://www.google.com
```
<img width="763" alt="截屏2024-09-26 下午2 29 08" src="https://github.com/user-attachments/assets/0c7ca594-97c6-4a15-aa3e-3acfecfb49c5">

### 📷 Recurrence Steps

1. 点击主页的
![image](https://github.com/user-attachments/assets/96f214dc-e4ad-4d36-af31-31dda488fdc6)
2. bun install
3. 修改.env

```
# Specify the service mode as server if you want to use the server database
NEXT_PUBLIC_SERVICE_MODE=server

# Postgres database URL
DATABASE_URL=postgres://default:BChG1Yzu9oTx@ep-restless-cell-a49pem4x.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require
# DATABASE_DRIVER=node

# use `openssl rand -base64 32` to generate a key for the encryption of the database
# we use this key to encrypt the user api key
KEY_VAULTS_SECRET=jgwsK28dspyVQoIf8/M3IIHl1h6LYYceSYNXeLpy6uk=

APP_URL=https://www.google.com
```
4. bun build 
5. 报错：❌ Database migrate failed

### 📝 Additional Information

本地使用database版本docker已经部署成功，
但这个版本始终不能编译成功

**Comment by e1100x** [comment]
似乎不没有解决，而且不只是CodeSpaces上有这个问题，本地也遇到同样的问题，只是CodeSpaces上方便复现

**Comment by sxjeru** [comment]
Vercel 之外的环境应当使用 Docker 部署服务端数据库版本。
参考 #3237

**Comment by e1100x** [comment]
Docker版本已经部署成功，只是做二次开发的本地版本一直无法编译。试了一下Github 的Codespace环境也是一样的问题。所有用的Postgres都是Vercel的，描述中放的Vercel Postgres链接也是可用的，是我创建的全新的
```
DATABASE_URL=postgres://default:BChG1Yzu9oTx@ep-restless-cell-a49pem4x.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require
```

**Comment by sxjeru** [comment]
这应该与数据库无关，不论是 vercel 的还是自建的，不过是 DATABASE_DRIVER 的区别。

**Comment by e1100x** [comment]
主要是这个问题很容易复现，有什么修改的建议我可以尝试的吗？还是更推荐用docker版本

现在二次开发上确实有些瓶颈，望各位大神能给点建议

**Comment by cy948** [comment]
平常别在dev环境里面做生产构建不就行了，要测生产的构建直接docker。

**Comment by e1100x** [comment]
现在遇到的困难就是无论在哪个环境都build不了，都会复现 ❌ Database migrate failed，只能使用官方build好的docker。

.env是按照LobeChat的官方文档配置的（https://lobehub.com/zh/docs/self-hosting/server-database/vercel），不知道问题出在哪里，是不是被我漏了什么

**Comment by ycz87** [comment]
我是在vercel上部署的，一开始用的vercel上neon的Postgres，但使用体验相当不好，因为每次发送内容都要等待一段时间写入数据库，非常卡，所以想把NEXT_PUBLIC_SERVICE_MODE的server切换为client，编译后也得到同样的错误。

**Comment by hyrhyrh** [comment]
遇到同样的问题，请问下后面解决了吗

**Comment by KazeroG** [comment]
with #4900 should be resolved

to be test and deployed on your environnement

on my side build passed

![image](https://github.com/user-attachments/assets/1d91cf1d-fe51-466f-abd5-28be124aedaa)
