### ISSUE TITLE
[Request] 目前智谱模型不支持中断输出，希望支持

### ISSUE THREAD

**Issue by BiFangKNT** [lobehub/lobe-chat#4155]
### 🥰 需求描述

如题

### 🧐 解决方案

智谱的api应该是支持中断的，希望调整一下调用方式。另外之前提到的tag更新希望也一起做了 #3909

**Comment by arvinxx** [comment]
默认就应该支持中断的，不太理解这个需求

**Comment by BiFangKNT** [comment]
> 默认就应该支持中断的，不太理解这个需求

我提出这个议题时是不支持的，最近的版本支持了（我目前是1.29.2，还没更新）
