### ISSUE TITLE
[Bug] Ollama API Key

### ISSUE THREAD

**Issue by lyz0994** [lobehub/lobe-chat#4159]
### 📦 Environment

Docker

### 📌 Version

v1.19.34

### 💻 Operating System

Windows

### 🌐 Browser

Edge

### 🐛 Bug Description

正确添加ollama方式后显示使用自定义的Ollama API Key，但是我没有设置任何key,而且ollama好像并没有key，我该如何解决
![屏幕截图 2024-09-26 212923](https://github.com/user-attachments/assets/f6d63c3f-484c-4f2b-a3c0-c944950e710d)

**Comment by lyz0994** [comment]
![Uploading 屏幕截图 2024-09-26 212923.png…]()

**Comment by lyz0994** [comment]
好的，谢谢您，我这边解决了，我没有相应的models。。已经添加完了，感谢！！

**Comment by lyuscott** [comment]
我出现同样的错误，我没做任何的更改， 上一刻正常使用，下一刻就要求输入api key了，有没大神看看什么原因
