### ISSUE TITLE
[Bug] 首页每次自动跳转到欢迎页

### ISSUE THREAD

**Issue by leeyiding** [lobehub/lobe-chat#416]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

现在在新设备上，每次从首页进入都会自动跳转到欢迎页，我记得原来只会进入一次欢迎页，之后再进入都会跳转聊天页面呀。

**Comment by arvinxx** [comment]
你的会话中没有消息吗？

**Comment by leeyiding** [comment]
闲聊里面有消息，好像得新建个助手才行

**Comment by arvinxx** [comment]
> 闲聊里面有消息，好像得新建个助手才行

应该是判断逻辑有bug，我处理下。判断是否为空应该加上闲聊里的
