### ISSUE TITLE
[Request] 请求Hunyuan大模型支持Hunyuan_MODEL_LIST

### ISSUE THREAD

**Issue by SAnBlog** [lobehub/lobe-chat#4166]
### 🥰 需求描述

请求Hunyuan大模型支持Hunyuan_MODEL_LIST

### 🧐 解决方案

模型挺多的,默认选择性价比高的列出

**Comment by SpeedupMaster** [comment]
已经支持了吧 #4147

**Comment by SAnBlog** [comment]
> 已经支持了吧 #4147

不好意思我看岔了,关闭了

**Comment by arvinxx** [comment]
欢迎将其补充到文档中：https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
