### ISSUE TITLE
[Bug] OpenRouter下配置gpt-4o模型没有自动适配模型参数

### ISSUE THREAD

**Issue by jorben** [lobehub/lobe-chat#4170]
### 📦 部署环境

Docker

### 📌 软件版本

v1.20.0

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

<img width="512" alt="image" src="https://github.com/user-attachments/assets/243cdb55-cea5-405f-bea3-b611a6c150b3">

```
# .env 中配置如下
OPENROUTER_MODEL_LIST=-all,+openai/o1-mini,+openai/o1-preview,+openai/gpt-4o-mini,+openai/gpt-4o
```

其他模型能够自动适配模型信息（模型名称、上下文长度等信息）

### 🚦 期望结果

openai/gpt-4o 展示为 GPT-4o ，并且关联模型上下文长度、视觉、函数调用等能力

**Comment by SpeedupMaster** [comment]
`openai/gpt-4o-2024-08-06`
用这个
