### ISSUE TITLE
[Bug] local deplyment storage issue

### ISSUE THREAD

**Issue by BILAL324** [lobehub/lobe-chat#4174]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

For even local deplyment , why there is only one option to configure the storage which is S3 and there is no proper documentation to configure, we face many issue 
also if there is local stoarage option please give them here and also in the documentation

**Comment by BILAL324** [comment]
and what will be the structure of .env file for configuration of this

**Comment by SpeedupMaster** [comment]
Cloudflare R2 Storage [ref](https://lobehub.com/docs/self-hosting/advanced/s3/cloudflare-r2)

Deploy with minio [ref](https://lobehub.com/docs/self-hosting/server-database/docker-compose#configure-min-io-s-3)

**Comment by arvinxx** [comment]
I think you don't read the document correctly. try to ready it carefully: https://lobehub.com/docs/self-hosting/server-database

**Comment by BILAL324** [comment]
![Screenshot from 2024-09-25 14-53-22](https://github.com/user-attachments/assets/1980768b-c312-4df6-bbe0-cfd9837b55f1)
cross origin request block even the request is 200 ok

even that link is accessible
