### ISSUE TITLE
[Request] 建议支持S3第三方服务的文件预览

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#4178]
### 🥰 需求描述

S3的第三方服务，例如腾讯云的COS，如果开启了万象模式，它是能够在网站上预览N多格式的文件的，不需要单独去开发预览的玩意。希望lobe能够考虑这个进去。

### 🧐 解决方案

对象存储-文档处理-开启
也有html预览方式，文档：https://cloud.tencent.com/document/product/436/54059

**Comment by arvinxx** [comment]
这不是 S3 的标准服务吧。不考虑
