### ISSUE TITLE
[Question] 怎么能代码内直接默认带一些自定义模型，而不是用户手动在web页面里面每个电脑添加一次。

### ISSUE THREAD

**Issue by itq5** [lobehub/lobe-chat#418]
### 🧐 问题描述 | Proposed Solution

[Question] 怎么能代码内直接默认带一些自定义模型，而不是用户手动在web页面里面每个电脑添加一次。
![image](https://github.com/lobehub/lobe-chat/assets/42521985/79c3c543-0d76-44ce-a76f-192452fcebc3)

**Comment by arvinxx** [comment]
会提供一个环境变量来添加默认值，相关 issue: https://github.com/lobehub/lobe-chat/issues/335#issuecomment-1765872342

**Comment by itq5** [comment]
我如何手动修改默认的gpt-4-1106-preview到其他模型呢，需要改哪个位置，谢谢！

**Comment by arvinxx** [comment]
@itq5 如果是已经添加了的，要手动改下 模型设置 -> 模型。如果是未添加的，可以到设置 -> 默认助手 -> 模型设置里修改默认模型
