### ISSUE TITLE
[Request] Add support for other text-embedding model providers

### ISSUE THREAD

**Issue by spuniun** [lobehub/lobe-chat#4180]
### 🥰 Feature Description

Because chunking of file uploads depends on text-embedding to be functional, the entire knowledge base feature does not work without API keys from OpenAI itself. Since other providers such as Github and Azure provide these models as well, it would be nice to support alternate API endpoints for this feature.

### 🧐 Proposed Solution

Add environment variables that allow for the customization of file chucking providers

### 📝 Additional Information

https://github.com/marketplace/models/azure-openai/text-embedding-3-large
https://github.com/marketplace/models/azure-openai/text-embedding-3-small
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#embeddings-models

This request is a dupe of #4128 but that request was closed after being marked as a duplicate of itself.

**Comment by arvinxx** [comment]
duplicate with https://github.com/lobehub/lobe-chat/issues/3785
