### ISSUE TITLE
[Docs] Feedback for `self-hosting/server-database`, NEXT_PUBLIC_SERVICE_MODE

### ISSUE THREAD

**Issue by Xeelix** [lobehub/lobe-chat#4183]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/server-database.mdx

### 🐛 Feedback

Hi! 

when I had a NEXT_PUBLIC_SERVICE_MODE=client, I could upload photos and process them using vision model without saving them in any storage. but after switching to the server, the application requires you to upload this file to the server. But I don't have the ability to connect S3 just for the sake of it, I don't need it. 

is there a way to disable "Manage files and knowledge base" and just temporarily upload photos when communicating with vision model when NEXT_PUBLIC_SERVICE_MODE=server is enabled?

**Comment by Xeelix** [comment]
> Hello, @Xeelix! I'm here to help you with any bugs, questions, or contributions you have. Let's see if we can solve this together.
> 
> Yes, there is a way to disable "Manage files and knowledge base" and just temporarily upload photos when communicating with the vision model when `NEXT_PUBLIC_SERVICE_MODE=server` is enabled.
> 
> In the provided code, the `canUploadImage` variable determines whether the image upload functionality is enabled based on the current model. You can control the upload options by modifying the `items` array in the `FileUpload` component.
> 
> To disable the "Manage files and knowledge base" and only allow temporary photo uploads, you can adjust the `items` array to only include the image upload option and ensure that other upload options are disabled or removed.
> 
> Here is the modified code:
> 
> ```tsx
> const items: MenuProps['items'] = [
>   {
>     disabled: !canUploadImage,
>     icon: <Icon icon={ImageUp} style={{ fontSize: '16px' }} />,
>     key: 'upload-image',
>     label: canUploadImage ? (
>       <Upload
>         accept={'image/*'}
>         beforeUpload={async (file) => {
>           await upload([file]);
> 
>           return false;
>         }}
>         multiple
>         showUploadList={false}
>       >
>         <div className={cx(hotArea)}>{t('upload.action.imageUpload')}</div>
>       </Upload>
>     ) : (
>       <Tooltip placement={'right'} title={t('upload.action.imageDisabled')}>
>         <div className={cx(hotArea)}>{t('upload.action.imageUpload')}</div>
>       </Tooltip>
>     ),
>   },
> ];
> ```
> 
> Additionally, to ensure that the "Manage files and knowledge base" feature is disabled when in server mode, you can modify the `Upload` component to check the `enableKnowledgeBase` flag from the server configuration and render the appropriate mode:
> 
> ```tsx
> import { isServerMode } from '@/const/version';
> import { featureFlagsSelectors, useServerConfigStore } from '@/store/serverConfig';
> 
> import ClientMode from './ClientMode';
> import ServerMode from './ServerMode';
> 
> const Upload = () => {
>   const { enableKnowledgeBase } = useServerConfigStore(featureFlagsSelectors);
>   return isServerMode && enableKnowledgeBase ? <ServerMode /> : <ClientMode />;
> };
> 
> export default Upload;
> ```
> 
> This modification ensures that the knowledge base management is disabled when `NEXT_PUBLIC_SERVICE_MODE=server` is enabled, and only the image upload option is available [[1]](https://github.com/lobehub/lobe-chat/blob/main/src/features/ChatInput/ActionBar/Upload/ServerMode.tsx)[[2]](https://github.com/lobehub/lobe-chat/blob/main/src/app/(main)/repos/layout.tsx)[[3]](https://github.com/lobehub/lobe-chat/blob/main/src/features/ChatInput/ActionBar/Upload/index.tsx).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

@dosu No, after making these changes, s3 storage is still required.

**Comment by SpeedupMaster** [comment]
use the FEATURE_FLAGS
`FEATURE_FLAGS=-knowledge_base`

**Comment by Xeelix** [comment]
> use the FEATURE_FLAGS `FEATURE_FLAGS=-knowledge_base`

yeah, after that, the knowledge tab stopped being displayed. But when trying to upload an image in chat, it still requires S3 to be configured. is there any way to fix this and disable s3 support?
<img width="401" alt="Снимок экрана 2024-09-28 в 14 50 20" src="https://github.com/user-attachments/assets/b2b3b1f3-1246-4998-9fd8-f9c471db1678">

**Comment by SpeedupMaster** [comment]
> > use the FEATURE_FLAGS `FEATURE_FLAGS=-knowledge_base`
> 
> yeah, after that, the knowledge tab stopped being displayed. But when trying to upload an image in chat, it still requires S3 to be configured. is there any way to fix this and disable s3 support? <img alt="Снимок экрана 2024-09-28 в 14 50 20" width="401" src="https://private-user-images.githubusercontent.com/32061277/371757238-b2b3b1f3-1246-4998-9fd8-f9c471db1678.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MjczNDAsIm5iZiI6MTcyNzUyNzA0MCwicGF0aCI6Ii8zMjA2MTI3Ny8zNzE3NTcyMzgtYjJiM2IxZjMtMTI0Ni00OTk4LTlmZDgtZjljNDcxZGIxNjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDEyMzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYjhmYmVjY2RkYzhjYTU1NjNhZjdlZDU5OTNiMzJmMGFjYWJiMjJmOTNkZmNkYzQ4YWQ4YjNlNGI4ZjVkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a841cPQKFh0R5Vh8darMCUuvEH0qrAsVSTW2KwlwnFI">

Maybe you can use cloudflare R2, it has 10GB free storage. [ref](https://lobehub.com/docs/self-hosting/advanced/s3/cloudflare-r2)

**Comment by arvinxx** [comment]
We won't support this request. It's not reasonable. If you don't save file to S3 , you have nowhere to storage the image.
