### ISSUE TITLE
[Bug] 使用 Claude 3.5 模型调用网站爬虫插件时，没有响应？

### ISSUE THREAD

**Issue by 80imike** [lobehub/lobe-chat#4185]
### 📦 部署环境

Docker

### 📌 软件版本

1.20.2

### 💻 系统环境

Android

### 🌐 浏览器

Other

### 🐛 问题描述

使用 Claude 3.5 模型调用网站爬虫插件时，插件没有任何响应，但使用  gpt 4o 模型时，能正常工作。

网站爬虫插件是不支持 Claude 3.5 模型吗？

**Comment by SpeedupMaster** [comment]
![图片](https://github.com/user-attachments/assets/f0e0030a-e793-433e-a337-c918db33b3d1)
是不是你的API Key不支持函数调用

**Comment by 80imike** [comment]
> ![图片](https://private-user-images.githubusercontent.com/130642629/371723373-f0e0030a-e793-433e-a337-c918db33b3d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MDY4NjEsIm5iZiI6MTcyNzUwNjU2MSwicGF0aCI6Ii8xMzA2NDI2MjkvMzcxNzIzMzczLWYwZTAwMzBhLWU3OTMtNDMzZS1hMzM3LWM5MThkYjMzYjNkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQwNjU2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTBmMDJiMjM0NDAwNzZhNjdmNzBiYWZkYzMxNjg5ZGU1ZTBlNTJlNjg4YjQ3ZDI1YmVjYjAzNDI2NDE4NDhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9wbD3VNvj60eQUSC8Z9bfkZFkEhtKRUG851tHQNi3w4) 是不是你的API Key不支持函数调用

![Screenshot_2024-09-28-14-58-16-462_mark via](https://github.com/user-attachments/assets/be7431ad-e307-45fc-be10-e238fdab70f5)


按你的方法测试了，我的返回是这样的，这是因为  api key 不支持吗？  @SpeedupMaster

**Comment by SpeedupMaster** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/130642629/371723373-f0e0030a-e793-433e-a337-c918db33b3d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MDY4NjEsIm5iZiI6MTcyNzUwNjU2MSwicGF0aCI6Ii8xMzA2NDI2MjkvMzcxNzIzMzczLWYwZTAwMzBhLWU3OTMtNDMzZS1hMzM3LWM5MThkYjMzYjNkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQwNjU2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTBmMDJiMjM0NDAwNzZhNjdmNzBiYWZkYzMxNjg5ZGU1ZTBlNTJlNjg4YjQ3ZDI1YmVjYjAzNDI2NDE4NDhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9wbD3VNvj60eQUSC8Z9bfkZFkEhtKRUG851tHQNi3w4) 是不是你的API Key不支持函数调用
> 
> ![Screenshot_2024-09-28-14-58-16-462_mark via](https://private-user-images.githubusercontent.com/1665201/371738058-be7431ad-e307-45fc-be10-e238fdab70f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1Mjc1MDMsIm5iZiI6MTcyNzUyNzIwMywicGF0aCI6Ii8xNjY1MjAxLzM3MTczODA1OC1iZTc0MzFhZC1lMzA3LTQ1ZmMtYmUxMC1lMjM4ZmRhYjcwZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMTI0MDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWZiYzM4N2JmMDI1NTk1ZWQ0NDE0MzVhOTQ1ODVlMmZjYmIzZjNhOTgyY2I3NDA2MmRiMDRhNWZlNzNkZTMxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.x0WTqlqoN7sYPOvzuQZ_ixlnzzaDkXTuB1od19n7nyY)
> 
> ![Screenshot_2024-09-28-15-02-35-765_mark via](https://private-user-images.githubusercontent.com/1665201/371738284-82bce088-9edf-47d9-abf3-1a84be78cb14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1Mjc1MDMsIm5iZiI6MTcyNzUyNzIwMywicGF0aCI6Ii8xNjY1MjAxLzM3MTczODI4NC04MmJjZTA4OC05ZWRmLTQ3ZDktYWJmMy0xYTg0YmU3OGNiMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMTI0MDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTlmNTY1MjM4NDNmM2ZlNzIwNWFhNzYzZTdmNzRkNzE0MTQyNTNhM2NkMWE4ZTE1NjE3NTFlOTI2OTc0ZTA2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4udCl5Xd0j1jsdCLNQGzEmwIauJtHOXgxpDWYrW2M1U)
> 
> 按你的方法测试了，我的返回是这样的，这是因为 api key 不支持吗？ @SpeedupMaster

其他的插件可以正常调用吗

**Comment by arvinxx** [comment]
@80imike 很显然是你的 api 不支持。大概率是哪里逆向来的
