### ISSUE TITLE
[Bug] 使用4turbo模型的时候，发送图片回复异常

### ISSUE THREAD

**Issue by gaojunyang666** [lobehub/lobe-chat#4189]
### 📦 部署环境

Docker

### 📌 软件版本

v1.20.2

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

![image](https://github.com/user-attachments/assets/77275b11-e81e-412d-8713-a08582319d9a)
会发生回复中断，百分百出现问题，而使用其它客户端就不会

**Comment by sxjeru** [comment]
请尝试 重新生成，目前已知问题是带图片首次聊天，发送的请求中可能没有带上图片。

**Comment by arvinxx** [comment]
应该已经修复
