### ISSUE TITLE
[Bug] o1模型部分时候无法正常回复

### ISSUE THREAD

**Issue by huoxianribao** [lobehub/lobe-chat#4190]
### 📦 部署环境

Official Preview

### 📌 软件版本

v1.20.2

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

直接使用的在 https://chat-preview.lobehub.com
经查api站，正常吐token，但是lobehub无法正常接收仍然提示504错误，您提示的方法还是希望有一个完整教程
o1mini的部分问题可以正常回答，正常版的o1模型应该都不能回答。
我正在使用o1模型，更改了token数限制
![image](https://github.com/user-attachments/assets/816ba5a0-4681-4060-bd73-327b70823555)
![image](https://github.com/user-attachments/assets/e338027f-782a-4dae-aa57-b8817f5a56a4)
![image](https://github.com/user-attachments/assets/80edc58b-7b79-4f86-8564-366651beb784)
[已经汇报过的bug，但是没有一个完整说明](https://github.com/lobehub/lobe-chat/issues/4046#issuecomment-2363903821)

### 📷 复现步骤

设置的最大token数，使用o1mini模型
![image](https://github.com/user-attachments/assets/816ba5a0-4681-4060-bd73-327b70823555)

### 🚦 期望结果

正常返回结果

**Comment by arvinxx** [comment]
504 是服务器响应超时导致的，Vercel Edge Runtime 对首字节有25s内响应的要求，应用层解决不了。

临时解法是切到客户端请求模式，或者你自己用 Docker 部署。

![image](https://github.com/user-attachments/assets/942b59b3-bf0e-403d-9c0a-2098ed0bc052)
