### ISSUE TITLE
[Bug] edge 浏览器将页面安装为应用后， 多桌面 只能启动一个应用

### ISSUE THREAD

**Issue by mooerccx** [lobehub/lobe-chat#4191]
### 📦 部署环境

Official Preview

### 📌 软件版本

v1.20

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

edge 浏览器将页面安装为应用后， 多桌面 只能启动一个应用， 在桌面1开启一个对话后，桌面2中只要点击任务栏图标就会直接跳转到桌面1，必须将桌面1中的关闭，才能在桌面2中使用

### 📷 复现步骤

edge 浏览器将页面安装为应用，在桌面1开启一个对话， 然后在其他桌面任务栏点击图标，会直接跳转到桌面1

### 🚦 期望结果

希望在任意的桌面中都能打开独立的应用，就像chatgpt页面一样

**Comment by arvinxx** [comment]
pwa 可能并不支持这个特性，有个思路是你用 Edge 装一个应用，然后再用 Chrome 装第二个。还要第三个的话再找一个浏览器装PWA 。
