### ISSUE TITLE
[Request] 希望增加全文上传和更强的rag性能

### ISSUE THREAD

**Issue by Zoumachuan** [lobehub/lobe-chat#4201]
### 🥰 需求描述

一、全文上传的功能大概会在哪个版本实现更新呢？非常期待这个功能，可以说有了这个功能我可以将lobe作为我唯一的人工智能平台。

二、知识库语言预处理的提示词是否可以手动修改，或者是否有办法修改生成预处理提示词的提示词？如图：

第二个问题基于目前用lobe进行学术辅助时面临的问题：倘若知识库里的文件中/英文文献均存在，则用中文提问会较大概率调用中文文献里的内容从而忽视英文文献。
![image](https://github.com/user-attachments/assets/d5668f8b-e48c-4fb1-b5ba-23fb61f4f809)

### 🧐 解决方案

问题一已有相同的issue #4005
问题二参考类似的fastgpt，可以通过适当调整预处理提示词的提示词来进行改进
![image](https://github.com/user-attachments/assets/a3f5b9d0-8f5b-4ab7-80b2-a7ee54eb24b5)

**Comment by cy948** [comment]
可以在 rfc #4204 上表达更多你对rag性能增强的想法😋
