### ISSUE TITLE
[Request] 向量模型是否可以支持使用智谱的？

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#4207]
### 🥰 需求描述

向量模型是否可以支持使用智谱的？

### 🧐 解决方案

向量模型是否可以支持使用智谱的？

### 📝 补充信息

向量模型是否可以支持使用智谱的？

**Comment by BiFangKNT** [comment]
你这个问题我在讨论里提过了🤣 #4062

**Comment by zhangleijun111** [comment]
> 你这个问题我在讨论里提过了 🤣 #4062

我看下方貌似都没有回复嘛

**Comment by Zoumachuan** [comment]
我看最近有pr把另几个embedding模型调用进来了，如果合并之后可能就支持了？

**Comment by cookieY** [comment]
pr #4208

**Comment by BiFangKNT** [comment]
> pr #4208

这是好的！

**Comment by cookieY** [comment]
可以先用我改好的版本过渡下  [lobe-chat](https://github.com/cookieY/lobe-chat)

**Comment by BiFangKNT** [comment]
> 可以先用我改好的版本过渡下 [lobe-chat](https://github.com/cookieY/lobe-chat)

刚刚看到你上面的pr关闭了，是因为暂时无法合并吗？有暂时无法解决的冲突吗？

**Comment by arvinxx** [comment]
重复： https://github.com/lobehub/lobe-chat/issues/3785
