### ISSUE TITLE
[Bug] 1.20.5版本，在zeabur中github fork构建后无法启动

### ISSUE THREAD

**Issue by LovelyGuYiMeng** [lobehub/lobe-chat#4209]
### 📦 部署环境

Zeabur

### 📌 软件版本

1.20.5

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

1.20.5版本，在zeabur中github fork构建后无法启动
![image](https://github.com/user-attachments/assets/23ca8b8e-c738-4646-9b23-9e174dd728bd)

而docker部署可以正常启动
![image](https://github.com/user-attachments/assets/1adb8bda-efbd-4887-97c9-261b46561853)

@hezhijie0327 

### 📷 复现步骤

直接在zeabur通过github部署lobechat 1.20.5，构建成功后启动阶段无法启动

### 🚦 期望结果

构建成功后正常启动

**Comment by arvinxx** [comment]
@hezhijie0327 来看下这个

**Comment by hezhijie0327** [comment]
`/app/docker.cjs` 不存在？我研究下 zeabur 咋用

@LovelyGuYiMeng 它这是直接构建镜像在运行的吗？

**Comment by hezhijie0327** [comment]
@LovelyGuYiMeng 这个 DB 版是在哪里的？咱们 REPO 里的貌似不是数据库版本
![image](https://github.com/user-attachments/assets/c92885ee-c265-46f7-842c-26ed15e5ce72)

**Comment by LovelyGuYiMeng** [comment]
> @LovelyGuYiMeng 这个 DB 版是在哪里的？咱们 REPO 里的貌似不是数据库版本 ![image](https://private-user-images.githubusercontent.com/58100052/371837569-c92885ee-c265-46f7-842c-26ed15e5ce72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTgwOTIsIm5iZiI6MTcyNzU5Nzc5MiwicGF0aCI6Ii81ODEwMDA1Mi8zNzE4Mzc1NjktYzkyODg1ZWUtYzI2NS00NmY3LTg0MmMtMjZlZDE1ZTVjZTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA4MTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkM2Y2ZjNhNjhjOWIyMDc1MzA4YTI0NWZiMTI5ZDhmYWRkNmJmNTQ1MjJkNzZhYzQ0MDQ0ZDQ3MzQwZTdhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lZNX_OLueU_CCi9rMqGp9fn13WKcAmWrIUCpvtTtYqo)

不要用模板里的，模板里的是Docker镜像
用GitHubFork部署的，DB版在环境变量里加上NEXT_PUBLIC_SERVICE_MODE=server

**Comment by hezhijie0327** [comment]
@arvinxx @LovelyGuYiMeng 我看了下有个 Template https://zeabur.com/templates/RRSPSD 运行正常的

![image](https://github.com/user-attachments/assets/c487fcd9-d8d2-4055-92cf-0febf868ba3d)

@LovelyGuYiMeng 你这个方式我过会儿看看咋弄

**Comment by hezhijie0327** [comment]
@LovelyGuYiMeng 我大致知道为啥了，但是之前版本真的能用吗？

有办法调整默认 Dockerfile 的方法不？按照之前版本的话，也是凑巧能用，因为 DB 没做迁移
![image](https://github.com/user-attachments/assets/67d5318b-1ceb-424b-9835-3529382334b1)

`NEXT_PUBLIC_SERVICE_MODE="server"` 触发了启动器的判断

https://github.com/lobehub/lobe-chat/blob/86736dbb099a85a5e2aacb692932ab63467e1010/scripts/serverLauncher/startServer.js#L169-L177

**Comment by arvinxx** [comment]
@hezhijie0327 好像之前版本就是没有做迁移， @LovelyGuYiMeng 每次都是手动自己做db migration的…

**Comment by hezhijie0327** [comment]
@arvinxx 那这样的话 我搞个环境变量 让它跳过迁移就行，现在是强制，当初设计的时候没想到还有这需求...

TODO: 在变量设置后，输出 warning

**Comment by hezhijie0327** [comment]
@LovelyGuYiMeng  #4213 试下这个分支，设置 `SKIP_DB_MIGRATION="true"`

**Comment by hezhijie0327** [comment]
换了一个思路，可以不用设置 ENV ~
