### ISSUE TITLE
[Bug] 按wiki使用Vercel 自动部署 LobeChat报错 

### ISSUE THREAD

**Issue by qinghuannn** [lobehub/lobe-chat#4214]
### 📦 Environment

Vercel

### 📌 Version

latest

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

使用vercel部署，提示：Cloning An unexpected error occurred. Our team has already been notified and are working to resolve the issue, please try again shortly.
重复多次也是这样

### 📷 Recurrence Steps

1

### 🚦 Expected Behavior

![image](https://github.com/user-attachments/assets/30e24814-4c21-4c51-aae9-943815f8c4f3)

### 📝 Additional Information

1

**Comment by sxjeru** [comment]
可以试试在 github 这边手动 fork，然后导入仓库到 vercel 。

**Comment by arvinxx** [comment]
文档中试了下，是正常的
