### ISSUE TITLE
[Bug] https+ip最新版v1.20.8依然禁止访问

### ISSUE THREAD

**Issue by chung1912** [lobehub/lobe-chat#4220]
### 📦 部署环境

Docker

### 📌 软件版本

v1.20.8(Database版)

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

https+ip最新版v1.20.8依然禁止访问（注：v1.20.4是正常的）
以下是启动后的后台日志：
![image](https://github.com/user-attachments/assets/6e966439-52ae-402e-a3a0-4f21c903d0ba)
以下是nginx的错误日志
` [error] 183#183: *1494 connect() failed (111: Connection refused) while connecting to upstream, client: 172.99.0.2, server: lobechat, request: "GET /sw.js HTTP/2.0", upstream: "http://172.99.0.99:3210/sw.js", host: "192.168.1.118:3210", referrer: "https://192.168.1.118:3210/sw.js"`
以下是浏览器前端的console打印日志：
![image](https://github.com/user-attachments/assets/bd69cb78-a48d-422d-9cdd-1cc37049a3bc)

### 🚦 期望结果

希望能够正常访问

### 📝 补充信息
另外，我发现这个日志里面多了一个 DNS server的信息127.0.0.11，在之前的版本里面并没有这个，不知道跟这个是否有关系
_No response_

**Comment by arvinxx** [comment]
@hezhijie0327 还是有问题

**Comment by hezhijie0327** [comment]
@chung1912 末尾有其他输出吗？截图不完整
![image](https://github.com/user-attachments/assets/c0682333-0c1e-4bbb-9c85-8c1c55f61fb4)

**Comment by chung1912** [comment]
> @chung1912 末尾有其他输出吗？截图不完整 ![image](https://private-user-images.githubusercontent.com/58100052/371962610-c0682333-0c1e-4bbb-9c85-8c1c55f61fb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NzY1NzIsIm5iZiI6MTcyNzY3NjI3MiwicGF0aCI6Ii81ODEwMDA1Mi8zNzE5NjI2MTAtYzA2ODIzMzMtMGMxZS00YmJiLTljODUtOGMxYzU1ZjYxZmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA2MDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMDA4YjE4NzM5YjUxOWQ5MmNjZTlhZTkzYTljMWQwNTEwOGUxODdiMjRhYTEyYmFlYWVjZjUxZDg3ZmQ3Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ujhq11u4G29urQVxkiOEUwha1Jo978K3sfWshIcmZ0w)

没有，到那里就结束了，后面没东西了

**Comment by chung1912** [comment]
> > @chung1912 末尾有其他输出吗？截图不完整 ![image](https://private-user-images.githubusercontent.com/58100052/371962610-c0682333-0c1e-4bbb-9c85-8c1c55f61fb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NzY1NzIsIm5iZiI6MTcyNzY3NjI3MiwicGF0aCI6Ii81ODEwMDA1Mi8zNzE5NjI2MTAtYzA2ODIzMzMtMGMxZS00YmJiLTljODUtOGMxYzU1ZjYxZmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA2MDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMDA4YjE4NzM5YjUxOWQ5MmNjZTlhZTkzYTljMWQwNTEwOGUxODdiMjRhYTEyYmFlYWVjZjUxZDg3ZmQ3Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ujhq11u4G29urQVxkiOEUwha1Jo978K3sfWshIcmZ0w)
> 
> 没有，到那里就结束了，后面没东西了，我用v1.20.4就像你那样的日志

**Comment by hezhijie0327** [comment]
做个简单的测试
```
docker exec -it lobechat /bin/node
```
进入 node 后复制以下代码，将 `https://www.baidu.com` 改为你的 OSS 或者 OAUTH 的 URL
```
const tls = require('tls');

const parseUrl = (url) => {
  const { protocol, hostname: host, port } = new URL(url);
  return { protocol: protocol.replace(':', ''), host, port: port || 443 };
};

const isValidTLS = (url = '') => {
  if (!url) {
    console.log('⚠️ TLS Check: No URL provided. Skipping TLS check. Ensure correct setting ENV.');
    console.log('-------------------------------------');
    return Promise.resolve();
  }

  const { protocol, host, port } = parseUrl(url);
  if (protocol !== 'https') {
    console.log(`⚠️ TLS Check: Non-HTTPS protocol (${protocol}). Skipping TLS check for ${url}.`);
    console.log('-------------------------------------');
    return Promise.resolve();
  }

  const options = { host, port, servername: host };
  return new Promise((resolve, reject) => {
    const socket = tls.connect(options, () => {
      console.log(socket)
      socket.end();

      resolve();
    });

    socket.on('error', (err) => {
      reject(err);
    });
  });
};

isValidTLS("https://www.baidu.com")
```

看看结果

**Comment by hezhijie0327** [comment]
还有种可能性是 `NODE_EXTRA_CA_CERTS`

新镜像为了使用系统的 CA，默认设置为 `/etc/ssl/certs/ca-certificates.crt`，你是挂载了单个 CA 还是整个系统 CA？

**Comment by chung1912** [comment]
> 还有种可能性是 `NODE_EXTRA_CA_CERTS`
> 
> 新镜像为了使用系统的 CA，默认设置为 `/etc/ssl/certs/ca-certificates.crt`，你是挂载了单个 CA 还是整个系统 CA？

`NODE_EXTRA_CA_CERTS`是挂载单个CA，把自签名CA加入到系统CA很麻烦

**Comment by chung1912** [comment]
> 做个简单的测试
> 
> ```
> docker exec -it lobechat /bin/node
> ```
> 
> 进入 node 后复制以下代码，将 `https://www.baidu.com` 改为你的 OSS 或者 OAUTH 的 URL
> 
> ```
> const tls = require('tls');
> 
> const parseUrl = (url) => {
>   const { protocol, hostname: host, port } = new URL(url);
>   return { protocol: protocol.replace(':', ''), host, port: port || 443 };
> };
> 
> const isValidTLS = (url = '') => {
>   if (!url) {
>     console.log('⚠️ TLS Check: No URL provided. Skipping TLS check. Ensure correct setting ENV.');
>     console.log('-------------------------------------');
>     return Promise.resolve();
>   }
> 
>   const { protocol, host, port } = parseUrl(url);
>   if (protocol !== 'https') {
>     console.log(`⚠️ TLS Check: Non-HTTPS protocol (${protocol}). Skipping TLS check for ${url}.`);
>     console.log('-------------------------------------');
>     return Promise.resolve();
>   }
> 
>   const options = { host, port, servername: host };
>   return new Promise((resolve, reject) => {
>     const socket = tls.connect(options, () => {
>       console.log(socket)
>       socket.end();
> 
>       resolve();
>     });
> 
>     socket.on('error', (err) => {
>       reject(err);
>     });
>   });
> };
> 
> isValidTLS("https://www.baidu.com")
> ```
> 
> 看看结果

这个是执行完成之后的结果：
![image](https://github.com/user-attachments/assets/d6b0fa60-85c4-4ce3-a20c-d5f34cc29492)

**Comment by hezhijie0327** [comment]
我们先排除下 `NODE_EXTRA_CA_CERTS` 这个的干扰

把 `NODE_OPTIONS` 设置为空看看，即`NODE_OPTIONS=""` 这个会让 Node 使用内建 CA

**Comment by chung1912** [comment]
> NODE_OPTIONS=""

我将`NODE_EXTRA_CA_CERTS`注释掉了，然后`NODE_OPTIONS=""` ，情况没有变化
![image](https://github.com/user-attachments/assets/a108aa42-1cc6-41fb-832a-b4d7a7fd41f0)

**Comment by hezhijie0327** [comment]
Double confirm 下，镜像版本是最新对吧？

因为感觉怪怪的... 我拿 IP 自签去测试至少会抛错
![image](https://github.com/user-attachments/assets/05ac9732-fdfc-4409-8dd6-459cfd6a6e33)

但是有一种情况可能会卡着，就是目的服务器不可用，会卡个 timeout 时间
![image](https://github.com/user-attachments/assets/9351273d-3cec-49f9-acf2-269c47400f47)

按照现在这个位置的话，是在检测 OSS 服务

**Comment by hezhijie0327** [comment]
默认的 `NODE_EXTRA_CA_CERTS` 位置得改下，改成默认为空，现在如果要搞的话，你得在 Host 上信任你的证书，再把它映射进去，这么一想确实变复杂了...

**Comment by hezhijie0327** [comment]
对 设计中的话遇到 http 会直接跳过检测 这个应该有解，我过会儿 Build 一个版本 你改下镜像试试

**Comment by chung1912** [comment]
> 对 设计中的话遇到 http 会直接跳过检测 这个应该有解，我过会儿 Build 一个版本 你改下镜像试试

而且，如果你minio设置为http的话，lobechat用https将无法正常用minio，因为https不允许掺杂http的链接访问。。很麻烦，这样全局就强制只能用http。。

**Comment by hezhijie0327** [comment]
要么临时测试下如果把 `NODE_TLS_REJECT_UNAUTHORIZED="0"` 看看过的去不，过得去估计就是 CA 这块的引入问题

**Comment by chung1912** [comment]
> 要么临时测试下如果把 `NODE_TLS_REJECT_UNAUTHORIZED="0"` 看看过的去不，过得去估计就是 CA 这块的引入问题

改成0也不行，这个似乎不单纯是没正确信任证书的问题，就是不允许docker内部对外访问https+ip的地址，检查的时候给拦下来了，不给启动服务
![image](https://github.com/user-attachments/assets/f5c09a7a-8cb9-4cdc-9f37-0dbc7e0eea27)

**Comment by hezhijie0327** [comment]
@chung1912 试下这个镜像 `hezhijie0327/lobechat:database`，用你改之前的 ENV 看看

`NODE_EXTRA_CA_CERTS` 填写自签证书路径

**Comment by arvinxx** [comment]
@hezhijie0327  https://discord.com/channels/1127171173982154893/1197459409807343697/1290220420561113109 这个问题也看下

**Comment by hezhijie0327** [comment]
@arvinxx 这个在这个 PR 里已经修掉了

**Comment by chung1912** [comment]
> @chung1912 试下这个镜像 `hezhijie0327/lobechat:database`，用你改之前的 ENV 看看
> 
> `NODE_EXTRA_CA_CERTS` 填写自签证书路径

虽然没有那行提示了，但是还是不能正常启动：
![image](https://github.com/user-attachments/assets/90b6f296-9c92-40d1-ad30-93aeffa8e289)

**Comment by hezhijie0327** [comment]
连接超时了... OSS 连通性？本来是想做简单的问题诊断的...

**Comment by hezhijie0327** [comment]
@arvinxx 我过会儿把这个检测机制拿掉，还是 Case by case 处理

**Comment by chung1912** [comment]
> 连接超时了... OSS 连通性？新的一版里加了3s的超时检测。本来是想做简单的问题诊断的...

如果暂时不好解决的话，建议先恢复成原来的版本，不然只能一直用v1.20.4

**Comment by hezhijie0327** [comment]
嗯 我拿掉这块 重新 Build 一个 然后你试试

**Comment by chung1912** [comment]
> 嗯 我拿掉这块 重新 Build 一个 然后你试试

刚拉了你那个最新的，循环报错日志
![image](https://github.com/user-attachments/assets/09956142-6ab8-450c-95e0-85c36586f502)

**Comment by hezhijie0327** [comment]
还在构建 等一下，这是 3s timeout 的版本

**Comment by chung1912** [comment]
> @chung1912 好了 试试

这个正常，可以进去了

**Comment by hezhijie0327** [comment]
同时测试下自签证书

**Comment by chung1912** [comment]
> 同时测试下自签证书

这个也没有问题
