### ISSUE TITLE
[Bug] The third-party API KEY I use reports an error 404

### ISSUE THREAD

**Issue by zhouxiangbin** [lobehub/lobe-chat#4222]
### 📦 Environment

Docker

### 📌 Version

26.0.0

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

Error requesting OpenAI service, please troubleshoot or retry based on the following information

### 📷 Recurrence Steps

The third-party API I use works fine when running with the chatgpt-web-midjourney-proxy container;
But the LobeChat program reports a 404 error
The docker run command is as follows

docker run -d -p 3210:3210 \
  -e OPENAI_API_KEY=hk-dri6666666666666666666666666666666666cf1e712 \
  -e OPENAI_PROXY_URL=https://api.openai-hk.com \
  -e ACCESS_CODE=lobe66 \
  --name lobe-chat \
  lobehub/lobe-chat  

![image](https://github.com/user-attachments/assets/369e907e-5b4c-43cd-8623-98bad232c94a)

**Comment by arvinxx** [comment]
-e OPENAI_PROXY_URL=https://api.openai-hk.com/v1
