### ISSUE TITLE
[Bug] 在一个对话中第二次上传图片时，模型会回答第一张图片的内容

### ISSUE THREAD

**Issue by hlc1209** [lobehub/lobe-chat#4243]
### 📦 部署环境

Docker

### 📌 软件版本

v1.20.2

### 💻 系统环境

Windows, macOS

### 🌐 浏览器

Chrome, Safari

### 🐛 问题描述

在一个对话中第二次上传图片时，模型会回答第一张图片的内容
必须点“删除并重新生成”，才会回答新上传图片的内容

**Comment by arvinxx** [comment]
duplicate of #3760
