### ISSUE TITLE
[Bug] 文生图 dall-e-3 无法使用

### ISSUE THREAD

**Issue by fluidog** [lobehub/lobe-chat#4247]
### 📦 Environment

Docker

### 📌 Version

lastest

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

每次使用 dall-e-3，会显示响应为空
<img width="498" alt="image" src="https://github.com/user-attachments/assets/4df961bf-c463-4378-a800-35413938b2a9">

**Comment by checkso** [comment]
I have the same issue.

The only error I see:

{
  "name": "SyntaxError"
}

<img width="194" alt="image" src="https://github.com/user-attachments/assets/c8a12514-eb49-4341-8048-90989b7b5dec">

**Comment by forever-lwy** [comment]
我也有同样的问题，检查了一下api那边的日志，没有收到请求，然后其他插件使用正常，应该不是接口和模型的问题，是dalle3这个内置插件出了什么问题？

**Comment by nexusdiscord** [comment]
It happened to me too

![{D41B9F10-7BE5-4557-A826-F3D5E0FEDD20}](https://github.com/user-attachments/assets/e81ca221-5e9e-43b0-93ce-196ed7b5c505)

**Comment by SiJin233** [comment]
It happened to me too！

**Comment by nexusdiscord** [comment]
After the update, there's still an error but with additional information in the error message.

`Sorry, the server seems to be experiencing some difficulties and is temporarily unable to complete your request. Please try again later.
Show Details
json
{
  "error": {},
  "provider": "openai"
}`

![{F39952AC-0ADF-40EA-BC56-38481BC21829}](https://github.com/user-attachments/assets/f5a613b9-30aa-46bb-a7e3-f825a0e6fe8c)

**Comment by arvinxx** [comment]
@nexusdiscord check the error on your server

**Comment by nexusdiscord** [comment]
I use vercel
![{9E01FA58-9075-4140-8581-E7AC95841849}](https://github.com/user-attachments/assets/c1f217b4-b440-4339-ba04-a74b1b5b11ce)
