### ISSUE TITLE
[Request] User Topup Payment support 充值支付

### ISSUE THREAD

**Issue by shawnmuggle** [lobehub/lobe-chat#4249]
### 🥰 需求描述

What about adding a payment service on the user Account session ? 
Either subscription fee or pay as you go.

### 🧐 解决方案

1. Since it's a global userbase, we start with crypto payments topup
2. Users can topup their account by USDT and USDC payments (stablecoins)
3. Ideally, the money will be sent to the developer (self managed). Developer can pay OpenRouter for api key.

**Comment by Sun-drenched** [comment]
Recharge payment and other commercial/profit functions should be available through the commercial version of Lobechat. You can contact the developer through the official community on Discord for details.
The community version of lobechat open source on GitHub should not include these functions

**Comment by arvinxx** [comment]
@Sun-drenched is right. The payment and management is not suitable for the open source version.
