### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by liaoke01** [lobehub/lobe-chat#425]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Firefox

### 🐛 问题描述 | Bug Description

vercel在更新到项目最新的源代码后，一键部署错误
![Screenshot_20231108-074249_Evolution X Launcher](https://github.com/lobehub/lobe-chat/assets/104013620/e1d1e4d4-6c78-4e5c-9c9c-f8a1aa678aec)

### 📷 复现步骤 | Recurrence Steps

在vercel项目中一键部署

**Comment by arvinxx** [comment]
请截一下部署的图？

![image](https://github.com/lobehub/lobe-chat/assets/28616219/7a334833-c686-4f23-b6a3-dfd566a30a77)

我看下是啥报错

**Comment by Shadownc** [comment]
Same deployment error
![image](https://github.com/lobehub/lobe-chat/assets/19424471/ad781212-c421-4b0d-be83-a6c37e97c467)

**Comment by arvinxx** [comment]
@Shadownc @liaoke01 fixed, just need to sync repo or wait for the auto sync
