### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by davidelectricfree** [lobehub/lobe-chat#4253]
### 📦 Environment

Docker

### 📌 Version

1.19.21

### 💻 Operating System

Other Linux

### 🌐 Browser

Edge

### 🐛 Bug Description

使用docker compose 对lobe-chat-DB 进行部署，以下是compose 文件

services:
  network-service:
    image: alpine:3.20
    container_name: lobe-network
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}" # MinIO API
      - "9001:9001" # MinIO Console
      - "${LOGTO_PORT}:${LOGTO_PORT}" # Logto
      - "3002:3002" # Logto Admin
      - "${LOBE_PORT}:3210" # LobeChat
    command: tail -f /dev/null
    networks:
      - lobe-network

  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - "10190:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=${LOBE_DB_NAME}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - lobe-network

  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z
    container_name: lobe-minio
    network_mode: "service:network-service"
    volumes:
      - "./s3_data:/etc/minio/data"
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
      - "MINIO_API_CORS_ALLOW_ORIGIN=http://localhost:${LOBE_PORT}"
    restart: always
    command: >
      server /etc/minio/data --address ":${MINIO_PORT}" --console-address ":9001"

  logto:
    image: svhd/logto
    container_name: lobe-logto
    network_mode: "service:network-service"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - "TRUST_PROXY_HEADER=false"
      - "PORT=${LOGTO_PORT}"
      - "DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:10190/logto"
      - "ENDPOINT=http://localhost:${LOGTO_PORT}"
      - "ADMIN_ENDPOINT=http://localhost:3002"
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]

  lobe:
    image: lobehub/lobe-chat-database:v1.19.21
    container_name: lobe-database
    network_mode: "service:network-service"
    depends_on:
      postgresql:
        condition: service_healthy
      network-service:
        condition: service_started
      minio:
        condition: service_started
      logto:
        condition: service_started

    environment:
      - "APP_URL=http://localhost:${LOBE_PORT}"
      - "NEXT_AUTH_SSO_PROVIDERS=logto"
      - "KEY_VAULTS_SECRET=Kix2wcUONd4CX51E/ZPAd36BqM4wzJgKjPtz2sGztqQ="
      - "NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg"
      - "NEXTAUTH_URL=http://localhost:${LOBE_PORT}/api/auth"
      - "LOGTO_ISSUER=http://localhost:${LOGTO_PORT}/oidc"
      - "DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:10190/${LOBE_DB_NAME}"
      - "S3_ENDPOINT=http://localhost:${MINIO_PORT}"
      - "S3_BUCKET=${MINIO_LOBE_BUCKET}"
      - "S3_PUBLIC_DOMAIN=http://localhost:${MINIO_PORT}"
      - "S3_ENABLE_PATH_STYLE=1"
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local

networks:
  lobe-network:
    driver: bridge

现在lobe-logto 启动后，立马停止运行，查看报错信息为：

lobe-logto
date | stream | content
-- | -- | --
2024/10/04 11:53:03 | stderr | at process.processTimers (node:internal/timers:519:7)
2024/10/04 11:53:03 | stderr | at listOnTimeout (node:internal/timers:581:17)
2024/10/04 11:53:03 | stderr | at Timeout._onTimeout (/etc/logto/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:106:28)
2024/10/04 11:53:03 | stderr | fatal Error: timeout expired
2024/10/04 11:52:55 | stdout |  
2024/10/04 11:52:55 | stdout | > logto db seed --swe
2024/10/04 11:52:55 | stdout | > cli
2024/10/04 11:52:55 | stdout

查看了https://github.com/lobehub/lobe-chat/issues/4007 但是好像和我的报错不太一样，确实不知道怎么处理了，请大佬们帮忙

**Comment by SpeedupMaster** [comment]
试下使用zitadel本地部署？
https://github.com/lobehub/lobe-chat/tree/main/docker-compose/local/zitadel

**Comment by davidelectricfree** [comment]
> 嘿 ！我在这里帮助你解决任何错误、问题或贡献。我是一个擅长解决技术问题的机器人🤖。
> 
> 我发现了一个类似的讨论，其中 Docker Compose 设置中的服务在启动后会自动退出。该问题与 的版本更新有关 ，建议使用该版本以避免错误`logto``lobe-chat-db``logto``svhd/logto:1.19.0`[[1]](https://github.com/lobehub/lobe-chat/discussions/4009).
> 
> 在您的情况下，错误消息指示客户端存在超时问题。您可以尝试以下步骤来解决此问题：`pg`
> 
> 1. **检查数据库连接**：确保服务正在运行且可访问。您可以通过检查容器的日志来验证这一点，以确保它运行状况良好并准备好接受连接。`postgresql``postgresql`
> 2. **调整超时设置**：如果可能，请尝试增加服务中客户端的超时设置。这可能涉及修改与数据库连接相关的配置文件或环境变量。`pg``logto`
> 3. **验证环境变量**：仔细检查环境变量，尤其是 ，以确保它们设置正确并指向正确的数据库主机和端口。`DB_URL`
> 4. **使用兼容版本**：如类似讨论中所述，请考虑使用已知可以正常工作的特定映像版本，例如 .`logto``svhd/logto:1.19.0`
> 5. **网络配置**：确保网络配置允许服务与服务通信。应正确设置以允许此通信。`logto``postgresql``network_mode`
> 
> 如果这些步骤无法解决问题，您可能需要查看 Docker Compose 设置的具体配置，并确保所有服务都已正确定义并且能够相互通信。
> 
> _要继续与 [Dosu](https://dosu.dev) 交谈，请提及 。_

按照你的建议，我做了两方面的修改，首先是将PGSQL的连接进行了修改，由原来的10190端口，修改为docker内的5432端口，其次，我将LOGTO的版本修改为1.19.0，似乎LOGOTO一样存在同样的报错。
同时，我注意到在LOBE的LOG中，存在如下报错：


date | stream | content
-- | -- | --
2024/10/04 12:17:21 | stdout | [Database] Start to migration...
2024/10/04 12:17:20 | stderr | }
2024/10/04 12:17:20 | stderr | port: 5432
2024/10/04 12:17:20 | stderr | address: '172.24.0.3',
2024/10/04 12:17:20 | stderr | syscall: 'connect',
2024/10/04 12:17:20 | stderr | code: 'ETIMEDOUT',
2024/10/04 12:17:20 | stderr | errno: -110,
2024/10/04 12:17:20 | stderr | at async runMigrations (/app/docker.cjs:17:3) {
2024/10/04 12:17:20 | stderr | at async Object.migrate (/app/node_modules/drizzle-orm/node-postgres/migrator.cjs:27:3)
2024/10/04 12:17:20 | stderr | at async PgDialect.migrate (/app/node_modules/drizzle-orm/pg-core/dialect.cjs:50:5)
2024/10/04 12:17:20 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024/10/04 12:17:20 | stderr | at /app/node_modules/.pnpm/pg-pool@3.7.0_pg@8.13.0/node_modules/pg-pool/index.js:45:11
2024/10/04 12:17:20 | stderr | Error: connect ETIMEDOUT 172.24.0.3:5432
2024/10/04 12:17:20 | stderr | ❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below:
2024/10/04 12:15:12 | stdout | [Database] Start to migration...
2024/10/04 12:15:11 | stderr | }
2024/10/04 12:15:11 | stderr | port: 5432
2024/10/04 12:15:11 | stderr | address: '172.24.0.3',
2024/10/04 12:15:11 | stderr | syscall: 'connect',
2024/10/04 12:15:11 | stderr | code: 'ETIMEDOUT',
2024/10/04 12:15:11 | stderr | errno: -110,
2024/10/04 12:15:11 | stderr | at async runMigrations (/app/docker.cjs:17:3) {
2024/10/04 12:15:11 | stderr | at async Object.migrate (/app/node_modules/drizzle-orm/node-postgres/migrator.cjs:27:3)
2024/10/04 12:15:11 | stderr | at async PgDialect.migrate (/app/node_modules/drizzle-orm/pg-core/dialect.cjs:50:5)
2024/10/04 12:15:11 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024/10/04 12:15:11 | stderr | at /app/node_modules/.pnpm/pg-pool@3.7.0_pg@8.13.0/node_modules/pg-pool/index.js:45:11
2024/10/04 12:15:11 | stderr | Error: connect ETIMEDOUT 172.24.0.3:5432
2024/10/04 12:15:11 | stderr | ❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below:
2024/10/04 12:13:04 | stdout | [Database] Start to migration...

请大佬教教我下一步要怎么做以排除故障

**Comment by davidelectricfree** [comment]
> 试下使用zitadel本地部署？ https://github.com/lobehub/lobe-chat/tree/main/docker-compose/local/zitadel

替代了LOGTO是吗，好的，我稍后试一下

**Comment by SpeedupMaster** [comment]
❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below:
报错显示DATABASE_URL有问题

**Comment by davidelectricfree** [comment]
> ❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below: 报错显示DATABASE_URL有问题

对，我用的是群晖的NAS，我刚才检查了一下，群晖的NAS自己使用了PGSQL的端口5432，因为直接用大佬给的compose文件，会出现端口被占用的提示，所以我将    ports: - "5432:5432" 改成了ports: - "10190:5432"，同时，将所有PGSQL的端口也修改为了10190，但是好像还是会有连不上的问题，有点不知道怎么弄了😂

**Comment by davidelectricfree** [comment]
> ❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below: 报错显示DATABASE_URL有问题

https://discourse.joplinapp.org/t/joplin-server-with-custom-database-port/18916 
还有一种方法，我按照上面这个帖子，尝试使用command -p +端口的方式，修改PGSQL的端口，这样LOGTO倒是不会DOWN掉，但是会出现PGSQL unhealthy的问题

**Comment by davidelectricfree** [comment]
> ❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below: 报错显示DATABASE_URL有问题

这样也造成了我没办法进行下一步，大佬知道我应该怎么办嘛

**Comment by SpeedupMaster** [comment]
> > ❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below: 报错显示DATABASE_URL有问题
> 
> 对，我用的是群晖的NAS，我刚才检查了一下，群晖的NAS自己使用了PGSQL的端口5432，因为直接用大佬给的compose文件，会出现端口被占用的提示，所以我将 ports: - "5432:5432" 改成了ports: - "10190:5432"，同时，将所有PGSQL的端口也修改为了10190，但是好像还是会有连不上的问题，有点不知道怎么弄了😂

改端口没问题啊
```
DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/logto
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}
```
这两个的的端口不用改
![图片](https://github.com/user-attachments/assets/a7ea16c8-617e-4fc1-b69d-351cef107047)

**Comment by davidelectricfree** [comment]
> > > ❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below: 报错显示DATABASE_URL有问题
> > 
> > 
> > 对，我用的是群晖的NAS，我刚才检查了一下，群晖的NAS自己使用了PGSQL的端口5432，因为直接用大佬给的compose文件，会出现端口被占用的提示，所以我将 ports: - "5432:5432" 改成了ports: - "10190:5432"，同时，将所有PGSQL的端口也修改为了10190，但是好像还是会有连不上的问题，有点不知道怎么弄了😂
> 
> 改端口没问题啊
> 
> ```
> DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/logto
> DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}
> ```
> 
> 这两个的的端口不用改 ![图片](https://private-user-images.githubusercontent.com/130642629/373507425-a7ea16c8-617e-4fc1-b69d-351cef107047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMTc4OTMsIm5iZiI6MTcyODAxNzU5MywicGF0aCI6Ii8xMzA2NDI2MjkvMzczNTA3NDI1LWE3ZWExNmM4LTYxN2UtNGZjMS1iNjlkLTM1MWNlZjEwNzA0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQwNDUzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2RmNzAzMWZlYzM1MmJjOWNhYTBjNzE5NmJmY2IxM2Q0NzdlYThmZTI2OWVlYjE0YTU2OGM0ODE3ZjZhMTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zfd0zbZJy4syaxnCJ3RbvBwanT2HMiQxd0oX8BikYjQ)

好的，大佬，我试一下，谢谢

**Comment by davidelectricfree** [comment]
> DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}

十分感谢，我仔细回顾了一下，我的群晖防火墙目前我设置了白名单模式，新建的Docker网段不在白名单内，导致连不上数据库，十分感谢

**Comment by adaaaaaa** [comment]
> 会出现PGSQL unhealthy的问题

我第一次安装就出现这个问题，这个要怎么弄？
