### ISSUE TITLE
[Bug] unauthorized_client: Callback URL mismatch. http://0.0.0.0:3210/api/auth/callback/auth0 is not in the list of allowed callback URLs

### ISSUE THREAD

**Issue by gaye746560359** [lobehub/lobe-chat#4258]
### 📦 Environment

Docker

### 📌 Version

1.21.4

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

点击登录时提示unauthorized_client: Callback URL mismatch. http://0.0.0.0:3210/api/auth/callback/auth0 is not in the list of allowed callback URLs
![image](https://github.com/user-attachments/assets/5234f3cd-bbec-4551-9807-0856a24e69d9)
![image](https://github.com/user-attachments/assets/ba9ad09e-241a-4cf8-9efa-5594141d4881)

**Comment by gaye746560359** [comment]
> To resolve the "unauthorized_client: Callback URL mismatch" error, you need to ensure that the callback URL `http://0.0.0.0:3210/api/auth/callback/auth0` is included in the list of Allowed Callback URLs in your Auth0 application settings. Here’s how you can do it:要解决“unauthorized_client：回调 URL 不匹配”错误，您需要确保回调 URL 包含在 Auth0 应用程序设置的允许回调 URL 列表中。您可以这样做：
> 
> 1. Go to your Auth0 application settings.转到 Auth0 应用程序设置。
> 2. In the "Settings" tab, locate the "Allowed Callback URLs" field.在 “Settings” 选项卡中，找到 “Allowed Callback URLs” 字段。
> 3. Add the following URL to the list:将以下 URL 添加到列表中：
>    ```shell
>    http://0.0.0.0:3210/api/auth/callback/auth0
>    ```
> 
> Make sure that this URL is consistent with the URL used in your Docker environment [[1]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/advanced/auth/next-auth/auth0.mdx).确保此 URL 与 Docker 环境 [[1]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/advanced/auth/next-auth/auth0.mdx) 中使用的 URL 一致。
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._要继续与 [Dosu](https://dosu.dev) 交谈，请提及 。

如果回调配置http://0.0.0.0:3210/api/auth/callback/auth0
登录跳转时报错无法访问此网站
网址为 http://0.0.0.0:3210/api/auth/callback/auth0?code=yejkYCRIQ75riXBewB7RBo1y_ViRAKpHXliffwVDJVcPI&state=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiMzdPT3EwVFFheFhMdDNMTXo2YWFpMjgyWXBkc2FPYTdDbHlIdlg2QnViMm5NNWk0RDdZQ21nX0UtQUJac004QXBWaHc5NmhnSTQxb0VfNXpobjMwSVEifQ..tz0bC6dM42_IZiXFWJx9Vw.EB3p1uXzaww_ie56bLoRTnSyltkTVEkkIXfzwSLJiaAkLCKbUAGfrkZf-OuyM0FQlWWFtFibmw3_IrL7IGBs_PEaefCRYfstvXDTOXKeIBBKFJncGvXhYkmdHd81NyYoy3OG5Iz11MI3p8PZ8IlMmNNJX14bXnLkD22tPmx8_mxROtp30hyBoYjgWv_PVKmJDvklEgz8KhioFGTcQ4ISQtJEpWGz9ZZsSRgisVKlXti9TsUDFE88SH8mrbvO9TiniYJ7y9FDJ8DVGT0gXNTiPg.7cBAhhNjg0qmZOhTukCs8AQNJZ0xX7MsIwIWkgzgie4 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。

**Comment by SpeedupMaster** [comment]
NEXTAUTH_URL有设置吗？

**Comment by gaye746560359** [comment]
> NEXTAUTH_URL有设置吗？

NEXTAUTH_URL=http://公网IP:3210/api/auth

**Comment by SpeedupMaster** [comment]
> > NEXTAUTH_URL有设置吗？
> 
> NEXTAUTH_URL=[http://公网IP:3210/api/auth](http://%E5%85%AC%E7%BD%91IP:3210/api/auth)

设置成localhost试试

**Comment by gaye746560359** [comment]
> > > NEXTAUTH_URL有设置吗？
> > 
> > 
> > NEXTAUTH_URL=[http://公网IP:3210/api/auth](http://%E5%85%AC%E7%BD%91IP:3210/api/auth)
> 
> 设置成localhost试试

没用，报错如下
无法访问此网站
网址为 http://0.0.0.0:3210/api/auth/callback/auth0?code=RopNHPUxXbG5iUo7e6Te95_-d5pCfDPZF3rXFqgVRe1l1&state=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiMzdPT3EwVFFheFhMdDNMTXo2YWFpMjgyWXBkc2FPYTdDbHlIdlg2QnViMm5NNWk0RDdZQ21nX0UtQUJac004QXBWaHc5NmhnSTQxb0VfNXpobjMwSVEifQ..ElkmVJ7-tFTP9VXnVDz5yw.HkIkIeb8hhBOW-Z1NqhfVfNQXCkBvcgquuilfuRDBNRyVKIEwfvsnN2m-azfVt1SvHd0OZbBqAYGccPH1kXGvtkE1gwYWhwTcdndZp_qoRuLJmQZvv8PqLdh2GBD1ILNAfdzItiVv8uF64gIbGEIqdwmJ5T0OkNaUn0yfjq937egWhAAPv1AvWFpkDPAjABETkvG6OkioKQORPIdZdTdww4WyDuoMg3nfdh6BD2t3pfoYzBOI0c4dcl4EQq1nKzHdA2_0SplxVkrwIR4E9ddKQ.i3SL1ZhFJQqkWwNbj3YZrSN4uoLjTuTS4JiqRlDxxqo 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_ADDRESS_INVALID

**Comment by SpeedupMaster** [comment]
> > > > NEXTAUTH_URL有设置吗？
> > > 
> > > 
> > > NEXTAUTH_URL=[http://公网IP:3210/api/auth](http://%E5%85%AC%E7%BD%91IP:3210/api/auth)
> > 
> > 
> > 设置成localhost试试
> 
> 没用，报错如下 无法访问此网站 网址为 http://0.0.0.0:3210/api/auth/callback/auth0?code=RopNHPUxXbG5iUo7e6Te95_-d5pCfDPZF3rXFqgVRe1l1&state=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiMzdPT3EwVFFheFhMdDNMTXo2YWFpMjgyWXBkc2FPYTdDbHlIdlg2QnViMm5NNWk0RDdZQ21nX0UtQUJac004QXBWaHc5NmhnSTQxb0VfNXpobjMwSVEifQ..ElkmVJ7-tFTP9VXnVDz5yw.HkIkIeb8hhBOW-Z1NqhfVfNQXCkBvcgquuilfuRDBNRyVKIEwfvsnN2m-azfVt1SvHd0OZbBqAYGccPH1kXGvtkE1gwYWhwTcdndZp_qoRuLJmQZvv8PqLdh2GBD1ILNAfdzItiVv8uF64gIbGEIqdwmJ5T0OkNaUn0yfjq937egWhAAPv1AvWFpkDPAjABETkvG6OkioKQORPIdZdTdww4WyDuoMg3nfdh6BD2t3pfoYzBOI0c4dcl4EQq1nKzHdA2_0SplxVkrwIR4E9ddKQ.i3SL1ZhFJQqkWwNbj3YZrSN4uoLjTuTS4JiqRlDxxqo 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。 ERR_ADDRESS_INVALID

其他的也改成localhost了？之前在windows上本地部署，用auth0没问题，不过全是用的localhost没用公网IP

**Comment by arvinxx** [comment]
0.0.0.0:3210 和你 auth0 allow 的配置不一样，仔细检查下配置
