### ISSUE TITLE
[Bug] Nginx反代又出现问题了

### ISSUE THREAD

**Issue by chung1912** [lobehub/lobe-chat#4270]
### 📦 部署环境

Docker

### 📌 软件版本

v1.21.6(Database版)

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

升级v1.21.6之后，反代出现502错误，nginx日志：
`*196 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.88, server: lobechat, request: "GET /chat HTTP/2.0", upstream: "http://172.88.0.22:3210/chat", host: "192.168.1.88:3210"`
后台没有任何记录：
![image](https://github.com/user-attachments/assets/cd940fae-0bb8-4889-8fd5-f0dfb243560d)
之前的版本没问题

**Comment by arvinxx** [comment]
这个解决了吧？
