### ISSUE TITLE
[Bug] Dall3 内置插件无法生成图像

### ISSUE THREAD

**Issue by ProgramFan** [lobehub/lobe-chat#4275]
### 📦 部署环境

Vercel

### 📌 软件版本

1.21.6

### 💻 系统环境

Other Linux

### 🌐 浏览器

Edge

### 🐛 问题描述

gpt-4o 调用 dalle.3 无法生成图像，提示如下错误：
```
{
  "error": {},
  "provider": "openai"
}
```

### 📷 复现步骤

插件调用参数：
```json
{
  "apiName": "text2image",
  "arguments": "{\"prompts\":[\"A photo of a large space telescope floating in the vastness of space. The telescope is sleek and modern, with a reflective surface and intricate details. It is surrounded by a backdrop of stars and distant galaxies, with a faint glow from a nearby nebula. The image captures the grandeur and technological marvel of a space telescope in operation.\"],\"quality\":\"hd\",\"size\":\"1024x1024\",\"style\":\"natural\"}",
  "identifier": "lobe-image-designer",
  "type": "builtin"
}
```

### 🚦 期望结果

正确生成图片并显示

### 📝 补充信息

服务端存储，不能生成图片，本地存储可以生成。同样的OPENAI_API_KEY使用Python API调用可以正确生成图片。

**Comment by ProgramFan** [comment]
No, I am using directly the official OpenAI endpoints. It seems that this only happens if I deploy the application as server-side application, i.e., using the postgres db for storage. If I deploy it as client-side application (using browser IndexDB), it works.

**Comment by arvinxx** [comment]
@ProgramFan Are you using the clerk for auth?

**Comment by ProgramFan** [comment]
Yes, exactly. I am curious how this can be related to this issue?

**Comment by arvinxx** [comment]
@ProgramFan try again with latest version, I think it's fixed now

**Comment by ProgramFan** [comment]
Yes, it works.
