### ISSUE TITLE
[Bug] 文档中关于NEXTAUTH_URL的描述有误

### ISSUE THREAD

**Issue by zuilintan** [lobehub/lobe-chat#4277]
### 📦 部署环境

Vercel

### 📌 软件版本

1.21.6

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/user-attachments/assets/8134241b-de51-47b6-a3e7-d5675128c1c0)
是否应该为`可选`?

**Comment by SpeedupMaster** [comment]
NEXTAUTH_URL这个不设置的话，登录、退出登录后跳转有问题

**Comment by arvinxx** [comment]
如果你是用 Vercel 部署的话可以尝试不加。但 Docker 部署是必选的
