### ISSUE TITLE
[Bug] Vercel部署Server端后, 先登录然后再退出登录, 此时再次登录未弹出账户密码确认页, 而是直接登录成功

### ISSUE THREAD

**Issue by zuilintan** [lobehub/lobe-chat#4279]
### 📦 Environment

Vercel

### 📌 Version

1.21.6

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

Vercel部署Server端后, 先登录然后再退出登录, 此时再次登录未弹出账户密码确认页, 而是直接登录成功

**Comment by SpeedupMaster** [comment]
#3646

**Comment by zuilintan** [comment]
> #3646

THK, 
很可惜, 这个issue似乎没有Resolved的计划

**Comment by arvinxx** [comment]
重复 https://github.com/lobehub/lobe-chat/issues/3646
