### ISSUE TITLE
增加对第三方逆向OpenAI API的支持

### ISSUE THREAD

**Issue by cr-zhichen** [lobehub/lobe-chat#4294]
### 🥰 需求描述

加入 `gpt-4-all` `gpt-4o-all` `gpt-4-v` 这三个模型多模态支持

### 🧐 解决方案

允许 `gpt-4-all` `gpt-4o-all` `gpt-4-v` 这三个模型的图片输入

### 📝 补充信息

现在有很多转发API商家，都接入了OpenAI的转发API，想要增加对这些转发API的支持

**Comment by arvinxx** [comment]
逆向没有任何计划
