### ISSUE TITLE
[Request] 通过账号使用大模型，并且支持多窗口

### ISSUE THREAD

**Issue by aofly** [lobehub/lobe-chat#4301]
### 🥰 需求描述

![image](https://github.com/user-attachments/assets/27b413e5-de0e-4fde-b749-a627193f3500)
![image](https://github.com/user-attachments/assets/f1a2ef52-4ae5-4123-8102-0a79aa1ec467)

如图所示，可以登录自己的账号使用，同时支持多窗口，可以同时比较不同模型

### 🧐 解决方案

可以登录自己的账号使用，同时支持多窗口，可以同时比较不同模型，就想chathub这样

**Comment by arvinxx** [comment]
账号不会支持的。lobeChat只支持 api。

多个对话面板会做的
