### ISSUE TITLE
[Request] 请问有没有办法使要发送的图片不以url形式，而是以base64编码发送？

### ISSUE THREAD

**Issue by BiFangKNT** [lobehub/lobe-chat#4305]
### 🥰 需求描述

智谱api不支持ipv6，而我的服务器只支持ipv6访问，因此发送url的话模型是无法读取的，因此希望能够在相关逻辑中加入一个判断，如果是智谱系模型，就先将minio中的图片转为base64编码再发送。或者在智谱的模型设置里添加一个是否将图片url转换为base64的开关。

由于不了解lobe的项目结构，我不知道相关的处理逻辑是在哪里的，希望大佬告知一二！

相关讨论：https://github.com/lobehub/lobe-chat/issues/3909#issuecomment-2381260111

### 🧐 解决方案

在相关逻辑中加入一个判断，如果是智谱系模型，就先将minio中的图片转为base64编码再发送。或者在智谱的模型设置里添加一个是否将图片url转换为base64的开关。

**Comment by arvinxx** [comment]
不考虑做，等智谱支持 ipv6 就行了。或者你换成ipv4也行。

另外现在已经有环境变量支持url转base64了

**Comment by BiFangKNT** [comment]
> 不考虑做，等智谱支持 ipv6 就行了。或者你换成ipv4也行。
> 
> 另外现在已经有环境变量支持url转base64了

请问这个环境变量是在哪里添加的？是全局的吗？之前好像看到过相关的讨论，但是找不到了

**Comment by BiFangKNT** [comment]
@arvinxx 请问是`LLM_VISION_IMAGE_USE_BASE64`这个环境变量吗？这个好像是全局的，我不太想让所有模型都转base64

**Comment by BiFangKNT** [comment]
@arvinxx 另外大佬，我开启了这个环境变量，也还是不行
![image](https://github.com/user-attachments/assets/57cdd064-de16-4409-84b1-2827c744723a)
![image](https://github.com/user-attachments/assets/db61220e-8e79-4ba0-bbb4-b6e5d3c7d8db)

**Comment by BiFangKNT** [comment]
@arvinxx 诶，关闭客户端请求模式就可以了，这是为什么啊？
![image](https://github.com/user-attachments/assets/2978214f-3b65-408b-93c3-25862acca77e)
![image](https://github.com/user-attachments/assets/dac35837-494d-4dff-80ac-650f60b8ccc6)

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/discussions/3888

**Comment by BiFangKNT** [comment]
> #3888

@arvinxx 好的，非常感谢！
