### ISSUE TITLE
[Bug] When using Azure backend all chats names stay as "Default Topic"

### ISSUE THREAD

**Issue by bvajk** [lobehub/lobe-chat#4306]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Ubuntu

### 🌐 Browser

Firefox

### 🐛 Bug Description

When using Azure backend all chats names stay as "Default Topic"
![image](https://github.com/user-attachments/assets/a1a01341-63ed-4ba9-9acc-b29094a8c929)

### 📷 Recurrence Steps

use azure backend and chat with ai

### 🚦 Expected Behavior

With openai backend the chat topic names were appropriate

**Comment by bvajk** [comment]
@Dosu the issue is not that I dont like the "default topic" name and want to change it to another static name. What I want is the regular functionality when a gpt-4o mini sets the titlte according to the conversation

**Comment by arvinxx** [comment]
duplicate of https://github.com/lobehub/lobe-chat/issues/3513

**Comment by pepijnolivier** [comment]
For those experiencing this issue today, after the ChatGPT 5 update, you likely need to verify your organisation to use the configured "Topic Naming Model"

As a workaround, you can choose a different model under settings => system assistant
