### ISSUE TITLE
[Question] 代理设置

### ISSUE THREAD

**Issue by xiaoxiao-2944905105** [lobehub/lobe-chat#431]
### 🧐 问题描述 | Proposed Solution

{
  "endpoint": "https://api-proxy.com/v1",
  "error": {
    "cause": {
      "errno": -3007,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "api-proxy.com"
    }
  }
}

**Comment by arvinxx** [comment]
这个可能是你的代理问题，和本项目应该没啥关系

**Comment by xiaoxiao-2944905105** [comment]
?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lobehub/lobe-chat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月8日(星期三) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lobehub/lobe-chat] 紧急的问题 (Issue #431)





  
Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
  
 
This may be an issue with your agency, and it probably has nothing to do with this project.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;







是的，我把代理服务器换成openai,程序就可以正常运行了

**Comment by FrankFuShMomentLab** [comment]
> 这个可能是你的代理问题，和本项目应该没啥关系

但是这个代理服务器的地址是docker部署环境配置中提供的啊

**Comment by FrankFuShMomentLab** [comment]
> 这个可能是你的代理问题，和本项目应该没啥关系

所以请问这里我应该怎么设置？

**Comment by FrankFuShMomentLab** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> This may be an issue with your agency, and it probably has nothing to do with this project.

额 所以我应该怎么做呢?
