### ISSUE TITLE
[Bug] 错误显示计算额度已用尽

### ISSUE THREAD

**Issue by Luyi-2333** [lobehub/lobe-chat#4310]
### 📦 部署环境

Official Preview

### 📌 软件版本

v1.21.6

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

错误显示计算额度已用尽。目前只在“Excel公式大师”插件中使用会出现该情况。
![Snipaste_2024-10-10_11-22-07](https://github.com/user-attachments/assets/0cd45f5b-5a6d-4291-9098-0e0302ac8997)

**Comment by SpeedupMaster** [comment]
api的问题吧

**Comment by SpeedupMaster** [comment]
> api的问题吧

哦，没注意你用的是LobeChat Cloud😂

**Comment by Luyi-2333** [comment]
当我将模型从GPT mini切换到GPT后，此对话没有再出现该警告。

**Comment by arvinxx** [comment]
@Luyi-2333 只有 mini 会有这个问题吗？我这边没有复现哎

**Comment by SpeedupMaster** [comment]
> 只有 mini 会有这个问题吗？我这边没有复现哎

只有4o-mini在使用这个Excel公式大师时会出现这个问题，其他模型正常

**Comment by Luyi-2333** [comment]
使用其他助手时发现也会遇到该情况。猜想此问题可能与模型有关，与助手无关。
