### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by hbsky2015** [lobehub/lobe-chat#4315]
### 📦 部署环境

Docker

### 📌 软件版本

v1.21.9

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

Azure O1模型参数错误.max_tokens 参数已经改成了max_completion_tokens参数,请修复
{
  "error": {
    "message": "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.",
    "type": "invalid_request_error",
    "param": "max_tokens",
    "code": "unsupported_parameter"
  },
  "endpoint": "https://jc-gpt-swedencentral-inside-1.openai.azure.com",
  "provider": "azure"
}

### 📷 复现步骤

<img width="872" alt="image" src="https://github.com/user-attachments/assets/01fda9c9-695c-46d8-80f7-7622dac8d7d4">

### 🚦 期望结果

O1模型的 max_tokens改成了max_completion_tokens参数

**Comment by hbsky2015** [comment]
修复好了吗

**Comment by arvinxx** [comment]
重复 https://github.com/lobehub/lobe-chat/issues/4248
