### ISSUE TITLE
[Bug] 启动页的图片不显示，单独访问没问题

### ISSUE THREAD

**Issue by nanchao70** [lobehub/lobe-chat#4317]
### 📦 Environment

Docker

### 📌 Version

v1.21.6

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

![PixPin_2024-10-11_11-20-32](https://github.com/user-attachments/assets/003eca0f-b5fb-4ecb-b322-6916ccf445fe)
最早时候这个图片是正常的，后来发现不显示，然后多个版本升级下来都不显示。
图片链接单独访问是正常的。

**Comment by SpeedupMaster** [comment]
.top域名？#2828

**Comment by nanchao70** [comment]
> .top域名？#2828

是的，top域名

**Comment by SpeedupMaster** [comment]
> > .top域名？#2828
> 
> 是的，top域名

好像没解决方案

**Comment by nanchao70** [comment]
> > > .top域名？#2828
> > 
> > 
> > 是的，top域名
> 
> 好像没解决方案

一直用的top域名，之前都是正常的。这是什么原因导致？

**Comment by SpeedupMaster** [comment]
> > > > .top域名？#2828
> > > 
> > > 
> > > 是的，top域名
> > 
> > 
> > 好像没解决方案
> 
> 一直用的top域名，之前都是正常的。这是什么原因导致？

top 域名被 npmmirror 拉黑名单了，目前只能换域名解决 #3908
