### ISSUE TITLE
[Bug] 访问密码输入界面不应该限制只有 6 位、看上去数字形式

### ISSUE THREAD

**Issue by ShenQingchuan** [lobehub/lobe-chat#432]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

比如我的密码是 abcd1234 在密码输入界面就会很奇怪。

### 🚦 期望结果 | Expected Behavior

期望输入密码界面就应该是一个简单的 input 框而不是六位密码格

**Comment by ShenQingchuan** [comment]
## 输密码仅能有 6 位
![img_v2_02a59034-4a77-4e4c-b732-ed4657687dfg](https://github.com/lobehub/lobe-chat/assets/46062972/9c7e426f-33d0-4c44-910f-c74803ee6c43)

## 输入密码没有保护
![img_v2_bc6aa3d8-c27e-4351-a835-f0d59aa1c4eg](https://github.com/lobehub/lobe-chat/assets/46062972/112a3bc7-838b-41c1-af8d-f1c315924b8d)

**Comment by canisminor1990** [comment]
@arvinxx

**Comment by wwalkingg** [comment]
还有一个问题，在iOS上每输一个，键盘都会重置。如果你想输入6个数字，会非常麻烦

**Comment by arvinxx** [comment]
> 还有一个问题，在iOS上每输一个，键盘都会重置。如果你想输入6个数字，会非常麻烦

我改成 input 吧
