### ISSUE TITLE
[Docs] Feedback for `self-hosting/environment-variables/model-provider`

### ISSUE THREAD

**Issue by sunianyu** [lobehub/lobe-chat#4320]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/environment-variables/model-provider.zh-CN.mdx

### 🐛 Feedback

![image](https://github.com/user-attachments/assets/e4ca51ee-21f2-42fd-b01c-ac709f37e821)
我想请问一下，如何配置文心一样的API key 
Wenxin API Key 不正确或为空，请检查 Wenxin API Key 后重试
我找不到配置的地方

**Comment by SpeedupMaster** [comment]
WENXIN_ACCESS_KEY
WENXIN_SECRET_KEY

**Comment by arvinxx** [comment]
https://lobehub.com/zh/docs/usage/providers/wenxin

**Comment by wangping886** [comment]
> https://lobehub.com/zh/docs/usage/providers/wenxin
你好已经在env中配置了这两个，依然不可以调用ernie-4.0-turbo-8k，依然提示Wenxin API Key 不正确或为空
WENXIN_ACCESS_KEY
WENXIN_SECRET_KEY
WENXIN_MODEL_LIST=ernie-4.0-turbo-8k

**Comment by wangping886** [comment]
> https://lobehub.com/zh/docs/usage/providers/wenxin

hi,this 
![image](https://github.com/user-attachments/assets/41fd10d2-59d3-4011-a6ca-352e6f47e246)

**Comment by wangping886** [comment]
解决了 应该是用v2版本的ak和sk

**Comment by ferocknew** [comment]
> 解决了 应该是用v2版本的ak和sk

那如何使用呢？？？
