### ISSUE TITLE
[Bug] 助手SHareGPT分享失败

### ISSUE THREAD

**Issue by SAnBlog** [lobehub/lobe-chat#4321]
### 📦 Environment

Docker

### 📌 Version

v1.21.8

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

<img width="559" alt="image" src="https://github.com/user-attachments/assets/513995ee-ce57-41b2-8e91-5d23536ada52">

**Comment by arvinxx** [comment]
<img width="989" alt="image" src="https://github.com/user-attachments/assets/7cd13ee0-3f27-4825-aa9e-b202a82cf31c">


ShareGPT 挂了，正在想替代方案
