### ISSUE TITLE
[Bug] 字体大小设置不生效

### ISSUE THREAD

**Issue by ImAmelie** [lobehub/lobe-chat#433]
### 💻 系统环境 | Operating System

Ubuntu

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

在 `/settings/common` 页面设置字体大小，没有在会话界面生效。

我设置 18 ，结果会话界面的字体还是初始大小。

### 📝 补充信息 | Additional Information

Docker Image Vesion: v0.99.1

**Comment by canisminor1990** [comment]
字体大小设置确实好像还没绑定 我抽空实装下
