### ISSUE TITLE
[Bug] 在一个话题下只有第一次发送消息能提交图片

### ISSUE THREAD

**Issue by heshunme** [lobehub/lobe-chat#4340]
### 📦 部署环境

Docker

### 📌 软件版本

database 1.22.0

### 💻 系统环境

Windows

### 🌐 浏览器

Firefox

### 🐛 问题描述

我注意到在一个话题中，只有第一次上传的图片可以被正常合并到请求中发送（上传方式为复制图片并在输入框中粘贴）
哪怕是在完成第一次对话后将全部对话删除再进行完全相同的输入，也不能产生带有图片链接的正常请求。

具体如图：
第一次正常请求：
![图片](https://github.com/user-attachments/assets/33b74144-f518-44d6-bf87-cbde9c1971ee)
删除所有对话框后的第二次请求异常：
![图片](https://github.com/user-attachments/assets/7050bdff-3115-4b2d-9501-4dc085afe433)
图中请求中可见的用户输入文字来自模板，经过测试，无论有无模板、system prompt和历史消息限制条数均对该问题无影响。
与模型无关。Claude也会如此。

![图片](https://github.com/user-attachments/assets/e677da27-0ed7-45af-ad1c-bdec8f1d622a)

### 📷 复现步骤

方法一（我发现该问题的路径）
1.选择一个多模态大模型
2.复制一张图，在输入框中Ctrl+V粘贴并上传
3.写一段prompt并发送
4.逐个删除以上对话框
5.重复2和3
方法二：
1.选择一个多模态大模型
2.复制一张图，在输入框中Ctrl+V粘贴并上传
3.写一段prompt并发送
4.选择另一张图
5.重复2和3

### 🚦 期望结果

无论是上传的第几张图都能正常把URL发送给API提供商

**Comment by arvinxx** [comment]
重复 #3760
