### ISSUE TITLE
[Request]  聊天内容添加 copy 选项

### ISSUE THREAD

**Issue by Undertone0809** [lobehub/lobe-chat#435]
### 🥰 需求描述 | Feature Description

做一些文档翻译任务的时候，翻译出来的 markdown 文档需要 copy markdown 的结构，当前没有提供 copy 的选项，直接选中文字的话只能直接 copy 文字，不能把带有 markdown 的格式 copy 下来，建议添加一下该功能。

此外，还建议增加字符串格式或markdown的聊天格式导出功能。

### 🧐 解决方案 | Proposed Solution

为聊天内容添加 copy 选项

![image](https://github.com/lobehub/lobe-chat/assets/72488598/11769f36-22d2-4f1a-a473-799ee54a54f5)

![image](https://github.com/lobehub/lobe-chat/assets/72488598/1b59c026-1679-4ea6-999d-19aa3e57426b)

**Comment by arvinxx** [comment]
有的
<img width="1255" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/e86b29f3-0035-4f98-a8ac-4d2132a0fb52">
