### ISSUE TITLE
[Docs] Feedback for `self-hosting/advanced/auth/clerk`

### ISSUE THREAD

**Issue by byndrha** [lobehub/lobe-chat#4352]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/advanced/auth/clerk.mdx

### 🐛 Feedback

Can you please give us tutorial to use this Clerk Multi-User? Thankyou

**Comment by arvinxx** [comment]
https://lobehub.com/docs/self-hosting/server-database/vercel
