### ISSUE TITLE
[Bug] Docker Compose 示例文件和文档中的环境变量名有误

### ISSUE THREAD

**Issue by OneLostCat** [lobehub/lobe-chat#4353]
### 📦 部署环境

Docker

### 📌 软件版本

v1.22.2

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Firefox

### 🐛 问题描述

在 https://github.com/lobehub/lobe-chat/tree/main/docker-compose 的 Logto 示例中，用于设置 App ID 和 App Secret 的环境变量分别是 `AUTH_LOGTO_CLIENT_ID` 和 `AUTH_LOGTO_CLIENT_SECRET`

https://lobehub.com/zh/docs/self-hosting/environment-variables/auth#logto 也是 `AUTH_LOGTO_CLIENT_ID` 和 `AUTH_LOGTO_CLIENT_SECRET`

而 https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#登录鉴权服务配置 中却是  `AUTH_LOGTO_ID` 和 `AUTH_LOGTO_SECRET`

但在 v1.22.2 这个版本，设置 `AUTH_LOGTO_CLIENT_ID` 和 `AUTH_LOGTO_CLIENT_SECRET` 没有任何效果，只有设置 `AUTH_LOGTO_ID` 和 `AUTH_LOGTO_SECRET` 才能正常使用

文档是不是有点问题？

**Comment by arvinxx** [comment]
@zhuozhiyongde 文档还得调整下

**Comment by zhuozhiyongde** [comment]
OK，我的问题
