### ISSUE TITLE
[Bug] 同时配置ACCESS_CODE和Clerk后，ACCESS_CODE未生效

### ISSUE THREAD

**Issue by Joker2Yue** [lobehub/lobe-chat#4374]
### 📦 部署环境

Vercel

### 📌 软件版本

v1.22.6

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

在一周前我的LobeChat是没有使用server部署模式的，我在Vercel中配置了OpenAI的API-Key，同时开启了ACCESS_CODE访问密码，这样就能够方便我和我的小伙伴快速通过访问密码来进行对话，访客则需要输入自己的OpenAI API-Key以使用我的LobeChat。
一周后我决定将我的LobeChat部署为server模式，因为在原来的模式下不支持上传解析文件，于是我按照官方文档的教程，配置好了Clerk、S3存储桶、Postgres数据库......
然而我这么操作后，我发现，只要是注册后的用户，都可以不输入ACCESS_CODE而直接开始对话，这让我不得不紧急关闭Clerk的注册功能。

### 📷 复现步骤

正常以server模式配置好Vercel的环境变量，同时填写ACCESS_CODE的环境变量，部署就会发现，用户可以正常注册登录，而且可以【**直接开始对话**】，而并不需要输入ACCESS_CODE，在设置中的【访问密码】形同虚设。
![image](https://github.com/user-attachments/assets/c39bd59d-a835-405f-8cc0-ee44667dbcec)

### 🚦 期望结果

我期望在server模式下，启用ACCESS_CODE，能够像普通模式一样，弹出需要填写密码，就像这样：
![image](https://github.com/user-attachments/assets/b34dd8ed-126b-4543-abf1-7780be7d84b7)

**Comment by arvinxx** [comment]
用 clerk 就不需要access code了。这两个是互斥的鉴权方案

**Comment by fantasyroot** [comment]
> 用 clerk 就不需要access code了。这两个是互斥的鉴权方案

但是并没有提供个开关能卡注册，任何人都可以注册成功然后白嫖使用的。

注册和密码感觉是两码事，注册并不算鉴权只是有了个身份。

还是希望在 SSO 验证之后仍然校验 access code，或者能提供关闭注册的配置开关，谢谢

**Comment by arvinxx** [comment]
> 但是并没有提供个开关能卡注册，任何人都可以注册成功然后白嫖使用的。
> 
> 注册和密码感觉是两码事，注册并不算鉴权只是有了个身份。
> 
> 还是希望在 SSO 验证之后仍然校验 access code，或者能提供关闭注册的配置开关，谢谢

建议好好研究下clerk，你说的需求clerk都能满足。 Access code 已经是过去式了，面向未来吧
