### ISSUE TITLE
[Request] 能否增加 subdirectory/basePATH 自定义路径配置

### ISSUE THREAD

**Issue by BadException** [lobehub/lobe-chat#438]
### 🥰 需求描述 | Feature Description

在 nginx 反向代理中，想要配置特定的 location，比如：
`locaton /lobe-chat/ {
proxy_pass  http://172.17.0.2:3210 ;`
在 172.17.0.2 这个docker container 中配置 lobe-chat 路径，与 nginx 反代兼容

### 🧐 解决方案 | Proposed Solution

在 172.17.0.2 这个docker container 中配置 lobe-chat 路径，与 nginx 反代兼容

**Comment by arvinxx** [comment]
这块是我的知识盲区了，不知道咋做。

**Comment by T3rm1** [comment]
Any progress on this? I tried to run the docker container behind a reverse proxy. In my case it's Caddy. When I try to open the page, e.g. www.example.com/ai the page tries to load stuff from the root directory, e.g. https://www.example.com/_next/static/css/3cdca591b056ce4d.css
This is wrong and the sub path is ignored. Please fix this.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

**Comment by arvinxx** [comment]
Need help

**Comment by arvinxx** [comment]
已支持 `NEXT_PUBLIC_BASE_PATH` 环境变量，如果是 Vercel 部署，可以直接填写使用。但是如果是 Docker 部署使用，需要你自行构建 docker 镜像了

**Comment by PierreMesure** [comment]
Would be great to make it work out of the box when using Docker, having to build your own image every time is heavier than just pulling it. 🙏

**Comment by arvinxx** [comment]
@PierreMesure I think is impossible. Because we use the `NEXT_PUBLIC_BASE_PATH` env to achieve the basePath. but all `NEXT_PUBLIC_` env can't change after build, it's a build time env not the runtime.

**Comment by PierreMesure** [comment]
I'm sure you are more knowledgeable about Next.js but I found this: https://github.com/vercel/next.js/discussions/44628

It does confirm what you say about `NEXT_PUBLIC_` but also mentions another way.
