### ISSUE TITLE
[Bug] 首次登录,聊天会报错

### ISSUE THREAD

**Issue by zhang19980518** [lobehub/lobe-chat#4386]
### 📦 Environment

Zeabur

### 📌 Version

v1.22.6

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

当点立即开始进到默认助手此时不聊天,然后进行登录,登录成功后在默认助手界面聊天会报错。强制刷新后就没事了。

### 🚦 Expected Behavior

登录成功后第一次可以正常聊天

**Comment by arvinxx** [comment]
请录个屏看下你怎么操作的

**Comment by zhang19980518** [comment]
现在可以了。。
