### ISSUE TITLE
[Bug] 部署在vercel上的实例使用deepseek api key 输出会被截断

### ISSUE THREAD

**Issue by bakamake** [lobehub/lobe-chat#4388]
### 📦 部署环境

Vercel

### 📌 软件版本

v1.21.16

### 💻 系统环境

Windows, Other

### 🌐 浏览器

Edge

### 🐛 问题描述

我的服务 https://chat.bakamake.com/
需要我提供哪些细节，如何获取需要提交的信息

### 📷 复现步骤

![image](https://github.com/user-attachments/assets/503a28f6-834f-4d95-b7bf-240578ef5e27)
![image](https://github.com/user-attachments/assets/19718b75-bdc6-428a-94ca-e9763b49b0be)
![image](https://github.com/user-attachments/assets/b277d41d-d7fd-4a9a-95c1-f37c6ee9c753)

### 🚦 期望结果

https://chat.bakamake.com/

**Comment by sxjeru** [comment]
尝试了生成超五千字散文，也尝试用你截图中的信息询问，均未遇到截断情况。

如果可以，建议启用“客户端请求”。
