### ISSUE TITLE
[Request] use pdf and office365 files for use your chat

### ISSUE THREAD

**Issue by johnfelipe** [lobehub/lobe-chat#4399]
### 🥰 Feature Description

The current deployment mode does not support uploading non-image files. To upload files in pdf format, please switch to server database deployment or use the LobeChat Cloud service.

pls release this feature for all developers and DC in world

### 🧐 Proposed Solution

The current deployment mode does not support uploading non-image files. To upload files in pdf format, please switch to server database deployment or use the LobeChat Cloud service.

pls release this feature for all developers and DC in world

**Comment by SpeedupMaster** [comment]
If you want to upload PDF or other files, you need to deploy the database version. For detailed deployment instructions, please refer to [ref](https://lobehub.com/docs/self-hosting/server-database)
