### ISSUE TITLE
[Bug]  createShareGPTUrl issue / not create sharegpt

### ISSUE THREAD

**Issue by johnfelipe** [lobehub/lobe-chat#4400]
### 📦 Environment

Vercel

### 📌 Version

latest

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

    Uncaught (in promise) Error: No handler found for that type page
    /chat?topic=IMseBThd:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
    sharegpt.com/api/conversations:1 
            
            
           Failed to load resource: the server responded with a status of 405 ()
    chat:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
        at d.createShareGPTUrl (97013-197bfb78c7d24705.js:1:39822)
        at async shareToShareGPT (63605-d7cfedf4e6d2adda.js:1:30812)

![SNAG-0064](https://github.com/user-attachments/assets/2916662f-25f1-4568-b650-18b9f0f4c13d)

**Comment by johnfelipe** [comment]
any progress?

**Comment by arvinxx** [comment]
shareGPT is down.

**Comment by ebloom19** [comment]
![Screenshot 2024-10-28 at 5 49 03 PM](https://github.com/user-attachments/assets/f2ad7466-2245-420d-a4cd-ae944ef6fbff)

They seem to have deprecated their services

Check out their website

https://sharegpt.com/
