### ISSUE TITLE
[Bug] 1.22.8版本 一直停留在“应用启动中” 界面

### ISSUE THREAD

**Issue by Runarry** [lobehub/lobe-chat#4406]
### 📦 Environment

Docker

### 📌 Version

1.22.8

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

今天更新到1.22.8版本（lobe-database docker compose 部署），然后进入界面一直停留在应用启动中，查看docker log，也没有任何报错。还原到四天前的image后，一切正常。

**Comment by Runarry** [comment]
日志没有任何异常输出：
```
🌐 DNS Server: [ '127.0.0.11' ]
-------------------------------------
[Database] Start to migration...
✅ database migration pass.
-------------------------------------
  ▲ Next.js 14.2.8
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210

 ✓ Starting...
 ✓ Ready in 65ms
 ```
 
 今天尝试了1.22.8 版本，也仍然有问题。
 然后我逐版本回退，发现v1.22.6及之前的版本均正常。

**Comment by AmFe-GH** [comment]
更新一下浏览器版本，我解决了

**Comment by Runarry** [comment]
> 更新一下浏览器版本，我解决了

我的问题，和你的并不一致，我的问题是因为我自己蠢....
我Nginx是在一个单独的服务器，然后我检查了LobeChat服务器，甚至重新部署，都有问题，直到我无意中检查Nginx服务器，发现是因为硬盘满了.....老版本可以用是因为老版本的资源已经被CDN缓存过了，所以没有问题。

所以我关闭了这个问题。
