### ISSUE TITLE
[Request] 知识库Ollama Embedding模型支持

### ISSUE THREAD

**Issue by Baoyinliu** [lobehub/lobe-chat#4408]
### 🥰 需求描述

现在只能通过OpenAIAPIkey的方式来处理知识库中的文档，能否增加对Ollama中Embedding模型的支持

### 🧐 解决方案

Ollama中Embedding模型的支持

**Comment by SpeedupMaster** [comment]
#4370

**Comment by arvinxx** [comment]
重复 https://github.com/lobehub/lobe-chat/issues/3785
