### ISSUE TITLE
[Request] 侧边栏收起后显示小图标，以及不能鼠标拖动对话框滑块

### ISSUE THREAD

**Issue by Ruler27** [lobehub/lobe-chat#444]
### 🥰 需求描述 | Feature Description

1. 现在侧边栏收起后，助手栏会完全隐藏，我在非宽屏设备上用的时候会全部展开会让对话框变得很窄，收起来以后却不能快速选择别的助手了。
![image](https://github.com/lobehub/lobe-chat/assets/9345171/b4701b71-f16f-4c7d-a0ba-2e26a2d8539d)
![image](https://github.com/lobehub/lobe-chat/assets/9345171/2748cba0-6b4a-4ab6-a5e0-7894483b6b27)

2. 不能鼠标拖动对话框滑块，鼠标放过去就显示收起侧边栏的按钮，把滑块隐藏了：
鼠标不在上面的时候是可以看到滑块的：
![image](https://github.com/lobehub/lobe-chat/assets/9345171/214aac3b-2288-4c48-b509-52ec5a210775)
收起按钮显示后，滑块隐藏了：
![image](https://github.com/lobehub/lobe-chat/assets/9345171/a1a883af-c1b0-465d-b22d-3ab33e85910c)

### 🧐 解决方案 | Proposed Solution

1. 像ytb这种，收起后只显示图标就行。
![image](https://github.com/lobehub/lobe-chat/assets/9345171/a6b0c6ce-423c-494f-a7f2-3d4892c7db49)
![image](https://github.com/lobehub/lobe-chat/assets/9345171/dfdecf48-b115-4433-8873-3c1dc1f308d4)

2. 不要隐藏滑块

**Comment by Se7enMuting** [comment]
`不能鼠标拖动对话框滑块` 这个真的很困扰我。内容一旦输入多了，往上翻阅查找就相当的难受，希望可以改善下

**Comment by arvinxx** [comment]
@Se7enMuting @Ruler27 对话框滑块已经修复，请看下现在是否 OK~

**Comment by Se7enMuting** [comment]
0.139.1吗？好像没有，鼠标移上去还是自动隐藏滑块。

**Comment by Se7enMuting** [comment]
更新了v0.141.1，问题确实解决了，改成 滑块条 是一直显示的策略了。
但这样 收起右侧边栏的按钮 和 滑块条 就重叠显示了，滑块短的时候可能会和这个按钮有冲突，美观上也有点打折，不知道还有没有什么更好的解决方案，先这样用吧

**Comment by arvinxx** [comment]
> 不知道还有没有什么更好的解决方案

可用性优先吧，美观度这块我们只要找到方案，肯定会优化。这个放心好了

**Comment by zhaobudaomingzi** [comment]
@arvinxx 请问怎么可以调出侧边栏？我找不到按钮，现在只能转到“发现”页面去手动找到助手了

![屏幕截图 2024-04-01 212520](https://github.com/lobehub/lobe-chat/assets/54617500/2010e59b-c7ad-4e8a-b7a1-ed82f794718b)

**Comment by arvinxx** [comment]
@zhaobudaomingzi over到左侧区域就可以看到折叠的把手

**Comment by zhaobudaomingzi** [comment]
> @zhaobudaomingzi over到左侧区域就可以看到折叠的把手

感谢，终于找到按钮了！
