### ISSUE TITLE
[Bug] 能否对整体性能进行一下优化

### ISSUE THREAD

**Issue by Mgrsc** [lobehub/lobe-chat#4440]
### 📦 部署环境

Docker

### 📌 软件版本

v1.22.9

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

输出太多会卡，设置增删模型也卡，而且用久了内存爆涨
![image](https://github.com/user-attachments/assets/7309da33-b9a5-4247-bba2-93c86b6546af)

### 🚦 期望结果

流畅运行

**Comment by arvinxx** [comment]
> 输出太多会卡

这个有个录屏或者具体示例吗？

> 设置增删模型也卡

这个后续会优化

> 而且用久了内存爆涨

你的上下文是不是很大？如果上下文很大的话，tokenizer 会占用较高的内存的

**Comment by Mgrsc** [comment]
> > 输出太多会卡
> 
> 这个有个录屏或者具体示例吗？
> 
> > 设置增删模型也卡
> 
> 这个后续会优化
> 
> > 而且用久了内存爆涨
> 
> 你的上下文是不是很大？如果上下文很大的话，tokenizer 会占用较高的内存的

上下文只有8k
![image](https://github.com/user-attachments/assets/20d520c0-b40f-4cac-a5df-0cdf62dfcd24)

**Comment by Mgrsc** [comment]
> 只有 8k 的话那的确是有问题了…



> 只有 8k 的话那的确是有问题了…

是的麻烦排查下，是数据库版本
