### ISSUE TITLE
[Request] 能否将start文档到使用手册的渲染实现自动化

### ISSUE THREAD

**Issue by LYH-RAIN** [lobehub/lobe-chat#4443]
### 🥰 需求描述

我们提了关于使用手册-私有化部署的PR：（https://github.com/lobehub/lobe-chat/pull/4367 ）

但是我发现这个界面没有自动渲染出新的界面（https://lobehub.com/zh/docs/self-hosting/start）
为了保证文档的时效性，是否考虑新增自动化部署。

### 🧐 解决方案

比如GitHub Actions。

**Comment by LYH-RAIN** [comment]
@arvinxx 麻烦帮忙解答下。

**Comment by arvinxx** [comment]
@LYH-RAIN 是具体哪块没有渲染出来？

**Comment by LYH-RAIN** [comment]
> @LYH-RAIN 是具体哪块没有渲染出来？
我注意到start文档里都是通过这个组件渲染其下的快速部署平台
<PlatformCards urlPrefix={'platform'} />
而目前阿里云的快速部署子文档未能被渲染。
https://lobehub.com/zh/docs/self-hosting/start
![image](https://github.com/user-attachments/assets/5ab73c6c-679b-44f9-a0bf-07036baa0800)

**Comment by LYH-RAIN** [comment]
@arvinxx 麻烦再帮忙看下，我们是参考repo cloud的写法，但是现在快速部署按钮没有渲染出来。
![image](https://github.com/user-attachments/assets/07764408-94b2-4070-9e60-37d5a2a9b7c5)
而我们的图片外链是可以正常访问的：https://service-info-public.oss-cn-hangzhou.aliyuncs.com/computenest-en.svg
感谢！

**Comment by arvinxx** [comment]
> > @LYH-RAIN 是具体哪块没有渲染出来？
> > 我注意到start文档里都是通过这个组件渲染其下的快速部署平台
> > <PlatformCards urlPrefix={'platform'} />
> > 而目前阿里云的快速部署子文档未能被渲染。
> > https://lobehub.com/zh/docs/self-hosting/start
> > ![image](https://private-user-images.githubusercontent.com/51704305/380943799-5ab73c6c-679b-44f9-a0bf-07036baa0800.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjA1OTcsIm5iZiI6MTczMDI2MDI5NywicGF0aCI6Ii81MTcwNDMwNS8zODA5NDM3OTktNWFiNzNjNmMtNjc5Yi00NGY5LWEwYmYtMDcwMzZiYWEwODAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAzNTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYWI5M2Q2NWUwZGY5YjQwYmY3MTFjOTE5NDc5YTVlMTI4NzQwZDVlY2I2NjljZjZhZDdkYWZmZDM2NjIwNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XvNUK0I_4oH-cXJatjhKbMeP1GwXMMMqtNxVwtk12Lo)

这个我昨天看了下是应该没法自动化，这部分展示的内容是写死在官网项目里的。昨天我们更新了下，现在应该可以看到了

**Comment by arvinxx** [comment]
> 而我们的图片外链是可以正常访问的：https://service-info-public.oss-cn-hangzhou.aliyuncs.com/computenest-en.svg

这个有没有加跨域访问限制呢？

**Comment by LYH-RAIN** [comment]
我们加了OSS防盗链白名单，现在可以了。thk
