### ISSUE TITLE
[Request] Why is the DEFAULT_MODEL parameter not open for configuration?

### ISSUE THREAD

**Issue by SuperDuckGOGOGO** [lobehub/lobe-chat#4453]
### 🥰 Feature Description

Open configuration
![123123](https://github.com/user-attachments/assets/8e0c39e8-6841-45a8-b6ec-1c1dd25fcced)

### 🧐 Proposed Solution

Open configuration

**Comment by SuperDuckGOGOGO** [comment]
@arvinxx 

> try with `DEFAULT_AGENT_CONFIG` : #913

Setting DEFAULT_AGENT_CONFIG: model=x; does not change the settings in system-agent.

![11111111](https://github.com/user-attachments/assets/9b7ff777-8936-4cd2-ae6b-7449ee296ebc)

![2222](https://github.com/user-attachments/assets/a9853397-9c24-4b96-8e85-ad5a87ba75cf)

**Comment by arvinxx** [comment]
use system agent env

```
SYSTEM_AGENT=topic=azure/gpt-4o-mini,translation=azure/gpt-4o-mini,agentMeta=azure/gpt-4o-mini,queryRewrite=azure/gpt-4o-mini
```

**Comment by QwertyJack** [comment]
> use system agent env
> 
> ```
> SYSTEM_AGENT=topic=azure/gpt-4o-mini,translation=azure/gpt-4o-mini,agentMeta=azure/gpt-4o-mini,queryRewrite=azure/gpt-4o-mini
> ```

This works perfectly! By the way, where can I find it in the documentation?
