### ISSUE TITLE
[Request] 是否可以提供自定義 bedrock embedding model 的範例

### ISSUE THREAD

**Issue by harrypd** [lobehub/lobe-chat#4457]
### 🥰 需求描述

目前正在測試 lobechat knowledge base ,  有看到 #4208 的說明已經有支援 bedrock 的 embedding Model 了
我嘗試使用提供的方法 DEFAULT_EMBEDDING_MODEL=bedrock/amazon.titan-embed-text-v2:0 來啟動 chat 映像
但是我發現當我在對話框中打勾上傳去知識庫內容的時候,  與 chat 對話他依舊會去找 openai 造成錯誤, 
不曉得是不是我理解的環境變數有所錯誤

 

### 🧐 解决方案

是否可以提供關於 aws bedrock 自定義 embedding model 的方式,  謝謝

**Comment by SpeedupMaster** [comment]
等这个合并吧#4370

**Comment by arvinxx** [comment]
duplicate of #3785
