### ISSUE TITLE
[Request] 新增 AWS 模型 `anthropic.claude-3-5-sonnet-20241022-v2:0`

### ISSUE THREAD

**Issue by AnoyiX** [lobehub/lobe-chat#4458]
### 🥰 需求描述

添加 AWS 中对这个模型  `anthropic.claude-3-5-sonnet-20241022-v2:0`  的支持

### 🧐 解决方案

AWS 最新的模型列表详见文档：https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids.html

**Comment by eagleye1115** [comment]
v1.22.20 中已经支持[anthropic.claude-3-5-sonnet-20241022-v2:0
但是现在有2个问题：
1. DEFAULT_AGENT_CONFIG='model=anthropic.claude-3-5-sonnet-20241022-v2:0' 设置好以后, 默认可用. 但是模型列表里面的sonnet3.5 还是20240620版本, 列表里面没有20241022的版本可以选择，只要选择了其他模型就再也无法回到20241022版本了
2. 不支持函数调用, 插件不可用
![lobechat](https://github.com/user-attachments/assets/9987c144-5303-4bc6-b97e-087c55d68c10)

**Comment by AnoyiX** [comment]
等官方更新支持吧

**Comment by arvinxx** [comment]
已在 https://github.com/lobehub/lobe-chat/pull/4468 支持

**Comment by gemnioo** [comment]
last version still have aws bedrock claude 3.5 v2 request error.  searched other repositories have same issues

Invocation of model ID anthropic.claude-3-5-sonnet-20241022-v2:0 with on-demand throughput isn’t supported

https://github.com/danny-avila/LibreChat/discussions/4571
https://github.com/cline/cline/issues/689

even set the region in us-west-2 (cross-region inference support in us-east-1). pls modify the region number in the endpoint

```
To be able to use the latest Sonnet 3.5 from the us-east-1 region, the model inference profile id is 

'us.anthropic.claude-3-5-sonnet-20241022-v2:0', 

it will route the inference to the region where the model is hosted.
https://github.com/danny-avila/LibreChat/discussions/4571#discussioncomment-11114851

```

**Comment by CXwudi** [comment]
The workaround for using the model with `us.` prefix ID is just to create a new custom model with `us.anthropic.claude-3-5-sonnet-20241022-v2:0`.

![image](https://github.com/user-attachments/assets/d0f1b762-0341-4fff-a9d0-78d23912ef04)
![image](https://github.com/user-attachments/assets/fd6435e6-de86-455a-8e84-0d0f8cba42ce)

**Comment by gemnioo** [comment]
> create a new custom model

Hi, In docker deploy latest version. where is the path to create a new custom model  shows in pic1 ?

**Comment by CXwudi** [comment]
In the model list, simply just type ur custom model ID and then LobeChat will create the custom entry for you. Then you can open the setting shown in pic 1

**Comment by gemnioo** [comment]
> In the model list, simply just type ur custom model ID and then LobeChat will create the custom entry for you. Then you can open the setting shown in pic 1

thanks bro. it works
