### ISSUE TITLE
[Bug]  怎么消除烦人的安装提示

### ISSUE THREAD

**Issue by ArcCal** [lobehub/lobe-chat#4460]
### 📦 部署环境

Docker

### 📌 软件版本

 lobe-chat

### 💻 系统环境

macOS

### 🌐 浏览器

Firefox

### 🐛 问题描述

使用docker，参照官方文档部署以后，使用浏览器打开，右上角总是收到烦人的安装提示，关掉后下次还会出现

### 📷 复现步骤

不确定这是feature还是bug，几次部署都能重现

### 🚦 期望结果

希望可以永久性的关掉

**Comment by ArcCal** [comment]
![WX20241023-202714@2x](https://github.com/user-attachments/assets/296f024d-a60c-4fae-b8ac-7136f784d997)
![WX20241023-202547@2x](https://github.com/user-attachments/assets/1bce4015-8cba-40c4-951a-5f8ecbe85c07)
附件为恼人的截图

**Comment by LovelyGuYiMeng** [comment]
你装了就不会出现了

**Comment by ArcCal** [comment]
> 你装了就不会出现了

点安装没有任何反应

**Comment by SpeedupMaster** [comment]
火狐浏览器好像确实安装不了

**Comment by hermeneuticlens** [comment]
The issue still persists. Would appreciate an option in setting or an env variable to turn off the pwa popup.

**Comment by whc2001** [comment]
I think that's by design. You can try to use any ad blocker to block element `###pwa-install`
