### ISSUE TITLE
[Bug] 使用第三方API代理后claude模型回复为空，没有任何报错

### ISSUE THREAD

**Issue by hlc1209** [lobehub/lobe-chat#4466]
### 📦 部署环境

Docker

### 📌 软件版本

v1.22.6

### 💻 系统环境

Windows, macOS

### 🌐 浏览器

Chrome, Edge

### 🐛 问题描述

使用holdai的API代理后后claude模型回复为空，也没有任何报错。连通性测试通过。
![image](https://github.com/user-attachments/assets/83664490-5b0f-4316-a758-bacfe3ae04c5)

同款API代理下，openai模型使用则一切正常
同款API代理下，在chatgpt web中使用claude模型则一切正常

### 📷 复现步骤

API代理地址：https://api.holdai.top/

### 🚦 期望结果

我估计这需要第三方配合调试。但是我无法找到debug模式
是否有一个debug开关让我能看到API调用的情况？

**Comment by hlc1209** [comment]
我按照bot说的设置DEBUG_ANTHROPIC_CHAT_COMPLETION to '1'
只得到以下信息
![image](https://github.com/user-attachments/assets/ad1f50d5-7958-4c9e-b66c-2eacfe2d25ea)

**Comment by SpeedupMaster** [comment]
![Snipaste_2024-10-24_08-52-02](https://github.com/user-attachments/assets/a4ad4262-72b3-4765-90bc-4e148ec60157)
要在Openai这个渠道里调用，很多第三方代理都有这个问题，用的one-api做的接口转发

**Comment by arvinxx** [comment]
三方渠道放openai 那里

**Comment by hlc1209** [comment]
6的。希望在doc中能有所说明

**Comment by hlc1209** [comment]
> 三方渠道放openai 那里

随之而来有一个问题想请教，如果在openai里有一个第三方的claude-3-5-sonnet-20241022
官方API里也有一个claude-3-5-sonnet-20241022

如果要设置docker环境变量里的DEFAULT_AGENT_CONFIG为第三方API，应该怎么写？
model=claude-3-5-sonnet-20241022，使用的是哪一个API？

**Comment by SpeedupMaster** [comment]
> > 三方渠道放openai 那里
> 
> 随之而来有一个问题想请教，如果在openai里有一个第三方的claude-3-5-sonnet-20241022 官方API里也有一个claude-3-5-sonnet-20241022
> 
> 如果要设置docker环境变量里的DEFAULT_AGENT_CONFIG为第三方API，应该怎么写？ model=claude-3-5-sonnet-20241022，使用的是哪一个API？

![image](https://github.com/user-attachments/assets/bf47184e-755f-40e7-9c9b-d7b27c024425)
试试这样

**Comment by hlc1209** [comment]
> > > 三方渠道放openai 那里
> > 
> > 
> > 随之而来有一个问题想请教，如果在openai里有一个第三方的claude-3-5-sonnet-20241022 官方API里也有一个claude-3-5-sonnet-20241022
> > 如果要设置docker环境变量里的DEFAULT_AGENT_CONFIG为第三方API，应该怎么写？ model=claude-3-5-sonnet-20241022，使用的是哪一个API？
> 
> ![image](https://private-user-images.githubusercontent.com/130642629/379976610-bf47184e-755f-40e7-9c9b-d7b27c024425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjMzMjgsIm5iZiI6MTcyOTgyMzAyOCwicGF0aCI6Ii8xMzA2NDI2MjkvMzc5OTc2NjEwLWJmNDcxODRlLTc1NWYtNDBlNy05YzliLWQ3YjI3YzAyNDQyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwMjIzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2E3OWI2NWZmNGNjMzA2OGJiMTljZGUwZGFjZTkyZDc2MGQ5YjhjZWY2ZGJiNTRmYmQ2NzQ0ZmY2ZDhkYzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g7Rieu0No6O5J9xsYo4hNhoWM-bo8WB9tqE8hwVBg6Y) 试试这样

So nice. Thanks
