### ISSUE TITLE
[Bug] latex公式显示错误（重复显示）

### ISSUE THREAD

**Issue by Sam5440** [lobehub/lobe-chat#4469]
### 📦 部署环境

Vercel

### 📌 软件版本

v1.8.0

### 💻 系统环境

macOS

### 🌐 浏览器

Edge

### 🐛 问题描述

![image](https://github.com/user-attachments/assets/e7db4225-1040-4abc-ad43-8b77bf20534f)
![image](https://github.com/user-attachments/assets/ef2d1967-f83f-4adb-a959-31e93ec6bed2)

**Comment by Sam5440** [comment]
最新版同样存在该问题

**Comment by arvinxx** [comment]
你用了 `.top` 域名的关系

**Comment by DEAN-Cherry** [comment]
> 你用了 `.top` 域名的关系

为什么用.top 会导致这个问题，怎么修复？
