### ISSUE TITLE
使用dall e3 出现这个报错

### ISSUE THREAD

**Issue by yitao2020** [lobehub/lobe-chat#4470]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/usage/start.zh-CN.mdx

### 🐛 Feedback

{
  "error": {
    "message": "An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_kMEWqPM9YixkzhrJcxFGYnnK",
    "type": "invalid_request_error",
    "param": "messages.[46].role",
    "code": null
  },
  "endpoint": "https://api.openai.com/v1",
  "provider": "openai"
}

**Comment by arvinxx** [comment]
清空会话重试下
