### ISSUE TITLE
[Request] 讯飞星火支持SPARK_MODEL_LIST

### ISSUE THREAD

**Issue by SAnBlog** [lobehub/lobe-chat#4476]
### 🥰 需求描述

![image](https://github.com/user-attachments/assets/5ae3ad37-c318-4911-aa8c-4728d1ff7a2f)
科大讯飞在全球1024开发者节上展示了讯飞星火4.0Turbo大模型，超越了之前版本和GPT-4Turbo，在数学和编程能力上表现出色，效率提升50%。

同时发现Spark Lite报错
![image](https://github.com/user-attachments/assets/88a24c7c-aa1a-4dce-a9f1-8b1e5a5a4559)

Spark的命名规则是不是存在问题?官网上没有存在3.5 Max的命名
![image](https://github.com/user-attachments/assets/91834c15-3f2b-447e-9f2b-cc4939faf01a)

### 🧐 解决方案

1.增加SPARK_MODEL_LIST支持
2.Spark Lite报错问题
3.统一命名

**Comment by hezhijie0327** [comment]
spark lite 那边详细错误截个图看看，复现不出来
![image](https://github.com/user-attachments/assets/54111d76-f2ef-4c39-ba3c-276b2100b8ce)

然后 Spark 每个模型的 token 都得单独计算的，最好也可以去 console 看看，是不是没领取
https://console.xfyun.cn/services/cbm
![image](https://github.com/user-attachments/assets/4593a362-1750-4c49-9758-586c9eaabfec)

**Comment by SAnBlog** [comment]
> spark lite 那边详细错误截个图看看，复现不出来 ![image](https://private-user-images.githubusercontent.com/58100052/380106727-54111d76-f2ef-4c39-ba3c-276b2100b8ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTA1MjcsIm5iZiI6MTcyOTg1MDIyNywicGF0aCI6Ii81ODEwMDA1Mi8zODAxMDY3MjctNTQxMTFkNzYtZjJlZi00YzM5LWJhM2MtMjc2YjIxMDBiOGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA5NTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YzE4NWRjMTFjYzMyMWZlYjE1NTQwMDkzZjU4N2I4ZWFjNWRlOWIzMmE0Y2FjM2ZkNTcwOGUyNmFjMTU0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mh-VAYfoT8HjP08clsiml19DB2PZg_hOUa3uVn9W9GE)
> 
> 然后 Spark 每个模型的 token 都得单独计算的，最好也可以去 console 看看，是不是没领取 https://console.xfyun.cn/services/cbm ![image](https://private-user-images.githubusercontent.com/58100052/380106905-4593a362-1750-4c49-9758-586c9eaabfec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTA1MjcsIm5iZiI6MTcyOTg1MDIyNywicGF0aCI6Ii81ODEwMDA1Mi8zODAxMDY5MDUtNDU5M2EzNjItMTc1MC00YzQ5LTk3NTgtNTg2YzllYWFiZmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA5NTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwN2UzOTk5NjI3ZmMwYTYxN2Y0ZTkzN2NjMDhiMmQ3YTMyNmZmNjQ2ODc0MTVlOTQ0NTFjNDc0ZDUxZTczZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1bWRLQdJmaS4GRDC63nyn0eeFgCDaYgGgAXctF03Zf0)

{
  "context": {
    "chunk": {
      "id": "cha000bf27f@dx192c31b97cab8f2532",
      "sid": "cha000bf27f@dx192c31b97cab8f2532",
      "code": 11200,
      "created": 1729850218,
      "message": "AppIdNoAuthError:(17:56:58.446) domain.general"
    },
    "error": {
      "name": "TypeError",
      "message": "Cannot read properties of undefined (reading '0')"
    }
  },
  "message": "chat response streaming chunk parse error, please contact your API Provider to fix it."
}

**Comment by SAnBlog** [comment]
> spark lite 那边详细错误截个图看看，复现不出来 ![image](https://private-user-images.githubusercontent.com/58100052/380106727-54111d76-f2ef-4c39-ba3c-276b2100b8ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTA1NjYsIm5iZiI6MTcyOTg1MDI2NiwicGF0aCI6Ii81ODEwMDA1Mi8zODAxMDY3MjctNTQxMTFkNzYtZjJlZi00YzM5LWJhM2MtMjc2YjIxMDBiOGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA5NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNWNiYzVjYzI4YzU1OWQxZjM5ODE2YWUwNjRlMzFhODFjZjU4OTM1MjQ2NzcyYmVjNTNkOWU2ZDA0YTlkMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iw6Ptw7tw-85jUP2JsdtqdGUGf9Yp61__u05KKsff-k)
> 
> 然后 Spark 每个模型的 token 都得单独计算的，最好也可以去 console 看看，是不是没领取 https://console.xfyun.cn/services/cbm ![image](https://private-user-images.githubusercontent.com/58100052/380106905-4593a362-1750-4c49-9758-586c9eaabfec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTA1NjYsIm5iZiI6MTcyOTg1MDI2NiwicGF0aCI6Ii81ODEwMDA1Mi8zODAxMDY5MDUtNDU5M2EzNjItMTc1MC00YzQ5LTk3NTgtNTg2YzllYWFiZmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA5NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZmQxMDE0MmI0Yjg1MGMyYTg0NjE3MzJmZjRhYjg3NmM3MDM1MGU0Y2YxNzU1ZTkwYWE2OTI1MjE4ODY3NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wsCbY-Ac8YmkOboDfJblYOhLGIxetc-hxX9uLjeSWaM)

他的模型我都领取了,有个问题就是每个模型的APIPassword都不同,相同的是key,但是我输入key发现无法使用,只能使用APIPassword,目前使用的是4.0Utral的APIPassword,会不会是这个问题导致的

**Comment by hezhijie0327** [comment]
大致知道了问题了，官网模型endpoint改了，老实例应该做了兼容 `general` 还能用，等下补个 PR 
![image](https://github.com/user-attachments/assets/edfbf294-9bca-4fcc-bd91-a197fbe8f6f7)

你试下添加一个 `lite` 模型

**Comment by SAnBlog** [comment]
> 大致知道了问题了，官网模型endpoint改了，老实例应该做了兼容 `general` 还能用，等下补个 PR ![image](https://private-user-images.githubusercontent.com/58100052/380108962-edfbf294-9bca-4fcc-bd91-a197fbe8f6f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTA2OTQsIm5iZiI6MTcyOTg1MDM5NCwicGF0aCI6Ii81ODEwMDA1Mi8zODAxMDg5NjItZWRmYmYyOTQtOWJjYS00ZmNjLWJkOTEtYTE5N2ZiZThmNmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA5NTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ODc5OWQ1ZjRhZjIyOTM0NDYyYmQ4MWI4YTk0Yjg4YWQyNjI2YTVlOGFhOGRkZTU4N2YwNzU0NzUxNDY1YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._J7W3Mq2fdGL-JZ_0KP6UJYPa0pdFfF-cjAvdJcX2Q0)
> 
> 你试下添加一个 `lite` 模型

好的

**Comment by hezhijie0327** [comment]
这个之前做适配的时候试过，其实都能用，任意一个 APIPassword 就行
