### ISSUE TITLE
[Request] Mobile 侧支持 TextArea 输入框

### ISSUE THREAD

**Issue by imoyy** [lobehub/lobe-chat#448]
### 🧐 问题描述 | Proposed Solution

请问这个操作是尚未实现还是逻辑与其它软件有所不同，我已尝试ctrl+return shift+return alt+return win+return 均不可实现。如果是尚未实现输入框换行操作，希望能在后续更新中添加此功能。感谢！

**Comment by imoyy** [comment]
我发现是只有在窗口长度达到一定范围时才能换行发送，输入会出现下图的提示
![image](https://github.com/lobehub/lobe-chat/assets/115197762/c12f1d9e-4a80-4bbf-a2da-341bc1291662)
而类似于手机网页则不能进行换行发送
![image](https://github.com/lobehub/lobe-chat/assets/115197762/f67418ff-2628-4a83-be39-c38a6eabd39c)

**Comment by canisminor1990** [comment]
emm, 目前 mobile 布局用的是 `Input` 而不是 `TextArea` 后续有空可以优化成支持动态调整大小的 `TextArea`
