### ISSUE TITLE
[Bug] GOOGLE_MODEL_LIST似乎有点问题

### ISSUE THREAD

**Issue by SpeedupMaster** [lobehub/lobe-chat#4485]
### 📦 部署环境

Docker

### 📌 软件版本

v1.24.0

### 💻 系统环境

Windows

### 🌐 浏览器

Firefox

### 🐛 问题描述

`GOOGLE_MODEL_LIST=-all,+gemini-1.5-pro-latest,+gemini-1.5-flash-latest,+gemini-1.5-flash-8b=Gemini 1.5 Flash 8B<1008192:vision:fc>`
env中设置了GOOGLE_MODEL_LIST，但是新增加的`gemini-1.5-flash-8b`这个模型没有出现，而且所有其他模型仍然在模型列表中。`-all`似乎没有生效
![图片](https://github.com/user-attachments/assets/e46559b2-49fe-4557-8c19-9b9a36b5dcce)

### 🚦 期望结果

![图片](https://github.com/user-attachments/assets/71068553-3502-4a75-a688-19fb9daf3bce)
删除模型列表中的其他模型，只显示MODEL_LIST中设置的模型

**Comment by hezhijie0327** [comment]
`-all` 不会移除列表只会禁用模型
![image](https://github.com/user-attachments/assets/e68f7d01-6eeb-4423-88e4-c319d7e8365b)
```
GOOGLE_MODEL_LIST='-all,+gemini-1.5-pro-latest,+gemini-1.5-flash-latest,+gemini-1.5-flash-8b=Gemini 1.5 Flash 8B<1008192:vision:fc>'
```
![image](https://github.com/user-attachments/assets/6778e711-529a-47b5-bbe3-1fa0e55a2297)

---

但是确实模型选择有问题 `HUGGINGFACE_MODEL_LIST='-all,+gemini-1.5-flash-latest,+gemini-1.5-pro-latest'`
没配置具体信息，也会从其他地方做模型信息匹配
![image](https://github.com/user-attachments/assets/c27f5690-6f17-44f1-9a42-69c24745f3f9)

过会儿回退几个版本测试看看

**Comment by SpeedupMaster** [comment]
> `-all` 不会移除列表只会禁用模型 ![image](https://private-user-images.githubusercontent.com/58100052/380340254-e68f7d01-6eeb-4423-88e4-c319d7e8365b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MDQwODYsIm5iZiI6MTcyOTkwMzc4NiwicGF0aCI6Ii81ODEwMDA1Mi8zODAzNDAyNTQtZTY4ZjdkMDEtNmVlYi00NDIzLTg4ZTQtYzMxOWQ3ZTgzNjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAwNDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNmI3M2ViYzQzYjZkZTRhYjNlMjMzOGUzYjBiYWRkMzlmOWIyNGIxMDI1ZjdlZjg0YTBlOWQ4YzM5NzAwZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4e4Vo8DlRFggSsN1JD-y60kQuYUxpSNRCiQSHL3O3RU)
> 
> ```
> GOOGLE_MODEL_LIST='-all,+gemini-1.5-pro-latest,+gemini-1.5-flash-latest,+gemini-1.5-flash-8b=Gemini 1.5 Flash 8B<1008192:vision:fc>'
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/58100052/380339846-6778e711-529a-47b5-bbe3-1fa0e55a2297.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MDQwODYsIm5iZiI6MTcyOTkwMzc4NiwicGF0aCI6Ii81ODEwMDA1Mi8zODAzMzk4NDYtNjc3OGU3MTEtNTI5YS00N2I1LWJiZTMtMWZhMGU1NWEyMjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAwNDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNGQ3MzViODkzMDFiMTUxYWQ5ZjI1Nzk4YWUxMDQ0YzhhNGQyYjE1ZTllNzc4NzRkNGJjZmZlZjE2NjAyNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LRKlt8ovm_TUQClrhByXsEz01BcSiB-3dkm1-D4NHq4)
> 
> 但是确实模型选择有问题 `HUGGINGFACE_MODEL_LIST='-all,+gemini-1.5-flash-latest,+gemini-1.5-pro-latest'` 没配置具体信息，也会从其他地方做模型信息匹配 ![image](https://private-user-images.githubusercontent.com/58100052/380338561-c27f5690-6f17-44f1-9a42-69c24745f3f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MDQwODYsIm5iZiI6MTcyOTkwMzc4NiwicGF0aCI6Ii81ODEwMDA1Mi8zODAzMzg1NjEtYzI3ZjU2OTAtNmYxNy00NGYxLTlhNDItNjljMjQ3NDVmM2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAwNDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYjI3YjJjMTU5MjQ5ODllZGQzYzZhMGQ3ZjM2ZGJiM2Y4NmU4ZGMzOGVjNDQ5YjY5M2NiZWVjYzZkZWUwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sc7J3YVzIgjCha4AEbTjLchYVMF-cwc6TWcrPebcOqI)
> 
> 过会儿回退几个版本测试看看

好的，谢谢
![image](https://github.com/user-attachments/assets/5a9c75f7-1404-4f27-895f-c297e00246db)
openai和openrouter这两个可以用`MODEL_LIST='-all,+gemini-1.5-flash-latest,+gemini-1.5-pro-latest'`来实现模型列表里只显示MODEL_LIST中设置的模型

**Comment by arvinxx** [comment]
@hezhijie0327 想起来有个另外的地方要加才能实现-all 的效果

**Comment by hezhijie0327** [comment]
过会儿我补一个 PR

**Comment by LovelyGuYiMeng** [comment]
> 过会儿我补一个 PR

顺带把google的flash 8b改一下，日期去掉

另外googleprovider设置不管开没开LLM_VISION_IMAGE_USE_BASE64都会强制转base64
那么同理商汤的识图可不可以设置强制链接模式？
