### ISSUE TITLE
[Bug] 自定义embedding模型为智谱清言，但是依旧无法进行向量化

### ISSUE THREAD

**Issue by CCMAYNOTXX** [lobehub/lobe-chat#4486]
### 📦 Environment

Docker

### 📌 Version

1.23,0

### 💻 Operating System

Other Linux

### 🌐 Browser

Edge

### 🐛 Bug Description

由于deepbricks的API不支持embedding，我按照issue方法使用智谱清言模型，但是依旧无法进行向量化，openrouter里也没有可用的embedding模型
![微信图片编辑_20241025232255](https://github.com/user-attachments/assets/a8624052-03f2-462e-bbb2-6363bed1e5a3)
![微信图片_20241025232754](https://github.com/user-attachments/assets/b2816c73-8c2e-434c-8fc0-95b22b65bfe6)

### 📷 Recurrence Steps

centos,docker部署

### 🚦 Expected Behavior

请求一个可以正常使用知识库的方法，或者其他更靠谱的api提供商

**Comment by SpeedupMaster** [comment]
等这个 #4370 PR吧，API 我现在也用的是这两家。embedding API我用的[头顶冒火](https://burn.hair/)的

**Comment by LovelyGuYiMeng** [comment]
目前没有自定义embedding模型的方式，issues中的方法是不正确的
