### ISSUE TITLE
[Bug] Anthropic AI 配置 API 代理地址出错

### ISSUE THREAD

**Issue by Oniokey** [lobehub/lobe-chat#4489]
### 📦 部署环境

Docker

### 📌 软件版本

v1.24.1

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

在环境变量下配置 Anthropic AI 的 API 代理地址为`https://api.example.com` 和 `https://api.example/v1` 时，系统在发起请求时都会试图访问配置地址 + `/v1/messages`，这在某些情况下时不符合预期的。

### 📷 复现步骤

配置 Anthropic AI 的 API 代理地址为`https://api.example.com` 和 `https://api.example/v1`

### 🚦 期望结果

如果配置了一个含有 `/v1` 或者 `/v1/chat/completion` 这种含有 `/` 的 API 代理地址时，系统直接请求代理地址，而不再增加后缀

### 📝 补充信息

这在很多 API 代理或者聚合平台上是非常常见的，他们会提供一个 OpenAI 的兼容模式，而不是为每个模型单独适配

**Comment by SpeedupMaster** [comment]
第三方API代理的直接放到opanai那里面就好了

**Comment by arvinxx** [comment]
既然提供了 OpenAI 兼容模式，那就应该把代理地址填到 OpenAI 的provider 配置项下。你把 OpenAI 的转发地址填到 Anthropic 里自然就没法用。
