### ISSUE TITLE
[Bug] Can’t change the assistant’s avatar in ios safari

### ISSUE THREAD

**Issue by skyf0cker** [lobehub/lobe-chat#449]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

I put the lobe-chat on the main screen through safari. When i create a new assistant, i want to click the avatar to change a new one like i can do on my macos. But it did nothing after i clicked it.

### 🚦 期望结果 | Expected Behavior

when i click the avatar button, it should pop up a emoji selector and i can choose which emoji i want to use as my assistant’s avatar

### 📷 复现步骤 | Recurrence Steps

1. put the lobe-chat in the main screen through safari.(idk if this is a necessary step)
2. click create button in assistant’s list page
3. click avatar button

### 📝 补充信息 | Additional Information

Anyway Lobe-chat is a great open-source chatgpt client, thanks for your guys to create a such amazing product.

**Comment by skyf0cker** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/32331521/672f72fd-7776-4f37-bec8-6a7f3f19fcfe)

**Comment by arvinxx** [comment]
@skyf0cker please check this issue with latest version again. I think it's fixed with the latest version.

**Comment by skyf0cker** [comment]
Yep, it works. 🔥
