### ISSUE TITLE
[Bug] v1.25.1版本Stepfun模型ID冲突

### ISSUE THREAD

**Issue by SAnBlog** [lobehub/lobe-chat#4511]
### 📦 Environment

Docker

### 📌 Version

v1.25.1

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/d81e013e-7dff-4e1d-b11b-004f51e8cdf0)

跟minimax模型冲突,显示错误并无法在前台选择

**Comment by arvinxx** [comment]
重置下试试

**Comment by SAnBlog** [comment]
> 重置下试试

不行，重置之后列表只剩下6.5s这个模型

**Comment by arvinxx** [comment]
这个在官方演示站上可以复现吗？你有没有做什么额外配置

**Comment by SAnBlog** [comment]
model_list配置错误导致
