### ISSUE TITLE
[Request] 支持Ollama的多模态

### ISSUE THREAD

**Issue by DaLiWan666** [lobehub/lobe-chat#4513]
### 🥰 需求描述

Ollama内有一些模型支持多模态能力，如minicpm模型，可以输入图片，不知道能否支持

### 🧐 解决方案

支持ollama多模态

**Comment by arvinxx** [comment]
支持的

**Comment by DaLiWan666** [comment]
> 支持的

但是我选项ollama里面的多模态模型后，图片上传选项为灰色，显示模型不支持图片分析。模型minicpm和llava均为灰色

**Comment by DaLiWan666** [comment]
> 支持的

抱歉，查询文档得知可以操作，十分抱歉打扰了

**Comment by m0eak** [comment]
> > 支持的
> 
> 抱歉，查询文档得知可以操作，十分抱歉打扰了

文档哪里，我找不到。。

**Comment by dellnoantechnp** [comment]
要手动配置   
参考：https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/advanced/model-list.zh-CN.mdx
