### ISSUE TITLE
[Bug] HUGGINGFACE获得的模型列表不全

### ISSUE THREAD

**Issue by SuperDuckGOGOGO** [lobehub/lobe-chat#4529]
### 📦 部署环境

Docker

### 📌 软件版本

1.26.4

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

docker部署
配置好HUGGINGFACE_API_KEY
没有配置HUGGINGFACE_MODEL_LIST
在列表中只能显示一个模型
但实际上HUGGINGFACE上是有非常多模型可以免费试用的
![test](https://github.com/user-attachments/assets/ef3d4bdd-ae55-4c0f-9235-a372b32cbcce)

这里只显示了一个模型
![test2](https://github.com/user-attachments/assets/7d02c692-29c9-46b0-8a0f-6807cfe12954)

### 🚦 期望结果

应该显示所有可用模型

**Comment by SpeedupMaster** [comment]
感觉按自己需求配置`HUGGINGFACE_MODEL_LIST`要好点吧，毕竟模型太多了

**Comment by SuperDuckGOGOGO** [comment]
> 感觉按自己需求配置`HUGGINGFACE_MODEL_LIST`要好点吧，毕竟模型太多了

手动配置HUGGINGFACE_MODEL_LIST确实可以试用
但是这里有两个问题
1：XXXX_API_KEY参数的行为并不统一（其他供应商默认会展示所有可用的模型，而HUGGINGFACE的不会）
2：HUGGINGFACE的MODEL没有能力显示，如下图（或者可以配置，只是我没找到在哪？）
![test3](https://github.com/user-attachments/assets/b678e7e4-3f66-476a-9021-d0945743091a)

**Comment by SuperDuckGOGOGO** [comment]
我找到了代码位置，确实是只显示一个模型。
那么现在的问题是，如何修改模型的能力显示icon。。。。
![test4](https://github.com/user-attachments/assets/8805e244-91e6-4f11-be94-5c1528c6f07d)

**Comment by SpeedupMaster** [comment]
> 我找到了代码位置，确实是只显示一个模型。 那么现在的问题是，如何修改模型的能力显示icon。。。。 ![test4](https://private-user-images.githubusercontent.com/165230683/380959609-8805e244-91e6-4f11-be94-5c1528c6f07d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNzI1ODQsIm5iZiI6MTczMDE3MjI4NCwicGF0aCI6Ii8xNjUyMzA2ODMvMzgwOTU5NjA5LTg4MDVlMjQ0LTkxZTYtNGYxMS1iZTk0LTVjMTUyOGM2ZjA3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwMzI0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDU5MWM2ODM1ODllNjQzMDc0NzI4NDEyMjVjMDE4N2JmZjI1MmY1MTYwZThiNDY5OTE1MGExMGJmNjhmZGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jw942RWRuc_jaVsHIFJL-ZSOUJ-WUEP8CqhS7FeTz-g)

https://lobehub.com/zh/docs/self-hosting/advanced/model-list

**Comment by SuperDuckGOGOGO** [comment]
找到了配置方法
https://lobehub.com/zh/docs/self-hosting/advanced/model-list
问题可以关闭了
