### ISSUE TITLE
[Request] dall-e3 支持

### ISSUE THREAD

**Issue by EnochYe** [lobehub/lobe-chat#453]
### 🥰 需求描述 | Feature Description

能否增加对dall-e3 的支持？

### 🧐 解决方案 | Proposed Solution

无

**Comment by leochen-g** [comment]
+1

**Comment by arvinxx** [comment]
Refs to: https://github.com/lobehub/lobe-chat/discussions/460

**Comment by hbs1313** [comment]
+1

**Comment by CXK3023** [comment]
+1😀😀😀

**Comment by arvinxx** [comment]
> 希望增加dell-a，还有对图像的支持。

dall-a 是什么？你说的图像支持是识别图片么？识别图片已经支持了

**Comment by wusimpl** [comment]
we need DALL·E model which can generate images.

**Comment by XueshiQiao** [comment]
> > 希望增加dell-a，还有对图像的支持。
> 
> dall-a 是什么？你说的图像支持是识别图片么？识别图片已经支持了

是根据描述生成图片的。 OpenAI 和 Azure OpenAI 都支持了

**Comment by EnochYe** [comment]
邮件已收到，祝好！

**Comment by HeroadZ** [comment]
It would be amazing if dalle3 is supported!

**Comment by scutken** [comment]
+1

**Comment by Root-FTW** [comment]
+1

**Comment by jason-xiaobaiai** [comment]
+1
