### ISSUE TITLE
[Bug] GPT 4o上传图片失败，context length exceeded

### ISSUE THREAD

**Issue by sonnyding1** [lobehub/lobe-chat#4546]
### 📦 Environment

Official Preview

### 📌 Version

v1.26.11

### 💻 Operating System

macOS

### 🌐 Browser

Other

### 🐛 Bug Description

原来可以正常上传图片，现在不行了，可能是因为把图片作为byte stream直接上传到OpenAI API，而不是根据https://platform.openai.com/docs/guides/vision 的方法上传。我得到的error是context length exceeded，也就是说上传一张～170kb的图片直接让一个request超过了128k的context window。具体的log如下：

```json
{
  "error": {
    "message": "This model's maximum context length is 128000 tokens. However, your messages resulted in 174643 tokens. Please reduce the length of the messages.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  },
  "endpoint": "https://api.openai.com/v1",
  "provider": "openai"
}
```

请尽快修复，我尝试上传～40kb的图片，结果一条request就花了~$0.2，显然是把这40kb的图片算成request中的40k了。

**Comment by arvinxx** [comment]
图片是啥样的？最近没有改过这块吧
