### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by hbsky2015** [lobehub/lobe-chat#4549]
### 📦 Environment

Docker

### 📌 Version

v1.26.11

### 💻 Operating System

macOS, Ubuntu, Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

使用O1模型问题, O1使用 max_completion_tokens  ,原来模型是: max_tokens , 都好几个版本了都没有修复
{
  "error": {
    "message": "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.",
    "type": "invalid_request_error",
    "param": "max_tokens",
    "code": "unsupported_parameter"
  },
  "endpoint": "https://jc-gpt-swedencentral-inside-1.openai.azure.com",
  "provider": "azure"
}

### 📷 Recurrence Steps

使用O1模型问题, O1使用 max_completion_tokens  ,原来模型是: max_tokens , 都好几个版本了都没有修复
{
  "error": {
    "message": "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.",
    "type": "invalid_request_error",
    "param": "max_tokens",
    "code": "unsupported_parameter"
  },
  "endpoint": "https://jc-gpt-swedencentral-inside-1.openai.azure.com",
  "provider": "azure"
}

### 🚦 Expected Behavior

使用O1模型问题, O1使用 max_completion_tokens  ,原来模型是: max_tokens , 都好几个版本了都没有修复
{
  "error": {
    "message": "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.",
    "type": "invalid_request_error",
    "param": "max_tokens",
    "code": "unsupported_parameter"
  },
  "endpoint": "https://jc-gpt-swedencentral-inside-1.openai.azure.com",
  "provider": "azure"
}

### 📝 Additional Information

使用O1模型问题, O1使用 max_completion_tokens  ,原来模型是: max_tokens , 都好几个版本了都没有修复
{
  "error": {
    "message": "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.",
    "type": "invalid_request_error",
    "param": "max_tokens",
    "code": "unsupported_parameter"
  },
  "endpoint": "https://jc-gpt-swedencentral-inside-1.openai.azure.com",
  "provider": "azure"
}

**Comment by arvinxx** [comment]
重复 https://github.com/lobehub/lobe-chat/issues/4248
