### ISSUE TITLE
[Bug] 打开知识库生成的文件链接，内容存在编码问题

### ISSUE THREAD

**Issue by Luyi-2333** [lobehub/lobe-chat#4552]
### 📦 部署环境

Other

### 📌 软件版本

v1.26.11

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

当带有中文字符的文件以UTF-8编码格式上传到知识库后，通过链接打开的文件内容会出现乱码情况，而在LobeChat客户端打开或直接拖到浏览器上显示则不会出现这个情况。
如果把带有中文的文件转成ANSI编码则不会出现这种情况。
![Snipaste_2024-10-30_16-52-19](https://github.com/user-attachments/assets/19d8c761-78b2-437d-be7f-039f96267654)

### 🚦 期望结果

支持UTF-8编码文件正确解析。

**Comment by Luyi-2333** [comment]
另外我发现，转换成ANSI码后，在LobeChat客户端打开中文乱码，但链接内容正常。

还有一点疑惑是，智能体读取知识库时，到底是以哪一种编码结果读取的，会不会出现不使用英文写的知识库，读取时我看到的是正常，但智能体读取的是乱码。

**Comment by arvinxx** [comment]
浏览器打开链接读成 ansi 挺正常的吧，不用管。

正常用法里也不会有人想着打开一个cdn链接来预览内容。
