### ISSUE TITLE
手机端无法上传图片

### ISSUE THREAD

**Issue by wwalkingg** [lobehub/lobe-chat#456]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

![Uploading IMG_3402.png…]()

没有地方展示上传的图

### 🚦 期望结果 | Expected Behavior

和电脑一样

### 📷 复现步骤 | Recurrence Steps

选择gpt4-vision-preview 
上传一张图片

**Comment by arvinxx** [comment]
@wwalkingg 正在适配中，今天会再更新一版
