### ISSUE TITLE
[Request] Set restriction / access control for SSO users / conversation access 

### ISSUE THREAD

**Issue by KnightNFS** [lobehub/lobe-chat#4564]
### 🥰 Feature Description

Could you please implement in features releases additional Lobe-chat Tab in Settings named as "Admin" 
Access to Those  tab have only user name( or names )  marked  in special env, variable  ( Named for example ADMIN_PAGE_USER= ) 

On this tab Admin can set limitation for ( ADMIN_PAGE_USER user has no limitation )  : 
Restrict Access to chat at all ( For SSO users it will be good ) 
Creating additional chat 
Chat conversation long ( how many times users can ask )
set used Plugins ( allowed or not )   
Set different Ai engine to work with those username 
and some other function can be limited for non admin user 

### 🧐 Proposed Solution

 implement in features releases additional Lobe-chat Tab in Settings named as "Admin Settings "

**Comment by arvinxx** [comment]
it's not planned in the Open Source Edition
