### ISSUE TITLE
[Bug] 通义千问模型搜索插件影响流式输出

### ISSUE THREAD

**Issue by JIANGTUNAN** [lobehub/lobe-chat#4567]
### 📦 部署环境

Docker

### 📌 软件版本

v1.26.14

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

如果勾选了搜索插件的话就会影响流式输出。

### 📷 复现步骤

![image](https://github.com/user-attachments/assets/8a30a5a9-5c78-423d-9502-b50d9dbbc4cd)

### 🚦 期望结果

哐哐流式输出

### 📝 补充信息

不勾选插件：
![recording](https://github.com/user-attachments/assets/3ef0eb9f-5850-4ba0-8d9e-d68f94b19d15)

勾选插件：
![recording](https://github.com/user-attachments/assets/88039e6c-336b-4d59-80ae-87272d76cb89)

**Comment by JIANGTUNAN** [comment]
顺带请求一下，是否能优化一下图标变形的问题：
![image](https://github.com/user-attachments/assets/149b4d1f-ff7b-4b2d-adf6-c464eaaa676d)
![recording](https://github.com/user-attachments/assets/c1814ece-9090-44f6-83e0-76b208c31c66)

**Comment by LovelyGuYiMeng** [comment]
因为千问以前只能在非流情况下才能调用插件，流式调用插件会报错，所以设置了调用插件时强制使用非流
![image](https://github.com/user-attachments/assets/a2b08f75-cf16-410e-bd34-b8e224fd36e2)
现在流式能不能用不知道，看看有没有人更新吧

**Comment by JIANGTUNAN** [comment]
> 因为千问以前只能在非流情况下才能调用插件，流式调用插件会报错，所以设置了调用插件时强制使用非流 ![image](https://private-user-images.githubusercontent.com/76251800/382171955-a2b08f75-cf16-410e-bd34-b8e224fd36e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzE5NTIsIm5iZiI6MTczMDQzMTY1MiwicGF0aCI6Ii83NjI1MTgwMC8zODIxNzE5NTUtYTJiMDhmNzUtY2YxNi00MTBlLWJkMzQtYjhlMjI0ZmQzNmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAzMjczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMjRkMjMxOWJiMzdiNzRhNGNhMWNiODYyNzBmZjE5MzNjMjNiMGZjYTEzNjhjNWQxMTQyN2JkM2M4MTY0ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4razNE0Z9qOteLXKv9rCERTTHPCH_-5qUH1XTjql8U0) 现在流式能不能用不知道，看看有没有人更新吧

现在应该是支持了，查看官网的调用文档里面是有参数可以设置。
![image](https://github.com/user-attachments/assets/47eb569f-326d-415b-9672-44a95368021d)

**Comment by LovelyGuYiMeng** [comment]
@sxjeru 你有空的时候看一看?

**Comment by arvinxx** [comment]
@JIANGTUNAN 建议自己实际测试过再反馈，阿里云的文档里没有示例显示 tools calling 支持流式。

<img width="480" alt="image" src="https://github.com/user-attachments/assets/6fc25b4b-004f-42dd-b4c0-49d972cf9951">

你提到的流式参数只是单纯对话流式而已。

之前的讨论 https://github.com/lobehub/lobe-chat/pull/3114#issuecomment-2202124553
