### ISSUE TITLE
[Bug] Ctrl+Alt+Backspace 无法清空当前会话的消息

### ISSUE THREAD

**Issue by gomico** [lobehub/lobe-chat#4583]
### 📦 Environment

Vercel, Docker

### 📌 Version

v1.26.17 

### 💻 Operating System

Windows

### 🌐 Browser

Chrome, Edge, Other

### 🐛 Bug Description

`Ctrl+Alt+Backspace`无法清空当前会话的消息
已测试vercel和本地docker部署，均为v1.26.17版本（之前的几个版本是正常的），使用浏览器为edge/chrome/vivaldi，均使用`--disable-extensions`选项
powertoys的键盘管理器已关闭
用了AHK脚本测试，`Ctrl+Alt+Backspace`应该是没有被其他程序占用的
```
^!Backspace:: {
    MsgBox("Ctrl+Alt+Backspace pressed")
}
```

**Comment by SpeedupMaster** [comment]
#4526 快捷键已移除

**Comment by SpeedupMaster** [comment]
@arvinxx 这里的快捷键文字没删除
![图片](https://github.com/user-attachments/assets/46b50c51-698e-4af8-8eaa-99a4afd003b7)

**Comment by arvinxx** [comment]
快捷键删掉了，原因： https://github.com/lobehub/lobe-chat/issues/4517 

展示这边应该是漏删了……

**Comment by liuchao0807** [comment]
> 快捷键删掉了，原因： https://github.com/lobehub/lobe-chat/issues/4517 
> 
> 
> 
> 展示这边应该是漏删了……

能不能加个开关，这个快捷键还挺常用的。。。

**Comment by arvinxx** [comment]
@liuchao0807 后续做自定义快捷键的时候这个再加回来吧。建议可以先直接用 alt+n 新开会话。
