### ISSUE TITLE
[Docs] Feedback for `self-hosting/platform/alibaba-cloud`

### ISSUE THREAD

**Issue by JimXiongGM** [lobehub/lobe-chat#4598]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/platform/alibaba-cloud.zh-CN.mdx

### 🐛 Feedback

为什么在阿里云上配置的服务，不支持用户管理功能？

**Comment by arvinxx** [comment]
开源版不包含用户管理
