### ISSUE TITLE
[Request] 语言模型中单一类别可以添加多个渠道

### ISSUE THREAD

**Issue by tsingfenger** [lobehub/lobe-chat#4606]
### 🥰 需求描述

目前 LobeChat 只能填一组 OpenAI 的 API 地址和 API Key，但是我的代理为不同的 API Key 分配了不同的模型列表，一个key无法访问全部模型，希望能实现支持多组 API 地址和 Key。

### 🧐 解决方案

语言模型中可以添加多个Openai组。

**Comment by SAnBlog** [comment]
oneapi

**Comment by tsingfenger** [comment]
> oneapi

感谢提醒，已部署
