### ISSUE TITLE
[Request] 历史聊天记录配置

### ISSUE THREAD

**Issue by Eobravo** [lobehub/lobe-chat#461]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

录屏了复现步骤，见下图
![LobeChat设置后历史会话消失](https://github.com/lobehub/lobe-chat/assets/93071927/bbe6a8ba-2661-462a-8196-962621b8d619)

### 🚦 期望结果 | Expected Behavior

进入设置页面后返回聊天窗口，历史记录保留

**Comment by arvinxx** [comment]
@Eobravo 点下这个 
<img width="443" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/76b8a757-7b3d-441f-afe4-445d652aaa9e">

你需要的应该是保留上次会话的功能吧。 目前已经有相关讨论了：
- #407 
- #320 


我们近期做下该配置能力

**Comment by Eobravo** [comment]
> @Eobravo 点下这个，你的历史记录在话题那边。
> 
> <img alt="image" width="443" src="https://user-images.githubusercontent.com/28616219/282989490-76b8a757-7b3d-441f-afe4-445d652aaa9e.png">
> 你需要的应该是保留上次会话的功能吧。 目前已经有相关讨论了：
> 
> * [[Question] 历史消息会话在重新进入角色后会消失 #407](https://github.com/lobehub/lobe-chat/issues/407)
> * [[Request] 是否可以记录默认上次访问的话题页签 #320](https://github.com/lobehub/lobe-chat/issues/320)
> 
> 我们近期做下该配置能力

找到历史对话了！感谢！

**Comment by arvinxx** [comment]
release on v0.103.0
