### ISSUE TITLE
[Bug] 清空当前会话消息快捷键无响应

### ISSUE THREAD

**Issue by kindmesdilabso** [lobehub/lobe-chat#4611]
### 📦 部署环境

Docker

### 📌 软件版本

v1.27.1

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome, Edge

### 🐛 问题描述

在单轮对话不想继续进行的时候 使用快捷键 ctrl + alt + backspace 无响应,没有办法清空当前会话消息
已经尝试了多台不同的电脑访问均无法清空当前会话消息

### 📷 复现步骤

打开网页,任意助手对话一句
按下 ctrl + alt + backspace 组合键

### 🚦 期望结果

和以前一样能够清空当前会话的消息

或者可以提供自定义快捷键

### 📝 补充信息

似乎快捷键被不知名程序占用
使用OpenArk查找 提示是系统的一个叫csrss.exe 的占用了这个热键

**Comment by SpeedupMaster** [comment]
快捷键目前已删除 #4583
