### ISSUE TITLE
[Request] 角色设定 Prompt  支持指定Message Role 并支持多条初始Message 

### ISSUE THREAD

**Issue by wertycn** [lobehub/lobe-chat#4613]
### 🥰 需求描述

目前lobe-chat助手的角色设定 prompt 设置只支持单条文本，如图
<img width="1348" alt="image" src="https://github.com/user-attachments/assets/d5113606-ea0b-4880-ba82-0efbc0dccdc8">

而实际目前大部分的模型API的 请求参数是一个类似的Message 列表
```
[
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ]
```

基于模型API 的能力，我们可以通过填充多个Message 达到利用模型本身消息结构的few-shot的效果，而不是把所有提示都放到system 或第一次的user 消息中，以达到更好的fewshot 效果

### 🧐 解决方案

角色设定支持类似如下模式的输入：

<img width="889" alt="image" src="https://github.com/user-attachments/assets/6e9b1ace-4992-4233-b78e-b3d565ef47b4">

对于现有的模版，按照当前请求LLM API 的传参设定，补充默认role 信息或增加高级模式来实现

### 📝 补充信息

参考 ChatGPT-Next-Web 项目的设计，这项功能深受用户喜欢

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/138

**Comment by arvinxx** [comment]
重复 #336
