### ISSUE TITLE
[Bug] Docker 容器崩溃当访问 localhost:3210时

### ISSUE THREAD

**Issue by hengqujushi** [lobehub/lobe-chat#462]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

成功启动 Docker 容器后，当尝试访问 localhost:3210 页面时，容器会意外地退出。报错如下
![image](https://github.com/lobehub/lobe-chat/assets/2217955/09fad0e0-752b-49a6-b5fb-0b20710f47aa)

### 🚦 期望结果 | Expected Behavior

预期在访问 localhost:3210 时能够正常加载页面，不会导致 Docker 容器退出。

### 📷 复现步骤 | Recurrence Steps

使用 docker run -it -p 3210:3210 ... 命令启动 Docker 容器。
容器成功启动后，打开浏览器并访问 localhost:3210。
页面无法加载，并且 Docker 容器退出。

### 📝 补充信息 | Additional Information

项目不包含自定义的 server.js 文件，但 Dockerfile 中的 CMD 使用了 ["node", "server.js"] 启动命令。
当从 Docker 容器中移除对 server.js 的引用后，问题依旧存在。
问题可能与 Next.js 应用程序的 Service Worker 配置有关。
提交此问题时，没有能够提供更多的日志信息，因为 Docker 容器在崩溃时没有输出更多的错误信息。

**Comment by arvinxx** [comment]
docker版本？

**Comment by hengqujushi** [comment]
"You're currently on version 4.22.0 (117440). The latest version is 4.25.1 (128006)."

之前是4.22.0 (117440)，不行，升级到4.25.1 (128006)，也还是一样。

**Comment by hengqujushi** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/2217955/19c71ad8-9806-4b6c-a8e3-8aa118a401aa)

**Comment by arvinxx** [comment]
这个看样子没问题呀，你试过匿名状态访问么

**Comment by hengqujushi** [comment]
“匿名状态访问”是指？

**Comment by arvinxx** [comment]
> “匿名状态访问”是指？

浏览器匿名模式

**Comment by hengqujushi** [comment]
https://github.com/lobehub/lobe-chat/assets/2217955/300d4ba2-4d08-47ba-b84e-796742c38303

you can see this video.

**Comment by arvinxx** [comment]
pc 模式下正常吗？只是 mobile 下有问题还是都有问题？

**Comment by hengqujushi** [comment]
这个就是Mac Pro上的啊
