### ISSUE TITLE
[Bug] artifacts doesn't works on Mobile

### ISSUE THREAD

**Issue by Leonscreative** [lobehub/lobe-chat#4623]
### 📦 Environment

Docker

### 📌 Version

Last 

### 💻 Operating System

Android

### 🌐 Browser

Chrome

### 🐛 Bug Description

When creates an artifact file is not possible to open in mobile

### 🚦 Expected Behavior

Clicking on the artifact file Is suppose to open a new window(popup) to visualise the content and close the view

**Comment by ggatesdew** [comment]
1. Chrome in iOS:
Clicking on the generated artifact in mobile view does not react:
![image](https://github.com/user-attachments/assets/93e1514d-fc0a-4acb-b090-b53b286a6520)

**Comment by ggatesdew** [comment]
2. When doing so via "Request Desktop Site" in Chrome works properly
![image](https://github.com/user-attachments/assets/04b4e115-8c04-4655-8182-7d0d6065c4fb)

**Comment by ggatesdew** [comment]
Proposed solution: Add to the frontend code for mobile devices a frame/window similar to the [2nd screenshot above](https://github.com/lobehub/lobe-chat/issues/4623#issuecomment-2458773800)
