### ISSUE TITLE
[Request] lobechat是否允许自己搭建一个authjs服务去完成身份验证

### ISSUE THREAD

**Issue by BravoDD44** [lobehub/lobe-chat#4635]
### 🥰 需求描述

lobechat目前支持clerk与next auth等身份验证，如果想自己去搭建去做一些个性化设置，是否可以自己去搭建一个authjs服务，完成身份验证与登录的操作。

### 🧐 解决方案

我想自己搭建一个由next authjs构成的验证网页去完成lobechat的身份验证过程，该做法是否可行。

**Comment by arvinxx** [comment]
可行啊，你自己搭 casdoor、logto 这些都可以
