### ISSUE TITLE
[Request] Voice Input / Output Plugin

### ISSUE THREAD

**Issue by netconstructor** [lobehub/lobe-chat#464]
### 🥰 需求描述 | Feature Description

Development of a speech to text as well as a text to speech plugin which one could optionally enable for a chat agent.

### 🧐 解决方案 | Proposed Solution

Having experimented with various solutions such as RealChar (GitHub) I believe it would be very valuable to develop a plugin which would allow for voice input and output if the developer wants to enable or force it (or if the end user desires to enable that view) - similar to that demonstrated by OpenAI’s mobile app but for the browser (like RealChar)

Such functionality should allow for customizing which local or remote api can be used for speech to text as well as text to speech.

from my experimentations it seems the new whisper api from OpenAI seems to be the best for speech-to-text and in terms of text-to-speach Elevenlabs works incredible using their realtime api.

### 📝 补充信息 | Additional Information

See the GitHub project called RealChar which did a fairly good job demonstrating this functionality and it would be great to have these type of features implemented.

If anyone has any other examples like RealChar please provide such examples for review so we can identify the best approach to implement this.

From my perspective and experiments one should identify the best methods to deal with the ‘open microphone’ issues with cross platform/browser considerations.

Additionally I have been trying to identify the best method to add a low overhead method to tap into the realtime audio output and mic input steam to display a realtime visualization of the audio stream similar to the OpenAI app. Would love to share my research if there is interest by other developers.

**Comment by netconstructor** [comment]
@canisminor1990 Great that this is being worked on!

I'm curious what approach you have experimented with in terms of visualizing the audio input/output if such a view is desired. I've noticed various solutions are too processor intensive. Let me know if you have this covered or desire some thoughts. Cool work!

**Comment by canisminor1990** [comment]
@netconstructor  The integration of conversion services is not difficult, as there are convenient integration methods available from platforms like OpenAI and Microsoft. The current challenge lies in generating audio in a streaming manner when the text is returned as a stream. Since I am also new to audio processing development, my current approach is to locally segment the text into small sections and generate a playback queue. If there are better solutions, please feel free to provide them.

**Comment by netconstructor** [comment]
@canisminor1990 

While I appreciate your work on these developments I believe the implementation of this in its current state doesn't actually make this a functional component in terms of usefulness.

As referenced in my original message I believe it would be of value to review the approach RealChar utilized.

In particular I would suggest you review the following:
- the realtime chunking approach they utilized which provided a very effective low latency approach (in my tests under low traffic conditions this nearly felt like a live conversation).
- in particular review how they implemented the "open mic" approach for the client interface. While not perfect when on speakerphone it essentially allows you to trigger the mic once while it remains open and allows the user to interrupt the responses. Without headphones I have noticed this can result in an echo preventing this approach from working
- Most importantly I believe on the client interface once should be able to open a "voice conversation" view possibly using an overlay approach to autoplay/stream all audio responses and allow for manual or automatic user input by voice. One should be able to close this overlay bringing you back to the chat window to view the conversation.
- It seems that currently by default whenever audio is the input/output this are presented as playable files within the chat when it would make far more sense to display the transcription text instead (with the option to play the audio instead. This would also simplify search, and db archival of conversations.
