### ISSUE TITLE
[Bug] 切换模型时，默认列表的模型有时不显示

### ISSUE THREAD

**Issue by aiqinxuancai** [lobehub/lobe-chat#4643]
### 📦 部署环境

Docker

### 📌 软件版本

1.28.5

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

切换模型时，默认列表的模型有时不显示
![gif1.gif](https://cdn.sa.net/2024/11/08/7yIjAXsqYlSxfQ6.gif)

**Comment by arvinxx** [comment]
不显示是因为和随便聊聊一样了。
