### ISSUE TITLE
[Bug] 使用Artifacts时除了第一段，其他代码与画布脱钩

### ISSUE THREAD

**Issue by fangao888** [lobehub/lobe-chat#4648]
### 📦 Environment

Docker

### 📌 Version

v1.26.20

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

![QQ20241108-213950](https://github.com/user-attachments/assets/5304ef3c-3fc5-43de-8c04-6ea9fe2668bf)
![QQ20241108-214039](https://github.com/user-attachments/assets/132e7044-d6e4-4db3-8e91-eb16cea228c6)

**Comment by arvinxx** [comment]
重复 #4618
