### ISSUE TITLE
[Bug] The error returned to user is not detailed enough when getting OpenAIBizError

### ISSUE THREAD

**Issue by skyf0cker** [lobehub/lobe-chat#465]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Since this morning, the Lobe-Chat deployed on Vercel suddenly stopped working. When chatting, the frontend threw an error: "请求 OpenAI 服务出错，请根据以下信息排查或重试" The error message only included the endpoint without any details, and from the Vercel logs, I could only see a 577 error status code. All these indicate that the OpenAI interface was reporting an error, but I couldn't determine the specific reason, which led to the inability to resolve the issue.

Finally, in another Telegram group chat, I heard that the problem was due to API regional restrictions causing the API to fail. I briefly looked at the code, but I still don't understand it very well. Intuitively, I think the error message should be more comprehensive, including the error information of the OpenAI interface, HTTP status codes, and so on.

<img width="593" alt="image" src="https://github.com/lobehub/lobe-chat/assets/32331521/e3cf861c-d4f0-4894-88f3-c525b6133736">

https://github.com/lobehub/lobe-chat/blob/5bdbd6a06a73e0a4d5e77507c33f60dad0fd7ccf/src/app/api/openai/chat/createChatCompletion.ts#L38-L43

### 🚦 期望结果 | Expected Behavior

Intuitively, I think the error message should be more comprehensive, including the error information of the OpenAI interface, HTTP status codes, and so on.

**Comment by arvinxx** [comment]
you are right. we should add more info when meet this error.

**Comment by arvinxx** [comment]
By the way, why your message shows Chinese other than English? Do you use Chinese?

**Comment by skyf0cker** [comment]
Yep, i'm a Chinese native speaker, but used to communicate in English on gh
