### ISSUE TITLE
[Bug] 更新后所有对话都自动默认一条历史记录是什么情况

### ISSUE THREAD

**Issue by Mgrsc** [lobehub/lobe-chat#4663]
### 📦 Environment

Docker

### 📌 Version

v1.29.4

### 💻 Operating System

Ubuntu, Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

[Bug] 更新后所有存在的助手都自动变为默认一条历史记录是什么情况, 但是新建就是正常的八条
![image](https://github.com/user-attachments/assets/a3e14cd1-8271-4e42-851e-a0aad325967f)
![image](https://github.com/user-attachments/assets/7bf319d9-3bca-41e7-9bc4-5cabe57a7445)

**Comment by arvinxx** [comment]
助手的默认值数据做了变更，将原本的 1 改成了 8 ，由于助手数据会存进agent 配置里，所以改成 1 了。

如果你助手数不多的话，可以一个个手动更新下。如果助手数比较堵，可以执行下这个 SQL 做批量变更：

```sql
UPDATE agents 
SET chat_config = jsonb_set(
  chat_config, 
  '{historyCount}', 
  '8'::jsonb
)
WHERE chat_config->>'historyCount' = '1';
```

**Comment by Mgrsc** [comment]
> 助手的默认值数据做了变更，将原本的 1 改成了 8 ，由于助手数据会存进agent 配置里，所以改成 1 了。
> 
> 如果你助手数不多的话，可以一个个手动更新下。如果助手数比较多，可以执行下这个 SQL 做批量变更：
> 
> ```sql
> UPDATE agents 
> SET chat_config = jsonb_set(
>   chat_config, 
>   '{historyCount}', 
>   '8'::jsonb
> )
> WHERE chat_config->>'historyCount' = '1';
> ```

ok，我手动改下吧还好不多

**Comment by enor2017** [comment]
Thank you for the answer. Is there an environment variable for this? I want the history to be unlimited for all existing and new agents.

**Comment by enor2017** [comment]
> Thank you for the answer. Is there an environment variable for this? I want the history to be unlimited for all existing and new agents.

Solved by specifying `chatConfig.historyCount=xxx` and `chatConfig.enableHistoryCount=false` in env variable `DEFAULT_AGENT_CONFIG`. Thank you for the discussions above.
