### ISSUE TITLE
[Bug] 向量化失败

### ISSUE THREAD

**Issue by Qoo-330ml** [lobehub/lobe-chat#4665]
### 📦 Environment

Docker

### 📌 Version

v1.29.4

### 💻 Operating System

Ubuntu

### 🌐 Browser

Firefox

### 🐛 Bug Description

root@racknerd-5812470:~/lobe-chat-db# docker logs 7e12a4c906f1
🌐 DNS Server: [ '127.0.0.11' ]
-------------------------------------
[Database] Start to migration...
✅ database migration pass.
-------------------------------------
  ▲ Next.js 14.2.8
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210

 ✓ Starting...
 ✓ Ready in 130ms
执行第 1 个任务
任务[1]: embeddings: 2.070s
embeddingChunks error {
  message: '{"length":94,"name":"error","severity":"ERROR","code":"22000","file":"vector.c","line":"72","routine":"CheckExpectedDim"}',
  name: 'EmbeddingError'
}
执行第 1 个任务
任务[1]: embeddings: 2.447s
(node:28) Warning: Label '任务[1]: insert db' already exists for console.time()
(Use `node --trace-warnings ...` to show where the warning was created)
embeddingChunks error {
  message: '{"length":94,"name":"error","severity":"ERROR","code":"22000","file":"vector.c","line":"72","routine":"CheckExpectedDim"}',
  name: 'EmbeddingError'
}
执行第 1 个任务
任务[1]: embeddings: 2.342s
(node:28) Warning: Label '任务[1]: insert db' already exists for console.time()
embeddingChunks error {
  message: '{"length":94,"name":"error","severity":"ERROR","code":"22000","file":"vector.c","line":"72","routine":"CheckExpectedDim"}',
  name: 'EmbeddingError'
}
执行第 1 个任务
任务[1]: embeddings: 2.863s
(node:28) Warning: Label '任务[1]: insert db' already exists for console.time()
embeddingChunks error {
  message: '{"length":94,"name":"error","severity":"ERROR","code":"22000","file":"vector.c","line":"72","routine":"CheckExpectedDim"}',
  name: 'EmbeddingError'
}
root@racknerd-5812470:~/lobe-chat-db#

**Comment by arvinxx** [comment]
感觉是你的向量化模型有问题吧
