### ISSUE TITLE
[Bug]  The latest version of LobeChat - server database edition cannot upload images

### ISSUE THREAD

**Issue by Liyuzhou01** [lobehub/lobe-chat#4673]
### 📦 Environment

Docker

### 📌 Version

v1.31.0

### 💻 Operating System

Ubuntu

### 🌐 Browser

Edge

### 🐛 Bug Description

This error only occurs when uploading images; PDFs or other file types can be uploaded normally. The images can be seen in my R2 bucket.My API also works normally for image exchanges in other places.
<img width="1159" alt="截屏2024-11-12 11 30 13" src="https://github.com/user-attachments/assets/40c65c90-0e15-4e66-91d4-944fd78265ce">

**Comment by arvinxx** [comment]
<img width="506" alt="image" src="https://github.com/user-attachments/assets/4a6a0f6d-08c7-4b76-aa6f-662c6b8f83ac">

check your api key. switch to OpenAI official key and try again. Mostly it's your api key provider's issue.
