### ISSUE TITLE
[Bug] 连接腾讯云COS服务 上传文件报错

### ISSUE THREAD

**Issue by Zzzz5125** [lobehub/lobe-chat#4676]
### 📦 部署环境

Docker

### 📌 软件版本

LobeChat DB v1.31.0

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

连接腾讯云COS服务 上传文件日志报错
Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
 [TRPCError: Invalid region: region was not a valid DNS name.] {
  cause:  [EndpointError: Invalid region: region was not a valid DNS name.] {
  name: 'EndpointError'
},
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError'
}
Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
 [TRPCError: Unsupported GET-request to mutation procedure at path "upload.createS3PreSignedUrl"] {
  cause: undefined,
  code: 'METHOD_NOT_SUPPORTED',
  name: 'TRPCError'
}

### 🚦 期望结果

如何修复

**Comment by Zzzz5125** [comment]
> ### 📦 部署环境
> Docker
> 
> ### 📌 软件版本
> LobeChat DB v1.31.0
> 
> ### 💻 系统环境
> Ubuntu
> 
> ### 🌐 浏览器
> Edge
> 
> ### 🐛 问题描述
> 连接腾讯云COS服务 上传文件报错 日志报错
`Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
 [TRPCError: Invalid region: region was not a valid DNS name.] {
  cause:  [EndpointError: Invalid region: region was not a valid DNS name.] {
  name: 'EndpointError'
},
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError'
}
Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
 [TRPCError: Unsupported GET-request to mutation procedure at path "upload.createS3PreSignedUrl"] {
  cause: undefined,
  code: 'METHOD_NOT_SUPPORTED',
  name: 'TRPCError'
}
`
> 
> ### 📷 复现步骤
> _No response_
> 
> ### 🚦 期望结果
> 如何修复
> 
> ### 📝 补充信息
> _No response_

**Comment by obsidian0215** [comment]
我现在也遇到了这个问题，配置了腾讯云的COS后上传文件就报这个错
`Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
TRPCError: Invalid region: region was not a valid DNS name.
    at O (.next/server/edge-chunks/10.js:25:25221)
    at C (.next/server/edge-chunks/10.js:25:25537)
    at R (.next/server/edge-chunks/10.js:25:25379)
    at C (.next/server/edge-chunks/10.js:25:25575)
    at R (.next/server/edge-chunks/10.js:25:25379)
    at C (.next/server/edge-chunks/10.js:25:25575)
    at R (.next/server/edge-chunks/10.js:25:25379)
    at C (.next/server/edge-chunks/10.js:25:25575)
    at R (.next/server/edge-chunks/10.js:25:25379)
    at C (.next/server/edge-chunks/10.js:25:25575) {
  code: 'INTERNAL_SERVER_ERROR'
}`
请问如何解决
