### ISSUE TITLE
[Bug] deepseek/deepseek-chat模型的参数信息不正确

### ISSUE THREAD

**Issue by AKGO47** [lobehub/lobe-chat#4677]
### 📦 部署环境

Docker

### 📌 软件版本

1.31.2

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

官网信息是128000
代码中查了一下也是128000
但是web中显示的是62K
仅设置了DEEPSEEK_API_KEY参数 没有设置其他参数

![1](https://github.com/user-attachments/assets/76eea22e-faf0-474b-8a6a-524b15198765)
![2](https://github.com/user-attachments/assets/02f9c1a4-5b51-4558-afa9-302004ab35d0)
![3](https://github.com/user-attachments/assets/a2e1bc8a-71cb-481d-90cf-bc0c26cccba6)

### 📷 复现步骤

必现128000

### 🚦 期望结果

显示128000

**Comment by arvinxx** [comment]
https://api-docs.deepseek.com/zh-cn/quick_start/pricing/ 官网改了吧，你是不是看的还是老的？
