### ISSUE TITLE
[Request] 百川新增了两款性价格高的模型,请更新一下

### ISSUE THREAD

**Issue by SAnBlog** [lobehub/lobe-chat#4680]
### 🥰 需求描述

![image](https://github.com/user-attachments/assets/2c25f910-c8fd-4fb4-a607-ae110d689fe4)

Baichuan4-Turbo和Baichuan4-Air

### 🧐 解决方案

Baichuan4-Turbo和Baichuan4-Air增加模型列表

**Comment by LovelyGuYiMeng** [comment]
> 我咋记得这两个已经有了呢？

我刚加的😅
