### ISSUE TITLE
[Bug] 搜索话题功能失效

### ISSUE THREAD

**Issue by skywolf123** [lobehub/lobe-chat#4691]
### 📦 部署环境

Docker

### 📌 软件版本

v1.31.6

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

话题的搜索功能失效了，之前是可用的
我记得自从话题区改为按时间分组后这个话题搜索功能就不可用了

**Comment by arvinxx** [comment]
咦这样么…我晚点看下
