### ISSUE TITLE
[chat]全新用户引导

### ISSUE THREAD

**Issue by canisminor1990** [lobehub/lobe-chat#47]

**Comment by arvinxx** [comment]
路由逻辑：

1. 用户访问 / （App首页）  
      - 首先是未水合的首屏，一个 应用加载中状态（需要有个 loading 的效果？）；
      - localStorage 水合后，可以获取到当前是否有会话消息，如果有会话消息，那么展示 Chat ，如果没有会话消息，则展示 Welcome；
2. 在 Welcome 下：
     - 用户可点击侧边栏，如果点击 chat，则跳转 /chat 路由，点击markert，未来跳转 市场（是不是可以放个施工中的兜底页面？）；
     - 用户可以点击「开始使用」，直接创建一个默认消息 / 或 点击下方的模板，使用预置角色创建会话 / 或者在最后放一个配置面板，直接让用户做自定义创建（这一步的操作将始终跳转到 /chat/xxxx 的某个角色会话）；
3. 在 /chat 路由下：
     - 用户如果没有角色，那么展示没有任何会话的 会话页空状态；
     - 如果用户存在角色，则会展示角色列表，并自动切到第一个会话（现有逻辑）；
     - 如果用户直接在 /chat 路径下刷新，或者直接访问 /chat ，首屏应该是 /chat 的加载态，而不是 / 的加载态；
4. 在 /chat/xxx 路由下：
     - 首屏进入，是现在的首屏骨架，等待水合；
     - 水合玩出，直接展示消息；
