### ISSUE TITLE
[Request] Set PreferredRegion for OpenAI Chat edge function

### ISSUE THREAD

**Issue by skyf0cker** [lobehub/lobe-chat#470]
### 🥰 需求描述 | Feature Description

Accordding to the Vercel region doc: https://vercel.com/docs/functions/configuring-functions/region, it supports to set the preferred region for edge function so that the function calling will be served by the instance in the specific region. 
By doing this, we can bypass the OpenAI's block based on region, for example we can set the preferred region to `iad1 ` so that the requests to OpenAI will send from the Washington.

https://github.com/skyf0cker/lobe-chat/blob/515faab30bda5be1974b88e3c94018fedc8d0d75/src/app/api/openai/chat/route.ts#L14-L15

I tested in my self-hosted Lobe-Chat, it looks like that it works.
If this really works, maybe we can set it with a default region or provide a method to user to set like through env variables.

### 🧐 解决方案 | Proposed Solution

we can set the preferred region to `iad1 ` 
https://github.com/skyf0cker/lobe-chat/blob/515faab30bda5be1974b88e3c94018fedc8d0d75/src/app/api/openai/chat/route.ts#L14-L15

**Comment by arvinxx** [comment]
@skyf0cker yes we can, could your open a pr for this? I think it's great for the block based region user.

**Comment by arvinxx** [comment]
By the way, I think it's better to use an array regions like ` ['iad1', 'sfo1']` ?

https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#preferredregion

**Comment by skyf0cker** [comment]
> @skyf0cker yes we can, could your open a pr for this? I think it's great for the block based region user.

Of course, i will complete this work tonight.

**Comment by skyf0cker** [comment]
I just want to confirm whether using environment variables to specify the region can be more user-friendly? Some users may not need to consider the limitations brought by regions. If we directly specify the region as the United States, could it potentially lead to longer delays for them when using Lobe-Chat?
@arvinxx

**Comment by arvinxx** [comment]
>  Some users may not need to consider the limitations brought by regions.

you are right. I think a better way is to add a boolean environment variable to control whether need to use this feature. What's the name of the environment variable should be?

**Comment by skyf0cker** [comment]
I was thinking of adding an environment variable called "OPENAI_FUNCTION_REGIONS." If this variable is not set, we won't set the preferredRegion, which means we will use Vercel's default logic for accessing the nearest region. If it is set, we will then set the PreferredRegion to the value corresponding to this variable.
