### ISSUE TITLE
[Request] 对话分支

### ISSUE THREAD

**Issue by naimehao** [lobehub/lobe-chat#4706]
### 🥰 需求描述

现在可以修改对话中之前的提问，然后重新生成，但此前的提问就找不到了，而且生成的内容并没有覆盖之前AI的回复，而是在之前AI回复之下又生成了新的回复，这会让人比较困惑。

举例：
比如我问AI，xxx的方案。
AI给了两个，我两个都想具体了解，但又不想在一次会话中掺入与最终方案无关的支路对话内容，就会进行分支。
我第一次会说，我想了解A方案，完了我会将“我想了解A方案”修改为：我想了解B方案，然后我自行判断哪个更好，哪个更好，就沿着哪条路走下去，甚至我在A方案中走了10步后，我想想，还是B方案好，我再回到最开始“我想了解A/B方案”那个分支的地方，再沿着B方案走下去。

我知道现在可以对自己的和AI生成的内容进行修改和删除，但是修改了之后，不会覆盖之前的内容，而是在下面生成了新回复，看上去就比较奇怪，而且我也不知道这是不是会带到上下文中去。

还有就是对于修改AI回复的这个功能我持怀疑态度，这样确实很自由，但很多时候，AI行就是行，不行就是不行，如果AI回复的内容中部分不正确，你改对了，但AI本身能力不行，你这里改了，后面该错还是错。 

### 🧐 解决方案

完全仿照Claude，可以左右切换对话分支。（甚至我一直觉得Claude可以针对该特性搞个树状图的可视化出来。）

我是Claude这两天被封了之后开了你们的云版本的会员，这个功能我觉得可以搞成云版本特供。😆

**Comment by SpeedupMaster** [comment]
#4616

**Comment by arvinxx** [comment]
@naimehao 这个月就会上，而且你说的树状图模式未来也会有。这些也都会全开源

**Comment by arvinxx** [comment]
> 还有就是对于修改AI回复的这个功能我持怀疑态度，这样确实很自由，但很多时候，AI行就是行，不行就是不行，如果AI回复的内容中部分不正确，你改对了，但AI本身能力不行，你这里改了，后面该错还是错。

这个不会的，事实上这个用起来还是很舒服的。主要是改小细节。比如 `import abc from './yourpath'` 这样的输出，我直接编辑之后改成 `import abc from './index.ts'` ，这样继续对话时就会保持这个 `import abc from index.ts` 这个实现。

而且修改模型输出，本质上是在使用 few shots 的方式来规范模型输出。我个人一直认为 few shots 应该是所有提示词工程中最有效的方式。
