### ISSUE TITLE
[Request] 纯净模式

### ISSUE THREAD

**Issue by naimehao** [lobehub/lobe-chat#4707]
### 🥰 需求描述

有的时候就是专注于某次对话，但是lobechat的界面上下左右全都有内容，真正与AI交互的部分被挤在中间，看着很难受。

### 🧐 解决方案

搞个快捷键，能一键进入纯净模式，或者叫禅模式🤣🤣隐藏左边右边的内容，还有用户的输入，感觉可以对标Claude，现在的输入我咋调都感觉占了我好多空间😢 ，那些统计信息啥的一排按钮，在这个模式下，都可以不要显示了，或者搞个集成的，鼠标悬浮上去可以看到。

再讲一下之前使用Claude方式，一般是手头有一个主任务，比较长的对话，那么这之间可能会穿插着问一两个无关的小问题，这时候我不会在Claude界面中点击新建会话，我会直接点击浏览器收藏bar中的Claude来新建会话，而且，你会发现，这样一个新建的会话，它的用户输入框是在屏幕中央的，这就很舒服，等开始对话后，它再被放到最下面。

**Comment by SAnBlog** [comment]
Ctrl+\
