### ISSUE TITLE
[Request] 添加默认助手使用的模型环境变量

### ISSUE THREAD

**Issue by AquaHydro** [lobehub/lobe-chat#4735]
### 🥰 需求描述

当我配置`ENABLED_OPENAI `为0时，系统默认助手仍默认选择openai下的模型。造成不能生成相关的对话总结等信息。
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/7631f62d-a15b-4b69-b153-50323a268ab6">

### 🧐 解决方案

是否可以提供类似`DEFAULT_AGENT_CONFIG `环境变量，让默认助手也能自定义默认模型

**Comment by AquaHydro** [comment]
@hezhijie0327 已解决，感谢

**Comment by Yuyuyang** [comment]
> 使用 `SYSTEM_AGENT` 环境变量
> 
> ```
> SYSTEM_AGENT="agentMeta=zhipu/glm-4-flash,historyCompress=zhipu/glm-4-flash,queryRewrite=zhipu/glm-4-flash,topic=zhipu/glm-4-flash,translation=zhipu/glm-4-flash"
> ```

请问此处参数的具体含义是什么？我已经在渠道中配置某渠道名称，在系统助手处显示此渠道名，但是并未成功调用
