### ISSUE TITLE
[Docs] Feedback for `self-hosting/advanced/knowledge-base`

### ISSUE THREAD

**Issue by owenshen0907** [lobehub/lobe-chat#4748]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/advanced/knowledge-base.zh-CN.mdx

### 🐛 Feedback

_Your response_
上传文档，不一定就是要进入知识库
上传文档建议拆分成两步，第一步是文档解析，第二步在根据意图或者配置去决定是否需要向量化。
很多文档的内容都是一次性使用的，没有必要全都放到知识库。

**Comment by arvinxx** [comment]
你直接传文件不是也可以吗？不懂说要必须传知识库是什么意思
