### ISSUE TITLE
[Request] 首屏直接打开聊天界面

### ISSUE THREAD

**Issue by hjkcai** [lobehub/lobe-chat#4753]
### 🥰 需求描述

我主要通过 PWA 的方式在手机上使用 LobeChat。目前首屏始终打开的是 `/welcome` 页面，每次都需要再点击一次“立即开始”才能进入聊天页面。我希望可以通过某种配置直接跳过 `/welcome` 页面，直达 `/chat` 页面。

### 🧐 解决方案

也许增加一个 feature flag？或者是否有其它配置方式达成，例如 nginx？

**Comment by SpeedupMaster** [comment]
#4578 #3718
这个挺久了的，不知道啥时候可以修复

**Comment by sxjeru** [comment]
有试过环境变量添加 `FEATURE_FLAGS = -welcome_suggest` 吗？我这边手机端打开域名可直接跳转 chat，没有 welcome 页，不清楚是不是这个环境变量生效的作用。

参考 doc：https://lobehub.com/zh/docs/self-hosting/advanced/feature-flags

**Comment by arvinxx** [comment]
@SpeedupMaster 等分支对话发布以后开修
