### ISSUE TITLE
[Request] Option to simplify Interface

### ISSUE THREAD

**Issue by AbondonedScrawl** [lobehub/lobe-chat#4762]
### 🥰 Feature Description

<img width="1512" alt="Screenshot 2024-11-23 at 10 16 00" src="https://github.com/user-attachments/assets/0bbe8cee-3021-482a-bfea-4b97932d8c49">

The current start page of LobeChat contains numerous visual elements including multiple emojis, assistant recommendations, and FAQ sections that can be distracting for users who prefer a minimal interface. While these features may be helpful for new users, they can create visual noise for those who want to focus solely on their conversation with the AI assistant.

### 🧐 Proposed Solution

- Add a toggle in settings to enable a "Minimal Mode" for the start page
- In Minimal Mode:
   - Remove or reduce the number of emojis
   - Hide the assistant recommendations section
   - Collapse the FAQ section into a menu
   - Keep only essential elements like the chat input and basic navigation
- Allow users to customize which elements they want to show/hide

### 📝 Additional Information

This feature would improve the user experience for those who prefer a cleaner, more focused interface while maintaining the full functionality for users who enjoy the current layout

**Comment by SpeedupMaster** [comment]
Use `FEATURE_FLAGS = -welcome_suggest` to hide the welcome_suggest
