### ISSUE TITLE
[Bug] I guess XAI_PROXY_URL is not working

### ISSUE THREAD

**Issue by kaikanertan** [lobehub/lobe-chat#4777]
### 📦 Environment

Docker

### 📌 Version

v1.32.5

### 💻 Operating System

Ubuntu

### 🌐 Browser

Firefox

### 🐛 Bug Description

I have configured the environment variable: XAI_PROXY_URL, yet I am encountering the following error:
Route: [xai] ProviderBizError: Incorrect API key provided: sk***Ac. You can obtain an API key from https://console.x.ai.

I guess the variable is not working.

**Comment by lfy-page** [comment]
我也是遇到了这种情况，我使用的是网页端配置的xai的代理地址，当我不勾选使用客户端请求模式的时候，后端是直接发送请求到xai的端点，当我勾选了使用客户端请求模式的时候，才是使用我填写的代理地址。
![image](https://github.com/user-attachments/assets/fe31dda6-62c7-43ef-9205-d5e29700085d)
![image](https://github.com/user-attachments/assets/eecddbb5-5b58-474c-a378-d8a4f7014831)
