### ISSUE TITLE
[Bug] Moonshot填写API 代理地址，使用客户端请求模式不生效

### ISSUE THREAD

**Issue by lfffffy** [lobehub/lobe-chat#4785]
### 📦 部署环境

Docker

### 📌 软件版本

使用客户端请求模式

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

填写了Moonshot的API 代理地址，使用客户端请求模式的时候请求的还是Moonshot的官方地址而不是填写的API 代理地址。
![image](https://github.com/user-attachments/assets/3690e072-c704-4f4b-960e-5548d58410e6)

**Comment by lfffffy** [comment]
和昨天晚上xai那个issues有异曲同工的相似之处

**Comment by hezhijie0327** [comment]
找到问题了，过会儿补个 PR，和昨天的还不一样
