### ISSUE TITLE
[Request] 模型可以添加备注

### ISSUE THREAD

**Issue by yuntian123456** [lobehub/lobe-chat#4791]
### 🥰 需求描述

希望自动获取的模型也可以添加自定义备注。
![image](https://github.com/user-attachments/assets/fb14f7ef-796c-404d-8bc1-c7aca5110fb0)

当前是只有手动添加的模型才会有编辑的选项
![image](https://github.com/user-attachments/assets/b5c39abb-43ce-48d3-9f75-8b970a64b2c5)

希望实现这样的效果：模型列表展开可以有备注信息，方便区分。
![image](https://github.com/user-attachments/assets/703c6453-ec36-4edd-8cbd-d0d4f91340de)

### 🧐 解决方案

无

**Comment by arvinxx** [comment]
不考虑，复杂度有点太高了
