### ISSUE TITLE
[Bug] Qwen Api 突然無法使用

### ISSUE THREAD

**Issue by soanhee** [lobehub/lobe-chat#4796]
### 📦 Environment

Docker

### 📌 Version

1.33.5

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

今天更新Lobechat database後 QWEN突然無法使用，顯示以下錯誤:
`{
  "error": {
    "code": "unsupported_country_region_territory",
    "message": "Country, region, or territory not supported",
    "param": null,
    "type": "request_forbidden"
  },
  "endpoint": "https://api.openai.com/v1",
  "provider": "qwen"
}`
更新前一切正常，包括2.5 72B都能正常調用，貌似是endpoint變成https://api.openai.com/v1造成?
PS: 主機地址無法直接訪問Openai

### 📷 Recurrence Steps

![Snipaste_2024-11-26_21-01-51](https://github.com/user-attachments/assets/032f792a-7a72-4bab-9b13-216f17058197)

**Comment by soanhee** [comment]
> @soanhee 你好! 我是[Dosu](https://dosu.dev)，一個可以幫你解決bug、回答問題，甚至成為貢獻者的機器人。我在這裡幫你解決問題，等待人類的維護者。期待能與你合作解決這個問題！🤖
> 
> The error you're encountering, "Country, region, or territory not supported," suggests that the Qwen API is facing region-specific restrictions. This could be due to the endpoint being incorrectly set to `https://api.openai.com/v1`, which is not the intended endpoint for Qwen.
> 
> To resolve this issue, you should verify and update the API endpoint configuration for the Qwen provider. In Lobe Chat, the Qwen API endpoint is configured using the `LobeQwenAI` class, and the default URL is `https://dashscope.aliyuncs.com/compatible-mode/v1` [[1]](https://github.com/lobehub/lobe-chat/blob/main/src/libs/agent-runtime/qwen/index.ts). Ensure that this is the endpoint being used in your configuration.
> 
> Additionally, check if there are any environment variables that might be overriding the endpoint for Qwen. If you have set any such variables, make sure they point to the correct Qwen API endpoint.
> 
> If the issue persists, consider checking for any recent changes in the Lobe Chat database or configuration files that might have affected the Qwen API integration.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

請問Docker該如何修改呢?容器內找不到 src/libs/agent-runtime/qwen/index.ts

**Comment by arvinxx** [comment]
@hezhijie0327 帮忙看看？

**Comment by hezhijie0327** [comment]
复现出来了，让我想想咋触发的，全模型试了下就 QWEN 有问题

复现方法：不配置 `QWEN_API_KEY` 环境变量，手动输入 APIKey；若配置变量后，再手动输入 APIKey 则无影响

Work Around：先配置 `QWEN_API_KEY` 环境变量

**Comment by hezhijie0327** [comment]
大致是，我改了个小版本，在构建中等个结果

**Comment by soanhee** [comment]
> 大致是，我改了个小版本，在构建中等个结果

感謝回答，請問目前建議是等待官方更新Docker嗎?

**Comment by soanhee** [comment]
> 复现出来了，让我想想咋触发的，全模型试了下就 QWEN 有问题
> 
> 复现方法：不配置 `QWEN_API_KEY` 环境变量，手动输入 APIKey；若配置变量后，再手动输入 APIKey 则无影响
> 
> Work Around：先配置 `QWEN_API_KEY` 环境变量

在.env設定qwen api已解決，感謝大神
