### ISSUE TITLE
[Bug] 插件功能不能使用

### ISSUE THREAD

**Issue by Kac001** [lobehub/lobe-chat#4802]
### 📦 部署环境

Docker

### 📌 软件版本

v1.34.1

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

调用插件后，插件返回的结果不能正常调用
1.使用搜索插件，有结果返回，但是不能根据搜索结果做后续处理
![image](https://github.com/user-attachments/assets/b9b30c18-428b-49e1-a3c0-ae988940e6c6)
2.调用时间插件，有结果返回，但是会触发无限循环调用
![image](https://github.com/user-attachments/assets/d86a4c82-e1ae-44e2-b837-bfcf19a211e5)
![image](https://github.com/user-attachments/assets/267b2ceb-b1a6-406b-9d40-85561af014f9)

openai使用aihubmix

**Comment by arvinxx** [comment]
你的历史范围是不是设置的太少了

**Comment by Kac001** [comment]
这个我没修改过，我看了默认是1，把限制历史消息数关闭就没这个问题了
