### ISSUE TITLE
[Request] 自定义模型列表时如何在设置里还能选择其他?

### ISSUE THREAD

**Issue by SAnBlog** [lobehub/lobe-chat#4803]
### 🥰 需求描述

例如: BAICHUAN_MODEL_LIST=Baichuan4-Turbo,Baichuan4-Air,Baichuan4

聊天列表里只看到这3个模型没问题,但是进入设置里发现其他模型全部不可见,不是在-all,的情况下才会隐藏其他模型吗?
我想要的是默认显示一些优质模型的情况下,可以允许用户在设置里自主选择其他模型

### 🧐 解决方案

默认显示一些优质模型的情况下,可以允许用户在设置里自主选择其他模型

**Comment by SAnBlog** [comment]
![image](https://github.com/user-attachments/assets/114c1139-bd61-44ab-ae19-1687cd669eca)


类似这个效果,Gitee这个模型我并没有配置MODEL_LIST,默认有这种效果

**Comment by arvinxx** [comment]
MODEL_LIST 会直接覆盖 default 的模型列表。我最早做的时候是你这个需求的实现，但是很多人反馈用 MODEL_LIST 希望默认打开，所以就按覆盖的逻辑来做了。

考虑实现的复杂度和你这个需求的小众性（从 MODEL_LIST 4月改版到现在，似乎就你提了这个点），应该暂不会考虑支持这个特性
