### ISSUE TITLE
[Bug] Lobe language model runtime execution error with Qwen provider

### ISSUE THREAD

**Issue by duoartisan** [lobehub/lobe-chat#4809]
### 📦 Environment

Vercel

### 📌 Version

v1.34.0 to v1.34.2

### 💻 Operating System

Other Linux

### 🌐 Browser

Edge

### 🐛 Bug Description

when using any Qwen model of the Qwen provider, the following error message appears.
note that this issue only occurs using personally deployed lobe on vercel.
There is no such problem when using chat-preview.lobehub.com.

{
  "error": {
    "message": "Invalid URL string.",
    "name": "TypeError",
    "stack": "TypeError: Invalid URL string.\n    at (vc/edge/function:143:8948)\n    at (vc/edge/function:143:6681)\n    at (vc/edge/function:143:8032)\n    at (vc/edge/function:242:16648)\n    at (vc/edge/function:242:28984)\n    at (vc/edge/function:131:23318)\n    at (vc/edge/function:131:20923)\n    at (vc/edge/function:131:24621)\n    at (vc/edge/function:132:33139)\n    at (vc/edge/function:132:3743)"
  },
  "endpoint": "1111",
  "provider": "qwen"
}

### 📷 Recurrence Steps

talk to any agent using a qwen model from the qwen supplier.
![qwen](https://github.com/user-attachments/assets/5d5efeb4-5a77-47f6-a1cd-db44b513a5f4)

**Comment by arvinxx** [comment]
@hezhijie0327 qwen 还是有问题

**Comment by hezhijie0327** [comment]
@duoartisan 能贴下配置不，没复现出来...

**Comment by duoartisan** [comment]
> @duoartisan 能贴下配置不，没复现出来...

May I ask which configuration I should post?

**Comment by duoartisan** [comment]
> Has any ENV change on Vercel?
> 
> ```
> Error code
> "endpoint": "1111",
> ```

Hi, I haven't touched anything in Environment Variables since I deployed lobe on Vercel two months ago.

**Comment by hezhijie0327** [comment]
Do a conf reset first, if still no working, the try a rework
![image](https://github.com/user-attachments/assets/507db09f-315a-4568-8724-9a302307cd85)

**Comment by Liangpi000** [comment]
这两天更新后，我私有化部署的lobe，仅在环境变量里配置了openai的接口代理，但是别的模型服务商的代理地址也变成openai的了

**Comment by hezhijie0327** [comment]
> 这两天更新后，我私有化部署的lobe，仅在环境变量里配置了openai的接口代理，但是别的模型服务商的代理地址也变成openai的了

这个定位到问题所在了，稍后会补个 PR，fallback 判定行为异常
