### ISSUE TITLE
[Bug] Vercel部署失败

### ISSUE THREAD

**Issue by Winston1011** [lobehub/lobe-chat#4822]
### 📦 部署环境

Vercel

### 📌 软件版本

main最新分支

### 💻 系统环境

macOS

### 🌐 浏览器

Edge

### 🐛 问题描述

用action同步main分支，重新部署失败

### 📷 复现步骤

Attempted import error: 'Tongyi' is not exported from '@lobehub/icons' (imported as 'Tongyi').
Module not found: Can't resolve 'fs' in '/vercel/path0/node_modules/langfuse-core/lib'
Module not found: Can't resolve 'crypto' in '/vercel/path0/node_modules/langfuse-core/lib'
Failed to compile.
./src/app/(main)/settings/llm/ProviderList/providers.tsx:19:3
Type error: Module '"@lobehub/icons"' has no exported member 'Tongyi'.
  17 |   Stepfun,
  18 |   Together,
> 19 |   Tongyi,
     |   ^
  20 |   ZeroOne,
  21 |   Zhipu,
  22 | } from '@lobehub/icons';
error: script "build" exited with code 1
Error: Command "bun run build" exited with 1

### 🚦 期望结果

期望部署成功

**Comment by arvinxx** [comment]
你自己魔改过了吧。现在最新实现里这个文件已经没有Tongyi 的导入了

**Comment by Winston1011** [comment]
没有改过。。。用的是官网的action的方法进行同步的。。我重新拉一下仓库试试

**Comment by arvinxx** [comment]
@Winston1011 那要么就是没有完全同步到最新的实现？如果一点没有改过，完全自动同步的话，应该不会有这个问题的

**Comment by Winston1011** [comment]
已解决
