### ISSUE TITLE
[Bug] 使用 claude 模型，在触发“搜索引擎”插件后继续回答出错

### ISSUE THREAD

**Issue by Lockeysama** [lobehub/lobe-chat#4823]
### 📦 部署环境

Vercel

### 📌 软件版本

1.34.4

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

![LobeChat_Coder_2024-11-28](https://github.com/user-attachments/assets/d59c86b1-d397-4886-8393-a2e0dc89599b)

我使用 claude 模型进行提问，在问题触发“搜索引擎”插件查询，继续回答的时候，必现错误：
```json
{
  "error": {
    "error": {
      "type": "error",
      "error": {
        "type": "invalid_request_error",
        "message": "messages: at least one message is required"
      }
    },
    "status": 400,
    "headers": {
      "via": "1.1 google",
      "date": "Thu, 28 Nov 2024 03:08:06 GMT",
      "connection": "keep-alive",
      "request-id": "req_01FPixUjNDATdzvysZX4nxMQ",
      "content-type": "application/json",
      "x-robots-tag": "none",
      "content-length": "112",
      "x-should-retry": "false"
    },
    "request_id": "req_01FPixUjNDATdzvysZX4nxMQ"
  },
  "endpoint": "https://api.anthropic.com",
  "provider": "anthropic"
}
```

### 📷 复现步骤

1. 选择 claude 模型（Claude 3.5 Sonnet）
2. 提问（问题需要能触发搜索）
3. 等待搜索返回后继续等待回答

### 🚦 期望结果

回答有正常输出（不出错）

### 📝 补充信息

我是 github 手动同步更新的，最近一次更新是昨天，出现这个的时候是昨天更新了 Topic 功能，今天更新到最新版本，问题仍然存在。

-----------

![LobeChat_Coder_2024-11-28 (2)](https://github.com/user-attachments/assets/a9ef48e8-4cd1-46cd-93ac-aedff02b8b4a)

好像 GPT 也有相关的问题。看起来是搜索插件调用后，前面的上下文丢失了。

**Comment by arvinxx** [comment]
<img width="391" alt="image" src="https://github.com/user-attachments/assets/4339a7db-674e-4857-996f-56e9372f2de6">

你看下是不是开启了历史记录的限制？

**Comment by Lockeysama** [comment]
> <img alt="image" width="391" src="https://private-user-images.githubusercontent.com/28616219/390632907-4339a7db-674e-4857-996f-56e9372f2de6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NjU5ODAsIm5iZiI6MTczMjc2NTY4MCwicGF0aCI6Ii8yODYxNjIxOS8zOTA2MzI5MDctNDMzOWE3ZGItNjc0ZS00ODU3LTk5NmYtNTZlOTM3MmYyZGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDAzNDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3OGE2YzBiNGU0M2QxMWZkN2UyNjA5MTFjODIyMzFlNDk3YzYwMjVkZmI2YjQ4NWMxMWVmZDc5YmFmYzNmYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FoumuvYaZR4nAQ0HRMD1goeh6in9INZqyyYsxi_4phs">
> 你看下是不是开启了历史记录的限制？

好像确实是的，变成成 1 了。不过这块我印象中没有改过。😳

**Comment by arvinxx** [comment]
那应该是这个原因： https://github.com/lobehub/lobe-chat/issues/4663#issuecomment-2466667818

**Comment by zj1123581321** [comment]
"messages.0: `tool_use` blocks can only be in `assistant` messages

claude  function call 这个红包也是由于历史记录长度限制导致的，记录一下。

**Comment by arvinxx** [comment]
> "messages.0: `tool_use` blocks can only be in `assistant` messages
> 
> claude  function call 这个红包也是由于历史记录长度限制导致的，记录一下。

这个单独提个issue吧，我也发现了。要修下的

**Comment by zj1123581321** [comment]
> > "messages.0: `tool_use` blocks can only be in `assistant` messages
> > claude  function call 这个红包也是由于历史记录长度限制导致的，记录一下。
> 
> 这个单独提个issue吧，我也发现了。要修下的

已提：[[Bug] Claude 使用 function call + 开启限制历史消息数功能，报错：messages.0: `tool_use` blocks can only be in `assistant` messages · Issue #6556 · lobehub/lobe-chat](https://github.com/lobehub/lobe-chat/issues/6556)
