### ISSUE TITLE
[Bug] docker配置了OPENAI_MODEL_LIST之后，获取模型列表功能失效

### ISSUE THREAD

**Issue by skywolf123** [lobehub/lobe-chat#4828]
### 📦 部署环境

Docker

### 📌 软件版本

v1.34.4

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

docker配置了OPENAI_MODEL_LIST之后（+某个模型），比如+gpt-4-all=gpt-4-all<128000:fc:vision:file>,
在设置->语言模型->OpenAI->模型列表，显示"共1个模型可用"，点击"获取模型列表"不会刷新模型数量

**Comment by lfffffy** [comment]
Have the same problem

**Comment by arvinxx** [comment]
当你配置了 `OPENAI_MODEL_LIST` ，刷新模型按钮就是会失效。这是 by design，不是 bug
