### ISSUE TITLE
IP's blocked

### ISSUE THREAD

**Issue by sbkapase** [lobehub/lobe-chat#4829]
### 📦 Environment

Official Preview

### 📌 Version

2.25.1

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

Our Ip range 45.129.86.0/23 pool blocked by github.

### 📷 Recurrence Steps

Plase unblock this IP pool as soon as possible

### 🚦 Expected Behavior

Please solve this issues as soon as possible

**Comment by sbkapase** [comment]
Please check urgent as soon as possible. and resolve issue.

**Comment by breakstring** [comment]
？？？
I don't think this repo owner can Block your IP range in Github.

**Comment by sbkapase** [comment]
No sir,  I this IP pool blocked by Github.
Please advice how to white list this IP range

**Comment by breakstring** [comment]
> No sir, I this IP pool blocked by Github. Please advice how to white list this IP range

Maybe you can submit a ticket to [Github support](https://support.github.com/request) instead of this issue here.

**Comment by sbkapase** [comment]
Dear team,
  No any issue resolve. please check as soon as possible.
