### ISSUE TITLE
[Bug] logto用户注册后,报错

### ISSUE THREAD

**Issue by zhangnanchao** [lobehub/lobe-chat#4834]
### 📦 部署环境

Docker

### 📌 软件版本

lobehub/lobe-chat-database:latest

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

![1732864483260](https://github.com/user-attachments/assets/629ab2ce-f2f6-4683-ab85-e44c1229237f)
<img width="1329" alt="iShot_2024-11-29_15 15 20" src="https://github.com/user-attachments/assets/04ce1726-c63c-44c7-a664-abc7ce9f00d1">

### 📷 复现步骤

env
<img width="630" alt="iShot_2024-11-29_15 20 35" src="https://github.com/user-attachments/assets/2f49f70d-71cc-4659-9c5c-e4d0f0109ce7">
docker
<img width="608" alt="image" src="https://github.com/user-attachments/assets/a4830010-fdcd-49f2-bdd3-d2958fe0c3d7">
nginx
<img width="585" alt="image" src="https://github.com/user-attachments/assets/114ced99-3a97-4f92-af45-438bc0a68e74">
<img width="588" alt="image" src="https://github.com/user-attachments/assets/ddaa0419-eba3-45d9-ba3a-be904ee3318e">
logto
<img width="819" alt="image" src="https://github.com/user-attachments/assets/f2c16279-3ad6-406f-be26-07afc5934d69">

### 🚦 期望结果

用户注册后 页面报错，返回主页再点用户登陆，页面还是报错，去logto控制台删除该用户后，再去点登陆页面恢复正常，但是始终无法登陆

**Comment by zhangnanchao** [comment]
> @zhangnanchao大家好！我来这里是为了帮助您解决错误、问题并成为贡献者。让我们一起解决这些错误吧！🤖
> 
> I found a similar discussion regarding Logto login issues in the lobe-chat repository. The discussion is titled "[请问 logto 登录的问题，可否帮忙看下，下面提供了具体的配置](https://github.com/lobehub/lobe-chat/discussions/4221)" and it was last updated on September 30, 2024. The suggested solution in a related closed issue was to configure the `NEXTAUTH_URL` variable according to the documentation [[1]](https://github.com/lobehub/lobe-chat/discussions/4221).
> 
> 对于使用 Logto 后用户注册和登录错误的具体问题，请确保所有环境变量均已正确设置，尤其是与 Logto 和身份验证相关的环境变量。以下是需要检查的一些关键变量：
> 
> * `AUTH_LOGTO_ID`：确保将其设置为 Logto 应用程序中的正确客户端 ID。
> * `AUTH_LOGTO_SECRET`：确保将其设置为 Logto 应用程序中的正确客户端密钥。
> * `AUTH_LOGTO_ISSUER`：这应该设置为正确的 OpenID Connect 发行者 URL。
> * `NEXTAUTH_URL`：这应该设置为正确的回调URL，例如`https://lobe.example.com/api/auth`。
> 
> 此外，请验证您的 Logto 应用程序是否配置了正确的重定向 URI 和 CORS 设置，如文档[[2]](https://github.com/lobehub/lobe-chat/blob/main/docs/self-hosting/advanced/auth/next-auth/logto.mdx)中所述。如果问题仍然存在，请仔细检查您的 Docker 和 Nginx 配置，以确保它们与 lobe-chat 应用程序的预期设置一致。
> 
> _[要继续与Dosu](https://dosu.dev)交谈，请提及@dosu。_

<img width="482" alt="image" src="https://github.com/user-attachments/assets/a93c07cf-afe0-452b-aa3d-057335a40409">
已经设置 cors了

**Comment by arvinxx** [comment]
@cy948 和 #4826 是否有关系？

**Comment by cy948** [comment]
> @cy948 和 #4826 是否有关系？

这个错误和 #4826 中删除 `redirectUrl` 没有关系，但可以在这个 pr 中加入日志打印。不打印的话基本没法解决定位当前 issue 的问题。

**Comment by cy948** [comment]
看错误描述，是 token endpoint 的响应有问题，如果你想继续使用 Logto，可以前往 `/console/audit-logs` 看看日志报错。我的建议是更换认证 provider 到 casdoor 。

**Comment by zhangnanchao** [comment]
> 看看这个设置的刷新令牌开关有没有打开 ![图像](https://private-user-images.githubusercontent.com/67412196/391150166-bbc691ed-1be8-454e-be9d-ab5307613c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NTI1NTgsIm5iZiI6MTczMjk1MjI1OCwicGF0aCI6Ii82NzQxMjE5Ni8zOTExNTAxNjYtYmJjNjkxZWQtMWJlOC00NTRlLWJlOWQtYWI1MzA3NjEzYzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDA3MzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NTEyNzNhYzk1OTYwNWIzMWRlNTU5NzBhMWM4NDVjZGE4MWEzOWU0OGRiNWUyM2ZmMDdhMzU3MWExNTU5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2N9au5AEboHCOey5hz55ZKgv7LK2HYevY-cFW8SY904)

这个打开了

**Comment by cy948** [comment]
等待 #4826 合并后使用新版本的 `debug` 模式再进行排错吧。

**Comment by cy948** [comment]
logto的ssl证书是自签名吗？

**Comment by zhangnanchao** [comment]
> logto的ssl证书是自签名吗？

不是 ，是阿里云颁发的，我现在用的casdoor ，是可以用的

**Comment by cy948** [comment]
那先用着 Casdoor 吧
