### ISSUE TITLE
[Question] 很抱歉，服务器不支持您使用的请求方法，请确认您的请求方法是否正确

### ISSUE THREAD

**Issue by onlinedear** [lobehub/lobe-chat#484]
### 🧐 问题描述 | Proposed Solution

语音合成声源
为当前助手挑选一个声音，不同 TTS 服务支持的声源不同

点击播放提示：“很抱歉，服务器不支持您使用的请求方法，请确认您的请求方法是否正确”

### 📝 补充信息 | Additional Information

我在vercel里部署的，请问我需要如何设置，使其TTS正常运行。谢谢

**Comment by arvinxx** [comment]
查看下是否是这个问题 ：https://github.com/lobehub/lobe-chat/discussions/483#discussioncomment-7616769
