### ISSUE TITLE
[Docs] Feedback for `usage/providers/wenxin`

### ISSUE THREAD

**Issue by lybtt** [lobehub/lobe-chat#4852]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/usage/providers/wenxin.zh-CN.mdx

### 🐛 Feedback

_Your response_

![image](https://github.com/user-attachments/assets/831dcfc4-494d-4a96-9441-4fb40677b5bb)

**Comment by arvinxx** [comment]
错误 msg 为 IAM Certification failed 估计是你的鉴权配置啥的有问题吧

**Comment by lybtt** [comment]
> 错误 msg 为 IAM Certification failed 估计是你的鉴权配置啥的有问题吧

看起来是百度那边更新了什么可能.
![image](https://github.com/user-attachments/assets/e2e4546f-aeac-4093-b0ce-e207c90538b4)

**Comment by Sun-drenched** [comment]
你应该是填错了API key 、secret key。不能用千帆ModelBuilder-应用接入里的key，而是要用到全局（账户）安全认证-Access Key里的两个key
