### ISSUE TITLE
[Request] 向量存储额度的订阅包/加量包

### ISSUE THREAD

**Issue by LeoStruggle666** [lobehub/lobe-chat#4858]
### 🥰 需求描述

我工作的角色比较复杂，会涉及到很多不同方向的内容，以及需要引用到大量内外部文档。目前**知识库**对我是个非常重要&核心的功能，但目前瓶颈是知识库向量存储额度太小了，而说实话39.9刀/月档位的订阅也超出了个人承受范围..

### 🧐 解决方案

期望能对向量存储额度单独开个订阅包/加量包,并也能开放给自助版的订阅用户

**Comment by arvinxx** [comment]
@LeoStruggle666 这个有计划的，估计1月左右会上线，敬请期待~
