### ISSUE TITLE
[Bug] "智能重命名"失效

### ISSUE THREAD

**Issue by LeoStruggle666** [lobehub/lobe-chat#4862]
### 📦 部署环境

Official Preview

### 📌 软件版本

线上的版本v1.34.5

### 💻 系统环境

macOS

### 🌐 浏览器

Other

### 🐛 问题描述

如以下GIF演示，有正常配置模型，但话题里的“智能重命名”功能似乎从来没生效过，不论是直接开启新话题（预期会自动触发），还是手动触发。是漏掉了什么配置或者使用流程上有误嘛？
![PixPin_2024-12-02_14-28-27](https://github.com/user-attachments/assets/3f1439b2-7467-4cb7-9dba-e282a6fa8f39)

### 📷 复现步骤

不论是直接开启新话题（预期会自动触发），还是手动触发，都不会智能重命名话题

### 🚦 期望结果

预期会智能重命名话题

### 📝 补充信息

我是自助版订阅用户

**Comment by arvinxx** [comment]
请前往应用设置 -> 系统助手 那边，选择你的 provider 的模型。默认应该选择的都是 lobehub 这个 provider。

<img width="1189" alt="image" src="https://github.com/user-attachments/assets/320dc3fa-7b9b-4be8-9dfb-346979edf808">
