### ISSUE TITLE
@trpc/next need next@15.0.3

### ISSUE THREAD

**Issue by Gray19970** [lobehub/lobe-chat#4882]
### 📦 Environment

Other

### 📌 Version

latest

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

最新版本的代码，拉到本地npm install 报错@trpc/next 需要 next@15.0.3 ，改了之后其他的又不兼容了，怎么办
![Uploading 1.png…]()

### 🚦 Expected Behavior

1

**Comment by arvinxx** [comment]
不需要 next15 吧，它的范围很宽

<img width="730" alt="image" src="https://github.com/user-attachments/assets/28fac604-a520-491f-980f-7e242681f7e5">
