### ISSUE TITLE
[Bug] 只配置了spark 4.0 api，

### ISSUE THREAD

**Issue by FormatToday** [lobehub/lobe-chat#4884]
### 📦 部署环境

Docker

### 📌 软件版本

latest

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

只配置了星火4.0的key，随便聊聊最上面显示的也是4.0Ultra，但是聊天却好像还是走的openAI。
![image](https://github.com/user-attachments/assets/875aafae-33b1-44a4-b001-8b2681f8c870)
环境变量只配置了下面这几个
![image](https://github.com/user-attachments/assets/68986c1c-370d-4ae2-9bec-c2e7f5b56bfe)

### 🚦 期望结果

随便聊聊 也使用4.0Ultra回复。

**Comment by arvinxx** [comment]
default agent config 需要配置 provider
