### ISSUE TITLE
[Bug] Docker compose一键脚本 无法登录

### ISSUE THREAD

**Issue by BaituLime** [lobehub/lobe-chat#4891]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Other Linux

### 🌐 Browser

Firefox

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/b69a102e-14f2-42d6-ab90-c599309695ce)
使用一键脚本部署，会出现无法登录的问题。
可以注意到这里是localhost，所以基本可以排除网络问题。

### 📷 Recurrence Steps

 bash <(curl -fsSL https://raw.githubusercontent.com/lobehub/lobe-chat/HEAD/docker-compose/local/setup.sh) -f -l zh_CN
 docker compose up -d
 打开firefox
登录
出错

### 🚦 Expected Behavior

可以登录

### 📝 Additional Information

[auth][error] InvalidCheck: State could not be decoded. Read more at https://errors.authjs.dev#invalidcheck
    at Object.decode (/app/.next/server/chunks/73905.js:368:27844)
    at async iz (/app/.next/server/chunks/73905.js:368:40134)
    at async i0 (/app/.next/server/chunks/73905.js:368:51902)
    at async i2 (/app/.next/server/chunks/73905.js:368:56596)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
    at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/base-server.js:1359:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/base-server.js:1581:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/base-server.js:1489:28)
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}

**Comment by cy948** [comment]
请提供 `bash <(curl -fsSL https://raw.githubusercontent.com/lobehub/lobe-chat/HEAD/docker-compose/local/setup.sh) -f -l zh_CN` 这段指令的运行日志。

**Comment by cy948** [comment]
另外，请检查系统中是否有 `sed` 及 `openssl` 
```bash
sed --verison
openssl version
```

**Comment by BaituLime** [comment]
@cy948 
 bunny@RabbitServer  /main/LobeChatTest   bash <(curl -fsSL https://raw.githubusercontent.com/lobehub/lobe-chat/HEAD/docker-compose/local/setup.sh) -f -l zh_CN
docker-compose.yml            100%[=================================================>]   2.95K  --.-KB/s    in 0s
.env                          100%[=================================================>]   1.03K  --.-KB/s    in 0s
init_data.json                100%[=================================================>]  25.38K  --.-KB/s    in 0.01s
s3_data.tar.gz                100%[=================================================>]  11.77K  --.-KB/s    in 0.001s
s3_data.tar.gz 解压成功到目录： .
重新生成安全密钥...
安全密钥生成结果如下：
Casdoor:
 - Username: admin
  - Password: 9ed60d
  - Client Secret: 98751fc0075f3956e8606c4dbe891903

您已经完成了所有配置。请运行以下命令启动LobeChat：

                                                  docker compose up -d

完整的环境变量在'.env'中可以在文档中找到：https://lobehub.com/zh/docs/self-hosting/environment-variables

警告：如果你正在生产环境中使用，请在日志中检查密钥是否已经生成！！！

 bunny@RabbitServer  /main/LobeChatTest   sed --verison                                                   20:11:45
openssl version
sed: unrecognized option '--verison'
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...

  -n, --quiet, --silent
                 suppress automatic printing of pattern space
      --debug
                 annotate program execution
  -e script, --expression=script
                 add the script to the commands to be executed
  -f script-file, --file=script-file
                 add the contents of script-file to the commands to be executed
  --follow-symlinks
                 follow symlinks when processing in place
  -i[SUFFIX], --in-place[=SUFFIX]
                 edit files in place (makes backup if SUFFIX supplied)
  -l N, --line-length=N
                 specify the desired line-wrap length for the `l' command
  --posix
                 disable all GNU extensions.
  -E, -r, --regexp-extended
                 use extended regular expressions in the script
                 (for portability use POSIX -E).
  -s, --separate
                 consider files as separate rather than as a single,
                 continuous long stream.
      --sandbox
                 operate in sandbox mode (disable e/r/w commands).
  -u, --unbuffered
                 load minimal amounts of data from the input files and flush
                 the output buffers more often
  -z, --null-data
                 separate lines by NUL characters
      --help     display this help and exit
      --version  output version information and exit

If no -e, --expression, -f, or --file option is given, then the first
non-option argument is taken as the sed script to interpret.  All
remaining arguments are names of input files; if no input files are
specified, then the standard input is read.

GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.
OpenSSL 3.4.0 22 Oct 2024 (Library: OpenSSL 3.4.0 22 Oct 2024)

**Comment by cy948** [comment]
1. 提问： 是第一次部署，即在运行脚本前， `./s3_data` 和 `./data` 为空？
2. 请尝试：按照 casdoor 文档 https://lobehub.com/zh/docs/self-hosting/advanced/auth/next-auth/casdoor 检查一下lobe启动的环境变量中的 client id 和 client secrect 和 casdoor 后台显示的 id 和 secrect 是否一致。

**Comment by BaituLime** [comment]
@cy948 
1. 是的，为空
2. 这个我昨天就怀疑并试过了，一致的

**Comment by cy948** [comment]
等 #4826 合并后使用debug选项排查吧 目前没复现你的问题。

**Comment by cy948** [comment]
启动时添加环境变量 `NEXT_AUTH_DEBUG=1` 打一下日志看看。
