### ISSUE TITLE
[Bug] gemini用不了，已经订阅一个月

### ISSUE THREAD

**Issue by xuanyu2012** [lobehub/lobe-chat#4898]
### 📦 部署环境

Official Preview

### 📌 软件版本

网站

### 💻 系统环境

Android

### 🌐 浏览器

Chrome

### 🐛 问题描述

无法使用gemini，{
  "message": "litellm.APIConnectionError: APIConnectionError: OpenAIException - Provider returned error",
  "provider": "lobehub",
  "errorType": "ProviderBizError"
}

**Comment by arvinxx** [comment]
你好，请联系 support@lobehub.com 提供技术支持~
