### ISSUE TITLE
[Request] 希望有办法同步聊天记录以方便多端使用

### ISSUE THREAD

**Issue by ChenChen61882** [lobehub/lobe-chat#491]
### 🥰 需求描述 | Feature Description

如题，希望电脑端和手机端的聊天记录同步，不知道是不是已经有这个功能？

### 🧐 解决方案 | Proposed Solution

我知道这个可能存在成本，那么考虑增加同步选项，用户提供自己的云盘账户即可同步。

**Comment by canisminor1990** [comment]
请关注 【[RFC] 009 - 跨端同步WebDAV & YJS】动态 https://github.com/lobehub/lobe-chat/discussions/368

**Comment by arvinxx** [comment]
我们在 `v0.141.0` 上线了基于 YJS 与 WebRTC 的实验性数据同步功能，欢迎测试并反馈：
- 反馈issue: #1683
- 背后思考：https://github.com/lobehub/lobe-chat/discussions/1681

如果上述同步功能不满足你的诉求，可以 Reopen 该issue
