### ISSUE TITLE
[Request] 使用Dokploy部署Lobechat

### ISSUE THREAD

**Issue by SpeedupMaster** [lobehub/lobe-chat#4916]
### 🥰 需求描述

自己构建docker镜像使用clerk还是有点麻烦，想使用Dokploy替代Vercel部署Lobechat，使用clerk作为身份验证服务，并实现自动更新。
目前遇到两个报错
```
#11 10.62 npm ERR! Found: eslint@8.57.1
#11 10.62 npm ERR! node_modules/eslint
#11 10.62 npm ERR! dev eslint@"^8.57.1" from the root project
#11 10.62 npm ERR! peer eslint@"^8.57.0 || ^9.0.0" from @typescript-eslint/eslint-plugin@8.17.0
#11 10.63 npm ERR! node_modules/@typescript-eslint/eslint-plugin
#11 10.63 npm ERR! peerOptional @typescript-eslint/eslint-plugin@"^8.0.0-0" from eslint-plugin-unused-imports@4.0.1
```
```
367.0 > @lobehub/chat@1.36.0 build-migrate-db
367.0 > bun run db:migrate
367.0 
367.0 sh: 1: bun: not found
```

### 🧐 解决方案

`package.json`文件中的`devDependencies`里添加 `bun` 、`eslint` 使用 `^9.0.0` 版本。

![image](https://github.com/user-attachments/assets/d40b0690-82a0-47a7-a00d-06ee55d626d9)

经测试可以成功部署

**Comment by arvinxx** [comment]
1. 安装依赖不要用npm，用 bun 或者 pnpm 安装；
2. 找不到 bun 是因为你系统本地没有安装bun，请参考官网安装： https://bun.sh/

**Comment by arvinxx** [comment]
另外也欢迎提交一个使用 Dokploy 部署LobeChat 的文档PR~

**Comment by SpeedupMaster** [comment]
> 1. 安装依赖不要用npm，用 bun 或者 pnpm 安装；
> 
>     2. 找不到 bun 是因为你系统本地没有安装bun，请参考官网安装： https://bun.sh/

![图片](https://github.com/user-attachments/assets/a95baaf6-b478-40ea-ba91-6ef79a744b85)
Dokploy默认的Nixpacks用的npm，暂时不知道怎么改成pnpm。

bun VPS上是有安装的

**Comment by SpeedupMaster** [comment]
> 另外也欢迎提交一个使用 Dokploy 部署LobeChat 的文档PR~

这个我到时候看看怎么写一个
