### ISSUE TITLE
[Bug] 主题搜索不搜索内容 描述

### ISSUE THREAD

**Issue by CGamesPlay** [lobehub/lobe-chat#493]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

The global search function indexes all content from all conversation (see #1 in picture). However, the per-agent topic search indexes only the titles (see #3 in picture).

全局搜索功能索引了所有对话的所有内容（见图片中的#1）。然而，每个客服人员的主题搜索只索引标题（见图片中的#3）。

### 🚦 期望结果 | Expected Behavior

I would like the per-agent topic search to search through all content from each conversation.

我希望每个客服人员的主题搜索能够搜索每个对话的所有内容。

### 📷 复现步骤 | Recurrence Steps

1. Create an agent and ask it "Please list 6 citrus fruits".
2. Search in the main search list for "Grapefruit". Notice the agent you created.
3. Search in the agent's topic lists for "Grapefruit". Notice there are no results.

1. 创建一个客服人员，并询问它“请列出6种柑橘水果”。
2. 在主搜索列表中搜索“葡萄柚”。注意到你创建的客服人员。
3. 在客服人员的主题列表中搜索“葡萄柚”。注意到没有结果。

### 📝 补充信息 | Additional Information

<img width="1367" alt="Pasted_Image_11_21_23__09_40" src="https://github.com/lobehub/lobe-chat/assets/1216626/542fe803-8ea2-4bbc-9e54-cd1bd9bae6b3">

**Comment by arvinxx** [comment]
You are right, we need to improve this.
