### ISSUE TITLE
[Request] 希望能提供casdoor的域名部署方案

### ISSUE THREAD

**Issue by sonnyyin** [lobehub/lobe-chat#4932]
### 🥰 需求描述

目前使用docker的本地部署方式（local文件中的配置文件）部署了lobe-chat，lobe本地/内网访问casdoor正常，minio正常。手动修改成域名，并且对域名进行了反向代理（暴露端口是http:6500），lobe前端打开正常，但是登陆时无法跳转到casdoor登陆界面，即使给casdoor单独映射一个外网端口，使用域名或外网IP修改AUTH_CASDOOR_ISSUER仍旧无法跳转，提示如下图：
![图片](https://github.com/user-attachments/assets/fb49e623-6249-469c-8363-57cace9d921b)

后台提示错误如下：
lobe-chat      | [auth][error] TypeError: fetch failed
lobe-chat      |     at node:internal/deps/undici/undici:13392:13
lobe-chat      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lobe-chat      |     at async iB (/app/.next/server/chunks/88906.js:368:46924)
lobe-chat      |     at async iG (/app/.next/server/chunks/88906.js:368:49798)
lobe-chat      |     at async i0 (/app/.next/server/chunks/88906.js:368:52440)
lobe-chat      |     at async i2 (/app/.next/server/chunks/88906.js:368:56596)
lobe-chat      |     at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
lobe-chat      |     at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
lobe-chat      |     at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
lobe-chat      |     at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/base-server.js:1359:42)
lobe-chat      | [NextAuth] Error: {
lobe-chat      |   cause: 'Configuration',
lobe-chat      |   message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
lobe-chat      |   name: 'NextAuth Error'
lobe-chat      | }

单独使用casdoor的域名/IP访问是正常的，如下图：
![图片](https://github.com/user-attachments/assets/d34dc8fb-8a1b-4eb7-aa10-63b68562310f)

只将casdoor环境变量及docker-compose文件中的AUTH_CASDOOR_ISSUER、origin改回为内网ip地址，lobe可以访问到casdoor的登录界面。
针对这个情况折腾了一下午，还是没搞定。

### 🧐 解决方案

希望有大神给与指导，期待官方能给出casdoor的域名部署方案。

**Comment by SpeedupMaster** [comment]
域名后面应该不需要 :6500 吧

**Comment by Sun-drenched** [comment]
注意一下NEXTAUTH_URL这个变量有没有设置正确

**Comment by sonnyyin** [comment]
> 注意一下NEXTAUTH_URL这个变量有没有设置正确

这个设置了也不行，很奇怪

**Comment by sonnyyin** [comment]
> 域名后面应该不需要 :6500 吧

我服务器对外暴漏的端口不是80跟443，所以加了端口号。

**Comment by Lovest20018** [comment]
貌似跟我一样，同样用casdoor ，ip模式下正常，域名模式下同样的错误，同样需要加端口号访问。

**Comment by sonnyyin** [comment]
这个问题貌似是我自己网络环境的问题，现在已经解决了，我的服务器网络层网关这块解析有点问题，在网关配置好DNS解析就可以使用了。
