### ISSUE TITLE
[Request] 更新智普模型,新出了一个免费的视图模型glm-4v-flash

### ISSUE THREAD

**Issue by SAnBlog** [lobehub/lobe-chat#4933]
### 🥰 需求描述

![image](https://github.com/user-attachments/assets/52baf7ae-e4db-4027-8503-d54336872e27)

### 🧐 解决方案

更新智普模型列表:glm-4v-flash

**Comment by dupl** [comment]
更新了踢我一脚

**Comment by BiFangKNT** [comment]
> 更新了踢我一脚

github是可以点订阅的，并且你回复之后会自动开启订阅
