### ISSUE TITLE
[Bug] Unraid 数据库版Docker更新后，AUTH0无法登录

### ISSUE THREAD

**Issue by iparanoid** [lobehub/lobe-chat#4940]
### 📦 Environment

Docker

### 📌 Version

1.36.3

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

Unraid部署数据库版本一直稳定使用，最近更新lobechat容器后，发现无法登录了
使用chrome点击登录后显示
<img width="1989" alt="image" src="https://github.com/user-attachments/assets/b32ab139-625b-40af-bc83-a14a76cb02a7">

以下是相关配置，按理说是正确的，因为之前一直是正常的
<img width="979" alt="image" src="https://github.com/user-attachments/assets/ae718aef-abbe-4928-82ee-b87ad86932b7">
<img width="919" alt="image" src="https://github.com/user-attachments/assets/d8fb0e62-8adf-4f48-a1be-ea03e95c451b">

再附上Docker的容器日志
`🌐 DNS Server: [ '172.27.1.10' ]
[Database] Start to migration...
✅ database migration pass.
  ▲ Next.js 14.2.8
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210

 ✓ Starting...
 ✓ Ready in 145ms
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}`

**Comment by arvinxx** [comment]
@cy948 来看看？

**Comment by cy948** [comment]
环境变量加 `NEXT_AUTH_DEBUG=1` 再启动，看看日志。

**Comment by iparanoid** [comment]
> 环境变量`NEXT_AUTH_DEBUG=1`再次启动，查看日志。

不好意思，打扰了 经过排查，是我家中的网关配置出现了问题，不是lobechat的问题
