### ISSUE TITLE
[Bug] getaddrinfo ENOTFOUND chat-plugins.lobehub.com 链接插件网的时候报错

### ISSUE THREAD

**Issue by saralaaga** [lobehub/lobe-chat#4948]
### 📦 部署环境

Docker

### 📌 软件版本

v1.36.2

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

2024-12-10 09:10:30  [TypeError: fetch failed] {
2024-12-10 09:10:30   cause:  [Error: Client network socket disconnected before secure TLS connection was established] {
2024-12-10 09:10:30   code: 'ECONNRESET',
2024-12-10 09:10:30   path: undefined,
2024-12-10 09:10:30   host: 'chat-plugins.lobehub.com',
2024-12-10 09:10:30   port: 443,
2024-12-10 09:10:30   localAddress: null
2024-12-10 09:10:30 }
2024-12-10 09:10:30 }
之前一直链接不上 chat-plugins.lobehub.com 根据claude 的建议对alpine容器安装了几个插件，问题仍然没解决。
求问一下该如何解决？如果要配置代理的话如何配置

**Comment by hezhijie0327** [comment]
`ECONNRESET` 链接重置的话，应该是网络环境问题，可能被墙干扰了，看看下面两个命令有啥结果：
1. `wget -O - https://chat-plugins.lobehub.com`
2. `nslookup chat-plugins.lobehub.com`

或者像dosubot提供的方案，设置下全局代理模式看看

**Comment by hezhijie0327** [comment]
从结果上看上去应该没啥问题... 这问题是偶发还是必现？

要么设置下 `PROXY_URL` 变量，走全局代理看看

**Comment by saralaaga** [comment]
> 从结果上看上去应该没啥问题... 这问题是偶发还是必现？
> 
> 要么设置下 `PROXY_URL` 变量，走全局代理看看
请求gpt的api的时候没有遇到过这个问题，请求claude的时候遇到了这个问题。请问下设置PROXY_URL是设置docker-compose.yml文件，让其走宿主机的代理吗？

**Comment by hezhijie0327** [comment]
你的代理地址如果是 Host 的 127.0.0.1 的话，把地址改为 `host.docker.internal`

**Comment by saralaaga** [comment]
似乎是解决了，只是现在用artifacts模式会出现type error
<img width="682" alt="image" src="https://github.com/user-attachments/assets/34488b6d-730c-4dce-941e-e0bfbee7a8e4">
{
  "name": "TypeError",
  "stack": "TypeError: Cannot read properties of undefined (reading 'stop_reason')\n    at ee (http://localhost:3210/_next/static/chunks/25604-1a8570c55b21445b.js:1:21076)\n    at Object.transform (http://localhost:3210/_next/static/chunks/25604-1a8570c55b21445b.js:1:11506)",
  "message": "Cannot read properties of undefined (reading 'stop_reason')"
}
不知道是不是代理商的问题

**Comment by vual** [comment]
我也遇到了，目测是因为lobehub.com域名没有备案，直接被拦了。
