### ISSUE TITLE
[Bug] Broken image optimization in docker standalone builds

### ISSUE THREAD

**Issue by Trugamr** [lobehub/lobe-chat#495]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Running application using docker results in missing `sharp` errors in docker logs when we navigate to page with images.
![image_2023-11-21_12-13-32](https://github.com/lobehub/lobe-chat/assets/10532751/92bdfff9-26cf-4560-96b4-32c72aba9313)

Fixed by #494 

### 🚦 期望结果 | Expected Behavior

Images shown with `next/image` should be optimized but are not due to missing `sharp` depedency.

### 📷 复现步骤 | Recurrence Steps

Running application using docker and navigating to page with images
```shell
docker run --rm --env-file .env -p 3210:3210 lobehub/lobe-chat:v0.103.0
```

### 📝 补充信息 | Additional Information

We can install `sharp` package explicitly in `Dockerfile` but I don't think it would be an issue if it's an application dependency since next can figure out when to use it.

**Comment by arvinxx** [comment]
it should be fixed in #494, Thanks for your contribution!
