### ISSUE TITLE
[Bug] dockerfile部署Type error: Cannot find module '@lobehub/ui/es/LogoThree' or its corresponding type declarations.

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-chat#4952]
### 📦 部署环境

Docker

### 📌 软件版本

1.36.5

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

使用dockerfile部署提示下面错误，已经加了--no-cache
450.1 ./src/components/Branding/WelcomeLogo/LobeChat.tsx:7:40
450.1 Type error: Cannot find module '@lobehub/ui/es/LogoThree' or its corresponding type declarations.
450.1
450.1    5 | import { Center } from 'react-layout-kit';
450.1    6 |
450.1 >  7 | const LogoThree = dynamic(() => import('@lobehub/ui/es/LogoThree'), { ssr: false });
450.1      |                                        ^
450.1    8 | const LogoSpline = dynamic(() => import('@lobehub/ui/es/LogoThree/LogoSpline'), { ssr: false });
450.1    9 |
450.1   10 | const WelcomeLogo = memo<{ mobile?: boolean }>(({ mobile }) => {

### 📷 复现步骤

docker build -t lobechat --build-arg USE_CN_MIRROR=true --no-cache .

**Comment by bestZwei** [comment]
vercel也遇到了

**Comment by arvinxx** [comment]
升级到最新的版本
