### ISSUE TITLE
[Request] 登陆

### ISSUE THREAD

**Issue by wayliums** [lobehub/lobe-chat#496]
### 🥰 需求描述 | Feature Description

添加登陆的 支持

### 🧐 解决方案 | Proposed Solution

如果我想添加登陆的支持，要等db重构后么？加到什么地方比较合适？

**Comment by arvinxx** [comment]
参考 @mushan0x0 的 [lobe.ai0x0.com](https://lobe.ai0x0.com/)，算是一种方案。 https://github.com/lobehub/lobe-chat/issues/171#issuecomment-1812769138 。

LobeChat 本身不会内置登录模块的
