### ISSUE TITLE
[Bug] ollama检查无法通过

### ISSUE THREAD

**Issue by elcky** [lobehub/lobe-chat#4962]
### 📦 Environment

Docker

### 📌 Version

v1.35.10以及今天才拉的最新docker版本

### 💻 Operating System

Windows, Ubuntu

### 🌐 Browser

Chrome, Edge

### 🐛 Bug Description

ollama里面的设置检查始终无法通过，报下面的问题：
Ollama 服务连接失败，请检查 Ollama 是否运行正常，或是否正确设置 Ollama 的跨域配置
Show Details
json
{
  "host": "http://192.168.1.23:11434",
  "message": "please check whether your ollama service is available or set the CORS rules",
  "provider": "ollama"
}

DIFY以及maxkb都能正常访问，直接访问跨域的ollama地址也没问题，浏览器直接访问与检测在ollama服务器端显示得不一样，浏览器访问显示的是post方法，配置检查时发送给ollama server是options.

**Comment by elcky** [comment]
上面的建议没有作用，另外发现无论是否打开“使用客户端请求模式“，都是通过client电脑的ip访问的ollama

**Comment by elcky** [comment]
> 直接去对话窗口对话呢？

直接输出提示去下载安装ollama，及设置OLLAMA_ORIGINS。

**Comment by dellnoantechnp** [comment]
一样的问题，即使添加了  `OLLAMA_ORIGINS=*` 环境变量，仍然提示跨域
