### ISSUE TITLE
[Request] 希望增加one-api支持

### ISSUE THREAD

**Issue by 3qingmi** [lobehub/lobe-chat#4966]
### 🥰 需求描述

1、希望增加支持[one-api](https://github.com/songquanpeng/one-api)，我已经把自己的api托管到one-api了，不希望在lobechat再配置一次

2、我使用的是社区版，但似乎每换一个浏览器都需要重新配置一遍我的api，请问配置文件不能保存在服务端吗

### 🧐 解决方案

1、增加one-api支持
2、增加服务的配置保存功能

**Comment by SpeedupMaster** [comment]
配置环境变量
```
OPENAI_API_KEY=
OPENAI_MODEL_LIST=
OPENAI_PROXY_URL=
```

**Comment by breakstring** [comment]
> ### 🥰 需求描述
> 1、希望增加支持[one-api](https://github.com/songquanpeng/one-api)，我已经把自己的api托管到one-api了，不希望在lobechat再配置一次
> 
> 2、我使用的是社区版，但似乎每换一个浏览器都需要重新配置一遍我的api，请问配置文件不能保存在服务端吗
> 
> ### 🧐 解决方案
> 1、增加one-api支持 2、增加服务的配置保存功能
> 
> ### 📝 补充信息
> _No response_

本身是支持One-API 的呀
你这是。。。自部署的非数据库版本？

**Comment by liuluyanglly** [comment]
有讨论群吗。

**Comment by Sun-drenched** [comment]
> > > 机器人检测到问题主体的语言不是英语，自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > 
> > 
> > > ### 🥰 需求描述
> > > 
> > > 1. 我希望增加对[one-api](https://github.com/songquanpeng/one-api)的支持。我已经在 one-api 上托管了我的 api，不想在 lobechat 中再次配置它。
> > > 2. 我使用的是社区版本，但似乎每次更换浏览器时都需要重新配置 API。配置文件不能保存在服务器上吗？
> > > 
> > > ### 🧐 解决方案
> > > 
> > > 1. 添加one-api支持2.添加服务配置保存功能
> > > 
> > > ### 📝 补充信息
> > > _没有回应_
> > 
> > 
> > 它本身就支持One-API。 这个是你。。。自行部署的非数据库版本？
> 
> Yes, I deployed it with docker using the following command. I just want a simple chat UI, but I found that this version doesn't have many features. That is, if I want to support one-api, configure storage, do I need to deploy a database version? This seems too heavyweight to me.
> 
> ```
> $ docker run -d -p 3210:3210 \
>   -e OPENAI_API_KEY=sk-xxxx \
>   -e ACCESS_CODE=lobe66 \
>   --name lobe-chat \
>   lobehub/lobe-chat
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/33386763/394609348-fd6bf257-2aa0-47f2-9001-c05befdd7110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDA5NzAsIm5iZiI6MTczNDAwMDY3MCwicGF0aCI6Ii8zMzM4Njc2My8zOTQ2MDkzNDgtZmQ2YmYyNTctMmFhMC00N2YyLTkwMDEtYzA1YmVmZGQ3MTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDEwNTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMTEwYzU2MWQyNGNhMDI3MTQyOTU5MDgzNzhjMTJmNTgyZmEzOWI3OWY4ZDc3YmFiMDRhYjc2M2Y2MWJjZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YrGrIJlINoJTotDYnIVuVmYvL1xyJyJ1m2e3STJlx0k)

Fill in OPENAI_API_KEY, OPENAI_MODEL_LIST, and OPENAI_PROXY_URL according to your one-api configuration. This does not require the server database version.
If you need to synchronize account settings on multiple devices, you must use the server database version.

**Comment by chenchengzi** [comment]
> > > 机器人检测到问题主体的语言不是英语，自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > 
> > 
> > > ### 🥰 需求描述
> > > 
> > > 1. 我希望增加对[one-api](https://github.com/songquanpeng/one-api)的支持。我已经在 one-api 上托管了我的 api，不想在 lobechat 中再次配置它。
> > > 2. 我使用的是社区版本，但似乎每次更换浏览器时都需要重新配置 API。配置文件不能保存在服务器上吗？
> > > 
> > > ### 🧐 解决方案
> > > 
> > > 1. 添加one-api支持2.添加服务配置保存功能
> > > 
> > > ### 📝 补充信息
> > > _没有回应_
> > 
> > 
> > 它本身就支持One-API。 这个是你。。。自行部署的非数据库版本？
> 
> Yes, I deployed it with docker using the following command. I just want a simple chat UI, but I found that this version doesn't have many features. That is, if I want to support one-api, configure storage, do I need to deploy a database version? This seems too heavyweight to me.
> 
> ```
> $ docker run -d -p 3210:3210 \
>   -e OPENAI_API_KEY=sk-xxxx \
>   -e ACCESS_CODE=lobe66 \
>   --name lobe-chat \
>   lobehub/lobe-chat
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/33386763/394609348-fd6bf257-2aa0-47f2-9001-c05befdd7110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjY1NjksIm5iZiI6MTczNTI2NjI2OSwicGF0aCI6Ii8zMzM4Njc2My8zOTQ2MDkzNDgtZmQ2YmYyNTctMmFhMC00N2YyLTkwMDEtYzA1YmVmZGQ3MTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDAyMjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxODNmYjU4MGJkODE1MTY1ZDIyYzljY2FmOTk3M2RjOWZiNDhjMGIzOTY4NmQ2Nzc0OWZmYjI2MmM1NDNmMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RFOCafS4lF_VAak-aAvAMaKEbaAX9JaEhyMi4vO9X68)

![image](https://github.com/user-attachments/assets/e286f8cb-c5fd-4e75-94d3-4060090cf0e2)
启动lobe-chat容器时指定OPENAI_PROXY_URL地址为one-api地址就可以了

**Comment by arvinxx** [comment]
1. one-api 不考虑内置，已经没落了
2. 使用服务端 db 版就支持。
