### ISSUE TITLE
[Bug] Gemini-exp-1206 文本对话没有问题，但是发送图片会如下报错

### ISSUE THREAD

**Issue by flyhunterl** [lobehub/lobe-chat#4971]
### 📦 部署环境

Docker

### 📌 软件版本

1.36.2

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

Gemini-exp-1206 文本对话没有问题，但是发送图片会出下如下报错，发送图片链接能正常识别。Qwen的模型没有此类问题。 使用官方API

{
  "error": {
    "message": "Failed to fetch"
  },
  "provider": "google"
}

### 📷 复现步骤

选择Gemini-exp-1206 上传一张图片

**Comment by flyhunterl** [comment]
> 我发现了一个关于 Gemini 模型无法接收图片的类似未解决问题的讨论。你可能发现查看这个帖子有帮助：为什么 Gemini 模型不能收到图片 / Why can't the Gemini model receive images? [[1]](https://github.com/lobehub/lobe-chat/discussions/2962) .
> 
> _继续与 Dosu 交流，请提及@dosu。_
> 
> Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/8588ed50-ed03-4085-b632-8ca0b23f0f49?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/8588ed50-ed03-4085-b632-8ca0b23f0f49?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/8588ed50-ed03-4085-b632-8ca0b23f0f49?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/8588ed50-ed03-4085-b632-8ca0b23f0f49?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/8588ed50-ed03-4085-b632-8ca0b23f0f49?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/8588ed50-ed03-4085-b632-8ca0b23f0f49?feedback_type=other)  
没有帮助，我使用的官方api

**Comment by sxjeru** [comment]
无法复现，请问是否在使用云端数据库？

**Comment by flyhunterl** [comment]
> 无法复现，请问是否在使用云端数据库？

使用的postgres   和lobe一起使用dockercompose部署  测试视觉功能模型 书生和qwen的都能正常识图 除了gemini报错外 智谱glm4v也报错 智谱报错是文件超过5mb 实际文件只有一两百K。也这样报

**Comment by flyhunterl** [comment]
现在确定的lobe的问题 但是没有排查头绪了……因为其他模型在lobe中没问题  同样的API通过cherry也没问题…………

**Comment by flyhunterl** [comment]
找到原因好像是 转换图片到 base64失败了 什么导致的还不知道 我找找看

**Comment by Ranhuiryan** [comment]
你好，我在数据库版本测试也是这个问题，请问解决了吗

**Comment by flyhunterl** [comment]
> 你好，我在数据库版本测试也是这个问题，请问解决了吗

没有

**Comment by seabird000** [comment]
您好，现在解决这个问题了，一样的问题。Gemini上传图片，触发
{
"error": {
"message": "Failed to fetch"
},
"provider": "google"
}

**Comment by flyhunterl** [comment]
> 您好，现在解决这个问题了，一样的问题。Gemini上传图片，触发 { "error": { "message": "Failed to fetch" }, "provider": "google" }

我最后是吧知识库里的同样的照片删完了才解决……
