### ISSUE TITLE
[Bug] 数据库版本

### ISSUE THREAD

**Issue by zhangnanchao** [lobehub/lobe-chat#4976]
### 📦 Environment

Docker

### 📌 Version

数据库版本

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

最新版 数据库版本+ casdoor
创建几个账号，登陆后显示的昵称都是同一个，
而且还可以看见其 聊天内容和记录，确定输入不同账号密码后登陆的是同一个账号。。。

**Comment by arvinxx** [comment]
@cy948 来看看？

**Comment by zhangnanchao** [comment]
> 该问题已在#4919修复。目前按照您的步骤没有修复问题。请更新您的镜像
> 
> ```shell
> docker compose pull
> ```

请问  docker compose pull 都更新哪些镜像，我这里因为网路和系统架构 需要手动单独更新

**Comment by cy948** [comment]
更新lobechat的镜像即可。

**Comment by zhangnanchao** [comment]
> 更新lobechat的镜像即可。

是不是更新后，旧的用户还是有那个问题，新注册的才会各是各的？

**Comment by cy948** [comment]
对

**Comment by zhangnanchao** [comment]
好的，谢谢，已经解决了
