### ISSUE TITLE
[Bug] 导入json以后, 语言没有生效.

### ISSUE THREAD

**Issue by lovitus** [lobehub/lobe-chat#4985]
### 📦 部署环境

Docker

### 📌 软件版本

latest

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge, Firefox

### 🐛 问题描述

系统语言是英文, 默认lobechat也是英文,   在会话里设置为中文以后.
导出数据为json时候,选的全部.
在另一个浏览器导入这个json, 界面依旧是英文, 设置里已经是中文, 刷新也不行. 需要切到其他语言在切回中文才会生效.

是否语言设置不跟随json配置,而且当用户切换才会触发这个事件?

**Comment by arvinxx** [comment]
语言目前应该是没有跟随设置
