### ISSUE TITLE
[Request] 使用accesstoken访问的会话,希望能够保存

### ISSUE THREAD

**Issue by lovitus** [lobehub/lobe-chat#4987]
### 🥰 需求描述

比如我使用accesstoken访问的lobechat, "应用设置"-->"语言模型" 禁用了openai, 启用了claude. 可不可以设置为系统默认的配置?

其实我想整个"应用设置"都能持久化, 这样更换电脑和移动设备以后,可以直接恢复到之前的系统设置.
如果不符合开发者的设计方式, 能不能模型能保存.

打扰了, 谢谢

### 🧐 解决方案

----------

**Comment by arvinxx** [comment]
如果需要云端同步，请使用 database 版本。你说的能力目前我们都支持。但需要你自己看下文档
