### ISSUE TITLE
[Bug] Google Gemini 输入key后 使用模型报错

### ISSUE THREAD

**Issue by smarxtboy** [lobehub/lobe-chat#4994]
### 📦 Environment

Docker

### 📌 Version

1.36.5

### 💻 Operating System

Other

### 🌐 Browser

Chrome

### 🐛 Bug Description

{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:streamGenerateContent?alt=sse: [400 ] Invalid JSON payload received. Unknown name \"examples\" at 'tools[0].function_declarations[5].parameters.properties[1].value': Cannot find field.\nInvalid JSON payload received. Unknown name \"default\" at 'tools[0].function_declarations[12].parameters.properties[1].value': Cannot find field.\nInvalid JSON payload received. Unknown name \"default\" at 'tools[0].function_declarations[12].parameters.properties[3].value': Cannot find field.\nInvalid JSON payload received. Unknown name \"default\" at 'tools[0].function_declarations[12].parameters.properties[4].value': Cannot find field. [{\"@type\":\"type.googleapis.com/google.rpc.BadRequest\",\"fieldViolations\":[{\"field\":\"tools[0].function_declarations[5].parameters.properties[1].value\",\"description\":\"Invalid JSON payload received. Unknown name \\\"examples\\\" at 'tools[0].function_declarations[5].parameters.properties[1].value': Cannot find field.\"},{\"field\":\"tools[0].function_declarations[12].parameters.properties[1].value\",\"description\":\"Invalid JSON payload received. Unknown name \\\"default\\\" at 'tools[0].function_declarations[12].parameters.properties[1].value': Cannot find field.\"},{\"field\":\"tools[0].function_declarations[12].parameters.properties[3].value\",\"description\":\"Invalid JSON payload received. Unknown name \\\"default\\\" at 'tools[0].function_declarations[12].parameters.properties[3].value': Cannot find field.\"},{\"field\":\"tools[0].function_declarations[12].parameters.properties[4].value\",\"description\":\"Invalid JSON payload received. Unknown name \\\"default\\\" at 'tools[0].function_declarations[12].parameters.properties[4].value': Cannot find field.\"}]}]"
  },
  "provider": "google"
}

**Comment by SpeedupMaster** [comment]
function call问题，把插件关掉就好了

**Comment by arvinxx** [comment]
相关问题： https://github.com/lobehub/lobe-chat/issues/2537

Gemini 的 Function calling 一直有问题，是模型能力的 bug
