### ISSUE TITLE
自部署服务端用户管理

### ISSUE THREAD

**Issue by dvlin-dev** [lobehub/lobe-chat#4995]
### 🥰 需求描述

自部署服务端，用户注册后就能无限使用了，如果url泄漏，api会被无限刷

### 🧐 解决方案

增加用户管理

**Comment by SpeedupMaster** [comment]
关掉允许注册就好了

**Comment by wcu1117** [comment]
> 关掉允许注册就好了

怎么关闭注册的

**Comment by SpeedupMaster** [comment]
> > 关掉允许注册就好了
> 
> 怎么关闭注册的
看你用的什么身份验证服务，设置里面都有是否允许注册的，自己找下

**Comment by wcu1117** [comment]
> > > 关掉允许注册就好了
> > 
> > 
> > 怎么关闭注册的
> > 看你用的什么身份验证服务，设置里面都有是否允许注册的，自己找下

那应该没有，我用的微信登录

**Comment by SpeedupMaster** [comment]
> > > > 关掉允许注册就好了
> > > 
> > > 
> > > 怎么关闭注册的
> > > 看你用的什么身份验证服务，设置里面都有是否允许注册的，自己找下
> 
> 那应该没有，我用的微信登录

微信就不知道了，其他的好像都有
