### ISSUE TITLE
[Bug] 页面在某些情况下疯狂跳动

### ISSUE THREAD

**Issue by aiqinxuancai** [lobehub/lobe-chat#5006]
### 📦 Environment

Docker

### 📌 Version

Docker 数据库版 v1.36.18

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

![GIF 2024-12-13 17-07-16](https://github.com/user-attachments/assets/8c5f6a87-f44a-4ac5-b6e5-2b7e7d746e01)
好像输出代码时就在一直闪动，输出完毕后正常，滚动到上面固定的这个位置又开始闪，如果不主动滚到其他地方，就会永远这样跳动。尝试Ctrl+F5无效。

导出会话
[GDI+绘制扇形线的方法.json](https://github.com/user-attachments/files/18123912/GDI%2B.json)

**Comment by arvinxx** [comment]
@aiqinxuancai 看下最新版还有没有这个问题

**Comment by aiqinxuancai** [comment]
> @aiqinxuancai 看下最新版还有没有这个问题

更新docker到v1.36.21后刷新页面，问题似乎解决了，同浏览器+之前有问题的话题下试了多次没有复现。
