### ISSUE TITLE
[Bug] 加载巨慢

### ISSUE THREAD

**Issue by godoge** [lobehub/lobe-chat#5007]
### 📦 Environment

Official Preview

### 📌 Version

1.36.18

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

打开首页很慢，就连打开设置都要等半到一分钟时间，4060显卡，24GRAM，根本没法用

**Comment by arvinxx** [comment]
录个屏？preview怎么可能这么慢
