### ISSUE TITLE
[Bug] 网站回复输出格式有缺陷

### ISSUE THREAD

**Issue by yixiaip** [lobehub/lobe-chat#501]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

测试了一下当输出文字过多的时候，不会进行输出的换行直接糊成了一团，反而非常短的可以
直接输出:
![image](https://github.com/lobehub/lobe-chat/assets/54166443/2e8a3876-4714-45f9-a968-7bb1842d2478)
编辑状态下:
![image](https://github.com/lobehub/lobe-chat/assets/54166443/db70b59e-edee-41a3-8458-ed226530121e)

### 🚦 期望结果 | Expected Behavior

换行输出

### 📷 复现步骤 | Recurrence Steps

1.询问GPT
2.回复

**Comment by XoL1507** [comment]
> 👀 @yixiaip
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
> Please make sure you have given us as much context as possible.\
> 非常感谢您提交 issue。我们会尽快调查此事，并尽快回复您。 请确保您已经提供了尽可能多的背景信息。

>the issue is, the connection are not stable and long time to make a match.

**Comment by canisminor1990** [comment]
refs: https://github.com/lobehub/lobe-ui/issues/81

**Comment by canisminor1990** [comment]
Fixed: https://github.com/lobehub/lobe-ui/commit/c5b4f6b3881cad257d476dd3ac8bef26c1cad3c7
