### ISSUE TITLE
[Bug] pnpm dev debug模型巨慢

### ISSUE THREAD

**Issue by xsun15** [lobehub/lobe-chat#5024]
### 📦 Environment

Other

### 📌 Version

1.36.25

### 💻 Operating System

Windows, Ubuntu, Other Linux

### 🌐 Browser

Chrome, Edge, Firefox, Other

### 🐛 Bug Description

用pnpm dev 进行启动时，compiling巨慢，要几分钟，基本相当于卡死状态。但是先pnpm build后pnpm start就很快

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/discussions/5030
