### ISSUE TITLE
[Bug] The result of the plugin call will cause the size of the entire view to be unexpected.

### ISSUE THREAD

**Issue by skyf0cker** [lobehub/lobe-chat#505]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

The result of the plugin call will cause the size of the entire view to be unexpected.
(the thrown error when invoking OpenAI failed will also make the view like this)

plugin call result view:
<img width="1260" alt="image" src="https://github.com/lobehub/lobe-chat/assets/32331521/a2bbf520-f77f-470c-8d6c-410393f5c887">

when delete the plugin call result:
<img width="1260" alt="image" src="https://github.com/lobehub/lobe-chat/assets/32331521/41da3ebf-ee73-4c24-ba62-75e605b8afb4">

**Comment by arvinxx** [comment]
it's a bug of plugin, and I will find some methods to improve this.
