### ISSUE TITLE
[Request] 希望能通过环境变量配置搜索引擎插件的API Key

### ISSUE THREAD

**Issue by TonyBlur** [lobehub/lobe-chat#508]
### 🥰 需求描述 | Feature Description

希望能通过环境变量配置搜索引擎插件的API Key，因为在多个设备使用同一serp API key需要多次输入，如果可以实现在vercel等后天环境变量提前配置好将会方便许多

### 🧐 解决方案 | Proposed Solution

预置一个环境变量，并当检测到搜索引擎插件启用时，把该变量的值给填到SERPAPI_API_KEY中

**Comment by arvinxx** [comment]
在  https://github.com/lobehub/lobe-chat/discussions/411 跟进
