### ISSUE TITLE
[Request] API调用Gemini

### ISSUE THREAD

**Issue by oliverwu-cn** [lobehub/lobe-chat#5088]
### 🥰 需求描述

是否支持部署时直接附带 Gemini API 参数？ 不需要每次打开Chat都要手动在设置中输入 API参数，目前通过docker 部署时，似乎只有OPEN AI API key可以直接绑定。

### 🧐 解决方案

请大佬帮忙解答一下

**Comment by SpeedupMaster** [comment]
配置 `GOOGLE_API_KEY` 环境变量

**Comment by oliverwu-cn** [comment]
> 配置 `GOOGLE_API_KEY` 环境变量

好的，感谢大佬，回头试试，哈哈哈
