### ISSUE TITLE
[Bug] 无法使用管理员账号登录casdoor

### ISSUE THREAD

**Issue by Hwongyohong** [lobehub/lobe-chat#5098]
### 📦 Environment

Docker

### 📌 Version

1.36.37

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

![8200645c8590fef58ebd7c4abc29fb8 (1)](https://github.com/user-attachments/assets/2702c313-6dd5-49e5-ae2b-1da3e67e7042)

### 📷 Recurrence Steps

后台没有报错误，使用的admin/123

**Comment by SpeedupMaster** [comment]
前段时间更新了一键脚本，会重新生成密码

**Comment by Hwongyohong** [comment]
> 前段时间更新了一键脚本，会重新生成密码

密码在哪里可以看到

**Comment by SpeedupMaster** [comment]
> > 前段时间更新了一键脚本，会重新生成密码
> 
> 密码在哪里可以看到

运行脚本后输出内容里应该可以看到吧

**Comment by suwubee** [comment]
> > > 前段时间更新了一键脚本，会重新生成密码
> > 
> > 
> > 密码在哪里可以看到
> 
> 运行脚本后输出内容里应该可以看到吧

确实没有密码，在env里有加密后的，不知道咋搞了

**Comment by Matata-lol** [comment]
init_data.json 的 password 字段里可以查到

**Comment by SamDu1998** [comment]
遇到同样问题，发现是每一次docker compose up之后，管理员admin的密码就会改成env里面的一键配置的密码
其他用户的倒是不会有变化。
在管理员后台改密码，改好之后，只要docker compose up一遍，就会再改回去
（记下每次都要用脚本生成的密码就好，也许可以加到文档当中）
