### ISSUE TITLE
[Bug] prompt和用户消息似乎都无法换行

### ISSUE THREAD

**Issue by PoseidonLi0514** [lobehub/lobe-chat#510]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

prompt和用户消息似乎都无法换行，在消息栏里换行好的，到消息里就成一坨子了

### 🚦 期望结果 | Expected Behavior

支持换行即可

### 📷 复现步骤 | Recurrence Steps

在自定义助手里的prompt或者发消息shift+enter换行，发送出去是不带换行的

**Comment by mushan0x0** [comment]
refs: https://github.com/lobehub/lobe-chat/issues/501#issuecomment-1824756104

**Comment by canisminor1990** [comment]
Fixed: https://github.com/lobehub/lobe-ui/commit/c5b4f6b3881cad257d476dd3ac8bef26c1cad3c7
