### ISSUE TITLE
[Bug] 与claude-3-5-sonnet-20241022模型对话时会出现antThinking内容

### ISSUE THREAD

**Issue by skywolf123** [lobehub/lobe-chat#5107]
### 📦 部署环境

Docker

### 📌 软件版本

v1.36.39

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

与claude-3-5-sonnet-20241022模型对话时会出现antThinking内容

```
<antThinking>这是一个具体的CSS样式问题，适合使用代码工件来展示解决方案。</antThinking>
<Antartifact identifier="css-h2-styling" type="application/vnd.ant.code" language="css">
```

这个应该客户端处理下吧

**Comment by arvinxx** [comment]
给个完整的对话截图

**Comment by skywolf123** [comment]
![image](https://github.com/user-attachments/assets/76e32bcb-b296-48a7-8f5e-3c24ff913d17)

**Comment by arvinxx** [comment]
正常情况下应该不会有这个的：

<img width="1053" alt="image" src="https://github.com/user-attachments/assets/9e39bcaf-95b6-4293-87d5-f8f6896fa65f" />

应该是你的供应商用了逆向的 cluade 3.5 sonnet。找你的供应商解决吧
