### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by cookies925** [lobehub/lobe-chat#5141]
### 📦 部署环境

Official Preview

### 📌 软件版本

v1.37.2

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

我的所有助手和消息记录都消失了，里面存储了重要内容，我该怎么办？

### 📷 复现步骤

几天没打开网站，再打开网站显示加载中，加载完成后内容全部消失。

### 🚦 期望结果

我希望我的所有助手和消息记录都能复原。

### 📝 补充信息

刷新后也无法恢复

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/issues/5131
