### ISSUE TITLE
[Bug] 更新后出现的问题

### ISSUE THREAD

**Issue by asd26269546** [lobehub/lobe-chat#5143]
### 📦 部署环境

Official Preview

### 📌 软件版本

社区版

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

今天更新后，所有的聊天记录都消失了，能还原么

### 📷 复现步骤

今天打开使用新版，发现key需要重新填写，而且聊天记录全消失

### 🚦 期望结果

有恢复的方案么，公司挺多人再用

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/issues/5131

**Comment by arvinxx** [comment]
chat-preview 是我们的演示站点，从很早以前我们就一直在强调这个站点不建议用于生产用途，未来的任何变更都不会考虑生产的稳定性。

如果你们用于公司内部使用，强烈建议你们自部署一个版本，这样可以拥有完整的站点部署控制权，也不会遇到今天的问题。
