### ISSUE TITLE
[Bug] github o1模型不支持流式，请求适配非流输出

### ISSUE THREAD

**Issue by Zzz3626** [lobehub/lobe-chat#5145]
### 📦 部署环境

Docker

### 📌 软件版本

v1.36.46

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

{
"error": {
"code": "unsupported_value",
"type": "invalid_request_error",
"param": "stream",
"message": "Unsupported value: 'stream' does not support true with this model. Supported values are: false."
},
"endpoint": "https://models.inference.ai.azure.com/",
"provider": "github"
}

**Comment by jiajiaxd** [comment]
#5110 似乎已经适配过了，但是仍然需要手动自定义添加o1模型（如下图）
![image](https://github.com/user-attachments/assets/46077a36-eb8c-4280-b71a-de021d378eaa)
如果自定义添加o1的话，就会复现本issue出现的问题
版本：v1.37.1

**Comment by RS-Imagine** [comment]
请考虑默认关闭GitHub提供商的模型获取，modelList: { showModelFetcher: true }, // I'm not sure if it is good to show the model fetcher, as remote list is not complete.
