### ISSUE TITLE
[Bug] 网页页面卡在“用户状态初始化”

### ISSUE THREAD

**Issue by C-Dragon8** [lobehub/lobe-chat#5155]
### 📦 部署环境

Vercel

### 📌 软件版本

1.38.0

### 💻 系统环境

Windows, macOS, iOS

### 🌐 浏览器

Chrome, Edge, Safari

### 🐛 问题描述

Vecel部署v1.37.0-1.38.0各版本均遇到此问题，网页显示如下：
![image](https://github.com/user-attachments/assets/00dfd8ae-3513-47a8-9beb-ac1707ec2bdc)
身份认证采用Cloudflare Zero Trust，不清楚问题原因。

### 📷 复现步骤

Vecel部署v1.37.0-1.38.0各版本均遇到此问题。

### 🚦 期望结果

期待问题的解决方案。

**Comment by arvinxx** [comment]
@C-Dragon8 是服务端版本吗？还是客户端版本

**Comment by C-Dragon8** [comment]
> @C-Dragon8 是服务端版本吗？还是客户端版本

不清楚您说的服务端版本还是客户端版本具体指哪个，我fork的就是这个分支forked from https://github.com/lobehub/lobe-chat
目前，版本v1.39.0版本依然存在此问题。

**Comment by arvinxx** [comment]
@C-Dragon8 你怎么部署的，有没有用到数据库

**Comment by C-Dragon8** [comment]
> @C-Dragon8 你怎么部署的，有没有用到数据库

我用Vercel关联GitHub的库进行部署，配置的环境变量有OPENAI_MODEL_LIST、AU_CLOUDFLARE_ZERO_TRUST_ISSUER、AU_CLOUDFLARE_ZERO_TRUST_CLIENT_SECRET、AU_CLOUDFLARE_ZERO_TRUST_CLIENT_ID、NEXT_AUTH_SECRET、NEXT_AUTH_SSO_PROVIDERS、NEXTAUTH_URL、MOONSHOT_API_KEY、ANTHROPIC_PROXY_URL、ANTHROPIC_API_KEY、GOOGLE_PROXY_URL、GOOGLE_API_KEY、ACCESS_CODE，仔细核对过，环境变量并未做过什么改动，v1.37.0前的版本没有遇到过这类问题。印象中自动部署完，从v1.37.0就开始了，更换不同的设备、浏览器都是这样的。

没有用到数据库。

刚刚自动部署的v1.39.1版本，此问题依然存在。

**Comment by arvinxx** [comment]
@C-Dragon8 你这是用了 auth + client 模式，不在我们维护范围内，建议迁移到 server db模式 ，或移除auth 回到纯client db模式。
1.37.0 版本我们针对用户初始化的实现修正了一个的 bug，我想正是那个 bug 导致auth+ client模式下能够正常跑。而修复掉以后client + auth 这个方案不 work 是符合预期的。
