### ISSUE TITLE
[Request]获取manifest文件的请求是否可以带参数，这样可以根据参数返回不同的manifest

### ISSUE THREAD

**Issue by lucasfen** [lobehub/lobe-chat#5163]
### 🥰 需求描述

希望能动态生成manifest文件。

### 🧐 解决方案

获取manifest文件的请求是否可以带参数，这样可以根据参数生成返回不同的manifest

**Comment by arvinxx** [comment]
没懂

**Comment by lucasfen** [comment]
举个例子：我有插件A和插件B,对应有manifest文件ma和mb,以及对应的获取manifest文件的接口a和接口b。当前情况是每新增一个插件我就需要新增一个获取manifest文件的接口。我期望的是所有插件共用同一个获取manifest文件的接口，根据接口的请求参数的不同，来返回不同的manifest文件

**Comment by arvinxx** [comment]
那你是不是可以在插件的市场里修改 `manifest.json` 的 url ，自己改成带 query 的？
