### ISSUE TITLE
[Bug]can't use a model that specifies a default for direct conversations

### ISSUE THREAD

**Issue by cai417** [lobehub/lobe-chat#5166]
### 📦 Environment

Docker

### 📌 Version

v1.36.13

### 💻 Operating System

Other Linux

### 🌐 Browser

Edge

### 🐛 Bug Description

My profile reads as follows，After using docker compose up to start the service,I can't have a conversation directly, I need to manually select the model before I can have a conversation
![image](https://github.com/user-attachments/assets/9582881b-5f5f-4aed-8df7-4260c083bcc3)
If I don't click on the model, I get an error like this
![image](https://github.com/user-attachments/assets/9568fe67-c81f-4f0a-b963-0b994580c104)
When I click on the model, I can only have a normal conversation
![image](https://github.com/user-attachments/assets/4c275e27-5f6d-4fa5-9205-6c7ee1df5729)
The desired effect is that you can talk directly after setting the default model in the configuration file, rather than selecting the model to talk

I tried to add configuration to the config file to fix this issue, the config file reads as follows, but the problem still doesn't work
<img width="461" alt="image" src="https://github.com/user-attachments/assets/f26e71ba-97ac-46fa-9dbc-f5de4ba560ed" />
After using docker compose up to start the service, the following error occurs when talking on the front-end page
![image](https://github.com/user-attachments/assets/a26a829f-d632-41fd-807f-dc3f143e3f32)
It is still only available after clicking on the model，How can such a problem be solved

**Comment by cai417** [comment]
The configuration is correct because I can have a normal conversation, the problem is that I need to click on the model before the conversation, otherwise there will be an error

**Comment by arvinxx** [comment]
you need to set DEFAULT_AGENT_CONFIG

**Comment by cai417** [comment]
I've set up DEFAULT_AGENT_CONFIG
![image](https://github.com/user-attachments/assets/52ccf614-fbea-4466-9fa3-b9ec5028250e)

**Comment by arvinxx** [comment]
qwen. Lowercase
