### ISSUE TITLE
[Bug] 使用带参数的URL访问会白屏并报错

### ISSUE THREAD

**Issue by crabkun** [lobehub/lobe-chat#517]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

在聊天时将网页添加到书签后，打开新浏览器窗口点击书签会报错，页面白屏并显示：
Application error: a client-side exception has occurred (see the browser console for more information).
控制台输出是
Error: Minified React error #311; visit https://reactjs.org/docs/error-decoder.html?invariant=311 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

后来发现只要是URL带上参数（例如[https://mywebsite.com/chat#session=acab41be-77ba-4ec7-a4cb-a038de584970](https://mywebsite.com/chat#session=acab41be-77ba-4ec7-a4cb-a038de584970)）就会报错，直接使用[https://mywebsite.com](https://mywebsite.com)就能正常访问。
这些参数在新建会话时会产生，还是比较容易被用户收藏到书签里面。
麻烦看看有没有办法修复呢，非常感谢！

**Comment by arvinxx** [comment]
给个复现，我本地是正常的，你也可以拿 preview 试下。

**Comment by crabkun** [comment]
你好，我拿preview测试发现没有复现。我这边是使用了docker部署lobe-chat，并且使用nginx反代。
我这边试了下，直接访问docker映射出来的端口就正常，访问nginx反代就出现这个问题。
大概率是我这边nginx配置的问题，我这边检查下。非常感谢提供思路！

**Comment by ipengyo** [comment]
> 你好，我拿preview测试发现没有复现。我这边是使用了docker部署lobe-chat，并且使用nginx反代。 我这边试了下，直接访问docker映射出来的端口就正常，访问nginx反代就出现这个问题。 大概率是我这边nginx配置的问题，我这边检查下。非常感谢提供思路！

请我一下大佬最后nginx怎么解决的，我也是部署遇到如上问题了。

**Comment by crabkun** [comment]
> > 你好，我拿preview测试发现没有复现。我这边是使用了docker部署lobe-chat，并且使用nginx反代。 我这边试了下，直接访问docker映射出来的端口就正常，访问nginx反代就出现这个问题。 大概率是我这边nginx配置的问题，我这边检查下。非常感谢提供思路！
> 
> 请我一下大佬最后nginx怎么解决的，我也是部署遇到如上问题了。

不好意思刚看到消息。
最后排查出不是nginx的问题，而是我使用了某个版本的lobechat导出的配置文件有问题，我换了新版本导出之后就正常了。
那个配置文件已经发给作者大佬看了
