### ISSUE TITLE
[Request] 能否使用环境变量 添加 / 删除 模型

### ISSUE THREAD

**Issue by B3nDan** [lobehub/lobe-chat#518]
### 🥰 需求描述 | Feature Description

使用环境变量 添加 / 删除 模型

### 🧐 解决方案 | Proposed Solution

比如 NextWeb 的 CUSTOM_MODELS 

### 📝 补充信息 | Additional Information

暂无

**Comment by lgl1996521** [comment]
这个功能是有的，我用使用 Vercel 部署的没有问题，完全ok，可以添加环境变量增加模型，但是我用群晖docker部署的添加环境变量不生效，不知道是什么问题，官方说新版本解决了这个问题，但是我尝试了一下还是不行

**Comment by arvinxx** [comment]
@B3nDan 删除模型现在没有。刚看了下 next web的方案，感觉挺好的，这样还能支持模型映射。后面我加一下
