### ISSUE TITLE
[Bug] 之前版本中的会话，如何找回

### ISSUE THREAD

**Issue by dufei6515** [lobehub/lobe-chat#5182]
### 📦 Environment

Official Preview

### 📌 Version

没有开启客户端数据库的版本

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

![微信截图_20241226015137](https://github.com/user-attachments/assets/5e109870-d0c8-4292-81c8-42de9ab1376f)
选择后，原来的会话消失了

**Comment by SpeedupMaster** [comment]
#5131

**Comment by arvinxx** [comment]
如果是你自部署的话，去掉这个变量也能拿回来。
