### ISSUE TITLE
[Bug] The auto-update script does not detect the latest version

### ISSUE THREAD

**Issue by cai417** [lobehub/lobe-chat#5188]
### 📦 Environment

Other

### 📌 Version

v1.39.0

### 💻 Operating System

Other Linux

### 🌐 Browser

Edge

### 🐛 Bug Description

The version is updated but the script does not detect it
![image](https://github.com/user-attachments/assets/183a4c8b-e562-4842-82c0-8c562a68b9dd)
![image](https://github.com/user-attachments/assets/79fed450-16db-4e95-9cdc-6c46327eb58c)
![image](https://github.com/user-attachments/assets/42d7ea23-800e-4dcf-a93f-78a56f572c0c)

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/actions/runs/12500723224  docker is still releasing

**Comment by cai417** [comment]
The new version has reached v1.42.1 and mine is still stuck in v1.40.3, why is it not automatically updated
