### ISSUE TITLE
[Bug] 在使用第三方API接口时，插件功能失效

### ISSUE THREAD

**Issue by wgetnz** [lobehub/lobe-chat#520]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

部署命令行
docker run -d -p 3210:3210 -e OPENAI_API_KEY=sk-xxx -e OPENAI_PROXY_URL=https://gptapi.us/ -e ACCESS_CODE=xxqg lobehub/lobe-chat
在使用插件的时候，发现无法成功使用，表现如下
![1](https://github.com/lobehub/lobe-chat/assets/62410571/cc0d098a-0428-4d90-98a1-9af1d36ab9da)
换成官方api即可正常使用插件，表现如下
![2](https://github.com/lobehub/lobe-chat/assets/62410571/31051409-e406-4a47-8a2e-61f33b8bce93)

### 🚦 期望结果 | Expected Behavior

使第三方api proxy能够正常使用插件

**Comment by wgetnz** [comment]
> 插件功能是依赖`functions`的，请确保转发的 key 是支持该能力的

确定支持

**Comment by arvinxx** [comment]
> > 插件功能是依赖`functions`的，请确保转发的 key 是支持该能力的
> 
> 
> 
> 确定支持

可以discord上加我下，私发我，我测一下
