### ISSUE TITLE
加以开源版本提供web browsing插件功能

### ISSUE THREAD

**Issue by xsun15** [lobehub/lobe-chat#5206]
### 🥰 需求描述

是否可以将官方网站的内置插件web browsing开源。如下图所示：
![微信截图_20241227172951](https://github.com/user-attachments/assets/a558d182-80d9-436f-94ae-ee4b8c64f2e4)

### 🧐 解决方案

希望提供web browsing插件

**Comment by SpeedupMaster** [comment]
#4341

**Comment by xsun15** [comment]
3q
