### ISSUE TITLE
[Bug] trpc/edge/upload.createS3PreSignedUrl?batch=1 显示502

### ISSUE THREAD

**Issue by ywq2421** [lobehub/lobe-chat#5208]
### 📦 Environment

Docker

### 📌 Version

1.40.3

### 💻 Operating System

Ubuntu, Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

请求502,导致文件上传中断，另外，上传失败后，无法选择其他文件继续上传，选择文件上传按钮点不动

有时候刷新页面就能请求成功，有时候就502,确认服务正常，这里面在请求什么地址？
![image](https://github.com/user-attachments/assets/62f5df5e-0214-4795-b0e3-ab3fe0675afe)

### 🚦 Expected Behavior

文件正常上传

**Comment by arvinxx** [comment]
502 是你的服务端没响应，应该是你的服务器挂了

**Comment by ywq2421** [comment]
你的意思是，我在一个时间节点，多次上传文件，然后服务挂了？然后我刷新页面后服务又好了是吗？？？docker服务是没有停止过的好不？

**Comment by arvinxx** [comment]
> 你的意思是，我在一个时间节点，多次上传文件，然后服务挂了？然后我刷新页面后服务又好了是吗？？？docker服务是没有停止过的好不？

对。如果你的服务器性能能力较差的话，那么一次性同时上传多个文件的时候就会出现服务器没法 hold 住所有请求的情况，然后部分请求就会出现 502。这个跟docker请求是否有停止服务应该没太大关系。

**Comment by ywq2421** [comment]
单独将整个文件夹上传到minio是没问题的，和lobe部署在一个机器，而且也没看到cpu或内存占用飙升，性能我个人认为是够的，
如果开发团队有时间的话，建议排查优化一下项目整体。目前除了上传这个问题，还有就是lobe运行整体感觉都卡，这个并不是服务器的问题，而是流畅度的问题

**Comment by arvinxx** [comment]
> 单独将整个文件夹上传到minio是没问题的，和lobe部署在一个机器，而且也没看到cpu或内存占用飙升，性能我个人认为是够的

如果你觉得不是你的设备性能问题的话，麻烦录个屏看下你的操作，需要包含浏览器控制台的 network 的部分，这样可以确认整个请求的情况。

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/7f81c6fd-5143-4412-a268-3c3c31aaddd9" />

以及如果遇到 502 出错的请求，麻烦给下这个请求的日志详情。

> 如果开发团队有时间的话，建议排查优化一下项目整体。目前除了上传这个问题，还有就是lobe运行整体感觉都卡，这个并不是服务器的问题，而是流畅度的问题

前端卡顿的性能优化是我们明年的一个关键事项，不过现在非常依赖底层模块 antd 的改版升级，估计可能要到明年年中才能根本解决。

如果可以的话也欢迎详细说明下你觉得现在卡顿的地方？模型设置页面已经在改版优化中了，不知道你觉得其他哪些地方还卡？

**Comment by ywq2421** [comment]
那我先期待一下明年的改版体验，上传文件视频如下
https://github.com/user-attachments/assets/26fa1565-c434-4042-b054-04a17139ad64

**Comment by arvinxx** [comment]
@ywq2421 根据你的视频中的情况来看，是部分成功，然后部分出现502，我觉得大概率应该是被限制并发了。你用的网关是nginx 吗？能否检查下有没有限制了最大的同时请求数之类的配置。

**Comment by ywq2421** [comment]
是nginx,你是指这个吗，其他的配置都是默认，未作改动
`events {
    worker_connections 65535;
}`
暂时先这样把，不清楚什么问题，我先减少并发上传，另外i在看日志过程中，好像存在文件主键冲突，这个是否会影响文件上传，你们入库的主键hashid是依据什么计算的
![image](https://github.com/user-attachments/assets/55d772cd-6d76-4b66-9baa-93ba58659e03)

**Comment by arvinxx** [comment]
> 是nginx,你是指这个吗，其他的配置都是默认，未作改动
> 
> `events {
> 
>     worker_connections 65535;
> 
> }`
> 
> 暂时先这样把，不清楚什么问题，我先减少并发上传，另外i在看日志过程中，好像存在文件主键冲突，这个是否会影响文件上传，你们入库的主键hashid是依据什么计算的
> 
> ![image](https://github.com/user-attachments/assets/55d772cd-6d76-4b66-9baa-93ba58659e03)
> 
> 

哎 这个有点奇怪哎。主键hash是按照文件来算的如果文件 hash 一样的情况下理论上就会触发这个抛错。但在前端我是做了路由的，会先确认下文件在不在，如果存在一样的hash就会自动跳过上传，拿库里已有的记录来存。这个能稳定复现吗？如果能稳定复现应该是个bug，我修一下

**Comment by ywq2421** [comment]
似乎是版本问题导致，刚更新了最新版本，这个问题无法复现了，目前来看没什么问题了，祝lobe越来越好
