### ISSUE TITLE
[Bug] 每次更新需要重新填写api的key

### ISSUE THREAD

**Issue by trevorwang12** [lobehub/lobe-chat#5211]
### 📦 部署环境

Vercel

### 📌 软件版本

1.4

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

部署在vercel上，采用的github自动更新版本，更新频率比较频繁，需要每次重新填写api的key

**Comment by arvinxx** [comment]
正常不需要重新填的，你是不是换浏览器了

**Comment by Henry-Suen** [comment]
我这边也跟是vercel自动更新的版本，不需要重新填写。
