### ISSUE TITLE
[Bug] Using openai o1 model reports unsupported value

### ISSUE THREAD

**Issue by xucq07** [lobehub/lobe-chat#5228]
### 📦 Environment

Docker

### 📌 Version

1.42.1

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

The following error is reported:

```json
{
  "error": {
    "message": "Unsupported value: 'stream' does not support true with this model. Supported values are: false.",
    "type": "invalid_request_error",
    "param": "stream",
    "code": "unsupported_value"
  },
  "endpoint": "https://api.openai.com/v1",
  "provider": "openai"
}
```

### 📷 Recurrence Steps

Select the openai o1 model and use it to reproduce the problem

### 🚦 Expected Behavior

Expect to be able to use the openai o1 model normally

**Comment by sxjeru** [comment]
请更新镜像版本。

fixed in #5183

**Comment by xucq07** [comment]
Confirm that I have used the latest image, IMAGE ID: b6d23de2b434

**Comment by arvinxx** [comment]
@xucq07 I think you don't use latest image. Please check the image here: https://hub.docker.com/r/lobehub/lobe-chat/tags
