### ISSUE TITLE
[Bug] DEFAULT_AGENT_CONFIG配置对随便聊聊无效,必须要再选择一下才能生效

### ISSUE THREAD

**Issue by xiangnanscu** [lobehub/lobe-chat#5229]
### 📦 部署环境

Other

### 📌 软件版本

Latest

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

.env文件里面配置`DEFAULT_AGENT_CONFIG="model=gemini-2.0-flash-exp"`, 模型无效. 用户必须在网页上再点选一次才能生效
![b6](https://github.com/user-attachments/assets/397a217c-392f-4f1a-be7d-41de3c3159b8)

### 📷 复现步骤

1. `.env`文件里面配置`DEFAULT_AGENT_CONFIG="model=gemini-2.0-flash-exp"` 
2. 用户扫码登陆
3. 对话框上方显示的是`gemini-2.0-flash-exp`, 然后用户点击`随便聊聊`, 开始对话
4. 出错, 提示openai的错误

### 🚦 期望结果

用户登陆之后,直接对话就是按DEFAULT_AGENT_CONFIG指定的模型

**Comment by xiangnanscu** [comment]
截图遮了, 这里再贴一下用户点选之前尝试对话的提示信息:
```
请求 OpenAI 服务出错，请根据以下信息排查或重试
json
{
  "error": {
    "code": "model_not_found",
    "type": "invalid_request_error",
    "param": null,
    "message": "The model `gemini-2.0-flash-exp` does not exist or you do not have access to it."
  },
  "endpoint": "https://api.openai.com/v1",
  "provider": "openai"
}
```

**Comment by arvinxx** [comment]
加一下 provider=google
