### ISSUE TITLE
[Bug] How do I know how much the total cost is

### ISSUE THREAD

**Issue by cai417** [lobehub/lobe-chat#5233]
### 📦 Environment

Docker

### 📌 Version

v1.39.0

### 💻 Operating System

Other Linux

### 🌐 Browser

Edge

### 🐛 Bug Description

How do I know how much the total cost is, and where can I check it，Another question is the new version has reached v1.42.1 and mine is still stuck in v1.40.3, why is it not automatically updated

**Comment by arvinxx** [comment]
> How do I know how much the total cost is, and where can I check it

Currently we don't support it.

As for the auto update, you need to re pull docker And start again

**Comment by cai417** [comment]
I used the auto-update script, but it didn't recognize the new version
![image](https://github.com/user-attachments/assets/bd564a8e-bb6c-4ef8-b7b8-4ae46304753f)
