### ISSUE TITLE
[Request] openai o1模型如何发图片

### ISSUE THREAD

**Issue by jfjlhc** [lobehub/lobe-chat#5235]
### 🥰 需求描述

openai o1模型如何发图片，官网是可以发图片给o1的了。

### 🧐 解决方案

openai o1模型如何发图片，官网是可以发图片给o1的了。

**Comment by jfjlhc** [comment]
![image](https://github.com/user-attachments/assets/bc5991c1-b399-4d27-9367-83ffb1af6af6)
当我选择o1,图片按钮变灰色

**Comment by arvinxx** [comment]
修一下单测~
