### ISSUE TITLE
[Bug]  ERR_PNPM_NO_MATCHING_VERSION  No matching version found for react-layout-kit@^1.9.1

### ISSUE THREAD

**Issue by Miaologo** [lobehub/lobe-chat#5238]
### 📦 Environment

Other

### 📌 Version

v1.42.1

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

when exec pnpm install command,
some error show in log
# pnpm install
 WARN  deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for react-layout-kit@^1.9.1

This error happened while installing the dependencies of @lobehub/ui@1.155.6

The latest release of react-layout-kit is "1.9.0".

Other releases are:
  * beta: 1.1.1

If you need the full list of all 23 published versions run "$ pnpm view react-layout-kit versions".
Progress: resolved 660, reused 656, downloaded 0, added 0
Downloading bnpm.byted.org/next/15.1.3: 2.93 MB/25.32 MB
Downloading bnpm.byted.org/@codesandbox/sandpack-client/2.19.8: 358.02 kB/17.78 MB
Downloading bnpm.byted.org/@emoji-mart/data/1.2.1: 3.92 kB/5.39 MB

**Comment by Miaologo** [comment]
pnpm view react-layout-kit versions
[
  '1.0.0', '1.1.0', '1.1.1',
  '1.2.1', '1.2.2', '1.2.3',
  '1.2.4', '1.2.5', '1.3.0',
  '1.3.1', '1.4.0', '1.4.1',
  '1.5.0', '1.5.1', '1.6.0',
  '1.6.1', '1.7.0', '1.7.1',
  '1.7.2', '1.7.3', '1.7.4',
  '1.8.0', '1.9.0'
]

**Comment by arvinxx** [comment]
I think it's an issue of your npm registery sync issue
