### ISSUE TITLE
[Request] Request to add web proxy

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#524]
### 🥰 需求描述 | Feature Description

As mentioned above, currently LobeChat only allows configuring the URL of OPENAI. However, what I need now is to initiate requests through a local proxy port (such as Clash on port 7890). Currently, I have to use TUN mode proxy locally in order to use it (OPENAI official website is blocked within mainland China and I don't know any other trustworthy intermediate proxies).

如题，现在LobeChat只允许配置OPENAI的URL，但是现在我需要的是通过某一个本机代理端口发起请求（如在7890端口Clash），目前我必须在本地使用TUN模式代理才能使用（OPENAI官网在中国大陆境内被阻断，且我并不知道什么其他可信的中间代理）。

### 🧐 解决方案 | Proposed Solution

Add a PROXY configuration item.

添加一个PROXY配置项

**Comment by mushan0x0** [comment]
需要适配本地直连 #151

**Comment by zhuozhiyongde** [comment]
传入 http_proxy https_proxy --network host 环境变量并不起效... @mushan0x0

**Comment by arvinxx** [comment]
> 我并不知道什么其他可信的中间代理

refs to https://github.com/lobehub/lobe-chat/discussions/466

**Comment by zhuozhiyongde** [comment]
> > 但是现在我需要的是通过某一个本机代理端口发起请求（如在7890端口Clash），目前我必须在本地使用TUN模式代理才能使用
> 
> 
> 
> 这一层应该不适合在 LobeChat 做。
> 
> 
> 
> > 我并不知道什么其他可信的中间代理
> 
> 
> 
> refs to https://github.com/lobehub/lobe-chat/discussions/466

我注意到 AI 0x0 就提供了一个本机代理端口，我觉得这个功能还挺有用的？主要还是Docker不支持传入HTTP_PROXY...

**Comment by zhuozhiyongde** [comment]
> 我看 #466 已经有解决方案了，这个关闭了。

啊这，主要是感觉vercel有时候也不是很靠谱，之前没墙的时候有时也上不去，所以还是希望能支持自定义代理..？

**Comment by arvinxx** [comment]
> 主要是感觉vercel有时候也不是很靠谱，之前没墙的时候有时也上不去

你 assign 一个自己的域名就好了呀

> 所以还是希望能支持自定义代理..？

自定义代理没法做在 LobeChat 里的。请求发送的地方是在 服务端。服务端怎么可能支持走你本地的 7890 端口呢？

**Comment by zhuozhiyongde** [comment]
> > 主要是感觉vercel有时候也不是很靠谱，之前没墙的时候有时也上不去
> 
> 
> 
> 你 assign 一个自己的域名就好了呀
> 
> 
> 
> > 所以还是希望能支持自定义代理..？
> 
> 
> 
> 自定义代理没法做在 LobeChat 里的。请求发送的地方是在服务端，服务端怎么可能支持走你本地的 7890 端口呢？

我的意思就是支持使用服务端的7890端口代理orz，我目前docker是本地跑的所以是一样的，但如果我希望能在公网部署就需要能够使用服务端的7890端口代理了（

**Comment by mushan0x0** [comment]
如果你用 AI0x0 的话默认是代理了 openai 的，只填 key 就可以了。想要走本地代理的话要这个项目支持本地网络直连 openai 服务器，像 next-web 那样，这样才会走你的本地代理。要本地 docker 使用你的代理应该也是可以的，比如 `docker run` 的时候带上 `-e OPENAI_PROXY_URL=127.0.0.1:7890` @zhuozhiyongde

**Comment by mushan0x0** [comment]
哦，你是对的，那就是梯子配置的问题，请求都是从本地发出去的

**Comment by arvinxx** [comment]
如果是本地启动 docker 的情况。那么请求是从本地直接发请求给 openai 的。路径如下：

本地docker (localhost:3210)  -> openai (api.openai.com/v1)

我理解你希望的请求链路可能是：

本地 docker (localhost:3210) -> 本地 clashX 代理 (localhost:7890) ->  OpenAI (api.openai.com/v1)

这个方案要求在本地发送请求时，能做请求的代理，通过代理地址发出去。我之前研究过，不是很好弄。

而且上述方案就算在本地能跑了，服务端还需要你额外起一个服务端的代理，会比较麻烦。

所以我推荐的思路是弄一个 OpenAI 的透明代理做请求转发，那个贴子里已经有一个 Vercel  的推荐了，我觉得是可以的，因为我日常就在用，挺稳定的。

本地 docker(localhost:3210) -> 透明代理(api-proxy.com/v1) -> OpenAI(api.openai.com/v1)


这样服务端也可以走这种方式

**Comment by zhuozhiyongde** [comment]
谢谢，我主要还是对vercel访问效果有刻板印象了，刚才试了试使用 FastAPI 搭建了一个代理中间件，成功走了 clash 代理但是失去了流式输出特性，最后还是使用了这个透明代理的方法，目前一切顺利。感谢 @arvinxx

**Comment by arvinxx** [comment]
> 好像这个方法也不支持流式输出。

支持流式的。我用的就是支持流式版本

**Comment by vcredit-azure** [comment]
> 传入 http_proxy https_proxy --network host 环境变量并不起效... @mushan0x0

是的，不生效

**Comment by Turbolento** [comment]
问题有解决吗？我用vercel还是连接不上，该怎么处理呢？
![image](https://github.com/lobehub/lobe-chat/assets/30725265/29f0f879-16b8-4832-b4f9-69b8c5780362)

**Comment by arvinxx** [comment]
@Turbolento vercel.app 域名是被墙了的，你需要自行绑定域名
