### ISSUE TITLE
[Bug] 代码块背景颜色CSS选择器疑似选择范围过宽

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#530]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

<img width="483" alt="Cleanshot-2023-11-30-at-20 02 30@2x" src="https://github.com/lobehub/lobe-chat/assets/36695271/25c557a7-c903-4d75-8ebd-2b6575f1ccba">

如图，对于单行的代码块，和行内代码块一样，也会有这个浅绿色的背景渲染，感觉不像是有意为之的，故推测是CSS选择器选择范围过宽导致的。或者也有可能是因为 shiki 的渲染问题？我注意到后面正常的代码块中间有额外的空行

后面的是正常的：

<img width="1066" alt="Cleanshot-2023-11-30-at-20 09 07@2x" src="https://github.com/lobehub/lobe-chat/assets/36695271/7b7d4b0c-6dad-4961-9f8f-f1a0411f4ef9">

代码对比：

<img width="679" alt="Cleanshot-2023-11-30-at-20 10 50@2x" src="https://github.com/lobehub/lobe-chat/assets/36695271/dc73486a-c13a-477b-8c6f-72be1ca27df2">
<img width="670" alt="Cleanshot-2023-11-30-at-20 10 56@2x" src="https://github.com/lobehub/lobe-chat/assets/36695271/02d73676-1afa-4d15-9508-4e96af0e0fe0">

### 🚦 期望结果 | Expected Behavior

单行代码块取消此背景

### 📷 复现步骤 | Recurrence Steps

直接复制的md如下：
***

Docker 是一个开放平台，用于开发、运送和运行应用程序。你可以使用 Docker 来下载新的镜像，更新现有的镜像，以及移除不再需要的镜像。以下是如何使用 Docker 命令来下载最新的 `lobehub/lobe-chat` 镜像并移除先前的镜像的步骤：

1. 打开终端或命令行界面。

2. 首先，拉取最新的 `lobehub/lobe-chat` 镜像：
   ```bash
   docker pull lobehub/lobe-chat
   ```
   这个命令会从 Docker Hub 中拉取名为 `lobehub/lobe-chat` 的最新镜像。

3. 接下来，你可能想要查看当前安装的所有 Docker 镜像，以便找到需要删除的旧镜像：
   ```bash
   docker images
   ```
   这个命令会列出所有可用的镜像，包括 REPOSITORY、TAG、IMAGE ID、CREATED 和 SIZE 等信息。

4. 找到要删除的旧镜像的 IMAGE ID 或 REPOSITORY:TAG。

5. 使用以下命令移除旧的镜像：
   ```bash
   docker rmi [IMAGE ID 或 REPOSITORY:TAG]
   ```
   例如，如果你要移除特定的旧 `lobehub/lobe-chat` 镜像，你可以使用：
   ```bash
   docker rmi lobehub/lobe-chat:旧标签
   ```
   或者使用 IMAGE ID：
   ```bash
   docker rmi 旧镜像的IMAGE_ID
   ```
   如果镜像被容器使用，你可能需要先停止并移除那些容器，或者使用 `-f` 参数来强制删除镜像：
   ```bash
   docker rmi -f 旧镜像的IMAGE_ID
   ```
   
***
正常的md代码：
***
2. 然后，你可以将上述命令的输出作为输入传递给 `docker rmi` 命令来删除这些镜像。可以使用 `xargs` 来实现：

   ```bash
   docker images | grep 'lobehub/lobe-chat' | grep -v 'latest' | awk '{print $3}' | xargs docker rmi
   ```

   `xargs` 命令会接受来自管道的输入，并将其作为参数传递给 `docker rmi` 命令。

**Comment by zhuozhiyongde** [comment]
感觉是 shiki 导致的问题，md语法树解析有误，对于这种没有空行间隔的代码块不能很好的识别？

**Comment by canisminor1990** [comment]
emmm 这问题好像已经修了好几遍了，还存在么 我看看 ...

**Comment by canisminor1990** [comment]
Fixed: https://github.com/lobehub/lobe-ui/commit/5a378ccdaa127838e38e36eda26fec3a4bd26202

**Comment by zhuozhiyongde** [comment]
Thx！感谢大佬！
