### ISSUE TITLE
[Request] 两个 Logo 的优化问题

### ISSUE THREAD

**Issue by B3nDan** [lobehub/lobe-chat#537]
### 第一个
如图 1
**发现** 和 **默认助手** **Logo** 相同
很多用户给我反馈最开始都以为 **对话** 下面的 **发现** 是 **机器人/助手设置** ，因为你们那个 **Logo** 就是机器人的样子
而且你们 **默认助手** 也是用的同一个 **Logo**

### 第二个
如图 2
**新建助手** 和 **会话**  **Logo** 相似
这个 **新建助手** 很多人会以为是 **新建聊天**

另外，我没理解错的话，你们现在默认的 **新建聊天** 的交互设计是让用户去点 **话题列表** 里的 **默认话题** 吗？
（因为我注意到，每次开始一个聊天，都会另外新建一个 **默认话题** 的聊天

或许 **新建助手**  是个低频操作，那个明显的位置放个 **新建聊天** 可能更合适？

### 备注
我知道 hover 能看到当前按钮的功能，但对于很多 “傻用户” ，还是给他们一个 **明显易懂** 的 Logo 更利于交互。

### 🧐 解决方案 | Proposed Solution

更换为更适合的 Logo
例如
发现 可以用很常见的 Compass 图标
新建助手 可以用一个Bot图标 + 一个加号

### 📝 补充信息 | Additional Information

![Shot 2023-12-01 at 09 09 20@2x](https://github.com/lobehub/lobe-chat/assets/129975925/9f1fe8df-2b94-45c8-9c33-94daff4edefd)
![Shot 2023-12-01 at 09 11 12@2x](https://github.com/lobehub/lobe-chat/assets/129975925/1acb6a24-1c1e-467f-8f02-64db8ec88f76)

**Comment by arvinxx** [comment]
> 发现 和 默认助手 Logo 相同

@canisminor1990 市场的 icon 感觉换成「发现」或者 「市场」的更合适一些

**Comment by arvinxx** [comment]
> 这个 新建助手 很多人会以为是 新建聊天
>  或许 新建助手 是个低频操作，那个明显的位置放个 新建聊天 可能更合适？

那个位置应该是新建助手。icon 倒是可以改改。 结合你提到的 https://github.com/lobehub/lobe-chat/issues/538 里提到的：
> 而是在 新建助手 时，让用户现场设计 这个新建的助手 。

这个点，我感觉可以有一个创建并编辑助手的入口，点击就进入助手的设置去编辑助手。
