### ISSUE TITLE
[Question] 能否把图片上传做到每个模型？包括自定义模式？

### ISSUE THREAD

**Issue by deepphp** [lobehub/lobe-chat#544]
### 🥰 需求描述 | Feature Description

能否把图片上传功能安装到所有模型，包括自定义模型？有的中转把名字设置了，咱们的图片上传只有在选定gpt-4-vision-preview。。就很尴尬

### 🧐 解决方案 | Proposed Solution

能否把图片上传功能安装到所有模型，包括自定义模型？有的中转把名字设置了，咱们的图片上传只有在选定gpt-4-vision-preview。。就很尴尬

**Comment by canisminor1990** [comment]
因为目前只有 gpt-4-vision-preview 支持了视觉识别

**Comment by arvinxx** [comment]
@canisminor1990  可能后面还真得这么做。 `gpt-4-vision-preview`  是不支持 function call 的：https://github.com/lobehub/lobe-chat/discussions/427#discussioncomment-7560964

也就说如果在用 vision model 时同时又需要使用插件的话，现在的实现方案没法不支持。用户可能要多个模型间互相切换，才能实现，感觉灵活性就不太够了。

所以可能更优的解法模式是将 vision 做成一个内置能力，而且这个能力可能也是可插拔替换的，比如可以换成其他视觉识别的模型。

**Comment by arvinxx** [comment]
> > @canisminor1990  可能后面还真得这么做。 `gpt-4-vision-preview`  是不支持 function call 的：[#427 (reply in thread)](https://github.com/lobehub/lobe-chat/discussions/427#discussioncomment-7560964)
> > 也就说如果在用 vision model 的同时又需要使用插件的话，现在的实现方案没法支持。用户可能要多个模型间互相切换，感觉灵活性就不太够了。
> > 所以可能更优的解法模式是将 vision 做成一个内置能力，而且这个能力可能也是可插拔替换的，比如可以换成其他视觉识别的模型。
> 
> 把图片当成fc走呢

图片咋当成 fc 走
