### ISSUE TITLE
[Question] 使用Browser的Speech-to-Text Service兼容问题

### ISSUE THREAD

**Issue by zhanghxiao** [lobehub/lobe-chat#545]
### 🧐 问题描述 | Proposed Solution

您好，请问Speech-to-Text Service是只有在edge浏览器才能使用Browser的方式进行STT吗?
我分别在Firefox和Google Chrome还有edge浏览器上都试了一下，browser的形式只能在edge上起作用

**Comment by canisminor1990** [comment]
你的 chrome 是什么版本，我测试环境在 119.0.6045.200 上是正常的，同时查看下 chrome 中麦克风是否被禁用，如果 devtool 中相关报错信息页可以提供

**Comment by zhanghxiao** [comment]
> @zhanghxiao 你的 chrome 是什么版本，我测试环境在 119.0.6045.200 上是正常的，同时查看下 chrome 中麦克风是否被禁用，如果 devtool 中相关报错信息页可以提供

我的chrome版本是117.0.5938.92，前两天还不行，刚才重试后又可以正常录入了.....
