### ISSUE TITLE
[Question] Error requesting OpenAI service. Please troubleshoot or retry based on the following information.

### ISSUE THREAD

**Issue by Tharic99** [lobehub/lobe-chat#546]
### 🧐 问题描述 | Proposed Solution

I installed Lobe-Chat in an unraid container without any problems, created a new OpenAI account and generated a new API key. That API key was input into the unraid settings for the "OPENAI API Key"

However, when accessing the Lobe-Chat agent (or a custom agent) I get an error of

{
  "endpoint": "https://api.openai.com/v1",
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

No additional errors appear in the logs. I have a credit card on file with the OpenAI account and an existing balance established. 

In addition, the API shows 0 usage and that it has been last used as "Never.

Not sure what I'm missing.

**Comment by arvinxx** [comment]
Do you make sure your balance is enough?

**Comment by Tharic99** [comment]
> Do you make sure your balance is enough?

Yes. I said that there was an existing balance on the plan. The API shows 0 usage and that it has been last used as "Never.

**Comment by Tharic99** [comment]
> It is possible that your key has expired and is no longer usable.

I have created multiple API key's to test it with. Nothing else is using the key, so I know it's not an issue there. I can generate a brand new key, put it in the docker container, start it up and get the same error. The API page still shows 0 usage and that it has been last used as "Never"

It's like it's not even attempting to connect to the API, but there's nothing in the docker logs indicating any errors.
