### ISSUE TITLE
[Bug] 焦点在输入区时，清空对话的 `opt+delete` 快捷键不生效

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#556]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

如题。在macOS/Windows，Chrome/Safari 下均可复现。

不清楚是否为特意为之，但感觉焦点在输入区时，清空对话是很自然的过程。可以避免新开对话。

### 🚦 期望结果 | Expected Behavior

支持焦点在输入区时，使用快捷键清空对话

### 📷 复现步骤 | Recurrence Steps

如题

**Comment by arvinxx** [comment]
应该是支持的，你的版本是哪个

**Comment by zhuozhiyongde** [comment]
LobeChat v0.107.11 @arvinxx

**Comment by arvinxx** [comment]
哦 看错了 是 opt + enter 是支持， opt + delete  @canisminor1990  看看？
