### ISSUE TITLE
[Question] How do I change the language model Settings in my Settings?

### ISSUE THREAD

**Issue by caochengchen** [lobehub/lobe-chat#569]
### 🧐 问题描述 | Proposed Solution

I have one problems:
There is no button to upload images, which makes it impossible to use OpenAI's latest gpt-4-vision model.

**Comment by caochengchen** [comment]
Thank you. Now I only have one question left. Do I need to modify some snippets of the source code before deploying the code through Vercel? Because I want to change the link jump address and name in the Settings.
For example, I want to change Settings - Language model - scheduled access Jump URL links to my own personal URL, how do I change?

Also, how do I change Settings - Language Model - Interface proxy address? I want to change the interface address to the default address I specified, without entering the address myself, or enter the background board can prompt me to enter the address URL.

**Comment by caochengchen** [comment]
![_3%$9QTZXOG~ C5ALX~2B8H](https://github.com/lobehub/lobe-chat/assets/102595565/36685b12-4c31-49fe-acb0-7f8f5d3c98f2)
The two positions in this picture are the ones I just described that I want to change. How should it be changed?

**Comment by arvinxx** [comment]
you can deploy with Env, please check here: https://github.com/lobehub/lobe-chat#-self-hosting

**Comment by caochengchen** [comment]
In which code does it change? I searched for a long time and didn't know which file or files in the code base the two urls were defined

**Comment by arvinxx** [comment]
the first one don't need to change. you can set with env. the second one is here:
https://github.com/lobehub/lobe-chat/blob/main/src/app/settings/llm/index.tsx#L26

**Comment by caochengchen** [comment]
Thank you very much. But the first address I want to change to my own proxy address, or the display word is my own proxy address, which code in the code base controls this?
