### ISSUE TITLE
建议不要完全围绕gpt api来设计，路比较窄

### ISSUE THREAD

**Issue by guowc** [lobehub/lobe-chat#57]
国内大环境因素，围绕gpt难以实际应用推广，建议后续版本支持国内开源LLM

**Comment by arvinxx** [comment]
> 国内大环境因素，围绕gpt难以实际应用推广，建议后续版本支持国内开源LLM

开源 LLM 有适配 GPT 版本的接口，这个倒不是什么问题。我开个新 issue来跟踪吧
