### ISSUE TITLE
[Question] 导入配置得文件格式？

### ISSUE THREAD

**Issue by caochengchen** [lobehub/lobe-chat#570]
### 🧐 问题描述 | Proposed Solution

![image](https://github.com/lobehub/lobe-chat/assets/102595565/cb7d4250-a903-4688-a7a8-207137bda553)
这里的导入配置的文件，应该是什么后缀名？文件里面的内容应该怎么填写？可以导入哪些配置？

**Comment by arvinxx** [comment]
可以在使用后尝试导出一个文件看看
