### ISSUE TITLE
[Bug] Safari 下图片溢出边框、复制黏贴图片会自动黏贴图片路径、清空会话同时造成图片输入清空

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#571]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

如题。

经测试，这两个问题都只在 Safari 下出现。Chrome下一切正常。

额外的测试表明，粘贴路径可能和 CleanShotX 或者 Paste 有关？未测试原生截图是否会导致同样问题。

图片溢出应该就和截图软件无关了。

同时，我注意到清空会话消息（opt+delete）会**保留输入的文本内容，但移除输入的图片内容**。我推测这是一个 bug。

![image](https://github.com/lobehub/lobe-chat/assets/36695271/60f28ee4-5ed8-47b9-b451-2e0879f9abf2)

### 🚦 期望结果 | Expected Behavior

正常展示图片，同 Chrome。

黏贴路径我不确认是否是由于 LobeChat 引起的。

### 📷 复现步骤 | Recurrence Steps

在 Safari 下复制图片到输入栏。

系统版本是 macOS Sonoma。

### 📝 补充信息 | Additional Information

npx envinfo --system --binaries --browsers

  System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 77.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 10.2.1 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.10.5 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1.2

**Comment by zhuozhiyongde** [comment]
hey，我想请问有无更新的进展？@canisminor1990

**Comment by canisminor1990** [comment]
@zhuozhiyongde 我今晚修

**Comment by zhuozhiyongde** [comment]
> @zhuozhiyongde 我今晚修

感谢大佬！
