### ISSUE TITLE
[Bug] docker 部署后 https://registry.npmmirror.com 资源出现加载错误

### ISSUE THREAD

**Issue by onlylhf** [lobehub/lobe-chat#574]
### 💻 系统环境 | Operating System

Other Linux

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

宿主机在香港，在宿主机curl正常。

![image](https://github.com/lobehub/lobe-chat/assets/27225745/d35dc160-65b8-4676-ae25-9820f2ba9ed4)

页面加载图片缓慢

![image](https://github.com/lobehub/lobe-chat/assets/27225745/492e2999-3e95-48f1-ae0c-0addaa52eb85)

但是在docker内就会提示超时。

具体错误如下：

```
 /_next/image?url=https%3A%2F%2Fregistry.npmmirror.com%2F%40lobehub%2Fassets-emoji%2F1.3.0%2Ffiles%2Fassets%2Frobot.webp&w=32&q=75 HTTP/1.1" 500 32  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
chatgpt-next-web-lobe-chat-1         |  ⨯ TypeError: fetch failed
chatgpt-next-web-lobe-chat-1         |     at Object.fetch (node:internal/deps/undici/undici:11730:11)
chatgpt-next-web-lobe-chat-1         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
chatgpt-next-web-lobe-chat-1         |   cause: ConnectTimeoutError: Connect Timeout Error
chatgpt-next-web-lobe-chat-1         |       at onConnectTimeout (node:internal/deps/undici/undici:6869:28)
chatgpt-next-web-lobe-chat-1         |       at node:internal/deps/undici/undici:6825:50
chatgpt-next-web-lobe-chat-1         |       at Immediate._onImmediate (node:internal/deps/undici/undici:6857:13)
chatgpt-next-web-lobe-chat-1         |       at process.processImmediate (node:internal/timers:478:21)
chatgpt-next-web-lobe-chat-1         |       at process.callbackTrampoline (node:internal/async_hooks:130:17) {
chatgpt-next-web-lobe-chat-1         |     code: 'UND_ERR_CONNECT_TIMEOUT'
chatgpt-next-web-lobe-chat-1         |   }
chatgpt-next-web-lobe-chat-1         | }
```

**Comment by arvinxx** [comment]
@canisminor1990

**Comment by mushan0x0** [comment]
<img width="901" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/d088c289-1af8-44df-9e55-f929ed755969">
包依赖的问题吗，是不是自己构建的镜像，建议把 docker 命令贴一下

**Comment by onlylhf** [comment]
> @arvinxx
> 
> 你能复现么


可以复现，直接使用 [README.md](https://github.com/lobehub/lobe-chat/blob/main/README.md)   中的docker 命令一样。

服务器IP：

> 103.152.132.xxx
> 103.140.229.xxx


```
 docker run -d -p 3210:3210   -e OPENAI_API_KEY=sk-xxxx   -e ACCESS_CODE=lobe66   lobehub/lobe-chat
```

显示日志：

```
docker logs -f e624d04ed889
   ▲ Next.js 14.0.3
   - Local:        http://localhost:3210
   - Network:      http://0.0.0.0:3210

 ✓ Ready in 133ms

 ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3210". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
 ⨯ TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:6869:28)
      at node:internal/deps/undici/undici:6825:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:6857:13)
      at process.processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

**Comment by canisminor1990** [comment]
@arvinxx 

https://github.com/lobehub/lobe-chat/blob/main/next.config.mjs#L48-L48

加个环境变量？这边false可能可以解

**Comment by canisminor1990** [comment]
@onlylhf 你尝试进容器把这行改为 true 看看有没有效，有效的话后面可以添加环境变量，https://github.com/lobehub/lobe-chat/blob/main/next.config.mjs#L48-L48

**Comment by arvinxx** [comment]
> 你尝试进容器把这行改为 true 看看有没有效

docker 镜像里是没有这个文件的。得他自己重新构建镜像了

**Comment by arvinxx** [comment]
> @arvinxx
> 
> 你能复现么

我试了下也没复现。感觉应该是和网络环境有关系。

**Comment by onlylhf** [comment]
那应该是我网络的问题，我再试试吧，要不先关掉这个 issue吧

**Comment by qingyuan0o0** [comment]
(base) root@new:~/docker# docker rm -f lobechat && docker run --name lobechat -d -p 3210:3210   -e OPENAI_API_KEY=xxx  -e OPENAI_PROXY_URL=http://192.168.3.71:9996/api/v1   -e ACCESS_CODE=lobe66  lobehub/lobe-chat
lobechat
190588b7acb3b0eef702074597cc528dc32b10781b9b340cecac8e351e1418c1
(base) root@new:~/docker# docker logs lobechat 
   ▲ Next.js 14.0.4
   - Local:        http://localhost:3210
   - Network:      http://0.0.0.0:3210

 ✓ Ready in 519ms

 ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3210". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
(base) root@new:~/docker#

**Comment by zhufeizzz** [comment]
@onlylhf 我也遇到一样的问题了，你咋解决的，能同步一下吗

我是宿主机要通过Proxy才能上网，已经配置了Proxy。并且启动Docker时设置了HTTP_Proxy，但是也报这个错误。

```
TypeError: fetch failed
    at async x.getAssistantList (.next/server/chunks/74776.js:1:3624)
    at async p (.next/server/app/(main)/discover/(list)/(home)/page.js:132:5545) {
  digest: '1702110072',
  [cause]: [Error [ConnectTimeoutError]: Connect Timeout Error (attempted address: registry.npmmirror.com:443, timeout: 10000ms)] {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
```

**Comment by onlylhf** [comment]
> @onlylhf 我也遇到一样的问题了，你咋解决的，能同步一下吗
> 
> 
> 
> 我是宿主机要通过Proxy才能上网，已经配置了Proxy。并且启动Docker时设置了HTTP_Proxy，但是也报这个错误。
> 
> 
> 
> ```
> 
> TypeError: fetch failed
> 
>     at async x.getAssistantList (.next/server/chunks/74776.js:1:3624)
> 
>     at async p (.next/server/app/(main)/discover/(list)/(home)/page.js:132:5545) {
> 
>   digest: '1702110072',
> 
>   [cause]: [Error [ConnectTimeoutError]: Connect Timeout Error (attempted address: registry.npmmirror.com:443, timeout: 10000ms)] {
> 
>     code: 'UND_ERR_CONNECT_TIMEOUT'
> 
>   }
> 
> ```
> 
> 
> 
> 

我换到了日本的VPS上了。
