### ISSUE TITLE
[Request] 增加对One-api的whisper模型的支持

### ISSUE THREAD

**Issue by VectorZhao** [lobehub/lobe-chat#577]
### 🥰 需求描述 | Feature Description

不知能否增加对One-api的`whisper-1`模型的支持？貌似语音识别这里只能是openai官方的吧

### 🧐 解决方案 | Proposed Solution

`whisper-1`

**Comment by mushan0x0** [comment]
one-api 跟 openai 接口是保持一致的，你要看你渠道里是否启用了这个模型

**Comment by VectorZhao** [comment]
> one-api 跟 openai 接口是保持一致的，你要看你渠道里是否启用了这个模型

确实，刚试了一下可以用。。。。
