### ISSUE TITLE
[Design] Optimize the operation of lobechat on mobile devices

### ISSUE THREAD

**Issue by skyf0cker** [lobehub/lobe-chat#579]
### 🥰 需求描述 | Feature Description

The current operation requires double-clicking on the session to enter the specified assistant session, and clicking the return button to go back to the previous level. Hope to support single-click switching between sessions and swiping to go back to the previous level.

### 🧐 解决方案 | Proposed Solution

support single-click switching between sessions and swiping to go back to the previous level.

**Comment by arvinxx** [comment]
@canisminor1990 这个 iOS 上还是没解决

**Comment by ONLY-yours** [comment]
fixed now
