### ISSUE TITLE
[Bug] 随便聊聊的话题列表会影响助手的话题列表

### ISSUE THREAD

**Issue by ravenk1n9** [lobehub/lobe-chat#582]
### 💻 系统环境 | Operating System

Other Linux

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

安卓手机Edge浏览器，在随便聊聊中选择一个话题，会将助手切换到一个不存在的话题里。

### 🚦 期望结果 | Expected Behavior

优化话题列表，同时希望切换助手时能保持在原话题里而不是进入默认话题

### 📷 复现步骤 | Recurrence Steps

视频上传一直不成功，贴一个网盘链接吧lv_0_20231205224035.mp4
https://www.alipan.com/s/5xFKziH3S6e

**Comment by arvinxx** [comment]
我先尝试复现一下
