### ISSUE TITLE
[Bug] Language settings are not working correctly

### ISSUE THREAD

**Issue by magicnov** [lobehub/lobe-chat#586]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Language settings are not applied after browser restart

### 🚦 期望结果 | Expected Behavior

The site language matches the language in the settings

### 📷 复现步骤 | Recurrence Steps

1. Set language to Russian
2. Restart browser and reopen site
3. Site is in English, but in settings language is set to Russian

### 📝 补充信息 | Additional Information

demo: https://drive.google.com/file/d/1wCqjzxFscaS-u3M2eAbVgx6Yv7JFIZtw/view?usp=sharing

**Comment by magicnov** [comment]
Have you checked the video with the issue demo? I can provide more information, just let me know what you need.

**Comment by arvinxx** [comment]
@mushan0x0 @magicnov are you using docker version or vercel version？

can you reproduce the problem with https://chat-preview.lobehub.com/ ?

**Comment by mushan0x0** [comment]
Maybe I can fix this issue.

**Comment by magicnov** [comment]
> Maybe I can fix this issue.

Any updates?

**Comment by mushan0x0** [comment]
> > Maybe I can fix this issue.
> 
> Any updates?

The fixed code has been submitted, you can test it at this link: https://lobe-chat-1-d39h8edt7-mushan0x0.vercel.app
