### ISSUE TITLE
[Request] 兼容openai新版toolcalls机制

### ISSUE THREAD

**Issue by barryWang12138** [lobehub/lobe-chat#592]
### 🥰 需求描述 | Feature Description

如题，是否能兼容openai新版toolcalls机制

### 🧐 解决方案 | Proposed Solution

https://platform.openai.com/docs/guides/function-calling

**Comment by arvinxx** [comment]
WIP，详见： https://github.com/lobehub/lobe-chat/discussions/551

**Comment by barryWang12138** [comment]
> WIP，详见： https://github.com/lobehub/lobe-chat/discussions/551

目前我使用的第三方openai代理服务下线了functioncall参数，仅支持toolcall机制，今天早上使用时发现调用插件失败，已更新到最新版本

**Comment by arvinxx** [comment]
那这个是你的三方代理服务问题，不应该过早下掉的， toolcall 机制只在最新的模型中才能支持。比如 gpt-3.5-turbo 要等到下周二才会更新到新模型。我们计划的支持时间也是在更新之后。全部升级到toolcall机制，会导致现阶段旧模型全都无法使用插件了

**Comment by fredi-python** [comment]
Owner of Mandrill here, tools should work fine now
