### ISSUE TITLE
[Request] Disable/remove topic-deletion hotkey

### ISSUE THREAD

**Issue by SivertGullbergHansen** [lobehub/lobe-chat#594]
### 🥰 需求描述 | Feature Description

Add the ability to disable quick-delete entire topic (option + backspace).
I use option + backspace when I type to remove and entire word. I constantly click this and accidentally delete my entire topic, making me re-do my prompts to go back to my topic.

### 🧐 解决方案 | Proposed Solution

Add the option in settings to change this hotkey or disable it entirely.

### 📝 补充信息 | Additional Information
Example of issue:
After creating a prompt and receiving a response
![image](https://github.com/lobehub/lobe-chat/assets/6785315/c0a44588-0f97-4b5d-8a7d-4d24f7aef084)

I type in the input and accidentally press option + backspace
![image](https://github.com/lobehub/lobe-chat/assets/6785315/8eb88eaf-ca13-4085-aa0e-333c7bc2b737)

The entire history is deleted
![image](https://github.com/lobehub/lobe-chat/assets/6785315/35c0f054-5bbc-42fa-b387-c4c097bad009)

_No response_

**Comment by arvinxx** [comment]
@canisminor1990 should change the delete topic hotkey.

**Comment by canisminor1990** [comment]
refs: https://github.com/lobehub/lobe-chat/issues/616

**Comment by canisminor1990** [comment]
change to `command` + `option` + `backspace`
