### ISSUE TITLE
[Bug] 拓展工具已安装列表没有显示中文

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#597]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

拓展工具已安装列表没有显示中文
<img width="335" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/f603897e-c97a-4e51-84da-8277c70d6821">

### 🚦 期望结果 | Expected Behavior

显示中文应该比较好一点
<img width="826" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/7e761a73-10dc-4ed8-92df-2d6f020169fa">

**Comment by arvinxx** [comment]
在 #596 修复
