### ISSUE TITLE
[Bug] 发送消息按键显示错误

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#599]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

显示回车是换行，但是回车实际是发送消息
<img width="324" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/ad5bcec3-846c-4b2a-a040-2a7e173147d7">

**Comment by arvinxx** [comment]
哎 之前是正常的吗

**Comment by mushan0x0** [comment]
可能是[这段代码](https://github.com/lobehub/lobe-ui/commit/584d5cd#diff-5e971af157d1160d7969ee93ea2a88b5e5e8cb8083b499c1d13013c76f12ced6R48-R55)写反了？

**Comment by canisminor1990** [comment]
我改一下 重构放反了

**Comment by canisminor1990** [comment]
@mushan0x0 对了之前你说的那个 ios 底部高度的问题，你知道原因么

**Comment by mushan0x0** [comment]
> @mushan0x0 对了之前你说的那个 ios 底部高度的问题，你知道原因么

那个安全区域获取的高度是对的，感觉有可能是全屏导致的
