### ISSUE TITLE
[Bug] 关闭自动创建话题后，手动创建话题对话消息不会清空

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#601]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

关闭自动创建话题后，手动创建话题对话消息不会清空，打开自动创建话题后正常

### 🚦 期望结果 | Expected Behavior

手动创建话题的时候清空对话消息

### 📷 复现步骤 | Recurrence Steps

https://github.com/lobehub/lobe-chat/assets/29084441/27825bfb-67f3-404d-b503-f14a174064fe

**Comment by arvinxx** [comment]
感觉是刷新部分有问题。第二次进来默认列表里应该就是清空的
