### ISSUE TITLE
[Question] 三方api是否支持 function_calls 调用 

### ISSUE THREAD

**Issue by BUPTLdy** [lobehub/lobe-chat#604]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

我使用官方的API在体验地址上https://chat-preview.lobehub.com/，插件功能能够生效；但是如果使用第三方代理提供的API，插件功能就不生效。
![image](https://github.com/lobehub/lobe-chat/assets/11829435/62a7113c-fd89-455c-9357-dca241f7e411)

**Comment by arvinxx** [comment]
请确认三方api是否支持 function_calls 调用哈

**Comment by BUPTLdy** [comment]
看了下第三方代理API的文档：``兼容OpenAI新版tool_call机制，function_call参数下线``

**Comment by arvinxx** [comment]
与 #592 重复
