### ISSUE TITLE
更换emoji表情找不到源文件

### ISSUE THREAD

**Issue by lifeforf** [lobehub/lobe-chat#609]
### 🧐 问题描述 | Proposed Solution

![image](https://github.com/lobehub/lobe-chat/assets/109181764/3c65303f-7551-45ac-92b6-6cf5862f3d3a)这个表情到底怎么换呀，求告知

**Comment by mushan0x0** [comment]
在这里换 https://github.com/lobehub/lobe-chat/blob/da9c3a670b293fbfcc54ef5ed97cf5cd564a4bcf/src/const/meta.ts#L7

**Comment by lifeforf** [comment]
您好，按照提示更改了，有效的，可是刷新之后又变为了原样。

**Comment by mushan0x0** [comment]
<img width="1095" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/08e5afcc-0340-495f-ba5c-b860eb3a2a65">
可能要把旧的数据删了

**Comment by lifeforf** [comment]
牛的哥们，还有个问题啊，我标题栏的
![image](https://github.com/lobehub/lobe-chat/assets/109181764/227e0b45-2852-4b00-990d-aa85b32fa5f0)
怎么删除呀，我也不想要它。还有啊，我在尝试接入其他的模型，例如：chatglm，通义千问，等等。是编写openai——api接口尝试接入的。那么在模型选项里，我怎么把那些模型设置都删了，改为其他的我魔改后的模型参数。

**Comment by mushan0x0** [comment]
侧边栏的在这里换：https://github.com/lobehub/lobe-chat/blob/da9c3a670b293fbfcc54ef5ed97cf5cd564a4bcf/src/features/SideBar/index.tsx#L15
模型在这里改：https://github.com/lobehub/lobe-chat/blob/da9c3a670b293fbfcc54ef5ed97cf5cd564a4bcf/src/types/llm.ts#L4

**Comment by lifeforf** [comment]
哥们，你说的模型设置我捣鼓的差不多可行了。遇到了好几个问题，望您指教～之前说的那个emojj的表情不是侧边栏的，是title的，删除不掉。我在捣鼓接入模型的时候，想取消设置里，模型设置的频率惩罚啥的选项参数。在修改代码之后就变为了英文，怎么彻底取消这个选项呀

**Comment by mushan0x0** [comment]
这个在代码里面搜吧，很多可以地方可以通过搜索找到的
