### ISSUE TITLE
[Bug] 移动端无法停止对话

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#612]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

当 loading 时发送按钮没有变为停止按钮

### 📷 复现步骤 | Recurrence Steps

https://github.com/lobehub/lobe-chat/assets/29084441/9bb6607f-67e1-4a66-a5d3-769aacfc5f5f

**Comment by arvinxx** [comment]
@canisminor1990 重构又丢东西了

**Comment by mushan0x0** [comment]
我找到问题了，我提一个pr吧
