### ISSUE TITLE
[Bug] 「清空当前会话信息 opt+delete」快捷键与系统快捷键冲突

### ISSUE THREAD

**Issue by xuzuodong** [lobehub/lobe-chat#616]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

mac 系统下 `option + delete` 用来向前删除一个单词，我是这个快捷键的重度使用者。现在 LobeChat 将「清空当前会话信息」功能的绑定到这个热键，导致我会经常性误操作，从而直接把聊天记录清空掉，而且误操作后，无法撤销这一行为，按下快捷键后也不会弹出点击按钮后会出现的二次确认对话框。

因此能否建议将此功能的快捷方式更换，例如可以更换成 `cmd + control + C`，或者直接取消这一功能的快捷键？

**Comment by canisminor1990** [comment]
有推荐的快捷键嘛

**Comment by xuzuodong** [comment]
试了这几个，没有发现什么问题：

1. cmd + control + X
2. cmd + control + C
3. cmd + control + delete

**Comment by arvinxx** [comment]
@canisminor1990 已经有两个提了。可以考虑换成 cmd + control + delete

类似 #594

**Comment by canisminor1990** [comment]
change to `command` + `option` + `backspace`
