### ISSUE TITLE
[Bug] docker安装，配置好环境变量后，返回值是空白。

### ISSUE THREAD

**Issue by iAmP1us** [lobehub/lobe-chat#617]
### 💻 系统环境 | Operating System

Other Linux

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![QQ截图20231212105355](https://github.com/lobehub/lobe-chat/assets/86154051/970401f1-a1e8-490a-af54-05113705499b)
如上图，环境变量的API代理地址和key都配置好了，但是无论3.5还是4，返回值都是空白。
不知道是不是bug。

**Comment by arvinxx** [comment]
你的 api url 是否没加 `v1`

**Comment by iAmP1us** [comment]
> 你的 api url 是否没加 `v1`

我用的第三方API地址，没有v1，但是我用隔壁chatgpt next web同样的配置，是正常的。

**Comment by arvinxx** [comment]
可以私戳我，我来测试下

**Comment by iAmP1us** [comment]
> > > 你的 api url 是否没加 `v1`
> > 
> > 
> > 我用的第三方API地址，没有v1，但是我用隔壁chatgpt next web同样的配置，是正常的。
> 
> 隔壁确实是不需要加v1的,但是这边需要加上,完整的接口代理地址配置就是 地址/v1

解决了，确实是v1的问题，OPENAI_PROXY_URL=https://api-proxy.com/v1，我看到这条的时候第一反应，没考虑到v1，因为openai本来自带了一个v1，谢谢各位。
