### ISSUE TITLE
[Bug] 手机端网页/应用调起键盘，页面整体上移

### ISSUE THREAD

**Issue by junyangfan** [lobehub/lobe-chat#618]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

手机端网页/应用调起键盘时，页面整体会上移，顶部信息被遮挡
![photo_2023-12-12_10-58-54](https://github.com/lobehub/lobe-chat/assets/53593182/d00f33d7-262a-49d8-835e-540247726bcc)
![photo_2023-12-12_10-58-47](https://github.com/lobehub/lobe-chat/assets/53593182/e82d597b-42d5-462b-aa03-f591f0e302e9)

### 🚦 期望结果 | Expected Behavior

调起键盘不影响页面整体信息，底部输入框会随着键盘移动（和其他应用类似，例如微信）

**Comment by canisminor1990** [comment]
这个在pwa模式中暂时解决不了

**Comment by arvinxx** [comment]
> 这个在pwa模式中暂时解决不了

解决不了的原因是什么？

**Comment by canisminor1990** [comment]
> > 这个在pwa模式中暂时解决不了
> 
> 解决不了的原因是什么？

原生webview容器层面的事，你可以看下同类的pwa应用也无解 比如chat next

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/assets/28616219/aa64a40d-83cf-4f19-947a-b4dbd8ad1233

@canisminor1990 试了个其他类别的pwa 应用，跟 pwa 看起来没关系。这个就是可以正常显示的。

https://stackedit.io/app#

**Comment by canisminor1990** [comment]
你测得太靠上了https://github.com/lobehub/lobe-chat/assets/17870709/8c992164-4ffc-448f-b021-05aef9e4d747

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/assets/28616219/3df1fbdd-2e07-4ac9-a734-ce341f982332

我试了下 ios下 只有出现了一次偏移。我感觉是可以用啥方式解决的

**Comment by arvinxx** [comment]
哦 我知道了，跟光标激活位置有关。如果在上半屏，那么不会拉起来。如果是下半屏是会拉起来

**Comment by canisminor1990** [comment]
@arvinxx 对 他是把整个原生容器顶起来，所以没办法解

**Comment by canisminor1990** [comment]
原生 app 里 nav 和 view 是分离的，所以可以实现 nav 是固定的

**Comment by arvinxx** [comment]
我看到有个可能的解法是 webview 顶起来以后，其实 height size 是变了的，这个时候做个媒体查询来调整布局 可行么

**Comment by canisminor1990** [comment]
> 我看到有个可能的解法是 webview 顶起来以后，其实 height size 是变了的，这个时候做个媒体查询来调整布局 可行么

太hack而且 处理不了fix布局

**Comment by junyangfan** [comment]
> > 我看到有个可能的解法是 webview 顶起来以后，其实 height size 是变了的，这个时候做个媒体查询来调整布局 可行么
> 
> 太hack而且 处理不了fix布局

我看确实没有特别好的处理办法，都是根据软键盘展示与否动态调整位置，fix布局是布局的head吗？有没有可能把bottom那个组件独立出来，动态调整位置

**Comment by canisminor1990** [comment]
> > > 我看到有个可能的解法是 webview 顶起来以后，其实 height size 是变了的，这个时候做个媒体查询来调整布局 可行么
> > 
> > 太hack而且 处理不了fix布局
> 
> 我看确实没有特别好的处理办法，都是根据软键盘展示与否动态调整位置，fix布局是布局的head吗？有没有可能把bottom那个组件独立出来，动态调整位置

很难，因为你获取不到虚拟键盘真实高度，就算用算的面对不同的虚拟键盘也会遇到很多边界情况，在原生app开发里其实都有类似的情况，上面说的fix是 css position fix, 这个会强制follow webview定位而不是内部容器
