### ISSUE TITLE
[Bug] 使用 mandrillai 的接口时，调用插件会回复空

### ISSUE THREAD

**Issue by jjssjdhhd** [lobehub/lobe-chat#619]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

使用mandrillai的接口时，调用插件会回复空。 
![screenshot20231212](https://github.com/lobehub/lobe-chat/assets/131100864/f2ed7637-2211-4128-8593-33d483bcc3f9)

**Comment by arvinxx** [comment]
是否和 #617  是同一个问题？

**Comment by jjssjdhhd** [comment]
> 是否和 #617  是同一个问题？

不是，我加v1了，还是不行，不用插件就能回复，用了就返回值为空

**Comment by arvinxx** [comment]
> > 是否和 #617  是同一个问题？
> 
> 不是，我加v1了，还是不行，不用插件就能回复，用了就返回值为空

如果只是插件的问题，可能和 #592 有关
