### ISSUE TITLE
[Request] Remove System prompt intro and end part 

### ISSUE THREAD

**Issue by MarArMar** [lobehub/lobe-chat#628]
### 🥰 需求描述 | Feature Description

System prompts begins with "Hello, I'm <name>" and ends with "... Let's start the conversation!"

I am using system prompts that do not use them and want to remove them			

### 🧐 解决方案 | Proposed Solution

An option or toggle to remove the  "Hello, I'm <name>" and "... Let's start the conversation!"

**Comment by arvinxx** [comment]
System role will enter the chat context. The hello message will disappear after you start chatting
