### ISSUE TITLE
[Request] 增加 gpt-3.5-turbo-1106 支持

### ISSUE THREAD

**Issue by devyujie** [lobehub/lobe-chat#633]
### 🥰 需求描述 | Feature Description

增加 gpt-3.5-turbo-1106 支持

### 🧐 解决方案 | Proposed Solution

增加 gpt-3.5-turbo-1106 支持

### 📝 补充信息 | Additional Information

增加 gpt-3.5-turbo-1106 支持

**Comment by arvinxx** [comment]
无需增加. refs:  #554
