### ISSUE TITLE
[Request] French Translation

### ISSUE THREAD

**Issue by dreygraph** [lobehub/lobe-chat#637]
### 🥰 需求描述 | Feature Description

The application currently supports English as the primary language. However, as a user, I have noticed a significant number of users who would benefit from French language support. Adding a French translation would greatly enhance the user experience and accessibility for French-speaking users, and potentially expand the application's user base.

### 🧐 解决方案 | Proposed Solution

Consider integrating an internationalization library, such as i18n, to add the French language support. This would involve creating a French language file containing translations for all the application strings. Additionally, a language switcher could be added to the user interface, allowing users to easily switch between English and French as per their preference.

### 📝 补充信息 | Additional Information

I used lobehub to generate the content of this issue. 🤓

**Comment by canisminor1990** [comment]
@dreygraph Voilà qui est fait~ Veuillez profiter de l'interface en français avec plaisir. Si jamais vous trouvez des erreurs de traduction, n'hésitez pas à nous faire part de vos retours et à proposer des corrections (PR). 💞
