### ISSUE TITLE
[Request] Is it possible to have multiple passwords

### ISSUE THREAD

**Issue by MissingTwins** [lobehub/lobe-chat#638]
### 🥰 需求描述 | Feature Description

Same at the topic

### 🧐 解决方案 | Proposed Solution

`ACCESS_CODE=password1, password2, passwordN`

**Comment by arvinxx** [comment]
why？

**Comment by MissingTwins** [comment]
This project looks really promising, if we can have multiple passwords, it will be even better.
 
What if I hope to share this with a few family members or friends?
I can assign a unique password to each one. If one of the passwords is leaked, or if I decide to stop sharing with one of them, I can simply revoke that password without needing to ask everyone else to change theirs.

There is no needs of tight security, but some level of isolation for each user is preferred.

**Comment by arvinxx** [comment]
@MissingTwins Ok.I get it. I think it can be an enhance feature. And PR welcome~

**Comment by izk-20197** [comment]
Hey how do i get a password?
