### ISSUE TITLE
[Request] 支持Azure的GPT-4 Vision

### ISSUE THREAD

**Issue by Lerty** [lobehub/lobe-chat#639]
### 🥰 需求描述 | Feature Description

希望支持多模态聊天，针对Azure 的GPT-4-Vision模型。

### 🧐 解决方案 | Proposed Solution

支持流式显示，输入图片聊天，调用Azure GPT-4 Vision模型

**Comment by arvinxx** [comment]
azure的4v model 和其他 model 调用时有啥区别？

如果没区别的话，现在的机制应该是直接支持的

**Comment by Lerty** [comment]
需要使用REST API，然后指定 deployment name 和 自定义的azure endpoint，api-key，以及api-version。


Send a POST request to https://{RESOURCE_NAME}.openai.azure.com/openai/deployments/{DEPLOYMENT_NAME}/chat/completions?api-version=2023-12-01-preview

Required headers:

Content-Type: application/json
api-key: {API_KEY}

 request body：
{
    "messages": [ 
        {
            "role": "system", 
            "content": "You are a helpful assistant." 
        },
        {
            "role": "user", 
            "content": [ 
               { "type": "text", "text": "Describe this picture:" }, 
               { "type": "image_url", "url": "<URL or base-64-encoded image>" } 
           ] 
        }
    ],
    "max_tokens": 100, 
    "stream": false 
}


响应的样例：

{
    "id": "chatcmpl-8Uyxu7xpvngMZnvMhVAPpiI3laUef",
    "object": "chat.completion",
    "created": 1702394882,
    "model": "gpt-4",
    "choices":
    [
        {
            "finish_details":
            {
                "type": "stop",
                "stop": "<|fim_suffix|>"
            },
            "index": 0,
            "message":
            {
                "role": "assistant",
                "content": "This picture depicts a grayscale image of an individual showcasing dark hair combed to one side, and the tips of their ears are also visible. The person appears to be dressed in a casual outfit with a hint of a garment that has a collar or neckline. The background is a plain and neutral shade, creating a stark contrast with the subject in the foreground."
            }
        }
    ],
    "usage":
    {
        "prompt_tokens": 816,
        "completion_tokens": 71,
        "total_tokens": 887
    }
}

**Comment by Lerty** [comment]
把Azure的部署名字改成 官方openai的vision名字，即可正常运行，谢谢，我自己关了这个case
![image](https://github.com/lobehub/lobe-chat/assets/17094974/8f8d8ddb-dcc4-4078-a801-28c81a6e0a31)

**Comment by itcodes** [comment]
> 把Azure的部署名字改成 官方openai的vision名字，即可正常运行，谢谢，我自己关了这个case ![image](https://private-user-images.githubusercontent.com/17094974/290111137-8f8d8ddb-dcc4-4078-a801-28c81a6e0a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTI2NDAsIm5iZiI6MTcxMDg1MjM0MCwicGF0aCI6Ii8xNzA5NDk3NC8yOTAxMTExMzctOGY4ZDhkZGItZGNjNC00MDc4LWE4MDEtMjhjODFhNmUwYTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEyNDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNWIzOWM3OTA2NDdkZWRhOGFiZGNkZmUwNGIwOTY2MWZlNmFhMjQ2ZjFlMjVhYWZhMmI2MGJiNTBjM2IwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eZoGjYptYvPEpE9JyBJhRsQfn26u6jNlWHsH2iFosTs)

咋解决的？哥们
