### ISSUE TITLE
[Bug] 反向代理的API无法保存

### ISSUE THREAD

**Issue by hileel** [lobehub/lobe-chat#642]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

我使用了反向代理的接口地址，无法保存和使用

**Comment by arvinxx** [comment]
请详细描述

**Comment by mosas** [comment]
I'm having same problem, when using api-key along with api proxy address. 
use connectivity check at setting, nothing happens, no warning or confirmative sign. 
go back to chat window, it will response nothing.

**Comment by mushan0x0** [comment]
服务地址末尾要加一个/v1路径，请检查是否是相同问题

https://github.com/lobehub/lobe-chat/discussions/623#discussioncomment-7827313

<img width="917" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/8021a6ce-cc43-4deb-b373-c66756401e98">

**Comment by mosas** [comment]
solved. 
it is a little bit weird to add /v1, but thanks for your job!
