### ISSUE TITLE
[Bug] GPT-4 Vision 上传超过1张图片会直接提示上游服务器无响应

### ISSUE THREAD

**Issue by Lerty** [lobehub/lobe-chat#646]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/17094974/f2126919-d656-4bd3-a46e-ab09780ea6d0)

### 🚦 期望结果 | Expected Behavior

我使用API，可以正常进行多图片聊天，比如同时上传2个图片对比不同。OpenAI说明单次聊天调用最多支持10张图片。

### 📷 复现步骤 | Recurrence Steps

1、使用GPT-4-Vision 模型
2、上传2个图片，随便输入什么文字都行

### 📝 补充信息 | Additional Information

点击项目首页的使用Vercel部署的。

**Comment by Lerty** [comment]
如果是单张图片，则正常响应。
![image](https://github.com/lobehub/lobe-chat/assets/17094974/0ddf571b-b5f1-47eb-9f1b-63d2b3dba109)

**Comment by mushan0x0** [comment]
未复现

<img width="614" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/9cb4ff28-76d2-428f-96d7-30e1a7835ef4">

**Comment by arvinxx** [comment]
可能是图片很大造成的，比如上传图片用时很久，openai那边响应也很久，最后就导致超时了

**Comment by arvinxx** [comment]
@BrandonStudio by now we don't support
