### ISSUE TITLE
[Question] Docker 部署更新容器

### ISSUE THREAD

**Issue by cyx1322** [lobehub/lobe-chat#648]
### 🧐 问题描述 | Proposed Solution

使用docker部署后，如何更新容器映像，并保留原有数据呢？

**Comment by mushan0x0** [comment]
部署了就要用起来呀

<img width="652" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/abe46488-7516-443b-a861-6f7885a79588">

**Comment by cyx1322** [comment]
但是这样更新会丢失客户端上的数据的

**Comment by mushan0x0** [comment]
<img width="700" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/99bbff09-17c0-464a-aa00-c698578635d1">

**Comment by cyx1322** [comment]
不行的，我之前按照这种方法更新的，需要重新填密码的，而且会话也都丢了

**Comment by mushan0x0** [comment]
这些数据是存在浏览器上的，你是域名变了吗

**Comment by zhuozhiyongde** [comment]
我写个一个更新并重新部署脚本：

```bash
docker rm -f Lobe-Chat
docker pull lobehub/lobe-chat
docker run -d --network=host -e OPENAI_API_KEY=sk-XXXX -e ACCESS_CODE="" --name=Lobe-Chat --restart=always lobehub/lobe-chat
docker images | grep 'lobehub/lobe-chat' | grep -v 'latest' | awk '{print $3}' | xargs docker rmi
```

**Comment by cyx1322** [comment]
刚才又试了一下，确实不会丢数据。谢谢二位帮忙
