### ISSUE TITLE
[Request] Support for Google Gemini Pro and Vision models

### ISSUE THREAD

**Issue by mitdave95** [lobehub/lobe-chat#650]
### 🥰 需求描述 | Feature Description

Support for Google Gemini Pro and Vision models
https://cloud.google.com/vertex-ai?hl=en

### 🧐 解决方案 | Proposed Solution

Access can be optional if api key is set in environment variables. This can also be extended to Gemini Ultra model which will be released in future

**Comment by mitdave95** [comment]
Also support for Mixtral LLMs [https://api.together.xyz]
Apparently they follow the same convention as OpenAI (https://x.com/togethercompute/status/1734680608855728541?s=20)

**Comment by hallfay0** [comment]
Hope to achieve it as soon as possible
