### ISSUE TITLE
[Request] 增加谷歌AI的模型接入

### ISSUE THREAD

**Issue by laike** [lobehub/lobe-chat#656]
### 🥰 需求描述 | Feature Description

https://www.youtube.com/watch?v=0UfU1I88R30

google发布了最新，最强大的语言模型：Gemini。

12月13日，开发者终于可以通过API在应用程序中接入Gemini Pro。

### 🧐 解决方案 | Proposed Solution

google发布了最新，最强大的语言模型：Gemini。

12月13日，开发者终于可以通过API在应用程序中接入Gemini Pro。

**Comment by mushan0x0** [comment]
重复 https://github.com/lobehub/lobe-chat/issues/650

**Comment by cigolnam** [comment]
顶楼主。

**Comment by haizimajia** [comment]
顶

**Comment by thedavidweng** [comment]
希望也可以参考 [babaohuang/gemini-pro-chat](https://github.com/babaohuang/gemini-pro-chat) 提供对 [API Proxy](https://github.com/antergone/palm-netlify-proxy) 的支持，Google 目前对区域的限制比 OpenAI 还多。
