### ISSUE TITLE
[Request] Add more languages for the users

### ISSUE THREAD

**Issue by thijsvanhal** [lobehub/lobe-chat#659]
### 🥰 需求描述 | Feature Description

To add more languages for the users. Some big languages:

- [x] Spanish
- [x] German
- [ ] Polish
- [ ] Dutch
- [x] Portuguese
- [x] Turkish
- [ ] Italian
- [ ] Arabic

### 🧐 解决方案 | Proposed Solution

Translate using i18n

### 📝 补充信息 | Additional Information

Thanks a lot for doing this!

**Comment by arvinxx** [comment]
Arabic has some RTL issue, so we don't add it right now.
