### ISSUE TITLE
[Question] 使用docker-compose 部署并用nginx 反代时 带参数访问会报错

### ISSUE THREAD

**Issue by unknown-0054** [lobehub/lobe-chat#664]
### 🧐 问题描述 | Proposed Solution

![image](https://github.com/lobehub/lobe-chat/assets/93303847/0d8a6a88-a099-42a9-aefd-52a69a01341e)

```
server {
    listen       443 ssl http2;
    server_name  doamin;

    ssl_certificate       cer;
    ssl_certificate_key key;

    ssl_session_timeout  5m;

    location / {
        proxy_pass http://127.0.0.1:3210;
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header REMOTE-HOST $remote_addr; 
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection "upgrade"; 
        proxy_http_version 1.1; 
        add_header Cache-Control no-cache; 
        proxy_cache off;  # 关闭缓存
        proxy_buffering off;  # 关闭代理缓冲
        chunked_transfer_encoding on;  # 开启分块传输编码
        tcp_nopush on;  # 开启TCP NOPUSH选项，禁止Nagle算法
        tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
        keepalive_timeout 300;  # 设定keep-alive超时时间为65秒
    }
}

```

**Comment by mushan0x0** [comment]
https://github.com/lobehub/lobe-chat/issues/528#issuecomment-1833818271 试试这个配置呢

**Comment by unknown-0054** [comment]
> [#528 (comment)](https://github.com/lobehub/lobe-chat/issues/528#issuecomment-1833818271) 试试这个配置呢



> [#528 (comment)](https://github.com/lobehub/lobe-chat/issues/528#issuecomment-1833818271) 试试这个配置呢

依旧会报错

**Comment by arvinxx** [comment]
纯ip访问是否正常

**Comment by unknown-0054** [comment]
> 纯ip访问是否正常

正常 所以就很奇怪

**Comment by arvinxx** [comment]
> > 纯ip访问是否正常
> 
> 正常 所以就很奇怪

那应该是 nginx 的反代问题，可能要排查下。不妨问问 GPT

**Comment by arvinxx** [comment]
是否和 #761 是同一个问题

**Comment by unknown-0054** [comment]
看js报错时的调用栈 一样, 应该是同一个问题

**Comment by arvinxx** [comment]
> 看js报错时的调用栈 一样, 应该是同一个问题

调用栈能否贴出来一下？

**Comment by unknown-0054** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/93303847/1b678b8a-3abc-45d8-b778-836ce16aa64a)
![image](https://github.com/lobehub/lobe-chat/assets/93303847/c81797ab-018b-4ef5-b0e3-cb0254029d8f)
我和他之前报错 完全一致.
不过我刚刚重新用docker搭建+nginx 反代 并没有复现这个问题.

**Comment by arvinxx** [comment]
行，如果还会遇到的话再补充贴进来吧
