### ISSUE TITLE
[Bug] gpt-4-vision模型发送图片返回413错误，建议增加客户端图片压缩

### ISSUE THREAD

**Issue by lixplor** [lobehub/lobe-chat#668]
图像视觉模型对话单张照片返回413错误，感觉是照片过大导致请求体过大报错。
每次手动处理图片不太人性化，建议增加浏览器端选择图片后进行压缩，然后发送

![image](https://user-images.githubusercontent.com/10572807/290738344-a287a0ff-c81a-4a34-86a3-09341acf5550.png)

**Comment by mushan0x0** [comment]
refs: https://github.com/lobehub/lobe-chat/issues/646#issuecomment-1857315986

**Comment by arvinxx** [comment]
合理的，PC端上感觉问题不大，移动端上这个问题感觉会很明显。后面给加上~

**Comment by caocanx** [comment]
iOS，版本`v0.115.6`还能复现这个问题

**Comment by esmeetu** [comment]
0.119仍有这个问题，ios端safafi浏览器测试，测试下来与分辨率有关，当图片超过768x768就会返回413。桌面没有问题。 @arvinxx @mushan0x0
