### ISSUE TITLE
[Bug] 设置-语言模型-API Key 密码回显的是ACCESS_CODE

### ISSUE THREAD

**Issue by Sunxiaomo311** [lobehub/lobe-chat#671]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

通过Vercel一键部署成功，访问设置界面。正常回显应该是sk开头的api key，但目前显示的是部署时设置的ACCESS_CODE
![image](https://github.com/lobehub/lobe-chat/assets/39626778/fceb98d6-33ac-4e8e-9b26-71999f15d9fe)

### 🚦 期望结果 | Expected Behavior

修复bug

**Comment by mushan0x0** [comment]
这个是你浏览器记住的访问密码，API Key 是不会回显的

**Comment by Sunxiaomo311** [comment]
好的，感谢。这个功能对我来说有些混淆了，我还是期望通过点击
![image](https://github.com/lobehub/lobe-chat/assets/39626778/be6d8a65-4129-4c2c-90c1-b56e760ee235)
按钮能显示我部署时导入的OpenAI API Key

**Comment by arvinxx** [comment]
> 好的，感谢。这个功能对我来说有些混淆了，我还是期望通过点击 ![image](https://private-user-images.githubusercontent.com/39626778/290764823-be6d8a65-4129-4c2c-90c1-b56e760ee235.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MjkxODksIm5iZiI6MTcwMjYyODg4OSwicGF0aCI6Ii8zOTYyNjc3OC8yOTA3NjQ4MjMtYmU2ZDhhNjUtNDEyOS00YzJjLTkwYzEtYjU2ZTc2MGVlMjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA4MjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZjhjMTA3MDVkMDA2M2U4ZmQ4MzUwNzM5YzQ4MzczZWY0MzEzNzgzN2U3OTQ0OTg3NmE4NzUwNTBjYTJlMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SWjaApYOAcUbkIOr5b4nbIc1g9R8ECoMZzZL5tCIV6A) 按钮能显示我部署时导入的OpenAI API Key

这是不可能的。相当于 服务端密码在客户端泄密了

你总不希望自己把网站分享给朋友的时候，他们可以在你这边点一下就能看到你的 api key 了吧
