### ISSUE TITLE
[Question] 请问docker部署中，是否有参数，能禁止输入key

### ISSUE THREAD

**Issue by Lenspace** [lobehub/lobe-chat#674]
### 🧐 问题描述 | Proposed Solution

部署了一个，也设置了密码，然后发现，如果没有密码的情况下，直接在后台页面里，设置key以及代理地址，就可以正常使用。
请问，是否有相关参数，能禁止此功能？

**Comment by arvinxx** [comment]
目前好像还没有禁止输入apikey的配置。可以考虑加一个。
