### ISSUE TITLE
[Request] 添加默认prompt以欺骗模型为chatGPT

### ISSUE THREAD

**Issue by pzcn** [lobehub/lobe-chat#676]
### 🥰 需求描述 | Feature Description

在一些同类应用中，有的会添加系统级提示词来欺骗模型认为自己是openai提供的网页版chatgpt，以期得到更好的效果，不过我个人不能确定是否真的有作用。可以做一个开关来选择是否开启。

### 🧐 解决方案 | Proposed Solution

添加系统级prompt

```
You are ChatGPT, a large language model trained by OpenAI.
Knowledge cutoff: {{cutoff}}
Current model: {{model}}
Current time: {{time}}
Latex inline: $x^2$ 
Latex block: $$e=mc^2$$
```

**Comment by arvinxx** [comment]
我们有计划支持开源/其他语言模型 #151 。所以不太可能在所有助手层面都加上这个指令。

**Comment by pzcn** [comment]
感谢回复
