### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by lixiaoqin0218** [lobehub/lobe-chat#678]
### 🧐 问题描述 | Proposed Solution

1. pull main branch 
2. bun install
3. bun dev
then
update openaikey

always error:
{
  "endpoint": "https://api.openai.com/v1",
  "error": {
    "cause": {
      "errno": -54,
      "code": "ECONNRESET",
      "syscall": "read"
    }
  }
}

why? could you help ？
<img width="1115" alt="image" src="https://github.com/lobehub/lobe-chat/assets/31536111/c8edd93f-48ad-4023-aa17-9c06c771956f">

**Comment by arvinxx** [comment]
please make sure you can visit the openai api endpoint

**Comment by lixiaoqin0218** [comment]
yes, i put the openai key to another chatgpt([chat next gp](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web),it worked!
<img width="1050" alt="image" src="https://github.com/lobehub/lobe-chat/assets/31536111/cd985595-5067-40f2-8646-8caa19de0cd8">

**Comment by lixiaoqin0218** [comment]
i delete code of my mac ,and pull newest code from main branch,then it worked!

**Comment by lixiaoqin0218** [comment]
Today,the issue return back !!

error messages:
<img width="1105" alt="Pasted Graphic 8" src="https://github.com/lobehub/lobe-chat/assets/31536111/d6a1b470-6192-47bf-8892-5a7e1d29a6b5">
<img width="605" alt="Pasted Graphic 9" src="https://github.com/lobehub/lobe-chat/assets/31536111/db3ff5e0-1647-461e-aa65-49912ca39095">

and i am sure openai key is ok!  
<img width="1187" alt="Pasted Graphic 7" src="https://github.com/lobehub/lobe-chat/assets/31536111/485f24be-04c1-4f3f-83db-c343f725f5c9">

i need help!  @arvinxx

**Comment by arvinxx** [comment]
@lixiaoqin0218 我咋感觉是你网络问题呢…

**Comment by lixiaoqin0218** [comment]
感谢！ 我搭个代理服务重新试下

**Comment by arvinxx** [comment]
可以参考： https://github.com/lobehub/lobe-chat/discussions/466

**Comment by lixiaoqin0218** [comment]
搭建了一个azure open ai，在azure的playground是正常的，如图：
![image](https://github.com/lobehub/lobe-chat/assets/31536111/6da9c1a6-84f1-4ce4-9b1c-b10ecc9dc5db)

but，终端请求竟然是404！
<img width="724" alt="image" src="https://github.com/lobehub/lobe-chat/assets/31536111/1f1622b0-c50b-45dc-9a22-bc366ad3c40d">

百思不得其解~~~

**Comment by lixiaoqin0218** [comment]
> 可以参考： #466

这种deploy后的域名，公司网络限制无法访问，得找个🪜

**Comment by lixiaoqin0218** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/31536111/df3749de-845f-47a4-80b6-4b7b277b8090)

这个红框里并不是我的azure open ai的deployment name ,  难道是个bug?

**Comment by PeifengRen** [comment]
> ![image](https://private-user-images.githubusercontent.com/31536111/292390250-df3749de-845f-47a4-80b6-4b7b277b8090.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzAwNjIsIm5iZiI6MTcwMzIyOTc2MiwicGF0aCI6Ii8zMTUzNjExMS8yOTIzOTAyNTAtZGYzNzQ5ZGUtODQ1Zi00N2E0LTgwYjYtNGI3YjI3N2I4MDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA3MjI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZWJkOWM5ZTdjNzM2ZTI1ZjdhMTI5ZDBkM2YwN2JmNTZmOTI1ZDcxYmY0ODdjMzA5YjFkYzM3MWI1NzhiYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WuSdEpSbfJ30kcyBUgaeDZPcRXsOaIVvld4j3XeDydg)
> 
> 这个红框里并不是我的azure open ai的deployment name , 难道是个bug?

我也遇到一样的问题了。填写完model_name后，测试的时候依然是gpt-35-turbo
