### ISSUE TITLE
Let users select model version: 0314 or 0613

### ISSUE THREAD

**Issue by sagarspatil** [lobehub/lobe-chat#679]
### 🥰 需求描述 | Feature Description

Currently, the web app only let's you select GPT-4 which in turn uses the latest version of the API. For coding related tasks I find GPT-4 0314 version to be the best. 

### 🧐 解决方案 | Proposed Solution

After a user selects GPT-4, provide him an option to select old versions such as 0613 or 0314.

**Comment by sagarspatil** [comment]
Any plans to support this feature? If not, can you provide instructions on how to do this?

**Comment by arvinxx** [comment]
It can be support with `CUSTOM_MODELS`, refs: #684 . But there is a bug with the dockcer version.

**Comment by sagarspatil** [comment]
Thank you for taking a look at it. Please keep us updated.
