### ISSUE TITLE
[Pref] 性能有点差

### ISSUE THREAD

**Issue by guowc** [lobehub/lobe-chat#68]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

每次刷新都要加载大量远程资源，路由切换3-4s，组件加载，事件响应感觉都很卡顿，相比同技术栈的Yidaaaaaa/next，整体性能和体验差了不少，对React不是很熟悉，不知道问题出在哪？
<img width="805" alt="image" src="https://github.com/lobehub/lobe-chat/assets/11242226/6214c723-05cf-4310-96c0-4421d4300c67">

**Comment by arvinxx** [comment]
<img width="1914" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/f05838b6-8a2c-43aa-b752-fa3936a72468">

我自己的电脑测试下来还挺快的呀。 大量文件的加载是因为我们使用了 `shiki-es` 这个包来做语法高亮，它会动态加载相应的语法高亮 json。相应的好处就是所有的高亮都可以达到 VSCode 原生级别，牺牲就是每次都会拉一遍 json。但浏览器有缓存，我觉得问题不大。

路由切换慢的问题我有发现，正在研究是否是因为使用 nextjs 的动态路径的原因，考虑是否切回 query 方案 https://github.com/lobehub/lobe-chat/issues/72

**Comment by arvinxx** [comment]
我们已经将 shiki-es 切换成了更加先进的 shikiji ，已经不会再重复加载 json 文件了。

**Comment by arvinxx** [comment]
路由切换已经在 https://github.com/lobehub/lobe-chat/pull/157 中切换为 hash 模式。 同时存储方案升级为 indexedDB (https://github.com/lobehub/lobe-chat/pull/160)，欢迎再体验一下。

目前看应该没有性能问题了，这个issue先关了。如果觉得还有问题可以 repopen

**Comment by Cp0204** [comment]
也不知道怎么原因，真的特别卡顿，在栏目切换、对话窗口切换之间，等1~2秒才反应过来
