### ISSUE TITLE
[Request] 请求增加tts输出语音的下载功能

### ISSUE THREAD

**Issue by ohotto** [lobehub/lobe-chat#680]
### 🥰 需求描述 | Feature Description

希望可以下载tts生成的语音文件为mp3或wav，以便分享

### 🧐 解决方案 | Proposed Solution

在现有的删除按钮旁边添加一个下载按钮

### 📝 补充信息 | Additional Information

感谢辛苦开发！

**Comment by canisminor1990** [comment]
> ### 🥰 需求描述 | Feature Description
> 希望可以下载tts生成的语音文件为mp3或wav，以便分享
> 
> ### 🧐 解决方案 | Proposed Solution
> 在现有的删除按钮旁边添加一个下载按钮
> 
> ### 📝 补充信息 | Additional Information
> 感谢辛苦开发！

可以下载，不过目前可能有点隐晦，你 hover 时间的时候就会出现一个 下载选项，这块会在近期改进

**Comment by canisminor1990** [comment]
https://github.com/lobehub/lobe-chat/commit/6882752a0d4e6c9314554df200ee96c7a61ac352

**Comment by ohotto** [comment]
我找到了！谢谢
可能是在iPad端，Hover的操作不太容易达成
