### ISSUE TITLE
关于配置环境变量NEXT_PUBLIC_CUSTOM_MODELS

### ISSUE THREAD

**Issue by cyx1322** [lobehub/lobe-chat#684]
### 🧐 问题描述 | Proposed Solution

我使用docker部署容器的时候，给了如下的环境变量：
-e NEXT_PUBLIC_CUSTOM_MODELS=-all,+gpt-3.5-turbo,+gpt-4,+gpt-4-1106-preview,gpt-4-1106-preview=gpt-4-turbo \
但部署完之后发现模型还是默认的几个，请问配置哪里出现了问题？谢谢！

**Comment by arvinxx** [comment]
这个是 bug ，近期修复

 refs: #509
