### ISSUE TITLE
[Bug] Vercel部署，NEXT_PUBLIC_CUSTOM_MODELS 参数不起作用

### ISSUE THREAD

**Issue by B3nDan** [lobehub/lobe-chat#685]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

 Vercel部署本项目，打开后可以正常使用。
然后配置 NEXT_PUBLIC_CUSTOM_MODELS 并重新部署
在原来的浏览器刷新后发现 模型列表 **并未更新**
但是在新的浏览器环境下会显示更新后的 模型列表

### 🚦 期望结果 | Expected Behavior

刷新后，模型列表显示 更新后的内容

### 📷 复现步骤 | Recurrence Steps

Vercel部署本项目，浏览器打开一次后，
再配置 NEXT_PUBLIC_CUSTOM_MODELS 并重新部署，再第二次在同一个浏览器打开

### 📝 补充信息 | Additional Information

![Shot 2023-12-16 at 23 21 47@2x](https://github.com/lobehub/lobe-chat/assets/129975925/5c52617b-b409-4300-82f8-21bb8fe12263)
![Shot 2023-12-16 at 23 25 27@2x](https://github.com/lobehub/lobe-chat/assets/129975925/66e2b8cb-4836-433d-90c8-fb6b9428f002)

**Comment by reece00** [comment]
……CTRL+F5刷新浏览器

**Comment by arvinxx** [comment]
尝试替换使用 `CUSTOM_MODELS` 变量
