### ISSUE TITLE
[Request] Ability to upload multiple files and  generate some visuals or fill the files 

### ISSUE THREAD

**Issue by zeyadalmothafar** [lobehub/lobe-chat#686]
### 🥰 需求描述 | Feature Description

Ability to upload multiple files like Excel, CSV, and text documents like PDF and Word files and generate some visuals using the data inside the files or answer user questions based on the data inside
Fill the files with certain data from a web search, do some calculations on the data, and add new columns, or fill Excel files from other uploaded documents based on some logic requested by the user

### 🧐 解决方案 | Proposed Solution

-Add the upload files button to the interface
-Send the files to a code interpreter from OpenAI or send them to an OpenAI assistant

**Comment by sunzongjian** [comment]
你好，请问这个需求实现了吗？我发现即使启用askPDF插件，也没能找到上传文件的按钮，即使切换的模型gpt-4-vision-preview也只能发现上传图片的功能按钮，详情如下图所示。
![image](https://github.com/lobehub/lobe-chat/assets/24264891/a5b91202-f19c-4e16-acd2-13cccf31bc22)
![image](https://github.com/lobehub/lobe-chat/assets/24264891/49d739ac-2cc0-449c-86ee-c7ee1fb9fd5d)

**Comment by jkhcc11** [comment]
貌似这个AskYouPDF插件，需要更新了。不确定是不是我没有付费的原因，刚开始还可以。
![image](https://github.com/lobehub/lobe-chat/assets/28553032/da0a5efd-8e4e-42b8-af01-aa301f981338)

**Comment by jkhcc11** [comment]
> 你好，请问这个需求实现了吗？我发现即使启用askPDF插件，也没能找到上传文件的按钮，即使切换的模型gpt-4-vision-preview也只能发现上传图片的功能按钮，详情如下图所示。 ![image](https://private-user-images.githubusercontent.com/24264891/292612377-a5b91202-f19c-4e16-acd2-13cccf31bc22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTE0OTAsIm5iZiI6MTcwMzQ5MTE5MCwicGF0aCI6Ii8yNDI2NDg5MS8yOTI2MTIzNzctYTViOTEyMDItZjE5Yy00ZTE2LWFjZDItMTNjY2NmMzFiYzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA3NTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MWQ2MjhlZjVlYmM4NjBmOTQwOWViMjRhYzA0MWU3MmM1NjdhNjQ0YzQ4YjIxOGJiZDk2ODIzZWIyNTgzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m76tygRED3vXEuN9c-We3SiZ-aXnFRE-8QVh4A0c2Ys) ![image](https://private-user-images.githubusercontent.com/24264891/292612399-49d739ac-2cc0-449c-86ee-c7ee1fb9fd5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTE0OTAsIm5iZiI6MTcwMzQ5MTE5MCwicGF0aCI6Ii8yNDI2NDg5MS8yOTI2MTIzOTktNDlkNzM5YWMtMmNjMC00NDljLTg2ZWUtYzdlZTFmYjlmZDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA3NTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNmY2N2IwMzIyNDVmMjFjNGJkNzg0MTg0OTI3ZTNkZWFjNTgyMWY1ZmE4ZWJlMDU0OTMxYzY4MzZiZTkxMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UwLJPgDMJ2Y-EeulPefTTWLONo8nwkIwGBZ79EZhfi8)



> 你好，请问这个需求实现了吗？我发现即使启用askPDF插件，也没能找到上传文件的按钮，即使切换的模型gpt-4-vision-preview也只能发现上传图片的功能按钮，详情如下图所示。 ![image](https://private-user-images.githubusercontent.com/24264891/292612377-a5b91202-f19c-4e16-acd2-13cccf31bc22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTM5NzIsIm5iZiI6MTcwMzQ5MzY3MiwicGF0aCI6Ii8yNDI2NDg5MS8yOTI2MTIzNzctYTViOTEyMDItZjE5Yy00ZTE2LWFjZDItMTNjY2NmMzFiYzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA4NDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMDhjNGUwNGJkMzNkM2QyYzk3NzBlYTcxNzgzOWM1NmQ2ZWM2ZDBmMmMyYzYzODU2NTRjYTMyMjdhMjdlZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ybUoQGgVjL0a8OCq9vPX9GyEqaUwpXlHZe26UVMt7s) ![image](https://private-user-images.githubusercontent.com/24264891/292612399-49d739ac-2cc0-449c-86ee-c7ee1fb9fd5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTM5NzIsIm5iZiI6MTcwMzQ5MzY3MiwicGF0aCI6Ii8yNDI2NDg5MS8yOTI2MTIzOTktNDlkNzM5YWMtMmNjMC00NDljLTg2ZWUtYzdlZTFmYjlmZDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA4NDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZjE0ZTBkYjdmODMwMmY4YjYzNmNkNjZmZDI2ZjQzOTY4Y2YwOThmYTYyMTVmMTE4YTc0ODMzNjg3ZjUwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.juFq1GSDprXvupXdqtPRSHPOmudBRE984Ok_44uyJRI)

这个是调用插件，需要进它的官网，上传文档后，然后把文件ID给它。
