### ISSUE TITLE
无法私有化部署lobe-chat-agents

### ISSUE THREAD

**Issue by cyx1322** [lobehub/lobe-chat#689]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

使用vercel部署，提示：Cloning An unexpected error occurred. Our team has already been notified and are working to resolve the issue, please try again shortly.
![截屏2023-12-17 09 45 16](https://github.com/lobehub/lobe-chat/assets/81369393/32b5e521-b37b-4055-aa42-777574897db5)

**Comment by arvinxx** [comment]
重试了么？

**Comment by cyx1322** [comment]
重试好几次了

**Comment by reece00** [comment]
不要用自动部署vercel，那玩意有问题，创建个vercel项目手动选择

**Comment by cyx1322** [comment]
> 不要用自动部署vercel，那玩意有问题，复制git然后创建个vercel项目手动选择

具体怎么配置呢?之前没用过vercel，大佬帮忙指点指点呗

**Comment by arvinxx** [comment]
@cyx1322 已修复。重新试试看
