### ISSUE TITLE
[Bug] docker部署，需增加环境变量network_mode: "host"后，才可以使用API

### ISSUE THREAD

**Issue by ccdanpian** [lobehub/lobe-chat#690]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

默认不增加该环境变量时，发送问题后，对话框返回ECONNRESET错误。
增加该环境变量后访问正常，只是端口号修改不会生效只能用默认的3210了。

部署docker的机器没有设置全局。

请帮忙看一下具体原因是什么？

**Comment by arvinxx** [comment]
你是不是没 map 端口额

**Comment by ccdanpian** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> Do you have no map port?

是指这一项吗，在不设置network_mode: "host"的时候，端口是可以用13210的，设置后就智能用3210了：
ports:
      - '13210:3210'

不过这个也没有关系，因为不会影响我正常使用。主要是想知道是否要必须加network_mode: "host？？

**Comment by arvinxx** [comment]
不需要。host模式是指网络端口直接使用宿主机的，相当于容器端口直接使用服务器的对外提供服务。

**Comment by arvinxx** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/28616219/35cb806a-8eb4-443a-b7cc-e035a327f7cf)

**Comment by ccdanpian** [comment]
这个issue主要是要确认为什么用host才能访问openai，不用host访问azure是没有问题的。

**Comment by arvinxx** [comment]
你的服务器能正常连到openai吗

**Comment by ccdanpian** [comment]
> 你的服务器能正常连到openai吗

我的服务器是openwrt，可以运行终端端口，请问您知道怎么检查是否可以连openai吗？
按说应该可以，要不然net设置成host也不连上。

**Comment by arvinxx** [comment]
@canisminor1990 软路由的问题来看看

**Comment by canisminor1990** [comment]
你进软路由里 和进容器后分别 curl 下 openai api 服务就能检查是否可以链 openai

**Comment by ccdanpian** [comment]
> 你进软路由里 和进容器后分别 curl 下 openai api 服务就能检查是否可以链 openai
> 
> `curl {{OPENAI_PROXY_URL}}/engines -H "Authorization: Bearer {{OPENAI_API_KEY}}"`

直接在软路由里是没有问题的，会出来一大串的engine，容器里没有找到在哪里运行。

**Comment by arvinxx** [comment]
@ccdanpian 这个问题，你之前是不是配置了服务器的代理 api 地址？ 比如 `http://127.0.0.1:xxxx/v1` 这样的？
