### ISSUE TITLE
[Request] 希望能同时支持openai和azure

### ISSUE THREAD

**Issue by ccdanpian** [lobehub/lobe-chat#691]
### 🥰 需求描述 | Feature Description

使用docker部署，目前好像不能通过在环境变量中修改配置参数，来同时支持openai和azure。希望能同时支持，并且azure的endpoint是否可以单独给一个环境变量，不要复用OPENAI_PROXY_URL。

### 🧐 解决方案 | Proposed Solution

1、希望能同时支持azure和openai的API；
2、并且azure的endpoint是否可以单独给一个环境变量，不要复用OPENAI_PROXY_URL;
3、希望在azure开启时，可以单独增加几个模型，并且模型的名字用'azure-'来开头。

**Comment by arvinxx** [comment]
请补充说明下场景？

**Comment by ccdanpian** [comment]
使用场景，主要是对于我本人来说的，因为azure付费比较友好，我希望能比较多的使用azure，只要在使用类似openai目前独有gpt vision等模型的时候，才用openai。

**Comment by rockets-cn** [comment]
公司采用的 azure openai，目前为止 azure 没有提供 gpt4 的高级功能，例如 vision。同事会选中相关模型，导致报错。希望去掉这两个高级模型，或两个都能提供。
The company uses Azure OpenAI, which so far does not offer the advanced features of GPT4, such as Vision. Colleagues will select the relevant model, resulting in an error. Hopefully remove both of these premium models, or both.

**Comment by arvinxx** [comment]
@ccdanpian 我最近在重构 azure openai 的实现，现在缺一个 apikey 做测试，是否方便借我一下？
