### ISSUE TITLE
[Bug] 表格bug

### ISSUE THREAD

**Issue by devyujie** [lobehub/lobe-chat#695]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

询问天气时，表格内容撑开，右边对话列表被隐藏，不知道就是这样设计的还是bug，也许可以给表格加个**固定宽度**和**下滚动条**？

### 📝 补充信息 | Additional Information

![image](https://github.com/lobehub/lobe-chat/assets/48620527/70a4f0f5-0e28-48cd-bdbf-402da3358ab6)

**Comment by arvinxx** [comment]
是bug，近期会修复
