### ISSUE TITLE
[Bug] Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by ohko** [lobehub/lobe-chat#696]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

iphone safari可以正常对话，但是访问有几个功能会出现：“Application error: a client-side exception has occurred (see the browser console for more information).”白屏的信息。

例如：设置->默认助手，还有对话时点击右上角的“三”菜单，就会出现这个问题。

链接电脑查看console错误，显示的是：
SyntaxError: Invalid regular expression: invalid group specifier name

![IMG_8591](https://github.com/lobehub/lobe-chat/assets/4863673/f1cede29-3c3a-4241-99a6-7fd914d85312)
![WX20231217-210734@2x](https://github.com/lobehub/lobe-chat/assets/4863673/7243da5d-a381-4759-b27c-6eb3671b7339)

**Comment by arvinxx** [comment]
有什么方法可以复现的么？提供一下你的设置文件？

**Comment by arvinxx** [comment]
设置默认助手 和随便聊聊的菜单是同一个地方。你想一下之前有没有修改过随便聊聊的配置？或者导出下你本地的设置出来

**Comment by ohko** [comment]
> 设置默认助手 和随便聊聊的菜单是同一个地方。你想一下之前有没有修改过随便聊聊的配置？或者导出下你本地的设置出来

未做过任何配置或修改，Docker部署好后就用手机访问的。iphone上是不是都有这个问题哟。

我用手机访问你们的“https://chat-preview.lobehub.com/settings/agent”演示，也同样白屏报这个错误。
浏览器的UserAgent是：`Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1`

**Comment by arvinxx** [comment]
我也是iPhone ，但是是正常的 ![image](https://github.com/lobehub/lobe-chat/assets/28616219/ae00de06-c469-4069-95bb-5f1bf0178648)

**Comment by ohko** [comment]
我两台iphone都不行，一台iphone12(ios14.1)，一台iphoneSE2(16.3.1)，浏览器版本不兼容？

我在另外一台iphone8(13.2.3)还发现了另外的问题（如图），直接卡在首页了：

![WX20231218-132411@2x](https://github.com/lobehub/lobe-chat/assets/4863673/17086dbe-1f38-4852-b7c1-835d679c2276)
![IMG_7704](https://github.com/lobehub/lobe-chat/assets/4863673/8e4a2442-e4df-426e-b026-b0d45269a81a)

**Comment by ohko** [comment]
这个问题能解决吗？手机上不能使用，好难受。

**Comment by canisminor1990** [comment]
> 这个问题能解决吗？手机上不能使用，好难受。

能否在抹去你的相关密码秘钥等隐私信息后导出一份全局设置上传到这里，我们需要复现才能定位问题

**Comment by ohko** [comment]
> > 这个问题能解决吗？手机上不能使用，好难受。
> 
> 能否在抹去你的相关密码秘钥等隐私信息后导出一份全局设置上传到这里，我们需要复现才能定位问题

[LobeChat-config-v2.json](https://github.com/lobehub/lobe-chat/files/13721465/LobeChat-config-v2.json)
这是从手机上道出的配置文件。不过我感觉应该是某些代码与浏览器不兼容问题造成的。

**Comment by ipengyo** [comment]
这个问题我也遇到过了，但是访问 https://lobe.ai0x0.com/  这个大佬部署的 在我的手机上是正常的 

我试过 safari 、微信浏览器  ，都是上述错误。

**Comment by ipengyo** [comment]
> 我两台iphone都不行，一台iphone12(ios14.1)，一台iphoneSE2(16.3.1)，浏览器版本不兼容？
> 
> 我在另外一台iphone8(13.2.3)还发现了另外的问题（如图），直接卡在首页了：
> 
> ![WX20231218-132411@2x](https://private-user-images.githubusercontent.com/4863673/291159043-17086dbe-1f38-4852-b7c1-835d679c2276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NjYzNjcsIm5iZiI6MTcwMzc2NjA2NywicGF0aCI6Ii80ODYzNjczLzI5MTE1OTA0My0xNzA4NmRiZS0xZjM4LTQ4NTItYjdjMS04MzVkNjc5YzIyNzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTIyMTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDUwZTU3NThiYzFhNzI3N2ViNGY2MmI4Mjg2NGJkOTJlZDc5MjNhMTA3NDhlZGNlOWYxZGJkODk4MzY4NTE4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Iy4kWqIfEky_lxoJSbQCO0FqpILDiw0peubh3m7AXD4) ![IMG_7704](https://private-user-images.githubusercontent.com/4863673/291159063-8e4a2442-e4df-426e-b026-b0d45269a81a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NjYzNjcsIm5iZiI6MTcwMzc2NjA2NywicGF0aCI6Ii80ODYzNjczLzI5MTE1OTA2My04ZTRhMjQ0Mi1lNGRmLTQyNmUtYjAyNi1iMGQ0NTI2OWE4MWEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTIyMTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJjYTFkMzZlNGYwMDk5NThkMmYzZGJkYmEzNzA2ZjUyZWZkMWQzNTg5NjAzNmY0ZWFlZDRjYWY4MzJmYTczNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.msjY2k6vOQV4zXxd1Gin6Hr5eYSfdRNWwJbH708oAK0)

我同事 使用 ios 17 版本的访问正常。

我的手机是ios 16.0.2 访问白屏。

**Comment by ohko** [comment]
> 这个问题我也遇到过了，但是访问 https://lobe.ai0x0.com/ 这个大佬部署的 在我的手机上是正常的
> 
> 我试过 safari 、微信浏览器 ，都是上述错误。

@mushan0x0 我用手机测试了，大佬部署的确没有问题，请大佬赐教！

**Comment by mushan0x0** [comment]
https://github.com/lobehub/lobe-chat/discussions/531#discussioncomment-7718087 @ohko @ipengyo 试一下这个配置呢

**Comment by ohko** [comment]
> [#531 (comment)](https://github.com/lobehub/lobe-chat/discussions/531#discussioncomment-7718087) @ohko @ipengyo 试一下这个配置呢

谢谢，试过了，不是配置的问题。不用nginx，直接访问docker导出的3210端口仍然出错。使用文章中提到的IP流式也不行，手机未使用代理，直接通过电信网络访问阿里云服务器上部署的docker：3210端口。
按道理说是浏览器兼容问题了，可是 @mushan0x0 部署的为什么就能正常访问呢？同样和ai0x0部署的是同一个版本（0.117.1）。请问你是用docker部署的还是自己编译的呢？

**Comment by mushan0x0** [comment]
@ohko 我是自己编译的，但是没加什么兼容性的处理

**Comment by mushan0x0** [comment]
@ohko 可以把你部署的地址发出来看看不，看看能不能帮你定位到问题

**Comment by ohko** [comment]
> @ohko 可以把你部署的地址发出来看看不，看看能不能帮你定位到问题

感谢大佬，这是我部署的地址：http://lobe.lyl.hk:3210  PC上可能不会出现这个问题，可能需要iPhone8才好复现问题。

**Comment by mushan0x0** [comment]
> > @ohko 可以把你部署的地址发出来看看不，看看能不能帮你定位到问题
> 
> 感谢大佬，这是我部署的地址：http://lobe.lyl.hk:3210 PC上可能不会出现这个问题，可能需要iPhone8才好复现问题。

确实没有复现出来，手机电脑都正常，可以再截一个这样的报错图吗，需要定位到这个报错的js文件上

<img width="811" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/2efa473d-bb54-4d42-8ca6-920f423cc235">

**Comment by ohko** [comment]
> > > @ohko 可以把你部署的地址发出来看看不，看看能不能帮你定位到问题
> > 
> > 
> > 感谢大佬，这是我部署的地址：http://lobe.lyl.hk:3210 PC上可能不会出现这个问题，可能需要iPhone8才好复现问题。
> 
> 确实没有复现出来，手机电脑都正常，可以再截一个这样的报错图吗，需要定位到这个报错的js文件上
> 
> <img alt="image" width="811" src="https://private-user-images.githubusercontent.com/29084441/293386969-2efa473d-bb54-4d42-8ca6-920f423cc235.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjQxNjMsIm5iZiI6MTcwMzg2Mzg2MywicGF0aCI6Ii8yOTA4NDQ0MS8yOTMzODY5NjktMmVmYTQ3M2QtYmI1NC00ZDQyLThjYTYtOTIwZjQyM2NjMjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE1MzEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZGM0ZjY4YjVjZWJjNmUxYzdkOTVjOGIyNTQzZTFkMmU0MThhNmFmZmE5MTQ4ZTMzMmZlZDdiYjFkOTUxNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._wi6DBrYD0MMOMxu8O7iJGNBWISeVZBpHr8XUBl_L28">

![WX20231229-233330@2x](https://github.com/lobehub/lobe-chat/assets/4863673/ff1f199b-551c-4ef6-bf20-1c976db55bfc)
![WX20231229-233340@2x](https://github.com/lobehub/lobe-chat/assets/4863673/76c0cf2c-dde1-47b6-9296-69b01565fbd4)

**Comment by mushan0x0** [comment]
根据这个
<img width="652" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/cd93b40f-cc49-432b-b94a-c02f286522ee">
找到了，是这个正则不支持导致的报错
<img width="486" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/ae2e325f-a3af-41ad-88cd-4c5c1b6601c5">

**Comment by ohko** [comment]
@mushan0x0 似乎定位到问题了，执行这段代码报错了：
RegExp("(?<=[!.;?])", "g")
报错：SyntaxError: Invalid regular expression: invalid group specifier name

完整代码是：3108行：String.fromCharCode(e.charCodeAt(0) - 65248)
                    }).replaceAll("　", " ").replaceAll("。", ".").replaceAll("，", ",").replaceAll("！", "!").replaceAll("？", "?").replaceAll("；", ";").replaceAll("：", ":").replaceAll("（", "(").replaceAll("）", ")").replaceAll("【", "[").replaceAll("】", "]").replaceAll("《", "<").replaceAll("》", ">").replaceAll("“", '"').replaceAll("”", '"').replaceAll("‘", "'").replaceAll("’", "'").replaceAll("\n", ". ").replaceAll(/\s+/g, " ")).split(RegExp("(?<=[!.;?])", "g"))

**Comment by mushan0x0** [comment]
https://github.com/lobehub/lobe-tts/blob/master/src/core/utils/splitTextIntoSegments.ts#L28 @arvinxx @canisminor1990 是这个代码导致的

**Comment by ohko** [comment]
nice，终于找到问题了，javascript兼容问题，从ECMAScript 2018开始，JavaScript已经开始支持后视断言（Lookbehind Assertions）。所以，如果环境支持ECMAScript 2018或者更新的版本，可以使用后视断言。所以ios16.3.1是不支持的，请大佬修正此代码。

```
const regex = /(?<=[!.;?])\s/g;
const str = 'Hello. How are you? I\'m fine, thanks.';
console.log(str.replace(regex, '\n'));
```

**Comment by ohko** [comment]
@arvinxx 这个问题能修复吗？
