### ISSUE TITLE
[Request] 对话记录更新后没有自动滚动到底部

### ISSUE THREAD

**Issue by guowc** [lobehub/lobe-chat#70]
### 🥰 需求描述 | Feature Description

这是一个比较基础的功能，当对话列表高度超过一屏时，继续发送信息得手动滚动到底部才能看到，建议参照任意一个聊天软件的交互做下优化

### 🧐 解决方案 | Proposed Solution

增加一个scrollToBottom之类的方法，在对话记录更新后调用

**Comment by arvinxx** [comment]
> 增加一个scrollToBottom之类的方法，在对话记录更新后调用

没你想的这么简单，用户滚动不在底部的时候，强行拉到底部体验是很差的。比较好的是当用户滚动到底部的时候才会自动往下滚动，当不在底部的时候会有一个一键直达底部的悬浮按钮。

这个功能在计划中的，会和「停止」生成的功能一起实现

**Comment by arvinxx** [comment]
@guowc 来 try try？ 文档中增加一键部署了
