### ISSUE TITLE
[Bug] 网页操作起来有点卡顿  UI很好看就是动画不流畅 卡卡的

### ISSUE THREAD

**Issue by yh4922** [lobehub/lobe-chat#701]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

网页操作起来有点卡顿  UI很好看就是动画不流畅 卡卡的

**Comment by arvinxx** [comment]
有计划优化

**Comment by Feliks151450** [comment]
> 有计划优化

lobechat 哪里都好，就是真的卡，一大堆按钮点了都要半秒以上才能有反应，很多功能其实用不上，在部署的时候多弄几个环境变量，方便关掉一堆功能，软件逻辑都会清楚很多

**Comment by arvinxx** [comment]
> 一大堆按钮点了都要半秒以上才能有反应

哪些按钮点了需要半秒以上？

**Comment by Asuka109** [comment]
最好是能录屏演示下

**Comment by hqw567** [comment]
卡是真的，每个页面点击都有延迟，AI输出也明显慢了很多

**Comment by arvinxx** [comment]
> 设置界面，对话界面，机器人商店来回切换的时候很明显，设置界面不同部分来回切换也很明显的延迟

@Feliks151450 针对这一部分做了下预取优化，再来体验下试试。

**Comment by Feliks151450** [comment]
> > 设置界面，对话界面，机器人商店来回切换的时候很明显，设置界面不同部分来回切换也很明显的延迟
> 
> @Feliks151450 针对这一部分做了下预取优化 ( #749 )，再体验下。

感谢，试了一下，虽然还有点延迟，但是确实快了很多，这个体验目前还不错

**Comment by arvinxx** [comment]
OK 我们会继续优化的

**Comment by kangfenmao** [comment]
还是卡，建议直接把所有资源启动的时候下载下来，现在网速那么快，总比点击的时候卡一下要好，点击的时候卡一下多么影响心态呀。启动的时候卡，顶多是觉得自己网不行。

**Comment by arvinxx** [comment]
> 还是卡，建议直接把所有资源启动的时候下载下来，现在网速那么快，总比点击的时候卡一下要好，点击的时候卡一下多么影响心态呀。启动的时候卡，顶多是觉得自己网不行。

点哪里还卡？应该几乎都做了下载了

**Comment by kangfenmao** [comment]
> > 还是卡，建议直接把所有资源启动的时候下载下来，现在网速那么快，总比点击的时候卡一下要好，点击的时候卡一下多么影响心态呀。启动的时候卡，顶多是觉得自己网不行。
> 
> 点哪里还卡？应该几乎都做了下载了

是的，比之前快了很多。因为一些资源已经预加载过了。

可能是因为用 next 的原因，举例说明。点击右上角设置的时候，大概会有 100ms 延迟，虽然不影响使用，但是能主观感受到这个微弱的延迟。

后续有没有客户端的计划，资源在本地一切都能做到非常快。

**Comment by yh4922** [comment]
现在前端页面优化的怎么样了  之前好卡  临时换成了NextChat

**Comment by mushan0x0** [comment]
https://lobe.ai0x0.com/ 部署在国内服务器就不卡了

**Comment by yh4922** [comment]
我是私有化部署的

**Comment by arvinxx** [comment]
@kangfenmao 你们真的是苛刻啊 😅 之前优化的时候唯独右上角那个 settings 我没做预取，就是觉得普通用户应该不太会点那个地方，稍微等一会也还好 🤡

<img width="621" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/be930cef-39e0-47b7-b73f-c232cd0e1442">

这个路由我也做下预取吧

**Comment by mushan0x0** [comment]
> @kangfenmao 你们真的是苛刻啊 😅 之前优化的时候唯独右上角那个 settings 我没做预取，就是觉得普通用户应该不太会点那个地方，稍微等一会也还好 🤡
> 
> <img alt="image" width="621" src="https://private-user-images.githubusercontent.com/28616219/295400412-be930cef-39e0-47b7-b73f-c232cd0e1442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTMzNDMsIm5iZiI6MTcwNDg1MzA0MywicGF0aCI6Ii8yODYxNjIxOS8yOTU0MDA0MTItYmU5MzBjZWYtMzllMC00N2I3LWI3M2YtYzIzMmNkMGUxNDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyMTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNGEyNGQxMDkyNGU2MDUxNjlmYjk2N2NlY2Y4N2JlOGYyOGQ4ZWUyYWViNWE3MmZlNjIyYmM2MDM0OGJhMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KCiiZvd_2bCKrUnmQaFsydLDLlWzdmm6NQMy03TJHrk">
> 这个路由我也做下预取吧

偷懒又被发现了😂

**Comment by kangfenmao** [comment]
> @kangfenmao 你们真的是苛刻啊 😅 之前优化的时候唯独右上角那个 settings 我没做预取，就是觉得普通用户应该不太会点那个地方，稍微等一会也还好 🤡
> 
> <img alt="image" width="621" src="https://private-user-images.githubusercontent.com/28616219/295400412-be930cef-39e0-47b7-b73f-c232cd0e1442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTMzNTcsIm5iZiI6MTcwNDg1MzA1NywicGF0aCI6Ii8yODYxNjIxOS8yOTU0MDA0MTItYmU5MzBjZWYtMzllMC00N2I3LWI3M2YtYzIzMmNkMGUxNDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyMTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjODMzZWIyNmE4NzkzNGExOGQ4ZDg3MzQxMjMzYzE4OGRlNjg3MGQzNWIyYWJmMDBlOGU0ZGI1ODBjNzYwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MRCyNoPI081MpRD7rygGsHtUjPx2pT-px92XVVDL9gk">
> 这个路由我也做下预取吧

当然，用户群体广了，自然会有各种各样开发者想象不到的应用场景。我通常会在这里对会话做一些设置，所以会经常点击设置和返回。

**Comment by gngshn** [comment]
流式传输是不是有点问题呀. 问了问题要等好久才开始有回应, 开始回应的时候, 刷的一下全部都出来了.

**Comment by arvinxx** [comment]
> 流式传输是不是有点问题呀. 问了问题要等好久才开始有回应, 开始有回应的时候, 刷的一下全部都出来了.

应该是你的配置问题，看看 https://github.com/lobehub/lobe-chat/discussions/994

**Comment by gngshn** [comment]
> > 流式传输是不是有点问题呀. 问了问题要等好久才开始有回应, 开始有回应的时候, 刷的一下全部都出来了.
> 
> 应该是你的配置问题，看看 #994

我刚用IP直接访问试了下, 似乎没有问题. 感觉应该是nginx反代的问题. 不知道有没有什么参考. 之前nextchat没有额外的反代配置是没出现这个现象的.
谢谢

**Comment by arvinxx** [comment]
@guangzhengli  我刚发的链接有问题，改了，你再看下

**Comment by xianjuntang** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/31877679/65261d9a-ca61-4ed4-8c8c-c414160be502)
你们有遇到过这个吗window本地开发，启动卡死，cpu直接干到75多

**Comment by mwnu** [comment]
的确至今UI响应延迟依然非常高，由其是在手机上操作，而且点按控件比较小，非常不跟手。

**Comment by arvinxx** [comment]
> 的确至今UI响应延迟依然非常高，由其是在手机上操作，而且点按控件比较小，非常不跟手。

有问题建议新开 issue
