### ISSUE TITLE
[Question] windows的node18环境下运行报错

### ISSUE THREAD

**Issue by LPtrichor** [lobehub/lobe-chat#703]
### 🧐 问题描述 | Proposed Solution

想问一下大佬们，本地调试报错，这个怎么解决呀

从启动页进来之后点击刷新就会报错，不刷新可以正常使用
![image](https://github.com/lobehub/lobe-chat/assets/78304742/7db7288c-1f8b-422e-a300-dc5119a16cae)

**Comment by arvinxx** [comment]
@canisminor1990

**Comment by canisminor1990** [comment]
@LPtrichor 可能是 STT 的初始化配置偶尔会没有注入好，我近期看一下，目前解决方法你可以进入全局设置，把 STT 相关的设置挨个点一遍，更新下配置应该可以解决这个问题

**Comment by LPtrichor** [comment]
好的，谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月19日(周二) 晚上10:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lobehub/lobe-chat] [Question] windows的node18环境下运行报错 (Issue #703)




 
@LPtrichor 可能是 STT 的初始化配置偶尔会没有注入好，我近期看一下，目前解决方法你可以进入全局设置，把 STT 相关的设置挨个点一遍，更新下配置应该可以解决这个问题
