### ISSUE TITLE
[Bug] Failed to deploy on Zeabur

### ISSUE THREAD

**Issue by LeslieLeung** [lobehub/lobe-chat#710]
### 💻 系统环境 | Operating System

Other Linux

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

When deploying, it failed with last message:
```
error: failed to solve: process "/bin/sh -c pnpm run build:docker # run build standalone for docker version" did not complete successfully: exit code: 1
```

### 📷 复现步骤 | Recurrence Steps

Click `Deploy to Zeabur` button on README.

**Comment by arvinxx** [comment]
@MichaelYuhe

**Comment by MichaelYuhe** [comment]
Investigating the issue now

**Comment by MichaelYuhe** [comment]
@LeslieLeung Can you try deploy from template again? It should be fixed now

**Comment by LeslieLeung** [comment]
The deployment works now after I manually forked the repo and create a project and add a new service on Zeabur.

Is it the deploy button the problem? It is not forking a new repo, instead it just cloned one(not indicator said `Forked from xxx`) and this repo cannot be synced with the origin in the future(at least not on github webpage).

**Comment by MichaelYuhe** [comment]
> The deployment works now after I manually forked the repo and create a project and add a new service on Zeabur.
> 
> Is it the deploy button the problem? It is not forking a new repo, instead it just cloned one(not indicator said `Forked from xxx`) and this repo cannot be synced with the origin in the future(at least not on github webpage).

I've synced and enable the sync workflow now, the button is working now. 
Why we don't fork instead of using clone is that you can deploy a repo as private (which fork can't not do)
We also cloned the workflow part so you can enable it in the actions to sync upstream repo

**Comment by LeslieLeung** [comment]
I tried the button and can confirm it is working. Thank you for your time and insight on this matter.

However the cloned repo seem to have so many actions that won't be needed in private, and they are failing. Is it because some of the secrets is missing? (But I think I can just go ahead and delete them...)

**Comment by MichaelYuhe** [comment]
> I tried the button and can confirm it is working. Thank you for your time and insight on this matter.
> 
> However the cloned repo seem to have so many actions that won't be needed in private, and they are failing. Is it because some of the secrets is missing? (But I think I can just go ahead and delete them...)

Sorry for the trouble!

The actions are failing because of missing secrets and it's annoying :D We will try to find out a way to improve this!

**Comment by MichaelYuhe** [comment]
@LeslieLeung I think this issue can be closed? cc @arvinxx

**Comment by LeslieLeung** [comment]
Yes, closing it now.
