### ISSUE TITLE
[Bug] 回复跟随的问题

### ISSUE THREAD

**Issue by a616824431** [lobehub/lobe-chat#714]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

gpt在回复消息的时候,回复到让我问的问题内容快要消失时,页面不会跟随着gpt的回答继续向下而是卡住 需要手动滑鼠标才能看到下面的内容.  

### 🚦 期望结果 | Expected Behavior

希望能一直跟随gpt的回答.

**Comment by arvinxx** [comment]
有待优化。目前监测区域有点小，是只有部分时候会自动往下
