### ISSUE TITLE
[Question] deploy on cloudflare

### ISSUE THREAD

**Issue by Feliks151450** [lobehub/lobe-chat#715]
### 🧐 问题描述 | Proposed Solution

It is possible to depoly on cloudflare pares?

**Comment by suwubee** [comment]
确实不支持，改了半天。到最后剩下
export const runtime = 'edge';
提示太多文件，改不下去了

https://github.com/suwubee/lobe-chat/tree/main

**Comment by arvinxx** [comment]
@suwubee 能否分享一下兼容部署需要做哪些改造？

**Comment by suwubee** [comment]
> @suwubee 能否分享一下兼容 cloudflare 部署需要做哪些改造？
> 
> 我对 cloudflare 不太熟悉

我fork里主要是改了package.json和vercel.json，
变量是设置nodejs和yarn的版本。
但最后还是一堆edge的问题，现在的代码感觉就是为了vercel写的，比如那个vercel分析，默认开启，不太清楚有多少人需要，而且不通用。

**Comment by suwubee** [comment]
`
Build command:
npx @cloudflare/next-on-pages@1.5.0

Variable name | Value
-- | --
NEXT_PUBLIC_ANALYTICS_VERCEL | 0
NEXT_PUBLIC_VERCEL_DEBUG | 0
NODE_VERSION | 20.10.0
YARN_VERSION | 1.22.19
`
Settings - Functions - Compatibility flags
Compatibility flags:
nodejs_compat

上述配置是参考了next web的

**Comment by ckt1031** [comment]
> @suwubee 能否分享一下兼容 cloudflare 部署需要做哪些改造？
> 
> 我对 cloudflare 不太熟悉

所有頁面必須以edge模式運行,目前遇到的react i18n 文件的問題

**Comment by a562314** [comment]
> @suwubee 能否分享一下兼容 cloudflare 部署需要做哪些改造？
> 
> 我对 cloudflare 不太熟悉

I'm getting a lot of errors when deploying on Cloudflare
When to support lobechat deployment on Cloudflare pages？

**Comment by arvinxx** [comment]
@a562314 currently there is no plan about it.

**Comment by fjqz177** [comment]
When can I deploy lobechat on cloudflare pages? Because the pages deployed on cloudflare pages are faster to access.
请问什么时候能在cloudflare pages上部署lobechat啊？因为cloudflare pages部署的页面访问比较快（主要还是因为vercel被墙了）

**Comment by sxjeru** [comment]
@fjqz177 Cloudflare 免费计划对构建后的单文件大小限制在 25MB，lobechat 太大了。

如果你开通了付费，可以试试去部署，部署前记得删去根目录的 .nvmrc 文件。
