### ISSUE TITLE
授粉画图图片显示不出来

### ISSUE THREAD

**Issue by wangllxxxx** [lobehub/lobe-chat#719]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

通过授粉生成的图片显示不出来
<img width="1085" alt="3333" src="https://github.com/lobehub/lobe-chat/assets/122505992/0abcc139-5dba-4d04-830f-e7e48dde87f0">

**Comment by arvinxx** [comment]
@mushan0x0 帮忙看看

**Comment by mushan0x0** [comment]
这个是他们服务器有时候负载比较大显示不出来，毕竟是免费的

**Comment by wangllxxxx** [comment]
我好想没有一张显示出来。。。懵

**Comment by kelekekou8** [comment]
确实显示不出来，别外只有GPT4的API才能使用GPT4功能对吗？
