### ISSUE TITLE
[Request] 支持上传图片

### ISSUE THREAD

**Issue by shanshu1015** [lobehub/lobe-chat#720]
### 🥰 需求描述 | Feature Description

支持上传图片

### 🧐 解决方案 | Proposed Solution

根据模型 输入框自适应增减图片上传按钮

**Comment by canisminor1990** [comment]
可以具体解释下么，目前在支持图片识别的 gpt-4-vision 中是可以上传图片的，其他不支持的模型会将上传入口隐藏

**Comment by shanshu1015** [comment]
刚确认了模型，是我的疏忽，确实像你说的在支持图片识别的 gpt-4-vision 中是可以上传图片的
________________________________
发件人: CanisMinor ***@***.***>
发送时间: 2023年12月19日 22:18
收件人: lobehub/lobe-chat ***@***.***>
抄送: shanshu1015 ***@***.***>; Mention ***@***.***>
主题: Re: [lobehub/lobe-chat] [Request] 支持上传图片 (Issue #720)


可以具体解释下么，目前在支持图片识别的 gpt-4-vision 中是可以上传图片的，其他不支持的模型会将上传入口隐藏

―
