### ISSUE TITLE
[Bug] 环境变量agents index url无效

### ISSUE THREAD

**Issue by cyx1322** [lobehub/lobe-chat#738]
### 💻 系统环境 | Operating System

Ubuntu

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

docker部署时使用了  -e AGENTS_INDEX_URL="https://lobe-chat-agents-lzl3-cyx1322.vercel.app" \参数
自定义agents url，但界面仍显示默认的agents

**Comment by cyx1322** [comment]
发现用docker部署，除了access code、proxy url、openai api key这几个基本环境变量之外，其他的环境变量都是无效的，请尽快修复，谢谢！

**Comment by arvinxx** [comment]
和 `CUSTOM_MODEL`  （#684 ） 看起来是同一个问题

**Comment by cyx1322** [comment]
感觉是这样，今天我试了一下，这两个变量都是在vercel部署，或是本地bun build就有效，而用docker部署就无效了。可以参考一下

**Comment by arvinxx** [comment]
嗯 本周会一并解决掉
