### ISSUE TITLE
[Request] 支持隐藏配置代理地址

### ISSUE THREAD

**Issue by 1355873789** [lobehub/lobe-chat#740]
### 🥰 需求描述 | Feature Description

需求场景：自己搭建给家人同事或者朋友使用，但是很难保证他们会不会分享给别人使用或者是泄露之类的，这样的话又得从头折腾重新配置，希望在key或者密码上自定义选项能够多一点

### 🧐 解决方案 | Proposed Solution

需求1：希望有关闭使用自定义key的选项，然后可以支持多个key对应不同密码，用户端输入哪个密码对应使用哪个key，然后自己用自己的，哪怕被泄露了把对应key删除掉就可以了，不影响自己使用。

需求2：或者是希望可以有个把自定义key的代理地址固定的选项，锁死成自己预设的地址，只允许输入key，以免泄露出去给别人用别的自定义key和地址，要不纯纯自己搭建给别人做公益。个人觉得第二个需求比较好实现并且比较好规避这个问题。

**Comment by cachexy123** [comment]
作者，你好，我看到问题已经解决，请问一下该如何隐藏，怎么设置呢？
