### ISSUE TITLE
群晖部署，不能正常连接

### ISSUE THREAD

**Issue by guomengran** [lobehub/lobe-chat#741]
### 🧐 问题描述 | Proposed Solution

群晖部署，可以正常打开界面，聊天对话不能提示错误，提示词如下：

### 📝 补充信息 | Additional Information

{
  "endpoint": "https://openai.****cn/",
  "error": {
    "type": "invalid_request_error",
    "code": "unknown_url",
    "message": "Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.",
    "param": null
  }
}

**Comment by canisminor1990** [comment]
proxy 是不是没加上 v1

**Comment by guomengran** [comment]
<img width="568" alt="image" src="https://github.com/lobehub/lobe-chat/assets/94100624/fc87e149-b19a-4e9f-a91b-63ef2453358d">

**Comment by zrr1999** [comment]
> <img alt="image" width="568" src="https://private-user-images.githubusercontent.com/94100624/292057282-fc87e149-b19a-4e9f-a91b-63ef2453358d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjc1OTEsIm5iZiI6MTcwMzEyNzI5MSwicGF0aCI6Ii85NDEwMDYyNC8yOTIwNTcyODItZmM4N2UxNDktYjE5YS00ZTlmLWE5MWItNjNlZjI0NTMzNThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyNTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNzUyYWZmNTM0NDBlNDM2OGViNDc0ZTIxMjQyYWUxOWFmNTU4Y2E2Y2VlOWE2NTlkMDkyMzEyNzY1Yzc3OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KVDf3YegISI81U63TTYAZ2LrYsKwmCT3RcMo-TSr9HQ">

是的
