### ISSUE TITLE
[Request] 使用Azure API KEY之后，前端是否可以支持自定义开启某些模型

### ISSUE THREAD

**Issue by GuGuGee** [lobehub/lobe-chat#743]
### 🥰 需求描述 | Feature Description

使用Azure API KEY之后，前端是否可以支持自定义开启某些模型

![image-20231221114257565](https://img.laoda.de/i/2023/12/21/iw9tg8-0.webp)

目前默认是和OpenAI API搭建一样，显示所有模型的

### 🧐 解决方案 | Proposed Solution

我目前用azure api 部署了前端，

给公司的小伙伴使用的时候，会发现其实`gpt-4-1106-preview`和`gpt-4-vision-preview`是用不了的，

![image-20231221114434613](https://img.laoda.de/i/2023/12/21/ixbqek-0.webp)

希望前端或者后端可以有一个开关，可以把诸如这俩实际上不可用的模型暂时关闭，这样不会给一些单纯的使用者造成困扰。

谢谢开发者！

**Comment by opoet** [comment]
有这个设置项，但是如果使用 Docker 部署，目前此变量不会生效，见 #509 
https://github.com/lobehub/lobe-chat/wiki/Environment-Variable.zh-CN#next_public_custom_models

**Comment by jonnyhou** [comment]
> 有这个设置项，但是如果使用 Docker 部署，目前此变量不会生效，见 #509 https://github.com/lobehub/lobe-chat/wiki/Environment-Variable.zh-CN#next_public_custom_models

我也遇到这个问题，使用-all,+claude-2，完全无法生效，模型出来还是原始内置的内容。但是在客户端配置的时候是可以生效的，就是太麻烦，每个新访问的客户端都需要配置

**Comment by arvinxx** [comment]
@jonnyhou  尝试使用 `CUSTOM_MODELS` 变量
