### ISSUE TITLE
[Question] 使用OpenAPI请求插件出错

### ISSUE THREAD

**Issue by deku0818** [lobehub/lobe-chat#745]
### 🧐 问题描述 | Proposed Solution

我正在测试插件走通的流程，但是遇到了非常多的问题
  
message: '\'weatherinquiry____POST /api/weather\' does not match \'^[a-zA-Z0-9_-]{1,64}$\' - \'functions.0.name\' (request id: 202312211638248162983471NMwLpK9)',
  type: 'invalid_request_error',
  param: '',
  code: null
}
![image](https://github.com/lobehub/lobe-chat/assets/84755119/ef4876db-4bfe-4918-a16e-7e4e040076dc)

**Comment by arvinxx** [comment]
```
message: ''weatherinquiry____POST /api/weather' does not match '^[a-zA-Z0-9_-]{1,64}$'
```

这个是 openai  fc 请求的规范，你的 openapi 方法缺少了 `operationId`，导致请求报错了

**Comment by deku0818** [comment]
感谢！已解决！
