### ISSUE TITLE
[Bug] 搜索插件在gpt-4-1106-preview模型下无法正常调用

### ISSUE THREAD

**Issue by TonyBlur** [lobehub/lobe-chat#746]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/101348912/49381a11-2283-4aff-a8c8-b1d04a4b918c)
搜索插件在gpt-4-1106-preview模型下无法正常调用，而在其他模型下可以正常使用

### 📷 复现步骤 | Recurrence Steps

选中gpt-4-1106-preview模型，安装并开启搜索引擎插件，输入并发送“搜索...”的prompt，接下来会一直显示插件检测中，直至超时

### 📝 补充信息 | Additional Information

浏览器console报错如下：

Uncaught (in promise) SyntaxError: Unterminated string in JSON at position 1874 (line 1 column 1875)
    at JSON.parse (<anonymous>)
    at triggerFunctionCall (1349-651f6e713c4a6752.js?__WB_REVISION__=TrLzT_UKEqu1tAazyXIru:1:20338)
    at coreProcessMessage (1349-651f6e713c4a6752.js?__WB_REVISION__=TrLzT_UKEqu1tAazyXIru:1:18081)
    at async resendMessage (1349-651f6e713c4a6752.js?__WB_REVISION__=TrLzT_UKEqu1tAazyXIru:1:16350)

**Comment by arvinxx** [comment]
感觉像是4 在 fc 上的鲁棒性不太好。我回头试试看优化插件的提示词看看有没有用。你能把你的输入复制一份给我吗？我先复现试试

**Comment by TonyBlur** [comment]
> 感觉像是4 在 fc 上的鲁棒性不太好。我回头试试看优化插件的提示词看看有没有用。你能把你的输入复制一份给我吗？我先复现试试

好的，感谢
prompt输入只有`搜索初中信息技术人教版七年级下册第一单元第2课 学会基本绘图工具 的教材和教案`这一句

**Comment by arvinxx** [comment]
试下最新的 gpt-4-turbo 应该没有这个问题了：

<img width="1050" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/458a32ac-8815-4c2b-987e-147a78149ff8">
