### ISSUE TITLE
无法链接 openai 并且 timeout 

### ISSUE THREAD

**Issue by xushijie** [lobehub/lobe-chat#747]
### 🧐 问题描述 | Proposed Solution

使用这个命令启动的：
```
(base) ➜  sample docker run -d -p 3210:3210 \
  -e OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXXXXX \
  -e  HTTP_PROXY=http://127.0.0.1:1082/v1  -e HTTPS_PROXY=http://127.0.0.1:1082/v1 lobehub/lobe-chat

```
然后页面能够显示，但是输入一个聊天问题后，docker container显示出来就是：
![image](https://github.com/lobehub/lobe-chat/assets/1155134/6d8d94e0-8b7f-4d35-be1b-6d2024b7303f)

我localhost 开了一个  v2ray的proxy, 这个proxy 本身一直在用，是正常的。 
那这个在container 里面使用 host 上的 proxy 链接问题如何解决呢？

**Comment by MapleMoonSky** [comment]
这里填的不是梯子的代理，而是第三方代理网站，例如：https://api.chatanywhere.cn/v1
[文档-环境变量](https://github.com/lobehub/lobe-chat/blob/main/README.zh-CN.md#环境变量)里有
第三方代理配合他们自己的API Key使用可以免梯访问，不能用OpenAI官方的API Key

**Comment by GitHUB-ZYD** [comment]
希望可以加上请求api.openai.com的代理，不然使用中间人来实现有点麻烦

**Comment by arvinxx** [comment]
> 希望可以加上请求api.openai.com的代理，不然使用中间人来实现有点麻烦

https://github.com/lobehub/lobe-chat/discussions/466

**Comment by xtheing** [comment]
> > 希望可以加上请求api.openai.com的代理，不然使用中间人来实现有点麻烦
> 
> 不考虑增加请求代理功能。 透明代理类问题见 #466

为什么不考虑呢？可以给一个理由吗？第三方的透明代理会暴露自己的openapi key，应该是不安全的做法。

**Comment by taohongxiu** [comment]
真垃圾，代理都不支持
