### ISSUE TITLE
[Request] 建议增加自定义发送快捷键

### ISSUE THREAD

**Issue by maiyuanrdt** [lobehub/lobe-chat#748]
### 🥰 需求描述 | Feature Description

不确定是不是我没找到这个功能，当向GPT提交一份代码信息时，需要在其中换行增加一些其他代码，想必程序员在各种IDE里打代码换行都不是按Shift+Enter😁
所以就容易导致代码没打完，啪一个换行，出去了。。。。

### 🧐 解决方案 | Proposed Solution

能够自定义发送按钮的快捷键，或者默认发送为Ctrl+Enter，请把Enter留给换行~

**Comment by arvinxx** [comment]
@maiyuanrdt 以已在 #983 实现
