### ISSUE TITLE
[Question] 求助：docker build，编译失败

### ISSUE THREAD

**Issue by risn** [lobehub/lobe-chat#751]
### 🧐 问题描述 | Proposed Solution

执行docker build，failed to compile了。信息：#14 235.0 ./node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.6/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js:3:13
#14 235.0 Module not found: Can't resolve 'http'
#14 235.0 Did you mean './http'? 完整的日志在附件。
[build.log](https://github.com/lobehub/lobe-chat/files/13748294/build.log)

**Comment by arvinxx** [comment]
@risn 版本太低了，用最新版本应该就可以
