### ISSUE TITLE
[Question] 使用Nginx做代理自定义域名后，无法实现流式回答

### ISSUE THREAD

**Issue by syusama** [lobehub/lobe-chat#754]
### 🧐 问题描述 | Proposed Solution

部署在服务器上后，如果使用ip:port访问，可以正常流式回答（打字机效果），但是配置NGINX自定义域名之后，就没有打字机效果了，会等待很长一段时间然后返回回答

### 📝 补充信息 | Additional Information

NGINX配置如下：
server {
		server_name baize2.xxxxx.com;
		location / {
			client_max_body_size 64m;
			proxy_http_version 1.1;
			proxy_pass http://localhost:3210;
			proxy_set_header Host $host;
			proxy_cache_bypass $http_upgrade;
			proxy_set_header Accept-Encoding gzip;
			proxy_read_timeout 300s;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header Host $host:$server_port;
			proxy_set_header X-NginX-Proxy true;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_max_temp_file_size 0;
			proxy_redirect off;
			proxy_set_header X-Real-PORT $remote_port;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		}
	
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/baize2.scdipt.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/baize2.scdipt.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

	server {
    if ($host = baize2.xxxxxx.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

		listen 80;
		server_name baize2.scdipt.com;
    return 404; # managed by Certbot

}}

**Comment by arvinxx** [comment]
试试 https://github.com/lobehub/lobe-chat/discussions/531

**Comment by syusama** [comment]
> 试试 #531

感谢大佬，可以了！！！！
