### ISSUE TITLE
[Bug] 页面加载缓慢

### ISSUE THREAD

**Issue by shenmadouyaowen** [lobehub/lobe-chat#756]
### 💻 系统环境 | Operating System

Ubuntu

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

bun dev 运行后
有没有办法降低这个加载的时间，每次点一个功能等好久
![image](https://github.com/lobehub/lobe-chat/assets/12426724/9a061ae4-ab24-40f7-8c2d-475f2f621abe)

### 🚦 期望结果 | Expected Behavior

快速打开网站

### 📷 复现步骤 | Recurrence Steps

bun dev
打开网页慢

**Comment by arvinxx** [comment]
dev当然慢，每个nextjs 的每个页面是按需编译的。你激活才会开始编译

**Comment by shenmadouyaowen** [comment]
好的，谢谢
