### ISSUE TITLE
[Bug] azure OpenAI deployment name is not the model name

### ISSUE THREAD

**Issue by lixiaoqin0218** [lobehub/lobe-chat#757]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

<img width="1048" alt="image" src="https://github.com/lobehub/lobe-chat/assets/31536111/ae7e3eb8-ec2d-4cbd-9101-96276b801a97">

the red box is deployment name not model name ,maybe you could set it in .env file；

refer:
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

curl https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/completions?api-version=2023-05-15\
  -H "Content-Type: application/json" \
  -H "api-key: YOUR_API_KEY" \
  -d "{
  \"prompt\": \"Once upon a time\",
  \"max_tokens\": 5
}"

**Comment by arvinxx** [comment]
refs: https://github.com/lobehub/lobe-chat/discussions/178

**Comment by arvinxx** [comment]
需要对 azure 进行重构以支持上述特性： https://github.com/lobehub/lobe-chat/discussions/1219
