### ISSUE TITLE
[Bug] Error in ordered list formatting for numbers 10 and above.

### ISSUE THREAD

**Issue by zhuozhiyongde** [lobehub/lobe-chat#760]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/36695271/1dc12366-f8f8-40d0-b37d-91658ade53e5)

如图所示，大于等于 10 的序号会被截断。

**Comment by arvinxx** [comment]
@canisminor1990

**Comment by canisminor1990** [comment]
如何复现？你原本的 markdown 是什么

![image](https://github.com/lobehub/lobe-chat/assets/17870709/d9fb2d6f-643a-4fb7-873a-2f1ea8b9ba5a)

**Comment by zhuozhiyongde** [comment]
> 如何复现？你原本的 markdown 是什么
> 
> ![image](https://private-user-images.githubusercontent.com/17870709/292761172-d9fb2d6f-643a-4fb7-873a-2f1ea8b9ba5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MTI4NzIsIm5iZiI6MTcwMzUxMjU3MiwicGF0aCI6Ii8xNzg3MDcwOS8yOTI3NjExNzItZDlmYjJkNmYtNjQzYS00ZmI3LTg3M2EtMmYxZWE4YjliYTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDEzNTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZWJhNzFlYTNhYmZiMWJkYzVmYmEyYTlmOTA1OWFlM2ZlYWYzOWM2ZWU3NDVhMGE0MGM4YTMyOTk0ZDNhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QHWthnpsI7BVBdWhDwgJDSnKFn2hQzJrsnnqYGT_jw0)

```md
1. Natural Language Processing (NLP)
2. Machine Learning (ML)
3. Artificial Intelligence (AI)
4. Neural Networks
5. Deep Learning
6. Language Models
7. Pretrained Models
8. Transformers
9. Generative Pretraining
10. Fine-tuning
11. Text Generation
```

可能和浏览器有关？我是Safari下的pwa

**Comment by zhuozhiyongde** [comment]
我确定了，这个问题只在 Safari 上复现。

**Comment by canisminor1990** [comment]
修了下样式，再试试？

**Comment by zhuozhiyongde** [comment]
列表问题解决了，但是我发现了新的md解析问题：

![Cleanshot-2023-12-27-at-06 39 50@2x](https://github.com/lobehub/lobe-chat/assets/36695271/bef020f1-d3ce-400b-870c-12fbb1da0e54)

在列表项目中，若最开始即为加粗，且加粗内容最后一个字符为中文字符 `（` 或者 `：` 都会导致解析出错。

@canisminor1990

**Comment by arvinxx** [comment]
新问题开新 issue吧
