### ISSUE TITLE
[Bug] 开启单次回复限制无法关闭

### ISSUE THREAD

**Issue by wanghhao1** [lobehub/lobe-chat#762]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

开启单次回复限制按钮无论是开启还是关闭，都处于开启状态

**Comment by arvinxx** [comment]
请给个复现

**Comment by wanghhao1** [comment]
https://github.com/lobehub/lobe-chat/assets/123242842/0a86a065-adfd-4d74-a4bc-f2c64fc30eb2

你好，大概就是视频里这样子
