### ISSUE TITLE
[Request] 支持gpt-4-all

### ISSUE THREAD

**Issue by Feliks151450** [lobehub/lobe-chat#764]
### 🥰 需求描述 | Feature Description

现在一些中转站已经支持gpt-4-all了，它可以分析各种文件。而现在lobe最多只能上传图片，希望能支持文件上传

### 🧐 解决方案 | Proposed Solution

对于gpt-4-all模型，上传图片按钮变更为上传文件按钮，同时支持粘贴文件，从外部拖拽文件等

**Comment by arvinxx** [comment]
gpt-4-all 是哪个模型？，给个链接

**Comment by Feliks151450** [comment]
> gpt-4-all 是哪个模型？给个链接

好像是逆向网页版的gpt4 all tool，倒也给不出个链接，可以找找支持的中转站，比如这个 https://api1.zhtec.xyz/ 。用支持的apikey在lobe里面直接添加一个gpt-4-all就可以用，我自己修改了一下lobe的代码，把gpt-4-all加到图像模型里面，确实可以像vision-preview一样直接识别图像。

**Comment by arvinxx** [comment]
那使用 [`CUSTOM_MODELS `](https://github.com/lobehub/lobe-chat/wiki/Environment-Variable.zh-CN#custom_models) 即可实现

**Comment by Feliks151450** [comment]
> 那使用 [`CUSTOM_MODELS `](https://github.com/lobehub/lobe-chat/wiki/Environment-Variable.zh-CN#custom_models) 即可实现

用这个解决不了问题，图片和文件都不能上传

**Comment by arvinxx** [comment]
文件上传不太可能为 gpt-4-all 专门做的，可能要等后续的知识库功能吧。

图片上传的话你倒是可以先手动改下代码给 `gpt-4-all` 支持上。
