### ISSUE TITLE
[Bug] 搜索插件只能被3.5模型调用，无法被4.0模型调用

### ISSUE THREAD

**Issue by Yari55** [lobehub/lobe-chat#767]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%241%20Funded-%2300A156.svg" />](https://oss.issuehunt.io/r/lobehub/lobe-chat/issues/767)

### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

[Bug] 搜索插件只能被3.5模型调用，无法被4.0模型调用，以下是想通的指令被4.0和3.5模型调用结果
![image](https://github.com/lobehub/lobe-chat/assets/102930715/bdc53495-911f-4d8f-b536-62d4b219bc76)
![image](https://github.com/lobehub/lobe-chat/assets/102930715/cf73eeee-bdbe-4b87-9de4-2efcae9a98bd)
相同的问题，3.5模型可以调用搜索引擎插件，而4.0的模型无法调用，

### 🚦 期望结果 | Expected Behavior

希望搜索引擎插件可以同时被3.5模型和4.0模型调用

### 📷 复现步骤 | Recurrence Steps

None

### 📝 补充信息 | Additional Information

None

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $1.00)

- [<img src='https://avatars.githubusercontent.com/u/39287499?v=4' alt='sen-capoo' width=24 height=24> sen-capoo](https://oss.issuehunt.io/u/sen-capoo) ($1.00)

### Tips

- Checkout the [Issuehunt explorer](https://oss.issuehunt.io/r/lobehub/lobe-chat/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://oss.issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by ravenk1n9** [comment]
dalle插件也只能被3.5调用

**Comment by arvinxx** [comment]
4-vision 不支持插件

**Comment by arvinxx** [comment]
可能是 #592 相关

**Comment by TonyBlur** [comment]
same issue as mine

**Comment by kokojacket** [comment]
+1

**Comment by arvinxx** [comment]
@kokojacket @Yari55 现在还存在这个问题么？

**Comment by kokojacket** [comment]
@arvinxx 是的，选择其他模型后，插件不生效了

**Comment by arvinxx** [comment]
@kokojacket @Yari55 能告诉我你们使用的是哪一家的api 提供商么

**Comment by kokojacket** [comment]
@arvinxx 我用这个https://github.com/chatanywhere/GPT_API_free

**Comment by arvinxx** [comment]
@kokojacket @Yari55 现在还存在这个问题不？
