### ISSUE TITLE
[Question] 对话很慢，非常慢，比我本地部署的chatglm还慢

### ISSUE THREAD

**Issue by taurusduan** [lobehub/lobe-chat#772]
### 🧐 问题描述 | Proposed Solution

不知道为什么对话速度非常慢，同一个代理和key，在其他平台速度差不多，但是在lobechat上一个提问差不多要一分钟左右，不知道大家有没有遇到这个问题。

### 📝 补充信息 | Additional Information

![image](https://github.com/lobehub/lobe-chat/assets/30854760/74f420a7-9a89-4d84-bf2c-b03a91e2fde8)

**Comment by suwubee** [comment]
我看了下请求，是走lobe中转的请求， 不知道为啥这样设计。其他程序比如next web都是客户本地直接请求api的。这个应该是慢的主要原因

**Comment by arvinxx** [comment]
> 我看了下请求，是走lobe中转的请求， 不知道为啥这样设计。其他程序比如next web都是客户本地直接请求api的。这个应该是慢的主要原因

https://github.com/lobehub/lobe-chat/discussions/728

**Comment by taurusduan** [comment]
> > 我看了下请求，是走lobe中转的请求， 不知道为啥这样设计。其他程序比如next web都是客户本地直接请求api的。这个应该是慢的主要原因
> 
> #728

意思是说不管我用没用中转，都会走一遍他们的中转。而且如果我是国内中转，说不定比不用中转还慢。。。

**Comment by suwubee** [comment]
> > > 我看了下请求，是走lobe中转的请求， 不知道为啥这样设计。其他程序比如next web都是客户本地直接请求api的。这个应该是慢的主要原因
> > 
> > 
> > #728
> 
> 意思是说不管我用没用中转，都会走一遍他们的中转。而且如果我是国内中转，说不定比不用中转还慢。。。

如果你自己搭建的程序，走的是自己的中转。这个我也是才知道，其实对大多数用户来说没必要。反而增加了数据风险。等啥时候改回本地请求了我再用了。。。

**Comment by arvinxx** [comment]
> 如果你自己搭建的程序，走的是自己的服务器。这个我也是才知道，其实对大多数用户来说没必要。反而增加了数据风险。

对于大部分用户来说，使用 LobeChat 都是在部署的时候配置的 api-key。这个时候请求走服务端是合理的，因为 api-key 就在服务端。如果要求把 api-key 从服务端发送到客户端，然后再从客户端发送请求，这反而是不合理的行为。

只有纯前端使用（即 api key 是用户在前端填写的），这种时候才适合只在前端发送请求，这样也能兼容纯本地 LLM 使用的场景。计划会在 #737 中支持。

**Comment by arvinxx** [comment]
close 错了

**Comment by arvinxx** [comment]
从原始描述来看，可能是流式返回的问题，试试：https://github.com/lobehub/lobe-chat/discussions/531
