### ISSUE TITLE
The image cannot be loaded and displayed.

### ISSUE THREAD

**Issue by ThirvenGree** [lobehub/lobe-chat#775]
![screenshot20231223](https://github.com/lobehub/lobe-chat/assets/128895710/74d6b7ce-de37-4513-8b2a-89edd8b7e582)

**Comment by arvinxx** [comment]
are you import these messages?

**Comment by ThirvenGree** [comment]
image was successfully processed, but cannot be displayed in the conversation

**Comment by arvinxx** [comment]
It's a bug and I will fix it.
