### ISSUE TITLE
[Question] 能通过环境变量指定默认助手的模型吗？

### ISSUE THREAD

**Issue by crabkun** [lobehub/lobe-chat#782]
### 🧐 问题描述 | Proposed Solution

你好，请问能通过环境变量指定默认助手的模型吗？
目前默认是gpt-3.5-turbo，即使通过CUSTOM_MODELS环境变量从模型列表中删掉gpt-3.5-turbo，默认助手还是gpt-3.5-turbo模型。
能否新增环境变量指定默认模型，或者直接读取模型列表中的第一个模型呢？
主要是想分享给朋友，他打开就能直接使用gpt-4-1106-preview，不用去指导他如何切换模型以及介绍每个模型的区别。

非常感谢！！

**Comment by zhuozhiyongde** [comment]
@arvinxx 我尝试了一下，似乎不是仅仅 gpt-3.5-turbo 模型有此问题，而是整个 CUSTOM_MODELS 对于移除模型（-）的解析是错的：

命令已经设置移除 gpt-4 模型：

![Cleanshot-2023-12-24-at-10 39 54@2x](https://github.com/lobehub/lobe-chat/assets/36695271/1b397097-de38-4f92-b463-d3a0b78f082e)

但是还是会显示（且能使用）：

![Cleanshot-2023-12-24-at-10 40 49@2x](https://github.com/lobehub/lobe-chat/assets/36695271/f0af7a7c-2ce3-4311-baea-0e0977f923bd)

不过，模型重命名是对的。

**Comment by arvinxx** [comment]
@zhuozhiyongde 这个需求和默认助手模型没关系哈。看了下是 `-` 指令的删除逻辑有点问题 cc @mushan0x0 。

**Comment by mushan0x0** [comment]
> @zhuozhiyongde 这个需求和默认助手模型没关系哈。看了下是 `-` 指令的删除逻辑有点问题 cc @mushan0x0 。

好的，我空了看看，最近在旅游

**Comment by zhuozhiyongde** [comment]
> @zhuozhiyongde 这个需求和默认助手模型没关系哈。看了下是 `-` 指令的删除逻辑有点问题 cc @mushan0x0 。

hhh 猜到了，大佬们辛苦啦！

**Comment by arvinxx** [comment]
> > @zhuozhiyongde 这个需求和默认助手模型没关系哈。看了下是 `-` 指令的删除逻辑有点问题 cc @mushan0x0 。
> 
> 好的，我空了看看，最近在旅游

我顺手修了

**Comment by arvinxx** [comment]
@crabkun 研究了下修改默认助手的配置可能还不一定好改。我要回头想想怎么做才好做…

**Comment by arvinxx** [comment]
在 https://github.com/lobehub/lobe-chat/discussions/913 跟进
