### ISSUE TITLE
[Bug] Dalle3等内置工具function name问题

### ISSUE THREAD

**Issue by hackiey** [lobehub/lobe-chat#783]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

dalle3的systemRole里，工具名称是Dall.E 3，prompt里是dalle，但function name是dalle3____text2image____builtin。

因为这段system prompt是OpenAI训练Dalle3作为内置工具的prompt，所以会有偶发的function call中name为"dalle“的情况，导致后续失败。建议内置工具（尤其是OpenAI的内置工具）可以直接用原名，其他类型的tool可以拼上前后缀做独特identifier

**Comment by arvinxx** [comment]
用原名应该不行，这样现有的实现机制会有问题。

再观察观察

**Comment by hackiey** [comment]
触发概率还是挺高的，或者不改function name，把system prompt改一改应该也可以
![WechatIMG84](https://github.com/lobehub/lobe-chat/assets/11832062/5a7d20f0-dfdc-423b-993d-0bbafc894f6f)

**Comment by arvinxx** [comment]
我回头试试看 system prompt 修改吧
