### ISSUE TITLE
[Bug] Docker部署后只有在host网络模式下才能正常使用插件

### ISSUE THREAD

**Issue by cao888** [lobehub/lobe-chat#786]
### 💻 系统环境 | Operating System

Other Linux

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Docker部署后只有在host网络模式下才能正常使用插件
nat模式只要使用插件，所有对话都会无响应

**Comment by arvinxx** [comment]
这个怎么会和部署模式有关呢…
