### ISSUE TITLE
[Request] 自定义模型使用Gemini-pro-vision时增加图片上传选项      

### ISSUE THREAD

**Issue by Feiyuyu0503** [lobehub/lobe-chat#790]
### 🥰 需求描述 | Feature Description

我已经拥有将Gemini-pro-vision的调用转换成openai api格式调用的api，但是在对话中选择Gemini-pro-vision时，没有图片上传选项。

### 🧐 解决方案 | Proposed Solution

是否可能根据模型名是否带有'vision'来开启图片上传选项？

**Comment by arvinxx** [comment]
倒也可以，我改下

**Comment by Feiyuyu0503** [comment]
> 倒也可以，我改下

多谢开发者！
借楼再问一下，是否有可能将这里的'dall-e-3'变成可配置模型名呢？
https://github.com/lobehub/lobe-chat/blob/dc7642d8dea5d2ac04a79aa394c540e560b5d642/src/services/imageGeneration.ts#L11
因为我使用的api已经将其他绘画模型的调用适配成openai image generation的格式，https://<openai_proxy_url>/v1/image/generations，但是只支持包括sd等的其他绘画模型，不支持dall-e-3

**Comment by arvinxx** [comment]
@Feiyuyu0503 目前没有关于图像生成的配置，建议单独开个 issue 跟踪。这样后续在做  #737  这个的时候可以 ref 一下这个需求。

**Comment by kokojacket** [comment]
@Feiyuyu0503 转换项目能分享一下吗？

**Comment by Feiyuyu0503** [comment]
@kokojacket https://github.com/songquanpeng/one-api
