### ISSUE TITLE
[Question] dalle3 azure 配置方式?

### ISSUE THREAD

**Issue by shancwovo** [lobehub/lobe-chat#797]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://oss.issuehunt.io/r/lobehub/lobe-chat/issues/797)

### 🧐 问题描述 | Proposed Solution

dalle3 plugin是否支持 azure 调用？目前未找到配置地方。

> 附dalle3 azure 调用示例：
```python
# Note: DALL-E 3 requires version 1.0.0 of the openai-python library or later
import os
from openai import AzureOpenAI
import json

client = AzureOpenAI(
    api_version="2023-12-01-preview",
    azure_endpoint="https://{service-name}.openai.azure.com",
    api_key=os.environ["AZURE_OPENAI_API_KEY"],
)

result = client.images.generate(
    model="dall-e-3", # the name of your DALL-E 3 deployment
    prompt="<the user's prompt>",
    n=1
)

image_url = json.loads(result.model_dump_json())['data'][0]['url']
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars.githubusercontent.com/u/39287499?v=4' alt='sen-capoo' width=24 height=24> sen-capoo](https://oss.issuehunt.io/u/sen-capoo) ($2.00)

### Tips

- Checkout the [Issuehunt explorer](https://oss.issuehunt.io/r/lobehub/lobe-chat/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://oss.issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by arvinxx** [comment]
看调用方式应该是支持的。你参考 https://github.com/lobehub/lobe-chat/discussions/178 部署一个 dalle3 的模型服务应该就好了
