### ISSUE TITLE
请求支持Google gemini pro

### ISSUE THREAD

**Issue by ccdanpian** [lobehub/lobe-chat#798]
### 🥰 需求描述 | Feature Description

希望能增加Google gemini pro和 骗人vision的支持

### 🧐 解决方案 | Proposed Solution

/

**Comment by edisonzf2020** [comment]
可以通过one-api项目部署包括Gemini-Pro在内的第三方AI模型API，然后本项目可以完美调用。
https://github.com/songquanpeng/one-api

**Comment by 12123ads** [comment]
> 可以通过one-api项目部署包括Gemini-Pro在内的第三方AI模型API，然后本项目可以完美调用。 https://github.com/songquanpeng/one-api

vision没法用

**Comment by 12123ads** [comment]
> 可以通过one-api项目部署包括Gemini-Pro在内的第三方AI模型API，然后本项目可以完美调用。 https://github.com/songquanpeng/one-api

vision没法用
