### ISSUE TITLE
[Question] 使用Vercel部署，但是无法更新

### ISSUE THREAD

**Issue by hileel** [lobehub/lobe-chat#799]
### 🧐 问题描述 | Proposed Solution

<img width="420" alt="image" src="https://github.com/lobehub/lobe-chat/assets/6147589/9d026445-f45d-4999-ba85-dc8b26c4da1e">
已经按照自动更新的教程操作，但是一直都不能自动更新

**Comment by arvinxx** [comment]
试试去点一下 sync upstream

**Comment by hileel** [comment]
<img width="1320" alt="image" src="https://github.com/lobehub/lobe-chat/assets/6147589/a745362e-9356-4f02-bcd9-d380c830aeac">
显示都是成功的

**Comment by zwdzwdzwd** [comment]
顺便问一下，如何设置访问密码呢，一键部署 vercel 的时候只有一个 APIkey 参数可以填的字段，不知如何添加设置访问密码的字段呢？谢谢！

**Comment by arvinxx** [comment]
@hileel 现在还有吗？
