### ISSUE TITLE
[Bug] 默认助手-设置页面，左侧菜单项中激活的栏目不正确

### ISSUE THREAD

**Issue by core-admin** [lobehub/lobe-chat#800]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

进去默认助手，点击助手的头像或者点击右上角的会话设置，进去设置页面，激活的菜单选项与实际的功能区不匹配，见下图：
![image](https://github.com/lobehub/lobe-chat/assets/77573477/06833097-cb53-4b9d-978c-6ac9e6f4343e)

### 🚦 期望结果 | Expected Behavior

进去设置后，激活的菜单选项应该与页面的显示内容对应起来

### 📷 复现步骤 | Recurrence Steps

官网既可复现：https://chat-preview.lobehub.com/chat#session=inbox

**Comment by canisminor1990** [comment]
fixed in https://github.com/lobehub/lobe-chat/commit/447c006e01f8c1b96b79f92e1514c5b44ebb00af
