### ISSUE TITLE
[Bug] No output

### ISSUE THREAD

**Issue by ThirvenGree** [lobehub/lobe-chat#803]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/128895710/21b9be4a-3688-4cca-9be6-cd60c1b10eda)
No output

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/discussions/623
