### ISSUE TITLE
[Request] Mastodon option in share tab

### ISSUE THREAD

**Issue by Jai707** [lobehub/lobe-chat#804]
As its a open-source project shouldn't you guys promote open-source social media such as mastodon/lemmy in sharing options

**Comment by canisminor1990** [comment]
what's your mean? share feature only support image and shareGPT now

**Comment by Jai707** [comment]
I am talking about social media options under the share repo in Readme.

**Comment by canisminor1990** [comment]
okay, i got it,  but i dont know the share query string about mastodon/lemmy, pr welcome

**Comment by canisminor1990** [comment]
🥰
