### ISSUE TITLE
[Request] 建议可以优化下请求数量和体积

### ISSUE THREAD

**Issue by kaikai1221** [lobehub/lobe-chat#806]
### 🥰 需求描述 | Feature Description

![image](https://github.com/lobehub/lobe-chat/assets/63178455/257c38f6-d5e2-4cbf-9828-2d08a613b9e7)
一个页面500多个请求有点吓人，页面会转好久

### 🧐 解决方案 | Proposed Solution

是不是可以清理下无用代码，合并请求或者不要用过多的第三方很重的库

**Comment by arvinxx** [comment]
你可以具体看下每个请求的内容，大部分应该是依赖 shikiji 的语言高亮服务的文件。

**Comment by kaikai1221** [comment]
> 你可以具体看下每个请求的内容，大部分应该是依赖shikiji的语言高亮服务的文件。

是的，我看大多是这个和多语言的一些东西还有的应该是ui组件资源的请求，第一词打开的时候会请求全部页面的全部语言配置即使我就只访问了一个页面，导致在第一次打开的时候不停的发送请求
