### ISSUE TITLE
BUILD_ID 不存在

### ISSUE THREAD

**Issue by 895268679long** [lobehub/lobe-chat#807]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

[Error: ENOENT: no such file or directory, open '/root/lobe-chat/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/lobe-chat/.next/BUILD_ID'
}

**Comment by 895268679long** [comment]
💻 系统环境 | Operating System
Windows

🌐 浏览器 | Browser
Chrome

这里忘了改。是centos8

**Comment by Chef5** [comment]
同样的问题，Ubuntu 22, node v18.19.0
<img width="1042" alt="image" src="https://github.com/lobehub/lobe-chat/assets/38160059/dd780370-21cd-4f38-a562-c8925d17a96f">
