### ISSUE TITLE
[Question] Why is the reply from the Open AI API always blank? My API key is not expired.

### ISSUE THREAD

**Issue by AlexJones0228** [lobehub/lobe-chat#808]
### 🧐 问题描述 | Proposed Solution

![Uploading PixPin_2023-12-25_23-02-48.png…]()

**Comment by arvinxx** [comment]
try to add `/v1`

**Comment by AlexJones0228** [comment]
![PixPin_2023-12-26_00-13-52](https://github.com/lobehub/lobe-chat/assets/130199821/c624d6c1-36c2-4974-b329-1b2354775cc7)
这又是怎么回事啊?

**Comment by AlexJones0228** [comment]
![Uploading 2.png…]()

**Comment by arvinxx** [comment]
你的地址填的就有问题… api的地址是  api.openai.com/v1

**Comment by AlexJones0228** [comment]
謝謝,已解決,愛你麽麽噠
