### ISSUE TITLE
[Request] openrouter.ai 支持

### ISSUE THREAD

**Issue by YYaa18** [lobehub/lobe-chat#810]
### 🥰 需求描述 | Feature Description

由于各种原因，选择使用了openrouter.ai这个代理，api层可以通过openai这个包接入各种模型，包括 claude, Gemini ，是否可以在未来兼容？

### 🧐 解决方案 | Proposed Solution

openrouter.ai

### 📝 补充信息 | Additional Information

openrouter.ai

**Comment by arvinxx** [comment]
你现在替换 proxy url 应该就可以用

**Comment by YYaa18** [comment]
并不是这个意思，openrouter.ai 是使用openai的api 实现对接各种模型，替换url是可以用的，但是目前应用只能使用openai的模型，不能再选择其他模型，希望做出一些兼容

**Comment by arvinxx** [comment]
@YYaa18 目前搭配 Custom_Model 环境变量是不是就行了？ 更完善的方案可以等 #737
