### ISSUE TITLE
修改模型名称后置顶未更改

### ISSUE THREAD

**Issue by kokojacket** [lobehub/lobe-chat#811]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/74887370/591d50e7-eb4b-4e8c-9add-0c12e21f5f88)

**Comment by arvinxx** [comment]
相关问题 #782
