### ISSUE TITLE
[Question]  Incomplete function call payload makes plugins unusable

### ISSUE THREAD

**Issue by DannySu09** [lobehub/lobe-chat#812]
### 🧐 问题描述 | Proposed Solution

Below is one of the plugins installed on my self-hosted service. I found the function call payload of any of them is incomplete which makes plugins unusable.

![image](https://github.com/lobehub/lobe-chat/assets/3401641/230da5b2-fbe1-4ea5-be08-b8278de2f071)

**Comment by arvinxx** [comment]
参考 https://github.com/lobehub/lobe-chat/issues/923 ，看现场是一样的，估计是 oneapi 的问题，这个我先关了。
