### ISSUE TITLE
[Bug] Missing Authorization header when using a ChatGPT Plugin

### ISSUE THREAD

**Issue by ifsheldon** [lobehub/lobe-chat#815]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

I have a public domain, on which I hosted a GPT Plugin. When I tried to add it to LobeChat, I consistently got invalid plugin setting errors. Then I found that the request made by LobeChat plugin system did not include `Authorization` header, which my plugin requires.

### 🚦 期望结果 | Expected Behavior

Correctly read OpenAI GPT Plugin manifest file and add `Authorization` header in requests when a plugin that needs service_http auth is used.

### 📷 复现步骤 | Recurrence Steps

1. Please refer to my template [here](https://github.com/ifsheldon/GPTPluginFlaskTemplate) and host the simple weather plugin on a public domain and then add this plugin to LobeChat. 
2. Configure the plugin with API Key (Auth code)
3. Ask a simple question like "What is the weather in Shanghai", then GPT will try to call the function of the plugin
4. The backend log should have something like `Accessing function_name - Missing Authorization in headers` while the frontend of LobeChat keeps prompting to update plugin settings

**Comment by ifsheldon** [comment]
Found this [RFC](https://github.com/lobehub/lobe-chat/discussions/411) stating the authorization for OpenAPI still lacks some features.

**Comment by arvinxx** [comment]
@ifsheldon yeah, there are some works we need to do to make auth perfect.

**Comment by ifsheldon** [comment]
I think this is now fixed.
