### ISSUE TITLE
[Request] 能否支持多个API轮询？

### ISSUE THREAD

**Issue by Flyingpen** [lobehub/lobe-chat#816]
### 🥰 需求描述 | Feature Description

考虑到openai对API有一定限制，也考虑到部分人群，手上持有多个API key，能否支持多个API的轮询方式，便于绕开openai使用限制？

### 🧐 解决方案 | Proposed Solution

对API调用，增加轮询模式。

**Comment by CaoYunzhou** [comment]
建议用oneapi项目进行分发轮训，或者cloudflare的work做轮训，这样比较好

**Comment by Flyingpen** [comment]
> 建议用oneapi项目进行分发轮训，或者cloudflare的work做轮训，这样比较好

请问cloudflare的work做轮询，有方案吗？

**Comment by suwubee** [comment]
> > 建议用oneapi项目进行分发轮训，或者cloudflare的work做轮训，这样比较好
> 
> 请问cloudflare的work做轮询，有方案吗？

问gpt4写代码就行了，我年初就用的worker轮询。

**Comment by arvinxx** [comment]
是否支持多key就等于支持这个需求了？

**Comment by Flyingpen** [comment]
> 是否支持多key就等于支持这个需求了？

是的，支持多个KEY填入，在使用时，通过轮询KEY，做到绕过openai的单KEY限制。

**Comment by kokojacket** [comment]
还有同一个ip地址限制的问题吧？

**Comment by Flyingpen** [comment]
> 还有同一个ip地址限制的问题吧？

不是商用，只是大概2~5个API KEY做轮询而已。这样不会有IP限制。

**Comment by thedavidweng** [comment]
> oneapi

请问提到的 “oneapi” 是指的[muximus3/OneAPI](https://github.com/muximus3/OneAPI)吗？

**Comment by suwubee** [comment]
> > oneapi
> 
> 请问提到的 “oneapi” 是指的[muximus3/OneAPI](https://github.com/muximus3/OneAPI)吗？

https://github.com/songquanpeng/one-api

**Comment by thedavidweng** [comment]
> > > oneapi
> > 
> > 
> > 请问提到的 “oneapi” 是指的[muximus3/OneAPI](https://github.com/muximus3/OneAPI)吗？
> 
> https://github.com/songquanpeng/one-api

感谢，刚刚也找到了。
