### ISSUE TITLE
token消耗疑似较大

### ISSUE THREAD

**Issue by ccdanpian** [lobehub/lobe-chat#820]
### 🧐 问题描述 | Proposed Solution

如下第一张图，是使用https://openrouter.ai/api/v1的gpt3.5 turbo的对话记录。

第二张图，是在openrouter.ai里看到的这两条消息消耗的token记录。明显发送的token相对于实际信息特别大。

请帮忙看看是openeouter的问题，还是lobehat的问题。这两条消息都没有用助手，不过在4条消息前用过一个助手。

![Screenshot_2023-12-26-23-05-49-174_com android chrome-edit](https://github.com/lobehub/lobe-chat/assets/130242490/7f8c86ca-28e5-4dd0-bf44-584ada0705c5)

![Screenshot_2023-12-26-23-06-37-199_com android chrome-edit](https://github.com/lobehub/lobe-chat/assets/130242490/4bb7f2f5-7d64-4e82-9376-a77744d764eb)

**Comment by suwubee** [comment]
关闭 - 自动创建话题，这个是类似生成对话标题的功能。会有大量的输入，和较少的输出。

**Comment by ccdanpian** [comment]
@suwubee 第二句比第一句的还多，第二句也会这样吗？

**Comment by suwubee** [comment]
如果开了历史记录的话第二句会带上之前的。
建议请求和接收抓下包看下。
等作者完成了llm支持，就可以走本地请求来测试了。

**Comment by ccdanpian** [comment]
o, 明白是怎么一回事了，谢谢
