### ISSUE TITLE
[Question] 思维导图插件不可用

### ISSUE THREAD

**Issue by skywolf123** [lobehub/lobe-chat#824]
### 🧐 问题描述 | Proposed Solution

思维导图插件不可用，可以生成节点，但是每个节点都没有文本
查看调试信息，发给每个节点的文本内容都是/n

**Comment by mushan0x0** [comment]
@ Moonlit7 可能要优化一下插件的参数描述，另外可以加一个生成图片的下载按钮吗😂

**Comment by Moonlit7** [comment]
> @Moonlit7 可能要优化一下插件的参数描述，另外可以加一个生成图片的下载按钮吗😂
麻烦提供下测试文本

**Comment by arvinxx** [comment]
> > @Moonlit7 可能要优化一下插件的参数描述，另外可以加一个生成图片的下载按钮吗😂
> 
> 麻烦提供下测试文本

@Moonlit7 我参考chatGPT的插件，在manifest里补了一个 systemRole 字段，可以直接描述插件的作用，且会注入到全局的systemRole中。可以考虑补一下这个字段的信息。

**Comment by burugo** [comment]
@Moonlit7 请问思维导图可以导出吗
