### ISSUE TITLE
[Question] 角色编辑信息不改变

### ISSUE THREAD

**Issue by skywolf123** [lobehub/lobe-chat#825]
### 🧐 问题描述 | Proposed Solution

先选择一个助手，点击左上角的角色设定旁边的编辑按钮，不编辑，直接点取消
再选择另一个助手，点击左上角的角色设定旁边的编辑按钮，发现内容还是上一个助手的角色设定文本

**Comment by skywolf123** [comment]
我升级到了最新的版本v0.117.1，但是这个问题并没有解决，是需要我做什么额外操作吗？

**Comment by arvinxx** [comment]
咦， @skywolf123  能录个屏看下吗

**Comment by skywolf123** [comment]
我想我知道差别在哪里了，点击取消按钮会重新加载，但我习惯点击的是 X 来关闭弹窗，这时不会文本不会重载

https://github.com/lobehub/lobe-chat/assets/34243902/682435f2-37ab-4660-aaec-82bf8e6df859

**Comment by arvinxx** [comment]
Ok 我修下

**Comment by arvinxx** [comment]
@skywolf123 应该已经修复了，再试试
