### ISSUE TITLE
[Request] 是否可以支持Claude

### ISSUE THREAD

**Issue by banduoba** [lobehub/lobe-chat#83]
### 🥰 需求描述 | Feature Description

你好,是否可以支持Claude呢,另外很多浏览器插件可以无api直接使用token,是否可以支持呢

### 🧐 解决方案 | Proposed Solution

建议也增加一个浏览器插件方式,侧边栏读取网页总结网页

**Comment by arvinxx** [comment]
> ,是否可以支持Claude呢,

可以的，后续有计划。

> 外很多浏览器插件可以无api直接使用token,是否可以支持呢

这种一般是需要用户登录注册的么？还是直接填 api key 的？

浏览器插件 我们也有计划搞的，要在chat 插件体系搞完以后

**Comment by banduoba** [comment]
就是浏览器登录下Claude比如,然后会自动获取token,就可以使用了,这样方便没有api接口权限的使用

**Comment by banduoba** [comment]
<img width="447" alt="image" src="https://github.com/lobehub/lobe-chat/assets/4811366/7e4383ca-5f1d-4f72-94df-097ca563fb7d">
如图

**Comment by arvinxx** [comment]
这种方式比较 hack … 虽然可行，但是可维护性挺差的…

**Comment by banduoba** [comment]
主要api也不是人人都有,如果能支持更好哈

**Comment by arvinxx** [comment]
通过 one-api 支持
