### ISSUE TITLE
[Request] Knowledge files

### ISSUE THREAD

**Issue by RealityMoez** [lobehub/lobe-chat#836]
### 🥰 需求描述 | Feature Description

Did you really missed with all these features, the most core feature nowadays, The Knowledge files for assistant (or uploading document files at all).

### 🧐 解决方案 | Proposed Solution

Add upload functionality, and Implement RAG that applies to all uploaded files (for Knowledge or new chats) for efficient retrieval based on user's input.

**Comment by Clouder0** [comment]
I'm looking forward to this. Not sure but [embedchain](https://github.com/embedchain/embedchain) may be of some help.
