### ISSUE TITLE
[Bug] 使用gpt-4-vision-preview模型的时候经常只能回复1000个token

### ISSUE THREAD

**Issue by wanghhao1** [lobehub/lobe-chat#837]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![WeChat2fa854980c68c1cfca37d5023a86ef17](https://github.com/lobehub/lobe-chat/assets/123242842/743d624e-268b-49b7-bb88-79728e16e769)
如图所示，没有开启单次回复限制，但是回复1000个token的时候就会停下

**Comment by arvinxx** [comment]
居然回复 1000 token 还不够吗…

这个的原因是 gpt-4-vision-preview 默认的 max_token 很小，所以我写死了一个 1000 的最大值

https://github.com/lobehub/lobe-chat/blob/main/src/store/chat/slices/message/action.ts#L346C65-L346C96


<img width="1490" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/e833639b-76bf-49c1-b249-35a004c50d22">

你看下你的场景下大概还会输出多少？我改下这个值。

**Comment by wanghhao1** [comment]
明白了，原来是这样。大部分使用场景确实够了，可能看一些比较复杂的文献不太够用，我觉得2048应该就够了。
