### ISSUE TITLE
[Bug] Docker 启动后 环境变量设置的API KEY， PROXY地址等不生效，每次都要手动在网页填写

### ISSUE THREAD

**Issue by ouchuji** [lobehub/lobe-chat#838]
### 💻 系统环境 | Operating System

Ubuntu

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Docker 启动后 环境变量设置的API KEY， PROXY地址等不生效，每次都要手动在网页填写

### 🚦 期望结果 | Expected Behavior

打开页面无需每次手动填写

### 📷 复现步骤 | Recurrence Steps

 docker run --rm -it -p 3210:3210   -e OPENAI_API_KEY=sess-DlKixxxxxxxxxxxxxxxxxxk   -e OPENAI_PROXY_URL=https://api.openai-proxy.com/v1   -e ACCESS_CODE=lobe66    --name lobe-chat   lobehub/lobe-chat

### 📝 补充信息 | Additional Information

![image](https://github.com/lobehub/lobe-chat/assets/11475541/e3ff8404-2b7d-453b-bdc2-9534f56ebdda)
![image](https://github.com/lobehub/lobe-chat/assets/11475541/7cbb3189-b69a-4b61-91fd-8e47117330f9)

**Comment by ccdanpian** [comment]
你设置了一个密码:ACCESS_CODE=lobe66，网页让你输入密码认证，输入密码后再试试

**Comment by ouchuji** [comment]
> 你设置了一个密码:ACCESS_CODE=lobe66，网页让你输入密码认证，输入密码后再试试

确实，感谢，问题解决

**Comment by ouchuji** [comment]
问题解决，我提点建议，ACCESS_CODE， 一开始我以为这东西是邀请码，，，，我觉得可以换 ACCESS_PASSWORD可能会更明显一些
