### ISSUE TITLE
部分插件按钮是否可以隐藏？

### ISSUE THREAD

**Issue by Payne-Wang** [lobehub/lobe-chat#840]
### 🥰 需求描述 | Feature Description

大佬，我的api是直连的，原价调用DALLE3太贵了，我在分享给别人的时候总会被调用，是否可以在部署时设置隐藏DALLE3？

### 🧐 解决方案 | Proposed Solution

无

**Comment by arvinxx** [comment]
你跟分享的人说让他们别用不就好了？

**Comment by bestNiu** [comment]
我也在看这一块，想着根据accessCode:等级数字，来判断按钮、项目是否显示，但还在看代码

**Comment by arvinxx** [comment]
已支持： https://lobehub.com/zh/docs/self-hosting/advanced/feature-flags
