### ISSUE TITLE
[Bug] Vercel中配置的PLUGINS_SETTINGS变量不起作用

### ISSUE THREAD

**Issue by TonyBlur** [lobehub/lobe-chat#843]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/101348912/0b15d753-eac7-4330-ba40-b86618c07bb1)
如图所示已经正确按照文档中的格式配置环境变量，且确认SERPAPI_API_KEY无误，并进行了多次重新部署，但是使用search-engine时仍然提示未输入API Key

**Comment by TonyBlur** [comment]
我似乎在代码中找到了问题所在：server.ts的代码中的环境变量名是PLUGIN_SETTINGS而不是PLUGINS_SETTINGS，而在[文档](https://github.com/lobehub/lobe-chat/wiki/Environment-Variable#plugins_settings)中则被写成了PLUGINS_SETTINGS

**Comment by arvinxx** [comment]
哦 我修复下文档
