### ISSUE TITLE
[Feature] 支持复制助手

### ISSUE THREAD

**Issue by skywolf123** [lobehub/lobe-chat#846]
### 🧐 问题描述 | Proposed Solution

我需要尝试从一个现有的助手修改出另一个新的助手，如何能复制呢？没找到相关的按钮

**Comment by arvinxx** [comment]
感觉可以加一个

**Comment by nagaame** [comment]
其实现在有个歪办法，就是导出某个助手，然后打开导出的JSON文件修改id的值（id一定要修改，不然会跳过重复的id）和某些数据之后，然后再导入即可

**Comment by arvinxx** [comment]
> 其实现在有个歪办法，就是导出某个助手，然后打开导出的JSON文件修改id的值（id一定要修改，不然会跳过重复的id）和某些数据之后，然后再导入即可

比较麻烦，一般用户也不会这么用。我会加一个复制助手的功能的，感觉是有用的。

**Comment by nagaame** [comment]
> > 其实现在有个歪办法，就是导出某个助手，然后打开导出的JSON文件修改id的值（id一定要修改，不然会跳过重复的id）和某些数据之后，然后再导入即可
> 
> 比较麻烦，一般用户也不会这么用。我会加一个复制助手的功能的，感觉是有用的。

好耶ヾ(✿ﾟ▽ﾟ)ノ
