### ISSUE TITLE
gpt4-vision-preview版本+内置Dall E3 or授粉绘画都无法画图

### ISSUE THREAD

**Issue by liliwen365** [lobehub/lobe-chat#849]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

gpt4-vision-preview版本+内置Dall E3 or授粉绘画都无法画图，显示空白，没有给出图片，如下：
![image](https://github.com/lobehub/lobe-chat/assets/76478019/3cc358dd-ec3f-4d89-8f3d-6f4c4310650a)

**Comment by arvinxx** [comment]
因为 4v 不支持 tool calls

**Comment by mushan0x0** [comment]
@arvinxx 我看可以加一个 map 映射，里面有 functions 的和 upload 这些字段，切换到对应模型就隐藏不支持的功能

**Comment by arvinxx** [comment]
> @arvinxx 我看可以加一个 map 映射，里面有 functions 的和 upload 这些字段，切换到对应模型就隐藏不支持的功能

我现在的想法是把 vision model 作为一个额外能力提供出来。然后在处理消息的链路上，先分析一下消息中是否包含图片。如果包含，先走一轮vision model完成识别。然后再触发一次正常的ai消息。

这样一来就能实现类似现在chatgpt 识别图片然后再调用插件进行会话的效果了

**Comment by mushan0x0** [comment]
> > @arvinxx 我看可以加一个 map 映射，里面有 functions 的和 upload 这些字段，切换到对应模型就隐藏不支持的功能
> 
> 我现在的想法是把 vision model 作为一个额外能力提供出来。
> 
> 在处理消息的链路上，先分析一下消息中是否包含图片。如果包含，先走一轮vision model 完成识别，然后再触发一次正常的ai消息。
> 
> 这样一来就能实现类似现在chatgpt 识别图片然后再调用插件进行会话的效果了

那这样就相当于实现 GPT4 All Tools 了，而且应该 3.5 也支持👍
