### ISSUE TITLE
[Question] 设置api key等不起作用

### ISSUE THREAD

**Issue by s544838371** [lobehub/lobe-chat#86]
### 🧐 问题描述 | Proposed Solution

# 步骤
1. cd D:\git\lobe-chat
2. pnpm install
3. pnpm build
4. pnpm start
5. 全局设置-通用设置，输入api key、接口代理地址
6. 全局设置-默认助手，启用网页内容提取插件
7. 返回聊天界面，点击新建助手
8. 输入https://sspai.com/post/81986
9. 提示：很抱歉，服务器没有等到上游服务器的回应，请稍后再试

### 📝 补充信息 | Additional Information

win11 笔记本

> @lobehub/chat@0.54.2 start D:\git\lobe-chat
> next start
- ready started server on 0.0.0.0:3000, url: http://localhost:3000

edge chrome浏览器

**Comment by arvinxx** [comment]
插件服务从 lobe-chat 里剥离出来了。目前代码中的插件服务会走到插件服务网关（项目地址：https://github.com/lobehub/chat-plugins-server）去，目前项目的网关地址配置的应该是 https://lobe-chat-plugin-market.vercel.app，这个地址国内直接访问呢应该是被墙的。

你本地使用的话，可以在项目目录下添加一个 `.env` 文件，然后填入：
```
PLUGIN_RUNNER_BASE_URL=https://chat-plugins.lobehub.com
```
让本地走到 lobehub 的域名，这样国内就能正常访问到了

**Comment by s544838371** [comment]
> 插件服务从 lobe-chat 里剥离出来了。目前代码中的插件服务会走到插件服务网关（项目地址：[lobehub/chat-plugins-server](https://github.com/lobehub/chat-plugins-server) ）去，目前项目的网关地址配置了 `https://lobe-chat-plugin-market.vercel.app` ，这个地址国内直接访问是被墙的。
> 
> 你本地使用的话，可以在项目目录下添加一个 `.env` 文件，然后填入：
> 
> ```
> PLUGIN_RUNNER_BASE_URL=https://chat-plugins.lobehub.com
> ```
> 
> 让本地走到 lobehub 的域名，这样国内就能正常访问到了
# 步骤
1. 增加.env文件
2. .env文件内填写PLUGIN_RUNNER_BASE_URL=https://chat-plugins.lobehub.com
3. cd D:\git\lobe-chat
4. pnpm start
5. info Loaded env from D:\git\lobe-chat\.env
6. 新建助手
7. 输入[https://sspai.com/post/81986]
8. 很抱歉，服务器没有等到上游服务器的回应，请稍后再试
9. F12显示Failed to load resource: the server responded with a status of 504 (Gateway Timeout) :3000/api/openai:1
# 其他补充
API KEY 是能够使用的，接口代理地址是https://xxxx/v1也是可以正常使用的，在随便聊聊窗口输入你都会什么，都会提示很抱歉，服务器没有等到上游服务器的回应，请稍后再试，是接口代理地址没生效还是什么？

**Comment by arvinxx** [comment]
哦，那看来不是插件的问题，是正常访问 OpenAI 的问题。

应该是接口代理没生效。你试试看在 `.env` 里添加一个

```
OPENAI_PROXY_URL=https://xxx/v1
```

然后重新 `pnpm start` 试试

**Comment by s544838371** [comment]
> 哦，那看来不是插件的问题，是正常访问 OpenAI 的问题。
> 
> 应该是接口代理没生效。你试试看在 `.env` 里添加一个
> 
> ```
> OPENAI_PROXY_URL=https://xxx/v1
> ```
> 
> 然后重新 `pnpm start` 试试

设置了OPENAI_PROXY_URL后，无问题，但是PLUGIN_RUNNER_BASE_URL没生效，目前.env内容如下：
```
PLUGIN_RUNNER_BASE_URL=https://chat-plugins.lobehub.com
OPENAI_PROXY_URL=https://xxx/v1
```
启用插件后，输入文章网址，终端提示内容如下：
```
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from D:\git\lobe-chat\.env
Failed to proxy https://lobe-chat-plugin-market.vercel.app/api/v1/runner Error: connect ETIMEDOUT 168.143.171.189:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '168.143.171.189',
  port: 443
}
Error: connect ETIMEDOUT 168.143.171.189:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '168.143.171.189',
  port: 443
}
```

**Comment by arvinxx** [comment]
奇怪，我回头试试看。 如果现在 env 不生效的话，解决方案直接手动改 `next.config.mjs` 里 第8行

```
  process.env.PLUGIN_RUNNER_BASE_URL || 'https://lobe-chat-plugin-market.vercel.app';
```
把 `https://lobe-chat-plugin-market.vercel.app` 替换为 `https://chat-plugins.lobehub.com`

然后再 `pnpm start` 试试看。

**Comment by s544838371** [comment]
> 奇怪，我回头试试看。 如果现在 env 不生效的话，解决方案直接手动改 `next.config.mjs` 里 第8行
> 
> ```
>   process.env.PLUGIN_RUNNER_BASE_URL || 'https://lobe-chat-plugin-market.vercel.app';
> ```
> 
> 把 `https://lobe-chat-plugin-market.vercel.app` 替换为 `https://chat-plugins.lobehub.com`
> 
> 然后再 `pnpm start` 试试看。

pnpm build
pnpm start
已解决
