### ISSUE TITLE
[Bug] 新建一个聊天助手或者切换助手会导致所有的聊天记录消失

### ISSUE THREAD

**Issue by huicewang** [lobehub/lobe-chat#862]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

切换聊天助手，新建聊天助手导致所有的聊天记录消失掉

**Comment by arvinxx** [comment]
应该不会的吧。有录屏吗？
