### ISSUE TITLE
[Bug] dalle3 连续对话容易卡住

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#870]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

在生成画面后，进行对话修改，容易卡住，不触发插件

### 📷 复现步骤 | Recurrence Steps

<img width="784" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/41d603f6-45f9-4053-a25d-c599ed878910">

**Comment by arvinxx** [comment]
咦，这个返回的json消息是啥情况

**Comment by mushan0x0** [comment]
[LobeChat-可爱粉猪画像-session-v2.json](https://github.com/lobehub/lobe-chat/files/13792902/LobeChat-.-session-v2.json)

重新复现了下，上面是对话记录

**Comment by mushan0x0** [comment]
似乎是 identifier 的问题

<img width="628" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/697930c9-7ef6-409f-bccc-6f0b25d35f12">

**Comment by arvinxx** [comment]
感觉是的，相似问题 https://github.com/lobehub/lobe-chat/issues/783

**Comment by arvinxx** [comment]
感觉不能用dalle。我换个别的 identifier 去试试
