### ISSUE TITLE
[Bug] 使用爬虫插件时，插件检测失败，不继续执行

### ISSUE THREAD

**Issue by ccdanpian** [lobehub/lobe-chat#879]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

从插件检测返回值：
{"tool_calls":[ {"id": "call_bo82skFq25VLGsYiqo4CWCCD", "type": "function", "function": {"name": "website-crawler____getWebsiteContent", "arguments": "{\n  \"url\": \"http:\/\/export.arxiv.org\/api\/query?search_query=ti:chatgpt&sortBy=lastUpdatedDate&sortOrder=descending\"\n}"}}
![image](https://github.com/lobehub/lobe-chat/assets/130242490/be2c7cbf-426a-43dd-b1ad-f6e1c8a5ed17)

**Comment by ccdanpian** [comment]
另外，只要出现这个错误后，继续在当前会话发任何消息，都回复这个报错：
{
  "endpoint": "https://api.openai.com/v1",
  "error": {
    "message": "Missing parameter 'name': messages with role 'function' must have a 'name'.",
    "type": "invalid_request_error",
    "param": "messages.[1].name",
    "code": null
  }
}

**Comment by mushan0x0** [comment]
导出一份记录，把里面敏感信息删了，发出来看看呢
<img width="574" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/8c2e228e-91b2-48b6-b4f3-d1c23d829c9f">

**Comment by arvinxx** [comment]
应该是从 function_call 迁移到 tool_calls 的bug，我修一下

**Comment by ccdanpian** [comment]
[LobeChat-sessions-v2.json](https://github.com/lobehub/lobe-chat/files/13801319/LobeChat-sessions-v2.json)
我上传了助手和消息。

**Comment by ccdanpian** [comment]
已经不会出现之前的错误了。但是经常会出现超时或者无响应的问题。
1）超时的时候，我手动去copy链接直接访问，确实时间会稍微长一点（3s左右），但是还是可以正常获取到数据的。
2）无响应不知道是否插件本身连接的问题。

![image](https://github.com/lobehub/lobe-chat/assets/130242490/625703f0-7216-4c5e-b374-b2a3be894c36)

![image](https://github.com/lobehub/lobe-chat/assets/130242490/a5e71147-4882-407b-b9d4-ec6e04dc8950)

**Comment by arvinxx** [comment]
> 1）超时的时候，我手动去copy链接直接访问，确实时间会稍微长一点（3s左右），但是还是可以正常获取到数据的。
> 2）无响应不知道是否插件本身连接的问题。


我说明下原理。这个插件通过 Puppeteer 无头浏览器加载页面来获取内容，因此这段时间不可控，跟网页版本身的快慢也有关系。

然后 LobeChat 的插件 gateway 的请求超时时间为 10s ，如果超时就会报你下面截图那个错误。
