### ISSUE TITLE
[Bug] 手机端的返回检测有问题

### ISSUE THREAD

**Issue by Feliks151450** [lobehub/lobe-chat#880]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

手机用edge浏览器打开lobe-chat，并添加到桌面。启动后在聊天界面退出，再重新点进聊天界面，这时候返回手势不起作用，要连续的两次返回手势才能退出聊天界面，这是bug吗

**Comment by reece00** [comment]
不是，因为根本不支持网页前进后退，手势后退当然不好使。唯一有用的是主页地址会让移动端跳首页然后因为进对话改了多次地址所以跳主页多次，其他地方你多点点，那就不止两次了

**Comment by mushan0x0** [comment]
试试 lobe.ai0x0.com 呢

**Comment by Feliks151450** [comment]
> 试试 lobe.ai0x0.com 呢

看起来返回手势没问题，但是这网站没法用啊，自定义key之后不能用
