### ISSUE TITLE
[Question] 在Vercel上部署118.1之后报错，无法正常打开页面

### ISSUE THREAD

**Issue by TonyBlur** [lobehub/lobe-chat#882]
### 🧐 问题描述 | Proposed Solution

在Vercel上重新部署118.1之后报错，无法正常打开页面（如图）
![image](https://github.com/lobehub/lobe-chat/assets/101348912/d23f9ebe-d46a-49f1-b619-1389ff9a61e0)

此后在其他平台部署（Zeabur）也是相同的报错，回退到118.0的commit并重新部署仍然是相同的报错

### 📝 补充信息 | Additional Information

可以排除是vercel、环境变量配置的问题，代码也和之前能访问时一样没有修改

**Comment by 7tinghua** [comment]
我也遇到了同样的问题。。。我把118.1版本fork到本地，部署后同样的错误。 但是设置页面和market页面可以正常访问。但是无法进入聊天页面。
same bug to me。

> 👀 @TonyBlur
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible. Please make sure you have given us as much context as possible. 非常感谢您提交 issue。我们会尽快调查此事，并尽快回复您。 请确保您已经提供了尽可能多的背景信息。

**Comment by arvinxx** [comment]
先用vercel 平台的 rollback 回滚下上个部署版本吧。我排查下是什么原因。可能是依赖更新的缘故
