### ISSUE TITLE
选择多个模型，同时请求，返回结果

### ISSUE THREAD

**Issue by Sitoi** [lobehub/lobe-chat#887]
### 🥰 需求描述 | Feature Description

将选择模型改为多选，可以请求多个模型的结果

### 🧐 解决方案 | Proposed Solution

勾选多个模型，并发请求

**Comment by arvinxx** [comment]
在什么场景下需要？

**Comment by Sitoi** [comment]
1. 对于多个模型进行评测
2. 多个结果输出可以输出更多的信息

**Comment by Sitoi** [comment]
可以参考这个网站 https://openrouter.ai/

**Comment by arvinxx** [comment]
好想法，我们在 1.0 来做~

**Comment by arvinxx** [comment]
合并到 https://github.com/lobehub/lobe-chat/issues/2353
