### ISSUE TITLE
[Request] 能否增加设置自动同步功能

### ISSUE THREAD

**Issue by liuchao0807** [lobehub/lobe-chat#892]
### 🥰 需求描述 | Feature Description

自动同步模型和助手设置，在各个终端可以无缝切换

### 🧐 解决方案 | Proposed Solution

比如可以将导出/导入功能对接到webdav

**Comment by arvinxx** [comment]
track in #368

**Comment by arvinxx** [comment]
我们在 `v0.141.0` 上线了基于 YJS 与 WebRTC 的实验性数据同步功能，欢迎测试并反馈：
- 反馈issue: #1683
- 背后思考：https://github.com/lobehub/lobe-chat/discussions/1681

如果上述同步功能不满足你的诉求，可以 Reopen 该issue
