### ISSUE TITLE
[Bug] 过一段时间页面报错

### ISSUE THREAD

**Issue by bincooo** [lobehub/lobe-chat#894]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

RT，页面出现错误`Application error: a client-side exception has occurred (see the browser console for more information).`
直到回到首页，刷新无用

**Comment by bincooo** [comment]
huggingface上，https://huggingface.co/spaces/bincooo/lobe-chat，版本是直接clone最新编译的

**Comment by arvinxx** [comment]
看报错，应该是和 #761  同一个问题

**Comment by bincooo** [comment]
哦，更新后确实有效。谢谢
