### ISSUE TITLE
Azure多节点管理

### ISSUE THREAD

**Issue by lx1054331851** [lobehub/lobe-chat#897]
### 🥰 需求描述 | Feature Description

Azure不同的模型部署在不同的地区和节点，一个节点没法满足所有的模型需求，现在只能设置一个节点中的多个模型，另外节点中部署的模型，需要重新设置

### 🧐 解决方案 | Proposed Solution

模型设置里面可以多模型管理，通过对话的时候，通过模型名称选择

### 📝 补充信息 | Additional Information

无

**Comment by arvinxx** [comment]
考虑了下，这个需求不应该在 LobeChat 中做，多节点管理应该由专门的解决方案来实现（例如one-api）。LobeChat 中最多也只会计划支持一个节点。先关了
