### ISSUE TITLE
新版链接Azure OpenAI服务超时

### ISSUE THREAD

**Issue by lx1054331851** [lobehub/lobe-chat#898]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

今天更新到LobeChat v0.118.3，发现连接到Azure OpenAI服务超时,显示
{
  "endpoint": "https://xxxx.openai.azure.com/openai/deployments/gpt-35-turbo",
  "error": {
    "cause": {
      "name": "ConnectTimeoutError",
      "code": "UND_ERR_CONNECT_TIMEOUT",
      "message": "Connect Timeout Error"
    }
  }
}

**Comment by arvinxx** [comment]
检查下网络
