### ISSUE TITLE
[Request] 针对单个助手设置模型代理

### ISSUE THREAD

**Issue by twelife** [lobehub/lobe-chat#903]
### 🥰 需求描述 | Feature Description

我在设置 `>` 语言模型 `>` `OpenAI` 设置中 使用了百川的接口和 `key` ，在聊天中可以选择刚刚设置的百川模型，能够正常通讯，但是如果又选择了 `gpt-3` 或者 `gpt-4` 系列的模型，由于使用了代理，导致无法使用。

### 🧐 解决方案 | Proposed Solution

- 代理可以针对单个助手进行设置，不影响 `gpt` 的官方请求，也不会导致一旦设置了代理其它均不可用的情况；
- 或者 使用了代理，则只能选择用户设置的指定模型，`gpt` 系列的模型则不展示或不能选择；

**Comment by arvinxx** [comment]
在 #737 跟进
