### ISSUE TITLE
[Bug] Text-to-Speech Overlap and Unnecessary Regeneration in Chat History

### ISSUE THREAD

**Issue by babamsi** [lobehub/lobe-chat#905]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

When using the chatbot's text-to-speech feature, if I navigate away from the chat and then return, all previous text-to-speech responses play simultaneously, creating a jarring and confusing audio experience. Additionally, it seems that the text-to-speech responses are regenerated each time I revisit the chat history, which could lead to unnecessary resource usage.

### 🚦 期望结果 | Expected Behavior

Upon returning to a previous chat history, I expect that no text-to-speech audio will play automatically. I should have the ability to select and play the text-to-speech for individual chat responses at my discretion, rather than having the most recent or all previous responses play out loud without my input.

### 📷 复现步骤 | Recurrence Steps

Engage with the chatbot and use the text-to-speech feature to listen to responses.
Refresh the webpage or navigate to a different chat history.
Return to the original chat history.
Observe that all text-to-speech audio responses play at once or notice that they are required to regenerate again.

https://github.com/lobehub/lobe-chat/assets/26160647/4ffa37bd-c9fd-4ad3-ad5f-82e7e84d0cb2

### 📝 补充信息 | Additional Information

The issue occurs consistently across both Microsoft and OpenAI speech services. This problem persists regardless of the browser or device used, indicating that it is not specific to a particular setup. If needed, I can provide further details or assist in reproducing the issue to help pinpoint the cause and facilitate a resolution. This format should help the developer understand the problem, know what you expected to happen, and how to reproduce the issue. It also leaves room for additional information that might be necessary to resolve the bug.

**Comment by arvinxx** [comment]
I thinks it's fixed in the latest version. Please check again. If there is still problem, please reopen it.
