### ISSUE TITLE
[Bug] 连续对话 dall 插件还是会有卡住情况

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#907]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

refs: #870

版本 V0.118.4 还是有卡住的情况，identifier 又是重复了两次导致插件检测失败

### 📷 复现步骤 | Recurrence Steps

<img width="1341" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/baec6d20-3bbd-4d1d-aa1c-4195dc4f2182">

**Comment by mushan0x0** [comment]
但好像没那么容易被触发了

**Comment by arvinxx** [comment]
感觉 systemRole 还是需要再调一调。
