### ISSUE TITLE
[Request] 建议增加WebDAV 同步配置的功能

### ISSUE THREAD

**Issue by 370569218** [lobehub/lobe-chat#911]
### 🥰 需求描述 | Feature Description

建议增加WebDAV 同步配置的功能

### 🧐 解决方案 | Proposed Solution

建议增加WebDAV 同步配置的功能

**Comment by arvinxx** [comment]
track in #368

**Comment by arvinxx** [comment]
我们在 `v0.141.0` 上线了基于 YJS 与 WebRTC 的实验性数据同步功能，欢迎测试并反馈：
- 反馈issue: #1683
- 背后思考：https://github.com/lobehub/lobe-chat/discussions/1681

如果上述同步功能不满足你的诉求，可以 Reopen 该issue
