### ISSUE TITLE
增加环境变量设置“限制历史消息数”

### ISSUE THREAD

**Issue by liliwen365** [lobehub/lobe-chat#912]
### 🥰 需求描述 | Feature Description

分享给别人使用时，别人没有设置限制历史消息数量，用gpt4导致消耗大量的上下文tokens，20次对话消耗了55万token，其中54万时上下文；平均计算每发送一条消息大概耗费$0.8美元=￥6.2人民币；一句话要6块钱；强烈建议可以在配置时设置附带发送的消息数，减少上下文的附带数量，避免产生大量不必要的费用；没有配置好前都不敢给别人任意使用了；
![image](https://github.com/lobehub/lobe-chat/assets/76478019/46eaa1ca-d246-449a-91b6-6899f687c4b1)

### 🧐 解决方案 | Proposed Solution

部署配置时可以设置限制历史消息数，设置附带发送的消息，或设置好后，不允许被人修改；或者修改需要权限等；

### 📝 补充信息 | Additional Information

给别人还是自己使用时能够减少大量的无关费用产生；

**Comment by arvinxx** [comment]
本质需求是自定义初始化模型的属性。相关需求例如 #811 #782 ，统一考虑
