### ISSUE TITLE
[Request] 搜索插件能否接入免费的搜索功能

### ISSUE THREAD

**Issue by skywolf123** [lobehub/lobe-chat#914]
### 🥰 需求描述 | Feature Description

目前搜索插件仅能使用SerpAPI，这个免费额度不多，收费挺贵的，有没有可能接入免费的搜索接口呢？

### 🧐 解决方案 | Proposed Solution

可参考https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain
这个项目有个搜索引擎配置，可以支持多个免费的搜索接口

**Comment by arvinxx** [comment]
可以，我后面优化 搜索引擎插件的时候参考下

**Comment by CaoYunzhou** [comment]
DuckDuckGo是一个免费的搜索引擎

**Comment by skywolf123** [comment]
DuckDuckGo需要翻，还有些是不用翻的，国内可以直接用，所以最好是有个可配置项，能用哪个用哪个

**Comment by babamsi** [comment]
https://serper.dev/ "SERP API" this one can get you 2,500 requests per month with No credit card required

**Comment by DC925928496** [comment]
最好是有可配置项，能够自己选择

**Comment by oasis168** [comment]
很需要这个功能，希望能早点使用到

**Comment by burugo** [comment]
很需要这个功能，希望能早点使用到

**Comment by huzw1995** [comment]
或者还用tigerbot.com的搜索接口，0.1元能请求1000次

**Comment by baiyi-os** [comment]
还是希望可以加入一个DuckDuckGo插件，真的很方便

**Comment by arvinxx** [comment]
Cloud 版本已经上线进阶搜索引擎功能，支持多个搜索引擎批量搜索。
