### ISSUE TITLE
[Bug] 切换聊天窗口后聊天记录全部消失，在官网上操作

### ISSUE THREAD

**Issue by huicewang** [lobehub/lobe-chat#919]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/19237481/e347a96a-729e-42fb-80d7-e29f61c74200)

**Comment by mushan0x0** [comment]
旁边话题列表有吗
<img width="1645" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/0eb7ffa2-23c7-4e8d-bac7-e8001b28dce7">

**Comment by huicewang** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/19237481/131209dc-f890-4f23-a65e-a07d6176fae5)

话题列表有内容的

**Comment by mushan0x0** [comment]
点开话题就有聊天记录了

**Comment by huicewang** [comment]
谢谢，这样有点怪怪的，给用户的第一感觉是聊天信息消失了

**Comment by arvinxx** [comment]
> 谢谢，这样有点怪怪的，给用户的第一感觉是聊天信息消失了

By Design 习惯就好了。
