### ISSUE TITLE
[Bug] 生成内容过程中聊天框无法往上拉

### ISSUE THREAD

**Issue by wanghhao1** [lobehub/lobe-chat#920]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

如视频所示，生成内容时，聊天框无法往上滚，会自动回到最底部，生成结束后才能往上翻。

https://github.com/lobehub/lobe-chat/assets/123242842/ac51b139-be8e-4d8b-9ada-65655571883f

**Comment by arvinxx** [comment]
是个已知的实现 bug，会修复

**Comment by wanghhao1** [comment]
感谢
