### ISSUE TITLE
[Request] (功能权限)能否根据AccessCode的值来判断能加载的模型，比如使用gpt4，以及是否能使用dell3或其他高级功能

### ISSUE THREAD

**Issue by bestNiu** [lobehub/lobe-chat#925]
### 🥰 需求描述 | Feature Description

能否根据AccessCode的值来判断能加载的模型，比如使用gpt4，以及是否能使用dell3或其他高级功能

### 🧐 解决方案 | Proposed Solution

AccessCode后面跟着数字等级，每个等级可以分为1-5个等级，每个等级控制按钮的是否显示，以及某些下拉列表项目的是否显示

**Comment by arvinxx** [comment]
应该暂不计划支持这种能力

权限体系一般是给有账号体系的场景用的。 但LobeChat 是为有动手能力的个人服务的，没有计划上账号体系。

所以我们对团体使用的场景相应的支持度会很有限，相应的权限体系也不会考虑。

如果有需要的话建议自行实现。
