### ISSUE TITLE
[Question] pnpm run build error

### ISSUE THREAD

**Issue by lixiaoqin0218** [lobehub/lobe-chat#936]
### 🧐 问题描述 | Proposed Solution

CASE A: i pull the newest main branch ,and pnpm i, pnpm run build:docker , the result is good!
CASE B: i pull the main branch a month ago, and add some api , pnpm i ,pnpm dev ,the result is good ! but the biggest problem is pnpm run build:docker ,it's wrong, the error message is :
<img width="763" alt="image" src="https://github.com/lobehub/lobe-chat/assets/31536111/97604de5-c1fc-4c4f-9b7a-5be93b7e7efd">
<img width="753" alt="image" src="https://github.com/lobehub/lobe-chat/assets/31536111/3dfbedbf-f2e2-45ed-b81f-237db9a3f8bc">

i have delete  node_module  .next , and merge the newest main brach files (package.json,next.config.mjs,dockerfile,tsconfig), 
pnpm i 
pnpm run build:docker

but still error ,the same error!

i confuse why pnpm dev is ok? and pnpm run build is wrong?
i confuse why it's still the same wrong after merge the newst code of main branch?

please help!

**Comment by arvinxx** [comment]
the code is update, please upgrade the codebase to latest.

**Comment by lixiaoqin0218** [comment]
two problems:
i confuse why pnpm dev is ok? and pnpm run build is wrong?
i confuse why it's still the same wrong after merge the newst code of main branch?

**Comment by arvinxx** [comment]
> i confuse why pnpm dev is ok? and pnpm run build is wrong?

i don't know either.

> i confuse why it's still the same wrong after merge the newst code of main branch?

do you update all the new code?

**Comment by arvinxx** [comment]
@lixiaoqin0218 have you fixed your error？
