### ISSUE TITLE
[Bug] 本地源代码安装bun install时报错

### ISSUE THREAD

**Issue by Science2AI-TaoXu** [lobehub/lobe-chat#944]
### 💻 系统环境 | Operating System

Ubuntu

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

error loading current directory
  📦 Installing [2637/2230] 
error: failed to spawn life-cycle scripts for esbuild: CouldntReadCurrentDirectory
  📦 Installing [3248/2230] error: Failed to spawn script install due to error os.linux.errno.generic.E.PERM PERM
error: Failed to spawn script install due to error os.linux.errno.generic.E.PERM PERM
error: Failed to spawn script install due to error os.linux.errno.generic.E.PERM PERM
error: Failed to spawn script postinstall due to error os.linux.errno.generic.E.PERM PERM
error: Failed to spawn script install due to error os.linux.errno.generic.E.PERM PERM

### 🚦 期望结果 | Expected Behavior

能成功安装

**Comment by arvinxx** [comment]
重试下？

**Comment by Science2AI-TaoXu** [comment]
重试了还是一直有这个问题，Python 3.10.4 ubuntu 20.04

**Comment by arvinxx** [comment]
试试 pnpm 呢？

```
pnpm i
```

**Comment by BQQQQB** [comment]
> 试试pnpm呢？
> 
> ```
> pnpm i
> ```

这个用完之后呢？

**Comment by BQQQQB** [comment]
> > 机器人检测到问题正文的语言不是英语，会自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > 尝试一下 pnpm 怎么样？
> > ```
> > pnpm i
> > ```
> 
> 这个用完后会发生什么？

我又重新安装了bun install,没有报错

**Comment by arvinxx** [comment]
那就好了吧
