### ISSUE TITLE
[Bug] Vercel 部署时报错

### ISSUE THREAD

**Issue by Feliks151450** [lobehub/lobe-chat#949]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

最近的版本出现的，看起来是识别不到 SquareAsterisk
<img width="1166" alt="image" src="https://github.com/lobehub/lobe-chat/assets/44024139/3a8796ff-01d1-45b9-99a0-aca637bbb3f4">

**Comment by bestxiaoyuxy** [comment]
同样的error

**Comment by Sen-CaPoo** [comment]
import { KeySquare, **SquareAsterisk** } from 'lucide-react';

to

import { KeySquare, **AsteriskSquare** } from 'lucide-react';
