### ISSUE TITLE
[Request] PWA 在 Pad 上不支持宽屏，只能竖屏

### ISSUE THREAD

**Issue by icarusion** [lobehub/lobe-chat#951]
### 🥰 需求描述 | Feature Description

希望可以支持一下 PWA 模式在 Pad 上的宽屏模式

### 🧐 解决方案 | Proposed Solution

PWA 是不是有什么宽屏配置没开启

### 📝 补充信息 | Additional Information

使用的小米平板6Pro测试

**Comment by arvinxx** [comment]
我们回头研究下

**Comment by TonyBlur** [comment]
> 我们回头研究下

此问题仍然存在，会导致无法进入对话界面

**Comment by arvinxx** [comment]
似乎已经解决了，我的iPad测试下来没问题

**Comment by BaituLime** [comment]
此问题仍然存在。
