### ISSUE TITLE
[Bug] docker build 构建时终端报错

### ISSUE THREAD

**Issue by huicewang** [lobehub/lobe-chat#954]
### 💻 系统环境 | Operating System

Ubuntu

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Compiled with warnings

./src/features/Conversation/Error/InvalidAccess.tsx
Attempted import error: 'SquareAsterisk' is not exported from '__barrel_optimize__?names=KeySquare,SquareAsterisk!=!lucide-react' (imported as 'SquareAsterisk').

Import trace for requested module:
./src/features/Conversation/Error/InvalidAccess.tsx
./src/features/Conversation/Error/index.tsx
./src/features/Conversation/components/ChatItem/index.tsx
./src/features/Conversation/components/ChatList/index.tsx
./src/features/Conversation/index.tsx
./src/app/chat/(mobile)/mobile/index.tsx

./src/features/Conversation/Error/InvalidAccess.tsx
Attempted import error: 'SquareAsterisk' is not exported from '__barrel_optimize__?names=KeySquare,SquareAsterisk!=!lucide-react' (imported as 'SquareAsterisk').

Import trace for requested module:
./src/features/Conversation/Error/InvalidAccess.tsx
./src/features/Conversation/Error/index.tsx
./src/features/Conversation/components/ChatItem/index.tsx
./src/features/Conversation/components/ChatList/index.tsx
./src/features/Conversation/index.tsx
./src/app/chat/(mobile)/mobile/index.tsx

**Comment by huicewang** [comment]
Failed to compile.

./src/features/Conversation/Error/InvalidAccess.tsx:3:21
Type error: Module '"lucide-react"' has no exported member 'SquareAsterisk'.

  1 | import { Icon } from '@lobehub/ui';
  2 | import { Button, Input, Segmented } from 'antd';
> 3 | import { KeySquare, SquareAsterisk } from 'lucide-react';
    |                     ^
  4 | import { memo, useState } from 'react';
  5 | import { useTranslation } from 'react-i18next';
  6 | import { Flexbox } from 'react-layout-kit';
 ELIFECYCLE  Command failed with exit code 1.

**Comment by arvinxx** [comment]
升级到最新版本 ref: https://github.com/lobehub/lobe-chat/issues/949
