### ISSUE TITLE
[Bug] 开发环境，升级到最新版后报错

### ISSUE THREAD

**Issue by huicewang** [lobehub/lobe-chat#955]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/19237481/e7dac674-a47c-42ab-804f-1d6bce1c06af)

**Comment by arvinxx** [comment]
重装下依赖
