### ISSUE TITLE
这就是个API key收集器

### ISSUE THREAD

**Issue by hadkins1** [lobehub/lobe-chat#956]
前几天部署了这个东西，一直没用。昨天登陆platform.openai.com一看，发现账号余额里的钱都被人撸完了。这作者实在太缺德！

**Comment by mushan0x0** [comment]
你都自己部署了余额里的钱还能被作者撸走吗，代码都是开源的你可以看看是哪行代码撸走你余额的😂

**Comment by arvinxx** [comment]
请确认是否是你没有设置密码，被恶意攻击的人利用了。 本项目没有存在任何后门的

**Comment by Sen-CaPoo** [comment]
我使用該專案一陣子，並且也進行了大量的客製化調整，對專案代碼也看了數十小時以上，基本上不存在偷 KEY 的內容；請確保自己佈署的環境，以及環境設定檔是否有外洩的狀況，另外如果使用 OpenAI 也可以去他們的後台查看到底呼叫了哪些項目導致費用產生，說不定真的只是自己大量使用某些功能導致費用。

例如 GPT-4V 的模型，你如果一次 100,000 Token 給他問下去，那消耗速度會是非常可怕的。

不要惡意攻擊開源軟體，開發團隊也是無條件再貢獻分享給大家，就算真的存在 Bug，也應該是大家共同提出討論並修復，而不是直接的攻擊言語。

**Comment by ccdanpian** [comment]
不能上来就摸黑啊。
一定要设好密码，要不然很容易被爬虫爬去地址，不一定是key被盗了，倒是有可能被盗用。
最开始有一个项目没有设密码的功能，不少人都被盗用了。

**Comment by ccdanpian** [comment]
不能上来就抹黑啊。
一定要设好密码，要不然很容易被爬虫爬去地址，不一定是key被盗了，倒是有可能被盗用。
最开始有一个项目没有设密码的功能，不少人都被盗用了。

**Comment by leeyiding** [comment]
建议没有拿出任何确凿证据前，请不要随意抹黑开发者。

**Comment by ccdanpian** [comment]
@arvinxx 不过还是建议能再多加一级验证，或者用验证码的方式，部署的时候自己配置是否需要双重认证

**Comment by ccdanpian** [comment]
> 我使用該專案一陣子，並且也進行了大量的客製化調整，對專案代碼也看了數十小時以上，基本上不存在偷 KEY 的內容；請確保自己佈署的環境，以及環境設定檔是否有外洩的狀況，另外如果使用 OpenAI 也可以去他們的後台查看到底呼叫了哪些項目導致費用產生，說不定真的只是自己大量使用某些功能導致費用。
> 
> 例如 GPT-4V 的模型，你如果一次 100,000 Token 給他問下去，那消耗速度會是非常可怕的。
> 
> 不要惡意攻擊開源軟體，開發團隊也是無條件再貢獻分享給大家，就算真的存在 Bug，也應該是大家共同提出討論並修復，而不是直接的攻擊言語。

是的，上周实验一个助手，一天就花了20$。

**Comment by Feliks151450** [comment]
你要是没设密码那就是你自己的问题

**Comment by arvinxx** [comment]
> @arvinxx 不过还是建议能再多加一级验证，或者用验证码的方式，部署的时候自己配置是否需要双重认证

默认的 Vercel 部署按钮，把密码也作为必填项吧

**Comment by TonyBlur** [comment]
这是开源项目，你要是觉得是作者偷了你的Key可以去代码里找出证据来，而不是在这里张口就来

**Comment by jingkang99** [comment]
就是，瞎bb。这个是国人项目？

**Comment by rtpacks** [comment]
如果没有拿出任何证据，请您不要恶意攻击开源项目和开发者！
