### ISSUE TITLE
[Request] 自定义模型的窗口太小了

### ISSUE THREAD

**Issue by crybest** [lobehub/lobe-chat#957]
### 🥰 需求描述 | Feature Description

![image](https://github.com/lobehub/lobe-chat/assets/102134756/7f967899-918c-49e4-879c-59a25e6a06c3)

很多自定义模型，太长了，很难输入

### 🧐 解决方案 | Proposed Solution

增大窗口

**Comment by arvinxx** [comment]
可以，我改成 TextArea 吧
