### ISSUE TITLE
[Request] 增加自定义模型的别名

### ISSUE THREAD

**Issue by crybest** [lobehub/lobe-chat#958]
### 🥰 需求描述 | Feature Description

gizmo模型没有别名无法识别

### 🧐 解决方案 | Proposed Solution

增加别名设定

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/blob/main/docs/Deployment/Environment-Variable.zh-CN.md#custom_models 参考

**Comment by crybest** [comment]
> 参考 https://github.com/lobehub/lobe-chat/wiki/Environment-Variable.zh-CN#custom_models

收到
