### ISSUE TITLE
[Bug] iOS 用 gpt-4-vision 发送图片报错 413

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#981]
### 💻 系统环境

iOS

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

refs: #668

有人反馈还是有问题，网上搜了一下，似乎不只是图片分辨率或者大小造成的

https://community.openai.com/t/error-sending-image-to-openai-apierror-413-the-data-value-transmitted-exceeds-the-capacity-limit/469279

https://community.openai.com/t/bug-error-413-the-data-value-transmitted-exceeds-the-capacity-limit-when-calling-v1-images-edits/464513

**Comment by qq15725** [comment]
ios 用 Gemini Pro Vision 随便相机拍张图，也会提示超大小 

```json
{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro-vision:streamGenerateContent?alt=sse: [400 Bad Request] Request payload size exceeds the limit: 4194304 bytes."
  },
  "provider": "google"
}
```

**Comment by qq15725** [comment]
尝试找了下我这边的问题应该是老版本的 bug

https://github.com/lobehub/lobe-chat/blob/v0.129.5/src/services/file.ts#L37

v0.129.5 版本 ios 上图片压缩的代码 image/jpeg 转 image/webp 文件反而会变大

最新版本沿用 file.type 应该正常了

**Comment by arvinxx** [comment]
@mushan0x0 看下是不是最新版本已经修复了？我的手机测了下好像没问题

**Comment by mushan0x0** [comment]
没有出现过了
