### ISSUE TITLE
[Request] The Mindmap feature is fascinating, but could I download the result

### ISSUE THREAD

**Issue by ChrisXHLeung** [lobehub/lobe-chat#984]
### 🥰 Feature Description

The Mindmap feature is fascinating, but could I download the result?

### 🧐 Proposed Solution

Add a download feature into the Mindmap

**Comment by arvinxx** [comment]
@Moonlit7 Please consider add download button~ 😄

**Comment by elwizard33** [comment]
So no download for mindmaps?
