### ISSUE TITLE
[Bug] 窗口模式时翻译语言显示不全

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/lobe-chat#998]
### 💻 系统环境

macOS

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

refs: https://github.com/ant-design/ant-design/issues/46903

可能需要 antd 优化

### 📷 复现步骤

<img width="666" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/175e399b-7f36-4e3c-ba5f-25469ff46e42">

**Comment by arvinxx** [comment]
应该加个高度估计可以，我试下

**Comment by mushan0x0** [comment]
加个高度和滚动可以，就是滚动条占位有点丑

<img width="751" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/2a29c2e9-82a9-4970-9e5d-c032d114f239">
